### ISSUE TITLE
Add default Rails anti-CSRF token parameter

### ISSUE THREAD

**Issue by fourcube** [zaproxy/zaproxy#1662]
Rails uses 'authenticity_token' as the name of it's hidden anti-CSRF form parameter. Since Rails is quite common, it might make sense to include this parameter in the defaults.

I would be happy to submit a pull request if you think this is reasonable.

**Comment by psiinon** [comment]
Very reasonable - please submit a PR :)

**Comment by fourcube** [comment]
submitted #1663

**Comment by fourcube** [comment]
This was solved by 5a670b0d561662b6508e6cbaa7e20399ee44548e.
