### ISSUE TITLE
Add multiple URLs to the quick scan option

### ISSUE THREAD

**Issue by ghost** [zaproxy/zaproxy#1665]
Due to the requirement of multiple automated application scans, is it possible to pass in a file of multiple URLs into the quick scan option. In turn, ZAP spiders and active scans them, as well as reporting the findings separately.

**Comment by psiinon** [comment]
I like it :)
The only slightly tricky thing might be reporting the results separately, but I can see why thats important.
So how about something like:
./zap.sh -quickbulk <file> -quickout <directory>
and maybe with another option:
-quickformat <xml/html>
?

**Comment by jshaw87** [comment]
Sounds good! :)

**Comment by Manjeet17Singh** [comment]
Is there any way to pass multiple urls through ZAP docker cli?

**Comment by psiinon** [comment]
@Manjeet17Singh please use the ZAP User Group for questions: https://groups.google.com/group/zaproxy-users

**Comment by psiinon** [comment]
This is now possible using the Automation Framework.
I think thats a better solution than adding more and more command line options :)
