### ISSUE TITLE
zaproxy need an apikey for ZapClient to work with API 2.4

### ISSUE THREAD

**Issue by AlbanAndrieu** [zaproxy/zaproxy#1668]
When using https://www.npmjs.com/package/grunt-zaproxy
which depends on:
https://www.npmjs.com/package/zaproxy

zap_stop is not working.
Following issue has been created on grunt-zaproxy
https://github.com/TeamPraxis/grunt-zaproxy/issues/2#issuecomment-112198640

It seems that zaproxy is working only with API version 2.3
But ZAP 2.3.0 is already using api 2.4,

I need to give a apikey to ZapClient: https://github.com/AlbanAndrieu/grunt-zaproxy/blob/master/tasks/zaproxy.js

var options = { proxy: 'http://' + options.host + ':' + options.port, apikey: options.apiKey };
var zaproxy = new ZapClient(options);
See https://github.com/TeamPraxis/grunt-zaproxy/pull/4 as a sample, about what I need

Is it possible?

**Comment by psiinon** [comment]
The API key is optional, its only required if one is set in ZAP.
However the npm package does need to be updated - I'll ping the maintainer...

**Comment by AlbanAndrieu** [comment]
Indeed, message disappear if I remove apikey from zaproxy.
And now it is working.

But when zaproxy is installed a API_KEY is generated.
It would be nice to be able to add this key.

Thanks a lot for this quick answer.

**Comment by psiinon** [comment]
I think its actually the TeamPraxis guys who maintain the ZAP node.js client lib :) I've emailed them about this - it would be v good to get that updated for 2.4.0

**Comment by khamasaki** [comment]
This is actually an enhancement needed in grunt-zaproxy (see the above linked PR). Since the issue is being dealt with there, closing this one.

**Comment by AlbanAndrieu** [comment]
Indeed, It can be closed: 
See https://github.com/TeamPraxis/grunt-zaproxy/pull/4 for more details. 
apikey can be sent to API doing

```
zaproxy.core.shutdown(options.apiKey, function (err) ...
```

Feel free to update API documentation: https://github.com/zaproxy/zaproxy/wiki/ApiGen_core
So next time I will not bother you in order to find out where to add this apikey.

Anyway, thanks a lot for the community... It was a real pleasure to work with you.
And I am realy surprised having such a quick answer to my issue.
