### ISSUE TITLE
Ajax spider not considering get parameters

### ISSUE THREAD

**Issue by tunnelshade** [zaproxy/zaproxy#1674]
I performed login from browser proxied through ZAP. There is a session parameter in the url. But when I start ajax spider from a particular node, the url get parameters are not involved.

**Comment by psiinon** [comment]
The advice is _not_ to include session parameters in urls, but I can see why this would option would be useful for the Ajax Spider.

**Comment by tunnelshade** [comment]
Since ZAP is allowing users to select a node to start the ajax crawl, it will be useful to consider the get parameters as well, in that node. Any thoughts?

**Comment by psiinon** [comment]
Yeah - thats what I meant - I think an option to include the parameters would be a good thing to have

**Comment by tunnelshade** [comment]
Cool. Looking forward to a nightly.

**Comment by psiinon** [comment]
As the Ajax Spider is an add-on we can publish an update for it at any time.
However someone needs to implement the change, and I probably wont have time for a while as I'm crazily busy :(

**Comment by thc202** [comment]
Close with zaproxy/zap-extensions@cf958409e239b46bf78e2646c8b31c781dcb2e71
The issue was not properly linked in the commit message :(

**Comment by thc202** [comment]
Oh, let me know if you disagree with the fix and I'll do the required changes.

**Comment by thc202** [comment]
Fixed in  "Ajax Spider" add-on version 13 (included by default in ZAP 2.4.1 and 2.4.2).
