### ISSUE TITLE
Move downloads to anything but sourceforge?

### ISSUE THREAD

**Issue by pdehaan** [zaproxy/zaproxy#1676]
Re: https://github.com/zaproxy/zaproxy/wiki/Downloads

It looks like a lot of the downloads are pointing to sourceforge, but a lot of services are trying to block sourceforge lately because they are borderline shady:

```
uBlock Origin has prevented the following page from loading:
https://sourceforge.net/projects/zaproxy/files/
Because of the following filter
||sourceforge.net^$other
Found in: uBlock filters • uBlock filters – Badware risks
```

![chrome-extension___cjpalhdlnbpafiamejdnhcphjbkeiagm_document-blocked_html_details_eyj1cmwioijodhrwczovl3nvdxjjzwzvcmdllm5ldc9wcm9qzwn0cy96yxbyb3h5l2zpbgvzlyisimhuijoic291cmnlzm9yz2uubmv0iiwizg4ioijzb3vyy2vmb3jnzs5uzxqilcjmyyi6ijgwxhuwmdbill](https://cloud.githubusercontent.com/assets/557895/8334949/7db3aff6-1a4f-11e5-97af-191664ba0d47.png)

**Comment by thc202** [comment]
Yes, this a WIP.

**Comment by psiinon** [comment]
All of the main release files have been moved to github :)
We're keeping the copies on sourceforge as many people have linked directly to them, but future releases (including the weekly releases) will only be on github.
