### ISSUE TITLE
Fuzzers can't be expanded on OS X

### ISSUE THREAD

**Issue by marumari** [zaproxy/zaproxy#1677]
You can't select subcategories when fuzzing, on OS X, which makes it impossible to limit your fuzzing to simply XSS or SQL injection, etc.

![screen shot 2015-06-24 at 12 49 47 pm](https://cloud.githubusercontent.com/assets/230528/8339874/8d7f6572-1a6f-11e5-8c45-5cb3a8021cea.png)

**Comment by psiinon** [comment]
One line fix ;)
We'll include this in the forthcoming bugfix release

**Comment by marumari** [comment]
BTW, there are a number of places in ZAP where the pull handles are used; you may want to do a global search for them and add that line to all those places.  :)

**Comment by psiinon** [comment]
Thanks for the reminder - spotted one other instance we need to fix...
