### ISSUE TITLE
Feature request: multiple tabs for Manual Request Editor

### ISSUE THREAD

**Issue by amuntner** [zaproxy/zaproxy#1678]
Currently there is only one Manual Request editor. 
Burpsuite uses tabs to allow multiple manual request editor sessions at once, it's very useful.

Usage: 
When sending a request to the Manual Editor, a new tab would be created
Tabs can be close with an X on each tab
There should be a button to open a new, blank Manual Request tab

Nice to have:
Name tabs
Reorder tabs

**Comment by kingthorin** [comment]
The Requester addon seems to address thus.

https://github.com/zaproxy/zap-extensions/pull/50
