### ISSUE TITLE
Resent / Manual Request Editor merge

### ISSUE THREAD

**Issue by amuntner** [zaproxy/zaproxy#1679]
Depending on where it's opened from, there is a different window title for what is the same window.

If the tabbed manual request editor changes are made[1], they should become the same window. 
1. https://github.com/zaproxy/zaproxy/issues/1678

**Comment by thc202** [comment]
The dialogues are now (2.7.0, #3820) using the same name. Can be closed?

**Comment by psiinon** [comment]
Yeah, I think so too :)
