### ISSUE TITLE
Zap Error

### ISSUE THREAD

**Issue by projectspcloud** [zaproxy/zaproxy#1680]
I received this error while using the Zap Proxy to scan a https enabled website:
ZAP Error [javax.net.ssl.SSLHandshakeException]: Received fatal alert: handshake_failure

The current architecture of the site I am trying to scan is as follows:
Internet >> Firewall >> Server

My client has made it so that for anyone to access the websites on the Server, all internet traffic will have to pass through my client's Firewall before arriving at the Server itself. The Firewall and the Server are not in the same vicinity.

The Firewall belongs to my client and I do not have control over it. Any direct scans to the Server will be successful but as long as I attempt to scan through the Firewall to the Server, the scans will result either in the stated error above when using the proxy or it will display the error message "Failed to attack the URL, please check that the URL you specify is valid" when using the Quickstart scan.

Wish to add that I have already followed the instructions on the link below to generate the ZAP Root CA Certificate and have also imported it to my browser.
https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsOptionsDynsslcert

I am pretty much at my wits end so any help will be greatly appreciated. Thank you.

**Comment by kingthorin** [comment]
Are you able to manually browse the website just simply proxying through ZAP? 

If you browse the site without ZAP what version of SSL or TLS is the connection made with?

What version of Java are you running?

This might also lead you to a solution:
https://github.com/zaproxy/zaproxy/wiki/FAQsslHandshake

**Comment by projectspcloud** [comment]
Hey kingthorin, thanks for sharing the link. Took for granted that the cause of the handshake failure would not be the java jce. I am now able to scan the sites successfully. Thank you so much.
