### ISSUE TITLE
Change 'Active Scan' to show the last n requests instead of the first ones

### ISSUE THREAD

**Issue by leegarrett** [zaproxy/zaproxy#1681]
Hi,

currently the setting under 'Options' → 'Active Scan' → 'Max results to list' allows you to configure how many requests of the scan are shown. Currently it gets truncated after n requests, showing only the _first_ n requests. This isn't very useful though, because if an Active Scan actually produces a surprising result on the web application (like returning only 404s after a certain request), you actually want to review the _last_ n requests to check what caused this.

**Comment by psiinon** [comment]
Agreed.
I've been meaning to do this for ages - thanks for raising the issue as it means this shouldnt get forgotten now.
And anyone is free to take this issues - no idea when I'll find time to look at it!

**Comment by kingthorin** [comment]
Does this really need a limit anymore? Spiders don't appear to have a limit.

**Comment by psiinon** [comment]
This was introduced after some investigations showed that the Active Scan tab was significantly slowing down very large scans. We will be sending a lot more requests via an Active Scan than the Spider. I'd be happy if we could remove this limit (or change it to show the most recent requests) but we would need to make sure it no longer impacts performance.

**Comment by thc202** [comment]
Yes, the limit is still needed, we can only remove the limit once the results are properly (#1661) paginated. The spiders should also have a limit but not as evident because they usually (#1288) send/show less messages.

**Comment by kingthorin** [comment]
@thc202 @psiinon I've got [code together that does this.](https://github.com/kingthorin/zaproxy/blob/issue-1681-activescan-table-fifo/src/org/zaproxy/zap/extension/ascan/ActiveScan.java#L267-L278) Do I need to be handling the removals [more like the additions?](https://github.com/kingthorin/zaproxy/blob/issue-1681-activescan-table-fifo/src/org/zaproxy/zap/extension/ascan/ActiveScan.java#L287-L299)

**Comment by thc202** [comment]
Yes, the removal should also be done in the EDT (preferably both the addition and removal in the same event).

Regarding the changes, the model already takes care to notify that the row was removed.
