### ISSUE TITLE
Unable to configure pnh on Firefox Dev Ed

### ISSUE THREAD

**Issue by bgurung** [zaproxy/zaproxy#1682]
I am using Firefox Developer Edition v40.0a2 and ZAP v2.4.0 (with pnh v8) on Windows 7 and unable to configure the pnh. Check the image below, that's how far the configuration process goes and then gets stuck.

![firefox-pnh-config-stuck](https://cloud.githubusercontent.com/assets/2948638/8456874/ced9f686-1fd3-11e5-9a54-bd2d5e919bf4.jpg)

Thanks,
Bhesh.

**Comment by psiinon** [comment]
Thanks for reporting this - apparently the Firefox GCLI interfaces have changed :(
We're looking into this now.

**Comment by thc202** [comment]
Merging into #2069.
