### ISSUE TITLE
API - setScannerAlertTreshold/setPolicyAlertTreshold bad parameter

### ISSUE THREAD

**Issue by Wawki** [zaproxy/zaproxy#1683]
It seems that in the Java API, the functions setScannerAlertTreshold & setPolicyAlertTreshold ( Active Scan & Passive Scan ) uses "attackStrength" in the map whereas it should be "alertTreshold"

Example in Ascan.java :

```
public ApiResponse setScannerAlertThreshold(String apikey, String id, String attackstrength, String scanpolicyname) throws ClientApiException {
        Map<String, String> map = null;
        map = new HashMap<String, String>();
        if (apikey != null) {
            map.put("apikey", apikey);
        }
        map.put("id", id);
        map.put("attackStrength", attackstrength);
        map.put("scanPolicyName", scanpolicyname);
        return api.callApi("ascan", "action", "setScannerAlertThreshold", map);
}
```

Whereas in ascan/ActiveScanAPI.java :

```
this.addApiAction(new ApiAction(ACTION_SET_SCANNER_ALERT_THRESHOLD,
            new String[] { PARAM_ID, PARAM_ALERT_THRESHOLD }, new String[] {PARAM_SCAN_POLICY_NAME}));
```

Where PARAM_ALERT_THRESHOLD is equal to "alertTreshold"

So when I use it, I encountered this problem :

`org.zaproxy.clientapi.core.ClientApiException: Missing parameter : alertTreshold`

I think that the problem exists also for the Python & JS API

**Comment by thc202** [comment]
Yeah, the API clients in master (now "develop") are frequently outdated...
Though latest version of Java (2.4-v1), Python (v2.4-0.0.2) and JS (0.2.0) API clients do not have this issue.

Which Java API client are you using? The one bundled in zap-2.4.0.jar?

**Comment by Wawki** [comment]
I use the one bundled in the weekly release (to have the 2.4.0.1 version).

I switched to 2.4-v1 and it seems to work even if I encountered other problems (example scan has some different parameters)

**Comment by thc202** [comment]
Closing, no longer applies, the Java ZAP API client is no longer bundled with ZAP (#2530, it's now in its own [project](https://github.com/zaproxy/zap-api-java/)).
