### ISSUE TITLE
API scanAsUser throws error

### ISSUE THREAD

**Issue by logancarmody** [zaproxy/zaproxy#1685]
I am updating the ruby gem for the ZAP API to fit our needs as an organization... I just wrote a scanAsUser method:

    def scan_as_user(context_id, user_id)
            url = Addressable::URI.parse("#{@base}/JSON/ascan/action/scanAsUser/")
            url.query_values = {url: @target, contextId: context_id, userId: user_id}
            RestClient::get url.normalize.to_str
    end

When I run this, I get a `Bad Action` exception from the `handleApiAction` method.
Looking at your source, I don't see where that method makes a call to ApiResponseElement, and it just seems to initialize a bunch of variables without actually initializing a scan. Any insight on this?

**Comment by logancarmody** [comment]
just as a reference... `case ACTION_SCAN` returns 
`return new ApiResponseElement(name, Integer.toString(scanId));`
after making a call to get a scanId, where `case ACTION_SCAN_AS_USER` has no such call
https://github.com/zaproxy/zaproxy/blob/8b848cd8bfdf6f3d4937d04c60a9dd81faec3fb6/src/org/zaproxy/zap/extension/ascan/ActiveScanAPI.java

**Comment by thc202** [comment]
Which ZAP version are you using? That feature was not yet released in a "main" version, you need to use a weekly release or build from source.

(Note that the case ACTION_SCAN_AS_USER falls-through so will execute the same code as the case ACTION_SCAN)

**Comment by logancarmody** [comment]
Ahh... I was using the latest main version. Started using the most recent weekly release and all is well. Thank you!

**Comment by thc202** [comment]
Great! Thanks for letting us know.
