### ISSUE TITLE
Cannot securely update zap nor run any scans

### ISSUE THREAD

**Issue by claritydave** [zaproxy/zaproxy#1687]
I get the cannot securely update zap when trying to update it, and when trying to run an attack I get the failed to attack the URL error. This started yesterday. Running the latest 2.4.0, and nothing has changed on the system except for Windows updates.
In the zap log I do see the following errors:
1. 2015-07-07 10:03:41,445 ERROR ManageAddOnsDialog - Failed to get check for updates on https://raw.githubusercontent.com/zaproxy/zap-admin/master/ZapVersions-2.4.xml
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
2. 2015-07-07 10:08:12,001 ERROR ZAP$UncaughtExceptionLogger - Exception in thread "ZAP-ProxyServer"java.lang.OutOfMemoryError: unable to create new native thread
Any assistance is greatly appreciated.

**Comment by thc202** [comment]
Do you have an outgoing proxy set?

**Comment by claritydave** [comment]
We were experimenting with localhost on 8080; but I removed it thinking this might be causing the issue.



Dave Stock
IT Security and Compliance Manager
dstock@clarityservices.com
727-400-4649

[Clarity Services Inc.]

  15550 Lightwave Dr Ste 350
  Clearwater FL 33760
  www.clarityservices.com<http://www.clarityservices.com>



This message contains information that may be privileged or confidential and is the property of Clarity Services, Inc.  It is intended only for the person to whom it is addressed.  If you are not the intended recipient, you are not authorized to read, print, retain, copy, disseminate, distribute or use this message or any part thereof.  If you received this message in error, please notify the sender immediately and delete all copies of this message.

**Comment by psiinon** [comment]
'OutOfMemoryError' - have you tried increasing the memory available to ZAP?
You'll probably have to do this by editing zap.sh or zap.bat

**Comment by claritydave** [comment]
No I have not. Why would this suddenly happen when I have been using Zap for six months?



Dave Stock
IT Security and Compliance Manager
dstock@clarityservices.com
727-400-4649

[Clarity Services Inc.]

  15550 Lightwave Dr Ste 350
  Clearwater FL 33760
  www.clarityservices.com<http://www.clarityservices.com>



This message contains information that may be privileged or confidential and is the property of Clarity Services, Inc.  It is intended only for the person to whom it is addressed.  If you are not the intended recipient, you are not authorized to read, print, retain, copy, disseminate, distribute or use this message or any part thereof.  If you received this message in error, please notify the sender immediately and delete all copies of this message.

**Comment by thc202** [comment]
In which port is/was the local proxy running?

**Comment by claritydave** [comment]
8080. Issues are happening on Zap on my laptop, and on a server on our network.



Dave Stock
IT Security and Compliance Manager
dstock@clarityservices.com
727-400-4649

[Clarity Services Inc.]

  15550 Lightwave Dr Ste 350
  Clearwater FL 33760
  www.clarityservices.com<http://www.clarityservices.com>



This message contains information that may be privileged or confidential and is the property of Clarity Services, Inc.  It is intended only for the person to whom it is addressed.  If you are not the intended recipient, you are not authorized to read, print, retain, copy, disseminate, distribute or use this message or any part thereof.  If you received this message in error, please notify the sender immediately and delete all copies of this message.

**Comment by thc202** [comment]
I mean ZAP's local proxy.

**Comment by claritydave** [comment]
Localhost:8080



Dave Stock
IT Security and Compliance Manager
dstock@clarityservices.com
727-400-4649

[Clarity Services Inc.]

  15550 Lightwave Dr Ste 350
  Clearwater FL 33760
  www.clarityservices.com<http://www.clarityservices.com>



This message contains information that may be privileged or confidential and is the property of Clarity Services, Inc.  It is intended only for the person to whom it is addressed.  If you are not the intended recipient, you are not authorized to read, print, retain, copy, disseminate, distribute or use this message or any part thereof.  If you received this message in error, please notify the sender immediately and delete all copies of this message.

**Comment by thc202** [comment]
Unless I missing something it seems there's a loop here (which explains exhaustion of threads), the outgoing proxy is pointing to the local proxy.
Can you confirm that?
In any case ZAP should warn and disallow that.

**Comment by kingthorin** [comment]
@claritydave any update?

**Comment by kingthorin** [comment]
@claritydave any update?

**Comment by claritydave** [comment]
No sorry. Have not run Zap in a long time.

Thanks
Dave



Dave Stock
IT Security & Compliance Manager
dstock@clarityservices.com<mailto:dstock@clarityservices.com>
727-400-4649

[Clarity Services Inc.]

  15550 Lightwave Dr Ste 350
  Clearwater FL 33760
  www.clarityservices.com<http://www.clarityservices.com>



This message contains information that may be privileged or confidential and is the property of Clarity Services, Inc.  It is intended only for the person to whom it is addressed.  If you are not the intended recipient, you are not authorized to read, print, retain, copy, disseminate, distribute or use this message or any part thereof.  If you received this message in error, please notify the sender immediately and delete all copies of this message.



On Feb 3, 2017, at 9:32 PM, kingthorin <notifications@github.com<mailto:notifications@github.com>> wrote:


@claritydave<https://github.com/claritydave> any update?
