### ISSUE TITLE
Updating owasp/zap2docker image with Python Client API

### ISSUE THREAD

**Issue by anshumanbh** [zaproxy/zaproxy#1688]
Hello,

I am trying to automate ZAP deployment in a Docker container. So, I am using the owasp/zap2docker image from the Docker Hub. But, after pulling it and accessing that image, I notice that the python-owasp-zap-v2 Python Client API is not installed in it. As a result, I am having to install that before I could use those APIs to start/run/stop ZAP.

So, this is a request to install that API in that Docker Image so that it helps preventing the additional step of installing it every time the image is pulled.

Thanks!

**Comment by psiinon** [comment]
Hopefully this is a one line change - trying it out now...

**Comment by anshumanbh** [comment]
Yup, it is..

apt-get install python-pip
pip install python-owasp-zap-v2

:)

**Comment by psiinon** [comment]
Thats 2 lines!
You could always send a PR ;)
