### ISSUE TITLE
Policy Creation Script

### ISSUE THREAD

**Issue by jaysig112** [zaproxy/zaproxy#1693]
Hello,

Has anyone tried making a policy creation script with the python API yet? I am trying to work on one but the policy file is a little confusing to understand and I am having trouble setting up the fields for a call like
zap.ascan.set_policy_attack_strength(id,strength,policy_name,apikey). I don't really understand what the id is. I have been looking at this for a couple of hours and wanted to know if I can get some assistance.

**Comment by thc202** [comment]
That's id of the policy you want to change. You can check the ids with:
```python
zap.ascan.policies()
```
(or using the [API UI](https://github.com/zaproxy/zaproxy/wiki/ApiDetailsUI) with <http://zap/HTML/ascan/view/policies/>)

**Comment by jaysig112** [comment]
So what if I wanted to create a policy from the python API and change some of the tests. Like if I wanted to make SQL injections High and Directory Browsing Low. Is there a way to create a custom policy from the script and edit its strengths? Thank you for all the help.

**Comment by thc202** [comment]
Yes, for example:
```python
scan_policy = "MyCustomScanPolicy"
# Create custom scan policy
zap.ascan.add_scan_policy (scan_policy) 
# Configure the strengths of the individual scanners:
# Change (some of the) SQL Injection scanners to high
zap.ascan.set_scanner_attack_strength(40018, "HIGH", scan_policy)
zap.ascan.set_scanner_attack_strength(40019, "HIGH", scan_policy)
zap.ascan.set_scanner_attack_strength(90018, "HIGH", scan_policy)
# Change Directory Browsing to low
zap.ascan.set_scanner_attack_strength(0, "LOW", scan_policy)

# ...
# Scan with scan policy created previously
zap.ascan.scan(target, scanpolicyname = scan_policy)
```
The changes done to the scan policy are persistent so you just need to run them once.
The ids of the scanners are available with:
```python
zap.ascan.scanners()
```

**Comment by jaysig112** [comment]
Ok, that is awesome. Thank you very much for all the help. You are wonderful :)

**Comment by jaysig112** [comment]
Hello,

When I run the python scanning script that was provided as a example in the documentation I am getting a error: 
while (int(zap.spider.status()) < 100):
ValueError: invalid literal for int() with base 10: 'Does Not Exist'

Is there something I need to install to run it. I have installed all the python API necessities shown in the documentation. Is there something in the GUI I need to change to make it work?

**Comment by thc202** [comment]
That error means the spider was not (yet?) started. If you have [defined an API key](https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsOptionsApi#api-key) you need to pass it when starting the spider (and doing other "actions"):
```python
zap.spider.scan(target, apikey = 'API_KEY') 
```
If you don't have a key check what is the returning value of the call to start the spider (in normal cases it's the id of the scan).

**Comment by gorivishal** [comment]
Is there an option to not select a particular plugin while creating custom scan policy? For example: Create new attack policy (Test1) --> Define list of attacks to be attempted (XSS, SQL injection) --> Define their strength (Default).

**Comment by thc202** [comment]
Not directly, you can disable all scanners and then enable just the ones you want:
```Python
scan_policy = "Test1"
zap.ascan.add_scan_policy (scan_policy) 
zap.ascan.disable_all_scanners(scan_policy)
# Enable some SQLi scanners
zap.ascan.enable_scanners("40018, 90018", scan_policy)
# Enable XSS scanners
zap.ascan.enable_scanners("40012, 40014, 40016, 40017", scan_policy)
```
(scanners have default strength by default so no further changes needed)

Would that work for your use case?

**Comment by gorivishal** [comment]
Yes this works.

**Comment by thc202** [comment]
Great!

Closing, all questions seem to be answered. Any other question, please, let us know through the [User Group](https://groups.google.com/group/zaproxy-users). Thank you.
