### ISSUE TITLE
Launching ZAP from within Eclipse

### ISSUE THREAD

**Issue by robocoder** [zaproxy/zaproxy#1694]
Add a note to https://github.com/zaproxy/zaproxy/wiki/Building that one needs to set the user.dir property when launching ZAP from within Eclipse.  (Otherwise the ApacheLicense-2.0.txt file isn't found.)

<img width="1369" alt="screen shot 2015-07-10 at 7 28 11 pm" src="https://cloud.githubusercontent.com/assets/922051/8631164/b13d2162-273e-11e5-8c50-e78a0515f4f4.png">

**Comment by thc202** [comment]
This is a bug.
