### ISSUE TITLE
Lack of Encoding Breaks Syntax Highlighting

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#1701]
Who hasn't seen an app that fails to properly encode things right?

I noticed this morning that syntax highlighting fails if things are not properly encoded. See attached screenshot for an example.

It seems we only syntax highlight for POST requests that are "Content-Type: application/x-www-form-urlencoded", however if the body of the POST isn't truly adherent then what can we do?

![syntaxhighlightissue](https://cloud.githubusercontent.com/assets/7570458/8677947/eb7c7902-2a1f-11e5-94c4-d7022cf89433.png)

**Comment by kingthorin** [comment]
Note if the @ is changed to (%40) then it works properly.

**Comment by thc202** [comment]
That's by design (it's easier to spot encoding issues) but I'll happily change it to highlight everything (and show an error?) even if the characters are not properly encoded.

P.S. It seems there's a missing "not" in the second sentence of the issue report (i.e. "_not_ properly encoded") or I'm misunderstanding it?

**Comment by kingthorin** [comment]
Ya, it was a typo, I was rushing....

Could we add a checkbox "Highlight Even Broken Encoding" or something like that?

Or could we add a different highlighting rule for broken encoding? i.e.: if an @ is encountered instead of %40 then make it +1 font size, bold, and red or something like that...

**Comment by kingthorin** [comment]
I also don't mind tackling the fix but wanted to gather some details first. 

1) Is it by design.
2) Implementation/fix thoughts.
3) Where this code is within ZAP (I have not looked at all, it could be obvious, but if you know off the top of your head then great :smiley: )

**Comment by kingthorin** [comment]
Would it be possible to resume highlighting at the next well formed chunk?

i.e.: Based on the original screenshot @my.net would remain black (not highlighted) but everything from the subsequent & would be highlighted.

That was the mistake still stands out but highlighting isn't really broken.

**Comment by thc202** [comment]
> Where this code is within ZAP

Not code directly, it's in the lexer:
https://github.com/zaproxy/zaproxy/blob/87f9954eae41b471423fe2a0a16a596afb90c462/zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/syntaxhighlight/lexers/WwwFormTokenMaker.flex#L228-L243

That is then used to generate the Java class. I'm looking at adding a Gradle task(s) for that.

> Would it be possible to resume highlighting at the next well formed chunk?

Yes.
