### ISSUE TITLE
Add "recurse" option to the spider API

### ISSUE THREAD

**Issue by raven920** [zaproxy/zaproxy#1702]
Hi,
When spidering through the GUI, you can set up the "recurse" option. It would be very useful if you could enable or disable the "recurse" option when spidering through the API.

Currently, the API doesn't have this option.

![spiderrecurse](https://cloud.githubusercontent.com/assets/1153257/8686078/c0a9f79e-2a48-11e5-98a8-0f0183b48f66.png)

**Comment by psiinon** [comment]
Yes, the API should support all of the options available via the UI.
