### ISSUE TITLE
Allow custom XSS payloads through configuration

### ISSUE THREAD

**Issue by iriusrisk** [zaproxy/zaproxy#1703]
Allow the user to specify their own XSS payloads for the XSS scanner.
- If the web app has some XSS filtering in place, then the user could work out a string that bypasses that filter and use that for the automated scanning.
- Allows ZAP to be used with the Sleep Puppy delayed XSS detection tool: https://github.com/sbehrens/sleepy-puppy

**Comment by psiinon** [comment]
The XSS scanner probably isnt suitable for user specified payloads - it actually performs targeted attacks and then analyses the responses to see if it was able to break out of the relevant context.
So its not just doing pattern matching.
However a new scanner that allows users to specify their own payloads would be a great addition - would pairs of payloads and regex detection patterns be enough?
If not - whats needed?

**Comment by continuumsecurity** [comment]
Payload with regex matchers would be great!  
(For the integration with Sleepy Puppy, no matchers are necessary, just injection)

**Comment by psiinon** [comment]
We'll need to add some infrastructure to standardize a way for users to configure rules via the UI and API, but I've been meaning to do that for ages ;)
For the Sleepy Puppy integration can you just use the fuzzer?
If not, what exactly do you need? I'm not quite sure whats required :/

**Comment by continuumsecurity** [comment]
Fuzzer could work in a pinch, but since it's per-request, it's a bit of a pain to configure for the whole app, and since you have to configure all the injection points too that's 2 layers of hassle.

But an arbitrary payload injection + regex matcher would work nicely AND I'm sure would be useful for many more situations.

**Comment by kingthorin** [comment]
Seems 'official' dev of Sleepy Puppy has been picked up by Netflix.
https://github.comNetflix/sleepy-puppy
http://m.slashdot.org/story/298937
https://threatpost.com/netflix-sleepy-puppy-awakens-xss-vulnerabilities-in-secondary-applications/114517

**Comment by continuumsecurity** [comment]
Burp takes the concept a step further with their Collaborator feature: http://blog.portswigger.net/2015/04/introducing-burp-collaborator.html

**Comment by kingthorin** [comment]
@ricekot oast candidate?

**Comment by kingthorin** [comment]
I’m going to close this one.

Between the OAST adaptation of Dennis’ PR by @ricekot and some of the community-scripts I feel this is addressed.
