### ISSUE TITLE
Problem with "not-before-version" property in ZapAddOn.xml

### ISSUE THREAD

**Issue by h3xstream** [zaproxy/zaproxy#1705]
When loading the following plugin in ZAP 2.4.0, a cryptic message is prompted.
https://github.com/h3xstream/http-script-generator/blob/gh-pages/releases/zap/scriptgen-alpha-4.zap?raw=true

Unless the `<not-before-version>` node has changed meaning, the plugin should load.

Message prompted: 
![issue](https://cloud.githubusercontent.com/assets/1645749/8419123/1afcf76c-1ec0-11e5-8ea7-450316d5ccd5.png)

Ref: [ZapAddOn.xml](https://github.com/h3xstream/http-script-generator/blob/master/scriptgen-zap-plugin/src/main/resources/ZapAddOn.xml)

cc: @compfaculty @vskram21

**Comment by psiinon** [comment]
There have been changes which mean that add-ons are typically not binary compatible moving to ZAP 2.4.0
For that reason if an add-on has a not-before date prior to 2.4.0 then its disabled.
The add-on should be recompiled and the not-before date set to 2.4.0.

**Comment by h3xstream** [comment]
Can you elaborate on binary compatibility?
Is it related to ZAP API changes?

**Comment by psiinon** [comment]
The Dev Group post where I announced this is here: https://groups.google.com/d/msg/zaproxy-develop/gdLkKoR1-Wo/oqaX4rGN0cwJ
There were various changes that affected add-ons, but I dont think any of them were API related.
From memory the main changes were to support multiple dbs and the low memory option: https://groups.google.com/d/msg/zaproxy-develop/Ivh3MnGyo6k/2bMHjgTmw6gJ
We had to change core classes to support these options, and there affected classes and methods that many add-ons use.
We (well, probably "I" ;) should have documented these changes better :/
Add-ons are zip files, so you could open the zip file, edit the manifest to make the not-before value "2.4.0" save it and try to install it then, but thats very hacky ;)
It would be much better to change the original file and recompile the add-on and then (re)submit it to the marketplace.

**Comment by h3xstream** [comment]
Are you planning to publish the API with a version? This would make more sense to detect incompatibility.
Is there a separate package for the API or is it still bundle with the hole application?

**Comment by psiinon** [comment]
Well, its not really the ZAP API, its the core classes.
While we do our best to maintain backwards compatibility sometimes we have to break it.
The core classes are changing all of the time and we try to make sure they are all accessible to add-ons, and we dont know what classes/methods people are using.
Bug fix releases should always be backwards compatible. But functional releases may not be.
The only safe option is to always use the latest zap.jar file. If that causes compilation errors then you can be sure you'll need to re-release your add-on.
I'm not sure what else we can do, apart from implementing a defined and maintained API layer, which would be very useful but also non trivial.
