### ISSUE TITLE
Feature request: Option to specify number of token to be generated.

### ISSUE THREAD

**Issue by vskram21** [zaproxy/zaproxy#1711]
The lowest possible option is 10000 which increases the time for scanning the strength of the session tokens. especially when you have multiple token to scan for.
Please include a option to specify the number of token to be generated for analyzing strength of the tokens.

**Comment by psiinon** [comment]
The updated version of tokengen is now on the Marketplace :)
Note that is you use too low a value you might not generate enough results to analyse in a meaningful way...

**Comment by kingthorin** [comment]
Agreed the two other token analyzers I've seen set their threshold for statistically significant results at 10k and 20k respectively.

**Comment by vskram21** [comment]
Thanks for making the change.

I found this not working on the release 2.4.2. it was working on the previous versions.
Although, the token generator has generated the specified number of tokens. It provides a message like in the screenshot below.

![image](https://cloud.githubusercontent.com/assets/468730/9731308/c1507fd4-5639-11e5-9190-e62cd2e0f854.png)

Note: There is nothing displayed on the error tab. Also, when I tried to save the token using save analysis. it created a file which had no token in it.
I tried repeating the step by changing the number of token to be generated to 10k, 1k, 100, the error remains the same.

**Comment by vskram21** [comment]
Hi,

Any update on the request.
I notice that ZAP is not finding the cookie at all in the ZAP 2.4.3 release.
I tried to figure out where is issue is in the code - https://github.com/zaproxy/zap-extensions/tree/8eae6dfd5b11b891f4d3d0a71cee7034c89f59a0/src/org/zaproxy/zap/extension/tokengen 
 but have no clue on where the issue is.

how should I go about on locating the issue (whether it in identifying the parameter, or parsing and fetching the parameter) and fix it.

**Comment by thc202** [comment]
@vskram21 sorry for not answering sooner.
Please, raise a new issue, it's easier to track the status of the issue that you're seeing.

In the new issue, could you provide the number of tokens and check the log file for possible errors (file zap.log located in ZAP's default directory or the directory manually specified [1])?

You might be getting the following error:
```
35713 [Thread-16] ERROR org.zaproxy.zap.ZAP$UncaughtExceptionLogger  - Exception in thread "Thread-16"
java.lang.ArithmeticException: / by zero
	at org.zaproxy.zap.extension.tokengen.CharacterFrequencyMap.checkCharacterUniformity(CharacterFrequencyMap.java:134)
	at org.zaproxy.zap.extension.tokengen.TokenAnalyserThread.run(TokenAnalyserThread.java:97)
```

[1] https://github.com/zaproxy/zaproxy/wiki/FAQconfig
