### ISSUE TITLE
break on all requests and responses not working

### ISSUE THREAD

**Issue by TechadSr** [zaproxy/zaproxy#1717]
What steps will reproduce the problem?

1. Fresh install of ZAP 2.4.0 on Windows 7 with Java 1.8.0.31, 
2. Start zap from the desktop icon, 
3. Pin the break tab, 
4. Activate "break on all requests and responses, 
5. Start FireFox 36.0.1 
6. Configure proxy setting to 127.0.0.1:8080
7. Browse to an http site

What is the expected output? What do you see instead?

ZAP like Paros years ago should stop with the request in the Break box and enable the submit and step, submit and continue, and bin buttons, requiring one of these buttons to be pressed before the request is sent, then the same thing should happen for the response before it's sent to the browser.

For this fresh install, no requests or responses appear in the Break tab.  The submit and bin buttons remain greyed out.  History tab shows all requests flying by and page renders in Firefox without ever having to click on the ssubmit buttons.

Manually setting breakpoints on specific pages seems to work.  A global break does not. 

What version of the product are you using? On what operating system?

ZAP 2.4.0 on Windows 7 with Java 1.8.0.31

Please provide any additional information below.

![image](https://cloud.githubusercontent.com/assets/13450386/8824079/616ff8ca-3040-11e5-90cc-9cf73ac72992.png)

Is there a trick to making the break on all work or is this a bug?

**Comment by psiinon** [comment]
It looks like you're in Protected mode - in this mode any actions that could be attacks only work on urls that are in scope.
Either change to 'Standard mode' or add the relevant sites / pages to a Context that is in scope.

**Comment by TechadSr** [comment]
Thank you.  That was simple.  Setting mode to Standard worked.

**Comment by psiinon** [comment]
Thanks for letting us know :)
