### ISSUE TITLE
owasp zap 2.4.0

### ISSUE THREAD

**Issue by qa2015** [zaproxy/zaproxy#1732]
scanned liferay application (scan takes lots of time, sometimes even more than 12 hours) and scan interrupted. upon session timeout by the liferay application, it kills of zap scanning.

this happen consistently (tried 4-5 times for past 2 weeks)

**Comment by psiinon** [comment]
We have a FAQ for that :) https://github.com/zaproxy/zaproxy/wiki/FAQscanSpeed

**Comment by psiinon** [comment]
If you have specific questions about speeding up your ZAP scan the the user group is the place to ask them: http://groups.google.com/group/zaproxy-users
