### ISSUE TITLE
Progreso no iniciado

### ISSUE THREAD

**Issue by peoe721n** [zaproxy/zaproxy#1733]
I dont know what happened with my ZAP tool, two days ago I couldnt introduce any link and the progress option  displays NO INICIAL. 

 Why?

Regards!!

**Comment by kingthorin** [comment]
What version of ZAP?

Perhaps you've accidentally changed the Mode?
https://github.com/zaproxy/zap-core-help/wiki/HelpStartConceptsModes

**Comment by peoe721n** [comment]
Versión 2.4.0!






Enviado desde Correo de Windows





De: kingthorin
Enviado el: ‎martes‎, ‎28‎ de ‎julio‎ de ‎2015 ‎02‎:‎33‎ ‎p. m.
Para: zaproxy/zaproxy
CC: peoe721n





What version of ZAP?

Perhaps you've accidentally changed the Mode?
https://github.com/zaproxy/zap-core-help/wiki/HelpStartConceptsModes

**Comment by kingthorin** [comment]
Ok did you check what Mode ZAP is running in?

**Comment by peoe721n** [comment]
Mode Secure!!! upsss!!! this’s the problem!!!


Thanks for you help!!


Regards






Enviado desde Correo de Windows





De: kingthorin
Enviado el: ‎martes‎, ‎28‎ de ‎julio‎ de ‎2015 ‎04‎:‎03‎ ‎p. m.
Para: zaproxy/zaproxy
CC: peoe721n





Ok did you check what Mode ZAP is running in?
