### ISSUE TITLE
Run in ATTACK Mode via API

### ISSUE THREAD

**Issue by jaysig112** [zaproxy/zaproxy#1741]
Is there a way to turn on ATTACK Mode via the python API or even the command line when starting ZAP? I see there is a away to turn it on from start but no way to actually just turn it on. Hopefully I am not missing something simple.

Thanks for the help,
Jason

**Comment by psiinon** [comment]
You _should_ be able to change it via the -config command line option, eg
./zap.sh -config view.mode=attack
but that seems to work for all of the modes _except_ the attack mode :/
Not quite sure why at the moment...

**Comment by jaysig112** [comment]
Ohh ok, well that stinks. Is there a estimated time for a fix on this or is this something that will be worked on in the future.

Thanks

**Comment by jaysig112** [comment]
Is there any progress being made on this. I am curious because being able to set attack mode via the api would basically finish the project I am working on, and make it more efficient then running a huge scan at the end after the passive scanning.

**Comment by yannicsmeets** [comment]
@psiinon I've started to implement this in the Core API. Is that the correct place, or should I put it somewhere else? Also, as I set the mode via the API, the selectbox in the ui does not change accordingly. Should it change, and if so how can I do this?

**Comment by psiinon** [comment]
The main problem is that the modes were originally intended to only work via the UI.
We have another issue open for changing this:  #1590
Changing the API to allow the mode to be set without fixing this issue feels wrong :(
So my plan was to just enable setting the ATTACK mode from the cmdline.
I think we had discussions on the dev group and people didnt like the idea of starting ZAP in ATTACK mode, but we could either enable this in daemon mode or have another cmdline option that forces it. I'm ok with either of those. 
Would that be good enough until we implement modes correctly in daemon mode?

**Comment by jaysig112** [comment]
I think starting it in ATTACK mode via  the command line would be perfect and doesn't ATTACK mode only ATTACK urls in scope so it wouldn't start up and automatically start scanning everything that went through. My plan was to start it in ATTACK mode set a context for the scope I am testing for via python API and then run my tests through the proxy. Does that make sense?

**Comment by psiinon** [comment]
Yeah, I actually put changes in so that you could use ATTACK mode in daemon mode as I thought it would be useful. But obviously not enough changes :(
How about changing the code to allow ZAP to start in ATTACK mode when its a daemon?

**Comment by jaysig112** [comment]
That works for what I am doing. I should of mentioned I am starting it as a daemon. So having it be able to start in attack mode as a daemon would work perfectly.

This is how I am currently starting it
/ZAP_2.4.0/zap.sh -port 8090 -host 0.0.0.0 -newsession /ZAP_2.4.0/session/test8 -daemon &

**Comment by thc202** [comment]
@jaysig112 you can do that already by adding the following to your command:
```-config scanner.attackOnStart=true -config view.mode=attack```

**Comment by thc202** [comment]
Also of interest, to set the policy used in attack mode:
```-config scanner.attackPolicy=MyAttackPolicy```

**Comment by jaysig112** [comment]
Ohh I thought that @psiinon said that that that method worked for all of them except attack mode. It was stated in a previous answer up above.

**Comment by thc202** [comment]
Yes, that's correct. Changing just the mode does not work, the option "attack on start" must be enabled too.

**Comment by jaysig112** [comment]
Ok awesome that worked and fixed my problem. Thank you all so much for all the help on this. '

Thanks,
Jason
