### ISSUE TITLE
OWASP ZAP to keep session alive/active till completion of all scan check

### ISSUE THREAD

**Issue by qa2015** [zaproxy/zaproxy#1742]
i believe this feature had been requested by many, however i would like to highlight it again as I find it very important to keep session alive (in order to scan to actually catch a vulnerability that exist when session active).

The reason being on session time out by an application, and when owasp zap scan runs. I believe certain page would not be accessible upon session time out which rather gives an inaccurate scan result.

**Comment by kingthorin** [comment]
This doesn't seem to be something that ZAP can impact. If the maximum session time configured by the app is exceeded and the sessions expire that's only within control of the administrator.

While active scanning with ZAP you should never encounter an idle session timeout, so I'm assuming that you're talking about maximum session lifetime.

**Comment by psiinon** [comment]
Agree with kingthorin - if your session does get timeouted out while active scanning then I'm not sure what we can do about it.
I have been meaning to put in a 'keep session active' feature into the session handling code, but that wouldnt affect active scanning.
