### ISSUE TITLE
Failed to start zap 2.4.0

### ISSUE THREAD

**Issue by thinksabin** [zaproxy/zaproxy#1757]
Failed to start ZAP
 

Message:
    java.lang.OutOfMemoryError: Java heap space
Level:
    SEVERE
Stack Trace:
Java heap space
    java.util.HashMap.resize(Unknown Source)
    java.util.HashMap.putVal(Unknown Source)
    java.util.HashMap.put(Unknown Source)
    java.security.BasicPermissionCollection.add(Unknown Source)
    java.security.Permissions.add(Unknown Source)
    jdk.nashorn.api.scripting.NashornScriptEngine.createPermAccCtxt(NashornScriptEngine.java:85)
    jdk.nashorn.api.scripting.NashornScriptEngine. (NashornScriptEngine.java:90)
    jdk.nashorn.api.scripting.NashornScriptEngineFactory.getScriptEngine(NashornScriptEngineFactory.java:141)
    javax.script.ScriptEngineManager.getEngineByName(Unknown Source)
    org.zaproxy.zap.extension.script.ExtensionScript.initialize(Unknown Source)
    org.zaproxy.zap.extension.script.ExtensionScript.<init>(Unknown Source)
    org.zaproxy.zap.control.CoreFunctionality.createExtensions(Unknown Source)
    org.zaproxy.zap.control.CoreFunctionality.getBuiltInExtensions(Unknown Source)
    org.zaproxy.zap.control.ExtensionFactory.loadAllExtension(Unknown Source)
    org.parosproxy.paros.control.Control.addExtension(Unknown Source)
    org.parosproxy.paros.control.AbstractControl.loadExtension(Unknown Source)
    org.parosproxy.paros.control.Control.init(Unknown Source)
    org.parosproxy.paros.control.Control.initSingletonWithView(Unknown Source)
    org.zaproxy.zap.ZAP.runGUI(Unknown Source)
    org.zaproxy.zap.ZAP.run(Unknown Source)
    org.zaproxy.zap.ZAP.main(Unknown Source)

**Comment by kingthorin** [comment]
Had you previously run it?
How much RAM does the system have that you tried to run it on?
What version of Java?

**Comment by thinksabin** [comment]
Yes, previously it worked. After crashing when I re-run it it worked again but sluggish, never happened before in same machine.

I'm using win8.1 in the vmware environment with 2GB RAM
Installed java version is 1.8.0_25
java se runtime environment build 1.8.0.25-b18


thanks

**Comment by kingthorin** [comment]
Did you check for hung or orphaned java processes?

**Comment by thinksabin** [comment]
no, i didnt, zap just crashed and re-runned it. I dont think there is anything in the system that uses java besides zap. its an empty system with just moxilla firefox and zap, created just to run active scanning.

**Comment by kingthorin** [comment]
Agreed, but Java is complaining about memory issues. So if ZAP crashed but Java was still resident (and taking 2GB) then after just a few crashes I wouldn't be surprised if you'd exhausted available memory.

If you've been through a restart etc are you now able to load ZAP again?
