### ISSUE TITLE
ZAP 2.4.1 UI incorrect font

### ISSUE THREAD

**Issue by isgroup** [zaproxy/zaproxy#1758]
Starting ZAP with zap.sh under Ubuntu leads to an incorrect UI font loaded (the first in the list).

Good 2.3.1 ZAP
![screenshot from 2015-07-31 15 29 54](https://cloud.githubusercontent.com/assets/8706498/9008219/034e3486-3799-11e5-8cd3-3cf3887f22ff.png)

Bad 2.4.1 ZAP
![screenshot from 2015-07-31 15 29 51](https://cloud.githubusercontent.com/assets/8706498/9008221/06a15104-3799-11e5-8467-4510f7bcac15.png)

**Comment by isgroup** [comment]
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

**Comment by psiinon** [comment]
What language have you got set?
Tools / Options .. / Language

Cheers

**Comment by isgroup** [comment]
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.5 LTS
Release:	12.04
Codename:	precise

With LTS Enablement Stack (ex: 14 LTS Xorg), custom built 4.x kernel.

**Comment by isgroup** [comment]
Hi psiinon, thanks for your reply. It's hard to say but my guess is English, as the number of chars match.

![screenshot from 2015-07-31 15 40 07](https://cloud.githubusercontent.com/assets/8706498/9008423/883e11a6-379a-11e5-8918-c2398bd9aff1.png)

**Comment by isgroup** [comment]
<thc202> ascii_, try running zap with the following command line option: -config view.fontName="DejaVu Sans"

This solve the issue (right font shown).

**Comment by psiinon** [comment]
Oh good!
Now we just need to work out why it happened in the first place :/

**Comment by kingthorin** [comment]
Can this be closed? I've never seen or heard further of this occurring.

**Comment by psiinon** [comment]
Yeah, I think so :)
