### ISSUE TITLE
Automatic check for updates fails to report new versions

### ISSUE THREAD

**Issue by marumari** [zaproxy/zaproxy#1763]
Tested both on OS X and Ubuntu 14.04.2 LTS, if you have Options -> Check for Updates on startup checked, ZAP 2.4.0 will not notify you that there is a new version available.  If you go to Help -> Check for Updates..., however, ZAP will notify you that there is a new version (2.4.1) available.

**Comment by marumari** [comment]
Note that on relaunching the Linux one, it eventually popped up quite a bit after startup to let me know it had downloaded 2.4.1.  That was after I had gone to Help -> Check for Updates..., so I'm not sure if that influenced it or not.

**Comment by thc202** [comment]
ZAP is checking for updates though it's failing to report the newer versions.
