### ISSUE TITLE
Url containing ubdomain gives - Please check that the url you secify is valid.

### ISSUE THREAD

**Issue by alekperos** [zaproxy/zaproxy#1764]
Hi, 

as in development cycle my site is in the subdomaiin like http://test.universal-az.de but when entering the URL into Quick Start for attack, I get 

`Failed to attack the URL, please check that the URL yo specify is valid`

Any ideas why?

**Comment by thc202** [comment]
Are you able to access it while proxying through ZAP?
Is it returning 200 status code? ZAP requires that to start the attack.

**Comment by alekperos** [comment]
Yes, it is accessible. 
Also if I device a request using 'Manual Request Editor' : 

```
GET http://test.universal-az.de/ HTTP/1.0
Content-Length: 0
User-Agent: Jakarta Commons-HttpClient/3.1
Cookie: $Version=0; PHPSESSID=e27b2025bbabda0f8f19c13c04f52846; $Path=/
Host: test.universal-az.de
```

I do get successful response : 

```
HTTP/1.1 200 OK
Date: Wed, 05 Aug 2015 14:36:39 GMT
Server: Apache
X-Powered-By: PHP/5.5.27
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Strict-Transport-Security: ���max-age=31536000���
Connection: close
Content-Type: text/html
```

The Quick Start wizard just gives : 

`Failed to attack the URL, please check that the URL you specify is valid`

**Comment by psiinon** [comment]
The default user agent used by the manual editor is, I think, "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.0;)".
Using that I get a 404 from you site: 

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /notsupported.php was not found on this server.</p>
<p>Additionally, a 404 Not Found
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>

You can either fix that problem on your server, or change the user agent via an HttpSender script.

**Comment by alekperos** [comment]
That is really strange. Anyways, I removed subdomain and it is put in proper domain now. Works properly. Thanks for your time.
