### ISSUE TITLE
Update to use a more recent user-agent

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#1768]
We are seeing some sites return errors with the current 'default' user agent: "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.0;)" and I've also seen WAFs block access as well.
Updating to a more recent one would help but it would also be useful to make this easily configurable via the Options, eg in the Connection section

**Comment by jjgh** [comment]
I have a question about this: even though I've changed the user agent in the connection screen to one of the presets "Firefox 39.0 Win 8.1 64-bit" (Mozilla/5.0 Windows NT 6.3; WOW64; rv:39.0 Gecko/20100101 Firefox/39.0), when I inspect the headers of the requests that the spider makes I see:

User-Agent: Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.0;)

How is that? I do I make it use the user agent I've chosen?
Thank you.

**Comment by psiinon** [comment]
Very strange - all you _should_ need to do is change it via the Connection screen :/
How are you examining the request headers?

**Comment by jjgh** [comment]
I'm looking at them in the upper right window, under the request tab. 
I've tested a script to change the user agent on each request and following to that I can see, in the same screen above, that the user agents do change. But not if I make the change in the connection screen?

Update: 
Looking at it now, after having started a new Zap session, it seems that the change has gone into effect. Maybe it will not change for the current session (even though the session is idle and has not ongoing spidering)?

**Comment by bozRADAGAST** [comment]
Hello I found a solution;

Go to Tools > Replacer Options > Add > set "Match Type" to "Request Header String" > enter a description > enter your old user agent to "Match string" > enter your new user-agent to "Replacement String" textbox > Click "enable" > click "Save"

Works like charm
