### ISSUE TITLE
Brew install fails

### ISSUE THREAD

**Issue by limianwang** [zaproxy/zaproxy#1769]
When I attempt to install using Homebrew Cask, I am running into a 404.

```
$ brew cask install owasp-zap
==> Downloading http://downloads.sourceforge.net/sourceforge/zaproxy/ZAP_2.4.0_Mac_OS_X.dmg

curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'owasp-zap' with message: Download failed: http://downloads.sourceforge.net/sourceforge/zaproxy/ZAP_2.4.0_Mac_OS_X.dmg
```

I have a gut feeling that 2.4.0 no longer exists, as the new version is 2.4.1. Perhaps need to update the homebrew version?

**Comment by psiinon** [comment]
We moved the 2.4.0 binaries to github, as we've migrated from sourceforge.
Looks like we'll need to get https://github.com/caskroom/homebrew-cask/edit/master/Casks/owasp-zap.rb changed - I'll send a pull request..

**Comment by kingthorin** [comment]
Downloads have moved to github. I started to put together a change for:
https://github.com/caskroom/homebrew-cask/edit/master/Casks/owasp-zap.rb

Something like:
```
-  version '2.4.1'
-  sha256 'd8e296cc09908f7df9970ac6f701191bf7ccdff628d95194196a58689f8186be'
- # sourceforge.net is the official download host per the vendor homepage
+  # downloads have moved to github
+  url "https://github.com/zaproxy/zaproxy/releases/download/#{version/}ZAP_#{version}_MAC_OS_X.dmg"
```
But I only have access to a sha1 at the moment via: https://github.com/zaproxy/zap-admin/commit/8f1ef84ab3e34f8d2823e804a5e1a987c78722d3
Hopefully someone else is in a position to generate a sha256 and submit an update.

**Comment by psiinon** [comment]
I've raised a PR: https://github.com/caskroom/homebrew-cask/pull/13061/files

**Comment by psiinon** [comment]
Looks like this is now fixed - can you confirm it works for you?

**Comment by limianwang** [comment]
After `brew update && brew cask update`, it now works. 

Thanks!!
