### ISSUE TITLE
Document ant build instructions

### ISSUE THREAD

**Issue by max8github** [zaproxy/zaproxy#1774]
The wiki documentation, other than explaining how things are built in IDEs, should also explain how to generate things with just plain ant. Currently, in order to figure that out, you need to read the very build.xml.
The most natural action with ant, which is:

```
git clone.... (version 2.4, say)
cd zaproxy/build
ant
```

won't work. It will through an error complaining about jars missing, like `flex-messaging-common.jar`, `commons-csv-1.0.jar`, and other dependencies.

**Comment by thc202** [comment]
What commit/branch/tag did you checked out? Could you provide the output with the errors?
Builds fine here (default target) with tag 2.4.0 and branch 2.4.

You don't need to read the build.xml file to know how to build ZAP (and do some other tasks) with Ant.
It's enough with ```ant -p```. It shows the targets available and what they do (it's true that the descriptions could be better but it's enough information to know what they do).

**Comment by max8github** [comment]
yes, here we go:
```
git checkout 2.4
cd build
ant
```
result:
```
package-macosx:
     [echo] Packaging the Mac OS X build...

BUILD FAILED
/Users/max/code/zaproxy/build/build.xml:813: /Users/max/code/zaproxy/build/mac_os_x/OWASP ZAP.app/Contents/PlugIns does not exist.
```
Ant, java:
```
ant -version
Apache Ant(TM) version 1.9.4 compiled on April 29 2014

java -version
java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)
```

**Comment by thc202** [comment]
Ah, I see.

You have to create the ```PlugIns``` directory (it was lost during the migration from SVN to git, though that's already fixed).

**Comment by max8github** [comment]
ok, tried, thank you, now fails with:
```
BUILD FAILED
/Users/max/code/zaproxy/build/build.xml:813: Note that jre-7u75-macosx-x64.tar.gz must be in /Users/max/code/zaproxy/build/mac_os_x/OWASP ZAP.app/Contents/PlugIns for build to complete.
```

**Comment by psiinon** [comment]
By default the 'full-release' target generates Linux and Mac releases.
In order to generate the Mac one you need to download the specified JRE and put it in the specified directory.
If you dont need to generate the Mac release then you can just comment this out.

**Comment by kingthorin** [comment]
Is this still an issue?

**Comment by thc202** [comment]
Lets close it, https://github.com/zaproxy/zaproxy/wiki/Building#ant-no-ide has the minimum to build ZAP with Ant (moreover the macOS JRE is automatically downloaded from zap-libs).
