### ISSUE TITLE
Query Value for API

### ISSUE THREAD

**Issue by logancarmody** [zaproxy/zaproxy#1782]
Hey Guys... I know the docs haven't been updated since the last release, but what query value should I be passing the api key to with my requests?

**Comment by thc202** [comment]
If you can run with GUI you can check the value of the key in the API options panel. [1]
Otherwise you can check in the config.xml the element "apikey".

P.S. Which docs are you referring to? "API details"?

[1] https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsOptionsApi#api-key

**Comment by logancarmody** [comment]
I'm referring to this link:
https://github.com/zaproxy/zaproxy/wiki/ApiGen_Index

and I'm running in daemon, and I always get the error `Invalid or missing API Key` whenever I send a command. So I guess what I'm asking is how should I send my API key with my GET requests (I'm the one who is rewriting the terrible ruby gem)

**Comment by Grunny** [comment]
The query param name is just ["apikey"](https://github.com/zaproxy/zaproxy/blob/53e36d42e/src/org/zaproxy/zap/extension/api/API.java#L61). You can also browse the ZAP API locally while ZAP is running by navigating to http://zap/ if you're proxying through ZAP (or 127.0.0.1:<port ZAP is running on> if you're not) which will show you all the params each API method takes.

**Comment by psiinon** [comment]
More details here: https://github.com/zaproxy/zaproxy/wiki/FAQapikey
