### ISSUE TITLE
Option to include details of the tests run in the report

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#1783]
Be really useful to have an option to include the details of which tests were run in a report.
https://twitter.com/stephendv/status/631758405145858048

**Comment by kingthorin** [comment]
Scan policy report per scan? i.e.: "This scan included the following passive scanners and the following active scanners:"
Or test status per item per run? i.e.: "http://exmample.com/a.page | param fred | X-Fame-Options Scanner | Pass/Fail/Not Run/Error" (repeat for Every URL, Every Param/Cookie/etc, Every Enabled Scanner

**Comment by psiinon** [comment]
I'd have thought that 'per item per run' would generate far too much useless info ;)
We've had similar requests before, basically most people seem to want to know what tests were run at a high level, eg Cross Site Scripting, SQL Injection etc etc
I think we should also report the thresholds and levels used.
However ZAP reports currently show the 'current' state rather than the results of a scan. So I'm not really sure how we handle multiple scans - just report the superset of tests run?
Or give people the option to get results just from one scan? That could be really useful, particularly for repeating tests...

**Comment by psiinon** [comment]
Implement via the new report add-on :)
