### ISSUE TITLE
Scan Progress Pane Needs Sorting Change

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#1788]
ZAP 2.4.0 

Seems we're alpha sorting the scan list, which causes the drop-down to be pruned incorrectly.

Shown should be the most recent 5 (if I understand correctly). 50, 6, 7, 8, 9 is obviously not sorted numerically and therefore not the recent 5 (which would actually be 50, 49, 48, 47, 46).

![alpha_sort](https://cloud.githubusercontent.com/assets/7570458/9291105/245afaf2-437d-11e5-863f-4720b8be2133.png)

**Comment by thc202** [comment]
It also affects the Spider (i.e. any component that use the class ```ScanPanel2```).
