### ISSUE TITLE
Question Console App OWASP 

### ISSUE THREAD

**Issue by jengra** [zaproxy/zaproxy#1794]
Hey
can I ask you more things for programming with OWASP ? or it is not allowed ?
I think I understand some things wrong.
is it correct that the console program I only get a root url give or do I have to ensure that first all urls gone through .
an example:
http://domain.de/home/index root-Directory
our application has many subfolders
example:
http://domain.de/e.10444444/dashboard/index sub-Directories
http://domain.de/e.10444444/settings/index

http://domain.de/e.10444444/settings/anithinelse

and a lot of more.
if i do it the same in OWASP UI then a add my Proxy in Firefox, then i start our application and check each Link
after that i add in ZAP the context and user and i start my scan or the spider.
i have to do the same in console app.
the problem with "internel server error 500" has not done
but i think i don't need this methode i'm not sure.
Let me tell you what I intend:
I add a console applicateion in Buildserver,
this console app start zap and make the tests.
if we have enough errors we want stop the deployment of live-system.

you ask me if i tried to start ZAP multiple times?
I think no. becaus i open zap deamon and at the end i shutdonw zap.

is that possible can you give me leads?
Thank
you
many greetings

**Comment by psiinon** [comment]
Please ask questions on either:
* The ZAP User Group: http://groups.google.com/group/zaproxy-users
* The ZAP Developer Group: http://groups.google.com/group/zaproxy-develop

Many thanks :)
