### ISSUE TITLE
Sort Sites Map Alphabetically

### ISSUE THREAD

**Issue by davewichers** [zaproxy/zaproxy#1800]
When I attacked a target URL I believe the SiteMap that was generated was in alphabetical order under each folder. But when I ran the Spider against a site, the URL order was all jumbled up. So either automatically sort the site map, or add a feature where you can sort it.

**Comment by davewichers** [comment]
This has been open like 8 months. Has anyone looked at it? Can this at least be marked as an Enhancement so it gets in the right queue? I wouldn't think it would be that hard to implement this.

**Comment by psiinon** [comment]
Flagged as an Enhancement :)
TBH we dont really have a queue for work - people work on what they want to. So you need to convince / coerce someone into 'deciding' that they want to do it ;)
I agree that it shouldnt be too hard, but I'm way overloaded by things to do right now:/

**Comment by kingthorin** [comment]
Would we want this to be the new default? Or would we want it as an option?

(I have a workable code solution, however, it's non-optional ... it would be a replacement)

**Comment by davewichers** [comment]
I think sorted should be the default.

**Comment by thc202** [comment]
Sorted non-optional is fine by me (this will change the order in which the nodes/requests are active scanned, but that should be OK).

**Comment by psiinon** [comment]
Agreed (sorted, not optional, assuming theres no noticeable performance impact;)

**Comment by kingthorin** [comment]
The code is here if you want to have a quick look/test: https://github.com/kingthorin/zaproxy/tree/issue-1800-sort-site-tree

I've done basic testing with it of just branch/lead ordering in simple examples. 
I haven't tried DataDriven, or Structural params. 
I did test loading saved sessions which works without issue but also doesn't sort. Perhaps that's expected? I'm not sure how the tree is saved in the session...

![Here's a before screen cap:](https://cloud.githubusercontent.com/assets/7570458/22201985/0f8d7234-e134-11e6-9411-6eb0023e3faa.png)

![Here's an after screen cap](https://cloud.githubusercontent.com/assets/7570458/22201984/0f8a81c8-e134-11e6-95aa-503404c2c400.png)

**Comment by psiinon** [comment]
That looks good to me, submit that PR :)

**Comment by kingthorin** [comment]
Do either of you have simple setups for DataDriven, or Structural params that you can run test with this branch?

Also I just did some testing with numbers and it applies alpha sorting to leading numbers, i.e.: 4, 5, 50. Is that ok?

**Comment by davewichers** [comment]
I'm not sure what you are referring to by DataDriven, or Structural param.
I think my answer is no in any case. Regarding leading numbers, I would
expect that behavior so seems OK to me.

-Dave

**Comment by kingthorin** [comment]
Thanks @davewichers.

For  DataDriven, or Structural param examples I should have mentioned @psiinon & @thc202.

**Comment by thc202** [comment]
Sure, will test the branch with parameter modifiers and loading old sessions (I'd expect that to be sorted as well).

**Comment by kingthorin** [comment]
I think the sorting of old sessions might have been some weird one off, perhaps I hit start too quick in eclipse when switching branches or something. I've tested it a few times since and not encountered the same behavior so I'm less worried about that at this point. Versus knowing that Structural modifiers and DataDriven nodes are properly sorted.

Thanks @thc202! ⚡️

**Comment by psiinon** [comment]
Submit the PR and I'll test Structural Modifiers and Data Driven nodes - I have some test apps for that.

**Comment by kingthorin** [comment]
https://github.com/zaproxy/zaproxy/pull/3171 as requested.

**Comment by kingthorin** [comment]
@psiinon any luck testing this?

**Comment by thc202** [comment]
Just tested with structural modifiers, some nodes are not correctly sorted (seems to be because of use of `getCleanNodeName()` instead of `getNodeName()`).

**Comment by kingthorin** [comment]
Thanks
