### ISSUE TITLE
Allow users to specify a list of alerts to ignore

### ISSUE THREAD

**Issue by davehunt** [zaproxy/zaproxy#1843]
We should allow users to compile a list of alerts that they want to ignore, and when provided we should only report alerts that aren't on the list. This would allow quick identification of new alerts when scanning.

**Comment by kingthorin** [comment]
You can specify which scanners to include in the scan policy (active and passive), and I believe the reporting functionality was recently revised to allow you to select which alerts should be reported upon.

Additionally you can manually set the risk and confidence of individual alerts (including marking as false positive). Which are parameters that can be used from a reporting perspective as well (IIRC).

Do you mean that you want some sort of read/unread flag on each alert within the UI?

**Comment by davehunt** [comment]
My use case is for running ZAP in continuous integration. I'd like to specify the false positives and harmless alerts on a per site basis, and for ZAP to only alert when something outside of that list is detected.

**Comment by kingthorin** [comment]
Ok so you want to be able to create some sort of list of alerts/conditions to suppress.

i.e.: We know the Secure attribute on cookie lmnop is not set, we've decided it's fine, suppress this warning on subsequent runs of the tool suppress that finding.

**Comment by davehunt** [comment]
@kingthorin yep, that sounds about right

**Comment by psiinon** [comment]
I think this could actually be part of a larger solution, for example also defining which alerts are _expected_.
This could be useful with real apps to test that an app is being fully scanned, but more useful when testing ZAP by scanning benchmark apps ;)
I've assigned it to myself , and plan to post a proposed solution to the dev list before too long...

**Comment by psiinon** [comment]
Just posted to the Dev group about this: https://groups.google.com/d/msg/zaproxy-develop/S81DferznW8/nSFSMDN-BwAJ
Feedback via the group please :)

**Comment by psiinon** [comment]
Implemented and released the Context Alert Rules add-on which hopefully solves this problem.
