### ISSUE TITLE
ZAP not opening after installation Mac OSX 10.9.5

### ISSUE THREAD

**Issue by marylinh** [zaproxy/zaproxy#1847]
Downloaded ZAP 2.4.1 for Mac OS X
Attempted install from OWASP ZAP.app
IT opens but then I get this message
Also the Main ZAP screen seems empty
![screenshot 2015-08-22 22 05 57](https://cloud.githubusercontent.com/assets/13530220/9426584/0402ea6a-491a-11e5-92f5-5366d19b8e4a.png)

**Comment by thc202** [comment]
The error message was fixed in #1781 (fix not yet released though).

Could you provide a screen capture of the main ZAP screen that seems empty?

**Comment by marylinh** [comment]
After I opened Eclipse,I'm not able to reproduce the empty main screen.
I restarted the computer , started ZAP however I still get the 'unsupported option message'

**Comment by thc202** [comment]
The fix for that error message was just included in today's weekly release. [1]
Would you mind giving it a try?


[1] https://github.com/zaproxy/zaproxy/wiki/Downloads#zap-weekly

**Comment by marylinh** [comment]
I tested with build ZAP_D-2015-08-24 and it works. No msg is displayed. Can close the issue ;-)

**Comment by kingthorin** [comment]
Thanks @marylinh, closing.
