### ISSUE TITLE
Authentication requests made by Zest script don't go thru HttpSender

### ISSUE THREAD

**Issue by dmettem** [zaproxy/zaproxy#1850]
I've created an Authentication script using Zest and a HttpSender script using Rhino engine.

Authentication script is a simple POST request to login, followed by a GET request to get anti CSRF token value.

When I run Active scan on a URL, first the control goes HttpSender script with initiator (1 - Active Scan), and then it comes to Authentication script (once ZAP identifies that user is logged out, with the help of logged in/out indicator). At this point, I expect the requests made by Authentication script to go thru HttpSender. However, they don't.

If I change the Authentication script to Rhino engine (specifically, Javascript), I could see that the requests made by Authentication script go thru the HttpSender.

Does it mean that Authentication scripts in Zest don't go thru HttpSender? Why is the behavior different between Zest Authentication script vs. Rhino engine Authentication script?

**Comment by thc202** [comment]
This was fixed in inversion 20 of the Zest add-on (see #2114).
