### ISSUE TITLE
Controlling maximum depth to crawl using ruby gem owasp_zap

### ISSUE THREAD

**Issue by ambikashri** [zaproxy/zaproxy#1854]
Hello,
I wanted to know if we could control the depth to crawl in spidering using owasp_zap gem in ruby or could we pass parameters while calling the spider
```
spider = zap.spider
```
Also can we limit the number of urls visted during active scan in ruby?

**Comment by psiinon** [comment]
The owasp_zap Ruby gem is not maintained by the ZAP team - you'll need to ask the maintainers to update it to support the latest ZAP features.
To limit the number of urls visited in an active scan then just limit the number of urls you spider :)
