### ISSUE TITLE
Spider might report wrong progress after finishing

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#1858]
Issue reported in OWASP ZAP User Group: <https://groups.google.com/d/msg/zaproxy-users/GRtzMJ4WJzk/w0pq_ZqxFAAJ>

Steps to reproduce the issue:
1. Run ZAP and configure the spider to use more than one thread;
2. Spider a website;
3. Wait it to finish, note that the progress is not 100% (it might be, for example, 95%, 97%, 98%, 99% depending on number of threads and URLs found).

Remarks:
Since it's caused by a concurrency issue it might require several tries to reproduce.
The issue is very problematic/misleading for ZAP API users since the progress is normally used to check if the spider has finished.

ZAP Versions:
Versions >= 2.0.0

**Comment by thilina27** [comment]
This happens with the source build also. 

![image](https://cloud.githubusercontent.com/assets/13943331/9596243/ebb650be-508f-11e5-891e-36458940718f.png)
