### ISSUE TITLE
Jenkins + ZAProxy Report not generated in daemon mode

### ISSUE THREAD

**Issue by qaDream77** [zaproxy/zaproxy#1859]
I read that this is a bug, is it isolated to 2.4.1 or is there a stable build that does not have this issue?

Cheers.

**Comment by kingthorin** [comment]
Closing as duplicate of #1792 

Fixed in latest weekly: https://github.com/zaproxy/zaproxy/wiki/Downloads#zap-weekly

**Comment by qaDream77** [comment]
Not to be rude but i updated Zap today and have this issue currently, unless this was something that got updated within the last couple hours. :(

**Comment by kingthorin** [comment]
You need a weekly build to get the fix, or to wait for 2.4.2
