### ISSUE TITLE
Failed to attack url

### ISSUE THREAD

**Issue by malutanpetronel** [zaproxy/zaproxy#1861]
It is about a http://subdomain.domain.com which I am trying to attack.
Obviously that could be opened in the browser and is it valid
The message is:

Failed to attack url ! please check that the url you specify is valid

**Comment by psiinon** [comment]
Have a look at this FAQ: https://github.com/zaproxy/zaproxy/wiki/FAQquickScanFailed
Does that help?

**Comment by kingthorin** [comment]
7months later, no further update. Closing.
