### ISSUE TITLE
Can't Find JRE plugins

### ISSUE THREAD

**Issue by logancarmody** [zaproxy/zaproxy#1862]
When I download the latest version of the Zap project and run the `zap.sh` file, I get this output... I just recently updated java 1.8, but I've been using a bash script to change between versions... any insight?

Bash Script: http://www.jayway.com/2014/01/15/how-to-switch-jdk-version-on-mac-os-x-maverick/

```
Found Java version 1.7.0_71
Available memory:  8192 MB
Setting jvm heap size: -Xmx512m
/Users/logan/ZAP_2.4.1/zap.sh: line 86: /Users/logan/ZAP_2.4.1/../PlugIns/jre*/Contents/Home/bin/java: No such file or directory
/Users/logan/ZAP_2.4.1/zap.sh: line 86: exec: /Users/logan/ZAP_2.4.1/../PlugIns/jre*/Contents/Home/bin/java: cannot execute: No such file or directory
```

**Comment by marumari** [comment]
This should be fixed in the upcoming 2.4.2 version.  Grab this zap.sh file:

https://raw.githubusercontent.com/zaproxy/zaproxy/develop/src/zap.sh

And replace zap-dev.jar at the bottom with the correct version (zap-2.4.1.jar) and everything should work.  If it doesn't, let me know.

**Comment by logancarmody** [comment]
@marumari awesome... thank you. There are just two references to the .jar file that you have to change... other than that... all is well!

**Comment by marumari** [comment]
@logancarmody Thanks for checking up on that!  I really appreciate it!
