### ISSUE TITLE
Add post-processing logic to attack guis

### ISSUE THREAD

**Issue by xeno6696** [zaproxy/zaproxy#1866]
Not that we have to copy Burp--but Burp has a very nice feature where you can configure as part of your attack a post-processing step that will allow you to search for target text in the Header and in the response.  These fields are then output into the final report.  See the Grep features specified [here.](https://portswigger.net/burp/help/intruder_options.html)

**Comment by kingthorin** [comment]
@xeno6696 did you mean for the fuzzer?

**Comment by xeno6696** [comment]
Yes, yes I did!

**Comment by thc202** [comment]
If this is for the fuzzer then the Tag Creator processor (feature implemented in zaproxy/zap-extensions#49) addresses this?

**Comment by kingthorin** [comment]
Closing per previous reply, plus search allows regex.
