### ISSUE TITLE
[Python] Display error message for missing/invalid api key.

### ISSUE THREAD

**Issue by yashmehrotra** [zaproxy/zaproxy#1868]
Currently, if we haven't disabled the API KEY option in ZAP, the python client does not raise that specific error. Instead it raises a JSON Decoding Error: `ValueError: No JSON object could be decoded`.

Actual Traceback Example:
```python
>>> zap.spider.scan(target)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/zapv2/spider.py", line 108, in scan
    return self.zap._request(self.zap.base + 'spider/action/scan/', {'url' : url, 'apikey' : apikey})
  File "/usr/local/lib/python2.7/dist-packages/zapv2/__init__.py", line 131, in _request
    return json.loads(self.urlopen(url + '?' + urllib.urlencode(get)))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by thc202** [comment]
That's caused by #1805. Latest weekly release has the issue fixed in case you want to give it a try. [1]

[1] https://github.com/zaproxy/zaproxy/wiki/Downloads#zap-weekly

**Comment by yashmehrotra** [comment]
@thc202 Oh, my bad.
I tried this in the latest weekly release and its working as expected.

**Comment by thc202** [comment]
Thanks for letting us know.

**Comment by valour01** [comment]
I pulled the latest developed branch and build the python client lib. But the same exception raised. Do you have any idea?

**Comment by thc202** [comment]
The problem is/was in ZAP itself not the Python client.
What ZAP version are you using? Latest ZAP version (2.4.3) does not exhibit that issue.

**Comment by valour01** [comment]
@thc202 I am programming on the cloud with no GUI. I just want to use the python api provided by ZAP for development, do I have to install ZAP or do you have any idea when there is no GUI for me. Many Thanks

**Comment by valour01** [comment]
@thc202 I start ZAP 2.4.3 in daemon mode it works. Many thanks

**Comment by thc202** [comment]
OK, thanks for letting us know.
