### ISSUE TITLE
Two Cookie line in the header when adding a cookie with an httpsender script and doing an active scan

### ISSUE THREAD

**Issue by michaelcourcy** [zaproxy/zaproxy#1874]
I use an httpsender script that add cookie to every request.

    var has_js_cookie = new org.parosproxy.paros.network.HtmlParameter(COOKIE_PARAM_TYPE, HAS_JS_NAME, "1");
    cookieParams.add(has_js_cookie);
    var toolbar_cookie = new org.parosproxy.paros.network.HtmlParameter(COOKIE_PARAM_TYPE, TOOLBAR_NAME, "0");
    cookieParams.add(toolbar_cookie);

 If I use it during an active scan with a context that create a session based on cookies, first zap add the cookie of the session in the header 
    
    Cookie: SESS8bcff576a76286b5afa8392e2841f07f=9344OUeBNCCDF8YKkTni2SKSpFuzx5mNulec1n_sXnA

Then it adds the two other cookies in an other line 

    Cookie: toolbar.collapsed=0; has_js=1 

Instead of adding them to the cookie line already created, this results in a header with two lines of cookies.

    Cookie: toolbar.collapsed=0; has_js=1
    Connection: keep-alive
    Content-Length: 0
    Host: 172.17.0.3
    Cookie: SESS8bcff576a76286b5afa8392e2841f07f=9344OUeBNCCDF8YKkTni2SKSpFuzx5mNulec1n_sXnA

The cookie line that's going to be taken in account by the server is unpredictable. 
  
I use ZAP 2.4.1

**Comment by thc202** [comment]
How are you obtaining (i.e. cookieParams) and setting the cookies?
For which "initiator" are you changing the message? Active Scanner? All?

**Comment by michaelcourcy** [comment]
I obtain cookie param inside the function sendingRequest(msg, initiator, helper) 

     function sendingRequest(msg, initiator, helper) {
        ...
        var cookieParams = msg.getCookieParams();
        ....
    }

I use it at the moment for all the initiator but the goal is the active scanner.

**Comment by michaelcourcy** [comment]
Sorry I didnet't mean to close the issue.

**Comment by thc202** [comment]
OK, following a workaround:
```JavaScript
if (msg.getRequestingUser() && msg.getRequestingUser().getCorrespondingHttpState()) {
    var cookie = new org.apache.commons.httpclient.Cookie(/* domain */ msg.getRequestHeader().getHostName(), HAS_JS_NAME, "0");
    cookie.setPath("/");
    msg.getRequestingUser().getCorrespondingHttpState().addCookie(cookie);

    cookie = new org.apache.commons.httpclient.Cookie(msg.getRequestHeader().getHostName(), TOOLBAR_NAME, "1");
    cookie.setPath("/");
    msg.getRequestingUser().getCorrespondingHttpState().addCookie(cookie);
}
```
You might need to tweak the domain and path of the cookies.
The option "Single Cookie Request Header" [1] must be selected too.

[1] https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsOptionsConnection#single-cookie-request-header

**Comment by michaelcourcy** [comment]
The script do not get over if (msg.getRequestingUser()... because msg.getRequestingUser() is null 

But now I have a much simpler use case
If I resend this request using the request button with the forced User Mode enabled (note cookie line already exist Cookie: Drupal.toolbar.collapsed=0; has_js=1)

    GET http://172.17.0.3/ HTTP/1.1
    User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:31.0) Gecko/20100101 Firefox/31.0 Iceweasel/31.6.0
    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
    Accept-Language: fr,fr-fr;q=0.8,en-us;q=0.5,en;q=0.3
    Cookie: Drupal.toolbar.collapsed=0; has_js=1
    Connection: keep-alive
    Cache-Control: max-age=0
    Host: 172.17.0.3

Then ZAP add the cookie session at the end of the request header

     GET http://172.17.0.3/ HTTP/1.1
     User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:31.0) Gecko/20100101 Firefox/31.0 Iceweasel/31.6.0
     Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
     Accept-Language: fr,fr-fr;q=0.8,en-us;q=0.5,en;q=0.3
     Cookie: Drupal.toolbar.collapsed=0; has_js=1
     Connection: keep-alive
     Cache-Control: max-age=0
     Content-Length: 0
     Host: 172.17.0.3
     Cookie: SESS8bcff576a76286b5afa8392e2841f07f=EN-_01dPRO2fGDIQ0YDo972Q70JzSANgm9i_4b7REL4

And I click again on send then it duplicate the "Cookie: Drupal.toolbar.collapsed=0; has_js=1" line 

    GET http://172.17.0.3/ HTTP/1.1
    User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:31.0) Gecko/20100101 Firefox/31.0 Iceweasel/31.6.0
    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
    Accept-Language: fr,fr-fr;q=0.8,en-us;q=0.5,en;q=0.3
    Cookie: Drupal.toolbar.collapsed=0; has_js=1
    Connection: keep-alive
    Cache-Control: max-age=0
    Content-Length: 0
    Cookie: Drupal.toolbar.collapsed=0; has_js=1
    Host: 172.17.0.3
    Cookie: SESS8bcff576a76286b5afa8392e2841f07f=EN-_01dPRO2fGDIQ0YDo972Q70JzSANgm9i_4b7REL4

If I do it again ZAP create the same third line.

**Comment by thc202** [comment]
That means that there's no user. When are you enabling the "HTTP sender" script?
Is "Forced User" mode enabled? Or, are you specifying a user when active scanning?

Sorry, should have been more explicit, the issue is acknowledged. I was able to reproduce the issue with the indications you gave earlier.

**Comment by michaelcourcy** [comment]
I have to be more explicit myself also.

I discribe two cases now in the issue : 

1. Resquests sent by the active scanner
2. Request sent by the "Resend ..." dialog

For both cases :

-  The authentication is a form based authentication 
 - Regex pattern identified in logged in or log out response message is empty
 - I have one user (michael) which is enabled
 - Forced user is michael 
- Force user mode is enabled 
- Single cookie request header is checked

In the active scanner the httpsender script is enabled (and before starting the scanner)
In the "Resend ..." dialog the httpsender script is disabled

Hope my explainations were not too messy.

Thanks.

**Comment by michaelcourcy** [comment]
Hi I've made a pull request to solve this problem #2081
