### ISSUE TITLE
Scanner temp history not cleaned on close

### ISSUE THREAD

**Issue by dbalaouras** [zaproxy/zaproxy#1875]
According to org.parosproxy.paros.model.HistoryReference, history entries with type TYPE_SCANNER_TEMPORARY (int:14) should be removed on cleanup: 

```
    /**
     * A HTTP message sent by the (active) scanner which is set as temporary (i.e. deleted when the session is closed).
     */
    public static final int TYPE_SCANNER_TEMPORARY = 14;
```

Though, org.parosproxy.paros.db.paros.ParosTableHistory only cleans up type HistoryReference.TYPE_TEMPORARY (int: 0) by default:

```
    static {
        temporaryHistoryTypes.add(Integer.valueOf(HistoryReference.TYPE_TEMPORARY));
    }
```

The end result is having a huge session data file, containing a large number of undeleted temp history records.

**Comment by thc202** [comment]
Fixed with #1875.
