### ISSUE TITLE
Mapping between the alerts generated to the OWASP Top Ten vulnerability it belongs to

### ISSUE THREAD

**Issue by ambikashri** [zaproxy/zaproxy#1879]
It would be good to have if the alerts generated could be mapped to a specific OWASP vulnerabilty it belongs to. Like for e.g., the alert "Cookie set without HttpOnly flag" is a A3 vulnerability. 
As a suggestion it would be nice if it listed in the alert reports only wherein the the alert description, solution and other parameters relating the alert are described.

**Comment by psiinon** [comment]
Yeah, we should have this as an optional field in the alerts table, like we do with cwdId and wascId - another useful way of categorizing them :) Maybe the values should be something like "2013-A3" to cope with future changes to the Top 10?

**Comment by ambikashri** [comment]
Yes. That would be good to have.

**Comment by kingthorin** [comment]
https://groups.google.com/forum/m/#!topic/zaproxy-develop/McCDEblUE88

**Comment by ricekot** [comment]
Closing as this is now being done for most scan rules with alert tags.
https://www.zaproxy.org/docs/desktop/ui/dialogs/addalert/#alert-tags
