### ISSUE TITLE
Generating regex fuzz payloads takes forever

### ISSUE THREAD

**Issue by AndiDog** [zaproxy/zaproxy#1884]
I tried the experimental regex payload generator and expected `[0-9]{7,12}` with "Max. Payloads"=1000 and the default "Max. Length"=0 to give me either the first 1000 strings (0000000 through 0000999) or a random set of 1000 strings matching the regex. However the program hangs at 100% CPU.

The same happens with `[0-9]{1,2}`, so it's not a complexity problem.

If I use `[0-9]{1,2}` and set "Max. Length"=2, I don't get any generated strings, i.e. only the original request is repeated in the fuzz attack.

The reason seems to be that `[characters]{3}` syntax (min/max repetitions in braces) of regexes is not supported as described in https://github.com/zaproxy/zaproxy/wiki/GSoC_2014_Advanced_Fuzzing. That's fine for me, but should be warned about in the dialog. Using `*` or `+` works. There should be a maximum time to generate strings, so that the program cannot hang indefinitely.

Moreover, let's say I want to create a string of exactly 64 hex chars: `[a-f]+` with "Max. Length"=64 will generate strings of length 1-64, which is not what I want. Instead, either the mentioned repetition syntax should be supported directly (at least fixed length?), or there should be a setting "Min. Length".

**Comment by thc202** [comment]
The hang is caused by an issue in the generator, not related to support (or lack of) of repetitions.
Indeed, the implementation of max length is not correct.

Would you mind raising another issue for support of repetitions?

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#104.
