### ISSUE TITLE
Number of payloads not shown for script payload generator

### ISSUE THREAD

**Issue by AndiDog** [zaproxy/zaproxy#1887]
ZAP 2.4.2
- Add new script whose `getNumberOfPayloads` function returns 10000; enable it
- Open fuzz dialog and add the script as payload generator for some value

Result:
Column "# of Payloads" shows 0, but should be 10000.

**Comment by thc202** [comment]
Related to #1881 (fixing one should fix the other).

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#99.
