### ISSUE TITLE
Trying to disable policies to limit the scanning and alerts generated

### ISSUE THREAD

**Issue by ambikashri** [zaproxy/zaproxy#1888]
I tried disabling some policies using "http://127.0.0.1:8082/JSON/ascan/action/disableScanners/?ids=0,76,77,78,79,80,82,83,85&zapapiformat=JSON" but I didnt see any difference in the alerts generated.

```
    p  'Starting ZAP'
    zap = Zap.new :target => target,:output=>'logfile_policies.txt'

    if zap.running?
        p 'Activated ZAP'
    else
        p 'ZAP Tool Disabled'
    end

    p "Initiating Spidering for '#{target}'"
    p 'Setting Depth to Spider'
    spider_depth = ZapSpider.new
    spider_depth.depth
    p spider_depth.return_depth(depth)
    p 'Starting to Spider'
    spider = zap.spider
    spider.start

    p 'Disabling policies'
     policies = zap.scanner
policies.disable

    p 'Initiating Active Scan'
    scan = zap.ascan # Obtaining the Attack from zap instance
    scan.start   

    #Generating alerts for the active scan
    alerts = JSON.parse(zap.alerts.view)['alerts']
```

**Comment by kingthorin** [comment]
There are no scanners with ids `76,77,78,79,80,82,83,85` what made you pick those numbers?

Scanner IDs can be seen here: https://github.com/zaproxy/zaproxy/blob/develop/src/doc/alerts.xml#L24 note the list contains all scanners (active & passive at all 3 quality levels [release, alpha, beta]). Also keep in mind that third party extensions may implement their own plugin_id or scanner ID as seen [here] (https://github.com/h3xstream/rhinauditor/blob/e5a2a8e71dc9ac78a5bb58da0153e8f88dcbeec5/rhinauditor-zap-plugin/src/main/java/com/h3xstream/rhinauditor/zap/JavascriptScannerPlugin.java#L23).

**Comment by psiinon** [comment]
Also, ZAP returns all of the alerts raised to date.
So the last lot will still contrain any raised by the first scan.
You'll need to delete the alerts before the second scan if you want to see any differences (unless thats already done via a side effect of one of the calls).

**Comment by ambikashri** [comment]
I picked these numbers based on the 'id' field in the alerts generated 
```
"other": "This issue still applies to error type pages (401, 403, 500, etc) as those pages are often still affected by injection issues, in which case there is still concern for browsers sniffing pages away from their actual content type.",
        "param": "",
        "alert": "X-Content-Type-Options Header Missing",
        "evidence": "",
        "confidence": "Medium",
        "solution": "Ensure that the application/web server sets the Content-Type header appropriately, and that it sets the X-Content-Type-Options header to 'nosniff' for all web pages.\nIf possible, ensure that the end user uses a standards-compliant and modern web browser that does not perform MIME-sniffing at all, or that can be directed by the web application/web server to not perform MIME-sniffing.",
        "url": "http://testa2jul15.domain.com/robots.txt",
        "reference": "http://msdn.microsoft.com/en-us/library/ie/gg622941%28v=vs.85%29.aspx\nhttps://www.owasp.org/index.php/List_of_useful_HTTP_headers",
        "id": "76",
        "risk": "Low",
        "description": "The Anti-MIME-Sniffing header X-Content-Type-Options was not set to 'nosniff'. This allows older versions of Internet Explorer and Chrome to perform MIME-sniffing on the response body, potentially causing the response body to be interpreted and displayed as a content type other than the declared content type. Current (early 2014) and legacy versions of Firefox will use the declared content type (if one is set), rather than performing MIME-sniffing.",
        "attack": "",
        "messageId": "71",
        "cweid": "0",
        "wascid": "15"
```

**Comment by ambikashri** [comment]
Also now I want to disable searching for ""X-Content-Type-Options Header Missing" so according to the scanner id it belongs to  '10021' . I passed that to the policy id, but I still see it being listed in my generated alerts report.

**Comment by ambikashri** [comment]
I didnt understand the deleting alerts part. I am always running a new script and there is no connection to the reports generated previously. My aim is skip certain type of testing while performing active scan

**Comment by thc202** [comment]
The '76' is the ID of the alert not the ID of the scanner that raised that alert.
That's a passive scanner so it needs to be disabled with `pscan` API [1].

It's better to use the `scanners` view of the `ascan` and `pscan` APIs to check the IDs of the scanners:
<http://zap/JSON/ascan/view/scanners/>
and
<http://zap/JSON/pscan/view/scanners/>


[1] https://github.com/zaproxy/zaproxy/wiki/ApiGen_pscan

**Comment by kingthorin** [comment]
> Also now I want to disable searching for "X-Content-Type-Options Header Missing" so according to the scanner id it belongs to '10021'.

> My aim is skip certain type of testing while performing active scan

"X-Content-Type-Options Header Missing" is a passive scanner not active.

>  didnt understand the deleting alerts part. I am always running a new script and there is no connection to the reports generated previously.

If ZAP has been running in daemon mode the whole time or if you're persisting sessions then the alerts already exist, that was psiinon's point.

**Comment by ambikashri** [comment]
Ok. My concern is I am doing active scan in my script and not passive scan.
It calls this api "#{@base}/JSON/ascan/action/scan/"

**Comment by psiinon** [comment]
All requests proxied through ZAP, or started via the spiders are passively scanned - you dont need to do anything :)

**Comment by ambikashri** [comment]
So is there a way that while running in the daemon mode I clear the sessions saved and start as fresh?

**Comment by psiinon** [comment]
Yep : use core/newSession : https://github.com/zaproxy/zaproxy/wiki/ApiGen_core :)

**Comment by kingthorin** [comment]
@ambikashri can thus ticket be closed?

**Comment by kingthorin** [comment]
No further requester feedback, closing.
