### ISSUE TITLE
ZAP only scans "User-Agent", "Referer", and "Host" request headers

### ISSUE THREAD

**Issue by ElColmo** [zaproxy/zaproxy#1894]
When active scanning a request with the "HTTP Headers" input vector enabled, ZAP will only scan the following headers: "User-Agent", "Referer", and "Host".

This is due to the following code in org.parosproxy.paros.core.scanner.VariantHeader:

    public static final String[] injectableHeaders = {
        HttpRequestHeader.USER_AGENT,
        HttpRequestHeader.REFERER,
        HttpRequestHeader.HOST
    };

Currently, in order to scan request headers other than the headers named above, a "custom" input vector needs to be used.

@psiinon  suggests a black-list approach, rather than the white-list approach currently used.

I'd suggest we add the following headers to the black-list (of request headers not to scan).  I'm assuming all other request headers should be attacked by default:
- Content-Length
- Pragma
- Cache-Control

This also raises the question as to whether this list should be user specified,however.

**Comment by psiinon** [comment]
It would be good to tie this in to the attack strength, but that could be problematic ;)
A user specified white list, with the defaults @ElColmo suggested would work for me.

**Comment by ElColmo** [comment]
I have an initial change committed locally to fix this. I can't push this to the central repo though.  I'm getting " https://github.com/zaproxy/zaproxy: git-receive-pack not permitted" in Eclipse when I try to "Push To Upstream".  I have very little experience with Git, but I'm assuming this a permissions based error.

**Comment by psiinon** [comment]
We should all be using Pull Requests.
I dont yet, but I really should do :/

**Comment by ElColmo** [comment]
I'm happy to. I just don't know the specifics of how it works yet.  I'm off to do some reading on the subject!

I've already committed locally, so that might narrow my options without re-work.

**Comment by kingthorin** [comment]
Starting place: https://github.com/zaproxy/zaproxy/wiki/Contributing-Changes

**Comment by ElColmo** [comment]
Seems the process has gotten way more complicated to me.

Having said that, please see: https://github.com/zaproxy/zaproxy/pull/1899

**Comment by kingthorin** [comment]
Re: your pull request.

Should set-cookie also be marked non-injectable here? Aren't cookie injections handled properly as their own variant? Wouldn't invalidating the set-cookie header generally result in wasted requests?

What about http standard authentication headers? www-authenticate

**Comment by kingthorin** [comment]
Agreed as you said in the PR cookie not set cookie, and authz not authn
