### ISSUE TITLE
old versions can't be downloaded...

### ISSUE THREAD

**Issue by logancarmody** [zaproxy/zaproxy#1895]
I have a ruby script that runs a scan on a headless linux server. Our server provider wipes all data prior to deploy, so I worked into my script a wget call to download the linux zap version...
My issue is that every time you guys release a new version, my script breaks because
 
* Your current release url is static, i.e `/download/2.4.2/Zap_2.4.2_Linux.tar.gz`
* You remove the old packages when you release a new version, so I get a 404 when I try to access `/download/2.4.1/Zap_2.4.1_Linux.tar.gz`

I get you guys want to incentivize your users to upgrade to the most recent version, but it's a total pain on my end to have to update this every time you release... If you guys could fix one or both of the issues above that would be incredible...

**Comment by logancarmody** [comment]
@masonnl

**Comment by kingthorin** [comment]
Perhaps we need to publish something like `/download/current_version` and `/download/weekly_build`?

**Comment by logancarmody** [comment]
@kingthorin that would be a huge help if that's possible

**Comment by logancarmody** [comment]
@kingthorin is there also the ability to keep the downloads link from the previous releases? would help a ton.

**Comment by psiinon** [comment]
We already have a file that gives you links to the latest releases: https://raw.githubusercontent.com/zaproxy/zap-admin/master/ZapVersions.xml
We should publicise it better ;)
But yes, we also shouldnt download the links to the previous release straight away, my bad :(
I'll see if I can find reliable versions and recreate the release.

**Comment by logancarmody** [comment]
@psiinon thank you!

**Comment by psiinon** [comment]
Do you still need 2.4.1 downloads? 
From now on we'll aim to keep the last release as well as the current one.

**Comment by logancarmody** [comment]
No... already upgraded. thank you!

**Comment by psiinon** [comment]
Thanks for letting us know :)
