### ISSUE TITLE
Enhancement: User Story - I can view payload file contents while selecting payload files.

### ISSUE THREAD

**Issue by amuntner** [zaproxy/zaproxy#1896]
While adding payloads from a plugin or a file, it's not possible to ever see the payload contents until you actually run the attack. You need an external file browser to see what the file contents are, and to see what kind of regex replacement/formatting etc might be necessary. The same is true of Processor adding/creation. 

The functionality needed  to resolve this is already there - the Strings input and edit box. 
Currently, when you load a file, the file location is shown and you can never see it. 
If you open Strings and type in a list, Modify displays and allows editing of the list.  

Posting this as three separate user stories, the first follows

1. I can view payload file contents while selecting payload files.
Problem: Currently it is necessary to use an external file browser to view fuzzer payload contents. 
Resolution: on the Add Payload form, when adding a set of fuzzer payloads from an extension or by loading a file, a text box that displays the first few lines of whichever file is currently highlighted in the case of Add Payload or which was selected from the dialog box on the Add File form.

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#115.
