### ISSUE TITLE
Enhancement: User Story - I can view and modify the contents of the payloads I selected

### ISSUE THREAD

**Issue by amuntner** [zaproxy/zaproxy#1897]
2. I can view and modify the contents of the payloads I selected

Problem: Currently, it's not possible to view and edit the payloads themselves, only the filename selected. 

Resolution: Clicking the Modify button with the entry selected would show the Strings interface with the file contents instead of the location of the file(s) or files selected by the extension. The tester would then be able to manually view and modify the payloads. 

If the tester wanted to load a different file, they would need to Add the file. Modify would allow one to view and modify the contents with a text editor.

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#132.
