### ISSUE TITLE
Enhancement: User Story - I can view current list of payloads while creating processors in the Add and Modify Processor forms.

### ISSUE THREAD

**Issue by amuntner** [zaproxy/zaproxy#1898]
3. I can view current list of payloads while creating processors in the Add and Modify Processor forms. 
Problem: It's not possible to see the payloads while creating and modifying processors. 
Resolution: Display payloads in Add and Modify Processor forms in a view-only text box while creating the processors. It would reduce the steps of seeing what additional formatting to make your payloads work.

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#122.
