### ISSUE TITLE
ZAP returns different result when use docker container

### ISSUE THREAD

**Issue by napalm128** [zaproxy/zaproxy#1909]
ZAPproxy returns different results when use docker container.
    When I start a scan for the same target via GUI ZAP, it has the same result when I launch GUI ZAP and start scan via API. But when I launch the docker container and run a scan for the same target via API, it shows less results but some new vulnerabilities appear. What is kinda weird, cause why those vulnerabilities is missing in previous result using regular ZAP application.
    I'm using `ZAP 2.4.2` for GUI and latest `owasp/zap2docker-stable` docker container which now is `2.4.2` too, so I suppose they should return the same result.

**Comment by kingthorin** [comment]
Is the scan policy the same?
Do you have the exact same plugins/extensions installed?
Is the scan configuration the same?
Are the spider results the same?

**Comment by napalm128** [comment]
@kingthorin 
1. Yes
2. Seems like No (look below).
3. All configurations are same and I'm using the base setup of ZAP GUI and docker container which shipped by default.
4. `Spider` results are different by two `URL`s.
2 . Here is the list of plugins I can see in plugin folder, barely all plugins are different:

**docker version with ZAP 2.4.2:**
- ascanrules-release-17.zap
- bruteforce-beta-2.zap
- coreLang-release-6.zap
- diff-beta-5.zap
- directorylistv1-release-2.zap
- fuzz-beta-1.zap
- gettingStarted-release-3.zap
- help-release-1.zap
- invoke-beta-2.zap
- onlineMenu-beta-2.zap
- plugnhack-beta-8.zap
- pscanrules-release-12.zap
- quickstart-release-15.zap
- reveal-release-2.zap
- saverawmessage-release-2.zap
- scripts-beta-14.zap
- selenium-release-1.zap
- spiderAjax-release-12.zap
- tips-beta-4.zap
- websocket-release-9.zap
- zest-beta-18.zap

**desktop ZAP 2.4.2**
- ascanrules-release-20.zap
- bruteforce-beta-4.zap
- coreLang-release-9.zap
- diff-beta-5.zap
- directorylistv1-release-2.zap
- fuzz-beta-3.zap
- gettingStarted-release-4.zap
- help-release-4.zap
- invoke-beta-3.zap
- onlineMenu-release-3.zap
- plugnhack-beta-9.zap
- pscanrules-release-14.zap
- quickstart-release-16.zap
- reveal-release-2.zap
- saverawmessage-release-2.zap
- scripts-beta-15.zap
- selenium-release-3.zap
- spiderAjax-release-13.zap
- tips-beta-5.zap
- websocket-release-9.zap
- zest-beta-19.zap

**Comment by psiinon** [comment]
Ugh, I must have failed to update something when generating the Docker release :(
I'll look into that now...

**Comment by psiinon** [comment]
OK, I'm confused.
I ran:
docker run -i -t owasp/zap2docker-stable /bin/bash      

Unable to find image 'owasp/zap2docker-stable:latest' locally
Pulling repository owasp/zap2docker-stable

<load of download lines>

Status: Downloaded newer image for owasp/zap2docker-stable:latest
root@5661d6dc7d4c:/zap# ls
ZAP_2.4.2
root@5661d6dc7d4c:/zap# ls ZAP_2.4.2/
README  filter  lib      log     scripts  xml            zap-api-2.4-v6.jar  zap.ico
db      lang    license  plugin  session  zap-2.4.2.jar  zap.bat             zap.sh
root@5661d6dc7d4c:/zap# ls ZAP_2.4.2/plugin/
Readme.txt                     help-release-4.zap            scripts-beta-15.zap
ascanrules-release-20.zap      invoke-beta-3.zap             selenium-release-3.zap
bruteforce-beta-4.zap          onlineMenu-release-3.zap      spiderAjax-release-13.zap
coreLang-release-9.zap         plugnhack-beta-9.zap          tips-beta-5.zap
diff-beta-5.zap                pscanrules-release-14.zap     websocket-release-9.zap
directorylistv1-release-2.zap  quickstart-release-16.zap     zest-beta-19.zap
fuzz-beta-3.zap                reveal-release-2.zap
gettingStarted-release-4.zap   saverawmessage-release-2.zap

That looks like the same as the desktop addons reported.
Can anyone else try this?

**Comment by napalm128** [comment]
Sorry, seems like it's my bad, I have pulled owasp/zap2docker-stable:latest again and everything ok now. Thanks for your time.

**Comment by psiinon** [comment]
Thanks for letting us know :)
