### ISSUE TITLE
in OS X, always bloked.

### ISSUE THREAD

**Issue by baiyunping333** [zaproxy/zaproxy#1912]
I have the lasted version, and want to have a test. but when the scanning processing is to 25%, the whole program blocked! And can't accept any mouse event or keyboard event. 
My macbook infomation:

```
OS X Yosemite
版本： 10.10.5 (14F27)
Java version： java version "1.7.0_55"
```

**Comment by psiinon** [comment]
Are there any errors in the zap.log file?
https://github.com/zaproxy/zaproxy/wiki/FAQhelp

**Comment by kingthorin** [comment]
@baiyunping333 any further info on this?
