### ISSUE TITLE
On starting a new session when I do active scan the script breaks throwing the error  "URL Not Found in the Scan Tree"

### ISSUE THREAD

**Issue by ambikashri** [zaproxy/zaproxy#1918]
I am starting zap in daemon mode and performing active scan after starting a new session using the api call

```
http://localhost:8082/JSON/core/action/newSession/?overwrite=yes
```

On doing this during active scan, it throws the following error and stops my script
" URL Not Found in the Scan Tree". 
If I don't do the new session api call, no error is thrown.

What could be the issue? Also I have installed the Standard version of the ZAP tool. Is it because of that?

**Comment by psiinon** [comment]
You can only active scan URLs that are in the ZAP session.
If you start a new session then immediately try to active scan a url then it wont be in the session and will return this failure.
You'll need to either spider this url or access it proxying via ZAP after starting the session..

**Comment by ambikashri** [comment]
I am performing spidering before the active scan. So my steps are starting
ZAP, spidering the URL and then active scanning.
ᐧ

On Tue, Sep 22, 2015 at 2:58 PM, psiinon <notifications@github.com> wrote:

> You can only active scan URLs that are in the ZAP session.
> If you start a new session then immediately try to active scan a url then
> it wont be in the session and will return this failure.
> You'll need to either spider this url or access it proxying via ZAP after
> starting the session..
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zaproxy/zaproxy/issues/1918#issuecomment-142225776>.
>



-- 
Regards,
Ambikashri.

**Comment by psiinon** [comment]
Ah, so you're doing exactly the same in both cases, except when you start a new session first then the active scan fails.
That doesnt sound right ;)

**Comment by ambikashri** [comment]
I didnt quite understand your point. To reiterate, my zap is running in deamon mode, so in the script i do the following steps
1. Check if zap is running
2. Initiate a new session if zap is running using the api mentioned above
2. Start spider instance
3. Set a depth of 1 for spidering
4. Start spidering
4. Start active scanning

**Comment by ElColmo** [comment]
I can confirm this issue existed a few days ago, even after both Spidering and Ajax Spidering (via the API) a URL "downstream" from the URL that I want to active scan (via the API).  I never got to spend time on it, but it certainly didn't look like a scripting issue on my part.

In my case, ZAP is not in daemon mode.

**Comment by ElColmo** [comment]
And yes, I waited for the Spidering to be complete before scanning..

**Comment by psiinon** [comment]
sounds like a bug then

**Comment by thc202** [comment]
@ElColmo was the target URL really accessed? For example, trying to active scan `/x/y` will fail even after spidering (just, all under) `/x/y/z`, since `/x/y` was not actually accessed.

**Comment by ElColmo** [comment]
@thc202 No, you're correct: it wasn't.  I scanned a parent URL of the URL that was retrieved and spidered.  I tried scanning the URL that was actually retrieved spidered, and yes, that works (in the sense that the scan is actually performed).

My issue now is that I can't retrieve or spider the parent folder before scanning it, because it would have resulted in (way!) too many URLs being subsequently scanned.  Scanning a (not-explicitly retrieved) parent of the  URL that was was retrieved and spidered is supported in the GUI. It's counter-intuitive that the API doesn't support it as well.

**Comment by thc202** [comment]
Agreed. It shouldn't require access the target URL if the scan is set to `recurse`and there are URLs under the target URL.

**Comment by pcabreus** [comment]
I have a similar problem. I want to create a new session for every scanning that I want. But every time I create a new session the ascan return {"code":"url_not_found","message":"La URL No Existe"}, if a session is not created work well, but when I create the new one, only the scan fail, the spider run well. To perform the scan I need to stop the daemon and run it again. Some suggestion. This is using the API of course.

**Comment by thc202** [comment]
I guess you are having the same problem described in comment https://github.com/zaproxy/zaproxy/issues/1918#issuecomment-142255027, if you are running the spider after creating a new session and before starting the active can.
Could you confirm that?

**Comment by pcabreus** [comment]
Yes, I just want to create a new session( or multiples sessions), save it and create other and run the scan again and again. Then load wherever of the last session and see what happen.

**Comment by Madhankumar11** [comment]
I perform spider scan in my target url after I go to alerts but I get []res so how to solve this I expect for full alert report in zap told me @psiinon psiinon

**Comment by psiinon** [comment]
This issue should have been closed years ago 😁 
If you have problems like this then please ask on the ZAP User Group: https://groups.google.com/group/zaproxy-users
