### ISSUE TITLE
ZAP SQL Injections false positive

### ISSUE THREAD

**Issue by ravimds** [zaproxy/zaproxy#1919]
Hi Guys,

I have an issue while running ZAP on my web app. It detects SQL Injection even when there is no possibility for the sql injection.

Description
SQL injection may be possible.

URL
http://************/index.php

Parameter
ForgotPassword%5Bemail%5D

Attack
ZAP AND 1=1 --

Other information
The page results were successfully manipulated using the boolean conditions [ZAP AND 1=1 -- ] and [ZAP AND 1=2 -- ] The parameter value being modified was stripped from the HTML output for the purposes of the comparison Data was returned for the original parameter. The vulnerability was detected by successfully restricting the data originally returned, by manipulating the parameter.

===> This throws http 400 if email specified is not actually an email and if we try to send this parameter. Could any 1 please help us in this case.

**Comment by yhawke** [comment]
To address the issue we need some more information regarding the trouble.
More in detail:
- ZAP core Version and Plugin name and Version
- Scan configuration used (strenght and Threshold)
- How the page works and what are the page results when inserting the two payloads (e.g. what are the status codes returned back and if the content differs what're the differencies)

**Comment by ravimds** [comment]
As desired , please find below the details of the request and response for further analysis: 


1. Version : OWASP ZAP Version is : 2.4.0
2. Scan Configuration : Has been attached as screenshots
3. Request / Response for the request is as below

REQUEST : 

GET http://tests3.caslon.net/index.php?id=&source=home&storyId=444-2&noVideo=1&r=video%2Fview&mode=guide HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Referer: http://tests3.caslon.net/index.php?r=topic/homePage
Cookie: __utma=8064567.1205633237.1439916226.1439916226.1439984162.2; __utmz=8064567.1439916226.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); __utmb=8064567.7.10.1439984162; __utmc=8064567; PHPSESSID=7juv24ouav4bi79v39p511j1f0; __utmt=1
Connection: keep-alive
Content-Length: 0
Host: tests3.caslon.net

RESPONSE : 

HTTP/1.1 302 Moved Temporarily
Server: nginx/1.1.19
Date: Wed, 23 Sep 2015 08:16:30 GMT
Content-Type: text/html
Connection: keep-alive
X-Powered-By: PHP/5.3.10-1ubuntu3.12
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Location: http://tests3.caslon.net/index.php?r=site/login



Here are 2 sample request for analysis : 

1.

curl 'http://tests3.caslon.net/index.php?r=site/ForgotPassword' -H 'Pragma: no-cache' -H 'Origin: http://tests3.caslon.net' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: en-US,en;q=0.8,hi;q=0.6,af;q=0.4' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.99 Safari/537.36' -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' -H 'Accept: application/json, text/javascript, */*; q=0.01' -H 'Cache-Control: no-cache' -H 'X-Requested-With: XMLHttpRequest' -H 'Cookie: PHPSESSID=s9p9nkgge33ifmdtcn70n1nab5; utmt=1; utma=177697587.1051953075.1440051644.1442825148.1442988857.20; utmb=177697587.1.10.1442988857; utmc=177697587; __utmz=177697587.1440051644.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)' -H 'Connection: keep-alive' -H 'Referer: http://tests3.caslon.net/' --data 'email=ZAP+AND+1%3D1+--' --compressed


2. 

curl 'http://tests3.caslon.net/index.php?storyId=442+AND+1%3D1+--+&mode=guide&r=video%2Fview&source=home&id=&noVideo=1' -H 'Pragma: no-cache' -H 'Accept-Encoding: gzip, deflate, sdch' -H 'Accept-Language: en-US,en;q=0.8,hi;q=0.6,af;q=0.4' -H 'Upgrade-Insecure-Requests: 1' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.99 Safari/537.36' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'Cache-Control: no-cache' -H 'Cookie: utmt=1; PHPSESSID=lpc7qiv7fulf77trhbtms3im60; utma=8064567.261643361.1440054875.1442988614.1442992052.5; utmb=8064567.2.10.1442992052; utmc=8064567; __utmz=8064567.1440054875.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)' -H 'Connection: keep-alive' --compressed


Also Please find below other issues reported =>

1. 

Url : http://tests3.caslon.net/index.php?next=http%3A%2F%2Fwww.google.com%2F&storyId=442&mode=guide&r=site%2Flogout&source=home&id=&noVideo=1&timeout=t

Paramter : next

Attack : <title>Google</title>

My Comments : We had applied sanitisation, type casting, validations and other method to prevent attack. During out initial scan it was not reported but after 3-4 scan, we got this issue as High Medium.


2. 

We had observed the issue via charles to find out the Request/Response. Please find below the detail of the behaviour observed

URL : http://tests3.caslon.net/index.php?storyId=444-2&mode=guide&r=video%2Fview&source=home&id=&noVideo=1

Case 1. : If the user is not logged it then it gived 302 and redirects to login. Upon login. it then come back to the referer url and show 404 which is correct  

REQUEST : 
GET /index.php?storyId=444-2&mode=guide&r=video%2Fview&source=home&id=&noVideo=1 HTTP/1.1
Host: tests3.caslon.net
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.99 Safari/537.36
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8,da;q=0.6,id;q=0.4,nb;q=0.2
Cookie: PHPSESSID=fpre393rj5cedhi7mbdal051c7; __utmt=1; __utma=8064567.656991119.1441707798.1443001901.1443006068.17; __utmb=8064567.3.10.1443006068; __utmc=8064567; __utmz=8064567.1441707798.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)


RESPONSE : 
HTTP/1.1 302 Moved Temporarily
Server: nginx/1.1.19
Date: Wed, 23 Sep 2015 10:58:14 GMT
Content-Type: text/html
Transfer-Encoding: chunked
Connection: keep-alive
X-Powered-By: PHP/5.3.10-1ubuntu3.12
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Location: http://tests3.caslon.net/index.php?r=site/login




Case 2 : If the user is logged in and I visit the url, the it gives 404


REQUEST: 
GET /index.php?storyId=444-2&mode=guide&r=video%2Fview&source=home&id=&noVideo=1 HTTP/1.1
Host: tests3.caslon.net
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.99 Safari/537.36
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8,da;q=0.6,id;q=0.4,nb;q=0.2
Cookie: PHPSESSID=fpre393rj5cedhi7mbdal051c7; __utma=8064567.656991119.1441707798.1443000004.1443001901.16; __utmc=8064567; __utmz=8064567.1441707798.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)


RESPONSE:
HTTP/1.1 404 Not Found
Server: nginx/1.1.19
Date: Wed, 23 Sep 2015 10:56:02 GMT
Content-Type: text/html
Transfer-Encoding: chunked
Connection: keep-alive
X-Powered-By: PHP/5.3.10-1ubuntu3.12
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Content-Encoding: gzip

Comments : We had applied sanitization, type casting, validations and other method to prevent attack. During out initial scan it was not reported but after 3-4 scan, we got this issue as High Medium.


![zapconfig2](https://cloud.githubusercontent.com/assets/7530306/10043522/649c5702-6211-11e5-9868-8de432e3fbcf.png)
![zapconfig3](https://cloud.githubusercontent.com/assets/7530306/10043521/649c1e90-6211-11e5-951f-15f5a6d904c7.png)
![zapconfig4](https://cloud.githubusercontent.com/assets/7530306/10043523/64be2864-6211-11e5-843e-862034ed8221.png)
![zapconfig1](https://cloud.githubusercontent.com/assets/7530306/10043540/93dfc486-6211-11e5-8b46-120ce756c64e.png)

**Comment by yhawke** [comment]
Dear all, I see in your request that you're using compression, confirmed by the fact that the response content you attaced to this issue have the "Content-Encoding: gzip" header so it seems all response are gzipped.
If this is the situation, we have another issue related to gzipped content (https://github.com/zaproxy/zaproxy/issues/1871), that is compatible to the behavior you described in this issue. Indeed if the response is gzipped and a reflected value occurs, the 2 gzipped contents for True and False conditions are different because the active plugins currently work with the received raw content and don't decompress it, so they cannot detect reflected values and the boolean condition occurs...
Is this suitable to the environment you're testing?
Can you repeat the same test disabling compression on the HTTP server or removing the Accept-Encoding: gzip, deflate, ecc. header in the request?

**Comment by kingthorin** [comment]
@ravimds per @yhawke's suggestion: 
> Can you repeat the same test disabling compression on the HTTP server or removing the Accept-Encoding: gzip, deflate, ecc. header in the request?

Thanks.

**Comment by kingthorin** [comment]
No further user input. Closing, per @yhawke's previous update it seems very likely that this is #1871
