### ISSUE TITLE
Report the host:port ZAP is listening on in daemon mode, or exit if it cant

### ISSUE THREAD

**Issue by pdehaan** [zaproxy/zaproxy#1920]
Following the instructions at https://github.com/zaproxy/zaproxy/wiki/Docker#zap-headless and have the Docker portion installed, but running the following command just stalls "Creating new root CA" (on OS X 10.10.5):

```sh
$ docker run -u zap -p 8080:8080 -i owasp/zap2docker-stable zap.sh -daemon -port 8080

Found Java version 1.7.0_79
Available memory:  996 MB
Setting jvm heap size: -Xmx256m
364 [main] INFO org.zaproxy.zap.DaemonBootstrap  - OWASP ZAP 2.4.2 started.
814 [main] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - dataFileCache open start
826 [main] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - dataFileCache open end
1381 [main] INFO org.parosproxy.paros.network.SSLConnector  - Reading supported SSL/TLS protocols...
1382 [main] INFO org.parosproxy.paros.network.SSLConnector  - Using a SSLEngine...
1721 [main] INFO org.parosproxy.paros.network.SSLConnector  - Done reading supported SSL/TLS protocols: [SSLv2Hello, SSLv3, TLSv1, TLSv1.1, TLSv1.2]
1741 [main] INFO org.parosproxy.paros.extension.option.OptionsParamCertificate  - Unsafe SSL renegotiation disabled.

...

5771 [Thread-4] INFO org.zaproxy.zap.extension.dynssl.ExtensionDynSSL  - Creating new root CA
```

It's been stuck on that step for ~10m, so I'm guessing it's stuck and it doesn't take that long to create a cert. I've also tried running the command a few times, to make sure it wasn't a 1-time thing.

**Comment by thc202** [comment]
Are you sure that it is/was stuck? Did you try access the ZAP API?
I don't think it's stuck, wrongly, ZAP does not inform that the root CA cert was (successfully) created.

**Comment by thc202** [comment]
ZAP will now inform that the new root CA cert was created.

**Comment by psiinon** [comment]
Changed the title to match the proposed fix :)

**Comment by thesp0nge** [comment]
Guys, I can see this behaviour in Kali 2. ZAP is 2.4.1 and running in headless mode makes the tool stuck on INFO org.zaproxy.zap.extension.dynssl.ExtensionDynSSL  - Creating new root CA

**Comment by thc202** [comment]
Could you try access the ZAP API? ZAP should be ready to accept requests after showing that.
In the latest releases it shows more information (e.g. cert successfully created and the address/port ZAP is listening to).

**Comment by thesp0nge** [comment]
This doesn't happen with latest version, so I will upgrade ZAP

**Comment by thc202** [comment]
OK.
