### ISSUE TITLE
remove alerts for defined context

### ISSUE THREAD

**Issue by vardana** [zaproxy/zaproxy#1923]
Hi,

trying to use single ZAP daemon for multiple users and reporting and alerts miss separate context actions.

is it possible to remove alerts for defined context/scope?

only one function is available in core->deleteAllAlerts ()  which deletes all the alerts.

version I use is 2.4.2

thanks,

**Comment by psiinon** [comment]
Not at the moment, but it would be a good enhancement.
How is using one ZAP daemon for multiple users working out?
You can launch multiple daemons on the same box as long as they use different home directories and ports.
Right now ZAP is really designed for one user - ZAP as a Service (ZaaS) will change this of course ;)

**Comment by vardana** [comment]
Thanks for reply.

Running multiple ZAP daemons on the same server consumes too much memory, thus decided to check one daemon for multiple users.
Initially assumed that "Context" should exist everywhere: in reporting, alerts, scan tree thus making life easier for all users which should be great. But unfortunately its not true.

So, are there plans to make ZAP muti-user?
How can I help on it?
Rising issues, or beta testing?

Thanks.

**Comment by psiinon** [comment]
Contexts were added relatively recently, but yes, they should exist everywhere - where they dont please raise issues :)
We're not going to replace the single user ZAP desktop option, but we are going to also have a ZaaS option: https://groups.google.com/d/msg/zaproxy-develop/u_Lb16ktm7Q/cnXd-k9QGrQJ
Theres going to be a huge amount of work involved (which we have made a start on) so all help gratefully received. However its probably too early for beta testing :/
If you're interested in alpha testing some parts of ZaaS then there the MySQL support that you could have a look at :) https://groups.google.com/d/msg/zaproxy-develop/Ivh3MnGyo6k/2bMHjgTmw6gJ

Cheers

**Comment by vardana** [comment]
If I get you correctly I can rise issues for:
- Not possible to generate report html/xml for defined Context though ZAP API. Missing xmlreport(contextName* or contextID*)
- Not possible to remove scan (active/spider/...) for defined Context though ZAP API. Missing removeScan (contextName* or contextID*)
- Not possible to remove Alerts for defined Context though ZAP API. Missing deleteAllAlerts (contextName* or contextID*) or removeAllAlerts (contextName* or contextID*)

Correct?

Sure will have a look on ZaaS (good start) and mySQL support.

Thanks.

**Comment by psiinon** [comment]
Yeah, please raise issues for all of these :)

**Comment by vardana** [comment]
Thanks,

Closing this one.
