### ISSUE TITLE
Generate report for defined Context through ZAP API

### ISSUE THREAD

**Issue by vardana** [zaproxy/zaproxy#1924]
Hi

Raising new issue in response to issue https://github.com/zaproxy/zaproxy/issues/1923.
It is not possible to generate report html/xml for defined Context though ZAP API.
Missing xmlreport(contextName\* or contextID*).

Thanks

**Comment by jaysig112** [comment]
Was just curious to see if this is a feature being currently worked on? If not, is there a work around I could do for a html report?

Thanks

**Comment by raghuveerbathini** [comment]
I'm waiting for this enhancement, as there is no way to access the report by scanId or contextId.

**Comment by soumyadipmitralpl** [comment]
I am also waiting for this issue to be resolved to implement ZAP in my company for our area. Thanks.

**Comment by thc202** [comment]
Closing, being tracked in #6483. It will be added to the new Report Generation add-on:
https://www.zaproxy.org/docs/desktop/addons/report-generation/
