### ISSUE TITLE
Remove Alerts for defined Context through ZAP API

### ISSUE THREAD

**Issue by vardana** [zaproxy/zaproxy#1926]
Hi,

Raising new issue in response to issue zaproxy/zaproxy#1923.
It is not possible to remove Alerts for defined Context though ZAP API.
Missing `deleteAllAlerts (contextName* or contextID)` or `removeAllAlerts (contextName or contextID*)`.

Thanks

**Comment by vardana** [comment]
Hi,

Maybe to make it easy to implement, would be nice to have deleteAllAlerts (scanID).

Do you think that this needs a separate issue to be raised?

Thanks

**Comment by psiinon** [comment]
I'm ok with it being part of this issue - the changes will be in the same places.

**Comment by vardana** [comment]
Ok, then.

Please consider this one also - deleteAllAlerts (scanID).

Thanks
