### ISSUE TITLE
Enhancement: Break only for in-scope URLs.

### ISSUE THREAD

**Issue by amuntner** [zaproxy/zaproxy#1927]
User story: Options->Breakpoints contains a checkbox (default: off) which will result in breakpoints only being hit if the URL is in scope. 

1. Option-> Breakpoints contains new checkbox/text field "Break only for in-scope URLs"

**Comment by thc202** [comment]
Would the list be used by "Global Excluded URL" option?  [1]

[1] https://github.com/zaproxy/zap-core-help/wiki/HelpStartConceptsGlobalexcludeurl

**Comment by amuntner** [comment]
No, they would only be an exclusion for breakpoints. 

A tester would want them to appear in the history as they are used by the site but not want loading to set a breakpoint.  

I'm going to edit the initial issue with some additional comments to clarify, thanks.

**Comment by psiinon** [comment]
implemented, just need to tidy up ;)
