### ISSUE TITLE
Proxy is not capturing request for *.io websites

### ISSUE THREAD

**Issue by josephjose96** [zaproxy/zaproxy#1928]
I am using the latest ZAP version 2.4.2.

If you enable the proxy and try to connect to a site which having an .io instead of .com/.net/.org  . The proxy will not capture the request.

Take the site https://domain.io . This is in https, if you browse to the site you will face 502 Bad gateway ZAP Error [java.net.ConnectException]: Connection refused: connect . No problem for http websites. If you send a request manually also you will not get the response.

**Comment by thc202** [comment]
The problem doesn't seem to be related to TLD being accessed, for example, <https://github.io/> is properly intercepted by ZAP.
Do you have an outgoing proxy set in ZAP?

**Comment by josephjose96** [comment]
I faced the problem in some of the domain that I tried. I am not interested in sharing the url address of that sites. Seems something with the configuration that I done I guess, After doing google dork I go through some .io websites seems working correctly. So I am closing this.

**Comment by thc202** [comment]
OK, thanks for letting us know.
