### ISSUE TITLE
Enhancement: Payload Processing Preview

### ISSUE THREAD

**Issue by amuntner** [zaproxy/zaproxy#1931]
User story: While setting up payload processors, I can interactively see the result of the configured processing on a sample of selected payloads. 

Problem addressed: Currently, the user has to run a test and manually analyze the results in order to see the final payload processing. 

There are two places payload processors can be created: for each individual payload chosen, and for the entire set of payloads. 

Each location will contain a list box displaying payloads after they have run through the defined set of processors which would be executed by the current view context.

On the individual payload processor form, it would be the processors defined for that payload.

For the overall payload processing list form, it would be for the processing of the individual payload processors followed by the overall processor, followed by the final URL encoding option.  (final selective encoding - https://github.com/zaproxy/zaproxy/issues/1930)

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#122.
