### ISSUE TITLE
Enhancement: Save user-created payloads for reuse

### ISSUE THREAD

**Issue by amuntner** [zaproxy/zaproxy#1932]
User Story: An option to save user-created payloads (via Add->Strings) to the Fuzzers directory so that they could be selected for later reuse. 

1. Save option on the Strings Entry dialogue which saves the entered strings.

2. The Save option would allow either saving as a new payload set, or overwriting an already existing user created set.

3. If the user creates a new payload set, there will be a text box for providing a name 

4. After save, Zap registers the new payloads list so that it's available without restart.

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#125.
