### ISSUE TITLE
"URL to attack:" field on "Quick start" tab doesn't work as expected

### ISSUE THREAD

**Issue by xambroz** [zaproxy/zaproxy#1936]
Hello,
I am using ZAP 2.4.2 on linux with Oracle's java 1.8.60
When I click the field "URL to attack:" from the "Quick start" tab it is not possible to write anything there.
With mouse it is possible to select the pre-filled http:// text, but it is not possible to do anything else with the field.

When I use the "Select" button - then it is possible to choose some of the already visited sites in the session history of requests, but the "Attack" button still remains grayed out.

Best regards 
Michal Ambroz
![Uploading Screenshot from 2015-09-26 02:54:15.png…]()

**Comment by xambroz** [comment]
![screenshot from 2015-09-26 02 54 15](https://cloud.githubusercontent.com/assets/723625/10114957/13d68e00-63fb-11e5-8cac-104c380c5289.png)

**Comment by xambroz** [comment]
Issue was caused by something in the ~/.ZAP folder - removing it and installing plugins again fixed the issue.

**Comment by psiinon** [comment]
Thanks for letting us know.
Looks like it was in Protected mode as well, which wouldnt have helped :)
