### ISSUE TITLE
Ajax Spider Potential Bug?

### ISSUE THREAD

**Issue by qaDream77** [zaproxy/zaproxy#1942]
Following the steps
1. Make sure you are proxying via Zap
2. Identify the session
3. Set an active session from the Http Sessions tab
   3 Identify and exclude the Log off request from the spider

I fire off the ajax spider on index.cfm which is a form which posts to itself

The first page of the form collects personal information such as phone number, the ajax spider enters text into this and triggers a validation error, preventing it from ever proceeding to the next page of the form. Is this a bug or intended behavior?

Not only in ajax but the spider scan tries to put ZAP into my extension form field and also doesn't fill in some remaining empty but required fields, so it can't progress forward.

---

Similarly, is there a better way to go through a site and all of the forms on the site and evaluate it for security vulnerabilities? Especially when i need to exclude some buttons from a scan such as a go back / previous button.

**Comment by kingthorin** [comment]
@qaDream77 you can use the Form Filler addon to configure what values zap should use for specific fields. You can use the Sequence addon to record specific order of pages zap should scan. You can proxy your use of your app through zap to “teach” zap about the app (or functional tests [selenium or whatever]).
