### ISSUE TITLE
Allow to AJAX spider as a user

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#1956]
Change "AJAX Spider" dialogue to allow to specify the user (of a context) used in spider process.

Add an action to "ajaxSpider" API that allows to scan as a user.
The action will be named "scanAsUser" (the same as the traditional spider) and will allow to specify the user with the following mandatory parameters:
"contextName"
"userName"

It will also contain the following mandatory parameter (the same as the "scan" action):
"url"

Note, the optional parameter "inScope" of "scan" action is not included since it's superseded with the specification of the context.

Add-on:
"Ajax Spider"

**Comment by gonzamvita** [comment]
Hello!!

I am trying to use the AJAX spider but it is unable to login into my application. I found this issue and I assume that you are trying to add this functionality to the client but, is there any way I can try to use the AJAX Spider with user credentials?

Regards, gmv.

**Comment by thc202** [comment]
Yes, you can AJAX spider from a point of view of a user with "Forced User" mode. [1] [2]

[1] https://github.com/zaproxy/zap-core-help/wiki/HelpUiTltoolbar#--force-user-mode-on--off
[2] https://github.com/zaproxy/zap-core-help/wiki/HelpStartConceptsAuthentication#configuration-example

**Comment by thc202** [comment]
Released in version 16 of Ajax Spider add-on.
