### ISSUE TITLE
Allow URL to be pasted into AJAX Spider dialogue

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#1957]
Change "AJAX Spider" dialogue to allow to manually specify the initial URL (field "Starting point") of the spider process.
Same as #1799 but for AJAX spider.

Add-on:
"Ajax Spider"

**Comment by CalldiDoctor** [comment]
This would be really useful for supporting the addition of the URL parameters that are not sent to the server (parameters after #).
I've not been able to test the ajax spider on an application which require this kind of parameters.

**Comment by thc202** [comment]
For the record, it's possible to use a URL with a fragment as starting point for the spider.

**Comment by thc202** [comment]
Released in version 16 of Ajax Spider add-on.
