### ISSUE TITLE
Charset Mismatch must not showing on allerts

### ISSUE THREAD

**Issue by skbatoi** [zaproxy/zaproxy#1966]
We just scan out application and this allert shows up saying 

There was a charset mismatch between the HTTP Header and the HTML encoding declaration: [null] and [ISO-8859-1] do not match.

Response header:
`Content-Type: text/html;charset=ISO-8859-1`

Response Body:
`<meta charset="ISO-8859-1" content="text/html" http-equiv="content-type">`

Notice that the charset is both set to ISO-8859-1.

Rootcause: OWASP ZAP is unable to get the charset value of either the header or in the response.

We just analyze the problem. Please confirm if this is a bug. 

Thanks!
-Ronelle

**Comment by kingthorin** [comment]
Can you confirm:
* What version of ZAP? 
* What version of the Passive Scan Rules Beta addon?

Could you provide the full set of response headers? Could you also provide any META tags from the response that have `http-equiv` or `content` attributes? (Or even better the entire response?)

This is related to a Beta quality scanner [1] so it's entirely possible that it requires some work.

[1] https://github.com/zaproxy/zap-extensions/blob/beta/src/org/zaproxy/zap/extension/pscanrulesBeta/CharsetMismatchScanner.java

Looking around [line 86] (https://github.com/zaproxy/zap-extensions/blob/beta/src/org/zaproxy/zap/extension/pscanrulesBeta/CharsetMismatchScanner.java#L86) there's a check for body content character set declaration (via META tag) vs header charset declaration. Which we may need to clarify the alert text for and you might be hitting. However if you're response header is as listed above then something else might be missing as well.

**Comment by psiinon** [comment]
Do you get this problem on all pages, or just the temporary ones ZAP inserts into the tree?
I'm wondering if this is related to #1964

**Comment by thc202** [comment]
@psiinon that issue shouldn't be the problem since the temporary messages are not passive scanned.

@kingthorin the meta tag is in the issue report though not being rendered:
`<meta charset="ISO-8859-1" content="text/html" http-equiv="content-type">`
the scanner is extracting the charset from the `content` attribute, that's why it's reporting `null`.

**Comment by kingthorin** [comment]
Good catch, I've inserted Markdown into the original so that they'll display.

I'll pickup this issue and put together a fix.

**Comment by thc202** [comment]
OK, what fix do you have in mind?

**Comment by kingthorin** [comment]
Just additional checks to ensure we're actually comparing non-NULL values.

**Comment by kingthorin** [comment]
Were you thinking something more in involved or all encompassing? Feel free to grab the issue or suggest a directio. I wasn't set on anything just kinda figured it was a simple item I could take care of, knowing that you had other things going related to your recently opened tickets and the paros core replacement.

**Comment by thc202** [comment]
The alert reported is correct in this case (IMHO), since user-agents that implement older HTML specs (e.g. HTML4.01 [1]) do not know what meta charset attribute is, so the encoding set in the HTTP header does not match the one set in the HTML body (which is not set). I think we should change the alert message to not include "null" but instead say that's absent (and explain the reasoning).
In any case we should change the scanner to also check the meta charset attribute to cope with newer HTML spec. [2]

Yeah, have other things to do ;)

[1] http://www.w3.org/TR/html401/charset.html#h-5.2.2
[2] http://www.w3.org/TR/html5/document-metadata.html#charset

**Comment by skbatoi** [comment]
Hi All,

Please see details below.


What version of ZAP?
          ZAP Version = 2.4.0
What version of the Passive Scan Rules Beta addon?
          10
What version of the Passive Scan Rules Alpha addon?
          5

Response:
HTTP/1.1 200 OK
Date: Mon, 14 Sep 2015 10:14:42 GMT
X-Powered-By: Servlet/3.0
Pragma: no-cache
Cache-Control: no-store, no-cache, must-revalidate, private, proxy-revalidate
Expires: Sat, 1 Jan 2000 12:00:00 GMT
Last-Modified: Mon, 14 Sep 2015 10:14:42 GMT
X-Frame-Options: SAMEORIGIN
Content-Security-Policy: frame-ancestors *.infor.com
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Frscitna: mJClUlZgdSQoT8HIlSS67FRSnldWezg!2FFpzKQ0g3RRrYuaiZL6I5GAAAAU!2FLVzUf
Cache-Control: post-check=0, pre-check=0
Keep-Alive: timeout=10, max=100
Connection: Keep-Alive
Content-Type: text/html;charset=ISO-8859-1
Content-Language: en-US

<!DOCTYPE html><html><head><title>Infor Security Administrator</title><meta content="IE=edge" http-equiv="X-UA-Compatible">
<meta charset="ISO-8859-1" content="text/html" http-equiv="content-type">
<link href="https://lsf10.lpc.lawson.com:443/scwebadminapp/Styles/ext-all.css" rel="stylesheet" type="text/css">
<link href="https://lsf10.lpc.lawson.com:443/scwebadminapp/Styles/inforControlsCombined.css" rel="stylesheet" type="text/css">
<link href="https://lsf10.lpc.lawson.com:443/scwebadminapp/Styles/styles.combined.min.css" rel="stylesheet" type="text/css">
<link href="https://lsf10.lpc.lawson.com:443/scwebadminapp/Styles/dashboard.min.css" rel="stylesheet" type="text/css">
<script src="https://lsf10.lpc.lawson.com:443/scwebadminapp/Scripts/lib/jquery-1.11.1.min.js" type="text/javascript"></script>
<script src="https://lsf10.lpc.lawson.com:443/scwebadminapp/Scripts/lib/ext-all.js" type="text/javascript"></script>
<script src="https://lsf10.lpc.lawson.com:443/scwebadminapp/Scripts/lib/jquery.simplemodal.1.4.4.min.js" type="text/javascript"></script>
<script src="https://lsf10.lpc.lawson.com:443/scwebadminapp/Scripts/lib/json2.min.js" type="text/javascript"></script>
<script src="https://lsf10.lpc.lawson.com:443/scwebadminapp/Scripts/lib/jquery-ui-1.10.4.custom.min.js" type="text/javascript"></script>
<script src="https://lsf10.lpc.lawson.com:443/scwebadminapp/Scripts/lib/d3.min.js" type="text/javascript"></script>
<script src="https://lsf10.lpc.lawson.com:443/scwebadminapp/Scripts/main.js" type="text/javascript"></script>
<script src="https://lsf10.lpc.lawson.com:443/scwebadminapp/Scripts/ajax.sso.js" type="text/javascript"></script>
<script src="https://lsf10.lpc.lawson.com:443/scwebadminapp/Scripts/inforux30.combined.min.js" type="text/javascript"></script>
<script src="https://lsf10.lpc.lawson.com:443/scwebadminapp/Scripts/localizationmanager.js" type="text/javascript"></script>
<script src="https://lsf10.lpc.lawson.com:443/scwebadminapp/Scripts/MasterpageInitializer.js" type="text/javascript"></script>
<script src="https://lsf10.lpc.lawson.com:443/scwebadminapp/Scripts/widgets/inforControlsCombined.js" type="text/javascript"></script>
<script src="https://lsf10.lpc.lawson.com:443/scwebadminapp/Scripts/widgets/common.widgets.combined.min.js" type="text/javascript"></script>
<script src="https://lsf10.lpc.lawson.com:443/scwebadminapp/proxy/proxy.combined.min.js" type="text/javascript"></script>
<script src="https://lsf10.lpc.lawson.com:443/scwebadminapp/dashboard.min.js" type="text/javascript"></script>
<script>
		$(function() {
			//Globalize.culture("ar-SA");
			//$("#tabs").inforTabset({verticalTabs: true});
		});
	</script>
</head><body><div class="applicationContainer" id="js_AppContainer">
      
<div id="preLoad">
        
<div class="appLoaderOverlay"></div>
        
<div class="appLoaderContent">
          
<div class="appLoaderContentImg">
<span>Loading content</span>
</div>
        
</div>
      
</div>
      
<div class="Header"><div class="inforTopBanner">    <div class="inforTopBannerLeft">        <span class="inforLogo"></span>        <span class="inforBannerText" style="margin-left:30px;">Infor Security Administration</span>    </div>    <div class="inforTopBannerRight">        <ul class="userInfo">            <li><span id="loggedInUserInfo" class="inforBannerText">User</span><span class="inforToolbarSpacer"></span></li>                        <li id="selectedlanguage"></li>            <li><span class="inforToolbarSpacer"></span></li>            <li><button type="button" class="inforIconButton information" title="Show about page." onclick="showAboutPage()" style="position: relative;top: 4px;"><span></span></button><span class="inforToolbarSpacer"></span></li>                                </ul>        <button type="button" onclick="logout();" title="Sign Out" class="inforIconButton signOut" style="position: relative;top: 5px;"><span></span></button>    </div></div><div id="inforApplicationNavContainer">    <div id='pnlSearchBox' data-qtip="Search">        <input class="inforLookupField" type="text" id="lookupFieldResourceTypes" placeholder="Select resource types" title="Select resource types"/>         <input class="inforSearchField" type="text" placeholder="Search..." id="searchResourceTypes" title="Search Items">        </div>    <div id="inforApplicationNav" onclick="adjustZindex()" class="inforApplicationNav" style="height: 42px; overflow: hidden;"></div>    </div></div>
      
<div id="js_extjs_content"></div>
      
<div class="appContent" id="js_AppContent">
        
        <div id="js_pg_Main">
        
<div class="pageName"></div>
        
<div id="dbcontainer">
            
<div class="inforApplicationPadding" id="dashboard">
                
<div id="dbCardCategory"></div>
                
<div class="inforApplicationPadding" id="dbCardModules">                    
                
</div>
            
</div>
        
</div>
    
</div>

        
      </div>
      
<div class="clearfooter"></div>
    
</div>
<div class="inforBottomFooter" id="footer"><span class="inforBannerText">Infor Security Administration</span></div>
</body></html>



Thanks! 
ROnelle.

**Comment by skbatoi** [comment]
HTTP/1.1 200 OK
Date: Mon, 14 Sep 2015 10:14:42 GMT
X-Powered-By: Servlet/3.0
Pragma: no-cache
Cache-Control: no-store, no-cache, must-revalidate, private, proxy-revalidate
Expires: Sat, 1 Jan 2000 12:00:00 GMT
Last-Modified: Mon, 14 Sep 2015 10:14:42 GMT
X-Frame-Options: SAMEORIGIN
Content-Security-Policy: frame-ancestors *.infor.com
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Frscitna: mJClUlZgdSQoT8HIlSS67FRSnldWezg!2FFpzKQ0g3RRrYuaiZL6I5GAAAAU!2FLVzUf
Cache-Control: post-check=0, pre-check=0
Keep-Alive: timeout=10, max=100
Connection: Keep-Alive
Content-Type: text/html;charset=ISO-8859-1
Content-Language: en-US

<!DOCTYPE html><html><head><title>Infor Security Administrator</title><meta content="IE=edge" http-equiv="X-UA-Compatible">
<meta charset="ISO-8859-1" content="text/html" http-equiv="content-type">
<link href="https://lsf10.lpc.lawson.com:443/scwebadminapp/Styles/ext-all.css" rel="stylesheet" type="text/css">
<link href="https://lsf10.lpc.lawson.com:443/scwebadminapp/Styles/inforControlsCombined.css" rel="stylesheet" type="text/css">
<link href="https://lsf10.lpc.lawson.com:443/scwebadminapp/Styles/styles.combined.min.css" rel="stylesheet" type="text/css">
<link href="https://lsf10.lpc.lawson.com:443/scwebadminapp/Styles/dashboard.min.css" rel="stylesheet" type="text/css">
<script src="https://lsf10.lpc.lawson.com:443/scwebadminapp/Scripts/lib/jquery-1.11.1.min.js" type="text/javascript"></script>
<script src="https://lsf10.lpc.lawson.com:443/scwebadminapp/Scripts/lib/ext-all.js" type="text/javascript"></script>
<script src="https://lsf10.lpc.lawson.com:443/scwebadminapp/Scripts/lib/jquery.simplemodal.1.4.4.min.js" type="text/javascript"></script>
<script src="https://lsf10.lpc.lawson.com:443/scwebadminapp/Scripts/lib/json2.min.js" type="text/javascript"></script>
<script src="https://lsf10.lpc.lawson.com:443/scwebadminapp/Scripts/lib/jquery-ui-1.10.4.custom.min.js" type="text/javascript"></script>
<script src="https://lsf10.lpc.lawson.com:443/scwebadminapp/Scripts/lib/d3.min.js" type="text/javascript"></script>
<script src="https://lsf10.lpc.lawson.com:443/scwebadminapp/Scripts/main.js" type="text/javascript"></script>
<script src="https://lsf10.lpc.lawson.com:443/scwebadminapp/Scripts/ajax.sso.js" type="text/javascript"></script>
<script src="https://lsf10.lpc.lawson.com:443/scwebadminapp/Scripts/inforux30.combined.min.js" type="text/javascript"></script>
<script src="https://lsf10.lpc.lawson.com:443/scwebadminapp/Scripts/localizationmanager.js" type="text/javascript"></script>
<script src="https://lsf10.lpc.lawson.com:443/scwebadminapp/Scripts/MasterpageInitializer.js" type="text/javascript"></script>
<script src="https://lsf10.lpc.lawson.com:443/scwebadminapp/Scripts/widgets/inforControlsCombined.js" type="text/javascript"></script>
<script src="https://lsf10.lpc.lawson.com:443/scwebadminapp/Scripts/widgets/common.widgets.combined.min.js" type="text/javascript"></script>
<script src="https://lsf10.lpc.lawson.com:443/scwebadminapp/proxy/proxy.combined.min.js" type="text/javascript"></script>
<script src="https://lsf10.lpc.lawson.com:443/scwebadminapp/dashboard.min.js" type="text/javascript"></script>
<script>
		$(function() {
			//Globalize.culture("ar-SA");
			//$("#tabs").inforTabset({verticalTabs: true});
		});
	</script>
</head><body><div class="applicationContainer" id="js_AppContainer">
      
<div id="preLoad">
        
<div class="appLoaderOverlay"></div>
        
<div class="appLoaderContent">
          
<div class="appLoaderContentImg">
<span>Loading content</span>
</div>
        
</div>
      
</div>
      
<div class="Header"><div class="inforTopBanner">    <div class="inforTopBannerLeft">        <span class="inforLogo"></span>        <span class="inforBannerText" style="margin-left:30px;">Infor Security Administration</span>    </div>    <div class="inforTopBannerRight">        <ul class="userInfo">            <li><span id="loggedInUserInfo" class="inforBannerText">User</span><span class="inforToolbarSpacer"></span></li>                        <li id="selectedlanguage"></li>            <li><span class="inforToolbarSpacer"></span></li>            <li><button type="button" class="inforIconButton information" title="Show about page." onclick="showAboutPage()" style="position: relative;top: 4px;"><span></span></button><span class="inforToolbarSpacer"></span></li>                                </ul>        <button type="button" onclick="logout();" title="Sign Out" class="inforIconButton signOut" style="position: relative;top: 5px;"><span></span></button>    </div></div><div id="inforApplicationNavContainer">    <div id='pnlSearchBox' data-qtip="Search">        <input class="inforLookupField" type="text" id="lookupFieldResourceTypes" placeholder="Select resource types" title="Select resource types"/>         <input class="inforSearchField" type="text" placeholder="Search..." id="searchResourceTypes" title="Search Items">        </div>    <div id="inforApplicationNav" onclick="adjustZindex()" class="inforApplicationNav" style="height: 42px; overflow: hidden;"></div>    </div></div>
      
<div id="js_extjs_content"></div>
      
<div class="appContent" id="js_AppContent">
        
        <div id="js_pg_Main">
        
<div class="pageName"></div>
        
<div id="dbcontainer">
            
<div class="inforApplicationPadding" id="dashboard">
                
<div id="dbCardCategory"></div>
                
<div class="inforApplicationPadding" id="dbCardModules">                    
                
</div>
            
</div>
        
</div>
    
</div>

        
      </div>
      
<div class="clearfooter"></div>
    
</div>
<div class="inforBottomFooter" id="footer"><span class="inforBannerText">Infor Security Administration</span></div>
</body></html>

**Comment by kingthorin** [comment]
@thc202 Thanks, I'm good with that.

@skbatoi thanks for the details. I'll start working on a fix.

**Comment by kingthorin** [comment]
Sorry this is taking so long. I do have the code changes together. Just need to mockup some text content, test, and push the code. Hope to knock off remaining activities this week.

**Comment by kingthorin** [comment]
Ok I finally got some test content mocked up and started testing this. Now I've got an implementation question for everyone. 

The new code allows a single resource (URI) to subject to multiple conditions. In a single URL is subject to more than one condition do you feel it's best to:
1) Put in a placeholder or dummy parameter or attack value in order to differentiate alerts.
2) Have the alerts implement distinct names (per condition). 

Currently 'Other Info' is customized per occurrence/condition. The reason one of the two above is required is that the later (newer) finding ends up clobbering the existing one if names match and there is no distinguishing attack or parameter.

For reference the possible conditions handled are:
* header_metacontentype_mismatch = The header and meta content type charset declaration don't match.
* header_metacharset_mismatch = The header and meta charset declaration don't match.
* metacontenttype_metacharset_mismatch = Both meta content type charset and meta charset exist, but don't match each other. (Only detected at High threshold).
* no_mismatch_metacontenttype_missing = The header and meta charset match but there isn't a meta content type charset declaration which may overlook older clients. (Only detected at High threshold).

**Comment by kingthorin** [comment]
I decided to go with option 2.

**Comment by thc202** [comment]
Option 2 seems better, it's more evident that's reporting different (but related) issues.

While testing the changes I noticed an issue with the merge of the alerts in the report, we need to tweak that to also look at the alert name (not just the plugin ID) for proper alert differentiation. [1]
This affects other scanners too.

[1] https://github.com/zaproxy/zaproxy/blob/9ba9351ce72c9b4e04c4943d8708599f7e19ce14/src/org/zaproxy/zap/extension/alert/ExtensionAlert.java#L708-L710

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions@6428027960d3e85438c7f112ff8f867c6bb842b1.
