### ISSUE TITLE
Query Session Location via API

### ISSUE THREAD

**Issue by Harinus** [zaproxy/zaproxy#1967]
Missing: http://localhost:8080/UI/core/view/sessionLocation/
to display the full path of of the current session.

The value is already used in the GUI:
https://github.com/zaproxy/zaproxy/blob/2.4/src/org/parosproxy/paros/view/SessionGeneralPanel.java#L139

Needed for moving the session into a FTP directory after automated scan.

**Comment by kingthorin** [comment]
Fixed in https://github.com/zaproxy/zaproxy/pull/1968
