### ISSUE TITLE
Why zap find can not spider WebGoat 6.0.1 menu URLs

### ISSUE THREAD

**Issue by xuyun1976** [zaproxy/zaproxy#1979]
I want to use zap to PEN test the WebGoat 6.0.1. However, it just spider a few URLs. All of the menu URLs look like http://localhost:8080/WebGoat/attack?Screen=xx&menu=xx. Using the Ajax spider, I can see all the menus are navigated one by one in Firefox, but it only find the menu URL http://localhost:8080/WebGoat/attack?Screen=32&menu=5.

Could you tell me how to improve the spider results?

**Comment by kingthorin** [comment]
Use the standard spider?

**Comment by psiinon** [comment]
I seem to recall that WebGoat was specificity written to make if difficult to use automated tools against it ;)
However I'd still love ZAP to be able to cope with all apps, including WebGoat.
How are you telling that the Ajax Spider only finds just one URL? 
From the URL it looks like its a 'single page app' which means that you'll need to add the app to a context and then define 'Screen' (and maybe 'menu'?) as Structural Parameters (ie parameters that help define the structure of the app).
Then you'll need to rescan it and hopefully you'll see more nodes in the Sites tree

**Comment by Harinus** [comment]
I am facing the same issue.. Webgoat is indeed a single page app with "Screen=xx" and "menu=xx" defining the content. Even with defined Structural Parameters ZAP wont find any other values for those variables expect the default (32,5). The ajaxSpider though, sees all menu nodes and opens the dropdown but never clicks the items inside the dropdown ( or at least not successfully) Thats why xujun1976 cant find any other menu URLs

**Comment by thc202** [comment]
@Harinus was the option "Click elements once" selected? That might explain why the AJAX spider didn't click the items in the dropdown.

**Comment by Harinus** [comment]
@thc202 Disabling "Click elements once" results in an endless loop of reloading the landing page..

Here is a snippet of the WebGoat Menu if you want to have a detailed look on it: 1) Closed 2) Open

```
<li class="sub-menu ng-scope" ng-repeat="item in menuTopics">
	<a ng-click="accordionMenu(item.id)" href=""><i class="fa fa-angle-right pull-right"></i><span class="ng-binding">Introduction</span></a><!-- expanded = !expanded-->
	<ul style="display: block;" class="slideDown lessonsAndStages " id="Introduction" isopen="1">
		<!-- ngRepeat: lesson in item.children --><li ng-repeat="lesson in item.children" class="">
			<a ng-click="renderLesson(lesson.id, lesson.link, {showSource: lesson.showSource, showHints: lesson.showHints})" id="HowtoworkwithWebGoat" class="" title="link to How to work with WebGoat" href="">How to work with WebGoat</a><span class="glyphicon glyphicon-check lessonComplete"></span>
			<!-- ngRepeat: stage in lesson.children -->
		</li><!-- end ngRepeat: lesson in item.children --><li ng-repeat="lesson in item.children" class="">
			<a ng-click="renderLesson(lesson.id, lesson.link, {showSource: lesson.showSource, showHints: lesson.showHints})" id="TomcatConfiguration" class="" title="link to Tomcat Configuration" href="">Tomcat Configuration</a><span class="glyphicon glyphicon-check lessonComplete"></span>
			<!-- ngRepeat: stage in lesson.children -->
		</li><!-- end ngRepeat: lesson in item.children --><li ng-repeat="lesson in item.children" class="">
			<a ng-click="renderLesson(lesson.id, lesson.link, {showSource: lesson.showSource, showHints: lesson.showHints})" id="UsefulTools" class="" title="link to Useful Tools" href="">Useful Tools</a><span class="glyphicon glyphicon-check lessonComplete"></span>
			<!-- ngRepeat: stage in lesson.children -->
		</li><!-- end ngRepeat: lesson in item.children --><li ng-repeat="lesson in item.children" class="">
			<a ng-click="renderLesson(lesson.id, lesson.link, {showSource: lesson.showSource, showHints: lesson.showHints})" id="HowtocreateaLesson" class="" title="link to How to create a Lesson" href="">How to create a Lesson</a><span class="glyphicon glyphicon-check lessonComplete"></span>
			<!-- ngRepeat: stage in lesson.children -->
		</li><!-- end ngRepeat: lesson in item.children -->
	</ul>
</li>
```
```
<li class="sub-menu ng-scope" ng-repeat="item in menuTopics">
	<a ng-click="accordionMenu(item.id)" href=""><i class="fa fa-angle-right pull-right"></i><span class="ng-binding">Introduction</span></a><!-- expanded = !expanded-->
	<ul class="slideDown lessonsAndStages " id="Introduction" isopen="0">
		<!-- ngRepeat: lesson in item.children --><li ng-repeat="lesson in item.children" class="">
			<a ng-click="renderLesson(lesson.id, lesson.link, {showSource: lesson.showSource, showHints: lesson.showHints})" id="HowtoworkwithWebGoat" class="" title="link to How to work with WebGoat" href="">How to work with WebGoat</a><span class="glyphicon glyphicon-check lessonComplete"></span>
			<!-- ngRepeat: stage in lesson.children -->
		</li><!-- end ngRepeat: lesson in item.children --><li ng-repeat="lesson in item.children" class="">
			<a ng-click="renderLesson(lesson.id, lesson.link, {showSource: lesson.showSource, showHints: lesson.showHints})" id="TomcatConfiguration" class="" title="link to Tomcat Configuration" href="">Tomcat Configuration</a><span class="glyphicon glyphicon-check lessonComplete"></span>
			<!-- ngRepeat: stage in lesson.children -->
		</li><!-- end ngRepeat: lesson in item.children --><li ng-repeat="lesson in item.children" class="">
			<a ng-click="renderLesson(lesson.id, lesson.link, {showSource: lesson.showSource, showHints: lesson.showHints})" id="UsefulTools" class="" title="link to Useful Tools" href="">Useful Tools</a><span class="glyphicon glyphicon-check lessonComplete"></span>
			<!-- ngRepeat: stage in lesson.children -->
		</li><!-- end ngRepeat: lesson in item.children --><li ng-repeat="lesson in item.children" class="">
			<a ng-click="renderLesson(lesson.id, lesson.link, {showSource: lesson.showSource, showHints: lesson.showHints})" id="HowtocreateaLesson" class="" title="link to How to create a Lesson" href="">How to create a Lesson</a><span class="glyphicon glyphicon-check lessonComplete"></span>
			<!-- ngRepeat: stage in lesson.children -->
		</li><!-- end ngRepeat: lesson in item.children -->
	</ul>
</li>
```

**Comment by thc202** [comment]
That menu shouldn't be a problem to AJAX spider.

Which browser/version are you using? How many browser windows did you choose?
How much time did you leave the AJAX spider crawling the site?

The behaviour that you are seeing might be normal since it's crawling the elements more than once and it's also how the AJAX spider works, it will follow the crawling steps in sequence to reach a previously state found, that means, in this case, opening the main page again (and again) to click the (new) menus.

**Comment by Harinus** [comment]
Firefox 42, 1 Window, about 5 minutes.
I agree that i might see the main page several times but it does not open even one sub page in the mean time (visible in the browser and the AJAX Spider log) 
With the option Click elements once = Enabled:
The Sub menus get opended, but none of the sub pages opened
With the option Click elements once = Disables:
Endless main page loop

**Comment by kingthorin** [comment]
Is this still an issue?

**Comment by kingthorin** [comment]
No further input in almost 2months, closing.
