### ISSUE TITLE
 Invalid or missing API key

### ISSUE THREAD

**Issue by kamiNaranjo** [zaproxy/zaproxy#1982]
Good afternoon.

Excuseme if my question was answered before but I don't find nothing about it. I try to use the api ZAP and for starting I try to do this example: https://github.com/zaproxy/zaproxy/blob/develop/src/org/zaproxy/clientapi/core/SimpleExample.java but when I try to do it I get this Exception: org.zaproxy.clientapi.core.ClientApiException: Invalid or missing API key. 

In other issues I found that the API Key don't is necesary, but I don´t know how solve this problem.

Thanks for your help.

**Comment by kingthorin** [comment]
https://github.com/zaproxy/zaproxy/wiki/FAQapikey

**Comment by kamiNaranjo** [comment]
Thank you so much. This is the information that I try to find.
