### ISSUE TITLE
Alerts API should always return 'evidence' (and all other keys)

### ISSUE THREAD

**Issue by tbach** [zaproxy/zaproxy#1984]
First noticed when upgrading automation from ZAP 2.3.1 to 2.4.x.

In the past (and in most cases in 2.4.x) when ZAP's API returns alerts, if keys like 'evidence' do not have any data they are returned as an empty string. In 2.4.x, certain alerts seem to not include the 'evidence' key if there is no data. This may affect other keys as well, but this is the one I've noticed.

In example below, note that the first several alerts include an empty value for the evidence key whereas the final output does not include the evidence key at all. This seems to affect at least alert 10015 (Incomplete or no cache-control and pragma HTTPHeader set).

Expected behavior: All alert keys are returned in each alert dict with empty string values if they are not present in the alert. This allows automation to assume dict structure.

Ex:

> > > for alert in zap.core.alerts():
> > > ...     print alert
> > > ...     print alert['evidence']

{u'description': u"The Anti-MIME-Sniffing header X-Content-Type-Options was not set to 'nosniff'. This allows older versions of Internet Explorer and Chrome to perform MIME-sniffing on the response body, potentially causing the response body to be interpreted and displayed as a content type other than the declared content type. Current (early 2014) and legacy versions of Firefox will use the declared content type (if one is set), rather than performing MIME-sniffing.", u'url': u'https://demo.testfire.net', u'other': u'This issue still applies to error type pages (401, 403, 500, etc) as those pages are often still affected by injection issues, in which case there is still concern for browsers sniffing pages away from their actual content type.\nAt "High" threshold this scanner will not alert on client or server error responses.', u'reference': u'http://msdn.microsoft.com/en-us/library/ie/gg622941%28v=vs.85%29.aspx\nhttps://www.owasp.org/index.php/List_of_useful_HTTP_headers', u'solution': u"Ensure that the application/web server sets the Content-Type header appropriately, and that it sets the X-Content-Type-Options header to 'nosniff' for all web pages.\nIf possible, ensure that the end user uses a standards-compliant and modern web browser that does not perform MIME-sniffing at all, or that can be directed by the web application/web server to not perform MIME-sniffing.", u'param': u'', u'confidence': u'Medium', u'alert': u'X-Content-Type-Options Header Missing', u'evidence': u'', u'messageId': u'1', u'wascid': u'15', u'id': u'5', u'cweid': u'0', u'attack': u'', u'risk': u'Low'}

{u'description': u"X-Frame-Options header is not included in the HTTP response to protect against 'ClickJacking' attacks.", u'url': u'https://demo.testfire.net', u'other': u'At "High" threshold this scanner will not alert on client or server error responses.', u'reference': u'http://blogs.msdn.com/b/ieinternals/archive/2010/03/30/combating-clickjacking-with-x-frame-options.aspx', u'solution': u"Most modern Web browsers support the X-Frame-Options HTTP header. Ensure it's set on all web pages returned by your site (if you expect the page to be framed only by pages on your server (e.g. it's part of a FRAMESET) then you'll want to use SAMEORIGIN, otherwise if you never expect the page to be framed, you should use DENY.  ALLOW-FROM allows specific websites to frame the web page in supported web browsers).", u'param': u'', u'confidence': u'Medium', u'alert': u'X-Frame-Options Header Not Set', u'evidence': u'', u'messageId': u'1', u'wascid': u'0', u'id': u'6', u'cweid': u'0', u'attack': u'', u'risk': u'Medium'}

{u'description': u'The cache-control and pragma HTTP header have not been set properly or are missing allowing the browser and proxies to cache content.', u'url': u'https://demo.testfire.net/robots.txt', u'other': u'', u'reference': u'https://www.owasp.org/index.php/Session_Management_Cheat_Sheet#Web_Content_Caching', u'solution': u'Whenever possible ensure the cache-control HTTP header is set with no-cache, no-store, must-revalidate, private; and that the pragma HTTP header is set with no-cache.', u'param': u'', u'confidence': u'Medium', u'alert': u'Incomplete or No Cache-control and Pragma HTTP Header Set', u'cweid': u'525', u'messageId': u'6', u'wascid': u'0', u'id': u'7', u'attack': u'', u'risk': u'Low'}
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
KeyError: 'evidence'

> > > exit()

**Comment by kingthorin** [comment]
I've validated that there is a discrepancy with this. If [evidence returned is null](https://github.com/zaproxy/zaproxy/blob/2887f86fc7d0f4b74c31898dfabb52a432af17ad/src/org/zaproxy/zap/extension/api/CoreAPI.java#L1408) it isn't included. I verified this by listing 100 alerts, in which I encountered 70 occurrences of "evidence", when I changed that line to `String.valueOf(alert.getEvidence())` then I got 100 occurrences of "evidence" in my results (30 occurrences of "null").

Going forward we probably don't want "null" but rather just an empty string. But at last this identifies there where and the cause.

I checked through 100 alerts and only found `evidence` impacted, I then did a second set and found 2 occurrences of `attack` impacted. After that I went through a third set that confirmed the same but didn't reveal anything further.

Something like: `map.put("evidence", alert.getEvidence() == null ? "" : alert.getEvidence() );` might also be a workable solution.

**Comment by kingthorin** [comment]
So this can be handled in the API as mentioned above, however, I've been wondering if it would be better handled in the `Alert` class itself. Currently all the setElement type methods just return if the value being passed is null, I suggest that as per above we check null and set empty string instead.

Thoughts?

**Comment by thc202** [comment]
You mean for all setters or just for attack/evidence? I'm fine either way, but if the former we need to check if core or the add-ons are setting null values and tweak accordingly.
We still need to change CoreAPI to return always the `messageId`.

**Comment by kingthorin** [comment]
I hadn't decided one way or the other, just wanted to get the discussion started. 

There are definitely addons (rules) that set nulls for some elements when creating alerts. I guess they can be aligned to send empty strings, but I figured handling it centrally would work for those and for future cases as well.

**Comment by thc202** [comment]
Right, was not worried about the "bingo" methods but direct calls to the setters, probably we don't have any setting nulls (which would have a different behaviour if all the alert setters are changed to handle null as empty string).

**Comment by kingthorin** [comment]
Ok I see what you're getting at. I'll try to search around for direct use of the setters.

It looks like Eclipse has some functionality for finding references, so if I leverage that for each method do you think that provides good enough coverage?

**Comment by kingthorin** [comment]
Also am I missing something in this ticket or is there another one about the `messageId` being missing? Or is that something you've observed?

Don't mind tackling it but need to understand how/where it's happening.

**Comment by thc202** [comment]
Yeah, that should be enough.

That might happen but just on corner cases (e.g. an alert raised on a temporary message), I don't think there's any code change needed other than always add the field.

**Comment by kingthorin** [comment]
Oh it looks like it's this:
https://github.com/zaproxy/zaproxy/blob/develop/src/org/zaproxy/zap/extension/api/CoreAPI.java#L1481-L1483

Do we want to set `0` or `-1` for those edge cases? Because if there isn't a history ref (or if it's a temp message and the session is re-opened) there isn't a message to associate right?

**Comment by thc202** [comment]
Right. Maybe leave it empty? It does not need to be a number.

**Comment by kingthorin** [comment]
K

**Comment by kingthorin** [comment]
Using Eclipse references checking across ZAP and the extensions none of the following had occurences of specifically setting null: `setName`, `setURI`, `setDescription`, `setParam`, `setOtherInfo`, `setSolution`, `setReferences`, `setAttack`, `setEvidence`, `setCweId`, and `setWascId`.
