### ISSUE TITLE
Can't scan ".pw" TLD domains?

### ISSUE THREAD

**Issue by jjgh** [zaproxy/zaproxy#1994]
Is this a known problem already? I can't get to scan ".pw" TLD domains.
Maybe this is because some new GTLDs have not been set to be accepted in ZAP, yet?
Using Zap 2.4.2 on Windows 7.

**Comment by psiinon** [comment]
I dont think so - ZAP shouldnt be restricting access to any TLDs.
Can you proxy through ZAP to get to such sites?
What do you actually see?
Are any errors logged?

Cheers

**Comment by jjgh** [comment]
I'm sorry, I must have tried with a particularly "weird" domain, because I just tested with some other ".pw" domains and Zap works 'em out correctly..

**Comment by psiinon** [comment]
No problem - thanks for letting us know, and do let us know if you hit other 'weird' sites ;)

**Comment by jjgh** [comment]
;) will do :D
