### ISSUE TITLE
Htmlunit - Invalid selector

### ISSUE THREAD

**Issue by iammyr** [zaproxy/zaproxy#1997]
When running ZAP's Ajax Scan against the OWASP benchmark, choosing htmlunit as browser, I get the following error logged:

ERROR com.gargoylesoftware.htmlunit.javascript.StrictErrorReporter - runtimeError: message=[An invalid or illegal selector was specified (selector: ':checked' error: Invalid selector: *:checked).] sourceName=[https://localhost:8443/benchmark/js/jquery.min.js] line=[2] lineSource=[null] lineOffset=[0]
TypeError: Cannot find function addEventListener in object [object HTMLDocument]. (https://localhost:8443/benchmark/js/jquery.min.js#2)

**Comment by kingthorin** [comment]
@iammyr is this still happening with up-to-date versions of both ZAP  and the Benchmark?

**Comment by kingthorin** [comment]
Will close on AR after 20160407 if nothing further received.

**Comment by kingthorin** [comment]
Closing - InsufficientEvidence
