### ISSUE TITLE
Disabling all scanners through API does not seem to work

### ISSUE THREAD

**Issue by yannicsmeets** [zaproxy/zaproxy#2002]
Steps to reproduce the issue:
1. Run ZAP (2.4.2);
2. Call the ascan/disableAllScanners() function from the API;
3. Run a scan on a website;

In the GUI, you can see all scanners are running while the API claims all scanners are disabled (with the function ascan/scanners())

**Comment by thc202** [comment]
Closing as duplicate of #1893.
