### ISSUE TITLE
./zap.sh: 107: ./zap.sh: Syntax error: "(" unexpected (expecting "fi")

### ISSUE THREAD

**Issue by tayfunyasar** [zaproxy/zaproxy#2004]
Getting an error about jvm heap size.

tayfunyasar@tayfunyasar-PC:~/Development/ZAP_2.4.2$ sh ./zap.sh
Found Java version 1.7.0_80
Available memory:  11932 MB
Setting jvm heap size: -Xmx512m
./zap.sh: 107: ./zap.sh: Syntax error: "(" unexpected (expecting "fi")
tayfunyasar@tayfunyasar-PC:~/Development/ZAP_2.4.2$

how can i fix this?

**Comment by kingthorin** [comment]
What OS?
Are you trying to run ZAP from source or do you have it installed?

**Comment by psiinon** [comment]
Why are you calling it with "sh" ?
zap.sh is a bash script - calling it with sh will not work.
Just call "./zap.sh" - if it doesnt have execute perms then just do "chmod u+x zap.sh"

**Comment by venkatsubrahmanyam6119** [comment]
My code in Git: 
- chmod u+x ZAP_2.8.0/zap.sh
- ./ZAP_2.8.0/zap.sh -daemon -dir $(pwd) && python3 scan.py

scan.py has the shutdown call but the Linux box only says "ZAP is now listening on localhost:8080"

How do I make it shutdown?

**Comment by thc202** [comment]
Are you waiting for ZAP to start before issuing the shutdown call? Please, use https://groups.google.com/group/zaproxy-users for questions.
