### ISSUE TITLE
Owasp Zap blocks HTTPS acccess

### ISSUE THREAD

**Issue by fireflydt** [zaproxy/zaproxy#2013]

**Comment by fireflydt** [comment]
Using windows 10 and chrome Version 46.0.2490.80 m
Current version of OWASP ZAP.as a proxy server
Attempt to Connect to https sites result in :

in the address bar https has a red line through it
and the error message is:
"Your connection is not private

Attackers might be trying to steal your information from adclick.g.doubleclick.net (for example, passwords, messages or credit cards). NET::ERR_CERT_AUTHORITY_INVALID
Automatically report details of possible security incidents to Google. Privacy policy
ReloadHide advanced
adclick.g.doubleclick.net normally uses encryption to protect your information. When Chrome tried to connect to adclick.g.doubleclick.net this time, the website sent back unusual and incorrect credentials. Either an attacker is trying to pretend to be adclick.g.doubleclick.net, or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Chrome stopped the connection before any data was exchanged.

You cannot visit adclick.g.doubleclick.net right now because the website uses HSTS. Network errors and attacks are usually temporary, so this page will probably work later."

**Comment by psiinon** [comment]
Have you imported the ZAP root cert as a trusted CA certificate?
https://github.com/zaproxy/zap-core-help/wiki/HelpStartProxies

**Comment by fireflydt** [comment]
Hello psiion

I now understand about the certificate but have not imported it.    I do not know how to create or acquire the certificate.  However, the following site seems to provide a solution, please advise.
http://datacenteroverlords.com/2012/03/01/creating-your-own-ssl-certificate-authority/

Regards
firefltdt

**Comment by kingthorin** [comment]
https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsOptionsDynsslcert#generate

**Comment by psiinon** [comment]
ZAP automatically generates a unique CA certificate for you when it first starts up, so you dont need to generate a new one.
But you do need to import it as per the user guide link I gave.

**Comment by YIYIZH** [comment]
Hi Simon, I wanna ask if it is possible to get the zap certificate by command line. I installed zap in a remote server, where I can only access by ssh. However, I don't know how to generate the certificate  by command line, I need to import the certificate to java keystore. Is it something possible?

**Comment by kingthorin** [comment]
You can get it from the API: http://127.0.0.1:8080/UI/core/other/rootcert/

You could use `wget` or `curl` if the apikey is enabled you'll have to provide it, but it's a simple get request.

**Comment by YIYIZH** [comment]
Thank you kingthorin, it is working!

**Comment by arif1999** [comment]
@kingthorin  :  http://127.0.0.1:8080/UI/core/other/rootcert/
I am getting 500 for the api's to get certi .What does that mean ?
Can you please

**Comment by kingthorin** [comment]
What version of ZAP?

Did you provide the API key? https://github.com/zaproxy/zaproxy/wiki/FAQapikey

**Comment by reginabecker** [comment]
Menu Ferramentas Opcoes Certificados ssl dinamicos Clique em Salvar
