### ISSUE TITLE
ZAP API not responding -MWOS 2015

### ISSUE THREAD

**Issue by amandhapola** [zaproxy/zaproxy#2015]
After  proxying 50,000  websites for the MWOS project , The API stops responding . I am using ZAP in daemon mode with lowmem setting. I have disabled all  passive scan rule except with rule id 10040 (for mixed content).I am using python for scripting.

**Comment by psiinon** [comment]
Can you share your scripts with us somehow?
So we can reproduce the problem :)

**Comment by psiinon** [comment]
Ah, you've already sent them to me directly - many thanks!

**Comment by kingthorin** [comment]
@psiinon if this is still an issue could you attach the scripts?

**Comment by kingthorin** [comment]
Can this be closed?

**Comment by psiinon** [comment]
I suspect its still an issue - I'll try to dig out the scripts when I have some time :/

**Comment by kingthorin** [comment]
@psiinon any luck?

**Comment by psiinon** [comment]
Think it can be closed. We'll need to do a load of testing like this for ZaaS anyway..
