### ISSUE TITLE
Choose a unique port in the GUI if theres a clash

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#2016]
If the default port (8080) or the one selected is not available on start up then show a prompt for a new port and suggest the first free port above the current one.
The dialog should check the selected port is available.
In daemon mode ZAP should quit if the port isnt available, showing a suitable error message

**Comment by kingthorin** [comment]
Do we want to check the binding address, and remind/warn the user if it's not loop local?

Also need to handle binding errors for 0.0.0.0 specification....not sure how that plays out. If you've specified 0.0.0.0 and it can bind to something does it stay happy? (Even if the user can't bind to or use it on localhost:8080 or whatever they "normally" expect...)
