### ISSUE TITLE
ZAP API call to check the API key

### ISSUE THREAD

**Issue by abdellah2013** [zaproxy/zaproxy#2021]
Hi,

I'm wandering if it is possible to implement an API call that checks the API key given by the user.

It's just for user experience. I'm dealing with the ZAP jenkins plugin that let the user specify the API key.

Thanks in advance.

Cheers?
Abdellah AZOUGARH

**Comment by thc202** [comment]
I think it's OK to close the issue with the latest changes/versions. This can now be achieved (by default [1]) with any view (e.g.`/core/view/version/`). Thoughts?

[1] https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsOptionsApi

**Comment by kingthorin** [comment]
Agreed

**Comment by thc202** [comment]
Closing, per previous comments.
