### ISSUE TITLE
Allow to set client certificate (PKCS#12) through the ZAP API

### ISSUE THREAD

**Issue by hxd86** [zaproxy/zaproxy#2023]
Although some methods in javadoc such as setClientCertLocation(String clientCertLocation) and isUseClientCert() indicate ZAP is able to add/select client certificates with API, it is not possible to do it. 

This is related to discussion at https://groups.google.com/d/msg/zaproxy-users/7bh-zVzzGHw/FTcBUWksDgAJ

**Comment by MJUi** [comment]
The command line doesn't allow specifying a client certificate either.

Related to this question : https://groups.google.com/forum/#!topic/zaproxy-users/WyBc0vbIjPc

**Comment by adrianbarton** [comment]
Additionally, ZAP is not able to pick up/load certificates passed in at runtime e.g. using -Djavax.net.ssl.keystore.

**Comment by victorbordo** [comment]
@thc202 Has anyone expressed interest in adding this functionality to the API recently?

**Comment by sbrawner** [comment]
ME!

**Comment by kingthorin** [comment]
@sbrawner Great we'll watch for your PR

**Comment by sbrawner** [comment]
wait I meant I'd be interested in _having_ this functionality

**Comment by kingthorin** [comment]
Awwwwww. Ok. Thanks for clarifying.

Though we are happy to accept contributions 👍 😁

**Comment by Calbrilliant** [comment]
@kingthorin I've been looking into this and it seems like this functionality was purposefully disabled. Any idea why?

**Comment by thc202** [comment]
@victorbordo not that I'm aware of.

@Calbrilliant which functionality specifically?

**Comment by Calbrilliant** [comment]
The use of client certs. at least according my understanding of the following snippet in zaproxy/src/org/parosproxy/paros/extension/option/OptionsParamCertificate.java
```
        // always turn off client cert
        setUseClientCert(false);
        setClientCertLocation("");
```

**Comment by thc202** [comment]
That's because the cert options are not persisted (e.g. pin/pass, active cert...), it does not mean the cert functionality is disabled.

**Comment by thc202** [comment]
@Calbrilliant if you are interested in working on this issue we can help/guide with what/where needs to be one.

**Comment by Calbrilliant** [comment]
From what i can see that snippet prevents it from parsing any of the commandline options I am parsing. I would like to work on this issue, so your guidance would definitely be appreciated.

**Comment by thc202** [comment]
Which command line options? If you want to add support through the command line (`-config` arg?), yes, that needs to be adjusted.

Great! Which part(s) of the issue do you want address? Command line, ZAP API or both? (We could split this into other issue(s), e.g. just for command line if that's what you are interested most.)

**Comment by Calbrilliant** [comment]
I've been looking into it using the -config arg, but I would like to eventually work both components.

**Comment by ziogibom** [comment]
@Calbrilliant any progress on that?

**Comment by kingthorin** [comment]
I’ve got this working (to set/enable a cert from the web API) however I can’t get it playing nicely with the GUI. I’ll push the code to my repo later today or sometime tomorrow but I might need a hand with the GUI issue(s).
