### ISSUE TITLE
zaproxy closes Kali2 session since jde update

### ISSUE THREAD

**Issue by Random1984** [zaproxy/zaproxy#2024]
Zaproxy makes a "screen flash" and it turns back into Kali Sana login. Issue replicates in a VMware machine over Win7 0day updated and in a Kali Sana laptop x86 host SO.
Is anybody else having this issue? Did I make a mistake in both systems?
Thanks.

**Comment by psiinon** [comment]
No idea :/
Might be worth raising a Kali issue for this? They maintain their own ZAP packages, based on ours of course.

**Comment by Random1984** [comment]
I didn't try in a Debian machine yet, but it looks like a Gnome crash.
I'll keep trying&testing.

**Comment by Random1984** [comment]
I don't know what happened, but everything runs OK on a fresh Kali installation. I think i misconfigurated something.
Thanks a lot.

**Comment by josuegj** [comment]
R

On Friday, November 6, 2015, Random1984 <notifications@github.com> wrote:

> Closed #2024 <https://github.com/zaproxy/zaproxy/issues/2024>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zaproxy/zaproxy/issues/2024#event-456990526>.
>


--

**Comment by psiinon** [comment]
Thanks for letting us know
