### ISSUE TITLE
ZAP authentication  question

### ISSUE THREAD

**Issue by xuyun1976** [zaproxy/zaproxy#2029]
I use ZAP API to test online bank (http://http://zero.webappsecurity.com/). I meet an authentication issue.

Here is information:

login URL : http://zero.webappsecurity.com/signin.html
Payload : user_login=username&user_password=password&submit=Sign+in&user_token=ed15210c-8c6b-4c56-912d-f3247cea997d

However the user_token is come from (a hidden value) the page http://zero.webappsecurity.com/login.html

My question is how can I get the user_token in http://zero.webappsecurity.com/login.html page, and then use the user_token to send a login POST request 

Thanks a lot!

**Comment by psiinon** [comment]
Hopefully the easiest option is a Zest script.
Zest can extract tokens from responses and then submit them in future requests.
Try configuring user_token as a anti CSRF token, then going to the login page and signing in.
Then add those requests to a new Zest script.
If everythings set up correctly then the Zest script should include the relevant commands to extract and use the token in the right place.
If that all works then please submit your script to the community-scripts repo: https://github.com/zaproxy/community-scripts - it would be great to build up a set of authentication scripts for well known vulnerable apps :)

**Comment by xuyun1976** [comment]
Hi psiinon, 
Thanks a lot :). I will try to use script.
