### ISSUE TITLE
Wiki article showing owasp top 10 for zap passive scan and passive scanners not coinciding with the OWASP Top 10

### ISSUE THREAD

**Issue by ambikashri** [zaproxy/zaproxy#2031]
According to the wiki article "https://www.owasp.org/index.php/ZAPpingTheTop10", passive scan can help find OWASP Top 10's A5, A6, A8 and A9. Using the view scanners of pscan i have mapped a few of the alerts to the OWASP top 10. But I am unable to find out A6, A8 and A9 . 

```
Script passive scan rules	 -> OWASP Top 10?
Application Error Disclosure-> A6
Incomplete or No Cache-control and Pragma HTTP Header Set	-> OWASP Top 10?
Content-Type Header Missing	 -> OWASP Top 10?
Cookie No HttpOnly Flag	-> A3
Cookie Without Secure Flag ->A3
Cross-Domain JavaScript Source File Inclusion ->A3
Web Browser XSS Protection Not Enabled -> A5
Secure Pages Include Mixed Content -> OWASP Top 10?	
Password Autocomplete in Browser -> A2
Private IP Disclosure -> OWASP Top 10?
Session ID in URL Rewrite -> A2
X-Content-Type-Options Header Missing -> A3
X-Frame-Options Header Not Set ->A3
```
My question is am I missing some passive scanners? And also the scanners for which the OWASP top 10 isn't mentioned how do we find to which category they belong to because our aim to cover the OWASP Top 10.

**Comment by kingthorin** [comment]
Note the mapping you linked includes the relevant quality packages that include scanners with coverage for a given top 10 item. By default ZAP is packaged/distributed with only 'release' quality scanners/rules. For full coverage based on the linked article you will need to visit the ZAP market place and grab the 'alpoha', and 'beta' quality scanner packages.

https://mobile.twitter.com/zaproxy/status/654246475078205442
http://zaproxy.blogspot.ca/#Tutorial
https://github.com/zaproxy/zap-extensions/wiki/AddOn_pscanrules
https://github.com/zaproxy/zap-extensions/wiki/HelpAddonsPscanrulesBetaPscanbeta
https://github.com/zaproxy/zap-extensions/wiki/HelpAddonsPscanrulesAlphaPscanalpha
