### ISSUE TITLE
Import API endpoints defined using swagger / openapis

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#2034]
see http://swagger.io/ and https://openapis.org/

**Comment by alienatix** [comment]
@psiinon ability to import API definition to be able to automate scanning of API endpoints would be great! Do you have any idea when it can be added to zap?

**Comment by psiinon** [comment]
We can already import WSDL definitions via the 'SOAP Scanner' add-on on the ZAP Marketplace.
We dont have anything similar for REST services yet :(
What definitions do you think we should support?

**Comment by kingthorin** [comment]
ADL for REST?

**Comment by alienatix** [comment]
@psiinon for REST APIs I think the swagger (which recently reborn as Open API Definition Format (OADF)) is de-facto standard, so having it in ZAP would add a significant value. RAML is also used widely, but it's possible to convert from one definition to another using such tools as API Transformer

**Comment by psiinon** [comment]
Theres also http://json-schema.org/

**Comment by staticeffect** [comment]
I think supporting OAS 1.2/2.0 would be a big one for me.

**Comment by kingthorin** [comment]
Could you be more specific?

**Comment by psiinon** [comment]
I've just attached a project written by some students: Joanna Bona, Artur Grzesica, Michal Materniak and Marcin Spiewak. They've kindly granted us their permission to use it in ZAP and release it under the Apache v2 license.
This is a stand alone tool which takes a URL for an OpenAPI definition and issues the relevant requests to explore it. It can be easily proxied and works well with ZAP.
It should be easy to wrap this in a ZAP extension - I'll do that myself at some point unless anyone beats me to it :)



[rest-extension.zip](https://github.com/zaproxy/zaproxy/files/279394/rest-extension.zip)

**Comment by sdavis-r7** [comment]
Please support OAS 2.0 (swagger) as import!  It is (my 2 cents) better that WADL, RAML, or api-blueprint (and hey, you can convert to swagger from those too).  Having it in AppSpider increasingly makes scanning API's a breeze like they should be.  :)  (slides from last nights owasp here in PDX: http://www.slideshare.net/ScottLeeDavis/owasp-pdx-may-2016-scanning-with-swagger-oas-20 )

**Comment by rompic** [comment]
+1

**Comment by tlenaic** [comment]
+1

**Comment by psiinon** [comment]
[PR 765 ](https://github.com/zaproxy/zap-extensions/pull/765) provides this functionality. You can try it out by downloading the add-on from here: https://github.com/psiinon/zap-extensions/releases/download/openapi/openapi-alpha-1.zap 

I need to make some more changes in order for it to be merged, but I hope to get back to it soon.

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#765. The add-on is already available in the marketplace (for 2.5.0 and 2.6.0).
