### ISSUE TITLE
Linux ZAP 2.4.2 NoSuchMethodError setSerialNumber - Unable to SSL proxy

### ISSUE THREAD

**Issue by nestoru** [zaproxy/zaproxy#2038]
Also a problem with latest build ZAP_D-2015-11-09

Tested from ubuntu 14.04 LTS

15103 [AWT-EventQueue-0] INFO org.parosproxy.paros.control.Control  - New Session
15553 [Thread-7] ERROR org.zaproxy.zap.ZAP$UncaughtExceptionLogger  - Exception in thread "Thread-7"
java.lang.NoSuchMethodError: org.bouncycastle.asn1.x509.V3TBSCertificateGenerator.setSerialNumber(Lorg/bouncycastle/asn1/ASN1Integer;)V
	at org.bouncycastle.cert.X509v3CertificateBuilder.<init>(Unknown Source)
	at org.bouncycastle.cert.X509v3CertificateBuilder.<init>(Unknown Source)
	at org.bouncycastle.cert.jcajce.JcaX509v3CertificateBuilder.<init>(Unknown Source)
	at org.zaproxy.zap.extension.dynssl.SslCertificateUtils.createRootCA(Unknown Source)
	at org.zaproxy.zap.extension.dynssl.ExtensionDynSSL.createNewRootCa(Unknown Source)
	at org.zaproxy.zap.extension.dynssl.ExtensionDynSSL$1.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

**Comment by thc202** [comment]
That might be caused by the presence, in the classpath, of another (incompatible) version of the BouncyCastle library (bcprov) (probably version 1.46, which have a different method signature `setSerialNumber(DERInteger serialNumber)`).
We had a report of a similar issue some time ago:
#618

Removing the offending library from the classpath should fix the issue (if that's really the issue).

**Comment by nestoru** [comment]
Thanks for getting back to me. It was a classpath issue indeed. I guess incorrectly we have been using /opt/jdk/jre/lib/ext/bcprov-jdk16-1.46.jar which should be hosted somewhere else instead of polluting the global lib for the JVM.

Version 2.4.0 was working because the bc versions matched:
ZAP_2.4.0$ ls lib/bc*
bcmail-jdk16-146.jar  bcprov-jdk16-146.jar

But for 2.4.2 a different version is used:
ZAP_2.4.2$ ls lib/bc*
lib/bcmail-jdk15on-152.jar  lib/bcprov-jdk15on-152.jar
lib/bcpkix-jdk15on-152.jar

**Comment by thc202** [comment]
Thanks for letting us know.
