### ISSUE TITLE
Forced Browse hangs after fourth request

### ISSUE THREAD

**Issue by acaetano** [zaproxy/zaproxy#2039]
ZAP 2.4.2, when using dirbuster file directory-list-2.3-big, hangs after third or fourth requests. Current workaround is to use the file with the fuzzer tab.

**Comment by thc202** [comment]
@acaetano might be #559?

**Comment by acaetano** [comment]
Actually, it is.

**Comment by thc202** [comment]
Thanks for letting us know.
