### ISSUE TITLE
ZAP uses commons-collections-3.2.1.jar (use of insecure library)

### ISSUE THREAD

**Issue by ElColmo** [zaproxy/zaproxy#2057]
commons-collections-3.2.1.jar has a serious security vulnerability, and has recently been superceded by commons-collections-3.2.2.jar.  commons-collections versions from 3.0 up to 3.2.1, and 4.x are currently affected.

OWASP ZAP continues to use commons-collections-3.2.1.jar, in both the core, and in extensions.  

Core:
zaproxy/build/zap/lib/commons-collections-3.2.1.jar
zaproxy/lib/commons-collections-3.2.1.jar

Extensions:
zap-extensions/lib/commons-collections-3.2.1.jar
zap-extensions-beta/lib/commons-collections-3.2.1.jar
zap-extensions-alpha/lib/commons-collections-3.2.1.jar

References: 
https://commons.apache.org/proper/commons-collections/release_3_2_2.html
https://issues.apache.org/jira/browse/COLLECTIONS-580
http://foxglovesecurity.com/2015/11/06/what-do-weblogic-websphere-jboss-jenkins-opennms-and-your-application-have-in-common-this-vulnerability/

**Comment by thc202** [comment]
For reference:
https://blog.codecentric.de/en/2015/11/comment-on-the-so-called-security-vulnerability-in-apache-commons-collections/
