### ISSUE TITLE
spider in my device

### ISSUE THREAD

**Issue by grabber24** [zaproxy/zaproxy#2059]
This is curreently a spider within my operating system that a person using chromium thoughT would be funny. Does anyone know the quickest way to kill this spider so that my browser will start running for more than just a couple of minutes?

**Comment by psiinon** [comment]
Is there any particular reason that you think this is the ZAP spider?
The ZAP spider runs in the ZAP process, not in your browser.
If you havnt installed ZAP and are not running a web server on your machine then its very unlikely that ZAP is causing your problems.

**Comment by grabber24** [comment]
Thanks. I am gonna try to find that zapper.
