### ISSUE TITLE
Acitve Scan and Passive scan mentioned in the alerts.xml

### ISSUE THREAD

**Issue by ambikashri** [zaproxy/zaproxy#2062]
The below alerts have been mentioned in https://github.com/zaproxy/zaproxy/blob/develop/src/doc/alerts.xml. I wanted to know, are these alerts or they a way of finding alerts.
50000	Active Scan scripts
50001	Passive Scan scripts

**Comment by ambikashri** [comment]
Even these
50002	Fuzzer HTTP Processor scripts
60000	Example simple passive rule 
60001	Example file passive rule 
60100	Example simple active rule 
60101	Example file active rule

**Comment by thc202** [comment]
The IDs 50000, 50001 and 50002 are set to alerts raised by the corresponding scripts, so the name shown in alerts.xml does not correspond to a name of an alert (that would be set by the script itself, for example, refer to gof_lite.js [1]).
The IDs 60000, 60001, 60100 and 60101 are just example alerts used by the example Java scanners.

[1] https://github.com/zaproxy/community-scripts/blob/8d4b349554f68b3f3925d9b29b7a856b08624730/active/gof_lite.js#L28
