### ISSUE TITLE
How to know that ZAP in daemon mode has loaded

### ISSUE THREAD

**Issue by grubyrychu** [zaproxy/zaproxy#2063]
I am running ZAP in daemon mode from powershell. I need to know when ZAP is fully loaded. Currently I am checking whether the last line of the output is "... Initializing Tips and Tricks" but this does not seem like a perfect solution.

**Comment by psiinon** [comment]
You could poll until you get a connection to the API.
However we've also added a log message like:
INFO org.zaproxy.zap.DaemonBootstrap  - ZAP is now listening on localhost:8090
which would be better than the one you're currently looking at. 
This is in the weekly releases and will be in the next full release.

**Comment by josuegj** [comment]
Ok
