### ISSUE TITLE
How does HTTP sessions work and alerts generated by them

### ISSUE THREAD

**Issue by ambikashri** [zaproxy/zaproxy#2067]
I wanted to know how HTTP sessions works in the ZAP tool. I am using zap version 2.4.2. I started the ZAP tool and logged into the website through the browser. I have opened the Http Sessions tab in the tool and I can just see Session1 under Name column but 'Session Tokens Value and Message Matched column is empty. What are the further steps?
Also like how there is a list of alerts which can be generated through active and passive is there a way to know the alerts which be generated through HTTP sessions?

**Comment by guardian-project** [comment]
third unsibscribe

**Comment by psiinon** [comment]
Have you looked at the help that comes with ZAP for this tab?
Its also online here: https://github.com/zaproxy/zap-core-help/wiki/HelpUiTabsHttpsessions
I cant think of any active or passive rules that use the sessions recorded in this tab.
The main use for the tab is allowing you to view, create and switch between HTTP sessions.

**Comment by ambikashri** [comment]
Hi. I did what was told in the help section previously. I havent noticed anything coming in the sessions tokens values or in the messages matched column. Below are the steps performed by me
- start zap tool
- browse a login page in the browser
- open http session tab
- selected the site in the site field of http sessions.
- logged in to the site the browser as user1(noted down the session id)
-logged out of the site
-logged in as user 2 in the browser(noted down the session id, it differed from the previous session id)
Please let me know where I am going wrong because in all these interactions I didnt notice any change in the Http sessions tab. Also I was thinking the session id shouldn't have changed when I logged in as user2 as I am trying to do it in the same session.

**Comment by ambikashri** [comment]
Also wrt the alerts, I wanted to know are there any specific alerts from the alerts.xml which can be detected other than the passive/active scanners?

**Comment by ambikashri** [comment]
Hi, any solution to this?

**Comment by thc202** [comment]
If your session is not showing in the "Http Sessions" tab then you most likely need to add the session token in the "Http Sessions" options panel \[1]  (or flag it in the "Params" tab [2]).
Session IDs are expected to change in that case. [3]

Regarding the alerts, does the reply in issue #2062 answer your question?

[1] https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsOptionsHttpsessions
[2] https://github.com/zaproxy/zap-core-help/wiki/HelpUiTabsParams#flag-as-session-token
[3] https://www.owasp.org/index.php/Session_fixation
