### ISSUE TITLE
Plug-n-Hack add-on issues

### ISSUE THREAD

**Issue by afeld** [zaproxy/zaproxy#2069]
...due to be [unverified](https://support.mozilla.org/1/firefox/43.0/Darwin/en-US/unsigned-addons). Using:
- OWASP ZAP 2.4.2
- OSX 10.11.1
- Firefox 43.0b4

Steps to reproduce:
1. Start ZAP.
2. Click "Plug-n-Hack" from the Quick Start tab.
3. In Firefox, click "Click to setup!", then "Add to Firefox".
4. Click "Allow" in the modal that pops up.

The add-on seems to be unverified:

<img width="791" alt="Firefox has prevented this site from installing an unverified add-on" src="https://cloud.githubusercontent.com/assets/86842/11305294/fdf29a34-8f79-11e5-8df8-8c9308a29cfb.png">

Are there any special instructions that need to be added to [the wiki](https://github.com/zaproxy/zap-core-help/wiki/HelpAddonsPlugnhackPlugnhack) or the `/pnh/` page? Sorry if I'm missing something!

**Comment by kingthorin** [comment]
As of Firefox 43 it is no longer possible to load unsigned extensions such as fx_pnh.xpi without altering settings in about:config in Firefox 44 there will be no option to bypass the requirement for all extensions to be signed.

https://github.com/zaproxy/zap-extensions/blob/beta/src/org/zaproxy/zap/extension/plugnhack/resources/fx_pnh.xpi

Will need to be updated with a signature, or we're going to have to state quite clearly that pnh functionality is only supported when using Firefox Developer Edition (or nightly build).

Further discussion here:
https://github.com/zaproxy/zaproxy/issues/2149

Further reference info here:
https://wiki.mozilla.org/Add-ons/Extension_Signing
https://developer.mozilla.org/en-US/docs/Signing_an_extension
https://developer.mozilla.org/en-US/docs/Signing_a_XPI

**Comment by kingthorin** [comment]
@mozmark any news on getting PnH signed?

**Comment by kingthorin** [comment]
Is there actually any hope for plug n hack?

**Comment by ipatrol** [comment]
Supposedly Mozilla was onboard with the development of the idea. I'd think it would end up very embarrassing for them if they don't sign this.

**Comment by psiinon** [comment]
Well, pnh was developed by myself and @mozmark and we are both employed by Mozilla. Unfortunately I dont think @mozmark has been able to spend any time on pnh, and I dont have the knowledge necessary to work on the Firefox side. I'm proposing that we disable pnh until it can be fixed. Any objections?

**Comment by kingthorin** [comment]
Seems ok to me. I don't think the extension itself needs any changes, just need to get it through the Mozilla signing process (however that works :shrug:).

**Comment by thc202** [comment]
I'm ok with that.

**Comment by mozmark** [comment]
I'm also OK with that - though I should clarify it isn't just signing that needs addressing: There have been (fairly major) changes to the way Firefox addons need to operate due to the recent multi-process work (e10s). If it is still the case that the addon runs in release versions of Firefox, please be aware that changes are coming that will cause (more) breakage.

I'd love to see this working again. If anyone else is interested in picking up this work, I'd be happy to assist.

**Comment by kingthorin** [comment]
@mozmark thanks for the update. If someone is available to work through the e10s changes are you able to get it signed?

**Comment by mozmark** [comment]
I should be able to help through the process - I'm not in a position to approve signing requests, though.

**Comment by tuxayo** [comment]
> If it is still the case that the addon runs in release versions of Firefox please be aware that changes are coming that will cause (more) breakage.

I confirm that the add-on works with stable 45 and fails with Developer Edition 47 with e10s enabled.

**Comment by thc202** [comment]
This is being fixed as part of a MWoS project:
https://wiki.mozilla.org/Security/Automation/Winter_Of_Security_2016/Ringleader_Support_for_e10s

**Comment by andreicristianpetcu** [comment]
> As of Firefox 43 it is no longer possible to load unsigned extensions such as fx_pnh.xpi without altering settings in about:config in Firefox 44 there will be no option to bypass the requirement for all extensions to be signed.

@kingthorin I'm sorry but this is false. 

Here is [the addon signed by me](https://my.owndrive.com/index.php/s/bqkuuGcRG4L1m06/download). Enjoy! :)

You should not disable addon signing in about:config. This is a security issue unless you are an addon dev.

[Here's how to sign it yourself](https://blog.mozilla.org/addons/2015/12/18/signing-firefox-add-ons-with-jpm-sign/)

If you have any issues signing this addon please ping me :)

**Comment by kingthorin** [comment]
@psiinon should we just close this? Browser launch seems to simplify browser setup sufficiently (for my 2 cents).

**Comment by psiinon** [comment]
Yeah, plug-n-hack was a good idea at the time but is now no longer practical.
