### ISSUE TITLE
Access to HTTPSessions for Site via Script

### ISSUE THREAD

**Issue by Harinus** [zaproxy/zaproxy#2080]
Hi,

i am currently developing a Proxy Script which needs to work with the sessions of a specific site.
Most methods in the HttpSessionsSite class are already public but these 4 would be required to access them first of all:

```
ExtensionHttpSessions.java
    protected HttpSessionsSite getHttpSessionsSite(String site) 
    protected HttpSessionsSite getHttpSessionsSite(String site, boolean createIfNeeded)

HttpSessionsSite.java
    protected Set<HttpSession> getHttpSessions()    
    protected HttpSession getHttpSession(String name)
```

Best Regards, 
Martin

**Comment by kingthorin** [comment]
@harinus noticed that you closed the related pull request? Is this change still desirable or should this be closed?

**Comment by kingthorin** [comment]
Disregard, just found the replacement PR
