### ISSUE TITLE
Specify values during ajaxSpider

### ISSUE THREAD

**Issue by xuyun1976** [zaproxy/zaproxy#2089]
Hi, 
Could I specify values during ajaxSpider, especially login in page? I found the input value is random during ajaxSpider. If I can set the username and password in ajaxSpider, it will helpful to do authentication. 

Thanks

**Comment by Harinus** [comment]
Hi,

you want to achieve authenticated spidering:

1)    authenticate using the web browser, while proxying through ZAP
2)    go to the Http Sessions tab and identify the session on which you have just authenticated (normally it should be just one so far if you haven't done anything else)
3)    mark the session as Active (using the right-click menu)
4)    make sure you exclude the logout URL from the Spider
5)    spider normally using any of the spiders. The requests it sends should be all modified to match the authenticated session.

Source: This has already been discussed here: https://groups.google.com/d/msg/zaproxy-users/TG2AHZq2mCc/o2-UM0j7KrkJ

**Comment by psiinon** [comment]
This is now supported by the form handler and our authentication support.

**Comment by thc202** [comment]
The AJAX Spider does not use the form handler.

**Comment by psiinon** [comment]
Ah, thats covered by https://github.com/zaproxy/zaproxy/issues/3343
