### ISSUE TITLE
Release the ZAP client API into maven central repostory

### ISSUE THREAD

**Issue by ddt-tdd** [zaproxy/zaproxy#2091]
Hi psinion,

Can you release the zap-api-2.4-v6.jar into the Central Repository?
Then can I also release my zap-maven-plugin into the Central Repository.

Greetings,
David

**Comment by psiinon** [comment]
We dp plan to do that. But we need to get ZAP 2.4.3 out first .. which will hopefully be this week...

**Comment by ddt-tdd** [comment]
If it is OK, I'll include the sources in my project so I can release my zap-maven-plugin.
When the client API is central release repository, I'll remove the source and make a dependency.

**Comment by psiinon** [comment]
Thats no problem, just make sure its clear yours is not the 'official' one ;)

**Comment by thc202** [comment]
@ddt-tdd make sure to shade org.zaproxy package, to avoid JAR hell.

**Comment by ddt-tdd** [comment]
@thc202 I'll be careful. Ever thought to use some dependency management framework and build environment such as Gradle?
I saw the org.apache.commons.httpclient sources in the project. Wouldn't this be better be a dependency?

**Comment by thc202** [comment]
Yes, that's on the plans and has been talked in the dev mailing list.
That library is already a dependency although some of the classes were forked (per ZAP requirements, as commented in the classes).

**Comment by nvonop** [comment]
Hi Guys,

Any update on when we are likely to see this available in Maven Central?

**Comment by thc202** [comment]
Should now be available (see https://github.com/zaproxy/zap-api-java#how-to-obtain for Maven coordinates).
