### ISSUE TITLE
Problem with Spider URL in 2.4.2 ZAP version

### ISSUE THREAD

**Issue by fulgore83** [zaproxy/zaproxy#2093]
I use the Spider but then does not find any links (href)

I tested it on Damn Vulnerable Web Application (DVWA) 

Best regards
Grzegorz

**Comment by psiinon** [comment]
Does DVWA make heavy use of JavaScript? (I cant remember off hand)
If so you should use the Ajax Spider instead.

**Comment by fulgore83** [comment]
yes, but there is js and simple href links together

for example:
<li onclick="window.location='vulnerabilities/brute/'" class=""><a href="vulnerabilities/brute/">Brute Force</a></li>

**Comment by psiinon** [comment]
OK, we should def look at that then

**Comment by fulgore83** [comment]
thank you

**Comment by thc202** [comment]
Which DVWA version? 1.0.7? The spider finds 106 URLs with that version after proper set up of the context and authentication in ZAP.

**Comment by fulgore83** [comment]
Version 1.9 (Release date: 2015-09-19)

**Comment by thc202** [comment]
With that version it is able to find 76 URLs in the first run (more than 100 in consecutive runs, but most of them are directory listings).
With newer version the authentication needs to be done manually or with a script (because of the `user_token`), with older version it could be done with form-based authentication.

**Comment by fulgore83** [comment]
Yes i use authentication manually and spider find only login.php and index.php. I try to do on Kali linux with the same ZAP version and it too problematic. My feature in ZAP is Spider... not Spider URL that like in older ZAP version.

**Comment by thc202** [comment]
Right, that menu item opens the "Spider" dialogue where you can choose the seed, context and user (and many other configurations).

Following the steps used to spider/scan DVWA v1.9 at `http://localhost/DVWA` using ZAP 2.4.3:

1) Create a new authentication JavaScript/ECMAScript script [1] and replace/set the script contents with the following:
```JavaScript
function authenticate(helper, paramsValues, credentials) {
    var loginUrl = paramsValues.get("Login URL");
    var csrfTokenName = paramsValues.get("CSRF Field");
    var csrfTokenValue = extractInputFieldValue(getPageContent(helper, loginUrl), csrfTokenName);
    var postData = paramsValues.get("POST Data");

    postData = postData.replace('{%username%}', encodeURIComponent(credentials.getParam("Username")));
    postData = postData.replace('{%password%}', encodeURIComponent(credentials.getParam("Password")));
    postData = postData.replace('{%' + csrfTokenName + '%}', encodeURIComponent(csrfTokenValue));

    var msg = sendAndReceive(helper, loginUrl, postData);
    return msg;
}

function getRequiredParamsNames() {
    return [ "Login URL", "CSRF Field", "POST Data" ];
}

function getOptionalParamsNames() {
    return [];
}

function getCredentialsParamsNames() {
    return [ "Username", "Password" ];
}

function getPageContent(helper, url) {
    var msg = sendAndReceive(helper, url);
    return msg.getResponseBody().toString();
}

function sendAndReceive(helper, url, postData) {
    var msg = helper.prepareMessage();

    var method = "GET";
    if (postData) {
        method = "POST";
        msg.setRequestBody(postData);
    }

    var requestUri = new org.apache.commons.httpclient.URI(url, true);
    var requestHeader = new org.parosproxy.paros.network.HttpRequestHeader(method, requestUri, "HTTP/1.0");
    msg.setRequestHeader(requestHeader);

    helper.sendAndReceive(msg);

    return msg;
}

function extractInputFieldValue(page, fieldName) {
    // Rhino:
    var src = new net.htmlparser.jericho.Source(page);
    // Nashorn:
    // var Source = Java.type("net.htmlparser.jericho.Source");
    // var src = new Source(page);

    var it = src.getAllElements('input').iterator();

    while (it.hasNext()) {
        var element = it.next();
        if (element.getAttributeValue('name') == fieldName) {
            return element.getAttributeValue('value');
        }
    }
    return '';
}
```

2) Create "DVWA" context [2] \(or edit the "Default Context"):
2a) Context Name:
`DVWAv1.9`
2b) In "Include in Context" panel add:
`\Qhttp://localhost/DVWA\E.*`
2c) In "Exclude form Context" panel add:
`\Qhttp://localhost/DVWA/login.php\E`
`\Qhttp://localhost/DVWA/logout.php\E`
`\Qhttp://localhost/DVWA/setup.php\E`
2d) In "Authentication" panel, choose "Script-Based Authentication" [3], select the "DVWA" authentication script, load it and fill the fields:
Login URL:
`http://localhost/DVWA/login.php`
CSRF Field:
`user_token`
POST Data:
`username={%username%}&password={%password%}&Login=Login&user_token={%user_token%}`
Logged in:
`\Q<a href="logout.php">Logout</a>\E`
Logged Out:
`(?:Location: [./]*login\.php)|(?:\Q<form action="login.php" method="post">\E)`
2e) In "Users" panel, add the user:
User Name:
`Administrator`
Username:
`admin`
Password:
`password`
2f) Close the dialogue.

3) Verify authentication is working, create seed for the spider and configure DVWA:
3a) Enable "Force User Mode" [4] and access the main page (e.g. "http://localhost/DVWA") while proxying through ZAP, cookies should be disabled in the browser; It should show the main page thus the authentication is working and the spider has a seed;
3b) Access "http://localhost/DVWA/security.php" and change the "Security Level" to "low";
3c) Disable the "Forced User Mode" (no longer needed).
3d) Exclude from the context the following URLs, to prevent the spider from changing the "Security Level" and the password:
`\Qhttp://localhost/DVWA/security.php\E`
`\Qhttp://localhost/DVWA/vulnerabilities/csrf\E.*`


With the context and authentication set up, it's possible to spider/scan as user.
4) Spider:
4a) Select "Spider" tab and click the button "New Scan";
4b) Click "Select...", choose the context (e.g. "DVWAv1.9") and click OK;
4c) Select the user "Administrator" and click "Start Scan";
4d) Spider should start and spider as user "Administrator".
Spider can be run a second time to ensure that all URLs are found.

5) Active Scan:
5a) Select "Active Scan" tab and click the button "New Scan";
5b) Click "Select...", choose the context (e.g. "DVWAv1.9") and click OK;
5c) Select the user "Administrator" and click "Start Scan";
5d) Active scanner should start and scan as user "Administrator".

Active scanner should find some issues:
 - Cross Site Scripting (Persistent) (4)
 - Cross Site Scripting (Reflected) (6)
 - Path Traversal
 - Remote OS Command Injection
 - SQL Injection - MySQL
 - SQL Injection (2)
 - Directory Browsing (7)

[1] https://github.com/zaproxy/zap-core-help/wiki/HelpAddonsScriptsTree
[2] https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsSessionContexts
[3] https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsSessionContext-auth#script-based-authentication
[4] https://github.com/zaproxy/zap-core-help/wiki/HelpUiTltoolbar#--force-user-mode-on--off

**Comment by thc202** [comment]
@fulgore83 can this issue be closed?

**Comment by fulgore83** [comment]
thanks for help

**Comment by thc202** [comment]
You're welcome.

**Comment by tony1016** [comment]
Why it's not easy to scrap the dvwa links??Why it must use script auth but not form based auth??
In my case,it even can't find sql injection point.

**Comment by tony1016** [comment]
all the links not found.

<div id="main_menu_padded">
				<ul class="menuBlocks"><li onclick="window.location='.'" class="selected"><a href=".">Home</a></li>
<li onclick="window.location='instructions.php'" class=""><a href="instructions.php">Instructions</a></li>
<li onclick="window.location='setup.php'" class=""><a href="setup.php">Setup / Reset DB</a></li>
</ul><ul class="menuBlocks"><li onclick="window.location='vulnerabilities/brute/'" class=""><a href="vulnerabilities/brute/">Brute Force</a></li>
<li onclick="window.location='vulnerabilities/exec/'" class=""><a href="vulnerabilities/exec/">Command Injection</a></li>
<li onclick="window.location='vulnerabilities/csrf/'" class=""><a href="vulnerabilities/csrf/">CSRF</a></li>
<li onclick="window.location='vulnerabilities/fi/.?page=include.php'" class=""><a href="vulnerabilities/fi/.?page=include.php">File Inclusion</a></li>
<li onclick="window.location='vulnerabilities/upload/'" class=""><a href="vulnerabilities/upload/">File Upload</a></li>
<li onclick="window.location='vulnerabilities/captcha/'" class=""><a href="vulnerabilities/captcha/">Insecure CAPTCHA</a></li>
<li onclick="window.location='vulnerabilities/sqli/'" class=""><a href="vulnerabilities/sqli/">SQL Injection</a></li>
<li onclick="window.location='vulnerabilities/sqli_blind/'" class=""><a href="vulnerabilities/sqli_blind/">SQL Injection (Blind)</a></li>
<li onclick="window.location='vulnerabilities/xss_r/'" class=""><a href="vulnerabilities/xss_r/">XSS (Reflected)</a></li>
<li onclick="window.location='vulnerabilities/xss_s/'" class=""><a href="vulnerabilities/xss_s/">XSS (Stored)</a></li>
</ul><ul class="menuBlocks"><li onclick="window.location='security.php'" class=""><a href="security.php">DVWA Security</a></li>
<li onclick="window.location='phpinfo.php'" class=""><a href="phpinfo.php">PHP Info</a></li>
<li onclick="window.location='about.php'" class=""><a href="about.php">About</a></li>
</ul><ul class="menuBlocks"><li onclick="window.location='logout.php'" class=""><a href="logout.php">Logout</a></li>
</ul>

**Comment by thc202** [comment]
It's because of the dynamic fields ("user_token" in this case), which Form-based authentication method does not handle.
We should change Form-based to do that (or add another auth method that does it).
Would you mind raising an issue?

**Comment by tony1016** [comment]
No problem.

**Comment by thc202** [comment]
Thanks for raising the issue.
