### ISSUE TITLE
Put Request/Response tabs side-by-side

### ISSUE THREAD

**Issue by acaetano** [zaproxy/zaproxy#2096]
During analysis, sometimes we are required to collect evidence about issues that only make sense if we put information present in the request along with information present only in the response. Like session id expiration problems, id reusage, etc. I know that we have those buttons on the toolbar, but they are not valid for requests already in the history tab. For example, i'm testing an application that is returning some 503 problems for the past 5 minutes. It might be just some temporary technical glitch, or they are changing the application while i'm making the analysis. Anyway, the point is that i have the evidence in the History tab, but i'm unable to properly evidence it because i cannot put a request and its respective response in the same picture.

**Comment by thc202** [comment]
You can use the following option:
https://github.com/zaproxy/zap-core-help/wiki/HelpUiTltoolbar#-request-and-response-panels-side-by-side

Or, isn't that working?

**Comment by kingthorin** [comment]
Just tested this in 2.4.2. I have it setup tabbed by default. Proxied some traffic. Select various history items and switch between the views (tabbed, side-by-side, stacked), works no problem....

What happens when you click the buttons?

**Comment by acaetano** [comment]
Nothing. It stays just the same. It only changes the behavior when i'm using the Resend window.

**Comment by acaetano** [comment]
Never mind it. The faulty behavior i reported only happens when i'm using the "Expand Full" button. Using the "Expand Sites" or "Expand Information Tabs" the request and response tabs are put side-by-side normally.

**Comment by thc202** [comment]
We should probably disable those options (tabbed, side-by-side, stacked) when in "Expand Full" view option.
It would be more clear that do not apply to "Expand Full" view.
