### ISSUE TITLE
Multiple SQLException "channel not inserted" and "data exception: string data, right truncation"

### ISSUE THREAD

**Issue by mz0** [zaproxy/zaproxy#2097]
More then 700 of them logged after running "Attack"  from Quick Start page against a Vaadin (GWT) based app over HTTPS. Zap is the latest [weekly build from Nov. 30] (https://github.com/zaproxy/zaproxy/releases/download/w2015-11-30/ZAP_WEEKLY_D-2015-11-30.zip).
Two varieties:
org.parosproxy.paros.db.DatabaseException: java.sql.SQLDataException: data exception: string data, right truncation  - 5 exceptions
org.parosproxy.paros.db.DatabaseException: java.sql.SQLException: channel not inserted: 1 - 696 exceptions (also channel 2 - 6 exceptions)

I'm willing to add logging to know what data causes this. 
Help is very much welcome.  Attaching a redacted log.
[zap.redacted.log.txt](https://github.com/zaproxy/zaproxy/files/48755/zap.redacted.log.txt)

**Comment by kingthorin** [comment]
What version of ZAP?
What version of the websockets addon? (You can find this by opening 'Check for updates' and hovering your mouse over the addon name)

**Comment by mz0** [comment]
weekly build from Nov. 30. WebSockets ver. 9

**Comment by mz0** [comment]
created pull request. Changes tested and URLs of length 288 logged.
[vaadin-websocket-urls.log](https://github.com/zaproxy/zaproxy/files/50324/vaadin-websocket-urls.log.txt)
