### ISSUE TITLE
OWASP Zaproxy cannot attack URL if its begins with https

### ISSUE THREAD

**Issue by davshowhan449** [zaproxy/zaproxy#2101]
I am using the OWASP ZAP Tool (version 2.4.2). The problem is if I choose to attack urls that has https, it always says "Failed to Attack URL". It works fine if the url I entered is not https.

http://myapplication    <-- works fine
https://myapplication <--- "failed to attack URL" error

How can I enable it to work with https?

**Comment by psiinon** [comment]
Strange, ZAP should cope with most https sites with no changes.
Try proxying your browser through ZAP and accessing this site and see what happens.
Then report back and we'll take it from there :)

**Comment by davshowhan449** [comment]
I'm not trying to record urls or anything, just trying to attack my application to see how well it complies with OWASP Top 10. So I still need to set localhost 8080 as proxy for that?

**Comment by psiinon** [comment]
Dont be sorry - no reason for you to be a ZAP expert :)
Normally you shouldnt need to proxy in order to use the Quick Start attack, but in this case it would be very useful in order to help work out whats going wrong.
You can either manually configure your proxy or if you are using Firefox use the 'Plug-n-Hack' button.
I recommend using a separate Firefox profile for security testing - Chrome has something similar too.

**Comment by davshowhan449** [comment]
Ok ill try. Will let you know the result. Thanks

**Comment by psiinon** [comment]
We've actually improved the error messages for the next release: https://github.com/zaproxy/zaproxy/issues/2032 :)

**Comment by davshowhan449** [comment]
"Try proxying your browser through ZAP and accessing this site and see what happens.
Then report back and we'll take it from there :)"

I got this error:

ZAP Error [javax.net.ssl.SSLHandshakeException]: Received fatal alert: handshake_failure

Stack Trace:
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:1979)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1086)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1332)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1359)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1343)
	at org.parosproxy.paros.network.SSLConnector.createSocket(Unknown Source)
	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(Unknown Source)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(Unknown Source)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.parosproxy.paros.network.HttpSender.executeMethod(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.runMethod(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.send(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(Unknown Source)
	at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(Unknown Source)
	at org.parosproxy.paros.core.proxy.ProxyThread.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

**Comment by davshowhan449** [comment]
i fixed it. It turns out I need to install Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files 7 in my Java home directory. 

Thanks for the help

**Comment by kingthorin** [comment]
Thanks for letting us know. JCE is covered in our [SSL FAQ]  (https://github.com/zaproxy/zaproxy/wiki/FAQsslHandshake).

I've added a reference to the SSL FAQ in the [Quick Scan FAQ] (https://github.com/zaproxy/zaproxy/wiki/FAQquickScanFailed).

**Comment by padsmith70** [comment]
Tried to downlaod the Jave - downloaded, not sure what or how I install these ? So stil not working when I use OWASP ZAP on https web site ... under Advanced, Certificates on Firefox I did not have a Enable unsafe SSL/TLS renegotiation' in there so not sure how to enable this ? Using Firefox 46.0
Appreciate your help, I can use it as a proxy and as I browse I see non https sites in ZAP just not https.
Help !!!

**Comment by kingthorin** [comment]
The issue tracker is really a sub-optimal place to tackle such things.

Please move the discussion over to the User Group:
https://groups.google.com/forum/#!forum/zaproxy-users

Chances are you need to import ZAP's CA certificate in order to get HTTPS decryption going.

**Comment by padsmith70** [comment]
Thanks but no idea from  that what I need to look for in that forum   ?  I assume out of the box you cant test https ?

**Comment by thc202** [comment]
You just need to ask your question there, providing any details of the problem (errors that you are seeing, if any; what have you tried so far and so on) so that we can help better.

No, you should be able to scan HTTPS sites out of the box. But if you are trying to proxy through ZAP with a browser you might need to configure the browser to accept the certs issued by ZAP (by installing ZAP's root CA cert).

**Comment by padsmith70** [comment]
Thanks I am trying to do that ....and I will indeed as the question. 
For some reason I cannot browse direct from ZAP to https neither..but thanks I will ask the question in the forum...
Thanks again

**Comment by keyamlbd0034** [comment]
Thanks for the discussion above I tried each and every steps mentioned in https://github.com/zaproxy/zaproxy/wiki/FAQsslHandshake but still its not working from my end. Giving a description bellow what I did 
1. Tried to send a POST request using manual request editor 
Request header:
````
POST https://abc.def.com/v1/login HTTP/1.0
accept: */*
accept-encoding: gzip, deflate, br
accept-language: en
content-length: 60
content-type: application/json
origin: https://abc.def.com
referer: https://abc.def.com/login
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.79 Safari/537.36
Host: abc.def.com`
```
Request body:
```
{
  "email": "***",
  "password": "**"
}
```

Got the following error 
ZAP Error [javax.net.ssl.SSLHandshakeException]: Received fatal alert: handshake_failure

Is there any work around to solve this issue

**Comment by psiinon** [comment]
Please dont ask questions on closed issues.
The user group https://groups.google.com/group/zaproxy-users is a better place for these sort of questions.
