### ISSUE TITLE
Zest - script context menu has duplicated items

### ISSUE THREAD

**Issue by dfdumaresq** [zaproxy/zaproxy#2106]
In the right-click menu, under Add Zest Assignment, I find a duplicate set of options. I'm using 2.4.3. See screenshot below.
![script](https://cloud.githubusercontent.com/assets/20051/11599900/48b8c84a-9a7e-11e5-95ae-ffac601e3f77.png)

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#261.
