### ISSUE TITLE
ZAP API clients should not send optional parameters unless specified

### ISSUE THREAD

**Issue by continuumsecurity** [zaproxy/zaproxy#2108]
In 2.4.3:
Have to specify a context name when calling spider.scan from the API, if no context is entered then ZAP responds with "Does not exist".

To workaround this, I entered a context of "Default Context"
1. Enter context of "Default Context",
2. enter the API key 
4. enter true for recurse
3. and the URL: http://localhost:/9110/ropeytasks

The API request looks like this:
http://zap/JSON/spider/action/scan/?zapapiformat=JSON&apikey=apisecret&url=http%3A%2F%2Flocalhost%3A9110%2Fropeytasks&maxChildren=&recurse=&contextName=Default+Context

When submitting this request, the spider does not perform any action, it just immediately changes to FINISHED.  Reading the results from the spider with spider.results returns an empty array:
{"results":[]}

Performing these exact same actions in 2.4.0 worked (which did not request a context name), and the spider ran and produced results.

In case this had to do with recurse and maxchildren, I set both to 10 and resubmitted the request, with the same empty results list.

**Comment by continuumsecurity** [comment]
False positive, using the wrong URL.

**Comment by thc202** [comment]
Thanks for letting us know.

**Comment by thc202** [comment]
This is an issue, the context name is not mandatory but the API client sends always something even if the context name is not provided (i.e. null), which ends up being used and validated, when the API request is processed in ZAP.
The API client needs to be changed to not send the optional parameters if not specified, the Spider API should be changed as well to ignore empty context names, since most of the API clients send the parameters with empty values.

**Comment by thc202** [comment]
A new version (9) of the Java ZAP API Client has been released to address this issue.

**Comment by LisinIwan** [comment]
In 2017-10-02 (Weekly-Release) i faced the same Problem:
Always getting the ERROR-message that "Default Context" does not exist. It took me nearly 1 week to figure out what actually caused the error. 
First of all i tried to modify the Code, the most simple solution was just to comment out the try-catch-block inside the  includeInContext-Method, in the ZapHelper class. 
But i geuss it is not satisfying to modify a plugin yourself, so i was looking further into the  issue and figured out that actually the language Setup of ur PC caused the error. 
In my case (Germany) i could also set the 
private static final String ZAP_DEFAULT_CONTEXT_NAME = "Default Context"; to 
private static final String ZAP_DEFAULT_CONTEXT_NAME = "Standard-Kontext"; inside the ZapHelper class and it would fix the Problem ... but also switching ur PC to english would have the same result.

So short and simple Change the language on your Computer to english and it could solve your Problem, at least it did help me.
