### ISSUE TITLE
SQL Injection gets skipped

### ISSUE THREAD

**Issue by Harinus** [zaproxy/zaproxy#2110]
Hi, 
when executing any active scan the SQL Injection gets skipped. (Standard Mode)
It only works in ATTACK Mode. Looks like  a bug to me.
![skip](https://cloud.githubusercontent.com/assets/5645416/11630362/656831ca-9cfd-11e5-8627-9ad369f45341.png)
Best Regards,
Martin

**Comment by thc202** [comment]
What ZAP version are you using?

Does that happen with the default policy? Are you scanning a context?

**Comment by thc202** [comment]
Guess ZAP 2.4.3, by the image.

**Comment by Harinus** [comment]
I am using 2.4.3 but it was present in 2.4.2 also (reporting now as i assumed it may be fixed in .3) Having a Context with the Host included. Then right click active scan on the root of the site. Using default policy or any custom one (which have the SQL Injection enabled)

**Comment by thc202** [comment]
Are all the technologies of the context enabled? That scanner is (automatically) skipped if DB technology is not enabled.

**Comment by Harinus** [comment]
Technologies are unchanged.. so DB is enabled (by default)

**Comment by thc202** [comment]
OK, not sure why it's being skipped. Could you provide/take a look at the log?

**Comment by Harinus** [comment]
Of course.. you will get your logs tomorrow when back at the office.

**Comment by thc202** [comment]
Thank you.
btw, you should try running ZAP with a clean directory (with "-dir" option [1]).
That should give more clues to where the issue is.

[1] https://github.com/zaproxy/zap-core-help/wiki/HelpCmdline

**Comment by Harinus** [comment]
Here are the exact steps to reproduce the error:

1) Open ZAP 2.4.3
2) add the 3 policies mentioned above (remove default if existing)
3) set medium as default for Active Scan in the settings
4) Restart ZAP
5) Proxy a Page through ZAP
6) Right Click > Attack > Active Scan
7) notice Medium is selected
8) Start scan
9) Check the Strength in the Progress window -> Medium > OK!
10) Stop the scan if not yet finished
11) Save the session
12) Repoen the same session (no need to close ZAP here)
13) Repeat 6) to 8)
14) In the Progress window the strength is now "low"

**Comment by Harinus** [comment]
Here is the log:

```
2015-12-08 08:01:12,360 [Thread-297] INFO  HostProcess - completed host/plugin http://10.202.0.147 | TestCrossSiteScriptV2 in 0.468s
2015-12-08 08:01:12,360 [Thread-297] DEBUG ActiveScan - Plugin 40012 total # reqs: 17
2015-12-08 08:01:12,610 [Thread-297] INFO  HostProcess - skipped plugin http://10.202.0.147 | TestSQLInjection in 0s
2015-12-08 08:01:12,672 [Thread-297] INFO  HostProcess - start host http://10.202.0.147 | CodeInjectionPlugin strength MEDIUM threshold MEDIUM
```
I am able to reproduce it now:

Open ZAP
Proxy a Page
Add it to the default context
Start Active scan with default context
-> SQL skipped
Scan Site without Context -> SQL executed
Modify Context, uncheck the DB Technology and reenable it (even though its already enabled) -> SQL executed!
So it looks like there is a problem with reading the defaults from the context.
Also appears when using a new Context without touching the Technology Settings

**Comment by Harinus** [comment]
Having a look at the context files i found a possible cause:

This is the default Tech section of a context:
```
<include>Db.Firebird</include>
<include>Db.HypersonicSQL</include>
<include>Db.IBM DB2</include>
<include>Db.Microsoft Access</include>
<include>Db.Microsoft SQL Server</include>
<include>Db.MySQL</include>
<include>Db.Oracle</include>
<include>Db.PostgreSQL</include>
<include>Db.SAP MaxDB</include>
<include>Db.SQLite</include>
<include>Db.Sybase</include>
<include>Language.ASP</include>
<include>Language.C</include>
<include>Language.PHP</include>
<include>Language.XML</include>
<include>OS.Linux</include>
<include>OS.MacOS</include>
<include>OS.Windows</include>
<include>SCM.Git</include>
<include>SCM.SVN</include>
<include>WS.Apache</include>
<include>WS.IIS</include>
<include>WS.Tomcat</include>
<exclude>Db</exclude>
<exclude>Language</exclude>
<exclude>OS</exclude>
<exclude>SCM</exclude>
<exclude>WS</exclude>
```
But why are there 5 excludes? In the GUI is everything enabled. When unchecking the technologies and reenabling them as described above the excludes disappear

**Comment by thc202** [comment]
Thanks, that's caused by a problem in the selection state of technology tree.

**Comment by artem-tim** [comment]
I am facing a similar (same?) issue with ZAP 2.5.0 (on Mac, if it matters). To be precise, if at least one DB technology is unchecked in the context (anything), SQL Injection scan is always skipped. Otherwise (all DB technologies active) it runs.
Is it a bug or a feature ?

**Comment by thc202** [comment]
Looks likely a bug, but make sure that the add-ons are up-to-date (it could be zaproxy/zap-extensions#439, fixed in version 24 of Active scanner rules add-on).

**Comment by artem-tim** [comment]
Thank you for quick reply !
After updating all addons and installing Active Scanner Rules (beta), the problem is gone.
Cheers

**Comment by thc202** [comment]
Great, thanks for letting us know!
