### ISSUE TITLE
Wrong policy on active Scan

### ISSUE THREAD

**Issue by Harinus** [zaproxy/zaproxy#2112]
I created 3 Policies:
-lite (Threshold: med, Strength: low)
-maximum (Threshold: low, Strength: insane)
-medium (Threshold: med, Strength: med)

However when i select the medium policy and start an active scan. I can see in the scan Progress popup that the Strength is set to low. Therefore i assume that the wrong policy gets loaded.

Best Regards,
Martin

**Comment by thc202** [comment]
Could you provide the exact steps that you are doing?
It is working fine here (ZAP 2.4.3).

**Comment by Harinus** [comment]
Medium is pre-selected from the last scan in my case.. if i do not change it, it shows low in the scan.. (so it picks the first one it finds?) if reselecting medium before the scan everything is fine. Can give you a more detailed instruction tomorrow if required.

**Comment by thc202** [comment]
I'm not able to reproduce the issue with those steps, it still shows "Medium" strength.
That would be great, the exacts steps should help reproduce and narrow the cause of the problem.

P.S. I've to ask, are you sure that you are seeing the "Scan Progress" dialogue of the current (medium) scan?

**Comment by Harinus** [comment]
Here are the exact steps to reproduce the error:

1) Open ZAP 2.4.3
2) add the 3 policies mentioned above (remove default if existing)
3) set medium as default for Active Scan in the settings
4) Restart ZAP
5) Proxy a Page through ZAP
6) Right Click > Attack > Active Scan
7) notice Medium is selected
8) Start scan
9) Check the Strength in the Progress window -> Medium > OK!
10) Stop the scan if not yet finished
11) Save the session
12) Repoen the same session (no need to close ZAP here)
13) Repeat 6) to 8)
14) In the Progress window the strength is now "low"

**Comment by thc202** [comment]
Thanks!
