### ISSUE TITLE
Update Python API Client for ZAP 2.4.3

### ISSUE THREAD

**Issue by r3ver53r** [zaproxy/zaproxy#2113]
Unable to find the python API in context.py to remove a context from the current session. Could the addition of below code to context.py be a possible solution?

def remove_context(self, contextname='', apikey=''):
        """
        Removes a context from the current session
        """
        return next(self.zap._request(self.zap.base + 'context/action/removeContext/', {'contextName' : contextname, 'apikey' : apikey}).itervalues())

**Comment by r3ver53r** [comment]
Oh, I believe this has already been addressed in the last 2.4.3 release.
https://github.com/zaproxy/zaproxy/blob/5d7d0e7fb7644ab1b4ac519f7f7514ef89f85200/python/api/src/zapv2/context.py

**Comment by thc202** [comment]
Actually that feature was added in ZAP 2.4.2 (#1766), although the Python API client was not yet released with those changes.

**Comment by r3ver53r** [comment]
Ah, got you. Thanks!

**Comment by thc202** [comment]
A new version (0.0.7) of the Python ZAP API Client has been released.
