### ISSUE TITLE
Zest authentication requests not sent with ZAP's configurations

### ISSUE THREAD

**Issue by r3ver53r** [zaproxy/zaproxy#2114]
When ZAP's upstream proxy is configured from Tools > Options > Connections tab, the automatic requests for script based authentication aren't logged into upstream proxy.

**Comment by thc202** [comment]
Zest authentication script?

**Comment by r3ver53r** [comment]
Yes.

**Comment by thc202** [comment]
OK, thank you.

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions@94de3c4dbb2f9c808857c359254ea87daa0e3fe4.
