### ISSUE TITLE
Warn if the report generation failed

### ISSUE THREAD

**Issue by sbunde** [zaproxy/zaproxy#2127]
Hi,
- I am running a spider scan on an intranet site. 
- Generation XML and HTML report from 'Report-> generate XML/HTML report' option of ZAP GUI.
- Saving the report.
- Open the report (xml and html) it gives blank page.
- Please let me know what wrong am I doing.

**Comment by thc202** [comment]
What ZAP version?
Would you mind checking ZAP's log file to see if there's any error? (file zap.log located in ZAP's default directory or the directory manually specified [1]).


[1] https://github.com/zaproxy/zaproxy/wiki/FAQconfig

**Comment by sbunde** [comment]
ZAP version is 2.4.3 and I could not find the ZAP directory (windows 7 C:\Users\<username>\OWASP ZAP)
Also, I don't remember specifying it manually.

**Comment by thc202** [comment]
Did you replace `<username>` with the actual user that you're using?

**Comment by sbunde** [comment]
yes

**Comment by sbunde** [comment]
![image](https://cloud.githubusercontent.com/assets/16288184/11779764/875220c4-a25d-11e5-9d2b-de892bc0daed.png)

**Comment by thc202** [comment]
OK, might be hidden?
An alternative is to start ZAP with zap.bat file. [1]
It would output the error to the console, when generating the report.

[1] https://github.com/zaproxy/zaproxy/wiki/FAQinstall

**Comment by sbunde** [comment]
Hi,
I was now able to check the logs and it showed error
2015-12-14 13:22:32,628 [pool-2-thread-1] WARN  ENGINE - data file enlarge failed 
java.io.IOException: There is not enough space on the disk

So I changed the drive to save the report and they are saved successfully.

Thanks for your guidance.

**Comment by kingthorin** [comment]
@sbunde thanks for letting us know. 

I'm going to re-open this one as we should probably handle that condition more gracefully.

**Comment by DarkPrince304** [comment]
@kingthorin: How do you think this should be handled?

**Comment by kingthorin** [comment]
So originally I had thought this was about report generation failing, so I envisioned it going here:
https://github.com/zaproxy/zaproxy/blob/develop/src/org/zaproxy/zap/view/widgets/WritableFileChooser.java

However, this could have to do with a persisted session failing to grow properly (the HSQL DB), if that's the case we need to catch the condition and tell the user that they need to move their persisted session elsewhere (a disk with more space), else they're in a data loss scenario. What is further unknown at this point is how graceful HSQL is at dealing with full disks, we don't want to cause dialogs to just pop and pop and pop.
Looking [here ](https://github.com/arteam/hsqldb/blob/aa0a17fc0f4aad19afa42fb5afc46b4e0884601d/src/org/hsqldb/persist/RAFileSimple.java#L112-L126) it's only a warning, which is kind of surprising to me. I would assume that if the DB can't be grown you should see the error over and over again in ZAPs logs...

I guess. At this point more testing is needed to nail down the culprit, conditions, behavior, etc. then we can come up with a plan to address it.

**Comment by mustafa421** [comment]
@kingthorin I would like to work on this :). I was able to reproduce the error and I noticed you always end up with an IO error regardless of wether you were using the DB. The problem is that the exception is thrown after the user attempts to export the results to a disk w/o available space. As such, it would probably be useful to create a way to check if there is available space prior to exporting. I'd imagine the WritableFileChooser would need to be modified to accommodate this.

**Comment by thc202** [comment]
There are two different issues in this issue report. One is about the database and the other about generation of the report, being the latter handled in the pull request.
Probably better to rename the issue.
@kingthorin what do you think?

**Comment by kingthorin** [comment]
Renaming this one seems like a good move. A separate issue can be raised referencing this one to cover what happens to session data (temp or persisted) when a drive fills up.

**Comment by thc202** [comment]
Done (feel free to tweak the names and issue report ;)
