### ISSUE TITLE
Firefox 44 will require signed extensions with no bypass (PnH)

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#2150]
As of Firefox 43 it is no longer possible to load unsigned extensions such as fx_pnh.xpi without altering settings in about:config in Firefox 44 there will be no option to bypass the requirement for all extensions to be signed.

https://github.com/zaproxy/zap-extensions/blob/beta/src/org/zaproxy/zap/extension/plugnhack/resources/fx_pnh.xpi

Will need to be updated with a signature, or we're going to have to state quite clearly that pnh functionality is only supported when using Firefox Developer Edition (or nightly build).

Further discussion here:
https://github.com/zaproxy/zaproxy/issues/2149

Further reference info here:
https://wiki.mozilla.org/Add-ons/Extension_Signing
https://developer.mozilla.org/en-US/docs/Signing_an_extension
https://developer.mozilla.org/en-US/docs/Signing_a_XPI

**Comment by thc202** [comment]
I believe this issue is already being handled in #2069.

**Comment by kingthorin** [comment]
Good catch, closing as duplicate of issue#2069.
