### ISSUE TITLE
2.4.3 failed parse the URL containts bracket([]) in URL Query String

### ISSUE THREAD

**Issue by g-sato** [zaproxy/zaproxy#2152]
When scanning the URL containts bracket([]) in URL Query String, the OWASP ZAP 2.4.3 failed parse that URL. 

1) Request this URL.

http://localhost/test.php?param[]=value1

2) Do Attack - Active Scan that URL. (input Vectors - Injectable Targets: 'URL Query String' and 'POST Data')

3) OWASP ZAP sending many same requests.

log:
GET http://localhost/test.php?param%5B%5D=value1 HTTP/1.1
GET http://localhost/test.php?param%5B%5D=value1 HTTP/1.1
GET http://localhost/test.php?param%5B%5D=value1 HTTP/1.1
  .
  .

Instead of that URL, OWASP ZAP can scan this URL correctly.

http://localhost/test.php?param=value1

log:
GET http://localhost/test.php?param=0W45pz4p HTTP/1.1
GET http://localhost/test.php?param=%27 HTTP/1.1
GET http://localhost/test.php?param=value1%27 HTTP/1.1
  .
  .

Is this problem reproducible or is it just me?

**Update:**
note: the target URL 'test.php' in this sample is only 2 lines below:
<?php
print_r($_REQUEST);
[EOF]

Additional Information:
ZAP 2.4.3 fails scan this URL.(failed scan all parameters, ZAP sending many same (meaningless) requests)

http://localhost/test.php?a=b&c=d&e=f&g[]=h

ZAP can scan this URL correctly.

http://localhost/test.php?a=b&c=d&e=f&g=h

**Comment by thc202** [comment]
Merging into #1848.
