### ISSUE TITLE
Error connection refused while using ZAP python API

### ISSUE THREAD

**Issue by debojyotib** [zaproxy/zaproxy#2159]
I am facing issue while using **_ZAP pythonAPI_**. 

**Platform used**: Kali Linux 2.0
**Steps followed:**

1. pip install python-owasp-zap-v2.4
2. Copied the python script available in [ZAProxy PythonAPI!](https://github.com/zaproxy/zaproxy/wiki/ApiPython)
3. Uncommented the line 
    
        # zap = ZAPv2(proxies={'http': 'http://127.0.0.1:8090', 'https': 'http://127.0.0.1:8090'})
4. I also added the following lines to start the ZAP in daemon mode before the ZAPv2 proxy code.

        print 'Starting ZAP ...'
        subprocess.Popen(['/usr/share/zaproxy/zap.sh','-daemon'],stdout=open(os.devnull,'w'))
        print 'Waiting for ZAP to load, 10 seconds ...'
        time.sleep(10)

However, i am always getting the error: **_IOError: [Errno socket error] [Errno 111] Connection refused._**
The python file is attached.
[zapscan.txt](https://github.com/zaproxy/zaproxy/files/77272/zapscan.txt)

I tried to use the urlib library directly with following code snippets which works just fine

    import os
    import subprocess
    import time
    from pprint import pprint
    from zapv2 import ZAPv2
    import urllib

    target = 'http://demo.testfire.net'
    print urllib.urlopen(target).read()

**Any help would be useful.**

**Comment by thc202** [comment]
That error means that either ZAP was not yet started or it's not listening on 8090.
To ensure that ZAP listens on the port that your trying to connect to, you should use "-port" command line argument, e.g.:
```Python
subprocess.Popen(['/usr/share/zaproxy/zap.sh','-daemon', '-port', '8090'],stdout=open(os.devnull,'w'))
```

If it still does not work you need to verify that 10 seconds are enough for ZAP to fully start.

See also:
https://github.com/zaproxy/zaproxy/wiki/FAQapikey

[1] https://github.com/zaproxy/zap-core-help/wiki/HelpCmdline

**Comment by debojyotib** [comment]
Thank you. This worked. Also 10 seconds is very less. Making it 30 worked actually.

_Just a suggestion_: The sample code as part of Python API page should be updated to include the api key option.

**Comment by Stalluri1** [comment]
hey can u please help me in using api-key

**Comment by kingthorin** [comment]
https://github.com/zaproxy/zaproxy/wiki/FAQapikey

Please don't ask questions as issues - the ZAP User Group https://groups.google.com/group/zaproxy-users is a much better places for questions.
