### ISSUE TITLE
Scan Error: Data File Reached Max Size

### ISSUE THREAD

**Issue by lfatty** [zaproxy/zaproxy#2160]
This is the error that keep showing during scan:

[ZAP-ActiveScanner-1] FATAL hsqldb.db.HSQLDB379AF3DEBD.ENGINE - data file reached maximum size /var/lib/jenkins/.ZAP/session/untitled1.data
[java] 106425634 [ZAP-ActiveScanner-1] ERROR org.zaproxy.zap.extension.ascan.ActiveScan - java.sql.SQLException: Data File size limit is reached
[java] org.parosproxy.paros.db.DatabaseException: java.sql.SQLException: Data File size limit is reached
[java] at org.parosproxy.paros.db.paros.ParosTableHistory.write(Unknown Source)
[java] at org.parosproxy.paros.model.HistoryReference.(Unknown Source)
[java] at org.zaproxy.zap.extension.ascan.ActiveScan.notifyNewMessage(Unknown Source)
[java] at org.parosproxy.paros.core.scanner.HostProcess.notifyNewMessage(Unknown Source)
[java] at org.parosproxy.paros.core.scanner.AbstractPlugin.sendAndReceive(Unknown Source)
[java] at org.parosproxy.paros.core.scanner.AbstractPlugin.sendAndReceive(Unknown Source)
[java] at org.parosproxy.paros.core.scanner.AbstractPlugin.sendAndReceive(Unknown Source)
[java] at org.zaproxy.zap.extension.ascanrules.TestCrossSiteScriptV2.performAttack(TestCrossSiteScriptV2.java:105)
[java] at org.zaproxy.zap.extension.ascanrules.TestCrossSiteScriptV2.scan(TestCrossSiteScriptV2.java:220)
[java] at org.parosproxy.paros.core.scanner.AbstractAppParamPlugin.scan(Unknown Source)
[java] at org.parosproxy.paros.core.scanner.AbstractAppParamPlugin.scanVariant(Unknown Source)
[java] at org.parosproxy.paros.core.scanner.AbstractAppParamPlugin.scan(Unknown Source)
[java] at org.parosproxy.paros.core.scanner.AbstractPlugin.run(Unknown Source)
[java] at java.lang.Thread.run(Thread.java:745)
[java] Caused by: java.sql.SQLException: Data File size limit is reached
[java] at org.hsqldb.jdbc.Util.sqlException(Unknown Source)
[java] at org.hsqldb.jdbc.Util.sqlException(Unknown Source)
[java] at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source)
[java] at org.hsqldb.jdbc.JDBCPreparedStatement.executeUpdate(Unknown Source)
[java] at org.parosproxy.paros.db.paros.ParosTableHistory.write(Unknown Source)

**Comment by kingthorin** [comment]
Any info on the size of the file? Number of requests? Size of responses?

**Comment by psiinon** [comment]
Which version of ZAP are you suing?
The latest version supports significantly larger data files by default.
You can increase the max size by increasing the 'SET FILES SCALE' line in your zapdb.script file: https://github.com/zaproxy/zaproxy/blob/develop/src/db/zapdb.script#L27

**Comment by kingthorin** [comment]
@lfatty any further details?
