### ISSUE TITLE
BackupFileDisclosure rule making too many requests?

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#2169]
Based on the stats/chart in http://zapbot.github.io/zap-mgmt-scripts/reports/wavsep-1.5-weekly-RBAJ-M-M.html it looks like the BackupFileDisclosure rule (https://github.com/zaproxy/zap-extensions/blob/master/addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/BackupFileDisclosure.java) is making too many requests.
This rule should be tested in isolation and the number of requests at each strength level checked

**Comment by kingthorin** [comment]
https://github.com/zaproxy/zap-extensions/wiki/AddOnsBeta now contains the reqs/strength guideline.

**Comment by kingthorin** [comment]
Did a quick test, with a single URL being Active Scanned:
```
225127 [AWT-EventQueue-0] INFO org.parosproxy.paros.core.scanner.Scanner  - scanner started
225142 [Thread-15] INFO org.parosproxy.paros.core.scanner.HostProcess  - Scanning 1 node(s) from http://localhost
225142 [Thread-15] INFO org.parosproxy.paros.core.scanner.HostProcess  - start host http://localhost | BackupFileDisclosure strength MEDIUM threshold MEDIUM
225830 [Thread-15] INFO org.parosproxy.paros.core.scanner.HostProcess  - completed host/plugin http://localhost | BackupFileDisclosure in 0.688s with 36 message(s) sent and 0 alert(s) raised.
225830 [Thread-15] INFO org.parosproxy.paros.core.scanner.HostProcess  - completed host http://localhost in 0.688s
225830 [Thread-14] INFO org.parosproxy.paros.core.scanner.Scanner  - scanner completed in 0.703s
```
So currently 36 reqs per URL at Medium strength. Which actually seems to align with:
https://github.com/zaproxy/zap-extensions/wiki/AddOnsBeta
<hr>

  * Active Scan rules will conform to the recommended strength settings (where relevant):
    * Low: up to around 6 requests / param / page
    * Medium: up to around 12 requests / param / page
    * High: up to around 24 requests / param / page
    * Insane: whatever ;)
    * Page level rules should equate to ~ 6 params (eg up to around 36 requests / page, etc)

<hr>

Given the logic this scanner employs I don't think this is too bad. Given the example in the original issue was 135k requests in 3m 16s.

**Comment by thc202** [comment]
What URL did you scan? Would you mind adding tests (similar to the ones in `TestPathTraversalUnitTest`)?

**Comment by kingthorin** [comment]
It was like http://localhost/test/index.html

Sure I can look into that.

**Comment by thc202** [comment]
Thanks!

**Comment by kingthorin** [comment]
Ok so the issue mentions a Medium-Medium run, which does result in 36 which I _think_ meets the guideline. However, the guidelines isn't specific enough or is misleading: If the page rule definition is 6 params (eg 36) is that Low strength?

Currently:
Low == 13
Medium == 36
High == 75
Insane == 457

**Comment by thc202** [comment]
Yes, the example seems to be for low.

Right, those numbers meet the guidelines, but in WAVSEP scan it doesn't (for 1240 URLs it should got to 135k?), it might have been changed in the meantime.

**Comment by kingthorin** [comment]
None of the wavsep weeklies seem to be running successfully anymore:
* https://github.com/zapbot/zap-mgmt-scripts/tree/gh-pages/reports 
* http://zapbot.github.io/zap-mgmt-scripts/scans.html

**Comment by kingthorin** [comment]
I finally got around to re-testing this, with https://hub.docker.com/r/owaspvwad/wavsep/.

![image](https://user-images.githubusercontent.com/7570458/81462440-87e51480-9180-11ea-9bd4-c5f51a62e92c.png)

69,000/1417=~49

I guess 1240 was the number of URLs the spider was finding back in 2018/2017. I'm not sure why more were found, but 69k is basically half of the 135k the original issue was opened for. Plus there's still this [discrepancy](https://github.com/zaproxy/zaproxy/issues/2169#issuecomment-384962320) of pages vs params.

`BackupFileDisclosureUnitTest` does now contain `shouldSendReasonableNumberOfMessages....()`tests which designates medium at 72 (6x12) which 49 is below.

I think we're safe to close this issue. @psiinon? @thc202?

**Comment by psiinon** [comment]
Fine by me :)

**Comment by thc202** [comment]
> Plus there's still this discrepancy of pages vs params.

Is there? The example being Low matches the number (the wiki can be updated to clarify that).

Closing per above comments.

**Comment by kingthorin** [comment]
For the record: [wiki page updated](https://github.com/zaproxy/zap-extensions/wiki/AddOnsBeta/_compare/5437f86c83b8b4295c0681c65910cc1f2f709b1c...4cfac33fc7806f4598699b1f5bd93eb66a1614b4).

**Comment by thc202** [comment]
Thank you!
