### ISSUE TITLE
Add-ons managed via api, cli

### ISSUE THREAD

**Issue by fulgore83** [zaproxy/zaproxy#2171]
Hello,

is any way to manage add-ons? I want to disable, enable and listing which add-on is actual used. Do You have any feature to manage whitout  UI?

And second question: do You have any examples how can I configure Policy via API? I ask because i dont have UI on my serwer (only cli).

Best regards
Grzegorz

**Comment by psiinon** [comment]
You can manage add-ons via the command-line.
If you run ZAP from the command-line with the '-h' option you should see the following options included:
	-addoninstall <addon>    Install the specified add-on from the ZAP Marketplace
	-addoninstallall         Install all available add-ons from the ZAP Marketplace
	-addonupdate             Update all changed add-ons from the ZAP Marketplace
We have plans to support add-on management via the API as per https://groups.google.com/d/msg/zaproxy-develop/g_IpUEFEj5o/yk1Gu7bqAQAJ but that hasnt been implemented yet.
Do those options provide what you need?  If not let us know what your requirements are on that thread.

Regarding configuring the policy via the API can you ask on the ZAP User Group explaining exactly what you want to do: http://groups.google.com/group/zaproxy-users thats probably a better forum for such questions :)

**Comment by fulgore83** [comment]
Thanks, i think is useful will be somethng like addonlist (list of addons) and addondelete (uninstall addon).

About Policy i try ask on zaproxy-users.

Thank You very much

**Comment by psiinon** [comment]
Yeah, those look like good additions to the comdline

**Comment by omerlh** [comment]
I have a similar issue - what about "warmup"? meaning, launching zap just to install all needed add-ons, and then turn it off. It is highly important when installing a lot of add-ons in docker env - the first time you launch Zap (which is every time, as it runs in a container) is very very slow (a couple of minutes). Does that make sense? I would like to try and implement it.

**Comment by thc202** [comment]
If I'm understanding correctly you can already achieve that with the `-cmd` line argument, once all the arguments (e.g. install add-ons) are processed ZAP exits. [1]

[1] https://github.com/zaproxy/zap-core-help/wiki/HelpCmdline

**Comment by omerlh** [comment]
Nice, I'll try that. Also, noticed that most of the time was on add-ons update - why is that? Isn't the docker image contains the latest versions of the add-ons?

**Comment by thc202** [comment]
Depends on the images, stable/bare does not have the latest versions just the ones included with ZAP at the time of the release (weekly and live do have the latest versions).

**Comment by omerlh** [comment]
yeah, that makes a lot of sense. Thanks!

**Comment by davidwestonuk2000** [comment]
@psiinon is there a way to install the openapi addon from local files rather than over the internet? In the environment where I am running my docker image I do not have connectivity to the internet.

**Comment by psiinon** [comment]
@davidwestonuk2000 please dont ask questions on issues, especially ones that have been closed for so long. The ZAP User Group is a much better option :) https://groups.google.com/group/zaproxy-users
