### ISSUE TITLE
ExpressionLanguageInjectionPlugin - Needs logging fix 

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#2174]
Based on https://groups.google.com/forum/#!topic/zaproxy-develop/kpxnenhuoJA & http://zapbot.github.io/zap-mgmt-scripts/reports/wavsep-1.5-weekly-RBAJ-M-M.logs.txt

The value injected by this scanner caused an invalid redirect response to be returned:

`8920966 [ZAP-ActiveScanner-0] ERROR org.zaproxy.zap.extension.ascanrulesBeta.ExpressionLanguageInjectionPlugin  - Expression Language Injection vulnerability check failed for parameter [target] and payload [${226260+938830}] due to an I/O error
org.apache.commons.httpclient.InvalidRedirectLocationException: Invalid redirect location: http://172.17.0.2:8080/wavsep/active/LFI/LFI-FalsePositives-GET/${226260+938830}
        at org.apache.commons.httpclient.HttpMethodDirector.processRedirectResponse(HttpMethodDirector.java:671)`

This could result depending on the processing of the website/webapp under many circumstances. If anything this is a core issue not a scanner issue.

`8968471 [ZAP-ActiveScanner-1] ERROR org.zaproxy.zap.extension.ascanrulesBeta.ExpressionLanguageInjectionPlugin  - Expression Language Injection vulnerability check failed for parameter [target] and payload [${622304+532696}] due to an I/O error
org.apache.commons.httpclient.URIException: Invalid authority
        at org.apache.commons.httpclient.URI.parseAuthority(URI.java:2236)`

Log output messages might need work (note [target] is consistent...might be param name, but also might be a static string). Also was authority broken on response or request?

**Comment by kingthorin** [comment]
Specifically this was from this iteration of the log: https://raw.githubusercontent.com/zapbot/zap-mgmt-scripts/2d6cc66d9b2e70f28008df95e7c9f3400c19a067/reports/wavsep-1.5-weekly-RBAJ-M-M.logs.txt

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#228.
