### ISSUE TITLE
SQLInjectionMySQL -  SocketException Connection resets

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#2178]
Based on https://groups.google.com/forum/#!topic/zaproxy-develop/kpxnenhuoJA & http://zapbot.github.io/zap-mgmt-scripts/reports/wavsep-1.5-weekly-RBAJ-M-M.logs.txt

> 6881922 [Thread-21] INFO org.parosproxy.paros.core.scanner.HostProcess  - start host http://172.17.0.2:8080 | SQLInjectionMySQL strength HIGH threshold MEDIUM
> 6898798 [HSQLDB Timer @5c065f2b] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - Checkpoint start
> 6898799 [HSQLDB Timer @5c065f2b] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - checkpointClose start
> 6898801 [HSQLDB Timer @5c065f2b] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - checkpointClose synched
> 6898812 [HSQLDB Timer @5c065f2b] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - checkpointClose script done
> 6898812 [HSQLDB Timer @5c065f2b] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - dataFileCache commit start
> 6899630 [HSQLDB Timer @5c065f2b] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - dataFileCache commit end
> 6899668 [HSQLDB Timer @5c065f2b] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - checkpointClose end
> 6899668 [HSQLDB Timer @5c065f2b] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - Checkpoint end - txts: 3065730
> 6900500 [ZAP-ActiveScanner-1] ERROR org.zaproxy.zap.extension.ascanrulesBeta.SQLInjectionMySQL  - An error occurred checking a url for MySQL SQL Injection vulnerabilities
> java.net.SocketException: Connection reset
> 	at java.net.SocketInputStream.read(SocketInputStream.java:196)
> 	at java.net.SocketInputStream.read(SocketInputStream.java:122)
> 	at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
> 	at java.io.BufferedInputStream.read(BufferedInputStream.java:254)
> 	at org.apache.commons.httpclient.HttpParser.readRawLine(HttpParser.java:78)
> 	at org.apache.commons.httpclient.HttpParser.readLine(HttpParser.java:106)
> 	at org.apache.commons.httpclient.HttpConnection.readLine(HttpConnection.java:1116)
> 	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.readLine(MultiThreadedHttpConnectionManager.java:1413)
> 	at org.apache.commons.httpclient.HttpMethodBase.readStatusLine(HttpMethodBase.java:2032)
> 	at org.zaproxy.zap.ZapGetMethod.readResponse(ZapGetMethod.java:88)
> 	at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1147)
> 	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:450)
> 	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:191)
> 	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
> 	at org.parosproxy.paros.network.HttpSender.executeMethod(HttpSender.java:307)
> 	at org.parosproxy.paros.network.HttpSender.runMethod(HttpSender.java:519)
> 	at org.parosproxy.paros.network.HttpSender.send(HttpSender.java:478)
> 	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(HttpSender.java:456)
> 	at org.parosproxy.paros.network.HttpSender.sendAndReceive(HttpSender.java:364)
> 	at org.parosproxy.paros.core.scanner.AbstractPlugin.sendAndReceive(AbstractPlugin.java:237)
> 	at org.parosproxy.paros.core.scanner.AbstractPlugin.sendAndReceive(AbstractPlugin.java:189)
> 	at org.zaproxy.zap.extension.ascanrulesBeta.SQLInjectionMySQL.scan(SQLInjectionMySQL.java:242)
> 	at org.parosproxy.paros.core.scanner.AbstractAppParamPlugin.scan(AbstractAppParamPlugin.java:245)
> 	at org.parosproxy.paros.core.scanner.AbstractAppParamPlugin.scanVariant(AbstractAppParamPlugin.java:173)
> 	at org.parosproxy.paros.core.scanner.AbstractAppParamPlugin.scan(AbstractAppParamPlugin.java:144)
> 	at org.parosproxy.paros.core.scanner.AbstractPlugin.run(AbstractPlugin.java:282)
> 	at java.lang.Thread.run(Thread.java:745)
> 6920598 [ZAP-ActiveScanner-1] ERROR org.zaproxy.zap.extension.ascanrulesBeta.SQLInjectionMySQL  - An error occurred checking a url for MySQL SQL Injection vulnerabilities
> java.net.SocketException: Connection reset
> 	at java.net.SocketInputStream.read(SocketInputStream.java:196)
> 	at java.net.SocketInputStream.read(SocketInputStream.java:122)
> 	at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
> 	at java.io.BufferedInputStream.read(BufferedInputStream.java:254)
> 	at org.apache.commons.httpclient.HttpParser.readRawLine(HttpParser.java:78)
> 	at org.apache.commons.httpclient.HttpParser.readLine(HttpParser.java:106)
> 	at org.apache.commons.httpclient.HttpConnection.readLine(HttpConnection.java:1116)
> 	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.readLine(MultiThreadedHttpConnectionManager.java:1413)
> 	at org.apache.commons.httpclient.HttpMethodBase.readStatusLine(HttpMethodBase.java:2032)
> 	at org.zaproxy.zap.ZapGetMethod.readResponse(ZapGetMethod.java:88)
> 	at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1147)
> 	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:450)
> 	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:191)
> 	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
> 	at org.parosproxy.paros.network.HttpSender.executeMethod(HttpSender.java:307)
> 	at org.parosproxy.paros.network.HttpSender.runMethod(HttpSender.java:519)
> 	at org.parosproxy.paros.network.HttpSender.send(HttpSender.java:478)
> 	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(HttpSender.java:456)
> 	at org.parosproxy.paros.network.HttpSender.sendAndReceive(HttpSender.java:364)
> 	at org.parosproxy.paros.core.scanner.AbstractPlugin.sendAndReceive(AbstractPlugin.java:237)
> 	at org.parosproxy.paros.core.scanner.AbstractPlugin.sendAndReceive(AbstractPlugin.java:189)
> 	at org.zaproxy.zap.extension.ascanrulesBeta.SQLInjectionMySQL.scan(SQLInjectionMySQL.java:242)
> 	at org.parosproxy.paros.core.scanner.AbstractAppParamPlugin.scan(AbstractAppParamPlugin.java:245)
> 	at org.parosproxy.paros.core.scanner.AbstractAppParamPlugin.scanVariant(AbstractAppParamPlugin.java:173)
> 	at org.parosproxy.paros.core.scanner.AbstractAppParamPlugin.scan(AbstractAppParamPlugin.java:144)
> 	at org.parosproxy.paros.core.scanner.AbstractPlugin.run(AbstractPlugin.java:282)
> 	at java.lang.Thread.run(Thread.java:745)
> 6978646 [ZAP-ActiveScanner-1] ERROR org.zaproxy.zap.extension.ascanrulesBeta.SQLInjectionMySQL  - An error occurred checking a url for MySQL SQL Injection vulnerabilities
> java.net.SocketException: Connection reset
> 	at java.net.SocketInputStream.read(SocketInputStream.java:196)
> 	at java.net.SocketInputStream.read(SocketInputStream.java:122)
> 	at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
> 	at java.io.BufferedInputStream.read(BufferedInputStream.java:254)
> 	at org.apache.commons.httpclient.HttpParser.readRawLine(HttpParser.java:78)
> 	at org.apache.commons.httpclient.HttpParser.readLine(HttpParser.java:106)
> 	at org.apache.commons.httpclient.HttpConnection.readLine(HttpConnection.java:1116)
> 	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.readLine(MultiThreadedHttpConnectionManager.java:1413)
> 	at org.apache.commons.httpclient.HttpMethodBase.readStatusLine(HttpMethodBase.java:2032)
> 	at org.zaproxy.zap.ZapGetMethod.readResponse(ZapGetMethod.java:88)
> 	at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1147)
> 	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:450)
> 	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:191)
> 	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
> 	at org.parosproxy.paros.network.HttpSender.executeMethod(HttpSender.java:307)
> 	at org.parosproxy.paros.network.HttpSender.runMethod(HttpSender.java:519)
> 	at org.parosproxy.paros.network.HttpSender.send(HttpSender.java:478)
> 	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(HttpSender.java:456)
> 	at org.parosproxy.paros.network.HttpSender.sendAndReceive(HttpSender.java:364)
> 	at org.parosproxy.paros.core.scanner.AbstractPlugin.sendAndReceive(AbstractPlugin.java:237)
> 	at org.parosproxy.paros.core.scanner.AbstractPlugin.sendAndReceive(AbstractPlugin.java:189)
> 	at org.zaproxy.zap.extension.ascanrulesBeta.SQLInjectionMySQL.scan(SQLInjectionMySQL.java:242)
> 	at org.parosproxy.paros.core.scanner.AbstractAppParamPlugin.scan(AbstractAppParamPlugin.java:245)
> 	at org.parosproxy.paros.core.scanner.AbstractAppParamPlugin.scanVariant(AbstractAppParamPlugin.java:173)
> 	at org.parosproxy.paros.core.scanner.AbstractAppParamPlugin.scan(AbstractAppParamPlugin.java:144)
> 	at org.parosproxy.paros.core.scanner.AbstractPlugin.run(AbstractPlugin.java:282)
> 	at java.lang.Thread.run(Thread.java:745)
> 7016029 [ZAP-ActiveScanner-0] ERROR org.zaproxy.zap.extension.alert.ExtensionAlert  - 
> java.lang.NullPointerException
> 7021240 [ZAP-ActiveScanner-1] ERROR org.zaproxy.zap.extension.alert.ExtensionAlert  - 
> java.lang.NullPointerException
> 7026439 [ZAP-ActiveScanner-1] ERROR org.zaproxy.zap.extension.alert.ExtensionAlert  - 
> java.lang.NullPointerException
> 7031236 [ZAP-ActiveScanner-0] ERROR org.zaproxy.zap.extension.alert.ExtensionAlert  - 
> java.lang.NullPointerException
> 7036274 [ZAP-ActiveScanner-0] ERROR org.zaproxy.zap.extension.alert.ExtensionAlert  - 
> java.lang.NullPointerException
> 7046655 [ZAP-ActiveScanner-1] ERROR org.zaproxy.zap.extension.alert.ExtensionAlert  - 
> java.lang.NullPointerException
> 7051873 [ZAP-ActiveScanner-1] ERROR org.zaproxy.zap.extension.alert.ExtensionAlert  - 
> java.lang.NullPointerException
> 7056474 [ZAP-ActiveScanner-0] ERROR org.zaproxy.zap.extension.alert.ExtensionAlert  - 
> java.lang.NullPointerException
> 7057069 [ZAP-ActiveScanner-1] ERROR org.zaproxy.zap.extension.alert.ExtensionAlert  - 
> java.lang.NullPointerException
> 7071672 [ZAP-ActiveScanner-0] ERROR org.zaproxy.zap.extension.alert.ExtensionAlert  - 
> java.lang.NullPointerException
> 7072272 [ZAP-ActiveScanner-1] ERROR org.zaproxy.zap.extension.alert.ExtensionAlert  - 
> java.lang.NullPointerException
> 7087282 [ZAP-ActiveScanner-1] ERROR org.zaproxy.zap.extension.alert.ExtensionAlert  - 
> java.lang.NullPointerException
> 7091692 [ZAP-ActiveScanner-0] ERROR org.zaproxy.zap.extension.alert.ExtensionAlert  - 
> java.lang.NullPointerException
> 7092294 [ZAP-ActiveScanner-1] ERROR org.zaproxy.zap.extension.alert.ExtensionAlert  - 
> java.lang.NullPointerException

SNIP (lots of the same)

> 8098080 [ZAP-ActiveScanner-1] ERROR org.zaproxy.zap.extension.alert.ExtensionAlert  - 
> java.lang.NullPointerException
> 8118128 [ZAP-ActiveScanner-1] ERROR org.zaproxy.zap.extension.alert.ExtensionAlert  - 
> java.lang.NullPointerException
> 8118128 [Thread-21] INFO org.parosproxy.paros.core.scanner.HostProcess  - completed host/plugin http://172.17.0.2:8080 | SQLInjectionMySQL in 1236.206s

**Comment by kingthorin** [comment]
Specifically this was from this iteration of the log: https://raw.githubusercontent.com/zapbot/zap-mgmt-scripts/2d6cc66d9b2e70f28008df95e7c9f3400c19a067/reports/wavsep-1.5-weekly-RBAJ-M-M.logs.txt

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#236.
