### ISSUE TITLE
SQLInjectionPostgresql - SocketException Connection reset

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#2179]
Based on https://groups.google.com/forum/#!topic/zaproxy-develop/kpxnenhuoJA & http://zapbot.github.io/zap-mgmt-scripts/reports/wavsep-1.5-weekly-RBAJ-M-M.logs.txt

> 8420797 [Thread-21] INFO org.parosproxy.paros.core.scanner.HostProcess  - start host http://172.17.0.2:8080 | SQLInjectionPostgresql strength HIGH threshold MEDIUM
> 8423145 [ZAP-ActiveScanner-1] ERROR org.zaproxy.zap.extension.ascanrulesBeta.SQLInjectionPostgresql  - An error occurred checking a url for POSTGRES SQL Injection vulnerabilities
> java.net.SocketException: Connection reset
> 	at java.net.SocketInputStream.read(SocketInputStream.java:196)
> 	at java.net.SocketInputStream.read(SocketInputStream.java:122)
> 	at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
> 	at java.io.BufferedInputStream.read(BufferedInputStream.java:254)
> 	at org.apache.commons.httpclient.HttpParser.readRawLine(HttpParser.java:78)
> 	at org.apache.commons.httpclient.HttpParser.readLine(HttpParser.java:106)
> 	at org.apache.commons.httpclient.HttpConnection.readLine(HttpConnection.java:1116)
> 	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.readLine(MultiThreadedHttpConnectionManager.java:1413)
> 	at org.apache.commons.httpclient.HttpMethodBase.readStatusLine(HttpMethodBase.java:2032)
> 	at org.zaproxy.zap.ZapGetMethod.readResponse(ZapGetMethod.java:88)
> 	at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1147)
> 	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:450)
> 	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:191)
> 	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
> 	at org.parosproxy.paros.network.HttpSender.executeMethod(HttpSender.java:307)
> 	at org.parosproxy.paros.network.HttpSender.runMethod(HttpSender.java:519)
> 	at org.parosproxy.paros.network.HttpSender.send(HttpSender.java:478)
> 	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(HttpSender.java:456)
> 	at org.parosproxy.paros.network.HttpSender.sendAndReceive(HttpSender.java:364)
> 	at org.parosproxy.paros.core.scanner.AbstractPlugin.sendAndReceive(AbstractPlugin.java:237)
> 	at org.parosproxy.paros.core.scanner.AbstractPlugin.sendAndReceive(AbstractPlugin.java:189)
> 	at org.zaproxy.zap.extension.ascanrulesBeta.SQLInjectionPostgresql.scan(SQLInjectionPostgresql.java:246)
> 	at org.parosproxy.paros.core.scanner.AbstractAppParamPlugin.scan(AbstractAppParamPlugin.java:245)
> 	at org.parosproxy.paros.core.scanner.AbstractAppParamPlugin.scanVariant(AbstractAppParamPlugin.java:173)
> 	at org.parosproxy.paros.core.scanner.AbstractAppParamPlugin.scan(AbstractAppParamPlugin.java:144)
> 	at org.parosproxy.paros.core.scanner.AbstractPlugin.run(AbstractPlugin.java:282)
> 	at java.lang.Thread.run(Thread.java:745)
> 8505699 [HSQLDB Timer @5c065f2b] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - Checkpoint start
> 8505699 [HSQLDB Timer @5c065f2b] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - checkpointClose start
> 8505702 [HSQLDB Timer @5c065f2b] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - checkpointClose synched
> 8505706 [HSQLDB Timer @5c065f2b] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - checkpointClose script done
> 8505707 [HSQLDB Timer @5c065f2b] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - dataFileCache commit start
> 8506432 [HSQLDB Timer @5c065f2b] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - dataFileCache commit end
> 8506494 [HSQLDB Timer @5c065f2b] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - checkpointClose end
> 8506495 [HSQLDB Timer @5c065f2b] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - Checkpoint end - txts: 3603874
> 8572148 [Thread-21] INFO org.parosproxy.paros.core.scanner.HostProcess  - completed host/plugin http://172.17.0.2:8080 | SQLInjectionPostgresql in 151.351s

**Comment by kingthorin** [comment]
Specifically this was from this iteration of the log: https://raw.githubusercontent.com/zapbot/zap-mgmt-scripts/2d6cc66d9b2e70f28008df95e7c9f3400c19a067/reports/wavsep-1.5-weekly-RBAJ-M-M.logs.txt

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#236.
