### ISSUE TITLE
UsernameEnumeration - Overly verbose?

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#2180]
Based on https://groups.google.com/forum/#!topic/zaproxy-develop/kpxnenhuoJA & http://zapbot.github.io/zap-mgmt-scripts/reports/wavsep-1.5-weekly-RBAJ-M-M.logs.txt

Perhaps a mechanism for scanners to self disable is needed? (Idea added to group thread linked above).

> 9564386 [Thread-21] INFO org.parosproxy.paros.core.scanner.HostProcess  - start host http://172.17.0.2:8080 | UsernameEnumeration strength HIGH threshold MEDIUM
> 9564387 [ZAP-ActiveScanner-0] INFO org.zaproxy.zap.extension.ascanrulesBeta.UsernameEnumeration  - For the Username Enumeration scanner to actually scan this URL, the URL *must* be added to a context, and flagged as the login request in that context!
> 9564387 [ZAP-ActiveScanner-0] INFO org.zaproxy.zap.extension.ascanrulesBeta.UsernameEnumeration  - For the Username Enumeration scanner to actually scan this URL, the URL *must* be added to a context, and flagged as the login request in that context!
> 9564387 [ZAP-ActiveScanner-1] INFO org.zaproxy.zap.extension.ascanrulesBeta.UsernameEnumeration  - For the Username Enumeration scanner to actually scan this URL, the URL *must* be added to a context, and flagged as the login request in that context!
> 9564588 [ZAP-ActiveScanner-0] INFO org.zaproxy.zap.extension.ascanrulesBeta.UsernameEnumeration  - For the Username Enumeration scanner to actually scan this URL, the URL *must* be added to a context, and flagged as the login request in that context!
> 9564589 [ZAP-ActiveScanner-0] INFO org.zaproxy.zap.extension.ascanrulesBeta.UsernameEnumeration  - For the Username Enumeration scanner to actually scan this URL, the URL *must* be added to a context, and flagged as the login request in that context!
> 9564589 [ZAP-ActiveScanner-0] INFO org.zaproxy.zap.extension.ascanrulesBeta.UsernameEnumeration  - For the Username Enumeration scanner to actually scan this URL, the URL *must* be added to a context, and flagged as the login request in that context!
> 9564589 [ZAP-ActiveScanner-0] INFO org.zaproxy.zap.extension.ascanrulesBeta.UsernameEnumeration  - For the Username Enumeration scanner to actually scan this URL, the URL *must* be added to a context, and flagged as the login request in that context!
> 9564589 [ZAP-ActiveScanner-0] INFO org.zaproxy.zap.extension.ascanrulesBeta.UsernameEnumeration  - For the Username Enumeration scanner to actually scan this URL, the URL *must* be added to a context, and flagged as the login request in that context!

SNIP (lots of the same)

> 9584224 [ZAP-ActiveScanner-0] INFO org.zaproxy.zap.extension.ascanrulesBeta.UsernameEnumeration  - For the Username Enumeration scanner to actually scan this URL, the URL *must* be added to a context, and flagged as the login request in that context!
> 9584224 [ZAP-ActiveScanner-0] INFO org.zaproxy.zap.extension.ascanrulesBeta.UsernameEnumeration  - For the Username Enumeration scanner to actually scan this URL, the URL *must* be added to a context, and flagged as the login request in that context!
> 9584225 [ZAP-ActiveScanner-1] INFO org.zaproxy.zap.extension.ascanrulesBeta.UsernameEnumeration  - For the Username Enumeration scanner to actually scan this URL, the URL *must* be added to a context, and flagged as the login request in that context!
> 9584225 [Thread-21] INFO org.parosproxy.paros.core.scanner.HostProcess  - completed host/plugin http://172.17.0.2:8080 | UsernameEnumeration in 19.839s

**Comment by kingthorin** [comment]
I've got a patch ready for this. Pending acceptance of https://github.com/zaproxy/zap-extensions/pull/202 (so that I don't have to fight with rebases or merges :wink:)

**Comment by thc202** [comment]
OK :)

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#208.
