### ISSUE TITLE
Implement forced user capability for the Ant API

### ISSUE THREAD

**Issue by AlbertTresens** [zaproxy/zaproxy#2187]
The current implementation of the Ant API does not support the "forced user" authentication capability for Ant tasks which restricts the discovery phase on automatic logouts. Extend the Ant API to support an Ant task to enable "forced user" so spider and ajax spider can be user authenticated user on logout.

**Comment by kingthorin** [comment]
Can this be closed?

**Comment by psiinon** [comment]
Yeah, we no longer support the Ant API.
