### ISSUE TITLE
Enable/Disable Script Causes Save Prompt on Exit

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#2189]
To recreate (this should occur in either 2.4.3 or Dev w/ Script Console v15):
0. This assumes you have a script saved.
1. Launch ZAP.
2. Goto the Scripts tab (tree).
3. Enable or Disable a script (don't touch the Script Console tab at all).
4. Exit ZAP.
5. Note that ZAP asks to save changes to the script, though nothing was actually changed. (If you choose to discard the changes the enabled/disabled state is in fact discarded, however checking the actual script file before and after reveals no change in checksum.)

**Comment by thc202** [comment]
Right, that's expected. ZAP will (also) warn that the script has unsaved changes if one of its properties (name, description, enabled state, load on start...) was not (yet) saved, otherwise the changes would be lost without warning.
Maybe the message should be explicit on what was not saved?

**Comment by kingthorin** [comment]
For my 2 cents the properties and state should just be set (saved) when set, just like everything in the Tools:Options elements/attributes.

**Comment by thc202** [comment]
Yeah, makes sense. So, only the contents of the script would not be persisted when changed?

**Comment by kingthorin** [comment]
Yes if you'd actually changed the script not saved and discarded on exit, then your changes would be lost.
