### ISSUE TITLE
Sequence extension has no help resources

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#2191]
Source seems to lack help: https://github.com/zaproxy/zap-extensions/tree/alpha/src/org/zaproxy/zap/extension/sequence

Can't find anything on any of the wikis.

**Comment by psiinon** [comment]
Yeah, help is not (currently) a requirement for alpha add-ons, although its always very useful ;)

**Comment by kingthorin** [comment]
Might need to scrape some content from here:
https://zapmultistep.wordpress.com/

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#885.

**Comment by thc202** [comment]
Released in version 4 of Sequence add-on.
