### ISSUE TITLE
Raise a site level alert for http sites

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#2207]
We should report any sites that support http (at a site level, ie just one alert at the top of the site).
This can be done passively as we already have a rule for detecting https pages that are also accessible via http

**Comment by DarkPrince304** [comment]
I would like to look into this. Can you guide me more about this? 

Also how does ZAP detect https page

**Comment by kingthorin** [comment]
There was some discussion of this via email. It landed on the following idea:

> "...we could do somewhat the opposite of the [existing active check](https://github.com/zaproxy/zap-extensions/blob/alpha/src/org/zaproxy/zap/extension/ascanrulesAlpha/HttpsAsHttpScanner.java). Create an AbstractHostPlugin if something is accessed via http try https, if https doesn't work then alert."

**Comment by kingthorin** [comment]
Completed via https://github.com/zaproxy/zap-extensions/commit/b765ecf8237a198b28ee39a4c9332420279c5b6a
