### ISSUE TITLE
Apply for Google Summer of Code 2016

### ISSUE THREAD

**Issue by javabeanz** [zaproxy/zaproxy#2219]
with Google Summerof Code, tasks of selected open source projects get done by students (and they get some payment for that if i am not mistaken). Deadline for 2016 is 19 Feb 2016 !
https:/g.co/gsoc

**Comment by psiinon** [comment]
Both OWASP and Mozilla will be applying - hopefully at least one of them will get accepted this year and we can apply for projects via both. I think they're more likely to be accepted than ZAP going it alone (but I could be wrong).

**Comment by javabeanz** [comment]
ok, didnt know that. FOSDEM has a stand for the Google Code of Summer and it sounded like something interesting for ZAP.

**Comment by psiinon** [comment]
You can see some of the projects from previous years under https://github.com/zaproxy/zaproxy/wiki/GSoC on the wiki eg https://github.com/zaproxy/zaproxy/wiki/GSoC2012 :)

**Comment by kingthorin** [comment]
https://github.com/zaproxy/zaproxy/wiki/GSoC2013
https://github.com/zaproxy/zaproxy/wiki/GSoC2014
https://github.com/zaproxy/zaproxy/wiki/GSoC2015

**Comment by thc202** [comment]
And https://github.com/zaproxy/zaproxy/wiki/GSoC2016 :)

**Comment by javabeanz** [comment]
nice ! do you have some tasks in mind yet ? could we suggest the ZAAS maybe
?

**Comment by psiinon** [comment]
The list we've put together is on the OWASP wiki: https://www.owasp.org/index.php/GSOC2016_Ideas#OWASP_ZAP but students can suggest their own as well.
We didnt include ZaaS as thats too big for a single student project, but I'd definitely be interested in if students proposed anything that could be part of ZaaS :)

**Comment by javabeanz** [comment]
yeah I guess you're right. Do you have some idea for an aorchitecture yet ?

**Comment by kingthorin** [comment]
Could we move this discussion to the dev group [1] please? The issue tracker isn't really an appropriate venue.

[1] https://groups.google.com/forum/#!forum/zaproxy-develop
