### ISSUE TITLE
Fuzzer: option to search for payload names

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#2227]
The fuzzer supports _lots_ of payloads now, esp if you install some of the ones from the marketplace.
It would be really useful to have an option to search the payload names for a string - I knew there was a list of common debug params and ended up having to google for it.
Turns out they wre in: fuzzdb/attack-payloads/BizLogic/DebugParams.fuzz.txt
If there was a case insensitive search option I'd have been able to find it within ZAP by just searching for 'debug' ;)

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#443.

**Comment by thc202** [comment]
Released in version 6 of Fuzzer add-on.
