### ISSUE TITLE
Weak Auth Passive Scanner - Evidence vs Attack

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#2230]
The Weak Authentication Passive Scanner seems to list Attack quoting the relevant header instead of Evidence. It is also missing an associated WASC ID.

![weak_auth](https://cloud.githubusercontent.com/assets/7570458/12905725/8917d5e0-cea7-11e5-96c7-6b1f8897b478.png)

Should probably be WASC-01 : Insufficient Authentication or WASC-04 : Insufficient Transport Layer Protection: http://projects.webappsec.org/w/page/13246975/Threat%20Classification%20Taxonomy%20Cross%20Reference%20View

**Comment by DarkPrince304** [comment]
https://github.com/zaproxy/zap-extensions/blob/beta/src/org/zaproxy/zap/extension/pscanrulesBeta/InsecureAuthenticationScan.java

Is this the scanner in question here?

**Comment by kingthorin** [comment]
Yes that's the one. Note the WASC ID was already corrected in https://github.com/zaproxy/zap-extensions/commit/6acf57e8133e8591f54cc37469d0b0e678d41c8c, however the attack vs. evidence issue remains.

**Comment by DarkPrince304** [comment]
Is it so that "WWW-Authenticate: Basic realm="test realm:" should've been in Evidence? Since its passive scanning its only natural to show the evidence I guess.

**Comment by thc202** [comment]
Yes, passive scanners should not set the "attack" only the "evidence", if any.
Passive scanners don't perform any attack.

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#271.
