### ISSUE TITLE
Zaproxy Start Crash intel_set_pch_fifo_underrun_reporting

### ISSUE THREAD

**Issue by rioasmara** [zaproxy/zaproxy#2236]
Hi, 

I am using kali linux rolling that update the all package every morning from the repository. I found lately whenever I start zaproxy, After the splash screen finish load all the module then it crash. 

[ 1500.503730] [drm:intel_set_pch_fifo_underrun_reporting [i915]] *ERROR* uncleared pch fifo underrun on pch transcoder A
[ 1500.503746] [drm:cpt_irq_handler [i915]] *ERROR* PCH transcoder A FIFO underrun
[ 1500.519051] [drm:intel_set_cpu_fifo_underrun_reporting [i915]] *ERROR* uncleared fifo underrun on pipe B
[ 1500.519068] [drm:ironlake_irq_handler [i915]] *ERROR* CPU pipe B FIFO underrun

![img_20160213_081503](https://cloud.githubusercontent.com/assets/17211692/13025332/b38041f0-d23f-11e5-86b6-0f1e5955ce09.jpg)

**Comment by kingthorin** [comment]
You'lol need to report that to the kali team.
