### ISSUE TITLE
Core Help - Alerts Topic needs update

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#2243]
https://github.com/zaproxy/zap-core-help/wiki/HelpStartConceptsAlerts

Should mention passive scan, add-ons/extensions, and scripts can also raise alerts.

**Comment by thc202** [comment]
Also https://github.com/zaproxy/zap-core-help/wiki/HelpUiTabsAlerts
> Alerts can either be raised by Automated scanning or manually via the History tab.

To avoid redundancy/duplication I think the above phrase should be deleted, that's already (or should be) explained in the concepts page (already linked).
