### ISSUE TITLE
Regex Payload Causes ZAP to hang

### ISSUE THREAD

**Issue by xeno6696** [zaproxy/zaproxy#2247]
I decided to fuzz a JSESSIONID to try it out.  

For the regex, I used `[A-F0-9]{32}`, had a Max Payloads of 1000, and a max length of Zero.  When I click "Add," the application hangs.

**Comment by thc202** [comment]
That should be fixed (#1884) with latest version of fuzzer add-on (version 4).
Could you try with latest version? [1]

[1] https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsManageaddons

**Comment by kingthorin** [comment]
@xeno6696 can you confirm if this was fixed in v4 of the fuzzer add-on?

**Comment by xeno6696** [comment]
I will check in the morning, sorry for the wait!

**Comment by xeno6696** [comment]
Confirmed that this was closed by ZAP release 2.4.3.

**Comment by thc202** [comment]
Thanks for lettings us known.
