### ISSUE TITLE
command line version of owasp-zaproxy

### ISSUE THREAD

**Issue by skzaproxy** [zaproxy/zaproxy#2252]
Please let me know the installation steps and asample on how to use it to test a web server.

**Comment by skzaproxy** [comment]
base = 'http://zap/JSON/' in "python-owasp-zap-v2.4-0.0.7\src\zapv2" , base is not accessible. is the link changed.

**Comment by psiinon** [comment]
Please ask questions on the ZAP User Group: http://groups.google.com/group/zaproxy-users
Issues are for bugs and enhancements.

**Comment by skzaproxy** [comment]
Thanks.
