### ISSUE TITLE
ZAP in daemon mode does not respect settings in config.xml

### ISSUE THREAD

**Issue by AlbertTresens** [zaproxy/zaproxy#2253]
My ZAP is launched with the following command from Jenkins:

/opt/ZAP_2.4.3/zap.sh -daemon -host localhost -port 8500 -config api.key=ZAPROXY-PLUGIN -config scanner.defaultPolicy=InjectionPolicy.policy

which means that will use the default ~/.ZAP directory where the config.xml lives and have the pscans set  OFF :
```
<pscanrules>
<ApplicationErrorScanner>
<enabled>false</enabled>
<level>OFF</level>
</ApplicationErrorScanner>
<CacheControlScanner>
<enabled>false</enabled>
<level>OFF</level>
</CacheControlScanner>
<ContentTypeMissingScanner>
<enabled>false</enabled>
<level>OFF</level>
</ContentTypeMissingScanner>
<CookieHttpOnlyScanner>
<enabled>false</enabled>
<level>OFF</level>
</CookieHttpOnlyScanner>
<CookieSecureFlagScanner>
<enabled>false</enabled>
<level>OFF</level>
</CookieSecureFlagScanner>
<CrossDomainScriptInclusionScanner>
<enabled>false</enabled>
<level>OFF</level>
</CrossDomainScriptInclusionScanner>
<HeaderXssProtectionScanner>
<enabled>false</enabled>
<level>OFF</level>
</HeaderXssProtectionScanner>
<MixedContentScanner>
<enabled>false</enabled>
<level>OFF</level>
</MixedContentScanner>
<PasswordAutocompleteScanner>
<enabled>false</enabled>
<level>OFF</level>
</PasswordAutocompleteScanner>
<TestInfoPrivateAddressDisclosure>
<enabled>false</enabled>
<level>OFF</level>
</TestInfoPrivateAddressDisclosure>
<TestInfoSessionIdURL>
<enabled>false</enabled>
<level>OFF</level>
</TestInfoSessionIdURL>
<XContentTypeOptionsScanner>
<enabled>false</enabled>
<level>OFF</level>
</XContentTypeOptionsScanner>
<XFrameOptionScanner>
<enabled>false</enabled>
<level>OFF</level>
</XFrameOptionScanner>
</pscanrules>
```
I created a policy that only runs injection attacks as you can see in the launch command parameters.

However the final report contains pscan alerts such:

X-Frame-Options Header Not Set
Application Error Disclosureror Disclosure
Web Browser XSS Protection Not Enabled
X-Content-Type-Options Header Missing
Password Autocomplete in browser
Private IP Disclosure

which i would expect not to be listed with the config.xml setup i listed.

**Comment by kingthorin** [comment]
You mentioned creating a policy that runs only injection attacks, which means Active scanning. But then listed a bunch of results from the passive scanner.

Have you persisted a session that already has passive results?

**Comment by AlbertTresens** [comment]
Yes, I was trying to run a scan with ZAP in daemon mode from Jenkins that would only run a set of Injection active rules defined in the policy file. I wanted to disable all the passive scans as they are mostly false positives. 
To do so I persisted the changes using the UI, and I can see them in the config.xml file stored in the ~/.ZAP directory as you can see in my pasted blob. All passive scans are OFF. 
However, when I run ZAP in daemon mode again, the final report contains passive scan positives. I would expect it uses the config.xml in the ~/.ZAP directory and therefore non of the pscan rules. 

How can I configure ZAP in daemon to not run any of the passive scans? 
Can i use the -conf parameter? If so, which value would dissable all pscans?

**Comment by thc202** [comment]
What's the location of `~/.ZAP` when running from Jenkins? Is it the same location where you have the `config.xml` file?
For example, in my system Jenkins home is at `/var/lib/jenkins/` and the ZAP home directory is created there (`/var/lib/jenkins/.ZAP/`).

**Comment by AlbertTresens** [comment]
Yes indeed jenkins creates his own config.xml. So that would fix the issue. 
As i was explicitly giving the config.xml in the plugin I was assuming that was the one being used. 
So seems the config.xml is respected in that case.

**Comment by psiinon** [comment]
Thanks for letting us know :)
