### ISSUE TITLE
ZAP 2.4.3 in contention with WebGoat 7.0 (Tomcat?) for JVM_BIND address

### ISSUE THREAD

**Issue by sierratango68** [zaproxy/zaproxy#2256]
In Windows 7 SP1 
Firefox 44.0.2
ZAP 2.4.3
webgoat-container-7.0-SNAPSHOT-war-exec.jar
Apache Tomcat 7.0.59 (comes with WebGoat)
jre 1.8.0_73

If I start WebGoat first and then start ZAP, I get an error:
 'An error occurred while starting the proxy:
Address already in use: JVM_BIND'
Clicking OK on the error results in WebGoat not going through the zap proxy.

I have also tried:
Start Zap first, then start WebGoat.
This causes Apache server to fail.

It seems that there is some sort of resource conflict.

**Comment by kingthorin** [comment]
Start zap reconfigure your local proxy settings (port), restart zap, start webgoat.

**Comment by sierratango68** [comment]
I have already done the proxy setup as below:
ZAP
Address: localhost
Port:8080

Firefox:
Http Proxy: localhost
port: 8080
use this proxy for all protocols: checked
