### ISSUE TITLE
Better description minimum required eclipse version, dependencies

### ISSUE THREAD

**Issue by ossecsoft** [zaproxy/zaproxy#2257]
On page
https://github.com/zaproxy/zaproxy/wiki/Building#eclipse---quick-set-up

It should at least state a minimum version of Eclipse that is required or which plug-ins are required. For example:
1. Ensure you have a version of Eclipse 4.2 or later installed or if using an earlier version, the "EGit - Git Team Provider" plug-in installed.

​

**Comment by kingthorin** [comment]
The page you mentioned specifically links to lunasr2 which specifically includes 'Eclipse Git Team Provider'. 

There's also (work in progress):
https://github.com/zaproxy/zaproxy/wiki/Setting-up-and-developing-new-plugins

**Comment by kingthorin** [comment]
https://groups.google.com/forum/m/#!topic/zaproxy-develop/bWFp7Nx1TBU

I'll look at making the wiki a bit more userfriendly.

**Comment by thc202** [comment]
Maybe it should be explicitly mentioned somewhere (CONTRIBUTING.md?) that anyone (with a GitHub account) can edit zaproxy's wiki:
https://help.github.com/articles/editing-wiki-pages-via-the-online-interface/
https://help.github.com/articles/adding-and-editing-wiki-pages-locally/

**Comment by thc202** [comment]
Should this issue be closed with the changes done to the wiki? It was not closed automatically.

**Comment by kingthorin** [comment]
Yup :smiley:
