### ISSUE TITLE
Close all resources (files and sockets) on shutdown

### ISSUE THREAD

**Issue by javabeanz** [zaproxy/zaproxy#2258]
Using the https://github.com/continuumsecurity/bdd-security tests, when you press control-c to stop the tests, the Java process holds on to a lot of /tmp files that ZAP uses. Maybe we can solve this by implementing a ShutdownHook and looking for open filehandles/sockets. with JDK  7, there is also a try-with-resources formula that should work.

**Comment by thc202** [comment]
Could you provide more details on those temporary files? Name, contents....
Also, is ZAP not closing/finishing?

**Comment by javabeanz** [comment]
good point; the java.exe is hanging, because zap holds on to the log file
zap.log and the session folder

**Comment by thc202** [comment]
Are you sure that ZAP is really killed when that happens? (e.g. the tests might spawn other Java process for ZAP than the one being killed)
For example, if I Ctrl+C the zap.bat (more precisely, the java process initiated by zap.bat) the process does not hang.

**Comment by javabeanz** [comment]
in my case, zap is started from an Ant build process. The hanging process
is over 300MB big and holds the files mentioned, that is very likely the
ZAP process.

**Comment by thc202** [comment]
Not saying that it is not ZAP, just want to know/make sure that ZAP is being stopped (and not left running normally).
Could you check if the ZAP API is still accessible when that happens?

**Comment by thc202** [comment]
@javabeanz any comment on the above?

**Comment by javabeanz** [comment]
I can't remember how I reproduced this bug; maybe it would suffice now to
revisit the client api and check for connection leaks. JDK 7 has the new
try-with-resources construct, so this can be solved quite elegantly.
