### ISSUE TITLE
ZAP 2.4.3 crashing within Kali Linux

### ISSUE THREAD

**Issue by griddd** [zaproxy/zaproxy#2260]
Yesterday, I did an apt-get update && apt-get dist-upgrade, and ZAP now fails to work.

The UI loads, but when the progress bar fills, the screen goes black and I get forcibly logged out.  I log back in (as root), and start ZAP again.  As before, the UI loads and the progress bar fills.  At this point, the screen goes black and is replaced by the following message "Error in /usr/lib/xorg/Xorg free() corrupted unsorted chunks: 0x0000559937b40f20"  The system is completely hung at this point, and I have to power off the box.

I'm running the latest version of Kali Linux (Kali Rolling 2016.1).  Results of uname -a are below:
`Linux kali 4.3.0-kali1-amd64 #1 SMP Debian 4.3.5-1kali1 (2016-02-11) x86_64 GNU/Linux`

Thanks for any help you can provide.  A similar issue has been entered on the bugs.kali.org website.

**Comment by psiinon** [comment]
This is unlikely to be a ZAP issue, so the Kali bug will probably be your best bet, but we'll keep this open until its resolved.
Out of interest, what variant of Java and what version are you using?

**Comment by kingthorin** [comment]
https://bugs.kali.org/view.php?id=3067

**Comment by griddd** [comment]
Thanks for the quick reply, guys!  Psiinon, here's what dpkg --list has to say about the java stuff in Kali:
java-common  0.52.1      
java-wrappers 0.1.28   
libservlet2.5-java 6.0.41-4    
libhsqldb1.8.0-java 1.8.0.10+dfsg-5
libreoffice-java-common 1:5.0.5~rc2-1

Kingthorin, that's the Kali bug I was mentioning.  The behavior reported by rioasmara is very similar to what I'm seeing.  The Kali team hasn't yet responded to the bug you referenced.

**Comment by ElColmo** [comment]
Normally, you should do "apt-get upgrade", rather than "apt-get dist-upgrade" in Kali, since "apt-get dist-upgrade" risks breaking the installation.

If you fire up either the "synaptic" or "aptitude" GUIs in Kali, do you get any warnings about broken packages, or anything of that nature? If so, fixing those issues would be a good place to start.

The upgrade from Kali 2.0 to Kali 2.0 rolling seems to be plagued by broken X issues.. Is that what you were trying to do?  

So, almost certainly not a ZAP issue, in my view (I use both ZAP and Kali 2.0 rolling daily, BTW).

**Comment by griddd** [comment]
Thanks for the info, ElColmo.  I've typically done apt-get dist-upgrade, but after recent events, I'll switch to running apt-get upgrade.

Just ran the aptitude GUI, no warnings listed there.  I don't have the synaptic GUI package manager installed.

**Comment by griddd** [comment]
I did an apt-get update && apt-get dist-upgrade this morning. There was an update to X in the repos. After installing the updates, ZAP seems to be functioning normally.  I've noted this at https://bugs.kali.org/view.php?id=3067 and asked the Kali team to confirm.

**Comment by thc202** [comment]
Thanks for letting us know.

Should this issue be closed now?

**Comment by griddd** [comment]
No problem, thc202.

Yes, the update to X in the Kali repos seems to have resolved the issue.
