### ISSUE TITLE
A XSS is not detect by ActiveScan - False Negative

### ISSUE THREAD

**Issue by g-sato** [zaproxy/zaproxy#2279]
Hello zap team,

Thank you for making this useful tool.

I found a probrem that a simple XSS is not detect by OWASP ZAP ActiveScan.

［Steps to reproduce］

1) make a php file below.

zaptest.php
`<?php`
`print_r($_GET);`

2) put zaptest.php to web server.

3) access to zaptest.php with some url parameter.

example:

> http://localhost/zaptest.php?param=123

response:

> HTTP/1.1 200 OK
> Date: Sun, 28 Feb 2016 17:12:29 GMT
> Server: Apache/2.4.12 (Win32) OpenSSL/1.0.1l PHP/5.6.8
> X-Powered-By: PHP/5.6.8
> Content-Length: 29
> Keep-Alive: timeout=5, max=76
> Connection: Keep-Alive
> Content-Type: text/html; charset=UTF-8
> 
> Array
> (
>     [param] => 123
> )

4) run zaproxy-w2016-02-22 (Weekly Build), and install all release level add-on.

5) Do active scan to URL: http://localhost/zaptest.php?param=123.
(Input vectors = URL Quary String, Policy = All Default)

XSS vulnerabilitiy is not detect.

(There is simple XSS :
`http://localhost/zaptest.php?param=<script>alert(1)</script>`)

OWASP ZAP 2.4.3 stable has same problem.

Regards.

**Comment by psiinon** [comment]
The Reflected and Persistent XSS rules work by analysing where user input is reflected in HTML and then targeting those locations.
It doesnt look like your page is actually returning HTML - there are no HTML tags :)
If you changed it to something like:
`<head><title>test</title></head><body><?php print_r($_GET);</body>`
then I'd expect these rules to detect it.
Note that the DOM XSS rule works by launching browsers - I'd hope that this rule will detect this vulnerability.

Cheers,

Simon

**Comment by g-sato** [comment]
Thank you for answering my question.

I edited zaptest.php as below, the Reflected XSS is detected by ActiveScan.

zaptest.php
-------------------------------------
<html>
<body>
<?php
print_r($_GET);
?>
</body></html>
-------------------------------------

But I think there are not a few cases of user input is reflected outside HTML (Ex.SystemError dump).
I think Activescan can't detect XSS located outside HTML is bug, it should be detected by regular Reflected XSS rule.

For Example, this HTTP Response shows alert dialog on Firefox.
--------------------------------------------------------------------------
HTTP/1.1 200 OK
Date: Wed, 02 Mar 2016 18:26:01 GMT
Content-Length: 51
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: text/html; charset=UTF-8

Array
(
    [param] => <script>alert(1)</script>
)
--------------------------------------------------------------------------

Best Regards,

g-sato

**Comment by kingthorin** [comment]
Wait so after modification it was found by the DOM XSS addon but wasn't found by the regular reflected rule (_Cross Site Scripting (Reflected)_)?

Was it found by the DOM XSS addon before modificaiton?

**Comment by g-sato** [comment]
I am sorry for confusing you.
I forgot check result of DOM XSS rule scan at first post and I'd change text after checking a scan result of DOM XSS rule.

Sort out the results:

A script for test:
zaptest.php
```
<?php
print_r($_GET);
```

Access URL:
`zaptest.php?param=aaa`

Vulnerability:
`GET zaptest.php?param=<script>alert(1)</script>`

```
HTTP/1.1 200 OK
Date: Sun, 28 Feb 2016 17:12:29 GMT
Content-Length: 29
Keep-Alive: timeout=5, max=76
Connection: Keep-Alive
Content-Type: text/html; charset=UTF-8

Array
(
[param] => <script>alert(1)</script>
)
```
(This HTTP Response shows alert dialog on Firefox.)


Actual results:
Reflected and Persistent XSS rules not detect XSS Vulnerability in zaptest.php
DOM XSS rule detect XSS Vulnerability in zaptest.php


Regards,

g-sato

**Comment by kingthorin** [comment]
Thanks.

Ended up mocking this up myself with xampp portable.

I can confirm that the "Cross Site Scripting (Reflected)" scanner does find the issue when there is actual HTML content. So psiinon's [suggestion](https://github.com/zaproxy/zaproxy/issues/2279#issuecomment-190119827) does work [1], while the [original](https://github.com/zaproxy/zaproxy/issues/2279#issue-137078580) does not. The DOM XSS addon finds it in both cases.

[1] In fact this can be reduced to a minimum of:
```
<html>
<?php print_r($_GET); ?>
</html>
```
Which will still be picked up by the  "Cross Site Scripting (Reflected)" scanner.

I believe this is a reasonable set of conditions. @psiinon or @thc202, agree?

**Comment by psiinon** [comment]
Tricky - its an edge case but I've no idea how prevalent. Maybe its more likely with ajax apps which pull fragments from different endpoints?
I guess we could check to see if a simple script attack is reflected, the type is text/html and there are no html tags - then we could raise the alert.

**Comment by kingthorin** [comment]
This issue seems to have been resolved at some point:

![image](https://user-images.githubusercontent.com/7570458/35488550-f7293de2-0458-11e8-9a7c-3b22ea132f91.png)

Screenshot above based on ascan release v29.

Closing: wontfix, insufficientevidence.
