### ISSUE TITLE
Import Root CA certificate via API

### ISSUE THREAD

**Issue by Lux0r87** [zaproxy/zaproxy#2280]
Allow to import an existing Root CA certificate via the API.

**Comment by davewichers** [comment]
Is this a duplicate of: #2023?

**Comment by thc202** [comment]
No, this one is to allow to import ZAP's Root CA cert (equivalent to import option in Options > Dynamic SSL Certificates).

**Comment by thc202** [comment]
This will be provided with an add-on (included by default).

**Comment by thc202** [comment]
This is already available in 2.11 by installing the Network add-on: https://www.zaproxy.org/docs/desktop/addons/network/api/
