### ISSUE TITLE
Filter params for a specific site

### ISSUE THREAD

**Issue by Lux0r87** [zaproxy/zaproxy#2281]
The params view _site_ parameter is broken.

### Steps to reproduce:
1. Start ZAP and a browser with ZAP's proxy settings (e.g. localhost, port: 8090)
2. Open a page in the browser (e.g. http://stackoverflow.com)
3. Open the [params view](http://zap/UI/params/view/params) and use the prior page for the _site_ parameter

==> Note, that the parameters for all sites are shown and the given parameter has no effect.

**Comment by thc202** [comment]
Fixed in #2255.
