### ISSUE TITLE
Spider a whole context at once

### ISSUE THREAD

**Issue by Lux0r87** [zaproxy/zaproxy#2282]
In the ZAP GUI it's possible to spider a whole context with all included URLs at once (Spider tab --> New Scan --> Select... --> choose a context). It would be nice, if the same could be done via the API.

- The parameter _contextName_ on the [scan action](http://zap/UI/spider/action/scan) for the spider can only be used to constrain the scan to a context.
- The parameter _contextId_ on the [scanAsUser action](http://zap/UI/spider/action/scanAsUser) for the spider seems to use the paramter just to identify the contained user, but also doesn't scan all sites included in the context.

So maybe one could add a new action _scanContext_ for the spider and if possible also for the AJAX spider and active scanner.

**Comment by thc202** [comment]
Fixed with #2263 and #2275.

The spider scans started through the ZAP API will behave the same way as the ones started with GUI.
(Still using the same ZAP API endpoints.)

**Comment by thc202** [comment]
There's already an issue raised for the AJAX spider, #1955.
I'll open an issue for the active scanner.
