### ISSUE TITLE
Update to supported version of Java - 8

### ISSUE THREAD

**Issue by jaxley** [zaproxy/zaproxy#2286]
Seems bad form to ship a vulnerable, unsupported, end-of-lifed-since-April-2015 version of Java with a security application.  Is this on the roadmap (didn't see an issue offhand for this)?

I wonder if the startup scripts on OSX should also default to system Java as long as it's >= 7 rather than defaulting to the bundled version?

**Comment by psiinon** [comment]
I'm fine with bundling Java 8 on OSX :)

**Comment by jaxley** [comment]
Although if we bundle anything, we need to own keeping it updated for security patches.

**Comment by thc202** [comment]
Merging into #1597.
