### ISSUE TITLE
 False Negative : SQLi not detected

### ISSUE THREAD

**Issue by patrickdemasson** [zaproxy/zaproxy#2290]
a POST request with ean=xxx
when i send ean=xxx'  or ean=xxx' or 1=1 , i have an exception :

OLE exception from "Microsoft OLE DB Provider for ODBC Drivers": ODBC driver does not support the requested properties. Win32::OLE(0.1601) error 0x80040e21 in METHOD/PROPERTYGET "Open"

ZAP don't detect it with default active scan (intensive scan)

kingthorin+owaspzap -> Would you mind opening a False Negative issue for this?

**Comment by kingthorin** [comment]
https://groups.google.com/forum/#!topic/zaproxy-users/Sf8Ik-21Hmc

**Comment by kingthorin** [comment]
@patrickdemasson can you confirm that the quoted error is (was) displayed back to the user?

**Comment by kingthorin** [comment]
Thanks, bad push :-1:
