### ISSUE TITLE
Support Python 3.5 in API

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#2308]
As per https://groups.google.com/d/msg/zaproxy-users/pWaukbxtG-M/9OQz2__8CQAJ
Known changes required: 
- print statements to use parentheses

**Comment by thc202** [comment]
Also:
https://groups.google.com/d/topic/zaproxy-users/JxUJpC2wz5k/discussion

Completely rewrite how the requests (to ZAP API) are done?
https://docs.python.org/3/library/urllib.request.html

**Comment by you1anna** [comment]
@thc202 I hope we can get a fix for this. Our project is eager to use Zap for automated testing, however our build servers (and auto test suites) all use Python 3. Do you estimate the changes required for Urllib to be extensive?

**Comment by psiinon** [comment]
Quick update to let you know we're looking into this.
There arent many print statements, so those seem pretty straightforward.
The requests are another matter - I'm gradually solving each problem as I hit them, but its slow going :/

**Comment by Woolworths** [comment]
+1 just saw this after I submitted the request

**Comment by jitendriya09** [comment]
Hi
Is this issue fixed?
I checked the link "Improved Python API library #2419" above
It was said that support for python3 is added.

but while trying to install the zap API(python api) i am facing same issue
pip install python-owasp-zap-v2.4

below is the error message i am getting.
Downloading/unpacking python-owasp-zap-v2.4
  Cannot fetch index base URL https://pypi.python.org/simple/
  Downloading python-owasp-zap-v2.4-0.0.8.tar.gz
  Running setup.py (path:/tmp/pip-build-l7azoeh2/python-owasp-zap-v2.4/setup.py) egg_info for package python-owasp-zap-v2.4
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-l7azoeh2/python-owasp-zap-v2.4/setup.py", line 12
        print "You must have setuptools installed to use setup.py. Exiting..."
                                                                             ^
    SyntaxError: Missing parentheses in call to 'print'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-l7azoeh2/python-owasp-zap-v2.4/setup.py", line 12

    print "You must have setuptools installed to use setup.py. Exiting..."

                                                                         ^

SyntaxError: Missing parentheses in call to 'print'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-l7azoeh2/python-owasp-zap-v2.4
Storing debug log for failure in /root/.pip/pip.log
The command '/bin/sh -c pip3 install python-owasp-zap-v2.4' returned a non-zero code: 1

**Comment by Woolworths** [comment]
@jitendriya09 It is not fixed. Check out my fork of zap-api-python -- it supports both Python2 and Python3.

**Comment by thc202** [comment]
Fixed in zaproxy/zap-api-python#4.

**Comment by thc202** [comment]
Included in version 0.0.10.

**Comment by thc202** [comment]
@Woolworths you should be able to claim the bounty.

**Comment by psiinon** [comment]
@Woolworths last chance to claim the bounty - otherwise we'll claim it and donate it back to OWASP :)
