### ISSUE TITLE
HttpsAsHttpScanner functioning differently

### ISSUE THREAD

**Issue by DarkPrince304** [zaproxy/zaproxy#2310]
According to whats given in the definition of the class HttpsAsHttpScanner it says that an alert is raised if HTTPS content is available via HTTP. So obviously the request must go in HTTP to check this rule. 
But here: https://github.com/zaproxy/zap-extensions/blob/alpha/src/org/zaproxy/zap/extension/ascanrulesAlpha/HttpsAsHttpScanner.java#L110

The function stops as soon as it finds that the request is not HTTPS (i.e HTTP) but actually the checking needs to be done when the request is through HTTP. Please do check this and correct me if I am wrong on this :)

**Comment by kingthorin** [comment]
Yes, if the base (original) request isn't https there's no point proceding.

**Comment by DarkPrince304** [comment]
how does the scanner detect which part is https content?

**Comment by kingthorin** [comment]
On the line you asked about. If the base message is not (!) secure (i.e.: requested via https) then exit (return), otherwise it was https so request it via http, if successful raise an alert.

**Comment by thc202** [comment]
@DarkPrince304 is this issue resolved? Can it be closed?

**Comment by DarkPrince304** [comment]
Yes. It can be closed now :)

Thanks!
