### ISSUE TITLE
Cannot add several payloads to fuzzer (NullPointerException)

### ISSUE THREAD

**Issue by rbock** [zaproxy/zaproxy#2314]
Hi,

So here is what I do (using ZAP_D-2016-03-07):

  - Create a new Fuzzer for a POST request
  - Add a location from the URL
  - Add a payload (e.g. strings)
  - Try to add a second payload

-> NullPointerException

Running on Ubuntu 15.10, 
> $ java -version
> java version "1.7.0_95"
> OpenJDK Runtime Environment (IcedTea 2.6.4) (7u95-2.6.4-0ubuntu0.15.10.1)
> OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)

Since I only just recently switched to using i3wm as my window manager, I also tried Unity, just to be sure, but the effect is the same.

Below are top few lines of the stack trace.

Please let me know if you need any further information.

Thanks,

Roland

> 71004 [AWT-EventQueue-1] ERROR org.zaproxy.zap.ZAP$UncaughtExceptionLogger  - Exception in thread "AWT-EventQueue-1"
> java.lang.NullPointerException
> 	at org.zaproxy.zap.view.JCheckBoxTree$CheckBoxCellRenderer.getTreeCellRendererComponent(JCheckBoxTree.java:168)
> 	at javax.swing.JTree$AccessibleJTree$AccessibleJTreeNode.getCurrentComponent(JTree.java:4611)
> 	at javax.swing.JTree$AccessibleJTree$AccessibleJTreeNode.getCurrentAccessibleContext(JTree.java:4588)
> 	at javax.swing.JTree$AccessibleJTree$AccessibleJTreeNode.getAccessibleRole(JTree.java:4697)
> 	at org.GNOME.Accessibility.AtkWrapper$4.propertyChange(AtkWrapper.java:584)
> 	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
> 	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
> 	at javax.accessibility.AccessibleContext.firePropertyChange(AccessibleContext.java:766)
> 	at javax.swing.JTree$AccessibleJTree.treeCollapsed(JTree.java:4205)
> 	at javax.swing.JTree.fireTreeCollapsed(JTree.java:2802)
> 	at javax.swing.JTree.setExpandedState(JTree.java:3597)
> 	at javax.swing.JTree.collapsePath(JTree.java:2234)
> 	at javax.swing.JTree.collapseRow(JTree.java:2247)
> 	at org.zaproxy.zap.view.JCheckBoxTree.collapseAll(JCheckBoxTree.java:316)
> 	at org.zaproxy.zap.extension.fuzz.FuzzerPayloadGeneratorUIHandler$FuzzerPayloadGeneratorUIPanel.resetFileFuzzersCheckBoxTree(FuzzerPayloadGeneratorUIHandler.java:417)
> 	at org.zaproxy.zap.extension.fuzz.FuzzerPayloadGeneratorUIHandler$FuzzerPayloadGeneratorUIPanel.init(FuzzerPayloadGeneratorUIHandler.java:409)
> 	at org.zaproxy.zap.extension.fuzz.impl.AddPayloadDialog.<init>(AddPayloadDialog.java:70)
> 	at org.zaproxy.zap.extension.fuzz.impl.MessageLocationPayloadsPanel$PayloadsTablePanel.showAddDialogue(MessageLocationPayloadsPanel.java:215)
> 	at org.zaproxy.zap.extension.fuzz.impl.MessageLocationPayloadsPanel$PayloadsTablePanel.showAddDialogue(MessageLocationPayloadsPanel.java:147)
> 	at org.zaproxy.zap.view.AbstractMultipleOptionsBaseTablePanel$1.actionPerformed(AbstractMultipleOptionsBaseTablePanel.java:87)
> 	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
>

**Comment by kingthorin** [comment]
What version of the Fuzzer are you using?

To find out you can either browse to your plugin directory or open the MarketPlace [1], and hover your cursor over the addon...

![addon_vers](https://cloud.githubusercontent.com/assets/7570458/13680555/12224488-e6c7-11e5-88b4-db789d924af8.png)


[1] https://raw.githubusercontent.com/wiki/zaproxy/zap-extensions/images/zap-screenshot-browse-addons.png

**Comment by rbock** [comment]
Oops, the attachment did not make it. Anyway: Version 5.

I did have the same problem with the release version (2.4.3), too.

**Comment by thc202** [comment]
This is caused by a core issue.
