### ISSUE TITLE
JSON jar issue

### ISSUE THREAD

**Issue by JordanGS** [zaproxy/zaproxy#2316]
For my alpha release of a report export plugin. I noticed that the JSON library that we have seems to be depreciated. It only allows for use of simpleJSON objects. Trying to important another jar throws an ant compile error saying that i am trying to use a depreciated library.

My current workaround was to important the entire JSON library package as part of my plugin package.

**Comment by thc202** [comment]
Are you referring to library json-lib?
Could you provide the error that you are seeing and an example case that's not working with the library?

**Comment by JordanGS** [comment]
json-lib-2.4-jdk15.jar

import with:

import net.sf.json.JSONException;
import net.sf.json.JSONObject;

but it is missing classes as far as i can tell. In particular, there should be a class called XML.

Code to Execute is:

```
	JSONObject xmlJSONObj = XML.toJSONObject(ghi);
	jsonPrettyPrintString = xmlJSONObj.toString(PRETTY_PRINT_INDENT_FACTOR);
```

It cannot find the import for XML.

**Comment by thc202** [comment]
Those classes (XML and the JSONObject returned) belong to another library. [1]
You would have to bundle that library in the add-on.
If you are already bundling that library could you provide the errors that you are seeing?

[1] https://search.maven.org/#search|gav|1|g%3A%22org.json%22%20AND%20a%3A%22json%22

**Comment by JordanGS** [comment]
Jar from [Java2s](http://www.java2s.com/Code/Jar/j/Downloadjavajsonjar.htm)

Directory to JAR:
`C:\Users\userid\Documents\Documents\Development\workspace\zap-extensions_alpha\src\org\zaproxy\zap\extension\exportReport\lib\java-json.jar`

Then i added it to the build path and added the following imports:

```
import org.json.JSONException;
import org.json.JSONObject;
import org.json.XML;
```

When the ant build is compiled, the following errors occur:

```
Buildfile: C:\Users\userid\Documents\Documents\Development\workspace\zap-extensions_alpha\build\build.xml
clean:
   [delete] Deleting directory C:\Users\userid\Documents\Documents\Development\workspace\zap-extensions_alpha\build\zap-exts
   [delete] Deleting directory C:\Users\userid\Documents\Documents\Development\workspace\zap-extensions_alpha\build\build
   [delete] Deleting directory C:\Users\userid\Documents\Documents\Development\workspace\zap-extensions_alpha\build\temp
   [delete] Deleting directory C:\Users\userid\Documents\Documents\Development\workspace\zap-extensions_alpha\build\results
init:
    [mkdir] Created dir: C:\Users\userid\Documents\Documents\Development\workspace\zap-extensions_alpha\build\zap-exts
    [mkdir] Created dir: C:\Users\userid\Documents\Documents\Development\workspace\zap-extensions_alpha\build\build
    [mkdir] Created dir: C:\Users\userid\Documents\Documents\Development\workspace\zap-extensions_alpha\build\temp
    [mkdir] Created dir: C:\Users\userid\Documents\Documents\Development\workspace\zap-extensions_alpha\build\results
compile:
     [echo] Compiling the source...
     [echo] Debug = true
    [javac] Compiling 236 source files to C:\Users\userid\Documents\Documents\Development\workspace\zap-extensions_alpha\build\build
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.7
    [javac] C:\Users\userid\Documents\Documents\Development\workspace\zap-extensions_alpha\src\org\zaproxy\zap\extension\exportReport\Export\ReportExport.java:46: error: cannot find symbol
    [javac] import org.json.JSONException;
    [javac]                ^
    [javac]   symbol:   class JSONException
    [javac]   location: package org.json
    [javac] C:\Users\userid\Documents\Documents\Development\workspace\zap-extensions_alpha\src\org\zaproxy\zap\extension\exportReport\Export\ReportExport.java:47: error: cannot find symbol
    [javac] import org.json.JSONObject;
    [javac]                ^
    [javac]   symbol:   class JSONObject
    [javac]   location: package org.json
    [javac] C:\Users\userid\Documents\Documents\Development\workspace\zap-extensions_alpha\src\org\zaproxy\zap\extension\exportReport\Export\ReportExport.java:48: error: cannot find symbol
    [javac] import org.json.XML;
    [javac]                ^
    [javac]   symbol:   class XML
    [javac]   location: package org.json
    [javac] C:\Users\userid\Documents\Documents\Development\workspace\zap-extensions_alpha\src\org\zaproxy\zap\extension\exportReport\Export\ReportExport.java:291: error: cannot find symbol
    [javac] 			JSONObject xmlJSONObj = XML.toJSONObject(temp);
    [javac] 			^
    [javac]   symbol:   class JSONObject
    [javac]   location: class ReportExport
    [javac] C:\Users\userid\Documents\Documents\Development\workspace\zap-extensions_alpha\src\org\zaproxy\zap\extension\exportReport\Export\ReportExport.java:291: error: cannot find symbol
    [javac] 			JSONObject xmlJSONObj = XML.toJSONObject(temp);
    [javac] 			                        ^
    [javac]   symbol:   variable XML
    [javac]   location: class ReportExport
    [javac] C:\Users\userid\Documents\Documents\Development\workspace\zap-extensions_alpha\src\org\zaproxy\zap\extension\exportReport\Export\ReportExport.java:294: error: cannot find symbol
    [javac] 		catch (JSONException e)
    [javac] 		       ^
    [javac]   symbol:   class JSONException
    [javac]   location: class ReportExport
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 6 errors
    [javac] 1 warning

BUILD FAILED
```

It should be pointed out that there is no problem is the jar is added to the following directory:

`C:\Users\userid\Documents\Documents\Development\workspace\zap-extensions_alpha\lib\java-json.jar`

**Comment by thc202** [comment]
Right, you also need to add the library to main lib dir if it's a compilation dependency.

Probably better to obtain a newer (and identified) version of the library, that one is from 2011(?)
There are newer in Maven Central, e.g. "20160212".

**Comment by JordanGS** [comment]
"Right, you **also **need to add the library to main lib dir if it's a compilation dependency."

Also? or only add the library to the main lib dir?

Right now i have the following.

1) Jar in directory: `C:\Users\userid\Documents\Documents\Development\workspace\zap-extensions_alpha\lib\json-20160212.jar`

2) Added it to build path

3) imported the classes, same as above.

-> No conflicts and works as intended. I also updated it with a more identified version of the library. Thank you!

**Comment by thc202** [comment]
Yes, if it's a compilation dependency it needs to be in the two lib directories (the main lib and the one of the add-on).
One for compilation and the other, in the add-on, to be used at runtime.
Something that's going to be changed...

**Comment by JordanGS** [comment]
![buildpath](https://cloud.githubusercontent.com/assets/17622264/13693666/6428f322-e71b-11e5-9d8c-5c18f08f505f.png)

So after adding both to the build path my referenced libraries should look like this?

**Comment by thc202** [comment]
To Eclipse classpath is enough with one (normally the library from the main lib directory).

**Comment by JordanGS** [comment]
Yup, i noticed that. Eclipse doesn't even need the lib in my plugin folder. Thank you for the the clarification. It wasn't a bug :)

**Comment by thc202** [comment]
You're welcome!
