### ISSUE TITLE
ZAP 2.4.3 send same requests on activescan 

### ISSUE THREAD

**Issue by g-sato** [zaproxy/zaproxy#2317]
Hello zap team,

I've found a bug in ZAP_WEEKLY_D-2016-03-07 and ZAP 2.4.3.
The probrem is similar to  #2152.

［Steps to reproduce］

Target File:
zaptest.php
```
<html>
<body>
<?php
print_r($_GET);
?>
</body>
</html>
```

Scan Parameter:
Input vectors = URL Quary String
Policy = Cross Site Scripting (Refrected) is Default, other rule is Off.

1) Normal case
Target URL:

`http://localhost/zaptest.php?a=1&b=1&c=1&d=1&e=1&f=1&g=1&h=1&i=1&j=1&k=1&l=1&m=1&n=1&aaa=bbb`

Scan Log:

```
http://localhost/zaptest.php?aaa=0W45pz4p&a=1&b=1&c=1&d=1&e=1&f=1&g=1&h=1&i=1&j=1&k=1&l=1&m=1&n=1
http://localhost/zaptest.php?aaa=%3Cscript%3Ealert%281%29%3B%3C%2Fscript%3E&a=1&b=1&c=1&d=1&e=1&f=1&g=1&h=1&i=1&j=1&k=1&l=1&m=1&n=1
http://localhost/zaptest.php?aaa=bbb%3Cscript%3Ealert%281%29%3C%2Fscript%3E&a=0W45pz4p&b=1&c=1&d=1&e=1&f=1&g=1&h=1&i=1&j=1&k=1&l=1&m=1&n=1
http://localhost/zaptest.php?aaa=bbb%3Cscript%3Ealert%281%29%3C%2Fscript%3E&a=%3Cscript%3Ealert%281%29%3B%3C%2Fscript%3E&b=1&c=1&d=1&e=1&f=1&g=1&h=1&i=1&j=1&k=1&l=1&m=1&n=1
http://localhost/zaptest.php?aaa=bbb%3Cscript%3Ealert%281%29%3C%2Fscript%3E&a=1&b=0W45pz4p&c=1&d=1&e=1&f=1&g=1&h=1&i=1&j=1&k=1&l=1&m=1&n=1
.
.
.
```

This is normal result.reflected XSS scan is working.

2) Unusual case
Target URL:

`http://localhost/zaptest.php?a=1&b=1&c=1&d=1&e=1&f=1&g=1&h=1&i=1&j=1&k=1&l=1&m=1&n=1&aaa%3Cscript%3Ealert(1)%3C/script%3E=bbb`

Scan Log:

```
http://localhost/zaptest.php?a=1&b=1&c=1&d=1&e=1&f=1&g=1&h=1&i=1&j=1&k=1&l=1&m=1&n=1&aaa%3Cscript%3Ealert(1)%3C/script%3E=bbb
http://localhost/zaptest.php?a=1&b=1&c=1&d=1&e=1&f=1&g=1&h=1&i=1&j=1&k=1&l=1&m=1&n=1&aaa%3Cscript%3Ealert(1)%3C/script%3E=bbb
http://localhost/zaptest.php?a=1&b=1&c=1&d=1&e=1&f=1&g=1&h=1&i=1&j=1&k=1&l=1&m=1&n=1&aaa%3Cscript%3Ealert(1)%3C/script%3E=bbb
http://localhost/zaptest.php?a=1&b=1&c=1&d=1&e=1&f=1&g=1&h=1&i=1&j=1&k=1&l=1&m=1&n=1&aaa%3Cscript%3Ealert(1)%3C/script%3E=bbb
http://localhost/zaptest.php?a=1&b=1&c=1&d=1&e=1&f=1&g=1&h=1&i=1&j=1&k=1&l=1&m=1&n=1&aaa%3Cscript%3Ealert(1)%3C/script%3E=bbb
.
.
.
```

The Reflected XSS scan rule is doing noting.The scan rule only sending the same requests many times.

(A Smallest sample URL to reploduce is:
http://localhost/zaptest.php?a=1&b=1&c=1&d=1&e=1&f=1&g=1&h=1&i=1&j=1&k=1&l=1&m=1&n=1&aaa%3C=bbb)

( This result is very similar to #2152 .
Target URL:
`http://localhost/zaptest.php?a=1&b=1&c=1&d=1&e=1&f=1&g=1&h=1&i=1&j=1&k=1&l=1&m=1&n=1&aaa[]=bbb`
Scan Log:
```
http://localhost/zaptest.php?a=1&b=1&c=1&d=1&e=1&f=1&g=1&h=1&i=1&j=1&k=1&l=1&m=1&n=1&aaa%5B%5D=bbb
http://localhost/zaptest.php?a=1&b=1&c=1&d=1&e=1&f=1&g=1&h=1&i=1&j=1&k=1&l=1&m=1&n=1&aaa%5B%5D=bbb
http://localhost/zaptest.php?a=1&b=1&c=1&d=1&e=1&f=1&g=1&h=1&i=1&j=1&k=1&l=1&m=1&n=1&aaa%5B%5D=bbb
http://localhost/zaptest.php?a=1&b=1&c=1&d=1&e=1&f=1&g=1&h=1&i=1&j=1&k=1&l=1&m=1&n=1&aaa%5B%5D=bbb
http://localhost/zaptest.php?a=1&b=1&c=1&d=1&e=1&f=1&g=1&h=1&i=1&j=1&k=1&l=1&m=1&n=1&aaa%5B%5D=bbb
http://localhost/zaptest.php?a=1&b=1&c=1&d=1&e=1&f=1&g=1&h=1&i=1&j=1&k=1&l=1&m=1&n=1&aaa%5B%5D=bbb
.
.
.
```
)

Regards.

**Comment by g-sato** [comment]
update version information
old) ZAP_WEEKLY_D-2016-03-07 
new) ZAP_WEEKLY_D-2016-03-07 and ZAP 2.4.3

**Comment by thc202** [comment]
Merging into issue #1848 (this issue is a side effect of the former).
