### ISSUE TITLE
Custom Context Panels not show in existing contexts after installation of add-on

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#2331]
If you have ZAP running and install the Context Alert Filters addon then open the properties of your Default Context (or any pre-existing context) it doesn't show the Alert Filter category. However, if you create a new context after adding the Alert Filter Addon you'll see it. OR, if you restart ZAP it shows for the Default Context.

**Comment by thc202** [comment]
It also affects the add-on "Access Control Testing", it does not show the "Access Control" panel.
