### ISSUE TITLE
Enable searching in ZAP Addons Pop-up

### ISSUE THREAD

**Issue by yaziza** [zaproxy/zaproxy#2334]
Hi, 

as the number of ZAP extensions is growing, the addons pop-up should have a search box in order to be user-friendly.

I can work on this feature. Will need some guidance where to start also ;)

**Comment by psiinon** [comment]
That would be very good :)
This dialog could actually do with a bigger revamp - I'm sure we could display info about them better, maybe just by pulling in the help pages from the wiki...

**Comment by thc202** [comment]
I prefer a filter than search field, it's more user-friendly IMHO.
The current tables already support searching through a keyboard shortcut, usually Ctrl+F. That or something similar could be embedded in the dialogue.

Some relevant classes/methods:
 - ZAP:
  - [ManageAddOnsDialog](https://github.com/zaproxy/zaproxy/blob/ae38bddb83e2130f0dbf754e7fb9496137dbe085/src/org/zaproxy/zap/extension/autoupdate/ManageAddOnsDialog.java);
 - SwingX:
  - JXFindBar;
  - JXTable;
  - JXTable.setRowFilter(RowFilter);
  - SearchFactory;

**Comment by yaziza** [comment]
Thank you for the/your quick reply !

@thc202 : +1

I have some UI prototypes in mind. I will upload some screen shots as soon as I finish in order to get some feedback before starting the implementation.

**Comment by yaziza** [comment]
Hi, 

i have added a filter TextField to the Addons tables. It would be really helpful to know your opinion before implementing the filters. Any other ideas would also be appreciated ! 

Installed:

![bildschirmfoto 2016-03-19 um 20 03 37](https://cloud.githubusercontent.com/assets/1202509/13900746/053d6902-ee0e-11e5-9b5f-5f4376700bd9.png)

Marktplace :

![bildschirmfoto 2016-03-19 um 20 03 50](https://cloud.githubusercontent.com/assets/1202509/13900749/0c97eb96-ee0e-11e5-871a-d8e6f5624cc2.png)

**Comment by thc202** [comment]
Location of the text fields looks good to me :)
