### ISSUE TITLE
Addon Manager doesn't open

### ISSUE THREAD

**Issue by vdbaan** [zaproxy/zaproxy#2348]
When I click on the AddOn manager no window appears.

I've tried both jdk1.7.0_55 and jdk1.8.0_66
I'm using Ubuntu 15.10 x86_64 GNU/Linux

the only debug information I received regarding this screen was:
15649 [AWT-EventQueue-0] DEBUG org.parosproxy.paros.view.AbstractFrame  - Restoring preference window.size=700,500
15650 [AWT-EventQueue-0] DEBUG org.parosproxy.paros.view.AbstractFrame  - Restoring preference window.position=2003,324
15650 [AWT-EventQueue-0] DEBUG org.parosproxy.paros.view.AbstractFrame  - Restoring preference window.state=null
15716 [AWT-EventQueue-0] DEBUG org.parosproxy.paros.view.AbstractFrame  - Saving preference window.size=700,500
15722 [AWT-EventQueue-0] DEBUG org.parosproxy.paros.view.AbstractFrame  - Saving preference window.size=700,500
15770 [AWT-EventQueue-0] DEBUG org.parosproxy.paros.view.AbstractFrame  - Saving preference window.size=700,500
15770 [AWT-EventQueue-0] DEBUG org.parosproxy.paros.view.AbstractFrame  - Saving preference window.position=2004,352
15770 [AWT-EventQueue-0] DEBUG org.parosproxy.paros.view.AbstractFrame  - Saving preference window.size=700,500
15843 [AWT-EventQueue-0] DEBUG org.parosproxy.paros.view.AbstractFrame  - Saving preference window.size=700,500

**Comment by thc202** [comment]
Do you have more than one screen? What's the resolution?

**Comment by vdbaan** [comment]
Single screen 1920x1080

**Comment by thc202** [comment]
OK, the dialogue is being moved to "2003,324", I guess that's why it's not visible.
Did that happen recently? (i.e. it was visible before)

Try deleting the file `prefs.xml` in `/home/<username>/.java/.userPrefs/org/zaproxy/zap/extension/autoupdate/` and run ZAP again. It should show the dialogue in correct place.

**Comment by thc202** [comment]
We should allow to reset those properties from ZAP.

**Comment by vdbaan** [comment]
You were correct, my appologies.

**Comment by thc202** [comment]
OK, let us know if you are able to reproduce that or if it happens again.

P.S. There's nothing to apologise ;)
