### ISSUE TITLE
Add-on Firefox Signature

### ISSUE THREAD

**Issue by haf** [zaproxy/zaproxy#2353]
When trying to install the add-on for Firefox, it's failing because it hasn't been signed by Mozilla.

<img width="835" alt="screen shot 2016-03-26 at 17 35 20" src="https://cloud.githubusercontent.com/assets/193115/14061148/272a9b5a-f379-11e5-9c9b-b65ab3e98a5d.png">

Would you consider having your released addons properly signed?

**Comment by thc202** [comment]
Yes, this is a known issue #2069.
