### ISSUE TITLE
Does anti csrf's generate test form api work in daemon mode?

### ISSUE THREAD

**Issue by ambikashri** [zaproxy/zaproxy#2355]
I am using ZAP 2.4.1 and trying to use the generate anti csrf test form api to test for csrf in daemon mode.
I am using the below api
http://zap/JSON/OTHER/acsrf/other/genForm/?hrefId=351
But it throws the below error
751: unexpected token at 'No Implementor'

**Comment by psiinon** [comment]
It looks like you've got the URL wrong - the format is as per https://github.com/zaproxy/zaproxy/wiki/ApiDetailsUrlFormat
Try something like http://zap/JSON/acsrf/other/genForm/?hrefId=351

**Comment by ambikashri** [comment]
I got this URL from the UI.

**Comment by psiinon** [comment]
What was the URL of the UI that gave this URL?
Can you try the one I suggested?

**Comment by ambikashri** [comment]
I launch the ZAP tool then Tools ->Browse API -> Opens "http://zap" in the firefox browser -> Click on Local API -> acsrf -> genForm

The URL you suggested worked.

**Comment by ambikashri** [comment]
Also the API doesn't return any response as 200 or OK. How do I capture the test form to perform any modification
As of now I am using it as below
```
url = Addressable::URI.parse("#{@base}/JSON/acsrf/other/genForm/")
 url.query_values = {:hrefId => hrefid}
p response = JSON.parse(RestClient::get url.normalize.to_str)
```

response is returned as empty.

**Comment by psiinon** [comment]
What do you want to do with the response?
Although this operation is invoked by the API its really intended for manual testing.
It returns an HTML page with the relevant FORM - if you open it in your browser then you'll be able to 'view source'.
If you want to parse this you'll need to use an HTML parser.

**Comment by kingthorin** [comment]
Is there a reason you're still using 2.4.1?

In my dev instance this seems to work as expected associated with OTHER, since it's not returning JSON it's returning an actual HTML form.

**Comment by ambikashri** [comment]
Once the form is generated, I want to edit the token values and submit the form. So now I am doing the API call to get the url and directly loading the url in the browser. But it seems to be loading a blank page.
```
url = Addressable::URI.parse("#{@base}/HTML/acsrf/other/genForm/")
 url.query_values = {:hrefId => hrefid}
browser.goto(url.to_str)
p browser.html
```

Output
```
"<html xmlns=\"http://www.w3.org/1999/xhtml\"><head></head><body></body></html>"
```

Is this because I am running ZAP in daemon?

**Comment by thc202** [comment]
The request URL needs to use `OTHER` as the format. (It will still return the HTML form.)

Running as daemon shouldn't make any difference in this case.

**Comment by thc202** [comment]
@ambikashri any news on this?

**Comment by ambikashri** [comment]
Using OTHER as format worked fine. Thank You.

**Comment by thc202** [comment]
Thanks for letting us know!
