### ISSUE TITLE
Unable to change Mode without main tool bar

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#2375]
Steps to reproduce the issue:
1. Start ZAP;
2. Deselect the option "Options" > "Display" > "Show Main Toolbar" and restart ZAP;
3. Note that it's no longer possible to change the Mode, the option is/was only available in the main tool bar.

Remarks:
With newer versions it's possible to change the mode by other means than the GUI, for example, using the ZAP API.

ZAP Versions:
Versions >= 2.0.0

**Comment by thc202** [comment]
What's the (other) best place to add the option? Display panel of the options dialogue?

**Comment by Drag0s** [comment]
I'm still able to access throught the contextual menu, "Tools" > "Options" > "Display" with the latest version (2.4.3).

**Comment by thc202** [comment]
I mean it's not possible to change the mode. [1]

[1] https://github.com/zaproxy/zap-core-help/wiki/HelpStartConceptsModes

**Comment by Drag0s** [comment]
What do you think about changing it through some contextual menu like "Edit" or "Tools"? If not, what about the "Options" panel?

**Comment by thc202** [comment]
Edit menu seems to be a good place.

**Comment by akshaym96** [comment]
Do you want the mode option to be in both  **"Edit"** as well as in **"Main ToolBar"**?

**Comment by kingthorin** [comment]
Yes
