### ISSUE TITLE
Fuzzer Extension exception when removing PnH Extension

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#2387]
Encountered the following exception when uninstalling the PnH Extension. fuzz-beta-4.zap was installed at the time. 

> 378635 [SwingWorker-pool-2-thread-1] WARN org.zaproxy.zap.extension.fuzz.ExtensionFuzz  - Failed to read all custom file fuzzers:
> java.nio.file.NoSuchFileException: C:\Users\user\OWASP ZAP_D\fuzzers
> 	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
> 	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
> 	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
> 	at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(Unknown Source)
> 	at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(Unknown Source)
> 	at sun.nio.fs.WindowsFileSystemProvider.readAttributes(Unknown Source)
> 	at java.nio.file.Files.readAttributes(Unknown Source)
> 	at java.nio.file.FileTreeWalker.getAttributes(Unknown Source)
> 	at java.nio.file.FileTreeWalker.visit(Unknown Source)
> 	at java.nio.file.FileTreeWalker.walk(Unknown Source)
> 	at java.nio.file.Files.walkFileTree(Unknown Source)
> 	at org.zaproxy.zap.extension.fuzz.ExtensionFuzz.readFuzzersDir(ExtensionFuzz.java:389)
> 	at org.zaproxy.zap.extension.fuzz.ExtensionFuzz.access$800(ExtensionFuzz.java:110)
> 	at org.zaproxy.zap.extension.fuzz.ExtensionFuzz$FuzzerFilesUpdater.updateFiles(ExtensionFuzz.java:500)
> 	at org.zaproxy.zap.extension.fuzz.ExtensionFuzz$FuzzerFilesUpdater.filesRemoved(ExtensionFuzz.java:496)
> 	at org.parosproxy.paros.extension.ExtensionLoader.addonFilesRemoved(ExtensionLoader.java:490)
> 	at org.zaproxy.zap.control.AddOnInstaller.uninstallAddOnFiles(AddOnInstaller.java:434)
> 	at org.zaproxy.zap.control.AddOnInstaller.uninstall(AddOnInstaller.java:130)
> 	at org.zaproxy.zap.control.AddOnLoader.removeAddOnImpl(AddOnLoader.java:515)
> 	at org.zaproxy.zap.control.AddOnLoader.removeAddOn(AddOnLoader.java:475)
> 	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate.uninstall(ExtensionAutoUpdate.java:1021)
> 	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate.access$13(ExtensionAutoUpdate.java:1018)
> 	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate$10.doInBackground(ExtensionAutoUpdate.java:1485)
> 	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate$10.doInBackground(ExtensionAutoUpdate.java:1)
> 	at javax.swing.SwingWorker$1.call(Unknown Source)
> 	at java.util.concurrent.FutureTask.run(Unknown Source)
> 	at javax.swing.SwingWorker.run(Unknown Source)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> 	at java.lang.Thread.run(Unknown Source)

ZAP creates `C:\Users\user\OWASP ZAP_D\fuzzers\` at startup (if it doesn't exist). Installing PnH adds `PlugnHack DOM XSS Oracle` to that directory. Uninstalling PnH deletes the `fuzzers` directory.

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#442.

**Comment by thc202** [comment]
Released in version 6 of Fuzzer add-on.
