### ISSUE TITLE
HeadlessException should be handled more gracefully & README needs Headless details

### ISSUE THREAD

**Issue by tschernobyl** [zaproxy/zaproxy#2390]
Hi,
I'm trying to use ZAP for the first time on a virtual Fedora machine inside the Qubes OS. According to the README, I should just run the zap.sh, but this doesn't work. Next I tried zap.sh -.daemon (please add that instruction to README) and this time I get a lot further, but still not the whole way.

**Comment by kingthorin** [comment]
There's some info on the Docker page about starting ZAP headless which may help you: https://github.com/zaproxy/zaproxy/wiki/Docker

**Comment by kingthorin** [comment]
Reference: https://groups.google.com/forum/#!topic/zaproxy-users/OEvQgs2kNNw

> [user@ZAP ZAP_2.4.3]$ ./zap.sh

> Found Java version 1.8.0_60
> Available memory: 2901 MB
> Setting jvm heap size: -Xmx512m
> 0 [AWT-EventQueue-0] INFO org.zaproxy.zap.GuiBootstrap  - OWASP ZAP 2.4.3 started.
> 108 [AWT-EventQueue-0] ERROR org.zaproxy.zap.ZAP$UncaughtExceptionLogger  - Exception in thread "AWT-EventQueue-0"
> java.awt.HeadlessException
>     at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
>     at java.awt.Window.<init>(Window.java:536)
>     at java.awt.Frame.<init>(Frame.java:420)
>     at java.awt.Frame.<init>(Frame.java:385)
>     at javax.swing.JFrame.<init>(JFrame.java:189)
>     at org.parosproxy.paros.view.AbstractFrame.<init>(Unknown Source)
>     at org.zaproxy.zap.view.LicenseFrame.<init>(Unknown Source)
>     at org.zaproxy.zap.GuiBootstrap.showLicense(Unknown Source)
>     at org.zaproxy.zap.GuiBootstrap.startImpl(Unknown Source)
>     at org.zaproxy.zap.GuiBootstrap.access$000(Unknown Source)
>     at org.zaproxy.zap.GuiBootstrap$1.run(Unknown Source)
>     at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
>     at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
>     at java.awt.EventQueue.access$500(EventQueue.java:97)
>     at java.awt.EventQueue$3.run(EventQueue.java:709)
>     at java.awt.EventQueue$3.run(EventQueue.java:703)
>     at java.security.AccessController.doPrivileged(Native Method)
>     at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
>     at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
>     at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
>     at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
>     at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
>     at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
>     at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
>     at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Quote @thc202 from the User Group thread:

> By default ZAP starts with a GUI, in headless environments you need to
> start ZAP in daemon (or command line) mode [1]
> ./zap.sh -daemon
> 
> In daemon mode you need to use ZAP API to control ZAP though. [2][3]
> 
> 
> Anyway, it should shown a more user friendly message and the README
> should to mention that too.
> 
> Would you mind raising an issue? [4]
> 
> 
> [1] https://github.com/zaproxy/zap-core-help/wiki/HelpCmdline
> [2] https://github.com/zaproxy/zaproxy/wiki/ApiDetails
> [3] https://github.com/zaproxy/zaproxy/wiki/FAQapikey
> [4] https://github.com/zaproxy/zaproxy/issues/new
>
