### ISSUE TITLE
fuzzer doesnt work well

### ISSUE THREAD

**Issue by javixeneize** [zaproxy/zaproxy#2391]
Hi

I am comparing the behaviour of fuzzer in ZAP against Burp intruder

I am doing a very basic test against my own application. It is guessing a number that is between 1 and 25. I will have 24 responses saying that the number is invalid, and one saying that its valid

In ZAP, all the requests go very quick, and the response is the same in all the 25 requests, even when the request contains the right number

In Burp, it takes a bit longer to run every single request, and it returns 24 responses for the KO, and just one for the OK

What is the difference between both methods? ZAP is not working well here

Thanks

**Comment by psiinon** [comment]
Strange. If you look at the requests can you see the value you are fuzzing changing each time?

**Comment by javixeneize** [comment]
Yes, it changes, but looks like it retrieves a cached response or similar. As i said, the response for the 25 requests is almost inmediate (around 2 seconds) in ZAP, but it is slower in Burp (it takes near 15 seconds)

**Comment by psiinon** [comment]
In that case you might want to set some headers like:
Cache-Control: no-cache, no-store, must-revalidate
Pragma: no-cache

**Comment by psiinon** [comment]
Oh, and:
Expires: 0

**Comment by psiinon** [comment]
Out of interest can you see if Burp Intruder sets any of these automatically?

**Comment by thc202** [comment]
If it's a timing issue you can increase the request delay and/or reduce the number of threads.

**Comment by javixeneize** [comment]
Burp doesnt add those headers... It could be good to increase the delay...
Is there any option to do it currently or is a configuration to be added?

**Comment by thc202** [comment]
That (delay and threads) can be changed in the Options tab of Fuzzer dialogue.

**Comment by javixeneize** [comment]
Hi

It works fine. This topic can be closed

Thanks!

**Comment by thc202** [comment]
Thanks for letting us know.
