### ISSUE TITLE
Plug-n-hack setup fail on Firefox Developper Edition 47

### ISSUE THREAD

**Issue by tuxayo** [zaproxy/zaproxy#2397]
- When installing the add-on after allowing unsigned extensions
- And clicking the "Click to setup!" button
- Then the page shows "Configuring your browser to work with ZAP..."
- And the console shows "configuration has started"
- And nothing more happens

-

- Whereas on Firefox stable 45 
- There is the normal warning message that one must accept to configure PNH
- And it works

**Comment by thc202** [comment]
Merging into #2069.

**Comment by tuxayo** [comment]
I confirm that it's due to e10s.
As mentioned here: https://github.com/zaproxy/zaproxy/issues/2069#issuecomment-209388840

**Comment by thc202** [comment]
Thanks.
