### ISSUE TITLE
Building Source Code

### ISSUE THREAD

**Issue by BinaryResolved** [zaproxy/zaproxy#2404]
Can anyone give me a brief summary on how to build zap through the source code?

**Comment by kingthorin** [comment]
Info to get your started on setting up a dev environment can be found here:
https://github.com/zaproxy/zaproxy/wiki/Contributing-Changes
https://github.com/zaproxy/zaproxy/blob/develop/CONTRIBUTING.md
https://github.com/zaproxy/zaproxy/wiki/DevGuidelines
https://github.com/zaproxy/zaproxy/wiki/InternalDetails
https://github.com/zaproxy/zaproxy/wiki/DevTipsAndTricks

**Comment by BinaryResolved** [comment]
Thank you. @kingthorin

**Comment by kingthorin** [comment]
If you have further dev related questions please reach out via the Developer group:  https://groups.google.com/forum/m/#!forum/zaproxy-develop
