### ISSUE TITLE
incomplete or no cache-control and pragma HTTP header (False positive?)

### ISSUE THREAD

**Issue by jeichande** [zaproxy/zaproxy#2405]
Hi,

When scanning a website ZAP reports incomplete or no cache-control and pragma HTTP header (	
Recommendation: Whenever possible ensure the cache-control HTTP header is set with no-cache, no-store, must-revalidate, private; and that the pragma HTTP header is set with no-cache). But already configured accordingly and confirmed using curl: curl  -I -k https://xxxxxxxx. This can be considered a false positive?

Thanks

**Comment by kingthorin** [comment]
Could you provide an example of the response headers? Perhaps the rule needs tweaking.

**Comment by jeichande** [comment]
Sure:

HTTP/1.1 200 OK
X-Runtime: 0.01226
Cache-Control: private, max-age=0, must-revalidate
X-Frame-Options: SAMEORIGIN
Content-Length: 3535
Status: 200 OK
X-XSS-Protection: 1; mode=block
Cache-Control: max-age=31536000, private, no-cache, no-store, must-revalidate
Pragma: no-cache
Expires: 0
X-Content-Type-Options: nosniff
Content-Type: text/html; charset=utf-8

Thanks

**Comment by kingthorin** [comment]
I suspect it's because there are two Cache-Control headers, I'll do some testing and confirm.

According to this thread having multiple Cache-Control header is valid per the spec: http://stackoverflow.com/questions/4762377/cache-control-headers-repeated-valid-or-not-nginx

So that's something we should allow or account for.

**Comment by jeichande** [comment]
Hi,

I also noticed that and did not found any other cache-control header. 

Thanks,

**Comment by thc202** [comment]
I confirm the suspicion, the scanner checks each header individually, not cumulative, so if any of the headers is missing the expected values it raises the alert.

**Comment by jeichande** [comment]
Will make further investigation.This can be related to some rails cache control configuration? Can not find any other cache control settings on apache.

Thanks

**Comment by kingthorin** [comment]
https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2

**Comment by thc202** [comment]
Latest RFCs:
https://tools.ietf.org/html/rfc7230#section-3.2.2
https://tools.ietf.org/html/rfc7234
