### ISSUE TITLE
Warn if dynamic SSL root CA certificate is expired

### ISSUE THREAD

**Issue by codl** [zaproxy/zaproxy#2411]
If the root CA cert is expired, ZAP should issue a warning and maybe offer to generate a new one

**Comment by kingthorin** [comment]
Does anyone happen to have an expired cert or know an easy way of generating one?
Or, should I just implement this initially with `after(new Date())` which should be true for valid certs, and then just change it to `before` when I'm happy with the warning and logging (or whatever)?

**Comment by thc202** [comment]
The dates of the cert can be changed in: https://github.com/zaproxy/zaproxy/blob/1b8ea631f514835eee02123dfc91d44ff1c427ca/src/org/zaproxy/zap/extension/dynssl/SslCertificateUtils.java#L115-L116

But changing the logic for testing the warn/log is just fine.
