### ISSUE TITLE
Other information when spider

### ISSUE THREAD

**Issue by valour01** [zaproxy/zaproxy#2414]
I was wondering whether I can get the extra information like http request method, request headers and response headers for each URL when I get the result URLs by python api `zap.spider.scan()` and `zap.spider.result()`. This may helps me which method do the URLs support. Do you have any suggestions on the implementation. For example, which class I need to implement then I can get the info with python. Many Thanks

**Comment by thc202** [comment]
You can obtain the IDs of the messages that correspond to each URL using:
```Python
id = # id of the scan
zap.spider.full_results(id)
```
then use the core view `message` or `messageHar` to obtain the contents of the message:
```Python
id = # id of the message
zap.core.message(id)
# or for message in HAR format
zap.core.message_har(id)
```

The `full_results` already returns the method and status code and reason of each accessed URL.

**Comment by kingthorin** [comment]
This is a great question for the Development group:
https://groups.google.com/forum/#!forum/zaproxy-develop

On a side note the community-scripts repo might be of assistance:
https://github.com/zaproxy/community-scripts/

Also note that yes all messages do have associated headers, which for requests would include method. However the method used is not an enumeration of the methods available for a given resource/function/URL.

**Comment by thc202** [comment]
@valour01 is this issue addressed? Can it be closed?

**Comment by valour01** [comment]
@thc202  Sorry for the delay reply. I can get nearly all the things I wanna have by `zap.core.message(id)`. Thank you very much

**Comment by thc202** [comment]
OK, thanks for letting us know, closing the issue.

BTW, "nearly all" what's missing?

**Comment by valour01** [comment]
I opened another  [issue] (https://github.com/zaproxy/zaproxy/issues/2434). The missing part is that how to know the detail content that I post when I use spider. It seems I can only see the different content length but not the content itself.

**Comment by thc202** [comment]
OK, answering in that issue.
