### ISSUE TITLE
Show the reason why an active scanner was skipped

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#2415]
From OWASP ZAP User Group: https://groups.google.com/d/topic/zaproxy-users/AlT3gpxale8/discussion
 ---
ZAP shows that the active scanner was skipped but there's no indication why. It should be possible to know, through the GUI and the ZAP API, why an active scanner was skipped.
There are several reasons why an active scanner can be skipped, for example:
 - The target technologies were not included in the active scan (e.g. SQL Injection when DB is not selected);
 - Prerequisites of the scanner were not fulfilled (e.g. Possible Username Enumeration when no login URL was defined);
 - There's no reason to run the scanner (e.g. Script Active Scan Rules when there's no Active Rules enabled). 

Other than the core changes to show the reason it requires changes to allow scanners to report a custom reason (when using prerequisites) and change the scanners (mostly in add-ons) to specify the reason.

**Comment by davewichers** [comment]
In my case, the only DB tech I had enabled was MySQL. But strangely, it seemed like sometimes it would run, and sometimes it would not. So, I'm kind of wondering if having something else disabled somewhere was actually the cause. But really have no idea.

**Comment by thc202** [comment]
Were the techs defined in the context or the Active Scan dialogue?

**Comment by davewichers** [comment]
I used the Active Scan dialog to set the policy AND tune the Technologies to try to make the scan faster by disabling everything I thought was not relevant. The only techs I left ON were: MySQL, MacOS, and Tomcat. I turned off everything else I'm pretty sure.

**Comment by thc202** [comment]
OK, for the SQLi scanner it might be because of an issue (fixed in zaproxy/zap-extensions#439).
