### ISSUE TITLE
Contributing for ZAP

### ISSUE THREAD

**Issue by Mouheb22** [zaproxy/zaproxy#2423]
hi @psiinon I'm a new ZAP user, i'm doing my last year project(licence in computer sciences) i've added zap 2.4.3(standard , because i want to use the AJAX Spider) + Selenium to jenkins, up to here everything is OK, and now i want to contribute for ZAP and add security rules to it for a best ajax spidering , what should i do ? help me please :)

**Comment by kingthorin** [comment]
Your best bet is to take this question/discussion to the Dev group:
https://groups.google.com/forum/#!forum/zaproxy-develop

Info to get your started on setting up a dev environment etc can be found here:
https://github.com/zaproxy/zaproxy/wiki/Contributing-Changes
https://github.com/zaproxy/zaproxy/blob/develop/CONTRIBUTING.md
https://github.com/zaproxy/zaproxy/wiki/DevGuidelines
https://github.com/zaproxy/zaproxy/wiki/InternalDetails
https://github.com/zaproxy/zaproxy/wiki/DevTipsAndTricks

https://github.com/zaproxy/zaproxy/wiki/Building
