### ISSUE TITLE
java.net.SocketException SSL Redirection

### ISSUE THREAD

**Issue by avmp2208** [zaproxy/zaproxy#2426]
Hi guys, I'm trying to get in to a page where I have a redirect to a secure host, for example

> my link src = http://localhost:port/page.asp
> when I click the link above I have a redirection on my IIS Server to 
> src https://localhost:secureport/page.asp

when I try to use ZAP to see what happen on that request the software gave this error 

> ZAP Error [java.net.SocketException]: Connection reset
> 
> Stack Trace:
> java.net.SocketException: Connection reset
> 	at java.net.SocketInputStream.read(Unknown Source)
> 	at java.net.SocketInputStream.read(Unknown Source)
> 	at sun.security.ssl.InputRecord.readFully(Unknown Source)
> 	at sun.security.ssl.InputRecord.read(Unknown Source)
> 	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
> 	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
> 	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
> 	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
> 	at org.parosproxy.paros.network.SSLConnector.createSocket(Unknown Source)
> 	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
> 	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)
> 	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(Unknown Source)
> 	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(Unknown Source)
> 	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
> 	at org.parosproxy.paros.network.HttpSender.executeMethod(Unknown Source)
> 	at org.parosproxy.paros.network.HttpSender.runMethod(Unknown Source)
> 	at org.parosproxy.paros.network.HttpSender.send(Unknown Source)
> 	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(Unknown Source)
> 	at org.parosproxy.paros.network.HttpSender.sendAndReceive(Unknown Source)
> 	at org.parosproxy.paros.network.HttpSender.sendAndReceive(Unknown Source)
> 	at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(Unknown Source)
> 	at org.parosproxy.paros.core.proxy.ProxyThread.run(Unknown Source)
> 	at java.lang.Thread.run(Unknown Source)

I hope you can help me

Regards

**Comment by kingthorin** [comment]
Did it work directly through a browser at the same time?

What version of ZAP?
What version of java? (Open or Oracle/Sun?)

**Comment by avmp2208** [comment]
Yes, indeed.

ZAP Version 2.4.3
Java Version 8 update 73 Oracle

**Comment by kingthorin** [comment]
Do you have ZAP's CA cert installed?
https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsOptionsDynsslcert
https://github.com/zaproxy/zaproxy/wiki/FAQsslHandshake

What browser are you using?

**Comment by avmp2208** [comment]
My browser is FF, I don't know why its fails because with another apps where I have all certificates installed as well is all OK

**Comment by thc202** [comment]
Which protocols does the target server support? Could you try enable, in Connection options panel, just the ones supported?

**Comment by avmp2208** [comment]
I don't know what you mean, Are you talking about if Http or SSL support on my ZAP App??

**Comment by thc202** [comment]
(Was referring to versions of SSL/TLS protocol.)

I suppose that's one of versions supported by the target server?

**Comment by avmp2208** [comment]
Yes, TLS 1.2 that's the one.

**Comment by thc202** [comment]
OK, did you install "Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files"?

**Comment by kingthorin** [comment]
When you connect directly with Firefox, if you goto the Security tab of the Page Info dialog, near the bottom in the "Technical Details" section what details are listed? (It should show a Cipher Suite name, key length, and TLS version.)

Something like this:
https://support.cdn.mozilla.net/media/uploads/images/2015-08-03-14-01-22-e8be56.png
[Curious about the details of the entire line not just the red part.]

**Comment by thc202** [comment]
For reference:
http://docs.oracle.com/javase/8/docs/technotes/guides/security/SunProviders.html#SupportedCipherSuites

**Comment by avmp2208** [comment]
@thc202 Yes, JCE files are already installed.
Now I have tried to installl the ZAP Certificate in FF, FF Version 45.0.2
With Certificate Manager On Server Tab I set up the Zap Certificate, but now comes this error,

> Secure Connection Failed
> 
> An error occurred during a connection to "site". Peer's certificate issuer has been marked as not trusted by the user. Error code: SEC_ERROR_UNTRUSTED_ISSUER
> 
>     The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
>     Please contact the website owners to inform them of this problem.

**Comment by avmp2208** [comment]
Sorry on FF Authorities Tab and I checked all the boxes, 
as this link says https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsOptionsDynsslcert#install

**Comment by kingthorin** [comment]
If you tried connecting before adding ZAPs ca cert you might have to restart FF or clear your cache.

**Comment by thc202** [comment]
You can also use the add-on HttpsInfo to obtain that (and a little more) information. [1]

[1] https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsManageaddons

**Comment by kingthorin** [comment]
@avmp2208 can this issue be closed?

**Comment by kingthorin** [comment]
@avmp2208 can this issue be closed?

**Comment by kingthorin** [comment]
Closing, InsufficientEvidence.
