### ISSUE TITLE
ZAP 2.4.3 TreeView GUI Bug

### ISSUE THREAD

**Issue by ghelm** [zaproxy/zaproxy#2432]
The TreeView of ZAP is acting weird in the latest stable release on Kali Linux 2016.1.

Steps to reproduce:
- Download Kali Linux for VMWARE: https://images.offensive-security.com/virtual-images/Kali-Linux-2016.1-vm-amd64.7z
- login and run 'zapproxy' in a terminal
- scan a site like "http://webscantest.com"
- Play with the Tree on the left.

Please see the video on the following link for further reference:
https://www.ghelm.de/files/2016-04-23_16-12-31_zaproxy-2.4.3-treeview-bug.mp4

Thanks for looking into this.

Best Regards
G

**Comment by dwmuller** [comment]
I am also seeing this problem, in the same context, with ZAP 2.4.3. The Scripts tree has similar behavior.

**Comment by dwmuller** [comment]
I am also seeing this problem with ZAP 2.4.3 on a Kali VirtualBox VM (Windows host), installed via apt-get, with XFCE as my desktop environment. The Scripts tree has the same problem.

**Comment by thc202** [comment]
Disabling `assistive_technologies` seems to workaround the issue:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=813143

**Comment by dwmuller** [comment]
Thanks for the suggestion, @thc202, but that workaround provided only a marginal improvement for me. It seems to scramble the node labels a little less often.

**Comment by ghelm** [comment]
Workaround confirmed. Just commented the single line in /etc/java-7|8-openjdk/accessibility.properties and the issue was gone.

Nice Catch!

**Comment by kingthorin** [comment]
I believe the majority of our user base (Windows) is using ZAP with Oracle JDK (JRE) so no there shouldn't be any issue.

**Comment by dwmuller** [comment]
Once I applied the workaround to the right version of accessibility.properties, it worked great. (I applied it to Java 7 first, which of course was unhelpful. What can I say, it's a Monday morning.) 

Thanks, @thc202!

**Comment by thc202** [comment]
@ghelm, @dwmuller thanks for giving it a try!

An issue has been raised in Kali's bug tracker:
https://bugs.kali.org/view.php?id=3269

**Comment by thc202** [comment]
Fixed in libatk-wrapper-java version 0.33.3-7, already available in Kali.
