### ISSUE TITLE
Spider Python option

### ISSUE THREAD

**Issue by valour01** [zaproxy/zaproxy#2433]
When I use ZAP python api for spider. I noticed that the original configuration on the domain pattern is that the spider only follow links on the same domain where the scan started. I was wondering how can I know the total domains included in a page and how can I add one domain to my scope. And may I know the input value to represent `Ignore parameters completely`, `Consider only parameter's name`, `Consider both parameter's name and value` respective when using `zap.spider.set_option_handle_parameters`

**Comment by psiinon** [comment]
You could use the API to read which sites are in the sites tree after the spider has finished.
If we started spidering all 'off domain' sites we would probably end up trying to spider the whole internet :/
On what basis would you like to include off domain sites?

**Comment by valour01** [comment]
@psiinon Thanks for your explanation. The reason that I want to include off domain sites is that some sites may request resource from their CDN providers. Hence I may not be able to get the corresponding resource URL because the CDN  domain is not the scanned domain and I don't know these domain name before analyzing the site. So I may not available to get the whole resources a site request. 
But your explanation is good. Many Thanks

**Comment by kingthorin** [comment]
You could create a [passive script](https://github.com/zaproxy/community-scripts/tree/master/passive), to look for and scrape/alert on additional domains during your initial run of the spider.

**Comment by kingthorin** [comment]
As for this bit:
> And may I know the input value to represent `Ignore parameters completely`, `Consider only parameter's name`, `Consider both parameter's name and value` respective when using `zap.spider.set_option_handle_parameters `

- `Ignore parameters completely`
 - `example.org/page` is treated the same as `example.org/page?foo=bar`
- `Consider only parameter's name`
 - `example.org/page` is different than `example.org/page?foo=bar`, but `example.org/page?foo=bar` is the same as `example.org/page?foo=fred`
- `Consider both parameter's name and value`
 - `example.org/page`, `example.org/page?foo=bar`, and `example.org/page?foo=fred`; are all different

Further examples and explanation here: https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsOptionsSpider#query-parameters-handling

**Comment by valour01** [comment]
@kingthorin Thanks for your explanation. I know what does the three different parameter configuration mean. What I want to know is how to set the configuration in python api.  And the wiki seems have no example on this. Many Thanks

**Comment by thc202** [comment]
The values are `IGNORE_COMPLETELY`, `IGNORE_VALUE` and `USE_ALL`.

You can use a Context to define what is in scope (if you want the spider to follow everything you can set everything in scope `.*`).

**Comment by thc202** [comment]
@valour01 are the questions addressed? Can this issue be closed?

**Comment by thc202** [comment]
Closing, all questions answered (IMO).

@valour01 if something was missed or you have any other question, please, let us know through the [User Group](https://groups.google.com/group/zaproxy-users). Thank you.
