### ISSUE TITLE
Configure Authentication with Json object

### ISSUE THREAD

**Issue by horaciosolorio** [zaproxy/zaproxy#2439]
i have a json send for autenticate and y can not configure the user and the mail property, when i login "Login Request Post Data " fill whit my json  "user":{"mail":"test@gmail.com","pass":"1234"}} , but i can not configure﻿

"user":{"mail":"test@gmail.com","pass":"1234"}}

username = user.mail 
password = user.pass

![zap](https://cloud.githubusercontent.com/assets/8217370/14831853/0a27d41c-0bbd-11e6-9fba-13608ce136c5.png)

**Comment by thc202** [comment]
At the moment POST Data field supports only `application/x-www-form-urlencoded`.

**Comment by psiinon** [comment]
We should definitely make that configurable.

**Comment by horaciosolorio** [comment]
Thanks for, check this issue i try to test my nodejs server but without this i cant, please let me know any update.

**Comment by mustafa421** [comment]
I'd love to work on this. I would like to learn how to work with JSON anyway, so this would be a good learning experience.

**Comment by thc202** [comment]
Great! Let us know if you have any question about the issue (where to start, which classes need to be changed, discuss the UI changes...).

**Comment by thc202** [comment]
Right, FormBasedAuthenticationMethodType is the class that needs to be changed to add support for JSON data.
Maybe a combo box to choose the Content-Type would be enough?
(We could also allow to choose a "manual type" which would allow the user to define manually the position of the replacement tokens, independently of the Content-Type of the request.)

**Comment by mustafa421** [comment]
After further research, I ran into a few questions I'd like to have answered to help understand what I need to do (I'm really new to http requests :D). 

1. Currently, ZAP supports a urlencoded format with a separate text field for the user to enter POST parameters. ZAP attempts to extract the username and password parameters once the user enters the information in the POST data field. In order to support JSON authentication, I would need to allow ZAP to recognize that the user is entering JSON data (through a combo box in the GUI), and set up an HttpClient request accordingly. 

2. Independent of this new feature, I would also add support to allow a user to choose "manual type" to allow a user to manually select replacement tokens from within the parameter data.

Do I have the right idea so far?

**Comment by thc202** [comment]
1. Yes, it should be possible to choose the Content-Type of the POST request, a combo box should be fine. We should also allow to choose the JSON fields that represent the username and password (like currently done for x-www-form-urlencoded).
Regarding the request, you shouldn't need to set up the HttpClient request directly, just update the HttpMessage with the correct Content-Type (I think the current code would handle the replacement of username/password correctly).

2. That would be a good extra.

**Comment by JKazma** [comment]
Anything new about this? I would also find this feature useful.

**Comment by thc202** [comment]
Not that I'm aware of. Yeah, this is a good feature to have.

**Comment by zuBux** [comment]
I ran into this use-case today, I agree this is really good to have :)

**Comment by thc202** [comment]
I've the changes more or less ready, the form/dialogue is currently looking like:
![form-based with json](https://user-images.githubusercontent.com/4639210/27631997-51a15c6a-5bf2-11e7-90c7-a4a7580f8613.png)

**Comment by JKazma** [comment]
Will the jenkins plugin support json authentication?

**Comment by thc202** [comment]
The plan is to expose all the available authentication methods (there's already an issue to expose HTTP/NTLM).

**Comment by MattLok** [comment]
I agree this is an awesome feature, @thc202 Is there a branch available to start looking at the work you've done ?

**Comment by randomvoids** [comment]
@thc202 any update on when this feature might be added? Or anything I can do to help make this feature happen?
