### ISSUE TITLE
Add Passive Scanner for X-Debug-Token & X-Debug-Token-Link

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#2452]
This probably shouldn't be enabled without auth.... 

http://symfony.com/doc/current/cookbook/profiler/profiling_data.html
http://symfony.com/blog/new-in-symfony-2-4-quicker-access-to-the-profiler-when-working-on-an-api
https://www.shodan.io/search?query=X-Debug-Token-Link

**Comment by shivamdixit** [comment]
@kingthorin Can you please assign this to me?

**Comment by kingthorin** [comment]
@shivamdixit you should receive an invite to the organization you'll need to accept, once that's done I can assign this issue to you.

**Comment by shivamdixit** [comment]
@kingthorin Done, thanks

**Comment by kingthorin** [comment]
@shivamdixit so are you tackling this one?

**Comment by kingthorin** [comment]
Fixed in: https://github.com/zaproxy/zap-extensions/pull/868

**Comment by thc202** [comment]
Released in version 14 of Passive scanner rules (alpha) add-on.
