### ISSUE TITLE
Compatibility with IBM AIX 7.1 unix Operating system

### ISSUE THREAD

**Issue by shivinder07** [zaproxy/zaproxy#2457]
Hi,

I wanted to know the compatibility of Zed Attack Proxy Tool with the unix operating system - IBM AIX 7.1

Regards,
Shivinder Kaur

**Comment by psiinon** [comment]
Already answered on this thread in the User Group :/
https://groups.google.com/d/msg/zaproxy-users/I0WRSxHF0o4/vJ-BaB7yEgAJ
