### ISSUE TITLE
Zap seems to be doing something secret with asp.net app

### ISSUE THREAD

**Issue by binarymist** [zaproxy/zaproxy#2460]
I've got a strange situation currently with the Zap API.
Message 109 is a post (update of user details in all fields) from the my details page. This is created by selenium.
Message 198 is a post (update of user details in all fields) from the my details page. This is created by simply replaying the selenium request 109.

Message 109 is created like the following:

                    wd.Navigate().GoToUrl("http://localtest.me/ESS/BaseForm.aspx?_req=MyDetailsHost.ShowMyDetails&key=2");

                    IWebElement firstNames = wd.FindElement(By.Id("siteTemplate_MyDetailsParent_Construct_Construct_Component1_FirstNames"));
                    firstNames.Clear();
                    firstNames.SendKeys("Allison-SeleniumTest");
                    IWebElement lastNamme = wd.FindElement(By.Id("siteTemplate_MyDetailsParent_Construct_Construct_Component1_LastName"));
                    lastNamme.Clear();
                    lastNamme.SendKeys("Hill-SeleniumTest");
                    IWebElement dateOfBirth = wd.FindElement(By.Id("siteTemplate_MyDetailsParent_Construct_Construct_Component1_BirthDate"));
                    dateOfBirth.Clear();
                    dateOfBirth.SendKeys("01/01/1901");
                    IWebElement preferredName = wd.FindElement(By.Id("siteTemplate_MyDetailsParent_Construct_Construct_Component1_PreferredName"));
                    preferredName.Clear();
                    preferredName.SendKeys("Ally-SeleniumTest");
                    IWebElement previousName = wd.FindElement(By.Id("siteTemplate_MyDetailsParent_Construct_Construct_Component1_PreviousName"));
                    previousName.Clear();
                    previousName.SendKeys("Armstrong-SeleniumTest");
                    wd.FindElement(By.Id("siteTemplate_MyDetailsParent_Construct_Construct_Component2__Submit___internal")).Click();

Message 198 is created like the following. As you can see the route :
            _formsAuthenticatedScan.ActiveScan(
                relativeRoute: "ESS/BaseForm.aspx",
                postData: "ScriptManager1=siteTemplate%24contentUpdatePanel%7CsiteTemplate%24MyDetailsParent%24Construct%24Construct_Component2__Submit___internal&__EVENTTARGET=siteTemplate%24MyDetailsParent%24Construct%24Construct_Component2__Submit___internal&__EVENTARGUMENT=&__previousSidebarState=%7B%22autoCollapse%22%3Afalse%2C%22collapsed%22%3Afalse%2C%22openFolders%22%3A%5B%5D%7D&formChanged=1&__currentView=Construct.Construct&__LASTFOCUS=&__VIEWSTATE=%2FwEPDwULLTE0NDg4ODYyNTcPZBYCAgMPFgIeBXN0eWxlBQttYXJnaW46MHB4OxYCZg9kFgICAw9kFgJmD2QWAgIHD2QWAmYPZBYCAgEPZBYCAgEPZBYCAgEPZBYCAgMPZBYCAgEPZBYGAgEPDxYCHgdWaXNpYmxlaGRkAgIPD2QWAh8ABQp3aWR0aDo1MCU7FhACAg9kFgRmDw8WCB4NVmVydGljYWxBbGlnbgsqJ1N5c3RlbS5XZWIuVUkuV2ViQ29udHJvbHMuVmVydGljYWxBbGlnbgIeD0hvcml6b250YWxBbGlnbgsqKVN5c3RlbS5XZWIuVUkuV2ViQ29udHJvbHMuSG9yaXpvbnRhbEFsaWduAx4JQmFja0NvbG9yCqQBHgRfIVNCAoiADGQWAmYPDxYMHgtDZWxsU3BhY2luZ2YeC0NlbGxQYWRkaW5nAgMeCENzc0NsYXNzBQp0ZFBhZGRpbmczHgtCb3JkZXJXaWR0aBsAAAAAAAAAAAEAAAAeBVdpZHRoGwAAAAAAAAAABwAAAB8FAqKCGGQWAmYPZBYCZg8PFgYfAgsrBAIfAwsrBQMfBQKAgAwWAh8ABRN3aGl0ZS1zcGFjZTpub3dyYXA7ZAIBDw8WBB8KGwAAAAAAAFlABwAAAB8FAoACZBYCZg8PFgofB2YfBmYfCRsAAAAAAAAAAAEAAAAfChsAAAAAAABZQAcAAAAfBQKgghhkFgJmD2QWCGYPDxYEHwQKpAEfBQIIZGQCAQ8PFgYfBAmloqX%2FHgZIZWlnaHQbAAAAAAAAWUAHAAAAHwUCiAFkZAICDw8WBB8ECefn5%2F8fBQIIZGQCAw8PFgwfChsAAAAAAABZQAcAAAAfCxsAAAAAAABZQAcAAAAfAwsrBQEfAgsrBAIfBAnn5%2Bf%2FHwUCiIMMZBYCZg8PFg4fChsAAAAAAABZQAcAAAAfCxsAAAAAAABZQAcAAAAfBmYfBwIDHwgFCnRkUGFkZGluZzMfCRsAAAAAAAAAAAEAAAAfBQKigxhkFgJmD2QWAmYPDxYGHwMLKwUBHwILKwQCHwUCgIAMZBYCZg8PFgoeB0NvbHVtbnNmHglNYXhMZW5ndGgCHh8KGwAAAAAAAFRABwAAAB4ETW9kZQsqJVN5c3RlbS5XZWIuVUkuV2ViQ29udHJvbHMuVGV4dEJveE1vZGUAHwUCgAIWBh4Ib25jaGFuZ2UFEFNldEZvcm1DaGFuZ2VkKCkeCW9ua2V5ZG93bgUaSGFuZGxlRW50ZXJLZXlEb3duKGV2ZW50KTseB29ua2V5dXAFFExpbWl0VGV4dCh0aGlzLCAzMCk7ZAIED2QWBGYPDxYIHwILKwQCHwMLKwUDHwQKpAEfBQKIgAxkFgJmDw8WDB8GZh8HAgMfCAUKdGRQYWRkaW5nMx8JGwAAAAAAAAAAAQAAAB8KGwAAAAAAAAAABwAAAB8FAqKCGGQWAmYPZBYCZg8PFgYfAgsrBAIfAwsrBQMfBQKAgAwWAh8ABRN3aGl0ZS1zcGFjZTpub3dyYXA7ZAIBDw8WBB8KGwAAAAAAAFlABwAAAB8FAoACZBYCZg8PFgofB2YfBmYfCRsAAAAAAAAAAAEAAAAfChsAAAAAAABZQAcAAAAfBQKgghhkFgJmD2QWCGYPDxYEHwQKpAEfBQIIZGQCAQ8PFgYfBAmloqX%2FHwsbAAAAAAAAWUAHAAAAHwUCiAFkZAICDw8WBB8ECefn5%2F8fBQIIZGQCAw8PFgwfChsAAAAAAABZQAcAAAAfCxsAAAAAAABZQAcAAAAfAwsrBQEfAgsrBAIfBAnn5%2Bf%2FHwUCiIMMZBYCZg8PFg4fChsAAAAAAABZQAcAAAAfCxsAAAAAAABZQAcAAAAfBmYfBwIDHwgFCnRkUGFkZGluZzMfCRsAAAAAAAAAAAEAAAAfBQKigxhkFgJmD2QWAmYPDxYGHwMLKwUBHwILKwQCHwUCgIAMZBYCZg8PFgofDGYfDQJkHwobAAAAAAAAVEAHAAAAHw4LKwYAHwUCgAIWBh8PBRBTZXRGb3JtQ2hhbmdlZCgpHxAFGkhhbmRsZUVudGVyS2V5RG93bihldmVudCk7HxEFFUxpbWl0VGV4dCh0aGlzLCAxMDApO2QCCA9kFgRmDw8WCB8CCysEAh8DCysFAx8ECqQBHwUCiIAMZBYCZg8PFgwfBmYfBwIDHwgFCnRkUGFkZGluZzMfCRsAAAAAAAAAAAEAAAAfChsAAAAAAAAAAAcAAAAfBQKighhkFgJmD2QWAmYPDxYGHwILKwQCHwMLKwUDHwUCgIAMFgIfAAUTd2hpdGUtc3BhY2U6bm93cmFwO2QCAQ8PFgQfChsAAAAAAABZQAcAAAAfBQKAAmQWAmYPDxYKHwdmHwZmHwkbAAAAAAAAAAABAAAAHwobAAAAAAAAWUAHAAAAHwUCoIIYZBYCZg9kFghmDw8WBB8ECqQBHwUCCGRkAgEPDxYGHwQJpaKl%2Fx8LGwAAAAAAAFlABwAAAB8FAogBZGQCAg8PFgQfBAnn5%2Bf%2FHwUCCGRkAgMPDxYMHwobAAAAAAAAWUAHAAAAHwsbAAAAAAAAWUAHAAAAHwMLKwUBHwILKwQCHwQJ5%2Bfn%2Fx8FAoiDDGQWAmYPDxYOHwobAAAAAAAAWUAHAAAAHwsbAAAAAAAAWUAHAAAAHwZmHwcCAx8IBQp0ZFBhZGRpbmczHwkbAAAAAAAAAAABAAAAHwUCooMYZBYCZg9kFgJmDw8WBh8DCysFAR8CCysEAh8FAoCADGQWAmYPDxYIHwocHwwCCh8NZh8FAoACFgQfDwUQU2V0Rm9ybUNoYW5nZWQoKR8QBRpIYW5kbGVFbnRlcktleURvd24oZXZlbnQpO2QCDA9kFgRmDw8WCB8CCysEAh8DCysFAx8ECqQBHwUCiIAMZBYCZg8PFgwfBmYfBwIDHwgFCnRkUGFkZGluZzMfCRsAAAAAAAAAAAEAAAAfChsAAAAAAAAAAAcAAAAfBQKighhkFgJmD2QWAmYPDxYGHwILKwQCHwMLKwUDHwUCgIAMFgIfAAUTd2hpdGUtc3BhY2U6bm93cmFwO2QCAQ8PFgQfChsAAAAAAABZQAcAAAAfBQKAAmQWAmYPDxYKHwdmHwZmHwkbAAAAAAAAAAABAAAAHwobAAAAAAAAWUAHAAAAHwUCoIIYZBYCZg9kFghmDw8WBB8ECqQBHwUCCGRkAgEPDxYGHwQJpaKl%2Fx8LGwAAAAAAAFlABwAAAB8FAogBZGQCAg8PFgQfBAnn5%2Bf%2FHwUCCGRkAgMPDxYMHwobAAAAAAAAWUAHAAAAHwsbAAAAAAAAWUAHAAAAHwMLKwUBHwILKwQCHwQJ5%2Bfn%2Fx8FAoiDDGQWAmYPDxYOHwobAAAAAAAAWUAHAAAAHwsbAAAAAAAAWUAHAAAAHwZmHwcCAx8IBQp0ZFBhZGRpbmczHwkbAAAAAAAAAAABAAAAHwUCooMYZBYCZg9kFgJmDw8WBh8DCysFAR8CCysEAh8FAoCADGQWAmYPDxYKHwxmHw0CHh8KGwAAAAAAAFRABwAAAB8OCysGAB8FAoACFgYfDwUQU2V0Rm9ybUNoYW5nZWQoKR8QBRpIYW5kbGVFbnRlcktleURvd24oZXZlbnQpOx8RBRRMaW1pdFRleHQodGhpcywgMzApO2QCDg9kFgRmDw8WCB8CCysEAh8DCysFAx8ECqQBHwUCiIAMZBYCZg8PFgwfBmYfBwIDHwgFCnRkUGFkZGluZzMfCRsAAAAAAAAAAAEAAAAfChsAAAAAAAAAAAcAAAAfBQKighhkFgJmD2QWAmYPDxYGHwILKwQCHwMLKwUDHwUCgIAMFgIfAAUTd2hpdGUtc3BhY2U6bm93cmFwO2QCAQ8PFgQfChsAAAAAAABZQAcAAAAfBQKAAmQWAmYPDxYKHwdmHwZmHwkbAAAAAAAAAAABAAAAHwobAAAAAAAAWUAHAAAAHwUCoIIYZBYCZg9kFghmDw8WBB8ECqQBHwUCCGRkAgEPDxYGHwQJpaKl%2Fx8LGwAAAAAAAFlABwAAAB8FAogBZGQCAg8PFgQfBAnn5%2Bf%2FHwUCCGRkAgMPDxYMHwobAAAAAAAAWUAHAAAAHwsbAAAAAAAAWUAHAAAAHwMLKwUBHwILKwQCHwQJ5%2Bfn%2Fx8FAoiDDGQWAmYPDxYOHwobAAAAAAAAWUAHAAAAHwsbAAAAAAAAWUAHAAAAHwZmHwcCAx8IBQp0ZFBhZGRpbmczHwkbAAAAAAAAAAABAAAAHwUCooMYZBYCZg9kFgJmDw8WBh8DCysFAR8CCysEAh8FAoCADGQWAmYPDxYKHwxmHw0CHh8KGwAAAAAAAFRABwAAAB8OCysGAB8FAoACFgYfDwUQU2V0Rm9ybUNoYW5nZWQoKR8QBRpIYW5kbGVFbnRlcktleURvd24oZXZlbnQpOx8RBRRMaW1pdFRleHQodGhpcywgMzApO2QCEA9kFgRmDw8WCB8CCysEAh8DCysFAx8ECqQBHwUCiIAMZBYCZg8PFgwfBmYfBwIDHwgFCnRkUGFkZGluZzMfCRsAAAAAAAAAAAEAAAAfChsAAAAAAAAAAAcAAAAfBQKighhkFgJmD2QWAmYPDxYGHwILKwQCHwMLKwUDHwUCgIAMFgIfAAUTd2hpdGUtc3BhY2U6bm93cmFwO2QCAQ8PFgQfChsAAAAAAABZQAcAAAAfBQKAAmQWAmYPDxYKHwdmHwZmHwkbAAAAAAAAAAABAAAAHwobAAAAAAAAWUAHAAAAHwUCoIIYZBYCZg9kFghmDw8WBB8ECqQBHwUCCGRkAgEPDxYGHwQJpaKl%2Fx8LGwAAAAAAAFlABwAAAB8FAogBZGQCAg8PFgQfBAnn5%2Bf%2FHwUCCGRkAgMPDxYMHwobAAAAAAAAWUAHAAAAHwsbAAAAAAAAWUAHAAAAHwMLKwUBHwILKwQCHwQJ5%2Bfn%2Fx8FAoiDDGQWAmYPDxYOHwobAAAAAAAAWUAHAAAAHwsbAAAAAAAAWUAHAAAAHwZmHwcCAx8IBQp0ZFBhZGRpbmczHwkbAAAAAAAAAAABAAAAHwUCooMYZBYCZg9kFgJmDw8WBh8DCysFAR8CCysEAh8FAoCADGRkAhQPZBYEZg8PFggfAgsrBAIfAwsrBQMfBAqkAR8FAoiADGQWAmYPDxYMHwZmHwcCAx8IBQp0ZFBhZGRpbmczHwkbAAAAAAAAAAABAAAAHwobAAAAAAAAAAAHAAAAHwUCooIYZBYCZg9kFgJmDw8WBh8CCysEAh8DCysFAx8FAoCADBYCHwAFE3doaXRlLXNwYWNlOm5vd3JhcDtkAgEPDxYEHwobAAAAAAAAWUAHAAAAHwUCgAJkFgJmDw8WCh8HZh8GZh8JGwAAAAAAAAAAAQAAAB8KGwAAAAAAAFlABwAAAB8FAqCCGGQWAmYPZBYIZg8PFgQfBAqkAR8FAghkZAIBDw8WBh8ECaWipf8fCxsAAAAAAABZQAcAAAAfBQKIAWRkAgIPDxYEHwQJ5%2Bfn%2Fx8FAghkZAIDDw8WDB8KGwAAAAAAAFlABwAAAB8LGwAAAAAAAFlABwAAAB8DCysFAR8CCysEAh8ECefn5%2F8fBQKIgwxkFgJmDw8WDh8KGwAAAAAAAFlABwAAAB8LGwAAAAAAAFlABwAAAB8GZh8HAgMfCAUKdGRQYWRkaW5nMx8JGwAAAAAAAAAAAQAAAB8FAqKDGGQWAmYPZBYCZg8PFgYfAwsrBQEfAgsrBAIfBQKAgAxkZAIWD2QWBGYPDxYIHwILKwQCHwMLKwUDHwQKpAEfBQKIgAxkFgJmDw8WDB8GZh8HAgMfCAUKdGRQYWRkaW5nMx8JGwAAAAAAAAAAAQAAAB8KGwAAAAAAAAAABwAAAB8FAqKCGGQWAmYPZBYCZg8PFgYfAgsrBAIfAwsrBQMfBQKAgAwWAh8ABRN3aGl0ZS1zcGFjZTpub3dyYXA7ZAIBDw8WBB8KGwAAAAAAAFlABwAAAB8FAoACZBYCZg8PFgofB2YfBmYfCRsAAAAAAAAAAAEAAAAfChsAAAAAAABZQAcAAAAfBQKgghhkFgJmD2QWCGYPDxYEHwQKpAEfBQIIZGQCAQ8PFgYfBAmloqX%2FHwsbAAAAAAAAWUAHAAAAHwUCiAFkZAICDw8WBB8ECefn5%2F8fBQIIZGQCAw8PFgwfChsAAAAAAABZQAcAAAAfCxsAAAAAAABZQAcAAAAfAwsrBQEfAgsrBAIfBAnn5%2Bf%2FHwUCiIMMZBYCZg8PFg4fChsAAAAAAABZQAcAAAAfCxsAAAAAAABZQAcAAAAfBmYfBwIDHwgFCnRkUGFkZGluZzMfCRsAAAAAAAAAAAEAAAAfBQKigxhkFgJmD2QWAmYPDxYGHwMLKwUBHwILKwQCHwUCgIAMZGQCAw9kFgJmD2QWAmYPZBYCZg9kFgJmD2QWAmYPZBYEZg8PZBYCHwAFCnBhZGRpbmc6IDBkAgIPD2QWAh8ABQpwYWRkaW5nOiAwZBgBBR5fX0NvbnRyb2xzUmVxdWlyZVBvc3RCYWNrS2V5X18WAgUqc2l0ZVRlbXBsYXRlJE15RGV0YWlsc1BhcmVudCRDbGF5dG9uQnV0dG9uBShzaXRlVGVtcGxhdGUkTXlEZXRhaWxzUGFyZW50JHByaW50QnV0dG9uE1%2BCZD7Tg1yctuFVCogHQHll5IbRPYUu1Bghw4Z%2FPQs%3D&__VIEWSTATEGENERATOR=4D8586CC&__EVENTVALIDATION=%2FwEdABY0A5wr7o6lq1W2ywwLfjBALhKmbr523aAWRQrQYlwrWFzh%2BOWYMVmNuq5zGFeZ66PvxFYBrjE%2FtPmxu9DjCOsCs114SEJYu0dupvmlsetC6dL3EQatSR4ud74cRRwP6SjYMKFRRRJR%2FZNpxN4QUG1yk6g0ObNJDK%2FiZ9nL3q3cu0xZnyXRSL7kB%2FByvdKnn66OSCGK4vzyhP%2B5nsnkFFuUVXf1ZqGkNmhZar9S%2F2gKNUF01LHZ5670tW3%2FzDhPUYxjQUw1B0Zd9V47azKP2gBK%2FXiEAf0bDhwwdVYcjvb5nxRBgB14kxvW%2FDQ%2FYbDuwz1ugNQ%2BZIe8pd4zyPXAbSdjFw%2F34Vpoo%2FHxUGcuFOlZWIXKcF1PfcaXLSeeV3crIXEpVbjFWLAbWX9kVkrpwWicDj0N3Qtj9VGbi%2B5fB%2Fy3S0%2BOcKz8q7WmFwruBJ9S0WI6dMqK6HTwRC8v54RzJ3UmXk4K7Wm5SaJ95gbSE4Bm%2FJXYeb542QE2LAPE7hWgqzY%3D&siteTemplate%24MyDetailsParent%24Construct%24Construct_Component1%24FirstNames=Allison-ZapTest&siteTemplate%24MyDetailsParent%24Construct%24Construct_Component1%24LastName=Hill-ZapTest&siteTemplate%24MyDetailsParent%24Construct%24Construct_Component1%24BirthDate=02%2F02%2F1902&siteTemplate%24MyDetailsParent%24Construct%24Construct_Component1%24PreferredName=Ally-ZapTest&siteTemplate%24MyDetailsParent%24Construct%24Construct_Component1%24PreviousName=Armstrong-ZapTest&siteTemplate%24MyDetailsParent%24Construct%24Construct_Component1=&__ASYNCPOST=true&"
            );

_formsAuthenticatedScan.ActiveScan looks like the following:

            _apiResponse = _api.ascan.scan(
                _apikey,
                $"http://localtest.me/{relativeRoute}",
                recurse.ToString().ToLower(),
                inScopeOnly.ToString().ToLower(),
                "",
                method.ToUpper(),
               postData
            );

The 109 request

![image](https://cloud.githubusercontent.com/assets/2862029/15041965/1c9c0a56-1314-11e6-90ab-2bd345c70bda.png)

The 198 request

![image](https://cloud.githubusercontent.com/assets/2862029/15041979/3595dd84-1314-11e6-99df-1a0aaf6fccf3.png)

What I'm confused about is why the 198 request looks different to the 109 request in Zap, as 198 should be a simple replay of 109, but instead I'm seeing nothing but login attempts by the look of it.?

I kept playing and I get one ASP.NET_SessionId cookie sent, but 2 duplicates of one of our custom cookies sent. I've disabled cookies in the browser, but selenem webdriver seems to ignore that. Both the ASP.NET and the custom cookie are in the browser, but a duplicates of the custom cookie only are being sent.

The response of the active scan posts all look like the following, which as you can see appear to be redirecting to the login page:

![image](https://cloud.githubusercontent.com/assets/2862029/15041991/4fb84c1a-1314-11e6-9670-033dd2b2f6eb.png)

What am I missing and why am I not seeing the post to http://localtest.me/ESS/BaseForm.aspx? It's almost like Zap sees the message, drops it and trys to login.
The settings I've got setup:

![image](https://cloud.githubusercontent.com/assets/2862029/15041998/626bb338-1314-11e6-841b-1d0bdbd6a238.png)

![image](https://cloud.githubusercontent.com/assets/2862029/15042002/6aa7b54c-1314-11e6-9f9e-0602ca6ff6eb.png)

![image](https://cloud.githubusercontent.com/assets/2862029/15042005/70c738bc-1314-11e6-8fe1-4a77a4f84cb4.png)

Any ideas?

Simon helped out with a couple of links. 

* http://odetocode.com/articles/162.aspx
* https://support.microsoft.com/en-gb/kb/2915218

I'm already doing something very similar to how the first link with the WebClient deals with cookies, so I'm fairly sure now that cookies are fine. I've also tried turning off httponly (for giggles).

Every request I make, Zap makes a login request.

![image](https://cloud.githubusercontent.com/assets/2862029/15042069/0f375dd8-1315-11e6-9f66-31e22da9da98.png)

![image](https://cloud.githubusercontent.com/assets/2862029/15042075/15894c50-1315-11e6-8381-86e4e87c0ca8.png)

![image](https://cloud.githubusercontent.com/assets/2862029/15042077/1aa6ae58-1315-11e6-8a92-30acfafa4b75.png)

![image](https://cloud.githubusercontent.com/assets/2862029/15042078/20cf6b62-1315-11e6-90ef-ab0741e3ee28.png)

199 is the same as 197.
Now the next two are the most interesting. If I send this same payload through the browser, it's all good, so why when Zap forwards it do we get kicked out? We're logged in, so the request should yield the expected response shouldn't it? What am I missing? How does Zap handle the cookies? I think I told Zap about them in this code:
            _api.httpSessions.addSessionToken(_apikey, _target, "ASP.NET_SessionId");
            _api.httpSessions.addSessionToken(_apikey, _target, "sidebarState");

I also added them in the Options -> Http Sessions, and enabled them, as they didn't automatically turn up there after the above code.

![image](https://cloud.githubusercontent.com/assets/2862029/15042097/45607fb6-1315-11e6-82c0-17398abfca72.png)

![image](https://cloud.githubusercontent.com/assets/2862029/15042109/4dbe46fc-1315-11e6-9749-78b72f048499.png)

201 is the same as 199 and 197

When I setup Zap and populate the sites tree programmatically as per example (https://github.com/zaproxy/zap-api-dotnet/blob/master/src/OWASPZAPDotNetAPI/OWASPZAPDotNetAPI.Samples/AuthenticatedScanWithFormsAuthentication.cs), using the zap-api-dotnet then browse the site with a browser proxying through Zap immediately after the test run (cookies off, as Zap is supposed to be managing cookies), on Posts other than logins, I get back an error page. When I do the same but not through Zap, I get the response that is good. When I do the same through Burp with cookies on in browser, as Burp hasn't been programmed to know about the session cookies, the requests look the same as seen in Zap UI, but all responses are successful (no error page). So it seems that Zap is adding or removing something (other than the obvious cookies) instead of just proxying, but it's not showing it. Zap authenticates my user no problem except for all posts after a login which I just receive the error page.

This makes me think that Zap is either adding or removing something from the requests behind the scenes without providing visibility into what exactly it's adding or removing.

I've been through my code and am happy that it's all in order (spent close to two weeks on this one). I've also done a similar project in nodejs (https://github.com/binarymist/NodeGoat/wiki/Security-Regression-Testing-with-Zap-API) with few problems.

How can we get some insight into what Zap is "actually" doing? It's almost like we need to proxy Zaps requests through Burp to find out what's actually being sent.

**Comment by thc202** [comment]
@binarymist could you join #websectools channel at irc.mozilla.org? So we can discuss the problem more easily.

**Comment by binarymist** [comment]
public void ActiveScan(string relativeRoute, bool recurse = true, bool inScopeOnly = false, string method = "POST", string postData = "")
        {
            Console.WriteLine($"Active Scanner: {TargetBase}{relativeRoute}");

            Uri myDetailsUri = new Uri($"{Target}?_req=MyDetailsHost.ShowMyDetails&key=2");

            byte[] getPageResponse = _api.WebClient.DownloadData(myDetailsUri);

            string viewState = ExtractMarkupInputValue(Encoding.ASCII.GetString(getPageResponse), "__VIEWSTATE");
            string eventValidation = ExtractMarkupInputValue(Encoding.ASCII.GetString(getPageResponse), "__EVENTVALIDATION");
            
            string viewStatePostDataAndEventValidation = $"__VIEWSTATE={viewState}&{postData}&__EVENTVALIDATION={eventValidation}";

            ((WebClient)_api.WebClient).Headers.Add("Content-Type", "application/x-www-form-urlencoded");
            ((WebClient)_api.WebClient).Headers.Add("Origin", TargetBase);
            ((WebClient)_api.WebClient).Headers.Add("Referer", $"{Target}?_req=MyDetailsHost.ShowMyDetails&key=2");
            ((WebClient)_api.WebClient).Headers.Add("Accept", "*/*");


            byte[] postPageResponse = ((WebClient)_api.WebClient).UploadData($"{TargetBase}{relativeRoute}", "POST", Encoding.ASCII.GetBytes(viewStatePostDataAndEventValidation));


            




            _apiResponse = _api.ascan.scan(
                _apikey,
                $"{TargetBase}{relativeRoute}",
                recurse.ToString().ToLower(),
                inScopeOnly.ToString().ToLower(),
                "",
                method.ToUpper(),
                viewStatePostDataAndEventValidation
            );

            string activeScanId = ((ApiResponseElement)_apiResponse).Value;
            PollTheActiveScannerTillCompletion(activeScanId);
        }
    }

**Comment by binarymist** [comment]
@thc202 Grabbed the three POST requests we were talking about last session... 


ZapReq1.txt Driven by selenium from MyDetailsSuite.cs. Good response.
ZapReq2.txt Driven by Zap Api from MyDetailsSuite.cs. Doesn't persist update and the response looks more like that of the previous GET, unless I add in the extra hidden parameters and include a modern user-agent which seems to be requred for partial rendering. I was receiving an error "The page is performing an async postback but the ScriptManager.SupportsPartialRendering property is set to false. Ensure that the property is set to true during an async postbac" until I added the modern user-agent.
ZapReq3.txt Driven manually by browser. Good response.

[ZapReq1.txt](https://github.com/zaproxy/zaproxy/files/253271/ZapReq1.txt)
[ZapReq2.txt](https://github.com/zaproxy/zaproxy/files/253272/ZapReq2.txt)
[ZapReq3.txt](https://github.com/zaproxy/zaproxy/files/253273/ZapReq3.txt)

**Comment by thc202** [comment]
As mentioned in irc channel, the case differences in encoded chars should not matter (it decodes to same char).

Any useful differences between request 2 with the latest changes and request 1?

**Comment by binarymist** [comment]
Not that I can see. Can we try for another session same time as last week on Friday @thc202 ?

**Comment by thc202** [comment]
Sure!

**Comment by binarymist** [comment]
@thc202 I'm also noticing as of the new weeks build that when I call `ascan` immediately after the

    byte[] postPageResponse = ((WebClient)_api.WebClient).UploadData($"{TargetBase}{relativeRoute}", "POST", Encoding.ASCII.GetBytes(scriptManager + "&" + viewStatePostDataAndEventValidation));

I get the 400 Bad Request back from Zap

**Comment by binarymist** [comment]
[ZapReq2_ExtraHeaders.txt](https://github.com/zaproxy/zaproxy/files/262940/ZapReq2_ExtraHeaders.txt)

**Comment by binarymist** [comment]
[ZapReq2_ExtraHeaders.txt](https://github.com/zaproxy/zaproxy/files/262982/ZapReq2_ExtraHeaders.txt)

**Comment by binarymist** [comment]
[ZapReq2_ExtraHeaders.txt](https://github.com/zaproxy/zaproxy/files/263052/ZapReq2_ExtraHeaders.txt)

**Comment by binarymist** [comment]
[ReqForBadResp.txt](https://github.com/zaproxy/zaproxy/files/263101/ReqForBadResp.txt)
[ReqForGoodResp.txt](https://github.com/zaproxy/zaproxy/files/263102/ReqForGoodResp.txt)

**Comment by binarymist** [comment]
Just so that anyone reading this and wondering what happened. @thc202 has spent a good number of hours working through this with myself. Obviously the Zap team are very devoted and committed to seeing people have success with Zap, it's Api and other areas. Big thanks again! The application under test has been a bit of a night mare, but due to @thc202 help, things are moving forward and we can see Zap providing huge value in security regression testing soon to be part of this development teams automated (probably nightly) build

**Comment by kingthorin** [comment]
Does that mean this is resolved?

**Comment by binarymist** [comment]
Good question. The app is still behaving in a way that makes little to no sense. It certainly doesn't look like Zap is doing anything wrong. I'm going to continue to look into why the app seems to be producing non-deterministic responses. We can probably close this, but it may be reopened or at least added to as I find out more. So if you're looking at getting issues closed as quickly as possible then I'd say yeah, close?

**Comment by kingthorin** [comment]
No rush.

**Comment by binarymist** [comment]
I've moved off of this project now. It's now in someone elses hands. Another issue can be opened if need be.

**Comment by thc202** [comment]
Thanks for letting us know.
