### ISSUE TITLE
Websocket not proxied when outgoing proxy is set

### ISSUE THREAD

**Issue by piotr-pentest** [zaproxy/zaproxy#2463]
I have an issue with testing websockets in ZAP when outgoing proxy is set in Tools->Options->Connections. The usual web traffic works fine, but for some reason the websocket (e.g. http://www.websocket.org/echo.html) fails to connect through ZAP in such case.

**Comment by kingthorin** [comment]
Is there an actual failure or is it just not proxied?

**Comment by thc202** [comment]
It's not proxied (lack of functionality in ZAP).

**Comment by spyhunter99** [comment]
I'm seeing this issue with most of the online websocket testing sites. Running off of develop

**Comment by thc202** [comment]
Could you provide the URL of one of those sites? It's working fine here with `https://www.websocket.org/echo.html`. Using two ZAP instances one proxying through the other.

**Comment by spyhunter99** [comment]
https://www.websocket.org/echo.html 
https://libwebsockets.org/testserver/

I had to increase the default connection timeout setting, which was 5 seconds. At 5 seconds, the browser would connect successfully however the proxy would drop the socket at the timeout threshold. Even with a larger value, it will still eventually timeout though. Websockets can be open hours or days even.

**Comment by thc202** [comment]
Which proxy are you referring to? ZAP or the outgoing? Are you able to see any WebSocket traffic in ZAP?

**Comment by thc202** [comment]
Ah, I thought you were using browser > ZAP > other proxy > Internet (this issue is about this setup).
OK, that behaviour might be explained by missing WebSocket add-on, if you don't have a WebSocket tab it means it's not installed (you can install it through the marketplace as with main versions).

**Comment by spyhunter99** [comment]
@thc202 you're awesome, thanks! Do you by chance know if there's a way to programmatically get a callback when the websocket frames are captured?
