### ISSUE TITLE
MAC OS - Spider scan error

### ISSUE THREAD

**Issue by truonghoangphuc** [zaproxy/zaproxy#2468]
Hi all,

I'm new with ZAP so maybe it is stupid question.
When I run spider scan in ZAP (with my js in Passive Rules ), it return error :  "load" is not defined
My js start similar below:

// The scan function will be called for request/response made via ZAP, excluding some of the automated tools
// Passive scan rules should not make any requests

// Note that new passive scripts will initially be disabled
// Right click the script in the Scripts tree and select "enable"

load("nashorn:mozilla_compat.js"); ==> alert error **"load" is not defined** here

Thanks,

**Comment by kingthorin** [comment]
What version of Java?

**Comment by thc202** [comment]
The problem is most likely the Java version (Rhino vs Nashorn), if you are using the OSX package (which bundles Java 7 JRE) it is using Rhino JavaScript engine not Nashorn (the latter has that function defined).

**Comment by truonghoangphuc** [comment]
@kingthorin ,
I using the latest package for MAC (2.4.3)

@thc202 ,
Yes, I think it too but don't know how to make it switch to Nashorn ? I copy java_nashorn.jar to folder /Applications/OWASP ZAP.app/Contents/Java/lib but it no fixed.


Thanks,

**Comment by kingthorin** [comment]
The only reference I could find to `mozilla_compat` and zaproxy was [this Gist](https://gist.github.com/tfcporciuncula/9a4e5d3dff2fbf6a73bd) are you trying to use that script?

**Comment by thc202** [comment]
@truonghoangphuc I think you will have to use Java 8 for Nashorn (i.e. the whole JRE). If you already have it installed you can use the Linux package which does not bundle any JRE (or tweak the existing zap.sh script to not use the bundled JRE).

(Note that since you are already using Rhino you do not need to load the compatibility library.)

**Comment by truonghoangphuc** [comment]
@thc202  Yes, it's OK now. Thank you :)

**Comment by kingthorin** [comment]
Thanks for letting us know.
