### ISSUE TITLE
Circular Redirects

### ISSUE THREAD

**Issue by RaptorCZ** [zaproxy/zaproxy#2484]
Is Circular Redirects support active in the latest version (ZAP_WEEKLY_D-2016-05-09)? Trying to test my web in localhost (or hosted in IIS) but still getting error:
ERROR org.zaproxy.zap.extension.quickstart.AttackThread  - Circular redirect

My web is using custom authentication using certificate included in request, or using login token and I want to log in spider to web. Now it is possible only to scan default and login page. I'm not able to get him login and continue.

**Comment by thc202** [comment]
No, but (IMHO) that should be allowed by default.
