### ISSUE TITLE
Wrong charset used in HTTP body

### ISSUE THREAD

**Issue by pauser0000001** [zaproxy/zaproxy#2487]
ZAP version 2.4.3
These characters are used in a replay request: ÃÂÃÂÃ in a text field.
Every time I press SEND, the characters duplicate within the request.

**Comment by thc202** [comment]
Which OS and Java version are you using?
With which view is that happening, Text, Table or Table (adv)?

**Comment by pauser0000001** [comment]
OS: windows 7
Java: C:\Program Files\Java\jre1.8.0_77\bin\javaw.exe

The view is RawView, in HexView does not happens.
The request is a Json, here you have a simplified request:
{"descripcion":"LÃÂÃÂÃÂÃÂÃÂÃÂPIZ"}
The characters are c3 83 c2 83 hexadecimal.

**Comment by thc202** [comment]
OK, what's the exact Content-Type of the body? Is it using UTF-8?

**Comment by pauser0000001** [comment]
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: en,en-US;q=0.8,es-ES;q=0.5,es;q=0.3
Content-Type: application/json;charset=utf-8

Yes, apparently it is using UTF8.

**Comment by thc202** [comment]
Thanks, was able to reproduce the issue.

One thing, that encoding seems to be UTF-16:
`C3 83 C2 83`

For UTF-8 it should be:
`EC 8E 83 EC 8A 83`

Are the contents really being sent in UTF-8?

**Comment by pauser0000001** [comment]
I'm not sure, but that is what Firefox sends over https, therefore I can not see it through wireshark.  
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:46.0) Gecko/20100101 Firefox/46.0

**Comment by thc202** [comment]
Are you manipulating the contents before being sent?

**Comment by pauser0000001** [comment]
No, I was checking if the rest server answers several times to a request that must unique.

But the problem in my particular case could be that the server answers in utf16 even if it says it answers in utf8. I'll check if this is true.

**Comment by thc202** [comment]
OK.
