### ISSUE TITLE
In scope for customize alert report plugin not working

### ISSUE THREAD

**Issue by taurussieben** [zaproxy/zaproxy#2492]
Problem:

When I tick the box for scope the resulting alert report is empty, better showing all alerts as empty.

Checked:
- sites are in context
- when I use scope in the alert tab, I still get alerts shown

**Comment by kingthorin** [comment]
Version?
Screenshots?

**Comment by thc202** [comment]
This was (also) reported in IRC channel. It's reproducible with latest version of Custom Report add-on (currently 1) and 2.4.3, when the top level node is _not_ in scope but the messages with alerts are.

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#1682.
