### ISSUE TITLE
ZAP Proxy is not showing the HTTP CONNECT Request in history tab.

### ISSUE THREAD

**Issue by Huma123** [zaproxy/zaproxy#2494]
Hi All, 

I am using ZAP Proxy for one of my mobile project and wanted to intercept all network calls going from my  app. I can see all GET/POST requests, But ZAP is not showing any HTTP CONNECT Requests. 

My App is making couple of HTTP Connect Request. 
For ex. If I can ran ran current curl command I am getting the following output 

url -v -k --proxy <<PROXY_IP:PROXY_PORT>> "https://netflix.com"
* Rebuilt URL to: https://netflix.com/
*   Trying <<PROXY_IP:PROXY_PORT>>...
* Connected to <<PROXY_IP:PROXY_PORT>> port 8080 (#0)
* Establish HTTP proxy tunnel to netflix.com:443
> CONNECT netflix.com:443 HTTP/1.1
> Host: netflix.com:443
> User-Agent: curl/7.43.0
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 200 Connection established
< Proxy-connection: Keep-alive
< 
* Proxy replied OK to CONNECT request
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
* Server certificate: netflix.com
* Server certificate: OWASP Zed Attack Proxy Root CA
> GET / HTTP/1.1
> Host: netflix.com
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Cache-Control: no-cache, no-store
< Date: Wed, 18 May 2016 19:52:26 GMT
< Edge-Control: no-cache, no-store
< Location: https://www.netflix.com/
< Server: wwwservice i-2d9760f9
< Set-Cookie: nflx-rgn=ue1|1463601147557; Max-Age=-1; Expires=Wed, 18 May 2016 19:52:26 GMT; Path=/; Domain=.netflix.com
< Set-Cookie: memclid=d531bf30-a714-46f5-8cdc-6e23dcccc838; Max-Age=31536000; Expires=Thu, 18 May 2017 19:52:27 GMT; Path=/; Domain=.netflix.com
< Set-Cookie: nfvdid=BQFmAAEBECIXlGrxjgDDvwG4ybUP1tgwXm4lbjUx8ZwVBgCxC0PXbekTN4LIqGEq7ivc%2B6lp7FIstXj7buQoyXDF0FfnnOzH; Max-Age=31536000; Expires=Thu, 18 May 2017 19:52:27 GMT; Path=/; Domain=.netflix.com
< Strict-Transport-Security: max-age=31536000
< Via: 1.1 i-a40e3f23 (us-east-1)
< X-Content-Type-Options: nosniff
< X-Netflix-From-Zuul: true
< X-Netflix.nfstatus: 1_1
< X-Originating-URL: https://netflix.com/
< X-Xss-Protection: 1; mode=block; report=https://ichnaea.netflix.com/log/freeform/xssreport
< Content-Length: 0
< Connection: keep-alive
< 
* Connection #0 to host 192.168.1.21 left intact

But ZAP Proxy is showing only the GET request. 

Is there any way we can instruct/configure to show the Connect request also in History TAB. 

Thanks
Huma Shankar

**Comment by Huma123** [comment]
Can we expect this will be taken/covered in next release?

**Comment by thc202** [comment]
Probably not, the next release will be done (hopefully) next week.

**Comment by Huma123** [comment]
Ok. Thanks for the update.
