### ISSUE TITLE
ZAP only report the first alert in array

### ISSUE THREAD

**Issue by g-sato** [zaproxy/zaproxy#2496]
Hello zap team,

Thank you very much for making this useful tool.

I identified another bug while I was verifying the fix of bug #2153.

Steps to reproduce:

1) Put this php script to http://localhost/test.php

[test.php.txt](https://github.com/zaproxy/zaproxy/files/273209/test.php.txt)

2) Submit this form through ZAP.

[posttest.html.txt](https://github.com/zaproxy/zaproxy/files/273211/posttest.html.txt)

3) Active Scan to history previous 2) request.(to get simple example, Active Scan Policy:Cross Site Scripting(Reflected)=Default, other=OFF)

I confirmed that the bug #2153 is fixed in zaproxy-w2016-05-16. (Thank you!!!)

But, I've found other bug.

In 'Alerts' tab, a XSS found in result. But only this case is detected.

[case1.txt](https://github.com/zaproxy/zaproxy/files/273224/case1.txt)

Actually, there is other XSS in scan history.These case is not in detect result.

[case2-5.txt](https://github.com/zaproxy/zaproxy/files/273226/case2-5.txt)

Is these results shuld be in 'Alerts' tab and 'HTML Report' like case1?

(Because an array value from HTML form has different mean by order in array.
ex. param[0]: name , param[1]: address, param[2]: phone number...
So, only param[0] is in scan result, causes miss the XSS in param[1],param[2]...)

Regards.

**Comment by g-sato** [comment]
Additional Information: ZAP2.5.0 has this probrem.

**Comment by davewichers** [comment]
Is this issue the same as #2584?

**Comment by thc202** [comment]
It's a different issue, in this case it's not reporting the issue in some of the parameters.

**Comment by kingthorin** [comment]
No. This one outlines a potential false negative while yours is an enhancement request.

**Comment by thc202** [comment]
The scanner was raising the alerts but not all alerts were being shown/reported because they all have the same name (`param[]`) thus considered the same alert.
