### ISSUE TITLE
ZAP Scanning for E-Business Suite Custom Code - OAF

### ISSUE THREAD

**Issue by shivinder07** [zaproxy/zaproxy#2508]
Hi All,

I was wondering if anyone can provide us a lead, with the question, that can we scan an Oracle E-Business Suite - Custom Code developed using OAF(Oracle Application Framework) technology with ZAP Tool?

Regards,
Shivinder

**Comment by psiinon** [comment]
Please dont ask questions as issues.
Answered on the User Group thread.

**Comment by shivinder07** [comment]
Can you please share the link if possible ?

**Comment by psiinon** [comment]
https://groups.google.com/d/msg/zaproxy-users/I0WRSxHF0o4/d04fSZPpAgAJ
