### ISSUE TITLE
Form Handling

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#2525]
The ZAP traditional and Ajax spiders explore an application by putting basic default values in all forms. These may often not be valid values, for example using "ZAP" when an email address is required.

The enhancement would allow the user to define default values based on pattern matching against the field names and/or ids.

It would also be very useful if it could show the user all forms and their associated fields for an application, and then allow the user to update the default values.

Expected Results
- User able to specify default values for all forms used by the ZAP spiders
- Display all of the forms and fields for an application and allow the user to update the default values to be used
- Full support for defining default values via the API

Note that this enhancement has been suggested for [MWoS 2016](https://wiki.mozilla.org/Security/Automation/Winter_Of_Security_2016#ZAP:_Form_Handling)

**Comment by kingthorin** [comment]
Should this also include expansion of ZAP's default entry set, and attempts to guess or intuit which might be applicable? i.e.: If the parameter name matches some dictionary of "email" address identifiers use zap@example.org, etc.

**Comment by thc202** [comment]
Project page:
https://wiki.mozilla.org/Security/Automation/Winter_Of_Security_2016/ZAP_Form_Handling

**Comment by rwehe** [comment]
Thanks for adding me @psiinon! 
Can we also assign to @cdlaguna?

**Comment by psiinon** [comment]
Sure, I just wanted it assigned to someone before I tweeted about the 'projects' label ;)
I'll invite @cdlaguna then assign it to them :)

**Comment by thc202** [comment]
Assigned :)

**Comment by thc202** [comment]
A new add-on, Form Handler, is now available in the marketplace, it allows to define custom values for the form fields (requires weekly release >= 2017-03-06).

**Comment by thc202** [comment]
Online help at:
https://github.com/zaproxy/zap-extensions/wiki/HelpAddonsFormhandlerFormHandlerHelp

**Comment by psiinon** [comment]
Many thanks guys!
