### ISSUE TITLE
Feature request: Passive scanning during fuzzing

### ISSUE THREAD

**Issue by kurobeats** [zaproxy/zaproxy#2528]
Just a couple: 
1. Option to apply passive scanner rules to fuzzing activities.
2. Saving all session files into a zip archive (or any other format like 7z) to keep files consolidated and decrease storage size.

**Comment by kingthorin** [comment]
Note: #2 is a duplicate of zaproxy/zaproxy#373

**Comment by kingthorin** [comment]
Changing title, removing second part since it's a duplicate.
