### ISSUE TITLE
Cookie is not set during script authentication when following redirect

### ISSUE THREAD

**Issue by aine-rb** [zaproxy/zaproxy#2531]
What steps will reproduce the problem?
1. Choose a test site using redirects during authentication such as WebGoat
2. Create a context with a Script-based Authentication method and a Cookie-based Session Management method
3. In the script (for example, a Javascript one), use the function: "helper.sendAndReceive(msg, true);" (notice the second parameter is set to true) to send the authentication request and follow redirects
4. Use a network analyzer to see the content of request/response packets (because ZAP doesn't display in his history the redirect requests/responses when authenticating, maybe I'll raise another issue)
5. Use the User Forced Mode to test authentication and session management

What is the expected output? What do you see instead?
The server sends a Set-Cookie header with a Location header. ZAP process the Location header in order to follow redirect but ignore the Set-Cookie header and doesn't set the cookie in the HTTP State. The session is not setup, the User Forced mode fail to authenticate.

What version of the product are you using?
2.4.3

Please provide any additional information below.
After a quick research, the problem seams to come from the processRedirectResponse() method in org.apache.commons.httpclient.HttpMethodDirector class.

I would like to work on this issue, if you agree.

**Comment by aine-rb** [comment]
I made the [pull request 2589](https://github.com/zaproxy/zaproxy/pull/2589) for this issue

**Comment by Zabee** [comment]
I am also facing the same issue. In my case, the issue starts to happen when target website to be scanned is in another VM.  If both ZAP and VM are in the same machine the script is working fine.

**Comment by Zabee** [comment]
I am running ZAP version 2.7.0 and ZEST version 27.0.0

**Comment by thc202** [comment]
@Zabee would you be available to try your scripts with a daily release to check if this address the issues you mentioned?

**Comment by Zabee** [comment]
Thanks for the information. I am middle of a scan. Once I am done with that
I will definitely try this.
Thanks a ton.

**Comment by Zabee** [comment]
Sorry, I was super busy for some time. Yes, the issue fixed for me cookies are getting set now. Thanks.

**Comment by thc202** [comment]
Thanks for letting us know!
