### ISSUE TITLE
Overhaul HTTPS Info Addon

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#2532]
Extending from https://github.com/zaproxy/zaproxy/issues/758
- [x] Change from dialog to tab
- [ ] Evaluate adding additional SSL/TLS related checks (and alerts) 
- [x] Replace SSLServer.java > https://github.com/spoofzu/DeepViolet (https://twitter.com/jvehent/status/729292231438295041)

Also:
- [ ] Make the add-on outbound proxy aware/compatible? [20160603: In it's current form it seems that the add-on returns info specific to the outbound proxy, not the actual target. Further testing/investigation may be required.]
  - [x] As an interim step: Display a warning if the add-on is being used when an outbound proxy is configured. (thc202: marked as done per zaproxy/zap-extensions#557.)

For further consideration:
- [ ] Add grading? https://github.com/mozilla/tls-observatory/issues/108
- [ ] Store/Persist details in DB?
- [ ] Add functionality similar to "scan" or "spider" panels? (Target dropdown? Start/stop/pause?)

**Comment by kingthorin** [comment]
Something like this should probably also apply https://github.com/zaproxy/zaproxy/pull/2665

**Comment by kingthorin** [comment]
Should we add a mode check like (https://github.com/zaproxy/zaproxy/pull/2665/commits/ebcfcc6d50b5fbcab0686cf8b41b77cb17852fa9) to https://github.com/zaproxy/zap-extensions/blob/alpha/src/org/zaproxy/zap/extension/httpsinfo/MenuEntry.java#L44 ?

**Comment by thc202** [comment]
It's not necessary, pop up menu items are unsafe by default and are automatically enabled/disabled depending on the mode. [1]

[1] https://github.com/zaproxy/zaproxy/blob/fa291cc3027f783081ea36cc75b8dc20a17de633/src/org/zaproxy/zap/view/popup/ExtensionPopupMenuComponent.java#L112-L123

**Comment by kingthorin** [comment]
Thanks!

**Comment by spoofzu** [comment]
Hi Milton from DeepViolet TLS/SSL scanning project.  I thought I would bring some improvements to the teams awareness.  I'm planning to add two features leverage data provided by Mozilla team soon, [roadmap]( https://github.com/spoofzu/DeepViolet/issues/5), listed as improvement 1 and 2.  To implement improvement 1, I plan to add support for Mozilla's cipher suite evaluation.  Mozilla provides an evaluation of the cipher suites to flag identify: modern, intermediate, and old, in the form of a live [JSON feed](https://statics.tls.security.mozilla.org/server-side-tls-conf-4.0.json).  The feed provides users a better evaluation of cipher suite strength.  Next, for improvement 2 I plan to use Mozilla's cipher mapping that is generated by tls-table.py.  April from the Observer project is exploring the idea of a JSON feed for this as well.  For now, I will run tls-table.py manually and include in the DeepViolet build.  The benefit that the table provides is the ability generate mappings between different cipher suite naming conventions: GnuTLS, NSS, IANA, and OpenSSL.  Today DV provides only IANA cipher suite names.

**Comment by kingthorin** [comment]
@spoofzu will access to the json feed be live/required? Or updated when the jar is produced?

From ZAPs perspective we'd prefer the later.

**Comment by spoofzu** [comment]
Good points, glad I asked.  Understand the concerns.  I will provide the offline option as a default.  That being the case, do you consider it acceptable if both (online/offline) options are provided?  My concern is that I'm an army of one, my release cycles may not coincide with Mozilla cipher suite blacklisting.  Even after I make a change, it could take the ZAP team sometime to integrate, test, etc.  There are some tradeoffs for security geeks to consider with each approach.

**Comment by kingthorin** [comment]
Yup, seems perfect

**Comment by spoofzu** [comment]
Added the feature to take advantage of the Mozilla cipher suite mappings.  This maps between different the ciphers byte code and the human readable cipher suite names.  Mozilla provides support to map between, GnuTLS, NSS, IANA, and OpenSSL.  For now I have IANA hardcode but I plan to make some improvements to Beta5 to pass such options in the API.  Next, I include Mozilla's cipher suite evaluations: modern, intermediate, old.  I include the JSON files in the DeepViolet JAR and parse them so there are no downloads as suggested.  Anyway, I know you guys are not ready for this stuff.  Just keeping you up to date on the progress.

**Comment by kingthorin** [comment]
@spoofzu thanks!

**Comment by kingthorin** [comment]
FYI for anyone that cares, I've started working on item 3 (the SSLServer to DeepViolet switch).

**Comment by thc202** [comment]
Great :)

**Comment by spoofzu** [comment]
I noticed in [Issue 2532 Part3 #911](https://github.com/zaproxy/zap-extensions/pull/911) there was some regard to the idea of a progress bar.  If your noticing a delay in DeepViolet it's likely where I enumerate the server ciphersuites.  Enumerating the ciphersuites is time consuming.  You could pop up a spinner animation in the application to keep the user occupied.  If you want a progress indicator I have some implementation thoughts.  Offhand I'm thinking a way to do this is performing the scanning work in another thread then use an event driven model (action/listener or MVC pattern) to send progress back to the caller (ZAP).  It would be simple to use from ZAP perspective.  Let me know if this is an improvement you would like me to make.

**Comment by thc202** [comment]
Having access to the state of the enumeration would be great, we can provide a more accurate state to the user (it could even allow cancellation? i.e. if it's taking too much time for whatever reason).

**Comment by kingthorin** [comment]
Closing per https://github.com/zaproxy/zap-extensions/pull/3328
