### ISSUE TITLE
Why zap.spider.status generates the error "Does Not Exist" ?

### ISSUE THREAD

**Issue by ioclaudio** [zaproxy/zaproxy#2533]
Hi all,
I'm using the pyhton library (python-owasp-zap-v2.4-0.0.2) with zap-2.5.0.
Executing this script:
https://gist.github.com/ioclaudio/79ab470e925e7651849a51fb5eabce60#file-gistfile1-txt

The function zap.spider.status() after calling "zap.spider.scan(target)" generates the error:
u'Does Not Exist'.
Which is the problem according to you?
Thank you

Claudio

**Comment by psiinon** [comment]
That version is very out of date - you'll need to update it to the latest version, which right now is 8
https://pypi.python.org/pypi/python-owasp-zap-v2.4

**Comment by ioclaudio** [comment]
ok, thank you I've installed the new version and disabled the api-key and now works

**Comment by thc202** [comment]
Great, thanks for letting us know!
