### ISSUE TITLE
Commandline compile

### ISSUE THREAD

**Issue by anantshri** [zaproxy/zaproxy#2536]
Hi Folks, i am not able to find any instructions on how to compile ZAProxy completely via command line. while exploring the repo i encountered travis ci build instructions pointnig to build/build.xml to be used with ant. I am not able to find what call should give me a complete deb same as the one produced officially. I am able to run `ant -buildfile build/build.xml dist` or `ant -buildfile build/build.xml full-release` but both generated a debian file of 37MB, looks like i missing some step.

Hope someone can point me to right reference.

**Comment by psiinon** [comment]
I must admit I always generate the releases from Eclipse.
We do have these instructions on the wiki, but they're not quite complete: 

- https://github.com/zaproxy/zaproxy/wiki/GeneratingTheFullRelease
- https://github.com/zaproxy/zaproxy/wiki/GeneratingTheWeeklyRelease

I'm guessing you havnt deployed any of the add-ons?

**Comment by anantshri** [comment]
ah add-ons might be the reason any direct ant command i can run to get addon's included. 

Having a console way to generate executable gives us the capability to automate stuff and that would help in all ways

**Comment by psiinon** [comment]
I can definitely see the benefit in this. I'm not aware of anything that should stop you from being able to generate ZAP releases from the command line. If you do have problems or questions then let us know - hopefully the about wiki pages will give you enough info.

**Comment by thc202** [comment]
@anantshri anything we can do to help with this?

**Comment by psiinon** [comment]
We now have a script for this :) https://github.com/zaproxy/zap-admin/blob/master/scripts/build_weekly_release.sh
