### ISSUE TITLE
Enhancement: Passive Scanner - HSTS

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#2538]
Per: https://github.com/zaproxy/zap-extensions/pull/218#discussion_r52290885

- [x] Multiple headers
- [x] Header on a plain HTTP response
- [x] Header with no max-age specified at all
- [x] Attempted definition via meta tag

https://tools.ietf.org/html/rfc6797

Question for the team:
Would we want to alert on every failure/non-compliance condition, or just the first one?

**Comment by thc202** [comment]
I'd go for the former, otherwise you have to (potentially) passive scan multiple times. Ideally you would just need to scan two times, once to get all alerts and the final one to verify that everything is addressed (fixed or ignored with alert filters).

**Comment by kingthorin** [comment]
Sounds good to me.

**Comment by kingthorin** [comment]
Fixed in https://github.com/zaproxy/zap-extensions/commit/1fbf57d6c35d0f57db8e264b46a5c233516e986f
