### ISSUE TITLE
Enhancement: Passive Scanner - XFO

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#2539]
- [x] Check for duplicate/multiple header entries.
- [x] If XFO is set, make sure that it actually contains one of the valid values. 
  - [The [existing code](https://github.com/zaproxy/zap-extensions/blob/cb024c39f0ef1cf5998dec4f759943da1138580b/src/org/zaproxy/zap/extension/pscanrules/XFrameOptionScanner.java#L68-L70) actually does handle the `deby` vs `deny` situation, it just wasn't very specific about it. In addressing this enhancement it will become more obvious what the issue is.]
- [x] Check for XFO defined via META (https://twitter.com/soaj1664ashar/status/724609318444761088)

<sub>Spec ref: https://tools.ietf.org/html/rfc7034</sub>

**Comment by thc202** [comment]
Released in version 17 of Passive scanner rules add-on.
