### ISSUE TITLE
Asp.Net WebForms authentication

### ISSUE THREAD

**Issue by RaptorCZ** [zaproxy/zaproxy#2543]
I'm trying to force scan engine to login to our web site and scan all pages. It is standard web forms site with login dialog. How to configure session to log in? Tried everything but seems that nothing works. I'm not even sure, if spider is trying to login. Only anonymous pages and scripts etc. are scanned.

Tried to use session properties, set form-based authentication, set POST data based on fiddler requests. Still nothing.

What I'm doing wrong? Is there any help page for this case?

**Comment by psiinon** [comment]
Have you looked at https://github.com/zaproxy/zaproxy/wiki/FAQformauth ?
Thats probably the vest documentation we have right now.

**Comment by RaptorCZ** [comment]
Thnx, got it to work somehow using this tutorial. But it sometimes work and sometimes not. Based on Output tab sometimes authentication failed and nothing happens.

What is the right way to start attack if I set context and authentication properties? Using Quick start tab and Attack button, or using context menu on site tree? I simply want to start attack on whole site using entered info. Does it mean I have to set session properties and make this one session active, or I can persist Context with login info and use it anytime?

**Comment by kingthorin** [comment]
@RaptorCZ Quick Start is just that, it's meant to be a quick point and shoot scan. If you need additional configuration (authentication, etc) then starting via other means (API, new active scan, etc) is the way to go.
