### ISSUE TITLE
How to know that script is loaded then running zap from cmd

### ISSUE THREAD

**Issue by aisbaa** [zaproxy/zaproxy#2560]
I have a proxy script that adds session cookie header to each request. It works from GUI, but I cant get it working from command line. I've running zap with
```bash
$ ./zap.sh -daemon -script ./session-cookie.js
```

```bash
$ ./zap.sh -daemon \
    -config script.scripts.name="Session cookie" \
    -config script.scripts.engine="ECMAScript" \
    -config script.scripts.type=proxy \
    -config script.scripts.enabled=true \
    -config script.scripts.file="./session-cookie.js"
```

When execute urlopen in python shell:
```python
>>> zap.urlopen(target)
```

And finally inspect http request (packet) in wireshark. Unfortunately request did not contain session cookie. This made me question is this script is actually executed? And how can I make sure it is executed?

**Comment by thc202** [comment]
That can be achieved with the ZAP API endpoint `http://zap/UI/script/view/listScripts/`, that allows to know if it was correctly loaded, if it's enabled and if it ran without errors.

Note that the ECMAScript/JavaScript engine's name should be "Mozilla Rhino", if Java 7, or "Oracle Nashorn", if Java 8+.

For questions about ZAP usage is better to use the mailing list. [1]

Please, close the issue if the question was addressed.
Thank you.

[1] http://groups.google.com/group/zaproxy-users

**Comment by aisbaa** [comment]
Thats exactly what I was looking for, thank you! :+1:

**Comment by thc202** [comment]
You're welcome.
