### ISSUE TITLE
How to delete all resources related to a specified url in zapproxy scan in client api?

### ISSUE THREAD

**Issue by cwjcsu** [zaproxy/zaproxy#2566]
I need to release all resources(alerts,spider result,active scan result,memory usage) for the specified url and not interfere scans of other urls. Overview the whole java client api and RESTful api of zapproxy,I only got :
```
http://localhost:8080/UI/core/action/deleteAllAlerts
```
which i think will delete all alerts including those belong to the other urls.

**Comment by thc202** [comment]
Correct that will delete all alerts.

To remove the results of specific spider and active scanner scans it should be used the following endpoints:
`http://zap/UI/spider/action/removeScan/`
`http://zap/UI/ascan/action/removeScan/`

(Note that does not remove the persisted messages just info/results of the scans.)

To delete URLs/messages (and corresponding alerts) it should be used:
`http://zap/UI/core/action/deleteSiteNode/`

The latter endpoint was added in the latest ZAP release (2.5.0), it also requires a new ZAP API Java Client version. [1]

For questions about ZAP usage is better to use the mailing list. [2]

Please close, the issue if the question was addressed.


[1] https://github.com/zaproxy/zap-api-java
[2] http://groups.google.com/group/zaproxy-users

**Comment by cwjcsu** [comment]
Thanks @thc202 ,I've already done it.
