### ISSUE TITLE
Do not modify released tar-balls

### ISSUE THREAD

**Issue by blshkv** [zaproxy/zaproxy#2567]
You have released a "new" 2.5 zap-extensions with a difference size but the version number.
So it is confusing now, were these packages compromised or they are still legitimate.
I had to do quick comparison to make sure that there are no maclious code injected and update the checksum:
https://github.com/pentoo/pentoo-overlay/commit/bcbac2b4ae12e60b0c81555b8ac0f97857060e01

The integrity of packages is an important part of any project.
At Pentoo, we are trying our best to insure that the packages which we sign are clean.
Please help us in this process and do not update existing releases.

P.S. Yes, the url is different, but it is common to validate the checksum *after* a file has been downloaded, so I suggest to change the version number too

**Comment by psiinon** [comment]
Well, its difficult for us to help you if we dont know that you're repackaging our software and what your requirements are;)
We maintain the checksums in the files that we use for our 'check for updates' call, and the latest one is https://github.com/zaproxy/zap-admin/blob/master/ZapVersions-2.5.xml
The one for the previous version is https://github.com/zaproxy/zap-admin/blob/master/ZapVersions-2.4.xml - some of the add-ons are essentially the same but have been regenerated and have new checksums.
The zap-extensions release is essentially the ZAP marketplace - its where we download add-ons from within ZAP. How are you using these add-ons? Are you including them as standard in Pentoo (not really recommended) or have you changed the ZAP marketplace code?
We do want to help other projects repackage ZAP, but we would need to understand (and agree with) your requirements before we make any changes to our processes.
We can explore you requirements on this issue or we could set up a call, either is fine with me.

**Comment by blshkv** [comment]
we dont really repackaging it. it is more like a custom install.
And the way how Gentoo works is that it validates the checksum after the file is downloaded. 

I guess, I will have to rename extensions and make a prefix (2.5) as a major version number.
Thank you for clarifications.
