### ISSUE TITLE
Receiving mails from ZAP even if i stop the tool

### ISSUE THREAD

**Issue by mdarunkumar** [zaproxy/zaproxy#2569]
Hi ZAP Team,

I tried to verify my website using this tool. But I'm keep on receiving junk mails from ZAP. May I know the reason for this and guide me how to stop this?

Thanks,
Arun

**Comment by kingthorin** [comment]
Your app must have one or more forms that send email, which is now likely queued on your mail server. You could clear the queue or setup a mail rule to deal with them.

It's best not to test things in Production until you're 100% sure of the impacts.

**Comment by mdarunkumar** [comment]
Thanks but this is type of form filling can you please tell to stop form filling in word press. Since I have stopped in on Friday but till now I'm getting mail

**Comment by kingthorin** [comment]
If you let ZAP fill out the form 1000s of times Friday the only way to stop it is to deal with the mail your system is still trying to send.

https://groups.google.com/d/topic/zaproxy-users/e7gmvD8Nl7A/discussion

**Comment by mdarunkumar** [comment]
Thanks
