### ISSUE TITLE
CacheableScanner - Evidence field doesn't contain Evidence

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#2573]
Encountered "Storable and Cacheable Content" alert today, "Evidence" is reported as:

> In the absence of an explicitly specified caching lifetime directive in the response, a liberal lifetime heuristic of 1 year was assumed. This is permitted by rfc7234.

This should probably be "Other Info" not "Evidence".

<sub>Code ref: https://github.com/zaproxy/zap-extensions/blob/a3c6f7ecb31635a311e722f524f510858f67a3e2/src/org/zaproxy/zap/extension/pscanrulesAlpha/CacheableScanner.java</sub>

**Comment by shivamdixit** [comment]
PR shared – https://github.com/zaproxy/zap-extensions/pull/413

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#413.
