### ISSUE TITLE
CookieLooselyScopedScanner - Attack field isn't used properly

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#2574]
Encountered an alert from this passive scanner today. "Attack" is listed as:

> Cookies set from a subdomain like app.foo.bar are transmitted only to that domain by the browser. However, cookies scoped to a parent-level domain may be transmitted to the parent, or any subdomain of the parent.

Which seems more like description than attack.

<sub>Code ref: https://github.com/zaproxy/zap-extensions/blob/b261d873a069e28ee1b9d92c478e5fed6c9eebd9/src/org/zaproxy/zap/extension/pscanrulesBeta/CookieLooselyScopedScanner.java</sub>

**Comment by shivamdixit** [comment]
What should be the correct "Attack" field for it?

**Comment by kingthorin** [comment]
Attack can be empty string, this info could be added to description.

**Comment by shivamdixit** [comment]
@kingthorin PR shared – https://github.com/zaproxy/zap-extensions/pull/438/files

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#438.

**Comment by thc202** [comment]
Released in version 14 of Passive scanner rules (beta) add-on.
