### ISSUE TITLE
XPoweredByHeaderInfoLeakScanner - Evidence should highlight header not value to prevent incorrect selection

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#2575]
Encountered a header containing the following:

> Set-Cookie: ASP.NET_SessionId=utternsomevaluea2wnsublig; path=/; HttpOnly
> X-Powered-By: ASP.NET

When viewing the alert, the highlight in the response tab is incorrectly chosen as the set-cookie occurrence. The passive scanner should probably highlight the first occurrence of the X-Powered-By header itself, not the value.

<sub>Code ref: https://github.com/zaproxy/zap-extensions/blob/901fb4663bdb78b47f9f112cf12c1d4307dbc4d6/src/org/zaproxy/zap/extension/pscanrulesAlpha/XPoweredByHeaderInfoLeakScanner.java</sub>

**Comment by shivamdixit** [comment]
@kingthorin I've shared a PR for this https://github.com/zaproxy/zap-extensions/pull/412

**Comment by shivamdixit** [comment]
Shall we close this now?

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#412.
