### ISSUE TITLE
CSRFCountermeasures - Attack and Evidence not applicable

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#2576]
The alert "Absence of Anti-CSRF Tokens" lists the following for both "Attack" and "Evidence":

> None. Warning only.

The two fields should probably be blank, the description or other info could be enhanced to imply/confer the warning nature of the result.

<sub>Code ref: 
https://github.com/zaproxy/zap-extensions/blob/b261d873a069e28ee1b9d92c478e5fed6c9eebd9/src/org/zaproxy/zap/extension/pscanrulesBeta/CSRFCountermeasures.java
https://github.com/zaproxy/zap-extensions/blob/ce47ebd74d69e6caee5a6725a855c531f3f2ddfc/src/org/zaproxy/zap/extension/ascanrulesBeta/resources/Messages.properties#L61

</sub>

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#410.

**Comment by thc202** [comment]
Released in version 14 of Passive scanner rules (beta) add-on.
