### ISSUE TITLE
Reflected XSS False Positive when payload is in HTTP Response Title or Response Header

### ISSUE THREAD

**Issue by davewichers** [zaproxy/zaproxy#2577]
In ZAP 2.4.3, if an application echoes the value of a parameter in the page title, ZAP is saying this is a reflected XSS, when its not. For example, a response like:

HTTP/1.1 400 String:PARAMETER_VALUE is not a valid value
Then some response headers
Then a response body

ZAP is flagging the fact that PARAMETER_VALUE is included in the response without modification as an XSS vuln, but its not, when its in that location of the HTTP Response.  I suspect the same is true if its echoed in the value of a response header (like a cookie for example). That wouldn't be a direct XSS vuln.

In fact, I just saw another where the PARAMETER_VALUE was included in a Content-Disposition: header and ZAP flagged that as an XSS too, when its not. e.g., Content-Disposition: attachment; filename="filename-with-PARAMETER_VALUE"

I'm pretty sure that the reflected XSS rule should simply ignore the entire Header block and ONLY look for values echoed in the response body. Not sure if this has been fixed already in 2.5.0.

**Comment by kingthorin** [comment]
I'm guessing that this has to do with [TestCrossSiteScriptV2](https://github.com/zaproxy/zap-extensions/blob/a7942b9bef8ffa42b08e9f20ff13ac8b13ead1fa/src/org/zaproxy/zap/extension/ascanrules/TestCrossSiteScriptV2.java), which leverages HtmlContextAnalyser and does combine header and body [in it's constructor](https://github.com/zaproxy/zaproxy/blob/333f43b942da411f434c0cab782b94844697698c/src/org/zaproxy/zap/httputils/HtmlContextAnalyser.java#L91).

**Comment by kingthorin** [comment]
I've been unable to recreate this issue. Even setting the XSS scanner to High/Insane. The following php code includes the test cases I tried.

```php
<html>
<?php
if(isset($_REQUEST['name'])) {
  $name = $_REQUEST['name'];
  //header("X-Test: $name", true);
  $file_name = "filename-with-" . $name;
  header("Content-Disposition: attachment; filename=$file_name", true);
  echo "Welcome"; // $name<br>";
}
?>
</html>
```

As can be seen in the screenshot below the eye-catcher is injected but ZAP does not proceed to test further:
![image](https://user-images.githubusercontent.com/7570458/36954035-26814418-1fed-11e8-92aa-db0f26c2af6a.png)

Perhaps the issue has been corrected since original reporting or perhaps there were further injections/outputs further in the response that went un-noticed at the time.

**Comment by davewichers** [comment]
The above appears to test the Content-Disposition header. But what about the HTTP Response Title? That was the originally reported issue. e.g., create a server response with a 1st line like this:
HTTP/1.1 400 SomeStringWithSomeContentThatIsReflectedFromTheRequest

**Comment by kingthorin** [comment]
Thanks @davewichers I'll give that a shot too and provide an update.

**Comment by kingthorin** [comment]
Same for the prime header. The eye-catcher is injected but ZAP doesn't scan further.:
```php
<html>
<?php
if(isset($_REQUEST['name'])) {
  $name = $_REQUEST['name'];
  header("HTTP/1.1 400 String:$name is not a valid value");
  echo "Welcome"; 
}
?>
</html>
```

![image](https://user-images.githubusercontent.com/7570458/36984393-c9c9b7fc-2062-11e8-9c7f-f4b214354dc1.png)

**Comment by davewichers** [comment]
OK. I reported this so long ago that I have no idea what app I found this
issue in. If I notice it again, I'll let you know. So I guess you can close
this for now.

-Dave

**Comment by kingthorin** [comment]
Thanks @davewichers
