### ISSUE TITLE
Silent scanning

### ISSUE THREAD

**Issue by ioclaudio** [zaproxy/zaproxy#2580]
Hi all,
is possible to have a "silent scanning"?
I mean without messages as:
 [HSQLDB Timer @35c21f94] INFO hsqldb.db..ENGINE  - Checkpoint start
...
Is there a configuration to avoid these messages on the terminal?
Thank you

cld

**Comment by kingthorin** [comment]
You can redirect stdout/stderr to `/dev/null`. Start the process in `screen`. Background (`bg`) the process. Launch the GUI. Lots of options.

What's the actual problem/goal here?

**Comment by thc202** [comment]
You can also configure what's logged (or not) by changing the `log4j.properties` file (located in ZAP's home dir [1]).

We could also allow to disable the log to standard output when running in daemon/GUI.

**Comment by thc202** [comment]
@ioclaudio is the issue/question addressed with the above comments? If not, could you provide more information about the issue?
