### ISSUE TITLE
Reveived virus alert when upgrading to ZAP 2.5 - Trojan 

### ISSUE THREAD

**Issue by ppfeifer** [zaproxy/zaproxy#2581]
When I upgraded to ZAP 2.5 my systems virus scan deleted these files and labeled them as Trojan.  Are these files legitimate for ZAP or has a virus been introduced to you upgrade?  
OWASP ZAP\fuzzers\fuzzdb\web-backdoors\pl-cgi\perlcmd.cgi
OWASP ZAP\fuzzers\fuzzdb\web-backdoors\php\simple-backdoor.php
OWASP ZAP\fuzzers\fuzzdb\web-backdoors\php\php-backdoor.php
OWASP ZAP\fuzzers\fuzzdb\web-backdoors\jsp\jsp-reverse.jsp
\OWASP ZAP\fuzzers\fuzzdb\web-backdoors\jsp\cmdjsp.jsp
\OWASP ZAP\fuzzers\fuzzdb\web-backdoors\exe\nc.exe
\OWASP ZAP\fuzzers\fuzzdb\web-backdoors\asp\cmdasp.aspx
\OWASP ZAP\fuzzers\fuzzdb\web-backdoors\asp\cmdasp.aspx
\OWASP ZAP\fuzzers\fuzzdb\web-backdoors\asp\cmdasp.asp
OWASP ZAP\fuzzers\fuzzdb\web-backdoors\asp\cmd.aspx
\OWASP ZAP\fuzzers\fuzzdb\web-backdoors\asp\cmd-asp-5.1.asp

**Comment by kingthorin** [comment]
They're backdoors packaged by fuzzdb, if you don't intend to use them you can freely let your AV product remove or quarantine them.

**Comment by ppfeifer** [comment]
Okay Thanks.    I will ask sys admin to include them.  I just wanted to make sure they were legitimate.

**Comment by kingthorin** [comment]
Here is the original source: https://github.com/fuzzdb-project/fuzzdb/tree/master/web-backdoors
