### ISSUE TITLE
Alert Filters Appear not to Function Properly

### ISSUE THREAD

**Issue by twright-0x1** [zaproxy/zaproxy#2599]
When setting up an Alert Filter (via a context's Alert Filters dialog), I end up with "double" alerts in the Alerts tree.  I.e., when a relevant alert is triggered, I see a filtered version of the alert and an unfiltered version.

For example, if I set up a filter for "Incomplete or No Cache-control and Pragma HTTP Header Set" such that this alert is flagged at a risk level of "Info," when the alert is actually triggered, I see both its filtered "Info" level and its default "Low" level iterations in the Alerts tree.

An interesting note, here:  while the Info and Low iterations of the alert are the same type of alert, they always appear to be for different URLs (same site, though).  Almost as if the filter works for on some triggered alerts, but not all.

There is no difference in whether or not I modify the alert filter to use a URL regex or leave the URL setting empty.

**Comment by kingthorin** [comment]
Alert filters are not applied retro-actively (as noted in the help documentation). 

So if you have some alerts, turn on or configure an alert filter rule then end-up with further alerts, you'll end-up in the condition you're in (the originals plus the now modified/filtered new ones).

**Comment by twright-0x1** [comment]
Yep:  I had, in fact, read through the documentation and thought that might have been my problem.  It was not.  To test, I started a fresh session that included no prior alerts.

**Comment by kingthorin** [comment]
Then your rule match setting (url/regex) probably isn't matching everything.

> An interesting note, here: while the Info and Low iterations of the alert are the same type of alert, they always appear to be for different URLs (same site, though)

**Comment by twright-0x1** [comment]
Hmmm...  Well, the behavior I (thought I) observed happened whether or not I used a URL regex (e.g., at first, I left the URL setting empty so that all instances of the filtered alert would be caught; then I tried a URL regex that would trigger for all of my target site).

That said, I just attempted to repeat my earlier use of filters and, now, I'm unable to see the problem!  I suppose this is a case of "ID-10-T" on my part?

**Comment by kingthorin** [comment]
Not at all. "Weird" things happen with tech all the time. Software is created by humans and we're not perfect, nor are users. I'm going to close this but please feel free to comment or reopen (or both) if you manage to re-create.

**Comment by twright-0x1** [comment]
I _really_ hate to say it, but I'm now seeing this again.  Basically, if I set a filter, regardless of whether or not I use a URL or URL regex with that filter, the target alert is not always filtered.  In fact, the only time I really got filtering to work was earlier today when I thought I had simply gotten my observation wrong.

**Comment by kingthorin** [comment]
Ok can you provide some specifics. The Regex(es) you're using, examples where it did work, and where it didn't. Screenshots are fine.

**Comment by twright-0x1** [comment]
Okay, I believe I've figured out what the cause of my trouble has been.

Turns out, it isn't enough to set an alert filter for a context; for filtering to work properly, I found I also had to configure "Include in Context" (not sure if configuring "Exclude from Context" would have had the same effect...I didn't try that).

The real source of pain for me has been that I can't delete alerts from the alert tree (this is a bug that I reported last week).

Because I can't clean up the alert tree, in order for alert filtering to work, it's imperative that I start with a pristine, empty alert tree, or else the tree will be polluted with alerts that I want to filter.  However, as I discovered this morning, alert filtering won't work in a context until regexes for "Include in Context" have been configured.  Unfortunately, when I'm working on a site, I typically won't know ahead of time what those regexes should be.

So...  I've been ending up with alert trees that contain the same alert, both non-filtered (caught _before_ I was able to setup "Include in Context") and filtered.

I'm not sure this is an alert filter bug.  It's definitely a problem that I can't clean up my alert tree by deleting alerts.  If I could, then I could setup alert filtering whenever I wished, and simply manually clean up my alert tree to remove items that would otherwise be filtered.  (Any chance that alert-tree-delete bug could be assigned a high priority for fixing?)

Thanks for your patience on this!

**Comment by twright-0x1** [comment]
Oh, not sure that it matters, but a good test site is "www.whitehouse.gov."  Simply start with a fresh ZAP session (empty alert tree), configure the default context with an alert filter on "Incomplete or No Cache-control and Pragma HTTP Header Set" and go with a New Risk Level of "False Positive."  Then, open a browser and pull up www.whitehouse.gov.

Next, repeat everything, but, when adding the alert filter, also configure "Include in Context" to use the regular expression "https://www.whitehouse.gov.*".

You should see that the filtering works as expected the second time around.

**Comment by kingthorin** [comment]
@twright-0x1 version 9 of the Alert Filters addon has been release this morning. It now include the following enhancements:

* Filters can be set either related to a Context or Globally.
* You can test what the filter(s) will apply to.
* You can update existing alerts.

Please let us know if this addresses your concerns.

**Comment by twright-0x1** [comment]
Thanks!  Some very preliminary testing indicates that this will be useful.

I appreciate the new global-level alert filtering, since it means I can start out with some basic filters before knowing the "Include in Context" URL regex entries I'll employ.

Also, I see that I can set both global- and context-level filters for the same alert, and that the global filter appears to take precedence.  E.g., if I have a global filter for alert X setup to classify X as risk level "Info," and, simultaneously, a context filter for alert X classified as "High," the global filter wins out.

As it happens, I have an actual engagement this week in which I'll be using ZAP.  So, I'll circle back in a few work days with any additional feedback.

**Comment by twright-0x1** [comment]
So, the follow-up is positive:  the alert filter changes appear to be working well, thus far.  Thanks to the ZAP developers for their efforts!

**Comment by kingthorin** [comment]
Thanks @twright-0x1. I’m going to close this ticket, if something else comes up feel free to open a new one.
