### ISSUE TITLE
The Crawled Url count does not reset for AjaxSpider extension

### ISSUE THREAD

**Issue by Omkar20895** [zaproxy/zaproxy#2610]
- When a site is crawled using AjaxSpider we get a url count on the spiderPanel that shows the requests sent to the site. 
- When we attack again using AjaxSpider the crawled url count does not reset to 0, instead it adds to the previous crawled url count. 
- It needs to be reset to zero every time a new AjaxSpider is started.

**Comment by thc202** [comment]
Released in version 16 of Ajax Spider add-on.
