### ISSUE TITLE
Filtering ZAP Reports to Show High Risk Items

### ISSUE THREAD

**Issue by leonardwkerr** [zaproxy/zaproxy#2615]
This is a feature I wold like to see added into ZAP, filtering the alerts by the severity of the risk.

**Comment by kingthorin** [comment]
This is possible in the reporting addons.

**Comment by thc202** [comment]
Reopening, this is about the core view alerts. [1]

[1] https://groups.google.com/d/topic/zaproxy-users/Mxmq7wnYcx4/discussion
