### ISSUE TITLE
Allow to choose the name of session snapshots

### ISSUE THREAD

**Issue by davewichers** [zaproxy/zaproxy#2618]
We have the ability to Persist a session, but once done, we have Snapshot Session, but not Save As, which would allow the user to pick the name of this saved session. Snapshot Session autogenerates a name for the snapshot based on the Session name and current time, but I find those names very confusing/hard to read, especially if you have made several of them. (they seem to get longer and longer).

Anyway, I propose either:

1) Replacing Snapshot Session with Save As.
2) Adding a Save As... feature for sessions (but this creates yet another option :-( )
3) If you can figure out how, enhance Snapshot Session to allow the user to use the default autogenerated snapshot name OR chose their own name.

I think 1 or 3 are the best options as ZAP already has the 'too many features' problem so adding another one should be avoided if possible.

**Comment by kingthorin** [comment]
@davewichers Would you prefer Save as (newly saved session becoming active) or ability to specify snapshot name? (Where snapshot functionality stays the same as it currently is, a point in time copy of the session.)

**Comment by davewichers** [comment]
Save As, because I think that is more natural/expected behavior.

Dave

**Comment by psiinon** [comment]
My comment from #3186 as @davewichers probably didnt see it:

The reason we changed from Save As to Persist is the latter is more accurate.
People were getting confused - Save As implies to most people that they are saving a copy, which is not what it does. Its persisting the session in a db that keeps up to date whenever it changes.
So I dont think we should change Persist to Save as unless we also change how it works.

And to follow up...
I still think most people will expect "Save as" to save a one time copy, which it wont be. The snapshots are one time copies, but as mentioned they dont allow the snaphot to be named.

How about either 

* "Snapshot as..." which saves gives a dialog and saves the snapshop with the given name
* "Rename session..." which saves the session with the new name and makes it the active one

@davewichers (and anyone else) any preferences on those?

**Comment by davewichers** [comment]
Thanks for the explanation. That is helpful. I like Snapshot As ...

Dave

**Comment by kingthorin** [comment]
@psiinon @davewichers thank you both. I'll get working on it.

**Comment by thc202** [comment]
Issue title updated to match the current changes.

**Comment by thc202** [comment]
Fixed in #3186.
