### ISSUE TITLE
How to choose the tests?

### ISSUE THREAD

**Issue by ioclaudio** [zaproxy/zaproxy#2629]
Hi,
is there a way to configure the test executed by the command: zap.ascan.scan(target) ?
That is I would choose only some test among those executed by default.
Thank you
cld

**Comment by kingthorin** [comment]
You can configure a scan policy.
https://github.com/zaproxy/zap-core-help/wiki/HelpStartConceptsScanpolicy

**Comment by thc202** [comment]
Which can be specified with the "scanPolicyName" parameter.
The policy can also be configured with the ZAP API. [1]

[1] https://github.com/zaproxy/zaproxy/wiki/ApiGen_ascan

**Comment by thc202** [comment]
@ioclaudio is the issue/question addressed?

**Comment by ioclaudio** [comment]
yes thank you

**Comment by thc202** [comment]
Thanks for letting us know.
