### ISSUE TITLE
Improve CSP tests

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#2630]
Some good posibilities in the HTTP Observatory tests: https://github.com/mozilla/http-observatory/blob/master/httpobs/scanner/analyzer/headers.py#L8
also see https://github.com/mozilla/http-observatory/blob/master/httpobs/docs/scoring.md

**Comment by kingthorin** [comment]
Merge with https://github.com/zaproxy/zaproxy/issues/527 ?

**Comment by psiinon** [comment]
Yeah, should have rembered that ;)
Duplicate of #527
