### ISSUE TITLE
Problem with subsequent requests with the sequence add-on

### ISSUE THREAD

**Issue by apeyre06** [zaproxy/zaproxy#2634]
There is a problem with the subsequent requests (requests following the page actually tested) sent by the sequence add-on.
In fact, the sequence add-on don't inject cookies sent with the previous requests, which leads to lose the session on the server side.

**Comment by srirambk** [comment]
Please let me know is anyone looking into this issue? Even I encountered the same problem.

**Comment by thc202** [comment]
Yes, I uploaded a test version [1] along time ago to obtain some feedback. Apparently it works in some cases, others don't. I'll have to take a look at it again.

You're more than welcome to try it, note that it's old (some features/fixes might be missing).

[1] https://github.com/thc202/zap-extensions/releases/tag/zest-test-version

**Comment by srirambk** [comment]
Yes.  I tried it and still getting the same issue. Glad to know that you are going to look at it.

**Comment by thc202** [comment]
Thanks for giving it a try.

How did you start the sequence scanning? With Active Scan dialogue or through the context menu "Active scan sequence"? With the test version no cookie was being sent at all?

**Comment by kingthorin** [comment]
@srirambk are you able to answer the outstanding questions?
