### ISSUE TITLE
Slow mouse wheel scrolling in site tree

### ISSUE THREAD

**Issue by NVolcz** [zaproxy/zaproxy#2642]
When having a well populated site tree mouse wheel scrolling becomes very slow/not usable.
This was observed on Windows 10 with Java 8:
```
$ java -version
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)
```

**Comment by psiinon** [comment]
What platform and JVM are you using? As many details as possible please - its not a problem I've noticed on the platforms I've used.

**Comment by NVolcz** [comment]
Sorry. Accidentally pressed enter

**Comment by kingthorin** [comment]
Perhaps you could be a bit more quantitative on "well populated" too. 50 sites? 100 sites? 150 expanded nodes?

Are you using the default view?
Is your Win10 virtualized?

**Comment by NVolcz** [comment]
The tree contains 18 sites and 1012 nodes in total. 
I also noticed today that when the tree is minimized and can be displayed vertically the scrolling is performed horizontally. Maybe some scrolls are forwarded to some horizontal handling code and dropped?

I have several plugins installed but is using the default view (I'll create a fresh install and try to load the session later).
Windows is not being virtualized.

**Comment by thc202** [comment]
The slow scrolling is caused by lack of (enhanced) functionality.

That's the expected behaviour, it scrolls horizontally if it's not needed vertically.

**Comment by NVolcz** [comment]
What is enhanced functionality?

**Comment by thc202** [comment]
One of the ways is to change the panel that contains the trees (Contexts and Sites) to implement Scrollable (to scroll like a (single) tree).
