### ISSUE TITLE
SHA-512 Payload Processor

### ISSUE THREAD

**Issue by rschwass** [zaproxy/zaproxy#2643]
I see that I can use other hash functions on payloads but not the SHA-512. Can this be added?

**Comment by kingthorin** [comment]
Should be doable.

<sub>Refs:  https://github.com/zaproxy/zap-extensions/tree/7b7cecc085597ad6ff52cf46040fa0902d84c3ad/src/org/zaproxy/zap/extension/fuzz/payloads/processor & 
http://docs.oracle.com/javase/6/docs/technotes/guides/security/StandardNames.html#MessageDigest</sub>

**Comment by rschwass** [comment]
Great!

**Comment by thc202** [comment]
Reassigning, hope not stepping on existing work @kingthorin.

Hopefully we should be able to release a new version of fuzz add-on next week.

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#447.

**Comment by thc202** [comment]
Released in version 6 of Fuzzer add-on.
