### ISSUE TITLE
ZAP 2.5.0 do not calculate page length correctly in assertion

### ISSUE THREAD

**Issue by g-sato** [zaproxy/zaproxy#2671]
Hello zap team,

I've found a bug about that ZAP do not calculate page length correctly in case of website contains multibyte text when assert length in ZEST Script.

［Steps to reproduce］

1) Download this file, and rename file multibyte.html.txt to multibyte.html.
(This html file containts Japanese Text 'こんにちは' means 'Hello' in English)

[multibyte.html.txt](https://github.com/zaproxy/zaproxy/files/359719/multibyte.html.txt)

2) Put multibyte.html to web server.

3) Run ZAP 2.5.0 and Access multibyte.html on web server.

4) Create a new Zest standalone script, and add the history of multibyte.html to that Zest Script.

After this, two assertion added automatically below:
'GET multibyte.html' step that 'Assert - Status Code(200)'
'Assert - Length(response body = 58 +/- 1%)'.

5) Run that Zest standalone script under two condition below:

CASE1:
Response header contains 
>  Content-Type: text/html; charset=UTF-8

CASE2:
Response header contains 
>  Content-Type: text/html

RESULT:

CASE1:
[case1_response.txt](https://github.com/zaproxy/zaproxy/files/359790/case1_response.txt)

-> Assertion of Content Length returns 'FAILED'. Because Content-Length is 48.

> 6	GET	http://localhost/zaptest/multibyte.html	200	OK	14307	58	jar:file:/C:/Users/user123/Desktop/ZAP_2.5.0/zap-2.5.0.jar!/resource/icon/16/101.png	FAILED Assert - response.body length: expected 58 got 48 (17% difference)

CASE2:
[case2_response.txt](https://github.com/zaproxy/zaproxy/files/359792/case2_response.txt)
(the same response except Content-Type header.)

-> Assertion of Content Length returns 'OK'. Content-Length is 58.

> 9	GET	http://localhost/zaptest/multibyte.html	200	OK	2022	58	jar:file:/C:/Users/user123/Desktop/ZAP_2.5.0/zap-2.5.0.jar!/resource/icon/16/102.png	

[Additional Information]
When test webpage containts singlebyte text, this bug is not represent.

Regards.

**Comment by thc202** [comment]
See #2669.
