### ISSUE TITLE
Ability to set active scan requests rate limit per site

### ISSUE THREAD

**Issue by alienatix** [zaproxy/zaproxy#2679]
Ability to set a requests rate limit is critical when scanning APIs. Since many APIs usually have some user quota for requests that can be sent to API per time interval (f.ex. Twitter API  allows a client to make 180 search queries per 15 minute window, otherwise an error is returned). 

The same problem is also relevant to websites that are protected against DOS attacks by services like Cloudflare etc.

I believe that adding this setting per Site in ZAP would be very beneficial.

Original discussion: https://groups.google.com/d/topic/zaproxy-users/I-pGLZCayvo/discussion

**Comment by thc202** [comment]
Closing for administrative tasks.

**Comment by thc202** [comment]
There's a PR to add (global) rate limiting, this would build on top of that zaproxy/zap-extensions#4011.

**Comment by thc202** [comment]
Closing as done with the global rate limiting, while adding per scan/tool seems useful it does not actually allow to enforce the limits (as the user can easily/accidentally exceed them, e.g. spider, manual).

Feel free to leave a comment explaining the use case if you still think having per scan is useful.
