### ISSUE TITLE
Enhancement Request: Improve SSL Negotiation Failure Error Handling

### ISSUE THREAD

**Issue by davewichers** [zaproxy/zaproxy#2699]
There are numerous reasons SSL Negotiations can fail, such as:

1) Server cert isn't trusted.
2) Server cert is expired
3) Server cert is revoked (if ZAP checks that)
4) Server cert domain doesn't match site's domain
5) Failure to negotiate compatible ciphersuites
6) Java8 specific refusal to use weak ciphers
7) Improper configuration of JCE
 and even more.

Its very difficult to debug these in ZAP, which is why issues like: https://github.com/zaproxy/zaproxy/issues/2288 get raised, and there is even a FAQ for Java8 & JCE related issues here: https://github.com/zaproxy/zaproxy/wiki/FAQsslHandshake

Right now, ZAP simple returns an error like:

Stack Trace:
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
    bunch of at sun.security.ssl lines
    at org.parosproxy.paros.network.SSLConnector.createSocket(Unknown source)
    at bunch of org.apache.commons.httpclient lines
    at org.parosproxy.paros.network.HttpSender.executeMethod(Unknown source)
    then more parosproxy lines

Which is pretty unhelpful as the cause of the 'handshake_failure' could be one of MANY things.

I'd like to request 2 enhancements here at a minimum:

1) The URL that ZAP is trying to access be included first. (e.g., SSL failure trying to connect to: https://WHATEVER/params
2) Then the specific reason why be listed (along the lines of the different reasons I described in the above list), and then the stack trace (maybe). Not sure the stack trace is even helpful actually.

And if the reason is related to the FAQsslHandshake issue, then refer the user to that article which is helpful in how to FIX the problem.

**Comment by kingthorin** [comment]
So we don't seem to be able to check most of the things you mentioned, however, I do believe we can improve the messaging or details. I've just checked ZAP with Oracle Java 8 against most of the badssl.com sites and the only handshake failures are the RC4 suites and some of the Diffie-Hellman things.

**Comment by kingthorin** [comment]
How does this seem?
>16321 [ZAP-ProxyThread-5] WARN org.parosproxy.paros.network.SSLConnector  - An exception occurred while attempting to connect to: dh480.badssl.com/104.154.89.105
>16321 [ZAP-ProxyThread-5] WARN org.parosproxy.paros.network.SSLConnector  - The exception was: java.lang.RuntimeException: Could not generate DH keypair
>20982 [ZAP-ProxyThread-12] WARN org.parosproxy.paros.network.SSLConnector  - An exception occurred while attempting to connect to: dh512.badssl.com/104.154.89.105
>20983 [ZAP-ProxyThread-12] WARN org.parosproxy.paros.network.SSLConnector  - The exception was: DHPublicKey does not comply to algorithm constraints
>28103 [ZAP-ProxyThread-17] WARN org.parosproxy.paros.network.SSLConnector  - An exception occurred while attempting to connect to: rc4-md5.badssl.com/104.154.89.105
>28103 [ZAP-ProxyThread-17] WARN org.parosproxy.paros.network.SSLConnector  - The exception was: Received fatal alert: handshake_failure
>32328 [ZAP-ProxyThread-22] WARN org.parosproxy.paros.network.SSLConnector  - An exception occurred while attempting to connect to: rc4.badssl.com/104.154.89.105
>32329 [ZAP-ProxyThread-22] WARN org.parosproxy.paros.network.SSLConnector  - The exception was: Received fatal alert: handshake_failure

If debug is enabled then a full stack trace will be logged.

I also looked at logging the cipher that was attempted, that worked in the DH cases however in the RC4 cases it threw an NPE. We could try to account for that, however, I'm not sure it gets the user something more useful. Thoughts?

**Comment by kingthorin** [comment]
Per @thc202 another please this should be handled more gracefully:

> 50185 [Thread-10] WARN org.parosproxy.paros.extension.manualrequest.ManualRequestEditorDialog  - IO error in sending request: class javax.net.ssl.SSLException: java.lang.RuntimeException: Could not generate DH keypair
> java.io.IOException: IO error in sending request: class javax.net.ssl.SSLException: java.lang.RuntimeException: Could not generate DH keypair
> 	at org.parosproxy.paros.extension.manualrequest.http.impl.HttpPanelSender.handleSendMessage(HttpPanelSender.java:134)
> 	at org.parosproxy.paros.extension.manualrequest.ManualRequestEditorDialog$3.run(ManualRequestEditorDialog.java:207)
> 	at java.lang.Thread.run(Unknown Source)
> Caused by: javax.net.ssl.SSLException: java.lang.RuntimeException: Could not generate DH keypair
> 	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
> 	at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)
> 	at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)
> 	at sun.security.ssl.SSLSocketImpl.handleException(Unknown Source)
> 	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
> 	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
> 	at org.parosproxy.paros.network.SSLConnector.createSocket(SSLConnector.java:378)
> 	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:727)
> 	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)
> 	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:447)
> 	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:199)
> 	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
> 	at org.parosproxy.paros.network.HttpSender.executeMethod(HttpSender.java:317)
> 	at org.parosproxy.paros.network.HttpSender.runMethod(HttpSender.java:544)
> 	at org.parosproxy.paros.network.HttpSender.send(HttpSender.java:503)
> 	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(HttpSender.java:481)
> 	at org.parosproxy.paros.network.HttpSender.sendAndReceive(HttpSender.java:389)
> 	at org.parosproxy.paros.network.HttpSender.sendAndReceive(HttpSender.java:853)
> 	at org.parosproxy.paros.extension.manualrequest.http.impl.HttpPanelSender.handleSendMessage(HttpPanelSender.java:90)
> 	... 2 more
> Caused by: java.lang.RuntimeException: Could not generate DH keypair
> 	at sun.security.ssl.DHCrypt.<init>(Unknown Source)
> 	at sun.security.ssl.DHCrypt.<init>(Unknown Source)
> 	at sun.security.ssl.ClientHandshaker.serverKeyExchange(Unknown Source)
> 	at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)
> 	at sun.security.ssl.Handshaker.processLoop(Unknown Source)
> 	at sun.security.ssl.Handshaker.process_record(Unknown Source)
> 	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
> 	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
> 	... 17 more
> Caused by: java.security.InvalidAlgorithmParameterException: Prime size must be multiple of 64, and can only range from 512 to 2048 (inclusive)
> 	at com.sun.crypto.provider.DHKeyPairGenerator.initialize(DHKeyPairGenerator.java:120)
> 	at java.security.KeyPairGenerator$Delegate.initialize(Unknown Source)
> 	... 25 more
>

**Comment by davewichers** [comment]
This seems better, but I still don't necessarily understand these errors,
particularly the very vague handshake_failure. For the algorithm constrains
is there a way to interrogate the server to find out what algorithm's it
supports and what we support and list them, so the tester can see the two
sets are incompatible? And what they'd have to change to make them
compatible?

I'm really more interested in the certificate failures rather than
algorithm/key negotiation failures. Like when the cert is not
trusted/expired/revoked/wrong domain. This includes when the CLIENT cert is
the problem, not the server cert. Don't know if you have a framework for
testing client certs or not.

-Dave

**Comment by kingthorin** [comment]
There aren't any server cert issues that cause a failure. At least not that I could find using badssl.com (which includes expired, wrong host, self signed, untrusted root, revoked, incomplete chain, etc). There shouldn't be any Java 8 refusal to use weak ciphers we already dealt with that in Nov 2015 (https://github.com/zaproxy/zaproxy/pull/1977), if the JRE supports a cipher suite ZAP should attempt to use it.

If you've got live (or reproducible) test cases please let us know.

We do not have any framework for testing client certs, though that's not what the original issue was about.

**Comment by davewichers** [comment]
If you go to: https://badssl.com/, there are a bunch of links to other URLs on that site that have all the cert problems I mentioned. For example, if you click on 'expired' it takes you to: https://expired.badssl.com/. You should be able to individually test for issues 1-4 in my original list (and probably 2 more), by going to each of the 6 different bad conditions under the Certificate block.

**Comment by kingthorin** [comment]
I have, while proxying through ZAP and they all work fine, that's my point.

**Comment by davewichers** [comment]
Meaning that ZAP ignores these errors and negotiates the SSL connection anyway? Just like browsers do, which is fine.

However, if the client cert is invalid in any of these ways, the server will likely refuse the connection, and it would be great if ZAP explained the cause of such refusal. That's actually why I created this issue in the first place, even though I was obviously not clear about that in the initial writeup. Maybe we should create a separate issue for client cert SSL rejection, and when you are done with as much as you can do for this issue (algorithms, and such), close this ticket and work on the other one when we get the right test setup for client side certs.  The server might not explain why its refusing the client cert in any detail, but hopefully we'd at least know it was the cert that was the problem and indicate: invalid client cert (or something).

**Comment by kingthorin** [comment]
Ok thanks for clarifying Dave, I'll create a separate ticket for client cert issues.
