### ISSUE TITLE
Allow to manually specify application path and working directory

### ISSUE THREAD

**Issue by vdun** [zaproxy/zaproxy#2708]
In 'Tools>Options>Applications', make the field 'Full Command' a simple text field that take a full command line including the parameters, thus no need to specify the full path and the parameters in another field.

**Comment by psiinon** [comment]
That would then mean that we cant show a file selector dialog.
Wouldnt that make it harder for many people to use?

**Comment by vdun** [comment]
True. Would it be possible in the same time make it editable ?

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#477.

**Comment by thc202** [comment]
Released in version 4 of Invoke Applications add-on.
