### ISSUE TITLE
How to replay WebSocket requests through OWASP ZAP API ?

### ISSUE THREAD

**Issue by everping** [zaproxy/zaproxy#2709]
Hi,

I have read the source code of the ZAP api for dotnet but i haven't found any API which allows replay WebSocket Request (and HTTP Request), 
Does ZAP API supports this method?

Thanks.

**Comment by psiinon** [comment]
Please dont ask questions as issues - the ZAP User Group https://groups.google.com/group/zaproxy-users and Developer Group https://groups.google.com/group/zaproxy-develop are much better places for questions.

**Comment by everping** [comment]
Sorry for the inconvenience. Thanks psiinon
