### ISSUE TITLE
Implement a passive check for cookies without SameSite set

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#2716]
https://tools.ietf.org/html/draft-west-first-party-cookies-07
I'm currently planning on alerting on _all_ cookies without the SameSite directive.
Have pinged @mozmark on irc to check this is reasonable (he's one of the spec authors)

**Comment by kingthorin** [comment]
There is a sameSite passive script:
https://github.com/zaproxy/community-scripts/blob/master/passive/detect_samesite_protection.js

From:
https://github.com/zaproxy/community-scripts/pull/38

**Comment by thc202** [comment]
That's doing the opposite though, it raises an alert if the cookie being set has the attribute.

**Comment by psiinon** [comment]
And I suspect not that many of our users actually use the scripts :(

**Comment by kingthorin** [comment]
I was just pointing to it as a model, not necessarily as something that addresses the requirement.

**Comment by psiinon** [comment]
:)

**Comment by thc202** [comment]
@kingthorin ok, I should have guessed that.

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#471.
