### ISSUE TITLE
How to interpret the result of a scan done with the zap-api-python ?

### ISSUE THREAD

**Issue by ioclaudio** [zaproxy/zaproxy#2717]
Hi all,
executing a scan with the Python library I have as result a list of dictionaries with thousands of alerts.
> scanid = zap.ascan.scan(target)
> ...
> results = zap.core.alerts()

I wrote these alerts on a database and I've grouped them. This is the result:
> Attack_name 	COUNT(*) 	
> Application Error Disclosure                        --> 3
> Cross Site Scripting (Reflected) 	              -->12
> Password Autocomplete in Browser 	       -->218
> Private IP Disclosure 	                               -->327
> SQL Injection 	                                       -->15
> SQL Injection - MySQL 	                               -->1
> Web Browser XSS Protection Not Enabled     -->572
> X-Content-Type-Options Header Missing 	-->572
> X-Frame-Options Header Not Set 	                -->572

Why, for example, do I have 572 alerts called 'X-Frame-Options Header Not Set'?
They seems to be the same alert, why it is present 572 times?
The field attack_name, url, reference_url, risk_evaluation, description are the same, so I don't understand why the output is so verbose and if it is possible to have a list of essential alerts.

Thank you very much.

claudio

**Comment by psiinon** [comment]
Please dont ask questions as issues - the ZAP User Group https://groups.google.com/group/zaproxy-users and Developer Group https://groups.google.com/group/zaproxy-develop are much better places for questions.

**Comment by ioclaudio** [comment]
ok, excuse me

**Comment by psiinon** [comment]
you are excused :)
