### ISSUE TITLE
Active Scan API - scan the whole context 

### ISSUE THREAD

**Issue by Dalimil** [zaproxy/zaproxy#2722]
Currently the ascan API provides these two methods:

```
scan (url* recurse inScopeOnly scanPolicyName method postData )
scanAsUser (url* contextId* userId* recurse scanPolicyName method postData ) 
```

both of them require the URL parameter. However, I would like to run the ascan in a similar way I run the spider - using my whole context (without having to specify a url): `zap.spider.scan_as_user(ctx_id, user_id)`

**Comment by thc202** [comment]
Possibly related issue #1853.

**Comment by thc202** [comment]
Merging into #1853.
