### ISSUE TITLE
Support POST requests for API actions

### ISSUE THREAD

**Issue by Dalimil** [zaproxy/zaproxy#2723]
Using GET request everywhere (instead of POSTs for actions) makes certain API calls quite tricky to get right because one has to remember to url-encode any special characters - e.g. (python API):

```
zap.authentication.set_authentication_method(ctx_id, "formBasedAuthentication", "loginUrl=https://www.example.com/signin.html&loginRequestData=email={%25username%25}%26password={%25password%25}")
```

(Notice the required & -> %26 and % -> %25 escaping)  
`loginRequestData` is a url query parameter and therefore it's value cannot contain any special characters (like an ampersand)
Changing API GET requests to POST would most likely solve the problem, but changing the way authentication methods are set might suffice.

**Comment by psiinon** [comment]
We actually have a TODO in the code for this ;)
https://github.com/zaproxy/zaproxy/blob/develop/src/org/zaproxy/zap/extension/api/API.java#L293
Note that we will need to make this switchable for now, probably with a default of GET for backwards compatibility.
Shouldnt be too hard to implement, so if anyone fancies having a go at this then shout and we'll give any help you need.

**Comment by thc202** [comment]
Worth noting that the parameters still need to be properly encoded even when using POST method (e.g. `application/x-www-form-urlencoded`), the Content-Type would have to be changed too (which might also need some escaping/encoding and the ZAP API and clients changed to support it).

**Comment by Dalimil** [comment]
What would be the best way to implement it for the ZAP API clients? Should I create an optional parameter 'post' for each method or can I just change all actions from GET to POST directly?

**Comment by psiinon** [comment]
If you changed all actions to POST then we wouldnt be able to release the clients until a new version of ZAP was released. So I think the best approach is a non default option, or maybe implement but disable in the code?

**Comment by kingthorin** [comment]
Related thread: https://groups.google.com/forum/#!topic/zaproxy-users/uVZx3UvHG3Y
