### ISSUE TITLE
False positives for security headers missing due to redirections

### ISSUE THREAD

**Issue by nestoru** [zaproxy/zaproxy#2732]
Greetings,

I have noticed that if the server does not include certain headers when redirecting, for example X-Frame-Options, Cache-Control, X-XSS-Protection and X-Content-Type-Options, then zaproxy issues alerts that are really false positives as the final resource will not be vulnerable. I would propose to avoid checking for headers in 301/302 and possibly other 30X responses.

Best regards,
- Nestor

**Comment by psiinon** [comment]
I've already started addressing some issues like this: https://groups.google.com/d/msg/zaproxy-develop/6IAnEHANWpI/zva5350aBgAJ 
I'll review these suggestions as well and see if I can incorporate them in the same set of changes.

**Comment by psiinon** [comment]
Fixed in zaproxy/zap-extensions#473
