### ISSUE TITLE
Wiki: ModesAndScope doesn't cover ATTACK mode

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#2735]
https://github.com/zaproxy/zaproxy/wiki/ModesAndScope

Doesn't cover ATTACK mode.

**Comment by kingthorin** [comment]
Fixed in https://github.com/zaproxy/zaproxy/wiki/ModesAndScope/104541c8a5a8d0966f2c7155ceb96d1090b0a23a

**Comment by thc202** [comment]
Does it worth keeping the outdated information? It could point just to the help page (same for scope?).

**Comment by kingthorin** [comment]
On one hand it's nice to have the history, on the other hand it's kind of just clutter and something that might confuse users. Since core help does have mode and scope pages it might be OK to just drop the outdated zaproxy page.

**Comment by thc202** [comment]
The (updated) "Implementation notes" are something that we still need to keep (in that page?), the other sections can just link to the help pages.
The history it's still available (for archaeologists) in https://github.com/zaproxy/zaproxy/wiki/ModesAndScope/_history :)

**Comment by kingthorin** [comment]
Ok. I'm happy to do another edit. Here's what I suggest:

1. "Modes and Scope" section removed including lead-in text and screenshot.
2. "Modes" section leave the italic text, remove the rest.
3. "Scope" insert italic note similar to Modes, and remove the existing content.
4. "Implementation notes" section, title caps :grinning: and leave as is.

**Comment by thc202** [comment]
Sounds good to me. I can update the section "Implementation Notes" ;)
