### ISSUE TITLE
Unable to use Firefox 48+ with AJAX Spider

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#2743]
Steps to reproduce the issue:
1. Run ZAP;
2. Start the AJAX Spider using Firefox version 48.0;
3. Note that the browser opens but then nothing happens (for a while);
4. A pop up is shown saying "Failed to start 'Firefox', is the browser installed/available?";
5. In the log there's some warnings:

```
Caused by: org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(firefox) on port 7055; process output follows:
...
```

Remarks:
Newer versions of Firefox require the use of geckodriver [1] (which does not support version 47 [2]).
The geckodriver is included in version 3.0.0 of Selenium but it's still in beta and requires Java 8. [3]

ZAP:
2.5.0

Add-ons:
Selenium version 6 or 7.
Ajax Spider version 15.

[1] https://github.com/SeleniumHQ/selenium/issues/2559#issuecomment-237079591
[2] https://github.com/mozilla/geckodriver/blob/773c87baa4183865a4907824b47737b50284c25b/README.md#supported-firefoxen
[3] https://github.com/SeleniumHQ/selenium/blob/2aa21c1bca3ce863ed19791e20606a007a17dfa7/java/CHANGELOG#L14-L19

**Comment by thc202** [comment]
Selenium 3 is no longer in beta. Since the new version requires Java 8 the Selenium add-on will also be changed to depend on Java 8.

**Comment by jx6f** [comment]
I have been using crawljax(selenium 2.53.1) with [unbranded build FireFox48](https://wiki.mozilla.org/Add-ons/Extension_Signing#Unbranded_Builds).

The problem is due to the Firefox Driver Extension Signing. This discussion will be helpful.
https://groups.google.com/forum/#!topic/selenium-users/kDsWkujq0Y4

However, it might not be a good idea.

**Comment by thc202** [comment]
It's possible to use geckodriver with the version currently used by Selenium add-on, so, AJAX Spider, Selenium and Zest add-ons do not need to be changed to depend on Java 8.

**Comment by thc202** [comment]
@jx6f it's possible to use "normal" Firefox but it must be done with geckodriver/marionette.

**Comment by thc202** [comment]
Released in version 8 of Selenium add-on.
