### ISSUE TITLE
Unable to enable/disable Forced User mode without main tool bar

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#2744]
Steps to reproduce the issue:
1. Start ZAP;
2. Deselect the option "Options" > "Display" > "Show Main Toolbar" (and restart ZAP, if using older versions);
3. Note that it's no longer possible to enabled/disable Forced User mode, the option is/was only available in the main tool bar.

Remarks:
It's still possible to enable/disable it using the ZAP API.

ZAP Versions:
Versions >= 2.4.0

**Comment by thc202** [comment]
Related to #2375.

**Comment by shivanXI** [comment]
where do you want it , in **Display** section or  in **Tools** ?

**Comment by kingthorin** [comment]
Maybe also edit as suggested here? https://github.com/zaproxy/zaproxy/issues/2375
