### ISSUE TITLE
Spider Exception when sitemap.xml not found

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#2745]
I encountered the following when doing some basic functionality testing against Apache in XAMPP Portable (xampp-portable-win32-5.6.23-0-VC11).

> 47011 [Thread-10] INFO org.zaproxy.zap.extension.spider.SpiderThread  - Starting spidering scan on SpiderApi-0 at Thu Aug 04 21:05:24 EDT 2016
> 47011 [Thread-10] INFO org.zaproxy.zap.spider.Spider  - Spider initializing...
> 47026 [Thread-10] INFO org.zaproxy.zap.spider.Spider  - Starting spider...
> [Fatal Error] :2:10: DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl" set to true.
> 47074 [pool-1-thread-2] ERROR org.zaproxy.zap.spider.parser.SpiderParser  - An error occurred trying to parse sitemap.xml
> org.xml.sax.SAXParseException; lineNumber: 2; columnNumber: 10; DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl" set to true.
> 	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
> 	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:347)
> 	at org.zaproxy.zap.spider.parser.SpiderSitemapXMLParser.parseResource(SpiderSitemapXMLParser.java:105)
> 	at org.zaproxy.zap.spider.SpiderTask.processResource(SpiderTask.java:293)
> 	at org.zaproxy.zap.spider.SpiderTask.run(SpiderTask.java:240)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
> 	at java.lang.Thread.run(Thread.java:745)
> 47106 [pool-1-thread-1] ERROR org.zaproxy.zap.spider.parser.SpiderParser  - An error occurred trying to parse sitemap.xml
> org.xml.sax.SAXParseException; lineNumber: 2; columnNumber: 10; DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl" set to true.
> 	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
> 	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:347)
> 	at org.zaproxy.zap.spider.parser.SpiderSitemapXMLParser.parseResource(SpiderSitemapXMLParser.java:105)
> 	at org.zaproxy.zap.spider.SpiderTask.processResource(SpiderTask.java:293)
> 	at org.zaproxy.zap.spider.SpiderTask.run(SpiderTask.java:240)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
> 	at java.lang.Thread.run(Thread.java:745)
> [Fatal Error] :2:10: DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl" set to true.
> 47387 [pool-1-thread-2] WARN org.zaproxy.zap.spider.URLCanonicalizer  - Error while Processing URL in the spidering process (on base ): Host could not be reliably evaluated from: https://),url(https://),red
> 47387 [pool-1-thread-2] WARN org.zaproxy.zap.spider.URLCanonicalizer  - Error while Processing URL in the spidering process (on base ): Host could not be reliably evaluated from: https://)
> 47450 [pool-1-thread-2] WARN org.zaproxy.zap.spider.URLCanonicalizer  - Error while Processing URL in the spidering process (on base ): Host could not be reliably evaluated from: https://),url(https://),red
> 47450 [pool-1-thread-2] WARN org.zaproxy.zap.spider.URLCanonicalizer  - Error while Processing URL in the spidering process (on base ): Host could not be reliably evaluated from: https://)
> 50055 [pool-1-thread-1] WARN org.zaproxy.zap.spider.URLCanonicalizer  - Error while Processing URL in the spidering process (on base ): Host could not be reliably evaluated from: http://codemirror.net),
> 56374 [pool-1-thread-2] INFO org.zaproxy.zap.spider.Spider  - Spidering process is complete. Shutting down...
> 56389 [Thread-11] INFO org.zaproxy.zap.extension.spider.SpiderThread  - Spider scanning complete: true

Attempting to access sitemap.xml actually returned a 404, based on the following response (header & body):

```
HTTP/1.1 404 Not Found
Date: Fri, 05 Aug 2016 01:05:24 GMT
Server: Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.6.23
Vary: accept-language,accept-charset
Accept-Ranges: bytes
Content-Type: text/html; charset=utf-8
Content-Language: en

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<title>Object not found!</title>
<link rev="made" href="mailto:postmaster@localhost" />
<style type="text/css"><!--/*--><![CDATA[/*><!--*/ 
    body { color: #000000; background-color: #FFFFFF; }
    a:link { color: #0000CC; }
    p, address {margin-left: 3em;}
    span {font-size: smaller;}
/*]]>*/--></style>
</head>

<body>
<h1>Object not found!</h1>
<p>


    The requested URL was not found on this server.

  

    If you entered the URL manually please check your
    spelling and try again.

  

</p>
<p>
If you think this is a server error, please contact
the <a href="mailto:postmaster@localhost">webmaster</a>.

</p>

<h2>Error 404</h2>
<address>
  <a href="/">127.0.1.2</a><br />
  <span>Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.6.23</span>
</address>
</body>
</html>
```

**Comment by psiinon** [comment]
We should probably check the response is not an error and the content is XML before trying to parse it.

**Comment by kingthorin** [comment]
Dev ref: https://github.com/zaproxy/zaproxy/blob/4ce4887e5e1c6251b7ef703594ff89d5d11f1fc6/src/org/zaproxy/zap/spider/parser/SpiderSitemapXMLParser.java#L88
