### ISSUE TITLE
ZAP Spidering HTML Forms with multiple submit buttons

### ISSUE THREAD

**Issue by sdosis** [zaproxy/zaproxy#2748]
ZAP when encountering an HTML Form with multiple submit buttons defined

e.g.

```
<form action="test.jsp">
<input type="text" value="a" size="10" maxlength="10" name="name">
<input type="submit" value="Reload" name="submit1">
<input type="submit" value="Basic" name="submit2">
```

it spiders for the following URL
/test.jsp?name=a&submit1=Reload&submit2=Basic

instead of submitting two URLs like
/test.jsp?name=a&submit1=Reload
/test.jsp?name=a&submit2=Basic

Reference: https://github.com/zaproxy/zaproxy/blob/develop/src/org/zaproxy/zap/spider/parser/SpiderHtmlFormParser.java#L109

Additionally, the "value" attribute of the input type="submit" element can be used as a differentiator in the edge case where the two submit buttons have the same ID/name

e.g.
```
<form action="test.jsp">
<input type="text" value="a" size="10" maxlength="10" name="name">
<input type="submit" value="Reload" name="submit">
<input type="submit" value="Basic" name="submit">
```

the spider can generate the following requests
/test.jsp?name=a&submit=Reload
/test.jsp?name=a&submit=Basic

**Comment by psiinon** [comment]
With this (and #2749 ) we will probably need to first read all of the action values and then submit the form for each value without duplicating the other actions. Sound like a plan @thc202 @kingthorin ?

**Comment by kingthorin** [comment]
So you've got a form with two action attributes? I don't think the RFCs support that, do they?

**Comment by thc202** [comment]
Yes, that's how it should be (e.g. https://www.w3.org/TR/REC-html40/interact/forms.html#h-17.13.2 )

Both issues could be merged? (It doesn't really matter if they have the same name or not, only one submit button is included.)

**Comment by thc202** [comment]
The reference points to the form action but it should really be to "prepareFormDataSet" (which needs to be changed to properly handle the multiple submit fields).

**Comment by sdosis** [comment]
Merged the two issues as when the two submit buttons have the same ID/name can be considered an edge case of the general handling of multiple submit buttons
