### ISSUE TITLE
ZAP Spidering HTML Forms with multiple submit buttons (with same IDs/name attribute values)

### ISSUE THREAD

**Issue by sdosis** [zaproxy/zaproxy#2749]
ZAP when encountering an HTML Form with multiple submit buttons which have the same ID and name (a bad practice from the developer's side)

e.g.

```
<form action="test.jsp">
<input type="text" value="a" size="10" maxlength="10" name="name">
<input type="submit" value="Reload" name="submit">
<input type="submit" value="Basic" name="submit">
```
it spiders for the following URL
/test.jsp?name=a&submit=Basic

so it uses only the last element

Can it also use the 'value' attribute as a differentiator to spider for both URLs

/test.jsp?name=a&submit=Basic
/test.jsp?name=a&submit=Reload

**Comment by sdosis** [comment]
Merged into issue-2748

**Comment by thc202** [comment]
Thanks!
