### ISSUE TITLE
Implement unit tests for pscan rules (release)

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#2755]
- [x] ApplicationErrorScanner
- [x] CacheControlScanner
- [x] ContentTypeMissingScanner
- [x] CookieHttpOnlyScanner
- [x] CookieSecureFlagScanner
- [x] CrossDomainScriptInclusionScanner
- [x] HeaderXssProtectionScanner
- [x] MixedContentScanner
- [x] PasswordAutocompleteScanner
- [x] TestInfoPrivateAddressDisclosure
- [ ] TestInfoSessionIdURL
- [x] XContentTypeOptionsScanner
- [x] XFrameOptionScanner

https://github.com/zaproxy/zap-extensions/tree/master/addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules

<sub>Edit: 20190615 by @kingthorin updated source location link.</sub>

**Comment by kingthorin** [comment]
https://github.com/zaproxy/zap-extensions/blob/master/addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/InfoSessionIdUrlScanRuleUnitTest.java now exists, this checklist seems complete.
