### ISSUE TITLE
Class loading deadlock when loading httpsender script from API call and spidering

### ISSUE THREAD

**Issue by sdosis** [zaproxy/zaproxy#2756]
[zapdump.txt](https://github.com/zaproxy/zaproxy/files/409166/zapdump.txt)

Run into the following issue when loading an httpsender script via API call (api.script.load) and then running the spider (api.spider.scanAsUser)
# Found one Java-level deadlock:

"pool-1-thread-2":
  waiting to lock monitor 0x0000000017245658 (object 0x00000000da773ef8, a org.zaproxy.zap.control.AddOnClassLoader),
  which is held by "ZAP-PassiveScanner"
"ZAP-PassiveScanner":
  waiting to lock monitor 0x0000000017246208 (object 0x00000000da77c598, a org.zaproxy.zap.control.AddOnLoader),
  which is held by "pool-1-thread-2"

Full Thread dump at https://pastebin.mozilla.org/8890807 and attached

**Comment by waeller** [comment]
I had the same problem. It helped to define variables at the beginning of the script for all Java classes used by the script  instead of using them "inline". E.g.:

    var ScriptVars = Java.type('org.zaproxy.zap.extension.script.ScriptVars');
    function sendingRequest(...) {
      ScriptVars.setGlobalVar(...)
    }

instead of 

    function sendingRequest(...) {
        org.zaproxy.zap.extension.script.ScriptVars.setGlobalVar(...)
    }

**Comment by thc202** [comment]
Reopening, there's still one case that can lead to locks.
