### ISSUE TITLE
OWASP ZAP on Mac and iPhone, Apps don't work

### ISSUE THREAD

**Issue by Dadumm** [zaproxy/zaproxy#2764]
I have installed OWASP ZAP on my mac. Set my local Proxy and create a certificate profile for my iPhone. It works well if i use Safari. But some apps dont work, like Facebook or the AppStore.
Im not interested in traffic from Facebook or the AppStore.

How can i run Facebook and other apps on my iPhone if i had a ZAP proxy on my iPhone? I want only the traffic of Safari, Chrome or something.

**Comment by psiinon** [comment]
It sounds like ZAP is working correctly - you have configured your iPhone to use ZAP as a proxy and its using it.
Facebook and the AppStore probably use certificate pinning which is a known problem: https://github.com/zaproxy/zaproxy/wiki/FAQcertpinning
Issues are really for reporting problems or requesting enhancements.
If you're looking for a way around this then the ZAP User Group is a better forum for asking such questions: https://groups.google.com/group/zaproxy-users

**Comment by Dadumm** [comment]
Thanks for this link. I will search on this page too.

Isnt it possible to disable the proxy for Facebook or the AppStore app? Or only watch things like http on ZAP? Because i don't need to monitor this apps. I can disable some URLs in the ZAP options, but don't know if this work with apps too?

**Comment by psiinon** [comment]
I've no idea to be honest - that would be an iPhone option wouldnt it?
We dont support transparent proxying (that would be a feature request;).
In Firefox I use FoxyProxy which allows you to configure proxying based on regexes, but I dont know if there are equivalents for the iPhone. Someone on the User Group might know?
