### ISSUE TITLE
fuzz module request alignment

### ISSUE THREAD

**Issue by tbearden** [zaproxy/zaproxy#2766]
While doing fuzzing against a request, it looks like the fuzz data is becoming misaligned with the request.  Essentially, the end of one fuzz string bleeds into the next request.You can see in the screenshot that the end of the previous fuzz string got added to the start of the next request, resulting in a bad request.  The request looks correct in the gui, but based on the error, it is corrupted.

![zap-fuzz-bug2](https://cloud.githubusercontent.com/assets/2632991/17628303/6aeb3a84-607a-11e6-8033-bed1d3109770.jpg)
 
![zap-fuzz-bug](https://cloud.githubusercontent.com/assets/2632991/17628225/05b45e2a-607a-11e6-99e1-df825337d89a.jpg)

**Comment by thc202** [comment]
That seems to be caused by incorrect `Content-Length`, in the first image it has 11 but the payload has a lot more. That also explains why the other chars are then considered as part of the following request (the difference between 11 and the length of previous payload leads to `2]}`).
Was the fuzzer set up to automatically update the `Content-Length`?

**Comment by tbearden** [comment]
Yes, default fuzzer setup with 'request content-length updater' message processor.

Not sure if it's related, but I noticed that the payload dialog is showing incorrect data also, see attached. Value field is wrong.
![zap-fuzz-bug3](https://cloud.githubusercontent.com/assets/2632991/17629058/14dd801c-607e-11e6-91df-33d47d460b92.jpg)

**Comment by thc202** [comment]
OK, that's interesting, was the `Content-Length` changed in any of the requests?

That might be related, it's odd that the position/location is correctly identified as body.

**Comment by tbearden** [comment]
In that fuzzing session, no the content-length never changed.  In a different fuzz session for a POST request, the content-length updated correctly.

**Comment by thc202** [comment]
The `Content-Length` was only being updated for POST requests, it will be changed for all that have a body.

Regarding the incorrect value, another issue was raised to address that (it was unrelated). [1]

[1] https://github.com/zaproxy/zaproxy/issues/2774

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#499.

**Comment by thc202** [comment]
Released in version 7 of Fuzzer add-on.
