### ISSUE TITLE
ZAP forcing headers

### ISSUE THREAD

**Issue by acaetano** [zaproxy/zaproxy#2778]
I was checking some results after a tool scan and one of the issues that came up was a host header injection. After a few minutes trying to validate the issue, it came to me that ZAP could be resetting the header value.

Testing with ncat, i finally verified that the flaw was real indeed, confirming that ZAP was forcing a new value to the Host header, even when a changed it via a breakpoint.

Do we have a way to disable that? Can you change that behavior?

**Comment by kingthorin** [comment]
Sadly in the current version this is out of our control due to the client library in use. 

See https://github.com/zaproxy/zaproxy/issues/1318 for references to other similar reports.

**Comment by thc202** [comment]
Closing per previous comment.

Note that it's not a problem with the library (it can be changed but it's not a quick/easy change, mostly in ZAP side).
