### ISSUE TITLE
Document which character encoding is expected for ZAP scripts

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#2781]
Per #2773, we should document (in help pages?) what is the expected character encoding when reading/writing the scripts. At the moment ZAP (version 2.5.0 and earlier) uses the default character encoding (which varies between OS, can be override by the user...).

**Comment by psiinon** [comment]
+1 for documenting in the help pages.
Can we restrict the scripts to UTF-8? Do all of the scripting languages we use support specifying binary characters for when non UTF-8 characters are required?

**Comment by thc202** [comment]
Kinda, the changes proposed in #2773 prevent the loading of the scripts if they contain wrong byte sequences.
Not sure about that, but that would be problem with other character encodings as well.
