### ISSUE TITLE
Unit tests for ApplicationErrorScanner

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#2786]
Create unit tests for the class: https://github.com/zaproxy/zap-extensions/blob/master/src/org/zaproxy/zap/extension/pscanrules/ApplicationErrorScanner.java
In the package: https://github.com/zaproxy/zap-extensions/tree/master/test/org/zaproxy/zap/extension/pscanrules

Unit tests should test all of the associated functionality and include tests for false positives.
The tests should at least check the number of alerts and the parameters and evidence (as appropriate). Additional checks can be made if thought useful.
Tests for other rules can be found in https://github.com/zaproxy/zap-extensions/tree/master/test/org/zaproxy/zap/extension/pscanrules

**Comment by psiinon** [comment]
This issue is part of the ZAP Unit Test Bounty: http://zaproxy.blogspot.com/2016/08/announcing-zap-unit-test-bounties.html
Bounties will be paid only when the PR has been merged. The PRs must test all of the associated rule functionality and must conform to our Development Rules and Guidelines.

**Comment by kingthorin** [comment]
https://github.com/zaproxy/zaproxy/wiki/DevGuidelines#unit-test-specific-guidelines

**Comment by thc202** [comment]
@adioss please let us know your Bountysource username. You should be able to claim the bounty in:
https://www.bountysource.com/issues/37099825-unit-tests-for-applicationerrorscanner

**Comment by thc202** [comment]
(Linking to the pull request zaproxy/zap-extensions#527.)

**Comment by adioss** [comment]
bountysource username is "adioss" (https://www.bountysource.com/people/44718-adioss)

**Comment by thc202** [comment]
Thanks, the claim will be handled soon.

**Comment by psiinon** [comment]
The claim has been approved - thank you for this unit test:)

**Comment by kingthorin** [comment]
@adioss could you let us know how you'd like to be added to the credits?
https://github.com/zaproxy/zap-core-help/wiki/HelpCredits#zap-extended-team

**Comment by adioss** [comment]
@kingthorin you can put Adrien PAILHES

**Comment by thc202** [comment]
@adioss done in zaproxy/zap-core-help#98. Thanks!
