### ISSUE TITLE
Unit tests for PasswordAutocompleteScanner

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#2789]
Create unit tests for the class: https://github.com/zaproxy/zap-extensions/blob/master/src/org/zaproxy/zap/extension/pscanrules/PasswordAutocompleteScanner.java
In the package: https://github.com/zaproxy/zap-extensions/tree/master/test/org/zaproxy/zap/extension/pscanrules

Unit tests should test all of the associated functionality and include tests for false positives.
The tests should at least check the number of alerts and the parameters and evidence (as appropriate). Additional checks can be made if thought useful.
Tests for other rules can be found in https://github.com/zaproxy/zap-extensions/tree/master/test/org/zaproxy/zap/extension/pscanrules

**Comment by psiinon** [comment]
This issue is part of the ZAP Unit Test Bounty: http://zaproxy.blogspot.com/2016/08/announcing-zap-unit-test-bounties.html
Bounties will be paid only when the PR has been merged. The PRs must test all of the associated rule functionality and must conform to our Development Rules and Guidelines.

**Comment by kingthorin** [comment]
https://github.com/zaproxy/zaproxy/wiki/DevGuidelines#unit-test-specific-guidelines

**Comment by kingthorin** [comment]
Please let us know your username on bounty source so that we can award the bounty.

**Comment by thc202** [comment]
@schoeth you should be able to claim the bounty in:
https://www.bountysource.com/issues/37099906-unit-tests-for-passwordautocompletescanner

See also previous comment.

**Comment by thc202** [comment]
@schoeth could you confirm that your your Bountysource username is "schoeth"? Just want to make sure that it was really you that claimed the bounty ;)

**Comment by schoeth** [comment]
@thc202 yes, my Bountysource username is "schoeth".

**Comment by thc202** [comment]
Thanks, the claim will be handled soon.

**Comment by psiinon** [comment]
The claim has been approved - thank you for this unit test:)
