### ISSUE TITLE
Unit tests for TestInfoSessionIdURL

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#2791]
Create unit tests for the class: https://github.com/zaproxy/zap-extensions/blob/master/src/org/zaproxy/zap/extension/pscanrules/TestInfoSessionIdURL.java
In the package: https://github.com/zaproxy/zap-extensions/tree/master/test/org/zaproxy/zap/extension/pscanrules

Unit tests should test all of the associated functionality and include tests for false positives.
The tests should at least check the number of alerts and the parameters and evidence (as appropriate). Additional checks can be made if thought useful.
Tests for other rules can be found in https://github.com/zaproxy/zap-extensions/tree/master/test/org/zaproxy/zap/extension/pscanrules

**Comment by psiinon** [comment]
This issue is part of the ZAP Unit Test Bounty: http://zaproxy.blogspot.com/2016/08/announcing-zap-unit-test-bounties.html
Bounties will be paid only when the PR has been merged. The PRs must test all of the associated rule functionality and must conform to our Development Rules and Guidelines.

**Comment by kingthorin** [comment]
https://github.com/zaproxy/zaproxy/wiki/DevGuidelines#unit-test-specific-guidelines

**Comment by kingthorin** [comment]
Closed in https://github.com/zaproxy/zap-extensions/pull/2095
