### ISSUE TITLE
chinese disorder in HTTP response

### ISSUE THREAD

**Issue by yangyangwithgnu** [zaproxy/zaproxy#2794]
I am viewing the http://www.ip38.com/ by ZAP (v2.5.0, win7). there are lots of chinese hanzi in html, all hanzi display disorder in ZAP, BUT, if I copy the disorder string to notepad, everything is fine. as follow:
![chinese disorder in http response](https://cloud.githubusercontent.com/assets/3734415/17829226/e4781e9c-66da-11e6-80e0-5faf2bbb59c3.gif)

could U fix it, thx.

**Comment by kingthorin** [comment]
Is ZAP using the same font as notepad?

**Comment by yangyangwithgnu** [comment]
@kingthorin 

of course, ZAP using the same font as notepad, and the font supports well chinese. indeed, on ZAP main UI display disorder, but on encode/decode/hash... UI is all right (P.S., i'm not decode the string):

![record_screen ceyp](https://cloud.githubusercontent.com/assets/3734415/17831555/a7494e30-671e-11e6-86df-95ce2407ba8a.gif)

**Comment by kingthorin** [comment]
Thanks for the info. Had to ask as it is possible to customize.

**Comment by kingthorin** [comment]
Is this still an issue?

**Comment by yangyangwithgnu** [comment]
yes, the problem still there.

**Comment by markensisoul** [comment]
Hi everyone, i encounter the same issue in using ZAP 2.5 on Win7, and there are the same situation as @yangyangwithgnu show, hope can fix it as possible.
I just try to use "java -jar -Dfile.encoding=UTF-8 zap-2.5.jar", but useless....
![image](https://cloud.githubusercontent.com/assets/10271967/20738958/ed5b9144-b6f1-11e6-97b9-c7352f78cd65.png)

thanks.

**Comment by thc202** [comment]
@yangyangwithgnu, @markensisoul which JRE version are you using?

**Comment by markensisoul** [comment]
@thc202 I use jre1.8.0_111

**Comment by CinaStan** [comment]
ZAP 2.10 also encountered the same problem, the same as @yangyangwithgnu show, I hope it can be resolved as soon as possible

**Comment by thc202** [comment]
I don't think this is a ZAP problem but what fonts are used/provided by the system.

**Comment by ricekot** [comment]
This should have been fixed by https://github.com/zaproxy/zaproxy/pull/8171. Please try the latest weekly and let us know if you still run into this issue.

**Comment by thc202** [comment]
Closing, as possible fixed, feel free to leave a comment or raise a new issue if you still see this issue (note that you should use a weekly release as the fix was not yet included in the main release.)
