### ISSUE TITLE
SSL post request gives always gives timeout

### ISSUE THREAD

**Issue by AspireInfotech** [zaproxy/zaproxy#2795]
Hi,

I am trying to get some calls using zaproxy, but we had an issue were we could not get information for a specific ssl post request, other ssl request works fine, we had this issue with a specific host only.

Mean while when i use fiddler that call appears normally without any errors, the domain we face ssl errors with it is "https://api.segment.io", and the full call is a post http request on this url "https://api.segment.io/v1/import"

attached are some screen shots that defines the issue i am talking about:
<img width="1439" alt="fiddlerpassedrequestwithbody" src="https://cloud.githubusercontent.com/assets/8426927/17840090/42e0d624-6805-11e6-9650-cce36f429fce.png">
<img width="1435" alt="fiddlerrequestinfo" src="https://cloud.githubusercontent.com/assets/8426927/17840091/42e32d3e-6805-11e6-936d-0e5da5f7a55d.png">
<img width="1177" alt="owsapmainrequestinfo" src="https://cloud.githubusercontent.com/assets/8426927/17840092/42e81542-6805-11e6-95c8-90bff2f44bb6.png">
<img width="1142" alt="owsapresponse" src="https://cloud.githubusercontent.com/assets/8426927/17840093/42eb35e2-6805-11e6-85b3-fc137b245370.png">

**Comment by kingthorin** [comment]
What version of java?
Did you increase the timeout as ZAP suggested? (As seen in your screenshot.) What values did you try? 

In the fiddler screenshot you seem to have posted a bunch of JSON while the ZAP post seems empty.

**Comment by thc202** [comment]
Might have to do with the transfer coding.

**Comment by AspireInfotech** [comment]
I have JDK 1.8.0_60.
Default timeout of zap is 20 seconds, i changed it to 60 seconds and still have the gateway timeout issue, meanwhile the request does not take more than 2 seconds in real life it should not never give gateway timeout.

Also i have tried to change the user agent, chrome/firefox and android agent, but still have the same issue.

Request should have a request body on it which is a json text, this request body appears on both fiddler and charles, but it does not appear at all on ZAProxy

**Comment by kingthorin** [comment]
@aspireinfotech do you still have an issue ?

**Comment by AspireInfotech** [comment]
@kingthorin yes we couldn't have any workaround on this

**Comment by thc202** [comment]
ZAP's proxy does not support chunked transfer encoding (it should though), are you able to change the client to not use it? (to confirm that's the problem)

**Comment by kingthorin** [comment]
@aspireinfotech any update?
