### ISSUE TITLE
Unit tests for CharsetMismatchScanner

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#2799]
Create unit tests for the class: https://github.com/zaproxy/zap-extensions/tree/beta/src/org/zaproxy/zap/extension/pscanrulesBeta/CharsetMismatchScanner.java
In the package: https://github.com/zaproxy/zap-extensions/tree/beta/test/org/zaproxy/zap/extension/pscanrulesBeta

Unit tests should test all of the associated functionality and include tests for false positives.
The tests should at least check the number of alerts and the parameters and evidence (as appropriate). Additional checks can be made if thought useful.
Tests for other rules can be found in https://github.com/zaproxy/zap-extensions/tree/master/test/org/zaproxy/zap/extension/pscanrules

**Comment by psiinon** [comment]
This issue is part of the ZAP Unit Test Bounty: http://zaproxy.blogspot.com/2016/08/announcing-zap-unit-test-bounties.html
Bounties will be paid only when the PR has been merged. The PRs must test all of the associated rule functionality and must conform to our Development Rules and Guidelines.

**Comment by kingthorin** [comment]
https://github.com/zaproxy/zaproxy/wiki/DevGuidelines#unit-test-specific-guidelines

**Comment by stuartgunter** [comment]
I was planning on picking this up tonight, but it seems work has already started. Should I look at something else instead?

**Comment by psiinon** [comment]
Yeah, we try to give anyone who submits a PR for a unit test a decent amount of time to get it in a fit state to merge so its probably best to pick another one. If you run out of ones to look at then just let us know - we're planning of extending to bounty to cover active scan tests once most of the passive scan ones are implemented :)

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#543.

**Comment by thc202** [comment]
@rscipien please let us know your Bountysource username. You should be able to claim the bounty in:
https://www.bountysource.com/issues/37164894-unit-tests-for-charsetmismatchscanner

**Comment by kingthorin** [comment]
@rscipien could you let us know how you'd like to be added to the credits?
https://github.com/zaproxy/zap-core-help/wiki/HelpCredits#zap-extended-team

**Comment by rscipien** [comment]
Hi

I have just claim bounty.

**Comment by thc202** [comment]
@rscipien thanks, it will be accepted soon.

**Comment by rscipien** [comment]
Hi

By my full name Rafał Ścipień

I have just added unit test

**Comment by thc202** [comment]
@rscipien great, the remaining claim will be accepted soon.
