### ISSUE TITLE
Unit tests for InformationDisclosureDebugErrors

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#2802]
Create unit tests for the class: https://github.com/zaproxy/zap-extensions/tree/beta/src/org/zaproxy/zap/extension/pscanrulesBeta/InformationDisclosureDebugErrors.java
In the package: https://github.com/zaproxy/zap-extensions/tree/beta/test/org/zaproxy/zap/extension/pscanrulesBeta

Unit tests should test all of the associated functionality and include tests for false positives.
The tests should at least check the number of alerts and the parameters and evidence (as appropriate). Additional checks can be made if thought useful.
Tests for other rules can be found in https://github.com/zaproxy/zap-extensions/tree/master/test/org/zaproxy/zap/extension/pscanrules

**Comment by psiinon** [comment]
This issue is part of the ZAP Unit Test Bounty: http://zaproxy.blogspot.com/2016/08/announcing-zap-unit-test-bounties.html
Bounties will be paid only when the PR has been merged. The PRs must test all of the associated rule functionality and must conform to our Development Rules and Guidelines.

**Comment by kingthorin** [comment]
https://github.com/zaproxy/zaproxy/wiki/DevGuidelines#unit-test-specific-guidelines

**Comment by thc202** [comment]
Fixed zaproxy/zap-extensions#536.

**Comment by thc202** [comment]
@yetmorecode please let us know your Bountysource username. You should be able to claim the bounty in:
https://www.bountysource.com/issues/37164952-unit-tests-for-informationdisclosuredebugerrors

**Comment by yetmorecode** [comment]
Can you just add it to some other open bounty on my behalf? I don't think I need it anymore.

**Comment by thc202** [comment]
I'd suggest claiming the bounty (so that it's properly closed) and then just donate back to ZAP? If not, I'll see if we can move the bounty to other issue.

**Comment by yetmorecode** [comment]
Ok, I think I claimed it? Please let me know if there is more for me to do.

**Comment by thc202** [comment]
No, that's all, thank you! The claim will be accepted soon.

**Comment by psiinon** [comment]
@yetmorecode Many thanks!

**Comment by kingthorin** [comment]
@yetmorecode could you let us know how you'd like to be added to the credits?
https://github.com/zaproxy/zap-core-help/wiki/HelpCredits#zap-extended-team

**Comment by kingthorin** [comment]
@yetmorecode could you let us know how you'd like to be added to the credits?
https://github.com/zaproxy/zap-core-help/wiki/HelpCredits#zap-extended-team
