### ISSUE TITLE
Unit tests for ServletParameterPollutionScanner

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#2808]
Create unit tests for the class: https://github.com/zaproxy/zap-extensions/tree/beta/src/org/zaproxy/zap/extension/pscanrulesBeta/ServletParameterPollutionScanner.java
In the package: https://github.com/zaproxy/zap-extensions/tree/beta/test/org/zaproxy/zap/extension/pscanrulesBeta

Unit tests should test all of the associated functionality and include tests for false positives.
The tests should at least check the number of alerts and the parameters and evidence (as appropriate). Additional checks can be made if thought useful.
Tests for other rules can be found in https://github.com/zaproxy/zap-extensions/tree/master/test/org/zaproxy/zap/extension/pscanrules

**Comment by psiinon** [comment]
This issue is part of the ZAP Unit Test Bounty: http://zaproxy.blogspot.com/2016/08/announcing-zap-unit-test-bounties.html
Bounties will be paid only when the PR has been merged. The PRs must test all of the associated rule functionality and must conform to our Development Rules and Guidelines.

**Comment by kingthorin** [comment]
https://github.com/zaproxy/zaproxy/wiki/DevGuidelines#unit-test-specific-guidelines

**Comment by kingthorin** [comment]
https://github.com/zaproxy/zaproxy/wiki/DevGuidelines#unit-test-specific-guidelines

**Comment by kingthorin** [comment]
@Adrian clay please let us know your bug bounty username so we can award the bounty.

https://github.com/zaproxy/zap-extensions/pull/531

**Comment by adrianclay** [comment]
Hey, I'm not sure what my username is but my profile is here www.bountysource.com/people/44776-adrianclay does that help?

**Comment by thc202** [comment]
@adrianclay you should be able to claim the bounty in:
https://www.bountysource.com/issues/37165036-unit-tests-for-servletparameterpollutionscanner

**Comment by thc202** [comment]
@adrianclay thanks, the claim will be handled soon.

**Comment by psiinon** [comment]
The claim has been approved - thank you for this unit test:)

**Comment by kingthorin** [comment]
@adrianclay could you let us know how you'd like to be added to the credits?
https://github.com/zaproxy/zap-core-help/wiki/HelpCredits#zap-extended-team

**Comment by adrianclay** [comment]
Hi @kingthorin "Adrian Clay" works for me :+1:
