### ISSUE TITLE
more granular filtering on web sockets

### ISSUE THREAD

**Issue by digininja** [zaproxy/zaproxy#2812]
At the moment the web socket filter just allows the choice of opcodes, I'd like to also filter based on the content of messages. This client does custom heartbeats and so the table is flooded with two of these messages every second.

If it helps to understand what I mean, this is how Burp does its filtering.

![zap_ws_filter_request](https://cloud.githubusercontent.com/assets/117081/17886625/945b3376-691a-11e6-8cfb-c7f3722942c6.png)

**Comment by thc202** [comment]
Merging into #1382.
