### ISSUE TITLE
ZAP Lockup when HSQLDB gets too big

### ISSUE THREAD

**Issue by davewichers** [zaproxy/zaproxy#2827]
I'm seeing ZAP lock up after what appears to be the HSQL database getting too big (or something). I'm giving ZAP itself 2GIG of memory via the JVM options when I start it up.

This is occurring when I'm simply spidering a large set of interrelated sites. At some point I get a message in the terminal window like:
###### # [HSQLDB timer @65c3f252] INFO hsqldb.db..ENGINE  - Checkpoint start

more HSQLDB messages
###### # [HSQLDB timer @65c3f252] INFO hsqldb.db..ENGINE  - Checkpoint end - txts: ### (where ### is close to but less than 5,000,000)

and then everything just locks up. The UI is unresponsive and I have to kill ZAP at this point.

2 questions:

1) Can I make the max size of this HSQL DB bigger to make this issue less likely to occur? (If that's even the problem).
2) Is there any way to get ZAP to detect this condition itself and pause/warn gracefully rather than simply locking up like this?

**Comment by JordanGS** [comment]
I can't answer 1 or 2 but i would suggest allocating more ram to ZAP or keep your sessions smaller. I allocate 15GB out of my systems 16GB to it.

**Comment by davewichers** [comment]
I would be happy to give it more RAM if that would help. But I'm not sure
if this is a RAM issue, or a default size on disk for this database issue.
If someone can answer that question, that would help.

**Comment by kingthorin** [comment]
@davewichers have you done further testing allocating more memory?

**Comment by davewichers** [comment]
This is 2 years old. I haven't done anything with this in ages, so can't really comment on your question. I can say that I've been able to run ZAP against the full OWASP Benchmark now so I believe something in ZAP has improved to enable it to handily really large sites like Benchmark. I have no idea if this database sizing issue was something that was improved and helped.

**Comment by kingthorin** [comment]
@thc202 @psiinon good with closing this one?

**Comment by psiinon** [comment]
yeah
