### ISSUE TITLE
Private IP Disclosure: false positives

### ISSUE THREAD

**Issue by pierredittgen** [zaproxy/zaproxy#2834]
Hi,

I use ZAP application to test a local website and I get several "Private IP disclosure" warnings.
E.g. on a page containing an img URL like this : &lt;img src="/img/vignette/AILEM/AILEM-D-83/AR-10-01-07-17.jpg"/&gt;
ZAP highlights "10-01-07-17" which is not an IP address

My conf:
- OWASP ZAP : 2.5.0
- OS : Debian Linux (jessie)
- JDK : 1.8.0_65

**Comment by kingthorin** [comment]
Looks like hyphens were specifically included to 
> //find IPs from AWS hostnames such as "ip-10-2-3-200"

<sub>Code reference: https://github.com/zaproxy/zap-extensions/blob/master/src/org/zaproxy/zap/extension/pscanrules/TestInfoPrivateAddressDisclosure.java#L55-L59</sub>

Aligning with the code comment and details here:
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/set-hostname.html

I propose that this be fixed by including the `ip-` as part of the regex, which in theory could still match an image or something and lead to a False Positive (FP). But is much less likely.

**Comment by psiinon** [comment]
Sounds like a good plan

**Comment by thc202** [comment]
Sounds good to me, also it would be good to update the description of the alert and help page with an explanation of that pattern.

**Comment by kingthorin** [comment]
@pierredittgen any chance you want to take part in the unit test bounty program?
http://zaproxy.blogspot.ca/2016/08/announcing-zap-unit-test-bounties.html
https://github.com/zaproxy/zaproxy/issues/2790
https://www.bountysource.com/issues/37099938-unit-tests-for-testinfoprivateaddressdisclosure

As well as addressing this FP?

**Comment by pierredittgen** [comment]
Ok, I gave $15 for this unit test.

**Comment by psiinon** [comment]
You would get $35 for the test - thats shown in a green badge lower down on https://www.bountysource.com/issues/37099938-unit-tests-for-testinfoprivateaddressdisclosure
Note that we'll be expanding this bounty program further, so as you get more used to applying for bounties they should get easier for you to claim :)

**Comment by psiinon** [comment]
Oh wait, you gave $15 for it :) Thanks - hope someone takes us up on it soon...

**Comment by schoeth** [comment]
OK, i can take care of this (extension & unitTest), if you answer me one question to the `REGULAR_PORTS`-regex:
In fact, there will be taken any number, from :0 to :9999999999..., just cut to the first 4, 5 or 6 digits (depending on the first (two) digit(s)). But due to the style it is written: could it be, that the author has meant the ports 0-59999, 65000-65535, and 600000-649999. Would this make sense?
What to do really here?

**Comment by schoeth** [comment]
Forget the previous question, didn't see that this issue is already assigned, sorry.

**Comment by kingthorin** [comment]
No no, if you want to tackle it that's great.

**Comment by thc202** [comment]
Seems to me there's a typo in the regex `6[0-4][0-9]{4}`, the repetition should be of 3 numbers not 4 (to give the range [60000, 64999]).

**Comment by schoeth** [comment]
OK guys, then i need your help concerning the requested functionality: 
I've written a UnitTest that lets pass the current `TestInfoPrivateAddressDisclosure` just as a discussion base how this thing _should_ work. Would you be so kind and comment out the lines which aren't desired in that way (esp. below the "`desired functionality?`"-comments)? Additions are also welcome, of course ;)

Unfortunately, thc202's comment concerning the ports is not included yet, (read it just now. but to implement it afterwards shouldn't be the problem)

Many thanks in advance!
[TestInfoPrivateAddressDisclosureUnitTest.txt](https://github.com/zaproxy/zaproxy/files/446994/TestInfoPrivateAddressDisclosureUnitTest.txt)

**Comment by thc202** [comment]
Any reason to not open a pull request (or simply push to your repo) with that already? It would be easier to add the comments (and pull the changes).

**Comment by schoeth** [comment]
Didn't know how to handle the PRs in sync (test & scanner), so i putted all in one PR.

**Comment by thc202** [comment]
It's fine (and expected) having both test and scanner tweaks in the same pull request.

**Comment by Mickael-van-der-Beek** [comment]
Similar to this issue I've had false positives when ZAP finds internal IP address matches inside HTML SVG paths. e.g:

```
<path d="M50.342 44h-1.18v-2.753H46.21V44h-1.18v-6.298h1.18v2.71h2.952V37.7h1.18V44zm6.022-6.298v.932h-2.792v1.747h2.2v.902h-2.2v1.782h2.792V44h-3.972v-6.298h3.972zm2.965 5.33h2.52V44h-3.693v-6.298h1.172v5.33zm5.28 0h2.522V44h-3.694v-6.298h1.172v5.33zm9.802-2.18c0 .46-.077.888-.23 1.282-.154.393-.37.734-.65 1.02a2.924 2.924 0 0 1-1.006.674c-.392.16-.826.242-1.302.242-.476 0-.91-.08-1.304-.242a2.938 2.938 0 0 1-1.662-1.693 3.5 3.5 0 0 1-.23-1.284c0-.46.076-.888.23-1.282.154-.393.37-.734.65-1.02a2.92 2.92 0 0 1 1.012-.674 3.43 3.43 0 0 1 1.304-.242c.476 0 .91.08 1.302.244.392.163.728.387 1.007.673.278.285.495.625.65 1.018.152.394.23.82.23 1.283zm-1.202 0c0-.347-.045-.657-.137-.93a1.952 1.952 0 0 0-.394-.7 1.701 1.701 0 0 0-.626-.44 2.143 2.143 0 0 0-.83-.152c-.308 0-.585.05-.832.152s-.456.248-.63.44a1.989 1.989 0 0 0-.398.7c-.093.273-.14.583-.14.93 0 .344.047.654.14.93.093.273.226.506.4.696.172.19.38.336.628.437.247.102.524.153.832.153.308 0 .585-.05.83-.153.245-.1.454-.247.625-.437.17-.19.302-.423.393-.697.092-.274.137-.584.137-.93z" fill="#FFF" mask="url(#crb)"/>
```

where:

```
172.19.38.33
```

Is the highlighted / detected part.

One way of solving this would be to make sure that whatever RegExp is used also included that the beginning / end of the match should be either one of the spaces characters (`\s`) or a word boundary (`\b`).

**Comment by thc202** [comment]
Thanks, the new (or upcoming) regex no longer finds a private IP in that string.

**Comment by Mickael-van-der-Beek** [comment]
@thc202 Awesome! Side-node but it would be cool if when a ZAP scan is run with a local or private IP address as seed URL it filters that IP out as it is already a known address.

**Comment by thc202** [comment]
@Mickael-van-der-Beek issue #3031 has been raised to handle that case, thank you.
