### ISSUE TITLE
Feature Request: Default Eclipse Formatting Profile and Settings for Eclipse as part of DevGuide lines

### ISSUE THREAD

**Issue by JordanGS** [zaproxy/zaproxy#2843]
Standardize how we want the code formatted and what we want eclipse to do on save (remove excess white spaces for example), export this profile and make it publically available.

https://github.com/zaproxy/zaproxy/wiki/DevGuidelines

**Comment by kingthorin** [comment]
https://groups.google.com/forum/#!searchin/zaproxy-develop/format%7Csort:date/zaproxy-develop/X5i-1lvuqhc/_nSdDgvYCQAJ

**Comment by kingthorin** [comment]
Marking as duplicate of zaproxy/zaproxy#3503, and closing in favor of that other one which is currently assigned and being worked on.
