### ISSUE TITLE
Zap not ignoring https traffic

### ISSUE THREAD

**Issue by shashwat001** [zaproxy/zaproxy#2846]
I want zap to act only on http traffic and ignore https traffic. Currently my browser is giving Untrusted connection on https site as zap is hijacking the connection. I need to add zap certificate to remove the error. But I just want zap not to interfere with https network. Is there any setting to do so?

**Comment by psiinon** [comment]
Please dont ask questions as issues.
The ZAP User Group is the best place for those: https://groups.google.com/group/zaproxy-users
