### ISSUE TITLE
AJAX Spider Configuration should be more similar to standard Spider

### ISSUE THREAD

**Issue by davewichers** [zaproxy/zaproxy#2847]
Seems like the 'Spider Subtree Only' option makes sense for both types of Spiders.

I'm not sure if there are any other inconsistencies between the Scope dialogs for these two spiders but seems like this difference at least should be fixed.

**Comment by thc202** [comment]
Related issues (already closed) #1955, #1956 and #1957.

**Comment by thc202** [comment]
Released in version 16 of Ajax Spider add-on.

**Comment by thc202** [comment]
Also related zaproxy/zap-extensions#450 (allows to invoke the AJAX Spider dialogue with a keyboard shortcut, as the standard spider does).
