### ISSUE TITLE
Cannot use variable in Zest Script as part of POST URL

### ISSUE THREAD

**Issue by geredwards** [zaproxy/zaproxy#2854]
I've recorded an authentication script, and now I'm trying to get it to work repeatedly. The main issue is POSTing a form to its action url.

The login page request returns HTML along the lines of:
**&lt;header&gt;
&lt;h1&gt;Sign In To Application&lt;/h1&gt;
&lt;/header&gt;
&lt;form action="/MySecurityService/Login?key=dhsja9jAAAdsjaiidD2016-09-06T15%253a45%253a14Z" method="post" role="form"&gt;
   &lt;input id="UserName" name="UserName" type="text" value="" /&gt;
   &lt;input id="Password" name="Password" type="password" value="" /&gt;**
etc...

The key of the URL in the form action changes for every request, and is not re-usable, so I can't just replay the script I recorded.

I can extract the form's action URL into a variable using "assign variable via string delimiters", but am unable to use that variable to then POST the form to that URL.
If I try to change the URL on the request POST action, those changes get ignored, and reverts to the URL in the original recording. The variable is not used in the script source either (so it doesn't appear to be an UI issue).

So for example, I edit the POST Request, and set the URL to use the variable MyFormPostURL e.g.:
**http://10.1.1.1{{MyFormPostURL}}**
when I save it reverts to its previous value (the one originally recorded) 

The change does appear to get reflected in the script - urlToken does contain the URL as entered, including the variable name.

See also forum post: [https://groups.google.com/forum/#!topic/zaproxy-users/EZk1TzliuyM](url)

**Comment by thc202** [comment]
Which version of Zest add-on are you using? [1]

[1] https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsManageaddons

**Comment by geredwards** [comment]
I can't see a version number for the add on, but I'm using ZAP 2.5.0, and no available updates are showing on the Manage Add-Ons screen.

**Comment by kingthorin** [comment]
If you open the Marketplace (3 stacked cubes icon in the main toolbar), then hover your cursor over the addon you want to know the version of (Zest) it'll popup after 2 or 3 sec.

**Comment by geredwards** [comment]
Version 22.

**Comment by thc202** [comment]
Thanks!

**Comment by thc202** [comment]
Closed in zaproxy/zap-extensions#542.

**Comment by thc202** [comment]
Released in version 23 of Zest add-on (bundled in ZAP 2.6.0).
