### ISSUE TITLE
Outdated Reference link in Loosely Scoped Cookie - extension

### ISSUE THREAD

**Issue by schoeth** [zaproxy/zaproxy#2860]
The reference-link in the _Loosely Scoped Cookie_ - extension is outdated (https://code.google.com/archive/p/browsersec/wikis/Part2.wiki#Same-origin_policy_for_cookies)
Substitues could be e.g. 
https://tools.ietf.org/html/rfc6265#section-4.1
https://www.owasp.org/index.php/Testing_for_cookies_attributes_(OTG-SESS-002)
The only direct link to Domain restriction i've found was
http://www.maravis.com/library/protecting-web-application-cookies-by-restricting-scope/#domain-restriction

**Comment by kingthorin** [comment]
The google link still works.

I'll pre-pend the ietf and owasp links to the list.

**Comment by schoeth** [comment]
Interesting...
I just see the error-message "There was an error obtaining wiki data:" And that's on every page of this google-project... (Nat., since code.google.com shut the service down)

What do you see, if this link works for you?

**Comment by thc202** [comment]
I also see that message if some requests are blocked, when all are allowed it shows the actual wiki page content.

The Google Code projects will still be online for some time.

**Comment by schoeth** [comment]
Ah... thanks, and sorry for the inconvenience.

**Comment by kingthorin** [comment]
No inconvenience at all

**Comment by thc202** [comment]
Yeah, that link will stop working sooner or later so having more references is good.

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#545.

**Comment by thc202** [comment]
Released in version 14 of Passive scanner rules (beta) add-on.
