### ISSUE TITLE
Windows 10 display scaling

### ISSUE THREAD

**Issue by bradley-evans** [zaproxy/zaproxy#2873]
By default, the application renders text to be unreadably tiny in high resolution displays within Windows 10.

**Comment by kingthorin** [comment]
https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsOptionsView#font-size

**Comment by bradley-evans** [comment]
I had -1 in there for font size. The fix for me was running it in compatability mode for Window 7.
