### ISSUE TITLE
SQL injection 

### ISSUE THREAD

**Issue by mannemvamsi** [zaproxy/zaproxy#2875]
I have a simple app (**https://localhost:port/app/data** ) which displays datatable. Now that table is updated for a 2 minutes.. that url doesn't accept any query parameters. I mean for **/?something=something&other=nothing** .. it will result the same datatable. But zap proxy tool found some parameters in the hidden forms and attacked with **/?hidden_form_name=ZAP AND 1=1** etc..

It alerted SQL INJECTION RISK. ( with reason : page was successfully modified with the above parameters). 

when I enter the same query parameters, I do not see any changes in the UI ( my datatable is rendered with expected data). 

Now, my question is,  Does ZAP is thinking that it modified the data with its parameters ? Or am I missing something here..?

**Comment by psiinon** [comment]
Please dont ask questions as issues.
We have the ZAP User Group which is a much more suitable forum: https://groups.google.com/group/zaproxy-users for them
