### ISSUE TITLE
Ubuntu 16.04 version bump?

### ISSUE THREAD

**Issue by RRAlex** [zaproxy/zaproxy#2903]
Hi,
I was wondering if there was any blockers for moving the Dockerfile to Ubuntu 16.04?

15.04 is EOL since February 4th and is thus heavier on transfer for those using the LTS and is without security patches, etc.

cheers!

**Comment by psiinon** [comment]
Not that I'm aware of - I'll give it a go and see :)
I'm a big fan of Docker, but definitely still learning, so any more feedback about how we could improve our images gratefully received!
