### ISSUE TITLE
SQL Injection alert - there is no query involved

### ISSUE THREAD

**Issue by Harish27-GitHub** [zaproxy/zaproxy#2904]
Hi,

I have an REST API that accepts array of names and returns back complex object as result. ZAP tool logged it as possible flaw under SQL injection. Can you help me out with some explanation as help.

REST API URL: https://demo3.internal.com/local/GetMyThemes?Date=Thu%20Sep%2029%202016%2014:19:49%20GMT+0000%20(Coordinated%20Universal%20Time)
Type: POST
Actual Payload: 
{"Names":["StagingApp3","Invoice Processing","InFlight","HotFix1 Testing","CreateLocation","UpdateLocation","Opportunity","CreateHousehold","CreateTask","TestAppMilind","Comments"]}

ZAP tool attack Payload:
{"Names":["StagingApp3","Invoice Processing","InFlight","HotFix1 Testing","CreateLocation AND 1=1 --","UpdateLocation","Opportunity","CreateHousehold","CreateTask","TestAppMilind","Comments"]}

" AND 1=1 --" was appended as part of string item "CreateLocation" and considered as SQL injection opportunity.

Thank you,
 Harish

**Comment by Harish27-GitHub** [comment]
Similar to this, now Remote OS injection has started to pop up. ZAP is just including sleep command as one of the input array and in case response was actually taking more time due to internet then it logs as Attack successful.

**Comment by thc202** [comment]
Which ZAP version are you using?

**Comment by Harish27-GitHub** [comment]
ZAP 2.5.0 Standard. 
https://github.com/zaproxy/zaproxy/wiki/Downloads 
Windows Version.

**Comment by kingthorin** [comment]
https://groups.google.com/forum/m/#!topic/zaproxy-develop/y-IJDZG5skk

https://github.com/zaproxy/zaproxy/issues/2647

**Comment by kingthorin** [comment]
No further input after providing guidance on sleep settings.
