### ISSUE TITLE
Increase max number of brute force threads

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#2912]
As per https://twitter.com/__Freakyclown__/status/783320237622095877
Should be at least 50.
Maybe the max threads for all of the scanners could be overridable on the cmdline for 'expert' use?

**Comment by psiinon** [comment]
200 suggested via https://twitter.com/__Freakyclown__/status/783321932364128257 :)

**Comment by psiinon** [comment]
Note that using `-config bruteforce.threadPerHost=200` should work as long as you dont go back to the options page ;)

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#602.
