### ISSUE TITLE
Issues found : 0

### ISSUE THREAD

**Issue by shreyasmrs** [zaproxy/zaproxy#2913]
I'm running zap-cli on owasp bwa and I know it has vulnerabilities. I'm getting zero issues.
Please help me out

**Comment by kingthorin** [comment]
This type of inquiry is better suited to the User Group [1] than the issue tracker. When you post over there please include a bunch of additional detail. [BWA](https://www.owasp.org/index.php/OWASP_Broken_Web_Applications_Project) is a collection of apps. So which one are you having trouble with? What exactly is the problem? Do you have any errors? Can you connect to it manually? Through ZAP as a proxy? etc.

[1] https://groups.google.com/forum/#!forum/zaproxy-users
