### ISSUE TITLE
IOError: ('http protocol error', 0, 'got a bad status line', None) while running zap via python api

### ISSUE THREAD

**Issue by gb-kriss** [zaproxy/zaproxy#2914]
Hi All

Iam using Zap2.5 version, iam trying to  run the below python script to automate scanning the scanning process,

```
#!/usr/bin/env python
# coding: latin-1

import time
#import urllib2
from pprint import pprint
from zapv2 import ZAPv2

# Here the target is defined and an instance of ZAP is created.
target = 'http://demo.testfire.net/'
zap = ZAPv2()

# Use the line below if ZAP is not listening on 8090.
# zap = ZAPv2(proxies={'http': 'http://127.0.0.1:8090', 'https': 'http://127.0.0.1:9090'})

# ZAP starts accessing the target.
print 'Accessing target %s' % target
zap.urlopen(target)
time.sleep(2)

# The spider starts crawling the website for URL’s
print 'Spidering target %s' % target
zap.ascan.scan(target)
while (int(zap.ascan.status) < 100):
   print 'Scan progress %: ' + zap.ascan.status

   time.sleep(600)

print 'Scan completed'
```

On running the above script, getting the below error

"scan.py", line 23, in zap.spider.scan(target) File "build/bdist.linux-x86_64/egg/zapv2/spider.py", line 156, in scan File "build/bdist.linux-x86_64/egg/zapv2/init.py", line 145, in _request File "build/bdist.linux-x86_64/egg/zapv2/init.py", line 124, in urlopen File "/usr/lib/python2.7/urllib.py", line 87, in urlopen return opener.open(url) File "/usr/lib/python2.7/urllib.py", line 208, in open return getattr(self, name)(url) File "/usr/lib/python2.7/urllib.py", line 352, in open_http 'got a bad status line', None) IOError: ('http protocol error', 0, 'got a bad status line', None)

Thanks
Saikrishna

<sub>Edit by kingthorin 20161005: fix code tags so that things display properly</sub>

**Comment by kingthorin** [comment]
What version of the python api (ZAPv2) are you using?

**Comment by thc202** [comment]
Worth checking if ZAP is really listening on default port (8080).

**Comment by gb-kriss** [comment]
iam using zap 2.5.0 version

**Comment by gb-kriss** [comment]
zap is listening to default port 8080, i have verified tools--->options-->localproxy, the port it is listening to default port 8080, but how does it help?, iam trying to scan some different url http://demo.testfire.net/

**Comment by thc202** [comment]
That was to confirm that the API client is really connecting to ZAP.
Which version of the Python API client are you using?

Could you post the output of another run? (the posted stack trace is using the spider class but the posted script is not using it)

**Comment by gb-kriss** [comment]
Thanks for the response 
Python Api client is 2.4-0.0.8  iam using, actually its a script copied from the below link
https://github.com/zaproxy/zaproxy/wiki/ApiPython

**Comment by gb-kriss** [comment]
i have followed the instructions mentioned in below link
https://github.com/zaproxy/zaproxy/wiki/ApiPython

**Comment by gb-kriss** [comment]
Accessing target http://demo.testfire.net/
Spidering target http://demo.testfire.net/
Traceback (most recent call last):
  File "scan.py", line 23, in <module>
    zap.spider.scan(target)
  File "build/bdist.linux-x86_64/egg/zapv2/spider.py", line 156, in scan
  File "build/bdist.linux-x86_64/egg/zapv2/__init__.py", line 145, in _request
  File "build/bdist.linux-x86_64/egg/zapv2/__init__.py", line 124, in urlopen
  File "/usr/lib/python2.7/urllib.py", line 87, in urlopen
    return opener.open(url)
  File "/usr/lib/python2.7/urllib.py", line 208, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 352, in open_http
    'got a bad status line', None)
IOError: ('http protocol error', 0, 'got a bad status line', None)

**Comment by thc202** [comment]
@gb-kriss if you are still able to reproduce the issue, could you check zap.log file? (located in ZAP 'home' directory [1])

[1] https://github.com/zaproxy/zaproxy/wiki/FAQconfig

**Comment by thc202** [comment]
@gb-kriss do you have any other details about the issue?

**Comment by limquanheng** [comment]
I am currently facing the same issue

Traceback (most recent call last):
  File "C:/Users/limqu/Desktop/zaproxy_dev/zap-baseline.py", line 23, in <module>
    scanid = zap.spider.scan(target, apikey=apikey)
  File "C:\Python27\lib\site-packages\zapv2\spider.py", line 108, in scan
    return self.zap._request(self.zap.base + 'spider/action/scan/', {'url' : url, 'apikey' : apikey})
  File "C:\Python27\lib\site-packages\zapv2\__init__.py", line 131, in _request
    return json.loads(self.urlopen(url + '?' + urllib.urlencode(get)))
  File "C:\Python27\lib\site-packages\zapv2\__init__.py", line 110, in urlopen
    return urllib.urlopen(*args, **kwargs).read()
  File "C:\Python27\lib\urllib.py", line 87, in urlopen
    return opener.open(url)
  File "C:\Python27\lib\urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "C:\Python27\lib\urllib.py", line 357, in open_http
    'got a bad status line', None)
IOError: ('http protocol error', 0, 'got a bad status line', None)

**Comment by thc202** [comment]
@limquanheng what ZAP version? Could you check the zap.log file? (located in "home" directory [1])

[1] https://github.com/zaproxy/zaproxy/wiki/FAQconfig

**Comment by thc202** [comment]
Closing, insufficient evidence, also, latest Python API client version is no longer using urllib. If you still have issues with the latest version, please, let us know through the [User Group](https://groups.google.com/group/zaproxy-users). Thank you.

For reference, https://github.com/zaproxy/zaproxy/wiki/FAQapikey (which might help address connection problems).
