### ISSUE TITLE
Report generation for specific active scan - using ZAP API

### ISSUE THREAD

**Issue by BSec** [zaproxy/zaproxy#2920]
**Issue Noticed: in version: 2.5.0 API**

At this URL/API ( http://ZAP-IP:PORT/UI/core/other/htmlreport/), we are accepting only the API key but not the scanID. Because of this, the end user is allowed to see scan result of scanID zero always.
_Attached screen shot on the same._

**Solution:** aceept scanID field to get the relaent HTML report as per scanID value.
![za-capture](https://cloud.githubusercontent.com/assets/14342854/19232026/0efe69a8-8efb-11e6-88e1-3abb08baba83.PNG)

**Comment by BSec** [comment]
There can be multiple scanIDs, in this scenario the end user may want to see results of scanID=x.
So we need to have an entry point to let the ZAP tool know the scanID to share appropriate htmlreport results.

**Comment by thc202** [comment]
As that's specifically for active scan results I think it would be better with new `ascan` API endpoints (e.g. `ascan/other/htmlreport/?scanId=x`).

**Comment by raghuveerbathini** [comment]
I'm waiting for this enhancement, as there is no way to access the report by scanId or contextId.

**Comment by kingthorin** [comment]
@Bsec did @thc202 address you concerns/ideas? Can this be closed?

**Comment by BSec** [comment]
Will cross check it today and let you know. Thank you.

On 17 Jun 2017 5:42 a.m., "kingthorin" <notifications@github.com> wrote:

@BSec <https://github.com/bsec> did @thc202 <https://github.com/thc202>
address you concerns/ideas? Can this be closed?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/zaproxy/zaproxy/issues/2920#issuecomment-309170989>,
or mute
the thread

**Comment by thc202** [comment]
We should leave it open, the issue was not yet implemented (my suggestion was just where the new API endpoint(s) should be).

**Comment by kingthorin** [comment]
Ok

**Comment by DavidTimberlake** [comment]
I'm chiming in that not being able to request the html report from a specific scan ID means that we can't use the zap server to scan multiple sites on the same server without sometimes getting cross-contamination.  I think the request to add this to ascan endpoint by th202 is good.

**Comment by psiinon** [comment]
I can see why this would be really useful.
Unfortunately the way ZAP stores the issues doesnt make this easy.
Doesnt mean we shouldnt support it, just explaining why it hasnt been done to date ;)

**Comment by AshleyPoole** [comment]
Any update on this @psiinon @kingthorin, or maybe a work around? In my scenario we're scanning multiple web applications (around 15) so having a separate instance of ZAP isn't practical.

**Comment by AshleyPoole** [comment]
(Even if I could get alerts based on base url that would work, long as corrected alerts weren't displayed on new exports)

**Comment by ZainabAlShowely** [comment]
Will try to tackle this.

**Comment by thc202** [comment]
Based on latest discussions about reports this might be better added in one of the report add-ons (probably `exportreport`).
All information should be available to the add-ons (e.g. `ExtensionActiveScan#getAllScans()`/`#getScan(int)` → `ActiveScan#getAlertsIds()`). Also, worth noting that the inclusion of passive alerts should be optional.

**Comment by ZainabAlShowely** [comment]
Thanks, will do.
