### ISSUE TITLE
How to pass API key to ZAP to scan using PY API?

### ISSUE THREAD

**Issue by BSec** [zaproxy/zaproxy#2921]
The have observed that we are getting this error because of missing API key.

How to pass API key to ZAP to scan using PY API?
(https://github.com/zaproxy/zaproxy/wiki/ApiPython)
The current example code given at above URL is not reflecting the recent changes to use API keys. Please do the needful. Thanks.

**Comment by kingthorin** [comment]
https://groups.google.com/forum/#!topic/zaproxy-develop/LN88tarlnpU

**Comment by thc202** [comment]
Closing, the example script now shows how to use/pass the API key.
