### ISSUE TITLE
JavaDoc issue with scanAsUser client API call

### ISSUE THREAD

**Issue by dkindel** [zaproxy/zaproxy#2926]
Currently, the javadocs note that the scanAsUser signature is:
scanAsUser(String apikey, String url, String contextid, String userid, String maxchildren) 

In the code, the signature is actually:
scanAsUser(String apikey, String contextid, String userid, String url, String maxchildren, String recurse, String subtreeonly)

Not only are there the 2 extra parameters but the url parameter had moved positions.  This caused an exception while running:
Exception : Missing Parameter (missing_parameter) : contextId: JSONObject["contextId"] is not a number.

Using the signature as it is in the code, obviously, fixed the issue.

**Comment by thc202** [comment]
Which JavaDocs are you referring to? Which version of API client are you using?

**Comment by thc202** [comment]
Also, which version of ZAP?

**Comment by dkindel** [comment]
I got the javadocs from this page:
https://github.com/zaproxy/zaproxy/wiki/ApiJava

It looks like those are for 2.4.0 and I'm using 2.5.0 which might explain why it's out of date.  It might be as simple as updating that link at any rate.

**Comment by psiinon** [comment]
Yeah, we should generate the javadocs for 2.5.0, upload them and link to them :/
And update that page...

**Comment by kingthorin** [comment]
Closing. The JavaDoc was out of date and is no longer at the reported location.

Up-to-date java client api info is here: https://javadoc.io/doc/org.zaproxy/zap-clientapi/
