### ISSUE TITLE
Active scan

### ISSUE THREAD

**Issue by logeshhy** [zaproxy/zaproxy#2932]
It's an excellent tool.. I use it to test my websites to find vulnerability.. today I did a update on add-ons of zapp.. after that active Scan stucks on path traversal, even if I skip it stucks on every other tests which follows.. am testing my website at local host.. os-windows 10,  using wamp 3,zap 2.5 Everything is latest.. pls help me..

**Comment by logeshhy** [comment]
It stucks on Not only the website on local host.. but also the website live on internet..

**Comment by logeshhy** [comment]
Apache uses port 80; zap uses port 8080, spider was successful.. but path traversal stucks on some file (each time different file)..

**Comment by logeshhy** [comment]
Progressbar is full.. graph shows very low lines almost dead lines after stucking

**Comment by psiinon** [comment]
Heres a good guide to look at https://github.com/zaproxy/zaproxy/wiki/FAQhelp - especially things like checking zap.log for errors.

**Comment by logeshhy** [comment]
Active scan stucks exactly around 1000 requests everytime I try.. on windows 10 or on Kali linux via vmware.. even on live website or local one

**Comment by kingthorin** [comment]
There's a limit to the number of requests shown in the active scan window... just because you hit the default limit doesn't mean anything has stopped.

**Comment by psiinon** [comment]
By default the UI only shows the first 1000 requests, you can change that via https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsOptionsAscan#max-results-to-list
Look at the Request count - that should still be increasing.

**Comment by thc202** [comment]
Hm, might be related to https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsOptionsAscan#max-results-to-list ?

**Comment by psiinon** [comment]
well if all 3 of us think so then it must be right :P

**Comment by logeshhy** [comment]
If so.. incase of limits in gui.. what about graphs.. why the line is dead after 1000 requests and names of the files which is being scanned also stopped

**Comment by psiinon** [comment]
have you looked in the zap.log file?

**Comment by thc202** [comment]
Also, when that happens what's the state of the Progress tab in Scan Progress dialogue? (e.g. total requests stop at 1000 too?)

**Comment by kingthorin** [comment]
References:
https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsOptionsAscan#max-results-to-list
https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsScanprogress

**Comment by logeshhy** [comment]
Damn :).. now I increased the threads to max and display requests to 10000.. lol.. let's see what happens.. am running on local host.

**Comment by logeshhy** [comment]
And kudos to you guys for clearing me out on active scan..

**Comment by psiinon** [comment]
Glad thats sorted out :)
Can you ask about your SQL issues on the ZAP User Group https://groups.google.com/group/zaproxy-users ?
Thats a better forum for general questions like those.

**Comment by logeshhy** [comment]
Sure bro..
