### ISSUE TITLE
Wrong charset used in response body if no charset set

### ISSUE THREAD

**Issue by avinas-h** [zaproxy/zaproxy#2935]
Steps to reproduce the bug.
Download the latest weekly release of ZAP (I used the 2016-10-10 one)
1- In a web browser (which is configured to the latest ZAP), visit http://genius.com/login and notice how the web page is loaded (the web page will be loaded correctly)

2- Close the browser, load any Zest proxy rule to the latest ZAP, open the web browser and visit http://genius.com/login

3- You will noticed that the web page is loaded incorrectly, in particular the styling of the page gets messed up. This can severely affect Selenium tests utilizing ZAP and Zest proxy rules.

I noticed that the issue is also there in ZAP 2.5. But I didn't find the issue in June 2016 Weekly release of ZAP.

**Comment by thc202** [comment]
Is/was the browser trusting ZAP's certs? That page has styles from <https://assets.genius.com/> (note the HTTPS scheme).

**Comment by avinas-h** [comment]
Yes. That is the reason why the page was loading properly when it was intercepting via ZAP without any proxy rules. Btw, the following is the configuration of my machine.
![image](https://cloud.githubusercontent.com/assets/13018530/19478928/acf803d6-9544-11e6-9d1f-d65956c73360.png)

Were you able to reproduce the issue with the latest version of ZAP and the 2.5 stable version?

**Comment by avinas-h** [comment]
Update: I was also able to reproduce the issue also in a Windows 10 machine with yesterday's weekly release. Please note that you must clear the browsing history when you try to load the web page with the Zest proxy rule. Otherwise, you will not be able to see the issue because the browser uses caches stylesheets from the previous session in which the Zest proxy rule was not activated.

**Comment by thc202** [comment]
I was able to reproduce the issue, it's related to the character encoding of the (CSS) response. Thanks!

**Comment by avinas-h** [comment]
Great! Can't wait to have the fixed weekly release.

**Comment by avinas-h** [comment]
I thought the issue was resolved when you marked it as closed. But I downloaded yesterday's weekly release (D-2016-10-24) and the issue is still there. You should be able to reproduce the issue in the same way as I explained earlier.
The following screenshot shows how the web page loading correctly when the ZAP rule is disabled.
![image](https://cloud.githubusercontent.com/assets/13018530/19684658/c3d3da5c-9ab8-11e6-8abf-9c21ef4f74ae.png)

The following screenshot shows the web page loading incorrectly when the ZAP rule is enabled (the proxy rule does not tamper the requests or responses).
![image](https://cloud.githubusercontent.com/assets/13018530/19684693/ea60106e-9ab8-11e6-97ab-3c68fed1c939.png)

**Comment by kingthorin** [comment]
What are the conditions of the script?

**Comment by avinas-h** [comment]
![image](https://cloud.githubusercontent.com/assets/13018530/19685281/128c4474-9abc-11e6-99d4-8356043e4488.png)

**Comment by thc202** [comment]
Works for me with the latest weekly release. Could you provide a screenshot of the history tab after requesting the site? Preferably sorted by URL (only interested in the URL and size of response body, other columns could be hidden).

**Comment by thc202** [comment]
Instead of screenshot you could just copy/paste the contents of the history tab.

**Comment by avinas-h** [comment]
Sorry I didn't understand when you said copy/paste the contents of the history tab because when I do a Ctrl+A in the history tab and right click I only have the option "Copy URLs to clipboard". So I am doing it below and you can find the screenshot below that 
http://api.mixpanel.com/decide/?verbose=1&version=1&lib=web&token=77967c52dc38186cc1aadebdd19e2a82&ip=1&_=1477399393701
http://api.mixpanel.com/track/?data=eyJldmVudCI6ICJIb21lIFBhZ2UgVmlldyIsInByb3BlcnRpZXMiOiB7IiRvcyI6ICJXaW5kb3dzIiwiJGJyb3dzZXIiOiAiRmlyZWZveCIsIiRjdXJyZW50X3VybCI6ICJodHRwOi8vZ2VuaXVzLmNvbS8iLCIkYnJvd3Nlcl92ZXJzaW9uIjogNDYsIiRzY3JlZW5faGVpZ2h0IjogMTIwMCwiJHNjcmVlbl93aWR0aCI6IDE5MjAsIm1wX2xpYiI6ICJ3ZWIiLCIkbGliX3ZlcnNpb24iOiAiMi45LjE2IiwiZGlzdGluY3RfaWQiOiAiMTU3ZmJhNWVhOTMzMjItMGY5ZWY0YWFjMDNiNWI4LTRjMzMyZTdjLTIzMjgwMC0xNTdmYmE1ZWE5NDUyOCIsIkxvZ2dlZCBJbiI6IGZhbHNlLCJJcyBFZGl0b3IiOiBudWxsLCJJcyBNb2RlcmF0b3IiOiBudWxsLCJNb2JpbGUgU2l0ZSI6IGZhbHNlLCJDaGFubmVsIjogInJhcCIsIiRpbml0aWFsX3JlZmVycmVyIjogIiRkaXJlY3QiLCIkaW5pdGlhbF9yZWZlcnJpbmdfZG9tYWluIjogIiRkaXJlY3QiLCJnZW5pdXNfcGxhdGZvcm0iOiAid2ViIiwiZGZwX2VuYWJsZWQiOiB0cnVlLCJ0b2tlbiI6ICI3Nzk2N2M1MmRjMzgxODZjYzFhYWRlYmRkMTllMmE4MiIsIiRfX2MiOiAwfX0%3D&ip=1&_=1477399393707
http://api.mixpanel.com/track/?data=eyJldmVudCI6ICJQYWdlIFNlc3Npb24gRW5kIiwicHJvcGVydGllcyI6IHsiJG9zIjogIldpbmRvd3MiLCIkYnJvd3NlciI6ICJGaXJlZm94IiwiJGN1cnJlbnRfdXJsIjogImh0dHA6Ly9nZW5pdXMuY29tLyIsIiRicm93c2VyX3ZlcnNpb24iOiA0NiwiJHNjcmVlbl9oZWlnaHQiOiAxMjAwLCIkc2NyZWVuX3dpZHRoIjogMTkyMCwibXBfbGliIjogIndlYiIsIiRsaWJfdmVyc2lvbiI6ICIyLjkuMTYiLCJkaXN0aW5jdF9pZCI6ICIxNTdmYmE1ZWE5MzMyMi0wZjllZjRhYWMwM2I1YjgtNGMzMzJlN2MtMjMyODAwLTE1N2ZiYTVlYTk0NTI4IiwiTG9nZ2VkIEluIjogZmFsc2UsIklzIEVkaXRvciI6IG51bGwsIklzIE1vZGVyYXRvciI6IG51bGwsIk1vYmlsZSBTaXRlIjogZmFsc2UsIkNoYW5uZWwiOiAicmFwIiwiJGluaXRpYWxfcmVmZXJyZXIiOiAiJGRpcmVjdCIsIiRpbml0aWFsX3JlZmVycmluZ19kb21haW4iOiAiJGRpcmVjdCIsIlRpbWUgT24gUGFnZSI6IDM2NTMuNDM2NDY0OTk5OTk5OCwiVGltZSBPbiBQYWdlIFdoZW4gVmlzaWJsZSI6IDM2NTMuNDM1NjE1LCJUaW1lIE9uIFBhZ2UgV2hlbiBGb2N1c2VkIjogMTkuMzYxNzE1MDAwMDAwNTIyLCJnZW5pdXNfcGxhdGZvcm0iOiAid2ViIiwiZGZwX2VuYWJsZWQiOiB0cnVlLCJ0b2tlbiI6ICI3Nzk2N2M1MmRjMzgxODZjYzFhYWRlYmRkMTllMmE4MiIsIiRfX2MiOiAwfX0%3D&ip=1&_=1477399390247
http://api.mixpanel.com/track/?data=eyJldmVudCI6ICJtcF9wYWdlX3ZpZXciLCJwcm9wZXJ0aWVzIjogeyIkb3MiOiAiV2luZG93cyIsIiRicm93c2VyIjogIkZpcmVmb3giLCIkY3VycmVudF91cmwiOiAiaHR0cDovL2dlbml1cy5jb20vIiwiJGJyb3dzZXJfdmVyc2lvbiI6IDQ2LCIkc2NyZWVuX2hlaWdodCI6IDEyMDAsIiRzY3JlZW5fd2lkdGgiOiAxOTIwLCJtcF9saWIiOiAid2ViIiwiJGxpYl92ZXJzaW9uIjogIjIuOS4xNiIsImRpc3RpbmN0X2lkIjogIjE1N2ZiYTVlYTkzMzIyLTBmOWVmNGFhYzAzYjViOC00YzMzMmU3Yy0yMzI4MDAtMTU3ZmJhNWVhOTQ1MjgiLCJMb2dnZWQgSW4iOiBmYWxzZSwiSXMgRWRpdG9yIjogbnVsbCwiSXMgTW9kZXJhdG9yIjogbnVsbCwiTW9iaWxlIFNpdGUiOiBmYWxzZSwiQ2hhbm5lbCI6ICJyYXAiLCIkaW5pdGlhbF9yZWZlcnJlciI6ICIkZGlyZWN0IiwiJGluaXRpYWxfcmVmZXJyaW5nX2RvbWFpbiI6ICIkZGlyZWN0IiwibXBfcGFnZSI6ICJodHRwOi8vZ2VuaXVzLmNvbS8iLCJtcF9icm93c2VyIjogIkZpcmVmb3giLCJtcF9wbGF0Zm9ybSI6ICJXaW5kb3dzIiwidG9rZW4iOiAiNzc5NjdjNTJkYzM4MTg2Y2MxYWFkZWJkZDE5ZTJhODIifX0%3D&ip=1&_=1477399393711
http://b.scorecardresearch.com/b?c1=2&c2=17151659&ns__t=1477399393244&ns_c=UTF-8&cv=3.1&c8=Genius%20%7C%20Song%20Lyrics%20%26%20Knowledge&c7=http%3A%2F%2Fgenius.com%2F&c9=
http://b.scorecardresearch.com/b2?c1=2&c2=17151659&ns__t=1477399393244&ns_c=UTF-8&cv=3.1&c8=Genius%20%7C%20Song%20Lyrics%20%26%20Knowledge&c7=http%3A%2F%2Fgenius.com%2F&c9=
http://b.scorecardresearch.com/beacon.js
http://bam.nr-data.net/1/25a615a0b6?a=309898&v=974.7d740e1&to=IFleFkcJCAhdERteXQ5THxFdCRM%3D&rst=4694&ref=http://genius.com/&ap=559&be=158&fe=4444&dc=2976&af=err,xhr,stn,ins&perf=%7B%22timing%22:%7B%22of%22:1477399390118,%22n%22:0,%22u%22:115,%22ue%22:141,%22f%22:6,%22dn%22:6,%22dne%22:6,%22c%22:6,%22ce%22:6,%22rq%22:6,%22rp%22:114,%22rpe%22:115,%22dl%22:115,%22di%22:2855,%22ds%22:3133,%22de%22:3476,%22dc%22:4600,%22l%22:4600,%22le%22:4614%7D,%22navigation%22:%7B%7D%7D&ja=%7B%22signedIn%22:false%7D&jsonp=NREUM.setToken
http://cdn.mxpnl.com/libs/mixpanel-2.2.min.js
http://edge.quantserve.com/quant.js
http://genius.com/
http://js-agent.newrelic.com/nr-974.min.js
http://pagead2.googlesyndication.com/pagead/gen_204?id=slot_render_ended_false_positive&vrg=104&nw_id=342026871&nslots=3&eid=108809080%2C108809133%2C108809146&pub_url=http%3A%2F%2Fgenius.com%2F
http://partner.googleadservices.com/gpt/pubads_impl_104.js
http://srv-2016-10-25-12.config.parsely.com/config/genius.com
http://static.chartbeat.com/js/chartbeat.js
http://static.parsely.com/code/ptrack-v0.6.0-engaged-time.js
http://static.parsely.com/p.js
http://www.googletagservices.com/tag/js/gpt.js
https://assets.genius.com/javascripts/compiled/bagon_desktop-ece2f5112f1a74e0cd2d4b3a77f6aebe.js
https://assets.genius.com/stylesheets/compiled/bagon_desktop-73569b197c0c9bd44c85650284e4b585.css
https://assets.genius.com/stylesheets/compiled/bagon_fonts-bbc6a4e57e275a56e302efb59741b16c.css
https://dialog.filepicker.io/dialog/comm_iframe/
https://s.ytimg.com/yts/jsbin/www-widgetapi-vflFoWyC7/www-widgetapi.js
https://securepubads.g.doubleclick.net/gampad/ads?gdfp_req=1&correlator=2623946061419879&output=json_html&callback=callbackProxy&impl=fifs&json_a=1&eid=108809080%2C108809133%2C108809146&sc=0&sfv=1-0-5&iu_parts=342026871%2Cdesktop_home_leaderboard%2Cdesktop_home_medium1%2Cdesktop_home_skin&enc_prev_ius=%2F0%2F1%2C%2F0%2F2%2C%2F0%2F3&prev_iu_szs=970x250%7C728x90%2C300x600%2C1x1&prev_scp=is_atf%3Dtrue%7Cis_atf%3Dfalse%7Cis_atf%3Dtrue&cust_params=environment%3Dproduction%26platform%3Dweb&cookie_enabled=1&lmt=1477399393&dt=1477399393663&cc=100&frm=20&biw=579&bih=485&oid=2&adxs=0%2C48%2C8&adys=0%2C7842%2C13047&adks=2491846782%2C4156135790%2C150281395&gut=v2&ifi=1&u_tz=120&u_his=1&u_h=1200&u_w=1920&u_ah=1160&u_aw=1920&u_cd=24&u_nplug=2&u_nmime=4&u_sd=1&flash=22.0.0&url=http%3A%2F%2Fgenius.com%2F&dssz=28&icsg=32768&std=7&vrg=104&vrp=104&ga_vid=1657484162.1477399394&ga_sid=1477399394&ga_hid=1564293021
https://www.filepicker.io/dialog/comm_iframe/
https://www.google-analytics.com/ga.js
https://www.youtube.com/iframe_api

![image](https://cloud.githubusercontent.com/assets/13018530/19686490/aea7943a-9ac1-11e6-94e5-feb8791df404.png)

**Comment by thc202** [comment]
You can use the copy keyboard shortcut (usually Ctrl + C) to copy the selected rows.
It's better to copy as the unit of the response body is in bytes and it includes the whole URL.

The previous screenshot was with the Zest script enabled?

**Comment by avinas-h** [comment]
Yes the screenshot is with the Zest script enabled.
The following is the PASTE after doing CTRL+C in the history tab.
74	Tue Oct 25 14:43:13 CEST 2016	GET	http://api.mixpanel.com/decide/?verbose=1&version=1&lib=web&token=77967c52dc38186cc1aadebdd19e2a82&ip=1&_=1477399393701	200	OK	86	65	Low	false	JSON
77	Tue Oct 25 14:43:13 CEST 2016	GET	http://api.mixpanel.com/track/?data=eyJldmVudCI6ICJIb21lIFBhZ2UgVmlldyIsInByb3BlcnRpZXMiOiB7IiRvcyI6ICJXaW5kb3dzIiwiJGJyb3dzZXIiOiAiRmlyZWZveCIsIiRjdXJyZW50X3VybCI6ICJodHRwOi8vZ2VuaXVzLmNvbS8iLCIkYnJvd3Nlcl92ZXJzaW9uIjogNDYsIiRzY3JlZW5faGVpZ2h0IjogMTIwMCwiJHNjcmVlbl93aWR0aCI6IDE5MjAsIm1wX2xpYiI6ICJ3ZWIiLCIkbGliX3ZlcnNpb24iOiAiMi45LjE2IiwiZGlzdGluY3RfaWQiOiAiMTU3ZmJhNWVhOTMzMjItMGY5ZWY0YWFjMDNiNWI4LTRjMzMyZTdjLTIzMjgwMC0xNTdmYmE1ZWE5NDUyOCIsIkxvZ2dlZCBJbiI6IGZhbHNlLCJJcyBFZGl0b3IiOiBudWxsLCJJcyBNb2RlcmF0b3IiOiBudWxsLCJNb2JpbGUgU2l0ZSI6IGZhbHNlLCJDaGFubmVsIjogInJhcCIsIiRpbml0aWFsX3JlZmVycmVyIjogIiRkaXJlY3QiLCIkaW5pdGlhbF9yZWZlcnJpbmdfZG9tYWluIjogIiRkaXJlY3QiLCJnZW5pdXNfcGxhdGZvcm0iOiAid2ViIiwiZGZwX2VuYWJsZWQiOiB0cnVlLCJ0b2tlbiI6ICI3Nzk2N2M1MmRjMzgxODZjYzFhYWRlYmRkMTllMmE4MiIsIiRfX2MiOiAwfX0%3D&ip=1&_=1477399393707	200	OK	93	1	Low	false	JSON
7	Tue Oct 25 14:43:10 CEST 2016	GET	http://api.mixpanel.com/track/?data=eyJldmVudCI6ICJQYWdlIFNlc3Npb24gRW5kIiwicHJvcGVydGllcyI6IHsiJG9zIjogIldpbmRvd3MiLCIkYnJvd3NlciI6ICJGaXJlZm94IiwiJGN1cnJlbnRfdXJsIjogImh0dHA6Ly9nZW5pdXMuY29tLyIsIiRicm93c2VyX3ZlcnNpb24iOiA0NiwiJHNjcmVlbl9oZWlnaHQiOiAxMjAwLCIkc2NyZWVuX3dpZHRoIjogMTkyMCwibXBfbGliIjogIndlYiIsIiRsaWJfdmVyc2lvbiI6ICIyLjkuMTYiLCJkaXN0aW5jdF9pZCI6ICIxNTdmYmE1ZWE5MzMyMi0wZjllZjRhYWMwM2I1YjgtNGMzMzJlN2MtMjMyODAwLTE1N2ZiYTVlYTk0NTI4IiwiTG9nZ2VkIEluIjogZmFsc2UsIklzIEVkaXRvciI6IG51bGwsIklzIE1vZGVyYXRvciI6IG51bGwsIk1vYmlsZSBTaXRlIjogZmFsc2UsIkNoYW5uZWwiOiAicmFwIiwiJGluaXRpYWxfcmVmZXJyZXIiOiAiJGRpcmVjdCIsIiRpbml0aWFsX3JlZmVycmluZ19kb21haW4iOiAiJGRpcmVjdCIsIlRpbWUgT24gUGFnZSI6IDM2NTMuNDM2NDY0OTk5OTk5OCwiVGltZSBPbiBQYWdlIFdoZW4gVmlzaWJsZSI6IDM2NTMuNDM1NjE1LCJUaW1lIE9uIFBhZ2UgV2hlbiBGb2N1c2VkIjogMTkuMzYxNzE1MDAwMDAwNTIyLCJnZW5pdXNfcGxhdGZvcm0iOiAid2ViIiwiZGZwX2VuYWJsZWQiOiB0cnVlLCJ0b2tlbiI6ICI3Nzk2N2M1MmRjMzgxODZjYzFhYWRlYmRkMTllMmE4MiIsIiRfX2MiOiAwfX0%3D&ip=1&_=1477399390247	200	OK	59	1	Low	false	JSON
75	Tue Oct 25 14:43:13 CEST 2016	GET	http://api.mixpanel.com/track/?data=eyJldmVudCI6ICJtcF9wYWdlX3ZpZXciLCJwcm9wZXJ0aWVzIjogeyIkb3MiOiAiV2luZG93cyIsIiRicm93c2VyIjogIkZpcmVmb3giLCIkY3VycmVudF91cmwiOiAiaHR0cDovL2dlbml1cy5jb20vIiwiJGJyb3dzZXJfdmVyc2lvbiI6IDQ2LCIkc2NyZWVuX2hlaWdodCI6IDEyMDAsIiRzY3JlZW5fd2lkdGgiOiAxOTIwLCJtcF9saWIiOiAid2ViIiwiJGxpYl92ZXJzaW9uIjogIjIuOS4xNiIsImRpc3RpbmN0X2lkIjogIjE1N2ZiYTVlYTkzMzIyLTBmOWVmNGFhYzAzYjViOC00YzMzMmU3Yy0yMzI4MDAtMTU3ZmJhNWVhOTQ1MjgiLCJMb2dnZWQgSW4iOiBmYWxzZSwiSXMgRWRpdG9yIjogbnVsbCwiSXMgTW9kZXJhdG9yIjogbnVsbCwiTW9iaWxlIFNpdGUiOiBmYWxzZSwiQ2hhbm5lbCI6ICJyYXAiLCIkaW5pdGlhbF9yZWZlcnJlciI6ICIkZGlyZWN0IiwiJGluaXRpYWxfcmVmZXJyaW5nX2RvbWFpbiI6ICIkZGlyZWN0IiwibXBfcGFnZSI6ICJodHRwOi8vZ2VuaXVzLmNvbS8iLCJtcF9icm93c2VyIjogIkZpcmVmb3giLCJtcF9wbGF0Zm9ybSI6ICJXaW5kb3dzIiwidG9rZW4iOiAiNzc5NjdjNTJkYzM4MTg2Y2MxYWFkZWJkZDE5ZTJhODIifX0%3D&ip=1&_=1477399393711	200	OK	80	1	Low	false	JSON
43	Tue Oct 25 14:43:13 CEST 2016	GET	http://b.scorecardresearch.com/b?c1=2&c2=17151659&ns__t=1477399393244&ns_c=UTF-8&cv=3.1&c8=Genius%20%7C%20Song%20Lyrics%20%26%20Knowledge&c7=http%3A%2F%2Fgenius.com%2F&c9=	302	Moved Temporarily	27	0	Low	false	SetCookie
61	Tue Oct 25 14:43:13 CEST 2016	GET	http://b.scorecardresearch.com/b2?c1=2&c2=17151659&ns__t=1477399393244&ns_c=UTF-8&cv=3.1&c8=Genius%20%7C%20Song%20Lyrics%20%26%20Knowledge&c7=http%3A%2F%2Fgenius.com%2F&c9=	204	No Content	22	0		false	SetCookie
33	Tue Oct 25 14:43:12 CEST 2016	GET	http://b.scorecardresearch.com/beacon.js	200	OK	23	1495	Low	false	
124	Tue Oct 25 14:43:14 CEST 2016	GET	http://bam.nr-data.net/1/25a615a0b6?a=309898&v=974.7d740e1&to=IFleFkcJCAhdERteXQ5THxFdCRM%3D&rst=4694&ref=http://genius.com/&ap=559&be=158&fe=4444&dc=2976&af=err,xhr,stn,ins&perf=%7B%22timing%22:%7B%22of%22:1477399390118,%22n%22:0,%22u%22:115,%22ue%22:141,%22f%22:6,%22dn%22:6,%22dne%22:6,%22c%22:6,%22ce%22:6,%22rq%22:6,%22rp%22:114,%22rpe%22:115,%22dl%22:115,%22di%22:2855,%22ds%22:3133,%22de%22:3476,%22dc%22:4600,%22l%22:4600,%22le%22:4614%7D,%22navigation%22:%7B%7D%7D&ja=%7B%22signedIn%22:false%7D&jsonp=NREUM.setToken	200	OK	245	57	Low	false	SetCookie
55	Tue Oct 25 14:43:12 CEST 2016	GET	http://cdn.mxpnl.com/libs/mixpanel-2.2.min.js	200	OK	498	59691	Low	false	
34	Tue Oct 25 14:43:12 CEST 2016	GET	http://edge.quantserve.com/quant.js	200	OK	25	8046	Low	false	Comment
5	Tue Oct 25 14:43:10 CEST 2016	GET	http://genius.com/	200	OK	102	119208	Low	false	Script, SetCookie, Comment
117	Tue Oct 25 14:43:14 CEST 2016	GET	http://js-agent.newrelic.com/nr-974.min.js	200	OK	70	22761	Low	false	Comment
84	Tue Oct 25 14:43:13 CEST 2016	GET	http://pagead2.googlesyndication.com/pagead/gen_204?id=slot_render_ended_false_positive&vrg=104&nw_id=342026871&nslots=3&eid=108809080%2C108809133%2C108809146&pub_url=http%3A%2F%2Fgenius.com%2F	204	No Content	31	0		false	
46	Tue Oct 25 14:43:13 CEST 2016	GET	http://partner.googleadservices.com/gpt/pubads_impl_104.js	200	OK	53	161882		false	Script
92	Tue Oct 25 14:43:13 CEST 2016	GET	http://srv-2016-10-25-12.config.parsely.com/config/genius.com	200	OK	285	377	Low	false	SetCookie
119	Tue Oct 25 14:43:14 CEST 2016	GET	http://static.chartbeat.com/js/chartbeat.js	200	OK	74	31740	Low	false	
96	Tue Oct 25 14:43:13 CEST 2016	GET	http://static.parsely.com/code/ptrack-v0.6.0-engaged-time.js	200	OK	142	29804	Low	false	Comment
41	Tue Oct 25 14:43:12 CEST 2016	GET	http://static.parsely.com/p.js	200	OK	265	6593	Low	false	Comment
28	Tue Oct 25 14:43:12 CEST 2016	GET	http://www.googletagservices.com/tag/js/gpt.js	200	OK	15	3553		false	Script
22	Tue Oct 25 14:43:10 CEST 2016	GET	https://assets.genius.com/javascripts/compiled/bagon_desktop-ece2f5112f1a74e0cd2d4b3a77f6aebe.js	200	OK	261	1765718	Low	false	Form, Password, Hidden, Upload, Object, Script, Comment
12	Tue Oct 25 14:43:10 CEST 2016	GET	https://assets.genius.com/stylesheets/compiled/bagon_desktop-73569b197c0c9bd44c85650284e4b585.css	200	OK	84	324783	Low	false	
16	Tue Oct 25 14:43:10 CEST 2016	GET	https://assets.genius.com/stylesheets/compiled/bagon_fonts-bbc6a4e57e275a56e302efb59741b16c.css	200	OK	158	285768	Low	false	Comment
102	Tue Oct 25 14:43:13 CEST 2016	GET	https://dialog.filepicker.io/dialog/comm_iframe/	200	OK	637	2068	Medium	false	Script, SetCookie
17	Tue Oct 25 14:43:10 CEST 2016	GET	https://s.ytimg.com/yts/jsbin/www-widgetapi-vflFoWyC7/www-widgetapi.js	200	OK	154	24604		false	
76	Tue Oct 25 14:43:13 CEST 2016	GET	https://securepubads.g.doubleclick.net/gampad/ads?gdfp_req=1&correlator=2623946061419879&output=json_html&callback=callbackProxy&impl=fifs&json_a=1&eid=108809080%2C108809133%2C108809146&sc=0&sfv=1-0-5&iu_parts=342026871%2Cdesktop_home_leaderboard%2Cdesktop_home_medium1%2Cdesktop_home_skin&enc_prev_ius=%2F0%2F1%2C%2F0%2F2%2C%2F0%2F3&prev_iu_szs=970x250%7C728x90%2C300x600%2C1x1&prev_scp=is_atf%3Dtrue%7Cis_atf%3Dfalse%7Cis_atf%3Dtrue&cust_params=environment%3Dproduction%26platform%3Dweb&cookie_enabled=1&lmt=1477399393&dt=1477399393663&cc=100&frm=20&biw=579&bih=485&oid=2&adxs=0%2C48%2C8&adys=0%2C7842%2C13047&adks=2491846782%2C4156135790%2C150281395&gut=v2&ifi=1&u_tz=120&u_his=1&u_h=1200&u_w=1920&u_ah=1160&u_aw=1920&u_cd=24&u_nplug=2&u_nmime=4&u_sd=1&flash=22.0.0&url=http%3A%2F%2Fgenius.com%2F&dssz=28&icsg=32768&std=7&vrg=104&vrp=104&ga_vid=1657484162.1477399394&ga_sid=1477399394&ga_hid=1564293021	200	OK	66	1003	Low	false	SetCookie
107	Tue Oct 25 14:43:13 CEST 2016	GET	https://www.filepicker.io/dialog/comm_iframe/	200	OK	648	2068	Medium	false	Script, SetCookie
83	Tue Oct 25 14:43:13 CEST 2016	GET	https://www.google-analytics.com/ga.js	200	OK	165	43082		false	
10	Tue Oct 25 14:43:10 CEST 2016	GET	https://www.youtube.com/iframe_api	200	OK	42	745		false

**Comment by thc202** [comment]
Thanks, there's a difference on the size of the CSS response. Upon reviewing the code again I spotted the issue, there's a statement that's relying on the platform's default encoding (and that's why it's working here and not there).

Would you mind test a new "weekly release" with the fix applied?

**Comment by avinas-h** [comment]
No, I would love to have the fixed version because I need it. So I can do the test and you will have your results.

**Comment by thc202** [comment]
Thanks, the release is available at:
https://github.com/thc202/zaproxy/releases/tag/w2016-10-25

**Comment by avinas-h** [comment]
Looks like it works! Thank you.
![image](https://cloud.githubusercontent.com/assets/13018530/19693789/183bb618-9add-11e6-981d-efcabc5d9530.png)

**Comment by thc202** [comment]
Great, thanks for letting us know!
