### ISSUE TITLE
Script change monitor

### ISSUE THREAD

**Issue by vdun** [zaproxy/zaproxy#2950]
When a script is modified outside ZAP, it does not recognize the the update.

**Comment by psiinon** [comment]
Solution - dont modify scripts outside of ZAP ;)
I guess we could provide an option to resync, but out of interest, why are you modifying the scripts using another tool?

**Comment by vdun** [comment]
- Using your favorite text editor (vim, atom, ...)
- File is mounted (sshfs, smb, ...)
- File is externally auto generated (curl, ...)
- Run scripts on (sed, ...)
- ...

What is the path (if exist) of the current edited script inside ZAP ? so I can rsync manually for the moment.

Another question: How can one debug the script (breakpoint, single stepping, ...) outside ZAP when it is being called by ZAP ?

**Comment by psiinon** [comment]
The scripts are put under the scripts/scripts directory in the ZAP directory, which by default is https://github.com/zaproxy/zaproxy/wiki/FAQconfig

I'm not aware of any way to debug a script running in ZAP from outside, I usually just add add print statements to show me whats going on ;)
If you find a standard way of debugging JSR223 scripts in Java then please let us know.

**Comment by vdun** [comment]
The 'scripts/scripts' does not reflect the current stat of file being edited in ZAP.
I current have no idea to debug JSR223.
How about live-debugging others (python, ...) ?

**Comment by psiinon** [comment]
You need to Save the scripts before the filesystem will be updated.
All of the scripts we support (including python) we do via JSR223: https://www.jcp.org/en/jsr/detail?id=223
If that doesnt support debugging then it would probably be very difficult for us to implement it ourselves.

**Comment by dhutty** [comment]
@thc202 pointed me to this thread when I had stumbled over needing to restart the ZAP daemon after modifying an auth script. In my case, the whole thing is automated: installation/configuration of ZAP by configuration management, installation/config/running the target by Jenkins et al., running the scan using orchestration tooling. So, during a debugging session, I modified the auth script and wondered (briefly) why the behaviour didn't change. Then I realised I needed to bounce ZAP and run my testing script (which loads the auth script) again. And all was well.

**Comment by kingthorin** [comment]
Does disabling/enabling the script have the same effect?

**Comment by thc202** [comment]
I'm afraid not (note that the authentication scripts can't be enabled/disabled).

**Comment by psiinon** [comment]
I think there are 3 use cases here, and in each case a script has been edited outside of ZAP:

- The script is not in the script console tab, in which case we can just use the new one
- The script is in the console but hasnt been changed, in which case we should replace the one in the script console with the new one and use that
- The script is in the console and has been changed, in which case we should use the new one (we dont want to prevent httpsender etc sctipts from running) but should prompt user to see if they want to keep the one they've changed or use the new one

If the script it not in the console then we can just check for the file on disk having been changed based on the timestamp. If it is in the console then we might need to have a timer thread which keeps checking the filestore for changes?
Does that cover it?

**Comment by kingthorin** [comment]
I think so. Would it be better to checksum/hash the content instead of depending on modification timestamp? That would address changes and reversions (when new timestamp isn't new content), and might also provide a mechanism to address (https://github.com/zaproxy/zaproxy/issues/2189)?

**Comment by psiinon** [comment]
I'd rather not have to checksum script files every time they run, that could impact performance. 
How useful will checksumming be? That would just be if someone touched the file on filestore but didnt change its contents? If we reload it then its no problem, and if its in the console and we prompt the user then they can just keep their current changes?

**Comment by kingthorin** [comment]
Ya ok :+1:

**Comment by thc202** [comment]
Will the user be able to enable/disable this? Or, is it enabled (by default?) for all scripts?

**Comment by psiinon** [comment]
I was thinking it would be enabled by default and not configurable. But if anyone can suggest reasons why people might not want this then happy to make it an option...
I am planning on looking at this, but havnt assigned it to myself yet just in case I dont get round to it ;)
