### ISSUE TITLE
Add message sent notifying to websocket fuzzer

### ISSUE THREAD

**Issue by jx6f** [zaproxy/zaproxy#2955]
The websocket fuzzer calls `org.zaproxy.zap.extension.websocket.WebSocketProxy#send` to transmit websocket messages.
https://github.com/zaproxy/zap-extensions/blob/d2e90c13ffebb0794c18d8fbc0dfc56fb4484230/src/org/zaproxy/zap/extension/websocket/fuzz/WebSocketFuzzerTask.java#L69

`org.zaproxy.zap.extension.websocket.WebSocketProxy#sendAndNotify` notifies that event to WebSocketObserver, but `org.zaproxy.zap.extension.websocket.WebSocketProxy#send` is not.
https://github.com/zaproxy/zap-extensions/blob/e5ea2c062e5217b9fde29444148aeae781ef6f30/src/org/zaproxy/zap/extension/websocket/WebSocketProxy.java#L780

I think that is a good idea adding `org.parosproxy.paros.network.HttpSender#addListener` like method to notify all websocket traffics.

**Comment by jx6f** [comment]
We can catch websocket messages sent from the websocket fuzzer by ZAP scripting(Fuzzer Websocker Processor).
However it is difficult to do with our own extensions.

If you could accept my idea, i can program it and send a pull request.

**Comment by psiinon** [comment]
Yes, I agree we should do this, and PRs very gratefully received :)

**Comment by jx6f** [comment]
Thanks!
I'll send PR later.

**Comment by psiinon** [comment]
Looking forward to it:)

**Comment by jx6f** [comment]
I have a question.

The return value of WebSocketObserver#onMessageFrame is "True for continuing to notify and **forwarding** message".
https://github.com/zaproxy/zap-extensions/blob/68b44ae8c694e4988aed51dc5febce3f878fc515/src/org/zaproxy/zap/extension/websocket/WebSocketObserver.java#L55

However, WebSocketProxy#sendAndNotify forwards any frames regardless to that.
https://github.com/zaproxy/zap-extensions/blob/68b44ae8c694e4988aed51dc5febce3f878fc515/src/org/zaproxy/zap/extension/websocket/WebSocketProxy.java#L771

It might have been implemented in the reverse order.

**Comment by jx6f** [comment]
I found that reason.

When i use websocket breakpoint and websocket manualsend feature at the same time, the manual sent frame will be breaked by websocket breakpoint.
It might not be a good behavior in many case.
To avoid this behavior, WebSocketProxy#sendAndNotify should to forward any frames regardless to the return value of WebSocketObserver#onMessageFrame.

Reffer to below:

The websocket breakpoint feature passes WebSocketProxy#processRead, it forwards messages after notifying.
https://github.com/zaproxy/zap-extensions/blob/68b44ae8c694e4988aed51dc5febce3f878fc515/src/org/zaproxy/zap/extension/websocket/WebSocketProxy.java#L528

The websocket manualsend feature passes WebSocketProxy#sendAndNotify, it forwards messages before notifying.
https://github.com/zaproxy/zap-extensions/blob/68b44ae8c694e4988aed51dc5febce3f878fc515/src/org/zaproxy/zap/extension/websocket/WebSocketProxy.java#L771

Thanks.
