### ISSUE TITLE
ZAP docker maintains previous session records.

### ISSUE THREAD

**Issue by gorivishal** [zaproxy/zaproxy#2969]
With ZAP docker the report which gets generated with every docker run, maintains the previous state/sessions of the docker unless the docker image is completely deleted and re-downloaded everytime. This results in report showing all the previously scanned information with old vulnerabilities as well instead of publishing new information with every docker run.

**Comment by kingthorin** [comment]
Are you starting a new ZAP session each time you use ZAP?

**Comment by gorivishal** [comment]
I figured it's an implementation issue on my part. My docker file uses `FROM owasp/zap2docker-weekly` which I run as `docker run -d --name authdynscan -p 127.0.0.1:8080:8080 -i gorivishal/authdynscan_zap /bin/bash -c "zap.sh -daemon -newsession ./ -host 0.0.0.0 -port 8080 -config api.disablekey=true; /zap/scan.sh http://10.168.54.151:8080/bodgeit/home.jsp"` with my customized authenticated scanning script.

scan.sh looks like this:
`
#!/bin/bash
python /zap/enable_session_handling.py
python /zap/selenium_scripts/CengageBrainUser1_v1.py
python /zap/ZAP_API_Auth_scan.py --targetURL $1 # --url $2 $3 $4
`

**Comment by kingthorin** [comment]
Hmmmm ok I see that you're using `-newsession` and passing `./` as the location. 

Could you be invoking ZAP before it is fully shutdown? (Perhaps you need to do something similar to https://github.com/zaproxy/community-scripts/pull/46)

Aside from that could you use a timestamp or something as the newsession location? (So that it's always different.) Or move/remove the session file after use?

**Comment by gorivishal** [comment]
This worked as I added an `rm -rf /root/.ZAP_D/session/.` before `zap.sh -daemon ...`

Thanks

**Comment by gorivishal** [comment]
I wish there was a force session overwrite capability though.

**Comment by gorivishal** [comment]
Figured zap was not going to background. Modified `docker run` command to below:
```
docker run  --name authdynscan -p 127.0.0.1:8080:8080 -i gorivishal/authdynscan_zap /bin/bash -c '(zap.sh -daemon -newsession ./ -host 0.0.0.0 -port 8080 -config api.disablekey=true) & echo "Giving 15 seconds for zap to load"; sleep 15; echo "Been sleeping for 15 seconds now" ; /zap/scan.sh http://10.168.54.151:8080/bodgeit/home.jsp'
```

I no longer need to `rm /path/old_session` now.

**Comment by thc202** [comment]
The behaviour that you described would be a bug, ZAP should exit if the session already exists.

Could you confirm the problem? Was the same ZAP instance being used multiple times? (Thus using the same session and leading to inclusion of "old" data in the report.)

Regarding https://github.com/zaproxy/zaproxy/issues/2969#issuecomment-258270449, it's possible to overwrite an existing session if the new session is created through the ZAP API (by setting the parameter overwrite to true). [1]

[1] https://github.com/zaproxy/zaproxy/wiki/ApiGen_core

**Comment by gorivishal** [comment]
The behaviour that you described would be a bug, ZAP should exit if the session already exists.
>> ZAP did exit, but previous session was still running. My authentication scripts used that one. See below logs:
```
root@170bcb00faf0:/zap/db# /bin/bash -c zap.sh -daemon -newsession ./test1 -host 0.0.0.0 -port 8080 -config api.disablekey=true; /zap/scan.sh http://10.168.54.151:8080/bodgeit/home.jsp
Found Java version 1.8.0_91
Available memory: 1999 MB
Setting jvm heap size: -Xmx512m
0 [main] INFO org.zaproxy.zap.GuiBootstrap  - OWASP ZAP D-2016-10-17 started.
5 [main] FATAL org.zaproxy.zap.GuiBootstrap  - ZAP GUI is not supported on a headless environment.
Run ZAP inline or in daemon mode, use -help command line argument for more details.
(Note, some of the ZAP features that require a display, for example, running AJAX Spider with Firefox, might still be run with the help of applications like Xvfb.)
ZAP GUI is not supported on a headless environment.
Run ZAP inline or in daemon mode, use -help command line argument for more details.
(Note, some of the ZAP features that require a display, for example, running AJAX Spider with Firefox, might still be run with the help of applications like Xvfb.)
Since no zap server information has been provided, checking if ZAP is running locally.
Found ZAP running on http://127.0.0.1:8080
Auto session handling enabled: OK
.
----------------------------------------------------------------------
Ran 1 test in 17.984s

OK
Context Name: 10.168.54.151:8080
ContextID: 4
Context - 10.168.54.151:8080set in scope: OK
Context includes: [http://10.168.54.151:8080/bodgeit/home.jsp.*, http://10.168.54.151:8080/bodgeit/home.jsp.*, http://10.168.54.151:8080/bodgeit/home.jsp.*]
Excluded - \Qlogout\E from spider: OK
Session method defined: OK
Crawling through. Spider ID: 2
Spider scan status: 100
List of URLs obtained by spider : 
Passive scanning complete
Actively Scanning target http://10.168.54.151:8080/bodgeit/home.jsp
Scan progress %: 0
Scan completed
```
My script scanned over the previous session.

---------------------

Regarding #2969 (comment), it's possible to overwrite an existing session if the new session is created through the ZAP API (by setting the parameter overwrite to true). [1]

[1] https://github.com/zaproxy/zaproxy/wiki/ApiGen_core
>> This is great! Thanks.

**Comment by thc202** [comment]
Thanks for letting us know!
