### ISSUE TITLE
Improve time-based Blind OS Command Injection payloads

### ISSUE THREAD

**Issue by jx6f** [zaproxy/zaproxy#2973]
The time-based Blind OS Command Injection payload for *NIX is ["sleep 5s"](https://github.com/zaproxy/zap-extensions/blob/68b44ae8c694e4988aed51dc5febce3f878fc515/src/org/zaproxy/zap/extension/ascanrules/CommandInjectionPlugin.java#L123).

Linux supports the suffix, "s" is recognized as seconds.
OSX just ignores the suffix.
BSD does not supports the suffix, it prints usage.
```sh
$ uname -a
FreeBSD freebsd 11.0-RELEASE-p1 FreeBSD 11.0-RELEASE-p1 #0 r306420: Thu Sep 29 01:43:23 UTC 2016     root@releng2.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64
$ sleep 5s
usage: sleep seconds
$ sleep 5
<5 seconds>
$ 
```

It is better to remove the suffix in order to support BSD.

**Comment by psiinon** [comment]
That sounds like a good approach

**Comment by jx6f** [comment]
Thanks!

**Comment by thc202** [comment]
Released in version 26 of Active scanner rules add-on (bundled in ZAP 2.6.0).
