### ISSUE TITLE
Update the version of jython library to 2.7.0 from 2.5.3

### ISSUE THREAD

**Issue by jx6f** [zaproxy/zaproxy#2978]
To get compatibility CPython 2.7, would you like to update it?

**Comment by thc202** [comment]
Yeah, that should be updated, we might want to wait for dependency management to not push another big binary to the repo.

**Comment by jx6f** [comment]
Are you talking about compatibility of community-scripts written in python?

**Comment by thc202** [comment]
Was referring to the size of the library, but not a big issue.

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#1021.
