### ISSUE TITLE
Data driven scripts?

### ISSUE THREAD

**Issue by javixeneize** [zaproxy/zaproxy#2985]
Hi

Is there any way to do data driven scripts in Zap?

I am testing an application that calls 2 webservices. The first one receives user and password and returns an authentication token. Second one, sends a set of data, plus the auth token generated in the previous step

Is there any way to map this token generated in the first request to the second one?

Thanks

**Comment by psiinon** [comment]
Hiya,

The answer is yes, but can you ask this on the ZAP User Group: https://groups.google.com/group/zaproxy-users
Thats a better forum for questions - we try to keep the Issues for problems or enhancement requests :)

Cheers,

Simon
