### ISSUE TITLE
Zap not detecting Bricks Login-1 SQL Injection Flaw

### ISSUE THREAD

**Issue by pedroo21** [zaproxy/zaproxy#2992]
Hello,

I tried running ZAP in login-1 test case of OWASP Bricks, what happens is ZAP doesn't alert a flaw in SQL Injection, as it should ('1 OR '1'='1)

![zap](https://cloud.githubusercontent.com/assets/12183954/20147719/2da34b4a-a6a1-11e6-9644-cea329a02687.png)

I also tried to check if zap was doing sql injection coverage, and reports seem fine.

![zap2](https://cloud.githubusercontent.com/assets/12183954/20147764/5b2eddea-a6a1-11e6-9db1-5af38a6983ff.png)

Is this an issue or Where am I failing?

**Comment by kingthorin** [comment]
Since this is also cross posted to the User Group (https://groups.google.com/forum/#!topic/zaproxy-users/W6n7YZl5pUM) I'm going to close this ticket, it can be re-opened or another opened if an actual issue is identified.
