### ISSUE TITLE
session ID in URL rule doesn't work for ;jsessionid=## in URL

### ISSUE THREAD

**Issue by davewichers** [zaproxy/zaproxy#3008]
The current rule, whose code looks to be at: https://github.com/zaproxy/zap-extensions/blob/master/src/org/zaproxy/zap/extension/pscanrules/TestInfoSessionIdURL.java assumes the session ID is the name of a parameter.

However, sometimes sites include it like this: http://site.com/dir/page;jsessionid=SOME#

An example of a real bank doing it like this is discussed here: http://stackoverflow.com/questions/27499977/harm-of-passing-session-id-as-url-parameter

When I replaced the ; with a ? and tested ZAP, the rule detected it immediately.

Can this rule be enhanced to handle session IDs included in URLs this way?

**Comment by kingthorin** [comment]
Should be doable.

Either by looking for the known tokens as part of the uri, or by enhancing the URL parser to handle sub-delimiters other than &.

https://tools.ietf.org/html/rfc3986#section-2.2

**Comment by psiinon** [comment]
This should be implemented in the Context Structure. We already allow users to change the key value pair separators (default '&') and the key value separators (default '=') - we should add an option to specify the 'URL Parameter Separators' (name ok?)

**Comment by davewichers** [comment]
Hold on. For the app I'm testing, they are using the ;sessionid=whatever as
a separator before the ? and they use normal & to separate parameter values
after the ?. So in this case, they are using both, not one or the other.

If I switched ZAP to think that the ; was a parameter separator for this,
it would stop recognizing the primary use of &. And the ; is before the ?
anyway, so not sure it would even work.

-Dave

**Comment by psiinon** [comment]
The way the code _should_ work is to allow any of the specified characters to be separators, so it should work correctly for you (if we supported the parameter separators;)

**Comment by davewichers** [comment]
OK. Even if the ;sessionid=SOMEVALUE    is   BEFORE the   ?         ?????
I'd write a unit test using the exact URL I provided in my bug report to
make sure it works :-)   And a bunch of other variants of course ....

**Comment by thc202** [comment]
Released in version 23 of Passive scanner rules add-on.

**Comment by JavanXD** [comment]
### Can someone help me teaching ZAP to recognize the jsessionid from the URL?

In my case i have a application with the following URL: 
`htps://example.org/welcome.faces;jsessionid=whatever?foo=bar&bar=foo`
You said that this would work in version 23 of Passive scanner rules add-on. But I don't get it to work.

I already tried following setting: ![hvxsbo4tav](https://user-images.githubusercontent.com/4342160/51835450-b9c0c780-22fd-11e9-81cb-13dd5ecf8797.png)
But i don't know the correct syntax for these structure input fields. Maybe an example would be helpful [here](https://github.com/zaproxy/zap-core-help/wiki/HelpStartConceptsStructparams).

Applications that read the jsessionid from the URL have neither a cookie based session management nor an HTTP header based. So what do I select here? 
![javaw_tt6wmfcdv2](https://user-images.githubusercontent.com/4342160/51836037-71a2a480-22ff-11e9-9905-2051c5b33b17.png)


![javaw_xlndbkpmco](https://user-images.githubusercontent.com/4342160/51836128-bdede480-22ff-11e9-8f4c-68ce3c8ebca4.png)

The _form based authentication_ works. I also wrote a _ZEST script_, which also performs the login. However, in both cases the **jsessionid from the URL is not recognized** as login SESSION. So in attack mode everything is tested in logged out state, although **forced user mode is** activated. The login attempts are successful but the tests are still executed with an invalid jsessionid. No session was entered in the **HTTP Sessions** tab.

**Comment by JavanXD** [comment]
I took a look into [the code](https://github.com/zaproxy/zap-extensions/commit/808e5ea94ea160597c2e68b6e7a22d69d8d1a759) and found the issue in the used regex.
See [this example](http://regexr.com/477ut) why the zap regex does not work. The jsessionid in the application i am testing contains chars like "-", "_" and "!".

**Comment by JavanXD** [comment]
Now that I have invested some time in it, I have come up with an acceptable solution. Nevertheless with some open question marks.

The **passive scanner rule** recognizes jsessionids in the URL. But this has nothing to do with **session management**. The extension _HTTP Sessions_ does not recognize jsessionid in the URL.

So my _Zest script_ and everything around it is unnecessary. I have simply written myself a remedy with the **Replacer**. The Replacer replaces the old jsessionids from the recording with a current, valid sessionid. This has to be maintained manually. My setting:
![javaw_hrwgrkjbaa](https://user-images.githubusercontent.com/4342160/51849673-83e10a80-2320-11e9-8b15-591abd17363f.png)
