### ISSUE TITLE
ZAP Error [java.net.UnknownHostException]: Loacal host

### ISSUE THREAD

**Issue by nivedhamurthy** [zaproxy/zaproxy#3014]
i getting this error when i start to attack the application.kindly provide me a solution for this.

**Comment by psiinon** [comment]
What URL are you specifying?
Can you connect to that URL directly from your browser?
Theres a typo in the issue you raised - I'm guessing it should be 'localhost' - could this be the problem?

**Comment by nivedhamurthy** [comment]
ZAP Error [java.net.UnknownHostException]: Loacal host

Stack Trace:
java.net.UnknownHostException: Loacal host
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:286)

**Comment by nivedhamurthy** [comment]
i getting this error when i try to attack the application.same as like in zap tool also,getting bad gateway error

**Comment by nivedhamurthy** [comment]
HTTP/1.1 502 Bad Gateway
Content-Length: 1826
Content-Type: text/plain; charset=UTF-8

**Comment by nivedhamurthy** [comment]
can you please resolve this error.

**Comment by nivedhamurthy** [comment]
i facing this error in mozilla firefox browser

**Comment by kingthorin** [comment]
What URL are you specifying?
Can you connect to that URL directly from your browser?
Theres a typo in the issue you raised - I'm guessing it should be 'localhost' - could this be the problem?

**Comment by thc202** [comment]
@nivedhamurthy could you provide answers to the previous questions?

**Comment by thc202** [comment]
Closing, insufficient information provided to help address the issue.

**Comment by webduniaKunal** [comment]
i need help in this same issue .. i get HTTP/1.1 502 Bad Gateway in owasp zap tool, please help me

**Comment by psiinon** [comment]
@webduniaKunal Please do not ask questions on closed issues. Use the ZAP User Group instead: https://groups.google.com/group/zaproxy-users
You will also need to provide us with more information about what you are doing.

**Comment by webduniaKunal** [comment]
i need help in this same issue .. i get HTTP/1.1 502 Bad Gateway in owasp zap tool, please help me
![img](https://cloud.githubusercontent.com/assets/25813250/23021469/2551d2ee-f472-11e6-89cc-28d065694295.png)

**Comment by psiinon** [comment]
@webduniaKunal Ask support questions on the ZAP User Group https://groups.google.com/group/zaproxy-users
If you post again to a closed issue like this one then you will be blocked.
This is your one and only warning.

**Comment by webduniaKunal** [comment]
thanks Simon i get solution of my question by URL

**Comment by webduniaKunal** [comment]
Hello Simon

can you please tell me how to setup burp in Kali Linux

**Comment by psiinon** [comment]
@webduniaKunal So what part of "If you post again to a closed issue like this one then you will be blocked. This is your one and only warning." did you not understand?
You are now blocked from the zaproxy repos.
You can still post to the ZAP User and Developer groups.
