### ISSUE TITLE
Example for authentication with Federated Authentication

### ISSUE THREAD

**Issue by eL-Prova** [zaproxy/zaproxy#3019]
Hi all,

We have an application using Federated Authentication.
I created a script with Zest Script but it is not fully generic.
Is it possible to easy scan a site using Fed Auth?
Are there some tutorials available?

Kind regards

**Comment by psiinon** [comment]
Please ask questions on the ZAP User Group: https://groups.google.com/group/zaproxy-users
Thanks :)

**Comment by eL-Prova** [comment]
@psiinon srry I will :)

**Comment by psiinon** [comment]
No problem ;)

**Comment by thc202** [comment]
User Group thread at https://groups.google.com/d/topic/zaproxy-users/yii7xV4ucgI/discussion
