### ISSUE TITLE
Implement SSRF detection service

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#3022]
https://ssrfdetector.com/ is an online service for detecting Server Side Request Forgery vulnerabilities (SSRF).
It is developed and maintained by Jake Reynolds and is open source https://github.com/jacobreynolds/ssrfdetector

Currently ZAP does not detect SSRF vulnerabilities, due to the lack of this sort of service.

**Comment by psiinon** [comment]
SSRF bible: https://docs.google.com/document/d/1v1TkWZtrhzRLy0bYXBcdLUedXGb9njTNIJXa3u9akHM/edit

**Comment by rnehra01** [comment]
@psiinon Implementing this requires us to own a domain so that we can inject that in parameters and if server visits that URL, we get the request in the log. So how do you want to proceed? So either ZAP or the user should have a domain which can be used.

**Comment by psiinon** [comment]
@rnehra01 To start with we can depend on the user to set one up - they will then need to be able to configure ZAP with the relevant host name or IP address.

**Comment by kingthorin** [comment]
https://medium.com/@auxy233/the-design-and-implementation-of-ssrf-attack-framework-550e9fda16ea

**Comment by kingthorin** [comment]
https://medium.com/bugbountywriteup/the-design-and-implementation-of-ssrf-attack-framework-550e9fda16ea

**Comment by albvt** [comment]
yeah guys lets build one!!!better we get zap a domain for beginners case but anyway

**Comment by psiinon** [comment]
@albvt is this something you fancy working on? All help appreciated :)

**Comment by pwned-17** [comment]
Greetings, I am interested in working on this issue, as it seems to interest me but I  need some help figuring out the skills sets required to work on this issue. It would be really helpful if someone can help me figure this out :)

**Comment by psiinon** [comment]
Hi @pwned-17 :) As you may know this has been proposed as a GSoC 2020 project: https://owasp.org/www-community/initiatives/gsoc/gsoc2020ideas
As https://ssrfdetector.com/ is now abandoned this project will require you to create a web service that can:

- accept arbitrary requests
- record requests of a specific format in a db
- provide API access to those requests

The service should use unique tokens so that is can be made available online and safely shared between as many people who want to use it. It should not be realistically possible for one user to access another users data.
We'd like to set this service up online but it should also be straight forward for people to set up their own instances.
Once such a service is available then we would want the existing ZAP scan rules which detect SSRF to be changed to use this service, and potentially new ones to be created.
This may sound like a lot, but it definitely feasible for GSoC or a student project.
We can help with the design of the system, and there are plenty of frameworks which could provide the web services and db integration.

**Comment by pwned-17** [comment]
Thank you @psiinon  . I'll start ideating and try to come with an implementation .I would also like to know about the tech stack which we can use to implement this kind of feature .

**Comment by psiinon** [comment]
The SSRF service will be standalone so in theory could be implemented in any tech stack.
However ... the ZAP core team is most familiar with java, so would be able to provide more guidance if thats used. Its not a particularly complicated service so the simpler and more 'standard' a stack the better. 
Also this is something that we'd want maintained going forwards. You may not want to maintain this for years, so choosing a standard java stack would make it much more likely that the ZAP core team could maintain it without too much extra effort. If you did develop it and want to continue maintaining it then that would of course be great :)

**Comment by marcoagner** [comment]
Any moves on this? I'd love to see this on ZAP and I can write the server (not for gsoc as I'm not a student).
Go (lang) would be my first choice just because I'd be able to move faster from the beginning (than with java) and the tool serves the purpose, but I'm just being practical and have no deep feelings here.
In any case, I don't think the language choice will matter too much in the long run as what I'd really like to achieve together with your valuable input is to document a specification that could serve as a standard for anybody willing to write their own servers to use them with ZAP and whatnot. Thus, if we can agree on this, defining the interface exposed by the server would be the most important part so others could be free to write their own servers if they want or need for, who knows, some very specific case.
Of course, I see the value and need of having a reference server that is actively maintained and would fancy aiming for this as well as maintaining it, but maybe here's where the language choice may play a bigger role inside the ZAP core team's preferences.
Anyway, am I missing something? :)

**Comment by psiinon** [comment]
@marcoagner As far as I know, no one is working on this right now, and like you I'd love to see it happen :)
And I agree with your reasoning - an actively maintained service is the key thing, not the language.
So yes, defining the interface is key - do you fancy having an initial stab at this?

**Comment by marcoagner** [comment]
@psiinon Yes, let's go.
To begin, I think it may be a good idea that I write a high-level document containing at least the basic requirements and specs we should have for the server. I'll just come back with an uploaded markdown file containing an overview of the expected user/client interaction, architecture to make it happen, formulate any questions I may have for anyone wishing to answer them, and anything related that I think in the process. In case it's not clear, it'll be nothing too fancy as I don't intend to complicate an initial doc for a mostly straightforward server (may the devil lie in the details :stuck_out_tongue_closed_eyes:). With this, it'll be easier to gather everybody's reviews and ideas. Please, feel free to send me references or anything you think may help me with this step. Hopefully, that makes sense.

**Comment by marcoagner** [comment]
By the way, for the record, I've checked all the links posted on this issue and the Medium article linked by @kingthorin is now deleted on both so I found an archived version: http://archive.is/CbP5D. It's a good reference.

**Comment by marcoagner** [comment]
So here's the document with a high-level overview for the possible implementation: https://github.com/marcoagner/oast-server/blob/master/oast-server-overview.adoc. There's no need to despair as it's around 2,000 words only (well, it could be worse). But, if in a hurry, just search case-sensitive for "Questions" and start from there. Though, my biggest concerns are related to the practicality of running an instance of this server as a public instance while thwarting resource abuses and securely storing (or not storing at all) details about the triggered "OAST reactions".

I'm not in a hurry so, please, take your times. I was eventually going to code something similar anyway, but it'll be a huge pleasure if I can help integrating something similar to ZAP so your inputs are very important.

**Comment by psiinon** [comment]
This is great - will go through it and give feedback asap. Suggestion - post this to the ZAP Dev Group too?
Have you tweeted about it yet? Will retweet or send one out if you dont want to...

**Comment by psiinon** [comment]
Oh, and whats your prefered form of feedback? Email, issues on that repo, ...?

**Comment by psiinon** [comment]
@marcoagner just found https://github.com/jdonsec/AllThingsSSRF :)

**Comment by marcoagner** [comment]
@psiinon
> post this to the ZAP Dev Group too?

Oh, sure! I will do.

> Have you tweeted about it yet? Will retweet or send one out if you dont want to...

No, I haven't. But feel free to do it if you think the document is okay enough for that atm. :D
_Kind of off-topic: I deactivated my account to take a Twitter break and, even though I don't think my time had run out, it was deleted. :laughing: I got the same handle back, but it's now zeroed and I'm not so exactly active yet._

> Oh, and whats your prefered form of feedback? Email, issues on that repo, ...?

Oh, well, I should have added this information. But whatever works best for everyone. I guess issues on that repo works well so we don't get too cluttered and out of context here, but e-mail is also fine. I will update the document with the information routing feedbacks to issues and the ZAP Dev Group thread.

> just found https://github.com/jdonsec/AllThingsSSRF :)

That repo seems packed with juicy links. I will definitely check whatever pops my interest there.

**Comment by marcoagner** [comment]
I created the topic on ZAP Dev Group: https://groups.google.com/forum/#!topic/zaproxy-develop/527gUb12En0
I also added the prefered feedback channels and fixed some small stuff that I spotted while skimming the document; just check the commit messages if in doubt.

**Comment by marcoagner** [comment]
Hi all, I finally have some updates and a running test instance.
I will just paste what I've just posted on the ZAP Dev Group [here](https://groups.google.com/g/zaproxy-develop/c/527gUb12En0/m/JxvL3fPTAwAJ) so anybody interested and not there can see it.

> Hi all,
> 
> I've released the code for the server proposed in this thread.
> It is here as BOAST: https://github.com/marcoagner/boast
> 
> The draft (https://github.com/marcoagner/oastserver-draft) has been superseded by the implementation, but may still be useful for anyone who wants to grasp the high-level view about some details while the documentation is still lacking.
> 
> Atm, the most interesting parts to have a look first are the "deploying" (https://github.com/marcoagner/boast/blob/master/docs/deploying.md) and "interacting" (https://github.com/marcoagner/boast/blob/master/docs/interacting.md) docs. Deploying needs some love for better reproducibility and any feedbacks on this are very welcome.
> 
> A (very) test instance of BOAST is running on http://odiss.eu.
> I say "(very)" because it's running in a very cheap/weak server, with relaxed use limits, and no extra network-level protection between clients and the server.
> And since the server itself does not deal with authentication (only authorization), there are more than zero ways to partially disrupt service for other users.
> I'm yet to write the doc on potential disruption vectors and mitigations. This is only a concern for a public unauthenticated/unrestricted instance like this one, but I wanted to see how it reacts without much extra protection and generous limits. At the moment, I'm more interested in seeing if it crashes - which it should not.
> 
> Anyway, you can use the "interacting" doc linked above and this bash script (https://github.com/marcoagner/boast/blob/master/examples/bash_client/client.sh [just change the host and secret; port is the same]) to learn how to interact with the server. Feel free to check it out, break it, but DO NOT USE IT FOR ANY SERIOUS PURPOSES for now.
> It will be restarted often and every user data in the server is ephemeral. But, if not restarted, the TTL for any data on the server is 12 hours.
> 
> Other useful information about this running test instance...
> API port: 1337.
> DNS protocol receiver port: 53.
> HTTP protocol receiver ports: 80, 8080.
> HTTPS protocol receiver ports: 443, 8443.
> Status page (maybe in need of more stats, but you can already comfortably monitor how much damage you're doing): https://odiss.eu:1337/rzaedgmqloivvw7v3lamu3tzvi
> 
> Again, DO NOT USE THIS INSTANCE FOR ANY SERIOUS PURPOSE, but feel free to test and break it.
> General feedbacks or "damage reports" are welcome.
> 
> Marco

**Comment by ricekot** [comment]
Can we close this issue?

**Comment by kingthorin** [comment]
Implemented in the OAST add-on, thanks @ricekot !!
