### ISSUE TITLE
Support java as a scripting language

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#3024]
It would be very useful to support Java in addition to the JSR223 scripting languages within the ZAP script console'

It should be possible to provide much better auto complete support than will be possible with dynamically typed scripting languages.

**Comment by kingthorin** [comment]
Duplicate? https://github.com/zaproxy/zaproxy/issues/1516

**Comment by psiinon** [comment]
Arg, failed to find that one ;)
