### ISSUE TITLE
Context Alert Filter Enhancement Request

### ISSUE THREAD

**Issue by JordanGS** [zaproxy/zaproxy#3027]
[Wiki Support](https://github.com/zaproxy/zap-extensions/wiki/HelpAddonsAlertFiltersAlertFilter)

Current workflow is:

Add your application to a context
Open the Session Properties dialog (eg by double clicking on the context)
Select the contexts' 'Alert filters' panel
Click 'Add' and fill in the details for each alert you want to override

1. When following the regular workflow a new window called **Add Alert Filter** pops up, this window has focus and i am unable to give focus to session properties ot the main ZAP UI. I want to switch between the two windows so that i can copy + paste the URL values and the Parameter values.

2. Right Click on an Alert(URL) and have an option that says **Create new filter** which will ask you to pick a context from a list of already existing contexts. Then will directly add it to the list, not even opening the **Add Alert Filter** pop-up menu. If the user wants to change it to a regex, they can go to session properties.

3. After adding the filter, add option to apply it to current alerts and not only new alerts.

4. Currently all the alert filters can be exported along with the context. For integration with the zap-plugin (jenkins), i would not want the user to go to the UI to create a context and then add all the filters. Then go to jenkins zap-plugin ui and recreate the context and then import the context file just for the alert filters. Would be nice if they can export a filter list. Allow to export/import the filter rules more easily.

5. Similar to how you can select a policy. Be able to select a pre-defined filter list and also be able to export it just as you would a policy file (goes in line with 4).

**Comment by JordanGS** [comment]
@thc202 @psiinon Can we discuss this ticket and add it to the 2.7 milestone? We don't have to address all the point, some go into usability.

**Comment by thc202** [comment]
Definitely, although this does not need to be tied to a core release (we can add it as a reminder anyway), we can release the add-on any time.

**Comment by JordanGS** [comment]
@thc202 Out of that list, as per IRC

from a jenkins point of view, it's really inconvenient to have to load the full session to get the filters. Rather than specifying them like you would a policy file. So if alert filters could function more like policy files do. You can create filter files, export them as xml, import them, etc that would be ideal i think. Thoughts?

**Comment by thc202** [comment]
There's no reason to not support that.

**Comment by psiinon** [comment]
+1 for supporting these in addition to the current functionality.

**Comment by JordanGS** [comment]
@thc202 

Per IRC discussion. It would be good to be able to support the import/export of alert filter files but it would also be good to be able to allow users to add one or more override filters. Since this is done on the Job Config Page, i would need access to a publically accessible list of Alerts and their associated codes so that i can populate the drop down list. Is this information available anywhere outside of the API?

**Comment by kingthorin** [comment]
Is this what you're looking for?
https://github.com/zaproxy/zaproxy/blob/develop/src/doc/scanners.md

**Comment by JordanGS** [comment]
@kingthorin yes and no, seems like that is the full list. I need the one being used by Alert Filters. So i was wondering where that was, was it accessible outside of the API?

Also the list you linked, is that updated the moment that one of those numbers changes or something is added/deprecated?

**Comment by thc202** [comment]
That's the closest to what the Alert Filters add-on uses, the add-on obtains the names/IDs directly from the scanners at runtime. We could generate a XML(?) file with that info (which would contain the same info as scanners.md, except for the deprecated scanners/IDs).

Yes, that file is kept up-to-date.
