### ISSUE TITLE
URL not found in scan tree

### ISSUE THREAD

**Issue by ghouspasha** [zaproxy/zaproxy#3036]
I have zaproxy tool code and an client api code. I have started zap tool in daemon mode and then started client. Spidering is successful but Active Scan is not working, i am getting below exception

2344573 [ZAP-ProxyThread-19] WARN org.zaproxy.zap.extension.api.API  - ApiException while handling API request:
URL Not Found in the Scan Tree (url_not_found)
	at org.zaproxy.zap.extension.ascan.ActiveScanAPI.scanURL(ActiveScanAPI.java:535)
	at org.zaproxy.zap.extension.ascan.ActiveScanAPI.handleApiAction(ActiveScanAPI.java:240)
	at org.zaproxy.zap.extension.api.API.handleApiRequest(API.java:350)
	at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(ProxyThread.java:358)
	at org.parosproxy.paros.core.proxy.ProxyThread.run(ProxyThread.java:249)
	at java.lang.Thread.run(Thread.java:745)
2346536 [ZAP-SpiderThreadPool-2-thread-1] INFO org.zaproxy.zap.spider.Spider  - Spidering process is complete. Shutting down...

**Comment by thc202** [comment]
That error means that the URL provided to the active scan is not known by ZAP (i.e. it was not found in the Sites tree) thus it's not able to active scan it.

Was the URL that you are providing accessed by ZAP before starting the active scan?

For questions about ZAP and ZAP API usage it's better to use the [User Group](https://groups.google.com/group/zaproxy-users).

**Comment by ghouspasha** [comment]
oh do i need to register URL's before using this ZAP tool ?
and where can i add these urls?
I want ZAP to run in daemon mode only.

**Comment by thc202** [comment]
You just need to access the URL(s) by/through ZAP (e.g. proxy the request(s), use the spiders) before starting the active scan.
It's the same process whether ZAP is in daemon mode or using the GUI.

I notice that in the output provided the active scan was started before the spider has finished, it's better to wait for the spider before starting the active scan (so that all URLs are active scanned).

**Comment by thc202** [comment]
@ghouspasha any other question?

**Comment by thc202** [comment]
Closing, all questions seem to be answered. Any other question, please, let us know through the [User Group](https://groups.google.com/group/zaproxy-users). Thank you.

**Comment by binarymist** [comment]
What if the URL is known (clearly visible in the web UI: JSON/spider/view/allUrls) and we get this error? Well to be specific:
          Error occured while attempting to initiate active scan. Error was: 400 - {"code":"url_not_found","message":"URL Not Found in the Scan Tree"}
          400 - {"code":"url_not_found","message":"URL Not Found in the Scan Tree"}

**Comment by thc202** [comment]
Which ZAP version is being used? A URL with different method/post data than the one specified would also cause that.

**Comment by binarymist** [comment]
Weekly.
Yeah, it's post, I've checked.

**Comment by thc202** [comment]
Does the post data also match? What's the Content-Type?

For which API endpoint? `/core/view/urls/` should return all (e.g. proxied/spidered/forced browse...).

**Comment by binarymist** [comment]
Sorry actually currently I'm using the stable docker image. The route is also visible in the `/core/view/urls/` too. Not sure what the post data looks like (it's being driven from Selenium).

**Comment by binarymist** [comment]
I was populating a couple of hidden fields with empty strings as part of my code that was driving selenium webdriver, when the ascan ran with the query string I proivided it, I guess it looked a bit different (no empty strings), although other than that, that fields and their values were identicle. So working now.
