### ISSUE TITLE
False positive for remote command execution

### ISSUE THREAD

**Issue by bvdwiel** [zaproxy/zaproxy#3037]
ZAP 2.5.0 against a vanilla installation of TYPO3 8.4.1 (current) appears to register an OS command injection. I strongly suspect this to be a false positive but I can't prove it. This is the URL:

https://new.area536.com/typo3/?loginProvider=1433416747

Apparently it's possible to inject a sleep command into the loginRefresh parameter, but that's not something I can verify at all. I therefore suspect a false positive.

**Comment by kingthorin** [comment]
Why can't you verify it? is the response delayed or not?

**Comment by bvdwiel** [comment]
I get a response but nothing in it indicates any kind of injection. Also, injecting a different command (logger) that would leave a trace on the server actually doesn't.

**Comment by bvdwiel** [comment]
To clarify, the response looks like one I would expect from the app: a fully formed HTML page, status 200.

**Comment by thc202** [comment]
The issue can be reproduced with a page that simply sleeps with a value higher that the value injected (based on behaviour from [1]).

[1] http://cms-next.demo.typo3.org/typo3/

**Comment by thc202** [comment]
Merging into #2588.
