### ISSUE TITLE
Export param tab contents

### ISSUE THREAD

**Issue by jimweiler** [zaproxy/zaproxy#3040]
It would be really useful to be able to export a selected subset or all the contents of the **params** tab in csv format. You could compare parameter sets and values between site versions, user actions or navigation paths.

**Comment by kingthorin** [comment]
Good news and bad news:

1. Good news: you can copy/paste from the table to Excel.
2. Bad news: it seems that currently you can only select a single row.

**Comment by thc202** [comment]
Opened a pull request (#3042) to allow to select more than one parameter (row).
