### ISSUE TITLE
False positive on source disclosure when target answers invalid url with 200 OK

### ISSUE THREAD

**Issue by glestel** [zaproxy/zaproxy#3048]
Hello,

While active scanning against a target that works as a search engine, the Source Code Divulgation - WEB-INF Folder is seeing false positive everywhere because the target answers to every invalid URL with a `200 OK` and the content of the home page. I know it's not a good behaviour but it's generating false positives in the report.
It's happening with ZAP 2.5.0 and ZAP Weekly.
This might be linked to https://github.com/zaproxy/zaproxy/issues/9

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#653.
