### ISSUE TITLE
bad fonts no antialiasin...

### ISSUE THREAD

**Issue by ChrisFernandez** [zaproxy/zaproxy#3051]
I been using Zap on BlackArch GNU/Linux and the fonts always render very ugly and with out anti aliasing... in ubuntu they seem correct...
![owasp-zap-font](https://cloud.githubusercontent.com/assets/5316229/20915010/1d9be170-bb38-11e6-92f1-63c46a0cccd5.png)

**Comment by ChrisFernandez** [comment]
bump!

**Comment by thc202** [comment]
What JRE are you using? There's a command line flag to tweak the anti-aliasing [1], maybe that helps? It can also be set through the ZAP options. [2]

[1] https://docs.oracle.com/javase/8/docs/technotes/guides/2d/flags.html#aaFonts
[2] https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsOptionsJvm

**Comment by ChrisFernandez** [comment]
@thc202 thanks I will check that as soon I get home and report back.. hopefully thats the solution... I am a strong OWASP and open source advocate so always talking good things about ZAP, the last thing I want is see it look with this fonts.. :)

**Comment by ChrisFernandez** [comment]
Hello, I just check the zap.log and I saw this.. is prob related.
```
zap.log.1:2016-09-27 00:05:29,015 [Thread-21] WARN  DefaultCssErrorHandler - CSS error: 'http://fonts.googleapis.com/css?family=Open+Sans' [1:1] Error in style sheet. (Invalid token "(". Was expecting one of: <EOF>, <S>, <IDENT>, "<!--", "-->", ".", ":", "*", "[", <HASH>, <IMPORT_SYM>, <PAGE_SYM>, <MEDIA_SYM>, <FONT_FACE_SYM>, <CHARSET_SYM>, <ATKEYWORD>.)
zap.log.1:2016-09-27 00:05:31,561 [pool-4-thread-2] WARN  DefaultCssErrorHandler - CSS error: 'http://fonts.googleapis.com/css?family=Open+Sans' [1:1] Error in style sheet. (Invalid token "(". Was expecting one of: <EOF>, <S>, <IDENT>, "<!--", "-->", ".", ":", "*", "[", <HASH>, <IMPORT_SYM>, <PAGE_SYM>, <MEDIA_SYM>, <FONT_FACE_SYM>, <CHARSET_SYM>, <ATKEYWORD>.)
zap.log.1:2016-09-27 00:05:32,001 [pool-4-thread-3] WARN  DefaultCssErrorHandler - CSS error: 'http://fonts.googleapis.com/css?family=Open+Sans' [1:1] Error in style sheet. (Invalid token "(". Was expecting one of: <EOF>, <S>, <IDENT>, "<!--", "-->", ".", ":", "*", "[", <HASH>, <IMPORT_SYM>, <PAGE_SYM>, <MEDIA_SYM>, <FONT_FACE_SYM>, <CHARSET_SYM>, <ATKEYWORD>.)
zap.log.1:2016-09-27 00:05:32,146 [pool-4-thread-5] WARN  DefaultCssErrorHandler - CSS error: 'http://fonts.googleapis.com/css?family=Open+Sans' [1:1] Error in style sheet. (Invalid token "(". Was expecting one of: <EOF>, <S>, <IDENT>, "<!--", "-->", ".", ":", "*", "[", <HASH>, <IMPORT_SYM>, <PAGE_SYM>, <MEDIA_SYM>, <FONT_FACE_SYM>, <CHARSET_SYM>, <ATKEYWORD>.)
zap.log.1:2016-09-27 00:05:32,183 [pool-4-thread-4] WARN  DefaultCssErrorHandler - CSS error: 'http://fonts.googleapis.com/css?family=Open+Sans' [1:1] Error in style sheet. (Invalid token "(". Was expecting one of: <EOF>, <S>, <IDENT>, "<!--", "-->", ".", ":", "*", "[", <HASH>, <IMPORT_SYM>, <PAGE_SYM>, <MEDIA_SYM>, <FONT_FACE_SYM>, <CHARSET_SYM>, <ATKEYWORD>.)
zap.log.1:2016-09-27 00:05:34,042 [pool-4-thread-2] WARN  DefaultCssErrorHandler - CSS error: 'http://fonts.googleapis.com/css?family=Open+Sans' [1:1] Error in style sheet. (Invalid token "(". Was expecting one of: <EOF>, <S>, <IDENT>, "<!--", "-->", ".", ":", "*", "[", <HASH>, <IMPORT_SYM>, <PAGE_SYM>, <MEDIA_SYM>, <FONT_FACE_SYM>, <CHARSET_SYM>, <ATKEYWORD>.)
```

**Comment by ChrisFernandez** [comment]
ok is a bit better now.. I added this to the java opts
`-Dawt.useSystemAAFontSettings=on`
Any other tips? thanks

**Comment by kingthorin** [comment]
Could we get an updated screenshot?

**Comment by ChrisFernandez** [comment]
hey, one sec, I notice if I run it from the bash command line then is fine.. if I run it from a plasma/kde button in the panel then is when is missing the font/aliasing, trying to research why.

**Comment by ChrisFernandez** [comment]
I am still having this issue when I run it using the wrapper... ... very weird.

**Comment by kingthorin** [comment]
You can report issues re: BlackArch Linux over here: https://github.com/BlackArch/blackarch/issues

**Comment by kingthorin** [comment]
@chrisfernandez did you open a ticket for BlackArch?

**Comment by ChrisFernandez** [comment]
Not yet :) got busy but I should... if I remember I will as soon I get home from work.

**Comment by ChrisFernandez** [comment]
https://github.com/BlackArch/blackarch/issues/1698

**Comment by thc202** [comment]
Thanks!

**Comment by ChrisFernandez** [comment]
@thc202 turns out they pick up from upstream I have open a bug here:
https://bugs.archlinux.org/task/54551
but honestly I doub they will do anything about it.. :(

**Comment by kingthorin** [comment]
Sadly the Blacker h team closed their ticket without any further a tion, simply blaming a supposed config issue. There is nothing further that can be done if they won't investigate the discrepancy.

**Comment by ChrisFernandez** [comment]
@kingthorin I actually found a work around finally. I added this on arch/blackarch on /etc/enviroment
```
_JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on'
JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on'
JAVA_FONTS=/usr/share/fonts/TTF
```
and restarted now the fonts are "normal" finally!

**Comment by kingthorin** [comment]
@ChrisFernandez thanks for letting us know. I'll build an FAQ we can re-use for issues like this and include that as content.

**Comment by psiinon** [comment]
Nice! If we can be sure that we can detect the relevant environments then we could actually include these changes in the zap.sh script.
