### ISSUE TITLE
False positives with Integer Overflow scanner and 500 error responses

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#3064]
Steps to reproduce the issue:
1. Run ZAP with add-on "Active scanner rules (beta)" installed;
2. Access a page that returns always a 500 error;
3. Scan the page with "Integer Overflow Error" scanner;
4. Note that it raises an alert.

Add-on:
Active scanner rules (beta) version 21.

**Comment by kingthorin** [comment]
If it always returns 500 it shouldn't be scanned: https://github.com/zaproxy/zap-extensions/blob/beta/src/org/zaproxy/zap/extension/ascanrulesBeta/IntegerOverflow.java#L111

**Comment by thc202** [comment]
Right.

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#657.
