### ISSUE TITLE
Ensure Active Scanners perform initial checks against base message

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#3065]
Per: https://github.com/zaproxy/zaproxy/issues/3064 review all active scanners to ensure they're not generating False Negatives or False Positives

- [x] Release (https://github.com/zaproxy/zap-extensions/issues/658)
- [x] Beta (None of the Beta quality scanners seem to be impacted by this issue)
- [x] Alpha (None of the Alpha quality scanners seem to be impacted by this issue)

**Comment by thc202** [comment]
Thanks for taking a look at this!

**Comment by thc202** [comment]
Released in version 26 of Active scanner rules add-on (bundled in ZAP 2.6.0).
