### ISSUE TITLE
Spidering options in the doc in two place

### ISSUE THREAD

**Issue by glestel** [zaproxy/zaproxy#3066]
While reading the doc about spidering options, I've noticed that the `Maximum children to crawl` info is all alone on the page [HelpUiDialogsSpider](https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsSpider) while other options are listed at [HelpUiDialogsOptionsSpider](https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsOptionsSpider)

**Comment by thc202** [comment]
From talks in IRC channel, that option should probably be added to Spider options panel (and help moved accordingly).

**Comment by glestel** [comment]
In fact, the option is available only on the advanced options panel as most of the others options
