### ISSUE TITLE
Context structural parameter only accepts alphanumeric charts

### ISSUE THREAD

**Issue by martinkalina** [zaproxy/zaproxy#3069]
Hi, we try to use ZAP for scan of Spring Webflow based application deployed on Liferay. The URL parameter that determines the flow id and position contains underscores, and it cant be added as Structural Parameter in ContextStructurePanel.
Is there any reason to validate parameters on alphanum chars and do not allow e.g. underscores?

**Comment by psiinon** [comment]
There are some non alphanum chars that could cause us problems, but I cant think of any reason not to support underscores.

**Comment by martinkalina** [comment]
ok, let me fix that. I will make a PR soon
