### ISSUE TITLE
Active scan pre request scripts/requests

### ISSUE THREAD

**Issue by npavicevic** [zaproxy/zaproxy#3072]
Hello,

I have one question for you guys, I am having problems with actively scanning an application in my company.
The application I am trying to scan has an Init GET request that must be called each time before any other request. The init provides a requestId that has to be sent in each request. So what happens with the active scanner is that when it runs, of course, it just fuzzes the requests without sending the Init request. And as a result I am getting just a bunch of 400 errors with Init required messages...
Is there any way I can tell ZAP to call Init before each and every request when doing active scan and replace the requestId with the new one, in some sort of a script or something similar.

Thanks,
Nenad

**Comment by kingthorin** [comment]
It should be possible to work around this using an HttpSender script.

If you don't mind moving this discussion - the ZAP User Group https://groups.google.com/group/zaproxy-users and Developer Group https://groups.google.com/group/zaproxy-develop are much better places for questions (than our issue tracker). Then we can help you out and the info will be there for the next person as well.

**Comment by npavicevic** [comment]
Of course, sorry for the mix up. I will move the question. Thank you for the help.
