### ISSUE TITLE
ZAP removes minimize button of window

### ISSUE THREAD

**Issue by EnDe** [zaproxy/zaproxy#3085]
ZAP's GUI startet in an X window manager (i.e. xfce) removes the minimize button of the window. This seems to happen, after a stacktrace was thrown  (see other issue #3084 "cast exception with Java stacktrace").
IMHO, it's a bad idea to change the user's GUI behaviour silently.

**Comment by thc202** [comment]
With which window did that happen? If this happens after #3084, then it might be a side effect of that issue. AFAICT we are not changing the windows decorations.

**Comment by EnDe** [comment]
Yes, I observed it after #3084 .
I expected that the window decoration is not changed by the ZAP team but by some kind of "language not practical for GUIs" ;-)
So this issue is for FAQ, documentaion or whatever. Please close.

**Comment by thc202** [comment]
Closing, assuming this is a side effect of #3084. Please, let us know if it happens again. Thanks!
