### ISSUE TITLE
Zap API is missing an option for adding  custom exclude parameter

### ISSUE THREAD

**Issue by svejdo1** [zaproxy/zaproxy#3087]
Missing api equivalent of this screen:
![zap-active-scan-input-vectors](https://cloud.githubusercontent.com/assets/5519592/21356543/490f34b0-c6d2-11e6-98df-0269ba0ddac8.png)

**Comment by psiinon** [comment]
As per http://stackoverflow.com/questions/41245267/how-to-add-custom-exclude-parameter-via-zap-api/41245882#41245882
Thanks for raising this :)

**Comment by thc202** [comment]
Merging into #2694 ;)

**Comment by psiinon** [comment]
Ha!
