### ISSUE TITLE
Be more lenient on add-on's file name format

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#3090]
ZAP should not require the status nor the version in the file name of the add-on, both properties can be obtained (they already are) from the manifest bundled in the add-on (i.e. ZapAddOn.xml). This change would require less efforts to produce an add-on that is accepted by ZAP (for example, by default an add-on/artifact built using Maven/Gradle does not have one of the statuses required by ZAP).

**Comment by psiinon** [comment]
Currently the code can ignore replaced add-ons just based on their name.
We'll need to make sure we dont end up loading (and holding in memory) old add-ons ;)

**Comment by thc202** [comment]
It can but it's not doing that when enumerating the add-ons, it ends up reading the manifest (and the behaviour would be kept the same).

A correction to issue description, ZAP is not currently reading the status from the manifest (although the add-ons, at least in zap-extensions, do have it).
