### ISSUE TITLE
Outdated npm module - zaproxy

### ISSUE THREAD

**Issue by radekk** [zaproxy/zaproxy#3103]
Latest version of `zaproxy` module you can get from npm registry is `0.2.0` whereas the newest one is `0.3.0`.

- v0.2.0 - https://www.npmjs.com/package/zaproxy
- v0.3.0 - https://github.com/zaproxy/zaproxy/blob/develop/nodejs/api/zapv2/package.json

Any plans to update npm registry?

**Comment by thc202** [comment]
Yes, that's on the plans, not sure exactly when though.

**Comment by wyvern8** [comment]
@khamasaki @radekk any closer to updating https://www.npmjs.com/package/zaproxy  ?

It is two years old and missing some apis i need.  I've built the latest locally and npm linked it which is fine in the short term.

If not, i may need to create a new npm package i guess.

**Comment by radekk** [comment]
Would be cool to see a new release 👍

**Comment by Pamplemousse** [comment]
Just a note:

Would be cool to see the package on npm registry to be updated when the source code changes.

There is a way to make Travis publish on npm: [docs.travis-ci.com/user/deployment/npm/](https://docs.travis-ci.com/user/deployment/npm/) .

**Comment by khamasaki** [comment]
I published 0.3 from the repository but it hasn't been updated very recently. I'm having trouble remembering how to generate updated API files.

**Comment by psiinon** [comment]
@khamasaki we have some instructions here: https://github.com/zaproxy/zaproxy/wiki/GeneratingTheWeeklyRelease#generate-the-client-apis
They might be out of date, so try them and let us know if they dont work for you.
And feel free to improve them, especially with npm specific instructions.

**Comment by thc202** [comment]
Might be a good opportunity to finish the migration to new repo :)

**Comment by thc202** [comment]
Closing, superseded by #5044.
