### ISSUE TITLE
Can zaproxy run only in daemon, no GUI.

### ISSUE THREAD

**Issue by baiyunping333** [zaproxy/zaproxy#3107]
Can Zapproxy can only run in Daemon? I don,t need the GUI. I only want to communicate with it in api.

**Comment by baiyunping333** [comment]
Sorry! I get my answer!

**Comment by thc202** [comment]
For the record, yes, that can be done with `-daemon` command line argument:
https://github.com/zaproxy/zap-core-help/wiki/HelpCmdline
