### ISSUE TITLE
Allow context menu/tab/mouse interaction through a scripted interface

### ISSUE THREAD

**Issue by acaetano** [zaproxy/zaproxy#3110]
Hello All,

  I was navigating on some twitter post and found this link: http://resources.infosecinstitute.com/writing-burp-extensions-shodan-scanner/

  It guides Burp users on a scripted extension creation process. As far as i remember, ZAP was the first one to create a scripted plugin interface, but i noticed that Burp's goes further, allowing context menus and all that. 

  As ZAP is my number one choice, i was wondering if you could implement some way to allow Add-On creation through a scripted interface, or allow context menu and tab creation through the already existing scripted plugin interface, as some repetitive tasks need parameter insertions that are not that handy to manipulate via scripts, but can be easily referred to through mouse clicks.

**Comment by thc202** [comment]
All script types can access (and extend) the UI components, although it requires some knowledge of how ZAP works internally.

We could create examples on how to do that. Thoughts?

(Somewhat related to #623.)

**Comment by acaetano** [comment]
An example on selecting a string with the mouse and right-clicking to input into an encoding/decoding script would be very good, for example.

Maybe another one a little more advanced about creating a new tab/window for some custom task. It would allow the usage of web apis/M2M for sideloading data processing/transformation.

**Comment by psiinon** [comment]
Sounds like a good idea :)

**Comment by acaetano** [comment]
Another benefit is the possibility of integration betwen the different addons. I am heavy user of that fuzzer addon, but it is too isolated from other zap functionalities. There is no way to (quickly generate a custom) export or analyse anything from it, leaving me with "optical correlation" as the only possible analysis algorithm.

After some examples of how to use the scripting interface, i'll be able to quickly export the result of any addon, any info that i may need, as dark as its code may be, without the need to download zap's source code on its entirety to compile a workaround if the addon's developer did not provide the means for that.

**Comment by acaetano** [comment]
Hello team, any advances on this request?

**Comment by kingthorin** [comment]
Unfortunately no.

We gladly accept contributions from new people though 👍 

Alternatively if that's not your thing, you could try to push the item on bountysource and see if anyone takes it up: https://www.bountysource.com/teams/zap/issues [I don't seem to be able to find this issue on bountysource right now, but .....]

Other than that, it's a wait a see issue. Being Open Source and having a limited team we can't tackle everything (note we have issues dating back 6+ years). Contributors pick and choose what's of interest to them to work on.

**Comment by acaetano** [comment]
I could contribute with an example, but can someone show me where to begin with?

**Comment by thc202** [comment]
Could you provide a concrete example of what you want?

For example, the following Stand Alone script creates a new pop up menu item in the Scripts tree:
```JavaScript
var ExtensionPopupMenuItem = Java.type("org.parosproxy.paros.extension.ExtensionPopupMenuItem")
var ExtensionPopupMenuItemExtender = Java.extend(ExtensionPopupMenuItem)

var menuItem = new ExtensionPopupMenuItemExtender("Useless Menu Item") {
  isEnableForComponent: function(component) {
    return "ScriptListTree".equals(component.getName());
  }
}

menuItem.addActionListener(function (e) {
    org.parosproxy.paros.view.View.getSingleton().showMessageDialog("Not a useful action...")
})

org.parosproxy.paros.view.View.getSingleton().getPopupList().add(menuItem)
```
but does nothing useful.

**Comment by thc202** [comment]
We could add useful examples as Stand Alone(?) templates, or better create new script types? (With the latter we might end up having a lot of types.)

**Comment by kingthorin** [comment]
Standalone or Targetted makes sense to me depending on intended usage.

**Comment by acaetano** [comment]
Standalone seems more suited for this, although targeted may be better with different use cases in the future...

As for the example you asked, a script that creates a top window menu root item (like "File","Edit",... ) that, when clicked, creates a new window that has a button (or text field) in it, maybe?

**Comment by acaetano** [comment]
All right guys, i came up with a crude example that has a label and a menu.
`
var frame = Java.type("javax.swing.JFrame");
var tela = Java.extend(frame);
var jpanel = Java.type("javax.swing.JPanel");
var jlabel = Java.type("javax.swing.JLabel");
var jmenubar = Java.type("javax.swing.JMenuBar");
var jmenu = Java.type("javax.swing.JMenu");
var jmenuitem = Java.type("javax.swing.JMenuItem");
var wndw = new frame("Window Test");
init();

function init(){
    wndw.setAlwaysOnTop(false);
    wndw.setSize(500, 500);
    var menubar = new jmenubar();
    var menu = new jmenu("A Menu");
    menu.setText("Menu");
    menu.getAccessibleContext().setAccessibleDescription("The only menu in this program");
    var menuitem = new jmenuitem("Menu Item");
    menu.add(menuitem);
    menubar.add(menu);
    wndw.setJMenuBar(menubar);
    var lbl = new jlabel("Label Test");
    lbl.setHorizontalAlignment(jlabel.CENTER);
    lbl.setVerticalAlignment(jlabel.CENTER);
    wndw.setContentPane(lbl);
    wndw.setVisible(true);
}`

The only problem is that i could not create the window using ZAP's "AbstractFrame" like normal windows inside the tool. 

`var absframe = Java.type("org.parosproxy.paros.view.AbstractFrame");
var w = new absframe();`
results in  
`<eval>:21 TypeError: Can not create new object with constructor org.parosproxy.paros.view.AbstractFrame with the passed arguments;`

**Comment by thc202** [comment]
You need to "implement" the `AbstractFrame`, e.g.:
```JavaScript
var AbstractFrame = Java.type("org.parosproxy.paros.view.AbstractFrame")
var frame = new AbstractFrame() {};

frame.setVisible(true);
```

Do you still want the example for adding the top level menu to main ZAP window?

**Comment by acaetano** [comment]
Ok, those braces really escaped me... 

Thanks for that, and yes, i could use that help with the main window menu too.

**Comment by acaetano** [comment]
There is something else that i need help with. I've been trying to add a popup menu from a highlighted text withouch much success. I even tried to use this [PopupCopyMenu class](https://github.com/zaproxy/zaproxy/blob/cc58c9e73327cb8f8bc51b6afc3965ff6ab6901a/src/org/zaproxy/zap/extension/stdmenus/PopupCopyMenu.java), but i got nothing in return.

Can someone give me a hand?

**Comment by thc202** [comment]
For which component do you want that? Request/Response tabs?

**Comment by acaetano** [comment]
Yes! Both of them.

**Comment by thc202** [comment]
Adding a top level menu to main ZAP window:
```JavaScript
var JMenu = Java.type("javax.swing.JMenu");
var JMenuItem = Java.type("javax.swing.JMenuItem");

var topLevelMenu = new JMenu("Top Level Menu");
topLevelMenu.add(new JMenuItem("Menu Item"));

var topLevelMenuEntry = new JMenu("Menu");
topLevelMenuEntry.add(new JMenuItem("Menu Item"));
topLevelMenu.add(topLevelMenuEntry);

// Dynamically add the top level menu
var mainFrame = org.parosproxy.paros.view.View.getSingleton().getMainFrame();
mainFrame.getMainMenuBar().add(topLevelMenu);
```

Adding a pop up menu that obtains the selected text from any text component (that uses the main context menu):
```JavaScript
var JTextComponent = Java.type("javax.swing.text.JTextComponent");
var ActionListener = Java.type("java.awt.event.ActionListener");
var ExtensionPopupMenuItem = Java.type("org.parosproxy.paros.extension.ExtensionPopupMenuItem");
var ExtensionPopupMenuItemExtender = Java.extend(ExtensionPopupMenuItem, ActionListener);

var menuItem = new ExtensionPopupMenuItemExtender("Show Selected Text") {
  selectedText: "",

  isEnableForComponent: function(component) {
    if (component instanceof JTextComponent) {
      selectedText = component.getSelectedText();
      return true;
    }
    return false;
  },

  actionPerformed: function() {
    org.parosproxy.paros.view.View.getSingleton().showMessageDialog(selectedText);
  },

  dismissed: function(selectedMenu) {
    if (selectedMenu != menuItem) {
      selectedText = null;
    }
  }
}

menuItem.addActionListener(menuItem);

org.parosproxy.paros.view.View.getSingleton().getPopupList().add(menuItem);
```

> I guess any place different than those would be easy to adapt it to, right?

It depends on the component that's being accessed, but it should be.
