### ISSUE TITLE
IOError: [Errno socket error] [Errno 11004] getaddrinfo failed

### ISSUE THREAD

**Issue by javixeneize** [zaproxy/zaproxy#3128]
Hi

I am having an error when trying to spider. IOError: [Errno socket error] [Errno 11004] getaddrinfo failed
I am working behind a proxy, so i am sure that this is related to it

To summarise, when i run zap.urlopen(target), it works fine, i can see the request in ZAP, but, zap.spider.scan(target) is returning that error

What is being done differently between zap.urlopen and the methods in spider?  
Note that i have already set http_proxy and https_proxy

Thanks

**Comment by kingthorin** [comment]
https://groups.google.com/forum/m/?pli=1#!topic/zaproxy-users/c4VhXI_FGCc

**Comment by javixeneize** [comment]
Yes, thats me :) But i have had not answer there

**Comment by thc202** [comment]
Indeed but it's better to not use the issue tracker for questions (you could bump the thread in the mailing list, if not getting an answer).

Closing, this is being handled in the mailing list.
