### ISSUE TITLE
Unnecessary TODO

### ISSUE THREAD

**Issue by rnehra01** [zaproxy/zaproxy#3137]
```
TODO: if the argument is reflected back in the HTML output, the
boolean based logic will not detect an alert (because the HTML results of
argument values "id=1" will not be the same as for "id=1 and 1=1") 
```
I found above lines in `TestSQLInjection.java` but I think the issues has been addressed using`stripOff()` for each response to remove argument reflected back in HTML output.
And ZAP is working fine (raises required Alerts) for pages that reflect back the arguments.

**Comment by thc202** [comment]
Yes, that was already implemented (but the TODO was not deleted).

For questions/remarks like this one it could be used the dev mailing list:
https://groups.google.com/group/zaproxy-develop

In any case a pull request removing the TODO would be fine too.

**Comment by rnehra01** [comment]
I'll keep that in in mind asking this type of question next time.
