### ISSUE TITLE
Need of enhancement in testing Output where param gets reflected back

### ISSUE THREAD

**Issue by rnehra01** [zaproxy/zaproxy#3139]
Though the situation in which `param` gets reflected back in HTML output has been addressed using `stripOff` method but it still needs some improvement.
There are two ways in which param gets reflected back in HTML output
1. The parameter gets reflected back which user supplies
2. The parameter gets reflected back after evaluation from the database.

If code does both, then ZAP fails to detect SQLI 
```
$query=" SELECT * FROM users WHERE id = " . $_GET['id'];
echo "Executing query: " . $query . "<br>"; 
$result=mysqli_query($connection, $query); 
while($row= mysqli_fetch_assoc($result)){
	echo "ID        : ".$row['id']."<br/>";
	echo "User_name : ".$row['name']."<br/>";
}
```
On stripping Off 
**HTML normal parmeter=2 output**
```
Executing query: SELECT * FROM users WHERE id = 
ID : 
User_name : richguy
```
**HTML modified parmeter=4-2 output**
```
Executing query: SELECT * FROM users WHERE id =
ID : 2
User_name : richguy
```
Thus they are not equal.

**Comment by rnehra01** [comment]
This issue can be fixed by using the `stripOff` for modified param as
```
strippOff(stripOff(modifiedMsgRes, modifiedParam), originalParam)
```

**Comment by rnehra01** [comment]
@kingthorin ,@thc202 Any comments?

**Comment by kingthorin** [comment]
Your logic seems sound to me. 

Will the double (triple) check only been done in certain scenarios? (i.e.: Only the expression tests?)

**Comment by rnehra01** [comment]
Doing that generally does not seem to create any problem. It's good to compare after stripping off everything related to the parameter.

**Comment by rnehra01** [comment]
@kingthorin, should I fire up a PR implementing changes?

**Comment by kingthorin** [comment]
Sure

**Comment by thc202** [comment]
For the record, the change sounds good to me. It would be interesting to check if it could/should be used a lightweight version of `stripOff` (e.g. the expression and original parameter does not contain chars that would be encoded).

**Comment by rnehra01** [comment]
Apart from lighter strippOff, I would like to remove the comparison made for `unstripped part` as well as after this there is no NEED of that.
Does it sound good ? @thc202 @kingthorin

**Comment by kingthorin** [comment]
Can you be more specific?

**Comment by rnehra01** [comment]
@kingthorin I have made a PR implementing the idea.

**Comment by kingthorin** [comment]
Thanks @thc202, made a mistake on a push ... oops (to my fork instead of the OP's fork)

**Comment by kingthorin** [comment]
Fixed in https://github.com/zaproxy/zap-extensions/pull/735
