### ISSUE TITLE
Allow HSTS test on HTTP to be ignored

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#3148]
[StrictTransportSecurityScanner.java](https://github.com/zaproxy/zap-extensions/blob/alpha/src/org/zaproxy/zap/extension/pscanrulesAlpha/StrictTransportSecurityScanner.java#L132) reports an issue if an HTTP page has an HSTS header. This is a pain when you are scanning dev / staging sites which might well not have been configured for HTTPS. Turning off this check isnt good because it then doesnt scan for missing / incorrect HSTS headers.
Yes this check could be turned on and off on a per site basis but thats a pain when performing automated scans v a large number of sites, eg using the baseline.
Otpions - we could either move this check to another rule or we could disable it based on the threshold.
My initial suggestion is that is only included on the low threshold as its not _really_ a security issue.
Thoughts?

**Comment by kingthorin** [comment]
I'm good with making that part low threshold. I can tackle it this morning. Assign me the issue if that works.

**Comment by thc202** [comment]
I'm fine with the change too.

**Comment by psiinon** [comment]
Very happy for you to make this change @kingthorin :)

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#719.
