### ISSUE TITLE
Autoselect Imported Certificate

### ISSUE THREAD

**Issue by davewichers** [zaproxy/zaproxy#3163]
In ZAP Options, when you import a new PKCS#12 cert (and probably works the same for the other types as well), after successful import, it takes you back to the KeyStore tab (which is good).  But then to make that the Active cert the user has to:

a) Click on the cert in the left column,
b) Click on the username in the right column,
c) Click on the Set Active button

I'm requesting that when a cert is successfully imported, and they are sent back to the KeyStore tab, you automatically do a) and b) for them so they just have to do step c).

This doesn't hurt anything if they don't want to do step c) right now, but makes it MUCH easier if they do.  This should probably take like 5 minutes or less to implement this usability enhancement.

Given that #2489 is still open, I have to do this every time I start ZAP up again. If #2489 was addressed, I wouldn't care as much (but that's a much harder ticket to address).

**Comment by kingthorin** [comment]
I support this idea, I've run into this issue and had the same thoughts in the past as well.
