### ISSUE TITLE
Fuzzer: Not Rendering Custom States

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#3166]
Per this thread:
https://groups.google.com/forum/#!topic/zaproxy-scripts/zl0AgHzsYfs

Quote @kingthorin:

> I think you found a bug.
> 
> I did a quick test using the default script template as you described.
> 
> At first I was thinking it might need something like: https://github.com/kingthorin/community-scripts/blob/master/standalone/historySourceTagger.js#L36 but I see no equivalent (in a quick 2min look).
> 
> You can see the states are being added if you do a "print(fuzzResult.getCustomStates())" in the script right after the addCustomState.... line.
> 
> I sent 3 fuzz requests and got the following in the script console output:
> {Key Custom State=Message Contains X}
> {Key Custom State=Message Contains X}
> {Key Custom State=Message Contains X}
> 

Quote @thc202:

> The custom states are added and are in the column (if you copy the entry 
> you'll see the states) but are not shown/rendered... 
> 
> An issue would be great, custom states' values should be shown (even if 
> there's no specific renderer for them). 
>

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#746.

**Comment by thc202** [comment]
Released in version 8 of Fuzzer add-on (bundled in ZAP 2.6.0).
