### ISSUE TITLE
URLs included in context are disregarded by the spider

### ISSUE THREAD

**Issue by oldbam** [zaproxy/zaproxy#3192]
I am trying to use ZAP via python API client. I use official release 2.5 of ZAP. I want to crawl web site at http://mysite.com, and if there are links to subdomain.mysite.com, include them into crawl.

I tried to use the following code:

```
zap.core.new_session(apikey=apikey)
zap.context.include_in_context(context_name, ".*mysite\.com.*", apikey)
zap.spider.scan(url=target, contextname=context_name, apikey=apikey)
```

However, even though spider starts with a specified context, it still ignores URLs to subdomain.mysite.com and reports them in Spider->Processed window with OUT_OF_SCOPE flag.

**Comment by kingthorin** [comment]
Ref: https://groups.google.com/forum/#!topic/zaproxy-users/Q9zJx2oWdc0
