### ISSUE TITLE
zap wont start

### ISSUE THREAD

**Issue by jeneli** [zaproxy/zaproxy#3199]
I am using the cross platform version when i try to start ZAP it gets stuck after Creating root certificate wont go further and no errors in the log.

Any ideas

thanx

**Comment by psiinon** [comment]
If you're not sure if this is a bug or not then its best to asdk this on the ZAP User Group: https://groups.google.com/group/zaproxy-users

For info we'll want to know which ZAP version, which OS and how you are starting it :)

**Comment by thc202** [comment]
Reopening, per comments in the ZAP User Group:
https://groups.google.com/d/topic/zaproxy-users/8SKAQnXy6z4/discussion

**Comment by thc202** [comment]
Closing, this was most likely caused by the JRE/OS rather than ZAP (thread dump provided showed expected state).
