### ISSUE TITLE
Add Context functionality to command line

### ISSUE THREAD

**Issue by WendellFry** [zaproxy/zaproxy#3200]
I saw Simon mention using a context switch in a command line, and that is what I've been looking for, though it is not listed in the available command line commands available.  I would like to request this, as we will want to run as lean as possible with limited scans of our code.  This would be really great!

Thank you!  Here's hoping!  I've been looking and looking.  using the API with daemon mode of course is helping and is faster.  But we are looking at our best options.  Thank you!

Wendell Fry

**Comment by thc202** [comment]
Just to confirm, this feature is to be used with `-quickurl` command line option?

**Comment by thc202** [comment]
Reference:
https://groups.google.com/d/topic/zaproxy-users/j6OyYlqwZeI/discussion

**Comment by WendellFry** [comment]
Yes, with -cmd and -quickurl switches, or any possible -cmd scan, thanks!

**Comment by psiinon** [comment]
The direction we are going in for this is the automation framework: https://www.zaproxy.org/docs/automate/automation-framework/
This will let you specify a context via a yaml file which you can specify on the command line :)

**Comment by psiinon** [comment]
The Automation Framework now supports contexts :)
