### ISSUE TITLE
Older messages are not available within the same ZAP session

### ISSUE THREAD

**Issue by alienatix** [zaproxy/zaproxy#3208]
Sometimes after scanning a large site, I can't get a message via ZAP API (using previously saved message ID) for requests made a day before (in the same session).

Step 1: Get an alert by ID:
http://127.0.0.1:8080/JSON/core/view/alert/?id=0

`{"alert":{"other":"","evidence":"Set-Cookie: DEVICE","pluginId":"10010","cweid":"16","confidence":"Medium","wascid":"13","description":"A cookie has been set without the HttpOnly flag, which means that the cookie can be accessed by JavaScript. If a malicious script can be run on this page then the cookie will be accessible and can be transmitted to another site. If this is a session cookie then session hijacking may be possible.","messageId":"313","url":"http://example.com","reference":"http://www.owasp.org/index.php/HttpOnly","solution":"Ensure that the HttpOnly flag is set for all cookies.","alert":"Cookie No HttpOnly Flag","param":"DEVICE","attack":"","name":"Cookie No HttpOnly Flag","risk":"Low","id":"0"}}`

Step 2: Get message by ID
http://127.0.0.1:8080/JSON/core/view/message/?id=313

`{"code":"does_not_exist","message":"Does Not Exist"}`

I don't have clear steps to reproduce the problem yet...

ZAP version: 2.5.0 running in Docker container.

Interesting that container is running for 9 weeks:

`root@zap:~# docker ps
CONTAINER ID        IMAGE                            COMMAND                CREATED             STATUS              PORTS                    NAMES`
`f0b86b099761        owasp/zap2docker-stable:latest   "zap.sh -daemon -por   9 weeks ago         Up 9 weeks          0.0.0.0:9100->9100/tcp   zap`

When I review ZAP's HSQLDB log for the session, the first entry has today's date:

`root@f0b86b099761:/root/.ZAP/session# cat untitled1.log | less`
`/*C40*/SET SCHEMA PUBLIC
DISCONNECT
/*C3*/SET SCHEMA PUBLIC
INSERT INTO HISTORY VALUES(186685,1481128293791,1,200,1487156587257,342,'GET','https://example.com/b?tq=SELECT%20amount%2
0WHERE%20date%20%3E%3D%20%272009-10-01%27%20AND%20date%20%3C%3D%20%272009-10-31%27%20AND%20reference%3D89089'
...
,'HTTP/1
.1 200 OK\u000d\u000aServer: nginx\u000d\u000a
Date: Wed, 15 Feb 2017 11:10:12 GMT
...
,NULL,'',TRUE)
COMMIT`

Original discussion: https://groups.google.com/forum/#!topic/zaproxy-users/Mwiav2mquq0

**Comment by kingthorin** [comment]
@alienatix were you ever able to figure out the preconditions to this issue? Aside from the container being up for a crazy long time (do you know what kind of usage there was over those 9wks?).

**Comment by kingthorin** [comment]
@alienstix any news?

**Comment by kingthorin** [comment]
No follow-up from reporting user in years. Closing.
