### ISSUE TITLE
Can't find .ZAP_JVM.properties with %HOMEPATH% when using zap.bat in windows

### ISSUE THREAD

**Issue by ScofieldXu** [zaproxy/zaproxy#3211]
OS: Windows 7 professional Edition 32 - bit
ZAP_VERSION: ZAP_2.5.0_Cross_Platform
The .ZAP_JVM.properties exists.

When I start zap using zap.bat in windows command line, the shell can't find .ZAP_JVM.properties correctly. The "if exist" statement which use %HOMEPATH% variable is False. I found the value of %HOMEPATH% is something like \Users\username which has not contain the drive letter, and the "if exist" statement need a complete path like C:\Users\username to use. I think the shell should use %USERPROFILE% or %HOMEDRIVE%%HOMEPATH% instead of %HOMEPATH% to find .ZAP_JVM.properties. When I do like this, the shell start zap with the given jvm options in property file correctly.

Reference:
[https://www.microsoft.com/resources/documentation/windows/xp/all/proddocs/en-us/ntcmds_shelloverview.mspx?mfr=true](https://www.microsoft.com/resources/documentation/windows/xp/all/proddocs/en-us/ntcmds_shelloverview.mspx?mfr=true)

**Comment by thc202** [comment]
How many drives do you have? I'm not able to reproduce that (same OS, just one drive), the file is being found and used.

**Comment by ScofieldXu** [comment]
I have three hard drive (C, D and E), and I have some tests, Here is the results.

- when zap.bat located at drive C, %HOMEPATH% can find .ZAP_JVM.properties
- when zap.bat located at another drive except drive C like drive D, %HOMEPATH% can't find .ZAP_JVM.properties

```
C:\Users\scofield>if exist "%HOMEPATH%\OWASP ZAP\.ZAP_JVM.properties" (echo true) else (echo false)
true

C:\Users\scofield>D:

D:\>if exist "%HOMEPATH%\OWASP ZAP\.ZAP_JVM.properties" (echo true) else (echo false)
false

D:\>E:

E:\>if exist "%HOMEPATH%\OWASP ZAP\.ZAP_JVM.properties" (echo true) else (echo f
alse)
false
```

I think maybe windows can automatically add current drive when use %HOMEPATH%. So when we use start zap in drive C, everything is fine. When we start in another drive, %HOMEPATH% is not we want.

**Comment by thc202** [comment]
Thanks!
