### ISSUE TITLE
Use Referrer-Policy in ZAP API

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#3229]
Change ZAP API to use the `Referrer-Policy` [1] response header, with policy `no-referrer`.

[1] https://w3c.github.io/webappsec-referrer-policy/

**Comment by kingthorin** [comment]
Note there's no IE support, and Edge/Safari support is based on the old draft (which doesn't seem to support ZAP's implementation): http://caniuse.com/#search=referrer%20policy

**Comment by thc202** [comment]
Yeah, it will not work with all browsers. (I guess we could add the meta as well?)
