### ISSUE TITLE
Windows - Chrome/Firefox HSTS not working

### ISSUE THREAD

**Issue by Themercee** [zaproxy/zaproxy#3243]
Hello Guys,
I tried to use ZAP with website that enabled HSTS and it just doesn't work. I have done all my setup right (importing the certificate generate by ZAP into the trust authorities in the system certificate manager + adding it into firefox certificates). Nothing works. It may works on HTTPS website with no HSTS activated.

In the following picture, you can see the owasp certificate is installed. 

I need to also mention I restart the browser once the installation was done.

![2017-02-26 10_27_56-certlm - certificats - ordinateur local_autorites de certification racines de c](https://cloud.githubusercontent.com/assets/6720140/23341021/5b028192-fc0e-11e6-896d-633e7a087a92.png)

**Comment by Themercee** [comment]
Nevermind, I reboot my computer and it works.

**Comment by thc202** [comment]
Thanks for letting us know!
