### ISSUE TITLE
Remote zaproxy doesn't work

### ISSUE THREAD

**Issue by majones713** [zaproxy/zaproxy#3249]
I recall opening an issue related to this not too long ago and I believe it was a duplicate but I can't find it anywhere.  Hopefully opening this will allow me to track the original issue.

In any case, when attempting to access a remote proxy in which the local proxy settings are:

0.0.0.0:8090

And I attempt to access/browse the API remotely via:

http://{IP_ADDRESS}:8090/UI

I get:

**Failed to read http://{IP_ADDRESS}:8090/UI within 20 seconds, check to see if the site is available and if so consider adjusting ZAP's read time out in the Connection options panel.**

If I access locally on machine via  http://{IP_ADDRESS}:8090/UI I get the same error.

If I access locally using localhost or 127.0.0.1 via http://localhost:8090/UI or http://127.0.0.1:8090/UI it works.

**Comment by kingthorin** [comment]
You were proxying through zap while trying to access zap?

**Comment by thc202** [comment]
Where is ZAP? AWS EC2? Might well be #2318.

**Comment by majones713** [comment]
@kingthorin No, I wasn't proxying through zap while trying to access remotely

@thc202 yes ZAP is located on an AWS EC2 instance.  Just looked at referenced defect and that's it :-)

Thanks!  Will this fix be in the next release?

**Comment by thc202** [comment]
Yes, hopefully, will try to push a fix this week.

Merging into #2318 (you can subscribe to the latter issue to receive notifications).
