### ISSUE TITLE
Editing job throws "java.lang.RuntimeException"

### ISSUE THREAD

**Issue by ZoeThivet** [zaproxy/zaproxy#3257]
Hello,

I've created a job which works fine. Then I decided to generate reports in the "Finalize run" step. But I can't edit it anymore: when I clicked on "Save" after configuring the report, Jenkins threw an exception. From this time, any trivial change will throw this exception. (stack in attachments)
My job still works but I can't change anything about it. The only way I can change anything except the reporting options is cloning the job and configure the clone.
I've reproduced the bug with both "Generate report" and "Export report" options.

Here is my architecture:

-I have my ZAP jar, zap.sh and ZAP config files within my jenkins/tools/hudson.task.Ant_AntInstallation. I put them there because Jenkins was complaining he couldn't find them here.
-Jenkins version : 2.32.1
-ZAP plugin version : 1.0.5

Is there a workaround in order to retrieve the build reports? Thank you.

[stack-jenkins.txt](https://github.com/zaproxy/zaproxy/files/815742/stack-jenkins.txt)

**Comment by thc202** [comment]
Issues of the Jenkins plugin are tracked in Jenkins JIRA. [1] Would you mind create the issue there instead?

[1] https://issues.jenkins-ci.org/browse/JENKINS-40349?jql=project%20%3D%20JENKINS%20AND%20component%20%3D%20zap-plugin

**Comment by ZoeThivet** [comment]
Done

**Comment by thc202** [comment]
Thanks! Closing this one. For reference it's https://issues.jenkins-ci.org/browse/JENKINS-42463
