### ISSUE TITLE
Fuzzer - Can't navigate to save payload files outside of default directory

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#3263]
When you setup a new payload and click save, the save dialog does not allow you to navigate outside of the default location (fuzzers within the user's default [home?] directory).

**Comment by kingthorin** [comment]
The issue seems to be [`getFile()`](https://github.com/zaproxy/zap-extensions/blob/beta/src/org/zaproxy/zap/extension/fuzz/payloads/ui/impl/AbstractPersistentPayloadGeneratorUIPanel.java#L94) in `AbstractPersistentPayloadGeneratorUIPanel`

Something similar to the following (not fully tested) seems to address the issue:
```
    private Path getFile() {
        JFileChooser fileNameDialogue = new JFileChooser();
        Path path = null;
        int rc = fileNameDialogue.showSaveDialog(null);
        if (rc == FileChooser.APPROVE_OPTION) {
            return fileNameDialogue.getSelectedFile().toPath();
        } else {
            return null;
        }
    }
```

**Comment by thc202** [comment]
That behaviour is by design, the idea is to save the file in the fuzzers directory to be picked automatically by ZAP.

**Comment by kingthorin** [comment]
Oh really? Ok, I kind of figured the user should be able to save wherever they want.

Could we default to the fuzzers dir but allow navigation?

**Comment by thc202** [comment]
Missed your comment, sure, it's possible to allow that, although we need to change the tool tip :)

**Comment by thc202** [comment]
Original issue #1932.

**Comment by kingthorin** [comment]
Does the open dialog for custom 'File Fuzzers' prevent navigation as well?

**Comment by thc202** [comment]
Which dialogue do you mean specifically? The one to select the File Fuzzers previously added?

**Comment by kingthorin** [comment]
I'll have to look at the workflow more. I'm on a bus right now :) But was trying to figure out why it would be limiting the save location.... figured it would make sense if there was a corresponding open dialog that assumed the same directory.

**Comment by thc202** [comment]
Yeah, we just enumerate the custom File Fuzzers from the "fuzzers" directory (and list them in a tree for the user to select when adding the payloads from "File Fuzzers").

**Comment by kingthorin** [comment]
Oh ok, now the flow and ui choice make more sense. Will close this and leave as is.
