### ISSUE TITLE
Certificate Issue and Anti-Virus

### ISSUE THREAD

**Issue by JordanGS** [zaproxy/zaproxy#3266]
So two very common anti virus, Norton and Kaspersky throw a certificate issue. In the case of Kaspersky it's "Cannot guarantee authenticity of the domain to which encrypted connection is established".

This is after having generated the Dynamic SSL Certificate from ZAP and having imported it as a Certificate Authority in Firefox. So it's not Firefox that's preventing the connection but rather the anti-virus software.

When looking at the details, it specifically says: "Windows does not have enough information to verify this certificate".

Has anyone encountered this issue in the past? Is there any solution other than disabling my anti-virus?

ZAP_D-2017-02-27
Windows 10
Kaspersky Total Security 17
Firefox 51.0.1

![cert_issue](https://cloud.githubusercontent.com/assets/17622264/23589448/53ca23ac-019b-11e7-87b3-33fb17185fc4.png)

**Comment by kingthorin** [comment]
Your AV likely uses the Windows certificate store not Firefox's.

**Comment by JordanGS** [comment]
@kingthorin you are correct. Thanks :)
