### ISSUE TITLE
Global Exclude URL (beta) - after close and reopen does not pick up added regex for excluding URLs

### ISSUE THREAD

**Issue by gmaran23** [zaproxy/zaproxy#3275]
When added a regex to exclude a url (let's say google.com for example) via the Global Exclude URL (beta) feature, further requests doesn't show up in the History tab and the Sites tree.

The regex is saved to the config.xml file at the .\OWASP ZAP directory.

However, if ZAP is opened and closed, even though the newly added regex is preserved in the config.xml and loaded in the Options window, the setting is not honored, that is the requests appear in the Sites tree and History tab.

A screen recording of the issue here - https://vimeo.com/207585000

I am currently debugging the issue on the dev branch to analyse the root cause, I will post in the develop group when needed help.

**Comment by thc202** [comment]
That's because the global regexes are not being applied during startup.

**Comment by gmaran23** [comment]
Thanks for the fix guys. I will download next week's weekly and test this out.

**Comment by thc202** [comment]
Great!
