### ISSUE TITLE
Add elmah scanner

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#3279]
Add an active scanner that checks for elmah.axd exposure/use. It can provide stack traces, session IDs (for hi-jacking ;) ), etc

Make sure to check for auth needed response, not simple existence.

https://msdn.microsoft.com/en-us/library/aa479332.aspx
https://en.m.wikipedia.org/wiki/ELMAH

**Comment by kingthorin** [comment]
https://www.troyhunt.com/aspnet-session-hijacking-with-google/

http://notasafaweb.apphb.com/elmah.axd

**Comment by kingthorin** [comment]
Fixed in: https://github.com/zaproxy/zap-extensions/pull/873

**Comment by thc202** [comment]
Released in version 19 of Active scanner rules (alpha) add-on.
