### ISSUE TITLE
Add trace.axd scanner

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#3280]
Add an active scanner that looks for exposure of trace.axd. This component exposes client info (including session info), and server info (such as physical disk locations, etc)

https://msdn.microsoft.com/en-us/library/wwh16c6c.aspx

http://notasafaweb.apphb.com/trace.axd

**Comment by kingthorin** [comment]
https://www.dotnetperls.com/trace

**Comment by kingthorin** [comment]
Fixed in https://github.com/zaproxy/zap-extensions/pull/897

**Comment by thc202** [comment]
Released in version 19 of Active scanner rules (alpha) add-on.
