### ISSUE TITLE
CSP-Nonce Checks

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#3287]
Per: https://github.com/zaproxy/zap-extensions/pull/805

- [x] Add format validity check to [CSP Passive Scanner](https://github.com/zaproxy/zap-extensions/pull/713) ~(once reviewed/accepted)~.
- [ ] Add nonce registry of some sort and check for re-use across requests. (This might have to be broken into a separate request.)

Ref: https://w3c.github.io/webappsec-csp/#grammardef-nonce-source

**Comment by kingthorin** [comment]
I'm wondering if the second item is actually worth implementing? Has anyone ever encountered an "in the wild" condition where nonces were **not** generated sufficiently uniquely?

**Comment by psiinon** [comment]
Would someone be able to use the tokengen add-on for this? https://github.com/zaproxy/zap-extensions/wiki/AddOn_tokengen
If so then we could say thats already covered (and maybe reference it from the help?)

**Comment by kingthorin** [comment]
I'm not a CSP authority by any stretch of the imagination, however, from my understanding the nonces are expected to be unique. So, in theory requesting the same resource repeatedly should give a new nonce (token), therefore yes TokenGen should be applicable.

**Comment by psiinon** [comment]
I guess we could make a couple of requests - but to do a thorough check we'd want to do lots, and that wouldnt be a good option for an active scan rule. So I'm fine with leaving that out.

**Comment by kingthorin** [comment]
Closing per above.
