### ISSUE TITLE
Path Traversal False Positive

### ISSUE THREAD

**Issue by NeuroWinter** [zaproxy/zaproxy#3293]
I am getting this as a Path Traversal, however its not.

```
HTTP/1.1 200 OK
Server: KAYAK/1.0
Content-Type: application/json;charset=UTF-8
Content-Language: en-US
Set-Cookie: cluster=4; Expires=Wed, 15-Mar-2017 04:48:16 GMT; Path=/; HttpOnly
Set-Cookie: p1.med.sid.http=H-4e5tw66K3VqJzWjjXjQgG-Hd0M2FjdiQWVXbyc2YQW4igBYkuptV8n1xPsOEfHi; Path=/; HttpOnly
Set-Cookie: NSC_q4-lbqj=<REMOVED COOKIE>;expires=Wed, 15-Mar-2017 04:05:16 GMT;path=/;httponly
Via: 1.1 varnish
Fastly-Debug-Digest: 270be0b13ca02099238f66739e4490f29d057d924c73f4abe1a03a8c45a32811
Accept-Ranges: bytes
Date: Wed, 15 Mar 2017 04:03:16 GMT
Via: 1.1 varnish
Age: 0
Connection: keep-alive
X-Served-By: cache-jfk8146-JFK, cache-wlg7321-WLG
X-Cache: MISS, MISS
X-Cache-Hits: 0, 0
X-Timer: S1489550595.923270,VS0,VE236
Vary: Accept-Encoding
```

**Comment by psiinon** [comment]
Thanks for reporting this.
Which parameter is it flagging and what is the attack? Any more info you can supply from the alert would also be very useful.

**Comment by kingthorin** [comment]
@neurowinter Can we get the full request and response? Just having the response headers really doesn't give us anything useful.

**Comment by NeuroWinter** [comment]
Ahhh my mistake I will post when I get back home.

**Comment by kingthorin** [comment]
No problem

**Comment by NeuroWinter** [comment]
I couldnt find the exact scan that gave me this but I also found this one:

https://www.workfit.com/api/census/RecordHit?crumb=RecordHit

**Comment by kingthorin** [comment]
Thanks for looking, unfortunately without the details there's nothing further we can do.

**Comment by NeuroWinter** [comment]
OK I will close this ticket now and if I come accross another one I will get all the details I can. Sorry I was not saving scans at this point.

**Comment by kingthorin** [comment]
No problem,  thanks for letting us know.
