### ISSUE TITLE
Create script directories when initialising the home dir

### ISSUE THREAD

**Issue by JordanGS** [zaproxy/zaproxy#3296]
For the sake of clarity, let's have zap create all directories. Such as

1. scripts/scripts/authentication
2. scripts/scripts/sequences

and any other directories it will need during initialization rather than on an as needed basis.

**Comment by thc202** [comment]
That might be tricky (without hardcoding them), some of the script types are added by add-ons (which might not be bundled with ZAP).

**Comment by JordanGS** [comment]
@thc202 can we do the ones that are bundled with zap?

**Comment by thc202** [comment]
I think so, core can create the `scripts` directory and`ExtensionScript` can create the directories when the script types are added. That should create most of the directories.

**Comment by JordanGS** [comment]
@thc202 sounds good, let's do as much as we can :)
