### ISSUE TITLE
object has no attribute 'fullResults' error

### ISSUE THREAD

**Issue by fatihersinadim** [zaproxy/zaproxy#3301]
Hi,

I'm using Zap 2.5 version and python-owasp-zap-v2.4 (0.0.8)

When I trying to get full report for spidered URL's (As described here:  https://github.com/zaproxy/zaproxy/wiki/ApiGen_spider) "zap.spider.fullResults(scanid)",  on running the script, getting the below error;

**AttributeError: 'spider' object has no attribute 'fullResults'**

Is there another way to get the entire spidered url list?

Thanks,

**Comment by thc202** [comment]
With Python API you should use `full_results`, the function names are lower case and separated by underscores (instead of being camel case).

**Comment by fatihersinadim** [comment]
Thanks @thc202 it works. Is there written documentation for Python API?

**Comment by thc202** [comment]
I'm afraid not (there's no Python API specific documentation, just the doc you have linked above).
