### ISSUE TITLE
Received 407 error code for https URL

### ISSUE THREAD

**Issue by swatihpatil** [zaproxy/zaproxy#3316]
I am trying to attack https url, received Failed to attack URL: received a 407 response code.

Referred link for ssl handshake.
https://github.com/zaproxy/zaproxy/wiki/FAQsslHandshake

- Checked 'Enable unsafe SSL/TLS renegotiation' checkbox in the Certificate Options screen
- Downloaded  'Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files but still there is no luck.
I am new to ZAP, can anyone please help me.

**Comment by kingthorin** [comment]
Tell us more. Does it happen on all requests? How do you have ZAP setup?  Is the target local? Does it only happen on https URLS?  (Did you try non-https URLS?) Etc. Are you using an upstream proxy?  Does the upstream proxy require authentication? (Did you configure that?)

**Comment by swatihpatil** [comment]
Worked for other environment URL which is also https url. Also when I try to hit https://www.sourceforge.com/, gives me 407 error. Do we need to install SSL certificate for all desired site.

**Comment by thc202** [comment]
Based on the status code you might need to define the authentication credentials for the outgoing proxy to access external websites. [1]

[1] https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsOptionsConnection

**Comment by thc202** [comment]
@swatihpatil any info on this?

**Comment by thc202** [comment]
Closing, insufficient evidence.

**Comment by chucklu** [comment]
@swatihpatil  I encounter the problem because I have configured a proxy for zap. And the proxy did not work now. I just turn off the proxy setting to make it work again.

**Comment by psiinon** [comment]
@chucklu If this is a problem for you then please open a new issue and supply more evidence.

**Comment by kingthorin** [comment]
Or even better, since the described issue is unlikely to be a Zap bug (but more likely a corporate config thing) start a discussion in the ZAP User Group https://groups.google.com/group/zaproxy-users

**Comment by chucklu** [comment]
@psiinon  It's not a problem now, I just give feedback here for anyone who encounter the same problem.
By the way, is it possible that you can check the availability of the proxy first instead of give 407 error.

**Comment by thc202** [comment]
It's not ZAP that's returning 407 but the outgoing proxy (ZAP should be returning 502 in that case I guess).
