### ISSUE TITLE
Zap is taking to much time to attack 

### ISSUE THREAD

**Issue by swatihpatil** [zaproxy/zaproxy#3318]
We are trying to scan our systest environment url using zap. Since last 5 hour I can see only 9% progress.
Referred:
https://blog.mozilla.org/security/2013/07/10/how-to-speed-up-owasp-zap-scans/

as per suggestion, modified scan policy and made threshold off for all injection other than cross-site-scripting. But still its slow :(.

Please advise.

**Comment by psiinon** [comment]
Please ask questions like this on the ZAP User Group: https://groups.google.com/group/zaproxy-users
Only raise an issue if you think there is a specific problem with ZAP.
In this case we'll need to know more about your application, such as the number of URLs etc.

**Comment by fbarriosCL** [comment]
+1 @swatihpatil
