### ISSUE TITLE
Add ability to mark an issue as Reported

### ISSUE THREAD

**Issue by davewichers** [zaproxy/zaproxy#3319]
With Confidence, you can mark something as Confirmed, False Positive, etc. But I'd like the ability to mark an issue as reported as well (and probably in addition to Confirmed). Confirmed means 'yes its vulnerable'. Reported could be used to mean its been JIRAed or however such issues are reported to the app owner. In fact, if we built links between ZAP and things like JIRA so you could push things manually (or automatically), reported could indicate this has been done (even IF the issue has or has not been confirmed.

This issue was previously included as idea 5 in issue #2595.

**Comment by psiinon** [comment]
Sounds good to me.
One problem we have is that ZAP doesnt have any concept of repeated scans, but that will change with the (long awaited;) ZaaS.

**Comment by thc202** [comment]
Bug Tracker add-on could/should use this feature.

**Comment by thc202** [comment]
Candidate for alert tags.

**Comment by kingthorin** [comment]
I believe this can be closed. Alert tags should satisfy this requirement. They can now be marked "Reported" "Yes", "Reported" with a URL, etc.
