### ISSUE TITLE
Python API Example results in error

### ISSUE THREAD

**Issue by limquanheng** [zaproxy/zaproxy#3334]
I'm new to the Python ZAP API, apologies if I got it wrong:
The Python API example results in a error in zap.spider.status() call in zap.spider.status(str(scanid)

Accessing target http://demo.testfire.net/
Spidering target http://demo.testfire.net/
Traceback (most recent call last):
  File "zaproxy_dev/zap-baseline.py", line 26, in <module>
    while (int(zap.spider.status(str(scanid))) < 100):
TypeError: 'unicode' object is not callable

Process finished with exit code 1

**Comment by limquanheng** [comment]
ZAP is Version 2.5.0, API is python-owasp-zap-v2.4 0.0.8

**Comment by limquanheng** [comment]
Turned out I was just a n00b and did not spot this, the example at https://github.com/zaproxy/zaproxy/wiki/ApiPython calls zap.spider.status() as a function, but in the ZAP2 library, it is a @property and has to be called zap.spider.status.

It's not an issue with the code, rather, with the wiki example entry

**Comment by kingthorin** [comment]
Can you provide the URL?

**Comment by limquanheng** [comment]
Hello, it's at

**Comment by limquanheng** [comment]
Hello it's at https://github.com/zaproxy/zaproxy/wiki/ApiPython 
Near the bottom of the page. Experienced Python programers would probably spot it, but in new to both Python and ZAProxy

**Comment by psiinon** [comment]
@limquanheng I'm confused - wheres it calling "zap.spider.status()" ?
It looks to me like its calling "zap.spider.status(scanid)" which I think is correct.

**Comment by thc202** [comment]
Closing, insufficient evidence.

**Comment by thc202** [comment]
For the record the example works with the latest version (as of writing 0.0.9).

Also, for up-to-date examples refer to:
https://github.com/zaproxy/zap-api-python/tree/master/src/examples
