### ISSUE TITLE
Python API library needs to be updated for API key requirement in safe operations

### ISSUE THREAD

**Issue by limquanheng** [zaproxy/zaproxy#3342]
Noted that the Python library I was using did not send the API key for some functions eg. spider.status(), returning a "bad status" error from the requests library.

This can be bypassed with the option to not require API key for safe operations.

**Comment by thc202** [comment]
You need to pass the API key in the constructor:
```Python
apikey = 'changeme' # Change to match the API key set in ZAP, or use None if the API key is disabled
zap = ZAPv2(apikey=apikey)
```
There's an up-to-date example in:
https://github.com/zaproxy/zap-api-python/tree/master/src/examples
