### ISSUE TITLE
OpenAPI -  support ValueGenerator

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#3344]
The OpenAPI add-on currently hard codes the values it uses for form parameters, meaning that it will fail to explore sites that require specific values.
It should be enhanced to use the new [ValuGenerator](https://github.com/zaproxy/zaproxy/blob/develop/src/org/zaproxy/zap/model/ValueGenerator.java) interface which will allow the user to change the values using the [Form Handler](https://github.com/zaproxy/zap-extensions/wiki/HelpAddonsFormhandlerFormHandlerHelp) add-on.

**Comment by psiinon** [comment]
For info - have got this working, just need to tidy up:)

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#924.
