### ISSUE TITLE
the url disappear when i click it

### ISSUE THREAD

**Issue by junmoxiao** [zaproxy/zaproxy#3351]
![testtest1](https://cloud.githubusercontent.com/assets/9711902/24577044/23bbdaca-16f9-11e7-9012-67be1b3ff712.png)
![testtest2](https://cloud.githubusercontent.com/assets/9711902/24577045/27b9a742-16f9-11e7-8e71-57f2ae199f8b.png)

as the picture i uploaded above,when i click the url , it disappeared.

**Comment by junmoxiao** [comment]
i use mac , the same problem appear both in dmg and crossplatform version.

**Comment by thc202** [comment]
Reopening per https://github.com/zaproxy/zaproxy/pull/3376#issuecomment-294286944.

**Comment by thc202** [comment]
There's confirmation that the issue is fixed, https://github.com/zaproxy/zaproxy/pull/3420#issuecomment-295377299.
