### ISSUE TITLE
ZAP API View:contextList method returns a string instead of JSON list

### ISSUE THREAD

**Issue by asadasivan** [zaproxy/zaproxy#3353]
Issue:
ZAP API View:contextList method does not return a proper JSON list of values. It returns a string instead of a list. For example: If I have a context ZAP then list context method return value looks like this : {"contextList":"[Default Context, ZAP]"} but It should have been {"contextList":["Default Context", "ZAP"]}. Looks like instead of returning a list it is returning a string.
Note: 
Compare methods that returns scan policy names where the return type is a list instead of string.

**Comment by thc202** [comment]
Yes, the type is not the expected (there are couple of API endpoints with same/related problem), but fixing it now will break existing clients/consumers that are already consuming the value as is, guess we could create another endpoint or just break them(?).

**Comment by asadasivan** [comment]
But the problem is that it misses the consistency. I think new users will get affected. Also any point of time when the fix is release it is going to break existing clients / users. If we feel that we are not going to fix then it makes sense. But if we plan to move forward to ensure consistency then we should fix it on the next release. But I leave it to the project lead to make a call.
