### ISSUE TITLE
Enhancement: Options Panel Filter

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#3358]
This idea came from an email thread:

Quote @kingthorin:
>I've also been thinking in both the context configuration tree and more specifically the options panel it'd be awesome if we had a filter. For example in the options panel type local or proxy and the tree is filtered to only show "Local Proxy". Initially this only needs to be based on tree entries, down the road I can see users wanting to be able to filter/search specific options themselves.

Quote @psiinon:
>The options filter/search could be tricky to implement, but would be really useful to users.
If we have to make a set of core changes to enable it, then maybe we should create a (set of) class(es) which represents an option, in a similar way to how we represent API end points.
This might allow us make config screens much easier to produce - most of them could be generated on the fly automatically which a small number of custom ones for more complex interfaces.
It would also allow us to expose the config values via the UI, ie the ones that can be specified via the '-config' cmdline option.

**Comment by kingthorin** [comment]
Some code refs I dug up tonight:
http://blue-walrus.com/2011/03/swing-filtered-tree-just-like-in-eclipse/
https://github.com/zaproxy/zaproxy/pull/2341/files
http://www.adrianwalker.org/2012/04/filtered-jtree.html

Also note `AbstractParamPanel.getJSplitPane()` returns an `AbstractParamContainerPanel` which has methods such as `printTree()` which uses an enumeration to iterate and print.

**Comment by denniskniep** [comment]
Hi,
I like this idea an started to build something :). Can someone assign the issue to me?

Here is a first look: 
![poc_zap_searchoptions](https://user-images.githubusercontent.com/3629463/33789559-a7b62e52-dc79-11e7-902f-4b6b37d07639.gif)

**Comment by thc202** [comment]
Done.

Looks cool! May I suggest adding the filter/search text field to above the tree?

**Comment by denniskniep** [comment]
Thanks.
Sure, now on my todo :+1:

**Comment by kingthorin** [comment]
@denniskniep this PR might give you some ideas related to what @thc202 is suggesting:
https://github.com/zaproxy/zaproxy/pull/2341

**Comment by denniskniep** [comment]
@kingthorin you said:
> [...] in the options panel type local or proxy and the tree is filtered to only show "Local Proxy".

My implementation looks a bit different (see the gifs in the PullRequest). It only highlights the findings. Is this okay for you or should it be filtered anyway?

> to be able to filter/search specific options themselves
The current solution already provides the ability to search for a string in all child controls.

@psiinon you said:
>  [...] should create a (set of) class(es) which represents an option, [...] This might allow us make config screens much easier to produce - most of them could be generated.
That is not tackled by the implementation. Maybe we should extract this into a new issue?

**Comment by kingthorin** [comment]
@denniskniep the implementation in the gifs looks good to me.
