### ISSUE TITLE
Missing Help details Options Connection screen

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#3359]
https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsOptionsConnection

Doesn't have any details as to how the "Default User Agent" is used, or info on the "Security Protocols" section.

**Comment by thc202** [comment]
The "Default User Agent" was addressed recently (zaproxy/zap-core-help#84). I'll document the "Security Protocols" (my fault for not doing that in the day).

**Comment by kingthorin** [comment]
Sorry @thc202, I thought I had looked at that PR before 2.6.0 went out. Thanks!

**Comment by thc202** [comment]
@kingthorin could this issue be closed with the changes merged? Or, it's still something missing?

**Comment by kingthorin** [comment]
Seems good to me, thanks!

**Comment by thc202** [comment]
Great, will regenerate the wiki pages once zaproxy/zap-core-help#86 gets merged (to add the option included in 2.6.0).

**Comment by thc202** [comment]
Wiki should show the latest updates.
