### ISSUE TITLE
Spider Messages View Includes Underused Tags Column

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#3363]
I just noticed that when viewing messages in the spider there's a Tags column but it's almost always empty (might be a timing/redraw issue?). If I copy a URL from the spider messages table and access it via a browser it gets tagged in the history panel as expected....

Also the context menu in the spider messages table/panel doesn't have an option to add or edit Tags either.

**Comment by thc202** [comment]
The tags are only shown if the message has alert(s), at the moment there's no event/notification of tags added (currently relying on the alert events).
