### ISSUE TITLE
Enhancement: Additional Global Exclude default patterns

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#3365]
Food for thought ... re: <sub>https://github.com/zaproxy/zaproxy/blob/efce236ddf6f89516de6cd0592e22372149e0e05/src/org/zaproxy/zap/extension/globalexcludeurl/GlobalExcludeURLParam.java#L63</sub>

- [x] `^https?://detectportal\.firefox\.com.*$` Firefox mechanism for detecting captive portals.
- [x] `^https?://www\.google-analytics\.com.*$` Google analytics....nuff said.
- [x] `^https?://ciscobinary\.openh264\.org.*$` Firefox codec download (https://support.mozilla.org/t5/Firefox/Where-is-a-check-that-http-ciscobinary-openh264-org-openh264-is/m-p/1316497#M1005892)
- [x] `^https?://fonts.*$` This might be too generic, I built it broadly after seeing fonts.googleapis.com and fonts.gstatic.com used...

**Comment by kingthorin** [comment]
I've definitely going to do a PR for the first 3. What are everyone's thoughts on the 4th one? Since they're user enable-able does it matter that it might be too broad?

**Comment by psiinon** [comment]
I'm fine with the fonts one:)

**Comment by thc202** [comment]
Same here.
