### ISSUE TITLE
Cannot open https website for semi automatic testing

### ISSUE THREAD

**Issue by angshujit** [zaproxy/zaproxy#3378]
Hello,
I just installed ZAP Version 2.6.0 for Windows. I want to test our application which is hosted in server with https. Steps that I have taken so far are as follows:

1. Open ZAP. From menu, open Tools -> Options -> Dynamic SSL Certificate. Here it is already showing a certificate. I save the certificate in my desktop.
2. I am trying to use Chrome Version 57.0.2987.133 to test the application. I Open Chrome and then Customize and control Google Chrome -> Settings -> Show Advance Settings -> Manage Certificate. A dialog box opened from where I import the certificate that I saved in my desktop and then click on OK.
3. Then in Setting page itself I clicked on Change proxy settings -> LAN settings -> Then "Check" the Use a proxy server for your LAN checkbox. In the address text box I entered "localhost" and in the Port text box I entered 8080  (These two values are mentioned in ZAP local Proxy settings). Then I clicked on Advance button where I "Check" Use the same proxy server for all protocols checkbox. Clicked on OK consecutively in all dialog boxes.

Now when I am trying to open my website it is not opening and it is saying:

> Your connection is not private
> 
> Attackers might be trying to steal your information from XXXXXX.com (for example, passwords, messages, or credit cards). NET::ERR_CERT_AUTHORITY_INVALID

Same thing is happening even when I am trying to open google.com as well.

Can you please help me and let me know what I am missing.

**Comment by kingthorin** [comment]
Chrome on Windows uses the OS certificate store. 
https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsOptionsDynsslcert#windows--internet-explorer

**Comment by angshujit** [comment]
Thank you for this. It worked. I then tried with Firefox. Setting up in Firefox is much easy.

**Comment by thc202** [comment]
Thanks for letting us know.
