### ISSUE TITLE
typo in the install4j installation wizard

### ISSUE THREAD

**Issue by gmaran23** [zaproxy/zaproxy#3384]
Uninstall Old Version
Uninstall Old Version

An older version was detected. The older version must be installed before continuing with installation. Press uninstall to unistak and continue...

-----------------------------------

I doubt the work unistak was put there intentionally.

![image](https://cloud.githubusercontent.com/assets/7804480/24829213/8ad34de6-1c8b-11e7-8397-dcf20e70db4c.png)

**Comment by thc202** [comment]
Thanks, it should be `uninstall`.

**Comment by thc202** [comment]
This was fixed locally, pending a pull request.
