### ISSUE TITLE
push python api client 0.0.9 tag

### ISSUE THREAD

**Issue by g-k** [zaproxy/zaproxy#3388]
The download URL from https://pypi.python.org/pypi/python-owasp-zap-v2.4 points to:

https://github.com/zaproxy/zap-api-python/releases/tag/0.0.9 

which 404s

Should be able to fix it by running the following in zap-api-python:

```
git checkout 786993f98c679a87fb17c4e06b5f5589df5d831d # commit where version changed to 0.0.9
git tag 0.0.9
git push origin --tags
```

**Comment by thc202** [comment]
I'd suggest `64fae0ff4b092bcfe70de3e389dc9e9274aaffd4`, when the changes landed in the main branch.

**Comment by thc202** [comment]
Tag pushed.
