### ISSUE TITLE
Add option to spider anonymously with a session

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#3395]
The spider (trad, maybe ajax too?) by default makes completely new requests, ie it does not maintain any session. It will only maintain a session if you spider as a user, force the session or enable session tracking (which cant be set from the cmdline #3394 )
A new option to spider anonymously while maintaining the session (just in the spider) would be very useful.
It should probably even be the default.

**Comment by thc202** [comment]
The AJAX Spider accepts cookies by default (from default behaviour of the browsers).
