### ISSUE TITLE
Enhance DOM XSS scanner addon to use Selenium addon

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#3396]
Ref: https://groups.google.com/forum/#!topic/zaproxy-develop/-CmXy0Zl7LU

The DOM XSS scanner doesn't work with up-to-date versions of Firefox (ESR 45 still works). It should be enhanced to use the Selenium Addon like the Ajax Spider does.

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#987.
