### ISSUE TITLE
Share custom variables between scripts

### ISSUE THREAD

**Issue by comibat** [zaproxy/zaproxy#3402]
I want to be able to share some custom variables between scripts.
usecase:
I'm using Active Rules script to place a payload, and i want to be able to detect it using HTTP Sender.
ATM there is no other way to share the data between those two scripts except for using global ScriptVars.
I'd like to be able to use custom variables between those two (and the rest of the scripts as well) like strings, lists, maps etc.

Here is the suggestion from @psiinon "Maybe we should look at providing an interface for storing arbitrary data in the db - that would be more scalable."

**Comment by thc202** [comment]
Thanks for raising the issue.

**Comment by comibat** [comment]
np. I'll see if i find some time to suggest the solution as well (or even commit something); for not the issue it is.

**Comment by kingthorin** [comment]
Couldn't `kb` be used for this?

**Comment by thc202** [comment]
A global `kb`? Yes, that would work, but probably better to use/update `ScriptVars`?

**Comment by kingthorin** [comment]
You're right, just expanding the idea if global vars a bit is probably best.
