### ISSUE TITLE
ZAP Version 2.6.0 installs but fails to launch when selected in macOS Sierra.

### ISSUE THREAD

**Issue by wasp33b** [zaproxy/zaproxy#3421]
ZAP Version 2.6.0
macOS Sierra Version 10.12.4
Java Version 8 Update 121 (build 1.8.0_121-b13)

ZAP installs but fails to launch when selected. A question mark appears on the dock.

**Comment by kingthorin** [comment]
Unfortunately this is a known issue:
https://twitter.com/psiinon/status/851388447428403200
https://groups.google.com/forum/#!topic/zaproxy-users/joB-I0qfnWs

**Comment by psiinon** [comment]
Did you get a message about the installer not being signed?

What happens if you run:

    /Applications/ZAP\ 2.6.0.0.app/Contents/MacOS/OWASP\ ZAP.sh

All help with this issue appreciated - we're not Mac experts and only have one system to test on (a Mac Mini on which ZAP installs fine:/)

**Comment by wasp33b** [comment]
I didn't get a message about the installer not being signed when installing.

After running:
/Applications/ZAP\ 2.6.0.app/Contents/MacOS/OWASP\ ZAP.sh

I got:
/Applications/ZAP 2.6.0.app/Contents/Java/zap.sh: line 19: Get: command not found
Exiting: ZAP requires a minimum of Java 7 to run, found 1.6.0_65

Which was strange because I had a newer Java version. I also checked the updates and there was a newer Java version (Version 8 Update 131 build 1.8.0_131-b11) so I installed it and repeated the steps above with the same result.

**Comment by psiinon** [comment]
Thanks - thats really helpful.
We've found 2 problems, one minor and one which we think is the main one.
The minor one is a missing '#' at the start on line 19 of /Applications/ZAP\ 2.6.0.app/Contents/MacOS/OWASP\ ZAP.sh
The major problem is that the exe bit hasnt been set on the bundled java exes :(
Can you try running the following command as root:

`chmod +x /Applications/ZAP\ 2.6.0.app/Contents/PlugIns/jre1.8.0_121.jre/Contents/Home/bin/*`

If you like you can also add a '#' to the start of line 19 of /Applications/ZAP\ 2.6.0.app/Contents/MacOS/OWASP\ ZAP.sh

Then try starting ZAP again and letting us know what happens.
Many thanks

**Comment by wasp33b** [comment]
It works now! 

Did the major fix first and it ran from the app icon.
Did the minor fix and it ran by running the zap.sh file.

Reinstalled it and did the minor fix first and it gave me the same error 
but after adding the major fix both the app icon and the zap.sh file work.

The question mark still appears in the dock but you can select 'Remove from Dock'.

Thanks, good job!

**Comment by psiinon** [comment]
Thanks for letting us know! We'll fix those things and generate a new Mac installer.

**Comment by psiinon** [comment]
We have a new version of the installer: https://github.com/zaproxy/zaproxy/releases/download/2.6.0-mac-test/ZAP_2_6_0_macos.dmg - can you give it a go and let us know if that works? Many thanks

**Comment by wasp33b** [comment]
It installs and ZAP boots up.

Only thing is after the installation a question mark (referring to zap.sh) appears and remains in the dock even after quitting ZAP (I can right click it and select 'Remove from Dock' to remove it though).

**Comment by psiinon** [comment]
This is hopefully now fixed in the new version of the Mac installer.
If there are any other problems with the new installer (like the question mark) then please raise new issues.
Thanks.
