### ISSUE TITLE
RPM - Java package name in required dependencies seems wrong

### ISSUE THREAD

**Issue by sbattistin** [zaproxy/zaproxy#3434]
It seems that the requirement for Java JDK 1.8.0 is wrong in the REQUIRES entry of the RPM file.

Java 1.8.0 (OpenJDK) is installed in my machine but the package name has dots and not underscores.

The package name in the REQUIRES probably needs to be changed from **java-1_8_0-openjdk** to **java-1.8.0-openjdk**.

In particular when trying to install the package on Fedora 25 this is the error:
```
user@domain: ~ > sudo dnf install owasp-zap-2.6.0-6.1.noarch.rpm
Error: nothing provides java-1_8_0-openjdk needed by owasp-zap-2.6.0-6.1.noarch
(try to add '--allowerasing' to command line to replace conflicting packages)
```

This happens from both the downloaded RPM and repository.

**Comment by thc202** [comment]
Thanks.

**Comment by cabelo** [comment]
Repaired and tested in Fedora 25. Sorry, there are too many distributions for .

**Comment by thc202** [comment]
@cabelo thanks!

@sbattistin could you try the new package?

**Comment by sbattistin** [comment]
@thc202, @cabelo: Now the package installed without issues.

Thanks both! :)

**Comment by thc202** [comment]
Cool, thanks for letting us know!
