### ISSUE TITLE
Log Exception when the provided config file could not be parsed

### ISSUE THREAD

**Issue by rain0r** [zaproxy/zaproxy#3440]
Currently, when the exisiting config file `config.xml` could not be parsed, ZAP uses its own config file as it copies a default `config.xml` in the working directory (this can be provided by `-dir`).

That's fine, the problem is, the user won't get informed about that. I suggesst logging this exception and present the user a warning message. 

This is the [corresponding code](https://github.com/zaproxy/zaproxy/blob/develop/src/org/parosproxy/paros/Constant.java#L556):

```
...
} catch (ConfigurationException | ConversionException | NoSuchElementException e) {
	            //  if there is any error in config file (eg config file not exist, corrupted),
	            //  overwrite previous configuration file 
	            // ZAP: changed to use the correct file
	            copier.copy(getPathDefaultConfigFile().toFile(), new File(FILE_CONFIG));
	            
	        }
```

**Comment by thc202** [comment]
Fixed in #3483.
