### ISSUE TITLE
ProxyDisclosure Rule References Issue

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#3441]
It would be great if the ProxyDisclosure scan rule had some actually references instead of `???`. Or the `getReference()` method should be reworked.

<sub>Ref:
https://github.com/zaproxy/zap-extensions/blob/alpha/src/org/zaproxy/zap/extension/ascanrulesAlpha/resources/Messages.properties#L109
https://github.com/zaproxy/zap-extensions/blob/alpha/src/org/zaproxy/zap/extension/ascanrulesAlpha/ProxyDisclosureScanner.java#L158-L160
</sub>

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#864.

**Comment by thc202** [comment]
Released in version 19 of Active scanner rules (alpha) add-on.
