### ISSUE TITLE
Enhancement: Add ability to export a Site Map via Context Menu

### ISSUE THREAD

**Issue by davewichers** [zaproxy/zaproxy#3446]
I don't see any easy/good way to export a sitemap from within ZAP's UI.

I.e., I want to click on a folder in the sitemap and export it and ALL the URLs below it.

I see there is a Copy URLs to clipboard function, but it doesn't get all the lower level entries. Just the ones that are selected (i.e., if you select multiples you get those, but still not ALL of the leaves in the tree).

I would like/imagine 2 things:

1) Implement an API that accepts a URL and returns ALL the URLs from there down in the sitemap.
2) Be able to right click on a node in the Site Map and have an 'Export Site Map' option that does the same thing (maybe using the API :-) ).

**Comment by kingthorin** [comment]
Check the report menu, there are URL export items there

**Comment by thc202** [comment]
This one should do that:
https://github.com/zaproxy/zap-core-help/wiki/HelpUiTlmenuReport#export-selected-urls-to-file

I guess we could add that to the context menu too (to export to File and to clipboard).

**Comment by davewichers** [comment]
Ah yes. This is exactly what I want, and simply couldn't find it. Can we a)
add it to the right click menu in the SiteMap and b) is it available as an
API? I couldn't find it in the built in WebApp that comes with ZAP.

Thanks, Dave
