### ISSUE TITLE
How to handle multiple request sequentially in OWASP ZAP

### ISSUE THREAD

**Issue by paulbaboo** [zaproxy/zaproxy#3448]
How to handle multiple request sequentially in OWASP ZAP

1.i need to test a functionality which involves 2 URL
2.the 2 url dependent on each other  and result of the first url response is required for the submission of the second so to cover the complete cycle of that fucntionality
3.when i run Security scan, only 1 url is been scanned ie the frst one where no validation is present,all the validation are covered when the second url is submitted

How to structure the request been sent instead of random request sent???

Can anyone help me on this ,on how to cover this on OWASP scan

**Comment by kingthorin** [comment]
Goto the marketplace:
![](https://github.com/zaproxy/zap-extensions/wiki/images/zap-screenshot-browse-addons.png)

Install the Sequence addon.

Unfortunately there isn't currently any help resources for the addon (there's an outstanding [issue](https://github.com/zaproxy/zaproxy/issues/2191) for that), however, this might help: https://zapmultistep.wordpress.com/

If you have further questions please post them to the [User Group](https://groups.google.com/forum/#!forum/zaproxy-users) as that's a much better place to deal with them than Github tickets.
