### ISSUE TITLE
CSRFcountermeasures scanner handling multiple forms

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#3449]
Review: https://github.com/zaproxy/zap-extensions/pull/570/files consider `shouldPassWhenSecondFormHasAKnownCSRFToken()` the form without should probably cause an alert.

https://github.com/zaproxy/zap-extensions/blob/beta/src/org/zaproxy/zap/extension/pscanrulesBeta/CSRFCountermeasures.java

**Comment by kingthorin** [comment]
Current iteration of the UnitTests `shouldNotRaiseAlertWhenSecondFormHasAKnownCSRFToken`

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#1020.
