### ISSUE TITLE
nodejs zap.ascan.scan   errors related to \node_modules\zaproxy\index.js:93

### ISSUE THREAD

**Issue by gitDimaA** [zaproxy/zaproxy#3450]
Hi, 
I started to automating security testcases with nodejs and zap api. . 
```
// start ZAP with cmd:
//start "ZAP" javaw -jar "C:\Program Files\OWASP\Zed Attack Proxy\zap-2.6.0.jar" -config database.recoverylog=false -config api.key=**removed**

//in the testscript:
var ZapClient = require('zaproxy');  
var options = { proxy: 'http://localhost:8080' };  
var zap  = new ZapClient(options);

//In the function:
zap.ascan.scan(test_url,apikey, function(err, res, body) {
 if(err){
		logger.info('Error found from scan  ' + err);                            
		callback(err, 1);
 }
logger.info('\n  do something to ascan scan the site \n');
// logger.info('Ascan progress %: '+ zap.ascan.status() + ' \n');  
.....
```

Result: when running the script:
```
...\node_modules\zaproxy\index.js:93
      callback(err);
      ^
TypeError: callback is not a function
    at Request.handleResponse [as _callback] (...\node_modules\zaproxy\index.js:93:7)
    at self.callback (...\node_modules\zaproxy\node_modules\request\request.js:121:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.self.clientErrorHandler (...\node_modul
es\zaproxy\node_modules\request\request.js:230:10)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:256:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
```

Is there any workaround this issue?  If there is an example of using zapproxy api with nodejs for main functionalities such as ascan and spider please share it.

Thank you!

<sub>Edit: By @kingthorin for formatting and content.</sub>

**Comment by UmerIftikhar** [comment]
any possible solutions?

**Comment by thc202** [comment]
I don't think so, that API client is not actively maintained.

**Comment by thc202** [comment]
Not sure if that helps but the API key is not fully supported by that client (it does not send the API key for all endpoints), either the API key needs to be disabled or the option Options > API > Do not require an API key for safe operations.

Refs:
https://github.com/zaproxy/zaproxy/wiki/FAQapikey
https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsOptionsApi#do-not-require-an-api-key-for-safe-operations

**Comment by UmerIftikhar** [comment]
Thanks a lot.
Yeah I had to do something like this to make it work:  
```
zaproxy.spider.scan(target, '', '', function (err, resp) {
  console.log(resp); 
});  
```
Not a very elegant way to use a Lib.

**Comment by valvic66** [comment]
Not too much documentation for Node.js :(

**Comment by Edza** [comment]
Thanks for this issue. It's the only documentation I can find forthe node-zaproxy. If you could post your full script that would be beyond awesome.

**Comment by thc202** [comment]
A new version of the API has been released, the README has usage examples: https://github.com/zaproxy/zap-api-nodejs/#usage

If you have any further usage questions please let us know through the OWASP ZAP User Group: https://groups.google.com/group/zaproxy-users
