### ISSUE TITLE
Add "Remove from site tree" in search

### ISSUE THREAD

**Issue by NVolcz** [zaproxy/zaproxy#3452]
Currently the only way to remove nodes in the sites tree is to select/multi-select. This becomes cumbersome when trying to trim error nodes.

**Comment by kingthorin** [comment]
I was looking through 2.10 milestone issues tonight and noticed this one. I didn't notice it was assigned. (I've only futzed with it for 10 mins).

I made the following quick change:

```diff
diff --git a/zap/src/main/java/org/zaproxy/zap/extension/history/PopupMenuPurgeHistory.java b/zap/src/main/java/org/zaproxy/zap/extension/history/PopupMenuPurgeHistory.java
index b8e16b8..79eed6d 100644
--- a/zap/src/main/java/org/zaproxy/zap/extension/history/PopupMenuPurgeHistory.java
+++ b/zap/src/main/java/org/zaproxy/zap/extension/history/PopupMenuPurgeHistory.java
@@ -41,7 +41,7 @@
 
     @Override
     public boolean isEnableForInvoker(Invoker invoker, HttpMessageContainer httpMessageContainer) {
-        return (invoker == Invoker.HISTORY_PANEL);
+        return (invoker == Invoker.HISTORY_PANEL || invoker == Invoker.SEARCH_PANEL);
     }
 
     @Override
```

However, upon deleting something (using the context menu delete which is now showing in Search) then revisiting one of the deleted resources received the following exception:

```
163666 [ZAP-ProxyThread-21] WARN org.parosproxy.paros.extension.history.ProxyListenerLog  - Failed to check if message already exists:
org.parosproxy.paros.network.HttpMalformedHeaderException: No history reference for id 5 type=1
	at org.parosproxy.paros.model.HistoryReference.getHttpMessage(HistoryReference.java:449)
	at org.parosproxy.paros.extension.history.ProxyListenerLog.onHttpRequestSend(ProxyListenerLog.java:101)
	at org.parosproxy.paros.core.proxy.ProxyThread.notifyListenerRequestSend(ProxyThread.java:739)
	at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(ProxyThread.java:545)
	at org.parosproxy.paros.core.proxy.ProxyThread.run(ProxyThread.java:335)
	at java.base/java.lang.Thread.run(Thread.java:834)
163666 [ZAP-ProxyThread-23] WARN org.parosproxy.paros.extension.history.ProxyListenerLog  - Failed to check if message already exists:
org.parosproxy.paros.network.HttpMalformedHeaderException: No history reference for id 3 type=1
	at org.parosproxy.paros.model.HistoryReference.getHttpMessage(HistoryReference.java:449)
	at org.parosproxy.paros.extension.history.ProxyListenerLog.onHttpRequestSend(ProxyListenerLog.java:101)
	at org.parosproxy.paros.core.proxy.ProxyThread.notifyListenerRequestSend(ProxyThread.java:739)
	at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(ProxyThread.java:545)
	at org.parosproxy.paros.core.proxy.ProxyThread.run(ProxyThread.java:335)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by psiinon** [comment]
PopupMenuPurgeHistory deletes the requests from the History tab.
PopupMenuPurgeSites deletes the requests from the Sites tree - the same change to that file has the desired effect and is more logical (I think).
Selecting deleted urls in the Search tab just gives empty Requests/Responses and doesnt log an error.
However it might be better to rename the popup from just 'Delete' to 'Delete from Sites Tree' and to change the 'are you sure' dialog to say that you'll need to run the serch again to update the results, at least if its invoked from the Search tab.
Sound reasonable? I should be able to do that fairly quickly...

**Comment by kingthorin** [comment]
Seems good to me.

**Comment by thc202** [comment]
Both pop up menus delete from History and Sites, the difference between them is that `PopupMenuPurgeSites` deletes nodes rather than just specific messages (i.e. deletes the selected messages and, possibly, the "children" messages). IMO the behaviour of the pop up menu in the Search tab should be the same as in the History, just delete the selected messages not the associated nodes (which might be more messages than the user selected).

About the rename, the messages removed from the Sites are intended to be removed from all places (e.g. they are removed from the History and Spider results) so the new name would not be accurate. The Search should/can be changed to listen to the deletion of the messages and remove them accordingly.

**Comment by psiinon** [comment]
Well, the issue title is "Remove from site tree" and tbh I think thats a more useful option.
The History tab is our record of what happenned.
The Sites tree is our model of the application.
Removing requests from just the history tab (on its own) doesnt really affect much, so is more a visual thing.
Removing nodes from the Sites Tree is much more impactful as that changes ZAPs view of the app.
I dont think removing specific history URLs makes much sence, at least if that doesnt remove the corresponding Site Tree nodes.
I think that if a user selected one request from the search results and deleted it then they would be very surprised if that didnt remove the corresponsing Sites Tree node. I mean - whats the pont? :)

**Comment by thc202** [comment]
Deleting from the History deletes from the Sites as well, the same would apply to Search tab. It's true that if you delete just one message of a node than has past history the whole node is not deleted, but in the reported case the search would return all messages of the node not just one so deleting all messages would delete the node.

**Comment by psiinon** [comment]
I think that would be confusing to many users.
Maybe one to hold off on then...
