### ISSUE TITLE
Bug: Paused Scans Wiped Out when Persisting a Session

### ISSUE THREAD

**Issue by davewichers** [zaproxy/zaproxy#3456]
If you pause a scan, and then Save a session with 'Persist Session' when the save is done, the paused scan is 'gone'. Seems like it shouldn't have any affect on an active scan. If there is no easy way to fix this, please at least warn the user that the currently active scan is going to get wiped out so they can make the correct choice for their situation.

**Comment by thc202** [comment]
Same for the spider.

**Comment by thc202** [comment]
ZAP will now inform of the active actions before applying the session change.
