### ISSUE TITLE
Enhancement: Prescan Output is Confusing. Please Clarify.

### ISSUE THREAD

**Issue by davewichers** [zaproxy/zaproxy#3459]
When starting a big active scan, the scan starts to run, but you don't see the test categories be displayed for a long while (like 5+ minutes). So you simply see the counter counting up, but not in any category as no categories are displayed yet. This is confusing. Can this be improved to be more clear and/or make sure all the scan categories get displayed immediately before this is shown and another prescan row displayed before them (or something)?

From thc202: "Yes, that's a pre-scan functionality, it sends some requests to try to guess/obtain the "not found" pages. Since that's not a scanner it's not shown in the progress dialogue."

**Comment by psiinon** [comment]
I guess we could flag this as a 'Prescan' or something similar?

**Comment by thc202** [comment]
Yeah, we can add a new entry for that.
