### ISSUE TITLE
Enhancement: Provide help finding the Log directory in the UI

### ISSUE THREAD

**Issue by davewichers** [zaproxy/zaproxy#3460]
I know this page exists: https://github.com/zaproxy/zaproxy/wiki/FAQconfig
But when I look for the Win 7/8 directory it says ZAP's logs are supposed to be in, there is no such directory. To make it easier for users, can you add a command to the Help menu that tells the user the current Log directory that ZAP is using?

Maybe something like: Help-->Log Directory 

And this opens a dialog that displays the log directory path where you can then copy that path and ideally also open a command prompt into that directory.

I tried to use the API that returns the home directory, but it returns the directory where the current session is persisted, not the log directory.

**Comment by thc202** [comment]
The API was changed to also expose that path (#3367).

**Comment by kingthorin** [comment]
@davewichers @thc202 `/core/view/zapHomePath` in weekly or dev (future 2.7.0).

**Comment by davewichers** [comment]
Excellent. So it should be easy to add that info to the Help Menu??  It turns out that my home directory was mapped to a network share, so even though the documentation says it should be in: C:\Users\<username>\OWASP ZAP - it was actually somewhere like Y:\dwichers\OWASP ZAP. Its situations like this that making it easy to get from the GUI would be very helpful. Plus it would presumably 'just work' regardless of which OS and which version you were using.

**Comment by thc202** [comment]
Yeah, we need to update the wiki page to mention that ZAP uses the home directory of the user running ZAP.

(Also, in weekly/dev ZAP's home directory is logged/outputted during start up.)

**Comment by kingthorin** [comment]
- [ ] Add help menu item to display ZAP's home directory.
- [ ] Update the core help.

**Comment by psiinon** [comment]
@davewichers So your home directory was mapped to a network share? We should update the FAQ to note that as thats something thats out of our control

**Comment by psiinon** [comment]
A menu just for the home directory is probably a bit over the top - I cant see that many people using it.
However a menu item for generating diagnostics (including the home dir) which people can use when submitting issues could be more widely useful :)
Unless I'm missing a really obvious reason as to why users might need to know the default ZAP dir?

**Comment by kingthorin** [comment]
Because that's where logs and configuration are stored.

Note: I've already put together a PR for this. It adds a menu item to the Help menu, when used it opens a dialog that displays the path with an Open button and an Ok button. The user can either "Open" the directory (tested Win and Kali) or highlight the value and use it however they see fit. 

Future? If wanted this could be enhanced to include a textfield that displays ZAP Version, Java Environment details, etc.

**Comment by davewichers** [comment]
This sounds great. Thanks for implementing.

**Comment by davewichers** [comment]
I wanted this for diagnostic purposes. I.e., I was trying to find the logs
for ZAP and couldn't find them. So if you want to add more diagnostic info
to that same thing, that's great.
