### ISSUE TITLE
Enhancement: Browse API Doesn't work when browser isn't using ZAP as proxy

### ISSUE THREAD

**Issue by davewichers** [zaproxy/zaproxy#3461]
When you select Tools-->Browse API, ZAP opens your browser at: zap/. But this doesn't work if you don't have your browser configured to use ZAP as its proxy.

Can this function be enhanced to figure out where ZAP is actively listening and direct your browser there? That way it will work either way.

**Comment by kingthorin** [comment]
Ref: https://groups.google.com/forum/#!topic/zaproxy-users/Glro_PlsJLU
