### ISSUE TITLE
Lots of WARN  PropertyDeserializer - no property from null, null warnings, using the OpenAPI add-on (via import, Python API)

### ISSUE THREAD

**Issue by stephendonner** [zaproxy/zaproxy#3464]
Running:
```sdonner-17447:zaproxy sdonner$ docker run -v $(pwd):/zap/wrk/:rw -t stephendonner/zaproxy:1.0 zap-baseline.py --active_scan -t http://petstore.swagger.io -d -j -z "-config api.disablekey=true" -m 8```

With the following forked changes (to introduce active scanning + OpenAPI support): https://github.com/zaproxy/zaproxy/compare/zaproxy:d263fcf...stephendonner:fd74dd5, I am seeing a lot of these in the logfile:

**```2017-05-01 22:31:44,998 [ZAP-Import-OpenAPI-1] WARN  PropertyDeserializer - no property from null, null, {ENUM=null, TITLE=null, DESCRIPTION=null, DEFAULT=null, PATTERN=null, DESCRIMINATOR=null, MIN_ITEMS=null, MAX_ITEMS=null, MIN_PROPERTIES=null, MAX_PROPERTIES=null, MIN_LENGTH=null, MAX_LENGTH=null, MINIMUM=null, MAXIMUM=null, EXCLUSIVE_MINIMUM=null, EXCLUSIVE_MAXIMUM=null, UNIQUE_ITEMS=null, EXAMPLE=null, TYPE=null, FORMAT=null, READ_ONLY=null, VENDOR_EXTENSIONS={}}```
**

**Comment by stephendonner** [comment]
[zap-log.txt](https://github.com/zaproxy/zaproxy/files/968968/zap-log.txt)

**Comment by stephendonner** [comment]
Any ideas, @psiinon?

**Comment by psiinon** [comment]
@stephendonner Unfortunately the OpenAPI lib we use doesnt produce very helpful error messages :( However I was using http://petstore.swagger.io/v2/swagger.json to test the add-on and didnt notice these warnings. I'll have another look...

**Comment by stephendonner** [comment]
I just noticed I had passed in http://petstore.swagger.io/ to the command-line argument (target), but for the OpenAPI portion, I've hard-coded (for now) the Kinto dev Swagger/OpenAPI endpoint, here: https://github.com/stephendonner/zaproxy/blob/fd74dd5c51b4c009d72a88fda7849deb7f396ba8/build/docker/zap-baseline.py#L416

I've updated the attached logfile to reflect the new, correct run, of:

docker run -v $(pwd):/zap/wrk/:rw -t stephendonner/zaproxy:1.0 zap-baseline.py --active_scan -t https://kinto.dev.mozaws.net/v1/ -d -j -z "-config api.disablekey=true" -m 8

**Comment by thc202** [comment]
Closing, the WARNs no longer happen with latest version (14) and AFAICT the import is successful (i.e. endpoints are imported with corresponding data).
