### ISSUE TITLE
Sequence option is not working properly

### ISSUE THREAD

**Issue by paulbaboo** [zaproxy/zaproxy#3466]
![1](https://cloud.githubusercontent.com/assets/28147044/25605191/d0cd7bfc-2f26-11e7-87bc-7aa262177fdf.jpg)
I have 4 urls which has to be executed sequentially to get a proper output and I have added these 4 url to the sequence script ,but when I run active scan by checking the sequence option in the advance active scan, the OWASP ZAP is not executing the script sequentially.

Could you please help me on how run the sequence script in the correct order been set

**Comment by paulbaboo** [comment]
It would be really appreciable if someone could help me on this?

**Comment by thc202** [comment]
You need to create just one script, with all requests that belong to the sequence.

**Comment by paulbaboo** [comment]
Thank you very much for your prompt response, but i need some clarifications .

these scripts which I have added are recorded via proxy and haven't done modification to it.is that ok? can i do sequence operation with the recorded script or do i need to do any manual configuration.
Steps
1.Recorded the request via proxy settings
2.right clicked on the request and added to sequence operation under zest script
3.run active by checking the sequence tab

Is my operation correct??

**Comment by kingthorin** [comment]
@paulbaboo all of the requests related to a particular sequence should be recorded as a single sequence script.

**Comment by kingthorin** [comment]
@paulbaboo is something further needed here?
