### ISSUE TITLE
Move to using Java 8

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#3470]
As per https://groups.google.com/d/msg/zaproxy-develop/O-dLbL0-qc8/puL1RKbOEQAJ

- [x] Change zaproxy build file
- [x] Change travis configs (for oraclejdk8)
- [x] Include in a weekly release
- [x] Update zap.sh script
- [x] Update .deb package
- [x] Update docs (eg Release Notes)
- [x] Update wiki
- [x] Warn upstream projects (like Kali)
- [x] Change zap-extension build files (just before 2.7.0)
- [x] Also build using OpenJDK8 in travis #4136

**Comment by kingthorin** [comment]
FYI I booted a Kali VM this morning and it "should" be fine:
```shell
root@kali:~# uname -a
Linux kali 4.9.0-kali3-amd64 #1 SMP Debian 4.9.18-1kali1 (2017-04-04) x86_64 GNU/Linux
root@kali:~# java -version
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-4-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)
```

**Comment by psiinon** [comment]
Thanks @kingthorin :)

**Comment by kingthorin** [comment]
Given this update (https://github.com/zaproxy/zaproxy/issues/3470#issuecomment-299879901) can we mark the "warn upstream" item as completed? Are there other distros or projects we're concerned with? (ThreadFix? _____?)

**Comment by thc202** [comment]
I think so (https://software.opensuse.org/download.html?project=home%3Acabelo&package=owasp-zap is already using Java 8).

**Comment by thc202** [comment]
Closing, all tasks done.
