### ISSUE TITLE
Unclear "attribute type is unexpected" warning when importing OpenAPI definition

### ISSUE THREAD

**Issue by stephendonner** [zaproxy/zaproxy#3479]
Steps to Reproduce:

1. Launch ZAP and then File | New Session
2. Import and OpenAPI definition from a URL
3. Input http://petstore.swagger.io/v2/swagger.json and click "import"

Actual Results:

"attribute type is unexpected" appears in the Output tab

Expected Results:

Clearer error message: which attribute?
<img width="1680" alt="screen shot 2017-05-03 at 11 22 20 pm" src="https://cloud.githubusercontent.com/assets/387249/25692544/51ac4e56-3058-11e7-9605-b4c80df16c2c.png">

**Comment by stephendonner** [comment]
[zap-log.txt](https://github.com/zaproxy/zaproxy/files/975339/zap-log.txt)

**Comment by psiinon** [comment]
This isnt a ZAP error message. We'll need to work out where it comes from and raise an issue on the relevant project.

**Comment by eoftedal** [comment]
Just ran into the same problem

**Comment by kingthorin** [comment]
@eoftedal can you provide the log details? Can you provide the definition you're having issues with?

**Comment by eoftedal** [comment]
@kingthorin It's the same swagger.json file as in the original post: http://petstore.swagger.io/v2/swagger.json 
And the log only says "attribute type is unexpected" as far as I can see... Or is there a disk based log as well?

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#1205.
