### ISSUE TITLE
Zest Script execution action fails on Windows

### ISSUE THREAD

**Issue by ckarul** [zaproxy/zaproxy#3488]
The latest version (2.6.0) still has the Zest : Action : Script execution problem with Windows.
(Previously discussed here https://groups.google.com/forum/#!topic/zaproxy-users/8EdgqM8zSrQ ) 

> DEBUG: 1 Action result: test
> DEBUG: 2 Action invoke: org.mozilla.zest.core.v1.ZestActionInvoke
> java.io.IOException: Cannot run program "C:\Users\ckarul\OWASP ZAP\scripts\scripts\standalone\readToken.js": CreateProcess error=193, %1 is not a valid Win32 application
> java.lang.ArrayIndexOutOfBoundsExceptionjava.lang.ArrayIndexOutOfBoundsException  

Works fine on Linux

> DEBUG: Set zap.script.name = testCaller
> DEBUG: 1 Action invoke: org.mozilla.zest.core.v1.ZestActionInvoke

<sub>Edit: 20170505 by @kingthorin, minor formatting tweak.</sub>

**Comment by thc202** [comment]
This is being addressed in mozilla/zest#98.

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#985.
