### ISSUE TITLE
Zest script execution UI does not show the correct configuration 

### ISSUE THREAD

**Issue by ckarul** [zaproxy/zaproxy#3489]
To replicate:

- Create a Zest Script
- Right click on script,  Add Zest Action \  Action - Script
- On the UI select a script 
![image](https://cloud.githubusercontent.com/assets/28444360/25748371/d06e1ef6-3178-11e7-8d84-7723499c12d4.png) - saveToken.js
- Click Save (close screen)
-  Also Save the Zest script
- At this point the selected script should be saveToken.js
- Double click on the Action - Script node
- The UI still shows the first script (readToken) in the pull down menu
- Further testing shows that the script is actually active and executes fine, so this is just a UI issue where the correct script is not properly detected/shown by the combo box,

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#878.
