### ISSUE TITLE
Poor font rendering on linux

### ISSUE THREAD

**Issue by ksdev-pl** [zaproxy/zaproxy#3490]
Would it be possible to do something with font rendering in owasp zap on linux?

Please compare the request/response font rendering of owasp zap with burp:

![screenshot from 2017-05-05 18-02-25](https://cloud.githubusercontent.com/assets/4216259/25753951/c387df2a-31bd-11e7-8b7a-89a853929f2f.png)

![screenshot from 2017-05-05 18-00-44](https://cloud.githubusercontent.com/assets/4216259/25753961/cadab7de-31bd-11e7-990d-38c1ff2df5f4.png)

The screenshots were made on Kali xfce (but on pure Debian with gnome it looks similarly bad).

I'm using `_JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=gasp'` in `/etc/environment`. 

```
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```

I've also changed the interface font in zap (to Input Mono 16) - it looks slightly better with it.

It's hard to read the source/request/response code in zap, with better font rendering burp is much more pleasant in this regard. Shame, as zap is a great tool.

Thanks for your work.

**Comment by kingthorin** [comment]
1. I don't see anything wrong in the images you attached.
2. Duplicate? https://github.com/zaproxy/zaproxy/issues/3051

**Comment by psiinon** [comment]
For info ZAP on Fedora looks fine to me :/
Certainly doesnt look worse than any of the other apps I use on it.

**Comment by ksdev-pl** [comment]
#3051 is related to the `Dawt.useSystemAAFontSettings`. Without it the font rendering is abysmal. But with each possible flag options - I'm using the `gasp` - the request/response font rendering in owasp zap is still bad, this is the problem I'm writing about.

Here I've placed the comparison on one screenshot:

![untitled](https://cloud.githubusercontent.com/assets/4216259/25755247/7f55f68e-31c2-11e7-84e4-e69773fcf204.png)

You can see the "ideal" - system rendering (gedit in debian); slightly worse, but still ok burp; and bad zap rendering. I understand that the "system" rendering is a problem in java - the guys from jetbrains had similar (?): https://youtrack.jetbrains.com/issue/IDEA-57233

**Comment by ksdev-pl** [comment]
@psiinon Can you please post a screenshot of zap with request or response tab opened?

**Comment by psiinon** [comment]
Sure - could just be me not used to poor fonts ;) http://imgur.com/mjDNqsU

**Comment by ksdev-pl** [comment]
Or me being choosy ;)

It looks similar, if not the same with default font:

![screenshot from 2017-05-05 19-03-30](https://cloud.githubusercontent.com/assets/4216259/25756168/0b022204-31c6-11e7-80fa-92b6dc131997.png)

If it is not hard to you to read it for a long time (with this rendering) I'm afraid I will not convince you. I know that I should be happy that we have a graphical interface ;) But if there is at least a slight chance of improving the font rendering - please, consider this.

**Comment by ksdev-pl** [comment]
Maybe if the font in the request/response window could be changed by the user it would be enough (because now only the font size is taken from the settings, font name is ignored in the source window) - maybe it's a problem visible especially with the default font? Just an idea.

**Comment by psiinon** [comment]
I'm all for making ZAP as easy to use as possible, and that definitely includes improving font rendering and giving users extra choices (eg being able to choose fonts) :)

**Comment by ahmed-MAE** [comment]
i have aproblem with zap font to in manjaro linux, the font is really poor , i changed it and all fonts look the same , i open it withe `zaproxy` command in the command line,  i think i opend it the worong way or something like that, any help ?

**Comment by kingthorin** [comment]
@ksdev-pl @ahmed-MAE could you try this and let us know if it addresses your issue: https://github.com/zaproxy/zaproxy/wiki/FAQBadFonts

**Comment by ksdev-pl** [comment]
Hi

I'm not sure if there is anything new in the FAQ. I am already using the:
`_JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=gasp'`
in /etc/environment (the effect is visible on the screenshots).

I've tested the options from the FAQ (I've changed the `JAVA_FONTS` path because there is no "TTF" folder in Kali):
```
_JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on'
JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on'
JAVA_FONTS=/usr/share/fonts/truetype
```
I've also tried to run the zap from the command line.

There is no difference in font rendering. That is: the font looks like with the: `_JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=gasp'` option that I already used. I don't think that additional options are necessary, it's possible that it's the only option needed.

The problem on the screenshot in #3051 looks like missing `_JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=gasp'` - without this the font rendering is certainly worse.

The problem I've written about is related to the source/request/response code window - please compare the request/response font with the interface font (on the screenshot). With `_JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=gasp'` the font in the interface is quite OK, but the font in the request/response window is still "bad", as shown in the attached comparison between the zap/burp/system font rendering.

**Comment by thc202** [comment]
@ksdev-pl is the setting (context menu) View > Anti-Aliasing enabled in the Request/Response tabs? And changing the setting makes any difference?

**Comment by ksdev-pl** [comment]
Yes, anti-aliasing is enabled, I've tried this option already - it works correctly, so disabling it makes the font not anti-aliased (worse).

The screenshot shows the font with anti-aliasing enabled on Kali.

**Comment by thc202** [comment]
OK, that component is not using the font selected in the options (like other components do), we can easily change that.

When no font is selected in the options, should that component use the system/Java default font or still allow the component to use its own font (like now, which tends to be monospaced)?

**Comment by ksdev-pl** [comment]
The option to change the font in the request/response panel (or if the panel would use the font selected in the current options) would be great and should help.

I'm not sure about the answer to the question. If there will be an option to change the font it's not so important; even if it will look like now when no custom font is selected it will be easily changeable.

The default one for the request/response panel is monospaced, and the interface font is not, so it's an argument to keep the monospaced as default.

**Comment by thc202** [comment]
Yeah, changed the pull request to keep the monospaced as default.
