### ISSUE TITLE
Feature-Request: Select Multiple Contexts

### ISSUE THREAD

**Issue by JordanGS** [zaproxy/zaproxy#3491]
Hold Shift or Ctrl and select multiple context and delete them.

From a usability standpoint it makes sense but also zap jenkins will now create a new context each time. It would be quite useful to be able to bulk delete from the UI.

and/or

Allow the keyboard Delete button to be able to trigger the deletion and go straight to the "Are you sure you want to remove this context?" prompt.

**Comment by psiinon** [comment]
Can see the benefit in this, and it should be an easy one to implement, hence the IdealFirstBug tag.
For info the context delete functionality is here: https://github.com/zaproxy/zaproxy/blob/develop/src/org/zaproxy/zap/extension/stdmenus/ExtensionStdMenus.java#L195-L211

**Comment by AnamikaD** [comment]
@psiinon where is the "Contexts" part (when clicked it displays default context)?

**Comment by thc202** [comment]
The idea is to be able to select more than one context from the Contexts tree, shown in the Sites tab (currently only one of them can be selected at any given time, the Contexts tree needs to be changed to allow multiple selections [1], and then the pop up updated to handle them).

[1] https://github.com/zaproxy/zaproxy/blob/6eb3229e060b3e551dfaca52b7453429ea905adc/src/org/parosproxy/paros/view/SiteMapPanel.java#L420

**Comment by kingthorin** [comment]
The context related URL export functionality will need to be tweaked as well to accommodate multi-select.

**Comment by AnamikaD** [comment]
@thc202 and @kingthorin Thank you for the explanation!! I am new to ZAP. What is the functionality of the context? Since you are talking about multiple context. How do we generate "multiple" context?

**Comment by thc202** [comment]
More details about what a context is in:
https://github.com/zaproxy/zap-core-help/wiki/HelpStartConceptsContexts

You can create/add more contexts with the button "New Context..." (its icon is a dialogue/window with a green plus in bottom right corner) in the Sites tab.

**Comment by AnamikaD** [comment]
@thc202 thank you for the information!

**Comment by thc202** [comment]
Yes, it should/could be accessible with a keyboard shortcut.

**Comment by thc202** [comment]
In 2.7.0 the context can be deleted with delete key (#4001).

**Comment by ZainabAlShowely** [comment]
Will try to work on this.
