### ISSUE TITLE
Is it possible to do parametrization in OWASP Zap

### ISSUE THREAD

**Issue by paulbaboo** [zaproxy/zaproxy#3493]
Is it possible to do parametrization in OWASP Zap'

If Yes,could you exlain me in detail

I have a URl whose ID can be used only once.so is it possible for me do parametrization to sent proper request.

**Comment by psiinon** [comment]
Please ask questions like this on the ZAP User Group: https://groups.google.com/group/zaproxy-users
Issues should only be raised for bugs or enhancement requests.
