### ISSUE TITLE
getLevel() vs getAlertThreshold()

### ISSUE THREAD

**Issue by rain0r** [zaproxy/zaproxy#3495]
I was confused when I learned that in an active scanner, the threshold can be get with `AbstractPlugin.getAlertThreshold()` and in a passive scanner, it is `PluginPassiveScanner.getLevel()`.
Both methods return an `org.parosproxy.paros.core.scanner.Plugin.AlertThreshold` object.

Wouldn't it be nice if these two methods had the same name?

**Comment by thc202** [comment]
Yes, as long as we keep binary compatibility.
