### ISSUE TITLE
Provide universal formatter / code formatting guidelines

### ISSUE THREAD

**Issue by rain0r** [zaproxy/zaproxy#3503]
It would be great if the zap team could provide an eclipse code formatter file which can be imported to eclipse. So everyone has the same code style when doing Code -> Format in eclipse.

No more whitespace issues in pull requests!

**Comment by thc202** [comment]
The [CONTRIBUTING](https://github.com/zaproxy/zaproxy/blob/develop/CONTRIBUTING.md#formatstyle-java-code) doc now indicates which format/style is being used.
