### ISSUE TITLE
Zest - Allow to set/get global variables

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#3512]
From OWASP ZAP User Group: https://groups.google.com/d/topic/zaproxy-users/DpSEmlvsYmI/discussion

Allow to set (and get) global variables [1] directly from Zest scripts.

Add-on:
"Zest - Graphical Security Scripting Language".

[1] https://github.com/zaproxy/zap-core-help/wiki/HelpAddonsScriptsScripts#global-variables

**Comment by JavanXD** [comment]
This feature is especially useful if you are researching an application like me that uses an unsupported session management.

I was now able to write a workaround using my own Zest Authentication script in combination with a Zest Proxy script and shared global variables. [Here my use case explained.](https://groups.google.com/forum/#!topic/zaproxy-develop/bud4BvP_mqY). 

You can use set_global_var.js and get_global_var.js:
![grafik](https://user-images.githubusercontent.com/4342160/52869503-11f12980-3146-11e9-82a5-32dff6198a64.png)
