### ISSUE TITLE
Port Scan Options UI Tweaks

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#3513]
It would be really nice if the values were left aligned so that they are more visually associated with the labels.

It also seems that the port slider allows at value above 65535. It's unclear if this results in an error or warning, however it should be corrected.

![portscan_opt_ui](https://cloud.githubusercontent.com/assets/7570458/25899226/01fc6b0c-355d-11e7-9820-933bc229062e.png)

**Comment by thc202** [comment]
Maybe it could use `ZapPortNumbeSpinner` instead?

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#933.
