### ISSUE TITLE
Problem importing OpenAPI definition file using OpenAPI support add-on

### ISSUE THREAD

**Issue by Veronit** [zaproxy/zaproxy#3516]
I'm trying to import a swagger json file into ZAP using OpenAPI support add-on.
The problem I am getting is a StackOverflowError error.
Whole log of the error below.
[zap.txt](https://github.com/zaproxy/zaproxy/files/992744/zap.txt)

I tried increasing stack size with -Xss option and allocated more memory to Java but couldn't get ZAP to import the file.

The json file I'm importing has ~26000 rows and is 630k in size.

**Comment by kingthorin** [comment]
Ref: https://groups.google.com/forum/m/#!topic/zaproxy-users/-EgNsA9_-M4

**Comment by psiinon** [comment]
@Veronit are you able to share your swagger definition? Feel free to change any private details and/or email it to me directly.

**Comment by Veronit** [comment]
No, sorry.

**Comment by psiinon** [comment]
@Veronit OK, np.
Which version of the OpenAPI add-on are you using?

**Comment by Veronit** [comment]
@psiinon: Version 5

**Comment by psiinon** [comment]
@Veronit I dont suppose your swagger definition has any "#/definitions/" which could result in loops?

**Comment by Veronit** [comment]
Could be. It has quite a few #/definitions/. 
I need to check if there is loops.

**Comment by psiinon** [comment]
@Veronit  Without having an example to go on thats my best guess.
However I'll add debug statements to help us diagnose such problems.
Ideally ZAP should detect and handle loops, but without a test case I'm nervous about trying to add such functionality.

**Comment by Veronit** [comment]
@psiinon I'll go through the json file and try to find any loops. Swagger editor at least doesn't give warnings or error about them (don't know if it's supposed to do so).
I'm reluctant in sending the file since it contains so much sensitive data.

If I find the loop, I'll make some changes to the json and send it to you.

**Comment by Veronit** [comment]
@psiinon After couple of days away from work I got back on this, I found a loop on the definitions. Removing that got rid of the error. Do you want an example of the loop?

**Comment by thc202** [comment]
@Veronit yes, please, that would help address the issue.

**Comment by psiinon** [comment]
@Veronit definitely - we've got some code which we hope will detect these sort of problems but it would be great to have more examples to test against.

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#905.
