### ISSUE TITLE
Add SRI check to X-Domain Script Inclusion Passive Rule

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#3517]
If there's a cross domain inclusion that includes an integrity attribute then no alert or reduced severity... 

https://bugs.webkit.org/show_bug.cgi?id=148363

**Comment by kingthorin** [comment]
"Cross-Domain JavaScript Source File Inclusion"

https://github.com/zaproxy/zap-extensions/blob/master/src/org/zaproxy/zap/extension/pscanrules/CrossDomainScriptInclusionScanner.java

**Comment by kingthorin** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script

**Comment by kingthorin** [comment]
Closing, wontfix.

Seems this is aleady in place and I'd forgotten that someone had added it: https://github.com/zaproxy/zap-extensions/pull/473/files#diff-61439a4dbd11d8e5534cffe309c71cb4

**Comment by thc202** [comment]
Removed the `wonfix` (it was fixed/implemented).

**Comment by kingthorin** [comment]
Fair enough, I guess it's more like `wasfixed` :grinning:
