### ISSUE TITLE
'Parameter Tampering' alert has an invalid 'otherinfo' field value equals @

### ISSUE THREAD

**Issue by scannerwebs** [zaproxy/zaproxy#3524]
I think I have found a minor level bug for alert 'Parameter Tampering' other info field using ZAP API 2.6 docker version.
The value of tag **otherinfo** is _@_ when it usually comes with some useful data. Notice as well there is not **reference** tag for this particular alert.

`...
<count>6</count>
<solution>
<p>Identify the cause of the error and fix it.  Do not trust client side input and enforce a tight check in the server side.  Besides, catch the exception properly.  Use a generic 500 error page for internal server error.</p>
</solution>
**<otherinfo>**<p>@</p>**</otherinfo>**
<reference><p></p></reference>
<cweid>472</cweid>
<wascid>20</wascid>
<sourceid>1</sourceid>
</alertitem>
</alerts>`

Regards

**Comment by thc202** [comment]
From https://groups.google.com/d/topic/zaproxy-users/fo_nTMnwGQc/discussion
