### ISSUE TITLE
Minor Enhancement: Add Date Format Preference

### ISSUE THREAD

**Issue by davewichers** [zaproxy/zaproxy#3528]
I don't believe we have this feature. There are places within ZAP that use the DD-MM-YYYY date format, but in the U.S. we use MM-DD-YYYY. It's confusing to us to use the other format. Can we have a preference that allows us to switch this format everywhere it's used? Defaulting to European standard as it works now, is fine :-)

**Comment by thc202** [comment]
Could you provide the name of the component/dialogue/tab that's showing the wrong date format?

**Comment by davewichers** [comment]
Timestamp column in the History tab is the only one I'm aware of. But I
haven't searched for other places where dates might be displayed.

**Comment by psiinon** [comment]
No way. The American date format is completely nonsensical and should never be encouraged!
Only joking ;) We should pick up the locale default and use that, but we can def have an option if that doesnt work for everyone.

**Comment by davewichers** [comment]
Both would be fantastic. If it automagically 'just works' that would be
great.

**Comment by kingthorin** [comment]
> No way. The American date format is completely nonsensical and should never be encouraged!
Only joking ;) 

Well we are talking about people that still care about the size of the King's foot 😀  I mean why go biggest unit to smallest, or smallest to biggest when you can do it completely jumbled up? Hahahahaha

Ok I'll stop with the joking, we'll see what we can do @davewichers

**Comment by thc202** [comment]
We are already checking the locale and selecting the most appropriate language, which in this case ends up being en_GB :/

**Comment by psiinon** [comment]
As it should be :P

**Comment by davewichers** [comment]
Why would my locale by en_GB? I assume there is an en_US, which is what my
environ should resolve to, and so we could use that to select a default
date order that is more familiar to us?

**Comment by thc202** [comment]
@davewichers per #3587, ZAP will use the system's locale by default when formatting (thus showing the expected date order/format).

**Comment by davewichers** [comment]
Excellent. Thank you.

**Comment by davewichers** [comment]
Is this issue addressed now and should be closed??

**Comment by thc202** [comment]
We don't allow the user to define its own format yet.

**Comment by davewichers** [comment]
Ah. But if it defaults to their location's standard format, that's probably
'good enough'. Thanks.

**Comment by kingthorin** [comment]
Closing per original submitter feedback.
