### ISSUE TITLE
Sequence Addon "Active scan sequence" Doesn't Work From Scripts Tree

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#3536]
Choosing to run an active scan by creating a new scan and selecting the sequence(s) from the list does (when starting from the Active Scan tab > New Scan button). However, starting from the scripts tree right click "Active scan sequence" does not. Active scan tab becomes active and immediately transitions from 0% to 100% displaying 0 requests sent.

**Comment by thc202** [comment]
Could you attach/provide the (minimal) Zest script that reproduces the issue? Which versions of the add-ons are you using? Do you have the same options enabled in the main options panel and (advanced) Active Scan dialogue?

I'm not able to reproduce this issue.

**Comment by kingthorin** [comment]
This was my test target: https://github.com/silentsignal/damn-vulnerable-stateful-web-app I was running it under xampp portable on windows.  The following change is needed in ping.php (win vs. *nix):
`	system("ping -c $_SESSION[count] $_POST[host]");`
to
`	system("ping -n $_SESSION[count] $_POST[host]");`

**Comment by kingthorin** [comment]
Interestingly if I "Remvoe script" then re-open it, it works as expected.

**Comment by thc202** [comment]
Thanks!

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#887.
