### ISSUE TITLE
Private IP disclosure alerts on target IP with non default port

### ISSUE THREAD

**Issue by emanuelb** [zaproxy/zaproxy#3549]
when scanning:
http://IP:PORT/
it will report lots of 'Private IP disclosure' alerts when the response contain the same host that was scanned.

fix:
don't report 'Private IP disclosure' for IP that is used to browse the application.

**Comment by kingthorin** [comment]
Try setting the Threshold of the scan rule to LOW.

https://github.com/zaproxy/zap-extensions/commit/4573a04cc31ca637e1666a2ce7d66b21256560ee

**Comment by thc202** [comment]
@emanuelb which version of the Passive scanner rules add-on are you using? Which alert threshold has the scanner?

@kingthorin setting to LOW would report those cases.

**Comment by emanuelb** [comment]
version of the Passive scanner rules: 19
zap version: 2.6.0
os: kali linux

The threshold was medium, changed to high/low. still report the issue.
The target IP scanned:
http://10.0.2.2:8081/
the result:
"10.0.2.2:8081" (under 'other info' in 'Private IP disclosure' alert)
Some of the reported alerts are real (that give other IP in private range) but not the one which report the IP scanned.

is there a reason/scenario when this alerts are useful? it's looks to me like they always noise (as the information is already known = no leak of info = FP ....)

**Comment by kingthorin** [comment]
> @kingthorin setting to LOW would report those cases.

Yup you're right of course, the previous change I linked compares for same host (which handles localhost loopback etc), not necessarily all private IPs.

**Comment by kingthorin** [comment]
> is there a reason/scenario when this alerts are useful? it's looks to me like they always noise (as the information is already known = no leak of info = FP ....)

You can always make a quick risk decision and disable the scan rule.

**Comment by kingthorin** [comment]
As a work around you could also add a hosts file entry then access the web app/site by name and leave the rule on to highlight issues.

**Comment by thc202** [comment]
>  not necessarily all private IPs.

The problem is not with the IPs but the port, it's not being taking into account when doing the check.
