### ISSUE TITLE
missing webswing executable in weekly docker

### ISSUE THREAD

**Issue by emanuelb** [zaproxy/zaproxy#3550]
running:
```
docker run -u zap -p 8080:8080 -p 8090:8090 -i owasp/zap2docker-stable zap-webswing.sh
```

work, while running
```
docker run -u zap -p 8080:8080 -p 8090:8090 -i owasp/zap2docker-weekly zap-webswing.sh
```

return:

> Webswing executable not found in /zap/webswing-2.3/ folder

**Comment by thc202** [comment]
This is because of the live image (weekly is based on live), which does not include WebSwing.

**Comment by emanuelb** [comment]
Ok, consider to add notice about it to documentation/wiki or have more useful error message that indicate the reason (unless it will be fixed)

**Comment by thc202** [comment]
It will be fixed.

**Comment by thc202** [comment]
Latest owasp/zap2docker-weekly image has Webswing.
