### ISSUE TITLE
Update Webswing in Docker images

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#3553]
Update Webswing to version 2.5 to address the issues:
 - https://bitbucket.org/meszarv/webswing/issues/97 (fixed in 2.4, but following is a blocker)
 - https://bitbucket.org/meszarv/webswing/issues/214

that prevent some of the dialogues from being used (e.g. in Options > API, in Session Properties...).

(Pending release of version 2.5.)

**Comment by yilmi** [comment]
Having the same issue here, made difficult the configuration of ZAP API for me. I tried for example to add a Whitelisted ip to the API but the 2nd level contextual pop-up is not reachable.
I had the same StackTrace as the one reported on the first issue listed by @thc202 (https://bitbucket.org/meszarv/webswing/issues/97).

I see @psiinon and @flibustier have been working on the webswing startup script, could you guys fix it or let me know how you would fix it (I can help if you don't have time)

**Comment by thc202** [comment]
There's no release yet that have both issues fixed. We could use a dev build but that might have its issues too.

@psiinon what do you think, should we use a dev build in the meantime?

**Comment by GregoryPerry706** [comment]
So can these second level Swing menus be configured via the REST API with Python?

**Comment by thc202** [comment]
Depends on the exact functionality, re #4227, yes, contexts can be configured through the API (Python example at [1]).

[1] https://github.com/soprasteria/zap-api-python/blob/4b7e5ddbcac9401549a6bb3c857df46b13f8814a/src/examples/zap_example_api_script.py

**Comment by speedyuk** [comment]
Hi, is there any news regarding integrating Webswing 2.5? I hit the brick wall regarding adding users for authentication. Do we know if Webswing 2.5 will address the Java environment issue?

**Comment by thc202** [comment]
Yes, 2.5 is already released and it fixes the above issues, I have the changes more or less ready but need to try them in the docker image.

**Comment by speedyuk** [comment]
Fab, thanks thc202 for the quick reply. I'll pass on the info to my colleague who takes the docker images and packages for use in our environment will be great to get this working.

**Comment by speedyuk** [comment]
Hi I'm back again - My colleague has been creating various different combinations of ZAP and webswing to try and come up with a working combination for the entering username and password dialogue issue. He did try to create a 2.7 ZAP with webswing 2.5 build but had problems. So far have to go back to 2.5 ZAP with webswing 2.4 to have a working dialogue box. With ZAP 2.6 and webswing 2.4 only have half the box, no username and password part as per the attachment. Really looking forward to a working 2.7 combo.
![zap add user dialogue part missing](https://user-images.githubusercontent.com/36737624/36854404-d59df1da-1d68-11e8-9a70-e4eedd27650c.PNG)

**Comment by thc202** [comment]
Thanks for the bump and sorry for the delay, a pull request has been open to update Webswing in all images, #4471.

**Comment by speedyuk** [comment]
Hi I'm sorry I'm sure this isn't the correct place to put this now, but I'm not sure on the process of finding relevant thread. Anyway my developer produced a new docker image with 2.7 and 2.5 webswing using the info in the update post. The interface works and I'm able to add the user name and password, but when I go to replay the POST I get a CSRF token is incorrect error as per the attached screenshot. I didn't get this before. Sorry if I missed a new setting in 2.7? 
![image](https://user-images.githubusercontent.com/36737624/36912191-e6ec6842-1e3d-11e8-94b6-6fcd222bea5c.png)

**Comment by thc202** [comment]
Not that I'm aware of, manual request editor does not handle anti-CSRF tokens automatically (#111), how were you sending the request before? (script?)

Usage questions are usually handled in the OWASP ZAP User Group: https://groups.google.com/group/zaproxy-users

**Comment by speedyuk** [comment]
Hi thc202 many thanks for the support. I'm attaching an image of the response for ZAP 2.5. As you can see I'm basically following through the basic tutorial of setting up an attack to DVWA. All I'm doing is right clicking on the login.php POST and choosing the resend option after previously flagging this as a Forms based login. In 2.5 the login is successful and I'm able to mark logged in identification string in the response window. With 2.7 I'm not as I get the CSRF error. 
![image](https://user-images.githubusercontent.com/36737624/36932188-92585f36-1ebd-11e8-920d-1ef133e16e0f.png)

**Comment by thc202** [comment]
In 2.7.0 are you also resending the latest successful login request? I see the same behaviour (resend shows the logged in response) with 2.5.0 and 2.7.0, if using a still logged in session and resending latest login request.

**Comment by speedyuk** [comment]
Hi, sorry for delay, resetting up environment in the office. I have been able to do a successful login resend. I think it must have been as you said the session it was replaying was logged out. I've been able to reproduce that by actively logging out on the browser. Thanks again.

**Comment by thc202** [comment]
Thanks for letting us know!
