### ISSUE TITLE
Changing Session Name, doesn't Update the Window Name

### ISSUE THREAD

**Issue by egerod** [zaproxy/zaproxy#3555]
When updating the session name after opening the Session Properties view through a context, the window name is not updated to reflect the new session name.

Steps to reproduce: Open ZAP, double click default context to open Session Properties, navigate to general tab, change the session name, click ok.
Expected Outcome: Window name contains the new session name.
Outcome: The window still show the old session name.
This was done with ZAP 2.6 and on windows 10.

Finally, if the session properties are open through the File drop down menu or the key bind, the window name is updated as intended.

**Comment by kingthorin** [comment]
I agree that the behavior should be consistent but is it misleading if the window title is updated and the session is still not persisted (saved)?

**Comment by thc202** [comment]
I don't think it would be misleading, we show both, the session name and file name (for the latter when persisted).

**Comment by kingthorin** [comment]
Ok, perfect.

**Comment by kingthorin** [comment]
http://logs.glob.uno/?c=mozilla%23websectools&s=19+May+2017&e=19+May+2017

**Comment by kingthorin** [comment]
Ok so just to make sure I'm taking the right direction on this:

1. `setTitle()` will be removed from MenuFileControl.
2. The functionality from MenuFileControl will be added to `MainFrame.setTitle()`.
3. `ExtensionUiUtils.sessionChangedEventHandler()` should call `View.getSingleton().getMainFrame().setTitle("")` [or something like that].
4. Remove title handling from `Control`.

That's what I took from the chat log in the end. I'm left unclear as to whether or not changes were still necessary in `SessionGeneralPanel`  (in saveParam perhaps?)
