### ISSUE TITLE
zap scan (via container) that does both spider/active

### ISSUE THREAD

**Issue by claudijd** [zaproxy/zaproxy#3560]
I've been playing with the baseline scan via the weekly docker containers and I'm finding kind of difficult to get a point and shoot setup working that includes spidering and active scanning.  If this doesn't exist already I think would be a great addition.

**Comment by claudijd** [comment]
I particularly would like the combination of this and #3559 to provide a point and shoot spider/active scan that produces JSON blobs.  IMO, that would be a really common use cases for someone looking to build a scan pipeline (which is essentially what I'm hoping to do here).

**Comment by psiinon** [comment]
I've been meaning to create a zap_fullscan.py script for some time...

**Comment by claudijd** [comment]
this ^

**Comment by psiinon** [comment]
Ah, this was implemented some time ago: https://github.com/zaproxy/zaproxy/blob/develop/build/docker/zap-full-scan.py :)
