### ISSUE TITLE
Permission denied, failing to write HTML report in Docker, on Jenkins worker/slave node

### ISSUE THREAD

**Issue by stephendonner** [zaproxy/zaproxy#3570]
/cc @karlht with whom I had the hacking session, which led to this Issue filing

Problem:

Running any of the following variations (in Steps to Reproduce) of the zap-api-scan.py script, with -r zap_scan_report.html fails, with:

23:23:48 ERROR Permission denied
23:23:48 2017-05-23 06:21:37,957 I/O error(13): Permission denied
23:23:48 Traceback (most recent call last):
23:23:48   File "/zap//zap-api-scan.py", line 622, in main
23:23:48     with open(base_dir + report_html, 'w') as f:
23:23:48 IOError: [Errno 13] Permission denied: '/zap/wrk/zap_scan_report.html'

In the following logfiles, I'm using http://example.com, because it's quick, and still demonstrates the core problem.

In actual (and much, much longer runs), I'm running against https://kinto.dev.mozaws.net/v1/__api__ for the value passed to -t $TARGET_URL

Setup:

1. Jenkins manager (i.e.'master'), which runs the Docker image on a *worker* node (i.e. 'slave')
2. On the manager/master:
root@ip-172-31-58-216:/home/sdonner# getent passwd | grep jenkins
jenkins:x:107:113:Jenkins,,,:/var/lib/jenkins:/bin/bash
3. On the worker/slave:
[root@ip-172-31-58-166 ~]# getent passwd | grep jenkins
jenkins:x:1008:1008::/home/jenkins:/bin/bash
jenkins-slave:x:1009:1009::/home/jenkins-slave:/bin/bash
[root@ip-172-31-58-166 ~]# docker ps -a
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                      PORTS               NAMES
9baed761cfc8        owasp/zap2docker-live       "zap-api-scan.py -t h"   2 minutes ago       Exited (2) 22 seconds ago                       clever_shannon
[root@ip-172-31-58-166 ~]# docker start 9baed761cfc8
9baed761cfc8
[root@ip-172-31-58-166 ~]# docker exec -ti 9baed761cfc8 bash
zap@9baed761cfc8:/zap$ getent passwd | grep zap
zap:x:1000:1000::/home/zap:/bin/bash

Steps to Reproduce:

docker pull owasp/zap2docker-live

Next:

docker run -v $(pwd):/zap/wrk/:rw -e USERID=[userID] -t owasp/zap2docker-live zap-api-scan.py -t $TARGET_URL -f openapi -d -r zap_scan_report.html

Note: we've specifically tried:

* without passing -e USERID:

docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-live zap-api-scan.py -t $TARGET_URL -f openapi -d -r zap_scan_report.html

* passing the USERID of the "jenkins" user on the worker/slave node:

docker run -v $(pwd):/zap/wrk/:rw -e USERID=1008 -t owasp/zap2docker-live zap-api-scan.py -t $TARGET_URL -f openapi -d -r zap_scan_report.html

* passing the USERID of the "jenkins-slave" user on the worker/slave node:

docker run -v $(pwd):/zap/wrk/:rw -e USERID=1009 -t owasp/zap2docker-live zap-api-scan.py -t $TARGET_URL -f openapi -d -r zap_scan_report.html

Actual Results:

Because the earlier, initial step of creating the zap_scan_report.html file fails, the later HTML Publisher step fails, accordingly:

23:59:13 [htmlpublisher] Archiving HTML reports...
23:59:13 [htmlpublisher] Archiving at PROJECT level /home/jenkins/workspace/zap2docker-api to /var/lib/jenkins/jobs/zap2docker-api/htmlreports/HTML_Report
23:59:13 ERROR: Directory '/home/jenkins/workspace/zap2docker-api' exists but failed copying to '/var/lib/jenkins/jobs/zap2docker-api/htmlreports/HTML_Report'.
23:59:13 ERROR: This is especially strange since your build otherwise succeeded.
23:59:13 Build step 'Publish HTML reports' changed build result to FAILURE
23:59:13 Finished: FAILURE
Full logfile: [jenkins-zap-api-scan-log.txt](https://github.com/zaproxy/zaproxy/files/1021276/jenkins-zap-api-scan-log.txt)

Internal Jenkins job is: https://fx-test-jenkins-dev.stage.mozaws.net:8443/job/zap2docker-api/

**Comment by psiinon** [comment]
I dont _think_ this is a ZAP issue.
When you run docker with: `docker run -v $(pwd):/zap/wrk/:rw ...` you are mapping the /zap/wrk/ directory in the docker image to the cwd of the machine in which you are running docker, in this case the jenkins slave.
I think the problem is that your current jenkins  user doesnt have write access to the cwd.
Using `-e` on the call to `docker run` wont help you. The problem is with the jenkins cwd not the /zap/wrk/ directory in the ZAP docker image.

You need either get write access to `$(pwd)` or replace it with a directory that you do have write access to.

**Comment by psiinon** [comment]
FYI 

`docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-live zap-api-scan.py -t http://example.com/ -f openapi -d -r sdonner_report.html`

works fine when run here in a directory in which the user has write access and fails in a similar way to the above if I remove write access to the sdonner_report.html file.

**Comment by stephendonner** [comment]
Closing this out; @ckolos got a working shell script (you'll understand it better than I): https://gist.github.com/stephendonner/80f7bee6366b2eb151a1ed47c4dfe129

There might be a better/cleaner way to do this, and so I'll either move this into a Jenkinsfile or a shell script (so we can also track changes to it via SCM).

Thanks for your patience!

<img width="1792" alt="screen shot 2017-05-25 at 9 34 46 am" src="https://cloud.githubusercontent.com/assets/387249/26474442/fca9c004-4165-11e7-9e75-0d89f10ceeee.png">

**Comment by kingthorin** [comment]
@stephendonner thanks for letting us know
