### ISSUE TITLE
Add XSLT Injection Scanner

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#3572]
Add an active scanner for XSLT Injection issues. See https://www.owasp.org/images/a/ae/OWASP_Switzerland_Meeting_2015-06-17_XSLT_SSRF_ENG.pdf for further details.

**Comment by kingthorin** [comment]
https://www.contextis.com/blog/xslt-server-side-injection-attacks

**Comment by CaptainFreak** [comment]
This will be my first issue to tackle. I looked through codebase and was not able to figure out the flow of execution and the place where this should be addressed. Any directions towards understanding the project are appreciated. Looking forward to become a regular contributor.

**Comment by psiinon** [comment]
@CaptainFreak have a look at this blog post: https://zaproxy.blogspot.co.uk/2014/04/hacking-zap-4-active-scan-rules.html
Its a bit old now, but still pretty accurate.
There are lots of examples in the various zap_extensions branches (master, beta and alpha) for you to look at, and feel free to ask more questions here :)

**Comment by juhakivekas** [comment]
A thing that I found useful is to use the scripting interfaces to get famialiar with the internals of scanning. The Active Scanner scripts give a good picture of how a scanner written in Java should be written. Also for the first experiments this makes your development cycle extremly fast and agile since you won't need to build between testing and coding.

**Comment by psiinon** [comment]
👍 

1. Create a very simple test page with the vuln
1. Create a test ascan rule
1. Create a policy with just that rule
1. Run a scan against just that page with that rule
1. Keep hacking the script until it finds the vuln
1. Then start looking at more variations :)
1. Finally convert the script to java (although thats not mandatory;)

**Comment by CaptainFreak** [comment]
So this will be a part of Active Scanner or it will be a part of zap-extensions ?

**Comment by kingthorin** [comment]
It should be a new scan rule in the aextensions lpha branch:
https://github.com/zaproxy/zap-extensions/tree/alpha/src/org/zaproxy/zap/extension/ascanrulesAlpha

**Comment by CaptainFreak** [comment]
After Building the extensions and loading .zap file of ascan rules to the zap , Its giving following error after running scans against vulnerable host: 
` Declared "ascanrule" was not found: org.zaproxy.zap.extension.ascanrulesAplha.XSLTInjection` 
what am i missing here?

**Comment by thc202** [comment]
There's a typo in the package `ascanrulesAplha`.

**Comment by CaptainFreak** [comment]
Oops ! Thanks. And also as other scan rules have used `Constant.message.getString()` for getting info about Vuln form I18n . How i can do that?

**Comment by thc202** [comment]
You need to add the messages you want/need to the [`Messages.properties`](https://github.com/zaproxy/zap-extensions/blob/alpha/src/org/zaproxy/zap/extension/ascanrulesAlpha/resources/Messages.properties) file of the add-on.

**Comment by CaptainFreak** [comment]
Addresed in [#1384](https://github.com/zaproxy/zap-extensions/pull/1384/commits/2a11c681c03596fcbdf8c037bec573f8ed9461a3)
Thanks @psiinon @kingthorin @thc202 @juhakivekas . Will improve it more as suggested. It Always feels good to submit first PR in your favourite tools. :)

**Comment by ZainabAlShowely** [comment]
I will take a look at the open PR and hopefully address its outstanding issues.

**Comment by kingthorin** [comment]
Closed in https://github.com/zaproxy/zap-extensions/pull/2170
