### ISSUE TITLE
False Positive with Secure Pages Include Mixed Content and JavaScript files

### ISSUE THREAD

**Issue by jammasterj89** [zaproxy/zaproxy#3581]
In ZAP 2.6.0 it is reporting "Secure Pages Include Mixed Content" on a javascript file. However, the line it is reporting the vulnerability for is in a multi line comment, it looks like ZAP isn't registering it is in a comment. Inline comments with http in them seem to be fine. The comment looks like so (I've cropped it a bit):

```html
/**
 * The wrong way to write it:
 * ```html
 * <a href="http://www.gravatar.com/avatar/{{hash}}">link1</a>
 * ```
    </example>
 */
```
<sub>Edited by @kingthorin 20170526, formatting tweak.</sub>

**Comment by kingthorin** [comment]
Code ref: https://github.com/zaproxy/zap-extensions/blob/master/src/org/zaproxy/zap/extension/pscanrules/MixedContentScanner.java

**Comment by jammasterj89** [comment]
as per @thc202 requested the "other info"

Other information
tag=img src=http://www.gravatar.com/avatar/{{hash}}

**Comment by kingthorin** [comment]
Oh so that means what you quoted in the original issue isn't what the scanner picked up...

Are you able to provide the file or full response that triggered the alert?

**Comment by jammasterj89** [comment]
Sorry I've used the wrong comment, that gravatar link is in about six places in the .js.

Here's the report:
[https://ibb.co/kHyLCa](url)

And here's the instance in the .js file:
[https://ibb.co/fGXxsa](url)

**Comment by thc202** [comment]
Thanks!

**Comment by jammasterj89** [comment]
Hi @thc202, should this still be marked as false positive?

**Comment by thc202** [comment]
Yes, the scanner should not be reporting that.

**Comment by jammasterj89** [comment]
Sorry @thc202 I thought it meant the issue was a false positive, nevermind :)
