### ISSUE TITLE
Unable to download ZAP on Windows 8.

### ISSUE THREAD

**Issue by megh-2017** [zaproxy/zaproxy#3586]
The download fails after sometime. 
Error: Failed - Forbidden.

I tried downloading both 2.6.0 and 2.5.0.
https://github.com/zaproxy/zaproxy/releases/download/2.5.0/ZAP_2.5.0_Windows.exe

**Comment by kingthorin** [comment]
Seems like a network or browser issue. 

1. What's your connection like? (Dialup, DSL, cable, etc)
2. What browser are you using?
3. Are you using a proxy?
4. Are you using VPN?
5. Are you using a download manager?
6. What's the error coming from?

**Comment by kingthorin** [comment]
@megh-2017 anything further on this?

**Comment by kingthorin** [comment]
Closing - InaufficientEvidence
