### ISSUE TITLE
ZAP active scanner in daemon mode skips all scripts

### ISSUE THREAD

**Issue by ani2796** [zaproxy/zaproxy#3593]
I'm currently running ZAP in daemon mode by building it in IntelliJ. However, whenever I make calls to the ZAP API for the active scanner, it gives me the following errors:

121531 [ZAP-ProxyThread-51] INFO org.parosproxy.paros.core.scanner.Scanner  - scanner started
121604 [Thread-7] INFO org.parosproxy.paros.core.scanner.HostProcess  - Scanning 62 node(s) from http://localhost:8080
121615 [Thread-7] INFO org.parosproxy.paros.core.scanner.HostProcess  - start host http://localhost:8080 | ScriptsActiveScanner strength MEDIUM threshold MEDIUM
121637 [Thread-7] INFO org.parosproxy.paros.core.scanner.HostProcess  - skipped plugin [no scripts enabled] http://localhost:8080 | ScriptsActiveScanner in 0.022s with 0 message(s) sent
121637 [Thread-7] INFO org.parosproxy.paros.core.scanner.HostProcess  - completed host http://localhost:8080 in 0.057s
121637 [Thread-6] INFO org.parosproxy.paros.core.scanner.Scanner  - scanner completed in 0.106s

The spider, however, is working just fine. I need to run the spider before I get the active scanner to even start. Otherwise the active scanner tells me that the URL scan tree is not found.

**Comment by psiinon** [comment]
The Active Scanner can only act on urls that it knows about. If you just run it without exploring your site then there will be no urls and therefore it will exit.
You either need to run one of the spiders or explore you site in another way, eg by proxying regression tests or manual requests.

**Comment by ani2796** [comment]
Thanks for the prompt reply! But the active scanner didn't work even after I had run the spider. That was the trace I had copied in my original post.

Also, is there a possible way to start ZAProxy server using java code without using system commands?

**Comment by thc202** [comment]
When built from source ZAP does not include any add-ons by default, you either need to install the "Active scanner rules" add-ons (e.g. [1]) or build/copy the add-ons to src/plugin directory (and build ZAP again).

It's possible to do that as long ZAP jar and its dependencies are on the classpath (you can call ZAP main method, which starts ZAP), although it's probably better to use a JVM just for ZAP independently of your program.

[1] https://github.com/zaproxy/zap-core-help/wiki/HelpCmdline

**Comment by ani2796** [comment]
Alright thanks! I tried including the ZAP jar and run the main() function of ZAP. However, I'm getting the following error:

Failed due to invalid parameters. Use '-h' for more details.

Process finished with exit code 1

It'd be great if you could give help out ASAP, thanks!

**Comment by thc202** [comment]
It should be passed an empty array, if you don't want to specify any command line arguments.

**Comment by ani2796** [comment]
Thanks. However, now, I think I have to change my build.xml file because I'm getting this error:

Defaulting ZAP install dir to /C:/Users/asriram/.m2/repository/org/zaproxy/zap/2.6.0/zap-2.6.0.jar
Warning: failed to load language files from C:\Users\asriram\.m2\repository\org\zaproxy\zap\2.6.0\zap-2.6.0.jar\lang
Warning: failed to load jar files from C:\Users\asriram\.m2\repository\org\zaproxy\zap\2.6.0\zap-2.6.0.jar\lib
Can't find bundle for base name Messages, locale en_GB

Process finished with exit code 1

**Comment by thc202** [comment]
That means the lang directory (and its Messages.properties files) are not accessible or don't exist. Are you providing them? (Note that ZAP also needs some other config files.)
You can use the `-installdir` command line argument to indicate ZAP where the directory that contains those dirs is located.

**Comment by thc202** [comment]
Closing, all questions seem to be answered. Any other question, please, let us know through the [User Group](https://groups.google.com/group/zaproxy-users). Thank you.
