### ISSUE TITLE
ZAP API Ability to specify domains/addresses that API will be served from

### ISSUE THREAD

**Issue by gavk34** [zaproxy/zaproxy#3594]
Recently I have been attempting to setup ZAP Proxy on Kubernetes, which is behind a HAProxy(Synapse).
While I am able to use the Proxy this way and browse pages etc. accessing the API from outside of the machine results in an infinite loop, similar to what was reported in #2318 
I realise that the fix for this, https://github.com/zaproxy/zap-core-help/pull/79, has been checked in but this only applies to AWS.
Since there is now a growing list of cloud providers it maybe more useful and less maintenance on ye to let users configure the public IP/Addresses that the API is served from.

I have the following set as the configuration for the API
`zap.sh -daemon -port 8090 -host 0.0.0.0 -config api.disablekey=true -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true`

The current workaround for this is to expose the container directly through an external IP via a Service in Kubernetes i.e. skipping the HAProxy altogether. See discussion at https://groups.google.com/forum/#!msg/zaproxy-users/YSz5nFDVqZI/_FHBNttaAwAJ

**Comment by p3r1c0** [comment]
Exist any solution to this problem? I have the same problem (reported in: #4378 ).

**Comment by thc202** [comment]
As mentioned in the other issue, it's still possible to access the ZAP API with the `zap` domain.

**Comment by p3r1c0** [comment]
Hi @thc202 ,
I'm sorry but I don't get understand what you mean. Could you explain it with more details?
Regards,

**Comment by thc202** [comment]
Sure, if you proxy through ZAP's public address you can access the API using `http://zap/`, the same way you can do locally (most of the API clients should be already proxying and using the `zap` domain).

**Comment by p3r1c0** [comment]
Hi, 
Could you check this issue @thc202 ?
Regards.

**Comment by p3r1c0** [comment]
Hi @thc202,

I tested this and it's not working for me. I attach evidences:
OK:
![localhostok](https://user-images.githubusercontent.com/19948149/36982081-32618f0c-208f-11e8-8f5f-c0d1e2b63fa5.PNG)
OK: 
![dockeripwork](https://user-images.githubusercontent.com/19948149/36982096-415e7344-208f-11e8-839a-86ba79c4f8a0.PNG)
NOT OK:
![directipnotwork](https://user-images.githubusercontent.com/19948149/36982108-4aa919ae-208f-11e8-91a0-46b27a2d76d8.PNG)
NOT OK:
![solutionnotok](https://user-images.githubusercontent.com/19948149/36982111-4f7306f2-208f-11e8-83aa-a43e0afedf10.PNG)

Thanks and regards.

**Comment by thc202** [comment]
Hmm, are you sure the address `172.26.0.1` is the container? (and not the host)

**Comment by p3r1c0** [comment]
Hi @thc202 ,

Although you are right, I tested with the correct IP and I also receive the same error:
![new](https://user-images.githubusercontent.com/19948149/36983556-f068f80c-2092-11e8-8258-34fa4f673f1b.PNG)

**Comment by p3r1c0** [comment]
Hi @thc202 ,
Could you check this issue?
Regards.

**Comment by thc202** [comment]
Yes, silly me, the workaround suggested will not work as I was expecting, sorry for misleading you. So, your case does require the changes from this issue (it's almost finished though, will tidy up/polish and PR).

**Comment by p3r1c0** [comment]
Hi @thc202 ,
Many thanks! 
Regards.

**Comment by bharat-maher** [comment]
Is any solution available now?

I am getting the same issue as below when trying to bind with Kubernetes ingress host :
" Failed to read [http://hostname:port](http://hostname:port) within 20 seconds, check to see if the site is available and if so consider adjusting ZAP's read time out in the Connection options panel. "

How I can set my ZAP host as using Kubernetes ingress? is it possible?

**Comment by kostenko-anatolii** [comment]
Hello!
Is there any chances that ZAP API will be available to access not only locally from http://zap address, but from custom hosts? Currently it is not possible to host ZAP in kubernetes cluster using Ingress, any redirection tools also not helping at all.
Best regards, Anatolii

**Comment by thc202** [comment]
Sure, but no eta yet.

You need to rewrite the request to match the zap domain (that should work).

**Comment by thc202** [comment]
This will be provided by the Network add-on.

**Comment by thc202** [comment]
Closing, with the merge of #7080 this feature should now be available.
