### ISSUE TITLE
Always attack Data Driven Nodes 

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#3599]
Data Driven nodes are not attacked unless the option to attack paths is selected.
As these are really data rather than structure I think we should always attack them, especially as attacking all paths significantly increases the time a scan takes.
We could have an additional option but I'm not sure that will provide any real benefit and could just confuse matters.
@thc202 @kingthorin - thoughts?

**Comment by thc202** [comment]
I think it's OK to split that from "URL Path" but instead of attack always I'd associate that with an existing option, "URL Query String" and rename to "URL Query/DDN"(?).

**Comment by psiinon** [comment]
+1

**Comment by kingthorin** [comment]
I'm good with @thc202's suggestion.

**Comment by kingthorin** [comment]
Need clarification on our expectation of users defining DDN.

Consider the following base structure:
```
https://items.somesite.org
    en-US
        container
            item
                GET:itemA
                GET:itemB
```
DDN could be setup as:
`https://items.somesite.org/(en-US/container/)(.+?)(/.*)`
```
https://items.somesite.org
    en-US
        container
            «DDN1»
                GET:itemA
                GET:itemB
```
or:
`https://items.somesite.org/(en-US/container/item/)(.+?)(/.*)`
```
https://items.somesite.org
    en-US
        container
            item
                    «DDN1»
```
I'm anticipating that `https://items.somesite.org/(en-US/container/item/)(.+?)(/.*)` is our expectation. I can make this work either way, just need to be clear what the intended usage pattern is.

**Comment by thc202** [comment]
Does it matter where the DDN is defined (at least for the variant)?

**Comment by kingthorin** [comment]
Not really, it was more for functional understanding. I ended up submitting a PR over the weekend anyway :)

**Comment by kingthorin** [comment]
Done in https://github.com/zaproxy/zaproxy/pull/3805
