### ISSUE TITLE
ZAP Python API - Authentication 

### ISSUE THREAD

**Issue by jeannotteb** [zaproxy/zaproxy#3608]
I'd like to start off by saying that I love this tool and the API is written in a very easy to follow way if you are familiar with Zap. The only troubles I've had is that I can't find much documentation on the python API, so I've gone off of the source code and verifying how it works against the app. I've been able to pull of scans and set contexts, but I can't seem to be able to correctly call anything from the authentication module. One of my problems, I believe, is that I'm not entirely sure the exact variables to use or their respective formats when calling the functions. below is some example code that I've scrapped together. Every use of the authentication functions below fail me. Even if someone were to look at this and tell me where to go or look to solve this problem myself, I would be very grateful.

```Python
from zapv2 import ZAPv2
context = 'new_attack'
authmethodname = 'formBasedAuthentication'
authmethodconfigparams = "".join('loginUrl=https://192.168.0.1/dologin.html' 'loginRequestData=username%3D%7B%25user1%25%7D%26' 'password%3D%7B%25password%25%7D')
target = 'https://192.168.0.1'
apikey = 'password'
zap = ZAPv2(apikey=apikey)

print zap.context.new_context(context)
print zap.context.include_in_context(context, 'https://192.168.0.1.*')

print zap.context.context(context)

# everything below here gives me an error saying 'Missing Parameter'

print zap.authentication.set_logged_in_indicator(context, loggedinindicatorregex='Logged in')
print zap.authentication.set_logged_out_indicator(context, 'Sorry, the username or password you entered is incorrect')


print zap.authentication.set_authentication_method(context, authmethodname, authmethodconfigparams)
```

**Comment by thc202** [comment]
For `set_logged_in_indicator`, `set_logged_out_indicator`, and `set_authentication_method` you need to pass the ID of the context not the name. You can check more details of the API calls in the wiki [ApiGen_authentication](https://github.com/zaproxy/zaproxy/wiki/ApiGen_authentication) or using the [API UI]( https://github.com/zaproxy/zaproxy/wiki/ApiDetailsUI).

There's a typo when specifying the username field, it should be `username` not `user1`, also the parameter `loginRequestData` should have a `&` before it.

Once the authentication is set up you need to add the users (which can be set when spidering/scanning or used with forced user mode).

```Python
context = 'new_attack'
authmethodname = 'formBasedAuthentication'
authmethodconfigparams = "".join('loginUrl=https://192.168.0.1/dologin.html' '&loginRequestData=username%3D%7B%25username%25%7D%26' 'password%3D%7B%25password%25%7D')
target = 'https://192.168.0.1'
apikey = 'password'
zap = ZAPv2(proxies={'http': 'http://127.0.0.1:8119', 'https': 'http://127.0.0.1:8119'}, apikey=apikey)

contextid = zap.context.new_context(context)
print contextid
print zap.context.include_in_context(context, 'https://192.168.0.1.*')

print zap.context.context(context)

print zap.authentication.set_authentication_method(contextid, authmethodname, authmethodconfigparams)
# The indicators should be set after setting the authentication method.
print zap.authentication.set_logged_in_indicator(contextid, loggedinindicatorregex='Logged in')
print zap.authentication.set_logged_out_indicator(contextid, 'Sorry, the username or password you entered is incorrect')

userid = zap.users.new_user(contextid, 'User 1')
print userid
print zap.users.set_authentication_credentials(contextid, userid, 'username=MyUserName&password=MySecretPassword')
print zap.users.set_user_enabled(contextid, userid, True)

print zap.spider.scan_as_user(contextid, userid, target)
```

**Comment by jeannotteb** [comment]
Thanks a bunch for your time and help! I figured I was misinterpreting a few things. The errors gone away, it still gets hung up on the loggin page but that's something I can fix now that I can actually correctly call the functions.

I'm doing some basic scripting from a terminal while having the application up to see how my scripts affect the application and one thing I have noticed is that calling the authentication scripts, even yours, more than once during the same session will throw back some errors giving that 'Missing Parameters' error back. I assume that it's throwing that back because I'd be trying to make the same user with the same credentials over again. In fact creating a new session and running the script is fine, but I just wanted to mention it now because the error 'Missing Parameters' for having the same user and credentials wasn't the most obvious thing.

**Comment by thc202** [comment]
There are some changes (#3620) to fix some of the returned errors, it should no longer return "missing parameter" when invalid. Note that running the same script again will not work correctly, since it's not possible to have contexts with the same name. You could create a new session (`zap.core.new_session()`) at the start of the script to ensure it works always the same.
