### ISSUE TITLE
ZAP Report lack of data

### ISSUE THREAD

**Issue by Salinka** [zaproxy/zaproxy#3615]
Out of 27 alerts raport with only 16 is generated.

![image 1](https://cloud.githubusercontent.com/assets/9210304/26775462/131f974c-49a3-11e7-8cf2-5a3f835f2913.png)
![image](https://cloud.githubusercontent.com/assets/9210304/26775463/132e50c0-49a3-11e7-80f7-2e4ebc23d1f4.png)

**Comment by thc202** [comment]
Which ZAP version are you using?

**Comment by Salinka** [comment]
Sorry, I missed the update. It was for version 2.5

**Comment by thc202** [comment]
Can you confirm that's working as expected with latest version?

**Comment by Salinka** [comment]
I have it changed already, but now there is sth strange shown.
There are some high risks in raport when in OWASP there are no high risks (they turned out to be false positives)

![1](https://cloud.githubusercontent.com/assets/9210304/26779847/5f1bec60-49e7-11e7-94c3-44a55e0e92bb.PNG)
![2](https://cloud.githubusercontent.com/assets/9210304/26779849/5f34008e-49e7-11e7-9e42-78551279e631.PNG)

**Comment by thc202** [comment]
Thanks for the information. That's issue #2593, setting as duplicate of that one.
