### ISSUE TITLE
ERR_CONTENT_LENGTH_MISMATCH 

### ISSUE THREAD

**Issue by hkesharia** [zaproxy/zaproxy#3624]
Hi all,

In our organization, we have many internal/external applications. I am using OWASP ZAP to verify vulnerabilities in all of them. It works fine for most of the pages except few. It does not behave as expected when web server sends the data in chunk. Say example, web server set the Content-Length 12345, but flushes 1000 chars first and remaining data later. In this case, browser is showing the proper content, but the request is not getting finished and fails with error 'ERR_CONTENT_LENGTH_MISMATCH' after few seconds as shown in below image. However, browser renders page correctly. So, everything works fine if we run the test manually in browser, keeping ZAP as proxy server. But, but the same things does not work with automation tool. The automation tool fails the process as it does not receive complete response from the proxy server (that is ZAP). Since, we want to automate all the processes, the error should not come and proxy should response as it works without proxy. 

![image](https://user-images.githubusercontent.com/7568529/26874031-a7914658-4b99-11e7-8d72-d5b52e7486b6.png)

To verify the proxy server issue, I have setup nginx as proxy server and tried. All the pages are working perfectly fine with nginx, but somehow, does not work with ZAP. Since, we have to deal with many applications including third party application, it would not be not possible modify the web application code. 

Since I cannot share my web application, to reproduce the same issue, I have tried nopCommer (Open source ecommerce web application on .Net). There are many pages fails in nopCommerce as well, i.e. login page, search page, etc. 

Can someone please provide us solution here?

Regards,
Hitesh

**Comment by thc202** [comment]
Thanks for the report, I'll take a look at it.

**Comment by kingthorin** [comment]
Chunked transfer issue?

**Comment by kingthorin** [comment]
Closing. Original user did not provide further details and the ticket is over 600d old.
