### ISSUE TITLE
Allow to delete messages with keyboard shortcut

### ISSUE THREAD

**Issue by oresundstrandpark-etape2** [zaproxy/zaproxy#3626]
Please enable the delete key to delete items. Also when deleting it sometimes removes too many items, very annoying really...

**Comment by thc202** [comment]
Could you provide more details about "removes too many items"? Is that when a parent node is deleted it deletes its child nodes?

**Comment by thc202** [comment]
> Also when deleting it sometimes removes too many items

This is being handled in #4065.
