### ISSUE TITLE
ZAP does not warn if port already in use in macOS

### ISSUE THREAD

**Issue by oresundstrandpark-etape2** [zaproxy/zaproxy#3627]
zap does not check if port is already in use, by e.g. mitmproxy - can you add this ?

**Comment by thc202** [comment]
ZAP already informs when it can't listen on the specified port (when run in daemon mode and with GUI). What other check should it have?

**Comment by thc202** [comment]
Closing (as insufficient evidence) still let us know if/how the current behaviour can be improved. Thank you.

**Comment by oresundstrandpark-etape2** [comment]
Gosh, if you are closing all issues without changes, why bother having a 
feedback button. Other proxies will detect this, and alert, if the port 
is already in-use.

Peter

**Comment by thc202** [comment]
I closed the issue because no feedback was given after 20 days. As said in a previous comment ZAP already does that, it will inform if not able to listen to the specified port. Are you not seeing that? Which ZAP version are you using?

**Comment by oresundstrandpark-etape2** [comment]
I am using latest version... No warning whatsoever when other proxy app 
was started first... This is MAC version.

**Comment by thc202** [comment]
OK, thanks for the information. Reopening, I'll try check what's wrong (it works fine in Linux and Windows).

BTW, is there any error in the zap.log when that happens? [1]

[1] https://github.com/zaproxy/zaproxy/wiki/FAQconfig

**Comment by oresundstrandpark-etape2** [comment]
I can check. Using ZAP to investigate app interface. A given post works 
from the app, but shows Tags=JSON. If I duplicate this call it does not 
work, although request is alike, but Tags shows Form, Hidden, Script - 
is this coming from the server ?

Peter

**Comment by kingthorin** [comment]
Tags are added by passively analyzing traffic. It is possible for two requests/responses for the same resource to be completely different depend on the app and tech involved.

Most of the default tags are based on simple regex patterns.

More info is available here, or in the help bundled with ZAP:  https://github.com/zaproxy/zap-core-help/wiki/HelpStartConceptsTags

If you have further use/functionality questions please post them to the user group: https://groups.google.com/forum/#!forum/zaproxy-users

**Comment by kingthorin** [comment]
@oresundstrandpark-etape2 have you been able to recreate this issue and check the log file as requested by @thc202?

**Comment by thc202** [comment]
Updated the title to reflect the actual issue.

**Comment by kingthorin** [comment]
Original reporter hasn't replied after 2 weeks. Can this be closed?

**Comment by thc202** [comment]
Yeah, that's being tracked in the other issue.

Could you confirm that the warning is being shown?

**Comment by oresundstrandpark-etape2** [comment]
It did not work in Zap 2.6 - is there a newer version ?

**Comment by kingthorin** [comment]
Yup that's in https://github.com/zaproxy/zaproxy/issues/3626

**Comment by thc202** [comment]
@oresundstrandpark-etape2 there are weekly releases but no change was done that would have any impact on the warning dialogue. Were you able to replicate the issue? Anything in the log?
