### ISSUE TITLE
Starting ZAP server from source code

### ISSUE THREAD

**Issue by ani2796** [zaproxy/zaproxy#3645]
Hi,

I'm able to call the ZAP client API to execute my scans successfully. However, I wish to start the ZAP server from the java source code without using any system commands. I tried to import the ZAP maven dependency and call the ZAP.main(String[]) method, using the following line of code:

`ZAP.main(new String[] {"-daemon", "-port 1234"});`

However, I keep getting the following error:

> Warning: failed to load language files from C:\Users\asriram\.m2\repository\org\zaproxy\zap\2.6.0\zap-2.6.0.jar\lang
> Warning: failed to load jar files from C:\Users\asriram\.m2\repository\org\zaproxy\zap\2.6.0\zap-2.6.0.jar\lib
> Can't find bundle for base name Messages, locale en_GB
> 
> Process finished with exit code 1
> 

I'd appreciate any assistance relevant to this particular problem. Thanks in advance.

**Comment by thc202** [comment]
As mentioned in https://github.com/zaproxy/zaproxy/issues/3593#issuecomment-305144563 that happens if the files ZAP expects are not provided.

P.S. For questions like this it's better to use the User Group.

**Comment by ani2796** [comment]
Alright, thanks. I'll ask any further questions related to this one on the user's group.
