### ISSUE TITLE
Add docker health check

### ISSUE THREAD

**Issue by omerlh** [zaproxy/zaproxy#3649]
Dockerfile allow you to declare [HEALTHCHECK](https://docs.docker.com/engine/reference/builder/#healthcheck) command. It would be great to add this command to the docker image, and report Zap as healthy when it complete loading. This could be useful when using Zap in CI environment (using `docker-compose`), and waiting to Zap to complete loading before starting the tests. The only problem is how we detect that Zap complete loading - I think the API is responsive before Zap complete loading.

**Comment by thc202** [comment]
Using the API should be fine, since 2.6.0 (#3297) the API is available only after ZAP has finished starting.

**Comment by omerlh** [comment]
Ok, so I will try to create a PR with basic HEALTHCHECK - basically `curl`.

**Comment by psiinon** [comment]
I usually use core.version for this :)
https://github.com/zaproxy/zaproxy/blob/develop/build/docker/zap-baseline.py#L283-L289

**Comment by omerlh** [comment]
`zap-cli` is included in the image, so we can actually also use the `status` command. The only issue is to figure which port is used - as it is could be overridden. I think our best shot here is an environment variable. What do you think?

**Comment by thc202** [comment]
Using a environment variable sounds good to me, but we need to document that properly (in <https://github.com/zaproxy/zaproxy/wiki/Docker>?).

**Comment by omerlh** [comment]
You are correct, I am updating the documentation right now. I did not handle the case when Zaproxy is running with `apikey`, I think that in this case, the user should override the default health check. What do you think?

**Comment by omerlh** [comment]
Ok, I updated the documentation - appreciate feedback regarding the new section. Also, I think to change all the samples on how to run Zap to use `ZAP_PORT` instead of 8080.

**Comment by omerlh** [comment]
Ok, I updated the documentation. I was a bit surprised that I can just edit and save them, so I would like to hear your feedback.

**Comment by thc202** [comment]
Thank you! Just a minor comment, the user does not need to specify the `ZAP_API_KEY` environment variable even if that's enabled (`zap-cli status` check does not use any API endpoint, it just tries to access the API UI which does not require the API key).

**Comment by omerlh** [comment]
Oh, I see. Thank you, I will update the documentation. Already waiting to use the new container :)

**Comment by thc202** [comment]
Looks good to me, thank you!
