### ISSUE TITLE
Running Automated Security Scans in Daemon Mode

### ISSUE THREAD

**Issue by Dunnsk22** [zaproxy/zaproxy#3661]
Hi all,

First of all please forgive me if this issue is floating around elsewhere, but I cannot seem to find it. I am currently running selenium tests through ZAP and successfully executing security tests. However, to do this I need ZAP to be open, so that my code can create a connection. 

Is there any way of running these tests through ZAP without the software being open on my computer? So as a background process/daemon? Any help would be massively appreciated!

Thanks.

**Comment by kingthorin** [comment]
Check here (or the help that's packaged with ZAP):
https://github.com/zaproxy/zap-core-help/wiki/HelpCmdline#options
`-daemon`

You can then interact with ZAP via it's web API.
https://github.com/zaproxy/zaproxy/wiki/ApiDetails

If you have further questions the ZAP User Group https://groups.google.com/group/zaproxy-users and Developer Group https://groups.google.com/group/zaproxy-develop are much better places for questions.
