### ISSUE TITLE
API: sendHarRequest results in error if redirects are true

### ISSUE THREAD

**Issue by stephendv1** [zaproxy/zaproxy#3673]
To reproduce through the API:
1. setMode to "attack"
2. sendHarRequest with a request and redirects set to true
3. Returns error: {"code":"mode_violation","message":"Operation not allowed for current mode"}

If step 2 is repeated but with redirects set to false, then the request succeeds.

**Comment by thc202** [comment]
Issue introduced with the changes for #2546.
