### ISSUE TITLE
Sites tree option Show only URLs in Scope not working

### ISSUE THREAD

**Issue by ErkanAksoy** [zaproxy/zaproxy#3675]
Hello,
I am using ZAProxy in the latest version of Kali Linux with all updated packages. I browse a few sites using the proxy and then on the sites menu I add a site to the default context (https://ad.turn.com.* for example). Finally I select to "Show only URLS in Scope" but it does just nothing. I still see the every URL and the site list. I tried to renew the ZAProxy profile by deleting the /root/.ZAP folder, refreshing the site tree. I also double checked the Context to be in Scope.
What might be going wrong here?
Regards.

**Comment by psiinon** [comment]
@ErkanAksoy  Can you add screenshots of your Sites tree and Context definition screen?

**Comment by ErkanAksoy** [comment]
Here are they @psiinon. I tried the same on my Ubuntu box as well.

![zap2](https://user-images.githubusercontent.com/10220856/27285215-98efccfe-5504-11e7-9782-ebca073c3853.png)

**Comment by psiinon** [comment]
Sorry, can you show us a screenshot of the "Include in Context" screen for the relevant context. Thanks

**Comment by ErkanAksoy** [comment]
It is what written default by the app when I pick a site to "Include in context". Even If I change it doesn't matter as following. (First line is default one, second is the one that I modify)
http://192.168.188.128.*
http://192.168.188.128*

![zap3](https://user-images.githubusercontent.com/10220856/27285496-9782e486-5505-11e7-9d76-0ff29086e556.png)


Thank you very much by the way. And my app version is 2.6.0

**Comment by thc202** [comment]
Thanks for the information! The URLs are being included in context, it's the filtering/rendering of the tree that's not working properly.

**Comment by ErkanAksoy** [comment]
As I am quite new in ZAProxy, I hope that I didn't done anything wrong but found a bug. So It would be better If someone else can confirm this. Honestly I am quite new in web app pentesting and still confused If should go for it after 12 years of systems admin job.

Thanks and regards.

**Comment by ErkanAksoy** [comment]
Here is the result of latest daily build, site tree doesn't populate site addresses anymore. Also filter is still not working according to number of sites in the tree.

![zap4](https://user-images.githubusercontent.com/10220856/27303056-1e4cedfe-5542-11e7-9b8d-2559a88c44e0.png)

**Comment by thc202** [comment]
With latest daily build do you mean the weekly release? That version does not include the fix.

**Comment by ErkanAksoy** [comment]
Sorry for that @thc202, I meant latest weekly build. I now see that build doesn't fix the issue on this topic, just take it as a feedback for D-2017-06-19 :)

**Comment by thc202** [comment]
No worries. I saw that behaviour with the weekly as well, that's why I was asking.

**Comment by thc202** [comment]
For the record, the issue mentioned in https://github.com/zaproxy/zaproxy/issues/3675#issuecomment-309567637 was addressed in #3351.
