### ISSUE TITLE
ZAP doesn't play nice with high-DPI displays

### ISSUE THREAD

**Issue by vdbaan** [zaproxy/zaproxy#3689]
After installing ZAP on windows 10 it shows tiny GUI elements, unlike other java products like Burp or Intellij IDEA.

**Comment by psiinon** [comment]
Yeah, this would be great to fix.
You can scale ZAP fonts, but thats not the right solution.
Confession time - I change my display properties just so that ZAP (and some other programs) look better :/
Anyone know the 'right' way to solve this?

**Comment by thc202** [comment]
@vdbaan could you share some screenshots of IDEA and ZAP?

**Comment by vdbaan** [comment]
Sure,
here are three screenshots: ZAP, Burp and IntelliJ as demonstration.
![2017-06-21 18_14_38-owasp zap - owasp zap 2 6 0](https://user-images.githubusercontent.com/2207005/27397504-67b09fa0-56ae-11e7-9401-940218e975f1.png)
![2017-06-21 18_15_53-burp suite professional v1 7 23 - temporary project](https://user-images.githubusercontent.com/2207005/27397506-6a89c2a6-56ae-11e7-83d4-7f618b36276a.png)
![2017-06-21 18_17_13-untitled - c__users_steven_documents_4 projects_untitled - intellij idea 2017](https://user-images.githubusercontent.com/2207005/27397510-6c772dba-56ae-11e7-991d-4cd5bbbb0b64.png)

**Comment by thc202** [comment]
Thank you!

**Comment by vdbaan** [comment]
Just a heads up, this might be actually a Nimbus issue. I build a small GUI myself and the only time that I have a problem is when I use Nimbus as laf, both Metal and System look 'normal'.
I have read that it could be fixed with jdk9, but will check and give you an update.

**Comment by psiinon** [comment]
@vdbaan oh thanks, if thats the case we should change our default from Nimbus :)

**Comment by vdbaan** [comment]
Or make it an 'Option' ;)

**Comment by thc202** [comment]
What's default L&F in Windows? Metal?

**Comment by thc202** [comment]
Regarding Java 9, it should work fine: https://bugs.openjdk.java.net/browse/JDK-8055212

**Comment by vdbaan** [comment]
Unfortunately yes, however UIManager.getSystemLookAndFeelClassName() does play nice.

**Comment by vdbaan** [comment]
my bad, I had 'Override high DPI scaling behaviour' set to system, that made all LAF versions seem to play nice. 
Disabling that setting shows that:
- Nimbus still looks eny-tiny
- SystemLAF looks better, however not everything scales nicely as visible in the next screenshot
![image](https://user-images.githubusercontent.com/2207005/27483292-ac6fc19c-581c-11e7-9b2e-706840488a60.png)
also tables do not look nice as visible in the next screenshot:
![image](https://user-images.githubusercontent.com/2207005/27483322-cf273986-581c-11e7-940a-2c4c8b746a6e.png)


Aka, back to the drawing board for a better solution.

**Comment by packet01101** [comment]
You all find a solution or work around for this?  Setting up a new laptop and having the exact same issue.  I would think someone has found some sort of workaround since this was from June 21 and today is Aug 28.  Again, precisely the same problem/look/tables as vdbaan.
Thanks all!

**Comment by kingthorin** [comment]
Nope, with only a small team of volunteers I'm not aware of this getting any attention yet. Solutions/fixes/code contributions welcome.

**Comment by thc202** [comment]
@packet01101 did you try with Java 9? We might even need to do some changes to play well with the new HiDPI support.

**Comment by cubewise-tryan** [comment]
There is a workaround, you can provide a "manifest" file to fix the DPI issues. I can't get it to work using ZAP.exe but it works with zap.bat. The manifest file must be called java.exe.mainfest, use Task Manager to find the location of java.exe that Zap is using.

![image](https://user-images.githubusercontent.com/22929868/37384275-fd62a1be-27a1-11e8-937a-4b8ec8fb8ff4.png)

See this article for details:

https://www.danantonielli.com/adobe-app-scaling-on-high-dpi-displays-fix/

**Comment by matthewoflynn** [comment]
Another workaround for Windows 10, try setting the "Compatibility Settings" in the Properties of the executable (see annotated screenshot below):

![image](https://user-images.githubusercontent.com/3179932/45784667-8be9b900-bc61-11e8-8679-76c320c8c7a4.png)

**Comment by psiinon** [comment]
Yeah, this is the best option right now. We should probably put this info in a FAQ...

**Comment by psiinon** [comment]
Turns out the correct solution is to use Java 9+ :)
Have now put all of the options in the FAQ: https://github.com/zaproxy/zaproxy/wiki/FAQhighdpi

**Comment by richpowell** [comment]
On linux if you edit the zap.sh file in /opt/zaproxy/zap.sh
Add -Dsun.java2d.uiScale=2.5 

or whatever scale you want to the last couple exec commands, fixed my issue on a 13" hi-dpi laptop.
```bash
# Start ZAP; it's likely that -Xdock:icon would be ignored on other platforms, but this is known to work
if [ "$OS" = "Darwin" ]; then
  # It's likely that -Xdock:icon would be ignored on other platforms, but this is known to work
  exec java -Dsun.java2d.uiScale=2.5 ${JMEM} ${JAVAGC} -Xdock:icon="../Resources/ZAP.icns" -jar "${BASEDIR}/zap-2.8.0.jar" "${ARGS[@]}"
else
  exec java -Dsun.java2d.uiScale=2.5 ${JMEM} ${JAVAGC} ${JAVADEBUG} -jar "${BASEDIR}/zap-2.8.0.jar" "${ARGS[@]}"
fi
```

**Comment by psiinon** [comment]
Thanks, I've updated https://github.com/zaproxy/zaproxy/wiki/FAQhighdpi with this option.
However the recommended fix is still to use Java 9+
