### ISSUE TITLE
The connection is reset when submit a request on api page

### ISSUE THREAD

**Issue by c676228** [zaproxy/zaproxy#3701]
when I click Browse API, the zap page is open, then I navigate to Core, view, alert, the url look like this:
http://zap/UI/core/view/alert/
the page opens ok. However when I try to submit the form.
![2017-06-23_connectionreset](https://user-images.githubusercontent.com/13107355/27504280-9a753034-583b-11e7-8cea-1dfc153c0c8f.png)
the following message is displayed. Can you help?

**Comment by kingthorin** [comment]
Details here: 
https://github.com/zaproxy/zaproxy/wiki/FAQapikey
https://github.com/zaproxy/zap-core-help/wiki/HelpReleases2_6_0#api-security-changes

**Comment by psiinon** [comment]
@c676228 did this solve your connection problems?
