### ISSUE TITLE
Session Fixation scanner no longer available?

### ISSUE THREAD

**Issue by kiran-dp** [zaproxy/zaproxy#3710]
Using ZAP through "owasp/zap2docker-stable" (https://github.com/zaproxy/zaproxy/wiki/Docker)
We are using modified version of za-baseline.py to invoke individual tests. Most of the tests are running fine except '40013 Session fixation' isn't working/loading. 

40013 extension is listed at https://github.com/zaproxy/zaproxy/blob/develop/src/doc/scanners.md

Found old issue which indicated plugin-id collision was reason for session fixation extention was not loaded, which got fixed. But 'SessionFixation.java' isn't available at "https://github.com/zaproxy/zap-extensions/tree/master/src/org/zaproxy/zap/extension/ascanrules", is there any other location for this extension or extension isn't available anymore? Am I missing something, please advise.

Thanks,
-Kiran

**Comment by thc202** [comment]
Session Fixation scanner is bundled in the Active scanner rules (beta) add-on (scanner is in the beta branch).

**Comment by kiran-dp** [comment]
Appreciate quick response, will check beta branch. 
Is there timeline for this to make it to master branch?

Thanks,
-Kiran

**Comment by kingthorin** [comment]
Scanner promotion is a long term goal, but not something that is terribly actively looked into.

If you have any interest in tackling some and contributing to open source let us know.

**Comment by kiran-dp** [comment]
Thanks. Looking into it, pulling https://github.com/zaproxy/zap-extensions/releases/download/2.5/ascanrulesBeta-beta-21.zap into docker, its loading 40013 now.  

Will be happy to contribute back if I get this working.

**Comment by thc202** [comment]
You can also install the add-on from within ZAP, using command line arguments (e.g. `-addoninstall ascanrulesBeta` [1]) or the ZAP API.

[1] https://github.com/zaproxy/zap-core-help/wiki/HelpCmdline

**Comment by kingthorin** [comment]
@kiran-dp is this issue resolved?

**Comment by kiran-dp** [comment]
Yes, closing the issue.
