### ISSUE TITLE
Lost focus on modal dialogs

### ISSUE THREAD

**Issue by JanPaulEttles** [zaproxy/zaproxy#3716]
I've only just started looking at ZAP after years of genuinely thinking it was no longer an active project... 

I quickly came across a bug that means I have to kill ZAP and restart it.

From the History panel context menu.
Attack->Fuzz...
Select location
Click Add...
Payloads Add...
Select File from the drop down.
ALT+TAB to your desktop
ALT+TAB back to ZAP and the modal dialogs are hidden, and it is not possible to interact with ZAP at all.

**Comment by thc202** [comment]
Which OS?

**Comment by JanPaulEttles** [comment]
ubuntu

**Comment by thc202** [comment]
OK, which WM are you using?

**Comment by psiinon** [comment]
And why did you think ZAP was no longer an active project??
I would really like to know this - I'd hate for other people to be under the same misconception :/

**Comment by JanPaulEttles** [comment]
WM: Compiz

**Comment by kingthorin** [comment]
I’m not able to recreate this on a modern version of Win10 or Kali. Closing as this is a singular report with no follow-up.

**Comment by thc202** [comment]
This might have been fixed with zaproxy/zap-extensions#2926.
