### ISSUE TITLE
Zap not working when running manually

### ISSUE THREAD

**Issue by ChandanaShetty** [zaproxy/zaproxy#3721]
I set up the Zap for running application manually
Have done changes in Browser  set the proxy as localhost and port as 8095
And in zap tool also made the changes in connection and chose my ie driver
When I hit the google or other screens it reports in zap tool but when I hit my local application its not responding and not reporting it

**Comment by thc202** [comment]
Which browser? Is the browser configured to proxy everything? (For example, Firefox will not proxy localhost and 127.0.0.1 by default.)

**Comment by ChandanaShetty** [comment]
Team,

Please find my Zap setting .

[cid:image001.png@01D2F410.44EB6FA0]

My Google chrome

[cid:image002.png@01D2F410.44EB6FA0]

Thanks & Regards,
Chandana Shetty

**Comment by thc202** [comment]
The attached images are not shown. Could you add them through GitHub website?

**Comment by ChandanaShetty** [comment]
[issue images.docx](https://github.com/zaproxy/zaproxy/files/1119143/issue.images.docx)

**Comment by xandfury** [comment]
I think chrome accepts system wide proxy. (This is, the proxy settings your operating system is using). Could you run the following snippet in **`cmd`** and share the results?

```
reg query "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings" | find /i "proxyserver"
```

**Comment by thc202** [comment]
@xandfury right, that's most likely the reason (i.e. excluding local addresses).

**Comment by thc202** [comment]
@ChandanaShetty any news about this?

**Comment by thc202** [comment]
Closing, insufficient evidence.
