### ISSUE TITLE
Spider scan status 0%

### ISSUE THREAD

**Issue by naveenjh23** [zaproxy/zaproxy#3722]
Hi,

As I am new to the ZAP, I have few doubts

Can I scan any URL in jenkins using ZAP plugin.? (Any domain name)
Is it mandatory to use GIT while scanning.?
Is it possible to scan if application URL is in Intranet.?

Our application is in intranet, when I tried to scan in Jenkins, spider scan is going in loop and status will be 0% at the end, and ACTIVE scan also not able to scan, finally build failure.
please find below,

Thank you in advance.

[ZAP Jenkins Plugin] SPIDER SCAN THE SITE [ http://xxx.yyy.com ]

3892 [ZAP-SpiderInitThread-0] INFO org.zaproxy.zap.extension.spider.SpiderThread  - Starting spidering scan on Context: testsession at Mon Jul 03 09:46:32 UTC 2017
3898 [ZAP-SpiderInitThread-0] INFO org.zaproxy.zap.spider.Spider  - Spider initializing...

[ZAP Jenkins Plugin] SPIDER SCAN STATUS [ 0% ]
3932 [ZAP-SpiderInitThread-0] INFO org.zaproxy.zap.spider.Spider  - Starting spider...
[ZAP Jenkins Plugin] ALERTS COUNT [ 0 ]

[ZAP Jenkins Plugin] SPIDER SCAN STATUS [ 0% ]
[ZAP Jenkins Plugin] ALERTS COUNT [ 0 ]

[ZAP Jenkins Plugin] SPIDER SCAN STATUS [ 0% ]
[ZAP Jenkins Plugin] ALERTS COUNT [ 0 ]

[ZAP Jenkins Plugin] SPIDER SCAN STATUS [ 0% ]
[ZAP Jenkins Plugin] ALERTS COUNT [ 0 ]

[ZAP Jenkins Plugin] SPIDER SCAN STATUS [ 0% ]
[ZAP Jenkins Plugin] ALERTS COUNT [ 0 ]

[ZAP Jenkins Plugin] SPIDER SCAN STATUS [ 0% ]
[ZAP Jenkins Plugin] ALERTS COUNT [ 0 ]

[ZAP Jenkins Plugin] SPIDER SCAN STATUS [ 0% ]
[ZAP Jenkins Plugin] ALERTS COUNT [ 0 ]

[ZAP Jenkins Plugin] SPIDER SCAN STATUS [ 0% ]
[ZAP Jenkins Plugin] ALERTS COUNT [ 0 ]

**Comment by thc202** [comment]
> status will be 0% at the end

We had reports of that in the past, but not enough information to know what's causing it. Following some questions:
 - Is ZAP running in a slave machine?
 - Could you provide the whole zap.log file? Just want to check if the spider is finishing or not. (In previous reports the spider finished but was still showing as 0% in Jenkins.)
 - Are you able to capture the network traffic between Jenkins and ZAP? To know who/what is answering to the ZAP API requests.

Answering your previous questions:
> Can I scan any URL in jenkins using ZAP plugin.? (Any domain name)

Yes, as long as ZAP is able to access it.

> Is it mandatory to use GIT while scanning.?

To which functionality are you referring to?

> Is it possible to scan if application URL is in Intranet.?

Yes, it should be possible to do that.

**Comment by naveenjh23** [comment]
Hi,
Thank you for the response,

No, ZAP is running in Master
Yes, Spider finished but showing as 0% in Jenkins.
I have attached a file, which is a console output of Jenkins.
[ZAP.txt](https://github.com/zaproxy/zaproxy/files/1121317/ZAP.txt)

**Comment by thc202** [comment]
The odd thing is that the Jenkins plugin continues after a while (it should wait if not 100%). Which Jenkins version are you using?

Could you add the following line to log4j.properties file (in the same
dir as the zap.log file) and provide the log/output again?
`log4j.logger.org.zaproxy.zap.extension.api=DEBUG`

**Comment by thc202** [comment]
It seems the spider is not finding anything(?), when attempting to active scan it ends up with: `URL Not Found in the Scan Tree (url_not_found)`.

**Comment by naveenjh23** [comment]
Thank you, now I am able to scan for the URL for the welcome page only.
I am facing issue in the authentication, can you please guide me, where to pass URL's username & password in what format. coz there are two Username & Password section.

![zap11](https://user-images.githubusercontent.com/25816027/27832021-ba52e934-60ea-11e7-9728-60678112c35d.JPG)

**Comment by naveenjh23** [comment]
I tried, while building it will open the target URL, but in the username it is taking some different username, not what I mentioned in the authentication section.

**Comment by naveenjh23** [comment]
Hi can you please suggest me on this.

**Comment by thc202** [comment]
Is the authentication working correctly when just using ZAP?

**Comment by naveenjh23** [comment]
Without authentication its working fine, only login page it is scanning.
when I pass username and password, URL (which I mentioned in jenkins) will open in a browser, but it wont login.
Can you guide me, where should I pass the username and pass, and what should I pass in 'Logged in indicator', Username parameter etc.

**Comment by psiinon** [comment]
Have a look at https://github.com/zaproxy/zaproxy/wiki/FAQformauth, particularly the 'Diagnosing problems' section.
As far as I can tell from this discussion it look like this is a configuration question rather than an issue with ZAP.
As such it would be better discussed on the ZAP User Group: https://groups.google.com/group/zaproxy-users so please ask any more questions there.

**Comment by amitcsknit** [comment]
I am facing exactly same issue of while using zap plugin with jenkins .
[ZAP Jenkins Plugin] SPIDER SCAN STATUS [ 0% ]
[ZAP Jenkins Plugin] ALERTS COUNT [ 0 ]


@naveenjh23 how did you solve it. plz help.

**Comment by thc202** [comment]
@amitcsknit use #4462 instead, but (afaik) there's no workaround.
