### ISSUE TITLE
SQL Injection False Positive

### ISSUE THREAD

**Issue by PaulCanfield** [zaproxy/zaproxy#3744]
I'm encountering a false positive SQL injection. When I run an active scan against any of my sites it will trigger alerts indicating a potential SQL injection. Upon examination of the situation I'm unable to find any evidence of vulnerability.

The alerts tab does not highlight or flag any of the response as indicative of a possible injection. In the headers and HTML output of the page I can find no evidence of any of the malicious parameters or anything out of the ordinary. In fact a HTML request with the malicious url and without any parameters yields the exact same result.

Here's the vexing thing, there's no connection to an SQL database, this is not a database driven site, yet something is causing ZAP to report that there's a potential SQL vulnerability.

- What is it that the SQL injection tool is looking for in order determine a failed response versus a successfully defended attack? 
- Is something missing, or being included in the page that may be causing this?
- Can you see anything in the response or html output that is causing it to create a false positive?

**Environment**
> ZAP Attack Proxy 2.6.0 compiled JAR
> OSX 10.9.5
> Apache
> PHP 5.4

**ALERT**
> Risk: High
> Parameter: query
> Attack: query" OR "1"="1" --
> Evidence:
> CWE ID: 89
> WASC ID: 19
> Source: Active
> The page results were successfully manipulated using the boolean conditions [query" AND "1"="1" -- ] and [query" OR "1"="1" -- ]
The parameter value being modified was NOT stripped from the HTML output for the purposes of the comparison
Data was NOT returned for the original parameter.
The vulnerability was detected by successfully retrieving more data than originally returned, by manipulating the parameter

**Request Headers**
> GET https://sub.domain.com/path/creative?query=query%22+AND+%221%22%3D%221%22+--+ HTTP/1.1
> User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0
> Pragma: no-cache
> Cache-Control: no-cache
> Content-Length: 0
> Referer: https://sub.domain.com/path/sitemap
> Host: sub.domain.com
> 

**Response Headers**
> HTTP/1.1 200 OK
> Date: Thu, 06 Jul 2017 22:05:52 GMT
> Server: Apache
> Strict-Transport-Security: max-age=31536000;
> Cache-Control: no-cache, no-store, must-revalidate, private
> Pragma: no-cache
> Vary: Accept-Encoding
> BALANCEDTO: PWEB24
> X-Frame-Options: sameorigin
> X-XSS-Protection: 1; mode=block
> X-Content-Type-Options: nosniff
> Referrer-Policy: origin
> Content-Security-Policy: **[HIDDEN]**
> X-Content-Security-Policy: **[HIDDEN]**
> X-WebKit-CSP: **[HIDDEN]**
> Content-Type: text/html; charset=UTF-8
> BALANCEDTO: CWEB2
> Set-Cookie: PHPSESSID=kqunokqbbb8ucvgqc4ib323rk1; path=/; secure; HttpOnly;HttpOnly;Secure
> Set-Cookie: ROUTEID=.2; path=/
> Set-Cookie: ROUTEID=.1;HttpOnly;path=/
> Set-Cookie: ROUTEID=.1;HttpOnly;path=/
> Set-Cookie: ROUTEID=.1;HttpOnly;path=/
> 

**RESPONSE BODY**
```
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
	    <link rel="stylesheet" type="text/css" href="https://sub.domain.com/path/assets/f913c1d2/css/bootstrap.css" />
		<link rel="stylesheet" type="text/css" href="https://sub.domain.com/path/assets/f913c1d2/css/jquery-ui.min.css" />
		<link rel="stylesheet" type="text/css" href="https://sub.domain.com/path/assets/f913c1d2/css/creative.css" />
		<script type="text/javascript" src="https://sub.domain.com/path/assets/f913c1d2/js/jquery.min.js"></script>
		<script type="text/javascript" src="https://sub.domain.com/path/assets/f913c1d2/js/bootstrap.min.js"></script>
		<script type="text/javascript" src="https://sub.domain.com/path/assets/f913c1d2/js/jquery-ui.min.js"></script>
		<title>Creative</title>
	</head>
	<body>
		<div class="container" id="main">
			<div class="masthead">
				<ul class="nav nav-pills pull-right">
					<li class="active">
						<a href="/path/creative" title="pages">Preview</a>
					</li>
				</ul>
				<h3 class="pageTitle muted">Creative</h3>
			</div>
			<hr/>
			
<p>
	<em>Following these links will set the site into preview mode; intended to review layout, copy and templates, some site functions will not 
		work properly and dynamic content will be populated with test data. 	</em>
</p>

<p>
	<em>
		<b><a class="showTestingVars">Set Testing Vars</a></b>
	</em>
	<div class="testingVars">
		<a class="hideTestingVars">close <img src="/path/assets/f913c1d2/images/icons/stop.png" /></a>
		<div id="testVarsFormContainer">
			<form id="testingVarsForm" method="get">
				<div class="row">
					<label>Language:</label>
					<select name="language">
						<option selected="selected"  value="en_us">English</option>
					</select>
					<br />
				</div>
		
				<div class="row">
					<label>Time Machine: </label>
					<input type="text" id="timepicker" name="timeMachineHMS" value="14:56:27" />			
					<input type="text" id="datepicker" name="timeMachine" value="07/06/2017" /> 
				</div>

				<div class="row">
					<label>Email: </label>
					<input name="emailMachine" value="" />
				</div>

				<div class="submitButton row" style="margin-bottom: 0px">
					<input type="submit" value="Set Cookies" class="btn btn-primary" />
				</div>
			</form>
		</div>
	</div>		
</p>
<hr />
			<h4>Main</h4>
		<ul>
												<li>
						<a target="_blank" href="/path/creative/load?route=%2F" >Landing</a>
					</li>
									</ul>
		</div>
	<script type="text/javascript" src="https://sub.domain.com/path/assets/57a5ed0f/js/main.js"></script>
<script type="text/javascript" src="https://sub.domain.com/path/assets/f913c1d2/js/creative.js"></script>
</body>
</html>
```

**Comment by kingthorin** [comment]
Closing as duplicate of: https://github.com/zaproxy/zaproxy/issues/3662
