### ISSUE TITLE
Websocket tab focuses on every handshake message

### ISSUE THREAD

**Issue by juhakivekas** [zaproxy/zaproxy#3747]
When a site uses websockets, the websocket tab will pop up to focus the first time a message is sent. On OSX 10.11.6 and ZAP 2.6.0 the websocket tab will get to focus on every new message not just the first one in the ZAP session. This causes annoyance when one is not working with websockets.

The issue has been shortly discussed and is quite old: https://groups.google.com/forum/#!msg/zaproxy-users/sMeU3jp_tBo/1z-ybfjCTVIJ

**Comment by thc202** [comment]
Are you sure it's on every message and not just when a handshake happens?

**Comment by juhakivekas** [comment]
You are correct, it's only on new hadshakes

**Comment by thc202** [comment]
Thanks!
