### ISSUE TITLE
Can't read cryptographic policy directory: unlimited and Can not initialize cryptographic mechanism

### ISSUE THREAD

**Issue by mozfreddyb** [zaproxy/zaproxy#3757]
When running zap.sh on openjdk-9-jre (ubuntu)

> Available memory: 15794 MB
> Setting jvm heap size: -Xmx3948m
> Exception in thread "main" java.lang.ExceptionInInitializerError
>         at java.base/javax.crypto.JceSecurityManager.<clinit>(JceSecurityManager.java:66)
>         at java.base/javax.crypto.Cipher.getConfiguredPermission(Cipher.java:2610)
>         at java.base/javax.crypto.Cipher.getMaxAllowedKeyLength(Cipher.java:2634)
>         at java.base/sun.security.ssl.CipherSuite$BulkCipher.isUnlimited(CipherSuite.java:602)
>         at java.base/sun.security.ssl.CipherSuite$BulkCipher.<init>(CipherSuite.java:574)
>         at java.base/sun.security.ssl.CipherSuite$BulkCipher.<clinit>(CipherSuite.java:460)
>         at java.base/sun.security.ssl.CipherSuite.<clinit>(CipherSuite.java:1074)
>         at java.base/sun.security.ssl.SSLContextImpl.getApplicableSupportedCipherSuiteList(SSLContextImpl.java:354)
>         at java.base/sun.security.ssl.SSLContextImpl.access$100(SSLContextImpl.java:42)
>         at java.base/sun.security.ssl.SSLContextImpl$AbstractTLSContext.<clinit>(SSLContextImpl.java:590)
>         at java.base/java.lang.Class.forName0(Native Method)
>         at java.base/java.lang.Class.forName(Class.java:292)
>         at java.base/java.security.Provider$Service.getImplClass(Provider.java:1844)
>         at java.base/java.security.Provider$Service.newInstance(Provider.java:1820)
>         at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
>         at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
>         at java.base/javax.net.ssl.SSLContext.getInstance(SSLContext.java:169)
>         at org.parosproxy.paros.network.SSLConnector.getClientSocketFactory(Unknown Source)
>         at org.parosproxy.paros.network.SSLConnector.<init>(Unknown Source)
>         at org.parosproxy.paros.network.SSLConnector.<init>(Unknown Source)
>         at org.zaproxy.zap.ZAP.<clinit>(Unknown Source)
> Caused by: java.lang.SecurityException: Can not initialize cryptographic mechanism
>         at java.base/javax.crypto.JceSecurity.<clinit>(JceSecurity.java:118)
>         ... 21 more
> Caused by: java.lang.SecurityException: Can't read cryptographic policy directory: unlimited
>         at java.base/javax.crypto.JceSecurity.setupJurisdictionPolicies(JceSecurity.java:324)
>         at java.base/javax.crypto.JceSecurity.access$000(JceSecurity.java:73)
>         at java.base/javax.crypto.JceSecurity$1.run(JceSecurity.java:109)
>         at java.base/javax.crypto.JceSecurity$1.run(JceSecurity.java:106)
>         at java.base/java.security.AccessController.doPrivileged(Native Method)
>         at java.base/javax.crypto.JceSecurity.<clinit>(JceSecurity.java:105)
>         ... 21 more
>

**Comment by kingthorin** [comment]
Seems to be: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=866924
<sub>Per IRC: http://logs.glob.uno/?c=mozilla%23websectools&s=17+Jul+2017&e=17+Jul+2017 </sub>

**Comment by thc202** [comment]
@mozfreddyb are you using `9~b170-2`?

For reference:
https://packages.ubuntu.com/search?keywords=openjdk-9-jre
(Version with the fix `9~b177-2` does not seem to be available yet)

**Comment by mozfreddyb** [comment]
Ubuntu 17.04 has `9-b161-1`, see below
```$ java -version
openjdk version "9-Ubuntu"
OpenJDK Runtime Environment (build 9-Ubuntu+0-9b161-1)
OpenJDK 64-Bit Server VM (build 9-Ubuntu+0-9b161-1, mixed mode)```

**Comment by thc202** [comment]
OK, thank you.

**Comment by kingthorin** [comment]
Does this need to stay open?

**Comment by Soulsurfering** [comment]
You can fix this issue by creating a symbolic link 'conf' to the lib directory, e.g.
`> cd /usr/lib/jvm/java-9-openjdk-amd64`
`sudo ln -s lib conf`
