### ISSUE TITLE
ZAP HOST NOT permitted while running ZAP

### ISSUE THREAD

**Issue by ksk26** [zaproxy/zaproxy#3764]
[ZAP Jenkins Plugin] LOAD SESSION AT: [ C:\Jenkins\workspace\ZAP_EXAMPLE_JOB\SFDC53ZAP\ZAP5.3Session.session ]
6701 [ZAP-ProxyThread-2] WARN org.zaproxy.zap.extension.api.API  - Request to API URL http://zap/xml/core/action/loadSession/?apikey=ZAPROXY-PLUGIN&name=C%3A%5CJenkins%5Cworkspace%5CZAP_EXAMPLE_JOB%5CSFDC53ZAP%5CZAP5.3Session.session& from <HOST IP> not permitted
6706 [ZAP-ProxyThread-3] WARN org.zaproxy.zap.extension.api.API  - Request to API URL http://zap/xml/core/action/loadSession/?apikey=ZAPROXY-PLUGIN&name=C%3A%5CJenkins%5Cworkspace%5CZAP_EXAMPLE_JOB%5CSFDC53ZAP%5CZAP5.3Session.session& from <HOST IP> not permitted
ERROR: org.zaproxy.clientapi.core.ClientApiException: java.net.SocketException: Unexpected end of file from server
	at org.zaproxy.clientapi.core.ClientApi.callApiDom(ClientApi.java:329)

**Comment by thc202** [comment]
It's not the `zap` domain that's not permitted, but the remote address of the client connecting to the API.

There's an example in https://github.com/zaproxy/zaproxy/wiki/FAQapikey on how to add/permit it.

**Comment by thc202** [comment]
btw, how/where is the job being executed? I'd expect the client API to be in the same machine as ZAP (thus using one of the allowed addresses).

**Comment by thc202** [comment]
@ksk26 any news on this?

**Comment by kingthorin** [comment]
@ksk26 Any update?
