### ISSUE TITLE
zap-baseline.py errors with UnicodeEncodeError: 'ascii' codec can't encode characters in position 243223-243224: ordinal not in range(128)

### ISSUE THREAD

**Issue by the-nw1-group** [zaproxy/zaproxy#3780]
When running a scan of our application using zap-baseline.py within the owasp/zap2docker-stable:latest docker container, I get the following error:
```
Traceback (most recent call last):
  File "/zap/zap-baseline.py", line 561, in main
    f.write (zap.core.htmlreport())
UnicodeEncodeError: 'ascii' codec can't encode characters in position 243223-243224: ordinal not in range(128)
...
ERROR <type 'exceptions.UnicodeEncodeError'>
```
I get this error when requesting an html report (-r) or a simple error when requesting a markdown report (-w). XML seems to be ok, although I suspect the dev's won't be happy with that.

The full command line is:
```
/zap/zap-baseline.py -a -j -m 30 -t ${url} -r report.html
```

**Comment by omerlh** [comment]
We had the same error when using the Zap-cli, see Grunny/zap-cli#27 for more details. We solved it by saving the report using in binary format, see the PR in the issue. Should be easy to apply the same fix here.

**Comment by Grunny** [comment]
Yep, opened a quick PR to apply a similar fix here: https://github.com/zaproxy/zaproxy/pull/3786
