### ISSUE TITLE
I can't attack particular site.

### ISSUE THREAD

**Issue by NikitaTurakhia** [zaproxy/zaproxy#3785]
Hello,

I am running zap against my coded ui script. After running my script I am trying to attack my particular site but I am not able to do it.

How to include only site I want and exclude every other sites?

**Comment by kingthorin** [comment]
Could you be a bit more specific than 'not doing it'?

**Comment by NikitaTurakhia** [comment]
Yeah sure.

What I am doing is I am running mu coded ui script and running zap in background. So after running my script successfully I want to attack particular site not all the other sites. So I wanted to know that is there any other way to attack and generate a report for a particular site I want?

**Comment by kingthorin** [comment]
Sure define a context for what is in scope and scan that.

**Comment by NikitaTurakhia** [comment]
Can you tell me in brief how to do that because I am new in this tool.

Thank you in advance.

**Comment by kingthorin** [comment]
- https://github.com/zaproxy/zap-core-help/wiki/HelpStartConceptsContexts
- https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsSessionContexts
- https://zaproxy.blogspot.ca/2016/02/zap-newsletter-2016-february.html?m=1#Tutorial
- https://www.google.ca/amp/s/chrisdecairos.ca/intercepting-traffic-with-zaproxy/amp/

**Comment by NikitaTurakhia** [comment]
Thank you so much @kingthorin for the help.

**Comment by kingthorin** [comment]
In general the ZAP User Group https://groups.google.com/group/zaproxy-users is a much better places for questions than the issue tracker.

**Comment by NikitaTurakhia** [comment]
Okay. I will use zap user group if I will have any questions. Thanks.

**Comment by kingthorin** [comment]
Thanks @nikitaturakhia
