### ISSUE TITLE
ChromeDriver 2.31 released

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#3790]
https://sites.google.com/a/chromium.org/chromedriver/downloads
Note that as of now the PR for 2.30 still hasnt been merged: https://github.com/zaproxy/zap-libs/pull/8

For info: alerted via https://visualping.io/ :)

**Comment by thc202** [comment]
Do you plan to update that pull request? Or, left for other/later change?

**Comment by psiinon** [comment]
Good question ;)
I'll try to try it out today...

**Comment by psiinon** [comment]
Have updated https://github.com/zaproxy/zap-libs/pull/8
