### ISSUE TITLE
JBrowserDriver add-on?

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#3795]
https://github.com/MachinePublishers/jBrowserDriver
"A programmable, embeddable web browser driver compatible with the Selenium WebDriver spec -- headless, WebKit-based, pure Java "
Sounds very interesting - would be good to try out and see if its better than HtmlUnit, if so then this could be the headless browser of choice.
And might be easier than creating a PhantomJS add-on #3188

**Comment by psiinon** [comment]
Note that jBrowserDriver currently supports Selenium 2, while we're moving to Selenium 3 :/
I've raised an issue: https://github.com/MachinePublishers/jBrowserDriver/issues/290

**Comment by psiinon** [comment]
Looks like jBrowserDriver has not been updated for a couple of years, so not worth supporting?

**Comment by thc202** [comment]
+1 and we should also look at removing support from Zest (and forked crawljax).

**Comment by thc202** [comment]
Closing, no updates to `jBrowserDriver` have been done since the previous comments. (Support in Zest has been removed zaproxy/zest#238.)
