### ISSUE TITLE
Upgrade to Webswing 2.4

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#3797]
The Docker images currently include webswing 2.3
Webswing 2.4 has been released: http://webswing.org/#!/downloads
Upgrading should be easy but testing will be required :)

- https://github.com/zaproxy/zaproxy/blob/develop/build/docker/Dockerfile-stable#L54
- https://github.com/zaproxy/zaproxy/blob/develop/build/docker/Dockerfile-weekly#L55
- https://github.com/zaproxy/zaproxy/blob/develop/build/docker/Dockerfile-live#L71

**Comment by thc202** [comment]
Version 2.4 has an issue that prevents some of the dialogues from working properly: #3797

**Comment by thc202** [comment]
#3553 not this one ;)

**Comment by psiinon** [comment]
Oops, didnt spot you'd already raised this. Closing as a dup of #3553
