### ISSUE TITLE
Not accepting valid URL

### ISSUE THREAD

**Issue by rubley00** [zaproxy/zaproxy#3802]
This is a valid URL, it is not accepted by the application

https://host.xxxxxx.net/?!=equipment|multiplexer|list

**Comment by kingthorin** [comment]
Could you please elaborate on "not accepted by the application"?

Is there an error? Is something not behaving as you expected?

**Comment by thc202** [comment]
Most likely because ZAP expects the chars `|` to be encoded (e.g. `https://host.xxxxxx.net/?!=equipment%7Cmultiplexer%7Clist`).

**Comment by rubley00** [comment]
It pops a message saying "Enter a valid url"

**Comment by rubley00** [comment]
Apparently | is considered unsafe and it supposed to be encoded, however I've been using it for many years without ever seeing any issues. The RFC's explanation that "gateways and other transport agents are known to sometimes modify such characters" doesn't seem to hold true anymore.

**Comment by kingthorin** [comment]
Ok, so this issue can be closed now that you know the solution?

**Comment by rubley00** [comment]
Yeah. Although I still believe there is no reason to give an error, the URL works everywhere on every device
