### ISSUE TITLE
Error creating new session

### ISSUE THREAD

**Issue by johnchan1874** [zaproxy/zaproxy#3804]
Hello - I am new to ZAP. I launched the JAR version and tried to start using the tool by answering the question "Do you want to persist the ZAP session?". No matter what I answered ("persist this session with name based on the current timestamp", "persist this session but I want to specify the name and location" or "I do not want to persist this session"), it only popped up the error message "Error creating new session". Can't really find anything helpful online.

Please help!

**Comment by psiinon** [comment]
Is there any particular reason for launching ZAP via the jar file?
What platform are you using?
We recommend you use the zap.sh or zap.bat scripts - they set up the environment correctly.

**Comment by johnchan1874** [comment]
Thank you for your response, Simon. The issue is that I need to use my Win7 work machine, on which I don't have local admin rights. Also, corporate software whitelisting is turned on, so I can't run any "random" executable (JAR isn't blacklisted though). I need to run some scans with ZAP on couple internal web apps.. So I tried to launch the JAR version directly. But no luck, the "error creating new session" error popped up.

**Comment by kingthorin** [comment]
You should work with your IT department to get things sorted out, instead of trying to bypass their policies and controls.

**Comment by psiinon** [comment]
Have you tried using zap.bat?
But I agree with @kingthorin, thats your best option ;)
Closing as it doesnt appear to be a ZAP issue. Questions are best asked on the ZAP User Group: https://groups.google.com/group/zaproxy-users
