### ISSUE TITLE
Path Traversal warning with socket.io

### ISSUE THREAD

**Issue by Mikhail1994** [zaproxy/zaproxy#3807]
Hello. I use socket.io library in my web-application and every time I use ZAP active scanning on it the reports show that url which is used for 'handshake' connection could be affected by path traversal attack. Am i missing something or is it false positive?
![default](https://user-images.githubusercontent.com/20993351/29071245-585c62a6-7c4b-11e7-8566-51c86f21b897.PNG)

**Comment by kingthorin** [comment]
Can you provide the associate request and response?

**Comment by Mikhail1994** [comment]
The moment we open a web app with socket.io included in it the connection i described above established. If i do understand the concept of socket.io work then the request remains the same but only the 't' query changes in the process while the app is working. I'm not sure that i can tell you the response.
Request: https://tigris.ml/socket.io/?EIO=3&transport=polling&t=Lt1pWaj

**Comment by kingthorin** [comment]
Thanks I understand the URL you're talking about but am looking for the full text of the request and response related to the alert in your report. (I have no idea that tigris.ml is and have no authority to test it, so I can't recreate what you're seeing.)

**Comment by Mikhail1994** [comment]
This is the request from ZAP:
GET https://tigris.ml/socket.io/?EIO=3&transport=polling&t=Lt1rXxr&sid= HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:54.0) Gecko/20100101 Firefox/54.0
Accept: */*
Accept-Language: ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3
Referer: https://tigris.ml/employees/home
origin: https://tigris.ml
Cookie: _ga=GA1.2.1728481135.1501484247; sessionId=s%3AlljWlubDqzP7y1G1SlxQAlXwOQZLccN3.%2FTwAsUEgZhEnaUlXL%2BmuaPW17g0fVpkLwVaJxUu3Qy4; io=zxuVB5wCrtv_gTKJAAEZ
Connection: keep-alive
Content-Length: 0
Host: tigris.ml
------------------------------------
The response:
HTTP/1.1 200 OK
Server: nginx/1.10.3 (Ubuntu)
Date: Tue, 08 Aug 2017 12:36:05 GMT
Content-Type: text/plain; charset=UTF-8
Content-Length: 104
Connection: keep-alive
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: https://tigris.ml
Set-Cookie: io=XQndte1RAt0ABguTAAFT; Path=/; HttpOnly
Strict-Transport-Security: max-age=63072000; includeSubdomains
X-Frame-Options: DENY
X-Content-Type-Options: nosniff
Content-Security-Policy: default-src 'self'; script-src 'self' https://www.google-analytics.com https://www.googletagmanager.com 'unsafe-inline' 'unsafe-eval'; img-src 'self' data: https://www.google-analytics.com; style-src 'self' 'unsafe-inline'; font-src 'self' data:; frame-src 'self'; connect-src 'self' https://apis.google.com; object-src 'none'
Referrer-Policy: no-referrer-when-downgrade

Response body:
97:0{"sid":"XQndte1RAt0ABguTAAFT","upgrades":["websocket"],"pingInterval":25000,"pingTimeout":60000}2:40

**Comment by kingthorin** [comment]
Might be a duplicate zaproxy/zaproxy#3735

**Comment by thc202** [comment]
@Mikhail1994 which version of ZAP and Active scanner rules add-on are you using?

**Comment by Mikhail1994** [comment]
@thc202 ZAP version is 2.6.0 and Actvie scanner rules version is 26

**Comment by thc202** [comment]
Thanks! This should be fixed with zaproxy/zap-extensions#904. Would you mind trying a weekly release to verify the fix? [1]

[1] https://github.com/zaproxy/zaproxy/wiki/Downloads#zap-weekly

**Comment by kingthorin** [comment]
@mikhail1994 have you been able to try with a weekly?

**Comment by Mikhail1994** [comment]
@kingthorin I haven't for now unfortunately. I will leave my feedback as soon as i try it. Thank you!

**Comment by hvo408-brightplan** [comment]
+1.  I have the same issue and will try out the weekly build later this week and report back.

**Comment by kingthorin** [comment]
@Mikhail1994  @hvo408-brightplan any update?

**Comment by kingthorin** [comment]
@Mikhail1994 @hvo408-brightplan any update?

**Comment by thc202** [comment]
Closing as fixed. Tested with an application that uses Socket.IO (`gdbgui` [1]), with the version available in the marketplace the alert is raised, with the latest version (built from source) the issue is no longer raised.

[1] https://github.com/cs01/gdbgui

**Comment by kingthorin** [comment]
Thanks @thc202!
