### ISSUE TITLE
Zap2docker-stable command from docs not working

### ISSUE THREAD

**Issue by haydenflinner** [zaproxy/zaproxy#3812]
```
docker run -i owasp/zap2docker-stable zap-cli quick-scan --self-contained     --start-options '-config api.disablekey=true' http://myurl.com
[INFO]            Starting ZAP daemon
[ERROR]           Timed out waiting for ZAP to start.
```

I think this may be related to: if I log into the same image with bash, I can't run my own tool within the image because it says something else is already listening on the port. OSX if it matters.

**Comment by kingthorin** [comment]
What docs?

**Comment by thc202** [comment]
Seems to be https://github.com/zaproxy/zaproxy/wiki/Docker

@haydenflinner did you try specify other port? (e.g. `zap-cli` arg `-p 8081`)

**Comment by haydenflinner** [comment]
Same result. Is it working for someone else? I wouldn't be surprised if my Docker was set up wrong somehow.

**Comment by thc202** [comment]
Yeah, it's working here (with owasp/zap2docker-stable, ID 12c3b9347b07).

Could you try adding `--verbose` flag to `zap-cli`? Also, check the zap.log to see if there's any error?

**Comment by thc202** [comment]
@haydenflinner any news on this?

**Comment by haydenflinner** [comment]
I just abandoned using Docker. Thanks for trying though!

**Comment by thc202** [comment]
OK, thanks for lettings us know!

**Comment by robyoung** [comment]
I am having the same issue. It looks like it is because the ZAP daemon is failing to start with the following error.

```
1817 [ZAP-daemon] ERROR org.zaproxy.zap.ZAP$UncaughtExceptionLogger  - Exception in thread "ZAP-daemon"
java.lang.ExceptionInInitializerError
        at org.zaproxy.zap.control.CoreFunctionality.createExtensions(CoreFunctionality.java:68)
        at org.zaproxy.zap.control.CoreFunctionality.getBuiltInExtensions(CoreFunctionality.java:60)
        at org.zaproxy.zap.control.ExtensionFactory.loadAllExtension(ExtensionFactory.java:107)
        at org.parosproxy.paros.control.Control.addExtension(Control.java:160)
        at org.parosproxy.paros.control.AbstractControl.loadExtension(AbstractControl.java:53)
        at org.parosproxy.paros.control.Control.init(Control.java:123)
        at org.parosproxy.paros.control.Control.initSingletonWithoutViewAndProxy(Control.java:313)
        at org.zaproxy.zap.HeadlessBootstrap.initControl(HeadlessBootstrap.java:58)
        at org.zaproxy.zap.DaemonBootstrap$1.run(DaemonBootstrap.java:77)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
        at sun.awt.HeadlessToolkit.getMenuShortcutKeyMask(HeadlessToolkit.java:236)
        at org.parosproxy.paros.extension.edit.ExtensionEdit.<clinit>(ExtensionEdit.java:49)
        ... 10 more
```

**Comment by thc202** [comment]
Which image? A weekly?

**Comment by robyoung** [comment]
Yes, `owasp/zap2docker-weekly:latest` (`4cb9f5811545`)

**Comment by psiinon** [comment]
@robyoung how are you starting ZAP?

**Comment by robyoung** [comment]
I've tried the commands listed on the [main Docker page](https://github.com/zaproxy/zaproxy/wiki/Docker). Specifically I've tried the following

- `docker run -ti owasp/zap2docker-weekly zap.sh -daemon -port 8080 -host 0.0.0.0`
- `docker run -ti owasp/zap2docker-weekly zap.sh -daemon -port 8080 -host 0.0.0.0 -config api.disablekey=true`
- `docker run -i owasp/zap2docker-weekly zap-cli --verbose quick-scan --self-contained --start-options '-config api.disablekey=true' http://example.org`

All of which fail due to the same exception.

**Comment by robyoung** [comment]
I can confirm that I do not get the same error when using `owasp/zap2docker-stable:latest` (`12c3b9347b07`).

**Comment by robyoung** [comment]
@psiinon Should I open a new issue for this or will you reopen this one?

**Comment by thc202** [comment]
A new weekly image will be available soon that fixes that issue (#3798), in the meantime you can use the live image (which has the same contents).

**Comment by thc202** [comment]
And thanks for letting us know of the issue in the weekly docker image!

**Comment by thc202** [comment]
The new weekly image (`e38ce0264af7`) is now available.

**Comment by dizeee** [comment]
The same thing happened to me just now. It worked for 3 or 4 times, then started to time out constantly:
```
$ docker run --rm -i owasp/zap2docker-stable zap-cli --verbose quick-scan --self-contained --start-options '-config api.disablekey=true' http://example.org
[INFO]            Starting ZAP daemon
[DEBUG]           Starting ZAP process with command: /zap/zap.sh -daemon -port 8080 -config api.disablekey=true.
[DEBUG]           Logging to /zap/zap.log
[ERROR]           Timed out waiting for ZAP to start.
```
Image ID is 40848e80b7fb.

**Comment by thc202** [comment]
That's working here. I'd suggest checking the zap.log file, it should contain the reason why ZAP did not start in time.
