### ISSUE TITLE
Change right-click "Resend..." to "Send to Manual Request Editor"

### ISSUE THREAD

**Issue by claudijd** [zaproxy/zaproxy#3818]
One of the more common user actions I think a lot of testers do after they've built a site map is the ability to right-click and select a meaningful action.  One of the most common actions for me is to take a pre-existing request from the site map or individual alerts and send those requests to either the Manual Request Editor (repeater in Burp terminology) or the Fuzzer (intruder in Burp terminology).

It's possible I'm just doing it wrong, but I think a lot of other Burp heavy users may have this as an expectation when trying out or playing with ZAP for the first time.  If they can't find a quick way to do something useful, this may stunt adoption in the tool.

Hope this helps!

**Comment by kingthorin** [comment]
Resend...

![001](https://user-images.githubusercontent.com/7570458/29224333-db65babe-7e97-11e7-9aac-13defe3635b8.png)
![002](https://user-images.githubusercontent.com/7570458/29224335-db664ba0-7e97-11e7-8b5a-a91ba43af02c.png)
![003](https://user-images.githubusercontent.com/7570458/29224334-db65b212-7e97-11e7-9142-a53e8f04184e.png)

**Comment by claudijd** [comment]
@kingthorin what is the difference between "Resend..." and "Manual Request Editor"?  Are they basically the same?

**Comment by kingthorin** [comment]
Yes essentially the same.

Should be more consistent in naming.

**Comment by claudijd** [comment]
What about "Send to Manual Request Editor" in the drop down, but then it drops you into the "Manual Request Editor"?

**Comment by kingthorin** [comment]
Seems reasonable to me.

**Comment by thc202** [comment]
In almost all tabs that show a (HTTP) message the Fuzzer can be accessed with the context menu "Attack" > "Fuzz...". In the Request/Response tabs it can be accessed with "Fuzz..." menu item, adding the selection as a fuzz position.

**Comment by psiinon** [comment]
I dont like 'Send to Manual Request Editor' I'm afraid - sounds too Burp like :/

**Comment by psiinon** [comment]
"Open in Manual Editor..." I could live with maybe, or perhaps "Resend / Open in Manual Editor..." ?

**Comment by kingthorin** [comment]
Ok that's fair.
