### ISSUE TITLE
mysql NULL value in where in CLAUSE

### ISSUE THREAD

**Issue by YangYongZhi** [zaproxy/zaproxy#3827]
When I send a view messages request  to zap api (View Messages), there is only a empty history list return to me.
I think it's because:

The value of key "history.ps.gethistoryidsnottypes" in mysql.properties is :
history.ps.gethistoryidsnottypes	= SELECT HISTORYID FROM HISTORY WHERE SESSIONID = ? AND HISTTYPE NOT IN (?,?,?,?,?,?,?,?,?,?) ORDER BY HISTORYID

and the ViewMessages api will call query method like that:

tableHistory.getHistoryIdsExceptOfHistType(Model
					.getSingleton().getSession().getSessionId(), HistoryReference.TYPE_TEMPORARY)

so, the sql statement will be constructed :

SELECT HISTORYID FROM HISTORY WHERE SESSIONID = 1502690212412 
AND HISTTYPE NOT IN (0,null,null,null,null,null,null,null,null,null)
ORDER BY HISTORY

it will be return a empty history list.

I think it will be like this :
SELECT HISTORYID FROM HISTORY WHERE SESSIONID = 1502690212412 
AND HISTTYPE NOT IN (0)
ORDER BY HISTORY

https://stackoverflow.com/questions/3913364/mysql-null-value-in-where-in-clause

Thanks.

**Comment by thc202** [comment]
Thanks for raising the issues!
