### ISSUE TITLE
Weird docker issue with using upper-case letters in volume mapping names

### ISSUE THREAD

**Issue by claudijd** [zaproxy/zaproxy#3829]
I happened across this issue today, but it's probably more of a docker thing than anything...

If we invoke a full-scan, like so....

`docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-weekly zap-full-scan.py -r report.html -t http://example.com/`

... and the results of pwd contain an upper-case letter, it seems there is some weird issue where docker is trying to validate that and bombs out, with the following error...

`docker: invalid reference format: repository name must be lowercase.
See 'docker run --help'.`

I just found this interesting, as I'm guessing there was no expectation that this would bomb out the docker instance and it took a little experimentation to work around that and I figured this could help others, who were following instructions at https://github.com/zaproxy/zaproxy/wiki/Docker.

**Comment by traw** [comment]
You have to remove extra `-v` from command. 
Updated command will look something like this
`docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-weekly zap-full-scan.py -r report.html -t http://example.com/`

**Comment by claudijd** [comment]
@traw that was a typo and the same behavior applies without the extra -v, at least in my case.

**Comment by claudijd** [comment]
I believe I may have a work around for this...

docker run -v "$(pwd)":/zap/wrk/:rw -t owasp/zap2docker-weekly zap-full-scan.py -r report.html -t http://example.com/

If we quote the outside of the PWD, we are more clearly distinguishing that the PWD is a volume mapping and not to be confused with other command line parsing.

**Comment by claudijd** [comment]
I believe this issue was based on user error and I can no longer reproduce it.

**Comment by thc202** [comment]
Thanks for letting us know!
