### ISSUE TITLE
Update Selenium library to 3.7.1

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#3830]
Looks like its just been released: http://www.seleniumhq.org/download/
Thanks to https://visualping.io/ for the alert :)

**Comment by psiinon** [comment]
Java changelog: https://raw.githubusercontent.com/SeleniumHQ/selenium/master/java/CHANGELOG

**Comment by psiinon** [comment]
Note that it looks like we should update IEDriverServer at the same time #3831

**Comment by thc202** [comment]
Recommended for geckodriver 0.19 (#3890).

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#1146.
