### ISSUE TITLE
Allow IPv6 loopback address to access the API by default

### ISSUE THREAD

**Issue by apeppelsICTU** [zaproxy/zaproxy#3836]
First of all, thank you for your awesome tool. We have made our own version of zap_basline including authentication at https://github.com/ICTU/zap-baseline/

My issue is this: if the server does not reply according to protocol, when the request is made at  zapv2/\_\_init\_\_.py line 147, the ConnectionError thrown by httplib is not being caught.

> DEBUG:root:Spider http://SensitiveURL.Redacted
> DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): localhost
> WARNING:root:I/O error: ('Connection aborted.', BadStatusLine("''",))
> Traceback (most recent call last):
>   File "/zap/zap-baseline-custom.py", line 517, in main
>     spider_scan_id = zap.spider.scan(target, recurse=True)
>   File "/usr/local/lib/python2.7/dist-packages/zapv2/spider.py", line 189, in scan
>     return six.next(six.itervalues(self.zap._request(self.zap.base + 'spider/action/scan/', params)))
>   File "/usr/local/lib/python2.7/dist-packages/zapv2/__init__.py", line 157, in _request
>     data = self._request_api(url, get)
>   File "/usr/local/lib/python2.7/dist-packages/zapv2/__init__.py", line 147, in _request_api
>     return self.session.get(url, params=query, proxies=self.__proxies, verify=False)
>   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 501, in get
>     return self.request('GET', url, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
>     r = adapter.send(request, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 473, in send
>     raise ConnectionError(err, request=request)
> ConnectionError: ('Connection aborted.', BadStatusLine("''",))

<sub>Edited by @kingthorin 20170821: Formatting tweak.</sub>

**Comment by thc202** [comment]
That answer is from ZAP itself, which seems to be caused by missing API key (more information in: <https://github.com/zaproxy/zaproxy/wiki/FAQapikey>), you can pass the API key when creating the `ZAPv2` object:
```Python
zap = ZAPv2(proxies={'http': 'http://' + zap_ip + ':' + str(port), 'https': 'http://' + zap_ip + ':' + str(port)}, apikey='ApiKey')
```
but you need to set it when starting ZAP (either that or disable the API key).

**Comment by apeppelsICTU** [comment]
Ah my mistake :). Update must've set ik back to default settings causing it to be re-enabled. The error's not very informative, is it?

**Comment by psiinon** [comment]
Its deliberately not very informative I'm afraid - more useful error messages could be used by sites to detect the fact that ZAPs being used ;)

**Comment by thc202** [comment]
Note that you can always check in the logs why ZAP didn't answer (e.g. in this case using `docker logs` command).

**Comment by apeppelsICTU** [comment]
In the logs, this is the error i'm getting. Should i maybe open a new issue for this, for clarity's sake?


69911 [ZAP-ProxyThread-60] WARN org.zaproxy.zap.extension.api.API  - Request to API URL http://zap/JSON/core/view/version/ from 0:0:0:0:0:0:0:1 not permitted

**Comment by apeppelsICTU** [comment]
FYI, the option to disable the use of an API key is set in the config

**Comment by apeppelsICTU** [comment]
The issue seems to be with the official zap-baseline.py using ipv6, our fork was still at ipv4

**Comment by apeppelsICTU** [comment]
Thank you kindly for reopening the issue, glad i can contribute somewhat :)
I've added api.addrs.addr.name=0:0:0:0:0:0:0:1 to the config, however now it fails on this:

`Request to API URL http://zap/JSON/core/view/version/ with host header zap not permitted`

At https://groups.google.com/forum/#!topic/zaproxy-jenkins/PJBysyheHdw I see you mention this as a bug in the weekly of march 20th, I can't seem to find much info on resolving it elsewhere. How might i go about this? Thanks ever so much in advance.

**Comment by thc202** [comment]
Right, sorry, just adding that overrides the whole list of allowed addresses, you need something like:
`-config api.addrs.addr(0).name=0:0:0:0:0:0:0:1 -config api.addrs.addr(1).name=zap -config api.addrs.addr(2).name=localhost -config api.addrs.addr(3).name=127.0.0.1`

We need to update that FAQ entry to refer to https://github.com/zaproxy/zaproxy/wiki/FAQconfigValues
