### ISSUE TITLE
Path traversal false positive

### ISSUE THREAD

**Issue by robyoung** [zaproxy/zaproxy#3844]
I am seeing an alert for Path Traversal but the offending parameter has been given no value.

Label | Value
------ | -------
URL | http://localhost:8000/feedback/?next=
Risk | High
Confidence | Medium
Parameter | next
Attack | 
Evidence | 
CWE ID | 22
WASC ID | 33

## Request
```
GET http://localhost:8000/feedback/?next= HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0
Pragma: no-cache
Cache-Control: no-cache
Content-Length: 0
Referer: http://localhost:8000/
Host: localhost:8000
```

### Headers
```
HTTP/1.0 200 OK
Date: Wed, 23 Aug 2017 08:39:45 GMT
Server: WSGIServer/0.1 Python/2.7.13
Vary: Cookie, Accept-Language
X-Frame-Options: SAMEORIGIN
Content-Type: text/html; charset=utf-8
Content-Length: 11739
Content-Language: en
Set-Cookie: csrftoken=qAHkfCmL0rMxNfutRZIHjn7oRGcpc9UZEMgeOohN7fAxEGz1to743WUzIuKmwsnF; expires=Wed, 22-Aug-2018 08:39:44 GMT; httponly; Max-Age=31449600; Path=/
Set-Cookie: sessionid=".eJwVwUtSgzAAANATMVP-ZuEC-SUNEoNxINkwaQVKkaSUApbTO77XBf_ehGKAfq8ARfIOwo4ZI9eJYE01nwNR4uxyoJgpK_zMn75AxUw8ALdpokIabgZhG1dhgtF64reV16PZUd23fjBOVzffQvwTVXdH8Ap7gf0wZfXQV9vBBhnaycVgPWmzB8h_n0hSPA3VcNXAs1vEL_OjtpQyj40udEIjnK5xjjQBw2I2ziak3aeb0vBjFwHPloUxeuG_xLePyiuXVKLDLi3YDnWsdlKOc0K0ucHeuxVfr3-5nFKs:1dkRCT:nNtzGiG0PU0yTiPYAtV3PRZOfRI"; httponly; Path=/
```

### Body
I can't provide the raw output as it is large and contains sensitive information. However I can answer any questions you have about it.

**Comment by kingthorin** [comment]
This seems to be a duplicate of zaproxy/zaproxy#3735

**Comment by thc202** [comment]
Based on the alert details it's not the same issue.

@robyoung which ZAP version are you using? A weekly?

**Comment by kingthorin** [comment]
@robyoung which ZAP version are you using? A weekly?

**Comment by kingthorin** [comment]
@robyoung which ZAP version are you using? A weekly?

**Comment by kingthorin** [comment]
I'm unable to recreate this issue and the original reporter has stopped answering. I propose this be closed.

**Comment by thc202** [comment]
Right. Closing as duplicate of #3807.
