### ISSUE TITLE
False Positive: Anti CSRF Tokens Scanner reporting high issues on search paths

### ISSUE THREAD

**Issue by claudijd** [zaproxy/zaproxy#3845]
I'm running ZAP via zap-full-scan.py in the dockerized strategy and noticed I'm getting false positives from the Anti CSRF Tokens Scanner on search paths.  In this context, it doesn't seem all that relevant to raise this issue.

URL: https://mysite/mypath/
Method: GET
Evidence: `<form action="/search/">`

What if we had some logic that looked at the form action and if it contains search we don't throw the finding?  I would think that would help cut down on the noise so we can more focus on areas where this would be more relevant.

**Comment by kingthorin** [comment]
You can define that using https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsOptionsRuleconfig

**Comment by psiinon** [comment]
Yeah, thats the recommended option.
You can also specify attribute names to ignore, allowing you to whitelist forms in the HTML. The rules are rules.csrf.ignore.attname and rules.csrf.ignore.attvalue, but they might be post 2.6.0.
We do this in AMO :)

**Comment by kingthorin** [comment]
@claudijd will one of those options work for you? Can we close this issue?

**Comment by claudijd** [comment]
@kingthorin yep, I think that will work.

**Comment by claudijd** [comment]
Thanks!
