### ISSUE TITLE
zap-full-scan.py does not observe URL seed scope

### ISSUE THREAD

**Issue by claudijd** [zaproxy/zaproxy#3847]
When performing a scan using zap-full-scan.py in a dockerized strategy, I attempted to seed a scan with additional path information, like so...

`sudo docker run -v $(pwd):/zap/wrk/:rw -u root -it owasp/zap2docker-weekly zap-full-scan.py -d -r reporta.html -t https://mysite/directory1/directory2/`

I guess my behavior expectation of such a scan is that it would behave differently than the following scan in that the first scan would restrict it's scope to just things found in directory1/directory2's immediate path.

`sudo docker run -v $(pwd):/zap/wrk/:rw -u root -it owasp/zap2docker-weekly zap-full-scan.py -d -r reportb.html -t https://mysite/`

I guess I'm just wondering if my expectations are incorrect or whether or not is a bug.

**Comment by thc202** [comment]
Yes, that's the expected behaviour, spider/scan the (whole) host:
https://github.com/zaproxy/zaproxy/blob/7dc372f6427c23a7f26beca88a283575ef351950/build/docker/zap-full-scan.py#L306-L308

**Comment by claudijd** [comment]
@thc202 thanks for the quick reply.  Two questions...

1.) How can I seed URL paths (ie. I want to make sure the spider hits /foo/bar and /foo/baz, which are not linked from the root)
2.) How can I exclude URL paths (ie. I know not to go to /deletemywebsite, but want to let zap-full-scan know that)

**Comment by psiinon** [comment]
We use the full path to start the scan with things like OpenAPI definitions - restricting the scan to just one url like that would clearly not be the right thing to do.
But I can imagine that someone starting a full scan with a target of https://www.example.com/app1 would expect it to only scan app1 and not app2 etc :/

However we do have a solution - invoke the scan with a context - this can specify all of the urls you want to hit and all of the ones you want to exclude.
Right now the easiest way to create a context file is via the ZAP GUI - you can export it to a file and then specify that file to the full scan script.

**Comment by claudijd** [comment]
@psiinon thanks!
