### ISSUE TITLE
ZAP API is giving consolidated Results where from UI it seems working fine

### ISSUE THREAD

**Issue by anamikabhadola** [zaproxy/zaproxy#3861]
Hi, 
We are trying to run ZAP local api from our c# code but we are not getting the expected the result.
Steps we are following in our code:-
1. First start the spider scan - http://127.0.0.1:2051/JSON/spider/action/scan/?url=https://www.facebook.com/

2. Verify whether the spider scan completed 100% or not. - http://127.0.0.1:2051/JSON/spider/view/status/?zapapiformat=JSON&formMethod=GET&scanId=6

3. Then start active scan -http://127.0.0.1:2051/JSON/ascan/action/scan/?
url=https://www.facebook.com/&amp;recurse=&amp;inScopeOnly=

4.Check whether the active scan has been completed 100% or not - http://127.0.0.1:2051/JSON/ascan/view/status/?zapapiformat=JSON&formMethod=GET&scanId=6

5. At last, verify the result - http://127.0.0.1:2051/OTHER/core/other/htmlreport

Observations:- Every time when we run our code we always get the old result or consolidated which was executed through the ZAP UI.

**Comment by thc202** [comment]
That's the expected behaviour, the `htmlreport` includes all alerts raised (at the moment it's not possible to generate the report just for one scan, #2920). If you don't want the old alerts you new to delete them prior starting the new scan (e.g. create a `newSession`, or `deleteAllAlerts`).

**Comment by anamikabhadola** [comment]
Hi,
Thanks for replying.
This time the session is new, I ran the fresh scan by using its API but still nit getting the expected result. 
Following are the steps:-
1. http://127.0.0.1:2051/JSON/spider/action/scan/?zapapiformat=JSON&formMethod=GET&url=http%3A%2F   %2Fgmail.com&maxChildren=&recurse=&contextName=&subtreeOnly=

2. http://127.0.0.1:2051/JSON/spider/view/status/?zapapiformat=JSON&formMethod=GET&scanId=0

3. http://127.0.0.1:2051/JSON/ascan/action/scan/?zapapiformat=JSON&formMethod=GET&url=http%3A%2F   %2Fgmail.com&recurse=&inScopeOnly=&scanPolicyName=&method=&postData=&contextId=

4. http://127.0.0.1:2051/JSON/ascan/view/status/?zapapiformat=JSON&formMethod=GET&scanId=0

5. http://127.0.0.1:2051/OTHER/core/other/htmlreport/?formMethod=GET

I do not know where do I miss the step.

I tried with CURL commands as well, but no success.

Please suggest.

**Comment by thc202** [comment]
Which steps are/were you doing in the UI?

**Comment by thc202** [comment]
Closing, feel free to open if you have more details about the issue.
