### ISSUE TITLE
Selenium - Start Chrome/Firefox in headless mode (for tools)

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#3866]
From discussion in IRC:
Change Selenium add-on to start Chrome/Firefox in headless mode (by default) when used for tools (AJAX Spider, DOM XSS). Since this is a very noticeable change warn/inform the user when that happens, also, add an option to still start them with GUI, as it's useful to debug/know more easily what the tools are doing. In daemon mode they will be started always in headless mode.

References:
https://chromium.googlesource.com/chromium/src/+/lkgr/headless/README.md
https://developer.mozilla.org/en-US/Firefox/Headless_mode

**Comment by thc202** [comment]
Chrome will not be changed to be headless by default, there's an issue (https://bugs.chromium.org/p/chromium/issues/detail?id=721739) that prevents ignoring cert issues (which is required to proxy through ZAP).

**Comment by rezen** [comment]
Looks like the proxy + cert issue has been resolved possibly in Chromium?

**Comment by thc202** [comment]
Yes, Zest library was already changed, still changing Selenium add-on (adding other changes).

**Comment by thc202** [comment]
I didn't add any warning in the end, the tools show/allow to choose which browser is started, headless is selected by default (the user can quickly change to non-headless).
