### ISSUE TITLE
类注释太少了

### ISSUE THREAD

**Issue by gybcloud** [zaproxy/zaproxy#3868]
能不能把类的注释加上，有利于理解代码。

**Comment by kingthorin** [comment]
Google translate, translation: 
> Can not add the annotation of the class, is conducive to understanding the code.

https://javadoc.io/doc/org.zaproxy/zap/2.6.0

**Comment by thc202** [comment]
Closing, not much more to do. If you have any code related question, please, let us know through the [Developer Group](https://groups.google.com/group/zaproxy-develop). Thank you.
