### ISSUE TITLE
Manage Add Ons UI Should Indicate Where Add On Files Can Be Downloaded From

### ISSUE THREAD

**Issue by davewichers** [zaproxy/zaproxy#3869]
Some people use ZAP in a disconnected environment. To help them understand where they can download Add On files from, please add some kind of description/explanation of 1) Where they can download them from, and 2) how they can then add/import them (Via the File-->Load Add On File  feature or whatever).

**Comment by psiinon** [comment]
OK to have this in the relevant help page, which is online here: https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsManageaddons ?

**Comment by kingthorin** [comment]
You can download them here:
https://github.com/zaproxy/zap-extensions/releases

<sub>Cross-ref: https://groups.google.com/forum/#!topic/zaproxy-users/QgkKwxujyho</sub>

**Comment by thc202** [comment]
Being handled in zaproxy/zap-core-help#136.
