### ISSUE TITLE
Tag Creator Processor for Fuzzer not adding tags

### ISSUE THREAD

**Issue by ScatteredThoughts** [zaproxy/zaproxy#3872]
Details here: https://groups.google.com/forum/?pli=1#!topic/zaproxy-users/R_9Go9O9lco

**Comment by kingthorin** [comment]
What version of ZAP?
What version of the fuzz addon?

**Comment by ScatteredThoughts** [comment]
I don't see any versions listed for Fuzzer or it's Message Processors, when I right click on a request and select Fuzz. I also don't see either one in the Manage Add-ons section.

**Comment by kingthorin** [comment]
If you hover over the addon name in the Manage Add-ons dialog a tooltip should appear that displays the version ... something like this:
![image](https://user-images.githubusercontent.com/7570458/30192736-3b1dd43e-9417-11e7-956d-bfea1bbb4c0a.png)

**Comment by kingthorin** [comment]
Just did some quick testing `[]` results where there is no match. Try dropping the `^` and `$` from your regex, or try a regex you're 100% sure of.

**Comment by ScatteredThoughts** [comment]
Ahh. Version 8 for AdvFuzzer. I had thought that might be something else since the name is slightly different from what you see in the menu. The regex anchor tags seem to be the problem; it works after taking them out. I thought I had tried it without those previously. Part of it may be the site; results are a little inconsistent unless I lower the thread count and increase the delay.

Thanks for the help! Sorry for the mistake on my part.

**Comment by kingthorin** [comment]
No problem, we've all been there. Thanks for letting us know.
