### ISSUE TITLE
Implement null byte injection ascan rule

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#3877]
See https://groups.google.com/d/msg/zaproxy-users/_KyG4zxzO9s/MLwworzdAQAJ for more details.
Also see http://zaproxy.blogspot.co.uk/2014/04/hacking-zap-4-active-scan-rules.html for details of how to create an active scan rule.

**Comment by kepuss** [comment]
Hi @psiinon 
I want to contribute to ZAP project. I'd like to begin with this issue.

**Comment by kingthorin** [comment]
Go for it! 👍 

We look forward to your PR.

**Comment by kepuss** [comment]
@kingthorin  thanks, I managed to run everything and write simple scan, however few questions raised:
1. What file should be checked? In vulnerability examples /etc/passwd can be found, which should work for all Linux distros. What about windows machines?
2. File path is dependent on the execution location, which means that we need to manipulate path with "../". What should I do (i.e. create attempt for each level : ../etc/passwd ../../etc/passwd ... ; for few leves)?
3. Such scan is not going to work if app has some anti path traversal mechanism(that removes ../). We could check file that are on the same level, but I have no idea if there is a way to pick them?

**Comment by kingthorin** [comment]
It looks like this would actually be just a new payload in a few of the existing scan rules.

http://projects.webappsec.org/w/page/13246949/Null%20Byte%20Injection provides some decent examples.

For example: There is already a path traversal scanner.

Another option would be to enhance Zaps input variants to have the option of appending a null byte to payloads... @psiinon @thc202 what do you think of that?

**Comment by kepuss** [comment]
@kingthorin 
1. I've seen the page and examples are based on passwd or the same level file (like "server.logs.txt" from last example) 
2. Ok, I thought it should be in separate scan. So I'm waiting for your decision

**Comment by thc202** [comment]
@kingthorin how would that work?

**Comment by kingthorin** [comment]
Similar to that script I'd been working on to inject payloads in param names. Only in this case a null byte would just be appended or prepended to the value when the messages are re-built.

**Comment by kingthorin** [comment]
I'm fine with it being additional payloads. We'll just have to decide which scan rules it should be added to.

I was just trying to come up with alternatives since it doesn't seem to require a new scan rule on its own (unless I've missed something?)

**Comment by thc202** [comment]
Right, I think changing existing scanners to accommodate this case is probably better. The variant might require more changes (e.g. not all scanners would be using it(?), report the proper injected payload...).

**Comment by kepuss** [comment]
@thc202 @kingthorin 
So let me summarize what should be done(correct me if wrong):
1. Look through existing scanners and find where null byte injection can be used as payload (on master/alpha/beta branches?)
2. (Example) So one of that scanners is TestPathTraversal class. It stores payloads in array WIN_LOCAL_FILE_TARGETS which gonna have additional payload with null byte.

**Comment by thc202** [comment]
Yes, that's my understanding.

**Comment by kingthorin** [comment]
Also might require changes to conform to the strength guidelines https://github.com/zaproxy/zap-extensions/wiki/AddOnsBeta

**Comment by kepuss** [comment]
@thc202 @kingthorin 
I looked through activescan rules in master,beta and alpha, and only ones below seems to be right rules to apply null byte:

master:
1. CommandInjectionPlugin:              (example "cat /etc/passwd\0" )
2. TestCrossSiteScriptV2:                  (example 	<[%00]script>alert("alert(1)")</script>)
3. TestExternalRedirect:                    (example  '"http://" + REDIRECT_SITE + "%00"')
4. TestPathTraversal:                        (example "/etc/passwd%00")
5. TestRemoteFileInclude:                 (example "www.google.com/%00")

**Comment by kingthorin** [comment]
@kepuss sorry I lost track of this thread, yes those seem logical.

**Comment by 3bhady** [comment]
@kingthorin is this issue still being tackled or should i go for it?

**Comment by kingthorin** [comment]
@kepuss are you working on this?

**Comment by preetkaran20** [comment]
Hi @kingthorin/ @thc202.  

I have started working on this issue. I am thinking to go through list of extensions like .jpeg,.jsp,.png etc and then combine with the patterns which are there in CommandInjectionPlugin or other plugins and run the scanner.
eg -
/etc/passwd%00.jpeg etc so that incase there are some checks in code on extension can be passed and then same scanner code will run and the way it checks for CommandInjection will execute exactly.
eg -
``` 
String fn = request.getParameter("fn");
if (fn.endsWith(".db"))
{
File f = new File(fn);
//read the contents of “f” file
…
}

```
I am for now just targeting CommandInjectionPlugin. Please let me know if you have some other idea to approach null byte injections.

Also say we are trying to check for Security vulnerability in a Java Server and by banner grabing we came to know that Java Server and version, as we know this vulnerability is not there above ``` Java 7 update40 ```

Can we skip for those servers or we should blindly try as this vulnerability can occur in future versions due to some bug ?

thanks,
Karan

**Comment by preetkaran20** [comment]
@kingthorin please review the approach mentioned above.

**Comment by preetkaran20** [comment]
@kingthorin @thc202  please review the above approach.

**Comment by kingthorin** [comment]
I don't really follow your concept. Adding file extensions after a null which is meant to break/stop parsers probably won't accomplish anything. Also trying a bunch of file extensions will just exponentially increase the number of requests to be made and likely break the strength guidelines. I'd suggest reading through the whole history of the issue (there's lots of value in the existing discussion(s)). Then perhaps pursue the concept put forth by @kepuss who seems to have abandon working on this.

In the case where those suggestions are to end in the null value the original param value should probably be included after the null.

**Comment by preetkaran20** [comment]
Hi @kingthorin ,

I had gone through the comments but wrongly understood.I was thinking only from perspective of LFI/RFI's or Path traversals only.

Will go through all the scan's as mentioned by @kepuss.

thanks,
Karan

**Comment by kingthorin** [comment]
Ok that's fair. There's also nothing that says this has to be done in a single contribution. If you have some ideas on modifying just scan rule to accommodate this then suggest it or throw together a PR and submit it.

Also the mentioned strength guidelines can be found here:
https://github.com/zaproxy/zap-extensions/wiki/AddOnsBeta

**Comment by preetkaran20** [comment]
Hi @kingthorin,

I am doing the changes but i have doubt regarding testing scan rules on various platforms (windows/mac/linux). How do you guys generally test ? is there any document regarding the same.

thanks,
Karan

**Comment by preetkaran20** [comment]
Hi @kingthorin,
I have raised following pull request :- https://github.com/zaproxy/zap-extensions/pull/2156 with Initial Commit by adding null byte payloads for Command Injection.

I am not sure about testing of payloads so i did some manual testing by running the plugin against DVWA application. Please review and let me know, how can we test it efficiently.

thanks,
Karan

**Comment by kingthorin** [comment]
@preetkaran20 sorry for my delay in getting back to you, just been a lot to juggle in the last few days.

For testing there are junit UnitTests, you can add to them: https://github.com/zaproxy/zap-extensions/blob/master/addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/CommandInjectionPluginUnitTest.java

Also coming up with either your own local tests with xampp/lamp or whatever OpenSource vuln app.  (I think you mentioned testing against DVWA which is cool if those vulns require the use of null byte payloads.)

As for the number of payloads, I'm ok with the scan rules only trying to NULL byte patterns on Insane strength.

**Comment by preetkaran20** [comment]
@kingthorin Thanks for the reply. I have done the changes as you suggested.

**Comment by preetkaran20** [comment]
Added payloads with LFI/RFI and Command Injection. PR :- https://github.com/zaproxy/zap-extensions/pull/2156/commits

**Comment by preetkaran20** [comment]
@kingthorin , @thc202 please review https://github.com/zaproxy/zap-extensions/pull/2156 and let me know if there are some concerns.

thanks,
Karan

**Comment by preetkaran20** [comment]
oh ok. I thought there is some mistake in PR.

thanks for the reply.

**Comment by preetkaran20** [comment]
Hi @kingthorin and @thc202 ,

I have also added Null Byte injection to Cross Site Scripting Active scan.
Pull Request :- https://github.com/zaproxy/zap-extensions/pull/2156
thanks,
karan

**Comment by preetkaran20** [comment]
@thc202  i think this can also be included in ZAP 2.9.0 . can you please review https://github.com/zaproxy/zap-extensions/pull/2156

**Comment by thc202** [comment]
We don't usually add add-on issues to milestones, they can be released anytime.

**Comment by preetkaran20** [comment]
oh ok.

**Comment by kingthorin** [comment]
Are we good with closing this following the merge of: https://github.com/zaproxy/zap-extensions/pull/2156

**Comment by thc202** [comment]
Yes, closing.
