### ISSUE TITLE
Auto Set Active Imported Certificate

### ISSUE THREAD

**Issue by davewichers** [zaproxy/zaproxy#3879]
I had previously requested (in issue #3163):

In ZAP Options, when you import a new PKCS#12 cert (and probably works the same for the other types as well), after successful import, it takes you back to the KeyStore tab (which is good). But then to make that the Active cert the user has to:

a) Click on the cert in the left column,
b) Click on the username in the right column,
c) Click on the Set Active button

Steps a) and b) are now automatic, but the user still has to do step c).

Is there any reason why we don't automatically make the imported certificate active? If not, can we make step c) above happen automatically too?

**Comment by kingthorin** [comment]
To be clear I'm not against this idea, I've only worked with client certs a little bit and even then usually single user single cert.

If you had multiple certs I guess there's a scenario in which you'd import one (because you received it or whatever), but not immediately want to make it "active" for an existing user user.... I suppose it's fair to assume that if you're importing it you'd want to use it. But, it is an assumption. I can also see that a user might import and cert and then realize they had the wrong user selected and have to redo both.... I dunno... food for thought.

**Comment by davewichers** [comment]
ZAP doesn't remember certs between uses of ZAP, so you have to import the
cert EVERY time you use it (if you need one). At a minimum, we should
automatically set active the cert if its the 1st one imported. But I really
think, by default, we should set the latest one imported as active.  Either
of these would be an improvement over what happens now and I think would
cover 99+% of the usage of certs. (The 1st (and usually only) cert
imported).

**Comment by kingthorin** [comment]
I have no ability to test with pkcs#11 to make similar mods, however I was able to test with pkcs#12. So I propose we do something like the following. Basically, when a cert is added if it's the only cert then it is also activated. 

I was torn as to activating the latest cert, but it's definitely reasonable to activate the "only" cert. I can easily see instances where a user might import more than one cert at a time or import secondary/tertiary certs while still using the original one (with plans to use the others in the future). However, I wasn't able to convince myself of making the latest one the active one.... either way it's better than it was and saves a click or two in getting going which is nice.

```diff
diff --git a/src/org/parosproxy/paros/extension/option/OptionsCertificatePanel.java b/src/org/parosproxy/paros/extension/option/OptionsCertificatePanel.java
index 9834c37..38c7108 100644
--- a/src/org/parosproxy/paros/extension/option/OptionsCertificatePanel.java
+++ b/src/org/parosproxy/paros/extension/option/OptionsCertificatePanel.java
@@ -794,6 +794,10 @@
 
 		certificatejTabbedPane.setSelectedIndex(0);
 		selectFirstAliasOfKeyStore(ksIndex);
+		
+		if (keyStoreListModel.size() == 1) {
+			setActiveAction();
+		}
 
 		fileTextField.setText("");
 		pkcs12PasswordField.setText("");
@@ -849,6 +853,10 @@
 	}
 	
 	private void setActiveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setActiveButtonActionPerformed
+		setActiveAction();
+	}//GEN-LAST:event_setActiveButtonActionPerformed
+	
+	private void setActiveAction() {
 		int ks = keyStoreList.getSelectedIndex();
 		int alias = aliasTable.getSelectedRow();
 		if (ks > -1 && alias>-1) {
@@ -887,10 +895,7 @@
 			}
 			certificateTextField.setText(contextManager.getDefaultKey());
 		}
-
-
-
-	}//GEN-LAST:event_setActiveButtonActionPerformed
+	}
 
 	public String getPassword() {
 		JPasswordField askPasswordField = new JPasswordField();

```

**Comment by thc202** [comment]
Sounds good to me. I can test the PKCS#11 part.

**Comment by kingthorin** [comment]
Is the PKCS#11 functionality the same, check for a single entry and set it active, around here:
https://github.com/zaproxy/zaproxy/blob/681345bdced2e20dae869426ed22e89748292e94/src/org/parosproxy/paros/extension/option/OptionsCertificatePanel.java#L639-L643

It "looks" the same (code wise), but I don't have a way to go through the process and find out.

**Comment by thc202** [comment]
OK, will check that.
