### ISSUE TITLE
ZAPping the OWASP Top 10 2017

### ISSUE THREAD

**Issue by artiommocrenco** [zaproxy/zaproxy#3883]
I think it would be quite useful to upgrade this table https://www.owasp.org/index.php/ZAPpingTheTop10

And include the link to the upgraded version to the zaproxy documentation.

**Comment by amocrenco** [comment]
#1882 1879

**Comment by kingthorin** [comment]
Depends on publication of the Top 10 2017 edition...

In it's current form the only updates to the table would be to:
* Drop Diviner and Vehicle since they haven't been maintained. 
* Update the Access Control reference for A7.

**Comment by kingthorin** [comment]
Updates outlined above have been completed.

Leaving issue open to be tackled when the 2017 T10 is published.

**Comment by psiinon** [comment]
@kingthorin - the Top 10 has been published now, so I think its ok to publish this :)
Is it worth copying the current one to something like https://www.owasp.org/index.php/ZAPpingTheTop10-2013 ?

**Comment by kingthorin** [comment]
That’s actually where I’d done the previous mods. I guess now that 2017 is out I can build a new page and start linking it.

**Comment by kingthorin** [comment]
Second glance: yes :)

**Comment by omerlh** [comment]
A8 (insecure deserialization) might be challenging, I think there is no active scan for that - but this [tool](https://github.com/pwntester/ysoserial.net) could be a good start for that

**Comment by kingthorin** [comment]
Thanks @omerlh, are you volunteering to implement/integrate that? :)

**Comment by omerlh** [comment]
Totally on my backlog, but cannot guarantee when I'll get to it :) The main challenge IMO is how we can integrate this tool as is - but I'll open a different issue for that. Should I open it on this repo?

**Comment by kingthorin** [comment]
Cool...I was kind of joking. 

Sure you can open the issue here, though there may already be one for a deserialization scanner... 

There’s probably native java projects out there that might be easier to leverage or integrate.

**Comment by omerlh** [comment]
Well, I actually do have it on my board - as I want to add this to our DAST solution :) This project is mainly for C#, which is more relevant for us...

**Comment by kingthorin** [comment]
I've done an initial edit/transition for this content. A8 and A10 are currently listed as TBD.

https://www.owasp.org/index.php/ZAPpingTheTop10

**Comment by kingthorin** [comment]
I've added a note about potential usage for A10 and the outstanding items related to A8 have been documented.

Closing.
