### ISSUE TITLE
Upgrade JxBrowser

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#3893]
https://www.teamdev.com/jxbrowser

Release notes: https://jxbrowser.support.teamdev.com/support/discussions/topics/9000036612
One interesting new feature - ability to modify proxy settings at runtime.
Also start up time on Windows reduced.

**Comment by thc202** [comment]
JxBrowser 6.16 - https://jxbrowser.support.teamdev.com/support/discussions/topics/9000037169

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#1145.
