### ISSUE TITLE
Cannot Access IPv6 site using ZAP proxy. 

### ISSUE THREAD

**Issue by shree999** [zaproxy/zaproxy#3896]
Hello Everyone,

I recently came across an issue and I am stuck there. I was trying to perform some test on company website with its IPv6 address but was not able to do so. Can someone please help me on this. I did configure proxy settings and also tried the same on JxBrowser. 

Thank you.

**Comment by thc202** [comment]
This is a bug, at the moment ZAP is not able to access IPv6 addresses. Merging into #3705.

**Comment by ReK2Fernandez** [comment]
having same issue. i'm in the middle of a pen test and can't use ipv6 on zap :-1:
