### ISSUE TITLE
Failed to attack url: recived a 403 responce code

### ISSUE THREAD

**Issue by trollmad3** [zaproxy/zaproxy#3900]
Im trying to test out my friends site (he gave me permission) and its saying 403. 
![javaw_2017-09-23_13-47-13](https://user-images.githubusercontent.com/7843719/30776574-0574119e-a066-11e7-9f9d-9c1b52f821cc.png)

If you know how to fix this please tell me. Thanks!

**Comment by kingthorin** [comment]
Provide a starting URL that doesn't result in an HTTP 403

**Comment by psiinon** [comment]
We have a FAQ for this: https://github.com/zaproxy/zaproxy/wiki/FAQquickScanFailed
