### ISSUE TITLE
https certificate in ajax spider (FF, Selenium, Profiles)

### ISSUE THREAD

**Issue by robert-hoffmann** [zaproxy/zaproxy#3908]
When using normal spider or proxying through zap, the certificate one installs in firefox works just fine ..even on successive launches.

However when clicking browser launch, or going through ajax spider, the certificate dissapears, so i suppose ssl is not really working anymore in those scenarios..

The problem seems to be that FF in the second scenario is systematically launched with a **randomly** generated profile `firefox.exe -marionette -profile C:\Users\<user>\AppData\Local\Temp\7\rust_mozprofile.6sLbD7FGb76j`

Thus any settings that where made prior to launching the spider are lost.

Wouldn't it be simple to just launch FF with the default profile. Like this one can configure everything correctly (certificates, proxy, etc, etc) and when launching the spider, it will have a perfectly configured environment. ????

**Comment by thc202** [comment]
The browsers launched for AJAX Spider are automatically configured to proxy through ZAP (using a different proxy per scan) and to accept ZAP's cert (by ignoring SSL/TLS cert issues), so SSL/TLS should still be used between ZAP and the browser. Are you getting a different behaviour?
(Same happens for launched browsers but proxying through ZAP's Local Proxy.)

**Comment by robert-hoffmann** [comment]
Requests/Responses are readable from inside zap. I  just noticed that when i configure a certificate in FF and manually proxy through ZAP i get the green icon, and when the ajax spider is launched i get the insecure connection icon.

**Comment by psiinon** [comment]
Unfortunately browsers dont seem to provide an easy way to automatically import root CA certificates. I guess this could be seen as a security issue maybe?
When we launch browsers via the Ajax Spider (and browser launch) the browsers are started with new (clean) profiles. We cant import the ZAP cert, but we can (and do) configure the browsers to ignore any cert warnings.
So the browsers should work fine, but will show an insecure cert warning.
If we launch Firefox with the default profile then you'll have a problem if you already have a browser with that profile open - Firefox will complain and prompt you to close the other browser or choose a different profile. Thats a _real_ pain in my experience :)
@robert-hoffmann is this actually causing a problem for you?

**Comment by robert-hoffmann** [comment]
No doesn't seem to pose a problem.

I'm only working with sites using https, and  thought the browser needs the cert to be able to correctly handle SSL requests ?

**Comment by psiinon** [comment]
No, when we launch browsers (via selenium) we configure them to ignore any certificate issues :)
Ok to close this issue now?

**Comment by robert-hoffmann** [comment]
Ok thanks for the reassurance
