### ISSUE TITLE
False Positive: Backup Files Triggering on 403 responses

### ISSUE THREAD

**Issue by claudijd** [zaproxy/zaproxy#3911]
I was doing a number of scans and one of the really common false positives was the backup file detector logic.  It seems well-placed, as backup files can be a really good way to find sensitive information disclosure, but I would think that having every single example file returning a backup file hit would be a good indicator that it's a false positive that we can key on in the check.

Here's an example file, where ZAP is saying this is a backup file, when it's just a 403 response for any unknown file.

https://gameon.allizom.org/sitemap.old

I would also think that in order to throw this as an alert that you'd actually need to get something like a 200 response, rather than a 403.  Maybe that helps give enough information to help improve the check.

Please let me know if you have any other questions.

**Comment by psiinon** [comment]
It looks like the current code only handled 404s not 403s :/
https://github.com/zaproxy/zap-extensions/blob/beta/src/org/zaproxy/zap/extension/ascanrulesBeta/BackupFileDisclosure.java#L338
Anyone object to just changing the code to treat 403's in exactly the same way?
@thc202 @kingthorin

**Comment by kingthorin** [comment]
Could do something like: https://github.com/zaproxy/zap-extensions/blob/ba87c70bfa83b24d01999d8e5b6eb98dcab19441/src/org/zaproxy/zap/extension/pscanrules/CacheControlScanner.java#L67-L68

What are everyone's thoughts on redirects?

**Comment by psiinon** [comment]
I'm good with that.
I'm also good with handling redirects in the same way - I'd have thought they would be much more likely to be redirects to a standard error page rather than real backup files.

**Comment by thc202** [comment]
Sounds good to me.

**Comment by kingthorin** [comment]
I've been thinking about this more over the weekend. Instead of blanket excluding classes of response code, would we be better off (accuracy wise) just ensuring the new response code matches the original response code?

**Comment by thc202** [comment]
For both cases or just when not a 404 (`gives404s = false`)?

**Comment by kingthorin** [comment]
Good question, I hadn't looked at the code that specifically. But yes I guess I mean when `gives404s = false`. If the app/site did actually return 404s then ignoring client error responses (400 series) would invalidate the result. So if the app/site doesn't use 404s then instead of excluding all redirects, client errors, and server errors wouldn't it be better that the response of the test matches the original (assumed good) response? Is that too much of an assumption to start with?

**Comment by thc202** [comment]
Right, I assumed the fix would be to treat other response codes as `gives404s = false` not exclude them. Said that, I think so, we should compare against the know good response code when dealing with the non-404s.

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#1087.
