### ISSUE TITLE
VariantDirectWebRemotingQuery might hang in infinite loop

### ISSUE THREAD

**Issue by vmolotkov** [zaproxy/zaproxy#3912]
[diff.txt](https://github.com/zaproxy/zaproxy/files/1340287/diff.txt)
There is obvious bug in method 

`org.parosproxy.paros.core.scanner.VariantDirectWebRemotingQuery.parseContent(String).`

The following two conditions, if true, cause infinite loop:
```
...
           if ( patternIgnoreArray.matcher(paramDetails[1]).matches()) continue; //to the next iteration
           if ( patternIgnoreObject.matcher(paramDetails[1]).matches()) continue; //to the next iteration
...
```
Active scanner threads get stuck and scan process freezes eventually.
Proposed fix in the attachment.

**Comment by thc202** [comment]
Would you mind opening a pull request instead? [1]

[1] https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by vmolotkov** [comment]
Done

**Comment by thc202** [comment]
Thanks!

**Comment by kingthorin** [comment]
Fixed in https://github.com/zaproxy/zaproxy/pull/3913
