### ISSUE TITLE
Show only URLS in scope - Not working for Sites in macOS

### ISSUE THREAD

**Issue by ScatteredThoughts** [zaproxy/zaproxy#3917]
It appears that this issue was brought up before - #3675, and has resurfaced. 

I'm running Zap 2.6.0  primarily on Windows 10 but I the issue also happens with Kali Linux.

![zap_showurlsscope](https://user-images.githubusercontent.com/22101253/31064748-291f8d46-a6f4-11e7-83e9-637e905056ce.png)

**Comment by thc202** [comment]
The fix for issue #3675 was not yet included in a main release. Could you try with weekly release? [1]


[1] https://github.com/zaproxy/zaproxy/wiki/Downloads#zap-weekly

**Comment by ScatteredThoughts** [comment]
The weekly release seems fine on Windows. I did notice that I when I tried it on my Mac for work, the graphics were displayed a bit oddly.

![zap_weekly_mac](https://user-images.githubusercontent.com/22101253/31105035-d45cf24c-a795-11e7-8820-27cf090e9b53.png)

**Comment by thc202** [comment]
Does that happen always? Have you tried the context menu item "Refresh Sites Tree" when that happens?

**Comment by ScatteredThoughts** [comment]
Tested again. Same issue several times in a row. Using "Refresh Sites Tree" does not correct the view.

**Comment by thc202** [comment]
Which versions of Java and macOS are you using?

Could you add `-Dswing.defaultlaf=javax.swing.plaf.nimbus.NimbusLookAndFeel` to the JVM [1] options and try again? Just to check if the system's default L&F is causing that.
(You might need to start ZAP with `zap.sh` script.)

[1] https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsOptionsJvm

**Comment by ScatteredThoughts** [comment]
$ java -version
java version "1.6.0_36"
OpenJDK Runtime Environment (IcedTea6 1.13.8) (rhel-1.13.8.1.el5_11-x86_64)
OpenJDK 64-Bit Server VM (build 23.25-b01, mixed mode)

OSX El Capitan - version 10.11.6

Using the JVM options, the view looks as expected.

**Comment by thc202** [comment]
Thanks for the information!

I don't have access to a macOS to try a possible fix, would you be available to test/verify it?

**Comment by ScatteredThoughts** [comment]
Sure, I can do that.
