### ISSUE TITLE
working with context through api script and UI

### ISSUE THREAD

**Issue by thinksabin** [zaproxy/zaproxy#3925]
hi,
I having trouble with using the zap 2.4 python api. I did checked into following post:
https://github.com/zaproxy/zaproxy/issues/3608 

The script mentioned does work and did help alot, as mention it got issue with authentication.
For confirmation i checked into zap ui and context.
Now checking back into the zap ui and working with the context and setting up user and force user, login url, login post request, logged in and out pattern, and other information and later running the spider it wont actually crawl every links into the web application as the login user should do. The spider just end up crawling the links and javascripts within the scope of the login page. I thought it would login as user specified and then do ta crawling in the web application as the authenticated user.

I'm wondering if it should be working as i supposed or am i totally getting wrong here.
Im using zap 2.6.0 in macOS sierra 10.12.6

thanks

**Comment by kingthorin** [comment]
Is the internal content based on classic links or AJAX functionality?

**Comment by thinksabin** [comment]
its not classical web application login style. i believe its more of the ajax. The login request looks like following:

```
POST /pluggables/Authentication/Authentication/login HTTP/1.1
Host: 192.168.4.145
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:55.0) Gecko/20100101 Firefox/55.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Referer: https://192.168.4.145/
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
X-Requested-With: XMLHttpRequest
Content-Length: 130
Cookie: value-here
Connection: close

requestType=formsubmit&id=&username=admin&password=password&url_hash=&CSRFToken=45f0c1d9-2069-4874-ae83-217161412785-1507133950.13

```
and response:

```
HTTP/1.1 200 OK
Server: nginx/1.10.1
Date: Wed, 04 Oct 2017 16:35:35 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 61
Connection: close
Set-Cookie: session= value here

{"redirect":"/#","pageload":true,"message":"","success":true}

```

regarding CSRF token, you can put any value, you just need correct username and password.

I did add this request into the context setting and specified the parameters for username and password.

**Comment by kingthorin** [comment]
Addressed by https://github.com/zaproxy/zaproxy/pull/4682 ?

**Comment by kingthorin** [comment]
@thinksabin any information in the log?
https://github.com/zaproxy/zaproxy/wiki/FAQlogging

Also we have a FAQ that includes some trouble shooting info for auth setup:
https://github.com/zaproxy/zaproxy/wiki/FAQformauth

**Comment by kingthorin** [comment]
@thinksabin any further feedback on this or should the issue just be closed?

**Comment by thinksabin** [comment]
@kingthorin you can close the issue, in case of similar issue in zap 2.8 + i will let you guys know. Thanks.

**Comment by kingthorin** [comment]
Thanks
