### ISSUE TITLE
How can i change recorded service url in ZAP?

### ISSUE THREAD

**Issue by PraneshAnandhan** [zaproxy/zaproxy#3926]
Here I'm testing my application is dev environment and later I need to run the same test in the staging environment. so how can I modify the dev URL in ZAP?

**Comment by kingthorin** [comment]
You can either edit your hosts file, or use the Replacer addon; which is available from the MarketPlace: 
![zap-screenshot-browse-addons 1](https://user-images.githubusercontent.com/7570458/31174444-8abfa586-a8d9-11e7-9600-9848d2aca137.png)

**Comment by kingthorin** [comment]
Please don't ask questions as issues - the ZAP User Group https://groups.google.com/group/zaproxy-users and Developer Group https://groups.google.com/group/zaproxy-develop are much better places for questions.
