### ISSUE TITLE
zap-full-scan on docker tries to reach out to external network

### ISSUE THREAD

**Issue by mpeters** [zaproxy/zaproxy#3927]
When running zap-full-scan.py in the owasp/zap2docker-weekly image it fails when there is no access to the outside internet. It's trying to reach out to the external network to check the client API version number (https://pypi.python.org/pypi/python-owasp-zap-v2.4/json). I'm using a self-contained docker container with ZAP and the Python API already installed and they should be matching versions. Why does it need to verify this? And why does it need to try to hit an external URL to do it?

I'm running this inside of an isolated network that can't reach outside and the system under test is another docker container on the same host, so it should not be required to enable external network access to use it.

**Comment by thc202** [comment]
Could you provide the error/stacktrace when it fails? (The image should still work even if the check fails.)

The scripts are not always executed from the Docker image so the version might not always be the latest (#3347). But that's a good point we could skip the check if it's already in the Docker image.

**Comment by mpeters** [comment]
When there is no external network it doesn't have an error/stacktrace. It just hangs indefinitely. urllib.urlopen says "if not specified, the global default timeout setting will be used", which is misleading because apparently the default timeout is "no timeout" (see https://stackoverflow.com/questions/29649173/what-is-the-global-default-timeout).

So there are probably 2 changes needed: 1st add a timeout, say maybe 10 seconds (see my change). The 2nd would be to not run while under docker. I'll submit that as another change.

**Comment by thc202** [comment]
Thanks!

**Comment by thc202** [comment]
This is being addressed in #3928.
