### ISSUE TITLE
ServletParameterPollutionScanner: Outdated Reference on java.net

### ISSUE THREAD

**Issue by MichaelGissingNC** [zaproxy/zaproxy#3937]
The reference given for ServletParameterPollutionScanner is not valid any more, it links to java.net which is down.

`pscanbeta.servletparameterpollutionscanner.refs=http://java.net/attachments/lists/servlet-spec/jsr340-experts/2012-06/15/OnParameterPollutionAttacks.pdf`

This link is in all properties files. I would create a PR with an updated URL, but I can't find this PDF.

Can somebody please provide the PDF and update the link?

**Comment by thc202** [comment]
The file is now at:
http://download.oracle.com/javaee-archive/servlet-spec.java.net/jsr340-experts/att-0317/OnParameterPollutionAttacks.pdf

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#1073.
