### ISSUE TITLE
Default font in script console is non-monospaced on OSX

### ISSUE THREAD

**Issue by juhakivekas** [zaproxy/zaproxy#3939]
When no custom font selection is made, the Script tab has a non-monospace font. The issue is present in D-2017-09-11, but not D-2017-09-04

Possibly the reason: https://github.com/zaproxy/zap-extensions/pull/1037

**Comment by thc202** [comment]
Thanks for raising the issue.

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#1074.

**Comment by thc202** [comment]
@juhakivekas would you mind trying the fix?

**Comment by juhakivekas** [comment]
forgot to test this, works fine now

**Comment by thc202** [comment]
Thanks!

**Comment by juhakivekas** [comment]
This is back for some reason since 2018-02-19.
Java 1.8.0_152
OSX 10.13.3
ZAP weekly 2018-02-19

**Comment by juhakivekas** [comment]
not back after all :)

**Comment by thc202** [comment]
Cool, thanks for letting us know :)
