### ISSUE TITLE
Context Dropdown is empty when Active Scan panel is opened from tab button

### ISSUE THREAD

**Issue by selcukbeyhan** [zaproxy/zaproxy#3956]
There is a possibility to open the Active Scan Tab at the bottom.

When the active scan dialog is opened, the list of Contexts and Users is empty.
I suspect, this is because of these code in the class 
'public class CustomScanDialog extends StandardFieldsDialog {'
this.addComboField(0, FIELD_CONTEXT, new String[]{}, "");
this.addComboField(0, FIELD_USER, new String[]{}, "");

Basically, these lists are always empty.

Please have a look, thanks.
Here is the screenshot:
<img width="707" alt="screen shot 2017-10-16 at 17 31 38" src="https://user-images.githubusercontent.com/25543917/31620601-ef28b928-b297-11e7-9b70-a7006b8f9c7f.png">

**Comment by selcukbeyhan** [comment]
False Negative:
Found out that you have to select a target first.

**Comment by psiinon** [comment]
Yeah, we can only work out which contexts are available after you select the target.
If you open the dialog via the right click 'Attack..' menu then it should be set up correctly :)
