### ISSUE TITLE
ZAP skips URL deliberately ?

### ISSUE THREAD

**Issue by ParidaPunyasloka** [zaproxy/zaproxy#3957]
Hello All,

I have been working on ZAP scanner via the Standalone tool and also via the API. So, post the spider scan when I checked the no. of URLs scanned there are few URLs that are skipped. Initially, I had provided regex to skip certain URLs (which doesn't include the URLs that I found ZAP had skipped). I removed the regex and train plain spider scan and the results were same.

For eg. If I am scanning **http://xyz**

ZAP manages to scan - 

> http://xyz/aaa/abc
> http://xyz/aaa/def

but skips 

> http://xyz/aaa/ghi

However, If I provide **http://xyz/aaa/ghi** as an input to scan, It is included in the results. This was observed both in ZAP UI and via API. Do ZAP deliberately skips certain URLs? Is this is a bug or am I doing something wrong with the configuration? 

Thanks

**Comment by thc202** [comment]
Ref: https://groups.google.com/d/topic/zaproxy-users/tLdYNCcgjb8/discussion

**Comment by kingthorin** [comment]
Can you provide the actual html content where the links should be found?

**Comment by kingthorin** [comment]
@ParidaPunyasloka any update?

**Comment by thc202** [comment]
The thread in users group has new information. I guess this requires AJAX Spider?

**Comment by kingthorin** [comment]
Closing due to lack of feedback.
