### ISSUE TITLE
Properly generate cert for ZAP API and Callback when accessed with IP address

### ISSUE THREAD

**Issue by denniskniep** [zaproxy/zaproxy#3959]
When I use https within the API or Callback Url I get an error:

Firefox: Secure Connection Failed (SSL_ERROR_INTERNAL_ERROR_ALERT)
Chrome: This site can’t provide a secure connection (ERR_SSL_PROTOCOL_ERROR)

**Comment by thc202** [comment]
With 2.6.0 (or dev/weekly)? While proxying or accessing directly? Java version?

**Comment by denniskniep** [comment]
Currently working with a dev build. I am accessing the Url without  proxying. (If I am proxying there is no problem with the API).  I think Callback is never through proxy right? 
My Java Version is 1.8

**Comment by thc202** [comment]
Which revision/commit did you use to build? If it's working while proxying it might be a problem with SNI. (Yeah, for the callback it does not need to proxy just wanted to know if it was working for the API.)

No errors in the log when that happens?

**Comment by denniskniep** [comment]
I tried it with the latest commit 8017bc48ea0b5ba5278ca1a2a871d9ded3a13028

The Log output was:
`[ZAP-ProxyThread-34] WARN  SSLConnector - No domain extracted from SSL/TLS handshake session.`

**Comment by thc202** [comment]
Yeah, that's a problem with SNI. Which version of Firefox are you using? And what's the "update" Java version?

**Comment by denniskniep** [comment]
Firefox 56 
Java 1.8.0_131

**Comment by denniskniep** [comment]
The `ExtendedSSLSession` contains no `SNIServerName`
I accessed the API and the CallbackEndpoint with an Ip-Address, not with an DNS hostname.

The ["Server Name Indication"](https://de.wikipedia.org/wiki/Server_Name_Indication) is defined in the  [RFC6066](https://tools.ietf.org/html/rfc6066#page-6).

According to the RFC there are no Ip-Addresses allowed:

> Currently, the only server names supported are DNS hostnames;
> Literal IPv4 and IPv6 addresses are not permitted in "HostName".

Maybe a workaround is to issue the certificate with all in Zap used Ip-Addresses and HostNames into the SubjectAlternativeName.
https://en.wikipedia.org/wiki/Subject_Alternative_Name

**Comment by thc202** [comment]
Right, I assumed you were using the hostname not the IP address.
