### ISSUE TITLE
False Positive Mixed Content Error 

### ISSUE THREAD

**Issue by hypnossl** [zaproxy/zaproxy#3968]
I am receiving the following mixed content error 

`Mixed Content: The page at 'https://www.tryhypnosisnow.com/' was loaded over HTTPS, but requested an insecure image 'http://tryhypnosisnow.com/images/prbox.png'. This content should also be served over HTTPS.`

But I have checked the stylesheet and you see the code below includes https

`background: url("https://tryhypnosisnow.com/images/prbox.png") no-repeat scroll center top transparent;`

I cleared my caches but the error keeps coming up.

**Comment by psiinon** [comment]
Can you see a request for http://tryhypnosisnow.com/images/prbox.png in the sites tree?
Its also worth searching for that string in the search tab.
FYI I've proxied my browser through ZAP and opened https://www.tryhypnosisnow.com/ and I dont see that alert.

**Comment by thc202** [comment]
@hypnossl with which version of ZAP and Passive scanner rules add-on?

**Comment by hypnossl** [comment]
Sucuri cleared the firewall cache and the error is no longer there. Thank you for your help.

**Comment by kingthorin** [comment]
Thanks for letting us know.
