### ISSUE TITLE
macOS installer issues

### ISSUE THREAD

**Issue by omerlh** [zaproxy/zaproxy#3976]
Today I've used the auto-update feature to update Zap from 2.5.0 to 2.6.0. The update completed, but I noticed that I have multiple instances of Zap in my Applications folder:
```
 ls -la /Applications/ | grep ZAP
drwxr-xr-x   3 <>    <>    102 Jun  3  2016 OWASP ZAP.app
drwxr-xr-x   5 root      admin                  170 Oct 23 10:13 ZAP 2.6.0.app
```
I think I installed the previous version using brew, so that might be the issue.

Update: After using brew to update, the old version deleted and only ZAP 2.6.0 exists.

**Comment by thc202** [comment]
Updated the issue to be generic, the installer has other issues:
 - Invoked Applications does not work (https://github.com/zaproxy/zaproxy/issues/3960);
 - Unable to launch browsers (also reported in mailing list);

**Comment by thc202** [comment]
For reference, there's a discussion in the mailing list about providing (or not) the macOS installer:
https://groups.google.com/d/topic/zaproxy-users/0-mekZfxuEM/discussion

**Comment by thc202** [comment]
Actually this is not about the installer but the update from within ZAP? @omerlh could you confirm that?

**Comment by kingthorin** [comment]
@omerlh are you able to answer @thc202's question?

**Comment by thc202** [comment]
We no longer provide a macOS installer, just the DMG.

**Comment by thc202** [comment]
For the record, there was no feedback in the mailing list and in Twitter poll there was a preference for the DMG.
