### ISSUE TITLE
XSS False Positive: Reflected XSS in JSON Response with/Content-Type: application/json

### ISSUE THREAD

**Issue by davewichers** [zaproxy/zaproxy#3978]
ZAP is reporting XSS vulns when the injected payload is returned in a JSON response value that the attacker can't break out of. i.e., the payload remains JSON in the data value of a JSON name/value pair.  AND the Content-Type is application/json.

This situation isn't directly an XSS Vulnerability. It "MIGHT" be reasonable to report this as an XSS Weaknesses, or some such thing, because the JavaScript receiving this JSON data value MIGHT screw up and use an unsafe DOM update method with this data (like .setInnerHtml(DATA)), and end up with what I call a 'client-side' XSS vulnerability. 

But the responsive itself isn't directly vulnerable to XSS. As such, I'd suggest either:
1) Not reporting these, or
2) Reporting these as XSS 'Weaknesses' and explain how they 'could' lead to an XSS vulnerability.

In my experience most of these are false positives because the developers use safe JavaScript when processing JSON response data. They don't ALWAYS use safe JavaScript. But they 'usually' do.

**Comment by juhakivekas** [comment]
I agree with @davewichers, this should not rise an alert as it might lead to unnecessary fixes. In general I think the recommendation for output encoding is to do it as late as possible, and that would in this case be in the client-side JS. A note about possible XSS could be good, but as such these cases probably don't need a fix.

If the payload was html-encoded, it might actually encourage the use of setInnerHTML...

**Comment by kingthorin** [comment]
@davewichers when you encountered this was the issue raised with LOW confidence? Did the "other info" of the alert indicate that it was a non-HTML response?

@juhakivekas @davewichers would you rather that the alert was raised at LOW or INFORMATIONAL risk? (When the response is json.)

**Comment by davewichers** [comment]
This was so long ago that I have no idea about the confidence or other info.

I think raising it as an informational risk would be OK if you prefer that.
And then it's more a lack of input validation than XSS concern at that
point. Although it 'could' lead to DOM XSS, of course.

-Dave

**Comment by thc202** [comment]
Released in version 29 of Active scanner rules add-on.
