### ISSUE TITLE
Terminology - "Intercepting"

### ISSUE THREAD

**Issue by mnot** [zaproxy/zaproxy#3980]
Various parts of ZAP's documentation refer to it as an "intercepting proxy."

This phrase is used in HTTP to indicate a proxy that is inserted at the network layer, without configuration of the client.

As far as I can tell, ZAP is *not* an intercepting proxy, in that it has to be manually configured. If so, the appropriate term would be "forward proxy" or "configured proxy."

See:
  http://httpwg.org/specs/rfc7230.html#intermediaries
  https://en.wikipedia.org/wiki/Proxy_server#Transparent_proxy

**Comment by kingthorin** [comment]
Interesting point. Without bothering to read your references I would have said you were confusing transparent with intercepting.

In 5+ years this is the first mention I've encountered of any confusion, or debate as to the meaning/intention of the statements/description.

**Comment by mnot** [comment]
Please bother to read the references. 🙄

**Comment by thc202** [comment]
ZAP can act as an intercepting proxy, but, yeah, we should normalise how we reference ZAP's proxying capabilities (and document that better).

**Comment by kingthorin** [comment]
> Please bother to read the references. 🙄

I did 👍

**Comment by vanderaj** [comment]
@mnot, I know you literally set the HTTP standard, but this is a common term in our industry to mean something like Zap or Burp. We use "man in the middle" along with "intercepting proxy" pretty much everywhere. You might have an uphill battle reclaiming the term, similar to how we lost "hacker" to mean criminal and no one besides RMS regularly types "GNU/Linux". How important is it to be clear on this topic considering that we've been using this term for as long as Paros Proxy and WebScarab have been around (a decade or more).

**Comment by vanderaj** [comment]
Because this will also need to ripple through other OWASP standards and documents, like the Testing Guide, ASVS, and so on.

**Comment by vanderaj** [comment]
p.s. I need to disclose that Mark is a friend of mine. I'm challenging him not as a sock puppet but because I have a vested interest in the status quo, but I am willing to change my mind ;-)

**Comment by mnot** [comment]
Hey Andrew - I understand (and am not disputing that in this particular niche, a particular meaning has started to take hold), but in the rest of the industry (network operators, vendors, etc.), the term is widely used to mean the exact opposite of how you're using it. Search stackoverflow for examples.

If ZAP can be configured as an intercepting proxy or forward proxy, you should probably just be saying "proxy" (like Charles Proxy does), and saying it can be configured both ways explicitly.

Mind you, this isn't a huge issue; people will figure it out once they dive into your docs. It does create some confusion for folks used to the wider usage of the phrase, however.

**Comment by vanderaj** [comment]
As you asked the Zap guys, I'll let them consider this. @kingthorin @thc202 @psiinon please let me know what you land on, because if we do need to change, we need to coordinate this across all the Flagship and probably the Lab ones as well.

**Comment by kingthorin** [comment]
> It does create some confusion for folks used to the wider usage of the phrase, however.

Does it though? Pretty sure that terminology has been in use since ZAP was young. (As far as I can tell the help content goes back to v1.1.0 seven years ago). I can't speak for the whole team but this is the first I've heard of any questions/confusion.

**Comment by psiinon** [comment]
Its the first time I've seen this being questioned too :)
For reference, I wrote the original help pages (there were none in Paros) and being a newcomer to security I just accepted terms like this.
However I think we should aim to be as correct and accurate as possible, while accepting "industry standards". For example Cross Site Scripting isnt exactly an accurate term, but its one everyone uses for the (roughly;) the same thing.
We want to make sure that people understand that ZAP can be used to proxy browsers and other tools, and can intercept and change any data that flows through it.
We could change the 'offending' term with a phrase like the above. Its more unwieldy, but more technically correct :)
Lets have a look at where we use this term and see if we can work it better.
@vanderaj I dont think that this necessarily means that all OWASP documentation needs to change. However maybe its something we should raise on the leaders list?

**Comment by mnot** [comment]
I forgot this reference:
  https://tools.ietf.org/html/rfc3040#section-2.5

**Comment by psiinon** [comment]
Thanks @mnot.
I'm proposing that we change all references of 'interception proxy' to 'man-in-the-middle proxy'. This is not an implication that any other OWASP projects need to change their terminology - we'll leave that up to each project to decide :)
Any objections?
