### ISSUE TITLE
X-Content-Type-Options Help is Broken

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#3986]
https://github.com/zaproxy/zap-extensions/blob/master/src/org/zaproxy/zap/extension/pscanrules/resources/help/contents/pscanrules.html#L70

https://github.com/zaproxy/zap-core-help/wiki/HelpAddonsPscanrulesPscanrules#x-content-type-options

> This scanner check for the Anti-MIME-Sniffing header X-Content-Type-Options and ensures it is set to 'nosniff'. At MEDIUM and HIGH thresholds this scanner does not alert on client or server error responses or redirects. At LOW threshold it will alert on all responses including errors and redirects. thresholds it alerts on all response types if the header is missing or set to something other than 'nosniff'.

I believe the dangling sentence should just be removed?

Looks like the error snuck in here: https://github.com/zaproxy/zap-extensions/commit/7658674921d42850ff0bbe81a5acd7a0e1847f66#diff-d397771ac96cd46a7c8254585d891b37L57

**Comment by thc202** [comment]
Yeah, good catch.
