### ISSUE TITLE
localhost IPv6 is not in the whitelisted IPs by default

### ISSUE THREAD

**Issue by omerlh** [zaproxy/zaproxy#3987]
After adding `0:0:0:0:0:0:0:1` to the whitelist, I was able to browse the API UI from a browser. As it is the same as `localhost` and `127.0.0.1` already whitelisted, I think it makes sense to whitelist also this IP by default.

**Comment by thc202** [comment]
Yeah, that's now implemented in the weeklies. Closing as duplicate of #3836.
