### ISSUE TITLE
Selected checkbox tree nodes not correctly highlighted in macOS

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#3988]
Issue reported in OWASP ZAP User Group: https://groups.google.com/d/msg/zaproxy-users/8xw8VDLbO5U/PbOXDbOaAwAJ

The selected nodes in the checkbox tree are not correctly highlighted (like the Sites tree in #3351).

ZAP version:
Version 2.6.0 (older versions are also affected).

**Comment by psiinon** [comment]
Tested with a MacBook and it only appears to happen with the Mac OX X LaF - it works fine when using Nimbus and Flat Light.
