### ISSUE TITLE
X-COLD Passive Scanner Resource Typo

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#3997]
https://github.com/zaproxy/zap-extensions/blob/bf65399173f2d09c92e9f31eb575ff074de340e3/src/org/zaproxy/zap/extension/pscanrulesAlpha/resources/Messages.properties#L253

`or X-ChromePhp-Date` should be `or X-ChromePhp-Data` (e vs a)

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#1132.
