### ISSUE TITLE
Colouring history items

### ISSUE THREAD

**Issue by juhakivekas** [zaproxy/zaproxy#4000]
Some requests are more relevant than others, so having the ability to mark these in the history view by adding color to lines would help in analyzing more complex flows like complex login processes, features that require two-factor authentication, or flows that pass tokens to different services.

The minimal feature would be selecting a set consecutive of requests, and the select from the context menu `Colour -> blue (in blue?)`. A selection of a few colours (maybe matching the RSyntaxTextArea ones) would enable the user to use some personal colour coding for the messy parts of manual testing.

Enhancements to this feature could be colouring entries based on regular expressions, contexts, or some other rules, a bit like like [rules in wireshark](https://www.wireshark.org/docs/wsug_html_chunked/ChCustColorizationSection.html). Also being able to set the colour of histroy entries in scripts could be a nice addition. 

https://mozilla.logbot.info/websectools/20171101#c13791537

**Comment by thc202** [comment]
Could also colour based on the origin proxy #3983

**Comment by juhakivekas** [comment]
I made an addon over the weekend that colors items based on tags. It mostly covers the automated use-cases mentioned, and should be pretty generic since tags can be added manually, by passive scanners, or by scripts. I'll see how this works at its current state and figure out improvements later.

A current workflow could be like this:
- make a pasisve scanning script to identify interesting messages and tag them (eg. rest, auth, payment)
- configure color-tag pairs in addon panel (in history area)
- enjoy the colours and your new artificial synestesia

https://github.com/juhakivekas/zap-extensions/tree/neonmarker

**Comment by kingthorin** [comment]
Nice work.

Ref: https://github.com/zaproxy/zap-extensions/compare/alpha...juhakivekas:neonmarker

**Comment by thc202** [comment]
Closing. the Neonmarker add-on is already available in the marketplace. Related blog post: https://www.zaproxy.org/blog/2020-09-14-tags/
