### ISSUE TITLE
zap.bat should use %USERPROFILE% instead of %HOMEDRIVE%%HOMEPATH%

### ISSUE THREAD

**Issue by wlt** [zaproxy/zaproxy#4004]
ZAP Version: 2017-10-30 (weekly release)

## Suggenstion and Reasons

**zap.bat** should use `%USERPROFILE%` instead of `%HOMEDRIVE%%HOMEPATH%` to locate the file ".ZAP_JVM.properties".

There are two reasons:
1. [The user's default ZAP directory](https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsOptionsJvm) containing ".ZAP_JVM.properties" is [determined by "user.home" Java system property](https://github.com/zaproxy/zaproxy/blob/w2017-10-30/src/org/parosproxy/paros/Constant.java#L326) which usually equals to `%USERPROFILE%`, not `%HOMEDRIVE%%HOMEPATH%`.
2. `%HOMEDRIVE%%HOMEPATH%` can be different to `%USERPROFILE%`. (Actually I experienced it on a Windows machine managed by Active Directory. Of course, it caused an error same as #3211) See [about these variables](https://stackoverflow.com/questions/606483/what-is-the-meaning-of-these-windows-environment-variables-homedrive-homepath#8797855)

### Detail about reason 1

How "user.home" property is set is rather complicated, please see [stackoverflow answer](https://stackoverflow.com/questions/16889940/on-windows-7-how-does-java-jvm-set-user-home-system-property#16889969).

Here is summary:
* In Java 8: It equals to `%USERPROFILE%`
* In Java 7:  It seems to equal to `%USERPROFILE%` by default.

## Impact by adopting suggestion
* Users who have had `%HOMEDRIVE%%HOMEPATH%` different to `%USERPROFILE%` and put ".ZAP_JVM.properties" in only `%HOMEDRIVE%%HOMEPATH%` will get an error same as #3211

**Comment by thc202** [comment]
Yeah, that looks better, with Java 8 the `user.home` property is set from `FOLDERID_Profile`/`CSIDL_PROFILE`, which defaults to `%USERPROFILE%`.

**Comment by wlt** [comment]
Thank you for accepting my suggestion!
