### ISSUE TITLE
Issue when attempting to ignore all rules for a URL

### ISSUE THREAD

**Issue by ksindy** [zaproxy/zaproxy#4014]
I have created a config_file and can successfully ignore explicit rules for a url:

    #####  OUTOFSCOPE  http://bla.com

But WARNs are not being ignored when I use the asterisk wildcard in place of an explicit rule number:

    *  OUTOFSCOPE http://bla.com

Any ideas on what I might be doing wrong? Here is how I am running the scan:

    docker run -v ${PWD}:/zap/wrk --net=host -i owasp/zap2docker-weekly:latest zap-baseline.py -t http://bla.com/ -c zap_config

**Comment by kingthorin** [comment]
> But WARNs are not being ignored when I use the asterisk wildcard in place of an explicit rule number

Can you provide the contents of your config file for the problem scenario?

https://github.com/zaproxy/zaproxy/wiki/ZAP-Baseline-Scan#configuration-file

**Comment by ksindy** [comment]
```
# zap-baseline rule configuration file
# Change WARN to IGNORE to ignore rule or FAIL to fail if rule matches
# Only the rule identifiers are used - the names are just for info
# You can add your own messages to each rule by appending them after a tab on each line.
10010	WARN	(Cookie No HttpOnly Flag)
10011	WARN	(Cookie Without Secure Flag)
10012	WARN	(Password Autocomplete in Browser)
10015	WARN	(Incomplete or No Cache-control and Pragma HTTP Header Set)
10016	WARN	(Web Browser XSS Protection Not Enabled)
10017	WARN	(Cross-Domain JavaScript Source File Inclusion)
10019	WARN	(Content-Type Header Missing)
10020	WARN	(X-Frame-Options Header Scanner)
10021	WARN	(X-Content-Type-Options Header Missing)
10040	WARN	(Secure Pages Include Mixed Content)
2	WARN	(Private IP Disclosure)
3	WARN	(Session ID in URL Rewrite)
50001	WARN	(Script Passive Scan Rules)
90022	WARN	(Application Error Disclosure)
*	OUTOFSCOPE	http://localhost:4567/  
#10202	OUTOFSCOPE	http://localhost:4567/ 
```
When I uncomment the the line with the rule number, the rule is successfully ignored for the url.
But when running the config file as shown above (with the asterisk) the rule is not ignored for the url.

**Comment by ksindy** [comment]
Thanks @thc202 and  @psiinon ! Will these changes take effect in the next
`owasp/zap2docker-weekly` docker hub release?

**Comment by thc202** [comment]
Yes, the next release should have these changes (they are already available in `owasp/zap2docker-live`).

**Comment by ksindy** [comment]
Great thanks!
