### ISSUE TITLE
Proxying https://ipaddress raise a CERT_COMMON_NAME_INVALID Error in Browser 

### ISSUE THREAD

**Issue by denniskniep** [zaproxy/zaproxy#4016]
Every https://ipaddress url which is proxyed through ZAP would raise the NET::ERR_CERT_COMMON_NAME_INVALID Error in the Browser (Tested with Chromium and Firefox)

**Comment by kingthorin** [comment]
https://github.com/zaproxy/zaproxy/pull/3975
