### ISSUE TITLE
Zap scripting question

### ISSUE THREAD

**Issue by ChrisFernandez** [zaproxy/zaproxy#4022]
https://security.stackexchange.com/questions/173162/zap-proxy-script-to-modify-headers-automatically
Basically I am looking for a zap script to modify response codes in the headers before it gets to my browser, so I do not have to edit manually after each try.
Thanks

**Comment by kingthorin** [comment]
Well you could use the replaced extension (check the market place) or you could use an HttpSender script.

https://github.com/zaproxy/community-scripts/tree/master/httpsender

For future reference the ZAP User Group https://groups.google.com/group/zaproxy-users and Developer Group https://groups.google.com/group/zaproxy-develop are much better places for questions.

**Comment by ChrisFernandez** [comment]
Thanks <3 I will dig into that example and join the groups.

**Comment by thc202** [comment]
For help about the add-on:
https://github.com/zaproxy/zap-extensions/wiki/HelpAddonsReplacerReplacer

Although not as flexible in this case it's easier/faster to use a Replacer rule than a script.

**Comment by kingthorin** [comment]
Sorry that earlier response should have said "Replacer extension"

https://github.com/zaproxy/zap-extensions/wiki/HelpAddonsReplacerReplacer

**Comment by ChrisFernandez** [comment]
Thank you! I'll try it tonight and let you guys know and close the ticket.

**Comment by kingthorin** [comment]
If you're set on using a script you could build an HttpSender script that does something like:
```javascript
function sendingRequest(msg, initiator, helper) {
	// Nothing to do here
}

function responseReceived(msg, initiator, helper) {
     msg.setResponseHeader(msg.getResponseHeader().toString().replace('404','200'))
}
```

**Comment by thc202** [comment]
I'd suggest using a Proxy script (or check the `initiator` to just apply to the proxy?), otherwise it might affect the results of the active scanners (or other tools).
