### ISSUE TITLE
docker-base generates exceptions with WARN org.zaproxy.zap.extension.api.API

### ISSUE THREAD

**Issue by leopoldodonnell** [zaproxy/zaproxy#4027]
Steps to reproduce:

Run the following to start ZAP:

`docker run --rm -u zap --name zap -p 8180:8180 owasp/zap2docker-bare zap.sh -daemon -host 0.0.0.0 -port 8180 -config api.disablekey=true -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true -config database.recoverylog=false`

Test the API with curl

```
$ curl -s http://localhost:8180/JSON/core/view/version/?zapapiformat=JSON&formMethod=GET
{"version":"2.6.0"}
```
Review the output:

```
Found Java version 1.8.0_131
Available memory: 1999 MB
Setting jvm heap size: -Xmx499m
340 [main] INFO org.zaproxy.zap.DaemonBootstrap  - OWASP ZAP 2.6.0 started 10/11/17 17:35:51
395 [main] INFO org.parosproxy.paros.common.AbstractParam  - Setting config api.disablekey = true was null
395 [main] INFO org.parosproxy.paros.common.AbstractParam  - Setting config api.addrs.addr.name = .* was null
396 [main] INFO org.parosproxy.paros.common.AbstractParam  - Setting config api.addrs.addr.regex = true was null
397 [main] INFO org.parosproxy.paros.common.AbstractParam  - Setting config database.recoverylog = false was null
401 [main] INFO org.parosproxy.paros.network.SSLConnector  - Reading supported SSL/TLS protocols...
401 [main] INFO org.parosproxy.paros.network.SSLConnector  - Using a SSLEngine...
726 [main] INFO org.parosproxy.paros.network.SSLConnector  - Done reading supported SSL/TLS protocols: [SSLv2Hello, SSLv3, TLSv1, TLSv1.1, TLSv1.2]
739 [main] INFO org.parosproxy.paros.extension.option.OptionsParamCertificate  - Unsafe SSL renegotiation disabled.
1347 [main] INFO hsqldb.db..ENGINE  - open start - state not modified
1500 [main] INFO hsqldb.db..ENGINE  - dataFileCache open start
1520 [main] INFO hsqldb.db..ENGINE  - dataFileCache open end
1675 [ZAP-daemon] INFO org.zaproxy.zap.control.ExtensionFactory  - Loading extensions
4099 [ZAP-daemon] INFO org.zaproxy.zap.control.ExtensionFactory  - Installed add-ons: [[id=help, fileVersion=7], [id=spiderAjax, fileVersion=17], [id=diff, fileVersion=7], [id=alertFilters, fileVersion=4], [id=selenium, fileVersion=10, version=1.1.0], [id=webdriverlinux, fileVersion=2], [id=pscanrules, fileVersion=19], [id=fuzz, fileVersion=8, version=2.0.1], [id=saverawmessage, fileVersion=3], [id=invoke, fileVersion=6], [id=onlineMenu, fileVersion=5], [id=websocket, fileVersion=12], [id=jxbrowser, fileVersion=2], [id=jxbrowserlinux64, fileVersion=1], [id=jxbrowserlinux32, fileVersion=1], [id=zest, fileVersion=23], [id=replacer, fileVersion=2], [id=ascanrules, fileVersion=26], [id=tips, fileVersion=6], [id=directorylistv1, fileVersion=3], [id=gettingStarted, fileVersion=6], [id=scripts, fileVersion=18], [id=reveal, fileVersion=2], [id=bruteforce, fileVersion=6], [id=quickstart, fileVersion=19], [id=coreLang, fileVersion=11]]
4625 [ZAP-daemon] INFO org.zaproxy.zap.control.ExtensionFactory  - Extensions loaded

...

6400 [ZAP-daemon] INFO org.parosproxy.paros.extension.ExtensionLoader  - Initializing The ZAP Getting Started Guide
6401 [ZAP-daemon] INFO org.parosproxy.paros.extension.ExtensionLoader  - Initializing Quick Start panel 
6402 [ZAP-daemon] INFO org.parosproxy.paros.extension.ExtensionLoader  - Initializing Translations of the core language files
6520 [ZAP-daemon] INFO org.zaproxy.zap.extension.callback.ExtensionCallback  - Started callback server on 0.0.0.0:44137
6521 [ZAP-daemon] INFO org.zaproxy.zap.extension.dynssl.ExtensionDynSSL  - Creating new root CA certificate
9056 [ZAP-daemon] INFO org.zaproxy.zap.extension.dynssl.ExtensionDynSSL  - New root CA certificate created
9066 [ZAP-daemon] INFO org.zaproxy.zap.DaemonBootstrap  - ZAP is now listening on 0.0.0.0:8180
9924 [ZAP-ProxyThread-1] WARN org.zaproxy.zap.extension.api.API  - ApiException while handling API request:
Does Not Exist (does_not_exist) : scanId
	at org.zaproxy.zap.extension.ascan.ActiveScanAPI.getActiveScan(Unknown Source)
	at org.zaproxy.zap.extension.ascan.ActiveScanAPI.handleApiView(Unknown Source)
	at org.zaproxy.zap.extension.api.API.handleApiRequest(Unknown Source)
	at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(Unknown Source)
	at org.parosproxy.paros.core.proxy.ProxyThread.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)
14977 [ZAP-ProxyThread-2] WARN org.zaproxy.zap.extension.api.API  - ApiException while handling API request:
Does Not Exist (does_not_exist) : scanId
	at org.zaproxy.zap.extension.ascan.ActiveScanAPI.getActiveScan(Unknown Source)
	at org.zaproxy.zap.extension.ascan.ActiveScanAPI.handleApiView(Unknown Source)
	at org.zaproxy.zap.extension.api.API.handleApiRequest(Unknown Source)
	at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(Unknown Source)
	at org.parosproxy.paros.core.proxy.ProxyThread.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)

etc...
```

**Comment by psiinon** [comment]
It looks like you are also making other API requests, and at least one of them is missing the scanId parameter.
If thats the case then ZAP is acting as it should.

**Comment by leopoldodonnell** [comment]
Sorry, nope - I've checked to make certain that nothing is hitting the API.
All it takes is to start up docker the container and review the output.
Everything appears to work just fine, except that the exceptions are a
concern.

Here's what I get when I inspect the docker image:

The image Id:
sha256:14ec16aa0ef8702a8ea92fa5f3e939ef8483402d678eb36df81d60ab20b5a64c
The RepoDigest: owasp/zap2docker-bare@sha256
:176ca5dc0c167d5d6d383bf69f44582f79b4ae595ba0bacbae2122ec72a39b01

**Comment by kingthorin** [comment]
Looking at your config and the first few lines of your logs you listen on all interfaces, disable the API key, and allow connections from anywhere. Could be something else on your box or infra making invalid or unexpected requests to the API.

**Comment by leopoldodonnell** [comment]
As it turns out you are partly correct. I'm running it in a container, so
its only available from 8180 on my host and on the docker bridge network.
Being curious, I changed the port to 8999 and that appears to work. No idea
what's hitting the 8180 port; time to reboot!

I'll close this.

**Comment by thc202** [comment]
Thanks for letting us know.

Next time that happens you should try block all the addresses:
`docker run --rm -u zap --name zap -p 8180:8180 owasp/zap2docker-bare zap.sh -daemon -host 0.0.0.0 -port 8180 -config api.disablekey=true -config api.addrs.addr.name= -config database.recoverylog=false`

to know the source of those requests, e.g. trying to access it from host:
`8852 [ZAP-ProxyThread-1] WARN org.zaproxy.zap.extension.api.API  - Request to API URL http://localhost:8180/JSON/core/view/version/?zapapiformat=JSON&formMethod=GET from 172.17.0.1 not permitted`

**Comment by binarymist** [comment]
Hay @thc202 I'm having some trouble to get Zap to accept a source IP address. opening it up as in
`api.addrs.addr.name=.*`
is fine, but when I use `172.17.0.1` which is shown in the output from zap in container when I run your command, I just get:
`Request to API URL http://172.17.0.2:8080/ with host header 172.17.0.2 not permitted.`

**Comment by thc202** [comment]
Right, you also need to add the address ZAP is listening to (`172.17.0.2`), ZAP also/now validates the host header. [1]

[1] https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsOptionsApi#addresses-permitted-to-use-the-api

**Comment by thc202** [comment]
It uses the same key (that's why `-config api.addrs.addr.name=172.17.0.*` worked, as it was including both).

**Comment by binarymist** [comment]
Oh, right. Thanks, this is what I was looking for then: `-config api.addrs.addr.name=172.17.0.[1,2]`
Is this documented anywhere other than source code? If not, do we want it documented somewhere? 
Here: https://github.com/zaproxy/zaproxy/wiki/Docker
Here: https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsOptionsApi#addresses-permitted-to-use-the-api
and possibly Here: https://github.com/zaproxy/zaproxy/wiki/FAQapikey
If so, do you want to add it? If not, I can sub PR?

**Comment by psiinon** [comment]
Its in this FAQ: https://github.com/zaproxy/zaproxy/wiki/FAQapikey but maybe we need to include it elsewhere too

**Comment by binarymist** [comment]
It's there for hosts that "_connect to the API_", but don't think it says that the interface that Zap is bound to must also be specified, unless I'm just missing it?
