### ISSUE TITLE
MultiProxy Logging Discrepancy

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#4039]
Just noticed a minor logging issue with the new multiproxy functionality:
```
7730 [ZAP-BootstrapGUI] INFO org.zaproxy.zap.extension.proxies.ExtensionProxies  - Starting alt proxy server: localhost:8081
.....
23174 [Thread-9] INFO org.zaproxy.zap.extension.proxies.ExtensionProxies  - Stopping alt proxy server: localhost:8080
```

First there's no logging of the main proxy starting. Then at shutdown there main proxy is referred to as an alt and there's no logging for the actual alt.

![multiproxy](https://user-images.githubusercontent.com/7570458/32759511-d80d1ae6-c8b7-11e7-9489-5df3b21994a7.png)

**Comment by thc202** [comment]
The log at shutdown is also about the alt proxy (https://github.com/zaproxy/zaproxy/pull/4010#discussion_r150018795).
