### ISSUE TITLE
Local Proxy address unstable

### ISSUE THREAD

**Issue by juhakivekas** [zaproxy/zaproxy#4045]
When setting the main proxy in the Local Proxies options panel to 0.0.0.0, the proxy starts up correctly. However, when closing the options and opening it again, the dialog shows another address. For me it seems to semi-randomly jump between my wifi and vpn interface addresses.

Steps to reproduce:
1. Set proxy address to 0.0.0.0 from the drop-down menu or by typing it
2. OK, save the edits
3. Open options again, the proxy address now shows a different value (in my case 192.168.24.128 or 10.191.8.1)
4. OK, save the options
5. The proxy is no longer listening on all interfaces

The behavior is not the same when using an additional proxy, there addresses seem to be persisted correctly.
```
Java 1.8.0_77
Zap D-2017-11-13
osX 10.11.6
```

**Comment by thc202** [comment]
Closing, merging into #4032 (fixed in #4034).
