### ISSUE TITLE
Duplicate elements in context menus

### ISSUE THREAD

**Issue by eoftedal** [zaproxy/zaproxy#4060]
In the zest editor I'm seeing duplicate elements in context menus

<img width="361" alt="screen shot 2017-11-21 at 09 25 54" src="https://user-images.githubusercontent.com/238804/33061970-23cd9cda-ce9e-11e7-9271-b77dbc3a95ab.png">

I've reinstalled ZAP, but it didn't help...

OS: MacOS
ZAP: 2.6.0 installed via .dmg

**Comment by thc202** [comment]
Possibly a duplicate of #2106 (or related fix), leaving open until we get confirmation that it no longer happens with latest versions of Script Console and Zest.

**Comment by eoftedal** [comment]
Fixed in the latest version of the plugin

**Comment by thc202** [comment]
Thanks for the confirmation!
