### ISSUE TITLE
Deleting a parent URL in History tab should not delete all child URLs

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#4065]
See animated gif below. Note on the 3rd action against a single entry/line all entries from the history table are removed. (This is based on running from within eclipse on Windows 7.)

![test](https://user-images.githubusercontent.com/7570458/33124365-aaf366c0-cf4a-11e7-855b-5f35eb3d4455.gif)

Based on what I was testing at the time (addressing https://github.com/zaproxy/community-scripts/issues/77) it seems that the history table (db) is actually emptied (i.e.: this is more than just a UI issue.)

I doubt it matters but just so that I'm fully providing details the history was established using accessUrl via the web API.

**Comment by thc202** [comment]
Issue title updated, setting this to 2.7.0 (does not require much changes).

**Comment by thc202** [comment]
For the record, this was discussed in IRC and the conclusion is that the current behaviour is unintuitive. The behaviour in History tab should be changed to just delete the selected entries independently if they are parent URLs/nodes or not. The behaviour in the Sites tree should be kept the same, deleting a parent URL/node should delete the child URLs/nodes.
