### ISSUE TITLE
Path Traversal false positive with JAVA?

### ISSUE THREAD

**Issue by KuanCat** [zaproxy/zaproxy#4074]
Hi, I have a Java Servlet program.
My servlet have a filter to protect, but I run zap and get path traversal alert.

The request header

<pre>GET 
https://www.newnavigate.com/navigate/presenter.jsp?ext=%7B%25%3Dentry.extension%25%7D&fi=%7B%25%3Dentry.id%25%7D&m=%7B%25%3Dentry.mode%25%7D&s=%7B%25%3Dnavigate.params.servicegateway%25%7D&t=presenter.jsp&thu=%7B%25%3Dentry.thumbnailEncType3%25%7D&w= HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0
Pragma: no-cache
Cache-Control: no-cache
Content-Length: 0
Referer: https://www.newnavigate.com/navigate/error/?e=999&u=https://www.newnavigate.com/navigate/
Host: www.newnavigate.com
</pre>
Filter detect and redirect.

Java Code : `rsp.sendRedirect("/navigate/");`

Response Header
<pre>
HTTP/1.1 302 Found
Server: Apache-Coyote/1.1
Location: https://www.newnavigate.com/navigate/
Content-Length: 0
Date: Thu, 23 Nov 2017 14:34:53 GMT
</pre>

<pre>HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
Set-Cookie: JSESSIONID=9B5B6449828CC05145B38BFA634DE6FD; Path=/navigate; Secure
Set-Cookie: locale=zh_TW; Domain=.newnavigate.com; Expires=Fri, 23-Nov-2018 14:09:48 GMT; Path=/
X-Frame-Options: SAMEORIGIN
Cache-Control: no-cache
Pragma: no-cache
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Content-Type: text/html;charset=utf-8
Content-Language: zh-TW
Content-Length: 7213
Date: Thu, 23 Nov 2017 14:09:47 GMT</pre>

Is it a false positive or I have something wrong ?
Thank you.

**Comment by kingthorin** [comment]
@KuanCat could you provide the details of the alert your receiving? (A screenshot is fine)

**Comment by KuanCat** [comment]
@kingthorin Is this ok?
![default](https://user-images.githubusercontent.com/20170510/33193427-74323e4e-d103-11e7-950f-a6ab6b26c183.png)
Thank you.

**Comment by kingthorin** [comment]
That helps a bit. Are you able to provide the text of the response body, as well as the details in the bottom part of the alert display?

Can you tell us what the `t` parameter in the request is supposed to control? It seems ZAP injected "presenter.jsp" there and got a good response, while it had previously inserted a random string there and got a failed response.
https://github.com/zaproxy/zap-extensions/blob/35de4287c5ecdb7e2d9afa3232d8a841796a1919/src/org/zaproxy/zap/extension/ascanrules/TestPathTraversal.java#L459-L460

**Comment by KuanCat** [comment]
The following url is my response header and response body. Response body is index.html.
https://gist.github.com/KuanCat/1fbfa43143768b6a63d94625affc6d1d

The<pre>t</pre>paremeter is TOKEN to load image.

Like this <pre><img alt="" src="https://webrelay/${param.t}/${thu}.jpg"</pre>

![default](https://user-images.githubusercontent.com/20170510/33194823-a1e9eb70-d10d-11e7-99d4-5904aa742d48.png)

Use resend and uncheck Follow redirect will receive 302.
![default](https://user-images.githubusercontent.com/20170510/33194894-244362fe-d10e-11e7-92ec-b705488235e0.png)
![default](https://user-images.githubusercontent.com/20170510/33194901-362dd256-d10e-11e7-9713-f6dcb49b464d.png)

Thank you.

**Comment by kingthorin** [comment]
The actual 200 after the redirect (ZAP is following the redirect in this test) [the body text that goes with the header at the bottom of your original report]

**Comment by KuanCat** [comment]
So, if the request parameter is path and redirect is 200, the Path Traversal will alert?
Thank you.

**Comment by kingthorin** [comment]
Not quite. Let's look at that response body and we'll figure out what's going on and if you gave an issue or false positive.

**Comment by KuanCat** [comment]
Hello, I found use tomcat6 will alert, but use tomcat7 not alert. 
Maybe tomcat6 and tomcat7 response something different.
Thank you.

**Comment by kingthorin** [comment]
Is there some reason you can't provide the body of the response? If there's an actual issue you should fix it, if there's a false positive we should fix it.....

**Comment by KuanCat** [comment]
Sorry, this body that is what you want? It is from zap.
https://gist.github.com/KuanCat/fedfed0fbb041c3728461ae929586e55
Thank you.

**Comment by kingthorin** [comment]
That's the body that's associated with the alert?

**Comment by KuanCat** [comment]
Yes, I copy from ZAP.
![default](https://user-images.githubusercontent.com/20170510/33305256-3c2dd9de-d448-11e7-8387-81726e730689.png)

**Comment by kingthorin** [comment]
So as I understand things this is what the particular rule is doing at the point that this alert is generated (it checks about 5 or 6 different conditions, but this seems to be one specifically):

- Request a URL with a filename that shouldn't exist. (`https://www.newnavigate.com/navigate/thishouldnotexistandhopefullyitwillnot`)
- Get the filename from the original URL (in your example: `presenter.jsp`)
- If there is a filename (some URLs end in slash....) and either the status code for the non-exist file isn't ok (200) or the word Exception or Error was in the response then continue.
- With the original URL take the filename and insert it as a param value (hence: `t=presenter.jsp`), send the request.
- If the response is ok (200) and doesn't contain Error or Exception, then raise an alert. (As you seem to have encountered.)

Can you confirm that this sequence does play out for your particular app?

**Comment by kingthorin** [comment]
@KuanCat are you able to answer the previous questions or should this ticket be closed?

**Comment by kingthorin** [comment]
No further user input in months, closing.
