### ISSUE TITLE
the break option in zaproxy not available 

### ISSUE THREAD

**Issue by murradkh** [zaproxy/zaproxy#4088]
![ice_screenshot_20171127-235958](https://user-images.githubusercontent.com/26089554/33291630-2422ea38-d3cf-11e7-8c25-ab8bb946197c.png)

**Comment by murradkh** [comment]
i dont know why this option not clickable , can you help me with that.
regards,

**Comment by thc202** [comment]
Which ZAP version are you using?

Note that you can always (manually) add the breakpoints with the toolbar button. [1]

[1] https://github.com/zaproxy/zap-core-help/wiki/HelpUiTltoolbar#-add-a-custom-http-break-point

**Comment by thc202** [comment]
btw, does that happen with all nodes or just that one?

**Comment by thc202** [comment]
Worth checking the Mode, that's disabled when in Safe or Protected. [1]

[1] https://github.com/zaproxy/zap-core-help/wiki/HelpUiTltoolbar#mode-pulldown

**Comment by murradkh** [comment]
-)zap 2.6.0
-)thats happen with all nodes.
thank you for fast reply , i will check that .

**Comment by murradkh** [comment]
the problem is solved, i changed the mode.
thanks,

**Comment by thc202** [comment]
No problem, thanks for letting us know!
