### ISSUE TITLE
exclude specific url

### ISSUE THREAD

**Issue by galak06** [zaproxy/zaproxy#4095]
i am testing we site that have embed video from youtube when i am using proxy from selenuim my site get stack. what can be the reason

**Comment by thc202** [comment]
Are there any errors in the zap.log? Does your Selenium tests rely on the video being loaded? If not, blocking (e.g. drop, with a Proxy script) those requests is probably better (ZAP might have problems handling bigger files).

**Comment by kingthorin** [comment]
@galak06 any update?

**Comment by galak06** [comment]
you can close the case. 
%zap-cli% exclude "https://ajax.aspnetcdn.com.*"
%zap-cli% exclude "https://www.gstatic.com.*"
%zap-cli% exclude "https://www.youtube.com.*"

**Comment by thc202** [comment]
Thanks for letting us know. Closing.
