### ISSUE TITLE
can i make software application to use zaproxy ?

### ISSUE THREAD

**Issue by murradkh** [zaproxy/zaproxy#4096]
i know how to make the browser to use zaproxy,but i dont know if i can do that for software applications traffic.
regards,

**Comment by omerlh** [comment]
What do you mean? your question is very generic, please share more details

**Comment by kingthorin** [comment]
If you can set a proxy for it (at the app, the virtual machine [incl java], the OS) then yes.

**Comment by murradkh** [comment]
i want  all the traffic in my internet  to pass through the zaproxy , including programs in my computer which using the internet .
i hope now is more clear.

**Comment by kingthorin** [comment]
Set your system proxy, make sure you change the “no proxy for” to blank. As long as the apps aren’t using raw sockets you should be good....

**Comment by murradkh** [comment]
thanks you,
