### ISSUE TITLE
What are the correct API parameters for /JSON/authentication/action/setAuthenticationMethod/ for scriptBasedAuthentication?

### ISSUE THREAD

**Issue by eoftedal** [zaproxy/zaproxy#4098]
I keep getting:
``` {"code":"missing_parameter","message":"Missing Parameter"} ```

What are the expected parameters?

**Comment by thc202** [comment]
It depends on the script (if has or not required parameters), the authentication method itself only requires the "scriptName" (as given by `/JSON/authentication/view/getAuthenticationMethodConfigParams/?authMethodName=scriptBasedAuthentication`).
If you enable the option "Report error details via API" it will give the name of the parameter missing. [1]


[1] https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsOptionsApi#report-error-details-via-api

**Comment by eoftedal** [comment]
I figured out that this works:
```zap.authentication.set_authentication_method(2, 'scriptBasedAuthentication', 'server=http://example.com&scriptName=authentication.zst')```
which in turn sends:
```GET /JSON/authentication/action/setAuthenticationMethod/?contextId=3&authMethodName=scriptBasedAuthentication&authMethodConfigParams=server%3Dhttp%3A%2F%2Fexample.com%26scriptName%3Dauthentication.zst```
