### ISSUE TITLE
Websocket binary message rendering loses original message

### ISSUE THREAD

**Issue by juhakivekas** [zaproxy/zaproxy#4108]
When inspecting BINARY messages in the manual editor, `<unreadable binary payload> ` is shown for payloads that are not valid UTF-8. This is fine in the preview, but when switching to hex view, the hexdump of `<unreadable binary payload> ` is shown. This change will be present in the message until the message is reloaded from the database due to paging of the table view.

A possible fix seems to be that `WebSocketPanelTextView` should override `HttpPanelTextView.save()` when the payload is not valid UTF-8.

**Comment by thc202** [comment]
Warning and request explicit action from the user to change as text is probably the better.

**Comment by thc202** [comment]
Released in version 15 of WebSockets add-on.
