### ISSUE TITLE
making all software applications to use proxy

### ISSUE THREAD

**Issue by murradkh** [zaproxy/zaproxy#4110]
Hi,
Im trying  to make  testing for my App ,to passing through zaproxy, but useless efforts. 
i know how making the browser to use the zaproxy  ,but for Appi dont know. 
i tried to use proxifier, proxyCap (which i can choose specific App  to pass through specific proxy ) , and it success to pass through  zaproxy only if the protocol was http , else, it will give me error of certification .
anyone know how to solve this problem ? 
(maybe on how to make Ap to use zaproxy with another program better than proxifier or proxyCap).
(or how to remove the certification error.)
Regards,
![ice_screenshot_20171203-090050](https://user-images.githubusercontent.com/26089554/33523218-b40ec6b0-d809-11e7-9e81-987a9bc5cb81.png)
![ice_screenshot_20171203-090203](https://user-images.githubusercontent.com/26089554/33523220-b9789a22-d809-11e7-8fb2-1a6dfdba40ef.png)
![ice_screenshot_20171203-090646](https://user-images.githubusercontent.com/26089554/33523221-bb44f148-d809-11e7-899b-8967d7e150ba.png)

**Comment by kingthorin** [comment]
Did you add ZAP's certificate to your certificate store?

**Comment by kingthorin** [comment]
This FAQ might help you as well: https://github.com/zaproxy/zaproxy/wiki/FAQmetro

**Comment by murradkh** [comment]
thanks for replying, 
i did added the certification in "trusted root certification"  .
![ice_screenshot_20171203-121346](https://user-images.githubusercontent.com/26089554/33524317-b9cdcdf2-d823-11e7-9751-986d4ca340e3.png)
is that correct place?

**Comment by murradkh** [comment]
when i remove the certification , another type of error showes up .
![ice_screenshot_20171203-122819](https://user-images.githubusercontent.com/26089554/33524418-b3a20fe0-d825-11e7-85f5-ad26a590337c.png)

**Comment by kingthorin** [comment]
Yes that’s correct.

**Comment by murradkh** [comment]
@kingthorin do you have ideas about forwarding the traffic of apps through zaproxy ?
thanks,

**Comment by kingthorin** [comment]
@murradkh sorry I couldn't get back to your earlier (weekend, family, opensource, etc). Did you solve your issue?

**Comment by murradkh** [comment]
hey,
its okay, i Moved on this problem , i dont want to keep hanging on it.
Anyway thank you for your help :)
regards,
