### ISSUE TITLE
zap-api-scan URL Error with zap2docker-weekly (2017-12-04)

### ISSUE THREAD

**Issue by royjs** [zaproxy/zaproxy#4118]
Since the latest zap2docker-weekly (2017-12-04) I have an error when using the zap-api-scan.py script.

```
ERROR <type 'exceptions.TypeError'>
2017-12-05 15:08:02,823 Unexpected error: <type 'exceptions.TypeError'>
Traceback (most recent call last):
  File "/zap/zap-api-scan.py", line 349, in main
    if len(urls) > 0:
TypeError: object of type 'instancemethod' has no len()
```
And that prevents the scan from starting correctly.
It seems that simply adding "()" at the end of this line fixes it:
https://github.com/zaproxy/zaproxy/blob/733488f92cb26b62218a300a1c1b960af403d912/build/docker/zap-api-scan.py#L348

This file hasn't changed in a while so I'm not sure why this issue just appeared.

**Comment by thc202** [comment]
In the newer version of the API client that's no longer a property.
