### ISSUE TITLE
Duplicate requests not shown?

### ISSUE THREAD

**Issue by PenelopeFudd** [zaproxy/zaproxy#4128]
I'm trying to debug an application that has a 5MB .js file, and takes 10+ seconds to load.

ZAProxy is showing the initial request/response, but when I hit reload in the browser, it's not showing the second request, even though Firebug and the Firefox developer tools both show it.

Is there an option that hides/shows duplicate requests?

Thanks

**Comment by kingthorin** [comment]
The file is probably cached by the browser. If the browser retrieves it from local memory or disk cache there is no network activity for ZAP to "see". 

You can verify this by looking at the requests via the network tab of the browser dev tools.

**Comment by PenelopeFudd** [comment]
I did check, it is being downloaded again.  It takes more than ten seconds each time, which is what made it noticeable, but it's not showing up in Zap.On Dec 6, 2017 3:27 PM, kingthorin <notifications@github.com> wrote:The file is probably cached by the browser. If the browser retrieves it from local memory or disk cache there is no network activity for ZAP to "see".
You can verify this by looking at the requests via the network tab of the browser dev tools.

**Comment by PenelopeFudd** [comment]
I tried loading it in Chrome, and it does cache correctly there.  I must have set 'disable cache' somewhere in my settings.  

But regardless, Zap should have recorded these uncached requests.

**Comment by thc202** [comment]
They should be shown, ZAP does not check if the requests are duplicated or not (assuming the requests are not excluded/ignored, e.g. Exclude from Proxy, script).

Might worth checking the zap.log to see if there's an error.

**Comment by kingthorin** [comment]
@PenelopeFudd have you checked the log for errors are @thc202 suggested?

**Comment by kingthorin** [comment]
Closing. Nothing further from the user after >3mo.
