### ISSUE TITLE
Connection reset making request on API

### ISSUE THREAD

**Issue by elenabdc** [zaproxy/zaproxy#4129]
I get a connection reset when I make a request to the api (accessing via 127.0.0.1:8080). I'm using the last version 2.7.0 on kali.

I have tried to change the api key and disable it but the result is the same. I have also checked the information in https://github.com/zaproxy/zaproxy/wiki/FAQapikey

Thank you.

**Comment by kingthorin** [comment]
Are you making the connections locally?

**Comment by elenabdc** [comment]
Yes, I'm running a kali, then I start ZAP providing command line options as indicated in the FAQ api key link and then I access 128.0.0.1:8080.

In the API page, I select (as an example) API local - httpSessions - sites () and I get the connection reset error.

<img width="934" alt="captura de pantalla 2017-12-07 a las 13 43 53" src="https://user-images.githubusercontent.com/19324403/33715992-c7656810-db54-11e7-9523-9098e98a638a.png">
<img width="928" alt="captura de pantalla 2017-12-07 a las 13 44 11" src="https://user-images.githubusercontent.com/19324403/33715996-cb80a57c-db54-11e7-93a1-40d593c6f469.png">

**Comment by thc202** [comment]
Would you checking the log file (zap.log in ZAP home dir [1])? It should indicate what the problem is.

[1] https://github.com/zaproxy/zaproxy/wiki/FAQconfig

**Comment by kingthorin** [comment]
Are you sure that ZAP successfully started listening on 8080? (You're not running something else that's using the port?)

**Comment by elenabdc** [comment]
@kingthorin I'm completely sure.
@thc202 log file says the API key is incorrect. What am I doing wrong? I'm starting ZAP using command line like this:
`owasp-zap -config api.key=apikey12345 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true`

I have also tested:
`owasp-zap -config api.key=apikey12345`
And:
`owasp-zap -config api.disablekey=true`

**Comment by kingthorin** [comment]
Are you able to browse to http://localhost:8080 and get the welcome page? (It doesn't require apikey etc)

**Comment by kingthorin** [comment]
It's failing because of the way you're starting zap "owasp-zap" whatever script/wrapper that is that kali sets up doesn't seem to be passing the CLI arguments properly. If you do the following it should work as expected:
```
/usr/share/zaproxy/zap.sh -config api.key=apikey12345 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true
```

**Comment by elenabdc** [comment]
@kingthorin yes, that's it. By doing /usr/share/zaproxy/zap.sh ... I didn't get any kind of error.

Thank you for your help @kingthorin @thc202

**Comment by kingthorin** [comment]
\o/ thanks for letting us know.
