### ISSUE TITLE
zap-full-scan.py help references non-existent wiki page

### ISSUE THREAD

**Issue by claudijd** [zaproxy/zaproxy#4131]
~https://github.com/zaproxy/zaproxy/blob/develop/build/docker/zap-full-scan.py#L101~
https://github.com/zaproxy/zaproxy/blob/c767a320356503bdd07d83c39aa6a020acc77f05/docker/zap-full-scan.py#L101

When I go to https://github.com/zaproxy/zaproxy/wiki/ZAP-Full-Scan, I'm prompted to create the page.

I was looking for information on how to set a max run time on a zap-full-scan.

<sub>Edited by @kingthorin 20180329 - updated reference to resource location.</sub>

**Comment by kingthorin** [comment]
Looks like something @psiinon intended to build and include here: https://github.com/zaproxy/zaproxy/wiki/Packaged-Scans

That's just a guess though...

**Comment by kingthorin** [comment]
@claudijd I believe you're after: 
```python
-T                max time in minutes to wait for ZAP to start and the passive scan to run
```

https://github.com/zaproxy/zaproxy/blob/develop/build/docker/zap-full-scan.py#L98

**Comment by psiinon** [comment]
Yeah, I should have written this page before ;)

**Comment by psiinon** [comment]
Now written :D

**Comment by kingthorin** [comment]
Thanks!
