### ISSUE TITLE
zap-full-scan.py throwing type exceptions at the end of the scan

### ISSUE THREAD

**Issue by claudijd** [zaproxy/zaproxy#4132]
I'm running command-line invoked full scans using zap-full-scan.py in the docker container setup and I'm now seeing type exceptions after the scan is complete.

The invoking command is ($i is passed in as a hostname var):

docker run -v "$(pwd)":/zap/wrk/:rw --dns 8.8.8.8 -u root -i owasp/zap2docker-weekly zap-full-scan.py -d -c ./zap/config.cfg -J report_$i.json -t https://$i/

The resulting scan log appears all normal on the surface, no apparrent errors, until the end when it throw this type error:

59550 [Thread-11] INFO org.parosproxy.paros.core.scanner.HostProcess  - completed host https://sshscan.rubidus.com in 40.212s
59551 [Thread-10] INFO org.parosproxy.paros.core.scanner.Scanner  - scanner completed in 40.248s
ERROR <type 'exceptions.TypeError'>
Caught an exception trying to read report sshscan.rubidus.com

I thought this was isolated to a new domain I was trying, but this appears to affect any domain I try to scan.  I mentioned some questions in #websectools, looking for some ideas on how to proceed, but logging here in case anyone else has ideas on what might be causing this.

Also, I suspect I'm one of few using the -J flag for running scans, so I tried -r flag and got the same behavior.

**Comment by claudijd** [comment]
This could be a dup of https://github.com/zaproxy/zaproxy/issues/4118 seems really similar.

For a work-around, we think reverting to stable will be a reasonable work around for this until weekly is released next week.

**Comment by kingthorin** [comment]
This issue was worked in IRC, see https://mozilla.logbot.info/websectools/20171207 for details.

**Comment by thc202** [comment]
Closing, fixed in latest weekly Docker image.
