### ISSUE TITLE
How to scan the urls which are only in scope

### ISSUE THREAD

**Issue by usualwyy** [zaproxy/zaproxy#4133]
In the latest version, active scan work on all the urls except the exclude items.
How can I scan the urls only in scope?

**Comment by thc202** [comment]
Is that through the UI or API?

With "latest version" is that compared to an older version? If so, which one?

**Comment by kingthorin** [comment]
There seems to be something missing here. 

Yes exclusions won’t be scanned. (They’re excluded...)

You can set a Context as your starting point for scanning. If you have more than one context you’d have to scan them all in order to cover “all in scope”.

**Comment by usualwyy** [comment]
@thc202 
1.UI
2.All the versions,not only the latest version.

@kingthorin 
Yes,I can set a context,and there are both exclusion and inclusion rules in context setting.But it seems that the active scan only accept the exclusion rules which under the scan options.
Exclusion and inclusion rules in context options don’t effect the active scan,am I right?

**Comment by kingthorin** [comment]
I think this is just some terminology confusion. 

Yes you can exclude things from scan (say a logout page within your context... whatever).

“In scope” implies within a context. So if you want to scan something “in scope” you have to define the scope by creating one or more contexts.
