### ISSUE TITLE
REST API to manage script variables

### ISSUE THREAD

**Issue by compaluca** [zaproxy/zaproxy#4135]
Likely related to [https://github.com/zaproxy/zaproxy/issues/3512](https://github.com/zaproxy/zaproxy/issues/3512), but maybe more general.

Let me explain a simple use case:
* python application using ZAP REST API
* this app creates and loads different proxy rules into ZAP: both ZEST and JS ("Oracle Nashorn") proxy rules
* each rule performs a specific operation under certain conditions 
* the app needs now to know which operations were executed and which ones were not

IMHO, the simplest solution would be:
* each proxy rule that execute its operation sets a variable "proxy_rule_name_operation" to  "executed"
* notice that this needs to be done for both kind of rules (ZEST and JS)
* app invokes the ZAP REST API to get the values of those variables 

Discussion on google group: [https://groups.google.com/forum/#!msg/zaproxy-users/Zn1OorL2Cb0/-PXunroEAgAJ](https://groups.google.com/forum/#!msg/zaproxy-users/Zn1OorL2Cb0/-PXunroEAgAJ)

**Comment by psiinon** [comment]
It should be possible to add API calls for reading script variable using the new extender scripts, at least for 'standard' scripts.
I suspect Zest scripts dont support the script variables, but I'd have thought we could enhance them to support them ina suitably generic way :)

**Comment by kingthorin** [comment]
> I suspect Zest scripts dont support the script variables, but I'd have thought we could enhance them to support them in a suitably generic way :)

Yup we've got an issue for that : https://github.com/zaproxy/zaproxy/issues/3512
