### ISSUE TITLE
Can't find resource for bundle java.util.PropertyResourceBundle, key enc2.label.unicode.escapedText

### ISSUE THREAD

**Issue by usualwyy** [zaproxy/zaproxy#4139]
I did a commit several days ago(a9315b7c78bbdecd95fd3b216681183fab45ac57), but I found it throw a exception: Can't find resource for bundle java.util.PropertyResourceBundle, key enc2.label.unicode.escapedText.
I have already added the key->value message in Messages.properties,why it still has error?
I make a break point at `public String getString(String key)` in l18N.java, the info shows the language = "en",and the languageTag="en-GB",but I can not find the Messages_en_GB.properties in Resource Bundle dir.

**Comment by kingthorin** [comment]
Most likely you have a typo somewhere, I’ll pull the branch later and have a look. Is it that commit specifically that has the issue or have you made further changes locally?

**Comment by kingthorin** [comment]
BTW this is the type of thing the dev group is made for, which is much more appropriate for development questions than our issue tracker.

https://groups.google.com/forum/m/#!forum/zaproxy-develop

**Comment by usualwyy** [comment]
I did not make any local change,if you open the 'encode/decode/hash' tool after pull the branch,you will see the exception.
I will post this issue in the develop forum.

**Comment by thc202** [comment]
For the record:
https://groups.google.com/d/topic/zaproxy-develop/OkA6lbMbWxg/discussion

Closing the issue, we can reopen it if there's a bug/issue with the code.
