### ISSUE TITLE
ZAP : unable to listen on this address and  port :localhost:9080

### ISSUE THREAD

**Issue by nf634** [zaproxy/zaproxy#4152]
MY app is running on 9080, when i;m trying to add 9080 port in zap loacal proxy setting it's showing me error message  - unable to listen on this address and  port :localhost:9080

**Comment by thc202** [comment]
You need to choose a different port (than your app, or any port already in use) for ZAP. Then use that port to proxy through with the client/browser.

**Comment by nf634** [comment]
Ohh... it seems like i was completely in wrong assumption, it may sound like foolish still want to confirm - So my running application port is 9080 and ideally it not needed to add in local proxies of ZAP . right?

**Comment by thc202** [comment]
Correct, the local proxy should use its own port (unrelated to the possible targets it will connect to).

**Comment by thc202** [comment]
Closing, all questions seem to be answered. Any other question, please, let us know through the [User Group](https://groups.google.com/group/zaproxy-users). Thank you.
