### ISSUE TITLE
Are these false positives?

### ISSUE THREAD

**Issue by quartilesoftware** [zaproxy/zaproxy#4161]
Hi,

I have a .Net Core1.1 App running on Azure. I’ve run ZAP and have received a report which contains two items I think are false positives. 

I’m hoping to get some help or guidance here to confirm what I think, or otherwise suggest what I may be overlooking.

I’ve listed below what the ZAP alert title says about each of the issues, together with what I have already coded or configured in the App which directly addresses the alert, and which therefore leads me to think the alerts must be false positives:

1.Web Browser XSS Protection Not Enabled.

In Startup.cs for the application. I have included this:

   app.Use(async (context, next) =>
   {
     context.Response.Headers.Add("X-XSS-Protection", "1; mode=block");
      ….

      await next();
   );

2.Path traversal.

The URL which the alert relates to is a method which accepts a single string parameter. 
In the first line of the method I ensure that only standard alphabetic characters a-z are permitted. 
Special characters which might permit path traversal are not permitted.

Can anyone please let me know if I am correct to conclude these ZAP alerts are false positives, or otherwise what I may be overlooking?

Regards.

QSL

**Comment by kingthorin** [comment]
This isn't enough detail to answer your questions. 

For the first one, select the alert, look at the response tab...is the header there?
For the second one please provide the details of the alert and full text of the request/response (associated with the alert).

**Comment by quartilesoftware** [comment]
Thanks for helping.

For the first point, it was in fact an effect of the second point.

The second point – file traversal was pointing me in the direction of an issue, but it was certainly not related to file traversal.  When the parameters supplied to the URL were unacceptable, the MVC model being returned to the view did not contain a populated select list, as it would if the parameters had been acceptable. The resultant error caused a redirect to the error handling page. Correcting that unpopulated select list removed the file traversal alert being generated by Zap.

Neither of the two alerts is now reported by Zap.

**Comment by kingthorin** [comment]
Thanks for letting us know.
