### ISSUE TITLE
ajaxSpider.number_of_results is not cleared when a new session is created

### ISSUE THREAD

**Issue by eoftedal** [zaproxy/zaproxy#4163]
ajaxSpider seems to return an aggregated number when querying number_of_results over the REST API. 

This number should be reset, at least when a new session is created.

**Comment by thc202** [comment]
Which version of Ajax Spider add-on are you using? Could you provide the steps to reproduce that? The number of results is being cleared when starting a new (API) scan and when creating a new session.

**Comment by eoftedal** [comment]
Version 20.0.0

```
>>> zap.ajaxSpider.number_of_results
'19582'
>>> zap.core.new_session()
'OK'
>>> zap.ajaxSpider.number_of_results
'19582'
```
GET /JSON/ajaxSpider/view/numberOfResults/?apikey=xxx HTTP/1.1
```
HTTP/1.1 200 OK
...
{"numberOfResults":"19582"}
```
GET /JSON/core/action/newSession/?apikey=xxx HTTP/1.1
```
HTTP/1.1 200 OK
...
{"Result":"OK"}
```
GET /JSON/ajaxSpider/view/numberOfResults/?apikey=xxx HTTP/1.1
```
HTTP/1.1 200 OK
...
{"numberOfResults":"19582"}
```

**Comment by eoftedal** [comment]
It seems to be cleared when a new scan is started, so my initial impression was wrong.
But it does not seem to be cleared when a new session is started.

**Comment by thc202** [comment]
Thanks for the details!

**Comment by thc202** [comment]
Released in version 21 of Ajax Spider add-on.
