### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by Chris350F** [zaproxy/zaproxy#4195]
I am trying to install ZAP.  Win64 machine.  Java 8 (update 151).  Install advises it cannot locate 64 bit JRE and when I point it at the correct Java folder, it then tells me there is no JVM installed.  I have installed the latest Java and am stuck.  Thank you all for helping me get started with ZAP.

**Comment by kingthorin** [comment]
Are you able to run any java apps? Is java in your %PATH%? Are you sure you didn't install JDK without JRE?

**Comment by kingthorin** [comment]
@Chris350F did you get your issue resolved?

**Comment by kingthorin** [comment]
Closing. After >3mo and no submitter feedback.
