### ISSUE TITLE
API Spider call not taking ImportedUrls as input

### ISSUE THREAD

**Issue by breakthesec** [zaproxy/zaproxy#4202]
Hi,

I imported set of urls in zap using API and tried to run the spider using API.  However, the spider is not taking the imported urls as input, only the scanner use it for finding vulnerability.  But, the scanner checks only the url and not processing any Forms inside the given url. 

If you right click and run the spider from GUI, it is taking the imported urls as input.  

Note: When i unchecked the "recurse" option in GUI and run the spider, it didn't take the imported urls as input.  So i tried to pass different values to recurse parameter in API(like "yes",1,true,True..),  but still it didn't do.

**Comment by kingthorin** [comment]
Please provide further details, what API endpoints are you using and with what parameters? (When importing, when spidering, etc)

In general it is best to get things working as you intent to in the GUI then recreate that flow with the API. You can even run in GUI mode and execute with API then you can see what's going on.

If all of you're endpoints are within a part of the path (eg: example.com/API/endpoint1, etc) and you're starting point is example.com or /API then yes you have to recurse as the targets are "below" the starting point.

**Comment by breakthesec** [comment]
I am not using any API clients.  The problem: The spider is taking Imported URLs as input when i do it in GUI but not in the API

**Comment by psiinon** [comment]
@breakthesec you've told us that is works via the UI but not the API, so you must be using the API. We need to know which API calls you are using - it _could_ be a bug in ZAP but its possible that you are using the API incorrectly. Until we know what API calls you are making we cant tell which it is.

**Comment by breakthesec** [comment]
I meant i am not using any API clients(like zap-api-java library), i am using the ZAP API from the browser.

**This is API call i made for spidering(i gave various input to recurse param):**
http://127.0.0.1:8081/JSON/spider/action/scan/?zapapiformat=JSON&apikey=[API_KEY]&formMethod=GET&url=http://172.18.0.80:8080/JavaVulnerableLab/&maxChildren=&recurse=&contextName=&subtreeOnly=

View the crawled URLs in:
http://127.0.0.1:8081/JSON/spider/view/fullResults/?zapapiformat=JSON&apikey=[API_KEY]&formMethod=GET&scanId=0

(or)

http://127.0.0.1:8081/JSON/spider/view/allUrls/?zapapiformat=JSON&apikey=[API_KEY]&formMethod=GET

**Comment by thc202** [comment]
If the spider (through the API) is not picking the existing URLs it means the starting URL does not match an existing URL (under Sites node). Are you also importing (or accessing) `http://172.18.0.80:8080/JavaVulnerableLab/`?

**Comment by breakthesec** [comment]
@thc202 Hi,  yes i imported urls under the JavaVulnerableLab only .

**For example, this is the imported URLs:**
http://172.18.0.80:8080/JavaVulnerableLab/vulnerability/Injection/xpath_login.jsp
http://172.18.0.80:8080/JavaVulnerableLab/vulnerability/idor/download.jsp
http://172.18.0.80:8080/JavaVulnerableLab/vulnerability/xss/search.jsp

**and this is the URLs i gave for spidering:**
http://172.18.0.80:8080/JavaVulnerableLab/

**It is working in GUI(right click and select spider) but not in API(from the browser).**

**Comment by kingthorin** [comment]
But was http://172.18.0.80:8080/JavaVulnerableLab/ itself ever visited or imported?

**Comment by breakthesec** [comment]
Yes, i have accessed the main url( http://172.18.0.80:8080/JavaVulnerableLab/) using the '/core/action/accessUrl/' call.   Now also tried to include this in import url list, still not working.

**Comment by thc202** [comment]
Yes, there's a usability issue here. The spider API is trying to obtain (always) a GET node instead of the "directory" as such it does not include the other child nodes/paths.

**Comment by thc202** [comment]
Tweaked the title to reflect better the issue.
