### ISSUE TITLE
Error: Export Report xhtml not generating report  (official ZAP Jenkins plugin)

### ISSUE THREAD

**Issue by VadimGulich** [zaproxy/zaproxy#4206]
### Generating not valid xhtml 
ZAP: 2.6.0/2.7.0 
Export Report: last build
official ZAP Jenkins plugin: last build
![image](https://user-images.githubusercontent.com/12964120/34513602-aff49ade-f071-11e7-9d46-be43c27ff0d1.png)
![image](https://user-images.githubusercontent.com/12964120/34513644-ea5f7d92-f071-11e7-81f2-4d55659f662b.png)

**Comment by psiinon** [comment]
@VadimGulich how are you generating this report?

**Comment by VadimGulich** [comment]
Generate Reports in jenkins
![image](https://user-images.githubusercontent.com/12964120/34514773-a0a3efc0-f077-11e7-9cbb-a8a445158e2c.png)

**Comment by thc202** [comment]
Are the other formats (JSON/XHTML) correct? Is there any error/exception in the output?

What are the contents of the file `merge.xml.xsl` (in `xml` dir under ZAP home)?

**Comment by VadimGulich** [comment]
@thc202 JSON/XML report correct

**contents of the file merge.xml.xsl**
<?xml version="1.0" encoding="UTF-8"?>

<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output method="XML" version="1.0"  encoding="UTF-8" indent="YES" />
	<xsl:key name="KeyItem" match="AlertItem" use="concat(ancestor::Sites/Name, '|', PluginID)" />

	<xsl:template match="/Report">
		<Report>
			<xsl:copy-of select="@*" />
			<Title>
				<xsl:value-of select="Title"/>
			</Title>
			<For>
				<xsl:value-of select="For"/>
			</For>
			<By>
				<xsl:value-of select="By"/>
			</By>
			<ScanDate>
				<xsl:value-of select="ScanDate"/>
			</ScanDate>
			<ScanVersion>
				<xsl:value-of select="ScanVersion"/>
			</ScanVersion>
			<ReportDate>
				<xsl:value-of select="ReportDate"/>
			</ReportDate>
			<ReportVersion>
				<xsl:value-of select="ReportVersion"/>
			</ReportVersion>
			<Desc>
				<xsl:value-of select="Desc"/>
			</Desc>
			<xsl:for-each select="Sites">
				<Sites>
					<xsl:copy-of select="@*" />
					<Host>
						<xsl:value-of select="Host"/>
					</Host>
					<Name>
						<xsl:value-of select="Name"/>
					</Name>
					<Port>
						<xsl:value-of select="Port"/>
					</Port>
					<SSL>
						<xsl:value-of select="SSL"/>
					</SSL>
					<Alerts>
						<xsl:for-each select="Alerts/AlertItem[generate-id() = generate-id(key('KeyItem', concat(ancestor::Sites/Name, '|', PluginID))[1])]">  
							<xsl:sort select="RiskCode" data-type="number" order="descending"/>
							<xsl:sort select="Alert"/>
							
							<AlertItem>
								
								<Alert>
									<xsl:value-of select="Alert"/>
								</Alert>
								<RiskCode>
									<xsl:value-of select="RiskCode"/>
								</RiskCode>
								
								<PluginID>
									<xsl:value-of select="PluginID"/>
								</PluginID>
								
								<RiskDesc>
									<xsl:value-of select="RiskDesc"/>
								</RiskDesc>
								<Desc>
									<xsl:value-of select="Desc"/>
								</Desc>
								<Solution>
									<xsl:value-of select="Solution"/>
								</Solution>
								<Reference>
									<xsl:value-of select="Reference"/>
								</Reference>
								<ItemCount>
									<xsl:value-of select="count(key('KeyItem', concat(ancestor::Sites/Name, '|', PluginID)))"/>
								</ItemCount>
								<xsl:for-each select="key('KeyItem', concat(ancestor::Sites/Name, '|', PluginID))">
									<Item>
										<URI>
											<xsl:value-of select="URI"/>
										</URI>
										<Confidence>
											<xsl:value-of select="Confidence"/>
										</Confidence>
										<Param>
											<xsl:value-of select="Param"/>
										</Param>  
										<Attack>
											<xsl:value-of select="Attack"/>
										</Attack>          
										<Evidence>
											<xsl:value-of select="Evidence"/>
										</Evidence>
										<OtherInfo>
											<xsl:value-of select="OtherInfo"/>
										</OtherInfo>
										<RequestHeader>
											<xsl:value-of select="RequestHeader"/>
										</RequestHeader>
										<RequestBody>
											<xsl:value-of select="RequestBody"/>
										</RequestBody>
										<ResponseHeader>
											<xsl:value-of select="ResponseHeader"/>
										</ResponseHeader>
										<ResponseBody>
											<xsl:value-of select="ResponseBody"/>
										</ResponseBody>
									</Item>
								</xsl:for-each>
								<CWEID>
									<xsl:value-of select="CWEID"/>
								</CWEID>
								<WASCID>
									<xsl:value-of select="WASCID"/>
								</WASCID>
							</AlertItem>
						</xsl:for-each>
					</Alerts>
				</Sites>
			</xsl:for-each>
		</Report>
	</xsl:template>
</xsl:stylesheet>

**Comment by thc202** [comment]
Yeah, that one looks correct. How about the file `report.html.xsl` (in the same dir), does it have the same contents as https://github.com/zaproxy/zap-extensions/blob/68e2365fca616566287ffa13090123f12e001567/src/org/zaproxy/zap/extension/exportreport/files/xml/report.html.xsl ?

**Comment by VadimGulich** [comment]
No, report.html.xsl  was 
https://github.com/zaproxy/zaproxy/blob/develop/src/xml/report.html.xsl

**Comment by VadimGulich** [comment]
I replaced with  https://github.com/zaproxy/zap-extensions/blob/68e2365fca616566287ffa13090123f12e001567/src/org/zaproxy/zap/extension/exportreport/files/xml/report.html.xsl
 The report is generated, thanks

**Comment by thc202** [comment]
Cool, we should change the file name to avoid clashes :/ Although that also means the home and installation dir are the same? It's recommended to user other dir.

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#1231.
