### ISSUE TITLE
Suggest removing the Password Autocomplete passive scan rule

### ISSUE THREAD

**Issue by brittag** [zaproxy/zaproxy#4215]
(I'd like to post the following comment as a reply to the ["Password autocomplete passive scan rule implementation" thread in the OWASP ZAP User Group](https://groups.google.com/forum/#!msg/zaproxy-users/gqQU6OH36j4/46DlW6MfEAAJ), but my workplace restricts participation in Google Groups, and we're allowed to use GitHub. I hope it's still helpful to post here! Feel free to cross-post it there.)

I suggest reviewing the Password Autocomplete passive scan rule again, and I suggest removing it. The major browsers (Firefox, Chrome, IE, Safari) have ignored this “autocomplete=off” attribute for password fields since 2014, so it doesn’t have meaningful security impact if you implement it. The [OWASP Testing Guide for "Testing for Vulnerable Remember Password"](https://www.owasp.org/index.php/Testing_for_Vulnerable_Remember_Password_(OTG-AUTHN-005)) says: "Since early 2014 most major browsers will override any use of autocomplete="off" with regards to password forms and as a result previous checks for this are not required and recommendations should not commonly be given for disabling this feature."

Here's why reducing false positives is helpful for my use case: my team uses ZAP as part of fulfilling U.S. federal government system security compliance requirements. This means we run a default ZAP ruleset, then write formal justifications for any scan findings we don’t plan to fix (such as false positives), then get those justifications approved by our compliance reviewers. So it's helpful for us to support reducing false positives upstream when appropriate. :)

Thank you!

**Comment by kingthorin** [comment]
@brittag we're always happy to have feedback from users, however it comes. (You've explained a working environment limitation which seems reasonable to me.)

Given recent happenings, browser functionality/handling of the attribute, etc. I'm good with removal of this rule.

@psiinon @thc202 do you agree?

**Comment by thc202** [comment]
Yes, +1.

**Comment by psiinon** [comment]
yep, +1

**Comment by brittag** [comment]
Hooray, thank you all!

**Comment by thc202** [comment]
Released in version 22 of Passive scanner rules add-on.
