### ISSUE TITLE
‘Failed to attack the URL: received a 403 response code’?

### ISSUE THREAD

**Issue by HarmsSingh** [zaproxy/zaproxy#4216]
Please help trying to run Owasp Zap 2.7 and error received?

**Comment by kingthorin** [comment]
Please don't ask questions as issues - the ZAP User Group https://groups.google.com/group/zaproxy-users is much better place for user questions.

Also when you ask over there please be much more specific and detailed.

**Comment by HarmsSingh** [comment]
This is the error I am receiving - '‘Failed to attack the URL: received a 403 response code’? within Owasp Zap can you assist?

**Comment by thc202** [comment]
For the record, this is being handled in the users group:
https://groups.google.com/d/topic/zaproxy-users/ylUUu53YcH0/discussion
