### ISSUE TITLE
Unicode payload made parosproxy lib break

### ISSUE THREAD

**Issue by acaetano** [zaproxy/zaproxy#4222]
In a recent assessment, a payload containing the unicode character with code A6 ("¦") in a Fuzzer session made the parosproxy http lib completely freak out and not make the request. 

I even tried to put other chars before and after it, but the result was the same.

![image](https://user-images.githubusercontent.com/4494413/34615063-a037e966-f21a-11e7-950b-08541dcbeac8.png)

**Comment by thc202** [comment]
This has the same cause as #4127. Merging into that one.
