### ISSUE TITLE
owasp/zap2docker-weekly Swing Interface / Create Users Context (Add User) Not Working

### ISSUE THREAD

**Issue by GregoryPerry706** [zaproxy/zaproxy#4227]
Pulled the weekly ZAP Docker tonight, using the Webswing interface.

Set up a custom context with forms-based authentication for authenticated scanning and spidering, but when I go to the Users tab to create a user to populate the Login Request POST Data with, the Add button does not work.

**Comment by thc202** [comment]
This is because of an issue in Webswing, at the moment there's no (main) release with a fix. Merging into #3553.

**Comment by speedyuk** [comment]
Hi, Sorry I'm not a coder but I just found and started to try and use ZAProxy in the Docker environment. I followed an online video tutorial on how to set it up to attack DVWA. Unfortunately I hit the same issue with not being able to bring up the add user dialogue. This I understand throws up a Java error in the Webswing environment. Could someone please say what the latest news is regarding a new build being released that fixes this problem. Is anyone in dialogue with Webswing?  Many Thanks Cliff

**Comment by thc202** [comment]
Answered in #3553.
