### ISSUE TITLE
owasp/zap2docker-weekly Swing Interface / Fuzzer Doesn't Work

### ISSUE THREAD

**Issue by GregoryPerry706** [zaproxy/zaproxy#4228]
Pulled the most recent Docker weekly image tonight, Webswing interface.

Right click -> Attack -> Fuzz does not work, nor does Menu -> Tools -> Fuzz

Is the weekly image so bleeding edge that lots of functionality isn't working? Should I be using a more conservative image instead of weekly builds?

**Comment by thc202** [comment]
Merging into #3553, same problem as mentioned in #4227.
