### ISSUE TITLE
False Positive: SQL Injection (on pages where a query string has no impact)

### ISSUE THREAD

**Issue by brittag** [zaproxy/zaproxy#4231]
This may be a duplicate of https://github.com/zaproxy/zaproxy/issues/4169 or https://github.com/zaproxy/zaproxy/issues/3662, but I’ll start a new thread since it may be different.

We get a SQL Injection alert on our instance of [Kibana](https://github.com/elastic/kibana), with the following details:

```
<alertitem>
  <pluginid>40018</pluginid>
  <alert>SQL Injection</alert>
  <name>SQL Injection</name>
  <riskcode>3</riskcode>
  <confidence>2</confidence>
  <riskdesc>High (Medium)</riskdesc>
  <desc>&lt;p&gt;SQL injection may be possible.&lt;/p&gt;</desc>
  <instances>
  <instance>
  <uri>https://EXAMPLE.COM/app/kibana?query=query+AND+1%3D1+--+</uri>
  <method>GET</method>
  <param>query</param>
  <attack>query AND 1=1 -- </attack>
  </instance>
  <instance>
  <uri>https://EXAMPLE.COM/es_admin/.kibana/index-pattern/_search?stored_fields=+AND+1%3D1+--+</uri>
  <method>POST</method>
  <param>stored_fields</param>
  <attack> AND 1=1 -- </attack>
  </instance>
  <instance>
  <uri>https://EXAMPLE.COM/es_admin/.kibana/_mapping/*/field/_source?_=1515008538062%27+AND+%271%27%3D%271%27+--+</uri>
  <method>GET</method>
  <param>_</param>
  <attack>1515008538062&apos; AND &apos;1&apos;=&apos;1&apos; -- </attack>
  </instance>
  </instances>
  <count>3</count>
  <solution>&lt;p&gt;Do not trust client side input, even if there is client side validation in place.  &lt;/p&gt;&lt;p&gt;In general, type check all data on the server side.&lt;/p&gt;&lt;p&gt;If the application uses JDBC, use PreparedStatement or CallableStatement, with parameters passed by &apos;?&apos;&lt;/p&gt;&lt;p&gt;If the application uses ASP, use ADO Command Objects with strong type checking and parameterized queries.&lt;/p&gt;&lt;p&gt;If database Stored Procedures can be used, use them.&lt;/p&gt;&lt;p&gt;Do *not* concatenate strings into queries in the stored procedure, or use &apos;exec&apos;, &apos;exec immediate&apos;, or equivalent functionality!&lt;/p&gt;&lt;p&gt;Do not create dynamic SQL queries using simple string concatenation.&lt;/p&gt;&lt;p&gt;Escape all data received from the client.&lt;/p&gt;&lt;p&gt;Apply a &apos;whitelist&apos; of allowed characters, or a &apos;blacklist&apos; of disallowed characters in user input.&lt;/p&gt;&lt;p&gt;Apply the principle of least privilege by using the least privileged database user possible.&lt;/p&gt;&lt;p&gt;In particular, avoid using the &apos;sa&apos; or &apos;db-owner&apos; database users. This does not eliminate SQL injection, but minimizes its impact.&lt;/p&gt;&lt;p&gt;Grant the minimum database access that is necessary for the application.&lt;/p&gt;</solution>
  <otherinfo>&lt;p&gt;The page results were successfully manipulated using the boolean conditions [query AND 1=1 -- ] and [query AND 1=2 -- ]&lt;/p&gt;&lt;p&gt;The parameter value being modified was NOT stripped from the HTML output for the purposes of the comparison&lt;/p&gt;&lt;p&gt;Data was returned for the original parameter.&lt;/p&gt;&lt;p&gt;The vulnerability was detected by successfully restricting the data originally returned, by manipulating the parameter&lt;/p&gt;</otherinfo>
  <reference>&lt;p&gt;https://www.owasp.org/index.php/Top_10_2010-A1&lt;/p&gt;&lt;p&gt;https://www.owasp.org/index.php/SQL_Injection_Prevention_Cheat_Sheet&lt;/p&gt;</reference>
  <cweid>89</cweid>
  <wascid>19</wascid>
  <sourceid>1</sourceid>
</alertitem>
```

I suggest ignoring the first item (`https://EXAMPLE.COM/app/kibana?query=query+AND+1%3D1+--+`) because that's a search results page, and it’s probably difficult to auto-detect whether the search results are expected or the result of a successful injection attack.

For the second item (`https://EXAMPLE.COM/es_admin/.kibana/index-pattern/_search?stored_fields=+AND+1%3D1+--+`), that URL returns the following expected JSON file (response code 200, content type `application/json`) because that query has no results:

```
{"took":1,"timed_out":false,"_shards":{"total":1,"successful":1,"failed":0},"hits":{"total":8,"max_score":1.0,"hits":[{"_index":".kibana","_type":"index-pattern","_id":"logs-app","_score":1.0},{"_index":".kibana","_type":"index-pattern","_id":"logs-platform","_score":1.0},{"_index":".kibana","_type":"index-pattern","_id":"logs-app-2017.08.*","_score":1.0},{"_index":".kibana","_type":"index-pattern","_id":"logs-platform-*","_score":1.0},{"_index":".kibana","_type":"index-pattern","_id":"logs-app-*","_score":1.0},{"_index":".kibana","_type":"index-pattern","_id":"logs-*","_score":1.0},{"_index":".kibana","_type":"index-pattern","_id":"logs-platform*","_score":1.0},{"_index":".kibana","_type":"index-pattern","_id":"logs-app*","_score":1.0}]}}
```

You get the same JSON file if you visit `https://EXAMPLE.COM/es_admin/.kibana/index-pattern/_search?stored_fields=+AND+1%3D2+--+` or a URL without an attempted attack (like `https://EXAMPLE.COM/es_admin/.kibana/index-pattern/_search?stored_fields=ZAP`).

The third item is similar to the second item. `https://EXAMPLE.COM/es_admin/.kibana/_mapping/*/field/_source?_=1515008538062%27+AND+%271%27%3D%271%27+--+` returns the following JSON file because that query has no results:

```
{".kibana":{"mappings":{"index-pattern":{"_source":{"full_name":"_source","mapping":{}}},"visualization":{"_source":{"full_name":"_source","mapping":{}}},"search":{"_source":{"full_name":"_source","mapping":{}}},"timelion-sheet":{"_source":{"full_name":"_source","mapping":{}}},"config":{"_source":{"full_name":"_source","mapping":{}}},"dashboard":{"_source":{"full_name":"_source","mapping":{}}},"url":{"_source":{"full_name":"_source","mapping":{}}}}}}
```

A URL without an attempted attack (like `https://EXAMPLE.COM/es_admin/.kibana/_mapping/*/field/_source?_=ZAP`) returns the same file.

Unfortunately the [public demo of Kibana](https://demo.elastic.co/) returns different results for similar URLs - not sure if it's because that instance is on a different version, or because they've locked down the demo in some way.

Thank you!

**Comment by kingthorin** [comment]
For the example in which you provided full alert details if you check the "otherinfo" you can see that injecting `AND 1=1 --` (a always true condition) produced a different result vs. injecting `AND 1=2 --` (an always false condition).

**Comment by kingthorin** [comment]
@brittag are you still able to look into this?
> @brittag For the example in which you provided full alert details if you check the "otherinfo" you can see that injecting `AND 1=1 --` (a always true condition) produced a different result vs. injecting `AND 1=2 --` (an always false condition).

**Comment by brittag** [comment]
Thanks for checking in! Generally what's happening for each of our false positives for SQL Injection is that it's triggering on a search results page of some kind, which is expected to provide different results for different queries, without that being a vulnerability.

I'm not sure how to demonstrate this with a good public-facing test case that you can use to try the scan to get more insight, so I'll go back to my team and see if we can figure something out for you.

**Comment by NickStefan** [comment]
whats the recommended way of dealing with this? 

we have a similar issue, where a route that totally ignores querystrings is returning JSON, with the querystrings intact, and the test is incorrectly raising an alert on SQL injection.

are we expected to always strip querystrings on routes not using them?

**Comment by NickStefan** [comment]
"the parameter results were not stripped from the HTML". it returns JSON? If anyone can provide clarification or help me understand this bug, would be greatly appreciated. 

https://user-images.githubusercontent.com/6600333/50864502-76f37b80-135f-11e9-8057-d412000ae8ca.png

![image](https://user-images.githubusercontent.com/6600333/50940597-ca88c680-143e-11e9-8040-6a21d7aee445.png)

**Comment by kingthorin** [comment]
This may be significantly relieved by some changes which made the addition of query params optional and defaulted to off as of mid-Sept 2018 weekly releases (and 2.8.0 of whatever the next full release ends up being).
https://mobile.twitter.com/kingthorin_rm/status/1041855009263108097
