### ISSUE TITLE
Request for ZAP Fuzzer - Ability to Load Payloads from File

### ISSUE THREAD

**Issue by thiscantbetaken** [zaproxy/zaproxy#4242]
In the ZAP Fuzzer, the Strings option seems to only allow pasted payloads. It would be super handy to allow external file loading for this option.

**Comment by thc202** [comment]
Doesn't File payload allow achieve that? (The payloads can be edited after adding them.)
https://github.com/zaproxy/zap-core-help/wiki/HelpAddonsFuzzPayloads

**Comment by thiscantbetaken** [comment]
Ah. My bad, I had been using only the Strings option. Thanks for pointing that out.

**Comment by thc202** [comment]
No worries. Let us know if that way is fine (or if it can be improved).
