### ISSUE TITLE
Request for ZAP Active Scanner Reflected Payload Reporting

### ISSUE THREAD

**Issue by thiscantbetaken** [zaproxy/zaproxy#4243]
I haven't been able to figure out a way of reporting reflected payloads in ZAP other than the Fuzzer report output. It would be very helpful if reflected parameters from active scanning were reported in the Issues tab.

**Comment by thc202** [comment]
Just to be clear, this is not an enhancement request for the fuzzer but for the active scanner?

**Comment by thiscantbetaken** [comment]
Yes this would be for the Active Scanner; the Fuzzer reports reflected payloads properly but I haven't yet figured out a way of reporting that from Active Scanner in the issues tab, unless the Active Scanner isn't actively looking for reflected payloads?

**Comment by thc202** [comment]
It depends on the active scanners, XSS (Reflected/Persistent) [1] and DOM XSS [2] do that but both try to check if there's a real issue or not.

[1] https://github.com/zaproxy/zap-core-help/wiki/HelpAddonsAscanrulesAscanrules#cross-site-scripting-reflected
[2] https://github.com/zaproxy/zap-extensions/wiki/HelpAddonsDomxssDomxss

**Comment by thiscantbetaken** [comment]
Hmm I am not picking up any reflected queries during Active Scanning, but I have all of these reflection rules enabled. I get a ton of reflected alerts when using Burp Suite but haven't seen one yet in ZAP proxy. Is there a more in-depth refinement/configuration to the Active Scanner reflection rules beyond the reflection rule being enabled?

**Comment by kingthorin** [comment]
You can adjust the strength of tge scan rule in the policy, however tgat will increase requests made and scan time.

**Comment by thiscantbetaken** [comment]
I have everything cranked up to Insane with release reflection rules, but have yet to see a single reflection alert in the Issues tab while Burp Suite is picking up reflections all over the place.

________________________________

**Comment by kingthorin** [comment]
Without specifics there's not much we can add or address at this point.

**Comment by psiinon** [comment]
@thiscantbetaken are these real vulnerabilities? Just reflecting a payload is not necessarily a vulnerability.
If some of them are vulnerabilities then can you give us some sanitized examples?

**Comment by kingthorin** [comment]
@thiscantbetaken are you able to provide further details?

**Comment by thiscantbetaken** [comment]
I've been swamped the last few days. I will see if I can take a look at it
this weekend. I have been trying to avoid re-installing Burp to be honest.

**Comment by kingthorin** [comment]
@thiscantbetaken are you able to provide further details or can this issue be closed?

**Comment by kingthorin** [comment]
No further input for months. Closing,
