### ISSUE TITLE
Enhance XXE Scanner

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#4249]
Once the 2.8 core is available in the extensions repo. Modify the [XXE scanner](https://github.com/zaproxy/zap-extensions/blob/beta/src/org/zaproxy/zap/extension/ascanrulesBeta/XXEPlugin.java) to leverage them (similar to the [LDAPi scanner](https://github.com/zaproxy/zap-extensions/blob/3cd645c3551b893a000770ce67fa183b23d1d858/src/org/zaproxy/zap/extension/ascanrulesAlpha/LDAPInjection.java#L185-L195)). XXE should be tried on multipart form posts file content params.

<sub>Ref: https://github.com/zaproxy/zaproxy/pull/4208</sub>

**Comment by kingthorin** [comment]
https://twitter.com/owasp_juiceshop/status/950785748193677312

Spoilers (click at your own risk) > https://github.com/bkimminich/juice-shop/search?q=xxe&type=

**Comment by thc202** [comment]
The scanner could use the variant directly (i.e. copy/adapt the code to the add-on) in the meantime.

**Comment by kingthorin** [comment]
Closing, this seems to be a duplicate of #1190 which I just discovered.
