### ISSUE TITLE
ZAP Authentication not working

### ISSUE THREAD

**Issue by Akumary** [zaproxy/zaproxy#4263]
Trying to use ZAP 2.7.0 for spidering against my internal javascript based website. I used AJAX spider but I see that it is entering random username even after doing the proper configuration. Also, tried using ZEST based recording for authentication but same issue. I did following:

1) Launched firefox from ZAP and logged into Website. Now, I can see my website under the "Sites" tab.
2) Defined the new context and added my site into it.
3) Selected the POST Login request for my site and did right click and selected as "Flag as Context" / " Form-based Auth Login request"
4) Configured the Username and Password parameter correctly under "Authentication" in the context.
5) Set the Log in and Log out indicator
5) Created a new user with valid username and password (Same as what was used in the POST Login, mentioned in Step 3) under "Users" option in the context

After doing above steps, tried to run following:

1) Ran "Ajax Spider" using the above context and the user. I see ZAP launching firefox then it opens my website login page but enters a random username and then eventually login fails and the spider stops. Expected it to use the the Username and Password configured in the above steps and crawl further after successful login.

2) Just to check if ZAP is able to spider, I ran the "Spider" (normal Spider option) and I see it uses "ZAP" as username and password both in the POST Login request and eventually login fails and it is not able to spider further. Expected it to use the Username and Password configured in the above steps as "Spider" was run as this user in the context.

Please let me know if i'm missing something here or is there a genuine issue with ZAP.
Looking forward for the help. Thanks.

**Comment by kingthorin** [comment]
Closing, user already started a User Group thread, which is the proper place for questions.

https://groups.google.com/forum/m/?pli=1#!topic/zaproxy-users/whjTCLm_id4
