### ISSUE TITLE
Zap2Docker API scan - how to pass override Host parameter (similar to GUI)

### ISSUE THREAD

**Issue by FastNinja** [zaproxy/zaproxy#4269]
Hi,
Great tool!

Trying to ran ZAP scanner using OpenAPI specification.
Using GUI all works good - as I can select URL for `swagger.json` file and then I can specify host name (www.myapi.com).
See the picture below:
![image](https://user-images.githubusercontent.com/13673826/34975271-2cdba0f6-fae5-11e7-91f9-30b4a3884c0a.png)

However, when running
```
docker run -t owasp/zap2docker-weekly zap-api-scan.py -t \
        https://www.myapi.com/swagger/v1/swagger.json -f openapi
```
I could not find a way to pass the second parameter (Override Host) ..

The reason Host parameter is required - the `swagger.json` file does not know where it is hosted so it does not contain `host` field.

P.S. tried both `docker run -t owasp/zap2docker-weekly` and `docker run -t owasp/zap2docker-stable`. When running with `-d` flag I can see the issue:
```018-01-16 06:51:38,322 Took 13 seconds
2018-01-16 06:51:38,344 Import OpenAPI URL https://myapi.com/swagger/v1/swagger.json
2018-01-16 06:51:41,884 Number of Imported URLs: 4
2018-01-16 06:51:41,884 Import warnings: [u'Failed to access URL: https://null/operations?
filter.code=filter.code&filter.resourceTypeId=filter.resourceTypeId : 

java.net.UnknownHostException : null', u'Failed to access URL: https://null/operations : 

java.net.UnknownHostException : null', u'Failed to access URL: https://null/permissions?


filter.actorId=filter.actorId&filter.resourceId=filter.resourceId&include=none : 

java.net.UnknownHostException : null', u'Failed to access URL: https://null/permissions : 

java.net.UnknownHostException : null', u'Failed to access URL: https://null/permissions/id : 
java.net.UnknownHostException : null', u'Failed to access URL: https://null/resources : 


java.net.UnknownHostException : null', u'Failed to access URL: https://null/resources/id : 
java.net.UnknownHostException : null', u'Failed to access URL: https://null/resources/id : 
java.net.UnknownHostException : null', u'Failed to access URL:
```

**Comment by FastNinja** [comment]
I observe similar behavior if when using GUI I do not fill `Override Host` field

**Comment by FastNinja** [comment]
Just digging a bit more into OpenAPI - it says :
```
If host is not specified, it is assumed to be the same host where the API documentation is being served.
```
https://swagger.io/docs/specification/2-0/api-host-and-base-path/

However it seems that zap-extension for OpenAPI assumes that host must be there

**Comment by FastNinja** [comment]
It looks like https://github.com/zaproxy/zap-extensions/pull/905 this commit added HostOverride - so it is relevant... could it be that host override is not exposed via `zap-api-scan.py`?

**Comment by thc202** [comment]
Yes, that's not yet exposed through the script.

We also need to fix the issue in the OpenAPI add-on, which should default to host of the URL.

**Comment by FastNinja** [comment]
I was trying to find OpenApi addon source code but only found Jar file on GitHub repo.
I don’t mind creating s Pull Request to either expose Host parameter on the script or to fix addon

**Comment by thc202** [comment]
The source of the add-on is in the alpha branch:
https://github.com/zaproxy/zap-extensions/tree/alpha/src/org/zaproxy/zap/extension/openapi

FYI, I already have the changes in place, still checking everything is correct but should be ready today.

**Comment by FastNinja** [comment]
@thc202 great job! it works!

**Comment by lgufc** [comment]
@thc202 thank you for fixing that
I have a similar problem, but I'm using yaml file with swagger spec. I need to override host in that yaml file from cmd. Option `-O` is applicable to `target_url` case, not `target_file`
I also tried to use `-z "-config formhandler.fields.field\(0\).fieldId=host -config formhandler.fields.field\(0\).value=my_host.net -config formhandler.fields.field\(0\).enabled=true"` but it doesn't seem to be working
Could someone nudge me to the right direction?
Thanks in advance
