### ISSUE TITLE
Null pointer exception when scanning Session ID in URL

### ISSUE THREAD

**Issue by YangYongZhi** [zaproxy/zaproxy#4274]
I found an exception when the zaproxy is executing a passive scan, the exception message like this:
`2018-01-16 09:52:14,990 [ZAP-PassiveScanner] ERROR PassiveScanThread - Scanner Session ID in URL Rewrite failed on record 510490 from History table: GET http://static.sweet.com/kayak-project/??medusa/dist/medusa/pages/crowdlist/crowdlist.tpl?t=partnerpartner201801120930
java.lang.NullPointerException
	at org.zaproxy.zap.extension.pscanrules.TestInfoSessionIdURL.scanHttpResponseReceive(TestInfoSessionIdURL.java:169)
	at org.zaproxy.zap.extension.pscan.PassiveScanThread.run(PassiveScanThread.java:148)
`

I think that because may be missing a null point checking here:
`HttpSessionsParam sessionOptions = options.getParamSet(HttpSessionsParam.class);
        List<String> sessionIds = sessionOptions.getDefaultTokensEnabled();`

It seem that the "sessionOptions" maybe is a null object, so could I check it?

**Comment by thc202** [comment]
Yeah, we need to check that's not `null` before using it (that's `null` when the `ExtensionHttpSessions` is not enabled).

Which version (or revision) are you using and which starting options?

**Comment by thc202** [comment]
(And, yes, please, go ahead with a PR.)

**Comment by YangYongZhi** [comment]
I build this project with the master branch.

**Comment by YangYongZhi** [comment]
My start option :
nohup ./zap.sh -daemon -port 9797 -host 192.168.8.102 -config api.key=JAXMv3A3T -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true -experimentalDb -lowmem -nostdout &

**Comment by YangYongZhi** [comment]
Version : the newest version, ZAP_Dev Build_Core.tar.gz

**Comment by YangYongZhi** [comment]
And zap-extensions branch is master.

**Comment by thc202** [comment]
Thanks for the details!

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#1278.
