### ISSUE TITLE
Warn if a # is specified in a break point URL

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#4277]
If someone includes a URL fragment in a contains match then its probably not going to work as the fragment is not sent by the browser.
https://security.stackexchange.com/questions/177816/how-to-intercept-xmlhttprequest-with-owaps-zap/177825#177825

**Comment by varshav21** [comment]
I am a beginner and I would like to take on the issue.Can anybody give me suggestions on how to approach this issue?

**Comment by psiinon** [comment]
@varshav21 

1. Find the dialog in the UI which allows you to add break points
1. Search for some of the text in the dialog in the src folder
1. Make a note of the i18n key
1. Search for the i18n key in the src folder

You'll hopefully now have found the relevant code - have you got that far yet?

**Comment by varshav21** [comment]
Thank you so much for your response, I believe I have found the relevant code.

**Comment by psiinon** [comment]
Where have you found the text in the dialog? Can you post a link to it here?

**Comment by kingthorin** [comment]
> I am stuck on finding i18n key, can you please explain how do I do that?

All strings in the ZAP UI are internationalized (translated) into various other languages. These appear in the various messages.properties files. 

So if you take a few unique word from the UI (such as those displayed in the add breakpoint dialog or panel), search the code base for it, you'll find a messages.properties entry like: `core.view.add.breakpoint.label=Add Breakpoint` (or whatever....thats a fictitious example). You can then take the key `core.view.add.breakpoint.label` and search the code base for its use and find the java source code files it's used in.

**Comment by varshav21** [comment]
I think this is the i18n key
break.api.action.addHttpBreakpoint=Adds a custom HTTP breakpont. The string is the string to match. Location may be one of\: url, request_header, request_body, response_header or response_body. Match may be\: contains or regex. Inverse (match) may be true or false. Lastly, ignorecase (when matching the string) may be true or false.
I've found the key in  zaproxy/src/org/zaproxy/zap/extension/brk/BreakAPI.java

**Comment by psiinon** [comment]
Thats for the API, which isnt what you want in this case.
You need to be very specific when searching for strings - I cant see "Adds a custom HTTP breakpont" in the desktop UI anywhere, its only in the API UI.
A better string to look for is the title of the popup: "Add Break Point"

**Comment by varshav21** [comment]
I'm very sorry for the late reply and I've found the relevant code in  zaproxy/src/org/zaproxy/zap/extension/brk/impl/http/BreakAddEditDialog.java . How do I proceed further?

**Comment by thc202** [comment]
Cool, you now need to add the fragment check in the method that's doing the validations.

**Comment by thc202** [comment]
Fixed in #4349.
