### ISSUE TITLE
Reopen websocket connection to (re)send messages

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#4290]
As per: https://twitter.com/w3af/status/954441602960850944

> Just found something that would be a nice-to-have in @zaproxy's websocket re-send window: creating a new connection.
> It doesn't seem to be possible to re-send a ws message once the connection in which it was sent is closed.
> @zaproxy could just re-open the connection and send it
>

**Comment by juhakivekas** [comment]
> It doesn't seem to be possible to re-send a ws message once the connection in which it was sent is closed.

One can resend an old message in a newer channel (connection) by selecting the new connection in the repeater. If there is no appropriate connection, then it actually does make sense to reopen one. Of course, this probably refers to a case where the user does not want to manually re-open a socket.

It's starting to be quite common to have authenticated websockets (JWT, uuid token, etc.) so this might not work in all cases. Sounds useful to have for fuzzing.

**Comment by psiinon** [comment]
Yeah, I think this is the case where there is no newer active connection, so the request is to open a new connection.

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#1618.

**Comment by thc202** [comment]
Released in version 18 of WebSockets add-on.
