### ISSUE TITLE
Promote Image Location & Privacy Scanner to release

### ISSUE THREAD

**Issue by veggiespam** [zaproxy/zaproxy#4295]
I would like to promote my Image Location & Privacy Scanner to the release tract.  It has been around in the alpha channel for a few years and there has been no severe issues in either ZAP or Burp.  I feel it is mature enough to promote to v1.0 and to the main ZAP channel.

Both @kingthorin and someone from Portswigger assisted over the last year in getting this to v1.0.  Currently, the ZAP alpha channel contains v0.4 along with most of the patches for v1.0.  There are only a few minor extras since then, mostly cosmetic.

The v1.0 branch is here, https://github.com/veggiespam/ImageLocationScanner/tree/v1.0 , I would like to begin the promotion process.  Please let me know what additions I might need to take for the official release channel.  Thanks.

**Comment by thc202** [comment]
@veggiespam it would be great if the ILS was provided as library/jar, instead of copying the source.

**Comment by veggiespam** [comment]
@kingthorin - I appreciate your help.  Just email me directly and we can begin to work on the unit tests together.  Does the i18n treatment that already exists cover @psiinon concerns?  

@thc202 - there is already a jar for the Burp version of this plug-in.  I would be glad to create a ZAP-compatible jar if you could point me to an example or advice.  Also, in v1.2/2.0 or whatnot, I'm going to move this out of the pscanner and into its own module as I'd like to add features that are not possible as a pscanner.  So, would it be easier to wait until that time or would it still be better to do it now?

Thank you all.

**Comment by thc202** [comment]
I'd suggest creating the add-on now (no need to wait for more functionality), in its own add-on it can be promoted more easily (a tweak in the add-on manifest). @kingthorin, @psiinon thoughts?

Regarding the library, it's like the `fatJar` you are already producing but without `burp-extender-api` :)

**Comment by kingthorin** [comment]
After the current PR is dealt with. If we are then happy promoting this to Beta. let's separate it out at that point? (I'm happy to tackle the work.)

**Comment by thc202** [comment]
Sounds good to me.

**Comment by veggiespam** [comment]
I believe the current PR zaproxy/issues/4295 is ready.  After that, I'll work with @kingthorin to move this into an independent library.

**Comment by thc202** [comment]
That can be started once the Passive scanner rules (alpha) add-on is released.

**Comment by kingthorin** [comment]
@veggiespam are you going to put together a jar for ILS?

I’ll start putting together a PR for the beta promotion and separation from pscan. To be followed quickly by a PR removing it from alpha.

**Comment by thc202** [comment]
The move from pscan to a new add-on can be done in just one PR (the add-on can define its own status).

**Comment by kingthorin** [comment]
But don't we want it to reside in the beta branch? Or are we really close to flattening things and it not making any difference?

**Comment by thc202** [comment]
They no longer need to be in a specific branch (add-on status no longer depends on where they are) and the latter.

**Comment by kingthorin** [comment]
Great! :+1:

**Comment by veggiespam** [comment]
I'm trying to figure out Gradle now, to create a Burp jar and a ZAP jar.  Give me a day to learn it for myself before I cry wolf for help.

**Comment by kingthorin** [comment]
See https://github.com/zaproxy/zap-extensions/pull/1408

**Comment by thc202** [comment]
@veggiespam could you provide more details about the new features intended for the new add-on? Wondering if that will affect the name/description of the add-on/extension, package and so on.

**Comment by veggiespam** [comment]
I have discovered that I suck at Gradle.  I'll ping @kingthorin offline for a little bit of help soon.

@thc202 - Upcoming:

1. Future funky code optimization that will make enhancements quicker, easier, and scanning much faster.
2. Saved configuration options.
3. Feature Request: alerts only within certain geographies; such as scanning for images occurring in country XYZ or in abc km of certain lat/long.
4. Scan only certain types: jpg png gif tiff etc.
5.  Generalized image info display
     * Right click, show all Exif & Proprietary image info
     * Dump image info and scans into file on disk
6. More proprietary information as it comes available.

At this point, any next release will be months away, there is nothing urgent.

**Comment by kingthorin** [comment]
@veggiespam sorry to say but I have no graddle experience :(

**Comment by kingthorin** [comment]
Per [IRC discussion today](https://mozilla.logbot.info/websectools/20180227) this could be released without the jar. The jar is still preferable for future iterations though.

**Comment by thc202** [comment]
The new add-on, Image Location and Privacy Scanner, is now available in the marketplace.

**Comment by kingthorin** [comment]
@veggiespam are you still pursuing building a jar?

**Comment by kingthorin** [comment]
@veggiespam are you still pursuing building a jar?

**Comment by kingthorin** [comment]
@veggiespam if we could get a jar I'd be glad to do the updates to move this to master.

**Comment by kingthorin** [comment]
@veggiespam any news?

**Comment by kingthorin** [comment]
@veggiespam I see you were tackling some updates in late Nov which seemed to be planning for a release/update. Any hope that you'll tackle creating a JAR at the same time?

**Comment by veggiespam** [comment]
I am officially going to state for the record that I am not of the skill set to modify the build file to do what we need.  What I'd like to see is two different targets, one build to make a jar for Zap and another to make the jar for Burp.  I did not figure out how to do that in Gradle.  Could you be of assistance @kingthorin ?

**Comment by kingthorin** [comment]
So I believe we were hoping that your code would be packaged as a library, perhaps published to maven or something and that we could then just depend on it. That process isn't really something I'm familiar with but I could try to look into it.

**Comment by thc202** [comment]
It depends on how you want to structure it, but normally you would have two Gradle projects, one with the library (`ILS` class) and the other with the Burp plugin. The Burp plugin would consume the library as would the ZAP add-on (assuming the library is published to Maven Central). I can provide an example for that.

**Comment by thc202** [comment]
Is this still being pursued or should?

**Comment by veggiespam** [comment]
Still being pursued, but let's assume it is bit-rotted. I'll close this and re-submit at a later date.

**Comment by veggiespam** [comment]
Submission is stale, will re-submit later.
