### ISSUE TITLE
Bad Format (bad_format) API

### ISSUE THREAD

**Issue by testerrrrrr** [zaproxy/zaproxy#4304]
Hello,
I am using ZAP php class, When I tried to execute it I am getting Bad Format (bad_format), When I checked the logs I found the following:

[24-Jan-2018 07:30:42 Europe/Berlin] PHP Warning:  file_get_contents(http://localhost:8085/zap/JSON/spider/action/scan/?url=http%3A%2F%2Fexample.com%2F&amp;apikey=MYAPIKEY): failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request
 in /Applications/MAMP/htdocs/zap/vendor/zaproxy/php-owasp-zap-v2/src/Zap/Zapv2.php on line 134
[24-Jan-2018 07:30:42 Europe/Berlin] PHP Fatal error:  Uncaught Zap\ZapError: [0]: Connection error (proxy: tcp://127.0.0.1:8085)

I tried to access the above URL in the browser:
http://localhost:8085/zap/JSON/spider/action/scan/?url=http://example.com&apikey=mykey

I got the same error:

Bad Format (bad_format)
![Uploading Screen Shot 2018-01-24 at 9.57.36 AM.png…]()

What is the issue ??

Thanks,

**Comment by testerrrrrr** [comment]
<img width="1273" alt="screen shot 2018-01-24 at 9 57 36 am" src="https://user-images.githubusercontent.com/6566816/35318637-38f4bb6c-00ed-11e8-9538-5709429f5cb8.png">

**Comment by testerrrrrr** [comment]
It turns out that the PHP class using old API, 2.4.3 and the OWASP ZAP I am using is 2.7.
Someone needs to update the class.

**Comment by psiinon** [comment]
The PHP client is not officially supported by the ZAP team.
We would be happy to adopt it, but would need someone with PHP experience to help us maintain it.
If you're that person then please let us knoe :)
