### ISSUE TITLE
Intercept Like Burp suite

### ISSUE THREAD

**Issue by daudmalik06** [zaproxy/zaproxy#4311]
Can we have intercept option like burp suite , i mean when intercept is on it should wait for user to click on forward to send and it should add automatically other requests in queue , 
if intercept is off it should do as it's doing now,

the same way in which burp suite's proxy works.
thanks

**Comment by psiinon** [comment]
You mean like the Break tab: https://github.com/zaproxy/zap-core-help/wiki/HelpUiTabsBreak or something different?

**Comment by daudmalik06** [comment]
@psiinon  awesome , 
this is what i was searching for
you guys always rock , just love zap ,
thanks

**Comment by psiinon** [comment]
@daudmalik06 out of interest, where did you look for the 'intercept' functionality? Might help us improve the docs ;)

**Comment by daudmalik06** [comment]
![burpsuiteintercept](https://user-images.githubusercontent.com/3526480/35389097-a933c0f0-01d6-11e8-906c-9112b438886f.JPG)

this is what i was looking in zap ,
before i've always used burp suite that's why i wasn't aware of break points , 

by the way i think break point is more accurate term for this,

**Comment by psiinon** [comment]
yeah, I'm aware of the burp functionality ;)
I was wondering if you looked at any ZAP docs - we mention it in the Getting Started Guide
