### ISSUE TITLE
Struggling to Pass Authentication Header that contains space (for API ZAP scan)

### ISSUE THREAD

**Issue by FastNinja** [zaproxy/zaproxy#4332]
Hi There,
I am trying to pass Authorization header as described here:
https://zaproxy.blogspot.com.au/2017/06/scanning-apis-with-zap.html

However, my header must contain space i.e.`Bearer TOKEN_VALUE`
I noticed it seems that space is treated as end of value and my application receives only `Bearer ` 

```
./zap-api-scan.py  \
        -z "-config replacer.full_list(0).description=auth1 \
        -config replacer.full_list(0).enabled=true \
        -config replacer.full_list(0).matchtype=REQ_HEADER \
        -config replacer.full_list(0).matchstr=Authorization \
        -config replacer.full_list(0).regex=false \
        -config replacer.full_list(0).replacement=Bearer $ACCESS_TOKEN" \
        -t https://myURL/swagger.json \
        -f openapi -d
```
I think I need to escape space somehow so it is taken into account as value. I tried to use sinle quotes (') but it didn't work.
` -config replacer.full_list(0).replacement='Bearer $ACCESS_TOKEN'" \` resulted in exactly same behavior..

**Comment by thc202** [comment]
Right, escaping the space (or quote the `-config` value) would be the way to go but the script is not taking that into account (yet).

**Comment by FastNinja** [comment]
Hi, I fixed it with the following workaround:

1. Generate token
```
2. Store it in a props file (auth.prop) - 
```
BEARER_AUTH="Bearer "$ACCESS_TOKEN
echo $BEARER_AUTH

echo "----> Building prop file:"
echo  "replacer.full_list(0).description=auth1" >> auth.prop
echo  "replacer.full_list(0).enabled=true" >> auth.prop
echo  "replacer.full_list(0).matchtype=REQ_HEADER" >> auth.prop
echo  "replacer.full_list(0).matchstr=Authorization" >> auth.prop
echo  "replacer.full_list(0).regex=false" >> auth.prop
echo  "replacer.full_list(0).replacement=$BEARER_AUTH" >> auth.prop
```
3. call Zap
```
/zap-api-scan.py -z \"-configfile ./auth.prop"
```

**Comment by thc202** [comment]
Nice! Are you using stable image?

**Comment by FastNinja** [comment]
I have been using -live and -weekly with the same result ...what is the problem ?

**Comment by thc202** [comment]
That's odd, are you using the latest images? How are you escaping the header value?

**Comment by trallgorm** [comment]
I had the exact same issue as OP, I'm using the owasp/zap2docker-weekly image and escaping it with single quotes but it still doesn't work.

**Comment by thc202** [comment]
Could you provide the image ID?

**Comment by trallgorm** [comment]
I tried it with the zap2docker-live image, same issue. Image ID is 65d29d0ab1ef

**Comment by thc202** [comment]
Thanks, reopening, the fix is not working properly (while the args are correctly parsed, when passed to docker and then ZAP they are no longer interpreted correctly).

**Comment by thc202** [comment]
@trallgorm or @FastNinja would you mind trying with latest live image? It should be working properly now. Tested with the space escaped and with the config value single quoted:
 - `-config replacer.full_list(0).replacement=Bearer\ $ACCESS_TOKEN`
 - `-config 'replacer.full_list(0).replacement=Bearer $ACCESS_TOKEN'`

**Comment by trallgorm** [comment]
Seems to be working for me now, thanks a lot for a very quick fix!

**Comment by thc202** [comment]
Cool, thanks for trying that!
