### ISSUE TITLE
Include ID of the HTTP message in returned HAR

### ISSUE THREAD

**Issue by Naramsim** [zaproxy/zaproxy#4333]
Hello, is it intentional to not have in HAR messages the id attribute?

It is strange because we can query HAR messages by id (for example at this url: http://localhost:8080/OTHER/core/other/messageHar/?formMethod=GET&id=1) but inside the HAR message returned there is no id mentioned anywhere

Thanks

**Comment by thc202** [comment]
It was but there's no reason we can't have the ID of the message in each entry.

**Comment by Naramsim** [comment]
Good to see that you have put it in the 2.8 milestone
