### ISSUE TITLE
Request body not sent with PUT method in Zest scripts

### ISSUE THREAD

**Issue by AndyStatic** [zaproxy/zaproxy#4337]
Currently ZEST script recorder/editor allows GET, POST and custom method via variable
If I add custom method via variable as PUT, and part of this PUT request will be body, this body is not picked up during zest scrip run. Body only picked up for POST requests.

If I will run failed PUT via owasp zap request/response editor, it will be successfully executed.

You can see that content is not picked up during script player via WireShark

Thank you

**Comment by thc202** [comment]
Which version of Zest script add-on are you using?

**Comment by thc202** [comment]
Also, which script type?

Yes, the missing body is caused by an issue in the Zest library.

**Comment by AndyStatic** [comment]
"about": "This is a Zest script. For more details about Zest visit https://developer.mozilla.org/en-US/docs/Zest",
  "zestVersion": "0.3",

**Comment by kingthorin** [comment]
You can find the add-on version info via:

1. Hovering your cursor over the add-on's entry in Marketplace window.
2. Choosing "Support Info..." from the "Help" menu within ZAP.

**Comment by AndyStatic** [comment]
[id=zest, version=27.0.0]]

**Comment by thc202** [comment]
Thanks!

**Comment by AndyStatic** [comment]
thank you for the awesome tool

**Comment by thc202** [comment]
Being handled in mozilla/zest#148.
