### ISSUE TITLE
Need The Capability to Import Alerts

### ISSUE THREAD

**Issue by zqa19** [zaproxy/zaproxy#4359]
Hi,

We're using automated tests on ZAP proxy. But of course, to make this faster, we run tests in parallel.

So here's the problem, there will be multiple alert reports and a lot of duplication. This is why if alerts can be imported through ZAP API to be merged together would be helpful.

Thanks.

**Comment by psiinon** [comment]
What do you mean by running tests in parallel?
Are you running multiple ZAP instances?
Can you explain in a bit more detail what you would like?

**Comment by zqa19** [comment]
Yes, we set up multiple ZAP instances as proxies for selenium tests.
Therefore, there are multiple alert files.

I've tried to use one ZAP instance for all test segments, but since all segments are using the same hostname, they can only be run one by one using proxy chain which takes half a day for a single build.

This is why I wish to have a way to merge reports from multiple ZAP instances.

**Comment by zqa19** [comment]
Thanks Simon.

Good to know this.

Then I need to format the reports myself for the moment.
