### ISSUE TITLE
Filipino Translation thru GitHub

### ISSUE THREAD

**Issue by iam-strings** [zaproxy/zaproxy#4360]
Hi,

I would like to contribute on this project thru translation. I would like to translate the necessary files to Filipino thru GitHub in connection to Utopian Project. Utopian dropped the support in CrowdIn at the moment.

Hoping for your response.

Thanks..

**Comment by psiinon** [comment]
I'm afraid this will not be possible - see https://github.com/zaproxy/zap-core-help/pull/165 for more details.
Note that it looks like Utopian will support Crowdin again soon - see https://steemit.com/utopian-io/@utopian-io/crowdin-loves-utopian

**Comment by iam-strings** [comment]
okay sir. thanks!
