### ISSUE TITLE
Web/AppServers like WebLogic, WebSphere N/A while defining Scan Context

### ISSUE THREAD

**Issue by ch1c0hacker** [zaproxy/zaproxy#4363]
I believe ZAP doesn't have contextual test cases for Web/AppServers like WebLogic, WebSphere as those options aren't listed while defining Scan Context.

Please can you help me in case I'm missing something. Else, I believe this can be an enhancement.
![zap_observation](https://user-images.githubusercontent.com/36267098/35976114-10d7bd04-0d05-11e8-91d9-aed196e70c08.jpg)

**Comment by psiinon** [comment]
The reason we dont have those is (probably) because none of the rules have special cases for these app servers.
Be great to have those sort of special cases, but until we do theres not much point adding the options in the Technology panel :/
PRs always welcome ;)

**Comment by ch1c0hacker** [comment]
Apologies if its a dumb question....
Don't we have any test cases to identify any of the vulnerabilities listed in CVE or NVD.
Ex: https://www.cvedetails.com/vulnerability-list/vendor_id-93/product_id-14534/Oracle-Weblogic-Server.html
At least in cases if the server default error messages [or] stack traces are returned with server version details etc...

**Comment by psiinon** [comment]
Not at the moment, but would be very happy if someone added them :)
ZAP is more focussed on finding new vulnerabilities in custom apps, rather than known vulnerabilities in existing products. We're always happy if anyone submits PRs adding such checks but thats not really the focus of the ZAP core team.

**Comment by kingthorin** [comment]
No further user input in over a month. Closing.
