### ISSUE TITLE
Allow to specify a name for session snapshot through the API

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#4365]
From OWASP ZAP User Group: https://groups.google.com/d/msg/zaproxy-users/5HBCwJZ90sU/Ncph3QvWBAAJ

The core action `snapshotSession` does not allow to specify a name for session snapshot.

**Comment by kingthorin** [comment]
Also somewhat related to: 

- https://github.com/zaproxy/zaproxy/pull/3186
- https://github.com/zaproxy/zaproxy/issues/2618
