### ISSUE TITLE
Exclude from Context not used by active scan

### ISSUE THREAD

**Issue by bjamesvERT** [zaproxy/zaproxy#4368]
Version 2.7.0, the context "Exclude from Context" URL patterns appear to have no effect on Active scans.

I've tried several very simple patterns (e.g.: ".\*source.\*") and still see many URLs with values like ".../source/... etc." in the `Active Scan` results tab.

**Comment by bjamesvERT** [comment]
(this may have been what #4133 was referencing - e.g.: more then just terminology/conflating Context-level exclude with the Active Scan level exclude options).

**Comment by thc202** [comment]
Yeah, reading that again it seems to imply that.
