### ISSUE TITLE
Turkish Translation

### ISSUE THREAD

**Issue by halokaya67** [zaproxy/zaproxy#4375]
I want to help this project by translating it into turkish. I'm turkish and 25 years old. I'm working as an english teacher in a school. I think i can help. Please just show me which file should i translate and you will see. You won't regret because i take my job serious.

**Comment by kingthorin** [comment]
Thanks for the offer, all our translations are done by volunteers via crowdin:
https://crowdin.com/project/owasp-zap
https://crowdin.com/project/owasp-zap-help
