### ISSUE TITLE
JAVA_VERSION issue on Docker bare image

### ISSUE THREAD

**Issue by omerlh** [zaproxy/zaproxy#4383]
Today, suddenly the Zap Docker bare image failed to start due to the following error:
```
zap_1        | /zap//zap.sh: line 51: [: -ge: unary operator expected
zap_1        | /zap//zap.sh: line 54: [: -ge: unary operator expected
zap_1        | Exiting: ZAP requires a minimum of Java 8 to run, found
loggingapi_zap_1 exited with code 1
```
Those are the relevant lines from `zap.sh`:
```
JAVA_VERSION=$(java -version 2>&1 | awk -F\" '/version/ { print $2 }')
JAVA_MAJOR_VERSION=${JAVA_VERSION%%[.|-]*}
JAVA_MINOR_VERSION=$(echo $JAVA_VERSION | awk -F\. '{ print $2 }')

# JEP 223, newer Java versions (>= 9) no longer use 1 as major version
if [ $JAVA_MAJOR_VERSION -ge 9 ]; then
  DEFAULTJAVAGC=""
  echo "Found Java version $JAVA_VERSION"
elif [ $JAVA_MAJOR_VERSION -ge 1 ] && [ $JAVA_MINOR_VERSION -ge 8 ]; then
  echo "Found Java version $JAVA_VERSION"
else
  echo "Exiting: ZAP requires a minimum of Java 8 to run, found $JAVA_VERSION"
  exit 1
fi
```

The image is based on Java alpine image. The [image](https://github.com/docker-library/openjdk/blob/master/8-jdk/alpine/Dockerfile) defines the following env vars:
```docker
ENV JAVA_VERSION 8u151
ENV JAVA_ALPINE_VERSION 8.151.12-r0
```
The `JAVA_MAJOR_VERSION` is using `JAVA_VERSION` and try to extract from it the first number - but this will not work because of the format. It should use `JAVA_ALPINE_VERSION` instead.
What is not clear to me is how this worked until now - look like nothing have changed.
Can you help me figure this out?

**Comment by thc202** [comment]
What's the output of `docker run --rm -i owasp/zap2docker-bare java -version`? (Or the image you are using.)
`JAVA_VERSION` is being defined in the script,

**Comment by omerlh** [comment]
Yeah, I just found this. It was just one line above that I haven't read 🤦‍♂️ . 
The real issue was because `java -version` failed with the error `Error occurred during initialization of VM`. Deleting all data and restarting docker solve it...

**Comment by thc202** [comment]
Great! Closing per previous comment.
