### ISSUE TITLE
Allow to configure the irrelevant parameters for the Spider

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#4388]
From IRC channel: https://mozilla.logbot.info/websectools/20180207

It should be possible to configure the irrelevant parameters (e.g. session tokens)  when canonicalising the URLs found during the spider scan, currently they are hardcoded:
https://github.com/zaproxy/zaproxy/blob/fc0cbcbad2ad982de35060260e2c2ac6685f9ee3/src/org/zaproxy/zap/spider/URLCanonicalizer.java#L60-L64
and
https://github.com/zaproxy/zaproxy/blob/fc0cbcbad2ad982de35060260e2c2ac6685f9ee3/src/org/zaproxy/zap/spider/URLCanonicalizer.java#L305

(Ideally the session tokens should be retrieved from the HTTP Sessions options.)

**Comment by AleksandrPea** [comment]
@thc202 
Hi! I'd like to work on this issue. Please, confirm or reject my suggestions: to retrieve session tokens we may use `ExtensionHttpSessions.getHttpSessionTokensSet(String site)` instance of which is located in `CoreFunctionality`?

**Comment by thc202** [comment]
The extension would be obtained from the `ExtensionLoader`, e.g.:
```
ExtensionHttpSessions extensionHttpSessions = Control.getSingleton().getExtensionLoader().getExtension(ExtensionHttpSessions.class);
// extensionHttpSessions is null if disabled.
```
but might worth starting by changing `SpiderController`/`URLCanonicalizer` to allow to use custom parameters (then allow the user to configure them and include the ones from the HTTP Sessions)?

**Comment by AleksandrPea** [comment]
Ah, ok. Therefore, firstly we need to add additional spider param(class `SpiderParam`) (e.g. spider.irrelevantParameters) that would be defined somewhere in config.xml to allow to use custom parameters, don't we?

**Comment by thc202** [comment]
Yeah, that's where the configured parameters would be.

**Comment by AleksandrPea** [comment]
Does this feature need changes in UI as well?

**Comment by thc202** [comment]
Yes, it should be possible to configure them through the UI (Options and Spider dialogue) and also the ZAP API.
