### ISSUE TITLE
Enhancement: Params Tab - Multipart Form Params

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#4391]
I see that this came up in IRC the other day: https://mozilla.logbot.info/websectools/20180212

It's great that one of our users scripted a way around the current limitation, however, it may as well actually be part of the tool.

Now that the multipart form params handling has been revised (various recent PRs [1][2]). It seems pretty easy to add those params. 

My question is how would we want the file part of multipart form posts handled? I'm thinking by filename. Having the file content in the params window doesn't seem practical....

I'm thinking something like this around L309 in ExtensionParams.java
```
VariantMultipartFormParameters params2 = new VariantMultipartFormParameters();
params2.setMessage(msg);
for (NameValuePair nvp : params2.getParamList()) {
	if (Arrays.asList(NameValuePair.TYPE_MULTIPART_DATA_PARAM, NameValuePair.TYPE_MULTIPART_DATA_FILE_NAME)
			.contains(nvp.getType())) {
		persist(sps.addParam(site, new HtmlParameter(HtmlParameter.Type.form, nvp.getName(), nvp.getValue()),
				msg));
	}
}
```

Seem reasonable?

[1] https://github.com/zaproxy/zaproxy/pull/3814
[2] https://github.com/zaproxy/zaproxy/pull/4208

**Comment by psiinon** [comment]
yeah, that sounds good.

**Comment by thc202** [comment]
How about using other type than `form` (to differentiate them)?

**Comment by kingthorin** [comment]
Sure, I can add another type as well.
