### ISSUE TITLE
Add option to include headers in Invoke parameters

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#4396]
The current list of parameters supported is: https://github.com/zaproxy/zap-core-help/wiki/HelpAddonsInvokeOptions
Adding the option to include header params, eg "%header-User-Agent%" would be very useful, as would adding the history ID.
Requested via irc.
The relevant code is https://github.com/zaproxy/zap-extensions/blob/beta/src/org/zaproxy/zap/extension/invoke/InvokeAppWorker.java

**Comment by rezen** [comment]
##### `%msgid%`
To get the message id history reference which a script can pull from the full message data from the api `JSON/core/view/message/?zapapiformat=JSON&id=%msgid%`
The msgid would be pull from `msg.getHistoryRef().getHistoryId()`

##### `%header-{{ key }}%`
Any template tag with a header prefix would fetch the header by name of the suffix key.
`msg.getRequestHeader().getHeader(key)`

Example for user agent the template string would be `%header-user-agent%` which would essentially call  `msg.getRequestHeader().getHeader('User-Agent')`. Casing would be normalized so either `%header-user-agent%` or `%header-User-Agent%` would work.

**Comment by thc202** [comment]
Note that the source of the help page is in:
https://github.com/zaproxy/zap-extensions/blob/beta/src/org/zaproxy/zap/extension/invoke/resources/help/contents/options.html

the wiki is updated when the add-on is released.

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#1373.

**Comment by thc202** [comment]
Released in version 9 of Invoke Applications add-on.
