### ISSUE TITLE
html report generation uses stale info relative to core/action/deleteAlert and includes deleted alerts

### ISSUE THREAD

**Issue by renatofasoli** [zaproxy/zaproxy#4403]
ZAP 2.7.0 added the core/action/deleteAlert endpoint to delete individual alerts.  I've noticed that after deleting an alert via deleteAlert, the set of alerts shown in the ZAP GUI is correctly updated, the number of alerts returned by core/view/numberOfAlerts is revised correctly, and the set of alerts found by traversing the set of alerts via core/view/alert is revised correctly.

Unfortunately, if after calling core/action/deleteAlert an html report is generated via core/other/htmlreport or via the GUI (Report > htmlreport) the generated report still shows the alerts that were removed.  I haven't looked at the code but it obviously uses stale info.

**Workaround:** after calling core/action/deleteAlert, snapshot the session, shutdown ZAP, bring up ZAP again, and load the session that was snapshoted after the deleteAlert calls, then generate the html report.  The report will now be correct (relative to the deleteAlert calls)

**Comment by thc202** [comment]
Added to #6483.

**Comment by psiinon** [comment]
The new Reporting add-on generates the reports in a different way and so this should not longer be a problem.
I've tried the above tests manually and could not reproduce the problem with the new add-on.
