### ISSUE TITLE
URL Scanning for different environments

### ISSUE THREAD

**Issue by ssnmworld** [zaproxy/zaproxy#4411]
I am using ZAP for scanning APIs and web sites. One requirement is to create a session using the JUnit tests and other testing scripts, and have the ability to run it on different hosting environments like QA and UAT, where the baseurl would be different. Is there any way, I can only switch the baseurl of the application, but still have the ability to scan the session. 

I tried exporting the urls, it is only saving the url as text, but does not have the ability to store the request/response details. 

Please advise.

Thanks

**Comment by thc202** [comment]
This is a recurrent request, it's not possible at the moment, one can workaround that by replacing the URL when ZAP sends the requests (for example, using a HTTP Sender script).

Merging into #682, please, let us know if the Copy/Paste proposal would address your use case (if not, provide more details on how you would use the feature).

**Comment by kingthorin** [comment]
The other option might be to use a hosts file entry to override DNS.
