### ISSUE TITLE
Script Console should handle scripts changed on disk

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#4450]
Related to https://github.com/zaproxy/zaproxy/issues/2950
If https://github.com/zaproxy/zaproxy/pull/4449 is merged then the Script Console will need to change to handle scripts that have changed on disk.
The code also needs to handle scripts that have been changed but not saved - these might not be the currently displayed script.
The script currently being displayed should also be handled if its changed on disk even if its not been changed via the console,
In all cases the user should be prompted to ask if they want to change to see the new contents, and informed if any changes they made via the console will be lost.

**Comment by thc202** [comment]
Being handled in zaproxy/zap-extensions#1441.

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#1441.
