### ISSUE TITLE
"ServletParameterPollutionScanner" FP reduction changes

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#4454]
Edit 20190425:
After the discussion here and on IRC we have decided not to promote this passive scanner. 

TODO:

- [ ] Add Tech handling once zap-extensions are targeting 2.9.0.
- [x] Only enable the scan rule only on Low Threshold (https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsOptionsPscanrules#threshold)

**Comment by psiinon** [comment]
I'm not so sure about this one - it can give a lot of false positives.
Maybe if we could tie it in with some simple tech detection (for jsps) it might be better?

**Comment by kingthorin** [comment]
The problem with that is that not all components will be http://example.com/bleh.jsp some will be simply /bleh (servlet or mapped).

I guess we could add a tech check for Java? ..... only we don't have a [Java/JSP lang tech](https://github.com/zaproxy/zaproxy/blob/cfb44f7e29f490d95b03830d90aadaca51a72a6a/src/org/zaproxy/zap/model/Tech.java#L43-L47) :disappointed: 

I guess I could add the tech entries, and we could plan the plugin change after 2.8.0?

**Comment by psiinon** [comment]
+1 for adding the java (or JSP?) tech. That would at least allow people to filter that out.
However even if we do that I'm a bit worried about promoting it to release due to the amount of false positives :/

**Comment by kingthorin** [comment]
Okay, well we (aka you 😀) could do a Twitter/slack/mailman blast and ask about people encountering the issue in modern apps perhaps it’s not worth checking any more? 

Or maybe someone sees a way to tighten up the logic?

**Comment by kingthorin** [comment]
Should we deprecate this plugin? Or enable it only at Low Threshold?
