### ISSUE TITLE
ZAP Jenkins plugin does not obtain latest spider status

### ISSUE THREAD

**Issue by HUssain14** [zaproxy/zaproxy#4462]
[jenkins_logs.txt](https://github.com/zaproxy/zaproxy/files/1770333/jenkins_logs.txt)
Logs attached Debug mode is on already. Looking for suggestions. 

Issue:
Jenkins plugin become unresponsive while running the zap and failed after a while.

**Comment by thc202** [comment]
Thanks for providing the logs, this is a recurrent issue. Seems more an issue in the client side (Jenkins plugin or ZAP API client) than ZAP, after a while ZAP is no longer receiving any API requests.

**Comment by HUssain14** [comment]
Thank you for your response. But this is a show stopper for performing testing. what is the solution for this?. I'm clueless.

**Comment by thc202** [comment]
Are you able to get the traffic sent by Jenkins? (e.g. with Wireshark) It would be great to confirm if the API requests are not reaching ZAP.

**Comment by HUssain14** [comment]
Traffic is getting to the machine and proxy gets working i check on browser Zap starts successfully but where it is getting lost im still clueless

**Comment by thc202** [comment]
Does that include the API requests that don't appear in the ZAP log? I was wondering if something was caching those.

**Comment by HUssain14** [comment]
I haven't seen any api request hitting the machine but it triggers the ZAP only with proxy. Else i try to run with cmd and that works fine so where is the issue still unclear.

**Comment by thc202** [comment]
What happens if you shutdown/kill ZAP while the job outputs:
```
[ZAP Jenkins Plugin] SPIDER SCAN STATUS [ 0% ]
[ZAP Jenkins Plugin] ALERTS COUNT [ 0 ]
```
Does it fail? If so could you provide the stack trace?

Which JRE is used for Jenkins?

**Comment by HUssain14** [comment]
ERROR: java.lang.InterruptedException
	at java.lang.Object.wait(Native Method)
	at hudson.remoting.Request.call(Request.java:167)
	at hudson.remoting.Channel.call(Channel.java:908)
	at hudson.FilePath.act(FilePath.java:998)
	at hudson.FilePath.act(FilePath.java:987)
	at org.jenkinsci.plugins.zap.ZAPBuilder.perform(ZAPBuilder.java:292)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.Build$BuildExecution.build(Build.java:206)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1727)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)

Build step 'Execute ZAP' marked build as failure
ERROR: java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at org.jenkinsci.plugins.zap.ZAPDriver.spiderScanURL(ZAPDriver.java:1896)
	at org.jenkinsci.plugins.zap.ZAPDriver.executeZAP(ZAPDriver.java:1191)
	at org.jenkinsci.plugins.zap.ZAPBuilder$ZAPDriverCallable.invoke(ZAPBuilder.java:448)
	at org.jenkinsci.plugins.zap.ZAPBuilder$ZAPDriverCallable.invoke(ZAPBuilder.java:436)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:2813)
	at hudson.remoting.UserRequest.perform(UserRequest.java:210)
	at hudson.remoting.UserRequest.perform(UserRequest.java:53)
	at hudson.remoting.Request$2.run(Request.java:358)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at hudson.remoting.Engine$1$1.run(Engine.java:94)
	at java.lang.Thread.run(Unknown Source)


[ZAP Jenkins Plugin] SHUTDOWN [ START ]

612133 [ZAP-ProxyThread-2] DEBUG org.zaproxy.zap.extension.api.API  - handleApiRequest http://zap/xml/core/action/shutdown/?apikey=ZAPROXY-PLUGIN
612142 [ZAP-ProxyThread-2] DEBUG org.zaproxy.zap.extension.api.API  - handleApiRequest returning: <?xml version="1.0" encoding="UTF-8" standalone="no"?><shutdown>OK</shutdown>
this is what it shows

**Comment by thc202** [comment]
Thanks! Would you be available to try the Jenkins plugin with more debug or possible fix?

**Comment by sello4354** [comment]
Yes I am available to try

**Comment by sello4354** [comment]
How do i capture traffic on the loop back address ? and i am still waiting for build post

**Comment by sello4354** [comment]
Hi I was able to solve the capturing of traffic by installing npcap , which needs to be installed on windows if you want to capture traffic on loopback address . 
After doing so , I have confirmed that there is only  one request sent from ZAP plugin to ZAP regarding the numberOfAlerts .

**Comment by thc202** [comment]
Thanks for the info. Attached a modified ZAP Jenkins plugin, [zap.zip](https://github.com/zaproxy/zaproxy/files/1851397/zap.zip) (the extension needs to be changed to `hpi`), it logs the URLs that the API client requests and it also has the HTTP cache disabled...

Let me know if that makes any difference.

**Comment by thc202** [comment]
@amitcsknit could you try that as well?

**Comment by amitcsknit** [comment]
@thc202  do you mean i should install zap jenkins client & install from give zip?.    

Just for information as of now: I am running zap as slave in windows machine & jenkins in Ubuntu machine. In case i set proxy in slave windows machine lan settings and browse google in browser it tracks in logs but still its keep running & running untill i kill it. if i kill no report generated. if i dont kill it keeps running forever. Now i am plannig to try without salve.

1 Question: do i really need to somebody to browse actually in browser or it should take website from s context or start point configuration of jenkins plugin.

**Comment by thc202** [comment]
The "zap.zip" (which really should be "zap.hpi", but GitHub does not allow to upload with that extension) is the ZAP Jenkins plugin, you would have to install it in Jenkins and try running the job again.

You don't need the browser, ZAP Jenkins plugin can access/spider the target, so it's enough to configure the job to get it working.

**Comment by amitcsknit** [comment]
@thc202   i checked as you suggested from given build from ZAP.
[Jenkins_Error_log_ZAP_HIP.txt](https://github.com/zaproxy/zaproxy/files/1851808/Jenkins_Error_log_ZAP_HIP.txt)
Your ZAP.zip works & i made progress but not sure how much. I have attached logs. it seems spide scan is completed which was not happening earlier. But Active scan is going on & one. Process is keep running .. I think i have to kill the jenkins job to stop it.

Kindly check error log attached so that you will get mire insight.  Thanks for you support you provided till now.

**Comment by thc202** [comment]
Thank for trying it! Could you confirm that using the older version the issue is back?

The active scanner takes more time to finish, so that might be normal (the message count is not always the same so ZAP and the Jenkins plugin seem to be working as expected). There's some suggestions on how to improve the time the active scanner takes:
https://blog.mozilla.org/security/2013/07/10/how-to-speed-up-owasp-zap-scans/

**Comment by sello4354** [comment]
Thank you and I will update once I finish testing

**Comment by thc202** [comment]
Thanks for trying it!

That means the AJAX Spider add-on is not installed in ZAP.

**Comment by sello4354** [comment]
what is that mean ? i was able to run manually using AJAX spider and did not face any problem . Can you please elaborate on what you said ?

**Comment by thc202** [comment]
Were the same (ZAP) home [1] and installation [2] directories used in both cases? For example, it's possible that it's present in the home directory you used but not the one used by Jenkins.

Note that you can install it by passing the command line argument `-addoninstall spiderAjax` (it's enough once). [3]

[1] https://github.com/zaproxy/zaproxy/wiki/FAQconfig
[2] https://github.com/zaproxy/zaproxy/wiki/FAQinstall
[3] https://github.com/zaproxy/zap-core-help/wiki/HelpCmdline

**Comment by amitcsknit** [comment]
@thc202  Thank you much for all your support.
your build given zap.zip ran successfully except one thing that i am using generate report.
If i use Export report in place of generate report option of plugin it doesn't work and gives plugin missing error not sure y. Anyways for me reporting workaround is don't use export report , just use generate report & use archive artifact plugin & Html Publisher plugin to display.  

@thc202  when zip you provided will got to actual distribution for public download.

@thc202 
As of now i havn't used form based authentication. Will work on that as well and let you know. But i have a doubt in that.  

What is Logged in Indicator & Logged out Indicator?
What should pass in Username Parameter & Password parameter?
What is Extra POST Data?
How to proceed if My login page is not having label of username & password & just to text boxes first for username & second for password?

**Comment by sello4354** [comment]
@thc202  i am still getting the same error 
Here is the log from Jenkin 
[Zed Attack Proxy] $ "C:\Program Files\OWASP\Zed Attack Proxy\zap.bat" -daemon -host localhost -port 8090 -config api.key=ZAPROXY-PLUGIN -dir "C:\Users\QAUser\OWASP ZAP" -installdir %ZAPROXY_HOME% "-addoninstall " spiderAjax

ZAP Jenkins Plugin] SPIDER SCAN THE SITE [ http://10.3.3.62/evi/prior-auth ]

Open URL: http://zap/xml/spider/action/scan/?contextName=spa_zap_105&apikey=ZAPROXY-PLUGIN&recurse=true&subtreeOnly=false&url=http%3A%2F%2F10.3.3.62%2Fevi%2Fprior-auth&maxChildren=0&
Open URL: http://zap/xml/spider/view/status/?apikey=ZAPROXY-PLUGIN&scanId=&

Open URL: http://zap/xml/spider/view/status/?apikey=ZAPROXY-PLUGIN&scanId=&
[ZAP Jenkins Plugin] SPIDER SCAN STATUS [ 0% ]
Open URL: http://zap/xml/core/view/numberOfAlerts/?baseurl=&apikey=ZAPROXY-PLUGIN&
63556 [ZAP-SpiderInitThread-0] INFO org.zaproxy.zap.extension.spider.SpiderThread  - Starting spidering scan on Context: spa_zap_105 at Fri Mar 30 18:10:41 UTC 2018
63642 [ZAP-SpiderInitThread-0] INFO org.zaproxy.zap.spider.Spider  - Spider initializing...
[ZAP Jenkins Plugin] ALERTS COUNT [ 112 ]

63902 [ZAP-SpiderInitThread-0] INFO org.zaproxy.zap.spider.Spider  - Starting spider...
65671 [ZAP-SpiderThreadPool-0-thread-2] INFO org.zaproxy.zap.spider.Spider  - Spidering process is complete. Shutting down...
65674 [ZAP-SpiderShutdownThread-0] INFO org.zaproxy.zap.extension.spider.SpiderThread  - Spider scanning complete: true
Open URL: http://zap/xml/spider/view/status/?apikey=ZAPROXY-PLUGIN&scanId=&

[ZAP Jenkins Plugin] AJAX SPIDER ENABLED [ TRUE ]
	AJAX SPIDER SETTINGS
		SUB TREE ONLY: [ FALSE ]

[ZAP Jenkins Plugin] AJAX SPIDER THE SITE [ http://10.3.3.62/evi/prior-auth ]

Open URL: http://zap/xml/ajaxSpider/action/scan/?apikey=ZAPROXY-PLUGIN&inScope=false&url=http%3A%2F%2F10.3.3.62%2Fevi%2Fprior-auth&
68698 [ZAP-ProxyThread-144] WARN org.zaproxy.zap.extension.api.API  - Bad request to API endpoint [/xml/ajaxSpider/action/scan/] from [127.0.0.1]:
No Implementor (no_implementor)
	at org.zaproxy.zap.extension.api.API.handleApiRequest(API.java:356)
	at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(ProxyThread.java:456)
	at org.parosproxy.paros.core.proxy.ProxyThread.run(ProxyThread.java:317)
	at java.lang.Thread.run(Unknown Source)
ERROR: org.zaproxy.clientapi.core.ClientApiException: No Implementor
	at org.zaproxy.clientapi.core.ApiResponseFactory.getResponse(ApiResponseFactory.java:50)
	at org.zaproxy.clientapi.core.ClientApi.callApi(ClientApi.java:330)
	at org.zaproxy.clientapi.gen.AjaxSpider.scan(AjaxSpider.java:139)
	at org.jenkinsci.plugins.zap.ZAPDriver.ajaxSpiderURL(ZAPDriver.java:1940)
	at org.jenkinsci.plugins.zap.ZAPDriver.executeZAP(ZAPDriver.java:1197)
	at org.jenkinsci.plugins.zap.ZAPBuilder$ZAPDriverCallable.invoke(ZAPBuilder.java:448)
	at org.jenkinsci.plugins.zap.ZAPBuilder$ZAPDriverCallable.invoke(ZAPBuilder.java:436)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:2731)
	at hudson.remoting.UserRequest.perform(UserRequest.java:153)
	at hudson.remoting.UserRequest.perform(UserRequest.java:50)
	at hudson.remoting.Request$2.run(Request.java:336)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at hudson.remoting.Engine$1$1.run(Engine.java:94)
	at java.lang.Thread.run(Unknown Source)

[ZAP Jenkins Plugin] SHUTDOWN [ START ]

Open URL: http://zap/xml/core/action/shutdown/?apikey=ZAPROXY-PLUGIN

73246 [Thread-129] INFO hsqldb.db..ENGINE  - dataFileCache commit start
73353 [Thread-129] INFO hsqldb.db..ENGINE  - dataFileCache commit end
73362 [Thread-129] INFO hsqldb.db..ENGINE  - Database closed
73464 [Thread-129] INFO org.zaproxy.zap.extension.api.CoreAPI  - OWASP ZAP 2.7.0 terminated.


[ZAP Jenkins Plugin] SHUTDOWN [ SUCCESSFUL ]

[ZAP Jenkins Plugin] LOG SEARCH...
	ZAP HOME DIRECTORY [ C:\Users\QAUser\OWASP ZAP ]
	JENKINS WORKSPACE [ c:\Users\jenkins\workspace\QA_Automation_ZAP_sPA ]
	CLEARING WORKSPACE/LOGS

	[ /opt/bitnami/apache-tomcat/logs/C:/Users/QAUser/OWASP ZAP/zap.log ] LOG HAS BEEN FOUND
	COPY [zap.log] TO [c:\Users\jenkins\workspace\QA_Automation_ZAP_sPA\logs\zap.log]


Build step 'Execute ZAP' marked build as failure

**Comment by thc202** [comment]
@amitcsknit:
1. You need the add-on Export Report to use that option.
2. There's no exact date, but hopefully this week.
3. The following pages explain what those fields are:
https://github.com/zaproxy/zap-core-help/wiki/HelpStartConceptsAuthentication
https://wiki.jenkins.io/display/JENKINS/zap-plugin+Form-Based+Auth
If you still have any question please let us know through the groups:
https://groups.google.com/group/zaproxy-users or https://groups.google.com/group/zaproxy-jenkins

@sello4354 the parameter `-addoninstall` should not be quoted, otherwise ZAP will not interpret it correctly.

**Comment by sello4354** [comment]
@thc202 
I believe the ZAP plugin added the quotation.  I did not configure it that way as you can see it in the below  log excerpts : 
[ZAP Jenkins Plugin] START PRE-BUILD ENVIRONMENT VARIABLE REPLACEMENT
	HOST = [ localhost ]
	PORT = [ 8090 ]

	SESSION FILENAME = [ session_folder/spa ]
	INTERNAL SITES = [ http://10.3.3.62 ]

	CONTEXT NAME = [ spa_zap_105 ]

	INCLUDE IN CONTEXT = [ http://10.3.3.62.* ]

	EXCLUDE FROM CONTEXT = [  ]

	STARTING POINT (URL) = [ http://10.3.3.62/evi/prior-auth ]
	REPORT FILENAME = [ JENKINS_ZAP_VULNERABILITY_REPORT_105 ]
	REPORT TITLE = [ JENKINS_ZAP_VULNERABILITY_REPORT_105 ]

	COMMAND LINE = 
		OPTION : [ -installdir ]
		VALUE  : [ %ZAPROXY_HOME% ]
 
		OPTION : [ -addoninstall  ]
		VALUE  : [ spiderAjax ]

[ZAP Jenkins Plugin] END PRE-BUILD ENVIRONMENT VARIABLE REPLACEMENT

[ZAP Jenkins Plugin] CLEAR LOGS IN SETTINGS...
	ZAP HOME DIRECTORY [ C:\Users\QAUser\OWASP ZAP ]
	JENKINS WORKSPACE [ c:\Users\jenkins\workspace\QA_Automation_ZAP_sPA ]
	CLEARING ZAP HOME DIRECTORY/LOGS

	[ /opt/bitnami/apache-tomcat/logs/C:/Users/QAUser/OWASP ZAP/zap.log ] LOG HAS BEEN FOUND
	DELETE [zap.log] FROM [/opt/bitnami/apache-tomcat/logs/C:/Users/QAUser/OWASP ZAP/zap.log]


[ZAP Jenkins Plugin] START PRE-BUILD STEP

[ZAP Jenkins Plugin] PLUGIN VALIDATION (PLG), VARIABLE VALIDATION AND ENVIRONMENT INJECTOR EXPANSION (EXP)
	ZAP INSTALLATION DIRECTORY = [ C:\Program Files\OWASP\Zed Attack Proxy ]
	(EXP) HOST = [ localhost ]
	(EXP) PORT = [ 8090 ]
	(EXP) SESSION FILENAME = [ session_folder/spa ]
	(EXP) INTERNAL SITES = [ http://10.3.3.62 ]
	(EXP) CONTEXT NAME = [ spa_zap_105 ]
	(EXP) INCLUDE IN CONTEXT = [ http://10.3.3.62.* ]
	(EXP) EXCLUDE FROM CONTEXT = [  ]
	(EXP) STARTING POINT (URL) = [ http://10.3.3.62/evi/prior-auth ]
	(EXP) REPORT FILENAME = [ JENKINS_ZAP_VULNERABILITY_REPORT_105 ]

[ZAP Jenkins Plugin] CONFIGURE RUN COMMANDS for [ C:\Program Files\OWASP\Zed Attack Proxy\zap.bat ]
[ZAP Jenkins Plugin] EXECUTE LAUNCH COMMAND
[Zed Attack Proxy] $ "C:\Program Files\OWASP\Zed Attack Proxy\zap.bat" -daemon -host localhost -port 8090 -config api.key=ZAPROXY-PLUGIN -dir "C:\Users\QAUser\OWASP ZAP" -installdir %ZAPROXY_HOME% "-addoninstall " spiderAjax

**Comment by thc202** [comment]
OK, could you try remove the space after `-addoninstall`? I guess it's because of that.

**Comment by sello4354** [comment]
i am still seeing the same error .

**Comment by thc202** [comment]
btw, what is the ZAP home logged by ZAP?

**Comment by sello4354** [comment]
[ZAP Jenkins Plugin] CLEAR LOGS IN SETTINGS...
	ZAP HOME DIRECTORY [ C:\Users\QAUser\OWASP ZAP ]
	JENKINS WORKSPACE [ c:\Users\jenkins\workspace\QA_Automation_ZAP_sPA ]
	CLEARING ZAP HOME DIRECTORY/LOGS

	[ /opt/bitnami/apache-tomcat/logs/C:/Users/QAUser/OWASP ZAP/zap.log ] LOG HAS BEEN FOUND
	DELETE [zap.log] FROM [/opt/bitnami/apache-tomcat/logs/C:/Users/QAUser/OWASP ZAP/zap.log]

**Comment by thc202** [comment]
That's from the Jenkins plugin, I was referring to the ZAP logs/output, something like:
```
1 [main] INFO org.zaproxy.zap.DaemonBootstrap  - OWASP ZAP 2.7.0 started 02/04/18 16:19:14 with home /home/zap/X1/
```
And when installing the add-on:
```
8045 [ZAP-daemon] INFO org.zaproxy.zap.extension.callback.ExtensionCallback  - Started callback server on 0.0.0.0:45115
10330 [ZAP-daemon] INFO org.parosproxy.paros.CommandLine  - Downloading add-on from: https://github.com/zaproxy/zap-extensions/releases/download/2.7/spiderAjax-release-21.zap
14334 [ZAP-daemon] INFO org.parosproxy.paros.CommandLine  - Add-on downloaded to: /home/zap/X1/plugin/spiderAjax-release-21.zap
14407 [ZAP-daemon] INFO org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate  - Installing new addon spiderAjax v21.0.0
14468 [ZAP-daemon] INFO org.zaproxy.zap.DaemonBootstrap  - ZAP is now listening on localhost:8048
```
or if already installed:
```
4454 [ZAP-daemon] INFO org.zaproxy.zap.extension.callback.ExtensionCallback  - Started callback server on 0.0.0.0:33194
5575 [ZAP-daemon] INFO org.parosproxy.paros.CommandLine  - Add-on already installed: /home/zap/X1/plugin/spiderAjax-release-21.zap
5576 [ZAP-daemon] INFO org.zaproxy.zap.DaemonBootstrap  - ZAP is now listening on localhost:8048
```

If you know exactly which dir ZAP is using you could copy the add-on to the `plugin` dir (if failing to install the add-on).

**Comment by sello4354** [comment]
I did not see either of the logs in the logs/output file but I found out that ajaxSpider plugin is installed in ZAP home directory (i.e C:\Users\QAUser\OWASP ZAP . 
I do not know how much this will help you  I opened zap program manually and kicked off my zap Jenkins job and everything works fine . ZAP Jenkins job was able to terminate the ZAP program after finishing the scanning . Can I conclude that  the ZAP plugin is unable to run the ZAP program ?

**Comment by thc202** [comment]
Based on logs provided earlier ZAP and the Jenkins plugin are working fine, the problem is that the ZAP instance being run in the slave(?) machine does not have the AJAX spider add-on. Which package was used to install ZAP? Core? [1] This one does not have AJAX Spider, only the standard package (or weekly).

[1] https://github.com/zaproxy/zaproxy/wiki/Downloads#zap-270-core

**Comment by sello4354** [comment]
I installed the standard version . i found this in zap log file . what is the requirement ?
2018-04-02 17:32:41,393 [ZAP-daemon] WARN  DaemonBootstrap - Add-on "jxbrowserwindows" or its extensions will no longer be run until its requirements are restored: [Add-On with ID "webdriverwindows"]
2018-04-02 17:32:41,393 [ZAP-daemon] WARN  DaemonBootstrap - Add-on "quickstart" or its extensions will no longer be run until its requirements are restored: [Add-On with ID "selenium", Add-On with ID "plugnhack"]
2018-04-02 17:32:41,393 [ZAP-daemon] WARN  DaemonBootstrap - Add-on "spiderAjax" or its extensions will no longer be run until its requirements are restored: [Add-On with ID "selenium"]
2018-04-02 17:32:41,393 [ZAP-daemon] WARN  DaemonBootstrap - Add-on "websocket" or its extensions will no longer be run until its requirements are restored: [Add-On with ID "fuzz"]
2018-04-02 17:32:41,394 [ZAP-daemon] WARN  DaemonBootstrap - Add-on "zest" or its extensions will no longer be run until its requirements are restored: [Add-On with ID "selenium"]

**Comment by thc202** [comment]
It seems that several add-ons are no longer runnable or no longer installed (e.g. Selenium, Windows WebDrivers), from the log which add-ons are installed? e.g. ` [ZAP-daemon] INFO  ExtensionFactory - Installed add-ons: ...`
that explains why the AJAX Spider add-on was not started.

No problem :)

**Comment by sello4354** [comment]
[ZAP-daemon] INFO org.zaproxy.zap.control.ExtensionFactory  - Installed add-ons: [[id=alertFilters, version=7.0.0], [id=ascanrules, version=31.0.0], [id=coreLang, version=13.0.0], [id=gettingStarted, version=9.0.0], [id=invoke, version=9.0.0], [id=jxbrowser, version=8.0.0], [id=pscanrules, version=22.0.0], [id=quickstart, version=23.0.0], [id=replacer, version=5.0.0], [id=scripts, version=24.0.0], [id=websocket, version=15.0.0]]

**Comment by thc202** [comment]
Yeah, that confirms the Selenium add-on is not installed. Could you try download/install ZAP again? Hopefully that restores the add-ons (Selenium and AJAX Spider are included in the standard package).

**Comment by sello4354** [comment]
I downloaded and installed the standard version ( ZAP-2.7.0) but I am still seeing the same above warnings

**Comment by sello4354** [comment]
it looks like something is wrong with zap standard version . It looks for the plugin and zapdb.script files under C:\Program folder instead ZAP home folder ( C:\QAUser\OWASP ZAP\ . I installed the cross platform distribution and i am not seeing any error . Everything is working perfectly fine

**Comment by thc202** [comment]
Strange, both packages use the same code, the only difference is in which add-ons are bundled in them (Windows installer includes just the Windows specific add-ons, JxBrowser, WebDrivers). In both cases ZAP should be looking in the installation directory for the session files and for the add-ons (although the the latter it also checks the home directory).

Glad it's working fine! Might be because it's also bundling non-Windows add-ons(?).

**Comment by kingthorin** [comment]
Closing, the Jenkins plug-in is my supported by the core team.
