### ISSUE TITLE
Reports aren't generated on the selected language

### ISSUE THREAD

**Issue by AmandaBSobrinho** [zaproxy/zaproxy#4475]
When selecting Brazilian Portuguese as language, the XML report generated after an attack is in English, not in Portuguese. I'm aware that there is a project in Crowdin to translate ZAP to portuguese, and that the translation is far from complete, but I would like to know which files I would have to translate so that the XML report is also generated in Portuguese.

**Comment by thc202** [comment]
That would be the alerts' data, which are mainly in the active/passive scanner rules add-ons, in Crowdin those can be shown by filtering with `scanrules`. [1]

https://crowdin.com/project/owasp-zap/pt-BR#filter-files

**Comment by thc202** [comment]
Closing, the question seems to be answered.
