### ISSUE TITLE
Having trouble accessing ZAP (2.7.0) API through browser while hosting in a Docker container on mac

### ISSUE THREAD

**Issue by V1Reddy** [zaproxy/zaproxy#4485]
Hi,
(Sorry, re-posting the same from zap google groups for the larger audience)

I am still struggling with accessing the ZAP API through UI while hosting the ZAP in a Docker container on my mac.

Here's the command that I am using -

`docker run -p 8090:8090 -i owasp/zap2docker-stable zap.sh -daemon -port 8090 -host 0.0.0.0 -config api.disablekey=true`

Also, tried this command -

`docker run -p 8090:8090 -i owasp/zap2docker-stable zap.sh -daemon -port 8090 -host 0.0.0.0 -config api.disablekey=true -config api.addrs.addr.name=172.17.0.*`

Ultimately, I keep getting the exception as -
`ZAP-ProxyThread-20] WARN org.zaproxy.zap.extension.api.API  - Request to API URL http://localhost:8090/UI from 172.17.0.1 not permitted`
or
`ZAP-ProxyThread-20] WARN org.zaproxy.zap.extension.api.API  - Request to API URL http://127.0.0.1:8090/UI from 172.17.0.1 not permitted`

And when trying to access the ZAP API as http://172.17.0.2:8090/UI, the browser seems to hang their until it gives up as the connection times out.

I have followed the instructions from these URLs - https://github.com/zaproxy/zaproxy/wiki/Docker#accessing-the-api-from-outside-of-the-docker-container
and https://github.com/zaproxy/zaproxy/issues/4027.

Can someone please help? I would really appreciate it.

Thanks and Regards,
V Reddy

**Comment by thc202** [comment]
Could you provide the latest command used to start ZAP? I guess it needs some debug logging to know better what's happening, add the following to `docker run` command:
-v /path/to/log4j.properties:/home/zap/.ZAP/log4j.properties

with `/path/to/log4j.properties` having:
```
log4j.rootLogger=info, R

log4j.logger.org.parosproxy.paros.core.proxy=DEBUG
log4j.logger.org.zaproxy.zap.extension.api=DEBUG
```

Reference:
https://groups.google.com/d/topic/zaproxy-users/vIFDtfQNCI8/discussion

**Comment by V1Reddy** [comment]
Here's the new one (included the Log4j props)
`docker run -v /<pathToNewLog4Props>/log4j.properties:/home/zap/.ZAP/log4j.properties -p 8093:8093 -i owasp/zap2docker-stable zap.sh -daemon -port 8093 -host 0.0.0.0 -config api.disablekey=true -config api.addrs.addr.name=172.17.0.* -config api.addrs.addr.regex=true`

I checked the log4 file in that docker container and it reflected the new Log props - 

```
$ docker exec feee650dc39c cat /home/zap/.ZAP/log4j.properties

log4j.rootLogger=info, R

log4j.logger.org.parosproxy.paros.core.proxy=DEBUG
log4j.logger.org.zaproxy.zap.extension.api=DEBUG
```

Are you looking for anything in particular in the log messages while the zap starts?

**Comment by thc202** [comment]
Just when trying to access the ZAP API, it should log more info.

**Comment by V1Reddy** [comment]
Unfortunately, it's not logging anything for http://172.17.0.2:8093/UI until the connection times out eventually.

**Comment by thc202** [comment]
Not even something like `DEBUG org.parosproxy.paros.core.proxy.ProxyThread  - Timed out while reading a new HTTP request.`?

It seems that ZAP is not being accessed at all, is the container still using that IP address?

**Comment by thc202** [comment]
OK, odd. @psiinon have you seen this in macOS?

**Comment by Naramsim** [comment]
Mmm, 172... never worked for me. I always use 10.0.75.2:port

**Comment by thc202** [comment]
Was that also in a mac? (Works fine here in Linux.)

**Comment by V1Reddy** [comment]
@Naramsim 
How do you set it up to 10.0.75.2? I ask since the docker is setting these containers IPs to 172.17.0.*
Can you please provide few more details?

**Comment by Naramsim** [comment]
Hi, in theory, 172... are the internal address of the container in the docker network. In windows, you should browse localhost or if it does not work you should try 10.0.75.2. This IP in Windows can be found in the Docker settings

**Comment by Naramsim** [comment]
> ZAP-ProxyThread-20] WARN org.zaproxy.zap.extension.api.API - Request to API URL http://127.0.0.1:8090/UI from 172.17.0.1 not permitted

I can see anyway that here you manage to contact successfully ZAP. It is ZAP that drops the request. Try drop this part `-config api.addrs.addr.name=172.17.0.* ` I dont use it on windows

**Comment by V1Reddy** [comment]
@Naramsim 
I tried starting ZAP without the `-config api.addrs.addr.name=172.17.0.*` and still couldn't reach the container from the host browser and I am running this on mac.

**Comment by V1Reddy** [comment]
Looks like this is a known issue with Docker on Mac - https://docs.docker.com/docker-for-mac/networking/#known-limitations-use-cases-and-workarounds

I am trying some workarounds using the reverse proxy through Nginx, not sure if that will work.

Meanwhile, if anyone knows of an alternative, pls do share.

**Comment by jonvel** [comment]
The following works for me:
`docker run -i -d -p 8080:8080 -e ZAP_KEY=foobarbaz owasp/zap2docker-bare sh -c "./zap.sh -cmd -addonupdate > zapoutput.out && ./zap.sh -daemon -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true -config api.key=\${ZAP_KEY} -host 0.0.0.0 -port 8080 >> zapoutput.out 2>&1"`
on my Mac (10.12.x) with docker `Docker version 17.12.0-ce, build c97c6d6`.  Note the key was I had to also include the `-config api.addrs.addr.regex=true`.  When I used `-config api.addrs.addr.name=172.17.0.*`, I saw several logs in the container that looked like `Request to API URL http://localhost:8080/ with host header localhost not permitted` when I tried to get there with my browser.  Changing it to _wide open and dangerous_ `api.addrs.addr.name=.*` seems to have alleviated that.  "When in doubt, run it as root and disable all security".

If there was a way to set multiple `api.addrs.addr.name` (or come up with a clever-er regex to do that), then that might be a solution to add `127.0.0.1` and `172.17.0.*`.  That last bit is pure speculation on my part.

**Comment by thc202** [comment]
It might have to do with Docker configurations then, because in the initial logs it did log accesses but not in the latest reports. (The problem does not seem related to configurations in ZAP.)

It's possible to add multiple entries, e.g.:
`-config api.addrs.addr(0).name=172.17.0.* -config api.addrs.addr(0).regex=true`
`-config api.addrs.addr(1).name=127.0.0.1`

But it's also possible to add one that includes all, e.g.:
`-config api.addrs.addr.name=(172.17.0.*|127.0.0.1|localhost) -config api.addrs.addr.regex=true`

**Comment by V1Reddy** [comment]
Hi @jonvel ,
Thanks for your reply!
`docker run -i -d -p 8080:8080 -e ZAP_KEY=foobarbaz owasp/zap2docker-bare sh -c "./zap.sh -cmd -addonupdate > zapoutput.out && ./zap.sh -daemon -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true -config api.key=\${ZAP_KEY} -host 0.0.0.0 -port 8080 >> zapoutput.out 2>&1"`
The above command lets the mac access the API through the localhost and 127.0.0.1 from a browser which it wasn't earlier. The difference I noticed was to provide a 'api.key' to zap rather than disable it in the config.
Although, it still doesn't let the traffic through the host when the browser uses local IP of the docker image as http://172.17.0.2/UI which is what I am trying to resolve. 

@thc202 ,
I tried both the config patterns but none of them worked. It kept complaining on the '(' parentheses although I escaped them. I didn't get much time to look into it. I will try again this weekend and let you know if it worked.

Thanks again for all your responses!

**Comment by YoussefKaib** [comment]
@V1Reddy worked for me too thank you!

**Comment by itsecforu** [comment]
@V1Reddy where can I find this api key?

**Comment by psiinon** [comment]
https://www.zaproxy.org/faq/why-is-an-api-key-required-by-default/

**Comment by kingthorin** [comment]
Seems like this was all explained above.
