### ISSUE TITLE
Does ZAP scan for Input Validation vulnerabilities in API calls using JSON, SOAP, XML

### ISSUE THREAD

**Issue by ch1c0hacker** [zaproxy/zaproxy#4490]
POST body of a JSON request would look like
{param1:value1,param2:value2,param3:{param4:value4,param5:value5},param6:value6}

POST body of a SOAP/XML request would look like
`<?xml version="1.0" encoding="UTF-8"?>
<request   param1=value1 param2=value2>
<app param3=value3>
<app_string1>string1</app_string1>
<app_string2>string2</app_string2>
</app>
...`

Can ZAP scan for Input Validation issues like XSS, SQLInjection in these types of requests as well?

**Comment by psiinon** [comment]
Please ask questions on the ZAP User Group: https://groups.google.com/group/zaproxy-users. 
We like to keep issues for problems and enhancement requests.

**Comment by ch1c0hacker** [comment]
Okay, Thank you.
