### ISSUE TITLE
Mapping between ASVS and ZAP

### ISSUE THREAD

**Issue by xBowns** [zaproxy/zaproxy#4492]
Hi,

currently I use a few tools to perform automated security test. One of these tools is ZAP. Since I have to cover as many ASVS requirements as possible with these tools, I am interested in how many requirements only ZAP can cover. Has someone already created a mapping or something similar? Unfortunately I don't have the necessary knowledge about ZAP to create an exact mapping. 
Can someone please help me? I would be very grateful.

Many thanks and greetings

**Comment by kingthorin** [comment]
I'm not aware of any effort to create a mapping, however, you might find some interest via the ZAP User Group https://groups.google.com/group/zaproxy-users.

This provides some mapping vs. the OWASP Top 10: https://www.owasp.org/index.php/ZAPpingTheTop10

**Comment by kingthorin** [comment]
No further user input in over a week, closing.
