### ISSUE TITLE
Manual Request Editor submits original request instead of edited values

### ISSUE THREAD

**Issue by r8tor** [zaproxy/zaproxy#4500]
Hi ZAP Team, 

I thinks I discovered an issue when trying to test for privilege escalation by manipulating a request and swapping an unprivileged session ID into a request that was originally from a application admin.

I found it weird that all my tests worked without exception(it is never that easy :P)

The issue is as the title describes, ZAP does not submit an edited request when you try to tamper with it in the request editor. It actually sends the original request with all the original values.
I was able to reproduce this across multiple restarts(OS and ZAP), reinstalled  ZAP, etc. nothing seems to solve it. I wasn't able to test this on a different computer, so I really hope it is not one of those things that only happens on my computer.

The version I'm using is: 2.7.0
The OS I'm using is OSX 10.13.3 (17D102) on a MacBook Pro.
My Java version is:
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

Steps to reproduce.
1) Select a request on request history and click "Open/Resend with Request Editor"
2) Edit the value of the session cookie to something else
3) Submit request
4) Check newly added(last) record on request history. The value of the cookie submitted is in fact the same as the original request instead of the value you modified on step 2.

Let me know if there is anything I can help with or if you need any additional information.

Cheers, 
R8tor,

**Comment by thc202** [comment]
Any exception in the log/output? It could be #4235, if not it seems to me this is caused by the cookie jar in use in the Manual Request Editor, which overwrites the changes done to the cookies. I believe there's already an issue for this... I'll recheck.
You could try enable the option "Connection > Enable (Global) HTTP Sate " and try resending it, that should disable the cookie jar (if the cookie [1] is not selected).

[1] https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsMan_req#-use-current-tracking-session

**Comment by r8tor** [comment]
So I tried playing with the "Use Current Tracking Session" after enabling
"Global HTTP State" without much success.

I couldn't notice any difference between having that enabled or disabled.

One thing that is important to notice is that the application I'm working
on will set a new cookie value for every request..(Every response has a
Set-Cookie header), so this might be throwing the cookie tracker off.

I will try to reproduce with regular/session cookie to see if the same
issue is happening.

**Comment by thc202** [comment]
I should have mentioned that you need to close/open the dialogue for the option to take effect, the issue (#1161) was fixed recently though. It's available in the weekly releases:
https://github.com/zaproxy/zaproxy/wiki/Downloads#zap-weekly

**Comment by kingthorin** [comment]
No further user input in over 3 weeks. Closing.
