### ISSUE TITLE
JxBrowser 6.20 released

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#4504]
Release notes: https://jxbrowser.support.teamdev.com/support/discussions/topics/9000041742

:zap: https://mozilla.logbot.info/websectools/20180307#c14416643

**Comment by kingthorin** [comment]
6.20 is out now.
https://jxbrowser.support.teamdev.com/support/discussions/forums/9000110576

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#1666.
