### ISSUE TITLE
Allow to upload scripts through the API

### ISSUE THREAD

**Issue by Naramsim** [zaproxy/zaproxy#4512]
Hello, 

first of all thanks for your software. I'm using it extensively at work.

I think that a nice feature to help us deploy Zaproxy in production in the cloud would be to allow the APIs to upload scripts (zest/nashorn/standalone/proxy...). Since, as of now, when we want to load a script into Zaproxy using the APIs it has to be on the same disk where Zaproxy is installed.

Thanks

**Comment by thc202** [comment]
Merging into #4512, which is more generic.
