### ISSUE TITLE
AuthenticationScript (Python, Ruby, Groovy) does not work

### ISSUE THREAD

**Issue by denniskniep** [zaproxy/zaproxy#4515]
Creating a new AuthenticationScript (Python, Ruby or Groovy) that misses the Methods `getLoggedInIndicator` and `getLoggedOutIndicator`. Fails when it gets loaded. 
Because it tries to first load `AuthenticationScriptV2`. Some ScriptEngines do not verify if all Interface Methods are contained in the script. Some ScriptEngines (Python, Ruby, Groovy) loads successfully AuthenticationScriptV2. But without the methods `getLoggedInIndicator()` `getLoggedOutIndicator()`.
Than an exception occures when the methods are invoked. Exception depends on the ScriptEngine but something like `MethodNotFoundException`

The ScriptEngine JavaScript has no problems, because it does some verification in the `getInterface()` Method. That kind of verification are not implemented by the other ScriptEngines.

**Comment by denniskniep** [comment]
@thc202 can you assign this to me?

**Comment by thc202** [comment]
Done.
