### ISSUE TITLE
Ajax Spider doesn't establish WebSocket connections

### ISSUE THREAD

**Issue by ManosMagnus** [zaproxy/zaproxy#4521]
I am trying to discover websocket connection in [DVWS](https://github.com/interference-security/DVWS/) but I can't.
Ajax Spider navigate and fill the fields properly in the Web app but nothing appears neither in site tab nor in WebSocket tab. I also checked the server I host DVWS and none of the messages and connections have been transmitted via websocket.

**Comment by psiinon** [comment]
Thanks for reporting this. Definitely something we need to look into soon.

**Comment by kingthorin** [comment]
Do you see WebSocket use in the browser dev tools when doing the same actions in DVWS?

**Comment by thc202** [comment]
I think AJAX Spider's proxies are not wired with WebSocket's persistent connection handler.

**Comment by kingthorin** [comment]
@ManosMagnus did you try the normal spider? What if you just proxy while using the DVWS manually?

**Comment by ManosMagnus** [comment]
In console

```
csrf.php
{"npass":"","cpass":""}
csrf.php:174:5
InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable
csrf.php:175
{"npass":"","cpass":""}
csrf.php:174:5
InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable
csrf.php:175
Navigated to http://83.212.100.19/DVWS/blind-sql-injection.php

```

In Network -> WS panel in firefox I get only requests and responses with status code 200

**Comment by ManosMagnus** [comment]
I tried also with normal spider but nothing at all. When I navigate manually in DVWS with proxy all works fine

**Comment by thc202** [comment]
That's expected for the normal spider (it does not check for ws URIs, nor does it execute JavaScript).

**Comment by psiinon** [comment]
Notes c/o @thc202 : 

> it should just require changes in ajax spider, in the SpiderThread we should add the ExtensionWebSocket as a PersistentConnectionListener to the proxy (now that should be dynamic to account for un/installation of the WebSocket add-on) that would be similar to the changes done for quick start
