### ISSUE TITLE
Basic HTTP Authentication using Python API

### ISSUE THREAD

**Issue by leisipeisi** [zaproxy/zaproxy#4537]
Hi everyone,

for reference: I already posted my question [here](https://groups.google.com/forum/#!topic/zaproxy-users/h3o5LO38U-s) but it seems that nobody could help me.

I am currently trying to spider a Website which uses a Basic HTTP Authentication. When I am doing this via the GUI and using a HTTP Request from the proxy which uses the authentication already as a starting point to set my context and add the credentials, everything works fine. But if I want to do this using the Python API the authentication does not work. This means that the sent requests do not contain the Basic Authentication information. In Addition I have the same issue in the GUI when I use a HTTP Request which does not have the authentication inside as a starting point. How could I make it work throught the API? Do I somehow need to create a Request already using the authentication or something?
Please find my code and one of the resulting Requests in the following:
```
        api_key = "myapikey"
        dst = "192.168.101.22"
        my_zap = ZAPv2(apikey=api_key)
       
        my_zap.urlopen(str(dst))
        time.sleep(2)

        context_name = "my_context"
        context_id = my_zap.context.new_context(context_name)

        scope = "\Q"+ dst + "\E.*"
        my_zap.context.include_in_context(context_name, scope, api_key)
        my_zap.context.include_in_context(context_name, dst, api_key)
        my_zap.context.include_in_context(context_name, dst + ".*", api_key)
        my_zap.context.set_context_in_scope(context_name, True, api_key)

        # I don't know if this is necessary
        my_zap.sessionManagement.set_session_management_method(context_id, "httpAuthSessionManagement", None, api_key)

        print(my_zap.authentication.set_authentication_method(context_id, "httpAuthentication", "hostname="+dst+"&realm=""&port=80", api_key))

        print(my_zap.authentication.set_logged_in_indicator(context_id, 'Welcome', api_key))
        print(my_zap.authentication.set_logged_out_indicator(context_id, 'Unauthorized', api_key))
           
        user_id = my_zap.users.new_user(context_id, "user", api_key)
        my_zap.users.set_authentication_credentials(context_id,user_id,"username=myusername&password=mypassword",api_key)

        my_zap.users.set_user_enabled(context_id, user_id, True, api_key)

        my_zap.forcedUser.set_forced_user(context_id, user_id, api_key)
        my_zap.forcedUser.set_forced_user_mode_enabled(True, api_key)

        scanid = my_zap.spider.scan_as_user(context_id, user_id, dst, None, True, None, api_key)
```

In the log of ZAP I find the following:
```
       INFO org.zaproxy.zap.spider.Spider - Scan will be performed from the point of view of User: user
```
One of the Requests sent by ZAP is the following:
```
      GET / HTTP/1.1
      Accept: */*
      Connection: keep-alive
      User-Agent: python-requests/2.18.4
      Host: 192.168.101.22
```
It includes no Basic Authentication and that is why the response will always be a 401 - Unauthorized.

Any help is really appreciated!!

**Comment by thc202** [comment]
> I already posted my question here but it seems that nobody could help me.

Sometimes the posts go unnoticed, feel free to bump them when that happens.

The problem is most likely in the URL included in scope, it should also have the scheme, e.g.:
`scope = "http://\Q"+ dst + "\E.*"`

> I don't know if this is necessary

Yes, it should be selected that authentication session management method.

The URL specified when starting the spider must have the scheme too.
(Note that you don't need to enable Forced User mode when spidering with a user.)

**Comment by leisipeisi** [comment]
Thank you so much for your fast reply and help!

I changed my code to
```
scanid = my_zap.spider.scan_as_user(context_id, user_id, "http://\Q"+ dst + "\E.*", None, True, None, api_key)
```
Now it says the following, even if I included the same url in the context using
```
scope = "\Q"+ dst + "\E.*"
my_zap.context.include_in_context(context_name, scope, data['api_key'])
```
```
6809 [ZAP-ProxyThread-14] WARN org.zaproxy.zap.extension.api.API  - Bad request to API endpoint [/JSON/spider/action/scanAsUser/] from [127.0.0.1]:
The provided url is not in the required context (url_not_in_context) : url
	at org.zaproxy.zap.extension.spider.SpiderAPI.scanURL(SpiderAPI.java:455)
	at org.zaproxy.zap.extension.spider.SpiderAPI.handleApiAction(SpiderAPI.java:253)
	at org.zaproxy.zap.extension.api.API.handleApiRequest(API.java:431)
	at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(ProxyThread.java:456)
	at org.parosproxy.paros.core.proxy.ProxyThread.run(ProxyThread.java:317)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by thc202** [comment]
When starting the spider it should be just the URL, `"http://" + dst`.

**Comment by leisipeisi** [comment]
I believe I am not able to follow you, sorry. I now have the following settings:

```
my_zap.context.include_in_context(context_name, "\Q" + dst + "\E.*", api_key)
my_zap.context.include_in_context(context_name, "http://\Q" + dst + "\E.*", api_key)
my_zap.context.include_in_context(context_name, dst, api_key)
my_zap.context.include_in_context(context_name, dst + ".*", api_key)
```
And:
```
scanid = my_zap.spider.scan_as_user(context_id, user_id, "http://" + dst, None, True, None, api_key)
```

The result is, that I see the info in the log that the user is used and that it has been authenticated, but the credentials are not used for the spider process. Is it possible that I am including too much things in the context?
Thank you for your help!

**Comment by thc202** [comment]
It should be enough with:
`my_zap.context.include_in_context(context_name, "http://\Q" + dst + "\E.*", api_key)`
but adding the other entries would not prevent the user from authenticating correctly.

Assuming the user credentials are correct it should be already working.
Could you enable debug logging in ZAP?
In `log4j.properties` file in ZAP home dir[1] change the line:
`log4j.logger.org.apache.commons.httpclient=ERROR`
to:
`log4j.logger.org.apache.commons.httpclient=DEBUG`

it will then log the HTTP authentication attempts.


[1] https://github.com/zaproxy/zaproxy/wiki/FAQconfig

**Comment by leisipeisi** [comment]
Thank you for this suggestion, I will try it tomorrow!

**Comment by leisipeisi** [comment]
Thank you for your help, with the debug mode I found the problem: When setting the authentication method, I had given the URL including http:// and not the ip address. After changing this, it works. Thanks again!

**Comment by thc202** [comment]
Great, thanks for letting us know!
