### ISSUE TITLE
Spider/Active scans on Rest APIs

### ISSUE THREAD

**Issue by ssnmworld** [zaproxy/zaproxy#4539]
Hi - I am trying to run scans on Rest APIs - Basically using the Junit test cases to record the URLs and runs the spider/active scans on them.

https://github.com/zaproxy/zaproxy/wiki/ApiDetailsActions - I am using the URL approach using the zap gradle plugin. 

But is there any way to tell the scans, the url is a REST API url, rather than a web site - so the vectors can be applied accordingly ? 

Thanks

**Comment by psiinon** [comment]
Please dont ask question as issues, the User Group is a much better place for them: https://groups.google.com/group/zaproxy-users
