### ISSUE TITLE
ATTACK Mode Enablement Suggestion

### ISSUE THREAD

**Issue by davewichers** [zaproxy/zaproxy#4548]
I like the idea of this new feature but find it a bit confusing. When you enable it, it essentially asks if you want it to be enabled, and that's fine. But if you say 'no', it still looks like it is enabled, but I don't think it actually is. Am I understanding this right?

I would think it would be more clear if the warning language was essentially: "Do you want to enable ATTACK Mode? This means ...". And if the user says 'no', then the mode reverts to what was previous enabled.

**Comment by thc202** [comment]
The attack mode is always enabled when selected (it's only disabled when changed back to other mode). That question is to know if you want existing nodes to be rescanned when the scope changes.

**Comment by davewichers** [comment]
OK. Thanks for the explanation but I'm still unclear on a few things. The
actual text is: "Rescan all of the nodes when scope changes? If you select
this option then ZAP will scan all nodes current in scope and will rescan
all of the nodes in scope if the scope changes."  I think the main issue is
that I simply don't understand what Scope is.  Scope isn't mentioned
directly in any of the main menu items that I can see. There is a 'Show
only URLs in Scope' button in the Site pane, but when I click it, the
entire site tree disappears.

1) Does that mean there is nothing in Scope by default?
2) If you say Yes to the Attack mode question (above), will it scan
anything under the default scope (if nothing is included)?
3) Is Context and Scope the same thing? If not, how are they related? In
the Context tree you can 'Remove from Scope' but in the Sites tree you can
'Include in Context'. I don't see an 'Add to Scope' feature, but maybe
Include in Context is that.

Sorry I'm so confused.

I also suspect many people like me don't set the Context so the ATTACK mode
change question about Scope would be confusing to them as well, as they
don't understand what it means.

-Dave

**Comment by kingthorin** [comment]
> 1) Does that mean there is nothing in Scope by default? 

Yes, exactly.

> 2) If you say Yes to the Attack mode question (above), will it scan anything under the default scope (if nothing is included)? 

The Default Context (scope) doesn't contain anything (unless the user has configured it), so there would be nothing to scan.

> 3) Is Context and Scope the same thing? If not, how are they related? In the Context tree you can 'Remove from Scope' but in the Sites tree you can 'Include in Context'. I don't see an 'Add to Scope' feature, but maybe Include in Context is that.

Scope == all resources that are part of configured Contexts

https://github.com/zaproxy/zap-core-help/wiki/HelpStartConceptsScope

**Comment by davewichers** [comment]
OK. I played with this a bit, and your answers are helpful. I think when
switching to 'Attack' mode, it might be helpful if ZAP explained, when this
is the case, that there is nothing currently in the Active scope so
switching to this mode won't do anything. And then either explain how to
add something to the scope, or even better, take them through a little
wizard that helps them add the application(s) of interest to the scope
(probably just one).
