### ISSUE TITLE
Add support for OpenAPI 3.0

### ISSUE THREAD

**Issue by thomasdejagere** [zaproxy/zaproxy#4549]
When trying to import an OpenAPI 3.0 .json file, using the OpenAPI extension, I receive the error 'Failed to parse OpenAPI definition'. Is there support for the OpenAPI 3.0 type?

**Comment by thc202** [comment]
As mentioned in the PR, version 3.0 is not yet supported.

@kingthorin, @psiinon should we update to the RC or wait for final version of swagger-parser 2.0.0?

**Comment by thomasdejagere** [comment]
@thc202  Do you have an idea when support for version 3.0 will be added?

**Comment by kingthorin** [comment]
> @kingthorin, @psiinon should we update to the RC or wait for final version of swagger-parser 2.0.0?

I think it's a level of effort trade-off. If it's a 10min job then go for it I guess. If it's gonna take hours then it may as well wait. For my 2 cents anyway.

**Comment by psiinon** [comment]
:+1:

**Comment by kingthorin** [comment]
OpenAPI 3.0 became official at the end of July (2018): https://swagger.io/blog/news/announcing-openapi-3-0/

**Comment by Edza** [comment]
I have some problems importing C# interfaces with nullable types. OAS 3.0 supports nullable. This might be an additional reason to prioritize this.

**Comment by mxbrandi** [comment]
:+1:

**Comment by pexus** [comment]
Is there any sample OpenAPI 2.0 project that can be used to test the OpenAPI scanning?

**Comment by kingthorin** [comment]
> Is there any sample OpenAPI 2.0 project that can be used to test the OpenAPI scanning?

https://github.com/OAI/OpenAPI-Specification/tree/master/examples/v2.0/json?

**Comment by coobr01** [comment]
Its been a year, any updates?

**Comment by kingthorin** [comment]
Sadly no. No one has taken interest in addressing this.

**Comment by kingthorin** [comment]
@coobr01 you could always put a bounty on it and see if that spurs any action:
https://www.bountysource.com/issues/56391491-add-support-for-openapi-3-0

**Comment by dsever** [comment]
I'm also very interested in OpenAPI 3 support, maybe for now is there kid of workarround?

**Comment by mxbrandi** [comment]
> I'm also very interested in OpenAPI 3 support, maybe for now is there kid of workarround?

Hi dsever, as a workaround, you can use an API converter tool (e.g., [api-spec-converter](https://www.npmjs.com/package/api-spec-converter)) to convert your OpenAPI v3 spec to swagger v2 and finally import this in ZAP. This worked for me.

**Comment by dsever** [comment]
@mxbrandi,

I was looking for something like that, I will give a  try.

Tnx

**Comment by secdevmx** [comment]
Hello,
We have Added support for OpenAPI 3.0 and tested it locally. The changes are big, so before making a pull request we would like to get some feedback, especially whether this should be merged or released as a new addon. 
@psiinon @kingthorin @thc202 can anynone please take a look at the [new code](https://github.com/secdevmx/zap-extensions/pull/1/commits/2c595c45eeb27247fb731fcf76fdf75a7e507efe).

Thanks,
 [Murex](https://www.murex.com) security team

**Comment by psiinon** [comment]
@secdevmx thats great! We'll look at your changes asap.
Thanks for taking this on.

**Comment by dsever** [comment]
Great work!

**Comment by psiinon** [comment]
@secdevmx sorry for the delay - we've been distracted by other things :/
A PR to the existing repo would be great - I dont think theres any reason to make this a new add-on. Thanks for your patience.

**Comment by ntharalla** [comment]
OpenAPI v3.0 support would be great

**Comment by pauldzy** [comment]
Both OpenAPI 3.0 and Swagger 2.0 are complex systems that share a lot of concepts but not a lot of common structure.  Asking folks to learn 2.0 just to create documents for input to ZAP is a bummer.  I'd rather encourage colleagues to put their time and energy into OpenAPI 3.0.

**Comment by kingthorin** [comment]
> Asking folks to learn 2.0 just to create documents for input to ZAP is a bummer.

I'm not aware of us doing that. Someone in the community may have suggested that as a work around.

Also to be clear, Swagger vs OpenAPI: one is a spec, one is a tool implementing the spec. Chances are throughout the history of this issue/ticket they've been used improperly.

https://swagger.io/blog/api-strategy/difference-between-swagger-and-openapi/

Anyway, the good news is that as you can see in the history of this issue a Pull Request adding OpenAPI v3 support was opened just under a month ago. It's a non-trivial change, it's been through one review, we know it's functionality many are interested in.
