### ISSUE TITLE
Investigate usage of RE2/J in Wappalyzer add-on

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#4566]
Investigate if [RE2/J](https://github.com/google/re2j) works faster (and still accurate) than `java.util.regex.Pattern` in Wappalyzer add-on. There are 293 occurrences of the logical operator or (`|`) in the regular expressions...

From a quick check there's one entry that fails (it would have to keep using `java.util.regex.Pattern`):
```JSON
"Zeuscart": {
  "cats": [
    "6"
  ],
  "html": "<form name=\"product\" method=\"post\" action=\"[^\"]+\\?do=addtocart&prodid=\\d+\"(?!<\\/form>.)+<input type=\"hidden\" name=\"addtocart\" value=\"\\d+\">",
  "icon": "Zeuscart.png",
  "implies": "PHP",
  "url": "\\?do=prodetail&action=show&prodid=\\d+",
  "website": "http://zeuscart.com"
}
```
with:
```
Invalid pattern syntax <form name="product" method="post" action="[^"]+\?do=addtocart&prodid=\d+"(?!<\/form>.)+<input type="hidden" name="addtocart" value="\d+">
com.google.re2j.PatternSyntaxException: error parsing regexp: invalid or unsupported Perl syntax: `(?!`
	at com.google.re2j.Parser.parsePerlFlags(Parser.java:1146)
	at com.google.re2j.Parser.parseInternal(Parser.java:828)
	at com.google.re2j.Parser.parse(Parser.java:805)
	at com.google.re2j.RE2.compileImpl(RE2.java:185)
	at com.google.re2j.Pattern.compile(Pattern.java:135)
	at com.google.re2j.Pattern.compile(Pattern.java:123)
	at org.zaproxy.zap.extension.wappalyzer.ExtensionWappalyzer.strToAppPattern(ExtensionWappalyzer.java:266)
```

References:
 - https://github.com/zaproxy/zap-extensions/tree/alpha/src/org/zaproxy/zap/extension/wappalyzer
 - https://github.com/zaproxy/zap-extensions/blob/alpha/src/org/zaproxy/zap/extension/wappalyzer/resources/apps.json
 - https://github.com/google/re2j#caveats
 - https://github.com/google/re2/wiki/Syntax

**Comment by thc202** [comment]
Yes, that should work. The one in the extensions repo.

**Comment by kingthorin** [comment]
Oh then my first reply is wrong because I literally removed the one problem pattern.

**Comment by psiinon** [comment]
Just tried this, using re2j where possible and falling back to the java implementation.
I've implemented an option where you can run the 2 side by side and it will log the times of each and if they agree.
The stats from my first run are:
```
"stats.wappalyser.justr":"4",
"stats.wappalyser.no_r_pattern":"66",
"stats.wappalyser.same":"66945",
"stats.wappalyser.time_java":"515299",
"stats.wappalyser.time_re2j":"109906"
```
ie re2j is significantly faster than java, they nearly always agree (66k vs 4) and re2j could be used in all but 66 cases.
On this basis I'll submit a PR for my changes with the test code present but not actually used.

**Comment by thc202** [comment]
Done in zaproxy/zap-extensions#1670.
