### ISSUE TITLE
Data size limit exceed and Java heap memory size exceed

### ISSUE THREAD

**Issue by thinksabin** [zaproxy/zaproxy#4584]
hi,

I'm using owasp zap in the CI process using zap api and selenium. The problem i'm facing is the exceed of java memory and data size limit. 
<img width="733" alt="screen shot 2018-04-11 at 11 11 35 am" src="https://user-images.githubusercontent.com/6102027/38597847-95d8564a-3d79-11e8-8983-459c886c224a.png">

i'm using python library zapv2 for api calls and scans. So far the case is I already have to start owasp zap in background before running api calls. similar to this example: https://github.com/zaproxy/zaproxy/wiki/ApiPython

can this issue of memory be mitigated ?

One way i thought is to restart zap application but this option might not be good in the CI process. 

Help :)

**Comment by psiinon** [comment]
How long are you running ZAP for?
Is it just for scanning one app or multiple ones?
FYI that limit is set here: https://github.com/zaproxy/zaproxy/blob/develop/src/db/zapdb.script#L25 so you could just try increasing it..

**Comment by psiinon** [comment]
ZAP isnt really designed for running for days on end.
Right now I'd recommend starting a new ZAP instance for every application that you scan.
We do have a 'low memory' mode but this is experimental so if you do want to use it make sure you test it to make sure it does what you need. And let us know if it does work for you :)

**Comment by thinksabin** [comment]
:)
thanks. I will check into it.

**Comment by kingthorin** [comment]
@thinksabin anything further on this?

Memory (heap) warnings will be coming via: https://github.com/zaproxy/zaproxy/issues/3486

**Comment by thinksabin** [comment]
hi,
well i did increase the cache limit size as suggested by psiinon. But more importantly I have scope down the web application coverage within the  automation where I'm using selenium and starting new instance of zap every time.
To confirm on the java memory issue, please give me few days. I will test and try to replicate. May be i can try a new zap nightly or weekly build ?

Thanks

**Comment by kingthorin** [comment]
@thinksabin you seem to have confirmed in a previous update that you've worked around the issue, can this be closed?

**Comment by thinksabin** [comment]
@kingthorin Yes, i think this issue can be closed relating to the fact as @psiinon "ZAP isnt really designed for running for days on end." The work around does work but primarily the scope of the scan have to be managed by the user.

Thanks everyone for support  👍

**Comment by mikilino** [comment]
How do I increase the cache?
Thank you

**Comment by kingthorin** [comment]
IIRC you can only change it in the [weekly](https://github.com/zaproxy/zaproxy/wiki/Downloads#zap-weekly). ex: `ZAP_D-2018-05-08\db\zapdb.script`

**Comment by mikilino** [comment]
Thank you!
