### ISSUE TITLE
Scan for more hidden files

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#4585]
For example, see https://blog.hboeck.de/archives/892-Introducing-Snallygaster-a-Tool-to-Scan-for-Secrets-on-Web-Servers.html
We already scan for some of the files it looks for but not all.
We could have a new scan rule whcih just looks for files in fixed location (ie relative to the root) and have these defined in a text file to make it really easy to extend.
If we also had a policy just including rules that look for hidden files then it would be easy to just scan for those for a site from the command line.

**Comment by psiinon** [comment]
Note that the config file (csv, tsv, xml, json?) should include info like:

- File path
- Contents regex (to confirm its valid, if possible)
- User friendly desc + links for reporting

**Comment by NamanArora** [comment]
Hello. I would like to take up this issue. Can anyone tell me where to begin?

**Comment by psiinon** [comment]
Hi @NamanArora - start by getting a ZAP development environment set up, as per https://github.com/zaproxy/zaproxy/wiki/Building
This feature should be implemented as a passive scan rule, so next have a look at https://zaproxy.blogspot.com/2014/04/hacking-zap-3-passive-scan-rules.html
Try implementing a very simple passive scan rule that just writes something to the ZAP log - that way you can tell if your code is being run.

**Comment by kingthorin** [comment]
I believe it would actually need to be an active to request specific paths:
https://zaproxy.blogspot.com/2014/04/hacking-zap-4-active-scan-rules.html

Similar to:
- https://github.com/zaproxy/zap-extensions/blob/alpha/src/org/zaproxy/zap/extension/ascanrulesAlpha/ElmahScanner.java
- https://github.com/zaproxy/zap-extensions/blob/alpha/src/org/zaproxy/zap/extension/ascanrulesAlpha/EnvFileScanner.java
- https://github.com/zaproxy/zap-extensions/blob/alpha/src/org/zaproxy/zap/extension/ascanrulesAlpha/TraceAxdScanner.java

(Based on https://github.com/zaproxy/zap-extensions/blob/alpha/src/org/zaproxy/zap/extension/ascanrulesAlpha/AbstractAppFilePlugin.java)

**Comment by psiinon** [comment]
Yeah, you're right of course :)

**Comment by NamanArora** [comment]
Thank you for your response. I have the dev environment setup and was able to successfully run my own passive scanner that logs in data randomly. Will try creating a active scan rule now before actually getting started with the issue.

**Comment by NamanArora** [comment]
Hello. I have pushed my code for the hidden scanner. Please go through it over here and let me know of the required changes: https://github.com/zaproxy/zap-extensions/pull/1968

**Comment by kingthorin** [comment]
Todo: 
- [ ] Add Unit Tests
- [ ] Consider implementing support for checking byte arrays in responses (could use HexString handling similar to Replacer).
- [ ] Consider implementing support for "not" conditions in content checks.
