### ISSUE TITLE
ZAP API converts data to wrong format

### ISSUE THREAD

**Issue by javixeneize** [zaproxy/zaproxy#4590]
Hi

I did open a bug the other day about json compatibility in post requests #4580 

I have seen another bug related to this. When the ZAP API (in python) returns that data, the JSON is formatted as a dictionary instead of having a JSON format

So, if the post body was {"name": "test", "id":"1"}

The API returns this data as {'name': 'test', 'id':'1'}

And therefore, it is not recognised as a JSON anymore

**Comment by thc202** [comment]
Which API endpoint did you use?

**Comment by javixeneize** [comment]
core.messages

**Comment by thc202** [comment]
Thanks.

**Comment by javixeneize** [comment]
Great news! Any idea when will this be released?

Thanks

**Comment by thc202** [comment]
No exact data for the main release (2.8.0), but it will be included in the next weekly.
