### ISSUE TITLE
False prediction over IP finding 

### ISSUE THREAD

**Issue by rexjazz** [zaproxy/zaproxy#4598]
![owaspreport](https://user-images.githubusercontent.com/5547019/38803613-644c9f88-418d-11e8-8e20-5e6083a6234f.png)

Its stating issue in the report as IP if any number / names it stated in the website . Please check the image for a better understanding  of the issue.  Its falsely stating a file name as IP.

**Comment by kingthorin** [comment]
How about this:
At High Threshold impose a word boundary check at the start and end of the IP pattern (since you're indicating that false negatives are ok). At Medium & Low Threshold leave it as is (will match substrings), which may lead to a few false positives like this.

Keeping in mind that the user can always mark them as False Positive in ZAP or implement an Alert Filter for them (https://github.com/zaproxy/zap-extensions/wiki/HelpAddonsAlertFiltersAlertFilter).

https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsScanpolicy#threshold

**Comment by psiinon** [comment]
👍

**Comment by kingthorin** [comment]
Won't work as I suggested. The regex is already checking word boundaries. I'll try something else.

**Comment by kingthorin** [comment]
Ok I'm open to ideas. I thought about checking the character at `start()-1` and `end()+1` but that isn't really solid. It _might_ be arguably ok at HIGH to check if the preceding character is a period, which is unlikely unless the content is malformed or the match is part of a longer dotted string (as seen here). That can't as easily be argued on the end (it's likely to be a simple period).

I guess 2 character strings could be extracted and checked against `\d\.` (a number followed by period [at the start[) or `\.\d` (a period followed by a number [at the end])? Is that strong enough given that at HIGH threshold the user has indicated some acceptance of False Negatives? [1] Add the check for threshold and the substring match around here: [https://github.com/zaproxy/zap-extensions/blob/7ba9eeaeaea9d1ba5e6292c4a37c1048408a7bd9/src/org/zaproxy/zap/extension/pscanrules/TestInfoPrivateAddressDisclosure.java#L114](https://github.com/zaproxy/zap-extensions/blob/7ba9eeaeaea9d1ba5e6292c4a37c1048408a7bd9/src/org/zaproxy/zap/extension/pscanrules/TestInfoPrivateAddressDisclosure.java#L114) then `continue` if HIGH and one of the start/end conditions is true.

[1] https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsScanpolicy#threshold

**Comment by kingthorin** [comment]
Anyone have feedback or thoughts on this?

**Comment by psiinon** [comment]
This might be one where we have to access false positives can happen.
If the string that really is a valid internal IP address but just doesnt happen to be in the context its used then thats where we need a human to validate it.

**Comment by kingthorin** [comment]
I'm good with that. :+1:

**Comment by kingthorin** [comment]
Will do.

**Comment by thc202** [comment]
Thanks.
