### ISSUE TITLE
Context menu in request and response text-areas behaves as if the mouse pointer was elsewhere

### ISSUE THREAD

**Issue by pqyptixa** [zaproxy/zaproxy#4607]
In ZAP version D-2018-04-04, after resizing (maximizing) the application window and restarting it, when right-clicking in the text area under the "request" or "request and response" tab, the context menu will not respond correctly, and the program will behave as if the mouse pointer was elsewhere (noted by how, sometimes, some buttons in the program menu are highlighted when hovering over the context menu).

How to test: open ZAP, resize the window to a size lower than the max size, then maximize it, and close ZAP. Make sure the file "~/.java/.userPrefs/org/parosproxy/paros/view/prefs.xml" contains the string "MAXIMIZED". Then start ZAP again, go to the "Request" or "Request and response" tab, and right-click on any textarea. Hover over any items and see if the UI changes elsewhere in the program window (it could also happen that the context menu appears elsewhere in the window).

An example of a configuration file that causes the bug is this:
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE map SYSTEM "http://java.sun.com/dtd/preferences.dtd">
<map MAP_XML_VERSION="1.0">
  <entry key="MainFrame.window.position" value="481,10"/>
  <entry key="MainFrame.window.size" value="1242,974"/>
  <entry key="MainFrame.window.state" value="MAXIMIZED"/>
  <entry key="WorkbenchPanel.horizontal.divider.location" value="330"/>
  <entry key="WorkbenchPanel.vertical.divider.location" value="522"/>
</map>
```

Workarounds are:
- to resize the window until the context menu works again
- to close ZAP and delete ~/.java/.userPrefs/org/parosproxy/paros/view/prefs.xml before restarting it 

I'm running LXQt 0.11.1 on Ubuntu 17.10, Java version 1.8.0_162 (happens with Java 9, too). My display is set at 1920x1080. For some reason, this doesn't happen in my laptop that is running KDE 5.12.4 on Ubuntu 18.04, display resolution is 1366x768, Java 8 and 9.

I think the code responsible for saving and retrieving these configurations is in /src/org/parosproxy/paros/view/AbstractFrame.java , but I couldn't find the root cause of this bug. My guess is that window size is not being reported correctly by the system.

Thanks for your work.

**Comment by kingthorin** [comment]
Seems like an LXQt issue, can you try a different desktop manager? (Like KDE...)

**Comment by pqyptixa** [comment]
Yes, it doesn't happen in KDE. It does happen in LXDE too, though.

**Comment by kingthorin** [comment]
Have you opened tickets for those projects?

**Comment by pqyptixa** [comment]
OK, nevermind then. As I was told in the IRC channel, this is probably a problem with the JVM, or the interaction between it and the system, so there isn't much to do.
Anyway, I hope this bug helps someone in the future...
Closing.
