### ISSUE TITLE
Zest "Replace in response-body" doesn't update the Content-Length header

### ISSUE THREAD

**Issue by yuniorb** [zaproxy/zaproxy#4613]
_What steps will reproduce the problem?_

1. Create a custom Zest Script from "Proxy > Replace in response body".
2. Choose a testing environment that sets the "Content-Length" header.
3. Choose some value to be replaced from one arbitrary value of length A with some
arbitrary value of length B (whereas the length differs [A!=B]).
4. As the request is routed through ZAP, the replacement occurs, but the Content-Length
header stays at the original value. If B > A then Firefox cuts off the response body
and ignores everything in the body that exceeds the original Content-Length.

_What is the expected output? What do you see instead?_

Content-Length header should be updated to
length of the modified request. This works fine if you add a breakpoint and inspect the request before sending back.

_What version of the product are you using? On what operating system?_

ZAP 2.7.0, OSX Sierra

_Please provide any additional information below._

This issue is related to https://github.com/zaproxy/zaproxy/issues/1071. According to @thc202 it was an incomplete fix, so creating this defect.

**Comment by thc202** [comment]
Thanks for raising the issue.

In the steps you mention request, that one should be fine, it's the response body that's not, right?

**Comment by yuniorb** [comment]
Good catch, I updated the steps. The content length is the issue, copy pasta error.

**Comment by thc202** [comment]
Thanks.

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#1552.

**Comment by thc202** [comment]
Released in version 28 of Zest add-on.
