### ISSUE TITLE
Add option for custom font in work panels

### ISSUE THREAD

**Issue by oxdef** [zaproxy/zaproxy#4616]
It will be great if ZAP has separate options for font name and font size in HTTP Panel/Editor. Because monospace family font looks better for such purpose.

**Comment by thc202** [comment]
Would make sense to apply this to other works panels (e.g. Script Console)?

**Comment by oxdef** [comment]
Why not...let's rename the option to  "Work Panels Font Name" and apply this  to other works panels. I can do it in https://github.com/zaproxy/zaproxy/pull/4617

**Comment by thc202** [comment]
Cool, issue title updated. Note that some of the work panels are added by add-ons (e.g. Script Console) so they will have to wait for those changes.

**Comment by oxdef** [comment]
It's becoming not small improvement :) Please, assign this ticket on me.

**Comment by thc202** [comment]
Invite sent, you need to accept it to assign the issue to you.

**Comment by oxdef** [comment]
>Note that some of the work panels are added by add-ons (e.g. Script Console) so they will have to wait for those changes.
If there is a list of such work panels somewhere?

**Comment by thc202** [comment]
No, although the main one is the Script Console.

**Comment by oxdef** [comment]
@thc202 Script Console is included in ZAP by default according to https://github.com/zaproxy/zaproxy/wiki/ScriptConsole. In the same time when I try to build ZAP using `ant -f build/build.xml dist` it is disabled (I can't see it in ZAP UI). Could you please tell me how to correctly build ZAP with Script Console switched on?

**Comment by thc202** [comment]
Note that the changes will not be immediately available to add-ons (most likely after/around 2.8.0).

**Comment by oxdef** [comment]
@thc202 I have added the work panels font support to the script console and it looks like everything is done. Final question is how to correctly make PR to https://github.com/zaproxy/zap-extensions? I mean that `zap-extensions/blob/beta/lib/zap-2.7.0.jar` should be updated to make all works.

![workpanels_font_screenshot](https://user-images.githubusercontent.com/3337518/42737949-4d8cbfc4-8884-11e8-8b66-86278ea8dd5d.png)

**Comment by thc202** [comment]
That needs to wait for the core changes (or use reflection for the time being).

**Comment by oxdef** [comment]
Should I make PR to https://github.com/zaproxy/zap-extensions right now with **only** changes in Script console code? What else I need to do to make the issue fixed?

**Comment by thc202** [comment]
This issue will be fixed with just #4617. The add-on changes are not part of this (although related).

If you plan to use reflection it's fine to open a PR now (but might worth waiting for the merge of the previous PR).

**Comment by oxdef** [comment]
@thc202 Do you need any addtional help accodring to this issue?

**Comment by thc202** [comment]
No, need to check the PR.
