### ISSUE TITLE
Enhancement: JWT fuzzer - for active scanner.

### ISSUE THREAD

**Issue by omerlh** [zaproxy/zaproxy#4620]
Many APIs using JWT for authZ/authN. I would like to be able to test how the API implement authN/authZ by fuzzing the JWT - Removing/adding/changing claims, and make sure the API return 401/403 for all invalid JWTs.
The hard part of this implementation is exposing the well-known endpoint. This is required for modifying the JWT - so Zap can sign them, and the API will accept Zap's signature as a valid signature. Somewhat similar to how Zap's handle TLS interception.

**Comment by psiinon** [comment]
Sounds very useful. Is this something you might be able to look at?
If not then any extra details you could supply would be very useful.

**Comment by omerlh** [comment]
I hope to, this is something that is really important to us.

**Comment by psiinon** [comment]
:+1:

**Comment by kingthorin** [comment]
@omerlh have you had any time to look into this?

**Comment by preetkaran20** [comment]
Hi @omerlh , @psiinon , @kingthorin and @thc202  ,

For handling this enhancement we need web application to give one of the below ways :-
1. either giving us a way to upload zap certificate like we do in browser (as @omerlh suggested)
2. or give an API which we can call with the fuzzed payload and it embed private key encrypted hash into the payload and return it.

is there any other approach for handling in this ?

also is there any active scanner addon for OAuth/SAML ? if we have then it can be something similar if not then we can extend this for those too.  

thanks,
karan

**Comment by kingthorin** [comment]
Zap does have a SAML addon that was developed as part of GSoC2013, personally I haven't used it and am not sure what kind of shape it's in.

https://github.com/zaproxy/zap-extensions/tree/master/addOns/saml
https://www.owasp.org/index.php/GSoC2013_Ideas/OWASP_ZAP_SAML_Support

**Comment by preetkaran20** [comment]
thanks @kingthorin. i will look into these links.

**Comment by preetkaran20** [comment]
Hi @kingthorin ,

![image](https://user-images.githubusercontent.com/13570884/68850620-5ff98480-06fa-11ea-85c6-ead1a18bb344.png)
as per the addon, it is written that it doesn't handle signing. is this because of the above problem as mentioned in above comments and by @omerlh .

do you think above approaches mentioned by me can be done in ZAP ? 

thanks,
Karan

**Comment by preetkaran20** [comment]
Hi team,

As discussed over call, best approach is trust store path for now. in case JWT is using HMAC then user has to specify the Key in the ZAP. 

thanks,
Karan

**Comment by preetkaran20** [comment]
Hi team, 
i have created document containing list of issues with JWT implementation by reading from various sources.
Following is the brainstorming document:- https://github.com/SasanLabs/JWTExtension/blob/master/BrainStorming.md

thanks,
Karan

**Comment by preetkaran20** [comment]
Hi @thc202 and @kingthorin ,

While reading about the vulnerabilities, i found that general issues are related to the Storage of JWT tokens in browser and libraries having vulnerabilities like none algorithm etc.

But problem statement of this issue is more towards fuzzing and changing values in JWT and checking how application behaves but my point is as application signed the token with some key and key is only known to the application then trusting that token is absolutely correct and incase application relying on the token values is what it is intended for.

please share your thoughts on fuzzing and any example to explain more on how fuzzing and trusting can be an issue.

thanks,
Karan

**Comment by preetkaran20** [comment]
Hi @thc202 and @kingthorin ,
Gentle reminder regarding above queries.

**Comment by kingthorin** [comment]
Sorry I haven't done any research on this topic.

**Comment by preetkaran20** [comment]
@kingthorin  thanks for the reply.
@omerlh and @psiinon  please share your thoughts about the above queries.

**Comment by preetkaran20** [comment]
Hi @psiinon, @kingthorin and @thc202 ,

I was writing Extension and have one doubt,
There can be scenario that JWT signature is based on HMAC and application is using weak key like smaller than 32 bytes or common  english words then we might need to check that using ZAP extension jwt. So i was thinking of either 2 possibilities
1. Having a dictionary/text file which we will read and try to bruteforce
2. generating some 15 byte strings (byte length input will be given by the user) and try to brute force

what is your take on this ? do you think it will be helpful ? Also do we consider having both or any one ?

thanks,
Karan

**Comment by kingthorin** [comment]
Could you more easily support both by depending on and leveraging the existing fuzzer?

**Comment by preetkaran20** [comment]
Is there any existing fuzzer for this ? can you please point to it. I was thinking of writing one.

**Comment by kingthorin** [comment]
Not specifically for JWT, but the existing fuzzer handles both the scenarios you mentioned (file and generation)

**Comment by preetkaran20** [comment]
sorry little confusion. can you please point to the code so that i can look into it and check how it can work for JWT.  is this Fuzz Addon ?

**Comment by kingthorin** [comment]
Yup: https://github.com/zaproxy/zap-extensions/tree/master/addOns/fuzz

**Comment by preetkaran20** [comment]
thanks @kingthorin i will go through fuzz addon.
I have written some code for the extension in repo: 

https://github.com/SasanLabs/JWTExtension/tree/master/src/main/java/org/zaproxy/zap/extension/jwt please review.

I will add UML's for better understanding sooner.

thanks,
Karan

**Comment by preetkaran20** [comment]
Hi @kingthorin , @thc202  and @psiinon ,

is there any common weak password file in ZAP resources for running bruteforce ?

thanks,
Karan

**Comment by preetkaran20** [comment]
Hi team,

New UI screen which will be added in this enhancement:
![image](https://user-images.githubusercontent.com/13570884/74088458-b4738c80-4abc-11ea-951f-fe5cee3be0af.png)

thanks,
Karan

**Comment by preetkaran20** [comment]
JWT Scanner related PR: https://github.com/zaproxy/zap-extensions/pull/2373

**Comment by preetkaran20** [comment]
Hi Team,

JWT scanner is added to find the common vulnerabilities : https://github.com/SasanLabs/owasp-zap-jwt-addon

I am working on writing JWT Fuzzer now.

thanks,
Karan

**Comment by thc202** [comment]
Closing, the add-on is now available in the marketplace. Thanks @preetkaran20!
Mode information in the blog post: https://www.zaproxy.org/blog/2020-09-03-zap-jwt-scanner/
