### ISSUE TITLE
Zap Attack vectors

### ISSUE THREAD

**Issue by ssnmworld** [zaproxy/zaproxy#4622]
Hi - I am using zap using the zap urls as follows

Spider Scan
http://zap/JSON/spider/action/scan/?zapapiformat=JSON&url=127.0.0.1:8080&recurse=true&inScopeOnly=
http://zap/JSON/spider/view/status/?zapapiformat=JSON

Active Scan
http://zap/JSON/ascan/action/scan/?zapapiformat=JSON&url=127.0.0.1:8080&recurse=true&inScopeOnly=
http://zap/JSON/ascan/view/status/?zapapiformat=JSON

URLs scanned
And finding all the urls in scope using this
"http://zap/JSON/spider/view/allUrls/?zapapiformat=JSON"

I have the following questions.

1. How to specify site authentication parameters in the URL approach for scanning? 
2. How to find out the attack vectors used for scanning, so I can provide a report on what got scanned? 
3. Any other relevant scans that are required to be run in addition to Spiderscan/ActiveScan/AjaxSpiderscan in order to get full benefit of the scanning ? 

Thanks

**Comment by psiinon** [comment]
Please dont ask questions as issues, the User Group is a much better forum for those: https://groups.google.com/group/zaproxy-users
