### ISSUE TITLE
Enhancement - load scripts using the`-cmd` option

### ISSUE THREAD

**Issue by omerlh** [zaproxy/zaproxy#4626]
Currently (unless I'm missing something, my knowledge is based on what I read in the code), the only way to load new script is via the API. It might be easier to load them using the `-cmd` option, in case you want to load a whole folder (which is similar to what the UI is doing). 
Ideally, I want to be able to do:
```
zap.sh -cmd -addscripts <path_to_folder>
```

**Comment by psiinon** [comment]
You can do this via:
zap-sh -config dirs=<path_to_folder>

https://github.com/zaproxy/zaproxy/wiki/FAQconfigValues is your friend here :)
Ok to close this?

**Comment by omerlh** [comment]
Just to make sure I'll follow, because it was not clear from the documentation - any script in this folder will be loaded?

**Comment by thc202** [comment]
Help page for the option: https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsOptionsScript

**Comment by omerlh** [comment]
Yes, that I've already read. So the format should be:
```
<zap_dir>/.script/passive
```
for example?

**Comment by psiinon** [comment]
I think it should be:
```
<full_path>/active/<mutliple_scripts>
<full_path>/passive/<mutliple_scripts>
```
etc

**Comment by omerlh** [comment]
I'll try and reopen and if I'll encounter an issue

**Comment by psiinon** [comment]
Strange - I tried it out with a test dir and that appeared in the desktop GUI, but I didnt try with a real dir containing real scripts. I suggest using the desktop UI for testing - you can still use the API but you can also see whats going on much more easily.

**Comment by omerlh** [comment]
I managed to make it work on the GUI version by putting the scripts under `community-scripts`. It's not working on the docker, probably because the addon is not installed. Anyway, even if I was able to load the script - to enable it I still need an API call...

**Comment by thc202** [comment]
Wouldn't it require an API call in all cases? Or, the scripts would be enabled by default?

**Comment by omerlh** [comment]
Well, I imagine it as one `-cmd` option that load and enable all scripts. 
As I see it, scripts will allow us to easily extend Zap, with rules that are relevant only for us at Soluto. It will be a lot harder if each new script will be loaded by the API, as this will not be part of the docker image...

**Comment by psiinon** [comment]
Yeah, the idea of the scripts dir was to allow people to add a load of scripts they always use.
Would an option to enable them all on startup do the trick?

**Comment by omerlh** [comment]
Yeah, but I would like to only enable my script, not all the community scripts. Does that makes sense?

**Comment by psiinon** [comment]
Ah, right. I was thinking about the case where you bundle a set of scripts.
We could add a cmdline option something like:
```
-addscript /path/to/script.sh;type=passive;enabled=true
```
Thoughts anyone?

**Comment by psiinon** [comment]
good point - if we go down this route then a different separator should be used. '|' maybe?

**Comment by omerlh** [comment]
Yep, or escaping, both can work. But that seems like a good direction :)

**Comment by omerlh** [comment]
Thanks to @thc202, look like simply changing `config.xml` to include something like that:
```
  <dirs>/Users/omerl/scripts</dirs>
  <script>
    <scripts>
      <name>Copy as curl command menu.js</name>
      <description/>
      <engine>Oracle Nashorn</engine>
      <type>extender</type>
      <enabled>true</enabled>
      <file>/Users/omerl/Library/Application Support/ZAP/scripts/templates/extender/Copy as curl command menu.js</file>
    </scripts>
  </script>
```
Could work, I'll try that tomorrow and update.

**Comment by kingthorin** [comment]
> good point - if we go down this route then a different separator should be used. '|' maybe?

Can't use pipe because that's a redirector `ps -ef|grep fred` :zap: But ya I'm sure we can land on something if it's needed.
