### ISSUE TITLE
Do not install/update add-ons if -silent is passed to ZAP in packaged scans

### ISSUE THREAD

**Issue by sebastien-prudhomme** [zaproxy/zaproxy#4633]
zap-api-scan.py, zap-baseline.py and zap-full-scan.py all try to update and install addons.

When using them in a network without internet access, this cause timeouts:

```
57401 [ZAP-cfu] WARN org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate  - Failed to check for updates using: https://raw.githubusercontent.com/zaproxy/zap-admin/master/ZapVersions-dev.xml
java.net.SocketTimeoutException: connect timed out
```

Can you add an option to disable this behaviour?
Thanks

**Comment by adrianer** [comment]
Interestingly: even if removing the "-addonupdate" parameter from the Python scripts, Zap will still run into the same timeout, but only once and not twice as before. Could it be that it also looks for updates for ZAP itself (and not the addons)?

**Comment by kingthorin** [comment]
@adrianer yes.

**Comment by rcooper85** [comment]
I'm experiencing the same issue. Is there a way you can disable -addonupdate?

**Comment by psiinon** [comment]
@rcooper85 try using the `-silent` ZAP option - when used on its own that will definitely prevent these checks, but if its used with them then I'm not so sure. But its worth a try...

**Comment by thc202** [comment]
The `-silent` just prevents automatic check for updates requests not the ones required to install the add-ons.

**Comment by knazanga** [comment]
I tried using weekly release and I've same issue. This issue occurs only when I provide a custom config file with `-c` option, even if this config file is the default config generated when I use `-g` option.

**Comment by psiinon** [comment]
Following a discussion on irc we've decided that not checking for updates if the ZAP `-silent` option is specified is an acceptable approach, even though this changes the behavious on stable.
