### ISSUE TITLE
Error during the start

### ISSUE THREAD

**Issue by Etienne-Lebrard** [zaproxy/zaproxy#4636]
Hi,

I got an issue during the start of the program

When I launch it with .\zap.bat I  got the following error message :

Error: Unable to access jarfile "zap-dev.jar"

**Comment by Etienne-Lebrard** [comment]
How can I know which packet am I using ?

Yhea i'm building it from zaproxy-zaproxy-dcec5e1\src

**Comment by thc202** [comment]
I was suggesting one of the packages available in the downloads page. [1]

Which tasks are you running to build ZAP? From where are you running the zap.bat file?

[1] https://github.com/zaproxy/zaproxy/wiki/Downloads

**Comment by thc202** [comment]
Closing, does not seem to be an issue with ZAP (or its build).

Note that the start up scripts are not expected to be executed from the `src` directory, only from the "installation" directory, which is created after building ZAP. [1]

[1] https://github.com/zaproxy/zaproxy/wiki/Building#ant-no-ide
