### ISSUE TITLE
Packaging request - flatpak

### ISSUE THREAD

**Issue by kurobeats** [zaproxy/zaproxy#4643]
Just wondering if the project would consider packaging in flatpak format and adding to flathub.org.

Instructions found here: https://github.com/flathub/flathub/wiki/App-Submission

**Comment by psiinon** [comment]
Fine by me :)
Do you (or anyone else) have any experience creating flatpak manifests?
Other PRs on that repo dont look too bad but these things take time to put together - if someone can put together a good first attempt then theres a good chance we'll be able to tweak it into something we're happy with.
But I cant see myself haing time to come up with the first version for a while :/

**Comment by kurobeats** [comment]
Took me a while but I taught myself how to build this. For the interested, the manifest etc is here: https://github.com/kurobeats/flathub/tree/org.zaproxy.ZAP

I have submit to flathub.org for addition in their store.

**Comment by thc202** [comment]
Thanks (for tracking the PR is flathub/flathub#1188).

**Comment by kurobeats** [comment]
I'm more than happy to transfer ownership should this be desirable now or at a later date.

**Comment by psiinon** [comment]
This is great!
@kurobeats would you be ok adding myself, @thc202  and @kingthorin to the repo?
We're very happy for this to become a supported platform for ZAP, and for you to continue leading it :)
If its merged then we can add the details to the Downloads page - its very similar to the way we support Homebrew Cask.

**Comment by kurobeats** [comment]
I'd be humbled to continue being involved in this. I've added you all to the repo.

**Comment by psiinon** [comment]
Its great to have you on-board!

**Comment by bilelmoussaoui** [comment]
Hey!
Thanks for your interest on using Flathub to deploy your application. Would it be possible to upstream few things like the appdata (metainfo file used to describe the application to almost any Linux software center there, https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps), the desktop file which is the launcher of the application. Both makes more sense to have upstream here than downstream but that can happen later of course.

**Comment by kurobeats** [comment]
This has now been accepted to flathub.org

**Comment by thc202** [comment]
@bilelmoussaoui we already have a desktop file for Debian package so having those two would not be a problem, I was wondering how the flathub would get them though. We would have to bundle them in the Linux package?

**Comment by psiinon** [comment]
@bilelmoussaoui also, can you point us to any 'good practice' recommendations, eg maybe where we should be putting user files rather than in ~/.ZAP ?

**Comment by bilelmoussaoui** [comment]
@thc202 the desktop & metainfo should be bundled in the Linux package indeed. Regarding the good practice recommendations, you just need to use XDG directories https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html + shipping a desktop, metainfo & icon should be enough
