### ISSUE TITLE
Allow to specify higher values for delay while scanning through the UI

### ISSUE THREAD

**Issue by deadstar1** [zaproxy/zaproxy#4646]
![](https://i.imgur.com/iynCHS0.png)
 ##
The delay is only limited to 1 second. Text box should be used here instead

**Comment by kingthorin** [comment]
Why shoukd it be a text box? The scale could just be increased on the max end _if_ necessary
end if necessary. 

https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsOptionsAscan#delay-when-scanning-in-milliseconds

**Comment by deadstar1** [comment]
Is there a way to setup delay/throttle,something between 3-4 seconds, for active scan HTTP request? Some bug bounty program requires researchers to limit their tool, auto scanner, HTTP request. e.g. 1 request per 3 secs. As a result, text box allows tester to set delay they preferred.

**Comment by thc202** [comment]
Yes, through the API or command line you can specify higher values:
http://zap/JSON/ascan/action/setOptionDelayInMs/?Integer=3000
or
`-config scanner.delayInMs=3000`

Issue title updated.
