### ISSUE TITLE
ZAP- Request to API URL not permitted in server

### ISSUE THREAD

**Issue by vinayadi** [zaproxy/zaproxy#4652]
Hi,

I am trying to run Jenkins job using OWSAP ZAP, but getting below error that server is not permitting the API URL. Please assist how to fix this.

**3725 [ZAP-ProxyThread-2] WARN org.zaproxy.zap.extension.api.API  - Request to API URL http://zap/xml/core/action/saveSession/?apikey=ZAPROXY-PLUGIN&name=C%3A%5CJenkins%5Cworkspace%5Test&overwrite=true& from 10.21.30.101 not permitted**

> ERROR: org.zaproxy.clientapi.core.ClientApiException: java.net.SocketException: Unexpected end of file from server
> 	at org.zaproxy.clientapi.core.ClientApi.callApiDom(ClientApi.java:329)
> 	at org.zaproxy.clientapi.core.ClientApi.callApi(ClientApi.java:311)
> 	at org.zaproxy.clientapi.gen.Core.saveSession(Core.java:278)
> 	at org.jenkinsci.plugins.zap.ZAPDriver.executeZAP(ZAPDriver.java:1161)
> 	at org.jenkinsci.plugins.zap.ZAPBuilder$ZAPDriverCallable.invoke(ZAPBuilder.java:448)
> 	at org.jenkinsci.plugins.zap.ZAPBuilder$ZAPDriverCallable.invoke(ZAPBuilder.java:436)
> 	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:2816)
> 	at hudson.remoting.UserRequest.perform(UserRequest.java:210)
> 	at hudson.remoting.UserRequest.perform(UserRequest.java:53)
> 	at hudson.remoting.Request$2.run(Request.java:364)
> 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
> 	at java.util.concurrent.FutureTask.run(Unknown Source)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> 	at hudson.remoting.Engine$1$1.run(Engine.java:94)
>

**Comment by kingthorin** [comment]
You need to set 10.21.30.101 as a permitted host: https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsOptionsApi#addresses-permitted-to-use-the-api

**Comment by thc202** [comment]
For command line argument:
https://github.com/zaproxy/zaproxy/wiki/FAQremote

**Comment by vinayadi** [comment]
Hi,

I tried all this options, still same issue.

**Comment by kingthorin** [comment]
@vinayadi are you able to answer @thc202's question?

**Comment by kingthorin** [comment]
Closing. It's been over a month with no user feedback.
