### ISSUE TITLE
ZAP chromedriver is not up to date

### ISSUE THREAD

**Issue by jpparsons** [zaproxy/zaproxy#4658]
I am running ZAP in CircleCI using a their docker images (circleci/ruby:2.5.1-node-browsers to be exact). The chromedriver and googlechrome browser is already installed in these docker images and CircleCI also updates these images to keep the driver and browser current.

The issue I am having is ZAP already bundles and uses it's own chromedriver (currently version 2.33) which is out of date and will not work with recent chrome browser versions (65+).

Is there anyway to configure ZAP to use an external chromedriver already installed and not the one it is bundled with in .ZAP/webdriver/linux/64/chromedriver?

**Comment by thc202** [comment]
Weekly releases do use a newer ChromeDriver version (2.36), we need to release that.

Yes, you can override the paths:
https://github.com/zaproxy/zap-core-help/wiki/HelpAddonsSeleniumOptions
Command line:
`-config selenium.chromeDriver=/path/to/chromedriver`
(also available through the ZAP API)

**Comment by jpparsons** [comment]
Thank you!

**Comment by thc202** [comment]
No problem.

For the record, the new versions of the WebDrivers add-ons are now available in the marketplace.
