### ISSUE TITLE
ZAP Session Properties is failing to include the context URL through Environment Inject Plugin 

### ISSUE THREAD

**Issue by syndy1989** [zaproxy/zaproxy#4664]
I'm a newbie, trying to automate security testing using Official OWASP ZAP Plugin for Jenkins. I need to pass dynamic URL to perform security scan using ZAP. In order to achieve this i'm using Environment Injector  Plugin for jenkins (to pass the URL dynamically to ZAP plugin during execution). Everything works perfectly without injecting variables to ZAP Plugin. But when when a variable(URL) is injected to zap plugin i keep getting exception.

1. Go to jenkins -> ManageJenkins -> Manage Plugins -> click available -> select (Environment Injector  Plugin & Official OWASP ZAP Jenkins Plugin) -> Restart Jenkins 
2.Go to Jenkins - > New Item -> Give a filename -> Select Freestyle Project -> Click 'OK'
3. Click on the created job in jenkins -> click configure -> Build -> Inject environment variables  -> find below image for reference

![image](https://user-images.githubusercontent.com/25633749/39921744-aa379dc6-5539-11e8-862c-8f6337101783.png)

4. Scroll down to click Build -> Select Execute ZAP -> Please find below images for reference

![image](https://user-images.githubusercontent.com/25633749/39921840-08f6bf86-553a-11e8-892f-d6ea0900dafb.png)

![image](https://user-images.githubusercontent.com/25633749/39921873-2c1df0ba-553a-11e8-8fdb-2a59939c92d9.png)

![image](https://user-images.githubusercontent.com/25633749/39921905-4b63d0f2-553a-11e8-86f1-45b7f5630b40.png)

then Click ->Save

5. configured JAVA & JRE HOME Path in ManageJenkins -> Global Tool configuration -> Custom Tools
6. Please find the below build error

![image](https://user-images.githubusercontent.com/25633749/39922009-afa26e3e-553a-11e8-92ee-ccda1733f653.png)

**Expected behavior**
ZAP JENKINS Plugin supposed to initialize the zap-daemon and start the spider scan for the injected URL. 
![image](https://user-images.githubusercontent.com/25633749/39922070-f7534fd2-553a-11e8-9b96-0292f5e3fd7d.png)

**Software versions**
 - ZAP: 2.7.0
 - OS: Windows Server 2012
 - Java: jdk version "1.8.0_162

 I'm trying this for the past few days and unable to make it work.Any advise on this would be helpful. Thanks in advance.

**Comment by kingthorin** [comment]
For support of the Jenkins ZAP Plugin please see:
https://plugins.jenkins.io/zap#zapplugin-IssueTracking
https://groups.google.com/forum/#%21forum/zaproxy-jenkins

**Comment by kingthorin** [comment]
More appropriate support resources provided, no further input since May 11th. Closing.
