### ISSUE TITLE
Submitting the Attack Surface Detector plugin to the Marketplace

### ISSUE THREAD

**Issue by matthewD-AVI** [zaproxy/zaproxy#4670]
**Add-on repo**
https://github.com/secdec/attack-surface-detector-zap

**Your contact details**
matthew.deletto@securedecisions.com

**Are you one of the authors**
Yes

**Licence**
in repo

**Build instructions**
    Install Maven: https://maven.apache.org/install.html
    Clone Attack Surface Detector repository: https://github.com/secdec/attack-surface-detector-zap
    Navigate to the source code Directory, open terminal and run the command mvn clean package
    The plugin will be located in the target folder named: attacksurfacedetector-release-#.zap.

  also in readme

**Link to more information**
https://github.com/secdec/attack-surface-detector-zap/wiki

**Twitter handle for tool or author(s)**
https://twitter.com/secdec

**Promote to Beta or Release?**
Note that all new add-ons start at Alpha status.

**Anything else we should know**
During web application penetration testing, it is important 
to enumerate your application's attack surface. While Dynamic Application Security Testing (DAST) tools (such as Burp Suite and ZAP) are good at spidering to identify application attack surfaces, they will often fail to identify unlinked endpoints and optional parameters. These endpoints and parameters not found often go untested, which can leave your application open to an attacker. This tool is the Attack Surface Detector, a plugin for OWASP ZAP. This tool figures out the endpoints of a web application, the parameters these endpoints accept, and the data type of those parameters. This includes the unlinked endpoints a spider won't find in client-side code, or optional parameters totally unused in client-side code. The plugin then imports this data into ZAP so you view the results, or work with the detected endpoints and parameters from the target site map

**Comment by psiinon** [comment]
A few issues from me:

- Its using the ZAP [2.2.2](https://github.com/secdec/attack-surface-detector-zap/tree/master/zaproxy/lib/com/owasp/zap/zap/2.2.2) jar - that will need updating to 2.7.0
- The [file](https://github.com/secdec/attack-surface-detector-zap/blob/master/zaproxy/src/org/zaproxy/zap/extension/attacksurfacedetector/ZapAddOn.xml#L18) should be ...alpha-1.zap not ..release-1.10.zap
- Is the [description](https://github.com/secdec/attack-surface-detector-zap/blob/master/zaproxy/src/org/zaproxy/zap/extension/attacksurfacedetector/ZapAddOn.xml#L7) right?
- I'd recommend changing [not-before-version](https://github.com/secdec/attack-surface-detector-zap/blob/master/zaproxy/src/org/zaproxy/zap/extension/attacksurfacedetector/ZapAddOn.xml#L18) to 2.7.0 - we wont release it for old versions of ZAP in any case
- Logging at [info](https://github.com/secdec/attack-surface-detector-zap/blob/master/zaproxy/src/org/zaproxy/zap/extension/attacksurfacedetector/AttackSurfaceDetector.java#L52) should only be done for significant and infrequent events - 'debug' is much more suitable for frequent events
- Is the [url](https://github.com/secdec/attack-surface-detector-zap/blob/master/zaproxy/src/org/zaproxy/zap/extension/attacksurfacedetector/AttackSurfaceDetector.java#L113) right? Not sure this is still associated with Denim
- Likewise the Denim [icon](https://github.com/secdec/attack-surface-detector-zap/blob/master/zaproxy/src/org/zaproxy/zap/extension/attacksurfacedetector/dg-icon.png)

fyi we tend to use the fugue icons: https://github.com/yusukekamiyamane/fugue-icons - you can see them all here: https://github.com/yusukekamiyamane/fugue-icons/blob/master/all-preview.png :)

**Comment by thc202** [comment]
Worth noting that ZAP is already available in Maven Central:
http://search.maven.org/#search|gav|1|g%3A%22org.zaproxy%22%20AND%20a%3A%22zap%22

**Comment by thc202** [comment]
Is that the whole error, no stack trace? Is the code pushed (to take a look)?

**Comment by matthewD-AVI** [comment]
There is no stack trace for that error.
The code is not pushed since it is not working and I did not want to upload broken code. The only changes made where to the 
        <dependency>
            <groupId>com.owasp.zap</groupId>
            <artifactId>zap</artifactId>
            <version>${zap.version}</version>
            <scope>provided</scope>
        </dependency>
in the pom files which were replaced by 

<dependency>
    <groupId>org.zaproxy</groupId>
    <artifactId>zap</artifactId>
    <version>2.7.0</version>
</dependency>

**Comment by matthewD-AVI** [comment]
I was no longer providing the Jar file and was pulling directly from maven. I have never needed a scope before when the jar file is not provided.
https://mvnrepository.com/artifact/org.zaproxy/zap/2.7.0
That is what I used

**Comment by matthewD-AVI** [comment]
commit: a9d466415ecd7f3e3051d36d913a1b561973a7b6 should address all of @psiinon concerns.

**Comment by thc202** [comment]
In the `AttackThread` it should use the new API instead, something like:
```Java
Target spiderTarget = new Target(startNode);
spiderTarget.setRecurse(true);
int id = extSpider.startScan(spiderTarget, null, null);
// Give some time to the spider to finish to setup and start itself.
sleep(1500);
SpiderScan spiderScan = extSpider.getScan(id);
while (!spiderScan.isStopped()) {
    // Should sleep some time here too otherwise the thread will be too much active.
    if (this.stopAttack) {
        spiderScan.stopScan();
        break;
    }
}
```
this way it avoids conflicts with other running spider scans.

I think most if not all (except ZAP) of the provided dependencies could be removed, they seem to be transitive dependencies of ZAP (which are already being included). (Not that it matters for the release to marketplace, just tidy up.)

**Comment by thc202** [comment]
Note that the spider will fail to start when the Mode does not allow spider scans. A check before starting the ASD would be better but catching the exception (`IllegalStateException`) is fine as well.

**Comment by thc202** [comment]
Another thing worth doing now, is declare that the extension can be unloaded (e.g. override `canUnload` in `AttackSurfaceDetector` to return `true`), it seems to me that it can (from ZAP side it's removing everything from core, worth checking if the dependencies (e.g. `com.github.secdec.astam-correlator`) can also be GC'ed). It makes life easier to the user as it does not need to restart ZAP after updating the add-on.

**Comment by matthewD-AVI** [comment]
@thc202 I am currently rewriting the spider to use the new API and sleeps. I am also overridding canUnload, but can you clarify what is meant by "worth checking if the dependencies (e.g. com.github.secdec.astam-correlator) can also be GC'ed)." So I can properly address that concern.

**Comment by thc202** [comment]
I'm referring to the usual features that might lead to memory leaks (e.g. use of `ThreadLocal` in a long lived thread, EDT or passive scan thread, would be the main ones to be careful with).

**Comment by matthewD-AVI** [comment]
@thc202  commit b22493616a73434ebb79b70045abec034f4024b9 should have addressed all of your concerns. Thank you for all of your input.

**Comment by thc202** [comment]
@matthewD-AVI thanks! Will take a look ASAP.

**Comment by thc202** [comment]
The `AttackThread` is still stopping all spider scans, is that on purpose? (The `spiderScan.stopScan();` should work and does not interfere with other scans already running.)

Some comments regarding the add-on manifest (`ZapAddOn.xml` file):
 1. The following lines can be removed (not used by ZAP): https://github.com/secdec/attack-surface-detector-zap/blob/365fa2d98d836db1f68b6d9eea5f95434d13fc43/zaproxy/src/org/zaproxy/zap/extension/attacksurfacedetector/ZapAddOn.xml#L5 and https://github.com/secdec/attack-surface-detector-zap/blob/365fa2d98d836db1f68b6d9eea5f95434d13fc43/zaproxy/src/org/zaproxy/zap/extension/attacksurfacedetector/ZapAddOn.xml#L7
 2. I'd suggest just use `version` with the semantic version (if you really want to use that), it's no longer necessary to use both and makes the version handling easier (just one version to maintain).

That's all from me.

**Comment by matthewD-AVI** [comment]
@thc202 The stopAllScans() just slipped through, it has been changed as well ZappAddOn.xml
commit: 4f050b52038fe0c153f4219e33745455f1f557c5

**Comment by kingthorin** [comment]
@matthewD-AVI could you email me? github username at gmail.com

Thanks

**Comment by thc202** [comment]
@matthewD-AVI, @kingthorin what's the current state?

**Comment by matthewD-AVI** [comment]
@thc202 as of commit: e18f9ba41e43d62e30d909e4b135a330c6f1e1ce all of your concerns should have been addressed.

**Comment by matthewD-AVI** [comment]
I'm just following up to see if there is anything else needed to get ASD into the Marketplace.

**Comment by kingthorin** [comment]
@matthewD-AVI  the only thing I see outstanding is the version info. Looking at https://github.com/secdec/attack-surface-detector-zap/releases 1.1.0 was from your original announcement (IIRC). 

So https://github.com/secdec/attack-surface-detector-zap/blob/master/zaproxy/src/org/zaproxy/zap/extension/attacksurfacedetector/ZapAddOn.xml#L3 should probably be 1.2.0 or 1.1.1?

**Comment by matthewD-AVI** [comment]
@kingthorin I will be doing a version bump soon, for now I will switch it back to 1.1.0. Thank you for the input.

**Comment by matthewD-AVI** [comment]
@kingthorin @psiinon @thc202 There is a new version available 1.1.1 that has addressed every concern that has been raised on this thread.

**Comment by thc202** [comment]
btw, IMHO the class `ZapPropertiesManager` is still to verbose, I can see a lot of log messages like:
```
INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Properties file is at /zap/asd.properties
INFO org.zaproxy.zap.extension.attacksurfacedetector.ZapPropertiesManager  - Successfully loaded properties.
```
when importing.

**Comment by matthewD-AVI** [comment]
As of the latest commit(8b1415266fd30310c79eb86fb8aceca86a78b76e), all issues raised by @thc202 have been addressed. I moved the tag to update release v1.1.1 with updated binaries

**Comment by kingthorin** [comment]
I think this is good to go?

**Comment by thc202** [comment]
Yeah, looks good to me.

**Comment by thc202** [comment]
Closing, the add-on is now available in the marketplace. Thank you! :)

**Comment by psiinon** [comment]
Yeah, thanks @matthewD-AVI :)
Also announced on twitter: https://twitter.com/zaproxy/status/1012337855555874817

**Comment by matthewD-AVI** [comment]
Thank you all

**Comment by matthewD-AVI** [comment]
Thank you all
