### ISSUE TITLE
Tag changes in Search tab not reflected in History tab

### ISSUE THREAD

**Issue by juhakivekas** [zaproxy/zaproxy#4671]
**Describe the bug**
Managing message tags with the "Manage Tags..." dialog in Search view does not affect message tags in History view. This might not be a bug, but actually just a missing feature, not sure though.

**To Reproduce**
1. find message in "Search" tab
2. got to "Manage Tags"
3. add a new tag and finish the dialogue
4. there is no new tag in the tag column of search view. This will appear if the search is repeated. The tag does not appear in the history view at all

**Expected behavior**
It is expected for a tag added in Search to affect the History view and be persisted in history and the ZAP session.

**Software versions**
 - ZAP: w2018-05-14
 - Add-on: Search is part of the core, right?
 - OS: OSX 10.13.4
 - Java: 1.8.0_152

**Comment by kingthorin** [comment]
Yes it's part of the core https://github.com/zaproxy/zaproxy/tree/develop/src/org/zaproxy/zap/extension/search

**Comment by kingthorin** [comment]
Search only provides point in time results. It doesn't update in real time (with spider, proxying, etc)

The update of the history table is probably just a missing call to:
`notifyHistoryItemChanged(historyReference);` like https://github.com/zaproxy/community-scripts/blob/a3c762166a8a0161ac8d87dc8a91cc8d16093842/standalone/historySourceTagger.js#L36

**Comment by thc202** [comment]
Note that the History tab is now using events to update its state.
