### ISSUE TITLE
I can not create pod using owasp/zap2docker-stable in openshift

### ISSUE THREAD

**Issue by xiaoyan1985** [zaproxy/zaproxy#4686]
It is failure as I created pod using 'owasp/zap2docker-stable' in openshift.
Could you help me solve this problem?
Thanks.

**Comment by psiinon** [comment]
I've not used openshift before I'm afraid.
Can you give us some more information, eg whats not working and/or any error messages that are shown.

**Comment by xiaoyan1985** [comment]
Thanks for your reply.
The error message as followings:

Error syncing pod, skipping: failed to "StartContainer" for "mark-zap" with ImagePullBackOff: "Back-off pulling image \"172.30.187.142:5000/lingandev3/mark-zap@sha256:2b623bc3844a8ca36e07224ba36cd623a8799a23bf2203bb336066b62c92b52a\""

**Comment by psiinon** [comment]
That means nothing to me :/
You might have to follow up with this on an openshift forum

**Comment by xiaoyan1985** [comment]
Ok, Thanks.

**Comment by thc202** [comment]
Closing, the issue does not seem to be specifically about ZAP Docker images (if it is, feel free to reopen while providing more details).
