### ISSUE TITLE
How to load a script file (from local pc) into ZAP API??

### ISSUE THREAD

**Issue by huymapmap40** [zaproxy/zaproxy#4687]
Hi everyone. i take a mistake when config to load a script file from local into form at http://localhost:8080/UI/script/action/load/ . Anybody can help me explain fields "fileName", i dont understand it can be a path or a name.
![image](https://user-images.githubusercontent.com/37060736/40418565-e8b4415e-5eac-11e8-8b80-6d3083d45c22.png)

I put a script file on desktop, how can i refer it from filed "fileName".
Thank you so much<sun>Wdit: typo fix</sub>

**Comment by thc202** [comment]
That should be file system path to the file. Note that the script type should be `httpsender` (the engine name could be just `jython`).

**Comment by thc202** [comment]
Great, closing then.
