### ISSUE TITLE
How can i use POST method with request body on Zap UI to send data??

### ISSUE THREAD

**Issue by huymapmap40** [zaproxy/zaproxy#4689]
Hi, everyone.
Im clearly done with GET method when i want to get data, but i meet a issue when use POST method.
I dont know how to use it, i tried many ways, i make sure that my params request are right.
![image](https://user-images.githubusercontent.com/37060736/40473735-35d2a614-5f67-11e8-8be8-a0ddbd018c18.png)
Can anyone send me a demo , Please help me, thanks.

**Comment by kingthorin** [comment]
URL encode the content?

**Comment by thc202** [comment]
Or change the `Content-Type`.

Note that for questions about ZAP usage it's preferable to use the User Group: https://groups.google.com/group/zaproxy-users

**Comment by huymapmap40** [comment]
nice, i did it. thank you, you save my life :v

**Comment by kingthorin** [comment]
Thanks for letting us know.
