### ISSUE TITLE
Improving the Persistent XSS scanner function 

### ISSUE THREAD

**Issue by DanielMyshkin** [zaproxy/zaproxy#4692]
Hi,

the XSS scanner cannot find a stored XSS vulnerability on the Google Gruyere Project. The actual payload is rather simple: 

***<p <script>alert(1)</script>hello*****

**Comment by kingthorin** [comment]
Can you provide a link or appropriate steps to re-create/test?

**Comment by kingthorin** [comment]
https://google-gruyere.appspot.com/part2#2__stored_xss

Looks like we might need to port some of the Reflected XSS enhancements to the persistent XSS plugin.

```diff
diff --git a/src/org/zaproxy/zap/extension/ascanrules/TestPersistentXSSAttack.java b/src/org/zaproxy/zap/extension/ascanrules/TestPersistentXSSAttack.java
index d095f37..5d893d7 100644
--- a/src/org/zaproxy/zap/extension/ascanrules/TestPersistentXSSAttack.java
+++ b/src/org/zaproxy/zap/extension/ascanrules/TestPersistentXSSAttack.java
@@ -351,12 +351,26 @@
 		            	            contexts2 = performAttack (sourceMsg, param, 
 		            	            		context.getSurroundingQuote() + ";alert(1);" + context.getSurroundingQuote(), 
 		            	            		sinkMsg, context, 0);
-		            	            if (contexts2 != null && contexts2.size() > 0) {
+		            	            if (contexts2 == null) {
+		            	            	break;
+		            	            }
+		            	            if (contexts2.size() > 0) {
 		           	            		// Yep, its vulnerable
 		           						bingo(Alert.RISK_HIGH, Alert.CONFIDENCE_MEDIUM, null, param, contexts2.get(0).getTarget(), 
 		           								otherInfo, contexts2.get(0).getMsg());
 		        						attackWorked = true;
 		            	            }
+		        	            } else {
+									// Try an img tag
+									List<HtmlContext> contextsA = performAttack(sourceMsg, param, "<img src=x onerror=alert(1);>",
+											sinkMsg, context, 0);
+									if (contextsA != null && contextsA.size() > 0) {
+										bingo(Alert.RISK_HIGH, Alert.CONFIDENCE_MEDIUM, null, param,
+												contextsA.get(0).getTarget(), "", contextsA.get(0).getTarget(),
+												contextsA.get(0).getMsg());
+										attackWorked = true;
+										break;
+									}
 		        	            }
 		            		}
 		            	}
```

**Comment by kingthorin** [comment]
Note: Although the Google Gruyere Project does suggest the payload outlined by @DanielMyshkin it doesn't seem to work (not in FF60.0.1 or IE 11 anyway). However, the change in the diff above does manifest the vuln.

**Comment by kingthorin** [comment]
The persistent scanner could probably benefit from all of the following:
- https://github.com/zaproxy/zap-extensions/pull/1160 : XSS in PUT Response
  - Said handling should probably be in `TestPersistentXSSPrime` (Only check PUT requests @ Low Threshold.)
- https://github.com/zaproxy/zap-extensions/pull/1217 : Handle XSS in JSON response
- https://github.com/zaproxy/zap-extensions/pull/1369 : False Negative on Double Encoding
- https://github.com/zaproxy/zap-extensions/pull/1349 : False Negative when script tags are prevented
  - This is the one in the diff earlier.

**Comment by kingthorin** [comment]
FYI, I've submitted a PR that addresses this. 

I did notice that if you want to properly test the issue outlined in the original submission you need to ensure that login and logout URLs are set as "Exclude from Scanner" or your session gets invalidated and the issue isn't found.

**Comment by kingthorin** [comment]
As per the details above, this is fixed in https://github.com/zaproxy/zap-extensions/pull/1646

Closing.
