### ISSUE TITLE
Active scan with sequence causes some request to use old anti-CSRF tokens from initial site discovery responses

### ISSUE THREAD

**Issue by knutsiem** [zaproxy/zaproxy#4701]
When using the Sequence extension in an active scan on a URL in the site tree, certain requests will not have fresh anti-CSRF tokens obtained during execution of the sequence script but instead have stale tokens from when the site tree was built.

**To Reproduce**
1. Extract [zap-sequence-anticsrf.zip](https://github.com/zaproxy/zaproxy/files/2047663/zap-sequence-anticsrf.zip) to a web server so that page1.html is reachable at http://localhost:8080/zap-sequence-anticsrf/page1.html etc.
2. Start ZAP and launch a browser with traffic proxied through ZAP
3. Enter the address http://localhost:8080/zap-sequence-anticsrf/page1.html to discover GET:page1.html 
4. Click "Submit" twice to discover POST:page2.html and POST:page3.html (with parameter `anticsrf=oldsecret`)
5. Change the value of the anti-CSRF tokens manually in the `<form>` elements of page1.html and page2.html to e.g. "newsecret".
5. Import the Sequence script anticsrf-test.zst
6. Run an active scan on http://localhost:8080/zap-sequence-anticsrf and include the Sequence "anticsrf-test"
7. Observe that a large number of the POST:page2.html and POST:page3.html requests will actually have the parameter `anticsrf=oldsecret`, even though the Sequence script correctly assigns "newsecret" to the variables `{{csrf1}}` and `{{csrf2}}` and both POST requests in the script have these variables as part of their request bodies.

Note that the problem with the attached example is only clear when looking at the anti-CSRF tokens used in requests made during the scan. To keep the example simple, there is no server-side logic to actually reject the requests with stale token values.

**Expected behavior**
The stale anti-CSRF tokens from the initial site discovery should not be used in Sequences included in later active scans. Only fresh tokens obtained when executing the Sequence script should be used.

**Software versions**
 - ZAP: 2.7.0
 - Add-on: Sequence 5.0.0
 - OS: Windows 10
 - Java: "Oracle Corporation 1.8.0_171"
 - Browser: Chrome 66.0.3359.181 (64bit)

**Comment by kingthorin** [comment]
Are you sure you had `Handle anti-CSRF tokens (experimental functionality` enabled?
![image](https://user-images.githubusercontent.com/7570458/42469463-cfc3e084-8385-11e8-863e-cdd206254ce3.png)

https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsOptionsAscan#handle-anti-csrf-tokens

**Comment by kingthorin** [comment]
No feedback in over a month and a half. Closing.
