### ISSUE TITLE
Input value of zap api export report?

### ISSUE THREAD

**Issue by huymapmap40** [zaproxy/zaproxy#4702]
I confuse when export report in zap api via http://localhost:8080/UI/exportreport/action/generate/
![image](https://user-images.githubusercontent.com/37060736/40656957-58f465bc-6370-11e8-96aa-216d974971c4.png)
Can you explain all require input in that form, specify absolutePath and sourceDetail. I not found  document about those parameters.
thanks

**Comment by thc202** [comment]
Those are described in the help page:
https://github.com/zaproxy/zap-extensions/wiki/HelpAddonsExportreportExportreport

(Note "The restrictions are the same as those for Command Line above.")

**Comment by kingthorin** [comment]
@huymapmap40 did the help page resolve your question?

**Comment by kingthorin** [comment]
No further input in over a month and a half. Closing.
