### ISSUE TITLE
Post request with complex header and body via Zap api

### ISSUE THREAD

**Issue by huymapmap40** [zaproxy/zaproxy#4703]
I had reference this discuss https://groups.google.com/forum/#!topic/zaproxy-users/uVZx3UvHG3Y , so i still confuse much
i try to use sendRequest api with header and body in below:

POST https://inventory.bodhi-qa.io/kms_qa_test/store_test/InventoryCountSheet/addCountItem/8a45a670-60ce-11e8-9f6a-2b81255bd4b6 HTTP/1.0
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0
Pragma: no-cache
Content-Length: 101
Content-Type: application/json
Host: inventory.bodhi-qa.io

{"locationId":"507c51f0-9487-11e7-a5f9-4d054cdc3bd2","itemId":"ae83e6d0-5e73-11e8-bfe1-0ff28d61a7a8"}

- I encode that request such as below but it not work :
POST%20https%3A%2F%2Finventory.bodhi-qa.io%2Fkms_qa_test%2Fstore_test%2FInventoryCountSheet%2FaddCountItem%2F8a45a670-60ce-11e8-9f6a-2b81255bd4b6%20HTTP%2F1.0%0AUser-Agent%3A%20Mozilla%2F5.0%20(Windows%20NT%206.3%3B%20WOW64%3B%20rv%3A39.0)%20Gecko%2F20100101%20Firefox%2F39.0%0APragma%3A%20no-cache%0AContent-Length%3A%20101%0AContent-Type%3A%20application%2Fjson%0AHost%3A%20inventory.bodhi-qa.io%0A%0A%7B%22locationId%22%3A%22507c51f0-9487-11e7-a5f9-4d054cdc3bd2%22%2C%22itemId%22%3A%22ae83e6d0-5e73-11e8-bfe1-0ff28d61a7a8%22%7D

- I tried to edit param request many way , but it not work.
Thanks

**Comment by thc202** [comment]
An answer was posted to the User Group:
> The request header and body should be separated with \r\n\r\n (i.e. "%0D%0A%0D%0A") not just \n\n ("%0A%0A%").

Closing, further questions can be handled in the User Group.

**Comment by kingthorin** [comment]
I was able to successfully send using the web UI as follows (browser dev tools were used to hide apikey and change request field to a textarea):

![image](https://user-images.githubusercontent.com/7570458/40659292-d8bd059c-631b-11e8-83b5-71c9f8cc45c2.png)
