### ISSUE TITLE
Setting user authentication credentials - Java ClientApi

### ISSUE THREAD

**Issue by jspr12** [zaproxy/zaproxy#4704]
**Description of Problem**
I'm using the Java ClientApi to automate some scans. I'm trying to add a new user and for some reason the config parameters of the setAuthenticationCredentials-method needs the session name.

First of all, this seems weird to me because in the UI, you have to configure the users in the context so the session has nothing to do with it, or so it seems. And now I'm unable to find any way to either change the name of the session or to fetch the current session name.

**What I've tried**
1. If I create a new session, the session name remains "Untitled Session". When I try to parse "Untitled Session" as the session name to the above mentioned method, I get the error "Doesn't exist".
2. I'm aware that there's an example in the github but that example only sets username and password as parameters and then I get the error "Missing parameter".

**Software versions**
I'm using version 1.6.0 of the java clientapi from the releases page.

**Questions**
1. Has anyone figured out how to set these credentials in the java clientapi?
2. Can you start ZAP from the commandline and create a new session with specifying a session name?

Thanks in advance.

**Comment by thc202** [comment]
That's most likely referring to "HTTP session" not the ZAP session. What type of authentication are you using?

Could you provide the API calls (or code) that you are using?

**Comment by jspr12** [comment]
I'm using script based authentication with the script you provided in the github to authenticate in DVWA.
[https://github.com/zaproxy/zaproxy/wiki/FAQvulnappdvwa](https://github.com/zaproxy/zaproxy/wiki/FAQvulnappdvwa)

Below you can find my testing code that I'm using at the moment. Sorry about the formatting... It's acting out a bit.

**Code**
`public static void main(String[] args) {
	ClientApi api = new ClientApi(ZAP_ADDRESS, ZAP_PORT, ZAP_API_KEY);

	try {
		
		System.out.println(api.core.newSession("Session1","true"));
		
		api.context.newContext("Context1");
		ApiResponseSet ctxt = (ApiResponseSet) api.context.context("Context1");
		String contextId = ctxt.getValue("id").toString();
		
		ApiResponseElement id = (ApiResponseElement) api.users.newUser(contextId, zap.username);
		String userId = id.getValue();
		
		setUserTokenAuthentication(api, contextId);
		
		StringBuilder sb = new StringBuilder();
		sb
				.append("sessionName=").append(URLEncoder.encode("Session1","UTF-8"))
				.append("&username=").append(URLEncoder.encode("user", "UTF-8"))
				.append("&password=").append(URLEncoder.encode("pswd","UTF-8"));
		api.users.setAuthenticationCredentials(contextId,userId, sb.toString());
		
	} catch (Exception e) {
		System.out.println("Exception : " + e.getMessage());
		e.printStackTrace();
	}
}

public void setUserTokenAuthentication(ClientApi api, int contextId) {
	String scriptName = "UserTokenAuth.js";
	
	try {
		StringBuilder scriptBasedConfig = new StringBuilder();
		scriptBasedConfig
				.append("scriptName=")
				.append(URLEncoder.encode(scriptName, "UTF-8"))
				.append("&Login URL=")
				.append(URLEncoder.encode(loginUrl, "UTF-8"))
				.append("&CSRF Field=")
				.append(URLEncoder.encode(CSRFfield, "UTF-8"))
				.append("&POST Data=")
				.append(URLEncoder.encode(postData, "UTF-8"));
		api.authentication.setAuthenticationMethod(Integer.toString(contextId), "scriptBasedAuthentication", scriptBasedConfig.toString());
		api.authentication.setLoggedInIndicator(Integer.toString(contextId), loggedInIndicator);
		api.authentication.setLoggedOutIndicator(Integer.toString(contextId), loggedOutIndicator);
	} catch (Exception e) {
		System.out.println("Exception: " + e.getMessage());
	}
}`

**Comment by jspr12** [comment]
Yes, the script loads fine. When I check in the UI, everything is filled in. I only have trouble with adding the user but that's probably because I wasn't using the HTTP session name as you pointed out in your first comment.

Unfortunately I don't really understand what these HTTP sessions are. If I call below method, it gives me an empty string. I give the site's url as a parameter, maybe that's my mistake? I don't really know what else to give to this method...
`String httpSession = api.httpSessions.activeSession(url).toString();`

Or do I create a new empty HTTP session with this method?
`api.httpSessions.createEmptySession(url)`

**Error**
The error I used to get with the previous code I posted earlier, was that the session doesn't exist, I pressume:
```
Exception : Does Not Exist
org.zaproxy.clientapi.core.ClientApiException: Does Not Exist
	at org.zaproxy.clientapi.core.ApiResponseFactory.getResponse(ApiResponseFactory.java:50)
	at org.zaproxy.clientapi.core.ClientApi.callApi(ClientApi.java:332)
	at org.zaproxy.clientapi.gen.Users.setAuthenticationCredentials(Users.java:114)
	at zap.ZAP.main(ZAP.java:127)
```

With my changed code I get this:
```
Exception : Missing Parameter
org.zaproxy.clientapi.core.ClientApiException: Missing Parameter
	at org.zaproxy.clientapi.core.ApiResponseFactory.getResponse(ApiResponseFactory.java:50)
	at org.zaproxy.clientapi.core.ClientApi.callApi(ClientApi.java:332)
	at org.zaproxy.clientapi.gen.Users.setAuthenticationCredentials(Users.java:114)
	at zap.ZAP.main(ZAP.java:127)
```

The line responsible for the error being: 
`api.users.setAuthenticationCredentials(contextId,userId, sb.toString());`

With the sessionName in "sb" now being the httpSession as seen below:
```
StringBuilder sb = new StringBuilder();
            sb
                    .append("sessionName=").append(URLEncoder.encode(httpSession,"UTF-8"))
                    .append("&username=").append(URLEncoder.encode(zap.username, "UTF-8"))
                    .append("&password=").append(URLEncoder.encode(zap.password,"UTF-8"));
```

**Comment by jspr12** [comment]
Ah thank you! I didn't know about the API error details. It appeared that the parameters had to be with a capital letter, so "Username" instead of "username". I removed the HTTP session part and everything works perfectly know.

Thank you so much for your help @thc202 !

**Comment by thc202** [comment]
Great! No problem.

**Comment by V1Reddy** [comment]
Hi @jspr12 
I am trying to achieve the same with the Java ClientAPI to automate our scans, but I am stuck at  loading the script successfully by the API. I am keep getting '**Unable to find script while loading Script Based Authentication Method for name**' error.

Where did you place the script? How did you resolve this issue?

Thanks.
