### ISSUE TITLE
Initiate active scan from "break point"

### ISSUE THREAD

**Issue by Nagpradis** [zaproxy/zaproxy#4706]
Hi there,

I don't know whether this feature is already there or not. But is it possible to launch an active scan for a intercepted request in "break" area. If not, request you to add this as a feature.

Best regards,
Nagpradis

**Comment by kingthorin** [comment]
Before or after modification?

https://github.com/zaproxy/zaproxy/issues/1646

**Comment by Nagpradis** [comment]
Both. I think, we can always start an active scan from sitemap, but for large applications, with multiple sessions already logged, it might not be easy to select the request with active session ID and start a scan. Rather, it would be easy to start a scan from "break" area.
