### ISSUE TITLE
No callback handler for URL

### ISSUE THREAD

**Issue by MayraER** [zaproxy/zaproxy#4710]
Al lanzar la solicitud recibo el siguiente mensaje de error en el servidor ZAP:
[ZAP-ProxyThread-8] ERROR org.zaproxy.zap.extension.callback.ExtensionCalback  - No callback handler for URL

y en la tarea:

Task Failed. Error: {"Success":false,"Message":"Unexpected end of JSON input"}

**Comment by thc202** [comment]
Which API call? Is that while scanning with custom code/scanner?

**Comment by MayraER** [comment]
llamando al API desde OWASP Zed Attack Proxy Scan 

Esta es la respuesta completa:

[ZAP-ProxyThread-2] ERROR org.zaproxy.zap.extension.callback.ExtensionCallback  - No callback handler for URL : http://zap.dominio.com:50237/JSON/spider/action/scan/?apikey=%27%27&url=http%3A%2F%2Fgoogle.com%2F&maxChildren=&r
ecurse=false&subtreeOnly=false&contextName=&formMethod=GET&zapapiformat=JSON fro
m /65.52.4.69

recibo esta respuesta con diferentes urls y con/sin apikey.

**Comment by thc202** [comment]
The callback server is not expected to be used directly (that's for the target to call). [1]

ZAP should be listening on other port which does have the ZAP API. [2] Could you try that one instead?

[1] https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsOptionsCallback
[2] https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsOptionsLocalproxy

**Comment by MayraER** [comment]
Me guie de 2do link y funciono perfecto, mil gracias!

**Comment by thc202** [comment]
Thanks for letting us know!
