### ISSUE TITLE
sites tree no longer accessible

### ISSUE THREAD

**Issue by ghost** [zaproxy/zaproxy#4711]
When running zap 2.7.0 on windows 7 64-bit with java 1.8.0_172, and the jaws screen reader (2018.2105.33) jaws can no longer read the entries in the sites tab treeview.  

It used to be that jaws could read the sites tree without a problem, but now it just reads 1 of 1 or 2 of 20 without reading the text of the tree node.

<sub>Edited: removed template text. </sub>

**Comment by kingthorin** [comment]
When you say “it used to be” can you provide a timeline or ZAP version reference?

What version of Java was applicable at the time?
What version of Jaws was applicable at the time?
What OS were you on when it worked? What OS are you using now?

**Comment by psiinon** [comment]
I've just had another report that this isnt working, and that it did work in an earlier version of ZAP (prior to 2.6.0 maybe?).
I suspect its due to one of the many Site Tree changes we've made, and probably applies to all OSs.

**Comment by kingthorin** [comment]
I wonder if this is simply related to the move to Java 8?

I used `Traverse sites tree.js` and tried printing the various getName, getPath, getChild, toString  methods etc. None of which resulted in # of # type output.

**Comment by thc202** [comment]
That was an example to point out that jaws is no longer able to read all nodes (nor its text).

**Comment by kingthorin** [comment]
Ya, I figured it must be "reading" something the objects output though....

**Comment by thc202** [comment]
Right, but it doesn't use the `SiteNode`s directly, it's through the UI component (so it's up to the data we pass to the UI component).
I think we simply need to do:
```Diff
@@ -68,6 +68,7 @@ public class SiteMapTreeCellRenderer extends DefaultTreeCellRenderer {
                this.listeners = listeners;
                this.component = new JPanel(new FlowLayout(FlowLayout.CENTER, 4, 2));
                component.setOpaque(false);
+               this.setLabelFor(component);
                this.putClientProperty("html.disable", Boolean.TRUE);
        }
```
to restore the old behaviour, this should ensure the panel (`component`) has the proper accessible name (which is obtained from the label, which is the `SiteNode`'s `toString` result). Thoughts?
(I'm tempted to open a PR with that change, but would prefer confirmation first if that makes sense.)

**Comment by kingthorin** [comment]
Seems reasonable to me.

**Comment by thc202** [comment]
Thanks.

**Comment by donraikes** [comment]
I tested this in the 2018-06-19 weekly build and it works perfectly now.  Great job all!
