### ISSUE TITLE
Param tab unable to "Flag as Anti-CSRF token"

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#4729]
**Describe the bug**
From the params tab via the context menu I'm unable to "Flag as Anti-CSRF token" on a cookie value....

**To Reproduce**
1. Launch ZAP
2. Browse OWASP Pixi a bit
3. Review the Params tab a bit
4. Note there are two CSRF token cookies.
5. Right click on them and note that "Flag as Anti-CSRF token" is not enabled for use.

**Expected behavior**
The menu item should be enabled for use.

**Screenshots**
![image](https://user-images.githubusercontent.com/7570458/41009061-b7d044e8-68fc-11e8-87b3-9958383aea53.png)

**Software versions**
 - ZAP: Dev Build
 - OS: Win 7
 - Java:
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
 - Browser: Firefox 60.0.1

**Additional context**
Also note the menu item is subject to an Issue 2000 title caps discrepancy as well.

**Comment by thc202** [comment]
Cookies are not supported yet.

**Comment by kingthorin** [comment]
Ok, I hadn't taken the time to look at the code yet.

**Comment by thc202** [comment]
How/where are they being set?

**Comment by kingthorin** [comment]
I had started with a quick scan. It looks like they were set in response to the first request by the spider for robots.txt.
```
HTTP/1.1 404 Not Found
X-Powered-By: Express
Set-Cookie: _csrf=jrW3ZM6dC9v9wQGBdXdrlgDw; Path=/
Set-Cookie: CSRF-TOKEN=4tisFkvH-1-mapgoz88EoaKRyFYWGOc2DUuo; Path=/
Content-Security-Policy: default-src 'self'
X-Content-Type-Options: nosniff
Content-Type: text/html; charset=utf-8
Content-Length: 149
Date: Tue, 05 Jun 2018 23:56:44 GMT
Connection: keep-alive
```
