### ISSUE TITLE
Different results on different OS

### ISSUE THREAD

**Issue by MartynenkoA** [zaproxy/zaproxy#4731]
I`m using ZAP 2.7
On windows I didn`t have any errors, but on MAC I have 1 alert - Path Traversal
Is it error or?

**Comment by psiinon** [comment]
Please dont ask questions as issues, the User Group is a much better forum for them: https://groups.google.com/group/zaproxy-users

**Comment by thc202** [comment]
For the record, being handled in:
https://groups.google.com/d/topic/zaproxy-users/5FuOppDTeQE/discussion
