### ISSUE TITLE
/login.jsp?/ added to most Request URLs during user authorized scan making them invalid

### ISSUE THREAD

**Issue by hnestorova** [zaproxy/zaproxy#4739]
**Describe the bug**
When I run a user authorized active scan, probably due to some Referer problem, /login.jsp/ is added to most Request URLs which makes them invalid

**To Reproduce**
1. Start ZAP
2. Launch JxBrowser
3. Go to the login page of an application, sign in and perform some actions 
4. Add the recorded sites to a new context in ZAP
5. Set Authentication of the Context to Form based 
6. Add user to the context, mark it to be used as the forced user
7. Set session managment to Cookie based and press OK 
8. Find the POST:login request in ZAP and add it as the Context Form based Auth Log in Request
9. Select the correct username parameter and press OK 
10. Flag the name of the password field on the login page as the logged out indicator
11. Run Attack -> Spider scan with the added user selected
several Authentication successful. messages are seen
12. Run Attach -> Active Scan with the added user selected -> I guess something with the Referers messes up the sent request and they all contain /login.jsp?/... which makes then invalid - returns to the login page

**Expected behavior**
The Request URLs that have been recorded after a successful log in not to be added /login.jsp/ before being sent

**Screenshots**

**Software versions**
 - ZAP: [2.7.0]
 - Add-on: Name and version [e.g. Passive Scan Rules Alpha v19. https://github.com/zaproxy/zaproxy/wiki/FAQAddonVersions]
 - OS: [Windows Server 2008 R2]
 - Java: [jdk1.8.0_45]
 - Browser: [JxBrowser and Internet Explorer 11]

**Comment by kingthorin** [comment]
I'm unable to re-create this issue.

**Comment by kingthorin** [comment]
@hnestorova you could check this spider setting and see if it has any impact on what you're experiencing:
https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsOptionsSpider#send-referer-header

**Comment by hnestorova** [comment]
can be resolved - I added login.jsp as the logged out indicator and for some reason the issue stopped appearing

**Comment by kingthorin** [comment]
Thanks for letting us know.
