### ISSUE TITLE
OWASP ZAP Proxy - Re test the previous session

### ISSUE THREAD

**Issue by sreenathtester** [zaproxy/zaproxy#4741]
Hi,

On performing a Security scan and Fuzzing over an Application , we will get the security issues in alerts which is fine and good. But when developer says the issue is fixed and to re test the same issues we need to do  the test again from first and adding fuzzes gain, Active scans , spiders, ajax spiders again. Can we have some feature like  re testing the whole previous  session activities again on one click ?

**Comment by thc202** [comment]
Merging into #375. Please leave a comment there about your workflow (I guess we could create recipes of what was done in the session and repeat that...).
