### ISSUE TITLE
Handling of empty client certificates

### ISSUE THREAD

**Issue by derpsteb** [zaproxy/zaproxy#4749]
**Is your feature request related to a problem? Please describe.**
Upon becoming familiar with ZAP I played around with the configuration for a specific website. At some point I enable client certificates, but did not provide a certificate. This resulted in the browser being unable to access website via HTTPS.

**Describe the solution you'd like**
As far as I understood the problem is that ZAP provides null certificates in case there is no certificate set. I do not know what kind of default value would be more appropriate but I assume someone here does know such things :D.

**Describe alternatives you've considered**
A warning, for the user wanting to leave the configuration site without providing a certificate, that HTTPS connection will not work without a certificate might also be helpful for new users. But this seems very obvious in hindsight. Nevertheless I did not think about it when enabling the option.

**Additional context**
@thc202 helped me figure out the problem and asked me to write an issue for the behavior of ZAP in this case. I hope this is not included in #3225 or in another place.

**Comment by thc202** [comment]
Thanks for raising the issue (I ended up raising one too, #4745 :)

This was fixed in #4746, ZAP will no longer try to use a certificate if none was set.
