### ISSUE TITLE
ClientApi.java -> buildZapRequest hardcoded url.

### ISSUE THREAD

**Issue by centu81** [zaproxy/zaproxy#4750]
**Describe the bug**
Method buildZapRequest is using hardcoded values. Can not execute on other host and port. 

**To Reproduce**
Method buildZapRequest is using hardcoded values. Can not execute on other host and port. 

**Expected behavior**
Method buildZapRequest should use zapAddress and zapPort

**Software versions**
v1.6.0

**Errors from the zap.log file**

**Additional context**

**Comment by thc202** [comment]
The client API connects to the address/port specified (and requests with the ZAP domain). What's not working?

**Comment by kingthorin** [comment]
Duplicate? https://github.com/zaproxy/zaproxy/issues/3594

**Comment by centu81** [comment]
Look on the code:
https://github.com/zaproxy/zap-api-java/blame/5aa17ba59175cb13fd6ae56a59be1911f9df3637/subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/core/ClientApi.java#L394 and it will explain you.

**Comment by psiinon** [comment]
As long as you supply the correct host and port when you start the API then ZAP will proxy through it: https://github.com/zaproxy/zap-api-java/blame/5aa17ba59175cb13fd6ae56a59be1911f9df3637/subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/core/ClientApi.java#L158
If its proxying through ZAP then http://zap/ will work fine.
Are you actually having problems with this if so please explain what you are doing and why you think its not working for you.

**Comment by thc202** [comment]
@centu81 could you provide more details?

**Comment by centu81** [comment]
There was an problem with a query. Closing issue.

**Comment by thc202** [comment]
Thanks for letting us know.

**Comment by dsbonafe** [comment]
Please, could you guys help me on this configuration?
I'm using the maven version 1.6.0 of ZAP-API and I'm facing exactly the same issue.

- I have instantiated my ClientApi with the constructor passing my 9.x.x.x host and 8080 port. This is the host of the virtual machine where a docker container with ZAP is running.
```final ClientApi api = new ClientApi(host, port, apiKey, true);```
- I'm running zap through the following docker command in the machine 9.x.x.x.
```
docker run -u zap -p 8080:8080 -i owasp/zap2docker-stable zap.sh -daemon -host 0.0.0.0 -port 8080 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true -config api.disablekey=true
```
-Debuging the api, inside the method  callApiDomain (@ClientApi.339), the client is calling the method `buildZapRequest` which contains the hard coded address for `zap`.

You have told we should proxy the `9.x.x.x:8080` to `zap` but I'm not using an UI interface neither a browser, but doing the call from automated java code.

Are there a way to make this proxy dynamically in code?

**Comment by dsbonafe** [comment]
Please, could you guys help me on this configuration?
I'm using the maven version 1.6.0 of ZAP-API and I'm facing exactly the same issue.

I have instantiated my ClientApi with the constructor passing my 9.x.x.x host and 8080 port. This is the host of the virtual machine where a docker container with ZAP is running.
final ClientApi api = new ClientApi(host, port, apiKey, true);
I'm running zap through the following docker command in the machine 9.x.x.x.
docker run -u zap -p 8080:8080 -i owasp/zap2docker-stable zap.sh -daemon -host 0.0.0.0 -port 8080 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true -config api.disablekey=true
-Debuging the api, inside the method callApiDomain (@ClientApi.339), the client is calling the method buildZapRequest which contains the hard coded address for zap.

You have told we should proxy the 9.x.x.x:8080 to zap but I'm not using an UI interface neither a browser, but doing the call from automated java code.

Are there a way to make this proxy dynamically in code?
Or how to connect in "http://zap" if it's not defined in my DNS, if there are no `zap` but `9.x.x.x:8080`?

Thanks.

**Comment by thc202** [comment]
You don't need to proxy, the API client already does that and once connected requests with zap domain.
What error are you seeing? Is the request reaching ZAP but ignored or not even that?

**Comment by dsbonafe** [comment]
The request is reaching ZAP, and the request stay processing, without throw any exception in the client side. In the server side, we receive "Socket timeout while reading first message". By the way, I think it could help:
- If I access 9.x.x.x:8080 in the browser, I received the API home page and access all methods.
- If I access `http://zap` in the browser, I receive 404.
- If I run curl command in the 9.x.x.x:8080 everything works... so the connection is established.
- If I run with RestTemplate or curl the exact command that your `request` attribute executes, it works fine too.
- The `uc.connect()` in the above line works fine.

**Comment by kingthorin** [comment]
`http://zap/` only works if the browser is proxying through zap, so that zap can fake the dns.

**Comment by dsbonafe** [comment]
But if I don't have a browser? All `ClientApi` request pass by the `buildZapRequest` method and in this method, we have hard coded the `http://zap`, even if I instantiate the `ClientApi` with another host and port.
So, when I call the `ClientApi` method below:
```api.context.contextList()```...
It does the same if I did:
```curl -X GET "http://zap/UI/context/view/contextList/"```
Right?
But `curl -X GET "http://zap/UI/context/view/contextList/"` does not works when I run it from terminal. What works is ```curl -X GET "http://9.x.x.x:8080/UI/context/view/contextList/"```.

**Comment by kingthorin** [comment]
The API client is essentially proxies so it can speak to the “zap” host.

**Comment by dsbonafe** [comment]
So.... how to make the call below using zap-api-client? 
```
curl -X GET "http://zap/UI/context/view/contextList/"
```
What I have done is...
```
ClientApi api = new ClientApi(HOST, PORT, KEY, true);
api.context.contextList();
```

**Comment by kingthorin** [comment]
In python it's `api.context.context_list`

**Comment by dsbonafe** [comment]
So... what could be happening to don't get the answer of the Zap Server? The ZAP server does not return any error and stay processing the request .

In the following method:

```java

    private InputStream getConnectionInputStream(HttpRequest request) throws IOException {
        HttpURLConnection uc = (HttpURLConnection) request.getRequestUri().openConnection(proxy);
        uc.setUseCaches(false);
        for (Entry<String, String> header : request.getHeaders().entrySet()) {
            uc.setRequestProperty(header.getKey(), header.getValue());
        }
        uc.connect();
        if (uc.getResponseCode() >= HttpURLConnection.HTTP_BAD_REQUEST) {
            return uc.getErrorStream();
        }
        return uc.getInputStream();
    }
```

JAVA stay locked in the `uc.getResponseCode()`. Just stay locked for a long time without receiving an exception neither an response.

**Comment by kingthorin** [comment]
Are you providing the proper API key? Is the client host authorized?

https://github.com/zaproxy/zaproxy/wiki/FAQapikey
https://github.com/zaproxy/zaproxy/wiki/FAQremote

**Comment by kingthorin** [comment]
Here's a Java API client example:
https://github.com/zaproxy/zap-api-java/blob/develop/subprojects/zap-clientapi/src/examples/java/org/zaproxy/clientapi/examples/SimpleExample.java

(https://github.com/zaproxy/zap-api-java/tree/develop/subprojects/zap-clientapi/src/examples/java/org/zaproxy/clientapi/examples)

**Comment by dsbonafe** [comment]
I have deactivated apiKey because we are in a safe environment. And
authorized all urls to connect in the host,as described in suggested
documentation above.

Em qua, 22 de mai de 2019 20:28, kingthorin <notifications@github.com>
escreveu:

**Comment by dsbonafe** [comment]
My code is the same thing. When I use localhost it works. If I change to
9.x.x.x I stay locked in that method I have showed.

Em qua, 22 de mai de 2019 20:30, kingthorin <notifications@github.com>
escreveu:

**Comment by dsbonafe** [comment]
To you see the results running your code:
```
Spider : http://www.google.com
Open URL: http://zap/xml/spider/action/scan/?recurse=false&subtreeOnly=false&url=http%3A%2F%2Fwww.google.com&maxChildren=10&
```
The terminal stay locked in there.
