### ISSUE TITLE
Update Generex

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#4751]
The Fuzzer add-on is using a custom/development version of Generex which includes an iterator that counts the strings that can be generated (up to a given limit, and without creating the strings). This change needs to be included in the main repo (ideally) to stop using the custom version.

Add-on:
Fuzzer version 10.

**Comment by kingthorin** [comment]
https://github.com/mifmif/Generex ?

**Comment by thc202** [comment]
Yes.
