### ISSUE TITLE
After doing form base authentication i am getting "CSRF verification failed. Request aborted."

### ISSUE THREAD

**Issue by Vivek-NSI** [zaproxy/zaproxy#4758]
This is my login request
![image](https://user-images.githubusercontent.com/20392301/41397833-108facb8-6fd3-11e8-9af5-d34b5c0eda39.png)

I am not getting what and how to use CSRF token in form based authentication.

csrfmiddlewaretoken=**_csrfmiddlewaretoken_**&username={%username%}&password={%password%}&next=%2Fadmin%2F

Can you please let me know what exectly we do for CSRF token

**Comment by psiinon** [comment]
This has recently been fixed: #2182 
Please try again using the weekly release

**Comment by Vivek-NSI** [comment]
I am not gettig where should i add csrf token or cookies token
DO i need to write code for it or it has to be inserted somewhere in the Context etc.

**Comment by thc202** [comment]
For the cookies, that's still being worked on (#1370).

**Comment by KajanM** [comment]
> I am not gettig where should i add csrf token or cookies token

in your case, you do not need any additional configuration for the anti-CSRF token as  csrfmiddlewaretoken` is already (by default) configured as an anti-CSRF token in ZAP.

ZAP should be able to automatically reauthenticate with the usual form-based authentication setup unless the server sends different `csrftoken` set-cookie value for each request.

 are you not able to setup authentication with the weekly release?
