### ISSUE TITLE
Access Control Add-Generate Report- Report says Yes as Authorized for user whose credentials are false or incorrect

### ISSUE THREAD

**Issue by Vivek-NSI** [zaproxy/zaproxy#4759]
In the attached email, for both valid credentials and invalid credential user, results are same. Ideally it must say Authorise=No for user with invalid credentials.

I am using "Access Control" add on

![image](https://user-images.githubusercontent.com/20392301/41402889-191a37dc-6fe1-11e8-82c2-c28001e6aa31.png)

**Comment by thc202** [comment]
It's up to you to define if that user should be authorised or not:
https://github.com/zaproxy/zap-extensions/wiki/HelpAddonsAccessControlContextOptions

ZAP expects the configured users to have valid credentials (i.e. correct username/password) otherwise that's the same as the unauthenticated user.

**Comment by thc202** [comment]
Also note that the Authorized column indicates if the user was able to access the page or not (so that might indicate that the Authorization of the context was not correctly set up).

**Comment by kingthorin** [comment]
@Vivek-NSI did thc202 answer your questions/concerns? Can this be closed?

**Comment by kingthorin** [comment]
No further input in over a month. Closing.
