### ISSUE TITLE
Do we have any blog or document etc. that will explain how ZAP can be used to verify all 2017 OWASP vulnerability

### ISSUE THREAD

**Issue by Vivek-NSI** [zaproxy/zaproxy#4774]
Do we have any blog or document etc. that will explain how ZAP can be used to verify all 2017 OWASP vulnerability?

**Comment by psiinon** [comment]
We have this on the OWASP wiki: https://www.owasp.org/index.php/ZAPpingTheTop10
In the future please ask questions on the ZAP User Group: https://groups.google.com/group/zaproxy-users - its a more suitable forum than github issues.
