### ISSUE TITLE
ZAP Jenkins Plugin not catching new security fixes due to the usage previously recorded session

### ISSUE THREAD

**Issue by hnestorova** [zaproxy/zaproxy#4778]
Hi,

I am using the Jenkins plug-in to run ZAP tests towards an application. The sessions run have been previously recorded. Does this mean that any new fixes that involve parameters removal, for e.g., won't be acknowledged by ZAP and it will continue issuing an alert until a new session with the fix is recorded? Also, if so, is there any way to run the tests in a way that new changes will be taken into consideration?

Thank you in advance,

Hristina.

P.S. This is a general question but do let me know about any additional info you may require to answer

**Comment by thc202** [comment]
Closing, this is being handled in: https://groups.google.com/d/topic/zaproxy-jenkins/k2M7Az6bbJQ/discussion
