### ISSUE TITLE
ZAP permanently at the top of the desktop windows in "breaking point" mode

### ISSUE THREAD

**Issue by LuigiCasciaro** [zaproxy/zaproxy#4779]
**Describe the bug**
When you activate the "break on all requests and responses" feature after activating proxy mode, ZAP remains at the top of the desktop and the only way to minimize it is to press the minimize button while the switching with other applications does not work.
Furthermore, the behavior does not change when the breakpoint mode is stopped (only if there are still some pending requests breaking). 

**To Reproduce**
1. Lunch the Zap JxBrowser
2. Lunch "Set break on all requests and responses"
3. Press "ok" on the "foreground mode" ZAP request

**Expected behavior**
The behavior I expect is that once you have a break point, ZAP rightly passes in the foreground but you can still browse through the other windows.

**Software versions**
 - ZAP: 2.7.0

**Comment by kingthorin** [comment]
You can turn off the 'always on top' option via https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsOptionsBreakpoints#zap-always-on-top-when-breakpoint-hit

**Comment by kingthorin** [comment]
Or you could be hitting this: https://github.com/zaproxy/zaproxy/issues/3075 ?

**Comment by LuigiCasciaro** [comment]
Yes, it is the same. Regarding the fact that ZAP does not want to relinquish it's position "on top", I found it happens only if, after pressing stop button, there are still requests intercepted but not "skipped" ahead.
More in general, I think that when ZAP goes on foreground, it should still be possible to switch to other applications.

**Comment by thc202** [comment]
That's the expected behaviour if there are still messages caught, it only stops being always on top when there are no more messages (this behaviour can be disabled with the above option). Is ZAP window still on top when there are no more messages?

**Comment by LuigiCasciaro** [comment]
Ok, I thought it was an abnormal behavior. For the rest it's ok.
