### ISSUE TITLE
Tidy up dependencies

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#4780]
Tracker issue to tidy up the dependencies, used by the `zaproxy` project, for 2.8.0 release.

From OWASP ZAP Developer Group: https://groups.google.com/d/topic/zaproxy-develop/wN6HtAKOFfw/discussion

Remove dependencies not used by core nor add-ons (in `zap-extensions`):
 - [x] Apache HttpComponents HttpCore/HttpClient. Done in #4794.

Remove dependencies in use but not really needed:
 - [x] BrowserLauncher, it's used in core as fallback and in one add-on (not currently available in the marketplace). This is effectively replaced with a JRE class (`java.awt.Desktop`). Done in #4782, zaproxy/zap-extensions#1683, and zaproxy/zap-extensions#1685.
 - [x] JavaFX runtime, only required by an add-on. It would rely on the JRE (e.g.
OracleJDK, OpenJDK+OpenJFX). Done in #4785.

**Comment by kingthorin** [comment]
Since this is 3/3 can it be closed?

**Comment by thc202** [comment]
Still plan to check other dependencies (e.g. diffutils) and update others.

**Comment by kingthorin** [comment]
Ping :grin:

**Comment by thc202** [comment]
This will be done after the migration to Gradle.

**Comment by thc202** [comment]
Closing, all changes done.
