### ISSUE TITLE
Test a single api using zap without importing swagger file 

### ISSUE THREAD

**Issue by thivyae** [zaproxy/zaproxy#4787]
Hi,
My project doesnt have a api documentation in place but i have all the necessary endpoint details with me to get started.Is there any way to test a api using zap without importing swagger doc?

**Comment by thc202** [comment]
Yes, you just need to access them while proxying through ZAP (that has the same effect as importing).

**Comment by thivyae** [comment]
Hi @thc202 Is there any link that i can refer to for proxying api request thru zap?

**Comment by kingthorin** [comment]
Web traffic is web traffic is web traffic 😀 Point whatever browser or client at ZAP as an HTTP Proxy and use the end point.

**Comment by thivyae** [comment]
Hi my browser doesn't register the rest calls which I make via postman or
any rest client.can u shade some more light on this?

**Comment by kingthorin** [comment]
If you're using Postman with Chrome, set your proxy settings in Chrome and the Postman requests will show in ZAP.

**Comment by kingthorin** [comment]
No further input in ~1month. Closing.
