### ISSUE TITLE
Break tab is not automatically shown in full layout when breakpoint is hit

### ISSUE THREAD

**Issue by fd0** [zaproxy/zaproxy#4789]
**Describe the bug**

When the "full layout" is active, the Break tab is not yet added and global break is enabled, the Break tab is not shown when a breakpoint is hit. This means that users are not aware that there's an HTTP request still waiting for interaction, it's just hanging there.

Manually adding the Break tab then shows the hanging request so users can decide what to do with it.

**To Reproduce**
1. Start ZAP
1. Activate "full layout" by clicking on the icon in the icon list
1. Break tab should not be added already
1. Activate global break
1. Make an HTTP request
1. Nothing happens, Break tab does not appear
1. Add the Break tab manually via the + sign in the tab bar
1. Intercepted HTTP request is shown

**Expected behavior**

Break tab should appear automatically in "full layout" mode.

**Software versions**
 - ZAP: 2.7.0
 - OS: Debian stable 9.4 ("stretch")
 - Java: openjdk 1.9, Debian version number: `9~b181-4~bpo9+1`, package `openjdk-9-jre`

**Comment by kingthorin** [comment]
I'm able to recreate this. 

I also noticed in Full Layout you can choose to show the Break and Break Points tab (from the green + control). However, if you switch back to the default layout the Break tabs seem to have gone missing (they don't show on global break, and they don't show in the green + control).

**Comment by thc202** [comment]
The latter should be on dev/weekly only.

**Comment by kingthorin** [comment]
Right, I was using a dev setup.

**Comment by fd0** [comment]
Awesome, thanks!
