### ISSUE TITLE
Zap Jenkins Plugin scan the list of URL's?

### ISSUE THREAD

**Issue by HUssain14** [zaproxy/zaproxy#4795]
Providing the list of URL's but it's getting stuck over Attack Mode (Spider). Suggestion required.
![screenshot from 2018-06-26 14-30-14](https://user-images.githubusercontent.com/36950281/41905135-b0b1bcfc-7953-11e8-80e9-dbf7cc5a50f0.png)

**Comment by thc202** [comment]
Closing, this is already being asked in ZAP Jenkins Plugin: https://groups.google.com/d/topic/zaproxy-jenkins/shAAJJ4QdsE/discussion

We'll answer there.
