### ISSUE TITLE
ZAP doesn't start with java 9 in kali xfce

### ISSUE THREAD

**Issue by vschs007** [zaproxy/zaproxy#4798]
**Describe the bug**
zaproxy don't start with java 9 in kali xfce

**To Reproduce**
1. Install java 9 in your kali xfce
2. start zproxy
3. a message will be shown "Exiting: ZAP requires a minimum of Java 7 to run, found 9.0.4"

**Expected behavior**
It should be open

**Screenshots**
See below.

**Software versions**
 - OS: Kali Linux XFCE
 - Java: [9.0.4]

**Comment by vschs007** [comment]
![zap](https://user-images.githubusercontent.com/17596607/41980630-8fe91b40-7a44-11e8-8a46-2b8477b42ffa.png)

**Comment by thc202** [comment]
Are you using the latest ZAP version in Kali? That should be addressed in 2.7.0 (#3759).

**Comment by vschs007** [comment]
yes i am on latest zaproxy 2.7.0

**Comment by vschs007** [comment]
issue resolved

**Comment by kingthorin** [comment]
Could you be more specific in order to help others?

**Comment by vschs007** [comment]
updated version has no compatibility issues with java 9 ,
