### ISSUE TITLE
IRC information in README

### ISSUE THREAD

**Issue by franklinyu** [zaproxy/zaproxy#4799]
> * IRC: irc.mozilla.org #websectools (eg using Mibbit) - chat with core ZAP developers (European office hours usually best)

Is this information outdated? I cannot find `#websectools` in [list of channels in Mozilla IRC](https://wiki.mozilla.org/IRC).

**Comment by thc202** [comment]
It's not, the channel exists and it's active. Probably no one added the channel to that list (yet).

**Comment by franklinyu** [comment]
Thanks. I will try to contact the Mozilla wiki team to update that.

**Comment by thc202** [comment]
OK. After rereading that, I guess it's not listed because it's not one of the commonly used channels (there are currently more than 1000, the majority is not listed there).

**Comment by psiinon** [comment]
I'm a Mozilla employee and _could_ update the wiki ... but I havnt because, as @thc202 pointed out, its not one of the most commonly used channels and so doesnt really belong there :)
