### ISSUE TITLE
form based authentication in url with anchor 

### ISSUE THREAD

**Issue by javabeanz** [zaproxy/zaproxy#4804]
**Describe the bug**
Anchor urls are not shown in the Sites explorer and therefore not selectable in the Session properties > authentication url.  Anchors parts are not sent to the server and therefore not captured by Zap Proxy. When the authentication form is inside an anchor url it cannot be selected as basis for the form authentication.

**To Reproduce**
1. Go to juice shop Docker 
2. Click on http://localhost:3000/#/login
3. go to Zap Sites explorer
4. no http://localhost:3000/#/login shown, way to aiuthenticate in Session Properties menu.

**Expected behavior**
A work around to be able to work around this limitation, for instance to add a manual URL to the Sites tree with anchor

**Screenshots**
see https://hub.docker.com/r/bkimminich/juice-shop/

**Software versions**
 - ZAP: 2.7.0
 - Add-on: all default settings
 - OS: Fedora 28
 - Java: openjdk 1.8.0_172
 - Browser: Firefox 60

**Errors from the zap.log file**
no errors

**Additional context**
anchors are often overlooked by developers. With the popularity of one page web applications, web anchors are more important. Here the proxy nature of the ZAP setup breaks down, because so much is going on on the client side that the proxy doesnt know of.

**Comment by thc202** [comment]
Note that the actual login request/URL is `http://localhost:3000/rest/user/login `.

**Comment by kingthorin** [comment]
@javabeanz did thc202's tip help  you get past the issue?

**Comment by javabeanz** [comment]
As a workaround it works.

But this means that you need to know the REST calls that are related to the login, when you only see a login form with an anchor url. Maybe there is an easier way to help ZAP users with this.

**Comment by kingthorin** [comment]
Yes you actually have to know how authentication works in order to setup authentication. There is work underway to simplify/aide users in setting this up.

**Comment by thc202** [comment]
For the record, the above is being tracked in #4105.

**Comment by javabeanz** [comment]
digging a bit further was a bit disappointing:
- after some spidering ZAP often hangs and i have to shutdown ZAP
- the user from the  POST to /rest/user/login as auth context is not shown in the Session Properties window; it seems json is not yet handled well ? (seems covered in #4105 )
- after Launch Browser Firefox I have to delete 35 irrelevant domains in my tree (maybe thats a Fedora only thing)
- reloading a stored session failed
- several stacktraces on the console
yes, its not positive, but i hope this makes the product better
