### ISSUE TITLE
GET http://XXXX/me/profiles?query=query+%2F+sleep%2815%29+

### ISSUE THREAD

**Issue by thivyae** [zaproxy/zaproxy#4809]
I have added advanced sql injection rules for my endpoint.
What does query=query mean?

I'm getting an vulnerability reported by zap saying "Advanced SQL Injection - AND boolean-based blind - WHERE or HAVING clause " but there are no other app user data thrown apart from my profile results.
Wanted to check if it might be false positive? and also what does query=query+... mean?is it a valid syntax fr mysql?

**Comment by thivyae** [comment]
Any thoughts?

**Comment by kingthorin** [comment]
@thivyae anything further on this?

**Comment by thivyae** [comment]
Yes,its resolved

Thivyalakshimi Easwarasekaran
Quality Analyst
Email thivyae@thoughtworks.com
Telephone +91 9789805026 <+91+9789805026>
[image: ThoughtWorks]
<http://www.thoughtworks.com/?utm_campaign=thivya-lakshimi%20e-signature&utm_medium=email&utm_source=thoughtworks-email-signature-generator>
