### ISSUE TITLE
User-Agent changes from configured value

### ISSUE THREAD

**Issue by leoppp** [zaproxy/zaproxy#4846]
When using the ZAP gui I found that in certain circumstances the default user agent defined in tools-options-connection was not used. Instead an older user agent was used.

To reproduce, set value to 'Firefox 39.0 Win8.1 64-bit' and attack a URL.

Expected behaviour is that all pages will be attacked with the same user agent that has been set as above.

Request for alert "Content-Security-Policy (CSP) Header Not Set":
![image](https://user-images.githubusercontent.com/23527218/42765149-4558f92c-890f-11e8-8ab3-dfb3c156193e.png)

Response - note CSP is set. I believe the X-CSP header is set as a result of the IE6 user agent as it normally appears as CSP without the X:
![image](https://user-images.githubusercontent.com/23527218/42765449-fa1dd9c2-890f-11e8-8d61-3403080c50a4.png)

Request for alert "Timestamp Disclosure - Unix":
![image](https://user-images.githubusercontent.com/23527218/42765254-806c528e-890f-11e8-9e38-3115e3cff149.png)

OWASP ZAP Version 2.7.0 on Linux (Kali) and Windows 10 64-bit

**Comment by leoppp** [comment]
No comments?

**Comment by thc202** [comment]
Yes, seems to be a bug, in theory all components should be already using the configured user agent when creating default messages. Do you still have the session around? It would be great to know the type of that message.

**Comment by leoppp** [comment]
It's easy enough to recreate. What do you mean by the type of message? What info do you need?

**Comment by psiinon** [comment]
If we could reproduce it then we'd be able to get all the info we need :)
So do you have any steps we can follow?

**Comment by leoppp** [comment]
Well, the steps are in the original message, but here they are again, expanded:

To reproduce, 

- tools->options->connection->default user agent
   set value to 'Firefox 39.0 Win8.1 64-bit'
- attack a url - to ensure it worked on a public URL I attacked google.com for about 30 seconds
- examining the headers will reveal that the user agent is usually Mozilla/5.0, but occasionally Mozilla/4.0
   In my scan this was, for example, **`Incomplete or No Cache-control and Pragma HTTP Header Set`** on the first entry: **`GET: https://www.google.com/`**

Expected behaviour is that all pages will be attacked with the same user agent that has been set in 'connection' as above.

**Comment by thc202** [comment]
How is the target being accessed? Spider? Proxy?

The type indicates which component (spider, manually, proxy...) created the request. The type is not exposed in the UI (you would have to use the ZAP API, one of the message/alert core endpoints).

**Comment by leoppp** [comment]
I wasn't using the API, I used the quick attack form on the welcome page of the UI. No proxy. The attack progressed through spider and scan.

**Comment by thc202** [comment]
A new version of Quick Start add-on is available in the marketplace, it should address that.

**Comment by leoppp** [comment]
Great thanks!

**Comment by thc202** [comment]
Reopening, still pending core changes to prevent similar issues.
