### ISSUE TITLE
I want scan few specific url it is both get and post method

### ISSUE THREAD

**Issue by idtestingking** [zaproxy/zaproxy#4849]
I'm using cent OS
started ZAP using below 
zap-cli start
Imported context file. [ i recorded few url using zap [windows with GUI Export to context].
after that i imported into cent os non gui 
using below command i imported
zap-cli context import /root/XXX/XXX.context
after that i used below command to scan it 
zap-cli quick-scan -s all https://demo.com/

It is navigating to other link except the one which i gave. please help me to resolve it. i want to scan few url's using ZAP-CLI on Centos

**Comment by psiinon** [comment]
The context file doesnt contain the URLs accessed by ZAP - thats stored in the ZAP session.
zap-cli is a third party product, so I'm not absolutely sure what its doing, but I'm guessing that the quick-scan maps onto the ZAP quick start scan. If so then that doesnt use a context in any case.
You'll need to either:

1. Save a ZAP session containing the URLs you accessed, and then reload that before scanning, or
1. Record the URLs using something like Zest and replaying them, or
1. Use either the standard or Ajax Spider to explore your app

I'm not sure whether zap-cli supports any or all of those options..

**Comment by idtestingking** [comment]
Thank you let me try..
