### ISSUE TITLE
Nashorn deprecated in Java 11

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#4851]
Tracker issue for the status of Nashorn JavaScript engine following deprecation, for removal, in Java 11: http://openjdk.java.net/jeps/335

If no one picks the engine we would have to bundle an alternative (e.g. https://github.com/mozilla/rhino).

**Comment by Pamplemousse** [comment]
If the APIs between Nashorn and Rhino has changed, then migrating from one to the other might break some [community scripts](https://github.com/zaproxy/community-scripts).

According to GitHub, 70.8% ([69 scripts](https://github.com/zaproxy/community-scripts/search?l=javascript)) of these are written in Javascript...

**Comment by thc202** [comment]
They are not the same, we already had that problem when moving from Rhino to Nashorn...

**Comment by kingthorin** [comment]
https://medium.com/graalvm/oracle-graalvm-announces-support-for-nashorn-migration-c04810d75c1f

**Comment by kingthorin** [comment]
https://jaxenter.com/nashorn-deprecation-interview-caldwell-146951.html
https://www.infoworld.com/article/3291322/oracle-switch-now-from-nashorn-javascript-engine-to-graalvm.html

**Comment by thc202** [comment]
For the record, GraalVM JavaScript engine has a compatibility mode for Nashorn.

**Comment by thc202** [comment]
The Nashorn engine will be removed in Java 15: https://openjdk.java.net/jeps/372

**Comment by thc202** [comment]
Closing this as done, the GraalVM JavaScript add-on is now available in the marketplace which can be used to run older JavaScript scripts (might require changes in some cases).
