### ISSUE TITLE
False positive SQL injection alerts

### ISSUE THREAD

**Issue by hnestorova** [zaproxy/zaproxy#4852]
ZAP issues a false positive SQL injection alert for the followng response (I have replaced some real values with 'PRIVATE' here due to security issues):
```
HTTP/1.1 200
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Set-Cookie: JSESSIONID=PRIVATE; Path=/PRIVATE; HttpOnly
Cache-Control: no-cache
Content-Type: text/html;charset=ISO-8859-1
Content-Length: 5792
Date: Tue, 17 Jul 2018 08:59:39 GMT
```

In the request body html, our application is printing an error -
```
head>
	<title>PRIVATE- Error Page</title>
	
<meta http-equiv="Content-Type" content="text/html"/>
```
and so on

Does ZAP expect some specific response code that is not 200 ?

**Comment by hnestorova** [comment]
another response body to a request again marked as SQL injection success is:

{"id":11,"error":{"msg":"Internal Server Error","trace":"java.lang.IllegalArgumentException: Internal Server Error | {"id":11,"error":{"msg":"Internal Server Error","trace":"java.lang.IllegalArgumentException: Internal Server Error
-- | --
{"id":11,"error":{"msg":"Internal Server Error","trace":"java.lang.IllegalArgumentException: Internal Server Error

**Comment by psiinon** [comment]
Whats the confidence in the alert?
And is there any additional information?
The fact that an SQL injection attack caused an internal server error could in fact be indicative of an SQLi vulnerability, so I think there is an argument for reporting these. But we do need to make sure that the associated info makes it clear that these are just possibilities and not likelihoods.

**Comment by kingthorin** [comment]
> Does ZAP expect some specific response code that is not 200 ?

Not specifically. The response from the original request is compared against the response from the injected request, etc. 

However, that you provide an error response that's marked 200 - Ok is perhaps not good form (in general ... separate from ZAP or SQLi).

**Comment by hnestorova** [comment]
Hi,

The confidence is medium.
I checked the response of the original request for the {"id":11,"error":{"msg":"Internal Server  blabla and it is: {"result":null,"id":11} . So, even if there is some other problem on our side, the responses are not identical, are they?

**Comment by thc202** [comment]
Could you provide the details of the alert? (Name, description, other info...) That should help check what test is being performed and why it's not working correctly.

**Comment by hnestorova** [comment]
Description
SQL injection may be possible.
Solution
Do not trust client side input, even if there is client side validation in place.  
In general, type check all data on the server side.
If the application uses JDBC, use PreparedStatement or CallableStatement, with parameters passed by '?'
If the application uses ASP, use ADO Command Objects with strong type checking and parameterized queries.
If database Stored Procedures can be used, use them.
Do *not* concatenate strings into queries in the stored procedure, or use 'exec', 'exec immediate', or equivalent functionality!
Do not create dynamic SQL queries using simple string concatenation.
Escape all data received from the client.
Apply a 'whitelist' of allowed characters, or a 'blacklist' of disallowed characters in user input.
Apply the principle of least privilege by using the least privileged database user possible.
In particular, avoid using the 'sa' or 'db-owner' database users. This does not eliminate SQL injection, but minimizes its impact.
Grant the minimum database access that is necessary for the application.
Reference
https://www.owasp.org/index.php/Top_10_2010-A1 https://www.owasp.org/index.php/SQL_Injection_Prevention_Cheat_Sheet
URI
POST : http://PRIVATE/PRIVATE/GLOBAL-JSON-RPC?query=%22
Confidence
Medium
Parameter
query
Attack
"
Evidence
com.microsoft.sqlserver.jdbc
OtherInfo
RDBMS [Microsoft SQL Server] likely, given error message regular expression [\Qcom.microsoft.sqlserver.jdbc\E] matched by the HTML results.
The vulnerability was detected by manipulating the parameter to cause a database error message to be returned and recognised
RequestHeader
POST http://PRIVATE/PRIVATE/GLOBAL-JSON-RPC?query=%22 HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0
Accept: */*
Accept-Language: bg,en-US;q=0.7,en;q=0.3
Content-type: text/plain
Content-Length: 85
Connection: keep-alive
Host: PRIVATE
Cookie: JSESSIONID=PRIVATE


RequestBody
{id:11,method:"PRIVATE.PRIVATE",params:["PRIVATE"]}
ResponseHeader
HTTP/1.1 200
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Content-Type: application/json;charset=utf-8
Content-Length: 5237
Date: Tue, 17 Jul 2018 11:53:14 GMT


ResponseBody
{"id":11,"error":{"msg":"Internal Server Error","trace":"java.lang.IllegalArgumentException: Internal

**Comment by kingthorin** [comment]
Per the Evidence the injection did cause a SQL error `com.microsoft.sqlserver.jdbc`...

**Comment by hnestorova** [comment]
yes, there was a deadlock on our side.  Let me monitor our tests results for a few days for the problem below. I will post an update if/when the issue reoccurs:
ead>
	<title>PRIVATE- Error Page</title>

**Comment by hnestorova** [comment]
Hi, today the issue with the Error in the Response body got reproduced. Here are some details, please, let me know what you find:
URI
POST : http://PRIVATE/PRIVATE/PRIVATE/login?query=query%27+AND+%271%27%3D%271%27+--+
Confidence
Medium
Parameter
query
Attack
query' OR '1'='1' -- 
OtherInfo
The page results were successfully manipulated using the boolean conditions [query' AND '1'='1' -- ] and [query' OR '1'='1' -- ]
The parameter value being modified was NOT stripped from the HTML output for the purposes of the comparison
Data was NOT returned for the original parameter.
The vulnerability was detected by successfully retrieving more data than originally returned, by manipulating the parameter

RequestHeader
POST http://PRIVATE/PRIVATE/PRIVATE/login?query=query%27+AND+%271%27%3D%271%27+--+ HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: bg,en-US;q=0.7,en;q=0.3
Referer: http://PRIVATE/PRIVATE/login.jsp;jsessionid=PRIVATE?/PRIVATE/
Content-Type: application/x-www-form-urlencoded
Content-Length: 45
Connection: keep-alive
Upgrade-Insecure-Requests: 1
Host: PRIVATE
Cookie: JSESSIONID=PRIVATE


RequestBody
userName=PRIVATE&passwordName=PASSWORD&password=PRIVATE

ResponseHeader
HTTP/1.1 200
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Set-Cookie: JSESSIONID=PRIVATE; Path=/PRIVATE; HttpOnly
Cache-Control: no-cache
Content-Type: text/html;charset=ISO-8859-1
Content-Length: 5812
Date: Thu, 19 Jul 2018 01:09:11 GMT

ResponseBody
<head>
	<title>PRIVATE - Error Page</title>
	
<meta http-equiv="Content-Type" content="text/html"/>


<link rel="stylesheet" type="text/css" href="/PRIVATE/css/PRIVATE-access.css" />
<link rel="stylesheet" type="text/css" href="/PRIVATE/css/helpTooltip.css" />
blabla
</head>
<div class="error" style="font-size: 16px">
PRIVATE</div>

**Comment by kingthorin** [comment]
Looks valid to me based on the limited info shared.

**Comment by psiinon** [comment]
Yeah, if an SQL injection attack causes the app to return an error page then I'd definitely think that should be looked into.
It not definitely an SQLi vuln, but its very suspicious.

**Comment by hnestorova** [comment]
Actually, this request is for a login and, since the request is not valid for our API, it throws an error. Why should this be interpreted as a successful SQL injection?

**Comment by kingthorin** [comment]
`The page results were successfully manipulated using the boolean conditions [query' AND '1'='1' -- ] and [query' OR '1'='1' -- ]
The parameter value being modified was NOT stripped from the HTML output for the purposes of the comparison
Data was NOT returned for the original parameter.
The vulnerability was detected by successfully retrieving more data than originally returned, by manipulating the parameter`

If you tested further and disagree you can mark it False Positive in ZAP and for future scans you can implement a Context Alert Filter for it (see the marketplace for the extension).

**Comment by psiinon** [comment]
All security tools have to deal with edge cases. In this case I think ZAP is right to report it, but I guess we could reduce the confidence as theres no direct evidence of a successful attack.

**Comment by hnestorova** [comment]
OK, if we decide to mark the alert as false positive, would this be possible if the test is run using the ZAP plugin from Jenkins? To have a valid up-to-date results, for each run, we copy a clean session in which all alerts have been deleted, as I was previously advised by @thc202 .

**Comment by kingthorin** [comment]
Yup, just setup a Context Alert Filter.

**Comment by hnestorova** [comment]
I found how to do it, I will try this then, thanks

**Comment by hnestorova** [comment]
[Res_Header.txt](https://github.com/zaproxy/zaproxy/files/2245962/Res_Header.txt)
[Req_Body.txt](https://github.com/zaproxy/zaproxy/files/2245963/Req_Body.txt)
[Req_Header.txt](https://github.com/zaproxy/zaproxy/files/2245964/Req_Header.txt)
[Orig_Req.txt](https://github.com/zaproxy/zaproxy/files/2245965/Orig_Req.txt)
[Orig_Res.txt](https://github.com/zaproxy/zaproxy/files/2245966/Orig_Res.txt)
[alert.txt](https://github.com/zaproxy/zaproxy/files/2245967/alert.txt)





@kingthorin , @psiinon , @thc202 , do you compare response body size only, or do you also check the response header size? I am attaching the original request/response and the one after active scan. The response body is empty but still, the alert is for positive for SQL injection. There is a difference in the response header.

**Comment by hnestorova** [comment]
@kingthorin , @psiinon , @thc202 , any feedback?

**Comment by kingthorin** [comment]
I have nothing to add beyond what I said 19days ago.

**Comment by hnestorova** [comment]
ok, then @psiinon  or @thc202  could you tell me:
" do you compare response body size only, or do you also check the response header size? I am attaching the original request/response and the one after active scan. The response body is empty but still, the alert is positive for SQL injection. There is a difference in the response header."

**Comment by kingthorin** [comment]
The code for the SQLi scan rules can be found here:

- https://github.com/zaproxy/zap-extensions/blob/master/src/org/zaproxy/zap/extension/ascanrules/TestSQLInjection.java
- https://github.com/zaproxy/zap-extensions/blob/beta/src/org/zaproxy/zap/extension/ascanrulesBeta/SQLInjectionHypersonic.java
- https://github.com/zaproxy/zap-extensions/blob/beta/src/org/zaproxy/zap/extension/ascanrulesBeta/SQLInjectionMySQL.java
- https://github.com/zaproxy/zap-extensions/blob/beta/src/org/zaproxy/zap/extension/ascanrulesBeta/SQLInjectionOracle.java
- https://github.com/zaproxy/zap-extensions/blob/beta/src/org/zaproxy/zap/extension/ascanrulesBeta/SQLInjectionPostgresql.java
- https://github.com/zaproxy/zap-extensions/blob/alpha/src/org/zaproxy/zap/extension/ascanrulesAlpha/SQLInjectionMsSQL.java
- https://github.com/zaproxy/zap-extensions/blob/alpha/src/org/zaproxy/zap/extension/ascanrulesAlpha/SQLInjectionSQLite.java

**Comment by hnestorova** [comment]
:) good to know. I am trying to make things understandable and working on our side, not trying to waste your time, if that's what it appears to be. 
Thanks for the feedback.

**Comment by kingthorin** [comment]
No problem (it doesn't appear that way), it's just hard to pin point the exact cause of the issues that are reported and sometimes it easier for the reporters to take a gander at the code. Based on the alert.txt that you shared earlier it should be the first scanner that I linked that's raising the alert (not any of the tech specific ones).

The determination is not _only_ based on size, it's based on comparison of content between the original against a request with an always true condition and a request with an always false condition and two different variants of those (with and without removing any content that ZAP might have injected)...

**Comment by kingthorin** [comment]
Unless someone is able to provide further details, having read the code etc. I don't think there's anything further we can do with this ticket.
