### ISSUE TITLE
Zest client launches firefox with acceptInsecureCerts: false

### ISSUE THREAD

**Issue by josfyorobe** [zaproxy/zaproxy#4870]
**Description**
Zest client launches firefox browser that is unable to access https websites
From logs, acceptInsecureCerts is set to false

> Driver info: org.openqa.selenium.firefox.FirefoxDriver
> Capabilities {acceptInsecureCerts: false, browserName: firefox, browserVersion: 62.0, javascriptEnabled: true, moz:accessibilityChecks: false, moz:headless: false, moz:processID: 10660, moz:profile:...

Note: Unable to add capabilities via UI

**To Reproduce**
1. New Standalone Script
2. Add Zest Client -> set to firefox
3. set url to any site with https

**Screenshots**
![image](https://user-images.githubusercontent.com/17715678/43123816-eafd9b1e-8f57-11e8-9b24-ff1a54d5dea3.png)

![image](https://user-images.githubusercontent.com/17715678/43123749-b3b76298-8f57-11e8-8d42-e0c7ac6e564f.png)

**Expected behavior**

**Screenshots**

**Software versions**
 - ZAP: [note that we typically only support the latest version of ZAP]
 - Add-on: Zest, selenium
 - OS: Windows 10
 - Browser: firefox version 62.0b10 64bit

**Comment by thc202** [comment]
This has been addressed in Zest library (mozilla/zest#136), it will be addressed in ZAP side once updated in the add-on (#4797).

Regarding the capabilities, unfortunately the required one needs to be a boolean but it's set as string (which is then rejected), we would have to allow to define the type.

**Comment by cjuroz** [comment]
As a workaround we are using mozilla.cfg and firefox setting
> lockPref("security.enterprise_roots.enabled", true);

to make all firefox instances launched by zest use windows certificate store instead of firefox cert store. This is because zest launches browser with random clean profile and its cert store is also empty.

**Comment by arscek** [comment]
I am also having this issue in ZAP 2.8.0 and Firefox 69, setting the capability to true throws an exception in the console and shows the same message as the original post in the opened Window:
`org.openqa.selenium.InvalidArgumentException: acceptInsecureCerts is not boolean: "true"
 os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.5', java.version: '1.8.0_212'
Driver info: driver.version: FirefoxDriver`

**Comment by thc202** [comment]
This was not yet fixed in the Zest add-on, still waiting for #4797.
