### ISSUE TITLE
Add an Export button for AJAX Spider

### ISSUE THREAD

**Issue by rkhal101** [zaproxy/zaproxy#4875]
It would be nice to have an export button for the AJAX Spider URLs just like the one present on the Spider tab.

**Comment by kingthorin** [comment]
Agreed.

Note (for the time being) you can do a select all in the table and copy/paste the content.

**Comment by kingthorin** [comment]
Unless someone knows of lots of requests for this I'd propose that it wait until after 2.8.0 as it can then take advantage of `org.zaproxy.zap.utils.TableExportButton`

**Comment by thc202** [comment]
That's available in 2.7.0 (based on the since tag).

**Comment by kingthorin** [comment]
Oh, I looked at where it was used but hadn't actually looked at the class itself.... I'll go dig more.

**Comment by thc202** [comment]
Released in version 22 of Ajax Spider add-on.
