### ISSUE TITLE
Allow More than One Url in Default Context Using Right Click

### ISSUE THREAD

**Issue by rkhal101** [zaproxy/zaproxy#4876]
If I load multiple URLs of my application and I want to include them in my default context, I can do that by clicking the Session Properties icon and then adding the URLs under Contexts>Default Context>Include in Context. 

However, if I right click on the URL from the History tab or the Sites tree, it only allows me to include one URL in the Default Context. If I try the same method with another URL, the option is no longer allowed. I would have to go through the Session Properties window to get around it.

![context](https://user-images.githubusercontent.com/19655290/43238887-1d0aba40-905e-11e8-9a67-dcf2a69955e4.png)

**Comment by thc202** [comment]
That means the selected URL is already included in the context.

**Comment by rkhal101** [comment]
In this particular situation, I was running zap on the wavsep application. Below are the exact steps I made:
1. Load wavsep on my configured browser so that it appears in the History tab of ZAP. The link was:  http://localhost:8090/wavsep/.
2. Load the index-active.jsp page on my configured browser so that it appears in the History tab of ZAP. The link was: http://localhost:8090/wavsep/index-active.jsp.
3. Go to the History tab > right click on the URL http://localhost:8090/wavsep/ > select Include in Context > select Default Context.
4. In the History tab right click on the URL  http://localhost:8090/wavsep/index-active.jsp > select Include In Context > the Default Context is greyed out.

I checked in the Session Properties window and the only URL included is http://localhost:8090/wavsep/.

**Comment by thc202** [comment]
Is that exactly the regex included? Or it has `.*` at the end?

Which version are you using?

**Comment by rkhal101** [comment]
Yes, sorry, in the session properties window the URL included has a .* at the end. The version I'm using is 2.7.0.
