### ISSUE TITLE
False Positive in Path Traversal and Backup File Disclosure

### ISSUE THREAD

**Issue by CSPF-Founder** [zaproxy/zaproxy#4878]
The scanner is giving too much false positive for path traversal and backup file disclosure.  One of the reasons is that the website is giving 200 status code for non-existing pages also.  

The algorithm of these two extensions should be improved.  

The possible solutions are:
* Checking the signature of the pages of different inputs:  For example, when checking path traversal, it should compare the page sources produced for two different inputs. 
*  It should also check the 404/500/403 page signature and compare it with the page source produced for the inputs.

**Comment by kingthorin** [comment]
The first idea might work for certain situations with the Path Traversals but not all of them. The code for that particular rule is here if you want to submit a PR: https://github.com/zaproxy/zap-extensions/blob/master/src/org/zaproxy/zap/extension/ascanrules/TestPathTraversal.java

Checking status codes isn't terribly reliable as numerous apps and servers are non-compliant (as you've outlined).

**Comment by kingthorin** [comment]
Anyone have further input on this?

Note the future Custom Error Pages functionality can be leveraged to provide support for option 2 in the  (see issue: zaproxy/zaproxy#9 for further details).
