### ISSUE TITLE
ZAP Alert Filter not working with Jenkins

### ISSUE THREAD

**Issue by hnestorova** [zaproxy/zaproxy#4880]
I have added an alert filter but, when the test is run from Jenkins, I see:
[ZAP Jenkins Plugin] ALERT FILTERS: [ None ]

**Comment by psiinon** [comment]
I'd be surprised if that was a ZAP bug. Its more likely to be a problem with the ZAP Jenkins plugin, so maybe raise on https://issues.jenkins-ci.org/browse/JENKINS-52345?jql=project%20%3D%20JENKINS%20AND%20component%20%3D%20zap-plugin instead?

**Comment by hnestorova** [comment]
I posted it here:
https://groups.google.com/forum/#!forum/zaproxy-jenkins

Could you also let me know where I can see different examples of filters (if available)?

**Comment by thc202** [comment]
Closing, this is being handled in the mailing list.
