### ISSUE TITLE
Support new HTTP header Feature Policy

### ISSUE THREAD

**Issue by javabeanz** [zaproxy/zaproxy#4885]
**Is your feature request related to a problem? Please describe.**
Thee is  no problem, but it is coming when browsers support this new HTTP header.

**Describe the solution you'd like**
Detect holes in the Feature Policy similar to the CSP header, that could be epoited

**Describe alternatives you've considered**
I expect the Feature Policy header to have a report-only mode too to tune it 

**Additional context**
https://scotthelme.co.uk/a-new-security-header-feature-policy/
https://w3c.github.io/webappsec-feature-policy/

**Comment by Ketharan** [comment]
Hi.... I am interested to work with this project. Shall I start working on this issue?

**Comment by psiinon** [comment]
Please do :) 
I've sent you an invite to join this project as a collaborator - if you accept that then we'll be able to assign this issue to you.

**Comment by thc202** [comment]
@Ketharan do you know where to start? Have you already built ZAP and add-ons (zap-extensions repo)?

**Comment by Ketharan** [comment]
@thc202 I have built ZAP and add-ons. As I have understood need to add a scanner class extending the relevant parent class to check the availability of Feature Header in the HTTP response. But I am not sure where to add the scanner either in ascanrules or pscanrules. Much helpful If you can guide on that.

**Comment by kingthorin** [comment]
It should be added here: https://github.com/zaproxy/zap-extensions/tree/alpha/src/org/zaproxy/zap/extension/pscanrulesAlpha
(Note: alpha branch)

You'll also need to update ZapAddOn.xml (`changes` section, and add an entry to the `pscanrules` section).

**Comment by Ketharan** [comment]
What should be added to the `changes` section of the ZapAddOn.xml for this case?

**Comment by thc202** [comment]
Can be just `Add scanner for Feature Policy header` (IMO).

**Comment by kingthorin** [comment]
@Ketharan please open a PR for https://github.com/zaproxy/zaproxy/blob/develop/docs/scanners.md, reserving a plugin ID for the new scanner I'd suggest `1006 3`

**Comment by Ketharan** [comment]
https://github.com/zaproxy/zaproxy/pull/5261
Opened the PR reserving the plugin ID.

**Comment by Ketharan** [comment]
Opened the PR including the feature policy scanner https://github.com/zaproxy/zap-extensions/pull/1960
