### ISSUE TITLE
firefox fail to open 

### ISSUE THREAD

**Issue by c676228** [zaproxy/zaproxy#4891]
Hi,

I just downloaded and installed Zap from owasp web site. The version is 2.7.0.
When right click a URL --> attack --> AJAX spider. the popup says "fail to open firefox, is the browser installed or vailable"?
When right click a URL in sites window --> open URL in firefox (or chrome). It pops up:
failed to start browser, it gives the path for firefox.exe on my computer, which is right.
build info: version:'unknown', revision:'unknown', time: 'unknown'...

Thanks, 
Betty

**Comment by kingthorin** [comment]
What version is installed?

**Comment by psiinon** [comment]
And have you checked to see if there are any updates for the add-ons?
If you've only just installed 2.7.0 then there almost certainly will be.

**Comment by c676228** [comment]
Hi Simon,

I have just updated all the installed(One failed to update, quick start).
Same issue.

Thanks,
Betty

**Comment by thc202** [comment]
Which Firefox version is being used? Not all of them are supported (e.g. 52 ESR).

**Comment by c676228** [comment]
firefox quantum 61.0.1 (64-bit)

**Comment by kingthorin** [comment]
Could you remove Quick Start, close and re-open ZAP, and add Quick Start from the Market Place.

If that doesn't get it behaving could you provide the version info for all installed addons? https://github.com/zaproxy/zaproxy/wiki/FAQAddonVersions

**Comment by thc202** [comment]
Also, worth taking a look at the zap.log for any errors.

That Firefox version is supported, so the problem might be in geckodriver (old version?).

**Comment by c676228** [comment]
Some very weird things happened which never occurred to me before when I used version 2.6.0.
As I was trying to figure out what caused the strange behavior mentioned above. I downloaded it again from OWASP web site on my another computer (windows 10 which was upgraded from windows 8.1. it has zap version 2.6.0 installed before so I uninstalled this version before installing 2.7.0). After I installed 2.7.0 on my computer It keeps popping up "a threat is detected, quarantined". It doesn't stop the popup until I uninstalled Zap.
For now I uninstalled the app on both of my computers. It's pretty scary.
Oh, my God, I must be out of my mind.

**Comment by kingthorin** [comment]
Some of the fuzzdb files get picked up by AV products. If you can provide the details of the anti-virus alert we can confirm it aligns with what others have reported in the past.

**Comment by kingthorin** [comment]
@c676228 are further details coming or should we close this?

**Comment by c676228** [comment]
Hi Kingthorin,

The files are picked up by or Sophos are:

1) fuzzdb\web-backdoors\php\php-backdoor.php
2) NetCat

Please remove those files.

Thanks,
Betty

**Comment by c676228** [comment]
It says the php-backdoor.php is "Virus/spyware(Troj/Zonie-A)"
NetCat is "Adware or PUA"

**Comment by kingthorin** [comment]
Theyre included on purpose and are totally legit for penetration testing purposes. You can always uninstall the fuzzdb addon, create an AV exception, or install ZAP Core and add the addons you want/need.

**Comment by c676228** [comment]
Yes, I talked to our company already. We might add exceptions on a separated computer.

**Comment by c676228** [comment]
Kingthorin, thanks for your quick response.

**Comment by kingthorin** [comment]
Great. I can lookup other tickets or add a FAQ entry if that helps.

**Comment by psiinon** [comment]
@thc202 @kingthorin wdyt about splitting out the 'backdoors' section of fuzzdb into another add-on, and explaining in the description that it may get flagged by anti virus scanners?

**Comment by kingthorin** [comment]
Sure that seems fine, it's not like the add-on is updated too frequently so splitting should be simple enough.

This ticket/issue seems to have taken a sharp left turn, so I suggest if that's an enhancement we agree on it should be opened seperately and this one closed.

**Comment by thc202** [comment]
I'm ok with that.

Closing, nothing else to do.
