### ISSUE TITLE
[FrontEndScanner] Automatically manipulate CSP for it to work

### ISSUE THREAD

**Issue by Pamplemousse** [zaproxy/zaproxy#4893]
For now, the FrontEndScanner add-on requires the CSP header to be removed from responses.

(This could be done using the [community-scripts/proxy/Remove CSP](https://github.com/zaproxy/community-scripts/blob/master/proxy/Remove%20CSP.zst) for example).

  * This in not self-contained in this add-on. So it should provide a way to do it without relying on an external script.
  * For the page to behave similarly than in the "real" environment, it should relax the CSP rules as little as possible.
  * Because this update can fail or break the feature, leave the option to completely disable CSP.

~Needs #4894~.

**Comment by psiinon** [comment]
Note that the HUD already does this: https://github.com/zaproxy/zap-hud/blob/develop/src/main/java/org/zaproxy/zap/extension/hud/ExtensionHUD.java#L440-L445 so that code could be rippen off :)

**Comment by Pamplemousse** [comment]
As per discussion on IRC, automatic removal of CSP headers is an acceptable solution (which has been merged with zaproxy/zap-extensions#2490).
