### ISSUE TITLE
Unable to set values using command line 

### ISSUE THREAD

**Issue by ashkaps** [zaproxy/zaproxy#4912]
I am trying to start zap programmatically and also trying to pass some command line parameters. ZAP starts but the parameters are not set and i get error as soon as ZAP UI comes up. I have tried multiple ways. If I run zap.sh from Terminal and pass the same parameters, zap opens correctly with cmd passed values.

`private static final String NO_API_KEY = "-config api.disablekey=true"; 
//	https://github.com/zaproxy/zaproxy/wiki/FAQapikey
	private static final String NON_UI_MODE = "-daemon";
	public static final String ZAP_ADDRESS = "localhost";
	private static final String DEFAULT_ZAP_HOST = "-host " + ZAP_ADDRESS;
	public static final int ZAP_PORT = 8080;
	private static final String DEFAUlT_ZAP_PORT = "-port " + ZAP_PORT;
	private static final String ZAP_API_KEY = "None"; 
//	= "95aat12fikf41g1hfp550m6o6b"; // Change this if you have set the apikey in
																			
// ZAP via Options / API
	public static void OpenZAP() {
		String zapWorkingDirectory = "/Users/abcd/Downloads/ZAP_2.7.0/";
		String zapExecutableLocation = zapWorkingDirectory + "zap.sh";
		String commandToBuild = "-port 8090";
		String[] cmdarray = {zapExecutableLocation,commandToBuild};
		try {
// using Runtime
			Runtime.getRuntime().exec(cmdarray);
		} catch (IOException e) {
			e.printStackTrace();
		}
// Using ProcessBuilder 1
//		ProcessBuilder pb = new ProcessBuilder("java", "-jar",zapWorkingDirectory+"zap-2.7.0.jar", "-config api.disablekey=true","-d","-port 8090");
// Using ProcessBuilder 2
//				new ProcessBuilder(zapExecutableLocation, NO_API_KEY, DEFAULT_ZAP_HOST, DEFAUlT_ZAP_PORT);
//		pb.directory(new File(zapWorkingDirectory).getAbsoluteFile());
//		pb.redirectErrorStream(true);
//		pb.redirectOutput(new File("OWASPZAPOutputStream.txt"));
//		System.out.println("Trying to invoke the ZAP executable");
//		try {
//			Process p = pb.start();
//		} catch (IOException e) {
//			System.out.println(e);
//		}
		System.out.println("Waiting for successful connection to ZAP");
	}`

Error:
![screen shot 2018-08-08 at 2 13 34 am](https://user-images.githubusercontent.com/31744402/43801442-be954d56-9ab0-11e8-9284-cc3de85b91e3.png)

Any help is appreciated.
I have already gone through a lot of forums and help sites.

**Comment by thc202** [comment]
The `-port` and its value should be two arguments, e.g. `"-port", "8090"`. (Same for other command line arguments that have values.)

**Comment by ashkaps** [comment]
Thanks! This is resolved

**Comment by thc202** [comment]
Great, thanks for letting us know!
