### ISSUE TITLE
Questions for 'Basic Authentication' headers and Ajax Spider 

### ISSUE THREAD

**Issue by WeiserAriel** [zaproxy/zaproxy#4918]
Hey All,
I am trying to run Ajax spider for my web application but I have several problems I need your help with:

1. **_Basic Authentication_** - I can't manage to add basic authentication header for my requests using 'repeater', for some reason the header is added into another header which already exists ( please see picture attached ).
I tried to use both " Requset Header" & " Request Header String " :(

 Could you explain how to fix it? (Basically, I am trying to add new header without changing anything else in the request )

![basic](https://user-images.githubusercontent.com/41187619/44033504-406d3ca6-9f13-11e8-8f1a-583e5eadc3b8.PNG)

2. **_Failed to start AjaxSpider via ZAP UI_** - when trying to manually run it via the UI I am getting an error "Failed to start 'Firefox', is the browser installed/available?" Am I missing something here or that's a known issue? 

3. **_Ajax Spider in Python_** -  my last concern is how do to write a simple python script to check the Ajax Spider progress? 
my last one got into a deadlock.  what is the recommended value for time? any suggestion? 

Thank You!

**Comment by kingthorin** [comment]
When you said 'repeater' did you mean Replacer?

Is there a reason you're setting it up using Replacer instead of actually configuring a Context and Authentication?

**Comment by KajanM** [comment]
Regarding the first question, we don't manually add `Authorization` header, instead, we set up `ZAP` for authentication.

Setting up `ZAP` for `Basic authentication` is documented [here](https://docs.google.com/document/d/1ZwJoIORtS10gvgJBJ4zuEKoQEMJ8mcMT1TlXlbmTCn8/edit?usp=sharing).

PS: authenticationhelper1.1.0 add-on can auto-configure required authentication method for you. It is not yet available in ZAP marketplace though.

**Comment by kingthorin** [comment]
1. Here's the rule config you need:
![image](https://user-images.githubusercontent.com/7570458/44034919-4671cce8-9edc-11e8-8756-53d04aab1768.png)

The `Authorization` header won't be found and then it'll be added with the value you want.

2. `Failed to start 'Firefox', is the browser installed/available?` What's the answer? What version of Firefox is installed?

3. Similar to this: https://github.com/zaproxy/zap-api-python/blob/e904db1f42cdacbf3504d286d870f74447144551/src/examples/basic-spider-scan.py#L22-L31 only you're going to use the `ajaxSpider.status()` enpoint (checking looking for `running` or `stopped`) [based on the 15sec test I just did with the API web UI]

**Comment by WeiserAriel** [comment]
@kingthorin  / @KajanM  Thanks you so much for your quick reply!

as you said, I meant replacer and not repeater :) after changing the 'match string' attribute it worked as expected! 

> Is there a reason you're setting it up using Replacer instead of actually configuring a Context and Authentication?

you are right, I probably do it in the wrong way... I am just not sure which authentication method is required. This is the flow what I am trying to achieve:

_Starting the spider on the login page_, and automatically set the credentials 
![image](https://user-images.githubusercontent.com/41187619/44041545-b91c7dfc-9f26-11e8-98e1-7ab2e9d43d2b.png)

after Pressing 'Login' button REST request is being sent to the server with Basic Authentication.
and the user is moved to the Dashboard page.
![image](https://user-images.githubusercontent.com/41187619/44041791-4b04dc46-9f27-11e8-9327-da2af65c07bb.png)
Note- The reason I used the 'Replacer' is that I didn't see 'Basic Authentication' Header for this request and received 404 code from the server. 

After I arrived at the dashboard (main page) I would like to use the Spider/Ajax spider  and discover all other URL's which exist in this HTML ( i still don't see them on Spider result... why ? ) 
![image](https://user-images.githubusercontent.com/41187619/44042204-5b631dea-9f28-11e8-9b66-cc5487a27de7.png)

Note- You can see that all these REST calls ( in the picture above ) are using 'Basic Authentication' also!
This is why I decided to use the Replacer. Am I wrong here? 

Any guidance for test flow will be much appreciated! My 'workarounds' are probably not the best solution for my web application. 

in regards to 

> What version of Firefox is installed?
**This is the Firefox version:** 38.3.0

**Comment by kingthorin** [comment]
Using Replacer will probably work, but the intended mechanism is to setup a Context and use HTTP Authentication:
https://github.com/zaproxy/zap-core-help/wiki/HelpStartConceptsAuthentication#httpntlm-authentication

As for the Ajax Spider issues, I'm guessing your Firefox install is just too old. https://github.com/zaproxy/zap-core-help/wiki/HelpAddonsSeleniumIntro

**Comment by WeiserAriel** [comment]
Thanks @kingthorin 

after upgrading firefox for 61.0 version the problem fixed and the Ajax spider starts.

Could you please advise what should be the required Regex for adding 'http://10.10.10.10/example/'  into my content? ( i am getting 'out of scope' results for some of my URL's ). everything that starts with that URL should be inside.

**Comment by kingthorin** [comment]
Assuming you don’t use https and that only things below /example/ are in scope for your context just add the regex wildcard `.*` on the end.

**Comment by WeiserAriel** [comment]
Looks like the scope has now set correctly! Thanks! 

unfortunately, I am still fighting with starting my ajax spider with the correct authentication.
when running the spider through the UI it seems like the authentication doesn't work (username/password are not written into login form and I **have never reached the dashboard page** )

Could you advise me what do I do wrong here? these are steps I made:

1. Set 'Form-based Authentication" with username & password ( in my example it's admin:123456 )
![image](https://user-images.githubusercontent.com/41187619/44090045-80a8ac38-9fd1-11e8-885d-98a6ae0dce66.png)

2. Set Regex Pattern identified in Logged out:
auto-id-app-login-btn ( it appears on HTML )


3. Set User:
![image](https://user-images.githubusercontent.com/41187619/44089986-537d6b68-9fd1-11e8-9c9c-49198b1d48d3.png)

4. start Ajax spider in login page 
![image](https://user-images.githubusercontent.com/41187619/44090250-3f311870-9fd2-11e8-8285-92ce1f08e999.png)

I don't see any request for '/example/#/login... and I can't reach the /example/dashboard because of that.
![image](https://user-images.githubusercontent.com/41187619/44092814-3b8c228e-9fda-11e8-92c5-7f369712b9d3.png)

Thanks,
Ariel.

**Comment by kingthorin** [comment]
Is it Form based authentication or Basic?

If it's Basic as you said earlier, then you should be setting the auth type as `HTTP/NTLM Authentication`. https://github.com/zaproxy/zap-core-help/wiki/HelpStartConceptsAuthentication#httpntlm-authentication

Then when you start the AjaxSpider set the context as your starting point.

**Comment by thc202** [comment]
The login URL looks suspicious, it shouldn't have a fragment. For the spider seed it's preferable to use the main page instead of login.

**Comment by WeiserAriel** [comment]
> Is it Form based authentication or Basic?
That's a good question, AFAIU that's a Basic Authentication but I am really confused :(
After entering the credentials  into login page (url= http://10.209.27.129/example/#/login) 
![image](https://user-images.githubusercontent.com/41187619/44095345-3cb0193e-9fe1-11e8-978f-963ed0d661cf.png)


I see a REST request sent with ' Authorization Basic ' Header... 

![image](https://user-images.githubusercontent.com/41187619/44095267-0af204a2-9fe1-11e8-99ad-fa9e3ae3aa16.png)

Can you advise what is the required authentication? kind of lost here..
let me know if you need more details.

**Comment by KajanM** [comment]
If there is a `WWW-Authenticate: Basic` in the response header of the login page request (before providing password) then it’s `Basic`.

However, I haven’t come across a form presented for `Basic` scheme.

If it matters, when working with `Spring Security` framework to set up *form* based authentication, the framework automatically added a login page.

Is the application running behind a proxy?

**Comment by WeiserAriel** [comment]
Thanks For your inputs! 

> If there is a WWW-Authenticate: Basic in the response header of the login page request (before providing password) then it’s Basic.

No, I don't see 'WWW-Authenticate: Basic' in the response headers. 

According to the information I provided you can't tell for sure what type of authentication is used here? 
I'm looking for the simplest solution to overcome this issue and move on :)

**Comment by kingthorin** [comment]
Do/did you have to provide a username/password (via a dialog) before you got the login form?

**Comment by KajanM** [comment]
If you are providing username and password via the form and not by dialog, any comments on the source of the login page(particularly the action attribute of the form tag)?

**Comment by WeiserAriel** [comment]
No, I haven't...

**Comment by WeiserAriel** [comment]
> If you are providing username and password via the form and not by dialog, any comments on the source of the login page(particularly the action attribute of the form tag)?

I'm proving a username and password via the form below..

![image](https://user-images.githubusercontent.com/41187619/44099553-90da9764-9feb-11e8-9b3d-76016893741c.png)

**Comment by KajanM** [comment]
`onsubmit=“return false;”`? need to look at the script then, can you try
1. set up HTTP authentication method in ZAP
1. enable forced user mode
1. make request to authorized resource from browser(not to the login page, but maybe to the page redirected after logging in)
Is the attempt successful?

With HTTP scheme the browser will cache the Authorization header. To try with forced user mode, I would suggest to use the launch browser option in ZAP.

**Comment by KajanM** [comment]
>  ![post-data](https://user-images.githubusercontent.com/17596394/44102590-b093a192-a007-11e8-9be7-a1a163dfaee4.png)

Ooh, did you manually enter this `post` data or by right-clicking the `post` request from the `site` tree and then `flag as context`...?

**Comment by WeiserAriel** [comment]
> Ooh, did you manually enter this post data or by right-clicking the post request from the site tree and then flag as context...?

I manually entered these credentials.

> set up HTTP authentication method in ZAP
**Which**? I think I tried all of them... 

> enable forced user mode
OK. I think I did it correctly... 
![image](https://user-images.githubusercontent.com/41187619/44136679-4b6504ae-a076-11e8-895b-3a8fb7ec896f.png)

![image](https://user-images.githubusercontent.com/41187619/44135536-1cd488de-a072-11e8-9529-24e07528f569.png)
![image](https://user-images.githubusercontent.com/41187619/44135552-2a9acb72-a072-11e8-975d-b4c4df294530.png)

> make request to authorized resource from the browser(not to the login page, but maybe to the page redirected after logging in)
Is the attempt successful?

Seems like it was not working, I have been moved back to login page automatically.  
![image](https://user-images.githubusercontent.com/41187619/44136483-9d0b2050-a075-11e8-81f2-9be9252542e6.png)
![image](https://user-images.githubusercontent.com/41187619/44136518-bad03b84-a075-11e8-9743-bebaa76a9770.png)

**Comment by KajanM** [comment]
> set up HTTP authentication method in ZAP
Which? I think I tried all of them...

Setting up `ZAP` for `HTTP Basic` scheme is documented [here](https://docs.google.com/document/d/1ZwJoIORtS10gvgJBJ4zuEKoQEMJ8mcMT1TlXlbmTCn8/edit) which is different from form-based one.

Regardless of the login page, I hope it's `HTTP Basic` scheme since the browser has added `Authorization: Basic ....` header.

It should be noted that there are a lot of authentication schemes [1]. However, with careful inspection, one can find the authentication scheme being used. If not `HTTP Basic` please go through the resources you have to find out the appropriate one. Setting up break on all requests and responses and going through each body, header and inspecting the `HTML` source of the login page will definitely help.

If the scheme being used is something that `ZAP` does not support, please make a feature request.

[1] most of the web app authentication schemes are documented [here](https://docs.google.com/document/d/1LSg8CMb4LI5yP-8jYDTVJw1ZIJD2W_WDWXLtJNk3rsQ/edit).

**Comment by KajanM** [comment]
> could it be that the client sends ' Authorization Basic' Header without getting 'WWW-Authenticate' Header before from the server ?

It's possible, making the request using `JavaScript`[1] and redirecting based on the response[2] can do it.

> does it make sense?

I couldn't understand why such a custom protocol is needed.

BTW, does the `Authorization: Basic` header sent with all requests or just with the login request?




[1] https://medium.freecodecamp.org/here-is-the-most-popular-ways-to-make-an-http-request-in-javascript-954ce8c95aaa
[2] https://stackoverflow.com/questions/199099/how-to-manage-a-redirect-request-after-a-jquery-ajax-call

**Comment by WeiserAriel** [comment]
> BTW, does the Authorization: Basic header sent with all requests or just with the login request?

Yes! all requests include the authorization header after login completes.

I will go over the links you sent here and try to solve it.

Thanks,
Ariel.

**Comment by kingthorin** [comment]
@WeiserAriel Did you ever sort this out?
