### ISSUE TITLE
Add a hook system into the baseline scripts (`docker/*.py`)

### ISSUE THREAD

**Issue by rezen** [zaproxy/zaproxy#4925]
The `zap-baseline` & `zap-full-scan` are awesome, but I frequently finding having to modify little configurations for edge cases. 
To make it easy to make little tweaks here and there I propose adding in a hook system where you can override or modify behaviour of the script components instead of having to write a new script.

**Use Cases**  
*Modfiying Args*  
For example, for the AJAX crawler specifically I wanted to target
a suburl but there is no easy way to do it, I had to essentially 
copy the script and modify that part.

*Running Scripts*  
I have a couple standalone scripts that I want to run before 
crawling & the other parts of the scan.

*Changing Configs*  
For some applications, there are a number active scan scanners that I 
disable that are not applicable for that application. Having a hook 
before the active scan would allow you to customize the policy before
running it.

**Solution**
- Modify existing scanner and shared libraries to include hooks
where it would be useful to modify behavour.
- On load, check for custom hook module `~/.zap_hooks.py`
  - Make the location overrideable with `ZAP_HOOKS` environment variable
- If file exists try loading module and error if you cant
- When a hook is triggered, check if there is a matching method in the module.

**Example**  
Declaring hooks in the existing codebase  
```python
# https://github.com/zaproxy/zaproxy/blob/develop/docker/zap-full-scan.py#L302
# After zap has started provide a hook with the zap object & target
trigger_hook('zap_started', zap=zap, target=target)

# Example of declaration of hook in zap_common.py
@hook("zap_ajax_spider", post=True)
def zap_ajax_spider(zap, target, max_time):
  """ ..... """
```

Customizations via `~/.zap_hooks.py`  
```python
# Example of setting some configs after zap has started
def zap_started(zap=None, target=None):
  zap.ascan.disable_scanners('90029')
  zap.ascan.disable_scanners('10053')


# Example of tweaking the target url for the spider
def zap_ajax_spider(target, max_time, zap=None):
  return target + '#/dashboard', max_time

```

**Comment by psiinon** [comment]
I really like this idea :)
How about specifying the hooks file via a command line option?
In CI there may be many baseline jobs running so ~/.zap_hooks.py could be incorrectly shared between multiple jobs.
@rezen is this something you might be able to work on?

**Comment by rezen** [comment]
@psiinon good suggestion on cli option, I'm thinking `-py` for the flag? or more explicit, `-hook`? (All the others letters are taken) 

Already started :smile:

**Comment by rezen** [comment]
Are there any generic tests the `zap-*.py` scans typically run against?

**Comment by rezen** [comment]
@thc202 would you like me to add some with my PR?

**Comment by psiinon** [comment]
Tests are always much appreciated :)
FYI we run the baseline scan from the ZAP Live docker image against a range of Mozilla sites every day, so if something breaks I get to know about it pretty quickly ;)

**Comment by rezen** [comment]
@psiinon gotcha! So no pressure :sweat_smile:

**Comment by thc202** [comment]
Closing, done in #4925.

**Comment by abdoudhassi** [comment]
@rezen, thank you for this awesome feature. I have one small question though: 
If I want to import an authentication script prior to loading my context, I just need to add that in the function `zap_import_context` inside my `zap_hooks.py` file, and that's it. Or do I need to call the `trigger_hook` function in the `zap-full-scan.py` script first?

**Comment by abdoudhassi** [comment]
Never mind, I figured it out from here: 
https://github.com/zaproxy/zaproxy/blob/develop/docker/docs/scan-hooks.md
