### ISSUE TITLE
Server header scanner is case sensitive.

### ISSUE THREAD

**Issue by omerlh** [zaproxy/zaproxy#4926]
**Describe the bug**
The server header scanner will report only on `Server` header, not `server`. Kestrel, for example, produces lower-case headers.
I've looked on the code, it looks (see this [line](https://github.com/zaproxy/zap-extensions/blob/eabba98495007eba95a76de6409f45f4d354cdf2/src/org/zaproxy/zap/extension/pscanrulesAlpha/ServerHeaderInfoLeakScanner.java#L64)) that it does look only for `Server`.
**To Reproduce**
1. Scan a site that produces `server` header
2. Make sure alpha rules are enabled 

**Expected behavior**
An alert on `server` header.

**Comment by omerlh** [comment]
Sorry, my failure - the docker version was not loading the alpha rules for some reasons. I'll check that. Thanks and sorry for oversight :) I'll double-check next time...

**Comment by kingthorin** [comment]
I just checked this via: `ServerHeaderInfoLeakScannerUnitTest`, manually changing one of the tests to set "server" (all lower) and it works fine.

**Comment by psiinon** [comment]
No worries, thanks for letting us know :)
