### ISSUE TITLE
Core API - "messages" returns wrong response body with \ufffd

### ISSUE THREAD

**Issue by kfirilani** [zaproxy/zaproxy#4942]
It seems that if response body has characters that cannot be encode as unicode, it replace it with \ufffd

Is there an option to get response body as bytes without loosing data?

Thanks

**Comment by psiinon** [comment]
Please dont ask questions as issues.
The thread you've started on https://groups.google.com/d/msg/zaproxy-users/1VJdy_IkCZ8/X8XI5UWeEQAJ is the right place for it.
We will get around to answering that thread, but we all have a lot to do :/
