### ISSUE TITLE
Make host in ClientApi of zap-api-java customisable

### ISSUE THREAD

**Issue by jo2** [zaproxy/zaproxy#4944]
I'm using zap in a docker environment and in ClientApi.java in line 420 (https://github.com/zaproxy/zap-api-java/blob/develop/subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/core/ClientApi.java) the url for the zap request starts hardcoded with "http://zap/". In my docker environment I'd like to use my docker container ip for that. 

This could be done by passing the host as another mybe optional parameter in the call method.

**Comment by kingthorin** [comment]
The `zap` host is only applicable if you're accessing the API while actively proxying through ZAP.

**Comment by jo2** [comment]
I'm instatiating the ClientApi with localhost:8090 which is also accessible from the browser. However access on "http://localhost:8090/xml/spider/action/scan/?url=http%3A%2F%2Flocalhost%3A8083%2Fv2%2Fapi-docs&" returns a connection refused. The url "http://localhost:8083/v2/api-docs/" returns my OpenAPI documents generated by swagger.

Also zap is listening on 0.0.0.0:8090.

**Comment by jo2** [comment]
I'm using docker-compose and I added "-config api.disablekey=true -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true" to the command.

**Comment by thc202** [comment]
Where's the `ClientApi`? In the same container as ZAP?

**Comment by jo2** [comment]
The i call ClientApi.callApi(..) from a container running on localhost:8761. The ZAP container runs on localhost:8090.

**Comment by thc202** [comment]
If the `ClientApi` is running in another container you need to use a different address than `localhost` when instantiating the `ClientApi` (more specifically the address from the container ZAP is running).

**Comment by jo2** [comment]
Even if the container port is mapped on 8090 on localhost?

**Comment by kingthorin** [comment]
> I'm instatiating the ClientApi with localhost:8090 which is also accessible from the browser. However access on "http://zap/xml/spider/action/scan/?url=http%3A%2F%2Flocalhost%3A8083%2Fv2%2Fapi-docs&" returns a connection refused while "http://localhost:8090/xml/spider/action/scan/?url=http%3A%2F%2Flocalhost%3A8083%2Fv2%2Fapi-docs&" is accessible from the browser.

That's expected. The `zap` hostname is only applicable when you're actively proxying through ZAP. ZAP can only fake the DNS for the `zap` hostname if it's processing the traffic.

**Comment by jo2** [comment]
> Yes, localhost from inside the container is referring to the container itself not the host (so it would fail to reach ZAP).

In that case using the `host ip` on linux or the `host.docker.internal` on docker for windows as the host for ClientApi should do the job. Thanks!

For me using docker for windows it works.

**Comment by kingthorin** [comment]
@jo2 thanks for letting us know.
