### ISSUE TITLE
root vs normal user - CA certificate & firefox error

### ISSUE THREAD

**Issue by CreativeWolf** [zaproxy/zaproxy#4954]
Heya,

The issue started with "Failed to start 'Firefox' is the browser installed/available?" while trying to run AJAX Spider.

Upon reading up past issues posted checked log and found this:

> Running Firefox as root in a regular user's session is not supported.  ($XAUTHORITY is /home/bilbo/.Xauthority which is owned by bilbo.)
> 56265 [ZAP-AjaxSpider] WARN org.zaproxy.zap.extension.spiderAjax.SpiderThread  - Failed to start browser firefox
> 
Yes, I was running ZAP using sudo.

To fix this, I ran ZAP as normal user and then I started getting certificate errors while trying to access any of the sites despite having a certificate installed.

Unless I run ZAP using sudo the certificate error issue won't go away but if I run ZAP using sudo, AJAX Spider wont work as Firefox won't start as root user in a regular user's session.

ZAP: 2.7.0
Firefox: Quantum 62

Appreciate any help on this.

Thanks!

**Comment by thc202** [comment]
Is the same Root CA certificate being used when running ZAP as normal user? They might be using different homes (which would default to different certs).

**Comment by CreativeWolf** [comment]
Update: Deleted cert9.db from the Firefox profile and followed steps 1 - 6 in the previous comment and that seems to have fixed it.

But this was weird :tired_face: 

>  I've also noticed that after removing the ZAP certificate and restarting Firefox, even without adding, ZAP certificate is listed - Which is weird and I have no clue as to why that'd happen.
> 
Cheers

**Comment by kingthorin** [comment]
Thanks for letting us know.
