### ISSUE TITLE
Need to add the ability to use a proxy.pac file as an upstream proxy

### ISSUE THREAD

**Issue by donraikes** [zaproxy/zaproxy#4956]
When configuring zap especially when using the python api, it could be helpful to allow a proxy.pac file as the proxy_chain upstream proxy.

For example, in a corporate setting where all browser traffic uses by default a proxy.pac file retrieved from a url, it is difficult to know exactly which proxy server is being used for a given website especially if files like javascript or css files are being retrieved from servers behind a different proxy host.

This problem is resolved by the use of the proxy.pac.  At present there is no way for zap to read/use the proxy.pac file as its upstream proxy which can lead to 404's 403's and other undesireable return codes.

**Comment by kingthorin** [comment]
https://github.com/zaproxy/zaproxy/issues/265 ?

**Comment by kingthorin** [comment]
Closing as duplicate.
