### ISSUE TITLE
ZAP Proxy clearstates 

### ISSUE THREAD

**Issue by asmishra1** [zaproxy/zaproxy#4959]
when i am trying to perform the action with clear stats , then its return result as "ok" but the data or dashboard information are not refreshed.

**Comment by psiinon** [comment]
@asmishra1 can you provide some more information about what you are doing and what you expect to see? Are you clearing the stats via the API? If so which data / dashboard are you referring to?

**Comment by kingthorin** [comment]
No further input from the original submitter in over 5mo, closing.
