### ISSUE TITLE
Include proper Accept header when requesting OpenAPI definitions

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#4961]
From https://mozilla.logbot.info/websectools/20180816
(Raising issue so that this is not forgotten, in case the pull request is not open in the end.)

The OpenAPI add-on does not add the Accept header which might lead to the target to serve other content than the API definition.

Add-on:
OpenAPI Support

**Comment by suryputra** [comment]
I would like to work on it. Could someone point me in the right direction, this being my first attempt at contribution in open source.

**Comment by kingthorin** [comment]
Dev info:
https://github.com/zaproxy/zaproxy/wiki/Contributing-Changes
https://github.com/zaproxy/zaproxy/wiki/Building

The OpenAPI extension is in the alpha branch of the extensions repo, under `/src/org/zaproxy/zap/extension/openapi/`. 

Builds are done via ant, use one of these build targets to build the extension, you can then load it in ZAP and test it:
https://github.com/zaproxy/zap-extensions/blob/e417097973e55f2f90aade1679fe4c41fd91f4a4/build/build.xml#L749-L755

If you need further assistance you can ask in the Dev Group or via IRC, details for both are listed on the main page of the main project: https://github.com/zaproxy/zaproxy

**Comment by tushar-97** [comment]
Hey! @suryputra @kingthorin 
Would it be alright if I jumped in to help out with this issue? (if no one else solved it in a different patch)

**Comment by kingthorin** [comment]
@tushar-97 sounds good to me.

**Comment by tushar-97** [comment]
I was unable to reproduce the problem but will this fix the issue?
![capture1](https://user-images.githubusercontent.com/19520011/48508397-774a2b80-e874-11e8-9278-183da56b06ba.jpg)

**Comment by tushar-97** [comment]
I used the OPs endpoint to test my changes (endpoint -> https://demo.openspeedmonitor.org/rest/man)
Failure:
![error](https://user-images.githubusercontent.com/19520011/48508949-e5432280-e875-11e8-8a91-47aa874458b9.JPG)

Successful import with Accept header:
![succ](https://user-images.githubusercontent.com/19520011/48508964-ed02c700-e875-11e8-90d5-555036b65109.JPG)

Have I reproduced the error correctly and does the fix look correct as well?

**Comment by kingthorin** [comment]
There shouldn't be any spaces in the accept header. `application/json,*/*` Though I'd expect servers to be somewhat forgiving. 

In your second screenshot what's the status code on the 'Response' tab? (I'm guessing it's a redirect of some sort ... 302?)

I can verify that via Firefox devtools if you Edit and Resend the request to https://demo.openspeedmonitor.org/rest/man with the Accept headers as `application/json,*/*` it does return JSON while with the normal browser header it does redirect (to Swagger UI).

**Comment by thc202** [comment]
The spaces are allowed (not that it matters in the end).

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#1890.
