### ISSUE TITLE
Add support for Jenkins Pipelines

### ISSUE THREAD

**Issue by museadmin** [zaproxy/zaproxy#4967]
**Is your feature request related to a problem? Please describe.**
While the Jenkins plugin works well with Jenkins Freestyle jobs, it lacks support for the more recent pipeline syntax. This means that anyone using the newer style of pipeline cannot create a ZAP Jenkins stage to run the plugin.

**Describe the solution you'd like**
Support added for the new style pipelines, see - 
https://jenkins.io/doc/developer/plugin-development/pipeline-integration/

**Describe alternatives you've considered**
I am happy to attempt forking ZAP and adding support myself by following the developer guide above, but would like confirmation that I'm not duplicating effort as someone else already has it in hand... 

Also, would someone, (@JordanGS ?), be able to answer any questions I might have when forking the project and getting it running in IntelliJ prior to doing the refactoring? 

Failing that, do you guys have the bandwidth to add this enhancement yourselves?

**Comment by thc202** [comment]
Worth nothing that the Jenkins plugin issues are managed in the Jenkins issue tracker:
https://issues.jenkins-ci.org/issues/?jql=project%20%3D%20JENKINS%20AND%20component%20%3D%20zap-plugin
the Jenkins related issues that we track here are for changes in ZAP side (core, add-ons...) not in the plugin itself (at least that's how we have handled them so far).

**Comment by museadmin** [comment]
Thanks guys :)

**Comment by museadmin** [comment]
A quick sanity check @psiinon 

I've forked the project. 
I need to create a branch from the "development" branch?
Looks like the last commits were to that

**Comment by kingthorin** [comment]
Yup create a local feature branch, make your changes, test them, commit it and push it back to origin (your fork) then open a pull request.

**Comment by vrondakis** [comment]
Sorry for advertising but I made a separate plugin [here](https://github.com/vrondakis/zap-jenkins-pipeline-plugin) that supports Jenkins pipeline builds, which may help you

**Comment by museadmin** [comment]
> Sorry for advertising but I made a separate plugin [here](https://github.com/vrondakis/zap-jenkins-pipeline-plugin) that supports Jenkins pipeline builds, which may help you

@vrondakis 

That looks like some nice clean code you've written there. I wish I had known about this, it would have saved me some effort.

Are you intending to release this as a plugin that's capable of supporting the Pipeline Syntax and the legacy Freestyle syntax? If so, there's no point in my carrying on with refactoring the existing plugin. 

Please let me know. :)

Brad

**Comment by vrondakis** [comment]
Thanks @museadmin, I wouldn't be against support for freestyle jobs in the plugin, it would be easy to add but it's not a priority right now because the other plugin does it pretty well already. There's no reason you can't have both plugins installed at once if you have both pipeline and freestlye projects though :+1:

**Comment by museadmin** [comment]
Hi @vrondakis Yes I think it would just pollute the code to make it support both types of job.

Can you tell me where you are with this new version? 

I have a requirement to upgrade our Jenkins server and add a pipeline job that runs ZAP. Will this become the official supported version and is it ready to go now?

If not, do you require any help, perhaps with testing or documentation?

**Comment by vrondakis** [comment]
@museadmin 

It is ready to go and works. I'm working on putting it onto plugins.jenkins.io but I'd like to give it more thorough testing before that. If you use it and have any problems / suggestions then please let me know. The documentation in the readme is pretty bad right now & someone said it doesn't work on Windows, so feel free to contribute if you want to help :)

**Comment by museadmin** [comment]
@vrondakis Cheers. I would like to try it out. 

Unfortunately our production Jenkins instance doesn't support ZAP and needs to be upgraded. I have a ticket in place for it, will chase the platform team and then try it out.

Failing that, I'll try running it from my Mac in a Jenkins docker image.

**Comment by thc202** [comment]
Closing per plugin provided by @vrondakis https://github.com/jenkinsci/zap-pipeline-plugin
