### ISSUE TITLE
Jenkins: Build should fail when a vulnerability is introduced to help continuous integration

### ISSUE THREAD

**Issue by arslanjavaid1** [zaproxy/zaproxy#4975]
This feature is very important when it comes to continuous integration. When a person introduces a vulnerability in the application, there should be an option to fail the build and email that person that the person has introduced the vulnerability. It will help in making applications more secure and achieve continuous integration.

Jenkins option to fail the job if there any new vulnerability is introduced

**Comment by thc202** [comment]
That's being tracked in https://issues.jenkins-ci.org/browse/JENKINS-39988
