### ISSUE TITLE
Dockerfile hangs in Concourse-CI since Xvfb never terminates

### ISSUE THREAD

**Issue by northdpole** [zaproxy/zaproxy#4979]
Hey everyone, when running any python script in the dockerized version of ZAP in Concourse CI the container will never terminate.
Here's why: Concourse by design, expects all processes in a container to exit cleanly otherwise it assumes there's some long running task and it keeps waiting for task output.

This task is Xvfb which even after ZAP and the python scripts have finished keeps running.

**To Reproduce**
1. With this [file](https://github.com/concourse/concourse-docker/blob/master/docker-compose.yml) in your current dir run docker-compose up -d to setup a local concourse environment. (default credentials being test:test)
2. Download and install fly either from 127.0.0.1:8080 with concourse running or from your package manager of choice
3. You can use the pipeline file below to setup a basic pipeline 
3. run the following commands to associate fly with your local concourse: 
`fly -t test login --concourse-url http://127.0.0.1:8080
fly -t test sync
fly -t test execute -c pipeline.yml
`
4. Observe that it never finishes. 

**Expected behavior**
All processes exit cleanly.

**Software versions**
 - ZAP: latest zap-weekly
 - OS:  Latest Ubuntu

**Errors from the zap.log file**
N/A

**Additional context**
There's a quick solution to separately kill Xvfb at the end of execution.
Also, since this issue is very specific to one use case, I'm not sure how interested you are in fixing this.
If you're not but there's an easy way to execute zap without zap-x.sh or Xvfb please let me know.
//Update: It's the zap-x.sh file, it exits if the file is commented out except the last line.
// I guess you need this file to launch graphical zap from docker, what if a --no-graphics or similar switch is added to the script to make it bypassable?

`--- pipeline.yml ---
platform: linux
image_resource:
        type: docker-image
        source: { repository: owasp/zap2docker-weekly }
run:
        path: zap-baseline.py
        args: [-t, '<Some Target you want>', -d]`

**Comment by psiinon** [comment]
Yes, you can just use 'zap-sh' to run ZAP.
zap-x.sh is only needed if you want to run the Ajax Spider - see https://github.com/zaproxy/zaproxy/wiki/Docker for more details.
We're always keen to fix things, even for specific use cases, as long as the fixes dont break ZAP in other situations :)

**Comment by psiinon** [comment]
Ah, just noticed that you are using the basline scan script which always uses zap-x.sh in case the Ajax Spider option is selected.
I _think_ we can fix this by changing the zap-x.sh script to do something like:
```
Xvfb :1 -screen 0 1024x768x16 -ac &
XVFB_PID=$!
/zap/zap.sh "$@"
kill $XVFB_PID
```
tweaked to cope with the 'if' statement.
I'll try and have a play once I've generated the weekly release...

**Comment by AdeOpe** [comment]
@northdpole 
Thank you for raising this!!

**Comment by kingthorin** [comment]
@AdeOpe the issue has been addressed and the ticket you commented on closed. If you have something further on the topic it should probably be discussed in the [User Group](https://groups.google.com/forum/#!forum/zaproxy-users) first.

**Comment by Ianwww** [comment]
@northdpole What is the new command that you ran?
