### ISSUE TITLE
passive scan alerts stop appearing in UI but are recorded in log file

### ISSUE THREAD

**Issue by sirfd** [zaproxy/zaproxy#4980]
when the zap passivescanner reaches a count of 59,999 it rolls over to 0 (restarts) and all alerts found afterwards stop appearing in the zap UI.
2018-09-15 11:17:32,199 [ZAP-PassiveScanner]
2018-09-15 11:19:56,849 [ZAP-PassiveScanner]
2018-09-15 11:19:56,860 [ZAP-PassiveScanner] 
2018-09-15 11:19:58,161 [ZAP-PassiveScanner]
2018-09-15 11:19:58,162 [ZAP-PassiveScanner] 
2018-09-15 11:19:59,411 [ZAP-PassiveScanner] 
**2018-09-15 11:19:59,412 [ZAP-PassiveScanner] 
2018-09-15 11:20:00,657 [ZAP-PassiveScanner]** 
2018-09-15 11:20:10,605 [ZAP-PassiveScanner]
**To Reproduce**
enable all passive scan rules both community and plugs low threshold
run ajax spider over OWASP Juice shop
verify history tab loads over 9,570 entries while spidering and executing manual recon of OWASP juiceshop
watch the passive scan rules run and passive alerts being created
after awhile noticed the alerts stopped being generated on either spider history or new manual recon

turned on owasp zap debug mode 
opened logs
verified no exceptions were occuring with passivescan rules and alerts were being found but not shown in UI.
debug entry for alerts being found but not shown in ZAP UI:
2018-09-15 11:49:33,605 [ZAP-PassiveScanner] DEBUG SimpleEventBus - publishSyncEvent alert.added from org.zaproxy.zap.extension.alert.AlertEventPublisher
2018-09-15 11:49:33,607 [ZAP-PassiveScanner] DEBUG ExtensionAlert - alertFound Web Browser XSS Protection Not Enabled http://192.168.33.10/i18n/en.json

noticed that the date/time stamp has numerical included, checked logs and found that the numeric rolls over (restarts)   when this occurs the it appears that the alert UI stopped showing new alerts being discovered.  may be coincidence but not sure.

**2018-09-15 11:19:59,412 [ZAP-PassiveScanner] 
2018-09-15 11:20:00,657 [ZAP-PassiveScanner]** 

**Expected behavior**
all alerts found and reported in log file are viewable in the owasp UI for reporting and investigation

**Screenshots**

![owasp_zap_alerts_stopped_appearing](https://user-images.githubusercontent.com/26119008/45589640-15a22b00-b8de-11e8-9123-e75d32db900d.PNG)
[OWASP_ZAP_enabled_passive_SCAN_RULES.txt](https://github.com/zaproxy/zaproxy/files/2386003/OWASP_ZAP_enabled_passive_SCAN_RULES.txt)
![zap_community_passive_scan_scripts_enabled](https://user-images.githubusercontent.com/26119008/45589641-15a22b00-b8de-11e8-8ec3-a41c77d5ae5c.PNG)

**Software versions**
 - ZAP: 2.7.0
 - Add-on: see attached lists
 - OS: Windows 10
 - Java: java -version
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
 - Browser: 60.02 ESR

**Errors from the zap.log file**
no errors found in log file

**Additional context**
not sure if the alert reporting stops  because of ajax spider data being added to the history tab which may be different from the manual history entries or if the jump in id in history tab is related or if the timestamp numeric rollover is related

**Comment by kingthorin** [comment]
> 2018-09-15 11:19:59,412 [ZAP-PassiveScanner]
> 2018-09-15 11:20:00,657 [ZAP-PassiveScanner]

That's from the Output tab isn't it? Your (Tools > Options > Display) time format is set to `yyyy-MM-dd HH:mm:ss,SSS`?) ... 19:59 to 20:00 makes perfect sense.

I spun up a private heroku instance of JuiceShop and had both spiders going for a while, my pscan queue got to at least 40k entries. When things finished core/view/alert/ was showing results up to alert ID 77568 and core/view/alertsSummary was returning the following: `{"alertsSummary":{"High":5,"Low":7711,"Medium":2946,"Informational":1952}}` (the counts don't match because of duplicates etc.)

**Comment by kingthorin** [comment]
No further input in 5months, closing.
