### ISSUE TITLE
SSE are not supported in some cases

### ISSUE THREAD

**Issue by IrmantasVaracinskas** [zaproxy/zaproxy#5003]
When request is made to LaunchDarkly it returns response with "content-type: text/event-stream; charset=utf-8" but ZAP expects "content-type: text/event-stream", so ZAP thinks it just a normal (not SSE) request.

Steps to reproduce: 
1. Build sample project, for example https://github.com/launchdarkly/hello-dotnet (not mine, just used it to reproduce problem)
2. Setup trial version of https://launchdarkly.com/ and configure feature flag
3. Open ZAP
4. Configure system proxy
5. Requests are not shown in ZAP (or shown after some time as timeout) and executable shows thread timeout errors

**Comment by adamvan101** [comment]
I know this is closed, but was this fix actually merged into Master? It does not look like it:

[line 162 from master](https://github.com/zaproxy/zaproxy/blob/master/src/org/zaproxy/zap/ZapGetMethod.java)
if (contentTypeHeader != null && contentTypeHeader.equals("text/event-stream")) {

**Comment by thc202** [comment]
The master branch contains the (main) releases, it will be merged for 2.8.0.

**Comment by adamvan101** [comment]
I see, so the weekly release should have this fix. It has not resolved our issue... Is [HttpMessage.java](https://github.com/zaproxy/zaproxy/blob/develop/src/org/parosproxy/paros/network/HttpMessage.java) also a culprit? 

			isEventStream = getResponseHeader().hasContentType("text/event-stream");

**Comment by thc202** [comment]
Please provide details about the issue you are having.

**Comment by adamvan101** [comment]
The scenario is the same as the OP - requests now show up in ZAP when expected, but the response body never makes it back to the calling executable. I notice that a "Transfer-Encoding: chunked" header is removed. Perhaps this directive isn't properly handled?

**Comment by thc202** [comment]
Is the Server-Sent Events add-on installed?

**Comment by adamvan101** [comment]
...no

Sorry for the fuss, that's fixed it!

**Comment by thc202** [comment]
No problem, thanks for letting us know.
