### ISSUE TITLE
Bad request.  Accept and/or Content-Type headers likely do not match supported values

### ISSUE THREAD

**Issue by kantonak** [zaproxy/zaproxy#5004]
**Accept parameter is ignored in HTTP request**
I am using a POST request towards the Okta server in order to get authenticated. In the request I am specifying both Accept and Content-type as "application/x-www-form-urlencoded".

When I click on Send button in Manuel Request Editor I get a HTTP 400 Bad Request error message with the following body : "{"errorCode":"E0000021","errorSummary":"Bad request.  Accept and/or Content-Type headers likely do not match supported values.","errorLink":"E0000021","errorId":"oaeqltoiQXWQQaOHsn97DkIcA","errorCauses":[]}"

When I convert my request header to text (Header: Text) I observe that Accept parameter has different encoding = "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" and not the one specified in the request. 

Not sure if this actually the problem here but it seems that Accept has different encoding.

**To Reproduce**
1. Go to Manual Request editor
2. Create a POST http command for Okta authentication containing necessary ClientID + ClientSecret in the request (see screenshots)
3. click "Send"
4. See Error in Response Body (see screenshot)

**Expected behavior**
I would expect that Accept parameter included in the POST request would define the encoding to be used in the request. 

**Screenshots**

![screenshot_post_request1](https://user-images.githubusercontent.com/7780174/46010499-2f542700-c0c3-11e8-8da8-bba21d944397.JPG)
![screenshot_post_request_in_text](https://user-images.githubusercontent.com/7780174/46010959-aa6a0d00-c0c4-11e8-9c7b-ccf21744cb62.JPG)
![screenshot_post_response](https://user-images.githubusercontent.com/7780174/46011093-19476600-c0c5-11e8-9d70-382bd74da527.JPG)

**Software versions**
 - ZAP: 2.7.0
 - Add-on: Manual Request Editor
 - OS: Windows 10
 - Java: version "1.8.0_181"
 - Browser: -

**Comment by thc202** [comment]
The bottom view/panel is to set the contents of the body, you need to add those headers in the top view/panel.

**Comment by kantonak** [comment]
> The bottom view/panel is to set the contents of the body, you need to add those headers in the top view/panel.

I just tried it but I get the same error in the response.

**Comment by kantonak** [comment]
OK, I found out what the problem was. I was sending the Authorization and Content-type headers as part of the POST command. They should had been sent as headers instead. It works sweet now.

**Comment by kingthorin** [comment]
@kantonak thanks for letting us know.
