### ISSUE TITLE
"assign variable to string" functionality to parse json response body?

### ISSUE THREAD

**Issue by kantonak** [zaproxy/zaproxy#5008]
Hi, I have a json response from which I need to take the authentication token from. I have used "Add Zest Assignment->Assign variable to string":
![image](https://user-images.githubusercontent.com/7780174/46151369-e5a83f80-c26e-11e8-8936-b9515e7ff58b.png)
and tried to print variable's contents (Add Zest Action->Action-Print): 
![image](https://user-images.githubusercontent.com/7780174/46151438-112b2a00-c26f-11e8-8aa7-9c51ac7fd58f.png)

As a result, I am getting the variable's name istead of its contents. 

To be more precise, let us assume the token is assigned to a variable "loginToken" with string {{id_token}} (the actual variable name that sits inside the json response body). When I am trying to use the variable during, for example, OAuth authentication then I get "Invalid token" error. 

In OAuth authentication I am using 

> Authorization: Bearer {{loginToken}} 

inside the header request. From the result I see that it tries to authenticate using {{loginToken}} as "token" which results to the error message:

> WWW-Authenticate: Bearer error="invalid_token"

**Comment by thc202** [comment]
If you want to extract some content from the JSON body you would have to use `Assign variable via regex delimiters` or `Assign variable via string delimiters`, the `Assign variable to string` just sets a string to a variable.

**Comment by kantonak** [comment]
I see that 
https://github.com/zaproxy/zaproxy/issues/3511 
https://github.com/zaproxy/zaproxy/issues/3512 
address my issue. 

What is the best way to implement this?

**Comment by thc202** [comment]
> Is this variable supposed to be global and be "visible" anywhere in ZAP?

No, Zest variables are only available in the corresponding Zest script. With #3512 it would be possible to easily share them with other scripts/languages, in the meantime you need to invoke another script to share them (like shown in #3511). For use of global script variables: https://github.com/zaproxy/zap-core-help/wiki/HelpAddonsScriptsScripts#global-variables

> What is the best way to implement this?

If you want to inject the token in the requests sent by ZAP you need to share the variable and then use a HTTP Sender script.

**Comment by thc202** [comment]
There's an example in https://groups.google.com/d/msg/zaproxy-users/HJZ8gxk17M8/9jgtSv2CAgAJ

**Comment by thc202** [comment]
Closing, the questions seem to be answered. Any other questions please let us know through the User Group: https://groups.google.com/group/zaproxy-users
