### ISSUE TITLE
Snap package does not work

### ISSUE THREAD

**Issue by Holston5** [zaproxy/zaproxy#5009]
The snapdoesn't work, no previous versions of ZAP are installed.  OpendJDK8 IS installed (though not as a snap package) and is known to work fine.  Awk is also installed, though not as a snap package.
 
zaproxy
/snap/zaproxy/2/zap.sh: line 46: awk: command not found
/snap/zaproxy/2/zap.sh: line 48: awk: command not found
/snap/zaproxy/2/zap.sh: line 51: [: -ge: unary operator expected
/snap/zaproxy/2/zap.sh: line 54: [: -ge: unary operator expected
Exiting: ZAP requires a minimum of Java 8 to run, found

1. snap install  --beta --devmode zaproxy
2. zaproxy

whereis java: /usr/bin/java /usr/share/java
whereis awk: /usr/bin/awk /usr/share/awk
OS: Solus 3.9999

**Comment by kingthorin** [comment]
Per: https://github.com/zaproxy/zaproxy/tree/develop/snap
`snap install zaproxy_2.7.0_amd64.snap --dangerous --classic`

**Comment by thc202** [comment]
Note that the classic is not yet published, we might need to change that.

@Holston5 would you mind posting those details in #4955 instead?

**Comment by kingthorin** [comment]
Closing and tracking as part of 4955.

**Comment by psiinon** [comment]
For reference the instructions most people should use are on https://github.com/zaproxy/zaproxy/wiki/Downloads#snapcraft
The ones in https://github.com/zaproxy/zaproxy/tree/develop/snap are just for creating and deploying snaps locally.

**Comment by kingthorin** [comment]
Thanks for clarifying.
