### ISSUE TITLE
Response in Browser in same window

### ISSUE THREAD

**Issue by jauharvp** [zaproxy/zaproxy#5025]
I'm always frustrated with the response checks in browser, each time when you check response in the browser it will be opening new window, instead of that, if we could change to tab, much appreciated!!

When we use fuzzer or Repeater in ZAP, we may need to check the response in browser for better understanding and whenever I try to open response in Firefox, it is/will open in new window, for few web application, have to login always!! 

The response check in Mozilla browser should be opening in same window

Machine OS: Kali Linux

**Comment by jauharvp** [comment]
> That's a browser setting "Open links in..."

Thank you for response and i have already tried the same.

When we open the response in the browser, it won't show you installed plugins and all.

**Comment by kingthorin** [comment]
> When we open the response in the browser, it won't show you installed plugins and all.

What?

**Comment by jauharvp** [comment]
![image](https://user-images.githubusercontent.com/13345445/46356118-b2efb400-c67f-11e8-8e16-b5065e2003b5.png)

First one is normal browser from kali.

![image](https://user-images.githubusercontent.com/13345445/46356226-eaf6f700-c67f-11e8-8b0a-e6e62b9c0d11.png)

Response URL opened using ZAP

**Comment by psiinon** [comment]
"Open URL in Browser..." uses selenium to open the browser, and that means it uses a new clean profile.
However you can use 'Open URL in System Browser' will open the link in your default browser, and if thats set to open new URLs in tabs then it should work as you want.

**Comment by kingthorin** [comment]
@jauharvp things more clear now? Can this be closed?

**Comment by jauharvp** [comment]
> @jauharvp things more clear now? Can this be closed?

Will check and keep posted

**Comment by jauharvp** [comment]
@psiinon Thank you, Google Chrome was the default browser and changed to Firefox worked it.

@kingthorin You can close this now!!

Thank you!
