### ISSUE TITLE
Allow custom scripts to run with the ZAP API scanner

### ISSUE THREAD

**Issue by tillig** [zaproxy/zaproxy#5031]
I have had some luck getting the ZAP API scan to run from inside Docker as part of a CI/CD pipeline. We have encountered a situation now where we need to add a custom header to the requests the scanner makes. There are plenty of community scripts and examples for how to do this but they all seem to require running interactively with the UI and enabling the script. I have not found an example of how to do this just with the `zap-api-scan.py` script and configuration values.

I would like to be able to instruct the `zap-api-scan.py` script to use some custom specified scripts as part of its scan. I imagine it could be done in the following manner:

- Mount the custom script directory as a volume on the ZAP container (`owasp/zap2docker-weekly`).
- Set a config value like `-z "-config dirs=/custom/scripts` to point to the mounted volume.
- Enable the scripts in one of three ways (I don't have a preference):
  - Another config value of some nature (`-z "-config script.enable=myscript.js"`)
  - A different flag (`-enable myscript.js`)
  - Some sort of [hook integration](https://github.com/zaproxy/zaproxy/issues/4925) to enable the scripts.

That last one, the hook integration, may actually already be possible but I just don't know how to do it.

I did try to find something "out of the box" that would work but I'm not really sure what I'm looking for. This may already exist but just isn't documented in a location I found.

**Comment by psiinon** [comment]
Have you looked at https://zaproxy.blogspot.com/2017/06/scanning-apis-with-zap.html ?
That explains how you can add authentication headers.
I've added a couple of blog post links on https://github.com/zaproxy/zaproxy/wiki/ZAP-API-Scan

**Comment by tillig** [comment]
I saw that article, but I got thrown off by two things:

- The section is about authentication, so I didn't notice the part where it mentioned you can add arbitrary headers.
- The add-in is called "Replacer," [the docs](https://github.com/zaproxy/zap-extensions/wiki/HelpAddonsReplacerReplacer) talk about how it's a search-and-replace sort of manipulator, but it I didn't pick up on the special treatment for headers. To be honest, I didn't even start drilling down that path because, mentally, it was like, "I'm _adding_ a header, not _replacing_ anything."

I will give Replacer a go.

Might still be worthwhile adding the ability to run custom scripts for API proxy scanning. I'm guessing there are other cases where Replacer won't work.

**Comment by tillig** [comment]
Just to follow up, I was able to successfully add my custom header using the technique from the blog article. Thanks for the pointer!

**Comment by tillig** [comment]
One thing I did notice - the retrieval of the OpenAPI document passed into the ZAP API scanner _does not_ include the custom header. I gather it doesn't run through the Replacer, which... will be a challenge we'll have to work around.

**Comment by thc202** [comment]
It should, could you provide more details about your setup?

**Comment by tillig** [comment]
OK, false alarm on that. It happened twice where we couldn't see the header coming through but it seems to be there now. Possibly bad log configuration on our end? Sorry for any time wasted there.

**Comment by psiinon** [comment]
No problem, thanks for letting us know.
