### ISSUE TITLE
Support HTTP/2

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#5038]
This depends on https://github.com/zaproxy/zaproxy/issues/1765
No eta yet, the above issue is non trivial :/

**Comment by zesty** [comment]
Is there somewhere interested folks can follow discussion/development on this?

**Comment by kingthorin** [comment]
Yup right here. Though there's really nothing to discuss. It is being actively worked on.

**Comment by psiinon** [comment]
@zesty is there anything in particular you like to know?

**Comment by zesty** [comment]
@psiinon nope, just curious

**Comment by eranpeleg1** [comment]
hey, 
@psiinon 
[#1765](https://github.com/zaproxy/zaproxy/issues/1765) seems to be closed
does it means zap supports http2 ?

**Comment by psiinon** [comment]
@eranpeleg1 in the weeklies yes 😁 
Have a play and let us know how it works for you!

**Comment by zesty** [comment]
Does this mean that HTTP host header (and/or "some parts"?) manipulation is arriving soon?

ref: "zap missing features" at: https://www.zaproxy.org/docs/burp-to-zap-feature-map/

**Comment by psiinon** [comment]
@zesty Yes - in fact its partly done.
I've just submitted this PR to update that page: https://github.com/zaproxy/zaproxy-website/pull/1500

**Comment by thc202** [comment]
Should we close this? (It was not yet "officially" announced though, e.g. changelog or main release notes.)

**Comment by kingthorin** [comment]
I think we can.

**Comment by thc202** [comment]
Closing, we did mention it's complete in a monthly blog post: https://www.zaproxy.org/blog/2023-02-02-zap-updates-2023-january/#http2-support
