### ISSUE TITLE
zap-full-scan.py unable to exit with ZAP's maxScanDurationInMins option set

### ISSUE THREAD

**Issue by V1Reddy** [zaproxy/zaproxy#5040]
**Describe the bug**
zap-full-scan.py from _owasp/zap2docker-stable docker image_ is unable to exit from the scanning loop after ZAP halts the Active scanning while the option _maxScanDurationInMins_ is set to certain mins. 

**To Reproduce**
1. Run the active scanning in Docker 
2. Execute the command as 'docker run -t owasp/zap2docker-stable zap-full-scan.py -t <https://website.com/> -r example_results.html -z \"-config scanner.maxScanDurationInMins=1\" '
3. After 1 minute (set for maxScanDurationInMins) the ZAP Active scan stops scanning but the log from the zap-full-scan.py will continue to display the same message, for e.g "_Active Scan progress %: 88_" repeatedly without exiting out.

**Expected behavior**
zap-full-scan.py should exit out and publish the results once ZAP halts the active scanning. 

**Screenshots**
N/A

**Software versions**
 - ZAP: owasp/zap2docker-stable (2.7.0)
 - Add-on: N/A
 - OS: Linux OL 7.5, Docker version 18.03.1-ol
 - Java: openjdk version "1.8.0_181"
 - Browser: [e.g. chrome 66, firefox 59, safari 11.1]

**Errors from the zap.log file**
N/A

**Additional context**
N/A

**Comment by V1Reddy** [comment]
I observed that owasp/zap2docker-weekly image doesn't have this issue. The python code exists right after the time set for maxScanDurationInMins. Although, the report generated after exiting doesn't mention anywhere the percentage of Active scanning completed. (I can log this feature of 'displaying the percent of Active scanning completed' as an Enhancement request)

When is the next release of ZAP especially the 'owasp/zap2docker-stable' docker image expected?

**Comment by psiinon** [comment]
When we release the next version of ZAP, which is probably going to be 2.8.0.
Not sure when that will be yet, hopefully not too long.
Can you use the weekly image until then? Its pretty stable - we release new versions if we find out its broken anything...

**Comment by V1Reddy** [comment]
@psiinon 
Thanks for your quick response!

I was little skeptical of using the weekly image since we want to run the scans against our prod urls (along with non-prod) and that we are setting this up for the CI/CD engagements. 
But I will take your word for it and use the weekly image. 

One another thing I noticed that even when using the weekly image, the report or the logs doesn't display the percent of Active scanning completed when exited after the time set. 
I felt it will definitely help the team while running scans on several urls per week to know how many urls exited before the completion of the full active scan due to the time that was set for the 'maxScanDurationInMins' option .
Do you know if anyone requested this feature before? If not, I would like to request this as an enhancement feature if you think this feature makes sense.

Thanks.

**Comment by psiinon** [comment]
So we actually use the live image for scanning production sites here at Mozilla :)
I dont think anyone has requested that feature, but I can see why it would be useful.
Can you submit it as a new enhancement request?
OK to close this issue now?

Cheers.

**Comment by V1Reddy** [comment]
Yes, please close the issue. I will submit that request for an enhancement.
Thanks.

**Comment by psiinon** [comment]
thanks
