### ISSUE TITLE
Updated Attack Surface Detector plugin

### ISSUE THREAD

**Issue by matthewD-AVI** [zaproxy/zaproxy#5043]
**Add-on repo**
https://github.com/secdec/attack-surface-detector-zap

**Your contact details**
matthew.deletto@securedecisions.com

**Are you one of the authors**
Yes

**Licence**
https://github.com/secdec/attack-surface-detector-zap/blob/master/LICENSE

**Build instructions**
Build instructions are on the Wiki
https://github.com/secdec/attack-surface-detector-zap/wiki

**Link to more information**
Wiki: https://github.com/secdec/attack-surface-detector-zap/wiki
OWASP project page: https://www.owasp.org/index.php/OWASP_Attack_Surface_Detector_Project

**Twitter handle for tool or author(s)**
@secdec

**Promote to Beta or Release?**
Updating the existing Alpha plugin

**Comment by matthewD-AVI** [comment]
Hello all,
Just checking to see if there has been any progress or if there is something I need to address or can do to help the process.

Thank you

**Comment by thc202** [comment]
I checked the latest changes some days ago and they looked good to me. The only issue is that in the manifest the changes still say first version, ideally that should have a short description with the latest changes. I'm fine with a release as is (since that's already tagged).

**Comment by thc202** [comment]
@psiinon, @kingthorin you ok with releasing as is?

**Comment by psiinon** [comment]
Yeah, fine by me.

**Comment by kingthorin** [comment]
Ya the manifest comment is unfortunate but not really a blocker I don't think.

**Comment by thc202** [comment]
@matthewD-AVI it seems the add-on uploaded to the release 1.1.2 does not have the expected contents, for example, the one uploaded has version 1.2.17 for `com.github.secdec.astam-correlator:threadfix-ham` while the one built from the tag has 1.3.2 (as [expected](https://github.com/secdec/attack-surface-detector-zap/compare/1.1.1...1.1.2#diff-ba58699127304e498ae238ef836418bcR332)). Some of the classes also have differences.

**Comment by thc202** [comment]
Thanks!

**Comment by thc202** [comment]
Closing, the new version is now available in the marketplace.

**Comment by psiinon** [comment]
Tweeted :) https://twitter.com/zaproxy/status/1054774332923240449
