### ISSUE TITLE
NodeJS API Upgrade

### ISSUE THREAD

**Issue by binarymist** [zaproxy/zaproxy#5044]
Working on this now:
https://github.com/zaproxy/zaproxy/blob/develop/src/org/zaproxy/zap/extension/api/NodeJSAPIGenerator.java
https://www.npmjs.com/package/zaproxy

**Comment by psiinon** [comment]
Great :)
FYI we'd like to move the NodeJS API to https://github.com/zaproxy/zap-api-nodejs :)
The NodeJSAPIGenerator can stay where it is though.

**Comment by binarymist** [comment]
Yip, changes (first round) have already been made in source. Just need to run the generator.

**Comment by binarymist** [comment]
Any idea why there is no `issues` tab on [zap-api-nodejs](https://github.com/zaproxy/zap-api-nodejs/issues)?

**Comment by kingthorin** [comment]
https://github.com/zaproxy/zap-api-nodejs/blob/master/LICENSE
https://github.com/zaproxy/zaproxy/blob/develop/LICENSE

Both Apache License 2.0???

**Comment by binarymist** [comment]
Yes, those two are @kingthorin , but the License in the link I provided above is MIT

**Comment by thc202** [comment]
Issues are not enabled since we manage them here, in the main repo. That's the same for all API clients.

**Comment by thc202** [comment]
I don't know why MIT was chosen.

**Comment by kingthorin** [comment]
> Yes, those two are @kingthorin , but the License in the link I provided above is MIT

Weird, maybe if you dig through the history/blame there's something about it...

**Comment by binarymist** [comment]
Todo future PR: @binarymist:
  - [ ] Remove zaproxy/nodejs files
  - [ ] Review of all generated files

**Comment by thc202** [comment]
The repo has been added to snyk.

**Comment by binarymist** [comment]
Can you please add the snyk badge to the README @thc202 ?

**Comment by thc202** [comment]
Sure.

**Comment by binarymist** [comment]
Then I guess:  
1. `npm version 1.0.0-rc.1`
2. `npm publish`
3. Update `CHANGELOG.md`

**Comment by psiinon** [comment]
0. Add to https://lgtm.com/ (done)
4. Publicise via ZAP groups, twitter etc :)

**Comment by psiinon** [comment]
lgtm has analysed the code now. Looks good until you show the files it excludes: https://lgtm.com/projects/g/zaproxy/zap-api-nodejs/latest/files/?sort=name&dir=ASC&mode=heatmap&showExcluded=true
158 issues but hopefully most of those have the same underlying cause

**Comment by psiinon** [comment]
If you're happy with it them I am :)

**Comment by binarymist** [comment]
Are you doing it @psiinon / @thc202 ? If not I'm happy to if you can supply creds.

**Comment by thc202** [comment]
We can do the release, but we should look into adding permissions to you as well.

I've a question regarding the release steps, wouldn't that leave the tag with an "incomplete" changelog, it would still say "unreleased" instead of the tagged version?

**Comment by thc202** [comment]
The release has been done.

**Comment by thc202** [comment]
@binarymist do you want the issue open for the follow up changes or can it be closed?
