### ISSUE TITLE
ZAP adds session cookies when resending in manual request editor

### ISSUE THREAD

**Issue by timhemel** [zaproxy/zaproxy#5050]
**Describe the bug**
When resending a request without a session cookie, ZAP adds the session cookie when resending the exact same request again.

**To Reproduce**
1. Make/pick a request without a session cookie with a response that sets a session cookie.
2. right click on the request in the history and select 'resend' / 'Open/Resend with request editor'
3. Resend the request, the response will show a Set-Cookie header with a session cookie
4. Click the request tab again, note that the request still does not have a session cookie
5. resend the request again, the response this time does *not* have a Set-cookie header
6. Click the request tab again, and see that ZAP has silently added a Cookie header to the request
7. Removing this header and resending does not prevent ZAP from sending the cookie with the request.

**Expected behavior**
ZAP should not have added the session cookie. In step 5, I would have expected to see a Set-Cookie header. In step 6, I would have expected to not see the cookie header.

**Screenshots**

**Software versions**
 - ZAP: 2.7.0 and 2.5.0
 - Add-on: 
 - OS: Linux, Fedora core-27
 - Java: java version "1.8.0_181"
 - Browser: n/a

**Errors from the zap.log file**
No errors.

**Additional context**
I often use resending a request to analyze an application's session management. If ZAP silently modifies my requests, I cannot rely on the results.

**Comment by thc202** [comment]
Merging into #1164, the editor has cookies enabled by default that's why it automatically adds the cookies.
