### ISSUE TITLE
ZAP proxy is returning with Too Many Redirect message

### ISSUE THREAD

**Issue by jchowdhary** [zaproxy/zaproxy#5051]
I have been using ZAP for almost 6-7 months. I have installed the version 2.7 version.I have configured the corporate proxy in outgoing proxy details in the connection section and local proxy is set to 8080.
In the browser, I have configured the Setting so that proxy is set to localhost:8080
now I am trying to open my local site in browser, it opens but information is not captured in ZAP.

Now when I try to open the same url from within the ZAP proxy own browser like JXBrowser or its Chrome Browser...page starts loading but automatically error page comes " too many redirects " and issue is captured in ZAP now.. I have not modified any settings other than putting the outgoing proxy server information.

**Comment by kingthorin** [comment]
Your corporate proxy likely can't be used for local targets... that would seem to cause a routing issue.

Also some browsers have a default "No proxy for" list that includes loopback and localhost.
