### ISSUE TITLE
Low performance, high CPU usage followed by possible hang while interacting with JSON responses > 60kb in size

### ISSUE THREAD

**Issue by wadim-al** [zaproxy/zaproxy#5057]
Steps:
1. Make a request which returns a JSON response > 60 kb. in size
2. Try selecting all text in the response tab
3. Try copying the selected text
4. Try scrolling the text

Expected:
Selecting text, copying, scrolling of the contents in the response tab should be quick.

Actual:
When the response contains JSON and is > 60 kb in size, selecting the text, copying to the clipboard using the rightclick menu takes up to 20 seconds on 4 ghz 4-core core i3 8350k CPU (for each action). Sometimes it hangs longer (waited 2 minutes max). Scrolling speed depends on the size of the response too.

**Comment by thc202** [comment]
With which view? Is the whole content in one line? This is probably a known performance issue, some workarounds were already applied in some places (#4589).

**Comment by kingthorin** [comment]
@wadim-al are you able to provide further details and answer the questions that have been asked?

**Comment by kingthorin** [comment]
Closing due to insufficient evidence.
