### ISSUE TITLE
pscan Open Redirect (10028) "Attack" should be Desc or Other Info

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#5058]
Open Redirect passive scan rule (10028), displays an "Attack" value, yet doesn't actually perform any "attack". The string in question should likely be part of the Description or Other Info field.

1. Passive Scan something that causes this rule to fire (like JuiceShop)
2. Review the generated alert(s)

Screenshots
![image](https://user-images.githubusercontent.com/7570458/47017518-752f6880-d120-11e8-895d-baef6e7903eb.png)

Software versions
 - ZAP: DEV (w2018-10-08)

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#1846.
