### ISSUE TITLE
Extend TableHistory with filter for "historyid > x" 

### ISSUE THREAD

**Issue by denniskniep** [zaproxy/zaproxy#5064]
**Is your feature request related to a problem? Please describe.**
In an iterative process it should be possible to query all "new" HistoryIds. 

**Describe the solution you'd like**
Extend the Interface `TableHistory` with the following Methods:

```
List<Integer> getHistoryIds(long sessionId, int startAtHistoryId) throws DatabaseException;

List<Integer> getHistoryIdsOfHistType(long sessionId, int startAtHistoryId, int... histTypes) throws DatabaseException;

List<Integer> getHistoryIdsExceptOfHistType(long sessionId, int startAtHistoryId, int... histTypes) throws DatabaseException;
```

Now we can save the last processed historyId and the next run of the process can start immediately with an unprocessed historyId.

**Comment by thc202** [comment]
The later two methods will make the existing method calls ambiguous.

**Comment by thc202** [comment]
Maybe rename to `getHistoryIds*From` or `getHistoryIds*Starting`?
