### ISSUE TITLE
Listening for changes of the message in the Request/Response panels

### ISSUE THREAD

**Issue by denniskniep** [zaproxy/zaproxy#5065]
**Is your feature request related to a problem? Please describe.**
I want to get a notification if the HttpMessage in the HttpPanel is changed. For example, the user selects a new message in the history tab.

**Describe the solution you'd like**
Maybe we could add a subscribe mechanism in the `View` class. And every time the method `displayMessage` is called all listeners will be notified.

Other suggestions are welcome

**Comment by thc202** [comment]
We should also take into account other messages types, which are not yet levering that method (e.g. the listeners would not be informed when the `HttpMessage` is no longer shown).

**Comment by denniskniep** [comment]
yes, you are right. We could implement it in the `HttpPanel` and bubble the notification up to all that are registered at the `View`.

Then we don't miss i.e. WebSocketMessages

**Comment by thc202** [comment]
Sounds good.
