### ISSUE TITLE
Regular re-build of Docker images?

### ISSUE THREAD

**Issue by fwilhe** [zaproxy/zaproxy#5074]
Hello,

I'm investigating adding ZAP to our CD pipeline, which is heavily based on Docker. I found the `owasp/zap2docker-bare` image, which looks good for that purpose, but the last build of this was "a year ago".

Is it possible to provide a recent image build, or should I use the "weekly" image?

Thanks,
Florian

**Comment by psiinon** [comment]
That is the most recent stable image.
If you start ZAP with the `-addonupdate` command line option then ZAP will download the latest versions of the add-ons.
You can also use the weekly image - we actually use the 'live' image at Mozilla, so the weekly image should be stable enough for most purposes.

**Comment by fwilhe** [comment]
Ok, I think in that case, using the `bare` image is still the best option for user use case. Thanks. I'll close this issue.
