### ISSUE TITLE
ZAP API: Replacer / AddRule - The parameter replacement*	must not be mandatory

### ISSUE THREAD

**Issue by rseedorff** [zaproxy/zaproxy#5080]
**Describe the bug**
The ZAP Rest API for the replacer function (/replacer/action/addRule()) contains a mandatory field: "replacement*", but in the ZAP UI it isn't mandatory. 

**Expected behavior**
The parameter "replacement*" must not be mandatory in the ZAP API. If you want to delete an existing matched value (replacer function) you need the possibility to define an empty "replacement*" value.

**Screenshots**
_Replacement String is **NOT** mandatory:_
![zap_replacer_ui](https://user-images.githubusercontent.com/7081348/47568413-58b9da00-d931-11e8-9426-2098a9fa2135.png)

_Replacement String is mandatory:_
<img width="603" alt="zap_api_ui_api" src="https://user-images.githubusercontent.com/7081348/47568464-7a1ac600-d931-11e8-8f87-f092283aa4ce.png">

**Software versions**
 - ZAP: 2.7.0

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#1857.

**Comment by thc202** [comment]
Released in version 7 of Replacer add-on.
