### ISSUE TITLE
Build/Contribute Doc Updates

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#5094]
Update docs following various recent changes:

Removal of Eclipse files:
- Following: https://github.com/zaproxy/zap-admin/pull/146
  - Update:
     - https://github.com/zaproxy/zaproxy/wiki/Building
     - https://github.com/zaproxy/zaproxy/wiki/Setting-up-and-developing-new-plugins
  - <sub>Ref: https://stackoverflow.com/questions/53064084/owasp-zap-plug-in-development</sub>

I'm sure there are or will be others, please edit this if you find others.

**Comment by kingthorin** [comment]
https://github.com/zaproxy/zaproxy/wiki/ZapAddOns will also need to be updated after the extensions repo is flattened.

**Comment by thc202** [comment]
I think we can close this, the wiki pages were updated and some of them are already linking to the new docs: https://www.zaproxy.org/docs/developer/
We also have a tracker issue in the website repo to migrate/add more: zaproxy/zaproxy-website#366.

**Comment by kingthorin** [comment]
Agreed.
