### ISSUE TITLE
Add JWT as an authentication method for Contexts

### ISSUE THREAD

**Issue by rezen** [zaproxy/zaproxy#5095]
As more web applications are client side heavy & leverage JWT it would be nice to natively support JWT. Currently, as an example, with Juice Shop, if you wanted to Force Authentication for spidering, you have to have 2 scripts, one for **authentication** and another **httpsender** script that includes the `Authorization` header with the token.

Having JWT as a native authentication method would be make it easier to use ZAP for single page apps that use JWT.

**Comment by thc202** [comment]
I don't think we need another authentication method, the existing ones already work (e.g. JSON-based Authentication). What's missing to support this use case is a session management method to extract the authentication token for subsequent use (#4662).

**Comment by rezen** [comment]
Ah! I haven't been using a newer version of ZAP so didn't realize JSON was added, that's good to know!

Hmm that makes sense, session management needs to know what to extract as well as where to include (Cookie vs Authorization header) in future requests.

**Comment by thc202** [comment]
Merging into #4662 then.
