### ISSUE TITLE
Some Zest Scripts Drop Every Topmost Request Header

### ISSUE THREAD

**Issue by Captain-Kludge** [zaproxy/zaproxy#5100]
Enabling an HTTP Sender Zest script will lose the top request header when executing standalone Zest scripts or requests generated by the open/resend function. It will 'consume' whatever the top header is and only the top, regardless if it is an authorization header or user-agent. In the case of right-clicking on a particular request and performing some manual/exploratory testing, each subsequent submission will consume the topmost header, so after 5 or 6 iterations all headers will be gone, though content-length and host appear to be immune. 

1. In the script dialogue, create a new HTTP Sender Zest script from template. The error is present without any actual content or rules, so none are necessary.
2. Activate HTTP Sender script.
3. Browse to a website proxying through ZAP. Note the topmost header for the primary site request.
4. Right click on the network request, and click 'send' without making changes.
5. Go back to the 'request' tab, and note that the topmost header is gone.
6. Repeat steps 4 and 5 several times.
7. Look in the ZAP History tab and observe a series of otherwise identical requests, each with one less header than the last. 

optional:

8. If needed, one can also record a standalone zest script of a series of network requests and observe that the standalone script will contain full headers in each request while the actual sent ones will have one less. (compare Zest tab contents with History tab, or with an upstream proxy like Fiddler)

I expect that when an HTTP Sender script is active, it will only modify elements of a request that meets the conditions explicitly created within the script and it will only change explicitly stated elements.

Screenshots included below!

ZAP: 2.7.0
Add-on: Zest Graphical Security Scripting language, 2.7.0.0
OS: Windows 10
Java: 1.8.0_191
Browser: Firefox 63.0

Log contents are in debugZAP1.jpg, where setVariable request.header can be seen at the top setting the proper headers, and when invoked again (during a resend action), the 'content-type' header is no longer present. 

Additional Note: 

Currently I use a lot of standalone Zest scripts to be able to repeatedly perform series of API calls in a consistent and simple way, my current workaround is to simply have a kind of 'padding' header at the top of my recorded requests (ie, something that doesn't matter when it gets dropped). And I have to remember to disable HTTP Sender when doing manual/exploratory stuff on a single request.

Hopefully it's some simple thing like it turns headers into an array [0,x] and when setting them is somehow setting [1,x] and thereby losing the first. Just a wild guess!

Anyway, thanks for the great tool and all the hard work, hope this helps! 

![debugzap1](https://user-images.githubusercontent.com/20678500/47918385-c4a9be80-deac-11e8-8f77-1de6f614ccaa.jpg)
![debugzap2](https://user-images.githubusercontent.com/20678500/47918386-c5425500-deac-11e8-88fe-fcaebdfc0d20.jpg)

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#1882.

**Comment by thc202** [comment]
Released in version 28 of Zest add-on.
