### ISSUE TITLE
Extensions issues with /tmp mounted as noexec

### ISSUE THREAD

**Issue by j34n-m3-2** [zaproxy/zaproxy#5106]
Hello
Describe the bug
Make extensions (mainly jxbrowser) working with /tmp mounted as noexec nodev or with fix https://jxbrowser.support.teamdev.com/support/solutions/articles/9000015146-chromium-binaries.

To Reproduce
    Go to /etc/fstab to set noexec nodev flags for /tmp partition (if exist)
    Restart computer
    Launch ZAP, in menu bar go to Tools > Options > jvm and fill textbox with the fix:
   ` -Djxbrowser.chromium.dir=watheverRelativPathUWantToUseForExtractChromiumBinariesTo`
    (i intentionally removed double quotes from the fix of the teamdev website)
    uninstall addons (jxbrowser core + linux x64 + linuxwebdriver) in my case
    restart zap and reinstall addons removed in previous step

See error:
Expected behavior
``129533 [Thread-7] INFO org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate - Installing new addon webdriverlinux v7.0.0 129964 [Thread-7] INFO org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate - Installing new addon jxbrowser v9.0.0 130072 [Thread-7] INFO org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate - Installing new addon jxbrowserlinux64 v7.0.0``
    Binaries are extracted where i want (~/.ZAP/tmp/.jxbrowser in my case)
    But when i lauch jxbrowser seems like the system parameter i set to `.ZAP_JVM.properties` file through the menu
   ` -Djxbrowser.chromium.dir=watheverRelativPathUWantToUseForExtractChromiumBinariesTo` is not used and i get this exception:
   `136930 [AWT-EventQueue-0] ERROR org.zaproxy.zap.ZAP$UncaughtExceptionLogger - Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: /tmp/browsercore-64.0.3282.24.6.20/data/Temp/libbrowsercore-common64-37f91c6a-e1d0-435c-9ff5-fb83f887b69a.so: /tmp/browsercore-64.0.3282.24.6.20/data/Temp/libbrowsercore-common64-37f91c6a-e1d0-435c-9ff5-fb83f887b69a.so: failed to map segment from shared object`
    I don't need a lot of addons, i love using zap and his integrated browser for webpentest, gives an history and an easy and cool way to control requests i send.

Software versions:
    ZAP: 2.7.0
    Add-on: webdriverlinux v7.0.0, jxbrowser v9.0.0, jxbrowserlinux64 v7.0.0 (i hope i could fix others alone if i need, like SOAP one)
    OS: Arch like (parabola)
    Java: openjdk version "10.0.2" 2018-07-17
    Browser: jxbrowser v9

Errors from the zap.log file
[zapLog.txt](https://github.com/zaproxy/zaproxy/files/2548636/zapLog.txt)

Additional context
i can join a screenshot of my fstab if needed

in advance, thks

**Comment by thc202** [comment]
Would you mind trying with latest versions of JxBrowser add-ons?

**Comment by j34n-m3-2** [comment]
thks for the response, still the same after addon update

**Comment by j34n-m3-2** [comment]
``22801 [AWT-EventQueue-0] ERROR org.zaproxy.zap.ZAP$UncaughtExceptionLogger  - Exception in thread "AWT-EventQueue-0"
java.lang.UnsatisfiedLinkError: /tmp/browsercore-64.0.3282.24.6.22/data/Temp/libbrowsercore-common64-bb8e66f9-6564-42a2-9491-b69be947eb75.so: /tmp/browsercore-64.0.3282.24.6.22/data/Temp/libbrowsercore-common64-bb8e66f9-6564-42a2-9491-b69be947eb75.so: failed to map segment from shared object`` after updating jvm the file browsercore-64common.so is in the path specified by the jvm ``-Djxbrowser.chromium.dir=watheverRelativPathUWantToUseForExtractChromiumBinariesTo``

**Comment by psiinon** [comment]
Everyone ok to close this as we no longer support JxBrowser?
