### ISSUE TITLE
Unexpected Content (Type was returned) - incompatible with RFC 7807

### ISSUE THREAD

**Issue by pmlech** [zaproxy/zaproxy#5121]
**Is your feature request related to a problem? Please describe.**

When performing automatic security tests, ZAP reports vulnerability :

Unexpected Content-Type was returned
"A Content-Type of application/problem+json was returned by the server.
This is not one of the types expected to be returned by an API.
Raised by the 'Alert on Unexpected Content Types' script"

This behavior is incompatible with RFC 7807 https://tools.ietf.org/html/rfc7807#section-6.1

**Describe the solution you'd like**
This behavior should not be identified as vulnerability.

**Comment by psiinon** [comment]
Agreed, also "application/problem+xml"
For info the relevant list of content types is here: https://github.com/zaproxy/zaproxy/blob/develop/docker/scripts/scripts/httpsender/Alert_on_Unexpected_Content_Types.js#L10-L18

**Comment by tillig** [comment]
Is there a way to pass a `-z "-config XXXXX"` sort of command to `zap-api-scan.py` to temporarily disable this rule? I haven't been able to figure out the magic incantation that makes it work.

**Comment by psiinon** [comment]
@tillig yes, just use the -g option to generate a config file, edit it it to change the relevant rule to IGNORE and then specify that file with the -c flag when you rerun it.
Thats all described here: https://github.com/zaproxy/zaproxy/wiki/ZAP-API-Scan#configuration-file

**Comment by tillig** [comment]
I was hoping to do it without the file, which is why I asked about -z. I already pass some options for the replacer plugin via -z and it'd be nice to just tack it on there.

**Comment by psiinon** [comment]
Yes, I think you can set it via a config option - we have a FAQ about finding those :) https://github.com/zaproxy/zaproxy/wiki/FAQconfigValues

**Comment by tillig** [comment]
I'll have to work more with that. I tried disabling a different plugin and guess the setting from my discoveries there but it didn't work. I'll have to replicate the loads that happen in zap-api-scan.py and go from there.

**Comment by tillig** [comment]
@psiinon I'm starting to think it may not be possible. Here's what I did:

- Downloaded the two scripts that get included via the `zap-api-scan.py` script: `Alert_on_Unexpected_Content_Types.js` and `Alert_on_HTTP_Response_Code_Errors.js`.
- Put those scripts in a folder `scripts-to-load/httpsender`.
- Started up ZAP in an interactive mode (which is not how I normally run the API scanner).
- In Tools => Options => Scripts added the `scripts-to-load` folder.

This is where I get stuck. There's no configuration setting I can find to disable an individual script. I see in the `config.xml` there's a `dirs` entry that has my script directory listed, but there's no UI to disable or remove a particular script.

I looked in the scan policy configuration but I don't see any entries for these two loaded scripts. There's nothing I can disable or change to have it persist a configuration setting.

I used the ZAP API to disable the `Alert_on_Unexpected_Content_Types.js` script. Using the API I can then see it's disabled. However, this doesn't appear to get persisted to the config.xml, at least that I can find. Perhaps it is saved in the session database?

I'm somewhat outside my depth at this point and the FAQs and docs don't really address the situation. I admit there's a non-zero possibility I'm missing something obvious, but my Google-fu skills seem to be failing me and it's been a non-trivial effort trying to reverse engineer the path between script loading and configuration serialization.

After spending about 10 hours on this so far I'm hoping someone may be able to just give me the `-config` line I need to disable the scanner _or_ confirm that there isn't such an option.

**Comment by kingthorin** [comment]
Create a modified version of the zap-api-scan.py script outside docker and use it to drive ZAP in the container or re-create your own docker image with your version of zap-api-scan.py. Just use the `script/action/disable/` API endpoint to disabled `Alert_on_Unexpected_Content_Types`

**Comment by tillig** [comment]
Again, [I was hoping to do this without creating any new files](https://github.com/zaproxy/zaproxy/issues/5121#issuecomment-462064575) - new script, forked script, extra config file, etc. - since we're already passing several options in and using `-z` to pass in replacer settings. Adding the extra files or forking is actually a bit of added complexity in an already complex CI/CD pipeline I'm really trying to avoid.

If I'm asking something that literally isn't possible, great, but it'd be nice to know; from the earlier indications pointing at FAQs, it sounded like I was just not figuring it out (and I'm still not able to).

It appears to be a pretty simple fix to the scripts, which I'm also willing to do but there's some... _organizational and legal_ processes I have to get through first to get approval to make the PR. However, it also may be that this has raised a shortcoming in the command-line configuration mechanism for the ZAP API scanner script that may need to be addressed. That is, maybe there should be something like `-L ID=LEVEL` for example `-L 100000=NONE` to set an individual rule level without a configuration file.

**Comment by thc202** [comment]
At the moment it's not possible to use command line arguments to disable that, the scanners are being added and enabled by the script.

**Comment by tillig** [comment]
Fair enough, I appreciate the info. I'll look at a rule config file and see how that affects our processes.

**Comment by thc202** [comment]
In any case it worth raising a new issue for the enhancement you mentioned.

**Comment by kingthorin** [comment]
>Again, [I was hoping to do this without creating any new files](https://github.com/zaproxy/zaproxy/issues/5121#issuecomment-462064575) - new script, forked script, extra config file, etc.

@tillig fair enough, I was just trying to provide options, I agree that it's not optimal. As thc202 suggested an enhancement request for a mechanism to disable scripts is probably your best bet: https://github.com/zaproxy/zaproxy/issues/new?labels=enhancement&template=Feature_request.md 

> If I'm asking something that literally isn't possible, great, but it'd be nice to know; from the earlier indications pointing at FAQs, it sounded like I was just not figuring it out (and I'm still not able to).

There's a way to ignore the alerts created by the script(s), but not to disable the script (without using the API and creating new files).
