### ISSUE TITLE
Accessing API UI via proxy doesn't work unless you add a host of private IP addresses

### ISSUE THREAD

**Issue by ojasp** [zaproxy/zaproxy#5123]
Steps to reproduce:
Create a new container on Azure container Instance using the following command:
```
New-AzureRmContainerGroup -ResourceGroupName $resourceGroupName -Name $containerGroupName -Image $imageName -Command zap-webswing.sh -Port 8080,8090 `
         -IpAddressType Public -DnsNameLabel $containerDnsName -RestartPolicy OnFailure -Location 'East US' -AzureFileVolumeShareName $storageShareName `
        -AzureFileVolumeMountPath '/output' -AzureFileVolumeAccountCredential $storageCredentials 

```
** I set the parameter values to the ones we need for our environment.
- Access the container via browser: XXXzapcontainerXXX.eastus.azurecontainer.io:8080/zap/
- Set a different browser to proxy through ZAP & confirm that the traffic shows up in ZAP.
- Access http://zap/UI from the above browser. You will get an error: connection was reset.
- Look at the webswing.log file and you'll notice that a bunch of private IP address are not allowed access. 
- Once you add these, you can then access the API UI. I believe that these local IP addresses are dynamic and will change on every container creation. Here's a screenshot:

![image](https://user-images.githubusercontent.com/15022394/48785283-74a36800-ecb2-11e8-9c2b-c3f66233b85e.png)

The IP address assigned to the container in this instance is 10.244.48.16. Two questions:  
- Why is zap container trying to access traffic over the 10.240.XX.XX range?
- Is there anyway to figure out the IP addresses the traffic will be coming from when the container is created and add them to whitelist?

**Comment by psiinon** [comment]
TBH I think this is more of an Azure issue that a ZAP one. By default ZAP only listens on local IP addresses. You can configure it to listen on other addresses and you can also specify which IP addresses ZAP should accept API requests from.

**Comment by ojasp** [comment]
> > Why is zap container trying to access traffic over the 10.240.XX.XX range?
> 
> Those are the addresses that tried to access the ZAP API (and were not allowed) not ZAP accessing them.

Sorry, that's what I meant. When I tried to access the API UI via proxy I was tailing the webswing log file and it showed that those 3 ip addresses were not allowed access. Like @psiinon said, it must be specific to the way Azure Container Services is architected. Between this and [limits](https://stackoverflow.com/questions/52170119/configuration-of-owasp-zap-on-azure-container-instances) on what parameters can be passed to the powershell commandlet to create a container, I haven't had the best luck setting up zap on ACI. I am gonna  set it up on a VM instead, is it possible to run webswing on a headless installation?

**Comment by kingthorin** [comment]
Not sure, but you could just try :smile: Might need xvfb or something like that. Check these resources for further details: 
https://github.com/zaproxy/zaproxy/wiki/WebSwing
https://github.com/zaproxy/zaproxy/wiki/Docker
