### ISSUE TITLE
Node API tidy ups from 1.0.0-rc.1

### ISSUE THREAD

**Issue by binarymist** [zaproxy/zaproxy#5126]
**Describe the bug**

Tidy ups to the Node API generator noticed while working on 1.0.0-rc.1

**Immediate items**

- [ ] Remove redundant `!= null` checks as described here:

* https://github.com/zaproxy/zap-api-nodejs/pull/1#issuecomment-437641119
* https://github.com/zaproxy/zaproxy/issues/5044#issuecomment-438647849

- [ ] Other code smells?

**Expected behavior**

Functionality should not change

**Additional context**

..

**Comment by thc202** [comment]
Closing, the release was done (latest 1.0.1).
