### ISSUE TITLE
Insecure Component Scanner (pscan) doesn't cleanup after itself

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#5133]
I noticed hundreds of 720kB files with names similar to `sqlite-3.8.11.1-e929a4c8-fce5-4af7-8d61-66ea0446f1c0-sqlitejdbc.dll` in my temp directory today (Win7).

After a little hunting I've tracked this down to the Insecure Component Scanner:
* https://github.com/zaproxy/zap-extensions/blob/master/addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/InsecureComponentScanner.java
  * https://github.com/zaproxy/zap-extensions/blob/master/addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/VulnerabilityCache.java

I ran out of time to investigate further, but both ZAP and the SVN Spider use SQLite without this issue occurring. I did notice that the SVN Spider uses try with resource on the DB connection so perhaps that's the relevant difference? https://github.com/zaproxy/zaproxy/blob/63d61b3a15ac8d518b8fd22ff01709414668ecca/src/org/zaproxy/zap/spider/parser/SpiderSVNEntriesParser.java#L141

**Comment by thc202** [comment]
Yeah, in this the connection needs to be closed when the add-on is uninstalled or ZAP closed.

**Comment by kingthorin** [comment]
Closing `wontfix` per: zaproxy/zaproxy#5788
