### ISSUE TITLE
Docker steps added as stage in Jenkinsfile - proxy error

### ISSUE THREAD

**Issue by deepikathimmegowda** [zaproxy/zaproxy#5147]
**Describe the bug**
I am using owasp/zap2docker-stable and automate pen testing in Jenkins. 
Using below commands but i see proxy error when ran in Jenkins

docker run --name deepika -u zap -p 8090:8090 -d owasp/zap2docker-stable zap.sh -daemon -port 8090 -host 0.0.0.0 -config api.disablekey=true
docker exec deepika zap-cli -p 8090 open-url http://testhtml5.vulnweb.com/

But But But when i run these in shell after ssh into same Jenkins instance it works  perfectly, I can open-url and can do active-scan as well. 

Unfortunately when i run these commands as below in Jenkinfile, build fails with error

```
stage('Pen Testing') {
       steps{
           sh "docker pull owasp/zap2docker-stable"
            sh "docker run --name deepika -u zap -p 8090:8090 -d owasp/zap2docker-stable zap.sh -daemon -port 8090 -host 0.0.0.0 -config api.disablekey=true"
            sh "docker exec deepika zap-cli -p 8090 open-url http://testhtml5.vulnweb.com/"
       }
}
```

```
requests.exceptions.ProxyError: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: http://zap/JSON/ascan/action/disableAllScanners/?apikey= (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f8671d10490>: Failed to establish a new connection: [Errno 111] Connection refused',)))
```

**To Reproduce**
1. Add docker steps in Jenkinsfile
2. Trigger build in Jenkins
3. I see error

<details>
<summary>Verbose error details (click triangle to expand)</summary>

```
+ docker pull owasp/zap2docker-stable
Using default tag: latest
latest: Pulling from owasp/zap2docker-stable
Digest: sha256:0deed8bcdf8d831f368a790be453e53107791f10104c76f2281df116db71a02d
Status: Image is up to date for owasp/zap2docker-stable:latest
[Pipeline] sh
+ docker rm deepika -f
deepika
[Pipeline] sh
+ docker run --name deepika -u zap -d owasp/zap2docker-stable zap.sh -daemon
5d4842504f461b5d0d0c98bd4c4b9b72824cc13faf3bab531f8a8960e785fad7
[Pipeline] sh
+ docker exec deepika zap-cli quick-scan -s xss,sqli --spider -l Informational --spider http://testhtml5.vulnweb.com/
[INFO]            Running a quick scan for http://testhtml5.vulnweb.com/
Traceback (most recent call last):
  File "/usr/local/bin/zap-cli", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 26, in new_func
    return ctx.invoke(f, ctx.obj, *args[1:], **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/zapcli/cli.py", line 217, in quick_scan
    zap_helper.set_enabled_scanners(options['scanners'])
  File "/usr/local/lib/python2.7/dist-packages/zapcli/zap_helper.py", line 310, in set_enabled_scanners
    self.zap.ascan.disable_all_scanners(apikey=self.api_key)
  File "/usr/local/lib/python2.7/dist-packages/zapv2/ascan.py", line 278, in disable_all_scanners
    return six.next(six.itervalues(self.zap._request(self.zap.base + 'ascan/action/disableAllScanners/', params)))
  File "/usr/local/lib/python2.7/dist-packages/zapv2/__init__.py", line 159, in _request
    data = self._request_api(url, get)
  File "/usr/local/lib/python2.7/dist-packages/zapv2/__init__.py", line 149, in _request_api
    return self.session.get(url, params=query, proxies=self.__proxies, verify=False)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 485, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: http://zap/JSON/ascan/action/disableAllScanners/?apikey= (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f8671d10490>: Failed to establish a new connection: [Errno 111] Connection refused',)))
```

</details>

<br>**Expected behavior**
Should be able to open-url and get results like below
docker exec deepika zap-cli -p 8080 open-url http://testhtml5.vulnweb.com/
[INFO]            Accessing URL http://testhtml5.vulnweb.com/

**Software versions**
Using owasp/zap2docker-stable:latest

Container logs attached:
[deepikacontainerlogs.txt](https://github.com/zaproxy/zaproxy/files/2672483/deepikacontainerlogs.txt)

**Comment by kingthorin** [comment]
You started the container/ZAP on 8090 but then tried to connect on 8080.

**Comment by deepikathimmegowda** [comment]
docker run --name deepika -u zap -p 8090:8090 -d owasp/zap2docker-stable zap.sh -daemon -port 8090 -host 0.0.0.0 -config api.disablekey=true - I started on 8090

then i tried running on 8090 only:
docker exec deepika zap-cli -p 8090 open-url http://testhtml5.vulnweb.com/"

but zap inside in trying to connect to 8080 when running from Jenkins.
can see below error
requests.exceptions.ProxyError: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: http://zap/JSON/ascan/action/disableAllScanners/?apikey= (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f8671d10490>: Failed to establish a new connection: [Errno 111] Connection refused',)))

if u see the container logs attached deepikacontainerlogs.txt, it clearly says its running on 8090

Could you please tell me where i am going wrong?

**Comment by deepikathimmegowda** [comment]
As i told earlier, when i run both these cmd from shell in Jenkins instance, it works perfectly fine, i am getting the mentioned error when running only from Jenkins.

**Comment by thc202** [comment]
Would you mind passing `--verbose` to see if it provides more details? You should also wait for ZAP to start (using `zap-cli status`) as ZAP might not start before the first command finishes.

**Comment by deepikathimmegowda** [comment]
Thanks for the note.

After first shell cmd
            sh "docker run --name deepika -u zap -p 8090:8090 -d owasp/zap2docker-stable zap.sh -daemon -port 8090 -host 0.0.0.0 -config api.disablekey=true"
I had to wait until daemon started

**Comment by kingthorin** [comment]
So your issue is solved?

**Comment by deepikathimmegowda** [comment]
Yes.. 
Its solved, I should wait until daemon is started.

**Comment by kingthorin** [comment]
Great thanks for letting us know!
