### ISSUE TITLE
Add support for GraphQL inspecting/attacking

### ISSUE THREAD

**Issue by omerlh** [zaproxy/zaproxy#5153]
**Is your feature request related to a problem? Please describe.**
[GraphQL](https://graphql.org/) is:
> GraphQL is a query language for APIs and a runtime for fulfilling those queries with your existing data. GraphQL provides a complete and understandable description of the data in your API, gives clients the power to ask for exactly what they need and nothing more, makes it easier to evolve APIs over time, and enables powerful developer tools.

Building a secure GraphQL is not simple - and also it is not simple to assess the security of a given endpoint. [This](https://blog.doyensec.com/2018/05/17/graphql-security-overview.html) post does a pretty good job describing the different risks with example malicious payload.

**Describe the solution you'd like**
Use Zap to inspect and attack a given GraphQL endpoint and be able to view alerts.

**Describe alternatives you've considered**
Manually running different scripts.

**Comment by psiinon** [comment]
Sounds like a good GSoC (or similar) project.
Note that to be supportable any implementation should have unit tests.

**Comment by kingthorin** [comment]
* https://hackerone.com/reports/291531
* https://developer.github.com/v4/guides/resource-limitations/

**Comment by J12934** [comment]
Now that there is basic support for GraphQL is there an updated ticket / list of features the GraphQL add-on is still missing and requires further contributions? I'd be interested to see how it is planned to get active scanning support for GraphQL APIs into ZAP.

**Comment by psiinon** [comment]
As per https://www.zaproxy.org/blog/2020-08-28-introducing-the-graphql-add-on-for-zap/ @ricekot is planning to keep working on these features :)

**Comment by daniel-ayers** [comment]
Is there any documentation for this extension besides the Aug 28 blog post?

The blog post doesn't explain how to actually use the extension.

It says: "The add-on is still in an early stage, so the range of its functionality is limited. However, you can combine it with existing ZAP functionality to abuse GraphQL endpoints in many different ways.".  But the blog post seems to leave those things as a mystery.

It does explain how to import a schema, and suggests that passive/active scans might find graphql endpoints.  It says queries are generated, but doesn't say how to find them or what to do next?  I've looked around the UI for clues but can't see anything obvious ... ?

**Comment by psiinon** [comment]
Oh, looks like this issue can be closed. Athough we could clearly do with some more help.
GraphQL schemas found as part of spidering will automatically be imported into the Sites Tree (think thats post 2.9.0).
To 'manually' import a GraphQL schema either use one of the "Import" menu options for iomporting a URL or file or one of the 2 API endpoints that do the same thing.
Once the end points are in the Sites Tree you can attack them using the active scanner or fuzzer just like any other URLs.

**Comment by psiinon** [comment]
Closing as we now have a GraphQL add-on - it will be maintained as any other ZAP add-on.

**Comment by psiinon** [comment]
Oh my bad, we do have help :)
Thats included with the add-on in the standard ZAP help and available online:

- https://www.zaproxy.org/docs/desktop/addons/graphql-support/
- https://www.zaproxy.org/docs/desktop/addons/graphql-support/options/
- https://www.zaproxy.org/docs/desktop/addons/graphql-support/script/
