### ISSUE TITLE
We've integrated ZAP with teamcity for continues integration. ZAP is generating reports in XML format. Is there any UI plugin which supports teamcity to import those XML files and present them in html format or any other graphical format?

### ISSUE THREAD

**Issue by ZenqDevSecOps** [zaproxy/zaproxy#5154]
**Add-on repo**
The URL of the repository for the add-on.

**Your contact details**
Email, twitter, whatever works for you.

**Are you one of the authors**
Yes / No

**Licence**
If not clearly stated in the repo.

**Build instructions**
If not in the repo.

**Link to more information**

**Twitter handle for tool or author(s)**
Will be used in the announcement tweet from @zaproxy

**Promote to Beta or Release?**
Note that all new add-ons start at Alpha status.

**Anything else we should know**

**Comment by psiinon** [comment]
Not that I'm aware of.
Please note that the ZAP User Group: https://groups.google.com/forum/#!forum/zaproxy-users is a better forum for asking questions - someone there might be looking at the same thing.
