### ISSUE TITLE
Add support for "good findings"

### ISSUE THREAD

**Issue by omerlh** [zaproxy/zaproxy#5155]
**Is your feature request related to a problem? Please describe.** No

**Describe the solution you'd like**
Zap has many rules, it could be nice to have a report saying something like this:

* Number of rules checked: 20
* Number of rules without any finding: 16 (maybe just a list of the rules?)
* Number of rules with finding: 4

The idea is to help people not only understand what is broken but also what is good. This might help people want to use Zap and improve adoption.
I know, this is kinda risky and we should be careful from people saying "Zap said my app has no vulnerabilities". On the other hand, you can get it already today - no findings is just that.

**Describe alternatives you've considered**
Maybe I can get something through the API? I'm not sure. I think I can write something that will scrape all the issues and rules from the API and combine them. The next thing is patching Glue so it will support reporting of good findings 

**Additional context**

**Comment by psiinon** [comment]
I definitely support this.
I think this has been requested before, but I cant find the relevant issue.
ZAP reports are pretty basic, and we've had lots of requests to improve them. I'd love to do that but just don't have the time right now :( If anyone fancies having a go at that then please get in touch!
Its worth noting that all of the raw information should be available via the API, eg using endpoints like ascan/view/scanProgress but the full set of info (including pscan results) is definitely not in an easy to consume format.

**Comment by psiinon** [comment]
Related twitter thread: https://twitter.com/omerlh/status/1075343215723728898

**Comment by jjburr** [comment]
+1 we need this for our release pipelines as when uploading test results, without having passes it shows 100% failures in security test reporting

**Comment by psiinon** [comment]
This is now supported by the new reporting add-on :)
