### ISSUE TITLE
Inconsistent JSON report format

### ISSUE THREAD

**Issue by omerlh** [zaproxy/zaproxy#5162]
**Describe the bug**
The JSON report output format looks differently where there is only one site and when there are multiple sites. 
When there is only one site, this is how it looks like:
```
{
    "@version": "2.7.0",
    "@generated": "Thu, 27 Dec 2018 12:41:32",
    "site": {
        "@name": "http://localhost:3000",
        "@host": "localhost",
        "@port": "3000",
        "@ssl": "false"
        
    }
}
```
When there are multiple sites, the `@site` property is an array - not an object:
```
{
    "@version": "2.7.0",
    "@generated": "Thu, 27 Dec 2018 12:42:05",
    "site": [
        {
            "@name": "http://other",
            "@host": "icinga2",
            "@port": "80",
            "@ssl": "false"
        },
        {
            "@name": "http://localhost:3000",
            "@host": "localhost",
            "@port": "3000",
            "@ssl": "false"
        }
    ]
}
```
**To Reproduce**
1. Proxy one site through Zap
2. Generate JSON report
3. Proxy another site through Zap
4. Generate JSON report

Compare both files
**Expected behavior**
A consistent behavior of `@site` - it should always be an array.

**Software versions**
 - ZAP: 2.7.0
 - OS: mac/docker

**Comment by omerlh** [comment]
Damn you're fast! I thought to write it down last night but didn't had time to do that :) Thanks!

**Comment by psiinon** [comment]
yeah, @thc202 is a star :)

**Comment by omerlh** [comment]
:) It we'll be released on Wednesday, right? As part of the weekly image?
Does the raw image also release weekly? I

**Comment by psiinon** [comment]
The weekly is usually released on Mondays - that should be available this morning, and yet that will include this fix.
Which raw image are you referring to? The 'bare' image is just for full ZAP releases, ie its still on 2.7.0

**Comment by omerlh** [comment]
Yes, sorry. Can I add a weekly bare image? What do you think?

**Comment by psiinon** [comment]
Maybe yes when we automate the builds better? Thats in progress but no eta

**Comment by omerlh** [comment]
Ok, I'll use the weekly image for now. Thanks :)
