### ISSUE TITLE
Not found response tab on options (keyboard shortcut setting)

### ISSUE THREAD

**Issue by hahwul** [zaproxy/zaproxy#5165]
**Describe the bug**
Not found response tab on options(keyboard shortcut setting)
tweet link: https://twitter.com/hahwul/status/1078150715359424513

**To Reproduce**
1. Launch ZAP Weekly(D-2018-12-17)
2. Open ZAP Preferences(options)
3. Click Keyboard menu
4. Not found response ..

**Expected behavior**
Can not set a keyboard shortcut for the response tab.

**Screenshots**
![1414](https://user-images.githubusercontent.com/13212227/50499028-45d69980-0a89-11e9-9b17-cc385827bae5.png)
![1415](https://user-images.githubusercontent.com/13212227/50499029-45d69980-0a89-11e9-9502-1085f76b433f.png)

**Software versions**
 - ZAP: D-2018-12-17(Weekly download)
 - Add-on: No add-on issue. 
 - OS: macOS Mojave(10.14.2)
 - Java: 1.8.0_152
 - Browser: No browser issue. ( I use firefox )

**Errors from the zap.log file**
um.. is this? There is no error when executed from the command line.
```
9466 [ZAP-BootstrapGUI] INFO org.zaproxy.zap.extension.callback.ExtensionCallback  - Started callback server on 0.0.0.0:57929
9466 [ZAP-BootstrapGUI] INFO org.zaproxy.zap.extension.keyboard.ExtensionKeyboard  - Initializing keyboard shortcuts
9767 [AWT-EventQueue-0] INFO org.parosproxy.paros.control.Control  - New Session
9882 [AWT-EventQueue-0] INFO org.parosproxy.paros.control.Control  - Create and Open Untitled Db
```

**Additional context**
-

**Comment by kingthorin** [comment]
Confirmed, I switched to the 2.6.0 tag in the repo and when I run it I do see a Response Tab options:
![image](https://user-images.githubusercontent.com/7570458/50499402-5fd79400-0a17-11e9-958c-e46e9ec4eb8c.png)

**Comment by kingthorin** [comment]
Seems to have gone missing between `w2018-03-12` and `w2018-03-19`.

In fact it seems all the hotkeys with 3 modifiers (ctrl+alt+shift) disappeared at that point, perhaps due to the look and feel changes?

**Comment by thc202** [comment]
This affects only weekly releases (broken by #4511).

**Comment by thc202** [comment]
@kingthorin that was already fixed (not related to the number of modifiers though, it was the visible state of the tabs).

**Comment by kingthorin** [comment]
Great, pulled latest and it seems to be working as expected. I believe this can be closed.
