### ISSUE TITLE
401 - Unauthorized: Access is denied due to invalid credentials response in fuzz using NTLM credentials in ZAP 2.7.0

### ISSUE THREAD

**Issue by Dubniak** [zaproxy/zaproxy#5170]
**Describe the bug**
Website to be attacked in added in the context, authentication is set to HTTP/NTLM Authentication, hostname and port provided, User with username and password added and enabled. This set up works fine for Spider and Active Scan (that's what I've tried so far) but returns a 401 Unauthorized response when trying to use the Fuzz. 

**Expected behavior**
Execute the web request and return any reply from the server except 401.

**Software versions**
 - ZAP: 2.7.0
 - Add-on: Defaults
 - OS: Win 10
 - Java: openjdk version "1.8.0_191-b_12"
 - Browser: chrome 71.0.3578.98

**Additional context**
I was able to make a work around by chaining another web proxy (Fiddler) in order to handle the NTLM authentication. https://resources.infosecinstitute.com/chaining-web-proxies-to-overcome-limitations/

**Comment by thc202** [comment]
Are you specifying the user [1] or using Forced User mode?

[1] https://github.com/zaproxy/zap-core-help/wiki/HelpAddonsFuzzHttpmessageprocessors#user-message-processor

**Comment by Dubniak** [comment]
I specified the user as per your suggestion (turn off the other proxy as well) and it works like a charm! 
BUT!! The request editor is not working with this technique - it wasn't working even before, only gave results when Fiddler was on.

**Comment by kingthorin** [comment]
Could you try a weekly build and let us know?

**Comment by nishantworah** [comment]
How to specify the user? I am getting the same 401 error on NTLM

**Comment by kingthorin** [comment]
You should answer the questions that were already asked above if you believe you’re experiencing a similar issue.

**Comment by kingthorin** [comment]
Actually I'm going to suggest that this discussion be moved to a more approrpiate place. This ticket should have been closed in late March.

The ZAP User Group https://groups.google.com/group/zaproxy-users is much better place for this type of question.

Here are some references relevant to the topic of this ticket:

- https://www.youtube.com/watch?v=cR4gw-cPZOA
- https://github.com/zaproxy/zap-core-help/wiki/HelpStartConceptsAuthentication#httpntlm-authentication
- https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsSessionContext-auth#httpntlm-authentication
- https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsSessionContexts#users
