### ISSUE TITLE
Docker zap-x.sh not working

### ISSUE THREAD

**Issue by teohaik** [zaproxy/zaproxy#5172]
Hello,

I'am trying to follow the instructions for running zap as a docker container, but the command:

docker run -u zap -p 8081:8080 --name zapSSP -i owasp/zap2docker-bare zap-x.sh -daemon -host 0.0.0.0 -port 8080 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true

yields the following error:

container_linux.go:247: starting container process caused "exec: \"zap-x.sh\": executable file not found in $PATH"

docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"zap-x.sh\": executable file not found in $PATH".

**Software versions**
 - ZAP: latest

DOCKER:
docker version
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Comment by thc202** [comment]
The `zap2docker-bare` image does not include that start up script (on purpose, it's a lightweight image with just ZAP). You would have to use one of the other images.

**Comment by teohaik** [comment]
yeap! that was the problem. I thought it will work because it was meant to be used in CI environments
