### ISSUE TITLE
Move and Promote CSP Scanner

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#5177]
The `CSP Scanner` was originally rolled out as a stand alone extension due to it's dependence on Java 8. Now that ZAP is targeting Java 8 it should be moved into the standard Passive Scan Rule extension(s).

Per discussion via email it should also be promoted to Release (master).

Current Location:
https://github.com/zaproxy/zap-extensions/tree/master/addOns/cspscanner/
Current Status:
[beta - cspscanner.gradle.kts](https://github.com/zaproxy/zap-extensions/blob/ea9d96b3d540dbb1634372809286082791b33527/addOns/cspscanner/cspscanner.gradle.kts#L8)
Future Location:
https://github.com/zaproxy/zap-extensions/tree/master/addOns/pscanrules/

It probably also makes sense to tackle this after the merge (flattening) of the extensions repo is completed (currently WiP).

**Comment by kingthorin** [comment]
At the same time it probably also makes sense to upgrade to 2.6.0 (or newer) of the Salvation library (https://github.com/shapesecurity/salvation/releases).

**Comment by thc202** [comment]
The branches are now merged (updated paths in the issue accordingly).

**Comment by thc202** [comment]
After releasing the add-ons we should update https://github.com/zaproxy/zap-extensions/wiki/HelpAddonsCspscannerCspscanner to link/mention the other add-on.
