### ISSUE TITLE
ZAP reporting falsely reporting X-XSS-Protection header not set

### ISSUE THREAD

**Issue by chrishornmem** [zaproxy/zaproxy#5183]
**Describe the bug**
When running attack scan on my web app running on localhost (node+express), I get the following error:

"Web Browser XSS Protection is not enabled, or is disabled by the configuration of the 'X-XSS-Protection' HTTP response header on the web server"

However, I have enabled the header and when I curl the server, I can see it is enabled.  I can also see it is enabled in Chrome.

The Zap tool is finding this "error" on the home route '/', so nothing special.

I have attached two outputs from one curl and the exported response from Zap.

It's very strange because when I have applied the same express settings in another application, I cannot reproduce this error.

I am using helmet in express, as follows:

app.use(helmet());  
app.use(helmet.noCache());
app.use(helmet.xssFilter());
app.use(xssFilter());

[resp-curl-set.txt](https://github.com/zaproxy/zaproxy/files/2745924/resp-curl-set.txt)
[resp-zap-not-set.txt](https://github.com/zaproxy/zaproxy/files/2745925/resp-zap-not-set.txt)

**Comment by kingthorin** [comment]
Can you provide the requests as well?

**Comment by kingthorin** [comment]
For the record, per your attachment the response does in fact show that it was set but disabled `X-XSS-Protection: 0`. The question is why did your app/server set it that way.

**Comment by chrishornmem** [comment]
Thanks for quick response :)

Zap request here:
[zap-request.txt](https://github.com/zaproxy/zaproxy/files/2746238/zap-request.txt)

I'm just doing curl:
`$ curl -i localhost:5000`

**Comment by kingthorin** [comment]
Also note this issue is becoming less and less relevant as vendors are dropping support/functionality for XSS filtering in Browsers in favor of CSP:
https://portswigger.net/daily-swig/xss-protection-disappears-from-microsoft-edge

**Comment by kingthorin** [comment]
- Is the alert generated when the requested URL has a trailing slash? (Perhaps helmet doesn't handle the missing slash case properly?)
- Does it happen with a more modern User Agent? https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsOptionsConnection#default-user-agent

(You might need to start a fresh ZAP session to test each of those in isolation.)

**Comment by chrishornmem** [comment]
OK, here's an update:

1) Adding trailing slash but that didn't make any difference.

2) Then I tried adding this in connection options screen as default user agent.

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36`

It's still using the old user agent when making the requests (I restarted zap and made a new session).

However, I managed to make a manual request using the above user-agent and I can see X-XSS-Protection is set correctly in the response.

Then I made a manual request using the old (default) user agent value and that is still responding with X-XSS-Protection: 0

So it seems to be something with the user-agent as you identified.

**Comment by kingthorin** [comment]
Ok ignore setting the UA in ZAP. Just start a new session, set your browser to proxy through ZAP. Access the URL in question. Is the alert generated?

> But, I see it's still using the old user agent when making the requests (I restarted zap and made a new session).
Where are you seeing that?

It seems like Helmet is setting the `X-XSS-Protection` header based on the UA.

**Comment by chrishornmem** [comment]
Yes, sure enough when I proxy via Chrome, I don't get the warning.  I'll
dig into the Helmet code and see if I can figure it out.  Thanks for your
help.  I guess you can close this issue.

**Comment by kingthorin** [comment]
@chrishornmem thanks for following up.

Note if you had been seeing the "old" UA in the Spider it might be dependent on what tab you have selected in the bottom panel. If you're on the Spider's URL tab then the top panels request/response aren't changing, if you're on the Messages tab then you should be seeing what the spider is generating and what ZAP is receiving (which should include the current UA from the Connection options screen).

**Comment by chrishornmem** [comment]
for others that have this problem, this issue refers:

https://github.com/helmetjs/helmet/issues/179

Solution  :
```
app.use(helmet({
  xssFilter: {
    setOnOldIE: true
  }
}))
```
