### ISSUE TITLE
ZAP won't un-minimize on OSX

### ISSUE THREAD

**Issue by jackassplus** [zaproxy/zaproxy#5190]
**Describe the bug**
If I minimize ZAP while it's running, I can't get it back.

**To Reproduce**
1. Start the program
2. Minimize the proxy window
3. The window is gone and I can't get it back. (menus still seem to work)

**Expected behavior**
the window to come back when I click it on the dock.

**Screenshots**
Wish I could...

**Software versions**
 - 2.7.0 vanilla
 - OS: MacOS 10.13.6
 - Java: 1.8.0_144
 - Browser: Firefox 62.0.3

**Errors from the zap.log file**
Don't see anything in the log that would be relevant.

**Additional context**
none

**Comment by psiinon** [comment]
Works ok for me on 10.10.5, upgrading to Mojave to see if thats changed something...

**Comment by psiinon** [comment]
Have upgraded my Mac mini to 10.14.2 and it still works fine :/
Can you try restarting your mac and see if that does the trick?
Suggestions from anyone else also very welcome - I'm no mac expert and have only the one machine to try on.

**Comment by psiinon** [comment]
Have asked on twitter: https://twitter.com/psiinon/status/1085549515749425152

**Comment by jackassplus** [comment]
Oddly enough, a reboot seemed to have resolved it.

**Comment by jackassplus** [comment]
Spoke too soon, broke again.

**Comment by psiinon** [comment]
Ugh :/ 
Dont suppose this affects any other programs you have installed?

**Comment by jackassplus** [comment]
Not that I've noticed.

**Comment by psiinon** [comment]
OK. Let us know if you notice anything else, and maybe someone on twitter will come up with something.
Other than that I'm not sure what we can do :/

**Comment by jackassplus** [comment]
better reproduction steps:

start zap
launch browser
start breakpoints
click the browser window, the zap browser pops on top
click zap
minimize
maximize, the window pops up, then disappears, never to be seen again.

**Comment by psiinon** [comment]
Thanks. I'll give that a go tomorrow.
As a work around you could try disabling the 'always on top' breakpoints option - that might be confusing things...

**Comment by jackassplus** [comment]
That works better so far.

**Comment by psiinon** [comment]
Just tried this and ZAP still appears ok, even with the 'always on top' option enabled :/
Can anyone else reproduce this?

**Comment by kingthorin** [comment]
Can this be closed?

**Comment by kingthorin** [comment]
Closing, no further feedback.
