### ISSUE TITLE
tag zap2docker-weekly image on docker hub

### ISSUE THREAD

**Issue by k3v3n** [zaproxy/zaproxy#5194]
It would be nice if you could add tag to your docker hub images. That way, we could use a specific weekly image when needed.

**Comment by kingthorin** [comment]
If you're not after the current weekly wouldn't you just use the latest stable?

**Comment by k3v3n** [comment]
@kingthorin thanks for the reply. We actually build our own ZAP image with our custom tools daily. We want to only use specific version that have tested. Also, stable release take a long time before going out and we don't want to wait for certain fixes.

**Comment by kingthorin** [comment]
@k3v3n ok I see your use case now.

**Comment by psiinon** [comment]
Makes sense - tag with the same tag we use for the weekly release in github I guess?

**Comment by psiinon** [comment]
Will tag todays release then...

**Comment by psiinon** [comment]
Done :) https://cloud.docker.com/u/owasp/repository/docker/owasp/zap2docker-weekly

**Comment by kingthorin** [comment]
Link that doesn't ask for authentication: https://hub.docker.com/r/owasp/zap2docker-weekly/tags
