### ISSUE TITLE
Bad request to API endpoint [/xml/ascan/action/scanAsUser/] from [127.0.0.1]: Does Not Exist (does_not_exist) : scanPolicyName

### ISSUE THREAD

**Issue by parag85** [zaproxy/zaproxy#5197]
**Describe the bug**
ACTIVE SCAN THE SITE - Gives error Bad request to API endpoint

I have taken webgoat app for trial. it's URL:  http://localhost:8090/webgoat/login.mvc

Session Properties:
Include in Context:  http://localhost:8090/webgoat/login.mvc

Login Form Target URL: http://localhost:8090/webgoat/login.mvc
username: webgoat
password: webgoat

Attack Mode:  http://localhost:8090/webgoat/login.mvc

Starting Point: http://localhost:8090/webgoat/login.mvc

Active scan: Default Policy

**Screenshots**

**Software versions**
 - ZAP: 2.7.0
 - OS: Ubuntu 18.04.1 LTS
 - Java: openjdk version "1.8.0_191"
 - Browser: Firefox 65

**Errors from the zap.log file**
[zap.log](https://github.com/zaproxy/zaproxy/files/2777037/zap.log)

**Comment by kingthorin** [comment]
So what was the actual API call? Because according to the error your scan policy name was invalid.

If you’re using attack mode why are you starting a scan as well?

**Comment by parag85** [comment]
I am new to ZAP - Jenkins, Without selecting 'Active Scan' - only home page scan successfully scanned. Not able to scan next sites.

Please guide....!

**Comment by psiinon** [comment]
This sounds very much like a support question than an issue with ZAP.
Please ask this on the user group: https://groups.google.com/group/zaproxy-users
