### ISSUE TITLE
passive scans for api's 

### ISSUE THREAD

**Issue by Crazyabout** [zaproxy/zaproxy#5198]
ATM you have the python script : zap-api-scan this will do a full scan on your api.

While there are 2 different python scripts for not api scans (full scan , baseline scan) there is only one possibility for the api. This can be found in the description of the Python script of the api scan (will perform a full scan). Is it possible to provide a baseline scan for api's as well ?

The main reason this feature would be a nice feature is because of this [documentation of microsoft](https://docs.microsoft.com/en-us/azure/devops/articles/security-validation-cicd-pipeline?view=vsts#application-deployment-to-dev-and-test) Where it explain why it is nice to have a baseline scan during normal working hours

**Comment by psiinon** [comment]
All this should need is a command line option that if set doesnt perform the active scan: https://github.com/zaproxy/zaproxy/blob/develop/docker/zap-api-scan.py#L420
A `-S` for safe?

**Comment by Crazyabout** [comment]
Thnx for pointing the solution out. Very usefull !!!

**Comment by thc202** [comment]
Note that was the proposed solution, it's not yet implemented.

**Comment by Crazyabout** [comment]
Is it oké that I implement this for my own. Until the team implements this ?
Just asking to make sure i don't break the 'AS-IS' rule  :D

**Comment by psiinon** [comment]
You can make the changes to this file and submit a PR - that would be even better :D

**Comment by Crazyabout** [comment]
Done
