### ISSUE TITLE
Add a new faraday zap add-on

### ISSUE THREAD

**Issue by ghost** [zaproxy/zaproxy#5205]
**Add-on repo**
https://github.com/infobyte/faraday/tree/master/plugins/repo/zap/java

**Your contact details**
devel@infobytesec.com

**Are you one of the authors**
Yes

**Licence**
If not clearly stated in the repo.

**Build instructions**
https://www.owasp.org/images/3/37/GuidelineZAPExtensionsAddOns1.0.pdf

**Link to more information**
https://www.faradaysec.com/
https://forum.faradaysec.com/

**Twitter handle for tool or author(s)**
@jliznaga, @llazzaro, @faradaysec

**Promote to Beta or Release?**
Yes

**Anything else we should know**

**Comment by thc202** [comment]
@jliznaga how are you building the add-on? Do you have an Ant build file?

**Comment by kingthorin** [comment]
The submitting user is gone, the code seems to be gone. Closing.
