### ISSUE TITLE
Zap-plugin for Jenkins  

### ISSUE THREAD

**Issue by VadimGulich** [zaproxy/zaproxy#5210]
Will be support Zap-plugin for Jenkins?
"Latest commit on 11 Jul 2017"
https://github.com/jenkinsci/zap-plugin

I'm sorry, maybe questions not related to ZAP itself

**Comment by thc202** [comment]
Yes, we'll work on it for ZAP 2.8.0 release.

**Comment by VadimGulich** [comment]
Thank you
