### ISSUE TITLE
Provide an easier way to get ZAP root cert out of a docker image

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#5214]
Proxying a local browser through ZAP running in a docker image is a good option, especially if you dont have / want java installed locally.
However you need to be able to import the ZAP root CA into your browser, and getting it out of the docker image is non trivial.
Anything that can be done to make this easier would help - please add ideas to this issue.
See this thread for background https://groups.google.com/d/msg/zaproxy-users/1dBs5fkz1AY/nVkNNuI1GgAJ

**Comment by psiinon** [comment]
One option would be to have a command line option (eg -dumprootcert filename ?) which would output the cert to the file specified which could be on a mounted directory.
Any other suggestions?

**Comment by psiinon** [comment]
Another option would be to make it possible to launch a browser from the command line using selenium that is set up to proxy through ZAP and ignore cert warnings, eg:

> ./zapLaunchBrowser.sh -proxy localhost:8080 firefox

Note that would require ZAP (or some of its jars) to be installed locally and java to be available.

**Comment by zestysoft** [comment]
Simon,

What about including a script in the docker image that could be executed externally?
I.E.
sudo docker exec -it (name of running docker instance) /zap/getCACert.py api-key

**Comment by psiinon** [comment]
This was fixed a while ago, as per described on https://www.zaproxy.org/blog/2021-02-03-run-zap-without-java-using-docker-and-webswing/
