### ISSUE TITLE
Passive (10097 - Hash Disclosure) generates false positives

### ISSUE THREAD

**Issue by clazba** [zaproxy/zaproxy#5215]
**Describe the bug**
Passive (10097 - Hash Disclosure) seems to be picking up JSESSIONID values as Low/Low alerts

**To Reproduce**
1. Enable passive scan rules for 10097 - Hash Disclosure
2. Browse site with JSESSIOID within cookie header
3. ZAP will generate low/low alerts for all JSESSIONID cookies

**Software versions**
 - ZAP: ZAP_D-2019-01-28$
Add-ons installed 
 | Passive scanner rules | 24.0.0 |
 | Passive scanner rules (alpha) | 22.0.0 | 
 | Passive scanner rules (beta) | 19.0.0 | 

 - OS: Ubuntu 18.10
 - Java: openjdk version "11.0.1" 2018-10-16

 - Browser: Firefox 65

**Comment by kingthorin** [comment]
Do you have some example values? Are you sure they aren't hashes?

**Comment by kingthorin** [comment]
> 4. See error

There's an error as well? Could you provide the text/details?

**Comment by thc202** [comment]
There's a new version of Passive scanner rules (alpha) add-on (the Hash Disclosure scanner was tweaked in the latest version, not sure it affects this issue though).

**Comment by clazba** [comment]
Some examples values - these are standard SESSIONID cookies that the pscan rules are flagging as Hash Disclosure - MD4 / MD5

JSESSIONID=28118411767C8D58C0AD50B94F327C4B
JSESSIONID=00E4C0EAA65A8573FDC85EC036C400A2

Sorry no error, that's some text left over from the issues template

**Comment by kingthorin** [comment]
What’s the app server, Tomcat?

**Comment by kingthorin** [comment]
You'd  have to research how the app server actually generates the sessionid,  I found at least one paper that said tomcat around v5 actually was using md5, and your examples do seem to be md5 hashes. You can always decide it's a false positive and mark it as such. 

The Regex for md5 is awfully specific https://github.com/zaproxy/zap-extensions/blob/94289ef6440438e98540381596b7a15f1de5cab5/src/org/zaproxy/zap/extension/pscanrulesAlpha/HashDisclosureScanner.java#L105 So if this really happens to be a false positive there isn't much we can do.

**Comment by clazba** [comment]
Sure will research the java server but this behaviour seems new - will run
some tests with the regex and confimr asap

**Comment by clazba** [comment]
Our java servers are tomcat 8 - can't find any recent article suggesting tomcat uses MD5 hashes for JSESSIONID cookie values. The few references I found are from 2005 so unsure how relevant they may be now

> The session ID is a 16 byte random number, run thorough a digest (MD5 by default), and then converted to Hex.
> [ August 01, 2005: [Message ](https://coderanch.com/t/85262/application-servers/session-IDs-generated)edited by: Ulf Dittmer ]

JSESSIONID sure look like MD5 hashes but does the regex need the case insensitive flag? 

As a test I created an MD5 hash string as a baseline
```
echo -n test123 | md5sum
cc03e747a6afbbcbf8be7668acfebee5
```
Tested both strings with the regex in the HashDisclosureScanner.java class

```
HashDisclosureScanner -> '\b[0-9a-f]{32}\b`

Flags: /gm
cc03e747a6afbbcbf8be7668acfebee5 <- match
28118411767C8D58C0AD50B94F327C4B <- no match

Flags: /gmi
cc03e747a6afbbcbf8be7668acfebee5 <- match
28118411767C8D58C0AD50B94F327C4B <- match
```
JSESSIONIDs cookie values are generally in caps while md5 hashes are not, so it seems the CASE_INSENSITIVE flag makes the regex too permissive for this specific use case.

Alternatively could amend regex to only match when string is not preceded by 'JESSIONID='

**Comment by kingthorin** [comment]
1. The hashes are just HEX representations and so can use 0-9, a-f, A-F. Though I agree most often lower case, there isn't a hard and fast standard. (Ex: Even https://en.wikipedia.org/wiki/Md5sum mixes case, because it happens IRL...)
2. The problem with trying to check for not preceded is that things can quickly become overly complex trying to get all the edge cases.

I guess I'd support removing the case sensitivity at [High threshold](https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsOptionsPscanrules):
> If you select High then fewer potential issues will be raised which may mean that some real issues are missed (false negatives)

**Comment by clazba** [comment]
Re #2 - is a case of how likely rule is to match JSESSIONID vs actual password MD5 hashes. Former much more likely than the latter. IMO JSESSIONID warrants its own exemption because of this.
> I guess I'd support removing the case sensitivity at [High threshold]
Agreed, that would be sensible although potentially complementary to JSESSIONID exemption

**Comment by thc202** [comment]
How about changing the name (to Potential Hash Disclosure) and/or risk (to Informative) for the MD5 hashes?

**Comment by clazba** [comment]
Name change is a good idea but risk should reflect actual risk of MD5 password hashes TPs - I feel Info is not reflective of that.
Point being JSESSIONID should not be seen as edge case if represents the vast majority of findings (found over 500 in my last scan)
Agree with @kingthorin it is difficult to get all edge cases but common FPs should be addressed or risk diluting value of ruleset.  Can work on PR if in agreement

**Comment by kingthorin** [comment]
@clazba are you happy with how this pans out? https://www.regexplanet.com/share/index.html?share=yyyyu0ua0ar
(Click java, then test)

**Comment by kingthorin** [comment]
@thc202 @psiinon you ok with that solution (Regex planet details above).

**Comment by clazba** [comment]
@kingthorin yes happy, latest regex no longer generated FPs

**Comment by kingthorin** [comment]
Addressed in https://github.com/zaproxy/zap-extensions/pull/1969#event-2235536205
