### ISSUE TITLE
ZAP Fuzzing

### ISSUE THREAD

**Issue by WeiserAriel** [zaproxy/zaproxy#5218]
Hey All,

I am trying to build an automated fuzzing tool in Python for a web application. before i start implemented everything from scratch I wanted to know if there is anything which can be useful for me. the functionality should be really simple:

1. start Ajax Spider
2. fuzz all URL's ( headers / GET & post params )
3. search for 500 Error codes in responses.

Is there any tool inside ZAP which can help me? 
I know that ZAP has nice fuzzer but I was able to run it only in UI mode.

any help will be appreciated !

**Comment by kingthorin** [comment]
Numbers 1 and 3 are easily accomlished via the web API and scripts, however, #2 isnt as the fuzzer doesnt ydt have a web API (https://github.com/zaproxy/zaproxy/issues/1689). 

For future reference he ZAP User Group https://groups.google.com/group/zaproxy-users and Developer Group https://groups.google.com/group/zaproxy-develop are much better places for questions.
