### ISSUE TITLE
Missing parts on Transfer-Encoding: chunked request

### ISSUE THREAD

**Issue by sabatmonk** [zaproxy/zaproxy#5223]
**Describe the bug**
When sending a POST request with Transfer-Encoding: chunked, i'm missing the last section of the body, making the request invalid.

**To Reproduce**
Send a POST request with a json body and the Transfer-Encoding: chunked header. 
For my tests, i used this payload (it is an assignation to a blob storage) 
```
Transfer-Encoding: chunked
Content-Type: application/json; charset=utf-8

{
"FileName":"TestIcon0.svg","Payload":"data:image/svg+xml;base64,aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaccccccccccccccdddd="
}
```

**Expected behavior**
The request should be whole, whether the Transfer-Encoding: chunked header is present or not. 

**Actual behavior**
If i remove the header, the whole request is there, if not, ZAP only see 
```
{
"FileName":"TestIcon0.svg","Payload":"data:image/svg+xml;base64,aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaccccccccccccccddd
```
If i send the request directly to the server, or through fiddler, it works, so i know the request is not the issue.

**Software versions**
 - ZAP: 2.7 and ZAP_WEEKLY_D-2019-02-04
 - OS: Windows server 2016
 - Java: Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
 - Request sent from postman

**Comment by kingthorin** [comment]
In `Options:Local Proxies` is "Remove Unsupported Encodings" on or off?

**Comment by sabatmonk** [comment]
Tried with both, no impact

**Comment by sabatmonk** [comment]
Is there any information i can provide to help on this?

**Comment by thc202** [comment]
The information provided so far is enough, thank you.

**Comment by endlessoblivion** [comment]
For me, in case of chunked encoding, it drops the whole POST body, since it's short:
```
19
{"userId":"","target":""}
0

```
Instead, the ProxyThread is trying to parse it as a header:
```
[ZAP-ProxyThread-1] WARN org.parosproxy.paros.core.proxy.ProxyThread  - Malformed Header: 
org.parosproxy.paros.network.HttpMalformedHeaderException
	at org.parosproxy.paros.network.HttpHeader.setMessage(HttpHeader.java:192)
	at org.parosproxy.paros.network.HttpRequestHeader.setMessage(HttpRequestHeader.java:281)
	at org.parosproxy.paros.network.HttpRequestHeader.<init>(HttpRequestHeader.java:168)
	at org.parosproxy.paros.network.HttpInputStream.readRequestHeader(HttpInputStream.java:68)
	at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(ProxyThread.java:486)
	at org.parosproxy.paros.core.proxy.ProxyThread.run(ProxyThread.java:335)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by thc202** [comment]
This will be addressed with the Network add-on (which will supersede the core proxy).

**Comment by thc202** [comment]
Closing, with the merge of #7080 ZAP should start to use the Network add-on to proxy.
