### ISSUE TITLE
Running zap for juice-shop

### ISSUE THREAD

**Issue by A1vinSmith** [zaproxy/zaproxy#5224]
![screen shot 2019-02-14 at 2 24 12 pm](https://user-images.githubusercontent.com/24937594/52755941-93708b00-3064-11e9-8b7a-01eb574e6b9b.png)

Running juice-shop locally by npm start.
Using Firefox and FoxyProxy (also settled the firefox Network proxy).
Green one is working for Owasp only.
Blue and Red are working for Burp Suite only.

Zap 2.7.0 Burp Suite Community 1.7.35

Is the difference between them caused?

**Comment by kingthorin** [comment]
What?

**Comment by A1vinSmith** [comment]
Sorry, I didn't make it clear. 
I just mean Zap couldn't using the Firefox internal proxy.
I have to use the extension like FoxyProxy to make Zap working.

**Comment by psiinon** [comment]
Can you share a screenshot of the proxy settings you tried?
Did you remove 'localhost and '127.0.0.1' from the 'No proxy for' section?
It should work fine.

**Comment by A1vinSmith** [comment]
Yes, I removed everything from 'No proxy for'. I'll share the screenshot tomorrow.

**Comment by kingthorin** [comment]
Seems more like a Firefox/FoxyProxy issue than a ZAP issue.

**Comment by A1vinSmith** [comment]
I changed Firefox HTTP Proxy to localhost replace of 127.0.0.1. It working now.
![screen shot 2019-02-15 at 8 20 36 am](https://user-images.githubusercontent.com/24937594/52811771-c7968b00-30fa-11e9-8670-3069eeaaec5e.png)

**Comment by kingthorin** [comment]
Thanks for letting us know.

**Comment by A1vinSmith** [comment]
I'd love to. But the thing here is 127.0.0.1 should be worked, isn't it?

**Comment by kingthorin** [comment]
You'd have to follow-up with FoxyProxy or Mozilla. 
Or perhaps Microsoft or whoever your OS vendor is. 
Or maybe even your AV/Internet Security provider vendor.
