### ISSUE TITLE
schedule or queue active scan

### ISSUE THREAD

**Issue by PiotrIr** [zaproxy/zaproxy#5226]
Hi,
I'm trying to find the way to schedule or queue active scan in OWASP ZAP UI. I have 19 different application with different URLs to scan and doing this one by one is very painful. I would like to scan them one by one over weekend but unfortunately not able to find this option in UI. I've tried to use Contexts, but when I run it, it just does something very quickly and finishes - perhaps I missed some settings but the same scan on single website works well.
Could you advise please?

**Comment by psiinon** [comment]
I'm afraid we dont currently support this option.
We have had plans for implementing ZAP as a Service for some time but we dont have enough people to work on it right now :/
You can of course use external tools to do this.
For example you can just write a script which calls one of the packaged scans: https://github.com/zaproxy/zaproxy/wiki/Packaged-Scans and then just schedule that using cron or similar.
Thats essentially what we do here at Mozilla - we perform a baseline scan of 100s of urls every day :)

**Comment by PiotrIr** [comment]
Simon,
Thank you fro your quick reply. I just wander, is it possible to include some Add-ons when using the script? I'm thinking about "Active scanner rules (beta)" and "Advanced SQLInjection Scanner"?

**Comment by psiinon** [comment]
Yes, just use the `-addoninstallall` option as per https://github.com/zaproxy/zap-core-help/wiki/HelpCmdline
You can install as many add-ons as you like that way :)

**Comment by PiotrIr** [comment]
Simon, thank you for your help, much appreciate. Have a good weekend.
