### ISSUE TITLE
Whad add-ons for active scan

### ISSUE THREAD

**Issue by PiotrIr** [zaproxy/zaproxy#5227]
I'm looking for advise what add-ons should I use. I'm not a developer but network engineer which needs to scan 19 applications in our network to make sure they are as much secured as possible. All applications are installed by third party supports so probably would be difficult to find help from them.
I was thinking about adding Active scanner rules (beta)" and "Advanced SQLInjection Scanner", does it make sense? Should I remove them or add another ones?
I've compared results from build in add-ons to tenable scanner and some things are missed so believe need to reconfigure something.
Could you advise please?

**Comment by psiinon** [comment]
Please ask this on the ZAP User Group: https://groups.google.com/group/zaproxy-users
We try to keep the issues for bugs and enhancement requests.

**Comment by kingthorin** [comment]
Please don't ask questions as issues - the ZAP User Group https://groups.google.com/group/zaproxy-users and Developer Group https://groups.google.com/group/zaproxy-develop are much better places for questions.
Also note Nessus and ZAP target different purposes in vulnerability assessment, so yes they’re going to produce different results.

**Comment by PiotrIr** [comment]
Thank you for advise and I'm sorry I've posted the question here.

**Comment by psiinon** [comment]
Np :)
