### ISSUE TITLE
Remove Filter extension

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#5244]
Tracker issue for removal of Filter extension.

The filter functionality is deprecated since 2.4.0 (superseded by Replacer add-on and scripting) and will be disabled in 2.8.0.

Setting to 2.9.0, if no one opposes by then.

**Comment by kingthorin** [comment]
Sounds good to me.

**Comment by psiinon** [comment]
https://twitter.com/psiinon/status/1103935047852150791

**Comment by psiinon** [comment]
and emailed dev + user groups :)

**Comment by kwwall** [comment]
Is there anything in marketplace for ZAP add-ons that rely on Filters? If so and those add-ons have been abandoned but are still being used, that may be a reason to defer this decision a bit longer.

**Comment by psiinon** [comment]
No there isnt. If there was we could still change them to use one of the alternative options.
Filters are relic from Paros days that we've never really used in the ZAP code base.

**Comment by thc202** [comment]
Removed references from the wiki: https://github.com/zaproxy/zaproxy/wiki/_compare/fd5fb82^...fd5fb82
