### ISSUE TITLE
OWASP ZAP

### ISSUE THREAD

**Issue by Asim-Crestech** [zaproxy/zaproxy#5248]
How can we do advance vulnerability scanning of already recorded scan in ZAP tool

**Comment by kingthorin** [comment]
Please don't ask questions as issues - the ZAP User Group https://groups.google.com/group/zaproxy-users and Developer Group https://groups.google.com/group/zaproxy-develop are much better places for questions.

**Comment by Asim-Crestech** [comment]
Not able to write question in that group that is why asking here only.
How can we do advance vulnerability scanning of already manually recorded scan in ZAP tool

**Comment by kingthorin** [comment]
https://m.wikihow.com/Join-Google-Groups
