### ISSUE TITLE
OpenAPI Support fails when importing arrays with primitives as payload

### ISSUE THREAD

**Issue by markuskiss** [zaproxy/zaproxy#5250]
When importing the OpenAPI definition of our system under test, we notice an error in ZAproxy: As we have a REST endpoint with a POST Payload that is an array of primitive integer values, ZAproxy fails importing it because it always expects that arrays have objects instead of primitive values. 

The exception stacktrace:

`
2019-03-12 14:07:25,175 [ZAP-Import-OpenAPI-3] WARN  ExtensionOpenApi - io.swagger.models.properties.LongProperty cannot be cast to io.swagger.models.properties.RefProperty
java.lang.ClassCastException: io.swagger.models.properties.LongProperty cannot be cast to io.swagger.models.properties.RefProperty
        at org.zaproxy.zap.extension.openapi.converter.swagger.RequestModelConverter.generateBody(RequestModelConverter.java:79)
        at org.zaproxy.zap.extension.openapi.converter.swagger.RequestModelConverter.convert(RequestModelConverter.java:49)
        at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.convertToRequest(SwaggerConverter.java:83)
        at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.getRequestModels(SwaggerConverter.java:77)
        at org.zaproxy.zap.extension.openapi.ExtensionOpenApi$3.run(ExtensionOpenApi.java:218)
`

**Software versions**
 - ZAP: 2.7.0
 - Add-on: OpenAPI Support 12.0.0
 - OS: macOS Mojave
 - Java: Latest JDK 8

**Comment by psiinon** [comment]
Thanks for reporting this.
Hopefully shouldnt be too difficult to fix so have flagged with the appropriate labels.
For info the code is here: https://github.com/zaproxy/zap-extensions/tree/alpha/src/org/zaproxy/zap/extension/openapi

**Comment by marimeireles** [comment]
Hey @psiinon can I take this one?

**Comment by psiinon** [comment]
@marimeireles definitely :) I've just sent you an invite to the project - if you accept that I can assign this issue to you

**Comment by psiinon** [comment]
Assigned :)

**Comment by marimeireles** [comment]
Thanks @psiinon, I'll let you know if I get stuck with something!
I'm still downloading the repos, my internet connection is specially bad today.

I think this problem is pretty straightforward, I just need to find the code that fetches the user data and change it to convert an array of `int` to an array of `Integer`, right?

**Comment by psiinon** [comment]
Yeah, that sounds like a good plan.
It would be worth creating a simple test case early on - ie an OpenAPI definition which includes an array of integers that ZAP fails on, as above. Then you'll be able to test any changes you make easily.
You can also include your test cases in the unit tests so we never regress :)
Let us know if you have problems building ZAP or the add-ons - our docs could def be better :/

**Comment by lucianot54** [comment]
I have the same problem with string format.

> 2019-04-18 11:33:42,652 [ZAP-Import-OpenAPI-1] WARN  ExtensionOpenApi -
> io.swagger.models.properties.StringProperty cannot be cast to io.swagger.models.properties.RefProperty
> java.lang.ClassCastException: io.swagger.models.properties.StringProperty cannot be cast to io.swagger.models.properties.RefProperty
> 	at org.zaproxy.zap.extension.openapi.converter.swagger.RequestModelConverter.generateBody(RequestModelConverter.java:79)
> 	at org.zaproxy.zap.extension.openapi.converter.swagger.RequestModelConverter.convert(RequestModelConverter.java:49)
> 	at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.convertToRequest(SwaggerConverter.java:83)
> 	at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.getRequestModels(SwaggerConverter.java:77)
> 	at org.zaproxy.zap.extension.openapi.ExtensionOpenApi$3.run(ExtensionOpenApi.java:218)

This example fail :
```
{
  "swagger": "2.0",
  "host": "test.com",
  "basePath": "/api",
  "paths": {
    "/v1/test": {
      "post": {
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "body",
            "required": true,
            "schema": { "type": "array", "items": { "type": "string" } }
          }
        ]
      }
    }
  },
  "definitions": {}
}
```
I updated the json like that and now it works
```
{
 {
  "swagger": "2.0",
  "host": "test.com",
  "basePath": "/api",
  "paths": {
    "/v1/test": {
      "post": {
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "body",
            "required": true,
            "schema": { "$ref": "#/definitions/ArrayStringObject" }
          }
        ]
      }
    }
  },
  "definitions": {
    "ArrayStringObject": {
      "type": "array",
      "items": { "type": "string" }
    }
  }
}
```
I created a quick script to update my json file but it's just a quickfix to explain how I can solve this bug now. I can extend the script to support all primitives. The best solution is bugfix when you have arrays with primitives.
```
cp api-docs.json api-docs-zap.json
sed -i'' -e 's/{"type":"array","items":{"type":"string"}}/{"$ref":"#\/definitions\/ArrayStringObject"}/g' api-docs-zap.json
sed -i'' -e 's/"definitions":{/"definitions":{"StringObject":{"type":"array","items":{"type":"string"}},/g' api-docs-zap.json
```

**Comment by psiinon** [comment]
@marimeireles - are you still looking at this? Anything you need help with?

**Comment by marimeireles** [comment]
Hi @psiinon, I'm sorry for taking so long to answer it! :(
I'm moving to Germany and my life is kind of messy right now. I'm stuck with this because I don't know Java! And I'm insecure about continuing it, if someone else wants to take this bug, please feel free to.
If nobody takes it maybe I can try to fix it in the future when I'm more available to learn how to play with Java.
Thanks Simon!

**Comment by kingthorin** [comment]
@marimeireles thanks for letting us know, we understand how life gets busy.

**Comment by markuskiss** [comment]
Hi @psiinon, @kingthorin and @marimeireles, if you don't mind, I'll try to fix it by myself. Feel free to assign the issue to me. I've already forked the zap-extensions project and will contribute the fix via pull request.

**Comment by thc202** [comment]
You need to accept the invite before we can assign the issue.
