### ISSUE TITLE
GUI hang (and NPE exceptions) when using Context Alert Filters

### ISSUE THREAD

**Issue by chozzz** [zaproxy/zaproxy#5259]
**Describe the bug**

ZAP UI & API freezes when running automated active scan. Suspect is `alertFilters` addon based on log.

My command to start ZAP UI:
```
java -XX:MetaspaceSize=128M -XX:MaxMetaspaceSize=256M  \
-jar /home/user1/ZAP_2.7.0/zap.7.0.jar \
-port 8081 \
-dir /home/user1/.ZAP \
-installdir /home/user1/ZAP_2.7.0 \
-config api.disablekey=true \
-config dirs=/var/www/myproject/nodirectaccess/cron/ProcessorServer/zap/scripts \
-config scanner.hostPerScan=2 \
-config scanner.threadPerHost=15 \
-config scanner.delayInMs=0 \
-config scanner.injectable=3 \
-config scanner.enabledRPC=63 \
-config scanner.scanHeadersAllRequests=false
```

First error in the logs (Full error is down below);

```
30264 [ZAP-PassiveScanner] ERROR org.zaproxy.zap.extension.alertFilters.ExtensionAlertFilters  - java.lang.NullPointerException
```

**To Reproduce**
Steps to reproduce the behavior (At least, this is how my automated flow works):
1.  Start ZAP UI (v2.7.0 with the command provided above)
2.  Run `core.deleteAllAlerts()`, `ascan.stopAllScans()` and `ascan.removeAllScans()`,
3.  Enable custom zest scripts,
4.  Run `core.newSession()`,
5.  Import ZAP contex.
6.  Run automated passive and active scans.

**Expected behavior**
ZAP UI doesn't freeze

**Screenshots**

**Software versions**
 - ZAP: 2.7.0
 - Add-on: [id=alertFilters, version=7.0.0]
 - OS: Ubuntu 18.04
 - Java: 
```
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
```
 - Browser: -

**Errors from the zap.log file**
https://pastebin.com/iYeMu0ps

Please shout how I can provide more details to reproduce this.

** Additional Info **

My context file - https://pastebin.com/2Dehw9vv
Thread dump output - https://pastebin.com/Wv0um8G8

**Comment by kingthorin** [comment]
_n_. You're probably best off getting things working in the GUI before you proceed with automation.

0. Is there a particular reason you're setting MetaspaceSize
1. Step 4 is newSession, why bother with step 2?
2. For step 6 you'll have to be more specific.

It seems like you can't get to whatever your target is:
> 2019-03-16 00:36:25,728 [ZAP-ProxyThread-1] WARN  ProxyThread - Socket timeout while reading first message.
...
> 2019-03-16 00:37:14,361 [ZAP-ProxyThread-51] WARN  ProxyThread - Failed to write/forward the HTTP response to the client: java.net.SocketException: Broken pipe (Write failed)

It seems like you have problems with your step 6:
> 2019-03-16 00:36:49,976 [ZAP-ProxyThread-34] WARN  API - Bad request to API endpoint [/JSON/ascan/action/scan/] from [127.0.0.1]:
> URL Not Found in the Scan Tree (url_not_found)

**Comment by chozzz** [comment]
@kingthorin Thanks for the quick response.

0. It's a resource limitation for running ZAP daemon in AWS - In there, I run ZAP in daemon mode, and I am just matching the commands to run this locally - if I remove them, it still happens in my local
1.  You're right, it's multi-devs issue doing in one same file, but I've refactored my flow to just start newSession instead
2.  The automation process is based on a list of JSON files which each of them containing a url and parameter, then to be;
    1.  Run in passive scan (e.g. curl via ZAP proxy),
    2.  Then, run it in active scan via '/JSON/ascan/action/scan/'

For some reason, this happens like 3 out of 5 times with the same flow above. Still not sure why, but if you think it's not related to this issue, then i'll dig more into it and raise a separate issue.

> 2019-03-16 00:36:49,976 [ZAP-ProxyThread-34] WARN API - Bad request to API endpoint [/JSON/ascan/action/scan/] from [127.0.0.1]:
> URL Not Found in the Scan Tree (url_not_found)

Please shout if I can provide more details.

**Comment by kingthorin** [comment]
You could test if it's a timing issue, just put some waits or sleeps in. It "shouldn't" be, but without experiencing it or a ton more details worth a try...

**Comment by chozzz** [comment]
@kingthorin I've added 5 to 30 secs delay to each passive scanning and the issue still exists. I've updated my post above and provided the thread dump if it might help.

**Comment by thc202** [comment]
@chozzz are you still interested in fixing this issue?

**Comment by chozzz** [comment]
@thc202 sure, i'd like to give this a shot if its not taken by anyone yet..

**Comment by thc202** [comment]
I'm not aware of anyone working on this.
