### ISSUE TITLE
Ability to filter what requests the Active Scans run against

### ISSUE THREAD

**Issue by rezen** [zaproxy/zaproxy#5278]
Currently, Active Scans run against an entire node or tree (methinks?) and tailoring an Active Scan against a subset of urls or request types is not something you can really do. What would be super awesome would be to limit the Active Scan to only scan requests with specific Tags.

For example, say there was *FeatureX* in an app which exercised a few distinct endpoints (`/user/1/profile` & `/profile`) and I wanted to only scan those  endpoints there is no easy way to do that. With tagged Active Scanning, I could simply add a tag *FeatureX* to those routes and have the Active Scan only attack routes with that tag. 

What this allows users to do is have a custom scan profile for that feature which was tailored for the specific tech of that feature. Say *FeatureX* didn't interact with a database, I could disable scanners that try testing for SQLi.

Another option for using tag filtering in Active Scans is for omitting content. If you wanted to scan everything that didn't have a JSON response, you could configure the tag *JSON* to be excluded from the scan.

**Comment by rezen** [comment]
I was looking in `src/org/zaproxy/zap/extension/ascan/` and felt like `AttackModeScanner.java@run` was the place to look? I'm assuming somewhere there is a place where a `HttpMessage msg` can be checked for x-tags before processing - maybe in `notifyNewMessage(HttpMessage msg)`?

**Comment by thc202** [comment]
That class (`AttackModeScanner`) would be for the attack mode, which runs as soon as the message is available, so those messages will not have been (auto/manually) tagged beforehand. The tags are accessible through the corresponding `HistoryReference` of the `HttpMessage`.
The method `notifyNewMessage(HttpMessage)` is used to notify of new messages created/sent by the scan.

For normal scans the method to check for the tags (which might already been set) would be `HostProcess#canScanNode`.

**Comment by preetkaran20** [comment]
Hi @thc202 

thanks for clarifying. when i tried to add tags to the successful URLs under spider tab, i am able to add the tags. 

> 1. It can be other requests too (e.g. proxied) but that's the idea. Probably better to add the filter functionality in a new tab.

![image](https://user-images.githubusercontent.com/13570884/64881257-ec92b280-d677-11e9-89d8-4650418f84b0.png)

something like a new tab for filtering on the basis of tags in active scan window ?So my understanding from discussion is  ``` User will tag urls proxied from anywhere like under sites, history or spider tab and when they try to run active scan there is a new tab  in active scan window where they can choose tags to run or specify tags to include in active scan or ignore tags from scanning. ```
is my understanding correct.
 
> 
> There's a proposal to add other/generic scan filters, this issue and that should be integrated... @psiinon can you chime in?
Is there anyone working on it ? can you please let me know the issue so that i can have a look.

thanks,
Karan

**Comment by thc202** [comment]
Right, that's correct.

I don't know if @psiinon is already working on that. There's no issue raised yet.
That should not prevent you from working on this issue though, just mentioned that because it overlaps (some part at least).

**Comment by preetkaran20** [comment]
Hi @thc202 ,

I was looking in the code, I am not sure about the GUI part but i have done some changes in backend so approach is :- 
I will create a new Panel say ``` FilterScanPanel ``` which will extend CustomScanPanel and the method getContextSpecificObjects will return the information of the Included or excluded tags.
Now When ActiveScanController will set the tag information into the Active Scan which is extending Scanner and Inside HostProcess Hook ``` canScanNode ``` we will call a method called ```isTagInScope``` of scanner which will check and return boolean as per condition.

class diagram depicting the same :- 
![image](https://user-images.githubusercontent.com/13570884/64920810-3646de80-d7d9-11e9-92fb-4420d27bae91.png)

please let me know if concerns about the approach.Also please let me know the UI look and feel so that i can start looking into it.

thanks,
Karan

**Comment by rezen** [comment]
Reading and thinking more about this, I wonder if instead of being able to run an ActiveScan against tags maybe it should be more generalized and instead have ActiveScan run against a filter similar to the History tab filter.

**Comment by psiinon** [comment]
OK, at one stage I was thinking of adding a 'scanFilter' script type - this could determine which nodes (urls) would be targeted when spidering, active scanning etc.
Then @kingthorin pointed out that a HttpSender script would probably work :)
So what we could do is to see if you can use an HttpSender script to essentially filter which urls are scanned. If so then we could publish that as an example - we could probably even implement one that would work on tags!
I like the idea of a script more than a dialog as its infinitely flexible.
@preetkaran20 do you trying this out?
I'm guessing the HttpSender script would need to fake some sort of error code for any urls that are out of the required scope, eg as per https://github.com/zaproxy/community-scripts/blob/master/proxy/Drop%20requests%20not%20in%20scope.js

**Comment by thc202** [comment]
@preetkaran20 I was thinking on something more generic, for example:
```Java
interface ScanFilter {
    boolean isFiltered(StructuralNode node);
}
```
to accommodate other/all use cases. The new panel would create a `ScanFilter` which would be added to the `Scanner`.
You don't need to extend `CustomScanPanel` (that's for add-ons), you can add the panel directly to the dialogue (like tech panel is).

@rezen sounds good.

@psiinon returning different values/responses might mislead the scan rules. It would be better if they were not scanned at all (which needs to happen before the HTTP Sender listeners are involved). I prefer a new script type, it's clearer/cleaner.

**Comment by thc202** [comment]
Tweaked the title to not refer just to tags.

**Comment by preetkaran20** [comment]
> @preetkaran20 I was thinking on something more generic, for example:
> 
> ```java
> interface ScanFilter {
>     boolean isFiltered(StructuralNode node);
> }
> ```
> 
> to accommodate other/all use cases. The new panel would create a `ScanFilter` which would be added to the `Scanner`.

hmm, yeah you are right, 
So i think of 2 approaches,
```1.  An implementation of this filter(by anyone like ascancontroller or spider or any other scanner) and the scanner will call the isFiltered method but issue is adding new filter requires modifying that existing filter.
2. Creating something like a chain of filters or say list of filter objects are provided to the scanner and scanner will call all of them so that adding a filter doesn't require modifying existing filters code and also one filter can be plug and played at many other places.
```
So Approach is Scanner will be generically written and has a scanfilter Interface hook as you mentioned.
Questions:-
``` 1. What kind of filters we are planning to add in the start ?
2. Are we looking for UI extensively, like Some kind of a Framework where adding new Filters is much easier for future enhancement or we can leverage the existing History Panel Dialog UI and extend as per our requirement.
```

**Comment by preetkaran20** [comment]
Hi @kingthorin , @thc202 ,

please help on the above queries.

thanks,
Karan

**Comment by kingthorin** [comment]
1. Don't over think it, a few options are all that's needed to start. Status code, seems like an obvious option.
2. Yes. I'd suggest looking at the existing scan progress/status code. 
3. IMHO the user should be able to check any characteristic of the base message and indicate that the message be filtered, the point of using scripts is that they'd provide ultimate flexability/specificity.
4. I think with some preset options, like status code, etc and a scripted option that provides good coverage for user needs. (I don't think a 3rd interface or option is necessary ... If I'm understanding this question properly.)

**Comment by preetkaran20** [comment]
> 1. Don't over think it, a few options are all that's needed to start. Status code, seems like an obvious option.
yes, i have added URL pattern based, tag based and Status Code based filters.
> 2. Yes. I'd suggest looking at the existing scan progress/status code.
ok. will look into it.
> 3. IMHO the user should be able to check any characteristic of the base message and indicate that the message be filtered, the point of using scripts is that they'd provide ultimate flexability/specificity.
yes yes, I am not sure how to add hook for scripts, can you please give some code reference or document describing same.
> 4. I think with some preset options, like status code, etc and a scripted option that provides good coverage for user needs. (I don't think a 3rd interface or option is necessary ... If I'm understanding this question properly.)
yes yes. thanks for the reply.

**Comment by kingthorin** [comment]
3. I’m working from my phone so digging up what you need isn’t the easiest, here are the general locations:
- https://github.com/zaproxy/zaproxy/tree/develop/zap/src/main/java/org/zaproxy/zap/extension/script
- https://github.com/zaproxy/zaproxy/blob/develop/zap/src/main/java/org/zaproxy/zap/extension/ascan/ActiveScript.java
- https://github.com/zaproxy/zaproxy/blob/develop/zap/src/main/java/org/zaproxy/zap/extension/ascan/ActiveScript2.java
- https://github.com/zaproxy/zap-extensions/tree/master/addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts

**Comment by preetkaran20** [comment]
> 1. I’m working from my cell phone so digging up what you need isn’t the easiest, here are the general locations:
> 
> * https://github.com/zaproxy/zaproxy/tree/develop/zap/src/main/java/org/zaproxy/zap/extension/script
> * https://github.com/zaproxy/zaproxy/blob/develop/zap/src/main/java/org/zaproxy/zap/extension/ascan/ActiveScript.java
> * https://github.com/zaproxy/zaproxy/blob/develop/zap/src/main/java/org/zaproxy/zap/extension/ascan/ActiveScript2.java
> * https://github.com/zaproxy/zap-extensions/tree/master/addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts

Thanks alot @kingthorin, i will dig into the links provided.

**Comment by kingthorin** [comment]
One more: https://github.com/zaproxy/zaproxy/tree/060da6d88991d7f9f94fd9932885a3810983a47a/zap/src/main/dist/scripts/templates

**Comment by thc202** [comment]
https://github.com/zaproxy/zaproxy/issues/5278#issuecomment-533154644

> 1. What kind of filters we are planning to add in the start ?

None? I'd prefer if the first PR focused on doing the underlying changes to the active scan to support filtering than add any filter implementation, while that seems useless it would already allow to programmatically start active scans with custom filters (say from a stand alone script). IMO incremental changes are better than trying to add everything/all in the same PR.

> 2. Do we need to indicate User why following request is filtered?

That's a good point, probably worth it, that's done in other places (e.g. spiders) when something is filtered/excluded.
I'd suggest calling it `FilterResult`, it's more meaningful. (We should avoid using the term "bean", that has a specific meaning/behaviour which is not needed/wanted here.)

> 3.

This can/should be added in a follow up PR, especially if we want that to apply to different scans (not just active).


https://github.com/zaproxy/zaproxy/issues/5278#issuecomment-533870740
> Yes. I'd suggest looking at the existing scan progress/status code.

How/where is that information going to be shown? We should discuss that first.

**Comment by preetkaran20** [comment]
Hi @thc202 ,

Got your point. 

In my first PR i will add the placeholders for Filters in the Scanner. As mentioned in my above [Comment](https://github.com/zaproxy/zaproxy/issues/5278#issuecomment-533154644) , i am thinking of adding list of Filters into the Scanner and same is depicted in the class diagram.

please look at the high level picture so that i can add the final code changes into the PR.

As suggested will add  ``` FilterResult ``` to the ScanFilter interface. 

thanks,
Karan

**Comment by preetkaran20** [comment]
Added UI changes in PR :- https://github.com/zaproxy/zaproxy/pull/5652.
Complete Testing of FilterPanel is Left. Will do that once the UI is approved.

**Comment by preetkaran20** [comment]
Added Filter Panel related changes in PR :- https://github.com/zaproxy/zaproxy/pull/5693/files

**Comment by preetkaran20** [comment]
New Screens :- 
![image](https://user-images.githubusercontent.com/13570884/69009636-474cd100-097d-11ea-8f23-aa4ae377cbb7.png)

![image](https://user-images.githubusercontent.com/13570884/69009643-5af83780-097d-11ea-9853-ff06cec55e1f.png)

**Comment by thc202** [comment]
Closing, all done. Thanks @preetkaran20!
