### ISSUE TITLE
"Saving session file." prompt remains when opening Zap

### ISSUE THREAD

**Issue by zestysoft** [zaproxy/zaproxy#5279]
**Describe the bug**
The "Saving session file. Please wait ..." prompt doesn't go away when starting Zap.

**To Reproduce**
1. Open Zap.
2. Choose to start a session with a name
3. Choose "DeleteMe"
4. Choose to overwrite.
5. Saving session file message never goes away.

**Expected behavior**
Message about the session goes away.

**Screenshots**
![Screenshot from 2019-03-22 11-20-17](https://user-images.githubusercontent.com/742554/54844736-cfff5a00-4c94-11e9-8eda-64b11b093c20.png)

**Software versions**
 - ZAP: Weekly in both 3-11 and 3-18
 - OS: Ubuntu 18.04 LTS
 - Java: 1.8.0_201

**Additional context**
This started happening when I unchecked the "Recovery Log" options under Options, Database. I seem to be able to use the program just fine as long as I move that dialog box out of the way.  I am unable to close it.

**Comment by thc202** [comment]
Is it happening always? Could you provide a thread dump? (`kill -3 <zap-pid>`)

**Comment by zestysoft** [comment]
On that day, I got it to happen twice, but I haven't been able to reproduce it since.  If it's okay, please keep this open a bit longer and I'll provide more details if I can get it to happen again.  One thing -- I've ran into weird race conditions with the Sopho's AV and apt in the past.  I imagine it's possible Sopho's could be the cause of this issue too.

**Comment by thc202** [comment]
OK.

**Comment by zestysoft** [comment]
I am unable to reproduce.  I'm going to assume it was a system issue on my end.

**Comment by thc202** [comment]
Let us know if it happens again, thank you.
