### ISSUE TITLE
When fuzzing, regex Tag Creator is matching the header only

### ISSUE THREAD

**Issue by ostracize** [zaproxy/zaproxy#5287]
I am experiencing the issue with at least w2019-03-18

Steps to reproduce:

1. Use fuzzing and select a payload that you know will produce a match
2. Under "Message Processors" -> "Add..."
3. Type: "Tag creator"
4a. Match: Regex == something in the response body (eg. Success). Set a tag.
4b. Match: Regex == something the response header( eg. nginx). Set a tag.

Expected behavior: Regex will match a string in the header or in the body. (4a or 4b)
Actual behavior: Response does not match any string in the body (4b only)

**Comment by kingthorin** [comment]
It works for me. What version of the fuzzer are you running? (https://github.com/zaproxy/zaproxy/wiki/FAQAddonVersions)

Are you 100% sure your regex is correct?

**Comment by ostracize** [comment]
Here's my support info output:
```
OWASP ZAP
Version: D-2019-03-18
---
Installed Add-ons: [[id=accessControl, version=6.0.0],
[id=alertFilters, version=8.0.0], [id=ascanrules,
version=33.0.0], [id=ascanrulesBeta, version=25.0.0],
[id=bruteforce, version=8.0.0], [id=coreLang,
version=14.0.0], [id=cspscanner, version=7.0.0], [id=diff,
version=9.0.0], [id=directorylistv1, version=4.0.0],
[id=formhandler, version=3.0.0], [id=fuzz, version=11.0.0],
[id=fuzzdb, version=4.0.0], [id=gettingStarted,
version=10.0.0], [id=help, version=9.0.0], [id=hud,
version=0.4.0], [id=importurls, version=6.0.0], [id=invoke,
version=10.0.0], [id=jxbrowser, version=13.0.0],
[id=jxbrowserlinux64, version=11.0.0], [id=jxbrowsermacos,
version=11.0.0], [id=jxbrowserwindows, version=11.0.0],
[id=jxbrowserwindows64, version=4.0.0], [id=onlineMenu,
version=7.0.0], [id=openapi, version=13.0.0], [id=plugnhack,
version=12.0.0], [id=portscan, version=9.0.0],
[id=pscanrules, version=24.0.0], [id=pscanrulesBeta,
version=19.0.0], [id=quickstart, version=26.0.0],
[id=replacer, version=8.0.0], [id=reveal, version=3.0.0],
[id=saverawmessage, version=5.0.0], [id=savexmlmessage,
version=0.1.0], [id=scripts, version=25.0.0], [id=selenium,
version=15.0.0], [id=sequence, version=6.0.0], [id=soap,
version=4.0.0], [id=spiderAjax, version=23.0.0], [id=tips,
version=6.0.0], [id=webdriverlinux, version=8.0.0],
[id=webdrivermacos, version=8.0.0], [id=webdriverwindows,
version=8.0.0], [id=websocket, version=19.0.0], [id=zest,
version=29.0.0]]
---
Operating System: Linux
Java Version: Oracle Corporation 1.8.0_191
System's Locale: en_US
Display Locale: en_GB
Format Locale: en_US
ZAP Home Directory: /home/zap/.ZAP_D/
ZAP Installation Directory: /zap/./
Look and Feel: Nimbus (javax.swing.plaf.nimbus.NimbusLookAndFeel)
```

My regex should be correct. I'm not doing any fancy search strings. Here's a more complete example. Here's my HTTP response:
```
HTTP/1.1 200 OK
Server: nginx/1.14.0 (Ubuntu)
Date: Mon, 25 Mar 2019 01:06:54 GMT
Content-Type: text/html; charset=utf-8
Connection: keep-alive
Cache-Control: public, max-age=0
Pragma: no-cache
Expires: 0
Content-Encoding: gzip

<!doctype html><html>	<head>		<title>Petshop Pro &mdash; Login</title>	</head>	<body>		<h1>Admin Login</h1>		<p><b style="color: red">Invalid username</b></p>		<form method="POST">			<p>Username: <input type="text" name="username"></p>			<p>Password: <input type="password" name="password"></p>			<p><input type="submit" value="Log In"></p>		</form>	</body></html>
```
If I search ```Invalid``` or ```username``` or ```Petshop``` or anything in the body and tag it as, say, FAIL, this does not get marked as "FAIL"
If I search anything I find in the header (eg. ```200```, ```nginx```, ```max-age```) and tag it as, say, FAIL, this DOES match and the response is marked as "FAIL".

**Comment by thc202** [comment]
The problem is most likely because of `Content-Encoding: gzip`, if the body is compressed the regex will fail (the Request/Response tabs automatically decompress it).

**Comment by ostracize** [comment]
Thanks! That makes a lot of sense.

So a few questions:
1. Is this documented anywhere? If not, can this be a feature request to either warn the user in the UI or at least document it in the documentation? https://github.com/zaproxy/zap-core-help/wiki/HelpAddonsFuzzConcepts
2. Is there a way around this? Can I force decompressed responses?
3. Can this be a feature request for the message processor to decompress the body the same way the Request/Response tab does. As is, this is quite counter-intuitive.

**Comment by ostracize** [comment]
I answered my own question. For those who are curious:
> Is there a way around this? Can I force decompressed responses?

Yes. Remove:
```gzip``` from the Accept-Encoding header
