### ISSUE TITLE
False Positive: Open Redirect

### ISSUE THREAD

**Issue by chozzz** [zaproxy/zaproxy#5289]
*Open Redirect* should check for the host origin and compare it with the user-supplied input.

Currently, ZAP raises an *Open Redirect* alert for the following request & response;

**Request**
```
GET https://example.com/join/login?redirect_to=https%3A%2F%example.com%2Fwp-admin%2F&reauth=1 HTTP/1.1
Accept-Language: en-US,en;q=0.9
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6; OWASP ZAP) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
Connection: keep-alive
Content-Length: 0
Cookie: REDACTED
site_id=86500c0b-d147-4677-9253-7bed67b9766b; testid=94
Host: example.com
```

**Response**
```
HTTP/1.1 302 Found
Date: Mon, 25 Mar 2019 15:54:31 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Access-Control-Allow-Headers: Authorization, Cache-Control
Cache-Control: no-cache, no-store, must-revalidate
Content-Security-Policy: TOOLONG-REDACTED;
Location: https://example.com
Pragma: no-cache
Set-Cookie: XSRF-TOKEN=16a9573c58425858c1a62b7d1763b49c; path=/; secure
Strict-Transport-Security: max-age=10886400; preload
X-Content-Type-Options: nosniff
X-CSRF-Protection: OWASP CSRFP 1.0.0
X-Frame-Options: SAMEORIGIN
X-Redirect-By: WordPress
X-XSS-Protection: 1; mode=block
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
CF-RAY: 4bd2105accb9cef6-IAD
```

According to [Wiki](https://github.com/zaproxy/zap-extensions/wiki/HelpAddonsPscanrulesAlphaPscanalpha#open-redirect) - it should check when an application allows user-supplied input to control an offsite redirect. But in the case above, it's **not** an offsite redirect, which makes this false positive.

**Comment by chozzz** [comment]
I'd like to give this a shot if no one else is on it yet.

**Comment by kingthorin** [comment]
Got for it!

Note there's a UnitTest over here: https://github.com/zaproxy/zap-extensions/blob/alpha/test/org/zaproxy/zap/extension/pscanrulesAlpha/UserControlledOpenRedirectScannerUnitTest.java that should also be updated, and can help you get the changes together.

If as per the IRC discussion you're also going to handle Threshold here are the UnitTests (and obviously other passive scanners) that handle threshold differences: 
![image](https://user-images.githubusercontent.com/7570458/54940514-3e485480-4f01-11e9-850b-510b77542956.png)

**Comment by kingthorin** [comment]
@chozzz are you tackling this?

**Comment by chozzz** [comment]
@kingthorin sorry for being inactive for quite some time.. but i think i can visit this in the weekend :)

**Comment by kingthorin** [comment]
@chozz is this still on your radar?

**Comment by preetkaran20** [comment]
Hi Team,
 
My understanding of the issue is, Location header is same as the Requested URL(Origin) so this should be considered as false positive. 
I have added the code and raised the PR :- https://github.com/zaproxy/zap-extensions/pull/2146

Now the extension is checking for the request url and if it is same as location header then it will not raise the alert.

thanks,
Karan
