### ISSUE TITLE
Make 500s its own alert separate from "Application Error Disclosure"

### ISSUE THREAD

**Issue by zestysoft** [zaproxy/zaproxy#5291]
**Is your feature request related to a problem? Please describe.**
Generic 500's currently trigger the Medium level "Application Error Disclosure" alert even in situations where nothing is disclosed.

**Describe the solution you'd like**
Create a new plugin just for 500s with a lower rating, or as Simon mentioned in Google Groups, give an option to suppress.

**Describe alternatives you've considered**
Besides begging to the github overlords?

**Comment by kingthorin** [comment]
It doesn't actually require a different plugin, just modified handling in the existing plugin.

**Comment by svkrdj** [comment]
Hello, I would like to take up this issue. Can anyone suggest where to begin with?

**Comment by kingthorin** [comment]
You should check out this post, about the new build process etc:
https://groups.google.com/forum/#!topic/zaproxy-develop/GqLZz9ex0F4

The file you'll need to modify is:
https://github.com/zaproxy/zap-extensions/blob/master/addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ApplicationErrorScanner.java

The `raiseAlert` method can simply be modified to accept different Risk (ex: `Alert.RISK_LOW`).

In the internal server error block you could also add a check for Threshold (https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsOptionsPscanrules#threshold) and just bail out of the scan (`return`) if the Threshold is HIGH I guess? (So at LOW or MEDIUM they'll still be included.)

In the `pscanrules` addon there are other examples of threshold checking, just search for `getAlertThreshold`.

**Comment by svkrdj** [comment]
That does mean, I have to check for the status code (of HttpMessage) in `raiseAlert()` and accordingly set the risk (Alert.RISK_LOW  for 500s,  else Alert.CONFIDENCE_MEDIUM).

**Comment by kingthorin** [comment]
The status code is already checked in the scan method: https://github.com/zaproxy/zap-extensions/blob/18dd1405908a11cd4b891804c3455ff6eb457259/addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ApplicationErrorScanner.java#L130-L132

Also, Risk and Confidence are completely different things.

**Comment by svkrdj** [comment]
Okay, Till now what I figured out is that `getRisk` method is called in during object creation of `Alert`, which return `RISK_MEDUIM`, and we have to set it to RISK_LOW for the 500s. Is that correct?

**Comment by kingthorin** [comment]
This would be my suggestion...

* Leave `getRisk()` returning medium.
* Change the signature of `raiseAlert` to be `private void raiseAlert(HttpMessage msg, int id, String evidence, int risk)`.  (Obviously the function will need to use `risk` instead of `getRisk()` in the appropriate location.)
  * In the 500 (Internal Server Error) block use `raiseAlert(msg, id, msg.getResponseHeader().getPrimeHeader(), Alert.RISK_LOW);`. 
  * In the other block use `raiseAlert(msg, id, evidence, getRisk());`

**Comment by svkrdj** [comment]
Thanks, got it

**Comment by kingthorin** [comment]
Since `raiseAlert` is private to that plugin it doesn't really matter if you change the signature.
