### ISSUE TITLE
Split fuzzdb

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#5294]
Per: https://groups.google.com/d/msg/zaproxy-users/1hugJG4oQCw/jgQDxGDPGwAJ (and many others over the years)
<sub>ex: 
https://github.com/zaproxy/zaproxy/issues/289
https://github.com/zaproxy/zaproxy/issues/2581
</sub>

Fuzzdb should be split such the the files that seem to "upset" AV scanners are moved into a separate addon (ex: fuzzdb-unsafe).

**Comment by kingthorin** [comment]
This is what Microsoft Security Essentials seems to have issues with:
![image](https://user-images.githubusercontent.com/7570458/55923272-c3ef2400-5bd2-11e9-99dd-b94fc772023e.png)

**Comment by psiinon** [comment]
Maybe remove all of the web-backdoors in case other AV has problems with it?
Should we move them to a separate repo so that people cloning zap-extensions dont get hit by this?
The HUD is already a separate repo, so its not as if this would be a radical departure...

**Comment by kingthorin** [comment]
Ya I think both those suggestions are good.

**Comment by svkrdj** [comment]
May I take up this issue. And do I need a Window OS to work and test since the issue is with the windows?

**Comment by svkrdj** [comment]
> May I take up this issue. And do I need a Window OS to work and test since the issue is mainly with the windows?

**Comment by kingthorin** [comment]
I’m ok with that. @psiinon can you create a new repo? The new add-on should probably exist before the older one has content removed.

No you don’t need windows, it’s more of an AV issue than windows. (Plus I can help test once you’ve opened a PR....well two really.)

**Comment by psiinon** [comment]
Created :) https://github.com/zaproxy/fuzzdb-web-backdoors

**Comment by svkrdj** [comment]
That's good. Any help regarding where to start with.

**Comment by psiinon** [comment]
I'd start by just adding the files under https://github.com/zaproxy/zap-extensions/tree/master/addOns/fuzzdb/src/main/zapHomeFiles/fuzzers/fuzzdb/web-backdoors
but without the "addOns/fuzzdb" directories - that right @thc202 ?

**Comment by kingthorin** [comment]
Setup that repo in your IDE. Move a copy of fuzzdb into it, make sure you can build it etc. Rename it to fuzzdb-unsafe, make sure you can build it (and use it in zap). Remove everything but the web backdoors. Build/test. Open PR. 

Once that’s all done, update fuzzdb in the extensions repo, removing the web backdoors. Build/test. Open PR.

**Comment by thc202** [comment]
@psiinon right.

@kingthorin copying as is will not build, it requires other changes. It might be easier to open the PR with the backdoors and guide from there.

**Comment by kingthorin** [comment]
Fair enough.

**Comment by svkrdj** [comment]
Apologies, I am not able to understand. Do I have to copy the files under https://github.com/zaproxy/zap-extensions/tree/master/addOns/fuzzdb/src/main/zapHomeFiles/fuzzers/fuzzdb/web-backdoors to repo fuzzdb-web-backdoors or the whole fuzzdb add-on to fuzzdb-web-backdoors and open the PR later or something else ? @kingthorin @thc202 @psiinon

**Comment by thc202** [comment]
The new repo should have the following directories/files:
```
├── travis.yaml
├── build.gradle.kts
├── settings.gradle.kts
├── gradle
│   └── wrapper
|       ├── gradle-wrapper.jar
|       └── gradle-wrapper.properties
├── CHANGELOG.md
└── src
    └── main
        └── zapHomeFiles
            └── (fuzzdb backdoors)
```

The files in `gradle` directory and the `travis.yaml` file (the cache of WebDrivers should be removed though) can be copied from `zap-extensions` repo.

The other files should have:
 - `settings.gradle.kts`
```
rootProject.name = "fuzzdb-web-backdoors"
```
 - `build.gradle.kts`
```
import org.zaproxy.gradle.addon.AddOnStatus
import org.zaproxy.gradle.addon.manifest.tasks.ConvertChangelogToChanges

plugins {
    `java-library`
    eclipse
    id("org.zaproxy.add-on") version "0.1.0"
}

eclipse {
    classpath {
        // Prevent compilation of zapHomeFiles.
        sourceSets = listOf()
    }
}

version = "1"
description = "FuzzDB web backdoors which can be used with the ZAP fuzzer"

val generateManifestChanges by tasks.registering(ConvertChangelogToChanges::class) {
    changelog.set(file("CHANGELOG.md"))
    manifestChanges.set(file("$buildDir/zapAddOn/manifest-changes.html"))
}

zapAddOn {
    addOnName.set("FuzzDB Web Backdoors")
    addOnStatus.set(AddOnStatus.RELEASE)
    zapVersion.set("2.5.0")

    manifest {
        author.set("ZAP Dev Team")
        url.set("https://github.com/fuzzdb-project/fuzzdb/")
        changesFile.set(generateManifestChanges.flatMap { it.manifestChanges })
    }

    zapVersions {
        downloadUrl.set("https://github.com/zaproxy/fuzzdb-web-backdoors/releases/download/v$version")
    }
}
```
 - `CHANGELOG.md`
```
# Changelog
All notable changes to this add-on will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/).

## Unreleased

First version.
```

with these the add-on in `fuzzdb-web-backdoors` should build, you can create a PR with that. Note that we might need to tweak some things (I didn't try them so might be missing something, description and name of the add-on might be changed...).

**Comment by svkrdj** [comment]
Create a PR. But still not able to build. [PR#1](https://github.com/zaproxy/fuzzdb-web-backdoors/pull/1)

**Comment by kingthorin** [comment]
Here's what McAfee AV didn't like on another system (again all Web Backdoor related):

<details>
<summary>McAfee Removals</summary>

```
addOns/fuzzdb/src/main/zapHomeFiles/fuzzers/fuzzdb/web-backdoors/jsp/browser.jsp
addOns/fuzzdb/src/main/zapHomeFiles/fuzzers/fuzzdb/web-backdoors/asp/cmd-asp-5.1.asp
addOns/fuzzdb/src/main/zapHomeFiles/fuzzers/fuzzdb/web-backdoors/asp/cmd.asp
addOns/fuzzdb/src/main/zapHomeFiles/fuzzers/fuzzdb/web-backdoors/asp/cmd.aspx
addOns/fuzzdb/src/main/zapHomeFiles/fuzzers/fuzzdb/web-backdoors/jsp/laudanum/cmd.war
addOns/fuzzdb/src/main/zapHomeFiles/fuzzers/fuzzdb/web-backdoors/asp/cmdasp.asp
addOns/fuzzdb/src/main/zapHomeFiles/fuzzers/fuzzdb/web-backdoors/asp/cmdasp.aspx
addOns/fuzzdb/src/main/zapHomeFiles/fuzzers/fuzzdb/web-backdoors/jsp/cmdjsp.jsp
addOns/fuzzdb/src/main/zapHomeFiles/fuzzers/fuzzdb/web-backdoors/jsp/jsp-reverse.jsp
addOns/fuzzdb/src/main/zapHomeFiles/fuzzers/fuzzdb/web-backdoors/exe/nc.exe
addOns/fuzzdb/src/main/zapHomeFiles/fuzzers/fuzzdb/web-backdoors/asp/ntdaddy.asp
addOns/fuzzdb/src/main/zapHomeFiles/fuzzers/fuzzdb/web-backdoors/pl-cgi/perlcmd.cgi
addOns/fuzzdb/src/main/zapHomeFiles/fuzzers/fuzzdb/web-backdoors/php/php-backdoor.php
addOns/fuzzdb/src/main/zapHomeFiles/fuzzers/fuzzdb/web-backdoors/php/simple-backdoor.php
```

</details>

**Comment by kingthorin** [comment]
Ref:
https://github.com/zaproxy/zap-extensions/pull/2025
https://github.com/zaproxy/fuzzdb-web-backdoors/pull/1

**Comment by thc202** [comment]
Closing, the add-ons are now available in the marketplace.
