### ISSUE TITLE
Provide portable version of ZAP

### ISSUE THREAD

**Issue by RiotRetroGaming** [zaproxy/zaproxy#5314]
As above.

Most people behind proxies also do not have any admin rights to install programs.
So, with all the lovely work you have been doing it's still pointless and unusable.
The only way around this is to use uninstallable software.

I myself use a 'portable' version of Chrome, Teamviewer and lots of other programs altered to run on work/business machines.

Thanks and hope this sorts a few more people out to be able to use this :)

**Comment by psiinon** [comment]
Have you tried running ZAP from a plugable drive?
The cross platform package doesnt require any installation, just unpack it.
Do you have Java installed? If not theres not much we can do :/

**Comment by kingthorin** [comment]
> Most people behind proxies also do not have any admin rights to install programs.
> So, with all the lovely work you have been doing it's still pointless and unusable.

In this scenario you likely can't set you proxy settings or import the CA cert either. Plus you're probably violating company/org policy and leading towards HR issues,  better to just actually get things approved and properly installed. (Don't violate the "Acceptable Use Policy".)

However the cross-platform package is an unzip'able option, or if the systems already have ava installed the weekly package will work.

**Comment by kingthorin** [comment]
Question answered, closing.
