### ISSUE TITLE
XXE Scanner Content-Type Question

### ISSUE THREAD

**Issue by ldjohnson** [zaproxy/zaproxy#5325]
Hello,

I am attempting automate the Zap XXE scanner and had a question regarding how the scan works.  I noticed that when I run the scan against a vulnerable target, it always seems to get skipped over.  I am only able to get the scan to run when I manually force (through the Zap UI) the content-type to text/xml or application/xml.  Even if I add the expected content-type to the html form that references the file that is vulnerable, I can only get the scan to run if I manually force the content type to text/xml or application/xml.  Is there a way I can get this working and automated in a way that I don't have to force the content-type to an xml based content-type?

Thanks so much in advance for your help.  I look forward to hearing from you!

**Comment by kingthorin** [comment]
The ZAP User Group https://groups.google.com/group/zaproxy-users and Developer Group https://groups.google.com/group/zaproxy-develop are much better places for questions.

The XXE scan rule will only run if the request content-type contains XML.
https://github.com/zaproxy/zap-extensions/blob/eac355cda61db3618f64d32ac60847d2ba2a68e9/addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/XXEPlugin.java#L227-L231
