### ISSUE TITLE
XXE Scanner Unit Test Question

### ISSUE THREAD

**Issue by ldjohnson** [zaproxy/zaproxy#5326]
Hello,

I attempting to write unit tests around the XXE Scanner and am having issues getting them to work properly.  Any help you could provide would be greatly appreciated.  The difficulties I am having are around the Remote File Inclusion check as it uses callbacks.  I tried the following to get it working:

1) I created an ExtensionCallback object to use in my unit tests
2) I created a CallbackParam object to use but was unable to connect to the ExtensionCallback object since callbackParam property is private.
3) I tried to use the ExtensionLoader to load the extension first and then use the ExtensionCallback object created from that.

In all three cases, I end up with a NullPointerException because the CallbackParam object is not initialized properly when it attempts to get the Remote Address.  Is there a way to load the extension in a way that it can be used for running unit tests?  If so, how might I accomplish this?

Thanks so much for your help on this.  it is much appreciated.  I look forward to hearing from you!

**Comment by kingthorin** [comment]
Please don't ask questions as issues - the Zap Developer Group https://groups.google.com/group/zaproxy-develop is a much better place for this type of question.
