### ISSUE TITLE
Ability to replace byte values with the Replacer tool

### ISSUE THREAD

**Issue by marky1124** [zaproxy/zaproxy#5328]
**Is your feature request related to a problem? Please describe.**
I am trying to intercept and change a non-ASCII payload, e.g. 0xDEAD to 0xBEEF for a project I'm working on. As I understand it ZAP is not able to do this at the moment, see discussion https://groups.google.com/forum/#!topic/zaproxy-users/gP70JgqXYZU

**Describe the solution you'd like**
I would like the ability to specify a regex that includes \x hex values for substitution, in the same way that sed can change the hex values 01 03 02 in the following example to 01 02 03

$ echo -n "abc\x01\x03\x02def" | xxd -g 1
0000000: 61 62 63 01 03 02 64 65 66                       abc...def

$ echo -n "abc\x01\x03\x02def" | sed -e 's/\x03\x02/\x02\x03/' | xxd -g 1
0000000: 61 62 63 01 02 03 64 65 66                       abc...def

In ZAP I'd like to be able to specify the Match string as "abc\x01\x03\x02def" and the replacement string as "abc\x01\x02\x03def" to achieve the same result.

**Describe alternatives you've considered**
I am open to alternative solutions that achieve the result of being able to specify match and replacement strings that are a mix of ASCII and non-ASCII values.

**Additional context**
This feature will be very useful for anyone working on a non-ascii API for testing and debugging, as well as any other interception and replacement scenario.

**Comment by psiinon** [comment]
I can see how useful this could be.
The \x01 notation looks good to me - better that the java equivalent.
Should we always enable this, or have it controlled by a checkbox option? Thoughts anyone?

This should be an easy enhancement to make - search the string for all instances of backslash x (just lowercase?), digit, digit and replace these with the hex equivalent. Possibly switchable via a checkbox.
All of the relevant code is here: https://github.com/zaproxy/zap-extensions/tree/master/addOns/replacer/src/main/java/org/zaproxy/zap/extension/replacer
Anyone fancy having a go at it?

**Comment by cotonne** [comment]
I'm on it. 

Do you think we can also do some refactoring or should it be in another PR?
I'm thinking of 
 * moving some functions (for example `ExtensionReplacer.contains/replace` to `ReplacerParamRule`) to comply to rule "Tell, don't ask"
 * add function like `rule.remplacementEmpty()` instead of `rule.getReplacement().length() == 0`. 
 * Move the logic (switch) to other places (maybe specific sub-classes or to `MatchType` enum). It can help reduce duplication.

**Comment by kingthorin** [comment]
It would be better to separate reactor from functional changes.

**Comment by cotonne** [comment]
:tada: 
Thanks for your help!
