### ISSUE TITLE
xml and zip is not really wellformed

### ISSUE THREAD

**Issue by nothingismagick** [zaproxy/zaproxy#5331]
I am using this to pull the latest version for the quasar app-extension:
https://raw.githubusercontent.com/zaproxy/zap-admin/master/ZapVersions.xml
Specifically I find the `<url>` and `<file>` confusing. 
```
        <daily>
            <url>https://github.com/zaproxy/zaproxy/releases/download/w2019-04-29/ZAP_WEEKLY_D-2019-04-29.zip</url>
            <file>ZAP_WEEKLY_D-2019-04-29.zip</file>
            <hash>SHA1:170b0def41b9ddfe6ab674be34d41e065c528dfe</hash>
            <size>347065883</size>
        </daily>
```

The file name is: ZAP_WEEKLY_D-2019-04-29.zip

But its in the `<daily>` block.
Then when I unzip it, the folder is named `ZAP_D-2019-04-29`, so I need to split the name and strip out the WEEKLY. Could you please make the name of the folder it resides in the EXACT same as the name of the zipfile?

**Comment by nothingismagick** [comment]
Also, it would be nice if possible for you to chmod a+x the zap.sh (if that's even possible in zip files, I forget.)

**Comment by zestysoft** [comment]
zap.sh has the executable flag already:

> zipinfo ZAP_WEEKLY_D-2019-04-29.zip |grep "zap.sh"
> -rwxr-xr-x  2.0 unx     4187 b- defN 19-Apr-29 15:58 ZAP_D-2019-04-29/zap.sh

**Comment by psiinon** [comment]
The naming conventions are historic I guess.
We decided to start off with weekly releases, but realised we might move to daily ones in the future (especially when we automated the builds more).
Can you explain why the naming conventions are causing you problems?
Even though they might seem a bit illogical I'm wary of changing the xml structure or file name conventions as that could break things for other people/processes that already handle them.

**Comment by nothingismagick** [comment]
My point was merely that it would be helpful to use the same name for the
top level folder in the zip as the zip itself. Now I understand why weekly
is in the folder name. I can work around it, but it will be brittle if you
don't maintain consistency.

**Comment by psiinon** [comment]
We are always wary of changing things, and try to make sure that we communicate any changes so that people can change anything that relies on them.

**Comment by nothingismagick** [comment]
FYI, this is what I am doing now:

```
  // => zip filename: ZAP_WEEKLY_D-2019-04-29.zip
  zip.extractAllTo("./zap/", true)
  // zip extracted top-level folder name => ZAP_D-2019-04-29
  let zipFolder = fileName.split('_')
  zipFolder = zipFolder[0] + '_' + zipFolder[2]
  let cmd =`./zap/${zipFolder.split('.')[0]}/zap.sh -daemon -host 127.0.0.1 -port 8082 -hud -nostdout`
```

Its just a quick workaround I wrote last night before I filed this issue, I guess I'll parse the top level directory in the zip and register that and be done with it.
