### ISSUE TITLE
Hash Disclosure Scanner patterns don't look for delimiters too

### ISSUE THREAD

**Issue by zestysoft** [zaproxy/zaproxy#5332]
**Describe the bug**
Patterns like "\\b[0-9A-F]{48}\\b" should also look for the negative of those characters surrounding the pattern otherwise they will match on strings that contain more than those number of characters.

This would match even though it shouldn't because there are more than 48 characters:
012323232323232323232123232312121212121212121212012323232323232323232123232312121212121212121212

Usually hashes like the ones being looked for here have some type of surrounding delimiters.

**Comment by kingthorin** [comment]
Please provide the actual response and add-on version. With the word boundary that doesn't match.

https://www.regexplanet.com/share/index.html?share=yyyydp2dhnr
(Click java, then test)

**Comment by zestysoft** [comment]
Sorry,

I was testing against content like this:
https://momentjs.com/downloads/moment-timezone-with-data.min.js

I got two matches and when I manually checked it looked like it wasn't using a word boundary.  However, after further searching, I see that there are other places in the file where it does match exactly using word boundaries, so the pattern is sound.

**Comment by zestysoft** [comment]
I did want to point out however that MacOS as of 10.8 (Apple is at 10.14 now and only support down to 10.12 -- anyone using 10.7 or below is using a version of the OS with known vulnerabilities) changed their password hashing and how it is stored:

This link goes into great detail about how to extract the hash and combine the various parts into something that a hash cracker would need to parse the data:
https://apple.stackexchange.com/questions/220729/what-type-of-hash-are-a-macs-password-stored-in

There are three parts, entropy (the hash), iterations, and the salt.  Each of these are base64 encoded and stored in binary xml format within a plist file.

It's not clear to me what you would want to match on here...

**Comment by kingthorin** [comment]
Thanks for following-up @zestysoft.

Although there's a code comment that attributes it to "Mac OS X salted SHA-1" it may be in use elsewhere or for other purposes.
