### ISSUE TITLE
UserControlledCookieScanner would work better as an active scan 

### ISSUE THREAD

**Issue by zestysoft** [zaproxy/zaproxy#5333]
**Is your feature request related to a problem? Please describe.**
If I'm understanding the code correctly, if there is a POST parameter value that matches a value in a cookie, this is alerting.  That means this will match on situations like:
POST username=myname
cookie RETURNING_USER=myname

If the login is successful, than RETURNING_USER should be assigned the username.  It is impossible to poison this cookie because any other value other than a real username (and valid password) would result in an unsuccessful login and thus RETURNING_USER would not get set.

**Describe the solution you'd like**
In an active check, Zap would be able to assign random values for the parameter and be able to check if a match is found in the cookie. This would be a much better check again the possibility of poisoning a cookie vs assuming a poisoning occurred simply because values matched.

**Comment by kingthorin** [comment]
It “could” work better as an active, however, it was specifically meant as an implementation of a Fiddler Watcher rule, the alerts should be raised at Informational risk just as a tip to testers. I’ll double check the behaviour next week.

**Comment by kingthorin** [comment]
Ok so it seems this is currently raising as Risk Medium and Confidence Medium (https://github.com/zaproxy/zap-extensions/blob/f7a191734e7a56b5a98337ef6dea62795ac071ba/addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/UserControlledCookieScanner.java#L155)

Shall we switch to Low/Low or Info/Low?

**Comment by kingthorin** [comment]
@psiinon @thc202?
