### ISSUE TITLE
Add feedback on search progress

### ISSUE THREAD

**Issue by zestysoft** [zaproxy/zaproxy#5335]
**Is your feature request related to a problem? Please describe.**
When doing a search, there is currently no indication if the search is active or has completed.

**Describe the solution you'd like**
Some type of feedback on search status, especially if no results are found.

**Describe alternatives you've considered**
Wait for an undetermined amount of time for results that may never appear (because there are no matches).

**Comment by psiinon** [comment]
Agreed, I've fallen foul of this more than a few times ;)
