### ISSUE TITLE
Allow setting 0 is unlimited for Active Scan "max results to list"

### ISSUE THREAD

**Issue by zestysoft** [zaproxy/zaproxy#5336]
**Is your feature request related to a problem? Please describe.**
There are times when I need to be able to see results in the Active Scan tab that aren't there due to the seemingly arbitrarily chosen 10,000 limit.  While I can attempt to set this to a larger value, I'd prefer not to have to guess what limit I need.  I understand that there may be performance implications in choosing this setting, however I've got gobs of memory and fast disk storage, so I'd like to at least attempt this.

**Describe the solution you'd like**
Have 0 = unlimited instead of what it currently does (disable storing any results).

**Describe alternatives you've considered**
I've tried setting the limit to a higher value only to find that wasn't big enough.  For scans that takes days, having to re-scan based on future larger guesses is inefficient.

**Comment by psiinon** [comment]
I dont have a problem with this, but it could cause ZAP to run out of memory on some systems, so we should warn people about that (eg in the help).

**Comment by zestysoft** [comment]
So I've tried bumping this number up to a very large number -- 1024000.
I scanned with Zap allotting 8 gigs of memory to it, and at a certain point the scan stops adding new entries in the Active Scan tab.  The CPU utilization of the Java process also climbs from an average of 10% to 100% and stays there.  The history tab continues to add entries and the GUI is otherwise responsive (for instance the timer on the alert category continues to climb).

Thinking that I ran into a memory ceiling (even though Top showed only around 4gb reserved) , I doubled the ram -- 16 gigs, however the same problem happened at right around the same place (The beginning of Advanced SQL Injection).  I got to id 63,092 at 5:34pm yesterday when this started to happen again.  I left the computer on and re-checked at 9:00am to see that nothing changed in the Active Scan tab (the other tabs continued to populate).  Again the memory reserve was nowhere near the max -- It was at 5gb.

Is there a hard-coded limit here that could explain this behavior?  Or maybe some kind of limit with the back-end db?

I'm using ZAP D-2019-05-07

I'm re-running the scan now using the default 1000 value because I need the results from this scan, but I can re-run in a development environment afterwards if that would help troubleshoot this.

**Comment by kingthorin** [comment]
In the weekly the max is a moving window of requests, once it counts up to X it will be the latest X. (Per: https://github.com/zaproxy/zaproxy/pull/3415)

It seems like the SQLi plugin is getting hung up processing a large response.

**Comment by kingthorin** [comment]
You might want to set [Maximum Rule Duration](https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsOptionsAscan#maximum-rule-duration-min-0-is-unlimited)

**Comment by zestysoft** [comment]
I believe this problem only occurs when I changed Active Scan / 'Max results to list' to that high value.  I've set it back to 1000 and am re-running.  I ran this scan over the weekend using the default setting and it went through without a hitch.

Since this is a "Feature" thread, should I move this discussion to a new issue?

**Comment by thc202** [comment]
Yes, better if handled in other issue. If you are able to reproduce the issue could you provide a thread dump?

**Comment by kingthorin** [comment]
@zestysoft any update?

**Comment by zestysoft** [comment]
I'm certain https://github.com/zaproxy/zaproxy/issues/5360 is responsible for this problem, and not with this setting.
