### ISSUE TITLE
SQL select pattern too inclusive  in SoureCodeDisclosureScanner.java

### ISSUE THREAD

**Issue by zestysoft** [zaproxy/zaproxy#5337]
**Describe the bug**
Sentences like these will currently match:

"Select the timezone from which the documents were "
"select or drag or select it from the staging area below."

with the pattern:
languagePatterns.put(Pattern.compile("select\\s+[a-z0-9., \"\'()*]+\\s+from\\s+[a-z0-9._, ]+", Pattern.MULTILINE | Pattern.DOTALL | Pattern.CASE_INSENSITIVE), "SQL");

**Software versions**
 - ZAP: Dev
 - Add-on: Passive Scan Rule Alpha 24

**Additional context**
I believe in a select statement there should only be a single space between select and from?  select * from
or
select id,username from

The only exception would be if a column name had a space in it (usually frowned upon), but these would have to include enclosing quote or brackets.

Or maybe it should look for a trailing semicolon?  or a list of valid words that can happen after from databasename?  like "where" or "sort"?

**Comment by kingthorin** [comment]
Syntactically there "should" be single spaces but plenty of implementations don't care if there are multiple. Semi-colon aren't always required, nor are where, sort, or order clauses. Plus you can come up with edge cases for all 4 of those as well.

To me this is a plausible but improbable thing. If you've encountered it simply mark the alerts false positive.

**Comment by kingthorin** [comment]
Anyone else got feedback on this?

**Comment by thc202** [comment]
I don't think tweaking the regular expression would address this generally (for example, `Select the timezone from which` is a valid query). Manually marking them as FP seems to be better.
