### ISSUE TITLE
zap-baseline.py I/O error(5): ZAP failed to access: {0}'.format(target))

### ISSUE THREAD

**Issue by cxzzero** [zaproxy/zaproxy#5339]
**Describe the bug**
It appears that with specific URL formats an error is raised when zap daemon is executed with _zap-baseline.py_ or _zap-full-scan.py_ (which both depends on _zap-common.py_).
Trying to figure it out if it is a bug or if there is some countermeasure or workaround on this.
I will explain further below.

**To Reproduce**
1. **Run latest "OWASP WebGoat" vulnerable application on a custom port, for example 8988**

either .jar
`java -jar webgoat-server-8.0.0.M24.jar --server.port=8988`

or dockerized
`docker run -p 8988:8080 -t webgoat/webgoat-8.0`

2. **Run latest zap-baseline.py (or zap-full-scan.py) scrip**t.

either local
`./zap-baseline.py -t http://localhost:8988/WebGoat/login`

or inside a docker image (_owasp/zap2docker-weekly, owasp/zap2docker-stable, owasp/zap2docker-live_), take note that localhost IP is obtained as explained in https://github.com/zaproxy/zaproxy/wiki/Docker 
`docker run -t owasp/zap2docker-weekly zap-baseline.py -t "http://$(ip -f inet -o addr show docker0 | awk '{print $4}' | cut -d '/' -f 1):8988/WebGoat/login"`

3. **See error and following initialization lines** 

> ERROR ZAP failed to access: http://localhost:8988/WebGoat/login
> 2019-05-05 12:55:36,956 **I/O error(5): ZAP failed to access:** http://localhost:8988/WebGoat/login
> Traceback (most recent call last):
>   File "./zap-baseline.py", line 315, in main
>     zap_access_target(zap, target)
>   File "<path>/zap_common.py", line 84, in _wrap
>     return_data = func(*args_list, **kwargs)
>   **File "<path>/zap_common.py", line 363, in zap_access_target
>     raise IOError(errno.EIO, 'ZAP failed to access: {0}'.format(target))**
> IOError: [Errno 5] ZAP failed to access: http://localhost:8988/WebGoat/login
> _XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

> Found Java version 1.8.0_191
> Available memory: <memory_available> MB
> Using JVM args: -Xmx3986m
> 138 [main] INFO org.zaproxy.zap.DaemonBootstrap  - OWASP ZAP D-2019-04-29 started 05/05/19 15:55:30 with home /home/zap/.ZAP_D/
> 171 [main] INFO org.parosproxy.paros.common.AbstractParam  - Setting config api.disablekey = true was null
> 171 [main] INFO org.parosproxy.paros.common.AbstractParam  - Setting config api.addrs.addr.name = .* was null
> 172 [main] INFO org.parosproxy.paros.common.AbstractParam  - Setting config api.addrs.addr.regex = true was null
> 172 [main] INFO org.parosproxy.paros.common.AbstractParam  - Setting config spider.maxDuration = 1 was null
> **[... other initialization log lines with INFO severity ...]**
> 3582 [ZAP-daemon] INFO org.parosproxy.paros.extension.ExtensionLoader  - Initializing The ZAP Getting Started Guide
> 3665 [ZAP-daemon] INFO org.zaproxy.zap.extension.callback.ExtensionCallback  - Started callback server on 0.0.0.0:35909
> 3666 [ZAP-daemon] INFO org.zaproxy.zap.extension.dynssl.ExtensionDynSSL  - Creating new root CA certificate
> 4103 [ZAP-daemon] INFO org.zaproxy.zap.extension.dynssl.ExtensionDynSSL  - New root CA certificate created
> 6115 [ZAP-daemon] INFO org.parosproxy.paros.CommandLine  - Add-on update check complete
> 6116 [ZAP-daemon] INFO org.zaproxy.zap.DaemonBootstrap  - ZAP is now listening on 0.0.0.0:60718

**Expected behavior**
As tested with other web applications the result should be similar to this:

1. **Run zap against public xss-game level 1 frame page**
`docker run -t owasp/zap2docker-weekly zap-baseline.py -t https://xss-game.appspot.com/level1/frame`

> 2019-05-05 16:28:43,141 Params: ['zap-x.sh', '-daemon', '-port', '37721', '-host', '0.0.0.0', '-config', 'api.disablekey=true', '-config', 'api.addrs.addr.name=.*', '-config', 'api.addrs.addr.regex=true', '-config', 'spider.maxDuration=1', '-addonupdate', '-addoninstall', 'pscanrulesBeta']
> _XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
> May 05, 2019 4:28:46 PM java.util.prefs.FileSystemPreferences$1 run
> INFO: Created user preferences directory.
> Total of 26 URLs
> PASS: Cookie No HttpOnly Flag [10010]
> [...]
> WARN-NEW: X-Content-Type-Options Header Missing [10021] x 19 
> 	https://xss-game.appspot.com/level1/frame
> [...]

2. **Run zap against Local Python SimpleHTTPServer**
Run `python -m SimpleHTTPServer 8999`

`docker run -t owasp/zap2docker-weekly zap-baseline.py -t "http://$(ip -f inet -o addr show docker0 | awk '{print $4}' | cut -d '/' -f 1):8999"
`

> 2019-05-05 16:42:57,315 Params: ['zap-x.sh', '-daemon', '-port', '51257', '-host', '0.0.0.0', '-config', 'api.disablekey=true', '-config', 'api.addrs.addr.name=.*', '-config', 'api.addrs.addr.regex=true', '-config', 'spider.maxDuration=1', '-addonupdate', '-addoninstall', 'pscanrulesBeta']
> _XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
> May 05, 2019 4:43:00 PM java.util.prefs.FileSystemPreferences$1 run
> INFO: Created user preferences directory.
> Total of 262 URLs
> PASS: Cookie No HttpOnly Flag [10010]
> [...]
> WARN-NEW: Web Browser XSS Protection Not Enabled [10016] x 117
> [...]

**Software versions**
 - ZAP: latest, 2.7.0
 - CI/CD automated scripts: **zap-baseline.py**, **zap-full-scan.py** 
 
**Errors from the zap.log file**
While running in docker I checked the **zap.log** file and did not appear any errors.

`docker run -v $(pwd):/home/zap/.ZAP_D/:rw -t owasp/zap2docker-weekly zap-baseline.py -t "http://$(ip -f inet -o addr show docker0 | awk '{print $4}' | cut -d '/' -f 1):8988/WebGoat/login"`

I attach zap.log file: [zap.log](https://github.com/zaproxy/zaproxy/files/3145817/zap.log)

**Additional context**
1. To note
I searched everywhere before posting this issue and came up with some interesting things but that were not useful for me. So it is worth to mention any case could help identifying the problem.

These links point out that an issue with "zap hangup could be the problem with that" and the usage of /dev/urandom or /dev/random could help solve that.

https://github.com/zaproxy/zaproxy/issues/3763
https://github.com/zaproxy/zaproxy/issues/3864
https://groups.google.com/forum/#!msg/zaproxy-users/TYkyrkymxHc/r-6br-g-BwAJ
https://docs.oracle.com/cd/E13209_01/wlcp/wlss30/configwlss/jvmrand.html

I tried for example this without success: 
`docker run -v /dev/random:/dev/random -t owasp/zap2docker-weekly zap-baseline.py -t "http://$(ip -f inet -o addr show docker0 | awk '{print $4}' | cut -d '/' -f 1):8988/WebGoat/login"`

2. To sum up
Anyway the thing is that zap is not hanging up but seems that the daemon of ZAP is running with a delay because of the last lines displayed in console in section "_To Reproduce_", trying to create a CA certificate and so on.

Besides I note that WebGoat application as it is hosted on localhost:port/WebGoat, there is nothing reachable in localhost:port as I saw in the tests. Just to add some more details.

Appreciate any help of you.

Kind regards,
Juan

**Comment by kingthorin** [comment]
> Besides I note that WebGoat application as it is hosted on localhost:port/WebGoat, there is nothing reachable in localhost:port as I saw in the tests. Just to add some more details.

So you expected ZAZp to get to something that you can’t normally get to?

This seems to be an issue with how you’re starting or accessing webgoat, not a zap issue.

**Comment by cxzzero** [comment]
Hi @kingthorin, I think there is a misunderstanding, perhaps I did not explained well there.

WebGoat is up and running, reachable at localhost:port/WebGoat, as I said there are no communication issues that are involved here.

If I run the ZAP GUI and make a no authenticated scan it display two alerts:

![image](https://user-images.githubusercontent.com/17437230/57200637-b70ce880-6f64-11e9-912e-51b1a46aaa72.png)

So with the GUI there are no problems at all, but the problem appears with dockerized images. I gave all the steps to reproduce the error.

What I mentioned with this line is that the context path of the web application is /WebGoat, so in localhost:port there is nothing hosted (as should be), but perhaps the python scripts (ex. _zap_common.py_) do something else with the context root, and that could be the error.
> Besides I note that WebGoat application as it is hosted on localhost:port/WebGoat, there is nothing reachable in localhost:port as I saw in the tests. Just to add some more details.

This line appear to be the one raising the error: https://github.com/zaproxy/zaproxy/blob/develop/docker/zap_common.py#L361

Hope to clarify a little bit.
Thanks.

**Comment by thc202** [comment]
The log indicates that the target URL is not accessible, as expected since WebGoat is not running in the Docker container:
> ERROR ZAP failed to access: http://localhost:8988/WebGoat/login

You need to obtain the address of the host machine in both cases (i.e. running the Docker container or invoking the script).

Running with `-t "http://$(ip -f inet -o addr show docker0 | awk '{print $4}' | cut -d '/' -f 1):8988/WebGoat/login"` from the host should indeed work, if not you need to check which address is that returning. I'd also suggest trying directly with the address of the host.

**Comment by cxzzero** [comment]
@thc202 thanks for your reply.

Just to clarify, I took **two different approaches** as mentioned:
1. (a) ran WebGoat locally at port 8988 and then (b) execute `zap-baseline.py` (downloaded directly from https://www.zaproxy.org/)

2. (a) ran WebGoat locally at port 8988 and (b) execute `docker run -t owasp/zap2docker-weekly zap-baseline.py -t "http://$(ip -f inet -o addr show docker0 | awk '{print $4}' | cut -d '/' -f 1):8988/WebGoat/login"`

**For the aproach 1** is  the log:
> ERROR ZAP failed to access: http://localhost:8988/WebGoat/login

It happened after I ran these 2 commands:
(console 1, wait until started) 
`java -jar webgoat-server-8.0.0.M24.jar --server.port=8988`, which is the same as executing `docker run -p 8988:8080 -t webgoat/webgoat-8.0` which exposes WebGoat locally _localhost:8988/WebGoat_

(console 2, after started WebGoat) 
`./zap-baseline.py -t http://localhost:8988/WebGoat/login`

**For the aproach 2** I did post the **zap.log** obtained from /home/zap/.ZAP_D directory inside the docker machine.
I ommited the following log in the console which is identical to the aproach 1 but the IP changes accordingly to docker assigned IP (from `$(ip -f inet -o addr show docker0 | awk '{print $4}' | cut -d '/' -f 1)`)

> ERROR ZAP failed to access: **http://<docker_assigned_IP>:8988/WebGoat/login**
> 2019-05-05 12:55:36,956 I/O error(5): ZAP failed to access: **http://<docker_assigned_IP>:8988/WebGoat/login**
> Traceback (most recent call last):
> File "./zap-baseline.py", line 315, in main
> zap_access_target(zap, target)
> File "/zap_common.py", line 84, in _wrap
> return_data = func(*args_list, **kwargs)
> File "/zap_common.py", line 363, in zap_access_target
> raise IOError(errno.EIO, 'ZAP failed to access: {0}'.format(target))
> IOError: [Errno 5] ZAP failed to access: **http://<docker_assigned_IP>:8988/WebGoat/login**
> _XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

**One more thing, if you check the section **Run zap against Local Python SimpleHTTPServer**, when I explained I ran the default "on the fly" simple pyhton http server, it is accesible ok, so I am pretty sure to discard that WebGoat is not accesible (it is the same case just change one app for another, no doubt).**

**Comment by thc202** [comment]
Note that in both approaches you need to use other address than `localhost` as the target, ZAP will run in a container.

I should have pointed out that running WebGoat with `java` command or with Docker is different, you will have to use different addresses (the former should be accessible with the address returned by `$(ip -f inet -o addr show docker0 | awk '{print $4}' | cut -d '/' -f 1)`, for the latter you will have to inspect the container to know which address it has).
(You might also need to bind WebGoat to 8988 when starting with Docker).

**Comment by cxzzero** [comment]
Thanks @thc202.

> (You might also need to bind WebGoat to 8988 when starting with Docker).

Yes it is already done. I bind 8988 (to 8080 - default port of WebGoat) with docker here;  `docker run -p 8988:8080 -t webgoat/webgoat-8.0`

> for the latter you will have to inspect the container to know which address it has).

But if it is accesible through localhost (docker port binding as you can see), I do not see why this is necessary :/. I can see this clear if I didn't do docker port binding, but it's not the case.

I will do more tests. Let me check and I keep you posted.

**Comment by thc202** [comment]
Redirecting the traffic from one port to the other it's not exactly the same as having WebGoat binding to it.

Since ZAP is running in a container localhost will refer to the container itself, not the one the WebGoat is running in, that's why you need to inspect/check the address in the second approach.

**Comment by cxzzero** [comment]
Ah ok, I understand your point. Let me do some checks and let you know. 
Appreciate your help!

**Comment by cxzzero** [comment]
I've made additional tests and figure it out!
Indeed guys you were right and some communication issues were in place. Let me explain my findings:

If I execute this command: `$(ip -f inet -o addr show docker0 | awk '{print $4}' | cut -d '/' -f 1)` what is giving me is the gateway IP of the docker subnet.

To check it out I ran `docker inspect <webgoat_container_id>`:

> "NetworkSettings": {
>             [...]
>             "Ports": {
>                 "8080/tcp": null
>             },
>             [...]
>             "Gateway": "**<gateway_IP>**",
>             "IPAddress": "**<webgoat_docker_assigned_IP>**",

---
So to fix it:
**(Method 1):**
1. Run webgoat binded to docker_gateway_address_IP and port 8988
`java -jar webgoat-server-8.0.0.M24.jar --server.port=8988 --server.address=$(ip -f inet -o addr show docker0 | awk '{print $4}' | cut -d '/' -f 1)`

2. Run zap-baseline this way
`docker run -t owasp/zap2docker-weekly zap-baseline.py -t "http://$(ip -f inet -o addr show docker0 | awk '{print $4}' | cut -d '/' -f 1):8988/WebGoat"`

---
**(Method 2):**
1. Run webgoat in docker container
`docker run -p 8988:8080 -t webgoat/webgoat-8.0`
The container IP can be obtained this way: 
<container_IP> = `docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker ps | grep webgoat | awk '{print $1}')
`
2. Then run zap:
`docker run -t owasp/zap2docker-weekly zap-baseline.py -t "http://<container_IP>:8988/WebGoat"`

---
**Alternative options:**
As mentioned here there are two more options: https://community.wia.io/d/15-accessing-the-host-from-inside-a-docker-container

1. Specify docker container address to `$(/sbin/ip route|awk '/default/ { print $3 }')`
2. Add docker container to local network by running: `docker run <image> --network="host"`

**Comment by kingthorin** [comment]
@cxzzero thanks for letting us know.
