### ISSUE TITLE
Add timestamps to debug/console output

### ISSUE THREAD

**Issue by zestysoft** [zaproxy/zaproxy#5358]
**Is your feature request related to a problem? Please describe.**
When troubleshooting problems in Zap, it would be helpful to match timestamps in the console output with the timestamps of items in the various tabs.

**Describe the solution you'd like**
Replace the counter? or add a timestamp to the output.

**Additional context**
8330471 [HSQLDB Timer @7cb9d95b] INFO hsqldb.db..ENGINE  - checkpointClose script done
8330471 [HSQLDB Timer @7cb9d95b] INFO hsqldb.db..ENGINE  - dataFileCache commit start
8330853 [HSQLDB Timer @7cb9d95b] INFO hsqldb.db..ENGINE  - dataFileCache commit end
8330971 [HSQLDB Timer @7cb9d95b] INFO hsqldb.db..ENGINE  - checkpointClose end
8330971 [HSQLDB Timer @7cb9d95b] INFO hsqldb.db..ENGINE  - Checkpoint end - txts: 1281895

Some of those 'counters' use the same number, so maybe this is using something time based already?  If that's the case, making this human readable would be helpful.

**Comment by psiinon** [comment]
You should be able to do this yourself by editing your local log4j.properties file
https://github.com/zaproxy/zaproxy/blob/develop/src/xml/log4j.properties

**Comment by thc202** [comment]
Those numbers are the milliseconds since ZAP started. The log file uses a different format (date/time) by default.

**Comment by kingthorin** [comment]
@zestysoft did either of those answers address your concern?

**Comment by zestysoft** [comment]
Sorry, yes, Simon's solution was exactly what I was looking for.
