### ISSUE TITLE
Advanced SQL Injection plugin sometimes doesn't complete

### ISSUE THREAD

**Issue by zestysoft** [zaproxy/zaproxy#5360]
**Describe the bug**
After running a scan 4 times, 3 of them resulted in the scanner stuck running the Advanced SQL Injection plugin.  The counter continues to count, but no new entries are added to the Advanced Scan tab.  Clicking on "Skip Active Scanner" doesn't stop the plugin.  I have to completely close Zap for everything to terminate.

**To Reproduce**
Start scan and wait for it to happen.

**Expected behavior**
Scan continues without locking up.

**Software versions**
ZAP Weekly (2019-05-07)
OpenJava v1.8.0_201
Ubuntu 18.04 LTS

**Errors from the zap.log file**
None.

**Additional context**
I had thought this bug was related to me changing the Active Scan "Max results to list" to a higher value, but even reset back to 1000, it still happened. One other change that I had made was to increase the concurrent scanning threads per host from 5 to 10.

**Comment by zestysoft** [comment]
Here's a threat dump of the latest lockup:
[threadDump.txt](https://github.com/zaproxy/zaproxy/files/3184332/threadDump.txt)

I set threads back to 5, and ran a scan of our system using all plugins except for "Advanced SQL Injection." That went through fine.  I then closed Zap, re-opened the session, and created a new policy that only had "Advanced SQL Injection" enabled and after authenticating myself back into the web app, ran it.  It didn't take long to lock up -- about 12 minutes.

I'll keep the process running for now if there is anything additional I can pull from it.  I can try this again through IntelliJ if that helps any.

**Comment by thc202** [comment]
Thanks, it seems the scanner is "hanging" with a regular expression, probably with a big response. Do you know if there's something big, more than usual?

(The number of threads is unrelated.)

**Comment by zestysoft** [comment]
Hmm.. How can I find out?  -- I just re-ran the scan by setting "Maximum rule duration" to 4 minutes and disabling "Handle anti CSRF tokens" after reading that this forces the scans to run in a single thread.

I didn't see anything come close to approaching 4 minutes, and it completed without issue.

The entire scan completed MUCH faster -- faster than I would have expected going from 1 thread to 5.

I've reverted those two changes and am re-running to see if this is still reproducible and then will run the scan by just changing CSRF.  It has already passed the point where it hung last time.

**Comment by kingthorin** [comment]
@zestysoft any news?

**Comment by zestysoft** [comment]
I'm going to have some time next week to look into this more.

**Comment by zestysoft** [comment]
I've tried this twice from my development vm, but couldn't reproduce it. The system I was scanning will be torn down soon so I won't be able to continue testing.  If this happens again with a future scan, I'll try to jump on it with a debugger faster next time.

**Comment by psiinon** [comment]
@zestysoft thanks for letting us know
