### ISSUE TITLE
Unable to access ZAP URL from another system in same network 

### ISSUE THREAD

**Issue by vbrundavanam** [zaproxy/zaproxy#5367]
Hi,

I installed ZAP in one of my VM1 ( 192.168.50.1 ) and i able to access through localhost:8080 and 127.0.0.1:8080 URL. I want access ZAP from multiple systems in same network. 

I want to access the ZAP URL with IP Address of VM1 ( 192.168.50.1 ) in VM2 ( 192.168.50.2 ).

Please suggest.

**Comment by psiinon** [comment]
Please dont ask questions in issues - the ZAP User Group is the best place for them: https://groups.google.com/group/zaproxy-users

**Comment by vbrundavanam** [comment]
Thank you Simon
