### ISSUE TITLE
ZAP exe might fail to find Java

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#5368]
Using OpenJDK 12.0.1 (64 bit) the (2.7.0) exe fails with “This application requires a java runtime 1.8.0” but the bat file apparently works fine.
Reported via email.

**Comment by ostens** [comment]
Are there any plans to fix this? I'm still experiencing it in the latest version. Currently using a workaround by changing the shortcut to use the bat file, but this might not be sustainable for new users.

**Comment by dnperfors** [comment]
I am using openjdk 11.0.6 using an AdoptOpenJDK build and I get exactly the same error on windows 10 with ZAP 2.9.0 when directly running the exe.
I can just do `java --version` and get the following result:
```
java --version
openjdk 11.0.6 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.18.1, JRE 11 Windows 10 amd64-64-Bit Compressed References 20200122_442 (JIT enabled, AOT enabled)
OpenJ9   - 51a5857d2
OMR      - 7a1b0239a
JCL      - da35e0c380 based on jdk-11.0.6+10)
```

But this probably has to do something with the following issue from Launch4j: https://sourceforge.net/p/launch4j/bugs/205/

**Comment by kingthorin** [comment]
Ref: https://mobile.twitter.com/JustinDoles/status/1228419948881510400

**Comment by thc202** [comment]
@dnperfors (and others using AdoptOpenJDK) as workaround you need to select the feature `JavaSoft (Oracle) registry keys` when installing the JRE.

**Comment by kingthorin** [comment]
“ZAP exe fails with newer Java versions“

Is it a version thing or a vendor thing? Would “non-oracle” be more correct?

**Comment by thc202** [comment]
Right, that's not accurate, tweaked (feel free to change).

**Comment by kingthorin** [comment]
Seems good

**Comment by jrchamp** [comment]
> Are there any plans to fix this? I'm still experiencing it in the latest version. Currently using a workaround by changing the shortcut to use the bat file, but this might not be sustainable for new users.

Thank you! I was about to give up until read more closely to see that:
**Using zap.bat instead of ZAP.exe is a workaround**

**Comment by isaaccardoso-ctl** [comment]
> > Are there any plans to fix this? I'm still experiencing it in the latest version. Currently using a workaround by changing the shortcut to use the bat file, but this might not be sustainable for new users.
> 
> Thank you! I was about to give up until read more closely to see that:
> **Using zap.bat instead of ZAP.exe is a workaround**

This workaround worked for me as well. Anyone know if there is a downside to this?

**Comment by kingthorin** [comment]
The only downside that I can think of is that you end-up with a cmd window open but that shouldn't be a big deal.

**Comment by GavinMoreYoung** [comment]
Use the zap.bat file

**Comment by DavidKrings** [comment]
Workaround using .bat works until there is an update. Would be helpful to know what exactly it is looking for.

**Comment by GavinMoreYoung** [comment]
收到，会尽快给您回复。

**Comment by kingthorin** [comment]
It's probably an issue around registry or env vars. When installing OpenJDK you should select the two optional items (one is JavaSoft something, I don't recall the other).

**Comment by DavidKrings** [comment]
That...and the key is to use OpenJDK rather than Oracle. Works better now.

**Comment by thc202** [comment]
There's a new version (3.50) of Launch4j that might address this (https://launch4j.sourceforge.net/changelog.html) requires update in the Gradle plugin though (TheBoegl/gradle-launch4j#144).

**Comment by GavinMoreYoung** [comment]
收到，会尽快给您回复。

**Comment by GavinMoreYoung** [comment]
收到，会尽快给您回复。
