### ISSUE TITLE
Fedora 30: ZAP GUI is not supported on a headless environment.

### ISSUE THREAD

**Issue by paaland** [zaproxy/zaproxy#5376]
**Describe the bug**
Trying to run ZAP on Fedora 30 (Wayland) and get the following error:
ZAP GUI is not supported on a headless environment.

My environment is not headless, but a laptop.

**To Reproduce**
1. Download installers on Fedora 30
2. Run installer to install ZAP
3. Run zap.sh to start ZIP

**Expected behavior**
ZAP actually starts...

**Comment by kingthorin** [comment]
That's true, the GUI isn't supported by a headless environment. Not sure why that's a surprise :man_shrugging: 

If you want to run zap headless us -daemon.

https://github.com/zaproxy/zaproxy/issues/4659

**Comment by paaland** [comment]
Fedora 30 workstation is *not* a headless environment. But it is using the new wayland window mananger vs the traditional x11 one. I guess your java app checks for the presens of x11 in a way that's not catched by the wayland compatibility layer.

**Comment by kingthorin** [comment]
Please refer to the referenced ticket https://github.com/zaproxy/zaproxy/issues/4659 as discovered in that long running ticket the solution the user arrived upon in the end is to install a JRE that isn’t headless.

**Comment by gu1113** [comment]
try it using these argument with your java binary,  -jar -Djava.awt.headless=false zap-2.7.0.jar

**Comment by kingthorin** [comment]
@paaland did switching JRE (per the previous issue) or using @gu1113's suggestion work out for you?

**Comment by kingthorin** [comment]
Closing due to lack of feedback.
