### ISSUE TITLE
Unable to set certificate when running full scan from a container against k8s deployed https service

### ISSUE THREAD

**Issue by vlad-crst** [zaproxy/zaproxy#5379]
I am trying to run inside the Owasp Zed docker image a full scan on a https service but i am not able to set or pass as an argument the certificate.
I tried to run as described on this page : https://github.com/zaproxy/zaproxy/wiki/ZAP-Full-Scan
I am having following error:

10960 [ZAP-ActiveScanner-0] ERROR org.zaproxy.zap.extension.ascanrules.SourceCodeDisclosureWEBINF  - Error scanning a Host for Source Code Disclosure via the WEB-INF folder: Received fatal alert: bad_certificate
javax.net.ssl.SSLHandshakeException: Received fatal alert: bad_certificate

Is there a way to set certificate when running "zap-full-scan.py -t https://www.example.com -g gen.conf -r testreport.html"

Sorry if i did a mistake by asking this here, but i am quite new on github :)

**Comment by thc202** [comment]
Closing, this was handled in the Users Group: https://groups.google.com/d/topic/zaproxy-users/p7wbcSmpLUY/discussion
