### ISSUE TITLE
Could not open ZAP 2.7.0 on macOS with JDK 12

### ISSUE THREAD

**Issue by kaustavch88** [zaproxy/zaproxy#5384]
**Describe the bug**
Could not open ZAP 2.7.0 on a macOS mojave with JDK 12. Exceptions from java are thrown.

**To Reproduce**
1. Extract the zip file of the Cross Platform Package
2. Run the .jar or .sh file

**Expected behavior**
Running the .jar or .sh file should open the program

**Screenshots**
NA

**Software versions**
 - ZAP: ZAP 2.7.0
 - OS: macOS Mojave 10.14.5
 - Java: 12.0.1

**Comment by psiinon** [comment]
@kaustavch88  Can you include some of the java exceptions?

**Comment by thc202** [comment]
Might be this: https://github.com/zaproxy/zaproxy/issues/4669#issuecomment-444913600

**Comment by psiinon** [comment]
It is - I've just tried it.
However the latest weekly works fine.
We're so close to releasing ZAP 2.8.0 that I propose we 'wontfix' this - the workaround is to use the weekly.
Any objections?

**Comment by psiinon** [comment]
Or just close it as a dup of course :)

**Comment by psiinon** [comment]
#4669

**Comment by kingthorin** [comment]
> We're so close to releasing ZAP 2.8.0 that I propose we 'wontfix' this - the workaround is to use the weekly.
Any objections?

Seems good.
