### ISSUE TITLE
Update to JxBrowser 7.0

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#5388]
Released May 30th: https://jxbrowser-support.teamdev.com/release-notes/2019/v7.html
Lots of changes, but ones that we want (like support for Java 11)
Upgrading looks like it will be non trivial: https://jxbrowser-support.teamdev.com/docs/guides/migration/v6-v7.html
I've made a start but wont be able to look at it over the next few days so v happy for anyone else to take this on.

**Comment by thc202** [comment]
The license we have only works with 6.x.

**Comment by psiinon** [comment]
I'll contact JxBrowser to see if we can get a license for 7.0

**Comment by psiinon** [comment]
Unfortunately TeamDev will not give us a license for 7.0 :(
