### ISSUE TITLE
Update HarLib library

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#5393]
Update HarLib library to version 1.1.3 (needs to be published to Maven Central first).

**Comment by kingthorin** [comment]
It seems 1.1.3 was published in April 2016, do we really think it will actually be published to maven at some point? (It's been 3.5 years at this point.)

**Comment by thc202** [comment]
We'll have to do that (we submitted the current version available in Maven Central).

**Comment by thc202** [comment]
Ref: https://issues.sonatype.org/browse/OSSRH-66429
