### ISSUE TITLE
Custom Header to detect traffic coming from ZAP

### ISSUE THREAD

**Issue by JayPowerUser** [zaproxy/zaproxy#5394]
This is to be used with the Zap baseline and API scanner. 

This is to allow and tune rules for WAF firewall detection's and false positives

This could also be a custom User Agent Header or something that helps identify that this originated from Zap.

**Comment by kingthorin** [comment]
This can be done with:
- The Replacer add-on https://github.com/zaproxy/zap-extensions/wiki/HelpAddonsReplacerReplacer
- An HTTPSender script https://github.com/zaproxy/community-scripts/tree/master/httpsender
  - https://www.securify.nl/blog/SFY20170301/scripting-with-zap_-adding-a-new-header-to-each-scan-request.html
  - https://github.com/zaproxy/zap-core-help/pull/154
    - https://github.com/zaproxy/zaproxy/blob/develop/zap/src/main/dist/scripts/templates/httpsender/AddZapHeader.js
- https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsOptionsAscan#inject-plugin-id-in-header-for-all-active-scan-requests

**Comment by JayPowerUser** [comment]
Do you know how this could be applied in with the Docker baseline scanner? 
Trying to include this in CI/CD. This is the commands that we use with a custom configuration file. 

```
docker run -t owasp/zap2docker-stable zap-baseline.py -t https://www.example.com -c config.conf
```

**Comment by kingthorin** [comment]
The ZAP User Group https://groups.google.com/group/zaproxy-users is a much better place for discussions like this.

**Comment by JayPowerUser** [comment]
@kingthorin  Thank you
