### ISSUE TITLE
Form login with the docker images

### ISSUE THREAD

**Issue by darakian** [zaproxy/zaproxy#5399]
**Describe the bug**
I'm trying to do a simple baseline scan with the zap weekly image against my web app and I can't seem to get the login working. 
```
docker run -t owasp/zap2docker-weekly zap-baseline.py -z "-config password=1234" -t https://foo.com/api/login/user
```
Am I simply missing how this is done? I can't find anything in the docs about it.

**Comment by kingthorin** [comment]
The ZAP User Group https://groups.google.com/group/zaproxy-users is a much better place for questions.

The baseline scan is meant to be simple (kind of like quickstart), and isn't geared toward leveraging auth.

Here are some resources that might assist you:

- https://stackoverflow.com/questions/43215234/pass-login-parameters-to-scan-with-owasp-zap-on-docker-command/43215537
- https://github.com/zaproxy/zaproxy/wiki/FAQconfigValues
- https://github.com/ICTU/zap-baseline
