### ISSUE TITLE
OWASP ZAP 2.7.0 vulnerability result not reproducible

### ISSUE THREAD

**Issue by francescoleone** [zaproxy/zaproxy#5403]
**Describe the bug**
We are using OWASP ZAP 2.7.0 importing our proprietary webAPI.
We launched an attack INsane /threshold: Low and in the first attack session, the tool evidenced an SQL injection - PostgresSQL Critical vulnerability.
We ran it again later days after, without changing anything in the test environment including the software version under attack and the same vulnerability "magically" disappeared.
We are doubting about attack reproducibility with this tool or we are not using the tool in the proper way.  Do OWASP zap perform attacks in different ways each run if everything is set and not changed between subsequent runs ?

**To Reproduce**
Run SQL-Injection - Postgres attack repeatedly, if a critical vulnerability appears it does disappear on subsequent run

**Expected behavior**
without changing anything, the vulnerability found should be present all in further attacks

**Software versions**
 - ZAP: 2.7.0
 - Add-on: -
 - OS: RHEL7.3
 - Java: 1.8u202
 - Browser: Firefox

**Comment by kingthorin** [comment]
Without the details of the alert it is hard to say. However if it was a time based SQLi then its possible that it was impacted by system load, network, etc. Any type of SQLi could be impacted by system state/data which is subject to change with time or between runs. (This is true of any system/tool.)

**Comment by francescoleone** [comment]
the SQLi injection that appeared was Time Based

High (Medium) | SQL Injection - PostgreSQL -   Time Based
-- | --
Description | SQL injection may be possible
 
URL | https://10.42.155.104:8443/ws1/services/xxxxxxxxxx
Method | POST
Parameter | xmlns:ns1

field:   [xmlns:ns1], value [http://xxxx.xxxxx.xxxxx.xxxxx./" and 0   in (select case when cast(pg_sleep(15) as varchar) > '' then 0 else 1 end   ) -- ]
--

**Comment by psiinon** [comment]
As @kingthorin said, time based vulnerabilities are affected by lots of different factors. 
If its not reproducible then its probably not an issue. But I dont think that means its a bug in ZAP.

**Comment by francescoleone** [comment]
HI there, just wondering if it appears once it means anyway we are subject at that type of issue. I'm understanding that it could be difficult to reproduce but at least it can be said we are affected by that vulnerability since it was found at least once. What do you think about ?

**Comment by kingthorin** [comment]
It's more likely that some separate factor (as mentioned earlier) caused Zap to report a false positive.

**Comment by francescoleone** [comment]
How can we get rid or be conscious it is a false positive and not a real vulnerability ?

**Comment by codingo** [comment]
@francescoleone all current proxies fail in this department as they tend to rely on timing based checks. You'll often see both [Burp Suite](https://portswigger.net/burp) and Zap Proxy reporting false positives in this area, I've even seen `robots.txt` reported as injectable because of the way these checks are implemented..

My recommendation would be to build these particular checks using [SQLMap](http://sqlmap.org/) (traditionally a lot more reliable for SQL Injection testing) and disregarding error and time based blind reports from your proxy, unless reproducible in alternative tooling. You could map your full site by doing a crawl in Zap Proxy or Burp Suite and then handing the task over to [SleuthQL](https://github.com/RhinoSecurityLabs/SleuthQL). Feel free to drop me a line on [twitter](https://github.com/codingo_) if you'd like some assistance building automation around this.

**Comment by francescoleone** [comment]
Hi there codingo, thanks for more clear explanation. Anyway you are assuming that OWASP zap project when talking about SQL injection testing is not so reliable as other tool as SQL map? And as a general approach we should classify those time based reports as False positive ?

**Comment by codingo** [comment]
@francescoleone I think that's pretty well understood by the industry. Zap will be much easier to integrate into a workflow (due to its API's), but it can't even come close to the coverage that SQLMap will offer for this particular bug class.

**Comment by kingthorin** [comment]
> And as a general approach we should classify those time based reports as False positive ?

No you should validate manually or with tertiary tools.

**Comment by kingthorin** [comment]
Can this be closed?

There are existing tickets that cover solutions which may at least  somewhat alleviate this problem. Ex: https://github.com/zaproxy/zaproxy/issues/3662

**Comment by francescoleone** [comment]
Hi Kingthorin, yes you can close it , just we are thinking to validate manually. About tertiary tools we should use some other reliable. You told me SQLMap, can you suggest me some other ?

**Comment by kingthorin** [comment]
SQLmap is kinda the king of the hill when it comes to that vuln class. Aside from that I'd suggest manual validation,. You can get further details on that from other OWASP initiatives like the Testing Guide, Prevention Cheet Sheet, etc (just web search "OWASP SQLi")
