### ISSUE TITLE
MacOS installation for ZAP 2.8.0 fails 'no mountable filesystem' in dmg file

### ISSUE THREAD

**Issue by securestep9** [zaproxy/zaproxy#5409]
**Describe the bug**
ZAP 2.8.0 installation (and upgrade from 2.7.0) fails on MacOS with error 'The following disk images cannot be opened - ZAP_2.8.0.dmg - no mountable file systems'

**To Reproduce**
Steps to reproduce the behavior when installing: 
1. Go to: https://github.com/zaproxy/zaproxy/wiki/Downloads
2. Click on 'MacOS Installer - Download now' - download the file 
3. Open the dowloaded file 
4. See error: 'The following disk images cannot be opened - ZAP_2.8.0.dmg - no mountable file systems'

Steps to reproduce the behavior when upgrading from ZAP 2.7.0
1. Launch ZAP 2.7.0 on Mac OS 
2. The following pop-up appears:' The latest ZAP release 2.8.0 has been downloaded to /Users/macuser/Library/Application Support/ZAP/plugin/ZAP_2.8.0.dmg. Launch this file and close ZAP?'
3. Click OK
4. See error: 'The following disk images cannot be opened - ZAP_2.8.0.dmg - no mountable file systems'

**Expected behavior**
Installation wizard was expected to launch

**Screenshots**
attached

**Software versions**
 - ZAP: 2.8.0
 - OS: MacOS 10.11
 - Java: 1.8.0_191
 - Browser:  chrome 74

**Errors from the zap.log file**
See https://github.com/zaproxy/zaproxy/wiki/FAQconfig for the location of the zap.log file for your OS.

**Comment by securestep9** [comment]
<img width="383" alt="Screen Shot 2019-06-10 at 09 51 38" src="https://user-images.githubusercontent.com/20112179/59188174-f5eb1b00-8b6e-11e9-91ed-b015424b4206.png">

**Comment by psiinon** [comment]
@securestep9 I've just tried this on my Mac mini and it works fine for me :/
Can you try downloading is again?
Whats the sha256 hash of the file when downloaded?
It should be: https://github.com/zaproxy/zap-admin/blob/master/ZapVersions-2.8.xml#L27

**Comment by securestep9** [comment]
@psiinon aftre some digging the problem is potentially is in the fact that the file system in the ZAP_2.8.0 DMG is APFS (in ZAP_2.7.0.dmg filesystem is HFS+) making it incompatible with older MacOS - apparently this is easily fixed by adding '-fs HFS+' option when building the dmg like this:

`hdiutil create DMG_filename.dmg -fs HFS+ -srcfolder fooProject/bin/ -format UDZO -volname ProjectFoo`

**Comment by psiinon** [comment]
@securestep9 thanks for that. I've regenerated the MacOS release with that option and uploaded it as https://github.com/zaproxy/zaproxy/releases/download/v2.8.0/ZAP_2.8.0-HFS-test.dmg
Can you test it to make sure it works for you now?
If it does we'll swap them.

**Comment by psiinon** [comment]
Note to self - submit PR to add the option to https://github.com/zaproxy/zaproxy/blob/v2.8.0/buildSrc/src/main/kotlin/org/zaproxy/zap/distributions.gradle.kts#L240-L246

**Comment by psiinon** [comment]
And regenerate the release with `./gradlew -PcreationDate=2019-06-07 distMac`

**Comment by psiinon** [comment]
And update https://github.com/Homebrew/homebrew-cask/blob/master/Casks/owasp-zap.rb with the new hash

**Comment by scotmatson** [comment]
The current 2.8.0 (8fe3c30411524a05d662c2a2d1e2762a43291db7c39b23963b7de0f259ab122c) build is working for macOS Mojave 10.14.4.

**Comment by psiinon** [comment]
@securestep9 have you had a chance to try out the download?

For reference someone else has also just reported this via twitter: https://twitter.com/Jaymzu/status/1141686039691632640

**Comment by Jaymzu** [comment]
Hey guys, 
Mojave 10.14.5 here
Q:tmp jay$ shasum -a 256 ZAP_2.8.0.dmg
8fe3c30411524a05d662c2a2d1e2762a43291db7c39b23963b7de0f259ab122c  ZAP_2.8.0.dmg
Q:tmp jay$ shasum -a 256 ZAP_2.8.0-HFS-test.dmg
95d8678443e90cd72996b3440ce3ef75a575ad5b36809b41f063c5a47c09dd9b  ZAP_2.8.0-HFS-test.dmg
Q:tmp jay$ diskutil mount ZAP_2.8.0.dmg
Unable to find disk for ZAP_2.8.0.dmg
Q:tmp jay$ diskutil mount ZAP_2.8.0-HFS-test.dmg
Unable to find disk for ZAP_2.8.0-HFS-test.dmg
Q:tmp jay$

**Comment by psiinon** [comment]
@Jaymzu just to confirm, do you mean that just  ZAP_2.8.0-HFS-test.dmg worked or  ZAP_2.8.0.dmg did as well?

**Comment by Jaymzu** [comment]
So, here's a funny story. Doubleclicking ZAP_2.8.0.dmg in finder spits out a window saying "no mountable filesystems"
Mounting it from command line (now that I learned how to do it ;) ), however, works. 
Q:tmp jay$ hdiutil attach ZAP_2.8.0.dmg
Checksumming Protective Master Boot Record (MBR : 0)…
Protective Master Boot Record (MBR :: verified CRC32 $FD137690
Checksumming GPT Header (Primary GPT Header : 1)…
 GPT Header (Primary GPT Header : 1): verified CRC32 $8FD5E2F4
Checksumming GPT Partition Data (Primary GPT Table : 2)…
GPT Partition Data (Primary GPT Tabl: verified CRC32 $952E2B58
Checksumming  (Apple_Free : 3)…
                    (Apple_Free : 3): verified CRC32 $00000000
Checksumming disk image (Apple_APFS : 4)…
.....................................................................................................................................................
         disk image (Apple_APFS : 4): verified CRC32 $4AD503FE
Checksumming  (Apple_Free : 5)…
                    (Apple_Free : 5): verified CRC32 $00000000
Checksumming GPT Partition Data (Backup GPT Table : 6)…
GPT Partition Data (Backup GPT Table: verified CRC32 $952E2B58
Checksumming GPT Header (Backup GPT Header : 7)…
  GPT Header (Backup GPT Header : 7): verified CRC32 $3AD9BB8E
verified CRC32 $7C5B065E
/dev/disk5          	GUID_partition_scheme
/dev/disk5s1        	Apple_APFS
/dev/disk6          	EF57347C-0000-11AA-AA11-0030654
/dev/disk6s1        	41504653-0000-11AA-AA11-0030654	/Volumes/OWASP ZAP

**Comment by psiinon** [comment]
@Jaymzu thanks!
@thc202 @kingthorin think its ok for us to keep using the existing dmg but to add a footnote explaining how to use it from the command line on older versions of MacOS?

**Comment by Jaymzu** [comment]
it's not on older versions. I'm running the latest Mojave (10.14.5)

**Comment by psiinon** [comment]
Ah, I clearly dont understand Macs well enough :/

**Comment by kingthorin** [comment]
> @kingthorin think its ok for us to keep using the existing dmg but to add a footnote explaining how to use it from the command line on older versions of MacOS?

Seems reasonable to me.

**Comment by thc202** [comment]
@psiinon can this be fixed for 2.9.0 (guess by doing this https://github.com/zaproxy/zaproxy/issues/5409#issuecomment-501243535)?

**Comment by ryopark** [comment]
@thc202 It worked by using this https://github.com/zaproxy/zaproxy/issues/5409#issuecomment-501242753
