### ISSUE TITLE
Webswing requires username / password

### ISSUE THREAD

**Issue by teohaik** [zaproxy/zaproxy#5411]
**Describe the bug**
Iam trying to follow the guidelines and open zap through webswing, but it asks for a username/password

I'am running the docker command:
docker run -u zap -p 8080:8080 -p 8090:8090 --name zapSSPWeb -i owasp/zap2docker-stable zap-webswing.sh

and then, on a browser:
http://localhost:8080/?anonym=true

and it gives me this:
![image](https://user-images.githubusercontent.com/1785012/59201838-02d63180-8ba4-11e9-8f0e-ca04ba82da35.png)

**Comment by thc202** [comment]
You need to use `http://localhost:8080/zap` instead.

**Comment by psiinon** [comment]
The wiki was out of date, I've just updated it: https://github.com/zaproxy/zaproxy/wiki/WebSwing
