### ISSUE TITLE
JxBrowser does not launch in ZAP 2.8

### ISSUE THREAD

**Issue by jeanbritz** [zaproxy/zaproxy#5415]
**Describe the bug**
After upgrading to ZAP 2.8 the built-in JxBrowser does not launch
and throws a stacktrace in the zap.log file, which I believe prevents the JxBrowser from launching correctly

**To Reproduce**
1. On the toolbar, click on the button (that has the Chromium icon) that launches the built-in JxBrowser
3. Open the zap.log in your user's folder to see stacktrace.

**Expected behavior**
If there is a compatibility issue, then just a message box to tell the user that JxBrowser is incompatible.

**Screenshots**
I think the stacktrace would suffice

**Software versions**
 - ZAP: 2.8
 - Add-on: JxBrowser (core) version 14.0.0, JxBrowser (Windows) 12.0.0 
 - JxBrowser version which ZAP uses: JxBrowser 6.23.1 .
 - OS: Windows 10
 - Java: Oracle java version "1.8.0_191"
 - Browser: N/A

**Errors from the zap.log file**
java.lang.RuntimeException: java.lang.NoSuchMethodException: com.teamdev.jxbrowser.chromium.swing.internal.HeavyWeightWidget.getPeer()
        at com.teamdev.jxbrowser.chromium.swing.internal.NativeWin.getWindowHandle(SourceFile:37)
        at com.teamdev.jxbrowser.chromium.swing.internal.DisplayWatcher.attach(SourceFile:51)
        at com.teamdev.jxbrowser.chromium.swing.internal.HeavyWeightWidget.addNotify(SourceFile:261)
        at java.desktop/java.awt.Container.addNotify(Container.java:2800)
        at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4783)
       

**Additional context**
Problem started after upgrading from ZAP 2.7 to 2.8

**Comment by thc202** [comment]
Based on the stack trace ZAP is being executed with a newer version than Java 8, JxBrowser does not work with Java 9+.

**Comment by jeanbritz** [comment]
Oooh ok. Thanks! I had Java 11 installed also with Java 8.
For interest sake, how does ZAP determine which Java installation to use on your computer? In essence which Java home directory does it check?

**Comment by psiinon** [comment]
On Windows I'd guess it uses the JAVA_HOME env var
