### ISSUE TITLE
Docker container is unhealthy on fresh start.

### ISSUE THREAD

**Issue by stormmuller** [zaproxy/zaproxy#5417]
Running a fresh instance of the ZAP app using docker and webswing does not produce a healthy container.

**To Reproduce**
`docker pull owasp/zap2docker-stable` followed by `docker run -u zap -p 8080:8080 -p 8090:8090 -i owasp/zap2docker-stable zap-webswing.sh`

Then run `docker ps` and look for the "owasp/zap2docker-stable" container

**Expected behavior**
A healthy container

**Screenshots**
![image](https://user-images.githubusercontent.com/17644200/59492394-2e4d6a80-8e89-11e9-977e-4c955e2765f0.png)

Docker logs have no info and there is no other info/errors printed to screen when running container

**Software versions**
 - ZAP: Latest Stable docker build
 - Add-on: None
 - OS:  Windows 10
 - Java: N/A (running in a container)
 - Browser: N/A

**Errors from the zap.log file**
Not sure where this in the container couldn't find it in the root folder after running `docker exec -it {container id} sh` Willing to up update issue if someone can help me find this.

**Additional context**
The swing UI **does** load up when navigating to http://localhost:8080/zap. Still need to actually try and run an attack. But regardless docker heath check is concerning.

**Comment by thc202** [comment]
The health check will only work if ZAP is listening on 8080 (by default), in any case it would be unhealthy until ZAP is actually started (by accessing the required URL):
https://github.com/zaproxy/zaproxy/wiki/Docker#healthcheck

**Comment by stormmuller** [comment]
Yep, you're right thanks!

**Comment by kingthorin** [comment]
@stormmuller are you good with this being closed then?

**Comment by kingthorin** [comment]
Assuming so, no feedback in 10d.
