### ISSUE TITLE
How to Integrate Zap with Selenium scripts using java

### ISSUE THREAD

**Issue by prasathmscss** [zaproxy/zaproxy#5432]
s there any possible way to integrate zap in headless mode with selenium scripts.

here is the sample code for selenium..  please tell me step by step how to write code for zap integrate with below mention code.

Note:

1)we need to integrate zap to selenium scripts

2)zap could run in headless mode using -daemon

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import org.openqa.selenium.chrome.ChromeDriver;;
public class Google {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	    System.setProperty("webdriver.chrome.driver", ".//drivers//chromedriver.exe");
		driver=new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void sample() {
    // Test name: sample
    // Step # | name | target | value | comment
    // 1 | open | / |  | 
    driver.get("https://www.google.com/");
    // 2 | setWindowSize | 1600x860 |  | 
    driver.manage().window().setSize(new Dimension(1600, 860));
    // 3 | click | id=hplogo |  | 
    driver.findElement(By.id("hplogo")).click();
    // 4 | click | id=hplogo |  | 
    driver.findElement(By.id("hplogo")).click();
    // 5 | click | id=lga |  | 
    driver.findElement(By.id("lga")).click();
  }
}

**Comment by kingthorin** [comment]
Please don't ask questions as issues - the ZAP User Group https://groups.google.com/group/zaproxy-users is a much better places for questions.
