### ISSUE TITLE
OWASP ZAP 2.8.0 Launch Firefox fails

### ISSUE THREAD

**Issue by kae36** [zaproxy/zaproxy#5434]
If I select "Manual Explore" and I select Launch Chrome it works fine, but if I try to Launch Firefox, the Firefox window comes up and then disappears. I have Firefox Quantum version 67.0.3 (64-bit) is installed (I'm getting ready to update to 67.0.4).  Does anyone else have this problem (or is there a solution)?  I noticed someone had this problem a while ago, but it seemed like it was their version of virus scanner (mine is different and isn't complaining about an infection).

This is the error I found in the zap.log file: [zap.log snippit](https://gist.github.com/kae36/666da3f83a73ac7e5dcbb460ee37f539)

[Here are the add-ons that came with the installation.](https://gist.github.com/kae36/9c4e32900c639f9ee778a85a82a5bf3d) I didn't load any extra add-ons.

Has anyone else seen this or have a work around or is this a bug with OWASP ZAP or Firefox?

Thanks for listening.
Alan

**Comment by thc202** [comment]
What's the path shown in Options > Selenium > geckodriver? Can you run `--version` on it? (It should be 0.24.0.)

**Comment by kae36** [comment]
It's not version 0.24.0.  It's version 0.19.1.

C:\Users\keaedwar>"C:\Users\keaedwar\OWASP ZAP\webdriver\windows\64\geckodriver.exe" --version
geckodriver 0.19.1

I went to https://github.com/mozilla/geckodriver/releases/ and downloaded 0.24.0 for my OS. I just moved the old geckodrive.exe to geckodriver-v0.19.0 and copied version 0.24.0 to the same location.

It's working now.   Thank you @thc202 !!!!!!!

**Comment by kae36** [comment]
Should I close the issue, since @thc202 solved it? Do I close it or does someone else do that?  I don't know the rules.

**Comment by kingthorin** [comment]
@kae36 thanks for letting us know. You could close it but since I'm here I'll go ahead and do it.

**Comment by thc202** [comment]
Odd, ZAP should have replaced that with newer version, it bundles 0.24.0.
