### ISSUE TITLE
forced browse: Requests aren't always counted

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#5437]
**Describe the bug**
When a short (or perhaps any) custom list is added, the "Num Requests" counter doesn't increase while the scan is run.

**To Reproduce**
1. Launch ZAP
2. Goto the Forced Browse panel, access the option (Gear button) and load a short custom list (4 or 5 entries).
3. Run "Force Browse Site" against a target
4. Notice that "Num Requests" stays at zero.

**Expected behavior**
Requests should be properly incremented.

**Screenshots**
![image](https://user-images.githubusercontent.com/7570458/59931584-4e45d680-9413-11e9-843d-cb711fc62f3b.png)

**Software versions**
 - ZAP: Dev (as of 20190621)
 - Add-on: bruteforce, version=9.0.0
 - Java: JDK 1.8.0_211

Code ref: https://github.com/zaproxy/zap-extensions/tree/master/addOns/bruteforce

**Comment by gsilvapt** [comment]
Hi!

Using version 2.8, I am unable to reproduce this bug as the picture below shows:

![Screenshot from 2019-10-03 18-26-08](https://user-images.githubusercontent.com/7786556/66149631-667ce280-e60b-11e9-881d-9ee296fcfc12.png)

I'm trying to look for previous versions in the log to see if there was anything changed regarding this package but I admit I am not that much aware of where the counter is being updated.

Hope this helps :+1:

**Comment by savva-k** [comment]
I'd like to work on this one

**Comment by thc202** [comment]
Assigned.

**Comment by thc202** [comment]
For this issue worth checking `DirBusterManager` and `BruteForce#run`.
