### ISSUE TITLE
ZAP produces empty xhtml reports when run from Jenkins since 18/05/2019

### ISSUE THREAD

**Issue by hnestorova** [zaproxy/zaproxy#5440]
**Describe the bug**
We run our recorded clean sessions using and get empty xhtml reports since 18/05/2019:

**Software versions**
Official OWASP ZAP Jenkins Plugin - 1.1.0
ZAP D-2019-05-28
 - Browser: Chrome

**Errors from the zap.log file**
In the Jenkins console I see:
05:01:37 [ZAP Jenkins Plugin] CLEAR WORKSPACE OF PREVIOUS REPORT(S) [ TRUE ]
05:01:37 	CLEARING WORKSPACE OF [ .xml, .html, .xhtml, .json ]
05:01:38 	CLEARING WORKSPACE/REPORTS OF [ .xml, .html, .xhtml, .json ]
05:01:38 		DELETED [ JENKINS_ZAP_VULNERABILITY_REPORT_1089.xhtml ]
05:01:38 
05:01:38 [ZAP Jenkins Plugin] GENERATE REPORT(S) [ TRUE ]
05:01:38 	EXPORT REPORT FORMAT CHECK [ TRUE ]
05:01:38 		[ XHTML ] IS A VALID FORMAT
05:01:38 
05:01:38 	INITIALIZE EXPORT REPORT VARIABLES FOR [ XHTML ] EXPORT
05:01:38 		API KEY [ ZAPROXY-PLUGIN ]
05:01:38 		ABSOLUTE PATH [ c:\Jenkins\workspace\ZAPTestJob\reports\JENKINS_ZAP_VULNERABILITY_REPORT_1090.xhtml ]
05:01:38 		FILE EXTENSION [ .xhtml ]
05:01:38 		SOURCE DETAILS [ JENKINS_ZAP_VULNERABILITY_REPORT_1090;Jenkins: ${ENV, var="BUILD_URL"}console;ZAP Jenkins PRIVATE Attack;${ENV, var="PRIVATE"};${ENV, var="PRIVATE"};${ENV, var="PRIVATE"};${ENV, var="PRIVATE"};ZAP Jenkins PRIVATE Attack Report ]
05:01:38 		ALERT SEVERITY [ t;t;t;t ]
05:01:38 		ALERT DETAILS [ f;f;t;f;f;f;f;f;f;f; ]
05:01:38 
05:01:38 1646797 [ZAP-ProxyThread-550] ERROR org.zaproxy.zap.ZAP$UncaughtExceptionLogger  - Exception in thread "ZAP-ProxyThread-550"
05:01:38 java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
05:01:38 	at org.zaproxy.zap.extension.exportreport.export.ExportReport.generateReport(ExportReport.java:192)
05:01:38 	at org.zaproxy.zap.extension.exportreport.ExtensionExportReport.generateReport(ExtensionExportReport.java:300)
05:01:38 	at org.zaproxy.zap.extension.exportreport.ExportReportAPI.handleApiAction(ExportReportAPI.java:170)
05:01:38 	at org.zaproxy.zap.extension.api.API.handleApiRequest(API.java:440)
05:01:38 	at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(ProxyThread.java:456)
05:01:38 	at org.parosproxy.paros.core.proxy.ProxyThread.run(ProxyThread.java:318)
05:01:38 	at java.base/java.lang.Thread.run(Thread.java:834)
05:01:38 Caused by: java.lang.ClassNotFoundException
05:01:38 	at org.zaproxy.zap.control.AddOnClassLoader.findClass(AddOnClassLoader.java:269)
05:01:38 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
05:01:38 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
05:01:38 	... 7 more
05:01:38 java.net.SocketException: Unexpected end of file from server

**Additional context**
html reports are successfully generated for the same sessions

**Comment by thc202** [comment]
This is caused by newer (9+) Java version.

Closing, duplicate of #4214.

**Comment by hnestorova** [comment]
@thc202 ok, but what fix can I apply to resolve this?

**Comment by thc202** [comment]
Use Java 8 or the new version of the add-on, once released (should be done today).

**Comment by hnestorova** [comment]
ok then, i will try updating the addons later today/tomorrow

**Comment by thc202** [comment]
The new version is now available.

**Comment by hnestorova** [comment]
great, thank you. I will now update all add-ons to see how it will go afterwards
