### ISSUE TITLE
ZAP configuration object of nodejs client implementation do not permit proxy

### ISSUE THREAD

**Issue by iAbhishek91** [zaproxy/zaproxy#5441]
**Problem statement**
I'm unable to connect ZAP with ZAP client (zaproxy - nodejs implementation) which are behind a proxy.

I am using a Docker container to run ZAP. However, to access the ZAP endpoint I need to pass through a corporate proxy.

Currently, the object looks like:
``` javascript
const zapOptions = {
  apiKey: null,
  proxy: 'http://localhost:8080',
};
```

**Proposed solution**
zaproxy nodejs implementation to accept proxy details apart from zap end point.

``` javascript
const zapOptions = {
  apiKey: null,
  **zapEndPoint: 'http://localhost:8080',
  proxy: {
     httpProxy: '....',
     sslProxy: '.....',
     authentication: '...',
  }**
};
```

**Currently to overcome this issue**
I'm using a local installation of ZAP, as I am not able to access ZAP hosted behind the proxy.

**Comment by kingthorin** [comment]
Ping @binarymist  :grin:

**Comment by binarymist** [comment]
Hi @iAbhishek91

Thanks for your detailed description! I think this should be possible, I'll try and get a chance to look at it tonight.

**Comment by binarymist** [comment]
As you have your proxy environment currently setup @iAbhishek91, it'd be great if you could make the necessary changes, test them, and submit a pull request, I can then test them locally, then make the changes to the generator, and take this issue through the process of getting it to NPM. The first place to look will be [here](https://github.com/zaproxy/zap-api-nodejs/blob/master/src/index.js#L57).

@kingthorin: it looks like the [generator(s)](https://github.com/zaproxy/zaproxy/wiki/ApiClientGen) have been moved?

Thanks.

**Comment by kingthorin** [comment]
Yup after the move to gradle based builds the paths are slightly changed. I’ll update that wiki page shortly. In the meantime you can find them here: https://github.com/zaproxy/zaproxy/tree/develop/zap/src/main/java/org/zaproxy/zap/extension/api

**Comment by binarymist** [comment]
@iAbhishek91 Shout out if you need any tips/pointers/help. Also if there is any urgancy?... and I'll do my best to make time in a very busy schedule. Thanks.

**Comment by iAbhishek91** [comment]
Thanks, @binarymist. I will very soon submit a PR requesting the change. Please review it. Thanks.

**Comment by iAbhishek91** [comment]
This is weird:

I tried to fix this, but when I started the connection is working without proxy

below code which is working:

```js
request(
 'http://zap/JSON',
 {
    proxy: 'http://zap.endpoint.behind.proxy',
 },
 (err, res, body) => {
  console.log('status code', r.statusCode);
}
);
```

But the project implementation is not working:

```js
const zapOptions = {
   apiKey: null,
   proxy: 'http://zap.endpoint.behind.proxy',
};

const zaproxy = new ZapClient(zapOptions);

zaproxy.core.setOptionUseProxyChain(true, (e) => {
  console.log(e);
})
```

Error thrown:

```sh
Error: connect ECONNREFUSED 127.0.0.1:8080
```

Not sure what I am missing :(

**Comment by iAbhishek91** [comment]
I found the root cause. ZAP running behind a corporate proxy is started without disabling the `API-KEY`.

Running the ZAP image with below command make it worked.

```sh
zap.sh
-daemon
-port 4446
-host 0.0.0.0
-config api.addrs.addr.name=.*
-config api.addrs.addr.regex=true
-config api.disablekey=true
```

Since this is working for me, I am closing this issue.

**Comment by psiinon** [comment]
Thanks for letting us know!
