### ISSUE TITLE
java.lang.NullPointerException in Session Fixation

### ISSUE THREAD

**Issue by hnestorova** [zaproxy/zaproxy#5444]
I noticed this one in the Jenkins console:

16:33:31 330692 [Thread-6] INFO org.parosproxy.paros.core.scanner.HostProcess  - start host http://PRIVATE-PRIVATE-PRIVATE.PRIVATE.PRIVATE| SessionFixation strength MEDIUM threshold MEDIUM
16:33:31 330695 [ZAP-ActiveScanner-0] ERROR org.zaproxy.zap.extension.ascanrulesBeta.SessionFixation  - An error occurred checking a url for Session Fixation issues
16:33:31 java.lang.NullPointerException
16:33:31 	at org.zaproxy.zap.extension.ascanrulesBeta.SessionFixation.scan(SessionFixation.java:149)
16:33:31 	at org.parosproxy.paros.core.scanner.AbstractPlugin.run(AbstractPlugin.java:343)
16:33:31 	at java.base/java.lang.Thread.run(Thread.java:834)

**Software versions**
- Official OWASP ZAP Jenkins Plugin - 1.1.0
- ZAP D-2019-05-28
- Java: openjdk version 11.0.2

**Comment by kingthorin** [comment]
>  16:33:31 at org.zaproxy.zap.extension.ascanrulesBeta.SessionFixation.scan(SessionFixation.java:149)

https://github.com/zaproxy/zap-extensions/blob/ed09d352f5c43bf14329df18b17b2d85b9cc9af6/addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/SessionFixation.java#L149

```java
&& requestUri.getPath().equals(loginUri.getPath())) {
```

I guess technically one or both paths could be null.

**Comment by thc202** [comment]
It's the path of `requestUri`.
