### ISSUE TITLE
Adding Rules to ZAProxy

### ISSUE THREAD

**Issue by ShubhamBhurke** [zaproxy/zaproxy#5445]
How can I add my own rules to ZAProxy
My Research- I came across few links related to Active and Passive Scan Rules.
I am a beginner please forgive my mistakes:)

**Comment by psiinon** [comment]
Please ask questions like this on the ZAP developer group: https://groups.google.com/group/zaproxy-develop
BTW the answer is yes, we'll give more details when you ask on the group :)
