### ISSUE TITLE
cannot scan on localhost

### ISSUE THREAD

**Issue by lesar** [zaproxy/zaproxy#5448]
**Describe the bug**
I have enable on firefox proxy listen on localhost port 8090 and empty 'no proxy for'.  
on zap I have setup option to listen local proxy on localhost port 8090

I am on ubuntu 16.04.2  
Firefox 67.0.3 (64 bit)  
Java: openjdk version "1.8.0_212"
ZAP: 2.8.0

If I browse on localhost nothing goes on history.  

If I use quick menu and manual explore the new firefox browser work well  

seams some extra setting on browser lost.  

I have no idea how to solve.  

can someone help?  

regards

**Comment by thc202** [comment]
Newer versions of Firefox no longer proxy localhost by default, you need to set the preference `network.proxy.allow_hijacking_localhost` to `true`.
The browser launched by ZAP is already configured to proxy.

**Comment by thc202** [comment]
Closing with previous comment.

**Comment by lesar** [comment]
thanks very much, it work using thc202 tip:  
`network.proxy.allow_hijacking_localhost to true.`
on url  `about:config`

regards,
Leonardo

**Comment by thc202** [comment]
Thanks for letting us know!
