### ISSUE TITLE
407 and 501 errors from external proxy while using Requester Add-on with external proxy configured.

### ISSUE THREAD

**Issue by wadim-al** [zaproxy/zaproxy#5457]
**Describe the bug**
After upgrading from ZAP 2.7.0 to 2.8.0 if I send a request with Requester Add-on while I've configured the external proxy I'm getting HTTP/1.1 407 Proxy Authentication Required response from the proxy, and if I continue sending requests it also shows HTTP/1.1 501 Not Implemented responses. The external proxy works ok when I'm not using the Requester plugin e.g. when inspecting the browser traffic with ZAP. The 2.7.0 version works ok. The password for the proxy doesn't have any special characters, it is alphanumeric. Configuring proxy realm didn't help. 
For the 407 code I'm getting Proxy-Authenticate: Basic realm="Please enter your  credentials" response header.
For the 501 code I'm getting the 'Unsupported Request Method and Protocol' error message.

**To Reproduce**
1. Go to Tools - Options - Connection
2. Configure the ougoing proxy by enabling outgoing proxy and authentication checkboxes and entering host, port, login and password.
3. Restart ZAP
4. Open a new Requester add-on tab and make a request to somewhere.
5. Check error messages from squid proxy server.

**Expected behavior**
As with ZAP 2.7.0 I expect to be able to make requests with the Requester Add-on when the outgoing proxy is enabled.

**Screenshots**
![javaw_2019-07-03_10-19-21](https://user-images.githubusercontent.com/29713984/60571652-b2a25780-9d7c-11e9-83df-d0e33c1e43ba.png)
![javaw_2019-07-03_10-19-32](https://user-images.githubusercontent.com/29713984/60571659-b59d4800-9d7c-11e9-84c1-8600fb0c813d.png)

**Software versions**
 - ZAP: 2.8.0
 - Add-on: Requester 3.0.0
 - OS: Windows 10
 - Java: Oracle Java JRE version "jre1.8.0_211"
 - Browser: N/A

**Errors from the zap.log file**
No errors in zap.log
Attached responses containing the proxy replies.
[rs1.txt](https://github.com/zaproxy/zaproxy/files/3353706/rs1.txt)
[rs2.txt](https://github.com/zaproxy/zaproxy/files/3353707/rs2.txt)

**Comment by kingthorin** [comment]
Does the core manual request editor work? (From the Tools menu)

**Comment by thc202** [comment]
This is most likely #5518. Worth trying with a weekly release.

**Comment by kingthorin** [comment]
@wadim-al any update?

**Comment by wadim-al** [comment]
No more reproducible in zap-D-2019-12-09.
Tested the latest weekly release.
Active scan, spider, integrated request editor and Requester Add-on are using the proxy now as expected.

**Comment by kingthorin** [comment]
Thanks for letting us know, glad you got it working.
