### ISSUE TITLE
Angular Js apps

### ISSUE THREAD

**Issue by mohamedoul** [zaproxy/zaproxy#5467]
Hello, 
I want to scan an Angular Js based app using CI/CD (owasp zap plugin with jenkins). 
But only the first page of the app is scaned. 
it seems that the plugin does not regognise the urls with (# )
Thank u

**Comment by psiinon** [comment]
Browsers dont send the URL fragment (the part after the `#`) to the server, so ZAP doesnt get to see it.
You'll probably need to use the Ajax spider to explore your app.
In any case you should ask on the relevant user group: https://groups.google.com/forum/#%21forum/zaproxy-jenkins
