### ISSUE TITLE
zap-api-dotnet - proxy to owasp/zap2docker-stable on Azure Container Instances

### ISSUE THREAD

**Issue by pkbfs** [zaproxy/zaproxy#5473]
Hi,

I would like to be able to use the zap-api-dotnet package with a docker image of zap 

owasp/zap2docker-stable

on Azure Container Instances.

=======================
Manual Access to API page
=======================

When zap is started in the container instance it logs

	9668 [ZAP-daemon] INFO org.zaproxy.zap.DaemonBootstrap  - ZAP is now listening on 0.0.0.0:8090

If I try to browse to the proxy address say something like 

myzapdockercontainer.uksouth.azurecontainer.io:8090

for a container that I have created I get an error instead of the API page.

	Failed to read http://myzapdockercontainer.uksouth.azurecontainer.io:8090/ within 20 seconds, 
	check to see if the site is available and if so consider adjusting ZAP's read time out in the Connection options panel.

However if I configure my browser to proxy to myzapdockercontainer.uksouth.azurecontainer.io:8090 and then enter http://zap

I can access the API page.

I did try to use the following parameter 

-config api.addrs.addr.name='(127.0.0.1|myzapdockercontainer.uksouth.azurecontainer.io)' 

when using zap.sh but without success

==========================
Accessing the API using zap-api-dotnet
==========================

I tried to use the zap-api-dotnet package but found I was having a similar issue.

It needs to proxy to the external address first

myzapdockercontainer.uksouth.azurecontainer.io:8090 

and then connect to the API via http://zap

Looking at the constructor code the ClientApi creates a proxy to itself

	public ClientApi(string zapAddress, int zapPort, string apiKey)
	{
		this.zapAddress = zapAddress;
		this.zapPort = zapPort;
		this.apiKey = apiKey;
		webClient = new SystemWebClient(zapAddress, zapPort);
		InitializeApiObjects();
	}
		
	public SystemWebClient(string proxyHost, int proxyPort)
	{
		webProxy = new WebProxy(proxyHost, proxyPort);
		webClient = new WebClient();
		webClient.Proxy = webProxy;
	}

in the example included with the solution the hostname is localhost so is the WebProxy needed?

Would the following not be preferable?

	public ClientApi(string zapAddress, int zapPort, string apiKey)
	{
		this.zapAddress = zapAddress;
		this.zapPort = zapPort;
		this.apiKey = apiKey;

		webClient = new SystemWebClient();

		InitializeApiObjects();
	}

	public ClientApi(string proxyHostName, int proxyPort , string zapAddress, int zapPort, string apiKey)
	{
		this.zapAddress = zapAddress;
		this.zapPort = zapPort;
		this.apiKey = apiKey;

		this.webClient = new SystemWebClient(proxyHostName, proxyPort);

		InitializeApiObjects();
	}
	
	public SystemWebClient()
	{
		webClient = new WebClient();
	}

	public SystemWebClient(string proxyHost, int proxyPort)
	{
		webProxy = new WebProxy(proxyHost, proxyPort);
		webClient = new WebClient();
		webClient.Proxy = webProxy;
	}
		
You then have the choice to connect to a local instance of zap and specify the zapAddress and zapPort, using say just localhost like in a browser

or

proxy to a docker instance first and then also specify the zapAddress and zapPort [which could default to http://zap and 80]

Cheers
pkbfs

**Comment by thc202** [comment]
The ZAP API clients should proxy always through ZAP and use the `zap` domain for the API requests, I thought this one was doing that.

**Comment by kingthorin** [comment]
Can someone confirm or deny?

**Comment by thc202** [comment]
This client is not using `zap` domain (yet).

**Comment by kingthorin** [comment]
Okay thanks 👍

**Comment by thc202** [comment]
Closing, zaproxy/zap-api-dotnet#10 has been merged.
