### ISSUE TITLE
OWASP ZAP 2.8.0 doesn't show localhost traffic in its history

### ISSUE THREAD

**Issue by nlykkei** [zaproxy/zaproxy#5474]
**Describe the bug**
OWASP ZAP 2.8.0 doesn't show localhost traffic in its history.

**To Reproduce**
Configure Firefox to use ZAP Proxy as HTTP proxy, and visit any localhost path in the browser, e.g. http://localhost/login.php, in the browser. Remember to remove "localhost" from "No proxy for" in Firefox proxy configuration.

**Expected behavior**
I expect that ZAP Proxy shows localhost in its history.

**Screenshots**

**Software versions**
 - ZAP: 2.8.0
 - OS: macOS Mojave
- Java: 1.8.0._202-b08
 - Browser: Firefox

**Comment by kingthorin** [comment]
Up to date versions of Firefox require setting "network.proxy.allow_hijacking_localhost" to "true" in about:config.
