### ISSUE TITLE
Allow Replacer to replace Host header

### ISSUE THREAD

**Issue by nlykkei** [zaproxy/zaproxy#5475]
**Describe the bug**
Replacer 7.0.0 won't replace Host header in HTTP requests. However, it will replace User-Agent and other headers in requests.

**To Reproduce**
Create a new Replacer rule with "Match String" set to "Host" and "Replacement" to anything. Remember to enable the rule.

**Expected behavior**
I expect the "Host" HTTP request header to be changed to  "Replacement" string.

**Software versions**
 - ZAP: 2.8.0
 - Add-on: Replacer v. 7.0.0
 - OS: macOS Mojave
 - Java: 1.8.0
 - Browser: Firefox

**Comment by kingthorin** [comment]
This isn’t a Replacer issue it’s a core issue. 

Closing as duplicate https://github.com/zaproxy/zaproxy/issues/1318.

**Comment by nlykkei** [comment]
Do you know of any workarounds? When is the issue planned to be fixed?

**Comment by kingthorin** [comment]
You can get around it with an HttpSender script and some creative coding (I don’t have an example handy).

There might be other solutions, it depends why you’re trying to change it.

**Comment by nlykkei** [comment]
Thanks. I'm trying to change it, because I SSH port forward and the remote server listening on localhost needs HTTP Host header set to valid domain name, not an IP address. Any ideas? :)

**Comment by kingthorin** [comment]
Add a hosts file entry and then use the “name”.

Ex.
target.nlykkei.com    127.0.0.1

**Comment by nlykkei** [comment]
Thanks. The problem is that ZAP also adds the :port part - and it's not really possible to bind SSH forwarding to local port 80, since Apache is running there :( 
Is there any tutorial on how to use the HttpSender script?

**Comment by kingthorin** [comment]
What’s wrong with accessing http://target.nlykkei.com:81 (assuming your local SSH is listening on 81)?

No there isn’t a tutorial, it’s not really something that’s supported.

**Comment by nlykkei** [comment]
If I access that URL from my browser, the Host header is set to "target.nlykkei.com:81", which is rejected by the server, which expects a Host header without the port (:81) part... :-( 

In order to use HttpSender (.py) script, where should I place it and how do I enable it?

This Host header issue makes it hard to use ZAP for my current jobs, where the Host header plays a crucial role wrt. virtual hosting.

**Comment by kingthorin** [comment]
Build a testing machine that doesn’t have Apache using the port you need?

I’m on my cell right now so don’t have an easy way to lookup the code details.

HttpSender is just a type of script that you can create within zap (Script Tree/Console), to enable it you simply use the context menu (like the majority of zap scripts).

There’s some HttpSender community contributions here: https://github.com/zaproxy/community-scripts/tree/master/httpsender
Unfortunately none of them do what you need. 

The code you’d need is in one of the scan rules in the zap-extensions repo but I don’t recall exactly which one.

**Comment by nlykkei** [comment]
Are they loaded using "Load Add-on File.."? I can't find a way to load those HttpSender community contributions scripts.
Also, will this core issue be fixed soon, or will it persist in the foreseeable future?

**Comment by kingthorin** [comment]
No s ripts aren't add-ons. Unfortunately if you're not already familiar with scripting in ZAP it's unlikely that this is going to be a good solution for you, or that you'll be able to adapt the mentioned code to your needs.

The core issue is being worked on but unlikely to be addressed before 2.9.0 it maybe even 3.0.0.

The quickest solution is to use a system on which you can implement an appropriate hosts entry without conflicting with other daemons.

**Comment by thc202** [comment]
Reopening, this requires changes in the Replacer add-on.
