### ISSUE TITLE
new document for beginners about interpreting results and identifying false positives

### ISSUE THREAD

**Issue by dannaksan12** [zaproxy/zaproxy#5481]
As a beginner it can be very hard to wrap your head around how to interpret the results you get by e,g, automation reports, the HUD or manual exploration.
When I used the HUD recently for some light vulnerability assessment on a new feature I had to look up a lot on google and kinda find my own way of working to interpret the results and verify any false positives - I emailed our security team to make sure that I did not interpret anything wrong. 
It would therefore be good to have a high level document that helps people kicking off their analysis. 
Things to include are e.g.
- what are false positives and why we need to spot them
- explain a bit more about the information the HUD gives (e.g. CWE Id) and how it can be used to get message across

**Comment by kingthorin** [comment]
Are you and your security team volunteering to have a first go at it? :+1: :wink:

**Comment by kingthorin** [comment]
https://www.zaproxy.org/faq/how-do-i-handle-a-false-positive/
