### ISSUE TITLE
DEB/RPM Packaging?

### ISSUE THREAD

**Issue by leo-lb** [zaproxy/zaproxy#5482]
I am surprised to find out that OWASP Zap Proxy isnt packaged for major Linux distributions, is there a licensing issue that causes inclusion rejection from distributions? I'd be happy to start working on it as soon as I get time. Note that I'm not a package maintainer so it might take some time for me to get things done but I could ask for some help.

**Comment by psiinon** [comment]
Dont these count? https://github.com/zaproxy/zaproxy/wiki/Downloads#linux-repos

**Comment by thc202** [comment]
It's also included in Kali and someone was working on adding it to Debian.

**Comment by leo-lb** [comment]
@psiinon I thought these packages were only for OpenSUSE, but apparently they are for every distributions, however, that's not exactly what I was asking for, I'm wondering why OWASP Zap is not included by default in Fedora official repos or Debian. Considering it's under Apache license, I think it's eligible for inclusion.

**Comment by leo-lb** [comment]
> It's also included in Kali and someone was working on adding it to Debian. Also present in NixOS.

Kali Linux is different because their inclusion policy even allows proprietary software.

**Comment by leo-lb** [comment]
One blocker for inclusion could be that OWASP Zap phones home through `bit.ly` which is another third party. https://github.com/zaproxy/zaproxy/blob/65afe6af651cc789e96a3079edd86dd025ca8da1/zap/src/main/java/org/zaproxy/zap/extension/autoupdate/ExtensionAutoUpdate.java#L101

**Comment by leo-lb** [comment]
Also, AFAICT, there's no signature verification of the packages being downloaded through built in automatic updates, so it means `Github` and `Bit.ly` currently can deliberately install malware on every computer having OWASP Zap installed, either them directly, or someone that compromises their infrastructure.

**Comment by psiinon** [comment]
Why isnt included by default in Fedora or Debian? Because we have no experience in making that happen :)
But it would be great if it could happen.
I am not aware of any licensing issues that should prevent it.
The reason why we use bitly is explained here: https://github.com/zaproxy/zaproxy/wiki/FAQcallshome
I dont think this should be a blocker to inclusion - we could have a build option to turn that off for distributions that require it.
We would also be happy to look at separate packages for add-ons - again thats not something we have experience with but I cant see that being a problem.
The urls we use to check for updates such as https://github.com/zaproxy/zap-admin/blob/master/ZapVersions-2.8.xml are accessed via HTTPS and include a sha-256 hash. but you are right, `github` or `bitly` could serve up malware with the right hashes. Again this is something that can be addressed if its a blocker.

**Comment by leo-lb** [comment]
@psiinon I have reached to some people within Fedora ( https://fedoraproject.org/wiki/Security_Lab ) - and I will get back to you with more information.

**Comment by leo-lb** [comment]
so I got an answer;

```
To be frank that will be a lot work. Existing SPEC files usually don't
match the requirements [1] which Fedora has for packages.

Another option could be to provide a flatpak.

Both options requires a review. For the RPM package this can be very
time consuming. The issue is that zap is written in Java and not many
people like to do review on this kind of packages because they are not
straight-forward and it's hard to track licensing and dependency issues.

To include it in the Fedora Security Lab is has to be a RPM package.
To run on Fedora a flatpak would be sufficient and would definitely
remove the hassle of the installation itself and the required steps to
get it running properly.

Kind regards,

Fabian

[1] https://docs.fedoraproject.org/en-US/packaging-guidelines/Java/
```

I will attempt the RPM approach on my own when I get the time. Flatpak could be good but I prefer RPM until the flatpak ecosystem matures.

**Comment by psiinon** [comment]
@leo-lb thanks for the update, and let us know if you need any help with anything. I'm not surprised its non trivial :/

**Comment by leo-lb** [comment]
@psiinon If you are aware of any third party code that you have included that could cause licensing issues, as well as pinpoint me where I can find all the dependencies for OWASP Zap and their respective licenses, that would help.

**Comment by leo-lb** [comment]
Easy way would be to run something like this: https://github.com/hierynomus/license-gradle-plugin -- Will do this ASAP.

**Comment by thc202** [comment]
https://github.com/zaproxy/zaproxy/blob/develop/LEGALNOTICE.md

**Comment by leo-lb** [comment]
Okay, thanks, seems compatible with Fedora guidelines at first glance.

**Comment by thc202** [comment]
Closing, there's nothing else to do/answer. If you have further questions let us know through the [developer group](https://groups.google.com/group/zaproxy-develop).
