### ISSUE TITLE
List item name becomes invisible when highlighted.

### ISSUE THREAD

**Issue by Syc0x00** [zaproxy/zaproxy#5485]
**Describe the bug**
Within the fuzzer add payload menu when I select file fuzzers and get the option of what file fuzzers to add selecting an item will cause it to go invisible.

**To Reproduce**
- Fuzz anything
- Select part of the message and add a payload
- Select file fuzzers and then highlight an item in the list by clicking on it

**Expected behavior**
I expect to be able to see the item I've selected.

**Screenshots**
Here I had `db2_default_pass.txt` selected and then I moved down 1 with the arrow down key.

![Screen Shot 2019-07-19 at 1 06 20 PM](https://user-images.githubusercontent.com/20033376/61562807-07093080-aa27-11e9-9345-8561c6dbc99e.png)
![Screen Shot 2019-07-19 at 1 12 02 PM](https://user-images.githubusercontent.com/20033376/61562809-083a5d80-aa27-11e9-9f6f-c084a9d8837f.png)

**Software versions**
 - ZAP: 2.8.0
 - Add-on: Defaults
 - OS: MacOS Mojave 10.14.5
 - Java: openjdk 12.0.1 2019-04-16

**Errors from the zap.log file**
Nothing from `tail -F zap.log`

**Additional context**

**Comment by thc202** [comment]
Thanks for the report, this is a know issue with macOS. Closing as duplicate of #3988.
