### ISSUE TITLE
Anti-CSRF tokens not encoded in authentication requests

### ISSUE THREAD

**Issue by mrtc0** [zaproxy/zaproxy#5490]
**Describe the bug**

`+` is not escape to `%2b` in `authorized_token` .

**To Reproduce**
1. Run follow script

```python
from zapv2 import ZAPv2

target = 'https://localhost/'
apikey = 'key'
context = "sample"

zap = ZAPv2(apikey=apikey)

zap.urlopen(target)

authmethodname = 'formBasedAuthentication'
authmethodconfigparams = "loginUrl=https://localhost/users/sign_in&loginRequestData=authenticity_token%3DBGF5HtOISJkEnm6pX27cZ8jO8oFkX091k8VOrDO79oSBNOWiPvypguaxSzwDdVma1EH1g7p1w3sLKf%252FTrFXOdA%253D%253D%26user%255Bemail%255D%3D%7B%25username%25%7D%26user%255Bpassword%255D%3D%7B%25password%25%7D%26signin_return_to%3D%26commit%3DLogin%26user%255Bremember_me%255D%3D0"

zap.core.new_session()
contextid = zap.context.new_context(context)
print(contextid)
print(zap.context.include_in_context(context, 'https://localhost.*'))

print(zap.context.context(context))
print(zap.authentication.set_authentication_method(contextid, authmethodname, authmethodconfigparams))
print(zap.authentication.set_logged_in_indicator(contextid, loggedinindicatorregex='\QYou are being\E'))
userid = zap.users.new_user(contextid, 'user1')
print(userid)
print(zap.users.set_authentication_credentials(contextid, userid, 'username=username&password=password'))
print(zap.users.set_user_enabled(contextid, userid, True))

zap.spider.scan_as_user(contextid, userid, target)
```

2. See History

if `+` not contains in `authorized_token`, loggin successful.
but if contains '+' in authorized_token, login failed ( `422 Unprocessable Entity` ). because, `+` is not escaped to `%2b` .

**Expected behavior**

`+` will encode to `%2b`, loggin success.

**Screenshots**

- `+` is not encoded when response code is 422

![Screenshot from 2019-07-24 19-03-42](https://user-images.githubusercontent.com/5842353/61785448-aaeb4580-ae46-11e9-9acf-eab649be067b.png)

- `+` is encode to `%2b` when response code is 302

![Screenshot from 2019-07-24 19-03-52](https://user-images.githubusercontent.com/5842353/61785449-ab83dc00-ae46-11e9-8a58-cdb82d02bead.png)

**Software versions**
 - ZAP: 2.8.0
 - OS: Arch Linux 5.2.0-arch2-1-ARCH
 - Java: 12.0.1

**Additional context**

Please show me how to if any parameter can encode.

**Comment by thc202** [comment]
ZAP does not change the POST data (other than replace the username/password), it's up to you to provide the data properly encoded. You should be able to encode it in the Python script before calling the API.

**Comment by mrtc0** [comment]
`authorized_token` is CSRF Token. Therefore, ZAP get a this token from the page that set in the Login Form Target URL of Session Properties.
Is it possible to hook parameters when zap sends an Authentication Request ?

**Comment by thc202** [comment]
Sorry, I missed the anti-CSRF token.

Yes, with HTTP Sender script, e.g.:
https://github.com/zaproxy/community-scripts/tree/master/httpsender

**Comment by mrtc0** [comment]
Thank you for creating a PullRequest. 
Close this issue once it is merged.
