### ISSUE TITLE
Unit tests for CacheableScanner

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#5500]
Create unit tests for [CacheableScanner](https://github.com/zaproxy/zap-extensions/blob/master/addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/CacheableScanner.java).

Unit tests should test all of the associated functionality and include tests for false positives.
The tests should at least check the number of alerts and the parameters and evidence (as appropriate). Additional checks can be made if thought useful.
Tests for other rules can be found in https://github.com/zaproxy/zap-extensions/tree/master/addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules

**Comment by psiinon** [comment]
This issue is part of the ZAP Unit Test Bounty: https://www.bountysource.com/issues/77792264-unit-tests-for-cacheablescanner
Bounties will be paid only when the PR has been merged. The PRs must test all of the associated rule functionality and must conform to our Development Rules and Guidelines: https://github.com/zaproxy/zaproxy/wiki/DevGuidelines#unit-test-specific-guidelines

**Comment by bunysae** [comment]
I want to start working on this. My first idea is to mock the `alertNonStorable` with mockito.

**Comment by thc202** [comment]
Could you be more specific on what will be mocked? (The tests can raise alerts and assert them.)

**Comment by bunysae** [comment]
When writing the last comment, i didn't see, that the test can verify the alerts.

**Comment by thc202** [comment]
OK, I'd suggest taking a look at [existing tests](https://github.com/zaproxy/zap-extensions/tree/master/addOns/pscanrulesAlpha/src/test/java/org/zaproxy/zap/extension/pscanrulesAlpha) to check how they work/are written. Basically you just need to scan messages and assert the alert(s) raised (or not) are the expected.

**Comment by thc202** [comment]
@bunysae you should be able to claim the bounty.
