### ISSUE TITLE
Does the riskdesc field in ZAP Report describe Impact (Likelihood) or Likelihood(Impact)?

### ISSUE THREAD

**Issue by synopsys-mehtaa** [zaproxy/zaproxy#5504]
Example:
<riskdesc>Medium (Medium)</riskdesc>

**Comment by synopsys-mehtaa** [comment]
For example: 
<riskdesc>Medium (Medium)</riskdesc>

**Comment by kingthorin** [comment]
Please don't ask questions as issues - the ZAP User Group https://groups.google.com/group/zaproxy-users is a much better place for questions.

It's `Risk (Confidence)`
