### ISSUE TITLE
SQLNonTransientConnectionException on ActiveScanAPI call

### ISSUE THREAD

**Issue by fillodemanuel** [zaproxy/zaproxy#5505]
Hi,

I'm developing a tool that makes use of ZAP to execute a series of tests. When the tool is deployed it launches ZAP through the zap.bat script and when it's up and ready, i use the API to set an initial configuration. Amongst other things, i'm setting some regex to exclude URLs from the scanner. Sometimes this API call results in an internal error that shuts down ZAP. Here's the exception taken from a remote debug:

![zap1](https://user-images.githubusercontent.com/6908349/62125771-5cb6c600-b2ce-11e9-9a47-84f169283cc8.png)

And here's part of the stacktrace:

> 32631 [ZAP-ProxyThread-9] ERROR org.zaproxy.zap.extension.ascan.ActiveScanAPI  - java.sql.SQLNonTransientConnectionException: excepci�n de conexi�n: cerrada
org.parosproxy.paros.db.DatabaseException: java.sql.SQLNonTransientConnectionException: excepci�n de conexi�n: cerrada
	at org.parosproxy.paros.db.paros.ParosTableSessionUrl.deleteAllUrlsForType(ParosTableSessionUrl.java:140)
	at org.parosproxy.paros.db.paros.ParosTableSessionUrl.setUrls(ParosTableSessionUrl.java:182)
	at org.parosproxy.paros.model.Session.addExcludeFromScanRegexs(Session.java:1033)
	at org.zaproxy.zap.extension.ascan.ActiveScanAPI.handleApiAction(ActiveScanAPI.java:422)
	at org.zaproxy.zap.extension.api.API.handleApiRequest(API.java:499)
	at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(ProxyThread.java:499)
	at org.parosproxy.paros.core.proxy.ProxyThread.run(ProxyThread.java:335)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLNonTransientConnectionException: excepci�n de conexi�n: cerrada
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.executeUpdate(Unknown Source)
	at org.parosproxy.paros.db.paros.ParosTableSessionUrl.deleteAllUrlsForType(ParosTableSessionUrl.java:138)
	... 7 more
Caused by: org.hsqldb.HsqlException: excepci�n de conexi�n: cerrada
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.Session.execute(Unknown Source)
	... 10 more
32635 [Thread-10] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - dataFileCache open start
32659 [Thread-10] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - dataFileCache open end

It's confusing because it only happens every now and then, it's not a constant, even though the API call that triggers it is ALWAYS the same.

I'm launching the ZAP process with the following params:

`java -jar zap-2.8.0.jar -host 127.0.0.1 -port 60205 -dir C:\<dir_path>\OWASP -installdir C:\Users\<myuser>\AppData\Local\Temp\1564482568591-0\ZAP_2.8.0 -newsession BDDSession_1564482597568 -config scanner.threadPerHost=10 -config spider.thread=10 -config api.key=ycPemMwTGeNNlNouHWYo -config connection.proxyChain.hostName=127.0.0.1 -config connection.proxyChain.port=8090 -config connection.proxyChain.enabled=true 
`

Any help would be much appreciated!!

**Comment by psiinon** [comment]
Do you really need to call JAVA directly?
I'd recommend using the `zap.sh` or `zap.bat` scripts - they set up the environment in the way ZAP expects to be run. You'll still be able to use all of the config settings in the same way.
I dont know if it will actually solve this problem, but I think its worth a try.

**Comment by fillodemanuel** [comment]
That was quick! thanks @psiinon 

I'm actually using the zap.bat script, but through a ProcessBuilder, and the rest of params al passed as the command:
`new ProcessBuilder().inheritIO().command(params);`

Is there an alternative way to set all of this configuration? I think some of them are configurable through the API but not sure it's all of them:

`....... -host 127.0.0.1 -port 60205 -dir C:\<dir_path>\OWASP -installdir C:\Users\<myuser>\AppData\Local\Temp\1564482568591-0\ZAP_2.8.0 -newsession BDDSession_1564482597568 -config scanner.threadPerHost=10 -config spider.thread=10 -config api.key=ycPemMwTGeNNlNouHWYo -config connection.proxyChain.hostName=127.0.0.1 -config connection.proxyChain.port=8090 -config connection.proxyChain.enabled=true`

**Comment by thc202** [comment]
Are you waiting for ZAP to fully start before calling the API? You can create a new session with the core API endpoint `newSession`, which should address the issue you are seeing.

Yes, those configurations (except the API key) can be set through the API.

**Comment by fillodemanuel** [comment]
Yes, I'm using the _waitForSuccessfulConnectionToZap_ call to wait for ZAP to be ready. I'll try to do all the configuring (except API key) through API calls then and get back to you as soon as I'm able to test it. 

Thanks everyone for the quick response!

**Comment by fillodemanuel** [comment]
Hi! I removed the `newsession` argument from the start script to create it through the API instead. It seems like this solves the issue. Thanks!

**Comment by kingthorin** [comment]
> is there a way to avoid the session prompt when ZAP starts in gui mode?

Click the ‘Remember my choice’ checkbox.

**Comment by fillodemanuel** [comment]
I was thinking about a way without user interaction. I'm generally using this in a headless scenario but giving the option to the developers to use a gui mode in their local environment so they can see what's going on yet still having everything automated. The thing is that if I create the session through the API but the user clicks the wrong option in that prompt.... well, there goes all the configuration i've set in the background

**Comment by thc202** [comment]
Sorry, didn't notice the new question. You can prevent that with `-config database.newsessionprompt=false`.
