### ISSUE TITLE
Customizable HTML report is not working

### ISSUE THREAD

**Issue by vishwa513** [zaproxy/zaproxy#5521]
**Describe the bug**
Customizable HTML report is not working, unable to geenerate the report. 

**To Reproduce**
1. Go to '.Reports'
2. Click on 'Customize HTML report'
3. Scroll down to 'Click on it and observe for Generate report' button

**Expected behavior**
ZAp should launch the customizable HTML report.

**Screenshots**

**Software versions**
 - ZAP: 2.8.0]
 - OS:  Windows 7
 - Java: jdk version "1.8.0
 - Browser: chrome 66

.
![image](https://user-images.githubusercontent.com/54053881/62918229-a1595b80-bdbc-11e9-80b6-8ec2667f033d.png)

**Comment by kingthorin** [comment]
I'm unable to recreate this issue. @vishwa513 could you please double check that you're running ZAP 2.8 and v4 of the Customizable Report addon?

https://github.com/zaproxy/zaproxy/wiki/FAQAddonVersions

**Comment by thc202** [comment]
This can be reproduced when there are many different alerts.

**Comment by kingthorin** [comment]
Thanks
