### ISSUE TITLE
Scan multiple sites with java api, zap memory grow up constantly ?

### ISSUE THREAD

**Issue by daviddone** [zaproxy/zaproxy#5523]
@thc202 
I used to start zap in daemon mode on the server and then submit some sites via java api. the memory grow up,canot release。how can I release zap memory excep restart zap。

Detail below:
At first, the memory is 200M，When I submit the first site, the zap memory grow up to 400M。
And then,I submit the second site，the zap memory group to 500M. If I run 50 sites，the zap memory grow up 2.5G。by the way,I set xmx 1999M,so there is no oom problem.

Code like here:
ClientApi api = new ClientApi(***);
api.core.newSession("test","true");
api.spider.scan(TARGET, null, null, null, null);

Best regards, David

**Comment by kingthorin** [comment]
Yup that’ll happen. ZAP is not currently designed to be a long running server app.

You could try low memory mode: https://github.com/zaproxy/zap-core-help/wiki/HelpCmdline#options that’ll help a bit, but is kind of an alpha/beta option.

**Comment by daviddone** [comment]
Thank you very much, @kingthorin
I use this code:
     api.core.runGarbageCollection();
It can release some memory by System.gc, but it can not fixed the problem when scaning many websites. do you know when simon release zass?

**Comment by kingthorin** [comment]
Unfortunately at this point ZaaS is just a concept there isn’t anyone actively working on it.

**Comment by psiinon** [comment]
Yeah, too much to do, not enough people or time right now I'm afraid :(

**Comment by kingthorin** [comment]
Is there a particular reason why you need to do 50sites/scans on a single run?

**Comment by psiinon** [comment]
FYI we run ZAP against 200+ sites every day, but we restart ZAP each time :)

**Comment by daviddone** [comment]
> Is there a particular reason why you need to do 50sites/scans on a single run/launch?

I just think it will help me save the restart time , no  particular reason.

**Comment by psiinon** [comment]
Restart time is usually much less than scanning time, so I'd recommend always restarting when scanning a load of sites :)

**Comment by daviddone** [comment]
@psiinon    thank you, psiinon. Maybe the easy way by restarting is the best way.

**Comment by daviddone** [comment]
@psiinon By the way, we found that the heap memory usage is normal but the RSS used by the process is very high, so looks like native memory leak. Do you have any idea?

**Comment by psiinon** [comment]
Last time we looked into this I think that main culprit was the Sites tree, so not really a memory leak but 'as designed'. The Sites tree is ZAPs representation of the application so key to the internal memory model, and by default its all held in memory. This makes sense for a desktop tool where you want the UI elements to be responsive. 
In low memory mode then the tree is stored in the db, but as @kingthorin said, its alpha/beta.
If you do try it out then let us know whether it works ok for you...

**Comment by daviddone** [comment]
We finally build zap with docker . Use jvm parameter :-XX:+ExitOnOutOfMemoryError, and docker parameter: --restart , solve this problem.  @psiinon

**Comment by kingthorin** [comment]
Thanks for letting us know.
