### ISSUE TITLE
Documentation: ZAP-Baseline-Scan docs does not mention -J (json format for reports)

### ISSUE THREAD

**Issue by san-ouadghiri** [zaproxy/zaproxy#5527]
**Describe the bug**
The baseline doc does not mention the json report format. Full scan doc has it. Baseline cli help also mention it. I guess the update was just forgotten.

**To Reproduce**
https://github.com/zaproxy/zaproxy/wiki/ZAP-Baseline-Scan#usage

**Expected behavior**
Added 
    -J report_json    file to write the full ZAP JSON document

**CLI help says**
**$ zap-baseline.py -t https://myURL -r testreport.html**
2019-08-16 15:14:18,326 A file based option has been specified but the directory '/zap/wrk' is not mounted 
**Usage: zap-baseline.py -t <target> [options]**
    -t target         target URL including the protocol, eg https://www.example.com
**Options:**
    -h                print this help message
    -c config_file    config file to use to INFO, IGNORE or FAIL warnings
    -u config_url     URL of config file to use to INFO, IGNORE or FAIL warnings
    -g gen_file       generate default config file (all rules set to WARN)
    -m mins           the number of minutes to spider for (default 1)
    -r report_html    file to write the full ZAP HTML report
    -w report_md      file to write the full ZAP Wiki (Markdown) report
    -x report_xml     file to write the full ZAP XML report
    -J report_json    file to write the full ZAP JSON document
    -a                include the alpha passive scan rules as well
    -d                show debug messages
    -P                specify listen port
    -D                delay in seconds to wait for passive scanning 
    -i                default rules not in the config file to INFO
    -I                do not return failure on warning
    -j                use the Ajax spider in addition to the traditional one
    -l level          minimum level to show: PASS, IGNORE, INFO, WARN or FAIL, use with -s to hide **example URLs**
    -n context_file   context file which will be loaded prior to spidering the target
    -p progress_file  progress file which specifies issues that are being addressed
    -s                short output format - dont show PASSes or example URLs
    -T                max time in minutes to wait for ZAP to start and the passive scan to run
    -z zap_options    ZAP command line options e.g. -z "-config aaa=bbb -config ccc=ddd"
    --hook            path to python file that define your custom hooks

**Comment by kingthorin** [comment]
Fixed in https://github.com/zaproxy/zaproxy/wiki/ZAP-Baseline-Scan/_compare/8e45b48dc529bb8043bcf5741387b2d765eaaa1a...f2e297bc3fc88614e2bd890b56b144dcf85f56c6

**Comment by san-ouadghiri** [comment]
Thank you @kingthorin.
