### ISSUE TITLE
ZAP-Baseline Scan returns error: Unable to find script while loading Script Based Authentication Method for name: script.zst

### ISSUE THREAD

**Issue by ivyheasty** [zaproxy/zaproxy#5529]
**Describe the bug**
I tried to perform a passive scan using the zap-baseline.py from the terminal. I entered the docker container and successfully mounted the all zap related scripts (context, scripts, etc) in zap/wrk. The scan was successful. However, the following error was found in the  output file:
`Unable to find script while loading Script Based Authentication Method for name: script.zst`

**To Reproduce**
`zap-baseline.py -t host -r report.html -n host.context`

**Expected behavior**
Able to load Script Based Authentication Method for name: script.zst

**Screenshots**
N/A

**Software versions**
 - ZAP: v2.8.0
 - Add-on: N/A
 - OS: macOS v1.13.6
 - Java version "1.8.0_151"
 - Browser: N/A

**Errors from the zap.log file**
Unable to find script while loading Script Based Authentication Method for name: script.zst
Note: this is only visible from the log file and not from CLI

**Additional context**
Issue is REPRODUCIBLE from the ZAP UI

**Comment by psiinon** [comment]
That will be a local configuration issue rather than a bug in ZAP.
Its best to ask about this on the ZAP User Group: https://groups.google.com/group/zaproxy-users rather than raise an issue.
