### ISSUE TITLE
forced browse: Use logger instead of standard out

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#5530]
the `bruteforce` extension could be further migrated from use of `System.out.println` to a standard ZAP logger. Then it would benefit from timestamps, etc which would potentially make troubleshooting easier.

**Comment by JFM9** [comment]
I'll tackle this

**Comment by thc202** [comment]
Assigned.

**Comment by thc202** [comment]
btw, do you know where to start? Any questions?

**Comment by JFM9** [comment]
Yes! I am in contact with @kingthorin in regards to this issue.
