### ISSUE TITLE
After Updating the installs modules, its showing various errors and not working even not opening up any browser

### ISSUE THREAD

**Issue by d3xter7-lab** [zaproxy/zaproxy#5532]
Everything was working fine, but as I updated the installed modules, nothing is working, could anybody would tell me what is the exact issue and how its going to be solved, or if I have clear the cache for the this one, I am using zap 2.8.0

**Comment by kingthorin** [comment]
Please be much more specific. What did you update, what isn't working, define "nothing is working".

**Comment by thc202** [comment]
Worth checking the zap.log file (in https://github.com/zaproxy/zaproxy/wiki/FAQconfig) for errors.

**Comment by d3xter7-lab** [comment]
I updated the installed modules of the zap 2.8.0, after installation, no testing is available to perform as no browser is opening up, no chrome, no firefox no jzbrowser, Also when I start the zap 2.8.0 it started to show me the modules error, after the updation
what to do ?

**Comment by kingthorin** [comment]
> what do do ?

Tell us what you updated (specifically).
Provide the errors.
Provide install details.

JxBrowser has been dropped due to license changes.

**Comment by d3xter7-lab** [comment]
> Worth checking the zap.log file (in https://github.com/zaproxy/zaproxy/wiki/FAQconfig) for errors.

I can't find anything here related to error, not even in the log file
it says like :- 
# Keep one backup file^M
 11 log4j.appender.R.MaxBackupIndex=3^M
 12 ^M
 13 log4j.appender.R.layout=org.apache.log4j.PatternLayout^M
 14 log4j.appender.R.layout.ConversionPattern=%d [%-5t] %-5p %c{1} - %m%n^M
 15 ^M
 16 log4j.logger.org.parosproxy.paros=INFO^M
 17 log4j.logger.org.zaproxy.zap=INFO^M
 18 log4j.logger.org.apache.commons.httpclient=ERROR^M
 19 # Disable Jericho log, it logs HTML parsing issues as errors.
 20 log4j.logger.net.htmlparser.jericho=OFF^M
 21 ^M
 22 # Prevent Crawljax from logging too many, not so useful, INFO messages.^M
 23 # For example:^M
 24 # INFO  Crawler - New DOM is a new state! crawl depth is now 10^M
 25 # INFO  Crawler - Crawl depth is now 1^M
 26 # INFO  Crawler - Crawl depth is now 2^M
 27 # INFO  UnfiredCandidateActions - There are 64 states with unfired actions^M
 28 # INFO  StateMachine - State state106 added to the StateMachine.^M
 29 log4j.logger.com.crawljax.core.Crawler = WARN^M
 30 log4j.logger.com.crawljax.core.state.StateMachine = WARN^M
 31 log4j.logger.com.crawljax.core.UnfiredCandidateActions = WARN^M

**Comment by kingthorin** [comment]
https://github.com/zaproxy/zaproxy/wiki/FAQlogging

**Comment by d3xter7-lab** [comment]
> > what do do ?
> 
> Tell us what you updated (specifically).
> Provide the errors.
> Provide install details.
> 
> JxBrowser has been dropped due to license changes.

All the installed options provided under check for update tab in help option I used the update all button to update every installed module in zap 2.8.0

**Comment by kingthorin** [comment]
If you can't provide details there's nothing we can do to help.

**Comment by thc202** [comment]
You need to check `zap.log` not `log4j.properties`.

**Comment by d3xter7-lab** [comment]
I just removed the old installation in home/.ZAP directory and again run the zaproxy in terminal & it worked guys ...just replying with one error that localhost can't listen to port 8080, if you can help me to set that, so that it could run without any error
Thanks

**Comment by thc202** [comment]
You just need to change the port to other value than 8080 in Options > Local Proxies. https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsOptionsLocalproxy

**Comment by kingthorin** [comment]
Look for defunct java proceses still using port 8080. Use socketstatus to see what's going on (https://mobile.twitter.com/b0rk/status/1090058524137345025), Reboot. etc

**Comment by d3xter7-lab** [comment]
Done, Thanks a lot, and How can I add values to scope in zap, as I am a new user to it, previously used burp ...so no idea of adding to scope the target ...

**Comment by kingthorin** [comment]
If you have further questions people refer to ZAP's help, the [getting started guide](https://github.com/zaproxy/zaproxy/releases/download/v2.8.0/ZAPGettingStartedGuide-2.8.pdf), or the [User Group](https://groups.google.com/forum/#!forum/zaproxy-users).

https://github.com/zaproxy/zap-core-help/wiki/HelpStartConceptsScope
