### ISSUE TITLE
Got ClientApiException when try to include url in context

### ISSUE THREAD

**Issue by DmitriyKapeliukh** [zaproxy/zaproxy#5533]
**Describe the bug**
Hi all!
I've an exception:
**org.zaproxy.clientapi.core.ClientApiException: Does Not Exist**
when I trying to add my url into context;

**To Reproduce**
Execute method:
```
    public void setIncludeInContext() {
        try {
            api.context.includeInContext(CONFIG.get("defaultContextName"), CONFIG.get("urlregexpToIncludeIntoScan"));
        } catch (ClientApiException e) {
            e.printStackTrace();
        }
    }

```
StackTrace:
```
org.zaproxy.clientapi.core.ClientApiException: Does Not Exist
	at org.zaproxy.clientapi.core.ApiResponseFactory.getResponse(ApiResponseFactory.java:50)
	at org.zaproxy.clientapi.core.ClientApi.callApi(ClientApi.java:339)
	at org.zaproxy.clientapi.gen.Context.includeInContext(Context.java:106)
```

**Software versions**
 - ZAP: 1.7.0
 - Add-on: Name and version [e.g. Passive Scan Rules Alpha v19. https://github.com/zaproxy/zaproxy/wiki/FAQAddonVersions]
 - OS: Mac OS 10.14.6
 - Java: 1.8.0_171
 - Browser: Chrome 76

**Comment by thc202** [comment]
Does the context exist?

**Comment by DmitriyKapeliukh** [comment]
> Does the context exist?

I've colled Context variable from ClientApi class. You mean I've to initialize Context as local?

**Comment by thc202** [comment]
I mean in ZAP, was the context created (or already exists) before calling `includeInContext`?

**Comment by DmitriyKapeliukh** [comment]
Yes. The ClientApi object created before calling this method and ClientApi class contain initialized local Context local variable.

**Comment by kingthorin** [comment]
Could we move this discussion to the [development group](https://groups.google.com/forum/#!forum/zaproxy-develop)? The issue tracker really isn't the right place for this type of thing.

**Comment by thc202** [comment]
Enable: https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsOptionsApi#report-error-details-via-api

and check which value does it say that does not exist.

**Comment by thc202** [comment]
Closing, this does not seem to be an issue in ZAP. Please, reopen/comment (or post to dev group) if you have more details.
