### ISSUE TITLE
Not able to launch ZAP after installation

### ISSUE THREAD

**Issue by JyotiVashist** [zaproxy/zaproxy#5537]
Hi,

I am getting error while launching the application on windows 10. Kindly help.
![error_message](https://user-images.githubusercontent.com/54399923/63509114-fbfb6180-c4f8-11e9-9106-8b5f1ec6a8de.png)

Regards,
Jyoti

**Comment by kingthorin** [comment]
Do you have java installed?

**Comment by psiinon** [comment]
Does that file exist and if so do you have permissions to run it?

**Comment by JyotiVashist** [comment]
Yes Java is installed on the system. Also I gave all the permissions.

**Comment by kingthorin** [comment]
Where did you download from? Did the download actually complete properly/fully? Did the install complete properly/fully? Have you checked the event log?

**Comment by kingthorin** [comment]
You could verify the hash of the file you downloaded:
https://github.com/zaproxy/zap-admin/blob/ec3a50165243a7276d82815f202fdfbd1601a807/ZapVersions.xml#L13-L16

**Comment by JyotiVashist** [comment]
After downloading & installing ZAP from the mentioned link. the issue is still same.

**Comment by kingthorin** [comment]
https://support.microsoft.com/en-ca/help/2669244/windows-cannot-access-the-specified-device-path-or-file-error-when-you

**Comment by thc202** [comment]
@JyotiVashist did the above link help?

**Comment by JyotiVashist** [comment]
No the above link didn't help. I found the error actually my java exe
location and zap location was different, but when I put both the files in
same folder it worked. Thank you for the help.

**Comment by kingthorin** [comment]
Weird, thanks for letting us know.
