### ISSUE TITLE
spider bug?

### ISSUE THREAD

**Issue by 687766616e** [zaproxy/zaproxy#5541]
it looks like cant cap thing like this:
`http://www.hidden.com.us/?d=1,83a45753c2cc2d93,*AF9EB886E879F427ED8F1161A52E60953AA0B189,0,html.php`

**Comment by thc202** [comment]
Could you provide more details? What's the expected behaviour and what's happening?

**Comment by 687766616e** [comment]
I can't see it on the site tree, But it is on the homepage. (no ajax or something like that (google translated

**Comment by 687766616e** [comment]
I will see if it will send relevant packets (but tmr

**Comment by thc202** [comment]
Were you able to check this?

**Comment by kingthorin** [comment]
> Were you able to check this?

**Comment by kingthorin** [comment]
@687766616e any update?

**Comment by 687766616e** [comment]
I will not be able to update more details for a long time. Because my notebook is broken
u can close it if u want to I'm sorry😅

**Comment by psiinon** [comment]
Ok, thanks for letting us know.
