### ISSUE TITLE
There is no support of redirects

### ISSUE THREAD

**Issue by bewell** [zaproxy/zaproxy#5556]
**Is your feature request related to a problem? Please describe.**
The ZAP scan does not follow to redirects. This is a problem if a page is redirecting the user somewhere else in the host. As described in the Zap channel on slack ([here](https://owasp.slack.com/archives/C04SX2GAS/p1567435882019000)) there are cases (especially with the microservices architecture) where redirecting the user would be useful. Since ZAP is avoiding that, the scope map provided by the spider is not complete. Naturally this hurts scan process too.

**Describe the solution you'd like**
Well first of all the support of the redirections would be great. If the spider gets `302` code it could easily follow there and check what's inside. Not to let the spider into infinite of the internet, the default value for redirection could be e.g. `maximum-redirects = 5`. 

**Describe alternatives you've considered**
Adding the different URLs into the scope could a workaround, but such behaviour is not really what dynamic scan is all about. With the redirects the scan would scan the site like its been used.

**Additional context**
Of course adding the functionality to both API level and UI is appreciated. Though I'm sure it's done like that anyway.

**Comment by psiinon** [comment]
I'm still a bit concerned that this could mean ZAP scans sites that should be completely out of scope.
I like the alternative you suggested better as the default option - ie only supporting redirects that are in the same context. The context could then be configured to include any number of domains.
We could then have a non default option that allowed redirects to any other site, subject to a maximum-redirect limit as you described.

**Comment by bewell** [comment]
Yes, scanning out of scope sites is not something we wan.t Agree on that. If the redirection happens inside the scope, then it's fine. Outside redirects could be omitted or configured in non-default setting.
Great thought!

**Comment by psiinon** [comment]
I've just added 2 different IP addresses to the same context with one redirecting to the other.
Spidering the first one _does_ result in the redirects to the second address being followed, ie it looks like the proposed behaviour is already supported.
Can anyone give an example where this doesnt work as required?

**Comment by thc202** [comment]
I guess this can be closed per latest comments in the Slack thread?

**Comment by bewell** [comment]
Probably yes.
Though I'm still not comfortable that redirect from `https://website.com` to `https://www.website.com` is not counted unless they both are added to the context.

**Comment by kingthorin** [comment]
Where’s the line though? Do we include `admin.`, what about, `mail.` etc etc

**Comment by psiinon** [comment]
I dont like the idea of having `https://website.com` being the same as `https://www.website.com` as a special case. We _could_ have an option to treat _all_ subdomains as in scope, but tbh I think doing that via contexts is clearer and more flexible.

**Comment by bewell** [comment]
Ok, you're right. I don't want to cause chaos in scans with this "feature".
Let's close the issue.
