### ISSUE TITLE
ZAP not Initializing when launched through java program 

### ISSUE THREAD

**Issue by ganginenisarath** [zaproxy/zaproxy#5560]
Hi,

I am trying to launch the ZAP through java program. Below is the snippet of the program I am using 

`File ZAPbatdir = new File(System.getProperty("user.dir") +"\\lib\\ZAP");`
`String command =  "cmd /c ZAP.bat -host 127.0.0.1 -port "+ port +" -config api.disablekey=true -newsession "+System.getProperty("user.dir")+"\\"+ createDirectory.getName();`
`Runtime.getRuntime().exec(command, null, ZAPbatdir);`
`Thread.sleep(30000);`

The command launches the zap successfully but the zap does not initialize after a certain point. ZAP loads successfully after the sleep time ends. After multiple tests found that if we use `Thread.sleep` command ZAP does not initialize.
![image](https://user-images.githubusercontent.com/7515152/64243174-86de5200-cf24-11e9-9a08-1a709f9e16e1.png)

**Comment by psiinon** [comment]
This will be an issue with your code rather than an issue in ZAP.
Questions like this are better asked on the ZAP user group: https://groups.google.com/group/zaproxy-users
