### ISSUE TITLE
forced browse: Use logger instead of printing exceptions' strack trace

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#5564]
Continuation of #5530, the `bruteforce` extension should be changed to log the exceptions instead of printing their stack traces.

**Comment by savva-k** [comment]
I'd love to work on this

**Comment by kingthorin** [comment]
It’s yours :+1:

**Comment by savva-k** [comment]
@kingthorin not sure if I made the pr correctly as I can't see it linked here.
Here's the link: https://github.com/zaproxy/zap-extensions/pull/2184

**Comment by kingthorin** [comment]
It’s good, it’s not linked here because your commit message or PR comment didn’t include a reference to the ticket. 

I’ll try to review it in a few hours.

**Comment by thc202** [comment]
Since the PR is in another repo you need to prefix the issue with `zaproxy/zaproxy`, you can also close it: https://help.github.com/en/articles/closing-issues-using-keywords
