### ISSUE TITLE
[Fatal Error] :1:1: Content is not allowed in prolog.

### ISSUE THREAD

**Issue by ahmed-awadelkarim** [zaproxy/zaproxy#5565]
I'm running the zap-proxy full scan, and seeing this error message as its traversing different endpoints. I'm running this scan from inside docker.

zap-full-scan.py -t https://www.test-url.com --hook=/zap/auth_hook.py -T 1 -z \"auth.username=\"test\"\" -z \"auth.password=\"test\"\" -z \"auth.auto=1\"

**Expected behavior**
To run full scan and send outputs.

**Screenshots**
[Fatal Error] :1:1: Content is not allowed in prolog.
[Fatal Error] :1:1: Content is not allowed in prolog.

**Comment by kingthorin** [comment]
What version of zap? What version of Java?

Is it only happening on XML content? What’s the charset? Does the content conform to the charset?

**Comment by ahmed-awadelkarim** [comment]
HI @kingthorin I'm not entirely sure the version, I'm using this image: zap2docker-weekly

**Comment by ahmed-awadelkarim** [comment]
And I'm seeing this on all endpoints I'm trying to test.

**Comment by ahmed-awadelkarim** [comment]
I'm going to close this for now. I believe the issue is on my end.

**Comment by kingthorin** [comment]
@ahmed-awadelkarim did you have an update?

**Comment by kingthorin** [comment]
Re-closing, no update after > 1 week.

**Comment by ahmed-awadelkarim** [comment]
I'm sorry for the late response. This has persisted, however the scans still seem to be running.

**Comment by ahmed-awadelkarim** [comment]
I receive a 200 response going to all the endpoints I attempt to access, and then get the fatal error from above @kingthorin

**Comment by kingthorin** [comment]
It might be your output, what type of report are you generating in the end?

**Comment by ahmed-awadelkarim** [comment]
I wasn't generating a report at first when seeing this error. I have since started using the -J to generate a json report but still see the above in the output.

**Comment by ahmed-awadelkarim** [comment]
The error shows btw the 47% - 62% scan progress points. But the scan continues and I see the outputs.

**Comment by kingthorin** [comment]
Okay let's more this to the ZAP User Group, this isn't the right place for a discussion.

https://groups.google.com/forum/#!forum/zaproxy-users

**Comment by ahmed-awadelkarim** [comment]
Ok thanks.
