### ISSUE TITLE
Leveraging Config File to Pass Oauth Token for Authenticated Scans

### ISSUE THREAD

**Issue by ahmed-awadelkarim** [zaproxy/zaproxy#5568]
I'm creating a config file which I name rules.conf and am passing it the zap full scan via docker using the -c flag as follows:

      results=`zap-full-scan.py -t https://${SCAN_URL} -T 1 -c rules.conf` 

When looking at the scan output I get this error messaage:

Failed to load config file /zap/wrk/rules.conf need more than 1 value to unpack

This is what my rules.conf file looks like:

replacer.full_list(0).description=auth1
replacer.full_list(0).enabled=true
replacer.full_list(0).matchtype=REQ_HEADER
replacer.full_list(0).matchstr=Authorization
replacer.full_list(0).regex=false
replacer.full_list(0).replacement=\"Bearer\ ${auth_token}\"

Not sure what I am missing here.

**Comment by thc202** [comment]
You need to use `-configfile` instead [1] (and it would have to be added through `-z` [2]).

[1] https://github.com/zaproxy/zap-core-help/wiki/HelpCmdline
[2] https://github.com/zaproxy/zaproxy/wiki/ZAP-Full-Scan#usage

**Comment by ahmed-awadelkarim** [comment]
Thank you, this seems to have resolved my issues.
