### ISSUE TITLE
Support global Alert filters

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#5575]
Context alert filters are a bit of a pain when automating ZAP - you need to define a context in order for them to work.
Global alert filters, which would work like context alert filters but would apply to all alerts, would make automating them easier.

Related Issues for ref: #5574 #3027

**Comment by thc202** [comment]
Done in zaproxy/zap-extensions#2178.

**Comment by kingthorin** [comment]
Ref: https://github.com/zaproxy/zap-extensions/releases/tag/alertFilters-v9
