### ISSUE TITLE
Getting org.zaproxy.clientapi.core.ClientApiException while executing FormBasedAuthentication.java for Authentication scan

### ISSUE THREAD

**Issue by Shivaram-goli** [zaproxy/zaproxy#5579]
I am using OWASP ZAP 2.8.0 and  sdk from https://github.com/zaproxy/zap-api-java
And running SimpleExample.java class for pscan and ascan is working fine.
I am trying to do Authentication scan, but I am getting the below Exception While Running the FormBasedAuthentication.java 
I given details like below for setFormBasedAuthenticationForBodgeit(ClientApi clientApi)
String contextId = "1";
String loginUrl = "http://localhost:8080/login.jsp";
String loginRequestData = "uid= test&passw= test123&btnSubmit=Login";
Please help me to move foreword.

Console log:
Supported authentication methods: [formBasedAuthentication, scriptBasedAuthentication, httpAuthentication, manualAuthentication, jsonBasedAuthentication]
'formBasedAuthentication' config param: loginUrl (mandatory)
'formBasedAuthentication' config param: loginRequestData (optional)
'scriptBasedAuthentication' config param: scriptName (mandatory)
'scriptBasedAuthentication' config param: scriptConfigParams (optional)
'httpAuthentication' config param: hostname (mandatory)
'httpAuthentication' config param: realm (mandatory)
'httpAuthentication' config param: port (optional)
'jsonBasedAuthentication' config param: loginUrl (mandatory)
'jsonBasedAuthentication' config param: loginRequestData (mandatory)

-------------
Setting form based authentication configuration as: loginUrl=http%3A%2F%2Fdemo.testfire.net%2Flogin.jsp&loginRequestData=uid%3D+%7B%25jsmith%25%7D%26passw%3D+%7B%25Demo1234%25%7D
Exception in thread "main" org.zaproxy.clientapi.core.ClientApiException: No Context found that matches parameter
	at org.zaproxy.clientapi.core.ApiResponseFactory.getResponse(ApiResponseFactory.java:50)
	at org.zaproxy.clientapi.core.ClientApi.callApi(ClientApi.java:339)
	at org.zaproxy.clientapi.gen.Authentication.setAuthenticationMethod(Authentication.java:83)
	at org.zaproxy.clientapi.examples.authentication.FormBasedAuthentication.setFormBasedAuthenticationForBodgeit(FormBasedAuthentication.java:156)
	at org.zaproxy.clientapi.examples.authentication.FormBasedAuthentication.main(FormBasedAuthentication.java:207)

**Comment by kingthorin** [comment]
Why not use the example that has auth details?
https://github.com/zaproxy/zap-api-java/tree/develop/subprojects/zap-clientapi/src/examples/java/org/zaproxy/clientapi/examples/authentication

The ZAP User Group https://groups.google.com/group/zaproxy-users is a much better place for questions (vs. our issue tracker).

**Comment by Shivaram-goli** [comment]
Thank you for replay.

https://github.com/zaproxy/zap-api-java/tree/develop/subprojects/zap-clientapi/src/examples/java/org/zaproxy/clientapi/examples/authentication

I tried that, with that auth details(same class) also getting same issue.

**Comment by thc202** [comment]
You might need to change the ID of the context (that can be obtained when the context is created).

**Comment by Shivaram-goli** [comment]
> You might need to change the ID of the context (that can be obtained when the context is created).

Thank you for replay.
Please can you share me the sample code to get the contextId.
