### ISSUE TITLE
Running zap docker weekly with zap-cli with Jenkins

### ISSUE THREAD

**Issue by benzionyunger** [zaproxy/zaproxy#5582]
I am new at using zap, and I've been running into issues getting it to work properly on my Jenkins slave. I have a bash script that launches zap docker that works seamlessly locally on my Ubuntu finding multiple issues on all levels, but when running off my Jenkins slave machine (also Ubuntu), although the script seems to be running correctly, it reports no issues found. 

Note: I changed the user to 'root' from 'zap', since zap was causing permission errors writing the reports to the file.

Here is my script:

#!/bin/sh

DOCKER=`which docker`
IMAGE='owasp/zap2docker-weekly'
URL='https://MY_SITE'
#URL=${URL}
ZAP_API_PORT='8180'

# Start our container
CONTAINER_ID=`$DOCKER run -d \
   --user=root \
   --rm \
  --name zap \
  -p $ZAP_API_PORT:$ZAP_API_PORT \
  -v $PWD:/zap/reports:rw \
  -i $IMAGE zap-x.sh \
  -daemon -port $ZAP_API_PORT \
  -host 0.0.0.0 \
  -port $ZAP_API_PORT \
  -config api.disablekey=true \
  -config api.addrs.addr.regex=true \
  -config api.addrs.addr.name=.* \
  -config scanner.attackOnStart=true \
  -config view.mode=attack \
  -config database.recoverylog=false`

# set up our status spinner
spin='-\|/'
i=0;

# Poll the api and wait for it to start up
while ! curl -s http://0.0.0.0:$ZAP_API_PORT > /dev/null
do
 i=$(( (i+1) %4 ))
 printf "\rWaiting for OWASP ZAP to start ${spin:$i:1}"
 sleep .1
done
echo "\nZAP has successfully started"

# Open the provided url
$DOCKER exec $CONTAINER_ID \
  zap-cli -p $ZAP_API_PORT open-url $URL

# Spider the site
$DOCKER exec $CONTAINER_ID \
  zap-cli -v -p $ZAP_API_PORT spider $URL

# Scan the site
$DOCKER exec $CONTAINER_ID \
  zap-cli -v -p $ZAP_API_PORT active-scan \
  --recursive $URL

# Show any alerts
$DOCKER exec $CONTAINER_ID \
  zap-cli -p $ZAP_API_PORT alerts -l Low

# Generate our report
$DOCKER exec $CONTAINER_ID \
  zap-cli -p $ZAP_API_PORT report \
  -o /zap/reports/report.html -f html

# Shut down the docker image
$DOCKER kill $CONTAINER_ID

**Comment by kingthorin** [comment]
Please don't ask questions as issues - the ZAP User Group https://groups.google.com/group/zaproxy-users and Developer Group https://groups.google.com/group/zaproxy-develop are much better places for questions.
