### ISSUE TITLE
ZAP 2.8.1 hanging on kali

### ISSUE THREAD

**Issue by strunz983** [zaproxy/zaproxy#5585]
Hi i need help with zaproxy. 
when is start is go the 
22508 [ZAP-BootstrapGUI] INFO org.parosproxy.paros.extension.ExtensionLoader  - Initializing HTTP Panel Syntax Highlighter View Extension point and after that is stop working.

My OS is Linux kali 5.2.0-kali2-amd64 #1 SMP Debian 5.2.9-2kali1 (2019-08-22) x86_64 GNU/Linux

My Java version is 
java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b01-1-b01)
OpenJDK 64-Bit Server VM (build 25.212-b01, mixed mode)

this is the info 
https://pastebin.com/HXhjt96E

![Untitled1](https://user-images.githubusercontent.com/42872580/65149194-8f9d5080-da19-11e9-9456-2418c9cefb00.jpg)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Software versions**
 - ZAP: [note that we typically only support the latest version of ZAP]
 - Add-on: Name and version [e.g. Passive Scan Rules Alpha v19. https://github.com/zaproxy/zaproxy/wiki/FAQAddonVersions]
 - OS: [e.g. Windows 10]
 - Java: [e.g. openjdk version "1.8.0_171"]
 - Browser: [e.g. chrome 66, firefox 59, safari 11.1]

**Errors from the zap.log file**
See https://github.com/zaproxy/zaproxy/wiki/FAQconfig for the location of the zap.log file for your OS.

**Additional context**

**Comment by thc202** [comment]
Could you provide a thread dump when in that state? You need to `kill -9 <zap-pid>`.

**Comment by kingthorin** [comment]
@strunz983 had you tried to install all addons from the market place?

**Comment by thc202** [comment]
Some of them are not in the marketplace (e.g. `birtreports`, `soap`, `cspscanner`).

**Comment by kingthorin** [comment]
Good point. Is this a really old kali install/mage?

**Comment by strunz983** [comment]
Hi i just reinstall zaproxy from kali pero and i download ZAP_WEEKLY_D-2019-09-16 version and i get the same issue

**Comment by strunz983** [comment]
how to do this 
Could you provide a thread dump when in that state? You need to kill -3 <zap-pid>.

EDIT: -3 not -9 ...

**Comment by thc202** [comment]
Check the PID of ZAP (e.g. using `ps` or task manager), then in a terminal run the command mentioned above. The thread dump will be displayed In the terminal where ZAP is running.

**Comment by strunz983** [comment]
Hi thc202 i make this in terminal
I first start zaproxy and then i make this 
root@kali:~# ps -a
   PID TTY          TIME CMD
   988 tty1     00:00:01 Xorg
  1100 tty1     00:00:00 gnome-session-b
  1139 tty1     00:00:11 gnome-shell
  1218 tty1     00:00:00 gsd-rfkill
  1222 tty1     00:00:00 gsd-smartcard
  1224 tty1     00:00:00 gsd-clipboard
  1226 tty1     00:00:00 gsd-xsettings
  1228 tty1     00:00:00 gsd-housekeepin
  1231 tty1     00:00:00 gsd-mouse
  1232 tty1     00:00:00 gsd-power
  1236 tty1     00:00:00 gsd-screensaver
  1240 tty1     00:00:00 gsd-sound
  1252 tty1     00:00:00 gsd-color
  1254 tty1     00:00:00 gsd-keyboard
  1256 tty1     00:00:00 gsd-print-notif
  1260 tty1     00:00:00 gsd-sharing
  1264 tty1     00:00:00 gsd-a11y-settin
  1265 tty1     00:00:00 gsd-wacom
  1268 tty1     00:00:00 gsd-datetime
  1270 tty1     00:00:00 gsd-media-keys
  1379 tty2     00:00:04 Xorg
  1390 tty2     00:00:00 lxsession
  1478 tty2     00:00:00 openbox
  1482 tty2     00:00:00 lxpolkit
  1483 tty2     00:00:01 lxpanel
  1484 tty2     00:00:01 pcmanfm
  1499 tty2     00:00:01 vmtoolsd
  1500 tty2     00:00:00 zeitgeist-datah
  1536 tty2     00:00:00 agent
  1542 tty2     00:00:00 xiccd
  1555 tty2     00:00:00 nm-applet
  1565 tty2     00:00:00 clipit
  2155 pts/0    00:01:43 java
  2431 pts/1    00:00:00 ps
but here is no zaproxy

so then i start stacer and i find out this  
![Untitled111](https://user-images.githubusercontent.com/42872580/65286790-bbfbbe80-db38-11e9-8a0f-6697dd67542b.jpg)

**Comment by kingthorin** [comment]
Can you open a terminal, start zap, check the process ID, do a `kill -3` on that pid, then send us the console text from the terminal you started zap in.

**Comment by strunz983** [comment]
this is kill -3 report
https://pastebin.com/sfhFYNjN

**Comment by thc202** [comment]
Thanks!

**Comment by kingthorin** [comment]
Could you try the work around mentioned here: https://github.com/zaproxy/zaproxy/issues/5526#issuecomment-522015202

**Comment by strunz983** [comment]
Than you kingthorin 
i disabled assistive_technologies=org.GNOME.Accessibility.AtkWrapper in /etc/java-8-openjdk/accessibility.properties file and now zaproxy is working fine 
Thank you a lot for your help :)

**Comment by thc202** [comment]
Reopening, it still needs to be fixed in ZAP.

**Comment by strunz983** [comment]
Thank you ALL :-)
