### ISSUE TITLE
 Xvfb failed to start error

### ISSUE THREAD

**Issue by benzionyunger** [zaproxy/zaproxy#5589]
**Describe the bug**
Running the docker image with webswing, port 8090 fails to open with msg localhost didn't send data. This was checked  _after_ using the GUI in 8080 as it says in the docs.
 
**To Reproduce**
1. run ``docker run -u zap -p 8080:8080 -p 8090:8090 -i owasp/zap2docker-weekly zap-webswing.sh``
2. open localhost:8090
3. try running the zap-webswing.sh script from within the container.
4. console output:
`zap@153fb8b667ef:/zap$ ./zap-webswing.sh
xvfb-run: error: Xvfb failed to start`

**Expected behavior**
**Screenshots**

**Software versions**
 - ZAP: [note that we typically only support the latest version of ZAP]
 - Add-on: Name and version [e.g. Passive Scan Rules Alpha v19. https://github.com/zaproxy/zaproxy/wiki/FAQAddonVersions]
 - OS: [e.g. Windows 10]
 - Java: [e.g. openjdk version "1.8.0_171"]
 - Browser: [e.g. chrome 66, firefox 59, safari 11.1]

**Errors from the zap.log file**
See the attached log file from the .ZAP_D/zap.log in the container

[zap.txt](https://github.com/zaproxy/zaproxy/files/3639677/zap.txt)

 for the location of the zap.log file for your OS.

**Additional context**

**Comment by kingthorin** [comment]
This seems to be a platform or thirdparty app (webswing/xvfb) issue not a zap issue.

**Comment by thc202** [comment]
More likely a misconfiguration: `Request to API URL http://localhost:8090/ from 172.17.0.1 not permitted`, you can configure ZAP to allow "remote" access in the API options https://github.com/zaproxy/zaproxy/wiki/FAQremote
