### ISSUE TITLE
Not support POST method when using postman

### ISSUE THREAD

**Issue by royoan** [zaproxy/zaproxy#5592]
**Describe the bug**
I using postman set the ZAP proxy, and using postman to test the microservice interface,
When I submit a post request, ZAP will translate it to a get request, It' very strange.
Other  method seems  have this issue also. e.g. PATCH

**To Reproduce**
1. Launch ZAP
2. Launch Postman and set the proxy, see figure-1
3. Make an POST method, see figure-2
4. See the history of the ZAP, will see it have an get request

**Expected behavior**

**Screenshots**

![postman-proxy-setting](https://user-images.githubusercontent.com/5915563/65499709-a39cf280-def0-11e9-9589-9a0fdd6e76a8.jpg)
[figure-1]
![postman-post-request](https://user-images.githubusercontent.com/5915563/65499975-1d34e080-def1-11e9-82e5-fbcaad06321d.jpg)
[figure-2]

**Software versions**
 - ZAP: 2.8.1
 - OS:  Kali
 - Java: [e.g. oracle jdk version "1.8.0_171"]
 - Browser: postman

**Errors from the zap.log file**
n/a

**Additional context**
n/a

**Comment by psiinon** [comment]
Strange. Do you have any ZAP scripts enabled?

**Comment by thc202** [comment]
Could you also show the GET request in ZAP?

**Comment by royoan** [comment]
Yes, I enabled http send script, but just add a authorization head,no change the Method,
![image](https://user-images.githubusercontent.com/5915563/65561506-49924080-df75-11e9-91cf-1cec554a24f8.png)
![zap_http_sender_script](https://user-images.githubusercontent.com/5915563/65561516-5151e500-df75-11e9-8426-40672241b8ec.jpg)

**Comment by royoan** [comment]
Even I disable the httpsender script, ZAP proxy also cannot support the POST method when use Postman!

**Comment by thc202** [comment]
Odd, ZAP does not change the method unless specified (e.g. Proxy script, Replacer rules). Worth checking the zap.log, also, start ZAP with a clean home (`-dir` [1]) to discard any custom configurations.

[1] https://github.com/zaproxy/zap-core-help/wiki/HelpCmdline

**Comment by kingthorin** [comment]
You could double check if you have the proxy script "Change all POSTs to GETs.zst" enabled.

https://github.com/zaproxy/community-scripts/tree/master/proxy

**Comment by kingthorin** [comment]
These might also be relevant: 

- https://support.getpostman.com/hc/en-us/articles/211913929-I-sent-a-POST-request-but-Postman-seems-to-be-sending-a-GET-request-
- https://github.com/postmanlabs/postman-app-support/issues/450
- https://github.com/postmanlabs/postman-app-support/issues/1490
- https://github.com/postmanlabs/postman-app-support/issues/1687

You could use wireshark to see what postman is actually sending.

**Comment by kingthorin** [comment]
@rayoan any news?

**Comment by royoan** [comment]
Hi, sorry for update it in time, the issue still exists.....

**Comment by kingthorin** [comment]
Did you find anything with Wireshark? Do any of the previously linked issues (from the postman repo) mirror behaviour you're experiencing?

**Comment by royoan** [comment]
> Did you find anything with Wireshark? Do any of the previously linked issues (from the postman repo) mirror behaviour you're experiencing?
> 
> Edit: Can you attach the wireshark pcap?

No, There is no Wireshark in my laptop. So I can't provide the pcap.
I only compared switch on/off proxy on Postman. 
When no proxy, the post request is correct and get the correct response from server.
But if I set the ZAP proxy, the post request will change to get method and the response is also wrong.
May be it's Postman's bug?

I update Postman today, I will try to test again later.
 Thank you, @kingthorin

**Comment by skyevil12** [comment]
@royoan, I use ZAP in my android app and met this issue as well.
After turned off ZAP HUD, the post request work normally. Maybe you could try it...

**Comment by royoan** [comment]
> @royoan, I use ZAP in my android app and met this issue as well.
> After turned off ZAP HUD, the post request work normally. Maybe you could try it...

Are you mean turn off HUD add-on? @skyevil12

**Comment by skyevil12** [comment]
![Zap_Hud](https://user-images.githubusercontent.com/6906187/70589624-1d4c9e80-1c0b-11ea-9cdd-89f3271fb643.png)
@royoan Yes. Turn off it by clicking the HUD toggle button.
