### ISSUE TITLE
Update documentation for showing localhost traffic from Firefox in history

### ISSUE THREAD

**Issue by jmakr0** [zaproxy/zaproxy#5593]
Just ran into the problem that ZAP 2.8.0 doesn't list the localhost traffic in its history. After a bit, I found the solution here #5474 

Since, as far as I can tell, this issue is not officially documented, it makes sense to update the [FAQ](https://github.com/zaproxy/zaproxy/wiki/FAQlocalhost) for testing applications on localhost noting at least the solution for Firefox:

Go to: `about:config`
```
network.proxy.allow_hijacking_localhost = true
```

**Comment by thc202** [comment]
For the record, the help page was updated to mention that:
https://github.com/zaproxy/zap-core-help/blob/9b772751e493dec0a1418d216e3cf5d38d15d48f/addOns/help/src/main/javahelp/contents/start/proxies.html#L45

**Comment by kingthorin** [comment]
Done.
