### ISSUE TITLE
ZAP Baseline Failed to start ZAP

### ISSUE THREAD

**Issue by theHackPot** [zaproxy/zaproxy#5605]
**Describe the bug**
When attempting to execute a baseline scan against a target in Jenkins pipeline ZAP fails to start

**To Reproduce**
1. Added ZAP baseline image as a dedicated node 
![Slave_Node](https://user-images.githubusercontent.com/17269499/65951479-08e46c80-e438-11e9-9a58-3683f8563667.JPG)

2. Execute baseline script with -h produces expected output
![runninghelp](https://user-images.githubusercontent.com/17269499/65951673-71cbe480-e438-11e9-9344-52f3115a7f95.JPG)

3. Attempt to run a scan against a target produces this error
![Output](https://user-images.githubusercontent.com/17269499/65951782-adff4500-e438-11e9-8bfd-46af6040dc35.JPG)

4. Pipeline Script 

![ZAP Baseline](https://user-images.githubusercontent.com/17269499/65951949-f454a400-e438-11e9-8553-42792a6b5f88.JPG)

**Comment by psiinon** [comment]
@theHackPot do you have docker installed on the jenkins server or slaves (as appropriate)?

**Comment by theHackPot** [comment]
@psiinon yep docker is installed. I have tested another slave node using a docker image and it works.

Do I need to mount a volume maybe?

**Comment by psiinon** [comment]
Not sure - its not a configuration I've tried. It should work though, as long as everything required is installed...

**Comment by theHackPot** [comment]
I set the -dir to $WORKSPACE and -installdir to /zap

`
/zap/zap-baseline.py -z "-dir $WORKSPACE -installdir /zap" -r zaprpt.html -t https://demo.testfire.net  || return_code=$?
                    echo "exit value was  - " $return_code 
`
Its working now

**Comment by psiinon** [comment]
thanks for letting us know!
