### ISSUE TITLE
The INFO flag is boolean and is ignoring a list of id's. 

### ISSUE THREAD

**Issue by ksiadz** [zaproxy/zaproxy#5608]
**Describe the bug**
The -i flag is supposed to take a list of ids which should be INFO instead of WARN. Instead of doing that it is changing settings of result to INFO all issues as the info_unspecified at: https://github.com/zaproxy/zaproxy/blob/bf4e040b398e4873e1b9f5a08fb245131eb3c601/docker/zap-full-scan.py#L184
is setting boolean value rather than taking a list and passing it further.

**To Reproduce**
`
docker run owasp/zap2docker-stable:2.8.0  zap-full-scan.py -t https://example.com -i 10015
`
**Expected behavior**
INFO-NEW: Incomplete or No Cache-control and Pragma HTTP Header Set [10015] x 5
WARN-NEW: Web Browser XSS Protection Not Enabled [10016] x 18
WARN-NEW: X-Frame-Options Header Not Set [10020] x 2
WARN-NEW: X-Content-Type-Options Header Missing [10021] x 10

**Screenshots**
<img width="1030" alt="Screenshot 2019-10-02 at 12 20 20" src="https://user-images.githubusercontent.com/20033156/66040457-597ac900-e50f-11e9-8d2f-ed0335ce6d88.png">

**Software versions**
 - ZAP: 2.8.0
 - Add-on: zap-full-scan
 - OS: docker

**Comment by kingthorin** [comment]
> 
> **Describe the bug**
> The -i flag is supposed to take a list of ids which should be INFO instead of WARN. Instead of doing that it is changing settings of result to INFO all issues as the info_unspecified at:
> 

What gave you that idea?

Here's what the commandline help says:
`-i                default rules not in the config file to INFO'`

**Comment by kingthorin** [comment]
No further user input after a week, closing.
