### ISSUE TITLE
Wiki - DevExtending "Forced Browse" broken link

### ISSUE THREAD

**Issue by patrickceg** [zaproxy/zaproxy#5611]
**Describe the bug**
The [DevExtending forced browse](https://github.com/zaproxy/zaproxy/wiki/DevExtending#custom-forced-browse-files) Wiki page has a link "You can add your own forced browse files by via:", but the heading the forced browse link is supposed to point to does not exist, sending you to the main wiki page https://github.com/zaproxy/zap-core-help/wiki.

(apologies if documentation issues need to go somewhere else - just message me about it and I can move and rewrite for wherever a document bug goes)

**To Reproduce**
1. Browse to https://github.com/zaproxy/zaproxy/wiki/DevExtending#custom-forced-browse-files
2. Click on the link "forced browse"
3. Instead of a forced browse description, you end up on the wiki main page

**Expected behavior**
After step 2, you should be at a page describing forced browse

Either that, or if the page is still in progress / unstable / outdated, then there should be a flair or other notice message at the top of the page to prevent new readers like me from wandering blindly :)

**Screenshots**
The link in question

![image](https://user-images.githubusercontent.com/19738617/66215242-2bbd8d80-e691-11e9-8ac5-09bc0be3b4d3.png)

**Software versions**
https://github.com/zaproxy/zap-core-help/wiki as of October 4th, 2019

**Comment by thc202** [comment]
Thanks, the new page is: https://github.com/zaproxy/zap-core-help/wiki/HelpAddonsBruteforceConcepts
Will fix that (and the other broken links) shortly.

**Comment by thc202** [comment]
Done in [f5a6f89](https://github.com/zaproxy/zaproxy/wiki/DevExtending/_compare/f5a6f89%5E...f5a6f89).
