### ISSUE TITLE
Nested Data Driven Nodes

### ISSUE THREAD

**Issue by crunchcat** [zaproxy/zaproxy#5616]
**Describe the bug**
Cannot create nested data-driven nodes. When attempted, ZAP creates duplicate entries in the tree for each entry in the Structural Modifiers table.

**To Reproduce**
1. Visit a page with nested data-driven nodes to populate the tree in the sidebar.
2. Right click on parent data-driven node > Flag as Context > ... Data-Driven Node. Confirm.
3. Right click on child data-driven node > Flag as Context > ... Data-Driven Node. Confirm.
4. Notice the tree for each node has been duplicated into two trees containing one data-driven node each.
    For the tree containing the parent data-driven node, requests directly to the child DDN will each be listed as separate endpoints and requests to children of the child DDN are missing. The tree containing the child data-driven node is duplicated for each value of the parent DDN but requests to it's children are displayed properly. 

**Expected behavior**
Data driven nodes should be aware of each other and able to be nested. The site tree should be updated to properly display each of the data-driven nodes without duplicate entries for each value of either node.

**Screenshots**
I can't easily attach screenshots but here's a representation of the tree sidebar after nested DDNs are configured for the context. In this example, the app returns hostnames and uptime for multiple user devices, DDN1 is a user ID and DDN2 is a device ID.

- Context
    - Example.com
- Sites
    - https://example.com
        - users
            - \<\<DDN1\>\>
                - devices
                    - GET:device1
                    - GET:device2
            - user1
                - devices
                    - \<\<DDN2\>\>
                        - GET:hostname
                        - GET:uptime
            - user2
                - devices
                    - \<\<DDN2\>\>
                        - GET:hostname
                        - GET:uptime

An example URL would be `https://example.com/users/user1/devices/device1/hostname`

**Software versions**
 - ZAP: 2.8.0
 - Add-on: `[[id=accessControl, version=5.0.0],
[id=alertFilters, version=9.0.0], [id=ascanrules,
version=33.0.0], [id=bruteforce, version=8.0.0], [id=diff,
version=9.0.0], [id=directorylistv1, version=3.0.0],
[id=directorylistv2_3, version=3.0.0], [id=fuzz,
version=11.0.0], [id=gettingStarted, version=10.0.0],
[id=help, version=9.0.0], [id=hud, version=0.7.0],
[id=importurls, version=6.0.0], [id=invoke, version=9.0.0],
[id=jxbrowser, version=14.0.0], [id=jxbrowsermacos,
version=12.0.0], [id=onlineMenu, version=6.0.0],
[id=openapi, version=13.0.0], [id=pscanrules,
version=24.0.0], [id=quickstart, version=26.0.0],
[id=replacer, version=7.0.0], [id=reveal, version=2.0.0],
[id=saml, version=8.0.0], [id=saverawmessage,
version=4.0.0], [id=savexmlmessage, version=0.0.1],
[id=scripts, version=25.0.0], [id=selenium, version=15.0.0],
[id=spiderAjax, version=23.0.0], [id=tips, version=6.0.0],
[id=viewstate, version=1.0.0], [id=webdrivermacos,
version=12.0.0], [id=websocket, version=20.0.0], [id=zest,
version=29.0.0]]`
 - OS: MacOS 10.14.6 (Mojave)
 - Java: AdoptOpenJDK 1.8.0_212
 - Browser: N/A

**Errors from the zap.log file**
A bunch of errors in the form of: (apologies for not being able to post complete logs)
```
2019-10-07 18:43:11,614 [AWT-EventQueue-0] WARN  ContextAccessRulesManager - Unable to find path segment while infering rule for devices (https://example.com/users/user1/devices): «DDN1»
```

Errors vary in endpoint and URL but are all appended with the `«DDN1»` identifier.

**Additional context**
The site structure features of Zap are some of my favorite. This type of stuff isn't really well handled by any of the MITM proxies out there and it makes my tests WAYY easier. It seems this edge case isn't being properly handled.  Would be nice if this could be implemented but for the time being maybe a warning to users to avoid confusion would be sufficient.

Thanks for the great work!

**Comment by psiinon** [comment]
FYI site map modifiers do support nested DDNs - the example script demonstrates them.

**Comment by kingthorin** [comment]
Closing per previous response.
