### ISSUE TITLE
Authentication handling improvements

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#5633]
Tracker for any changes that improve how ZAP handles authentication, especially for modern web apps.

- [x] #5609 Propagate authentication state to browsers
- [x] #5630 Support session management scripts - PR https://github.com/zaproxy/zaproxy/pull/5665

**Comment by globeone** [comment]
Is this the bug to put in a feature request for a Authentication Macro Recorder? 
In WebInspect you can perform a manual authentication once and in a sense showing the computer how to log in. It then remembers the steps and then reuses them in subsequent login attempts. This is especially necessary in the new two (or three) page logins. Where the Username and password are on separate pages.

**Comment by kingthorin** [comment]
@globeone one of the original items above has been completed (Session management scripts), for the other one (propagating state to browsers) is a work in progress (https://github.com/zaproxy/zap-extensions/pull/2300).

There are probably other things that could be done to make it easier on users.

If you're interested in tackling something auth related I'd suggest having a look at this unfinished PR from a previous GSoC: https://github.com/zaproxy/zap-extensions/pull/1712

Unless @thc202 or @psiinon have other ideas (I'm open to discussion).

**Comment by psiinon** [comment]
All completed.
