### ISSUE TITLE
Unable to select options panel with duplicated name

### ISSUE THREAD

**Issue by DouglasDRF** [zaproxy/zaproxy#5637]
There's an option in the Options Menu that seems duplicated on Windows version 2.8.0
**With me, the issue only happned in Portuguese language.**
In English it's not happening. Other langauges should be checked too.

Tools -> Options -> Passive Scan Tools
There are both Passive Scan options with the same window

<img src="https://i.imgur.com/b0JJzi8.png">

<img src="https://imgur.com/tV7V7KK.png">

<img src="https://imgur.com/PswSolV.png">

**Software versions**
 - OS: Windows 10 (1903, build 18362.418)
 - Java: 1.8.0_221

**Comment by thc202** [comment]
While they have the same name they do not represent the same options (the translation is not accurate).

**Comment by kingthorin** [comment]
Not that it mattes for this issue, but out of curiosity: Why are you still using 2.8.0?

**Comment by thc202** [comment]
It's an old issue, probably the latest at the time.

**Comment by kingthorin** [comment]
Oops, sorry didn't notice the date(s).
