### ISSUE TITLE
add Retire.js addon to zap in headless mode

### ISSUE THREAD

**Issue by Strieglitz** [zaproxy/zaproxy#5639]
Hello, i'am trying to add the Retire.js addon to zap in headless mode. 
https://github.com/h3xstream/burp-retire-js
What i tried :
- adding the addon file via the python api  `zap.autoupdate.install_local_addon(addonFileToInstall)`
   but the python-zap-api is on zap version 2.4 where install_local_addon was not implemented
- using the command line argument when starting zap   `zap.sh .....  -addoninstall <addonToInstall>`
   but the retire.js addon is not in the zap marketplace (addoninstall reqiures an addon id listed in the marketplace )
- using curl to connect to the api but i could not figure out how to sent the addon file via curl
maby someone know how to add the none-marketplace-addon retire.js in headless mode to zap

**Comment by thc202** [comment]
You need to copy it to the "plugin" dir in the ZAP home. [1]
(If you want to use `install_local_addon` you need to start ZAP with  `-dev` command line argument, that's intended just for development though.)

[1] https://github.com/zaproxy/zaproxy/wiki/FAQconfig

**Comment by thc202** [comment]
Related issue #3742.

**Comment by Strieglitz** [comment]
I'am still having trouble with this :
> If you want to use install_local_addon you need to start ZAP with -dev command line argument 
as i underastand install_local_addon is not an command line argument for starting the zap.sh ? install_local_addon should be the name of the python-api call, but the python-api is on api version 2.4 and in this version there is no install_local_addon Method provided and there is no python-api on higher versions, so i thought there is maby an command line argument.

**Comment by kingthorin** [comment]
Per pypi `v2.4 0.0.15 ` is actually the latest with support for ZAP 2.8
https://pypi.org/project/python-owasp-zap-v2.4/

**Comment by thc202** [comment]
@Strieglitz were you able to try with the above version?

**Comment by Strieglitz** [comment]
@thc202  sorry, i had no time to try it yet, but will leave an feedback when i try

**Comment by kingthorin** [comment]
It's been over a month with no follow-up. Closing.
