### ISSUE TITLE
Not able to Run Security Test using ZAP. Getting  Failed to establish a new connection error

### ISSUE THREAD

**Issue by AgrawalHimanshu** [zaproxy/zaproxy#5643]
Getting this error while running code-
requests.exceptions.ProxyError: HTTPConnectionPool(host='127.0.0.1', port=8090): Max retries exceeded with url: http://127.0.0.1/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A00F75E948>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))

**Comment by kingthorin** [comment]
Is it actually on 8090? Is there a host firewall blocking connections?

**Comment by AgrawalHimanshu** [comment]
yes... you can set any port number. So it it 8090. And there is no firewall

**Comment by kingthorin** [comment]
Okay provide more detail then.

How is ZAP configured? (Local proxies, chained proxies, etc)
How are you accessing it?
How is the target setup?

**Comment by kingthorin** [comment]
No follow-up in over a month. Closing.
