### ISSUE TITLE
[Question] CSP Scanner: Wildcard Directive alert for OpenID Connect session management endpoint

### ISSUE THREAD

**Issue by yukund** [zaproxy/zaproxy#5646]
We used ZAP 2.8 to scan our angular web application implemented with IdentityServer4 (implicit flow).It generated a Wildcard Directive alert (show in below), I am not sure it is a security issue or not.

If it is a security issue, what should we do? The OpenID Connect session management endpoint is not part of our app, it is IdentityServer4 build-in functionality. any suggestions? thanks

-----------------------------------------------------------------------------
Medium (Medium) | CSP Scanner: Wildcard Directive
-- | --
Description | The following directives either allow wildcard sources (or ancestors), are not defined, or are overly broadly defined:frame-ancestor
 
URL | https://hostname:52801/services.identity/connect/checksession
Method | GET
Parameter | Content-Security-Policy
Evidence | default-src 'none'; script-src 'sha256-ZT3q7lL9GXNGhPTB1Vvrvds2xw/kOV0zoeok2tiV23I='
Instances | 1
Solution | Ensure that your web server, application server, load balancer, etc. is properly configured to set the Content-Security-Policy header.

**Comment by psiinon** [comment]
Please dont raise issues for questions - the ZAP User Group is a better forum for them: https://groups.google.com/group/zaproxy-users

**Comment by kingthorin** [comment]
S.O. Answer &gt; https://stackoverflow.com/questions/58536555/csp-scanner-wildcard-directive-alert-for-openid-connect-session-management-endp/58559365#58559365
