### ISSUE TITLE
RootCA won't work on iOS

### ISSUE THREAD

**Issue by Ali-Razmjoo** [zaproxy/zaproxy#5650]
Hi,

I am trying to use zaproxy on new iOS but it seems it's not working, so I had a bit of search and I see this url https://support.apple.com/en-us/HT204132

> We are taking further actions to protect users in an upcoming security update. Apple products will block certificates from WoSign and StartCom root CAs if the "Not Before" date is on or after **1 Dec 2016 00:00:00 GMT/UTC.**

it would be great if someone can fix this issue.

zap certs are valid from the day of generation (I guess) so it won't work.

![image](https://user-images.githubusercontent.com/7676267/67605811-bb7dc580-f77f-11e9-8b3b-62a26c66c2ef.png)

Thanks.

**Comment by thc202** [comment]
Did you try with a weekly release? The Root CA cert validity period was changed recently (#5598).

From the user group https://groups.google.com/d/topic/zaproxy-users/7-TyFDPWu2o/discussion it was pointed out this https://support.apple.com/en-us/HT210176 (among other things mentions the validity).

**Comment by kingthorin** [comment]
The bit you quoted is irrelevant as ZAP's certs (CA or site) have nothing to do with WoSign or StartCom.

**Comment by Ali-Razmjoo** [comment]
@thc202 weekly release worked, @kingthorin you right, i skipped reading the whole thing. thanks for quick response.

**Comment by kingthorin** [comment]
Thanks for letting us know.
