### ISSUE TITLE
"alert" api component is not in api libs

### ISSUE THREAD

**Issue by simchev** [zaproxy/zaproxy#5661]
The ZAP API has an alert component documented here: https://github.com/zaproxy/zaproxy/wiki/ApiGen_alert.

The same alert function doesn't seem to be available in the api libs (in my case specifically the javascript node api: https://github.com/zaproxy/zap-api-nodejs).

Is this intended? Or did I miss it?

**Comment by kingthorin** [comment]
Alerts are part of core: https://github.com/zaproxy/zap-api-nodejs/blob/master/src/core.js

**Comment by thc202** [comment]
They were moved to its own API in 2.8.0 though, it seems the client was not yet regenerated.

**Comment by simchev** [comment]
I see. Is it documented somewhere? If not, it might be a good idea to prevent confusion.

**Comment by thc202** [comment]
Closing this with the work done in zaproxy/zap-api-nodejs#26. (Note that the new version was not yet released.)
