### ISSUE TITLE
API call core.snapshotSession not working properly in node lib

### ISSUE THREAD

**Issue by simchev** [zaproxy/zaproxy#5668]
API Call: core.snapshotSession
Lib: https://github.com/zaproxy/zap-api-nodejs

The ZAP API is expecting 2 arguments, the "name" which can be a filepath, and "overwrite", which is a boolean to overwrite existing or not. When using the call in the node lib, the arguments are ignored and the default behavior is used (sessionName-timestamp in the ZAP session directory). 

Workaround: I made the request directly (using request-promise-native), copying the request options used in the node lib.

Test: client.core.snapshotSession(name, true);
Workaround: this.request(\`${this.baseUrl}/JSON/core/action/snapshotSession/?name=${name}&overwrite=true\`);

Looks like the libs need some love.

**Comment by thc202** [comment]
Closing, the implementation was reworked in the meantime (not yet released).
