### ISSUE TITLE
API call core.saveSession unexpected behavior

### ISSUE THREAD

**Issue by simchev** [zaproxy/zaproxy#5669]
API Call: core.saveSession

When executing the request to save the session with the name and overwrite=true, the first time it works and overwrite the session, but each subsequent requests give an error code "already_exists". Unless I misunderstood the behavior of "overwrite", this looks like undesired behavior.

To reproduce:

1. Open ZAP
2. Save your session
3. Save your session using overwrite=true
4. Redo step #3

**Comment by kingthorin** [comment]
It's a DB you don't need to save it multiple times.

**Comment by simchev** [comment]
I see, then what's the overwrite option for? I thought the saveSession did something similar to snapshotSession. If it's intended, I guess you can close this issue.

**Comment by kingthorin** [comment]
Sorry let me be more clear. Yes, you should be able to overwrite multiple times. However, functionally the file(s) are a DB so you shouldn't need to do it more than once.

**Comment by thc202** [comment]
> Yes, you should be able to overwrite multiple times.

If it's not the session already in use, otherwise it's already saved and that's why it fails with `already_exists`.

**Comment by thc202** [comment]
Closing, the described behaviour is the expected (#5676 should make that clear).
