### ISSUE TITLE
New passive scan rule for dangerous js functions

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#5673]
This should scan javascript files and javascript in HTML for dangerous JS functions.
See https://github.com/danielmiessler/SecLists/issues/367 which already links to a PR for Angular ones.
Ideally the rule should include the relevant framework in the alert description.
I plan to look at this soonish, but if anyone else fancies a go at a relatively simple passive scan rule then just get in touch!

**Comment by psiinon** [comment]
Note that passive scan rules have access to the parsed DOM so extracting javascript shouldnt be too hard...

**Comment by psiinon** [comment]
Also see https://zaproxy.blogspot.com/2014/04/hacking-zap-3-passive-scan-rules.html which is a bit old but should still be mostly relevant.

**Comment by jvehent** [comment]
Could you pass the extracted javascript to `eslint` to do some of the linting?

**Comment by psiinon** [comment]
@jvehent the only runtime dependency was have for ZAP is Java 8+ and we want to keep it that way. We could provide optional support eslint if we can find (or have configured) a node install, but I suspect that might not work out-of-the-box for many people.
Java does include a JavsScript engine so In theory we might be able to run eslint in Java without Node installed, but that might be tricky to set up.
Anyone got any other ideas how we could make this happen? Being able to run eslint in ZAP would be awesome :)

**Comment by madanalogy** [comment]
As an initial implementation, would the functions listed under the linked PR be sufficient or were you hoping for a more comprehensive list of dangerous JS functions? If the latter, where would be a good starting point for further research? I'm interested in working on this :)

**Comment by kingthorin** [comment]
Using that as a starting point seems fine to me.

**Comment by madanalogy** [comment]
I would like to be assigned this issue please. I am currently drafting the scan rule and should be putting up a PR in a couple of days, thank you!
