### ISSUE TITLE
Issues with active scan ZAP CLI Docker 

### ISSUE THREAD

**Issue by teodem** [zaproxy/zaproxy#5674]
Hi,
I'm having some problems with the active scan in ZAP CLI (Docker Image) .

I got the 'proxy' error, now instead, after some modifications, I get this error:

```
zap-cli active-scan - scanners xss, sqli --recursive https: //
Traceback (most recent call last):
   File "/ usr / local / bin / zap-cli", line 11, in
     sys.exit (cli ())
   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 664, in call
     return self.main (* args, ** kwargs)
   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 621, in main
     raise RuntimeError ('Click will abort further execution'

RuntimeError: Click will abort further execution because Python is configured to use ASCII as encoding for the environment. Either switch to Python 2 or consult http://click.pocoo.org/python3/ for mitigation steps.

```
Has anyone already had the same problem or knows how I could solve it? Thank you all

**Comment by psiinon** [comment]
ZAP CLI is a third party product and not supported by the ZAP core team.
You could try asking on the Dev Group?
Also, have you tried the packaged scans? We do support those :)
https://github.com/zaproxy/zaproxy/wiki/Packaged-Scans

**Comment by teodem** [comment]
Hi, ok i wasn't warned about that, thanks for the information!
But by using the ZAP Full Scan included in the Packaged Scans, the scan get blocked at this point: 
`INFO org.zaproxy.zap.DaemonBootstrap  - ZAP is now listening on 0.0.0.0:45821`
Do you know what is the problem due to? Thanks again

**Comment by psiinon** [comment]
Well, that just means ZAP has started correctly and is listening on that port. Try using the `-d` flag to get debug messages? If that doesnt help can you share the command you are using to launch it, replacing you target url with something innocuous ;)

**Comment by teodem** [comment]
Yeah, I figured :)
But it becomes a bit complicated to work with GitLab with this. 
Is there any way to get results directly as with Baseline Command?
Thx

**Comment by psiinon** [comment]
It should work in exactly the same way as the baseline scan, but will probably take significantly longer.
By default theres no spider time limit - for the baseline scan this is set to just one minute. You can use the `-m` flag to change that.

**Comment by psiinon** [comment]
We use the baseline scan everyday at Mozilla and the full scan every week, so I'm pretty sure its working ok for some set of parameters ;)

**Comment by teodem** [comment]
Actually i was more interested in an active and more in-depth scan, that's why i asked you about this feature ;) 
Anyway, setting the timer seems to work, thanks a lot!!
