### ISSUE TITLE
Zap doesn't parse swagger url properly for some links

### ISSUE THREAD

**Issue by chriswalz** [zaproxy/zaproxy#5678]
**Describe the bug**

**To Reproduce**
1. docker pull owasp/zap2docker-stable
2. this is parsed correctly: docker run -t owasp/zap2docker-stable zap-api-scan.py -t https://www.example.com/openapi.json -f openapi
3. This is parsed inccorectly: docker run -t owasp/zap2docker-stable zap-api-scan.py -t https://firebasestorage.googleapis.com/v0/b/example-landing.appspot.com/o/swagger%2Fpetstore.json?alt=media&token=c7054566-36dc-4fec-9cdc-e947de7bdc34 -f openapi

**Expected behavior**

**Screenshots**
Success:
<img width="1013" alt="Successfully parse swagger url" src="https://user-images.githubusercontent.com/6971318/68534668-04e41e00-0305-11ea-916a-a84fc797a455.png">

Failure:
<img width="1014" alt="Screen Shot 2019-11-09 at 3 27 10 PM" src="https://user-images.githubusercontent.com/6971318/68534797-a1f38680-0306-11ea-94e4-4f6082df82a4.png">

**Software versions**
 - ZAP: docker -  owasp/zap2docker-stable
 - OS: Mac Mojave
 - Java: 9
 - Browser: chrome 78

**Errors from the zap.log file**
See https://github.com/zaproxy/zaproxy/wiki/FAQconfig for the location of the zap.log file for your OS.

**Additional context**

**Comment by kingthorin** [comment]
Pretty sure this is just a CLI issue not a ZAP issue, likely the URL value in the second case needs to be quoted or have characters escaped.

**Comment by chriswalz** [comment]
Thanks that worked.. for anyone else who had the same problem just wrap the url in quotes: 

docker run -t owasp/zap2docker-stable zap-api-scan.py -t "https://firebasestorage.googleapis.com/v0/b/example-landing.appspot.com/o/swagger%2Fpetstore.json?alt=media&token=c7054566-36dc-4fec-9cdc-e947de7bdc34" -f openapi

**Comment by kingthorin** [comment]
Thanks for letting us know.
