### ISSUE TITLE
HTML tags in other reports (JSON and XML)

### ISSUE THREAD

**Issue by simchev** [zaproxy/zaproxy#5685]
This isn't a big deal, but I'm wondering why there's html tags in the XML and JSON reports. Generally we'll use the JSON and XML reports for processing (ex: convert to another format like unit test reports), but there's extra html noise in messages (specifically paragraphs \<p\>).

**Comment by psiinon** [comment]
Thats historical :) I agree that really there shouldnt be any HTML in the XML/JSON reports.

**Comment by thc202** [comment]
We should address this with/for the new Report Generation add-on, added to #6483.

**Comment by psiinon** [comment]
The alerts should not include any HTML tags - they were added as part of report generation.
The new Reporting add-on uses different templates for HTML/XML/JSON reports and will therefore not add any HTML tags to XML/JSON reports.
