### ISSUE TITLE
Path Traversal False Positive

### ISSUE THREAD

**Issue by wulf2468** [zaproxy/zaproxy#5686]
**Describe the bug**
When using ASP.NET MVC path traversal often reports a false positive by placing the last part of the URL into free form fields of a form. This ends up being the controller or action. If the URL of the form is `https://abc.com/xyz/home` then it would place home in the free form fields and will error saying path traversal. It also doesn't give any evidence, so it's very confusing as to why it thinks it's an issue.

**To Reproduce**
1. Run ZAP with default settings on an ASP.NET MVC site with a form post

**Expected behavior**
Path traversal should not show up. Or at the very least it should have more information in the evidence about why it thinks this specific case is a problem.

**Software versions**
 - ZAP: 2.8.0
 - Add-on: Active scanner rules 33.0.0
 - OS: Windows 10
 - Java: Version 8 Update 231 (build 1.8.0_231-b11)
 - Browser: Firefox 70.0.1 (64-bit)

**Errors from the zap.log file**
I replaced the specific URL information with generic info as I can't post the actual URL.

> 2019-11-12 12:07:31,858 [ZAP-ActiveScanner-0] DEBUG TestPathTraversal - It is possible to check for local file Path Traversal on the url filename on [POST] [https://domain.com/subdirectory1/subdirectory2/controller], [FirstName]
> 2019-11-12 12:07:31,858 [ZAP-ActiveScanner-0] DEBUG VariantMultipartFormParameters - i: 4 pos: 5 S: 59281 E: 59287
> 2019-11-12 12:07:31,858 [ZAP-ActiveScanner-0] DEBUG HttpSender - Sending POST https://domain.com/subdirectory1/subdirectory2/controller
> 2019-11-12 12:07:31,858 [ZAP-ActiveScanner-0] DEBUG HttpSessionsSite - Matching session for request message (for site domain.com:443): HttpSession [name=Session 0, active=false, tokenValues='ASP.NET_SessionId=anp34pdmtpcgf5z3fjtehabq']
> 2019-11-12 12:07:31,858 [ZAP-ActiveScanner-0] DEBUG HttpSessionsSite - No active session is selected.
> 2019-11-12 12:07:31,874 [ZAP-ActiveScanner-0] DEBUG HttpSender - Sending message to: https://domain.com/subdirectory1/subdirectory2/controller
> 2019-11-12 12:07:32,155 [ZAP-ActiveScanner-0] DEBUG HttpSender - SUCCESSFUL
> 2019-11-12 12:07:32,155 [ZAP-ActiveScanner-0] DEBUG HttpSender - Received response after 297ms for POST https://domain.com/subdirectory1/subdirectory2/controller
> 2019-11-12 12:07:32,155 [ZAP-ActiveScanner-0] DEBUG HttpSender - Sending GET https://domain.com/subdirectory1/subdirectory2/controller/action
> 2019-11-12 12:07:32,155 [ZAP-ActiveScanner-0] DEBUG HttpSessionsSite - Matching session for request message (for site domain.com:443): HttpSession [name=Session 0, active=false, tokenValues='ASP.NET_SessionId=anp34pdmtpcgf5z3fjtehabq']
> 2019-11-12 12:07:32,155 [ZAP-ActiveScanner-0] DEBUG HttpSessionsSite - No active session is selected.
> 2019-11-12 12:07:32,155 [ZAP-ActiveScanner-0] DEBUG HttpSender - Sending message to: https://domain.com/subdirectory1/subdirectory2/controller/action
> 2019-11-12 12:07:32,202 [ZAP-ActiveScanner-0] DEBUG HttpSender - SUCCESSFUL
> 2019-11-12 12:07:32,202 [ZAP-ActiveScanner-0] DEBUG HttpSender - Received response after 47ms for GET https://domain.com/subdirectory1/subdirectory2/controller/action
> 2019-11-12 12:07:32,202 [ZAP-ActiveScanner-0] DEBUG TestPathTraversal - New alert pluginid=6 Path Traversal uri=null
> 2019-11-12 12:07:32,202 [ZAP-ActiveScanner-0] DEBUG ExtensionAlert - alertFound Path Traversal https://domain.com/subdirectory1/subdirectory2/controller
> 2019-11-12 12:07:32,233 [AWT-EventQueue-0] DEBUG SiteMap - addPath https://domain.com/subdirectory1/subdirectory2/controller
> 2019-11-12 12:07:32,233 [AWT-EventQueue-0] DEBUG SiteMap - findAndAddChild Sites / https://domain.com
> 2019-11-12 12:07:32,233 [AWT-EventQueue-0] DEBUG SiteMap - findChild Sites / https://domain.com
> 2019-11-12 12:07:32,233 [AWT-EventQueue-0] DEBUG SiteMap - findAndAddChild https://domain.com / subdirectory1
> 2019-11-12 12:07:32,233 [AWT-EventQueue-0] DEBUG SiteMap - findChild https://domain.com / subdirectory1
> 2019-11-12 12:07:32,233 [AWT-EventQueue-0] DEBUG SiteMap - findAndAddChild subdirectory1 / subdirectory2
> 2019-11-12 12:07:32,233 [AWT-EventQueue-0] DEBUG SiteMap - findChild subdirectory1 / subdirectory2
> 2019-11-12 12:07:32,233 [AWT-EventQueue-0] DEBUG SiteMap - findAndAddLeaf subdirectory2 / controller
> 2019-11-12 12:07:32,233 [AWT-EventQueue-0] DEBUG SiteMap - findChild subdirectory2 / POST:controller(multipart/form-data)
> 2019-11-12 12:07:32,233 [ZAP-ActiveScanner-0] DEBUG SimpleEventBus - publishSyncEvent alert.added from org.zaproxy.zap.extension.alert.AlertEventPublisher

**Additional context**
This has appeared for multiple sites, all with different controllers/actions, so it isn't a specific word that it is catching, but it's always the controller or action from the URL being placed into free form fields of a form.

**Comment by kingthorin** [comment]
Seems like a duplicate of #4209.

Clarification about why this is being raised here:
https://github.com/zaproxy/zaproxy/issues/4209#issuecomment-355177979

The code is here: https://github.com/kingthorin/zap-extensions/blob/master/addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/TestPathTraversal.java if you want to propose a solution or submit a PR with a fix.

**Comment by wulf2468** [comment]
I looked at the existing issues, but none of them seemed to be POST related. In particular, that issue had URL parameters, so I thought that was what that one was about. However, it's still a GET request. It is related, but I'm not sure it's the same thing.

In my case, none of the GET requests fail. The only time it fails is if it's a POST where there are form fields that have loose or no validation. Then it can successfully pass in the last portion of the URL into the form fields and considers it a possible vulnerability. This happens on fields for name, address, city, username, password, etc.

From the looks of your post for clarification, the only reason that the other fields are not erroring for the same reason in my case, is because the server ends up redirecting them back to the original form page with an error message stating that the field is not valid for one reason or another. This error message happens to have a class of "Error". This means "Error" is in the response. If I didn't have that specific class name, it would most likely show this false positive on every single form field. (I will test this when I get a chance and see if it's true)

I can see testing the URL parameters, but are the form fields vulnerable to this as well? It seems like this particular case of false positive for path traversal will happen on the majority of websites with form posts.

**Comment by kingthorin** [comment]
@wulf2468 

>If I didn't have that specific class name, it would most likely show this false positive on every single form field. (I will test this when I get a chance and see if it's true)

What did you find?

> I can see testing the URL parameters, but are the form fields vulnerable to this as well? It seems like this particular case of false positive for path traversal will happen on the majority of websites with form posts.

It's impossible to say, we have zero control of how developer write things. It doesn't seem any more or less likely for a GET param to be used for a file, template, or path value than a POST param (so yes it's applicable to both cases).

**Comment by kingthorin** [comment]
@wulf2468 any update(s)?

**Comment by kingthorin** [comment]
Closing, no further input for requester.
