### ISSUE TITLE
Session snapshot not showing any data and report empty, but I have all session data

### ISSUE THREAD

**Issue by simchev** [zaproxy/zaproxy#5688]
I ran a zap test on the daemon of a fresh ZAP installation and the scan did work. I got an html report and a session snapshot. 

The problem is that my html report is empty (no alerts) and when I open the session snapshot in ZAP, I don't see any sites or urls. I do see the context that I created for the run.

In my session snapshot, I have 400 MB of session.data right next to the session.session file. If I check the content with a text editor, I can clearly see the request data.

Is it possible that since I never opened ZAP, there's a weird behavior with the session? When we open ZAP the first time, there's a popup about persisting sessions. I am currently rerunning my scan to see if it's related. Or maybe it's because there's too much data?

I also noticed that I had a session.lobs file in the snapshot. I normally don't have this file when I do a snapshot, but I don't know what it is for.

What can I verify in the snapshot files to see what's missing and preventing the session from seeing the sites/url? Or what can cause the sites/urls to be in the session.data but not appear in the session?

**Comment by thc202** [comment]
What was the problem?
