### ISSUE TITLE
Wait for add-ons to be installed

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#5704]
If you install, for example, the alpha scan rules then they are often not installed in time for them to be applied.
The packaged scripts should check to see if any add-ons are being installed and if so wait until then have completed.

**Comment by psiinon** [comment]
Looks like a new API call will be needed

**Comment by thc202** [comment]
Setting this to 2.9.0 per https://github.com/zaproxy/zaproxy/issues/4072#issuecomment-566452155.
