### ISSUE TITLE
Wrong Credentials - still Authentication Success message

### ISSUE THREAD

**Issue by sonawanesarvesh** [zaproxy/zaproxy#5705]
Hi
I am facing very strange issue - for demo website - www.testfire.net (where the standard credentials are - admin/ admin)

I am using ZAP 2.8 in API mode (formbased authentication) using powershell.  (I am starting .bat file in attack mode but not in daemon mode so that i can see the interactions on UI)

**When i pass the URL with valid credentials - i see authentication success message
Even when i pass wrong credentials - i see same authentication success message**

Steps i followed - 
1. i have one CSV file where i mention URL, Login Parameters (credentails, loginindicator, etc)
2) I add URL to Scanner (accessUrl)
2) Create Session (createEmptySession)
3) Start Spidering (scan)
4) Add regex into includeInContext (includeInContext)
5) Setting Form-Based authentication (setAuthenticationMethod)
6) Setting Encoded Login Regex Parameter (setLoggedInIndicator)
7) Setting Encoded Logout Regex Parameter (setLoggedOutIndicator)
8) Adding user name from Config file (newUser)
9) Enabling User (setUserEnabled)
10) Adding user credentials from config file (setAuthenticationCredentials)
11) Enable Force User Mode (setForcedUserModeEnabled)
12) Shift User to Force mode (setForcedUser)

In the Output Tab (In UI Mode) i always see Authentication Success message.

Apart from above, my main problem is - i need to track the failed authentication events easily (not in stats mode if possible)

**Comment by kingthorin** [comment]
Something must be wrong with your step 7 & 8.

You should get it working via the GUI first so that you actually understand how everything is working (or not) then export the context and just re-use it (import).

**Comment by sonawanesarvesh** [comment]
My 
login indicator is = http://testfire.net/bank/transaction.jsp

http://localhost:8080/JSON/authentication/action/setLoggedInIndicator/?apikey=8uhfd4rrlmune7mveoedc7ckfm&contextId=1&loggedInIndicatorRegex=http%3a%2f%2ftestfire.net%2fbank%2ftransaction.jsp


Logout indicator = http://testfire.net/index.jsp

http://localhost:8080/JSON/authentication/action/setLoggedOutIndicator/?apikey=8uhfd4rrlmune7mveoedc7ckfm&contextId=1&loggedOutIndicatorRegex=http%3a%2f%2ftestfire.net%2findex.jsp

**Comment by kingthorin** [comment]
Well first off your indicators are not regex as is expected.

Plus `http://testfire.net/bank/transaction.jsp` does not actually appear in the logged in content responses...

**Comment by kingthorin** [comment]
The ZAP User Group https://groups.google.com/group/zaproxy-users is a much better place for such discussions.

**Comment by sonawanesarvesh** [comment]
Hi
I have updated the process as per following - but still having same issue

When i pass the URL with valid credentials (admin / admin) - i see authentication success message
Even when i pass wrong credentials  (wrong_user/ wrong_pass) - i see same authentication success message



Steps i followed -

1. i have one CSV file where i mention URL, Login Parameters (credentails, loginindicator, etc)  
2. I add URL to Scanner (accessUrl)
3. Create Session (createEmptySession)
4. Add regex into includeInContext (includeInContext)
5. Setting Form-Based authentication (setAuthenticationMethod)
6. Setting Encoded Logout Regex Parameter (setLoggedOutIndicator)
7. Setting Encoded Login Regex Parameter (setLoggedInIndicator)
8. Adding user name from Config file (newUser)
9. Enabling User (setUserEnabled)
10. Adding user credentials from config file (setAuthenticationCredentials)
11. Enable Force User Mode (setForcedUserModeEnabled)
12. Shift User to Force mode (setForcedUser)

In the Output Tab (In UI Mode) i always see Authentication Success message.

My input file contains following details

1. URL = http://testfire.net	
2. Authentication = formBasedAuthentication
3. LoginURL = http://testfire.net/doLogin
4. LoginIndicator = \QSign Off\E
5. LogoutIndicator = \QSign In\E	
6. username = wrong_user
7. password = wrong_pass
8. loginbutton = btnSubmit=Login

My FormAuth API Call
http://localhost:8080/JSON/authentication/action/setAuthenticationMethod/?apikey=8uhfd4rrlmune7mveoedc7ckfm&contextId=1&authMethodName=formBasedAuthentication&authMethodConfigParams=loginUrl%3dhttp:%2f%2ftestfire.net%2fdoLogin%26loginRequestData
%3dusername%253D%257B%2525wrong_user%2525%257D%2526password%253D%257B%2525wrong_pass%2525%257D%2526btnSubmit%3dLogin

My Logout Indicator
http://localhost:8080/JSON/authentication/action/setLoggedOutIndicator/?apikey=8uhfd4rrlmune7mveoedc7ckfm&contextId=1&loggedOutIndicatorRegex=%5cQSign+In%5cE

My Login Indicator
http://localhost:8080/JSON/authentication/action/setLoggedInIndicator/?apikey=8uhfd4rrlmune7mveoedc7ckfm&contextId=1&loggedInIndicatorRegex=%5cQSign+Off%5cE

For sample i have attached one image as well which  will explain the 3 major problems i am currently having

![OWASP Issues](https://user-images.githubusercontent.com/52656580/69697032-7f83aa80-1107-11ea-9b8f-a714082cde38.png)

**Comment by thc202** [comment]
Answered in the user group, we should keep the thread there.
