### ISSUE TITLE
Jenkins ZAP spider issue

### ISSUE THREAD

**Issue by stevansuraj** [zaproxy/zaproxy#5706]
**Describe the bug**
I am automating SPA application dynamic scanning and backend API are using different domain. spider is not submitting the forms, though I have added API url in the context spider is not recognizing or scanning the application.

**Comment by kingthorin** [comment]
Please don't ask questions as issues - the ZAP User Group https://groups.google.com/group/zaproxy-users is a much more apt place for such discussions. Or, in this case even the zaprpxy-jenkins group: https://groups.google.com/forum/#%21forum/zaproxy-jenkins

**Comment by god0fcode** [comment]
Thank you. I found similar issue on Google group but solution is not provided.
