### ISSUE TITLE
Unable to proxy https in Safari and Chrome on Mac OS Catalina (browsers launched outside ZAP)

### ISSUE THREAD

**Issue by alex1704** [zaproxy/zaproxy#5710]
Hi,
I generated Root CA Certificate in Dynamic SSL Certificates tab and then added it to trusted certificates on keychains. However when i try to load https on safari or chrome i see error that my connection is not private. I suspect that it might be related to tightening requirements for trusted certificates for MacOS  Catalina - https://support.apple.com/en-us/HT210176.
Firefox is working fine, probably because certificate is added to browser manually instead of relying on one that resides in keychain.
<img width="713" alt="Screenshot 2019-11-27 at 03 28 04" src="https://user-images.githubusercontent.com/1874436/69686615-f8afdd00-10c8-11ea-978d-05afabff71f4.png">

<img width="672" alt="Screenshot 2019-11-27 at 03 29 51" src="https://user-images.githubusercontent.com/1874436/69686599-ecc41b00-10c8-11ea-9947-0ac66ce84629.png">

**Comment by kingthorin** [comment]
Please try the weekly release, it includes some changes that may address this.

https://github.com/zaproxy/zaproxy/wiki/Downloads#zap-weekly

**Comment by RemakingEden** [comment]
I have just tried on the most recent weekly release and I am still getting issues with iOS 13. It seems the certificate is not being trusted fully. Should I start a new bug report or is this one valid as it appears to relate to the same thing?

**Comment by thc202** [comment]
Did you regenerate the Root CA cert?

This issue is fine.

**Comment by RemakingEden** [comment]
@thc202 Thanks for the reply. 

I have tried a few times now, regenerating, removing and re-adding. It does not appear change anything.

**Comment by kingthorin** [comment]
If you’re regenerating the cert the validity dates (timestamps) should be changing.

**Comment by thc202** [comment]
Might be because of:
> TLS server certificates must contain an ExtendedKeyUsage (EKU) extension containing the id-kp-serverAuth OID.

we are not doing that (I think that's the only requirement missing).

**Comment by kingthorin** [comment]
Isn't that this:
https://github.com/zaproxy/zaproxy/blob/ea704dc2fe8e80883cfc0ff9fa67817c11947cc4/zap/src/main/java/org/zaproxy/zap/extension/dynssl/SslCertificateUtils.java#L162-L168

**Comment by kingthorin** [comment]
Oh it's on the root but not on the site certs:
![image](https://user-images.githubusercontent.com/7570458/69756068-a3ef7f00-1127-11ea-894b-88c2e2ad7f27.png)

**Comment by kingthorin** [comment]
@alex1704, @RemakingEden please try the weekly next week, it should have the necessary fix.

**Comment by RemakingEden** [comment]
> @alex1704, @RemakingEden please try the weekly next week, it will have the latest changes that should address this.

Thanks for this, been a little busy over the weekend. giving the new one a go now.

**Comment by alex1704** [comment]
Working for me)
