### ISSUE TITLE
Add spring security csrf token name to the configuration

### ISSUE THREAD

**Issue by MichaelVetter** [zaproxy/zaproxy#5722]
The Anti CSRF Tokens Scanner does not detect the csrf token from spring security and reports an alert. The form parameter looks like this in the request:
...&_csrf=db8d189b
See https://docs.spring.io/spring-security/site/docs/5.2.1.RELEASE/reference/htmlsingle/#servlet-csrf-include

When I add the token in the ui, the file config.xml contains this:
```
....
            <token>
                <name>_csrf</name>
                <enabled>true</enabled>
            </token>
        </tokens>
    </anticsrf>
```
Please add the token "_csrf" to the default configuration for the daemon mode.

**Comment by kingthorin** [comment]
https://github.com/zaproxy/zaproxy/blob/90f19b34aca1cf21ca11584cca65b9c7885b79d9/zap/src/main/java/org/zaproxy/zap/extension/anticsrf/AntiCsrfParam.java#L54

**Comment by MichaelVetter** [comment]
Great, thank you. I only tested it with the last (windows) release 2.8.0.

**Comment by thc202** [comment]
That was added in 2.8.0 (#4946), did you use other version prior 2.8.0?

**Comment by MichaelVetter** [comment]
Yes, I used an older version before. Maybe the old configuration was not updated. I will test that again.

**Comment by thc202** [comment]
Old configurations were not being updated so they would miss the new default tokens, #5723 fixes that.
