### ISSUE TITLE
502 Bad Gateway Errors

### ISSUE THREAD

**Issue by ossie-git** [zaproxy/zaproxy#5726]
**Describe the bug**
I'm seeing a lot of HTTP/1.1 502 Bad Gateway errors when visiting web sites.  I'm currently using the pre-configured browser (click on Manual Explore) and visiting https://pentesterlab.com.  All the files on the domain assets.pentesterlab.com (such as https://assets.pentesterlab.com/public/css/bootstrap.css) result in 502 Bad Gateway errors.  I tried to follow the advice over at https://github.com/zaproxy/zaproxy/wiki/FAQsslHandshake but nothing worked.  I don't have an upstream proxy configured in ZAP or on my system

**To Reproduce**
1. Go to 'Manual Explore'
2. Set the URL to https://pentesterlab.com
3. You'll notice that the page does not render properly and the History tab shows 502 Gateway errors

**Expected behavior**
The requests should be proxied correctly.  I tried various things including enabling and disabling SSLv2Hello

**Screenshots**

![screen](https://user-images.githubusercontent.com/25382296/70024849-6be8b000-15ef-11ea-8698-183fb8222931.png)

**Software versions**
 - ZAP: D-2019-12-02
 - OS: Mac OS X
 - Java: java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
 - Browser: Firefox 70.0.1 (64-bit)

**Errors from the zap.log file**
See https://github.com/zaproxy/zaproxy/wiki/FAQconfig for the location of the zap.log file for your OS.

All I see are entries such as this:

`
297556 [ZAP-ProxyThread-224] WARN org.parosproxy.paros.core.proxy.ProxyThread  - An exception occurred while attempting to connect to: https://assets.pentesterlab.com/public/js/spectragram.min.js
The exception was:
Received fatal alert: handshake_failure
Root cause:
SSLHandshakeException: Received fatal alert: handshake_failure
The following document may be of assistance in resolving this failure:
https://github.com/zaproxy/zaproxy/wiki/FAQsslHandshake
`

**Additional context**

**Comment by thc202** [comment]
Could you try with a newer Java version (can be 8, but newer update). Not seeing those errors with 1.8.0_222.

**Comment by ossie-git** [comment]
You were right.  When I updated my Java version to 1.8.0_231, it worked.  Thanks.
