### ISSUE TITLE
HTML Reports should offer a table based on kind of alert

### ISSUE THREAD

**Issue by jsoref** [zaproxy/zaproxy#5732]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
In addition to:
### Summary of Alerts
Provide:
### Kinds of Alerts

Kind | Number of Alerts
-- | --
X-Frame-Options Header Not Set | 1
Incomplete or No Cache-control and Pragma HTTP Header Set | 8
... | ...

The link for a given kind could be to the first instance of that alert, although I'm not absolutely certain that's necessary. It would certainly be useful if the alerts were sorted by kind (currently, I'm not sure what their sort order is).

**Describe alternatives you've considered**

**Additional context**
Currently, the report has:

### Summary of Alerts

Risk Level | Number of Alerts
-- | --
High | a
Medium | b
Low | c
Informational | d

### Alert Detail
...

**Comment by thc202** [comment]
>  (currently, I'm not sure what their sort order is).

They are sorted by risk.

**Comment by jsoref** [comment]
Presumably a given item will only appear in a single category, is there any reason to not major sort by risk and minor sort by kind?

**Comment by akshathkothari** [comment]
Hello, can I work on this?

**Comment by kingthorin** [comment]
Absolutely!

**Comment by thc202** [comment]
https://github.com/zaproxy/zaproxy/issues/5732#issuecomment-561908971 I'm not aware of any, we should do that.

@akshathkothari do you know where to start? Any questions?

**Comment by kingthorin** [comment]
An alert can appear as various risks under two circumstances:
1. A user manually changes the risk on some but not all alerts.
1. Some alerts vary confidence (maybe also risk) based on analysis of details, ex: getting a 403 for a hidden file vs a 200 or successful content check.

**Comment by jsoref** [comment]
Personally, even in those cases, I'd rather a report stored by severity. If I'm specifically curious about all reports from a specific alert, I'm sure I can filter by it. Or, I could switch to the other sort of I really preferred it.

**Comment by akshathkothari** [comment]
[#5732 (comment)](https://github.com/zaproxy/zaproxy/issues/5732#issuecomment-575995158) Yes, I believe I have to modify the [xsl file for HTML reports](https://github.com/zaproxy/zaproxy/blob/afb991c16461cb07254b6addcebbe810c09c3a52/zap/src/main/resources/org/zaproxy/zap/resources/xml/report.html.xsl). I have two questions:
1. What does sorting by kind mean? Currently the alerts are major sorted by risk and minor sorted by confidence.
2. Should I also update the [xsl file for markdown reports](https://github.com/zaproxy/zaproxy/blob/afb991c16461cb07254b6addcebbe810c09c3a52/zap/src/main/resources/org/zaproxy/zap/resources/xml/report.md.xsl)?

**Comment by thc202** [comment]
1. That's referring to the name of the alert.
2. It would be better for consistency.
