### ISSUE TITLE
New Script blank field is inconsistent in dropdowns

### ISSUE THREAD

**Issue by jsoref** [zaproxy/zaproxy#5750]
**Describe the bug**
For Type and Script Engine, a blank value appears first in the drop down, for Template, it appears last.

**To Reproduce**
1. Select the Scripts panel
2. Expand Scripts>Templates>HTTP Sender
3. Right click on AddZapHeader.js
4. Select New Script...
5. Click on the Template drop down
6. Click on the Script Engine drop down
7. Click on the Type drop down

**Expected behavior**
There should be a consistent order placement for <blank>

**Screenshots**
![Template](https://user-images.githubusercontent.com/2119212/70204189-9e78d280-16ed-11ea-8b26-11f97dff34be.png)
![Script Engine](https://user-images.githubusercontent.com/2119212/70204211-af294880-16ed-11ea-8712-bccb637d5147.png)
![Type](https://user-images.githubusercontent.com/2119212/70204228-bcdece00-16ed-11ea-9ca6-cd733546e78d.png)

**Software versions**
 - ZAP: 2.8.0
 - Add-on: 
 - OS: 10
 - Java: 
 - Browser: 

**Errors from the zap.log file**

**Additional context**
I'm not actually sure that the blank fields should necessarily be present, but if they should be, there should be a consistent placement...

**Comment by thc202** [comment]
Done in zaproxy/zap-extensions#2235.

**Comment by thc202** [comment]
> I'm not actually sure that the blank fields should necessarily be present,

The script engine and template are not required, while script type is the empty entry allows to show all templates at the same time.
