### ISSUE TITLE
Need some help during my developing on outgoing stream via socks5 proxy.

### ISSUE THREAD

**Issue by usualwyy** [zaproxy/zaproxy#5755]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Add socks5 support on outgoing connections.

**Describe alternatives you've considered**
This would help when using tor or other socks4/5 proxies.

**Additional context**
I'm trying to do some work on socks4/5 outgoing proxy.Can somebody kindly point out the related codes position?
I saw something in org/parosproxy/paros/extension/option and org/zaproxy/zap/view/OptionsConnectionPanel, but I thought both of them are about UI or config stuffs. 
I want to know where is the outgoing proxy actually been used.
Thanks.

**Comment by kingthorin** [comment]
Are you trying to complete this issue? https://github.com/zaproxy/zaproxy/issues/29

If so this duplicate should be closed.

If you wish to have a development discussion I'd suggest either moving this to the [Developer Group](https://groups.google.com/forum/#!forum/zaproxy-develop), or joining #zaproxy on freenode (IRC) [ [you can use this webclient](https://webchat.freenode.net/) ]. I believe the code you're after is in `HttpSender`, there's a `createHttpClientViaProxy()` method that checks `isUseProxyChain` etc...

**Comment by thc202** [comment]
ZAP relies on the JRE for SOCKS handling.

Closing per previous comment, discussion/questions should happen elsewhere.
