### ISSUE TITLE
Sign On issue with ZAP proxy 

### ISSUE THREAD

**Issue by shubhamkumbhalkar** [zaproxy/zaproxy#5757]
Trying to log in to the website using Browser from zap, it is giving weird error as not authorized even though the creds are correct(Checked 5-6 times). 

Added the CA certificate and Self signed certificate for the website I am trying, but no success
<img width="240" alt="Screen Shot 2019-12-10 at 4 16 18 PM" src="https://user-images.githubusercontent.com/34781200/70580391-67c90f00-1b68-11ea-9d85-38cbf36b0318.png">

<img width="307" alt="Screen Shot 2019-12-10 at 4 16 55 PM" src="https://user-images.githubusercontent.com/34781200/70580408-7ca5a280-1b68-11ea-81b8-dad3208b6316.png">

I would really appreciate if this community could help

**Comment by kingthorin** [comment]
You probably need to use the [weekly](https://github.com/zaproxy/zaproxy/wiki/Downloads#zap-weekly) build due to recent OSX/Safari changes. You may also need to follow the tip in this comment: https://github.com/zaproxy/zaproxy/pull/5714#issuecomment-560487476

**Comment by shubhamkumbhalkar** [comment]
@kingthorin  I am still getting the problem of log in! It is not allowing me to log in!

**Comment by kingthorin** [comment]
Okay so you're no longer getting a certificate error?

**Comment by shubhamkumbhalkar** [comment]
No, I added the certificate but it still says the connection is not secure

**Comment by shubhamkumbhalkar** [comment]
file:///var/folders/nv/7wlw29ts0rd1sw5kr41rzf9w0000gp/T/TemporaryItems/(A%20Document%20Being%20Saved%20By%20screencaptureui%202)/Screen%20Shot%202019-12-11%20at%2011.22.47%20AM.png

**Comment by kingthorin** [comment]
Is it Safari and how are you launching it?
Did you regenerate the CA cert after starting to use the weekly?

**Comment by shubhamkumbhalkar** [comment]
I am launching from here: 
![image](https://user-images.githubusercontent.com/34781200/70655004-4f123500-1c0c-11ea-8917-b6af1d9bc873.png)
Yes, I generated the CA certificate after the weekly build install! 
![image](https://user-images.githubusercontent.com/34781200/70655131-8a146880-1c0c-11ea-8575-81299c488c7b.png)
Also my HUD settings look something like this: 
![image](https://user-images.githubusercontent.com/34781200/70655168-a0222900-1c0c-11ea-8839-0b21a7d3c53e.png)

**Comment by kingthorin** [comment]
Can you disable the HUD (little radar icon) in the main toolbar, then launch a browser from within ZAP, and let us know if that resolves your issue?

**Comment by shubhamkumbhalkar** [comment]
I am afraid, that it did not resolve my issue!

**Comment by kingthorin** [comment]
Try navigating something that isn't HTTPS to start with, ex: http://scanme.nmap.org/

**Comment by shubhamkumbhalkar** [comment]
I tried, it says something like this:
![image](https://user-images.githubusercontent.com/34781200/70656691-6a327400-1c0f-11ea-93f2-6454a8e8cb0f.png)

**Comment by kingthorin** [comment]
Then one of a few things seems true, that I can't sort out because I'm not sitting at the computer.

- You didn't disable HUD.
- You didn't access the plain HTTP resource.
- You haven't launched the weekly.
- You haven't properly installed and trusted the cert (generated by the weekly).

**Comment by shubhamkumbhalkar** [comment]
I have double checked all the things you asked me to.

1. You didn't disable HUD. => 
2. You didn't access the plain HTTP resource.
![image](https://user-images.githubusercontent.com/34781200/70657715-348e8a80-1c11-11ea-8d1b-d6de24ed92ed.png)

3. You haven't launched the weekly. => 
![image](https://user-images.githubusercontent.com/34781200/70657746-41ab7980-1c11-11ea-99e0-05f874dcbf28.png)

4. You haven't properly installed and trusted the cert (generated by the weekly).
<img width="537" alt="Screen Shot 2019-12-11 at 12 26 46 PM" src="https://user-images.githubusercontent.com/34781200/70657845-8505e800-1c11-11ea-910b-85cfc4db5c63.png">owasp_zap_root_ca.cer

**Comment by kingthorin** [comment]
Hey @shubhamkumbhalkar sorry I know how these things can be frustrating, I’m just out of ideas without being able to sit and fiddle. There are definitely others using it in OSX so there’s gotta be a solution for you, it just isn’t coming to me.

I almost feel silly suggesting it but you could fire up a Kali VM (though it’s admittedly an overkill solution, it would perhaps get you moving toward your end goal while you continue to troubleshoot this).
