### ISSUE TITLE
Swagger file for ZAP API

### ISSUE THREAD

**Issue by nlykkei** [zaproxy/zaproxy#5758]
I'm looking for a Swagger file or equivalent for generating classes, like it's being done in the `zap-api-dotnet` project:

https://github.com/zaproxy/zap-api-dotnet/tree/master/src/OWASPZAPDotNetAPI/OWASPZAPDotNetAPI/Generated

Is such file available - and if so, how to obtain it?

**Comment by psiinon** [comment]
Please dont ask questions as issues - the User Group is the best place for those: https://groups.google.com/group/zaproxy-users

**Comment by thc202** [comment]
This is duplicate of #2033.
