### ISSUE TITLE
Switch to use freenode

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#5759]
- [x] Update https://github.com/zaproxy/zaproxy/blob/develop/README.md#for-help-using-zap
- [x] Update https://github.com/zaproxy/zap-api-java/blob/develop/README.md#getting-help
- [x] Update https://github.com/zaproxy/zap-api-nodejs/blob/master/README.md#getting-help
- [x] Update https://github.com/zaproxy/zap-api-python/blob/master/README.md#getting-help
- [x] Update https://github.com/zaproxy/zap-api-rust/blob/master/README.md#getting-help
- [x] Update https://github.com/zaproxy/zaproxy/wiki/FAQquestions#irc
- [x] Update https://github.com/zaproxy/zaproxy/wiki/FAQhelp#ask-on-irc
- [x] Update Tips and Tricks add-on:
  - https://github.com/zaproxy/zap-extensions/blob/cd48e744c19ca9901c52ff8d10c458f0cd44658e/addOns/tips/src/main/javahelp/org/zaproxy/zap/extension/tips/resources/help/contents/tips.html#L101
  - https://github.com/zaproxy/zap-extensions/blob/cd48e744c19ca9901c52ff8d10c458f0cd44658e/addOns/tips/src/main/resources/org/zaproxy/zap/extension/tips/resources/Messages.properties#L32
- [x] Update zapbot tweets https://github.com/zapbot/zap-mgmt-scripts/blob/3afb3d446a9c1aefcb72c1f577f5756a59591554/tiptweets/tweets.txt#L10
- [x] Inform Google Groups
- [x] Update #websectools channel title
----
- [x] Update https://github.com/zaproxy/zaproxy.github.io/blob/master/irc/index.html
- [x] Add to zaproxy-website (common redirect, see PR 18).
- [x] Announce via Twitter
- [x] Announce via Slack

**Comment by thc202** [comment]
Closing, all tasks done.
