### ISSUE TITLE
wappalyzer addon: Add API

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#5761]
We've had a request to allow exporting of Wappalyzer info via the API. 

Initial endpoints should probably be:

view:
- siteList (per the GUI dropdown list)
- techListBySite (allow the user to specify a single siteList entry [hostname:port] and get the details just for that one)
- techList (for all sites)

**Comment by sonawanesarvesh** [comment]
Hi
I see little scope of corrections

The URLs which is set in context are - 
1) http://www.example.com
2) https://www.example2.com
3) www.example3.com
4) testingexmple.com

But the wappalyzer API displays results with custom URLs naming system
1) It removes https or http from context URL
2) it adds port numbers  443, 80 to the URL
3) Sequence of input is also gets changed in listall api call (specially when HTTP URL is provided in context but OWASP detects its HTTPS version as well - so Wappalyzer displays results for both HTTP and HTTPS verson so it alters the sequence)

So in programming, it becomes difficult to match the input context URL vs wappalyzer output results

So i request can you please use the same URL (which is set in context ) for wappalyzer output as well
