### ISSUE TITLE
Command line option 'newsession' not creates file when relative path is given

### ISSUE THREAD

**Issue by alex1704** [zaproxy/zaproxy#5767]
**Describe the bug**
When i run command `./zap.sh -daemon -port 8000 -newsession ../path/to/some.session` i see output in console `8394 [ZAP-daemon] INFO org.parosproxy.paros.control.Control  - New session file created` but no file is actually created.

**Software versions**
ZAP: D-2019-12-09

**Comment by thc202** [comment]
Relative paths are resolved from the session dir [1], did you check from there?

[1] https://github.com/zaproxy/zap-core-help/wiki/HelpCmdline

**Comment by alex1704** [comment]
Yes, it is created there, sorry for false alarm.

**Comment by kingthorin** [comment]
Thanks for letting us know
