### ISSUE TITLE
Relative paths don't work as expected

### ISSUE THREAD

**Issue by pigucatalin** [zaproxy/zaproxy#5771]
**Describe the bug**
zap.sh -daemon -configfile ZAP.properties -newsession ./sesions/ZAP-SESH
Will not load the desired properties and creates the session on ~/.ZAP/sesions folder

**To Reproduce**
1. Make sure you have a properties file with this keys/values
host=localhost
port=8281
2. Run the above command
3. Monitor the port used by ZAP
4. search for the desired session files

**Expected behavior**
Relative paths should work and properties should be loaded and session created where I configure it

**Screenshots**

**Software versions**
 - ZAP: 2.8.1
 - OS: Ubuntu 16.0.4
 - Java: Oracle Java 1.8.0_191

**Errors from the zap.log file**
See https://github.com/zaproxy/zaproxy/wiki/FAQconfig for the location of the zap.log file for your OS.

**Additional context**

**Comment by thc202** [comment]
Relative paths for the session are resolved from the session directory. [1]

The "host" and "port" are not configuration keys. [2] You need to use `proxy.port` and `proxy.ip`, respectively.

[1] https://github.com/zaproxy/zap-core-help/wiki/HelpCmdline
[2] https://github.com/zaproxy/zaproxy/wiki/FAQconfigValues
