### ISSUE TITLE
zap2docker-weekly zap-api-scan.py finding more URL's than previous day, taking way longer to complete

### ISSUE THREAD

**Issue by johnjbateman** [zaproxy/zaproxy#5773]
We are running this command on Ubuntu 16.04 in Azure DevOps as part of a scan after we deploy to an environment:

```bash
docker run -t owasp/zap2docker-weekly:latest zap-api-scan.py -t https://myapi.com/docs/v1/open-api.json -f openapi -w api.md -i -z "-config replacer.full_list\(0\).description=auth1 -config replacer.full_list\(0\).enabled=true -config replacer.full_list\(0\).matchtype=REQ_HEADER -config replacer.full_list\(0\).matchstr=User-Agent -config replacer.full_list\(0\).regex=false -config replacer.full_list\(0\).replacement=OWASP-ZAP-SCANNER-NO-THREAT"
```

The last time I ran this on 12/17/2019, 1:38:15 PM EST, it ran for about a minute: https://gist.github.com/johnjbateman/546508aa661bed22e978c2ae6299ecb8 

However, starting with a scan on 12/17/2019, 5:19:53 PM EST, it ran for around an hour: https://gist.github.com/johnjbateman/ff2051495694d05de22df33a370ee939

Check out this from 1:38PM log above:

```
2019-12-17T18:40:32.6060110Z 2019-12-17 18:40:32,605 Number of Imported URLs: 4
2019-12-17T18:41:07.8804411Z Total of 15 URLs
```

And from 5:19PM log above:

```
2019-12-17T22:22:19.2483010Z 2019-12-17 22:22:19,247 Number of Imported URLs: 28
2019-12-17T23:31:16.0444797Z Total of 784 URLs
```
_Do you see that it took 1h 11m to write that 784 URLs found line?_

I can run this command locally on Docker Desktop for Windows ver 2.1.0.4 and I get it to complete quickly and it finds 4 imported urls.

Any ideas on why this started yesterday and from everything I can see, our api is the same version, (also proven by running docker on my machine).

**Comment by psiinon** [comment]
Please don't ask questions as issues - the User Group is a much better forum for these sorts of discussions.
https://groups.google.com/group/zaproxy-users

**Comment by johnjbateman** [comment]
@psiinon I truly believe this is an issue.  I also asked if anyone experienced this on the user group.  Can you help?

**Comment by psiinon** [comment]
Right now this is a question not an issue or an enhancement, so this is not the right place to ask it.
If it turns out to be an issue then we can open one.
