### ISSUE TITLE
Neonmarker v1.1.0

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#5781]
**Add-on repo**
https://github.com/kingthorin/neonmarker

**Your contact details**
kingthorin at gmail dot com

**Are you one of the authors**
Yes

**Licence**
APL 2 (https://github.com/kingthorin/neonmarker/blob/master/LICENSE)

**Build instructions**
Gradle build similar to FuzzDB Web Backdoors.
Build to be released is here: https://github.com/kingthorin/neonmarker/releases/tag/neonmarker-v1.1.0

**Link to more information**

**Twitter handle for tool or author(s)**
@_guttula @kingthorin_rm

**Promote to Beta or Release?**
Not at this time.

**Comment by thc202** [comment]
Closing, the add-on is now available in the marketplace: https://twitter.com/zaproxy/status/1213038469355888641
Thank you! :)
