### ISSUE TITLE
Please add command line support to start attack on given URL for windows.Or Is there any Please let me know how to use it

### ISSUE THREAD

**Issue by rahuldhoundiyal0790** [zaproxy/zaproxy#5784]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by psiinon** [comment]
Please dont ask questions as issues - the User Group is a much better forum for that: https://groups.google.com/group/zaproxy-users

FYI yes there is command line support on Windows, ask on the User Group for more details
