### ISSUE TITLE
ZAP adding unnecessary headers and redirecting to HTTPS for some reason

### ISSUE THREAD

**Issue by abhaybhargav** [zaproxy/zaproxy#5790]
I have been trying to proxy a localhost app with ZAP (Docker app) and I am running into the following issue:
1. The SSL cert shows up as invalid, even though I have specifically generated a new cert (in ZAP) and added that to my OS (Mac OS Catalina) Trusted Cert list
2. if i go with `--verify False` type of flag, where I dont want to force SSL, ZAP proxies but weirdly tries to redirect to HTTPS and adds a bunch of security headers like CSP, etc. 

Here's a sample of that: 

```
http POST http://localhost:5050/login username=admin password=admin123 --proxy http:http://127.0.0.1:8080 --cert ~/Downloads/zap.cer
HTTP/1.1 302 OK
Access-Control-Allow-Headers: ZAP-Header
Access-Control-Allow-Methods: GET,POST,OPTIONS
Cache-Control: no-cache
Content-Length: 69
Content-Security-Policy: default-src 'none'; script-src 'self'; connect-src https://zap wss://zap; frame-src 'self'; img-src 'self' data:; font-src 'self' data:; style-src 'self' 'unsafe-inline' ;
Content-Type: text/html; charset=UTF-8
Location: https://localhost:5050/login
Pragma: no-cache
X-Clacks-Overhead: GNU Terry Pratchett
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block

<html><body>Redirecting to https://localhost:5050/login</body></html>
```

**Notice the Redirect here**

I tried the same thing with cURL

```
curl -x http://127.0.0.1:8080 --header "Content-Type: application/json" --request POST --data '{"username": "admin", "password": "admin123"}' --insecure http://localhost:5050/login
<html><body>Redirecting to https://localhost:5050/login</body></html>
```

This was working perfectly fine until I upgraded to Catalina. Not sure what happened in the upgrade process

ZAP proxies everything correctly with Mozilla, when I load the cert and explicitly set the proxy manually

Based on a previous solution I have tried: 
* Using the weekly release candidate
* re-generating the certificate, etc. 

Its not working for some reason.

**Comment by abhaybhargav** [comment]
Update - I also tried this by deleting the ZAP directory in `~/Library/Application Support/` and reloading a new version of ZAP. Same result.

**Comment by kingthorin** [comment]
Looks like you have a bunch of scripts enabled, hence the clacks header, etc. Also you probably gave HUD enabled hence the client side SSL force.

**Comment by abhaybhargav** [comment]
@kingthorin Its working now. HUD seemed to be the issue. HUD was enabled and was redirecting to SSL. I am so used to using ZAP in daemon, I didnt realize that this was the problem. 

For anyone else who has this issue. Please note the UI options to disable HUD

![image](https://user-images.githubusercontent.com/4427607/71895458-23d12600-3177-11ea-8667-2fc8d6834631.png)
