### ISSUE TITLE
Big messages cause GUI to freeze

### ISSUE THREAD

**Issue by emptyArrayLLC** [zaproxy/zaproxy#5791]
**Describe the bug**
After doing scans and collecting info on site, it detected 'Application Error Disclosure' (6).  Upon expanding and clicking on a link (javascript file, can't tell how large), it's instantly freezes and nothing else can be done (it may recover after a few minutes wait).  In other parts of app, I've seen the "Very large response body (xxx bytes) - switch views..." warning, but not in this situation.  I have to do a 'killall java' to exit the app and restart.  

On occasion, it will recover after a few minutes, but the app moves slow so I just restart it. When it does recover, the response is unintelligible (see screenshot) and navigating around is slow. 

**To Reproduce**
1. Have JS file (size?) in Alert, Application Error Disclosure 
2. Click on link.
3. App freezes instantly or moves slow.

**Expected behavior**
To see the Request and Response data of the alert.

**Screenshots**
##Click on the 'GET:https://xx/build/js/app.js?v=...
![AED-js](https://user-images.githubusercontent.com/57641147/72003916-3db64b80-31ff-11ea-904c-4da4c5f01c55.jpg)
##Screen freezes, switching desktop and back shows gray app
![goesGray](https://user-images.githubusercontent.com/57641147/72003925-4149d280-31ff-11ea-8989-6269bf75827c.PNG)
##If it does recover, Response window looks like
![if-it-does-recover](https://user-images.githubusercontent.com/57641147/72004073-7f46f680-31ff-11ea-9f6e-623b349c56ab.PNG)

**Software versions**
 - ZAP: 2.8.1
 - OS: BlackArch 5.4.6 x86_64
 - Java: openjdk 13.0.1
 - Hardware:  Happens on both VirtualBox and HD install on laptop.

**Errors from the zap.log file**
Will update, don't have currently.

**Additional context**

**Comment by kingthorin** [comment]
Thanks for the report. Could you try the following?

Select a js response that doesn't cause the issue. Right click in the response body area, goto syntax and disabled 'Syntax highlighting' and 'Wordwrap', then go back to the item that's causing the problem. 

Does that alleviate the issue?

**Comment by emptyArrayLLC** [comment]
I don't see the ability to disable Syntax Highlighting through the Syntax menu.  Only see Auto Detect, Plain, CSS, HTML, JavaScript, JSON, XML.  I changed it from Autodetect/JavaScript to Plain, but it only applies to that one JS response.  Is there another way to disable application wide?

**Comment by kingthorin** [comment]
Sorry yes, I wasn't specific enough. Once you disable Auto Detect and Wordwrap it should apply until you change it again.

![view_contexts](https://user-images.githubusercontent.com/7570458/72006916-9ea14c00-321e-11ea-9668-d220365ff07a.gif)

**Comment by emptyArrayLLC** [comment]
Issue still occurs.  No other JS files are causing the issue and I do see warnings on those about large file sizes.  Found some in History, and in other Alerts != Application Error Disclosure.

**Comment by kingthorin** [comment]
Can you navigate to one of the URLs in the browser and send us the content? (Assuming it's sufficiently generic/non-sensitive.)

**Comment by emptyArrayLLC** [comment]
Unfortuntately it does lots of information in it and I can't send.  I can tell you it's a 2MB webpack looking file :)

**Comment by kingthorin** [comment]
I'm 90% sure it's the issue I'm thinking, unfortunately I have no way of knowing that you're getting things turned off as expected or recreating it locally.....

**Comment by emptyArrayLLC** [comment]
After further review, you are correct.  After changing to plain, I can now load them in the Response.

**Comment by emptyArrayLLC** [comment]
Still moves a little slow, but it does not freeze the app.

**Comment by kingthorin** [comment]
Great, thanks for letting us know!

Is it one (or a number of) giant long lines?

**Comment by emptyArrayLLC** [comment]
One loooong line

**Comment by kingthorin** [comment]
Okay so it's probably actually Wordwrap that's the issue not syntax highlighting.

**Comment by emptyArrayLLC** [comment]
It appears it may be both?  I've disabled each one individually and the issue appears if Wordwrap or Syntax is enabled, but the other isn't.

**Comment by thc202** [comment]
This is not specific to JS files, it can be reproduced with other types that are highlighted or have long line(s).

**Comment by globeone** [comment]
Would you like me to repost the Log file from #5862 to this bug?

**Comment by thc202** [comment]
It's not necessary, the causes are known. Thanks.

**Comment by thc202** [comment]
Related #6241.

**Comment by jeandominoserver** [comment]
i used to see this on ZAP 2.9.0
tonight i updated to 2.10.0 and unfortunately it is still happening.

What would you need from me to investigate, if you are willing to of course  ?
Thanks, JD.

![image](https://user-images.githubusercontent.com/59081994/104969007-52671b00-59df-11eb-9999-753981082707.png)

**Comment by kingthorin** [comment]
The causes and work around are known and discussed earlier in the ticket 🙂

Thanks for the offer though.

**Comment by jeandominoserver** [comment]
that is a problem though as as soon as i highlight any of the alerts small or big the Ui freezes for minutes at a time though :-(

**Comment by kingthorin** [comment]
Change the settings on a small message. It’s set for the frame/field not the message.

**Comment by jeandominoserver** [comment]
i keep trying at this instant; as soon as i click any of the alerts the GUi becomes unresponsive and i get no way of disabling/enabling the setings as you are showing in your GIF above.
I have just killed and restarted ZAP and as soon as i successfully load my session; select an alert ago to the frame ... it is unresponsive.
Is there a way to set those through a config pre-launching ZAP or through a CLI of sorts ?

**Comment by kingthorin** [comment]
Start a new session, proxy like example.com or something. Select a message from History and set the option(s). Re-open one of your saved sessions.

Yes you could edit the config or set it via the CLI but I’m on mobile and don’t have the details handy.

**Comment by jeandominoserver** [comment]
Well thank you very much for being that responsive over your mobile. I highly appreciate !
i have bene able to do like you suggested, opened one of my saved sessions within the same Ui that i successfully disabled auto-highlight and enabled plain.
unfortunately the Ui is still locking up , just not as fast though to be fair.

**Comment by jeandominoserver** [comment]
i am in the GMT TZ here so i will be away from the keyboard in not so long.
Just respond when you can, i apprecaite your responsive help, thank You.

**Comment by kingthorin** [comment]
Do word wrap too?

**Comment by jeandominoserver** [comment]
yes it is done too..
I have a 1'42'' video grab if you want that shows the settings, working okay with the mozilla.com:
1- meaning i can browse the alerts pane and get them to display responsively in the dedicated frame.  
2- then i load my previously saved session and within seconds the Ui locks up

obviously since i can not scrub private data i am willing to share it with you but only privately.

**Comment by jeandominoserver** [comment]
any feedback ?

**Comment by kingthorin** [comment]
How big is your saved session? (Disk/file size? # of alerts? # of messages in the history table?)

What JVM are you using?
What OS are you using?

**Comment by thc202** [comment]
It would be great if you could provide details about the problem, e.g. thread dumps when ZAP is hanging.

**Comment by jeandominoserver** [comment]
@kingthorin :
Ubuntu Focal 20.04.1 LTS (up to date before i upgraded/ran ZAProxy 2.10.0

from the ubuntu terminal when launching zap.sh
Found Java version 11.0.9.1
Availbale memory: 15985 MB
Using JVM args: -Xmx3996m
![image](https://user-images.githubusercontent.com/59081994/105183051-a7ad4480-5b25-11eb-91c7-7d13ad9a3d6f.png)

@thc202 :

Happy to provide a thread dump, would the preference be either 'jstack -l" or just a plain "kill -3" ?

the Problem is exactly as the one described here. once i get to an alert in the bottom left frame and it displays the details in the upper right frame; the whole GUi freezes anywhere between few minutes to a couple of hours.
i left it untouched for over 1Hr 2 days ago and it was still unresponsive; yet 12Hrs later, it was somehow responsive.
I only used this opportunity to delete every single alerts one-by-one in the bottom left frame so that i could start my own scans.
Once all the alerts were deleted successfully i had no more problems.
Note that i enabled the workaround as described here : https://github.com/zaproxy/zaproxy/issues/5791?_pjax=%23js-repo-pjax-container#issuecomment-572207801
and still had the problem afterwards.

and it made no differences.
For me the issue started with the 2.9.0 version and just got more tangible again with 2.10.0

**Comment by thc202** [comment]
The kill one would be enough.

In that case I'd suggest disable the extension "HTTP Panel Syntax Highlighter View Extension", you'll lose syntax highlighting but at least it should not hang.

**Comment by jeandominoserver** [comment]
@thc202 
1- i will let my current scan complete before attempting to provide the Threads Dump
2- are you referring to the workaround shown here : https://github.com/zaproxy/zaproxy/issues/5791#issuecomment-572207801 
As if that is so, i have done those 3-steps (disable word-wrap/ deactivate syntax auto-highlight and manually selected 'plain'
see attached composite picture

**Comment by kingthorin** [comment]
No he means go into the Options, Extensions, find "HTTP Panel Syntax Highlighter View Extensions" and set it as disabled, restart ZAP. Re-open the session that manifested the issue.

**Comment by jeandominoserver** [comment]
Thank you for your prompt reply @kingthorin

**Comment by PenelopeFudd** [comment]
The CPU problem is one thing, but after it's done it looks like this:
![zap-hang](https://user-images.githubusercontent.com/1606480/122142294-068c9680-ce04-11eb-80e3-17f4aa06d63f.png)
I've turned off "HTTP Panel Syntax Highlighter View Extensions", auto-detect, set it to plain, turned off word wrap and am just about to restart Zap.

Maybe give the syntax highlighter a cpu budget?

**Comment by psiinon** [comment]
Does anyone know of any publicly available massive javascript files that we could use for testing this?

**Comment by PenelopeFudd** [comment]
https://code.jquery.com/ maybe?
Take one of the minified versions, and concatenate several copies into a single file.  That should do it.

**Comment by kingthorin** [comment]
Juice Shop 12.6.1 the URI `/vendor-es2018.js ` seems to manifest the issue.

**Comment by kingthorin** [comment]
Can someone point me at the code location to be futzing with this? I thought I had it sorted out before but for some reason I can't find an appropriate location this evening. There seems to be a lot of code duplication within: `/zap/src/main/java/org/zaproxy/zap/extension/httppanel/view/syntaxhighlight`. There's probably a higher or earlier location where I should be looking but it just isn't seeming obvious for some reason.

**Comment by thc202** [comment]
The base class is `HttpPanelSyntaxHighlightTextArea`, if you want to apply the fix just to the responses it would be in `HttpResponseBodyPanelSyntaxHighlightTextArea` and `HttpResponseAllPanelSyntaxHighlightTextArea`.

**Comment by jsoref** [comment]
For reference, my JS file is <6mb.

**Comment by kingthorin** [comment]
Would you be able to provide it?

I have come up with one test case but having others would help.

**Comment by jsoref** [comment]
I've provided it to @thc202 -- the file is publicly reachable, it's just a webpack, but I'd rather not publicly link it.

**Comment by jsoref** [comment]
In general, I'd request that the view only show a windowed view of the content, +/-2k
if someone wants the rest, they should ask to save it

A 4k window should be more than enough for me to make a reasoned opinion about the content in general, and anything else, i'm not going to want to do in a small pane.

**Comment by PenelopeFudd** [comment]
That's quite true.  Maybe it could do some content-aware/size-aware choices: if it's larger than 2k (for example), turn off the syntax highlighting; if it's larger than 20k, truncate it and present options for what to do with it.  The only options I can think of is 'save to disk' or maybe 'upload to S3'.

**Comment by globeone** [comment]
Thanks for finding the other case. 
So, the proposed workarounds, turning off Word Wrap and Highlighting, actually break important functionality for analyzing a case. 

Whereas, the issue we are facing is with graceful CPU handling of the application interface. Having an application hang for several hours using 95% of the computing resources and electricity, with users unable to use or stop the process, is an experience that may push people away from using this great software.

Is there any information as to why the Highlighter and WordWrap functionalities cause this high CPU load and the GUI to become unresponsive?

**Comment by thc202** [comment]
This is a known performance issue with the text area we are using: bobbylight/RSyntaxTextArea#41.

**Comment by globeone** [comment]
Is there a way in Java to encapsulate the RSyntaxTextArea library so that the GUI continues to function? At the moment, it's not even possible to File... Close... or X the application when RSyntaxTextArea has control of the CPU.

**Comment by globeone** [comment]
Maybe something like Bridge Pattern, to separate the RSyntaxTextArea from the GUI ? 

https://en.wikipedia.org/wiki/Bridge_pattern

**Comment by globeone** [comment]
Can confirm that disabling Word Wrap as shown in the GIF above is a valid workaround. 
Maybe it's possible to have Word Wrap 'off' by default? 
Or at least off by default for JavaScript files?
As, a new user, is not easily going to find the Word Wrap toggle, and this would lead to a better user experience.

**Comment by jsoref** [comment]
In web browsers, there's generally a ten-fold memory increase between html source and dom. The things that try to do syntax highlighting aren't particularly smart (they generally try to highlight the entire file, and they probably try to calculate painting the entire file or something similarly silly) -- it tends to be especially bad if they're trying to figure out how to word-wrap the entire file. You're welcome to use a profiler and look through it.
