### ISSUE TITLE
ZAP Proxy - Gateway Timeout while running E2E tests

### ISSUE THREAD

**Issue by greeshg** [zaproxy/zaproxy#5796]
We are running ZAP in daemon mode and configured it as proxy while executing our E2E tests. We are getting error "Operation returned an invalid status code 'GatewayTimeout'". 
Can this issue be solved by increasing the Options/ConnectionTimeout value? We can see the default value for timeout is 20sec. We are using zap-weekly image. 

@psiinon It would be helpful if you can please provide some inputs on this. 

Thanks

**Comment by psiinon** [comment]
Please ask questions on the ZAP User Group: https://groups.google.com/group/zaproxy-users
