### ISSUE TITLE
how to use 'zap-full-scan.py' scan web application with password and account and traverse all pages?

### ISSUE THREAD

**Issue by chchliang** [zaproxy/zaproxy#5798]
e.g:
docker run --user root  -v /home/billy/zap/wrk/:/zap/wrk/ -t owasp/zap2docker-weekly zap-baseline.py -t https://ip/login.html -r testreport.html

this page 'https://ip/login.html' need password and account, 
and how to traverse all pages?

**Comment by kingthorin** [comment]
Please don't ask questions as issues - the ZAP User Group https://groups.google.com/group/zaproxy-users is a much better place for questions.
