### ISSUE TITLE
Release main add-ons for 2.9.0

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#5799]
- [x] help (zap-core-help) zaproxy/zap-admin#315
 - [x] hud (zap-hud) zaproxy/zap-admin#314
 - zap-extensions: zaproxy/zap-admin#315
   - [x] alertFilters
   - [x] ascanrules
   - [x] bruteforce
   - [x] diff
   - [x] directorylistv1
   - [x] fuzz
   - [x] gettingStarted
   - [x] importurls
   - [x] invoke
   - [x] onlineMenu
   - [x] openapi
   - [x] pscanrules
   - [x] quickstart
   - [x] replacer
   - [x] reveal
   - [x] saverawmessage
   - [x] savexmlmessage
   - [x] scripts
   - [x] selenium
   - [x] spiderAjax
   - [x] tips
   - [x] webdriverlinux
   - [x] webdrivermacos
   - [x] webdriverwindows
   - [x] websocket
   - [x] zest

**Comment by thc202** [comment]
Per discussion in IRC, added OpenAPI to the list to help with #5802.

**Comment by thc202** [comment]
Closing, all released.
