### ISSUE TITLE
Enhancement: Wappalyzer API Output Suggestions

### ISSUE THREAD

**Issue by sonawanesarvesh** [zaproxy/zaproxy#5800]
Hi
I see little scope of enhancement in Wappalyzer Output

The URLs which is set in context are -

1. http://www.example.com
2. https://www.example2.com
3. www.example3.com
4. testingexmple.com

But the Wappalyzer API displays results with custom URLs naming system

1. It removes https or http from context URL
2. it adds port numbers 443, 80 to the URL
3. Sequence of input is also gets changed in **listall api** call (specially when HTTP URL is provided in context but OWASP detects its HTTPS version as well - so Wappalyzer displays results for both HTTP and HTTPS version so it alters the sequence)

So in programming, it becomes difficult to match the input context URL vs Wappalyzer output results

So i request can you please use the same URL (which is set in context ) for Wappalyzer output as well else keeping more generic will help to serve the purpose of matching input context URL vs Wappalyzer output

**Comment by psiinon** [comment]
Good suggestions. Using the original URL (which would work even if there wasnt a context) would also make it easier to surface these results in things like the HUD

**Comment by kingthorin** [comment]
Just to be clear this will mean changing the name or identifier accepted by the `listSite` API call, which will be a potentially breaking change. Hopefully this isn't used much so far (the API being fairly young) and so shouldn't be too impactful.

**Comment by thc202** [comment]
https://github.com/zaproxy/zaproxy/issues/5800#issuecomment-575053389 does that imply tracking the techs per page not the whole site as is now?

**Comment by kingthorin** [comment]
Good question, I was working toward a scheme and authority ‘site’ representation.

**Comment by kingthorin** [comment]
Fixed in https://github.com/zaproxy/zap-extensions/pull/2276
