### ISSUE TITLE
Install OpenAPI Addon for Docker?

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#5802]
We've had a few reports of users encountering "no implementor" when trying to import OpenAPI definitions without installing the OpenAPI addon. We should at least ensure it's installed on the docker images (check if it's available and install if not?).

Perhaps we should also consider making it part of the normal bundle? (GA/Weekly)

**Comment by thc202** [comment]
Right, the add-on is now included in all images (stable, weekly, and live).
