### ISSUE TITLE
Wants to exclude particular content-type: application/json;

### ISSUE THREAD

**Issue by NikitaShah2492** [zaproxy/zaproxy#5804]
I am running few urls in owasp and from one of the url I want to exclude particular content-type : application/json;

Will you please guide me how I can do it directly from the owasp tool and not from the command prompt?

**Comment by kingthorin** [comment]
Please don't ask questions as issues - the ZAP User Group https://groups.google.com/group/zaproxy-users is a much better places for questions.

You can select the item in the Site Tree and right click then "Exclude from".

If you're using a weekly or wait for 2.9 you'll be able to exclude resources from Active Scanning based on Tag and there is a default tag for JSON content.
