### ISSUE TITLE
Dockerized ZAP Proxy throws error when executing zap-cli commands

### ISSUE THREAD

**Issue by aluokkal** [zaproxy/zaproxy#5818]
**Start ZAP proxy container:**
```
docker run --detach --name zap -u zap -v "$(pwd)/reports":/zap/reports/:rw -i owasp/zap2docker-stable zap.sh -daemon -host 0.0.0.0 -port 8080 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true -config api.disablekey=true
```
**Execute zap-cli command in the running container**
```
docker exec zap zap-cli --verbose report -o /zap/reports/owasp-scan-report.html --output-format html
```
**Error occurs:**
```
Traceback (most recent call last):
  File "/usr/local/bin/zap-cli", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 621, in main
    raise RuntimeError('Click will abort further execution '
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment. Either switch to Python 2 or consult http://click.pocoo.org/python3/ for mitigation steps.
```
**Environment:**
4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux

**Comment by psiinon** [comment]
zap-cli is a 3rd party tool which is not supported by the ZAP core team.
You can raise issues on it here: https://github.com/Grunny/zap-cli

**Comment by aluokkal** [comment]
Ok, thanks, I will close this then.

**Comment by psiinon** [comment]
Actually looks related to https://github.com/zaproxy/zaproxy/issues/5632 so we _might_ be able to fix it ...

**Comment by aluokkal** [comment]
Ah, thanks, ok, will reopen :-).

**Comment by add-harris** [comment]
Is this issue fixed now? we are still getting the same error. Is a new owasp/zap2docker-stable base image being released?

**Comment by thc202** [comment]
It should in the weekly image released yesterday, stable will be released next (if no problems are reported with the weekly).

**Comment by psiinon** [comment]
Stable has now been re-released with this fix :)

**Comment by bb128b** [comment]
> Stable has now been re-released with this fix :)

Sorry to say I have been trying to zap2docker working on stable and still getting the same problems.

**Comment by thc202** [comment]
Which image ID? Did obtain/pull 2.9.0 again?
