### ISSUE TITLE
config arguments not accepted in docker image

### ISSUE THREAD

**Issue by javixeneize** [zaproxy/zaproxy#5819]
Hi

I have downloaded the latest docker image, and when starting zap headless, as explained in the wiki (https://github.com/zaproxy/zaproxy/wiki/Docker)

docker run -u zap -p 8080:8080 -i owasp/zap2docker-stable zap.sh -daemon -host 0.0.0.0 -port 8080 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true -config api.key=<api-key>

I have this error

no matches found: api.addrs.addr.name=.*

In the previous versions of the docker image it was working fine, so i think there might be a config missed?

Thanks

**Comment by thc202** [comment]
You need to quote the config value or escape the `*`.

**Comment by javixeneize** [comment]
Yes, make sense. Should the wiki be updated?

Thanks

**Comment by thc202** [comment]
That depends on how/where you are executing the command, it might not need any quotes/escape.
