### ISSUE TITLE
I am not able to record element name or xpath via inspect.exe in windows kits

### ISSUE THREAD

**Issue by NikitaShah2492** [zaproxy/zaproxy#5821]
Hello,

I am tying to get element name or xpath for owasp from inspect.exe in windows kits but it's not recording anything.

Please let me know if there is a way to get element name or xpath for selenium from owasp

**Comment by kingthorin** [comment]
Please don't ask questions as issues - the ZAP User Group https://groups.google.com/group/zaproxy-users and Developer Group https://groups.google.com/group/zaproxy-develop are much better places for questions.
