### ISSUE TITLE
Zap docker not accepting external connections

### ISSUE THREAD

**Issue by javixeneize** [zaproxy/zaproxy#5826]
Hi

Im starting the docker image like this:

docker run -u zap -p 8080:8080 -i owasp/zap2docker-stable zap.sh -daemon -host 0.0.0.0 -port 8080 -config 'api.addrs.addr.name=.*' -config 'api.addrs.addr.regex=true' -config 'api.key=test'

When i access to localhost:8080, i successfully hit the API, but, when accessing from an external machine, i have an error

ZAP Error [org.apache.commons.httpclient.NoHttpResponseException]: The server [IP] failed to respond

Stack Trace:
org.apache.commons.httpclient.NoHttpResponseException: The server [IP] failed to respond

I thought that exposing 0.0.0.0 it would be available to any computer in the network, isnt it?

Can you advise how should i expose that port to be available to external devices?

Thanks

**Comment by psiinon** [comment]
Please dont ask questions as issues - the User Group is a much better forum for them: https://groups.google.com/group/zaproxy-users
