### ISSUE TITLE
False Positive: Info Disclosure in URL (and 2 Evidence highlighting bugs)

### ISSUE THREAD

**Issue by davewichers** [zaproxy/zaproxy#5832]
**Describe the bug**
Bug 1: ZAP is reporting an "Information Disclosure - Sensitive Information in URL" issue because it found: "forceAuth=false&passiveAuth=false" parameter values in a URL, and it is flagging 'passiveAuth=false' as sensitive data, which seems wrong to me.

Bug 2: In the Request tab the 'false' value of forceAuth is being highlighted when the finding is saying it is the false value of the passiveAuth parameter that is the 'Evidence' that this is a true finding. Maybe the highlight code simply is doing a search for 'false' and flagging the first value it finds? Rather than finding the value of the flagged parameter and highlighting that?

**Expected behavior**
Bug 1: Shouldn't flag this.

Bug 2: Should highlight the parameter value of the parameter being flagged.

**Reproducibility**
I happen to also notice that there is another "Information Disclosure - Sensitive Information in URL" issue being reported for the exact same request. In this 2nd issue, the parameter name/vaue is: sessionDataKey=SOMEVALUE, and it is showing that parameter name and this value as the Evidence.

This 2nd finding might be legit. I'm wondering if it is the 2nd finding that is causing the erroneous first finding to also be flagged.

Bug 3: Related to this 2nd finding, the highlighting of the evidence for this one seems to be wrong too, because it is flagging the value attribute of this part of the response:

    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <input type="hidden" name="sessionDataKey" value='edb5e18d-f179-4f13-9218-138ae4f16f58'/>

Rather than the parameter value in the URL (which is where it also is). The above DIV is inside a <form> in the response.

**Software versions**
 - ZAP: ZAP: 2.9.0 snapshot D-2020-01-07

**Comment by kingthorin** [comment]
The first one is matching simply on `pass`, this is a false positive I'm happy for us to live with. Though the alert details could perhaps be more specific to help the user in designating it a false positive. I'll look at including the matched string int he description or other info.

The second one is due to matching first occurrence, matching specific occurrences or multiple occurrences is much more work. Not to say it'll never happen, but just to confirm your suspicion.
