### ISSUE TITLE
False Positive: Suspicious Comments Finding (and an enhancement request)

### ISSUE THREAD

**Issue by davewichers** [zaproxy/zaproxy#5834]
**Describe the bug**
The following response content was flagged by this rule:
```
 <script>
        function submitCredentials (e) {
            e.preventDefault();
        	var userName = document.getElementById("username");
            userName.value = userName.value.trim();
            if(userName.value){
                document.getElementById("loginForm").submit();
            }
        }
 </script>
```
**Expected behavior**
This content should not be flagged as far as I can tell.

**Enhancement request**
The flagged content is dumped into the 'Other Info:' window in the finding. Can you make the windows in a finding resizable vertically so you can expand the size of those windows rather than trying to scroll through a tiny box to see the content?

**Software versions**
 - ZAP: 2.9.0 snapshot D-2020-01-07

**Comment by kingthorin** [comment]
Please provide the full response

**Comment by davewichers** [comment]
Here you go. I removed some unnecessary white space but other than that, this is the exact response.

[SuspiciousCmnts-Issue5834Response.txt](https://github.com/zaproxy/zaproxy/files/4123332/SuspiciousCmnts-Issue5834Response.txt)

**Comment by kingthorin** [comment]
Thanks, was about to recreate. It's legitimately found based on the current logic, script blocks are also checked for the suspicious strings which includes "username" because the parser can't identify comments within script blocks.

We could tie that to a threshold check so that it would only be done at low threshold. (https://www.zaproxy.org/docs/desktop/ui/dialogs/options/pscanrules/)

**Comment by davewichers** [comment]
If it can't tell comments from code in script, then I would set those types of findings to low confidence. Can a single rule have different levels of confidence for different types of findings? i.e., findings in normal comments would be marked as medium confidence but script comments are marked low?

**Comment by kingthorin** [comment]
Yup that could definitely be done.
