### ISSUE TITLE
Zap2Docker-weekly api scan openapi working. SOAP is not. 

### ISSUE THREAD

**Issue by nikbru** [zaproxy/zaproxy#5836]
When I'm testing my swagger api. everything works correctly. When I'm testing with a WSDL and Soap, im getting an error: missing implementor. I think the zap2docker-weekly is missing the soap addon.

How can I install this?

Command:
docker run -v ${PWD}:/zap/wrk/:rw -t owasp/zap2docker-weekly zap-api-scan.py -t http://www.dneonline.com/calculator.asmx?wsdl -f soap -r testreportwsdl.html

Error:
No Implementor (no_implementor)

Installed add-ons: [[id=accessControl, version=6.0.0], [id=alertFilters, version=10.0.0], [id=ascanrules, version=34.0.0], [id=ascanrulesBeta, version=28.0.0], [id=bruteforce, version=9.0.0], [id=coreLang, version=14.0.0], [id=diff, version=10.0.0], [id=directorylistv1, version=4.0.0], [id=formhandler, version=3.0.0], [id=fuzz, version=12.0.0], [id=gettingStarted, version=11.0.0], [id=help, version=10.0.0], [id=hud, version=0.9.0], [id=importurls, version=7.0.0], [id=invoke, version=10.0.0], [id=onlineMenu, version=7.0.0], [id=openapi, version=15.0.0], [id=plugnhack, version=12.0.0], [id=portscan, version=9.0.0], [id=pscanrules, version=26.0.0], [id=pscanrulesBeta, version=22.0.0], [id=quickstart, version=27.0.0], [id=replacer, version=8.0.0], [id=reveal, version=3.0.0], [id=saverawmessage, version=5.0.0], [id=savexmlmessage, version=0.1.0], [id=scripts, version=26.0.0], [id=selenium, version=15.1.0], [id=sequence, version=6.0.0], [id=spiderAjax, version=23.1.0], [id=tips, version=7.0.0], [id=webdriverlinux, version=16.0.0], [id=webdrivermacos, version=15.0.0], [id=webdriverwindows, version=16.0.0], [id=websocket, version=21.0.0], [id=zest, version=31.0.0]]

**Comment by kingthorin** [comment]
The SOAP add-on 8s not currently available due to various functional issues.

**Comment by thc202** [comment]
Reference: #4866
