### ISSUE TITLE
False Positives: Timestamp Disclosure - Unix

### ISSUE THREAD

**Issue by davewichers** [zaproxy/zaproxy#5837]
**Describe the bug**
These are almost always false positives for me. For example, here is my current set of timestamps being reported:

2147483647, which evaluates to: 2038-01-18 22:14:07
0123456789, which evaluates to: 1973-11-29 16:33:09
2146823252, which evaluates to: 2038-01-11 06:47:32
62425156, which evaluates to: 1971-12-24 07:19:16
94906265, which evaluates to: 1973-01-03 05:51:05
00000000, which evaluates to: 1969-12-31 19:00:00
33333333, which evaluates to: 1971-01-21 14:15:33
etc.

All of these happen to be in .js or .css files, which are typically static. And these timestamps are also nowhere near current time. As such, I suggest two potential filters to reduce false positives for this rule:

1) Simply ignore all .js and .css files, 
and/or
2) Look at the time calculated and if its not +/- 1 year from current time, ignore them.

Isn't the risk that the system is leaking it's current time calculation? If so, then if the time leaked isn't anywhere near current time then its not leaking anything interesting. If current time is really the concern, then checking for +/- 1 day or 1 week might be even better.

**Expected behavior**
Not report these somewhat obvious values as potential timestamps.

**Software versions**
 - ZAP: 2.9.0 snapshot D-2020-01-07

**Comment by kingthorin** [comment]
I don't think you can assume that current time is all that matters.

Off the top of my head a timestamp for account creation or password reset could also be of value to an attacker if it was used as a salt or key of some sort. I'm sure there are plenty of other scenarios as well.

I guess we might be able to put a time bound on future dates, though I could see that perhaps I'm just not anticipating a use or abuse there as well.

**Comment by kingthorin** [comment]
I'll add [Threshold](https://www.zaproxy.org/docs/desktop/ui/dialogs/options/pscanrules/#Threshold) handling for this, so that at `High` it'll only be +/- 1 year. Then users will have the option of hearing less and potentially accepting false negatives.
