### ISSUE TITLE
False Positive: Backup File Disclosure

### ISSUE THREAD

**Issue by davewichers** [zaproxy/zaproxy#5838]
**Describe the bug**
An active scan request to access: https://TARGETSITE/logincontext.jar receives this response:

```
HTTP/1.1 400 Bad Request
Server: nginx/1.17.6
Date: Tue, 28 Jan 2020 17:40:13 GMT
Content-Type: text/html;charset=UTF-8
Content-Length: 825
Connection: keep-alive
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Set-Cookie: JSESSIONID=A4A6E63AED4FEDF817894F22776B64D6; Path=/; Secure; HttpOnly
Last-Modified: Tue, 13 Mar 2018 05:24:24 GMT
ETag: W/"825-1520918664000"

<!--
  ~ Copyright (c) 2016, some vendor. All Rights Reserved.
  ~ 
  ~ LICENSE TERMS HERE
  -->

<html>
    <head>
        <title>Error 400</title>
    </head>
    <body>
        <h1>Error 400 - Bad Request</h1>
    </body>
</html>
```

**Expected behavior**
I wouldn't expect this response to be flagged as a successful 'disclosure' of a backup file as it doesn't seem to disclose anything of interest (to me anyway).

**Software versions**
 - ZAP: 2.9.0 snapshot D-2020-01-07

**Comment by kingthorin** [comment]
If the file isn't there shouldn't it be a 404?

**Comment by davewichers** [comment]
Maybe. I don't know. I can ask for MADEUPFILENAME.jar and it responds with a 400. So the existence, or not, of the JAR file is irrelevant to the behavior. I just don't see how a 400 bad request discloses the existence of a 'backup' file.

**Comment by globeone** [comment]
I agree with @davewichers here: Anything other than an HTTP 200 shouldn't be flagged as a successful backup file disclosure. Also, there needs to be some kind of other check for example on content/type.

Might even be possible to check for keywords in the body of the page like in the example above "HTTP 400 - Bad Request"

This false positive is very common and creates a lot of 'noise' as the developers complain in the scans we perform. I'll see if I can dig up some more examples to test against.

**Comment by psiinon** [comment]
All good feedback, and I agree this rule currently produces way too many FPs.

**Comment by kingthorin** [comment]
Some of this will be addressed by the forth coming Custom Pages implementation, which will allow users to define custom 404 configs.

Some of this could be handled via Threshold, and functional changes.

**Comment by globeone** [comment]
Here are some examples. All of these returned:
"HTTP/1.1 500 Internal Server Error"
A real backup file disclosure might be better to restrict to HTTP 200's?
[
ZAPBug5838_examples_all_HTTP500.pdf](https://github.com/zaproxy/zaproxy/files/4186631/ZAPBug5838_examples_all_HTTP500.pdf)

**Comment by kingthorin** [comment]
It "might" be but you're over simplifying it. You have to account for servers that don't properly 404 amongst other things.

If you want to get a better handle for it checkout the code of the scan rule here: https://github.com/zaproxy/zap-extensions/blob/master/addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/BackupFileDisclosure.java

**Comment by globeone** [comment]
> It "might" be but you're over simplifying it. You have to account for servers that don't properly 404 amongst other things.
> 
> If you want to get a better handle for it checkout the code of the scan rule here: https://github.com/zaproxy/zap-extensions/blob/master/addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/BackupFileDisclosure.java

Ok, thanks for your answer.
That servers handle 404 Not Found as regular web pages I fully agree. 

Out of curiosity. Is there an example in the 'wild' of an "HTTP **500** Internal Server Error" returning a backup file? I've never seen this behaviour from a web server and it makes for an interesting security concern if it happens.  

I had a look at the code and only see handling of the HTTP 404 Not Found responses. Apologies my Java coding is not very good, so I can't seem to find the handling of HTTP 5xx Internal Server Error.

If HTTP 5[0-9][0-9]
Then exit

**Comment by kingthorin** [comment]
That's exactly the point you can't assume that a status code means something RFC relevant. This whole issue is based on the misbehaviour of an app/server returning 400 instead of 404 (which could just as easily be 500 instead of 404 of 200 instead of 404).

The scan rule does attempt to discern the weird or non compliant behaviours of the server/app before raising an alert but if it isn't consistent then the issue manifests as seen here.

As already mentioned:
> Some of this will be addressed by the forth coming Custom Pages implementation, which will allow users to define custom 404 configs.

> Some of this could be handled via Threshold, and functional changes.

**Comment by globeone** [comment]
I'm revisiting this bug as it's become an embarrassment to ZAP when dealing with vendors who are still stuck in the Burp days of doing things. At least I was embarrassed while demoing ZAP to a vendor we had scanned and had a stern talking-to by the product manager about why we are unable to keep the false positives down, as they are costly in time and resources to filter by hand.

As suggested earlier I set the Threshold to High thinking that hey, now ZAP will only flag HTTP 200's or things that actually return content. Unfortunately this was not the case, as you can see in the screenshot below. 

![2020-07-22_ZAP_BackUpFileDisclosureIgnoresHighThreshold](https://user-images.githubusercontent.com/10052587/88172312-1108d500-cc21-11ea-8976-b240b5d1efb7.png)

Is there a quick way to set the High Threshold to only return HTTP 200's responses?

Or are we better off just turning Backup File Disclosure off until there is a fix?

**Comment by kingthorin** [comment]
> Is there a quick way to set the High Threshold to only return HTTP 200's responses?

Submit a PR? :wink:

**Comment by psiinon** [comment]
Have you tried the weekly release?
I think this https://github.com/zaproxy/zap-extensions/commit/45d7523c6daa9317cc444f8b3b88fc034e86af8f might have fixed it. If so we just need to release the beta ascan rules...

**Comment by thc202** [comment]
Closing, done as part of #6059.

**Comment by psiinon** [comment]
We'll release the ascanBeta rules asap...

**Comment by globeone** [comment]
That's awesome, thank you, I'll see if I can figure out how to get onto the weekly build.

**Comment by kingthorin** [comment]
It's a separate download. It's just ZAP packaged in a zip, you can expand it then run zap.sh or zap.bat.

https://www.zaproxy.org/download/ scroll down to "ZAP Weekly".

**Comment by psiinon** [comment]
We're releasing the ascanBeta rules now...

**Comment by psiinon** [comment]
And it should be available now :)
