### ISSUE TITLE
##[error]Task Failed. Error: "Error: getaddrinfo ENOTFOUND https https:80"

### ISSUE THREAD

**Issue by thomazbandeira** [zaproxy/zaproxy#5839]
![error OWASP ZAP Scan](https://user-images.githubusercontent.com/54593998/73502373-92388b00-43a7-11ea-8058-40318b51c46f.jpg)

I'm having trouble applying the Proxy to the application's Scan at pipeline Azure.
Can someone help me with this?

App Version:
![OWASP ZAP Scan](https://user-images.githubusercontent.com/54593998/73502555-2dc9fb80-43a8-11ea-836a-0fa42ca7b307.jpg)

in advance thank you for your attention!

**Comment by kingthorin** [comment]
The VSTS Task was created by and is maintained by a third party, you should reach out to them for support. 

https://kasunkodagoda.com/2017/09/03/introducing-owasp-zed-attack-proxy-task-for-visual-studio-team-services/

https://github.com/kasunkv/owasp-zap-vsts-task

**Comment by thomazbandeira** [comment]
thank you

**Comment by thc202** [comment]
For the record, kasunkv/owasp-zap-vsts-task#51.
