### ISSUE TITLE
PIIScanner false postive. Floating Point and Scientific Notation numbers incorrectly being detected as credit card numbers (reopen of #5124)

### ISSUE THREAD

**Issue by globeone** [zaproxy/zaproxy#5841]
## ZAP 2.9 is detecting Floating Point (2.4) and Scientific Notation (2.4E-10) numbers as Credit Cards. 

A credit card number is neither a Floating-point number nor a number in Scientific notation. In the earlier example and in this example where a conversion rate is being calculated. Yes it matches VISA and LUN-10 but it's not a credit card number. 

So we need to filter out Floating-Point and Scientific notation numbers which are clearly not Credit Card numbers first before performing the check if it's a valid credit card number.

Pseudo code: 
```
If 
  number is a floating-point number
  # 2.4 is not going to be a credit card number

  or is a number written in Scientific Expression
  # ends in "E-[0-9]" is not going to be a credit card number
 
  exit
else
 Check regular expression and Luhn()

```
example code that was flagged by ZAP as a Visa credit card:
```
"common.shared.conversion_rate.to_eur.mur&q;
:&q;
2.4670000000000001E-2&q;"
```

**Comment by kingthorin** [comment]
While you're not wrong, I think this is an FP we're okay with, and as a user you can mark it as a False Positives in the GUI or via the API (or using Alert Filters).

Here are a few reasons why:
- There are various languages that use period and comma with numbers in the opposite order (ex: 3,00).
- There are data formats that use dot separated values 5.5105105105105100.20191121.

We could implement the logic you mentioned for [High threshold](https://www.zaproxy.org/docs/desktop/ui/dialogs/options/pscanrules/#Threshold) and then you'd have an option of accepting potential False Negatives.

**Comment by kingthorin** [comment]
Would you be able to provide the full response?

**Comment by kingthorin** [comment]
Don’t worry about the response for now, it does seem there is some discrepancy in the behaviour of different card patterns for some reason.

**Comment by globeone** [comment]
Thank you for your response and for looking into this issue.
When validating 100's of security scans per day it's really annoying, and time-consuming to have to keep removing the false positives. Turning off the check is not an option as most websites have some kind of financial data on them.
Being able to recognize a floating-point number (, or . separated) vs a dot separated value should be programmatically quite easy with existing code on the internet (see links below). 

Scientific notation is easy as it always ends in E- or has the letter e in the number sequence.

I like the idea of High Threshold yet am still of the opinion that this can be solved for Medium as well.

I found some hints on how to solve this here:
### Java Check for valid Floating point or Scientific number
https://www.geeksforgeeks.org/check-if-a-given-string-is-a-valid-number-integer-or-floating-point-in-java/

### Regular expressions for currency formats
http://regexlib.com/Search.aspx?k=currency&AspxAutoDetectCookieSupport=1

### A JavaScript library that might be portable to Java that can handle currency number formats 
http://openexchangerates.github.io/accounting.js/

**Comment by globeone** [comment]
> There are data formats that use dot separated values 5.5105105105105100.20191121.

For this specific example above the Credit card check should execute as this is neither a valid floating-point nor scientific number. 

Here below as dot (.), comma(,) or apostrophe(') separated numbers will always be preceded in groups of 3 therefore it shouldn't execute.

1'050'080,21
2.995.554,9998
842,158,900,300.22578696574947759549E-3

Funny how this is a problem that is easy for a human to recognize but a computer struggles.

**Comment by globeone** [comment]
Shame there isn't an open source version of this database, or that they would donate API access to the OWASP project.
This database has a complete list of all the Bank Identifications numbers and the issuing bank. Unfortunately they want US$9800 every 2 years for access.
### Bank Identification Number Database 
https://www.bindb.com/ultimate-samples.html

**Comment by globeone** [comment]
Ask and thee shall receive
Open Source Bank Identification Number List
https://github.com/iannuttall/binlist-data

This will make the identification of Credit Cards more accurate and make the report 'schnazzy' as we can now tell the end user the issuing bank.

**Comment by kingthorin** [comment]
Thanks for digging that up.

**Comment by globeone** [comment]
As requested more of the response. Might be nice to test with
`"common.shared.conversion_rate.to_eur.mro":"2.3500000000000001E-3",
"common.shared.conversion_rate.to_eur.mru":"2.4119999999999999E-2",
"common.shared.conversion_rate.to_eur.mur":"2.4670000000000001E-2",
"common.shared.conversion_rate.to_eur.mvr":"5.8569999999999997E-2",
"common.shared.conversion_rate.to_eur.mwk":"1.23E-3",
"common.shared.conversion_rate.to_eur.mxn":"4.8000000000000001E-2",
"common.shared.conversion_rate.to_eur.myr":"0.22202",
"common.shared.conversion_rate.to_eur.mzn":"1.4370000000000001E-2",
"common.shared.conversion_rate.to_eur.nad":"6.2269999999999999E-2",
"common.shared.conversion_rate.to_eur.ngn":"2.9399999999999999E-3",
"common.shared.conversion_rate.to_eur.nio":"2.6530000000000001E-2",
"common.shared.conversion_rate.to_eur.nok":"0.10112",
"common.shared.conversion_rate.to_eur.npr":"7.92E-3",
"common.shared.conversion_rate.to_eur.nzd":"0.59587999999999997",
"common.shared.conversion_rate.to_eur.omr":"2.34137",
"common.shared.conversion_rate.to_eur.pab":"0.90024999999999999",
"common.shared.conversion_rate.to_eur.pen":"0.27093",
"common.shared.conversion_rate.to_eur.pgk":"0.26386999999999999",
"common.shared.conversion_rate.to_eur.php":"1.7680000000000001E-2",
"common.shared.conversion_rate.to_eur.pkr":"5.8199999999999997E-3",
"common.shared.conversion_rate.to_eur.pln":"0.23602999999999999",
"common.shared.conversion_rate.to_eur.pyg":"1.3999999999999999E-4",
"common.shared.conversion_rate.to_eur.qar":"0.24732000000000001",
"common.shared.conversion_rate.to_eur.ron":"0.20918999999999999",
"common.shared.conversion_rate.to_eur.rsd":"8.5199999999999998E-3",
"common.shared.conversion_rate.to_eur.rub":"1.465E-2",
"common.shared.conversion_rate.to_eur.rwf":"9.6000000000000002E-4",
"common.shared.conversion_rate.to_eur.sar":"0.24007000000000001",
"common.shared.conversion_rate.to_eur.sbd":"0.10983",
"common.shared.conversion_rate.to_eur.scr":"6.4530000000000004E-2",
"common.shared.conversion_rate.to_eur.sdg":"1.9650000000000001E-2"`

**Comment by globeone** [comment]
Found another test case if necessary> Here Longitude (negative Floating Point number) is incorrectly identified as a credit card number. 

{\"$date\":1580100621000},\"altitude\":39000,\"lat\":30.816666666666666,\"lng\":-15.**583333333333334**}

**Comment by kingthorin** [comment]
Thanks for the follow-up, at this point that'll continue to alert. Unfortunately there's no good way to distinguish it from: `2022-08-15.583333333333334.Jane Doe`, or other plausible occurrences, etc.

**Comment by globeone** [comment]
Adding the BIC (Bank Identification Code) will stop this one from flagging as valid. According to https://www.validcreditcardnumber.com

![image](https://user-images.githubusercontent.com/10052587/74674900-9ee41e00-51b2-11ea-8892-4d345786c340.png)

**Comment by kingthorin** [comment]
Yup #5842 is still open.
