### ISSUE TITLE
Enhancement: Mechanism to disable Wappalyzer

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#5846]
As Wappalyzer can often end-up being a passive scanner which results in the greater than 5sec log messages it would be nice if there was a mechanism by which it could be disabled. Ex:
>123739 [ZAP-PassiveScanner] WARN org.zaproxy.zap.extension.pscan.PassiveScanThread  - Passive Scan rule Wappalyzer Scanner (Tech Detection) took 16 seconds to scan https://redacted.com/en text/html; charset=utf-8 244603
130059 [ZAP-PassiveScanner] WARN org.zaproxy.zap.extension.pscan.PassiveScanThread  - Passive Scan rule Wappalyzer Scanner (Tech Detection) took 6 seconds to scan https://redacted.com/CommonElements/js/jquery-3.1.1.min.js application/javascript 86709

Either it needs to be converted to a `PluginPassiveScanner` so that it can be disabled in the standard passive scan rule options panel, or it needs a button added to it's toolbar (or new options panel) tied to `PassiveScanner.setEnabled()`.

I'm leaning towards the second option.

**Comment by psiinon** [comment]
It would be good to know what sort of files it takes a long time with, eg if its just big files then we could have an option for it to ignore files over a configurable size. Hopefully it will still be able to fingerprint most techs from smaller files on sites.

**Comment by kingthorin** [comment]
Well that's more like: https://github.com/zaproxy/zaproxy/issues/3813 Which is also important but also a bigger change. 

Currently the only option for Wappalyzer is to have it or not, since it's a PassiveScanner (not a PluginPassiveScanner) it can't be disabled (in the UI). (I guess technically you could also disable the extension but that probably requires a Zap restart.)

I was just thinking a simple on/off (enable/disable) for users so that people didn't have to uninstall if it was causing performance issues.
