### ISSUE TITLE
Deprecate Web Browser XSS Protection Not Enabled?

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#5849]
See: https://security.stackexchange.com/questions/225415/are-favicon-ico-robots-text-sitemap-xml-vulnerable-to-xss

Per:
https://caniuse.com/#search=X-XSS-Protection
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection

---

![image](https://user-images.githubusercontent.com/7570458/73929409-be21a800-48a2-11ea-9bbc-ccf2846469c8.png)

**Comment by psiinon** [comment]
Yeah, I noticed that too. I'm good with deprecating it.

**Comment by kingthorin** [comment]
Ref:
  Addon: pscan release
  Rule: HeaderXssProtectionScanner.java
  PluginID: 10016
