### ISSUE TITLE
Zap Scan on windows created around 34GB data and eating up entire space.

### ISSUE THREAD

**Issue by ankitloud** [zaproxy/zaproxy#5852]
When I started one of my onpremises web application using ZAP active scan, it reached till 60% and after that I found windows is out of memory. I went to Owsap folder and checked under session that untitiled.data created 32 GB and untitiled.lobs have eaten up around 2 GB space. Now my scan is done only 60% so how would I run next remaining 40% and how to get back my 32GB space back ?

**Comment by kingthorin** [comment]
Please don't ask questions as issues - the ZAP User Group https://groups.google.com/group/zaproxy-users is much better place for questions.

There are tons of options for dealing with this, which include:
- Model the app properly: https://www.zaproxy.org/docs/desktop/start/features/structparams/
- Use a more specific scan policy: https://www.zaproxy.org/docs/desktop/start/features/scanpolicy/
- Target different pieces of your app separately.
- etc.

https://www.zaproxy.org/docs/desktop/

**Comment by ankitloud** [comment]
Consider I use default option then what should I do?

**Comment by psiinon** [comment]
As stated above, dont ask questions on github issues.
