### ISSUE TITLE
Base64 potentially long Loop

### ISSUE THREAD

**Issue by globeone** [zaproxy/zaproxy#5856]
**Describe the bug**
We are scanning a very large web application that is causing ZAP to crash. We've increased the memory to 8GB for ZAP in the zap.bat file but it continues to enter a kind of loop when passive testing BASE64 Disclosure and keeps reporting the same exact JavaScript file over and over again until it runs out of memory.

**To Reproduce**
- In ZAP BAT change from the default 512MB memory to "set jvmopts=-Xmx8096m"
- Manual Explore
- HUD
- Wait 30 seconds as ZAP passive scans the initial page
- ZAP alert queue Base64 starts filling up with alerts
- CPU fans starts going crazy
- Machine becomes slow
- Have to force quit ZAP before things get to hairy

**Expected behavior**
One single Base64 Disclosure per file, instead of 900 Base64 disclosures for a single file. Although I suspect this is more of a symptom than the actual root cause. Hopefully the Log File attached will tell more.

**Screenshots**
![image](https://user-images.githubusercontent.com/10052587/74260136-4f58aa80-4cf9-11ea-9f26-7a41ba07f734.png)

**Software versions**
 - ZAP: 2.9
 - Add-on: 
[2020-02-11_InstalledAddOns.txt](https://github.com/zaproxy/zaproxy/files/4187013/2020-02-11_InstalledAddOns.txt)

 - OS: Windows 10 1909 Build 18363.592
 - Java: Bellsoft openjdk version "13.0.2" 2020-01-15
OpenJDK Runtime Environment (build 13.0.2+9)
OpenJDK 64-Bit Server VM (build 13.0.2+9, mixed mode, sharing)
 - Browser: Firefox 72.0.1

**Errors from the zap.log file**
[2020-02-11_Passive_Scanning_outofmemory.log](https://github.com/zaproxy/zaproxy/files/4187018/2020-02-11_Passive_Scanning_outofmemory.log)

**Additional context**
The website is running on a nonstandard TCP port

**Comment by kingthorin** [comment]
I don't see any issue related to memory?

Your addons seems to be out of date, the SRI scanner NPE was fixed a number of versions ago.

**Comment by kingthorin** [comment]
Can you confirm whether or not the alerts are about ViewState?

**Comment by kingthorin** [comment]
We've been discussing this in IRC. There are some ways we can tweak the rule to be more user friendly.

In the case of ViewState issues there will still be the potential for two different alerts (viewstate and macless), in the case of plain b64 alerts it'll only alert once. 

We'll update the Alert description or "Other Info" with something along the lines of "...in the interests of performance not all b64 strings were separately evaluated, the entire response should be looked at by the analyst/security team/developer(s)."

**Comment by kingthorin** [comment]
Re: SRI scanner I'm wrong, I guess that hasn't been released yet.

**Comment by globeone** [comment]
I'm getting the same behavior with the Unix Timestamp vulnerability, together with the Base64 vulnerability. ZAP is enumerating the same JavaScript over and over again. ZAP has hung, so I'm having troubles getting the request-response pair to see if each vulnerability is the same or different.

**Comment by globeone** [comment]
![image](https://user-images.githubusercontent.com/10052587/74326125-2a604800-4d8a-11ea-80b1-7b63780c33b3.png)

You are correct about it not being a memory issue, it's actually a high CPU usage issue.

**Comment by globeone** [comment]
[2020-02-12_HighCPUBASE64andUnixTimestamp.log](https://github.com/zaproxy/zaproxy/files/4191869/2020-02-12_HighCPUBASE64andUnixTimestamp.log)

**Comment by kingthorin** [comment]
Thanks for the additional detail but I'm missing the problem. You're worried about 12-13% CPU usage and a rule that took 11sec on one request?

**Comment by globeone** [comment]
> Thanks for the additional detail but I'm missing the problem. You're worried about 12-13% CPU usage and a rule that took 11sec on one request?

No, I was being overworked and stupid. Basically ZAP was hanging completely and I drew the incorrect conclusion that CPU and Memory were a factor. They are clearly not the reason ZAP is hanging.
