### ISSUE TITLE
Is there any script to manage the session and help ZAP login application using Oauth(Cognito) for authentication

### ISSUE THREAD

**Issue by god0fcode** [zaproxy/zaproxy#5858]
I am looking for some script to manage the session when application uses cognito for login. When ZAP runs on Jenkins it perform the spider scan on only login page and some CDN URL. Is there any way ZAP can login to application working integrated with Cognito.

**Comment by kingthorin** [comment]
I'm not aware of one, however someone in the [ZAP User Group](https://groups.google.com/group/zaproxy-users ) may have created one plus it's a much better place for questions than our GitHub issue tracker.
