### ISSUE TITLE
BUG: History Tags Column is not filled consequently (JSON)

### ISSUE THREAD

**Issue by globeone** [zaproxy/zaproxy#5861]
**Describe the bug**
When viewing the History Tab in the "Tags" column the tag isn't filled in consequently. Sometimes it says JSON for a JSON response and other times it's just blank even for the same page. Even though other parts of the code have correctly identified the response as JSON

**To Reproduce**
- Start an Active Scan with lots of JSON responses
- View the History Tab
- View that for the same response JSON is filled in sometimes, and other times left blank.

**Expected behavior**
- The tag field should be filled in with the correct response type every time.

**Screenshots**
![image](https://user-images.githubusercontent.com/10052587/74348742-7a9fd000-4db3-11ea-9606-6a269ee6e4fb.png)

**Software versions**
 - ZAP: 2.9
 - Add-on:  Please note that I had to disable Passive Scanning entirely for this specific scan
[2020-02-12_InstalledAddOns_NoPassiveScanning.csv.txt](https://github.com/zaproxy/zaproxy/files/4193115/2020-02-12_InstalledAddOns_NoPassiveScanning.csv.txt)

 - OS: Windows 10 1909 18363.592
 - Java: java -version
openjdk version "13.0.2" 2020-01-15
OpenJDK Runtime Environment (build 13.0.2+9)
OpenJDK 64-Bit Server VM (build 13.0.2+9, mixed mode, sharing)
 - Browser: Firefox 73

**Errors from the zap.log file**
Domain Sanitized.
[2020-02-12_zapBugTagColumn.log](https://github.com/zaproxy/zaproxy/files/4193150/2020-02-12_zapBugTagColumn.log)

**Additional context**
This scan is still running (huge site takes a very long time) There may be other interesting things in the Log File to solve that I don't know where they go qua bug reports yet.

**Comment by kingthorin** [comment]
Is the content-type in the response header always `application/json`?

Also tagging is done as part of passive scanning so they may simply not have been applied yet.

**Comment by kingthorin** [comment]
Check the little eye icon and count in the bottom right footer of the window to see if there's still a passive scan queue.

**Comment by globeone** [comment]
> Check the little eye icon and count in the bottom right footer of the window to see if there's still a passive scan queue.

The scan was completely finished and the headers did contain application/json

**Comment by kingthorin** [comment]
Ummmm your original submissions states “ This scan is still running”

**Comment by globeone** [comment]
> Ummmm your original submissions states “ This scan is still running”

Yes, when I originally posted the scan was still running. When I replied to your post with a request to view the eye icon it was later and the scan had finished. :smile:
