### ISSUE TITLE
OpenAPI - Not creating Map structure properly

### ISSUE THREAD

**Issue by josehenriqueventura** [zaproxy/zaproxy#5863]
**Describe the bug**
The OpeAPI Zap-extension is not creating Map structure properly, every MapSchema is interpreted as a String which leads to errors on the backend when ZAP tries to perform a request.

**To Reproduce**
 [This](https://gist.github.com/josehenriqueventura/fabb103490d279d68f73beae9e5f721f) OpenAPI definition file generates the JSON [1] with the current implementation while it should generate the JSON [2]. Also is possible to past the definition file on the [swagger editor](https://editor.swagger.io/) to compare the results.

[1] `{"cites":"John Doe","description":"John Doe","name":"John Doe"}`

Running ZAP

**Request:**
{"cities":"John Doe","description":"John Doe","name":"any\r\nSet-cookie: Tamper=71303918-c37e-494d-a77d-c2b76664339d"}

**Response:** 
javax.ws.rs.ProcessingException: RESTEASY008200: JSON Binding deserialization error: javax.json.bind.JsonbException: Unable to deserialize property &#x27;cities&#x27; because of: Error deserialize JSON value into type: java.util.Map&lt;java.lang.String, java.lang.String&gt;.

====================

[2] `{"cites":{"John Doe":"John Doe"},"description":"John Doe","name":"John Doe"}`

Running ZAP (After my implementation)

**Request:**
`{"cities":{"John Doe":"c:/Windows/system.ini"},"description":"John Doe","name":"John Doe"}`

**Response**
`[{"cities":{"John Doe":"c:/Windows/system.ini"},"description":"John Doe","name":"John Doe"}]`

**Expected behavior**

**Map String Number** 

 `{"cites":{"John Doe":1.2},"description":"John Doe","name":"John Doe"}`

**Map String String** 

 `{"cites":{"John Doe":"John Doe"},"description":"John Doe","name":"John Doe"}`

**Map String Boolean**

 `{"cites":{"John Doe": true },"description":"John Doe","name":"John Doe"}`

**Map String Object**

 `{"cites":{"John Doe":{"name":"John Doe"}},"description":"John Doe","name":"John Doe"}`

**Screenshots**

**Software versions**
 - ZAP: 2.9.0
 - Add-on: OpenAPI
 - OS: Linux 
 - Java: java version "1.8.0_231"

==

I'm looking forward to making my first contribution and also future improvements on this extension if the team feels the necessity of it.

**Comment by thc202** [comment]
Released in version 16 of OpenAPI add-on.

**Comment by josehenriqueventura** [comment]
Great
