### ISSUE TITLE
Zap 2.9.0 hangs again and again for larger websites

### ISSUE THREAD

**Issue by ankitloud** [zaproxy/zaproxy#5865]
I am using 64GB Ram Windows 10 system and I believe it is more than recommended one. I am facing issue everyday whenever I put my web application for active scanning after crawling all web pages. some times during scan when I want to see Alert and scroll down, it hangs. Sometime when I left the system unattended for 24+ hrs and later want to see the status, it hangs. There is  no guarantee of successful scan which is wasting my effort every day. Can some one please help me here ? Do I need to some kind of fine tuning ?

**Comment by kingthorin** [comment]
Please don't ask questions as issues - the ZAP User Group https://groups.google.com/group/zaproxy-users  is a much better place for questions.

**Comment by thc202** [comment]
Might worth checking #5791.
