### ISSUE TITLE
Chrome crashing in ZAP 2.9.0

### ISSUE THREAD

**Issue by Shrimant** [zaproxy/zaproxy#5868]
We are trying to evaluate ZAP for our application. However, whenever we are running Automated Scan or even ... using Chrome, it shows a pop up saying: "Failed to start Chrome browser. Make sure that Chrome and ChromeDriver are available. For more details refer to "Options Selenium screen" help page.

When I open "Tools -> Options -> Selenium screen", under WebDrivers, I see gechodriver = C:\Users\<user name>\OWASP ZAP\webdriver\windows\64\geckodriver.exe and ChromiumDriver= C:\Users\shrimant.chakrabarti\OWASP ZAP\webdriver\windows\32\chromedriver.exe 

Also, the gechodriver version is 0.26.0. OS: Windows 10 Pro, 64 bit. JRE version: JRE 8 64bit, update 221

Kindly help us so that we can continue our process to evaluate ZAP for our application smoothly.

**Comment by psiinon** [comment]
Have you made sure that ZAP is completely up to date by checking for updates?
If so what version of chrome are you using?

**Comment by Shrimant** [comment]
When I am checking for updates, it shows that I already have the latest ZAP version 2.9.0. My chrome version is Version 80.0.3987.116. It was 79.X version when I had faced the issue.
Will check once more from my end.

**Comment by Shrimant** [comment]
The chrome browser is not opening. However, I had opted for Chrome 79 Wins 10 as my Default User Agent in General Configuration under Connection tab (Tools->Options->Connection). It seems to be working out for me but will you be adding Chrome 80 Wins 10 option too?

**Comment by kingthorin** [comment]
You can enter any UA you like.
