### ISSUE TITLE
Ajax Spider - per element exclusions

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#5875]
It would be really useful to be able to exclude specific HTML elements from the Ajax Spider.
A problem that this would solve was reported via Slack:
```
The Ajax Spider soon hits the logout button. 
This causes a bunch of JavaScript actions which render the logout page. 
Its obvious, that excluding the logout backend call from context does not solve the problem, 
because the rendering is done anyway.
Is it possible to exclude a specific button identified by an custom HTML attribute or at least by ID from AjaxSpider?
```
We would probably want to support a range of options, not just ID.
this would probably make more sense as context configuration rather than global level as its likely to be app specific.

**Comment by BernhardPalmISO** [comment]
![LogoutButton](https://user-images.githubusercontent.com/61512161/75365350-5ff24e80-58bd-11ea-9d8c-441850b95038.jpg)
As requested the HTML of the Logout button.
