### ISSUE TITLE
XVWA SQL Injection not found ZAP Version 2.9.0

### ISSUE THREAD

**Issue by bill-chan-cyber** [zaproxy/zaproxy#5879]
**Describe the bug**
Using ZAP 2.9.0 to attack http://127.0.0.1/xvwa but SQL Injection not found even set the policy to insane

**To Reproduce**
1. Start ZAP  2.9 in Kali Linux 
2. Attack URL http://127.0.0.1/xvwa

**Expected behavior**
Expect SQL Injection Alert found

**Screenshots**
screenshot attached
![Screenshot from 2020-02-28 19-06-18](https://user-images.githubusercontent.com/61577921/75523925-0aef3d80-5a61-11ea-9d0b-dcd351c0d33a.png)

**Software versions**
root:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Kali
Description:	Kali GNU/Linux Rolling
Release:	kali-rolling
Codename:	kali-rolling
root:~$ cat /etc/os-release
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
VERSION="2018.4"
VERSION_ID="2018.4"
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"

root:~$ java -version
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Debian-1)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Debian-1, mixed mode)

root:~$ firefox -version
Mozilla Firefox 60.2.0
[zap.log](https://github.com/zaproxy/zaproxy/files/4265916/zap.log)

**Comment by psiinon** [comment]
Have you tried using the Advanced SQL Injection Scanner? https://www.zaproxy.org/docs/desktop/addons/advanced-sqlinjection-scanner/
You'll need to install this from the marketplace as its not included by default.

**Comment by bill-chan-cyber** [comment]
Hi Simon,

Something wrong with Version 2.9. It is still not working.
It couldn't find the SQL Injection vulnerabilities under url path http://127.0.0.1/xvwa/sqli<http://1127.0.0.1/xvwa/sqli> and http://127.0.0.1/xvwa/<http://1127.0.0.1/xvwa/sqli>sqli_blind.

Screen attached.
Thank you.

M.
________________________________

**Comment by kingthorin** [comment]
Have you tried using the Advanced SQL Injection Scanner?

> Something wrong with Version 2.9. It is still not working.

Did it previously (2.8.0)?

**Comment by kingthorin** [comment]
With just the default install of ZAP:
![image](https://user-images.githubusercontent.com/7570458/75640164-0c0ba080-5c02-11ea-8b03-6a6b06988b15.png)

**Comment by bill-chan-cyber** [comment]
Hi All, OK.  Could you please deploy XVWA package into XAMPP Server 7.4.2 Linux version and test it out? I have Kali Linux OS here.  I have added Advance SQL Injection.zap into default ZAP 2.9 version and test it out. It will show XVWA setup SQL Injection alert only. If I used default ZAP 2.9  to test it, it show zero alert. Thanks. M. On Mar 2, 2020 1:18 PM, kingthorin <notifications@github.com> wrote:With just the default install of ZAP:

**Comment by kingthorin** [comment]
Did you initialize XVWA by doing the in-app setup step?

The screenshot I added above was based on using ZAP on Kali 2020.1 (ZAP 2.9.0) with this dockerized XVWA: https://github.com/tuxotron/xvwa_lamp_container

**Comment by bill-chan-cyber** [comment]
Hi, I deployed the XVWA straight into htdoc directory and setup MySQL Table using phpAdmin. Thanks. M. On Mar 2, 2020 1:59 PM, kingthorin <notifications@github.com> wrote:Did you initialize XVWA by doing the in-app setup step?
The screenshot I added above was based on using ZAP on Kali 2020.1 (ZAP 2.9.0) with this dockerized XVWA: https://github.com/tuxotron/xvwa_lamp_container

**Comment by kingthorin** [comment]
Did you use the form you're trying to test?

**Comment by bill-chan-cyber** [comment]
Hi, May I know what form?? Thanks.M. On Mar 2, 2020 10:12 PM, kingthorin <notifications@github.com> wrote:Did you use the form you're trying to test?

**Comment by kingthorin** [comment]
The one on the SQLi test pages.

**Comment by bill-chan-cyber** [comment]
Hi, Sorry.  Could you please show me the screen shot please? Thank you. M. On Mar 3, 2020 8:09 AM, kingthorin <notifications@github.com> wrote:The one on the SQLi test pages.

**Comment by bill-chan-cyber** [comment]
Hi, Is this what you after please? Thanks. M. On Mar 3, 2020 8:09 AM, kingthorin <notifications@github.com> wrote:The one on the SQLi test pages.

**Comment by kingthorin** [comment]
Was there supposed to be an attachment or screenshot?

**Comment by bill-chan-cyber** [comment]
On Mar 3, 2020 11:46 AM, kingthorin <notifications@github.com> wrote:Was there supposed to be an attachment or screenshot?

**Comment by kingthorin** [comment]
Here's an animated GIF of this working. I'll be closing the ticket. If you have further questions please visit the [ZAP User Group](https://groups.google.com/forum/#!forum/zaproxy-users) for community assistance.

![xvwa_020-03-03](https://user-images.githubusercontent.com/7570458/75797243-e3d78b00-5d42-11ea-9fc8-c2579743254f.gif)
