### ISSUE TITLE
zaproxy doesn't detect known CRLF Injection vulnerability  in Puma 4.1.1

### ISSUE THREAD

**Issue by ohaddahan** [zaproxy/zaproxy#5880]
**To Reproduce**
1. Create a new Rails application `rails new application_name`
2. Change the Gemfile to `gem 'puma', '4.1.1'`
3. Run `bundle install`
4. Make sure `Gemfile.lock` shows `puma 4.1.1` is used
5. Start the application with `rails server`
6. Run an active scan on `http://localhost:3000`

**Expected behavior**
I'm expecting to see an alert for CRLF Injection since it's clearly in the covered policies.

**Software versions**
 - ZAP: 2.9.9
- Puma: 4.1.1

**Additional context**
[Vulnerability  data](https://snyk.io/vuln/SNYK-RUBY-PUMA-559020)

**Comment by kingthorin** [comment]
Which active scan rule packages do you have installed?

**Comment by ohaddahan** [comment]
@kingthorin default one coming with `Cross Platform Package` , attaching a couple of screenshots, hope it helps.

![image](https://user-images.githubusercontent.com/20769037/75609882-fec4b800-5b14-11ea-8810-fce1fb87d164.png)

![image](https://user-images.githubusercontent.com/20769037/75609885-0be1a700-5b15-11ea-92df-451d72ebeea4.png)

**Comment by kingthorin** [comment]
When you scanned were cookies included in your input vectors?

**Comment by ohaddahan** [comment]
@kingthorin 

Turned everything on, didn't alert about CRLF.

![image](https://user-images.githubusercontent.com/20769037/75610452-e6a36780-5b19-11ea-99f5-a6e9a4602485.png)

**Comment by kingthorin** [comment]
Is this the issue you're trying to replicate?
https://github.com/puma/puma/pull/1812#discussion_r307806310

You'd have to trigger a chunked request with the appropriate characteristics not just randomly visit the server. On top of which ZAP's current networking core doesn't always handle chunked encoding well.

**Comment by ohaddahan** [comment]
Roughly , @kingthorin I was trying to see if we can detect : 
https://github.com/puma/puma/issues/2132#issuecomment-592718436
https://github.com/puma/puma/security/advisories/GHSA-33vf-4xgg-9r58
https://github.com/puma/puma/pull/1812

Sorry for the ignorance, but how do I activate it, anywhere I can find instructions?

In my opinion it gives a false sense of security seeing "CRLF Injection" in the policies checked yet as I see in the results, and you explain it doesn't actually work without special settings.

**Comment by kingthorin** [comment]
I'm sorry but I don't have time to unravel the circumstances under which this vulnerability would manifest in Puma. That question is probably better posed to that project's team or community.
