### ISSUE TITLE
Make "Force Browse" search for files without slash at the end of the path and without extension

### ISSUE THREAD

**Issue by DiogoMRSilva** [zaproxy/zaproxy#5883]
**Is your feature request related to a problem? Please describe.**
I was testing Force Browse on a Hackerone 101 exercise and It wasn't able to find a path that was on the wordlist. The reason for that is that the server answers with 200 for `/login` but 404 for `/login/` and zap never sends the `/login`.

**Describe the solution you'd like**
I would like to add an option to the "force browse" extension to force it to make requests to files without extension and without slash.

**Describe alternatives you've considered**
Always make the request to the endpoint with and without slash at the end for each of the words on the wordlist. The problem of this solution is that will increase the number of requests and in most of the sites this isn't a problem.

**Comment by DiogoMRSilva** [comment]
Can I implement my solution?

**Comment by thc202** [comment]
Looks reasonable to me.
