### ISSUE TITLE
False Positive "Remote File Inclusion" on location redirect

### ISSUE THREAD

**Issue by arunzer** [zaproxy/zaproxy#5887]
**Describe the bug**
Imagine a html form which has an input field that allows you to specifiy an url. Upon submit this url is send via post channel to the server. The server then sends a http location header back causing the browser to redirect to the specified url from the post request. In this case zap mistakes the html of the rediect url as being included in the result page of the original form while zap is in fact looking at the actual page it was trying to include rather then an included version of it in the page being tested.

**To Reproduce**
1. Setup the following HTML/PHP script on e.g. a LAMP enviroment.

```
<?php
if ( isset($_POST['red_url']) AND is_string($_POST['red_url']) AND mb_strpos($_POST['red_url'],"http")===0 )
{
	header('Location:' . $_POST['red_url']);
}
?>
<form action="" method="post">
	<input type="text" name="red_url" value="">
	<button type="submit">send</button>
</form>
```
2. Scan this script with zap

**Expected behavior**
zap should only warn about the possibility of external redirect and not about a possible remote file inclusion.

**Software versions**
 - ZAP: 2.9.0

**Comment by kingthorin** [comment]
https://github.com/zaproxy/zap-extensions/blob/15f57836e0631623fad09d739d856d88c9fda4f3/addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/RemoteFileIncludeScanRule.java#L160-L161

https://github.com/zaproxy/zap-extensions/blob/15f57836e0631623fad09d739d856d88c9fda4f3/addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/RemoteFileIncludeScanRule.java#L224-L248

**Comment by kingthorin** [comment]
It seems that this was actually alerting on Open Redirects, per the example provided the browser would actually be redirected to google and surprise surprise (sarcasm) find the expected content.
