### ISSUE TITLE
[SOLVE] CRSF Token "not caught"

### ISSUE THREAD

**Issue by CaosFR** [zaproxy/zaproxy#5888]
**Describe the bug**
Hi, I try to brute force a POST password with zap fuzzing on my website but I have an issue with the CSRF Token. It never refresh so all my requests are lost.

TY for your help.

**To Reproduce**
1. Add the token name on ZAP (Options > Anti-CSRF Tokens)
2. GET the page with the target token : http://192.168.10.8/app.php
Code : [get.app.php.auth.txt](https://github.com/zaproxy/zaproxy/files/4306728/get.app.php.auth.txt)
3. Click on login => POST my login/password with the token : http://192.168.10.8/app.php/auth
Code : [post.app.php.auth.txt](https://github.com/zaproxy/zaproxy/files/4306731/post.app.php.auth.txt)
4. LOGOUT the web site
5. Lock history panel and "CRSF-Token" tag did not appear.
6. Right click on POST request => "Fuzzing" => add payload on password input => start.
7. Look at FUZZING panel, any CRSF token is refreshing.

**Expected behavior**
I would like to refresh automatically the CSRF token.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/37581932/76215728-a2961e00-620f-11ea-9b11-f9867e3f0334.PNG)
![Capture2](https://user-images.githubusercontent.com/37581932/76215757-b0e43a00-620f-11ea-8461-be3e1a02e041.PNG)

**Software versions**
 - ZAP: 2.9.0
 - Add-on: Passive Scan Rules v27, AdvFuzzer 12.0.0, Retire.js 4.0.0
 - OS: Windows 10
 - Java:  Oracle JRE 1.8.0_241_b07
 - Browser: Firefox developer edition 74.0b959

**Errors from the zap.log file**
[zap.log](https://github.com/zaproxy/zaproxy/files/4306910/zap.log)

**Additional context**
The token is on a PHP Symfony form. I have try to solve this problem on a new session, same problem.

**Would you like to help fix this issue?**
Yes.

**Comment by kingthorin** [comment]
There's no token in `get.app.php.auth.txt`

**Comment by kingthorin** [comment]
Try adding it URL encoded as it's seen in the request `utilisateur_auth%5B_token%5D`

**Comment by CaosFR** [comment]
@kingthorin TY for you help.
You can find the token "utilisateur_auth[_token]" on "get.app.php.auth.txt". 
I dont understand what do you mean with URL encoded. What I have to do exactely ?

**Comment by kingthorin** [comment]
>  You can find the token "utilisateur_auth[_token]" on "get.app.php.auth.txt".

Sorry my bad, for some reason notepad defaulted to searching "Up" which produces no result from position 0...../sigh Microsoft.

> I dont understand what do you mean with URL encoded. What I have to do exactely ?

Use the string I quoted (with the `%5B and %5D).

**Comment by CaosFR** [comment]
No problem  :).

I have add "utilisateur_auth%5B_token%5D" in Options > Anti-CSRF Tokens but I get the same issue.

**Comment by thc202** [comment]
The token as `utilisateur_auth[_token]` is correct, although the message has to be passive scanned for ZAP to start tracking the token which I guess it wasn't (yet, by the number of messages in the queue).

Also, before starting the fuzzer make sure that in the Message Processors it has the Anti-CSRF Token Refresher, otherwise it's not going to get a new token.

**Comment by CaosFR** [comment]
@thc202 TY very much !
I have close my session to clean the passive scan queue and retry to analyse the login / logout with ZAP. The CSRF Token has been taged and everything is working :+1: 

SOLVED
