### ISSUE TITLE
ZAP vsts plugin unable to interact with zap 2.9.0 proxy listening on 8080.

### ISSUE THREAD

**Issue by KarthikPutlur** [zaproxy/zaproxy#5892]
I tried to integrate zap into the vsts pipelines and used the zap plugin from market place to interact with the zap tool installed on my build agent. But the plugin failed to trigger a scan on the zap proxy. I am using 2.9.0 version of zap. The zap was listening on 8080. Is this bug known?

**Comment by kingthorin** [comment]
The VSTS plug-in was not created by, and is not supported by the core team. Please visit the marketplace again to find appropriate support details.

Could be here: https://github.com/kasunkv/owasp-zap-vsts-task but I’m not sure which one you downloaded
