### ISSUE TITLE
The application in the github can't be download

### ISSUE THREAD

**Issue by jiaoyujulx** [zaproxy/zaproxy#5893]
**Describe the bug**
The application in the github can't be download

**Expected behavior**
Can be downloaded.

**Screenshots**
![屏幕快照 2020-03-11 下午1 55 04](https://user-images.githubusercontent.com/50047494/76386765-46163880-63a0-11ea-8617-9e969bfd689d.png)

**Comment by psiinon** [comment]
Thats not likely to be a ZAP problem. Can you download other file from github?

**Comment by jiaoyujulx** [comment]
Yes,it can download other application in the github.I want to ask the network administrator of my company first.The issue can be closed.
发自我的iPhone

------------------ Original ------------------

**Comment by psiinon** [comment]
OK, thanks for letting us know.
