### ISSUE TITLE
Passive scan rule for generating script SRIs

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#5894]
The rule would raise info alerts for each script it found along with the integrety hash, as per
https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity

This could just work on URLs that are in scope - it would just be useful when you're trying to create a CSP for a specific site.

**Comment by kingthorin** [comment]
Should I or someone work on finishing the CSP Helper add-on and include this?

**Comment by psiinon** [comment]
That would be better, but I raised this as I thought it would be a relatively quick tasks that someone new could take on :)

**Comment by kingthorin** [comment]
Fair enough.

**Comment by mwesolowski** [comment]
Hi, I would like to work on the issue. But before I start implementation I need to clarify two things:
1. There already exists SubResourceIntegrityAttributeScanner which alerts about scripts and links that refer to external resource and don't have an integrity attribute. I plan to extend functionality of this scanner by adding SRI hash(es) to the solution of generated alerts. Unfortunately that involves delaying generation of the alerts to the time when subresource content is fetched. What do you think about this?
2. There is more than one possible way of generating hashes. For now possible hash alghoritms include sha256, sha384 and sha512. Do we want to provide all of them? Example solution content could look like this:  _Provide a valid integrity attribute to the tag. Value of the attribute (based on the fetched subresource) should be equal to one of the following strings: sha256-qvuZLpjL9TNV6yI1kNdGCPnSTrWM6Y0ILEzzyvA9hGY=, sha384-VHLTmjf/fb40V/5vnrAVRa7uMViqiTo64rQKfaGUGMiut1q36gCEbNygLwGot5Lu, sha512-zr/e3AD6xV0mhs4Tucw50QB71qpCRuTBTrgeoOmn8RI7vp5OUk+4CoECeyUe//XMd4jsFsYkDrRnXI90A+eyWA==_

**Comment by kingthorin** [comment]
Is there an industry standard/preference/guideline? The MDN ref above seems to favour sha384.

**Comment by mwesolowski** [comment]
According to [W3C](https://www.w3.org/TR/SRI/#hash-collision-attacks) sha384 was a good baseline in mid 2016. I'm not sure if things have changed since then. If I had to choose only one, it would be sha512 as it's the most collision-resistant.

**Comment by psiinon** [comment]
I'm good with reporting the sha384 hash in the existing issue - it would fit well in the solution field.

**Comment by mwesolowski** [comment]
@kingthorin According to shouldIgnoreInvalidFormattedHostname test in SubResourceIntegrityAttributeScannerTest class, links and scripts referring to invalid URIs should raise alerts. I'm not sure if that's correct behaviour because this scanner should be responsible for finding lacks of integrity checks and not misspelled or garbled refs. If reference is invalid, subresource cannot be fetched and in consequence hash cannot be calculated. I would like to change assertion in the test I mentioned before. What do you think about it? I direct this question to you because you were lately fixing bugs and adding tests to SubResourceIntegrityAttributeScanner.

**Comment by thc202** [comment]
IMO the behaviour should be kept as is, that test is verifying that a subresource without `integrity` attribute still raises the alert even if ZAP is not able to parse the URI (the test does use an extreme case of invalid URI, but not long ago ZAP would consider a hostname with underscores invalid while a browser would happily access it).

**Comment by mwesolowski** [comment]
I see. Thanks for clarification. That means providing hashes in alerts' solution will be optional.

**Comment by kingthorin** [comment]
@mwesolowski are you still planning to tackle this?

**Comment by mwesolowski** [comment]
@kingthorin I did some initial, dirty implementation. It stores pending alerts in SubResourceIntegrityAttributeScanner which wait for corresponding messages to compute integrity hashes. I still have to figure out how to handle situations when such message never reach scanner (to delete pending alert to avoid memory leak). Or how to intercept events such as ZAP session discarding to know when I need to clear all pending alerts.

**Comment by theamanrawat** [comment]
Hi @kingthorin, can I work on CSP evaluation implementation in ZAP?

**Comment by kingthorin** [comment]
That would be seperate from this, but sure. You can start a new thread in the [Developer Group](https://groups.google.com/g/zaproxy-develop) to discuss. 
- There's already a good Passive scan rule based on the Salvation library, it needs to be re-writen to use the new release of that library.
- There is also a partially completed PR for a new add-on which attempts to make derive a suggested CSP.

**Comment by theamanrawat** [comment]
Hi @psiinon, can you please elaborate this.

> The rule would raise info alerts for each script it found along with the integrety hash, as per
> https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity
> 
> This could just work on URLs that are in scope - it would just be useful when you're trying to create a CSP for a specific site.

**Comment by ArkaprabhaChakraborty** [comment]
is somebody working on this issue? If not then I want to work on this issue and get started with my contributions to zap.

**Comment by kingthorin** [comment]
Go for it @ArkaprabhaChakraborty , welcome aboard!
