### ISSUE TITLE
Angular 8 Spider not recognize pages

### ISSUE THREAD

**Issue by gabry** [zaproxy/zaproxy#5896]
I'm new to ZAP, please be patient whether some information provided will be incorrect. 
I have the task to make a security assessment on our company's Angular 8 web site.
It seems that Spider does not automatically find pages.
Are Angular sites managed by ZAP Spider?
Currently the only way to perform an Active Scan will be by manually navigating menu items in order to add Urls to Context.

I'm using 2.9.0.

Thanks.

**Comment by gabry** [comment]
Dear all, any news about this issue?

**Comment by kingthorin** [comment]
Please don't ask questions as issues, especially when providing zero details - the ZAP User Group https://groups.google.com/group/zaproxy-users is a much better place for questions.

If you’re asking about a third party components such as the Jenkins plugin or VSTS plugin please look for their preferred support mechanism as these were not created by and are not supported by the core team.

In this particular case you likely need to leverage the Ajax Spider: https://www.zaproxy.org/docs/desktop/addons/ajax-spider/
