### ISSUE TITLE
Allow to import from file into regular expression panels (e.g. Include in Context)

### ISSUE THREAD

**Issue by khalil2535** [zaproxy/zaproxy#5898]
**Is your feature request related to a problem? Please describe.**
I want to be able to include more than a domain/domain regex in my context faster, when i need to add the multiple domain regexes now i need to do that manually which consume long time.

**Describe the solution you'd like**
I need to be able to include add the domains i need from a txt file.

**Additional context**
maybe the best way is add a button here which allow the user to add the domain regex.
![image](https://user-images.githubusercontent.com/26520106/76695907-8968f380-668d-11ea-8150-bf455fc87c69.png)

**Comment by lordoftheseas** [comment]
I would like to work on this issue :)

**Comment by psiinon** [comment]
@lordoftheseas great - I've assigned it to you.

**Comment by StefanTobler** [comment]
@shashank-kv any progress on this issue? I am interested in seeing your approach.

**Comment by ckoidl** [comment]
I'd like to pick this one up.
