### ISSUE TITLE
Allows Regex duplication in the same Context

### ISSUE THREAD

**Issue by khalil2535** [zaproxy/zaproxy#5899]
**Describe the bug**
When i add a duplicated domain regex in the "Include in Context" menu it can be allow me to do that while it's shouldn't.

**To Reproduce**
1. Click on your Context multiple times.
2. Go to '1: Include in Context'
3. Added duplicate regex.
4. It's allowed.

**Expected behavior**
I expect to prevent me to do so with a warning or information message.

**Screenshots**
![image](https://user-images.githubusercontent.com/26520106/76695981-7d316600-668e-11ea-9b9d-d50dd38d3fbb.png)

**Software versions**
 - ZAP: all versions

**Errors from the zap.log file**
- No Need

**Comment by kingthorin** [comment]
Fixed in https://github.com/zaproxy/zaproxy/pull/5901
