### ISSUE TITLE
ZAP ascan.scan method/API doesn't honor context 

### ISSUE THREAD

**Issue by jyothsna-smax** [zaproxy/zaproxy#5910]
**Describe the bug**
For active scaning, the scan API has these parameters that can be passed.
scan(self, url=None, recurse=None, inscopeonly=None, scanpolicyname=None, method=None, postdata=None, contextid=None, apikey='')

which is equivalent to this API
http://localhost/JSON/ascan/action/scan/?url=https%3A%2F%2Freadacted.com&recurse=True&inScopeOnly=&scanPolicyName=Default+Policy&method=&postData=&contextId=2

when I pass contextID, it doesn't honor it. So, any authentication scripts though loaded in the context, the context itself isn't honored when called via the above API.
     
**To Reproduce**
1. Go to ZAP UI -> upload authentication scripts,
2  Create or import a context and load the above mentioned authentication script.
3  Import Swagger for a site or build a site tree for the site under scan.
3. Go to ZAP API and start an active scan , make sure you provide the context id (for the one created in step 2)
http://localhost/JSON/ascan/action/scan/?url=https%3A%2F%2Freadacted.com&recurse=True&inScopeOnly=&scanPolicyName=Default+Policy&method=&postData=&contextId=2
3. Notice that authentication scripts do not get triggered as the above  method/API doesn't honor the context.

**Expected behavior**
I expect that the context is honored when passed as a parameter to the ascan scan method/API

**Screenshots**

**Software versions**
 - ZAP: 2.9.0
 - OS: [e.g. crossplatform]
 - Java: [e.g. openjdk version "1.8.0_171"]
 - Browser: [e.g. chrome 66, firefox 59, safari 11.1]

**Comment by jyothsna-smax** [comment]
Note that forced user mode is disabled for both cases
scan and scan_as_user APIs.

**Comment by thc202** [comment]
> Notice that authentication scripts do not get triggered as the above method/API doesn't honor the context.

That endpoint is just to scan with context information (i.e. include/exclude, techs, alert filters, structure...), you'd have to use `scan_as_user` to have an authenticated scan.

**Comment by jyothsna-smax** [comment]
yeah, the problem is , Packaged scans don't call scan_as_user. they just call the scan api.
https://github.com/zaproxy/zaproxy/blob/develop/docker/zap_common.py#L401

**Comment by thc202** [comment]
That's a different problem than what was original reported, in that case it's possible to use a hook to enable forced user mode.

**Comment by thc202** [comment]
Closing, the packaged scans now allow to use a context/user:
https://github.com/zaproxy/zaproxy/blob/main/docker/CHANGELOG.md#2020-12-11
