### ISSUE TITLE
Pushing ZAP report to Jenkins workspace (Docker container)

### ISSUE THREAD

**Issue by palok86** [zaproxy/zaproxy#5914]
**Describe the bug**
docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-weekly zap-baseline.py \
    -t https://www.example.com -g gen.conf -r testreport.html 
This works fine in a VM environment.
But my jenkins worker runs as a docker container and the mount fails and reports are not flushed out.
Any workaround for this
**To Reproduce**

**Expected behavior**

**Screenshots**

**Software versions**
 - ZAP: [note that we typically only support the latest version of ZAP]
 - Add-on: Name and version [e.g. Passive Scan Rules Alpha v19. https://www.zaproxy.org/faq/how-do-i-see-what-version-of-an-add-on-extension-i-have-installed/]
 - OS: [e.g. Windows 10]
 - Java: [e.g. openjdk version "1.8.0_171"]
 - Browser: [e.g. chrome 66, firefox 59, safari 11.1]

**Errors from the zap.log file**
See https://www.zaproxy.org/faq/what-is-the-default-directory-that-zap-uses/ for the location of the zap.log file for your OS.

**Additional context**

**Would you like to help fix this issue?**
Just say if you'd like to try and help fix this issue. We'll provide any advice and guidance you need.

**Comment by psiinon** [comment]
Why is the mount failing? What error does it give?
At the moment it sounds like that is your problem rather than anything to do with ZAP.

**Comment by palok86** [comment]
The report doesn't get pushed to the mounted volume as jenkins is running in a docker container.

**Comment by palok86** [comment]
Is there any way to directly access the reports in the zap container

**Comment by kingthorin** [comment]
> Why is the mount failing? What error does it give?

**Comment by palok86** [comment]
error is not there as such..scan works fine as i can see in console but report is not pushed to PWD.

**Comment by thc202** [comment]
Could you provide the whole error message?

**Comment by palok86** [comment]
**Logs:**
+ docker run --user 0:0 -v /tmp/workspace/xxxx/APPSEC/Owasp-Zap/Zap-demo/out:/zap/wrk/:rw -t xxxxxxxxxxxxxxxxx:xxxxx/owasp/zap2docker-stable zap-full-scan.py -t http://172.17.0.2:8080/bodgeit -r test_zap_report1.html -J test_zap_report1.json
2020-03-27 05:06:14,950 Params: ['zap-x.sh', '-daemon', '-port', '42910', '-host', '0.0.0.0', '-config', 'api.disablekey=true', '-config', 'api.addrs.addr.name=.*', '-config', 'api.addrs.addr.regex=true', '-config', 'spider.maxDuration=0', '-addonupdate', '-addoninstall', 'pscanrulesBeta', '-addoninstall', 'ascanrulesBeta']
Mar 27, 2020 5:06:17 AM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
[Fatal Error] :1:1013: The element type "hr" must be terminated by the matching end-tag "</hr>".
[Fatal Error] :1:1027: The element type "hr" must be terminated by the matching end-tag "</hr>".
Total of 776 URLs
PASS: Directory Browsing [0]
PASS: Cookie Without Secure Flag [10011]
PASS: Incomplete or No Cache-control and Pragma HTTP Header Set [10015]
PASS: Cross-Domain JavaScript Source File Inclusion [10017]
PASS: Information Disclosure - Sensitive Information in URL [10024]
PASS: Information Disclosure - Sensitive Info








WARN-NEW: Insecure HTTP Method - PUT [90028] x 332 
	http://172.17.0.2:8080/bodgeit/images/129.png/uy8ngsrsxz (403 Forbidden)
	http://172.17.0.2:8080/bodgeit/images/h3vn4jd39n (403 Forbidden)
	http://172.17.0.2:8080/bodgeit/images/130.png/ud4tjply4k (403 Forbidden)
	http://172.17.0.2:8080/bodgeit/images/151.png/0ydj1uobvs (403 Forbidden)
	http://172.17.0.2:8080/bodgeit/images/154.png/vnu8185x5o (403 Forbidden)
FAIL-NEW: 0	FAIL-INPROG: 0	WARN-NEW: 25	WARN-INPROG: 0	INFO: 0	IGNORE: 0	PASS: 80
+ true
+ echo DEBUG - Finding all files 'in' workspace
DEBUG - Finding all files in workspace
+ find /tmp/workspace/RITS/APPSEC/Owasp-Zap/Zap-demo
/tmp/workspace/RITS/APPSEC/Owasp-Zap/Zap-demo
/tmp/workspace/RITS/APPSEC/Owasp-Zap/Zap-demo/.git
/tmp/workspace/RITS/APPSEC/Owasp-Zap/Zap-demo/.git/branches
/tmp/workspace/RITS/APPSEC/Owasp-Zap/Zap-demo/.git/description
/tmp/workspace/RITS/APPSEC/Owasp-Zap/Zap-demo/.git/hooks
/tmp/workspace/RITS/APPSEC/Owasp-Zap/Zap-demo/.git/hooks/applypatch-msg.sample
/tmp/workspace/RITS/APPSEC/Owasp-Zap/Zap-demo/.git/hooks/commit-msg.sample
/tmp/workspace/RITS/APPSEC/Owasp-Zap/Zap-demo/.git/hooks/post-update.sample
/tmp/workspace/RITS/APPSEC/Owasp-Zap/Zap-demo/.git/hooks/pre-applypatch.sample
/tmp/workspace/RITS/APPSEC/Owasp-Zap/Zap-demo/.git/hooks/pre-commit.sample
/tmp/workspace/RITS/APPSEC/Owasp-Zap/Zap-demo/.git/hooks/pre-push.sample
/tmp/workspace/RITS/APPSEC/Owasp-Zap/Zap-demo/.git/hooks/pre-rebase.sample
/tmp/workspace/RITS/APPSEC/Owasp-Zap/Zap-demo/.git/hooks/pre-receive.sample
/tmp/workspace/RITS/APPSEC/Owasp-Zap/Zap-demo/.git/hooks/prepare-commit-msg.sample
/tmp/workspace/RITS/APPSEC/Owasp-Zap/Zap-demo/.git/hooks/update.sample
/tmp/workspace/RITS/APPSEC/Owasp-Zap/Zap-demo/.git/hooks/pre-merge-commit.sample
/tmp/workspace/RITS/APPSEC/Owasp-Zap/Zap-demo/.git/info
/tmp/workspace/RITS/APPSEC/Owasp-Zap/Zap-demo/.git/info/exclude
/tmp/workspace/RITS/APPSEC/Owasp-Zap/Zap-demo/.git/refs
/tmp/workspace/RITS/APPSEC/Owasp-Zap/Zap-demo/.git/refs/heads
/tmp/workspace/RITS/APPSEC/Owasp-Zap/Zap-demo/.git/refs/tags
/tmp/workspace/RITS/APPSEC/Owasp-Zap/Zap-demo/.git/refs/remotes

/tmp/workspace/RITS/APPSEC/Owasp-Zap/Zap-demo/.git/logs/HEAD
/tmp/workspace/RITS/APPSEC/Owasp-Zap/Zap-demo/.git/index
/tmp/workspace/RITS/APPSEC/Owasp-Zap/Zap-demo/aquasec-api-test.groovy
/tmp/workspace/RITS/APPSEC/Owasp-Zap/Zap-demo/deploy-aqua-csp.groovy
/tmp/workspace/RITS/APPSEC/Owasp-Zap/Zap-demo/deploy-aqua-enforcers.groovy
/tmp/workspace/RITS/APPSEC/Owasp-Zap/Zap-demo/deploy-aqua-scanner.groovy
/tmp/workspace/RITS/APPSEC/Owasp-Zap/Zap-demo/deploy-enforcers.groovy
/tmp/workspace/RITS/APPSEC/Owasp-Zap/Zap-demo/fortify-install-pipeline-lib.groovy
/tmp/workspace/RITS/APPSEC/Owasp-Zap/Zap-demo/nexus-api-test.groovy
/tmp/workspace/RITS/APPSEC/Owasp-Zap/Zap-demo/remove-aqua-csp.groovy
/tmp/workspace/RITS/APPSEC/Owasp-Zap/Zap-demo/remove-aqua-enforcers.groovy
/tmp/workspace/RITS/APPSEC/Owasp-Zap/Zap-demo/remove-aqua-scanner.groovy
/tmp/workspace/RITS/APPSEC/Owasp-Zap/Zap-demo/sca-docker-image-maven.groovy
/tmp/workspace/RITS/APPSEC/Owasp-Zap/Zap-demo/sca-docker-image.groovy
/tmp/workspace/RITS/APPSEC/Owasp-Zap/Zap-demo/sensitive_info_scan.groovy
/tmp/workspace/RITS/APPSEC/Owasp-Zap/Zap-demo/vault-test-api.groovy
/tmp/workspace/RITS/APPSEC/Owasp-Zap/Zap-demo/zap-demo.groovy
/tmp/workspace/RITS/APPSEC/Owasp-Zap/Zap-demo/out
+ cd /tmp/workspace/RITS/APPSEC/Owasp-Zap/Zap-demo/out
+ ls -alh
total 4K     
drwxrwxrwx    2 root     root           6 Mar 27 05:06 .
drwxr-xr-x    4 root     root        4.0K Mar 27 05:06 ..
+ cd ..
+ test -f /tmp/workspace/RITS/APPSEC/Owasp-Zap/Zap-demo/out/zap_scan_report.html
+ echo 'zap_scan_report.html not found!'
zap_scan_report.html not found!
+ exit 1

there is no permission issue as such but the report is not pushed out.

**Comment by palok86** [comment]
test -d ${PWD}/out               && docker run --user $(id -u):$(id -g) -v $(pwd)/out:/zap/wrk/test_zap_report1.json:rw -t docker-rits-devsecops-csec-local.pruregistry.intranet.asia:8443/owasp/zap2docker-stable zap-full-scan.py  -t http://172.17.0.2:8080/bodgeit -r test_zap_report1.html -J test_zap_report1.json || true
             
             echo DEBUG - Finding all files in workspace
             find $PWD
             cd $PWD/out
             ls -alh
             cd ..
              if test -f ${PWD}/out/zap_scan_report.html; then
              mv ${PWD}/out/zap_scan_report.html ${PWD}
              rm -rf ${PWD}/out
              echo DEBUG - Finding all files in workspace
              find $PWD
              exit 0
            else
              echo "zap_scan_report.html not found!"
              exit 1

this is my complete command

**Comment by gnirlos** [comment]
This seems eerily similar to to the problem that I asked about on the [google group](https://groups.google.com/forum/#!topic/zaproxy-users/WYjFiejjaQQ) yesterday.

In short, when running the docker container in a Jenkins pipeline, the scan report is not generated although the zap logfile is generated.

**Comment by cy4n** [comment]
pretty sure this is a problem around volumes related to the docker-in-docker setup. 
@palok86 do you mount the docker.sock from host into the jenkins agent container? this way you would tell the dockerd on the host to use its (host's) filesystem to mount it to the zap container volume

**Comment by palok86** [comment]
Hi, Thanks for your response.
I moved my setup from Docker in Docker to Docker on VM and issue got resolved.

Thanks

**Comment by kingthorin** [comment]
Thanks for letting us know.
