### ISSUE TITLE
How can I authenticate into the application used Azure DevOps extension? 

### ISSUE THREAD

**Issue by Joshwa15** [zaproxy/zaproxy#5917]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Would you like to help implementing this feature?**
Just say if you'd like to try and help implementing this feature. We'll provide any advice and guidance you need.

**Comment by kingthorin** [comment]
Please don't ask questions as issues, especially when providing zero details - the ZAP User Group https://groups.google.com/group/zaproxy-users is a much better place for questions.

If you’re asking about a third party components such as the Jenkins plugin or VSTS plugin please look for their preferred support mechanism as these were not created by and are not supported by the core team.
