### ISSUE TITLE
Skipped plugin TestSQLInjection with imported Context

### ISSUE THREAD

**Issue by Satya318** [zaproxy/zaproxy#5918]
TestSQLInjection works fine for the context if it is run via ZAP UI, but fails if the same context is run via JAVA client API. After digging so much, it is found that in the class file TestSQLInjection, the method  `public boolean targets(TechSet technologies)` uses `==` operator to compare two objects rather than `equals()` i.e `tech.getParent() == Tech.Db` which causes the validation fail and so, skipping the plugin.

**Comment by thc202** [comment]
Are you importing a context?

**Comment by Satya318** [comment]
> Are you importing a context?
Yes, in both JAVA client API as well as via UI. But in UI , it works fine.

**Comment by thc202** [comment]
Thanks, this also happens with the UI if you cancel the Session Properties dialogue shown after importing the context (as it ends up using different `Tech` instances, like when imported through the ZAP API).
