### ISSUE TITLE
FALSE2TRUE

### ISSUE THREAD

**Issue by w3b-mani4k** [zaproxy/zaproxy#5925]
Hi. It would be cool to add a "match and replace" function or plugin.
This means that ZAP could change responses and server headers.
For more information about this function, follow these links:
1) https://www.jonbottarini.com/2019/06/17/using-burp-suite-match-and-replace-settings-to-escalate-your-user-privileges-and-find-hidden-features/
2) https://web.archive.org/web/20191216140248/https://matthewsetter.com/write-burp-suite-match-and-replace-rules/
3) https://web.archive.org/web/20200106113815/https://matthewsetter.com/introduction-to-burp-suite/

**Comment by thc202** [comment]
I believe this is already available with Replacer add-on (https://www.zaproxy.org/docs/desktop/addons/replacer/) and scripting.

**Comment by psiinon** [comment]
Agreed, those 2 ways should cover all cases.
