### ISSUE TITLE
zap-full-scan.py and zap-api-scan.py do not support "-I" command line option

### ISSUE THREAD

**Issue by gnirlos** [zaproxy/zaproxy#5928]
zap-baseline.py includes this option:
 -I                do not return failure on warning

zap-full-scan.py and zap-api-scan.py do not.  This requires trapping for the return code upon completion of the script.  Instead, a similar command line option should exist in the other two scripts.

I'm not fluent in python (or github, for that matter), but it looks like it could be as simple as duplicating the three lines of code used in zap-baseline.py that set the "ignore-warn" flag.

...unless there's a reason why this option doesn't exist...

**Comment by psiinon** [comment]
Yeah, looks like an omission, and should be an easy fix :)
