### ISSUE TITLE
ContentSecurityPolicyScanner does not handle multiple CSP headers properly

### ISSUE THREAD

**Issue by rogheden** [zaproxy/zaproxy#5931]
It seems there are some bugs in the zap CSP plugin.
https://github.com/zaproxy/zap-extensions/blob/a2f7c391a0ff5b274363500bff1dc40fa37c87ab/addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ContentSecurityPolicyScanner.java

The plugin does not handle multiple headers correctly.
Looking at the source (line 129) we found this nugget which explains the `1:100: Expecting end of policy but found ","` CSP failure we are seeing in ZAP reports.
String policyText = cspOptions.toString().replace("[", "").replace("]", "");
The code uses toString() on a list of header values, removes the brackets but leaves the commas in the policy string causing the “Expecting end of policy…” error.

When removing the 2nd CSP header that problem goes away but is replaced with a warning instead about missing directive which is expected since they are now not sent.

**Comment by kingthorin** [comment]
For the record this is a known issue that's documented in the source you linked 😉 

https://github.com/zaproxy/zap-extensions/blob/a2f7c391a0ff5b274363500bff1dc40fa37c87ab/addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ContentSecurityPolicyScanner.java#L45-L46
```java
 * <p>TODO: Add handling for multiple CSP headers TODO: Add handling for CSP via META tag See
 * https://github.com/shapesecurity/salvation/issues/149 for info on combining CSP policies
```

**Comment by kingthorin** [comment]
@rogheden if you upgrade to v28 of the Passive Scan Rules Release release addon this issue should be addressed.

**Comment by kingthorin** [comment]
Announced: https://twitter.com/kingthorin_rm/status/1247901507619409920
