### ISSUE TITLE
OpenAPI API import might return before completely importing everything

### ISSUE THREAD

**Issue by shervyna** [zaproxy/zaproxy#5936]
**Describe the bug**
When I only have one url defined in my openAPI definition and I execute:
```
docker run -v {some_path}:/zap/wrk/:rw \
-t owasp/zap2docker-weekly zap-api-scan.py \
-t openapi.json \
-f openapi \
-r zapReport.html
```
I sometimes get this noURLsException:

![image](https://user-images.githubusercontent.com/19234081/79108872-d41f7d80-7da9-11ea-8d2d-b4396a7745a1.png)
(...logs in the middle omitted...)
![image](https://user-images.githubusercontent.com/19234081/79108890-dda8e580-7da9-11ea-90f5-3e5352399119.png)
and it ends by scan nothing as the screenshot above.

However, if I execute the same command again, sometimes it is able to get the url and successfully scan it.
![image](https://user-images.githubusercontent.com/19234081/79109339-bbfc2e00-7daa-11ea-93b3-2baeb576b2dd.png)

Then if I have 2 urls or above in my openAPi definition file, this issue will not happen.

Here is my openAPI definition:
```
{
    "openapi": "3.0.1",
    "info": {
        "title": "xxx",
        "description": "xxx",
        "version": "1.0"
    },
    "servers": [
        {
            "url": "http://localhost:7071/api"
        }
    ],
    "paths": {
        "/user": {
            "get": {
                "summary": "user",
                "operationId": "get-user",
                "parameters": [
                    {
                        "name": "name",
                        "in": "query",
                        "description": "name of the user",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": null
                    }
                }
            }
        }
    },
    "components": {
        "securitySchemes": {
            "apiKeyHeader": {
                "type": "apiKey",
                "name": "Ocp-Apim-Subscription-Key",
                "in": "header"
            },
            "apiKeyQuery": {
                "type": "apiKey",
                "name": "subscription-key",
                "in": "query"
            }
        }
    },
    "security": [
        {
            "apiKeyHeader": []
        },
        {
            "apiKeyQuery": []
        }
    ]
}
```
**Expected behavior**
ZAP should be able to get the url from openapi definition file even if there is only one url.

**Software versions**
 - ZAP: owasp/zap2docker-weekly
 - OS: MacOS Mojave 10.14.5

**Comment by thc202** [comment]
If you are able to reproduce the issue consistently could you run with `-d` and attach the logs when it fails and runs successfully?

**Comment by shervyna** [comment]
The logs are pretty long so I put the logs in separate files here:
[zap api scan_failed_logs.log](https://github.com/zaproxy/zaproxy/files/4468950/zap.api.scan_failed_logs.log)
[zap api scan_success_logs.log](https://github.com/zaproxy/zaproxy/files/4468951/zap.api.scan_success_logs.log)

**Comment by palok86** [comment]
Facing the same issue..
