### ISSUE TITLE
Ajax Spider Context

### ISSUE THREAD

**Issue by khalil2535** [zaproxy/zaproxy#5937]
**Describe the bug**
When i opened ajax spider i noticed there is an additional empty choice in contexts ComboBox.

**Expected behavior**
To view just the real contexts.

**Screenshots**
![image](https://user-images.githubusercontent.com/26520106/79182917-b76e5e80-7e18-11ea-9e4c-084aa9b86f92.png)

**Software versions**
Last weekly release.

**Comment by psiinon** [comment]
Thats by design. You might want to compare running the ajax spider with the context defined and without it.
