### ISSUE TITLE
The swing ui looks to ugly, replace swing code into javafx or web ui ?

### ISSUE THREAD

**Issue by ihexon** [zaproxy/zaproxy#5941]
any plans to rewrite old interface with new framework like webui or javafx ?

**Comment by kingthorin** [comment]
There is a web UI available, checkout the HUD.

- https://owasp.org/2019/07/02/ZAP-HUD
- https://www.zaproxy.org/docs/desktop/addons/hud/

As for a rewrite we have a FAQ just for that: https://www.zaproxy.org/faq/why-dont-you-rewrite-zap-in-my-favorite-language/
