### ISSUE TITLE
Question: XML Report only shows Failures - how do we show PASS too?

### ISSUE THREAD

**Issue by jjburr** [zaproxy/zaproxy#5947]
Hi
We are using ZAP docker in our release pipeline for security testing and we upload the XML report into AzureDevOps in NUnit.

However the report only shows failures - anyway to show passes in the XML report as well as failures?

The docker container executes the zap-baseline.py, could not see any args for passes

**Comment by kingthorin** [comment]
That's not currently supported. Seems like a duplicate of https://github.com/zaproxy/zaproxy/issues/5155
