### ISSUE TITLE
ZAP ajax-spider cannot crawl single page application and active scan cannot scan directly referenced pages.

### ISSUE THREAD

**Issue by bartoszbinda** [zaproxy/zaproxy#5949]
Hello, I have following problem with ZAP. AJAX-Spider cannot crawl pages SPAs. Even if I have manually added this sites like /logout to the URLs within Active Scan, Active Scan will return 404 error. However, if I go to the same pages using Firefox proxy and do a hard refresh by ctrl+f5 on every URL and manually clicks on the links, they will be added to the active scan and they will be scanned. I don't understand whether it is fault on my site and not configuring ZAP or there is a bug within zap.

1. Go to https://github.com/JavaInUse/angular-login and https://www.javainuse.com/zip/spring/boot/SpringBootHelloWorld-ang.rar and set them up
2. Set up AJAX-Spider on localhost:4200 
Login:javainuse password:password
Following ZEST Script was used to log in
```json
{
  "about": "This is a Zest script. For more details about Zest visit https://developer.mozilla.org/en-US/docs/Zest",
  "zestVersion": "0.8",
  "title": "login_local",
  "description": "",
  "prefix": "",
  "type": "StandAlone",
  "parameters": {
    "tokenStart": "{{",
    "tokenEnd": "}}",
    "tokens": {},
    "elementType": "ZestVariables"
  },
  "statements": [
    {
      "windowHandle": "win",
      "browserType": "chrome",
      "url": "http://localhost:4200/login",
      "capabilities": "",
      "headless": true,
      "index": 1,
      "enabled": true,
      "elementType": "ZestClientLaunch"
    },
    {
      "value": "javainuse",
      "windowHandle": "win",
      "type": "name",
      "element": "username",
      "index": 2,
      "enabled": true,
      "elementType": "ZestClientElementSendKeys"
    },
    {
      "value": "password",
      "windowHandle": "win",
      "type": "name",
      "element": "password",
      "index": 3,
      "enabled": true,
      "elementType": "ZestClientElementSendKeys"
    },
    {
      "windowHandle": "win",
      "type": "tagname",
      "element": "button",
      "index": 4,
      "enabled": true,
      "elementType": "ZestClientElementClick"
    }
  ],
  "authentication": [],
  "index": 0,
  "enabled": true,
  "elementType": "ZestScript"
}
```
3. See that only main page is added.
4. Add manually   'http://localhost:4200/addemployee',
  'http://localhost:4200/logout' to the sites.
5. See that active scan on the results in 404.
6. Configure proxy to use firefox browser. (Up to date versions of Firefox require setting "network.proxy.allow_hijacking_localhost" to "true" in about:config.)
7. Go to localhost:4200 and after log in to the hard refresh (ctrl+f5) on every URL (in incognito/private mode refresh will be enough)
8. Manually click on links. See that they are added to the sites in ZAP.
9. Run scan on them.

I have expected that every dynamic link: /logout and /addEmployee will be added by AJAX-Spider and be scanned by active scan.

**Software versions**
```text
OWASP ZAP
Version: 2.9.0
---
Installed Add-ons: [[id=alertFilters, version=10.0.0],
[id=ascanrules, version=34.0.0], [id=bruteforce,
version=9.0.0], [id=communityScripts, version=9.0.0],
[id=custompayloads, version=0.9.0], [id=diff,
version=10.0.0], [id=directorylistv1, version=4.0.0],
[id=fuzz, version=12.0.0], [id=gettingStarted,
version=11.0.0], [id=help, version=10.0.0], [id=hud,
version=0.10.0], [id=importurls, version=7.0.0], [id=invoke,
version=10.0.0], [id=onlineMenu, version=7.0.0],
[id=openapi, version=15.0.0], [id=pscanrules,
version=28.0.0], [id=quickstart, version=28.0.0],
[id=replacer, version=8.0.0], [id=reveal, version=3.0.0],
[id=saverawmessage, version=5.0.0], [id=savexmlmessage,
version=0.1.0], [id=scripts, version=26.0.0], [id=selenium,
version=15.2.0], [id=spiderAjax, version=23.1.0], [id=tips,
version=7.0.0], [id=webdrivermacos, version=16.0.0],
[id=websocket, version=21.0.0], [id=zest, version=32.0.0]]
---
Operating System: Mac OS X
Java Version: AdoptOpenJDK 1.8.0_232
System's Locale: pl_PL
Display Locale: en_GB
Format Locale: en_GB
ZAP Home Directory: /Users/batinex/Library/Application Support/ZAP/
ZAP Installation Directory: /Applications/OWASP ZAP.app/Contents/Java/./
Look and Feel: Mac OS X (com.apple.laf.AquaLookAndFeel)
```

<sub>Edited by @kingthorin, formatting.</sub>

**Comment by psiinon** [comment]
Please dont raise these sort of things as issues. Issues are for enhancement requests or clear cases where there a bug in ZAP.
There might be a bug in ZAP but at this stage its not clear.
The user group https://groups.google.com/group/zaproxy-users is a much better forum for this.
