### ISSUE TITLE
Stats includes Content-Type byteranges limits

### ISSUE THREAD

**Issue by sonawanesarvesh** [zaproxy/zaproxy#5952]
In wappalyzer API the results are crossing byteranges limits

**"stats.contentType.multipart/byteranges; boundary=00000000000000000018": 2,**  

![JSON ERROR](https://user-images.githubusercontent.com/52656580/80349401-d3e4af00-888c-11ea-9961-8628df8e0264.PNG)

**Comment by sonawanesarvesh** [comment]
One suggestion - 

Check sample - 
1. stats.contentType.text/plain; charset=utf-8
2. stats.contentType.text/html

Can we eliminate the special characters?

**Comment by psiinon** [comment]
Oops - this looks like a but in the core stats - we probably shouldnt include the boundry part..

**Comment by thc202** [comment]
Title updated.

**Comment by sonawanesarvesh** [comment]
Hello, any updates?

**Comment by kingthorin** [comment]
Nope. Would you like to tackle the issue? (We can provide advice/guidance.)

**Comment by sonawanesarvesh** [comment]
@kingthorin 
Yes sure, i will be happy, please share the details, i will try to get some solution

**Comment by thc202** [comment]
The Content-Type stats are being recorded in `StatsPassiveScanner`:
https://github.com/zaproxy/zaproxy/blob/da0467f2e55c98d16d355cb6ad3e475f79e642b2/zap/src/main/java/org/zaproxy/zap/extension/pscan/scanner/StatsPassiveScanner.java#L55-L58
