### ISSUE TITLE
XSS false positive

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#5958]
As per https://security.stackexchange.com/questions/230635/is-non-executed-content-still-considered-xss
The report shows: `path/contacts.php?search=John%3Balert%281%29`
The attack is reflected in the page as `var search = "John;alert(1)";`
Another example from manual testing: `?search=John";alert(1);`
Reflected as `var search = "John&quot;;alert(1);";`

I think we should be able to detect this case and not report it, but will need to double check the code and make sure we can come up with a simple test case.

**Comment by theamanrawat** [comment]
@psiinon , If no one is working on this issue then Can I work on this issue?

**Comment by psiinon** [comment]
@theamanrawat please do! I've assigned it to you.
If you need any help with it then just as here :)

**Comment by theamanrawat** [comment]
Single change in code solved this problem and Now it's not reporting when reflection is like this.

```javascript
var name = "aman&quot;;alert(1);"
```

But I'm getting error while running unit test saying `Unresolved references` in ascanrules.gradle.kts.
