### ISSUE TITLE
Update owasp.org references

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#5962]
All of the alerts refer to the old OWASP site. Some of them work, others dont.
In any case it would be good to change them to point to the new site over time.
Luckily they are easy to pull out from the website repo:

- [ ] 10009.md:* https://www.owasp.org/index.php/Testing_for_Error_Code_(OTG-ERR-001)
- [ ] 10010.md:* http://www.owasp.org/index.php/HttpOnly
- [ ] 10011.md:* http://www.owasp.org/index.php/Testing_for_cookies_attributes_(OWASP-SM-002)
- [ ] 10015.md:* https://www.owasp.org/index.php/Session_Management_Cheat_Sheet#Web_Content_Caching
- [ ] 10016.md:* https://www.owasp.org/index.php/XSS_(Cross_Site_Scripting)_Prevention_Cheat_Sheet
- [ ] 10021.md:* https://www.owasp.org/index.php/List_of_useful_HTTP_headers
- [ ] 10028.md:* https://www.owasp.org/index.php/Open_redirect
- [ ] 10028.md:* https://owasp.org/index.php/Top_10_2010-A10-Unvalidated_Redirects_and_Forwards
- [ ] 10035.md:* https://www.owasp.org/index.php/HTTP_Strict_Transport_Security
- [ ] 10035.md:* https://www.owasp.org/index.php/List_of_useful_HTTP_headers
- [ ] 10038.md:* https://www.owasp.org/index.php/Content_Security_Policy
- [ ] 10040.md:* https://www.owasp.org/index.php/Transport_Layer_Protection_Cheat_Sheet
- [ ] 10047.md:* https://www.owasp.org/index.php/HTTP_Strict_Transport_Security
- [ ] 10047.md:* https://www.owasp.org/index.php/List_of_useful_HTTP_headers
- [ ] 10057.md:* https://www.owasp.org/index.php/Top_10_2013-A4-Insecure_Direct_Object_References
- [ ] 10057.md:* https://www.owasp.org/index.php/Testing_for_Insecure_Direct_Object_References_(OTG-AUTHZ-004)
- [ ] 10094.md:* https://www.owasp.org/index.php/Top_10_2013-A6-Sensitive_Data_Exposure
- [ ] 10095.md:* https://wiki.owasp.org/index.php/Review_Old,_Backup_and_Unreferenced_Files_for_Sensitive_Information_(OTG-CONFIG-004)
- [ ] 10096.md:* https://www.owasp.org/index.php/Top_10_2013-A6-Sensitive_Data_Exposure
- [ ] 10097.md:* https://www.owasp.org/index.php/Top_10_2013-A6-Sensitive_Data_Exposure
- [ ] 10104.md:* https://www.owasp.org/index.php/Web_Application_Security_Testing_Cheat_Sheet
- [ ] 10106.md:* https://www.owasp.org/index.php/Transport_Layer_Protection_Cheat_Sheet
- [ ] 10106.md:* https://www.owasp.org/index.php/SSL_Best_Practices
- [ ] 10108.md:* https://www.owasp.org/index.php/Reverse_Tabnabbing
- [ ] 30001.md:* https://www.owasp.org/index.php/Buffer_overflow_attack
- [ ] 30002.md:* https://www.owasp.org/index.php/Format_string_attack
- [ ] 30003.md:* https://www.owasp.org/index.php/Integer_overflow and http://projects.webappsec.org/w/page/13246946/Integer%20Overflows.
- [ ] 40013.md:* https://www.owasp.org/index.php/Top_10_2010-A3-Broken_Authentication_and_Session_Management
- [ ] 40013.md:* https://www.owasp.org/index.php/Session_fixation
- [ ] 40013.md:* https://www.owasp.org/index.php/Top_10_2010-A9
- [ ] 40015.md:* https://www.owasp.org/index.php/Top_10_2010-A9
- [ ] 40015.md:* https://www.owasp.org/index.php/LDAP_injection
- [ ] 40018.md:* https://www.owasp.org/index.php/Top_10_2010-A1
- [ ] 40018.md:* https://www.owasp.org/index.php/SQL_Injection_Prevention_Cheat_Sheet
- [ ] 40019.md:* https://www.owasp.org/index.php/Top_10_2010-A1
- [ ] 40019.md:* https://www.owasp.org/index.php/SQL_Injection_Prevention_Cheat_Sheet
- [ ] 40020.md:* https://www.owasp.org/index.php/Top_10_2010-A1
- [ ] 40020.md:* https://www.owasp.org/index.php/SQL_Injection_Prevention_Cheat_Sheet
- [ ] 40021.md:* https://www.owasp.org/index.php/Top_10_2010-A1
- [ ] 40021.md:* https://www.owasp.org/index.php/SQL_Injection_Prevention_Cheat_Sheet
- [ ] 40022.md:* https://www.owasp.org/index.php/Top_10_2010-A1
- [ ] 40022.md:* https://www.owasp.org/index.php/SQL_Injection_Prevention_Cheat_Sheet
- [ ] 40023.md:* https://www.owasp.org/index.php/Testing_for_user_enumeration_%28OWASP-AT-002%29
- [ ] 40024.md:* https://www.owasp.org/index.php/Top_10_2010-A1
- [ ] 40024.md:* https://www.owasp.org/index.php/SQL_Injection_Prevention_Cheat_Sheet
- [ ] 40027.md:* https://www.owasp.org/index.php/Top_10_2010-A1
- [ ] 40027.md:* https://www.owasp.org/index.php/SQL_Injection_Prevention_Cheat_Sheet
- [ ] 90018.md:* https://www.owasp.org/index.php/Top_10_2010-A1
- [ ] 90018.md:* https://www.owasp.org/index.php/SQL_Injection_Prevention_Cheat_Sheet
- [ ] 90019.md:* https://www.owasp.org/index.php/Direct_Dynamic_Code_Evaluation_('Eval_Injection')
- [ ] 90020.md:* https://www.owasp.org/index.php/Command_Injection
- [ ] 90025.md:* https://www.owasp.org/index.php/Expression_Language_Injection
- [ ] 90033.md:* https://www.owasp.org/index.php/Testing_for_cookies_attributes_(OTG-SESS-002)

Might be worth sorting these so we can focus on the ones that 404...

**Comment by kingthorin** [comment]
|Original|Replacement|
|----------|----------|
|https://www.owasp.org/index.php/Testing_for_Error_Code_(OTG-ERR-001)|https://owasp.org/www-project-web-security-testing-guide/v41/4-Web_Application_Security_Testing/08-Testing_for_Error_Handling/|
|http://www.owasp.org/index.php/HttpOnly|https://owasp.org/www-community/HttpOnly|
|http://www.owasp.org/index.php/Testing_for_cookies_attributes_(OWASP-SM-002)|https://owasp.org/www-project-web-security-testing-guide/v41/4-Web_Application_Security_Testing/06-Session_Management_Testing/02-Testing_for_Cookies_Attributes.html|
|https://www.owasp.org/index.php/Session_Management_Cheat_Sheet#Web_Content_Caching|https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html#web-content-caching|
|https://www.owasp.org/index.php/XSS_(Cross_Site_Scripting)_Prevention_Cheat_Sheet|https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html|
|https://www.owasp.org/index.php/List_of_useful_HTTP_headers|https://owasp.org/www-community/Security_Headers|
|https://www.owasp.org/index.php/Open_redirect|https://cheatsheetseries.owasp.org/cheatsheets/Unvalidated_Redirects_and_Forwards_Cheat_Sheet.html|
|https://owasp.org/index.php/Top_10_2010-A10-Unvalidated_Redirects_and_Forwards|https://cheatsheetseries.owasp.org/cheatsheets/Unvalidated_Redirects_and_Forwards_Cheat_Sheet.html|
|https://www.owasp.org/index.php/HTTP_Strict_Transport_Security|https://cheatsheetseries.owasp.org/cheatsheets/HTTP_Strict_Transport_Security_Cheat_Sheet.html|
|https://www.owasp.org/index.php/Content_Security_Policy|https://cheatsheetseries.owasp.org/cheatsheets/Content_Security_Policy_Cheat_Sheet.html|
|https://www.owasp.org/index.php/Transport_Layer_Protection_Cheat_Sheet|https://cheatsheetseries.owasp.org/cheatsheets/Transport_Layer_Protection_Cheat_Sheet.html|
|https://www.owasp.org/index.php/Top_10_2013-A4-Insecure_Direct_Object_References|https://wiki.owasp.org/index.php/Top_10_2013-A4-Insecure_Direct_Object_References|
|https://www.owasp.org/index.php/Testing_for_Insecure_Direct_Object_References_(OTG-AUTHZ-004)|https://owasp.org/www-project-web-security-testing-guide/v41/4-Web_Application_Security_Testing/05-Authorization_Testing/04-Testing_for_Insecure_Direct_Object_References.html|
|https://www.owasp.org/index.php/Top_10_2013-A6-Sensitive_Data_Exposure|https://wiki.owasp.org/index.php/Top_10_2013-A6-Sensitive_Data_Exposure
|https://wiki.owasp.org/index.php/Review_Old,_Backup_and_Unreferenced_Files_for_Sensitive_Information_(OTG-CONFIG-004)|https://owasp.org/www-project-web-security-testing-guide/v41/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/04-Review_Old_Backup_and_Unreferenced_Files_for_Sensitive_Information.html|
|https://www.owasp.org/index.php/Web_Application_Security_Testing_Cheat_Sheet|https://owasp.org/wstg|
|https://www.owasp.org/index.php/SSL_Best_Practices|https://cheatsheetseries.owasp.org/cheatsheets/Transport_Layer_Protection_Cheat_Sheet.html|
|https://www.owasp.org/index.php/Reverse_Tabnabbing|https://owasp.org/www-community/attacks/Reverse_Tabnabbing|
|https://www.owasp.org/index.php/Buffer_overflow_attack|https://owasp.org/www-community/attacks/Buffer_overflow_attack|
|https://www.owasp.org/index.php/Format_string_attack|https://owasp.org/www-community/attacks/Format_string_attack|
|https://www.owasp.org/index.php/Integer_overflow and http://projects.webappsec.org/w/page/13246946/Integer%20Overflows.|Drop first link, fix resource file?|
|https://www.owasp.org/index.php/Top_10_2010-A3-Broken_Authentication_and_Session_Management|https://owasp.org/www-project-top-ten/OWASP_Top_Ten_2017/Top_10-2017_A2-Broken_Authentication|
|https://www.owasp.org/index.php/Session_fixation|https://owasp.org/www-community/attacks/Session_fixation|
|https://www.owasp.org/index.php/Top_10_2010-A9|https://wiki.owasp.org/index.php/Top_10_2010-A9-Insufficient_Transport_Layer_Protection|
|https://www.owasp.org/index.php/LDAP_injection|https://owasp.org/www-community/attacks/LDAP_Injection|
|https://www.owasp.org/index.php/Top_10_2010-A1|https://owasp.org/www-project-top-ten/OWASP_Top_Ten_2017/Top_10-2017_A1-Injection|
|https://www.owasp.org/index.php/SQL_Injection_Prevention_Cheat_Sheet|https://cheatsheetseries.owasp.org/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.html|
|https://www.owasp.org/index.php/Testing_for_user_enumeration_%28OWASP-AT-002%29|https://owasp.org/www-project-web-security-testing-guide/v41/4-Web_Application_Security_Testing/03-Identity_Management_Testing/04-Testing_for_Account_Enumeration_and_Guessable_User_Account.html|
|https://www.owasp.org/index.php/Direct_Dynamic_Code_Evaluation_('Eval_Injection')|https://owasp.org/www-community/attacks/Direct_Dynamic_Code_Evaluation_Eval%20Injection|
|https://www.owasp.org/index.php/Command_Injection|https://owasp.org/www-community/attacks/Command_Injection|
|https://www.owasp.org/index.php/Expression_Language_Injection|https://owasp.org/www-community/vulnerabilities/Expression_Language_Injection|
|https://www.owasp.org/index.php/Testing_for_cookies_attributes_(OTG-SESS-002)|https://owasp.org/www-project-web-security-testing-guide/v41/4-Web_Application_Security_Testing/06-Session_Management_Testing/02-Testing_for_Cookies_Attributes.html|

**Comment by kingthorin** [comment]
Note 10016 was deprecated and therefore https://www.owasp.org/index.php/XSS_(Cross_Site_Scripting)_Prevention_Cheat_Sheet is not a concern.
