### ISSUE TITLE
API to apply alert filters to alerts that are already generated.

### ISSUE THREAD

**Issue by Dileep17** [zaproxy/zaproxy#5966]
**Is your feature request related to a problem? Please describe.**
**Current Apply Filter Plugin Behaviour**: We can create alert filter to change the alert Risk level. Alert Filter creation will not impact the alerts (alert instances) that are already generated. In ZAP UI, we have "Apply" filter button in create alert filter dialog. This will apply the alert filter to alerts that are already generated. As of now ZAP API has only create and remove alert filters. We dont have apply filter api. (plz correct if my understanding is wrong)

**Our Scenario:** We proxy our e2e tests via ZAP and we use zap api to create context/scan policy, run spider, ascan, generate reports etc etc. Now we need to generate two zap reports 
- without applying alert filters (de facto zap report with actual Risk and confidence levels) - used by the security audit teams who want the whole report without suppression 
- After applying alert filters (after suppressing false positives that are already verified in previous runs)  - used by my team who is interested in pending or new issues 

Given our application is huge, there is a huge suppression list. Manually finding the new issues in zap report is time consuming and I'm trying to solve it.

**Describe the solution you'd like**
Please create apply filter api with which we can apply alert filter to existing alerts. This option is available in UI and there will/might be use cases to use it via API too. If this API is available, one can maintain a suppression list and use this API to suppress alerts after scans are completed

**Describe alternatives you've considered**
As I need to generate two reports, we can run ZAP scan twice with and without filters. This is time consuming and I don't think this is clean solution.  For now we are parsing zap json to suppress the alerts instances maintained in our repo and generating a HTML report. Im sure this is not a sustainable solution. 

**Additional context**
This is my first feature request so plz let me know If I missed to provide any crucial information!

**Would you like to help implementing this feature?**
I wish I could say yes, I looked the repo and couldn't figure our whats happening :(

**Comment by mdem99** [comment]
Hi @Dileep17 how did you manage to solve your problem? I'm having the same trouble and need to solve it, thank you :)

**Comment by Dileep17** [comment]
@mdem99, its been a while since I worked on ZAP, previously I maintained suppression JSON and generated a custom HTML report.
