### ISSUE TITLE
Fuzzdb - AV issues following update

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#5972]
Just encountered this upon updating FuzzDB on a corporate machine:

![image](https://user-images.githubusercontent.com/7570458/81330999-e91cc300-906e-11ea-93e4-037504ab97c7.png)

Shall I run the whole extension archive through VirusTotal and just remove anything that's problematic, or do we want to migrate it to the other FuzzDB addon even though it's specifically named webbackdoors and these aren't?

**Comment by thc202** [comment]
I'm fine if they are moved to the other add-on but probably better to rename it, `FuzzDB AV Trigger`? :)
Or merge it back and add a notice to the FuzzDB add-on that can lead to AV issues... might be a whack-a-mole otherwise.

**Comment by kingthorin** [comment]
Actually if I'm the only person that's raised this so far I'm not too worried about it. I think we should leave this open for a bit and see if anyone else chimes in.

**Comment by kingthorin** [comment]
After a bit of discussion the plan is to move everything within the 'Attack' folder: https://github.com/zaproxy/zap-extensions/tree/master/addOns/fuzzdb/src/main/zapHomeFiles/fuzzers/fuzzdb/attack/

To: https://github.com/zaproxy/fuzzdb-web-backdoors, updating various help and description components, and renaming the add-on/repo.

**Comment by kingthorin** [comment]
Remaining tasks:
- Rename repo.
- Update summary info on repo.

**Comment by kingthorin** [comment]
Closing, the relevant add-ons have been released.

- fuzzdb v7
- fuzzdb-offenisive v3
