### ISSUE TITLE
/usr/bin/env: ‘python’: No such file or directory 

### ISSUE THREAD

**Issue by dfuentes77** [zaproxy/zaproxy#5978]
**Describe the bug**
Can no longer run `zap-baseline.py` from weekly container

**To Reproduce**
```
docker run -v $(pwd):/zap/wrk/:rw --rm -it owasp/zap2docker-weekly zap-baseline.py -c ci/files/alerts.conf -r baseline-report.html -t ${TEST_URL}
```
results in
```
/usr/bin/env: ‘python’: No such file or directory
```

**Expected behavior**
This worked fine for weeks now up until this morning and I noticed the weekly container build was updated `12 hours ago`:
https://hub.docker.com/r/owasp/zap2docker-weekly/tags

Verified Digest that got pulled:
`Digest: sha256:fcd93307952c5acdc3a90c0ebde59025ad508d9c87c996a30f01341864ce85a9`

**Comment by psiinon** [comment]
A new version of the weekly release has been published which includes this fix.
