### ISSUE TITLE
How to manually install the addons in docker container 

### ISSUE THREAD

**Issue by mufleh-ahmad** [zaproxy/zaproxy#5982]
Hi

I am trying to run active scan alpha and beta rules on docker, but i am having issues downloading from zap market place as company have blocked any connections to github. I managed to manually add the zap files into the following folder  /.ZAP/plugin in docker container , but zap tests fail when i run any active scan alpha or beta rules stating that the rules doesn't exist

Is there anyway i can install the addons via docker

below is the docker command i am running 

docker run -p 8090:8090 -i owasp/zap2docker-stable zap.sh -config api.disablekey=true  -daemon -port 8090 -host 0.0.0.0 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true

**Comment by kingthorin** [comment]
Please don't ask questions as issues, - the ZAP User Group https://groups.google.com/group/zaproxy-users is a much better place for questions.

If you’re asking about a third party components such as the Jenkins plugin or VSTS plugin please look for their preferred support mechanism as these were not created by and are not supported by the core team.
