### ISSUE TITLE
Incorrect package in Dockerfile-stable

### ISSUE THREAD

**Issue by cbake886** [zaproxy/zaproxy#5985]
**Describe the bug**
Dockerfile-stable is installing "python-is-python3" on [line 22](https://github.com/zaproxy/zaproxy/blob/4816c2f83e3ffc5221b3558ae927a7d04626be01/docker/Dockerfile-stable#L22) This produces the error:

```
E: Unable to locate package python-is-python3
```

And the build fails. This build file is using [Ubuntu:18.04](https://github.com/zaproxy/zaproxy/blob/4816c2f83e3ffc5221b3558ae927a7d04626be01/docker/Dockerfile-stable#L2) and that package is for Ubuntu:20.04 or as of now "Ubuntu:latest". In the [Dockerfile-live](https://github.com/zaproxy/zaproxy/blob/4816c2f83e3ffc5221b3558ae927a7d04626be01/docker/Dockerfile-live#L2) and [Dockerfile-weekly](https://github.com/zaproxy/zaproxy/blob/4816c2f83e3ffc5221b3558ae927a7d04626be01/docker/Dockerfile-weekly#L2) they are being built on Ubuntu:latest. Got to bump stable or remove package.

**To Reproduce**
1. run sudo docker build -f Dockerfile-stable .

**Expected behavior**
Docker image is built.

**Would you like to help fix this issue?**
Sure!

**Comment by thc202** [comment]
Thanks for raising the issue!

I'm +1 to bump to 20.04 and pin live/weekly versions.
