### ISSUE TITLE
ZAP - Webswing Usage not working 

### ISSUE THREAD

**Issue by WeiserAriel** [zaproxy/zaproxy#5987]
Hey All, 

I am trying to use ZAP UI to start a normal scan for some reason the UI is not opened and we i open the URL I am getting a 404 error code. these are the steps i did :

1. docker pull owasp/zap2docker-stable
2. docker run -u zap -p 8050:8050 -p 8090:8090 -i owasp/zap2docker-stable zap-webswing.sh ( i used port 8050 becuase Jenkins is already running on 8080 ).
3. firefox &
4. http://localhost:8050/zap

actual results - 404 not found.

you can see that the container is running:
# docker ps
CONTAINER ID        IMAGE                     COMMAND             CREATED              STATUS                          PORTS                                            NAMES
d6c29d24bd77        owasp/zap2docker-stable   "zap-webswing.sh"   About a minute ago   Up About a minute (unhealthy)   0.0.0.0:8050->8050/tcp, 0.0.0.0:8090->8090/tcp   infallible_bouman
[root@r-qa-security01 ~]#

Please advise,

Thanks.
Ariel.

**Comment by thc202** [comment]
You also need to change Webswing's Jetty properties file ((under `/zap/webswing/jetty.properties`) to use that port, e.g.: `org.webswing.server.http.port=8050`

**Comment by WeiserAriel** [comment]
Thanks for the quick comment.

I don't see the directory ? are you sure it's the right path? 
ll /zap/webswing/jetty.properties
ls: cannot access '/zap/webswing/jetty.properties': No such file or directory

[root@r-qa-security01 zap]# cd /
[root@r-qa-security01 /]# find -name jetty.properties
./var/lib/docker/overlay2/d842a44f1ad42fed13a8160e06ad6325344905487b1288df8b18ee005afbdc5a/merged/zap/webswing/jetty.properties
./var/lib/docker/overlay2/6d2df38f02355bb646be2bbd9c4c15bc089049e18b7b380b884685dad18d32fa/diff/zap/webswing/jetty.properties
./var/lib/docker/overlay2/2642675daab3456a3091dca61933951b30f6a92293d8a5a529568478b89a8942/diff/zap/webswing/jetty.properties

**Comment by thc202** [comment]
Hmm, I think you can just map 8050 to 8080 (`-p 8050:8080`) instead of changing the properties file (it is in the container).

**Comment by WeiserAriel** [comment]
You are the man ! :) 👍
