### ISSUE TITLE
Question about Authentication via GUI/Docker CLI

### ISSUE THREAD

**Issue by WeiserAriel** [zaproxy/zaproxy#5988]
Hey Guys,

I successfully deploy the docker on my server and i am trying to run 'active scan'.
in order to scan all my website pages, I need to authenticate as admin user ( here the problem starts ).
This website was built long time ago and it seems like a it uses a really odd authentication. 

1.AFAIU the user directed to the login page where he needs to write 'Username & Password'. 
2. once he does it a GET requests has sent with 'X-Requested-With: XMLHttpRequest' with Basic Authentication  header .

for example:
GET /ufmRest/app/users HTTP/1.1
Host: 10.209.26.42
Connection: keep-alive
Pragma: no-cache
Authorization: Basic YWRtaW46MTIzNDU2
Content-Type: application/json
Accept: application/json, text/plain, */*
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36
Cache-Control: no-cache
X-Requested-With: XMLHttpRequest
Expires: Sat, 01 Jan 2000 00:00:00 GMT
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: https://10.209.26.42/ufm_web/
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,he;q=0.8,it;q=0.7,es;q=0.6

3. the server validate the Basic authentication (base64) and redicerct the user to dashboard page if successdud.
4. from now on all requests are sent with Basic Authentication header which are validated in each requests.

Questions:

a. how do i make an authentication manually with docker?( in order to run a scan)
b. how do i do an authentication with the cli ? ( in order to run a scan)

Hope it's clear. let me know if you have any questions.

Thanks,
Ariel.

**Comment by kingthorin** [comment]
Please don't ask questions as issues,  the ZAP User Group https://groups.google.com/group/zaproxy-users is a much better place for questions.

If you’re asking about a third party components such as the Jenkins plugin or VSTS plugin please look for their preferred support mechanism as these were not created by and are not supported by the core team.
