### ISSUE TITLE
ZAPs CA Root certificate has expired

### ISSUE THREAD

**Issue by gemal** [zaproxy/zaproxy#5990]
![image](https://user-images.githubusercontent.com/69105/81947187-8bedb800-9600-11ea-9a26-21a4a38496e2.png)

using latest version 2.9.0

**Comment by psiinon** [comment]
Thats your ZAP Root CA.
Regenerate it.
https://www.zaproxy.org/docs/desktop/ui/dialogs/options/dynsslcert/

**Comment by rsshilli** [comment]
If only that documentation told me the steps to regenerate the cert. It just tells me that I have to do it, but doesn't tell me the steps? Surely there's better documentation somewhere.

**Comment by thc202** [comment]
Click the Generate button.

**Comment by rsshilli** [comment]
@thc202 I updated my comment for the next poor soul so they can find that magical "Generate" button. That's pretty buried.

**Comment by andrewcoylesagecom** [comment]
@thc202 Excellent, thank you.

**Comment by kingthorin** [comment]
Also, 2.9.0 isn’t latest. You should upgrade to 2.10.0.
