### ISSUE TITLE
Fuzzer does not run when using rockyou.txt

### ISSUE THREAD

**Issue by man715** [zaproxy/zaproxy#6002]
When I try to use the rockyou.txt (134M) in Kali 2020.2 the fuzzer never starts. I have tried to load that list in two ways: 1.)Attack>Fuzz>File 2.) Options>Fuzzer>Add custom Fuzz file
When I attempt to load the file using option 1, I get the following error: An error occurred while calculating the number of payloads. That might be caused by incorrect character encoding. The file will still be processed." Using option 2 does not give me an error; however, it does not start the Fuzz.

There are no log entries when I attempt to load the list into ZAP, and the only entries when I try to run the Fuzzer is Fuzzer started and Fuzzer completed:
```
2020-05-21 13:46:56,235 [AWT-EventQueue-0] INFO  HttpFuzzer - Fuzzer started...
2020-05-21 13:46:56,246 [ZAP-FuzzerTerminationNotifier-0] INFO  HttpFuzzer - Fuzzer completed.
```
This has been brought up before [here:](https://github.com/zaproxy/zaproxy/issues/4106); however it did not get resolved as there was no response from the OP for a year.

ZAP Version: 2.9.0
OS Kali 2020.2
Java openjdk 11.0.7-ea 2020-04-14

Please let me know if you need any further diagnostic information, and explain how I can obtain that information. 

Thank you.

**Comment by man715** [comment]
This is appears to not be a ZAP issue but an issue with the wordlist. When I run file -i on rockyou.txt it says the charset is utf-8; however, when I try to read the file in a mousepad in Kali, it fails to open with an  "The document was not UTF-8 valid" error.
running the following command appears to fix the issue: 
`iconv -f iso-8859-15 -t utf8 rockyou.txt > fixed.txt`

**Comment by psiinon** [comment]
Thanks for letting us know.
