### ISSUE TITLE
Do not recompile unchanged scripts

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#6010]
As per https://groups.google.com/d/msg/zaproxy-users/uC7m6Jak8g4/oZaR8SGgAgAJ jython scripts are slow to start.
This is because we recompile then each time, even if they havnt changed.
Caching the compiled scripts should significantly speed them up and hopefully not take up too much space. We could always keep a non default option for not caching them?

**Comment by thc202** [comment]
Removed the add-on label and tweaked the title to not be language specific, all of them benefit from this change which can be provided by core.
