### ISSUE TITLE
API shutdown is killing all zap instances 

### ISSUE THREAD

**Issue by Pepitoh** [zaproxy/zaproxy#6012]
**Describe the bug**
Hi everyone. I discovered a problematic bug when using multiple instance of zap on a same machine. When I have 2 distinct instances running on the same machine (using amazing python API / and let's say baseline script from docker), when one of the scan is finished, the call of zap.core.shutdown() leads to the crash of the second scan (on the other instance) : API seems not to be reachable by the second scans whereas it is not the same port / instance used. 
>020-05-27 15:38:27,718 Records to passive scan : 19
/zap/zap-x.sh: 10: kill: No such process
2020-05-27 15:38:29,722 Starting new HTTP connection (1): localhost:55402
ERROR HTTPConnectionPool(host='localhost', port=55402): Max retries exceeded with url: http://zap/JSON/pscan/view/recordsToScan/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f74342a7a58>: Failed to establish a new connection: [Errno 111] Connection refused',)))
2020-05-27 15:38:29,722 I/O error: HTTPConnectionPool(host='localhost', port=55402): Max retries exceeded with url: http://zap/JSON/pscan/view/recordsToScan/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f74342a7a58>: Failed to establish a new connection: [Errno 111] Connection refused',)))
`

**To Reproduce**
1. Lauch a first scan : `python3 zap-baseline.py -t https://xxx.com -J report.json -d`
2. On a second bash, launch a concurrent scan : `python3 zap-baseline.py -t https://www.zzz.com -J report2.json -d`
3. Wait for one scan to finish
4. When
>http://localhost:45084` "GET http://zap/JSON/core/action/shutdown/?apikey= HTTP/1.1" 200 15

is triggered on the first scan to finish, the second one will crash with the error mentionned previously (Connection Refused). 

**Expected behavior**
The `api.core.shutdown()` should only kill the concern instance of zap, and let others in peace 😄. It seems to see a normal behaviour of shutdown control API as the commentary indicated "servers" in plurial "
>/** Override inherited shutdown to add stopping proxy servers. */" 

from Control.JAVA, but is there any way of only killing the called instance from API?

**Screenshots**
![image](https://user-images.githubusercontent.com/15944951/83112377-5d72e100-a0c6-11ea-94fd-3ca556f00967.png)

**Software versions**
 - ZAP: last version from docker-weekly
- Add on : Wappalizer
 - OS:  Debian I think (Docker one).
 - Java: from docker
 - Browser: N/A

**Errors from the zap.log file**
**Scan 1** : first to finish : 
`http://localhost:45084` "GET http://zap/JSON/core/action/shutdown/?apikey= HTTP/1.1" 200 15`
**Scan 2 ** : crashed
>020-05-27 15:38:27,718 Records to passive scan : 19
/zap/zap-x.sh: 10: kill: No such process
2020-05-27 15:38:29,722 Starting new HTTP connection (1): localhost:55402
ERROR HTTPConnectionPool(host='localhost', port=55402): Max retries exceeded with url: http://zap/JSON/pscan/view/recordsToScan/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f74342a7a58>: Failed to establish a new connection: [Errno 111] Connection refused',)))
2020-05-27 15:38:29,722 I/O error: HTTPConnectionPool(host='localhost', port=55402): Max retries exceeded with url: http://zap/JSON/pscan/view/recordsToScan/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f74342a7a58>: Failed to establish a new connection: [Errno 111] Connection refused',)))
``

**Would you like to help fix this issue?**
Why not ! 😃 .

Tanks a lot !
Pepitoh

**Comment by psiinon** [comment]
Are you running the 2 scans in the same docker image?
If so then you'll need to run them in different directories otherwise they'll use the same db - that will cause all sorts of problems.

**Comment by thc202** [comment]
You're killing me...

More seriously, I don't think it's the API shutdown stopping (or killing) both ZAP instances, they use different JVM instances/processes each with their own proxies.
I suspect the problem is with the `zap-x.sh` script killing Xfvb, which for some reason ends up killing ZAP. If I comment the `kill` then both ZAP instances terminate normally. Could you try that as well?

**Comment by thc202** [comment]
@Pepitoh were you able to try the above?

**Comment by Pepitoh** [comment]
Hi, 
Sorry for my response time.
You wereright!, the zap-x.sh was responsible of the killing of xfvb and then both instance were terminated, it makes indeed more sense than my first guest. 
 Thanks a lot for your help on the subjects.
