### ISSUE TITLE
Deprecate bit.ly update check

### ISSUE THREAD

**Issue by hazcod** [zaproxy/zaproxy#6016]
**Is your feature request related to a problem? Please describe.**
The fact that ZAP hides the update URL behind a bit.ly domain is suspicious to the user.
Ideally it should reach out to the github-admin repo directly, allowing users to whitelist that domain only and not the whole bit.ly domain, decreasing attack surface.

**Describe the solution you'd like**
Download the update XML straight from github.

**Describe alternatives you've considered**
Whitelisting bit.ly, which I am uncomfortable with.

**Comment by hazcod** [comment]
@psiinon mentioned the requirement for usage statistics.

**Comment by psiinon** [comment]
We need usage stats, and this is one of the few ways we can get them.
All of the calls home are documented on https://www.zaproxy.org/faq/what-calls-home-does-zap-make/
So if theres no way to keep getting these stats then this is a non starter.
We could set up a heroku app or similar, but then we'd just have the same problem but with a different domain wouldnt we?

**Comment by kingthorin** [comment]
You can always append a `+` to the end of a bitly link to see where it goes (ex: https://bitly.com/owaspzap-2-9-0+)

Also all of the links ZAP uses (currently) use the form `https://bit.ly/owaspzap*` so they're easily attributable.

**Comment by psiinon** [comment]
It looks like heroku support custom domains, so we _could_ create a suitable heroku app and create a domain like cfu.zaproxy.org ? https://medium.com/@ethanryan/setting-up-a-custom-domain-for-your-heroku-hosted-app-6c011e75aa3d

**Comment by hazcod** [comment]
@kingthorin : FYI most client firewalls only upport filtering on domain & port.
@psiinon : that would be excellent!

**Comment by kingthorin** [comment]
Understood, was just providing details/alternatives.

**Comment by psiinon** [comment]
And I can see why this is pain, but its not high up on my priority list right now I'm afraid. Way too many things a higher priority as far as I'm concerned.

**Comment by hazcod** [comment]
Another possibility is switching the domain behind the free Cloudflare CDN.
Offers you free CDN caching & analytics.
https://www.cloudflare.com/analytics/

**Comment by psiinon** [comment]
We're actually already using cloudflare!
I'll have a look to see what it looks like :)

**Comment by psiinon** [comment]
Just looked, but I cant see the per page requests. Thats the main thing I want from analytic - how many people visited which pages and ideally which geographic region they are connecting from.
Things like the device types and browsers they use (high level) are useful but not essential.
Am I missing something?

**Comment by psiinon** [comment]
This is somewhat related to https://github.com/zaproxy/zaproxy-website/issues/133 - if we could find a good non invasive way to track zaproxy.org page views then the CFU xml files could live on there, especially as we have the infrastructure to maintain them already set up.

**Comment by psiinon** [comment]
We are now working on implementing our own services to replace our use of bitly :)
