### ISSUE TITLE
Chrome driver is not working in ZAP 2.9.0

### ISSUE THREAD

**Issue by ankitloud** [zaproxy/zaproxy#6018]
I am using ZAP 2.9.0 and when I gives my website name and click on Launch browser --> chrome (under manual exposer) my browser opens up and close immediately. I am using chrome latest version 83.0.4103.61 (Official Build) (64-bit) . It works fine with mozilla but my entire automation is built around chrome browser so I want to use zap in chrome browser only. few days before it was working fine. I am not sure which was the last working chrome version.

**Comment by thc202** [comment]
You'll have to update to the latest version of WebDriver add-on, that should support that Chrome version.

**Comment by ankitloud** [comment]
Yes I have downloaded the lastest driver from website and now it is launching.
