### ISSUE TITLE
Incorrect JavaDoc

### ISSUE THREAD

**Issue by panthap2** [zaproxy/zaproxy#6020]
This comment is inconsistent: https://github.com/zaproxy/zaproxy/blob/3a1164d46e368d2353b0b664484afa23c746b008/zap/src/main/java/org/parosproxy/paros/extension/option/OptionsConnectionPanel.java#L736

- [x] The return type of the getTxtProxyChainPassword() method is JPasswordField rather than ZapTextField. (Done in https://github.com/zaproxy/zaproxy/pull/6021)

**Comment by thc202** [comment]
Tweaked the title to be generic, there are many cases where the JavaDoc is not correct.
