### ISSUE TITLE
Add option to display 'Sites' and 'Alerts

### ISSUE THREAD

**Issue by bleepnetworks** [zaproxy/zaproxy#6024]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Would you like to help implementing this feature?**
Just say if you'd like to try and help implementing this feature. We'll provide any advice and guidance you need.

**Comment by kingthorin** [comment]
ZAP already displays sites and alerts.
