### ISSUE TITLE
What are the levels of risk of OWASP ZAP?

### ISSUE THREAD

**Issue by yyosioka** [zaproxy/zaproxy#6027]
Reviewing the 「ZAP scanning report」, the following four levels of risk "High, Medium, Low and Informational
Could you please tell me what criteria are used to divide them into two categories?

**Comment by psiinon** [comment]
Please dont ask questions as issues.
The ZAP User Group is a much better place for them: https://groups.google.com/group/zaproxy-users

**Comment by yyosioka** [comment]
https://groups.google.com/group/zaproxy- ... users
Close to confirm.

**Comment by thc202** [comment]
For the record, the list is open for anyone to post (you might need to join first) or send an email.

The question was posted in https://groups.google.com/d/topic/zaproxy-users/KgmmlouTRfA/discussion
