### ISSUE TITLE
PathTraversal False positive

### ISSUE THREAD

**Issue by zakrush** [zaproxy/zaproxy#6030]
Hello.

ZAP set alert **Path Traversal** if see timezone in respose.
So I get very much alert where response  is contain
`"timezone": "Europe/Moscow"`,

Search in the response by patterns '\' or '/' get only timezone parameter.

**Comment by kingthorin** [comment]
Please provide the full alert details as well as the response message associated with the alert.

**Comment by zakrush** [comment]
Response body into Attach.
Some details of allert. 
![image](https://user-images.githubusercontent.com/33844164/84086657-0daee680-a9f1-11ea-809e-a5f171530caa.png)

[response_PAth_traversal.txt](https://github.com/zaproxy/zaproxy/files/4748909/response_PAth_traversal.txt)
