### ISSUE TITLE
Anti-CSRF Token Refresher not working properly with "Follow Redirects"

### ISSUE THREAD

**Issue by SkypLabs** [zaproxy/zaproxy#6032]
**Describe the bug**

When using the Fuzzer on the login page of [Bludit CMS](https://www.bludit.com/) to brute-force credentials within the context of a CTF, I realised that the "Anti-CSRF Token Refresher" message processor was not working as I expected due to 301 redirections.

When submitting credentials from the login page, Bludit CMS redirects the user either on the dashboard page in case of success or on the login page again if it failed to authenticate the user. If I don't tell the Fuzzer to follow redirections, the Anti-CSRF Token Refresher won't be able to capture the new token for the next attempt, which is the expected behaviour. However, if I do configure the Fuzzer to follow redirections, it only tries to grab the token from the first server's response which is the 301 redirection and of course fails. I expected the Fuzzer to wait for the redirection to complete in order to capture the new token before moving forward.

One way to get around this issue was to configure a "Delay when fuzzing" but of course it is not optimal as either I lose time between my brute-forcing attempts or I miss some anti-CSRF tokens.

**To Reproduce**

Steps to reproduce the behaviour:

1. Go to the login page of a Bludit CMS instance and try to connect to it with random credentials.
2. Add `tokenCSRF` to the list of anti-CSRF tokens: `Tools` > `Options` > `Anti-CSRF Tokens` > `Add` > Enter `tokenCSRF` and click on `Add`.
3. Right click on the POST request from the `History` tab, select `Attack` and then `Fuzz...`.
4. Select the value of `username` and add a payload to it.
5. Repeat step 4 for `password`.
6. Make sure `Anti-CSRF Token Refresher` in present in the `Message Processor` tab.
7. Enable `Follow Redirects` in the `Options` tab.
8. Click on `Start Fuzzer`.

**Expected behaviour**

I expect the Fuzzer to wait for the redirection to complete in order to capture the new token before moving forward.

**Screenshots**

![Screenshot from 2020-06-09 18-02-41](https://user-images.githubusercontent.com/9932586/84179599-1c8faa80-aa7e-11ea-9639-c7d283204f88.png)

**Software versions**

 - ZAP: 2.9.0
 - Add-on: AdvFuzzer 12.0.0
 - OS: Kali Linux, Rolling version
 - Java: Debian 11.0.7-ea
 - Browser: Firefox Quantum 68.8.0esr (64-bit)

Support info:

```
OWASP ZAP
Version: 2.9.0
---
Installed Add-ons: [[id=accessControl, version=5.0.0],
[id=alertFilters, version=10.0.0], [id=alertReport,
version=14.0.0], [id=ascanrules, version=35.0.0],
[id=ascanrulesAlpha, version=28.0.0], [id=ascanrulesBeta,
version=28.0.0], [id=attacksurfacedetector, version=1.1.4],
[id=browserView, version=5.0.0], [id=bruteforce,
version=9.0.0], [id=callgraph, version=4.0.0], [id=cmss,
version=2.0.0], [id=commonlib, version=1.0.0],
[id=communityScripts, version=9.0.0], [id=coreLang,
version=13.0.0], [id=cspscanner, version=6.0.0],
[id=custompayloads, version=0.9.0], [id=diff,
version=10.0.0], [id=directorylistv1, version=4.0.0],
[id=directorylistv2_3, version=3.0.0],
[id=directorylistv2_3_lc, version=3.0.0], [id=domxss,
version=9.0.0], [id=formhandler, version=2.0.0], [id=fuzz,
version=12.0.0], [id=fuzzdb, version=6.0.0],
[id=fuzzdbwebbackdoors, version=2.0.0], [id=gettingStarted,
version=11.0.0], [id=help, version=10.0.0], [id=httpsInfo,
version=12.0.0], [id=hud, version=0.10.0],
[id=imagelocationscanner, version=1.0.0], [id=importurls,
version=7.0.0], [id=invoke, version=10.0.0], [id=jsonview,
version=1.0.0], [id=jxbrowser, version=12.0.0],
[id=jxbrowserlinux64, version=10.0.0], [id=jython,
version=10.0.0], [id=onlineMenu, version=7.0.0],
[id=openapi, version=15.0.0], [id=pscanrules,
version=29.0.0], [id=pscanrulesAlpha, version=27.0.0],
[id=pscanrulesBeta, version=22.0.0], [id=quickstart,
version=28.0.0], [id=regextester, version=1.0.0],
[id=replacer, version=8.0.0], [id=requester, version=3.0.0],
[id=reveal, version=3.0.0], [id=revisit, version=3.0.0],
[id=saml, version=8.0.0], [id=saverawmessage,
version=5.0.0], [id=savexmlmessage, version=0.1.0],
[id=scripts, version=26.0.0], [id=selenium, version=15.2.0],
[id=spiderAjax, version=23.1.0], [id=sqliplugin,
version=13.0.0], [id=sse, version=9.0.0], [id=svndigger,
version=3.0.0], [id=tips, version=7.0.0], [id=tlsdebug,
version=3.0.0], [id=tokengen, version=13.0.0],
[id=treetools, version=7.0.0], [id=viewstate,
version=1.0.0], [id=vulncheck, version=1.0.0],
[id=wappalyzer, version=18.0.0], [id=webdriverlinux,
version=18.0.0], [id=websocket, version=21.0.0], [id=zest,
version=32.0.0]]
---
Operating System: Linux
Java Version: Debian 11.0.7-ea
System's Locale: en_IE
Display Locale: en_GB
Format Locale: en_IE
ZAP Home Directory: /home/skyper/.ZAP/
ZAP Installation Directory: /usr/share/zaproxy/./
Look and Feel: Nimbus (javax.swing.plaf.nimbus.NimbusLookAndFeel)
```

**Errors from the zap.log file**

N/A.

**Additional context**

None.

**Would you like to help fix this issue?**

Yes!

**Comment by thc202** [comment]
> I expect the Fuzzer to wait for the redirection to complete in order to capture the new token before moving forward.

The token is obtained before the fuzzed message is sent as it needs to be injected into the message, it seems more a problem with concurrency. How many threads are configured?

**Comment by SkypLabs** [comment]
> How many threads are configured?

I used 10 concurrent scanning threads.

**Comment by thc202** [comment]
Did you try reduce the number of the threads (or even use just one, just to make sure the problem is unrelated to the redirection)?

**Comment by kingthorin** [comment]
> Did you try reduce the number of the threads (or even use just one, just to make sure the problem is unrelated to the redirection)?

If you didn't, could you? :wink:

**Comment by SkypLabs** [comment]
> Did you try reduce the number of the threads (or even use just one, just to make sure the problem is unrelated to the redirection)?

No because I didn't think it could come from a concurrency issue. It thought the fuzzer's internal logic was flawed.

> If you didn't, could you? :wink:

I just did and it seems that you were right as the attached export from the fuzzer can attest: [fuzzer-1-thread-bludit-login-bruteforce.csv.txt](https://github.com/zaproxy/zaproxy/files/4754472/fuzzer-1-thread-bludit-login-bruteforce.csv.txt)

As a reminder, a response body of 2,467 bytes means that the token sent to the server was correct.

**Comment by kingthorin** [comment]
Closing per previous response. The issue was threading vs the specific target.

**Comment by SkypLabs** [comment]
> Closing per previous response. The issue was threading vs the specific target.

So you think it was a target-specific behaviour? No such threading issue has been observed in the past with ZAP? I haven't tested the same setup on another target.
