### ISSUE TITLE
Spider: implement a breadth first option

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#6034]
As per https://groups.google.com/d/msg/zaproxy-users/w1oGjJqDI54/n0QM7VPkBQAJ

**Comment by fraber** [comment]
Hi Karan,

I'm the guy who initiated this feature request. I'm the founder of ]project-open[, a pretty large (>1000 pages) Web application, that we tried to security-test using ZAP. This did not work out, as described above.

I'm not a ZAP expert, but I know quite a bit about large Web application in general (I've come across a bunch of other large business apps in the past, including ERP systems etc.). I would be available for testing your extension.

After doing some successful testing, I'd like to write-up a blog entry or magazine article on how to test large apps using ZAP, featuring this work. 

I believe there is a big need for tools capable of testing large apps...


Cheers
Frank

**Comment by preetkaran20** [comment]
@fraber Sure. Will connect with you once i have done the changes.

thanks,
Karan

**Comment by preetkaran20** [comment]
Hi @fraber ,

I have gone through the entire conversation and i think that the same can be achieved with the max depth parameter of the spider. As you are looking to crawl few levels of the application so i think that can be done easily with the max depth parameter. https://www.zaproxy.org/docs/desktop/ui/dialogs/options/spider/

please correct me if i missed something.

thanks,
Karan

**Comment by preetkaran20** [comment]
Also my understanding after reading code is:
say there is a graph like below:
![graph](https://user-images.githubusercontent.com/13570884/91792554-68905c80-ec33-11ea-88ed-e58190d63482.png)

Here say 7,5 and 3 are initial seed then what will happen in code is all three are given to thread executor which has a queue
now queue will have 7,5,3

once 7 node is processed then all the child of 7 are again given to thread executor which adds it to queue so now queue will have 5,3,11,8
and now child of 5 is processed and so on,

if we look at it closely i think this is a BFS with little distorted reason being some nodes are returned faster than others and because of multithreaded execution.

@kingthorin @thc202 @psiinon please correct me if i understood this code wrong or you have something else in mind.

**Comment by fraber** [comment]
Hi @preetkaran20,

> max depth parameter

This could be a workaround. @psiinon already proposed this in the original thread.

However, with a true breadth-first spider you would be able to "just start" ZAP on a Web app and coverage would just increase with every additional hour you'd run it.

But I agree.

Thanks
Frank

**Comment by preetkaran20** [comment]
@fraber 
No no i think you need not to increase the max depth parameter as it looks like it is working Breadth-first only. Waiting for simon's confirmation.

**Comment by thc202** [comment]
Currently the URLs are processed as they are found, which might result in depth, breadth, or a mix of both. It depends when the URLs are found and what they are (siblings vs children).

**Comment by preetkaran20** [comment]
> Currently the URLs are processed as they are found, which might result in depth, breadth, or a mix of both. It depends when the URLs are found and what they are (siblings vs children).
> 
I think, Even if they are processed as they are found but one node's processing only adds the children to the queue so on the whole if we look it looks like BFS. If Siblings are processed very slow then DFS chances are there but if all nodes are taking almost same time then it will result in BFS.

**Comment by preetkaran20** [comment]
@thc202 @kingthorin @psiinon @fraber can we close this issue ?

thanks,
Karan

**Comment by psiinon** [comment]
Closing as it looks like this will not provide much benefit to anyone.

**Comment by fraber** [comment]
Hi!

I understand that this request ist closed, as the max_depth option is a reasonable workaround. It will work for us.

However, I would argue that depth-first search is **never** a good search strategy in large systems with many parameters, as I believe that most Web applications are.

Anyway, thanks a lot for your effort!
Frank
