### ISSUE TITLE
Add Reflect - 3rd party add-on

### ISSUE THREAD

**Issue by cak** [zaproxy/zaproxy#6035]
**Add-on repo**
https://github.com/TypeError/reflect

**Your contact details**
Email: cak@derail.io 
Website: https://derail.io

**Are you one of the authors**
Yes

**Licence**
Apache License 2.0

**Build instructions**
`gradle build`

**Link to more information**
N/A

**Twitter handle for tool or author(s)**
OptionalValue

**Promote to Beta or Release?**
Note that all new add-ons start at Alpha status.

**Anything else we should know**
Thanks for everything!

**Comment by kingthorin** [comment]
https://github.com/TypeError/reflect/releases/tag/0.0.8
