### ISSUE TITLE
Allow Parsing of Some Non-text Messages by the Spider

### ISSUE THREAD

**Issue by ricekot** [zaproxy/zaproxy#6038]
**Is your feature request related to a problem? Please describe.**
 For the GraphQl addOn, I added a spider check for ".graphql" at the end of a URL to check if it is a schema. However, the Github graphql schema ( can be found here https://developer.github.com/v4/public_schema/ ) contains the "Content-type: application/octet-stream" in the response header, so it is not parsed by the spider.

**Describe the solution you'd like**
Some non-text messages which pass spider checks of add-ons are allowed to be parsed.

**Additional context**
thc202 suggested on IRC, 

>Maybe query custom filters before the default one(?).The filter is happening in DefaultParseFilter (which uses HttpResponseHeader#isText). 

>We should probably allow to configure what's considered text in the DefaultParseFilter (but we really don't want allow all octet-stream, just if we know how to parse it)

**Would you like to help implementing this feature?**
Yes

**Comment by thc202** [comment]
I'd suggest the following changes:
 - Call the default filter after the custom filters, if all custom filters return `NOT_FILTERED`;
 - Introduce a new filter result (e.g. `WANTED`) to signal that a parser wants to parse it. (A custom filter can still filter out a resource even if other custom filter wants to parse it  to allow custom restrictions, e.g. max depth.)
