### ISSUE TITLE
OpenAPI Import Choose File Dialog appears behind OpenAPI Import dialog

### ISSUE THREAD

**Issue by davewichers** [zaproxy/zaproxy#6041]
**Describe the bug**
File selection dialog appears underneath the dialog invoking it. This is minor, but hopefully easy to fix. And I don't know if this behavior is Mac specific or not.

**To Reproduce**
1. Click on 'Import --> Import an OpenAPI definition from the local file system'
2. Click on 'Choose File'
3. File selection dialog opens up behind the 'Import OpenAPI Definition from File' dialog

**Expected behavior**
Seems like it should open up on top of the Import dialog.

**Software versions**
 - ZAP: 2.9.0
 - OS: MacOS 10.15.5
 - Java: openjdk version "1.8.0_232"

**Comment by davewichers** [comment]
I'm actually NOT seeing this bad behavior when using the ZAP weekly - D-2020-06-15. I see you pushed a code change to fix this, but maybe it was already fixed?

**Comment by thc202** [comment]
I don't think it was, that code was not changed after 2.9.0 (I guess the issue does not happen always, it doesn't here, might depend on the window manager mood).
