### ISSUE TITLE
OpenAPI add-on doesn't support Cookie parameters

### ISSUE THREAD

**Issue by davewichers** [zaproxy/zaproxy#6045]
**Describe the bug**
openapi supports cookie parameters via "in: cookie". But the ZAP openapi extension doesn't honor that. It does support "in: header", as I tested both.

**To Reproduce**
Import an openapi spec that includes something like:
```yaml
   /pathtraver-00/BenchmarkTest00001:
    post:
      summary: Ask something, get something back.
      operationId: doPost
      parameters:
      - name: BenchmarkTest00001
        in: cookie
        required: true
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            text/html: {}
```
And then test it, and see that no: cookie header with a cookie named BenchmarkTest00001 is added to the request.

**Expected behavior**
When I tested "in: header" the zap extension adds this to the request:
BenchmarkTest00005: "John Doe"

For the above example "in: cookie", I'd expect to see something like:
Cookie: BenchmarkTest00001=JohnDoe

In the generated HTTP request.

**Software versions**
 - ZAP: Latest ZAP weekly.
 - Add-on: openapi
 - OS: MacOS X
 - Java: openjdk version "1.8.0_232"

I've attached the openapi.yaml file I was using for the testing against OWASP Benchmark. which defines 3 REST endpoints. 2 work (custom header, and POST body params), but the custom cookie doesn't work.  You can use this file to test yourself against the current OWASP Benchmark in the master branch on github.
[openapi.yaml.txt](https://github.com/zaproxy/zaproxy/files/4806565/openapi.yaml.txt)

**Comment by davewichers** [comment]
Any chance you can knock this out quickly like you did #6041 and #6042?

**Comment by davewichers** [comment]
OK. I tested this, and while it is better, it still doesn't work properly, because rather than generating:
Cookie: BenchmarkTest00001=JohnDoe    as I suggested, it generates:
Cookie: BenchmarkTest00005: "John Doe"

And a space is an ILLEGAL character in a cookie value.

If you read this: https://curl.se/rfc/cookie_spec.html (which is SUPER old), it says:

Set-Cookie: NAME=VALUE; expires=DATE;
path=PATH; domain=DOMAIN_NAME; secure
NAME=VALUE
This string is a sequence of characters **excluding semi-colon, comma and white space**. If there is a need to place such data in the name or value, some encoding method such as URL style %XX encoding is recommended, though no encoding is defined or required.

As such, when you autogenerate a cookie value, can you comply with the cookie spec when doing so, by either eliminating the space, or using %20 in its place? And the quotes don't do anything so you can probably drop those too.

**Comment by davewichers** [comment]
@kingthorin @thc202 - Can you reopen this ticket and address the bug in the 'fix' I described in my previous comment?

**Comment by kingthorin** [comment]
I’ll see if I can get something setup this weekend to attempt to re-create.

**Comment by thc202** [comment]
Note that latest is [RFC 6265](https://tools.ietf.org/html/rfc6265).

Agree that it would be better have proper default values for the cookie, I'll take a look at that.

**Comment by davewichers** [comment]
I tested the latest fix which eliminates the space char in the value put into the cookie. Seems all good now. Thanks.
