### ISSUE TITLE
proxy down into webswing mode

### ISSUE THREAD

**Issue by zakrush** [zaproxy/zaproxy#6055]
Hello. Have some trouble with webswing ZAP.

1. I run Docker zap webswing.
`docker run --rm -v $(pwd)/zap:/home/zap -v $(pwd)/webswing/webswing.config:/zap/webswing/webswing.config -u zap -p 8080:8080 -p 8090:8090 --env ZAP_PORT=8090 --name owasp-zap -d owasp/zap2docker-stable zap-webswing.sh`
Here I experimented with webswing.config, but in this case it set as default. 
2. Go regression tests thought zap proxy
3. Run Python scripts into other docker near ZAP docker. (Script create context, policy, set threads for ascan and Doing ASCAN).
4. After 2-3 hours proxy is down. I get Error massage from python script.
`Error: HTTPConnectionPool(host='zap', port=8090): Max retries exceeded with url: http://zap/JSON/ascan/view/status/?scanId=0 (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(104, 'Connection reset by peer')))`
Docker status is **unhealthy**
![image](https://user-images.githubusercontent.com/33844164/86108772-457aec80-bacc-11ea-8c89-fe6bd321ca91.png)

5. Into zap.logs I see this error:
```
2020-06-30 01:33:14,834 [ZAP-ActiveScanner-23] ERROR SourceCodeDisclosureFileInclusion - Error scanning parameters for Source Code Disclosure: Remote host closed connection during handshake
javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
```
I see only 5 includes of this error with small time interval.
`grep -e "Error scanning parameters for Source Code Disclosure: Remote host closed connect" zap.log | wc -l
5`
First Error in 2020-06-30 01:33:14,831 and last I share upper of this alert. 

6. Also I tried do scan into headless mode of zap. This worked for more than 4 hours
7. Also I tried play with threads of ascan. It stable down throught 2-3 hours of scan.
8. I excluded variant with resources of server where ZAP is working. During time of ZAP scanning server is healthy. 
9. I caught a mistake and checked the stand. It also worked fine.
I don't have any idea where I can find trouble.

**Comment by zakrush** [comment]
{"version":"2.9.0"}

Also I use beta rules.

**Comment by psiinon** [comment]
Are you trying to set up automated security testing?
If so then I'd recommend using the ZAP API rather than webswing.

**Comment by zakrush** [comment]
@psiinon 
Yes. I trying to set up automated security testing. The final goal it use a zap.sh or zap-x.sh but into first step I need debug options, alerts and see how it working.  
Also  the using of ZAP heardless mode don't exclude problem with webswing. 

I think trouble with beta rules o other addons. all work fine before setup beta rules and other addons. I'm cheking it now.

**Comment by zakrush** [comment]
Hello. 
It was trouble in Source Code Disclosure beta active scan rule. I disable checking of Source Code Disclosure ant it working fine, now.
