### ISSUE TITLE
Illegal Reflective Access with installer

### ISSUE THREAD

**Issue by spanishdudepr** [zaproxy/zaproxy#6058]
During the install of ZAP_2_9_0 in Kali-Linux, the following warning pop-up:

Starting Installer ...
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.install4j.runtime.installer.frontend.GUIHelper (file:/home/kali/Downloads/ZAP_2_9_0_unix.sh.8668.dir/i4jruntime.jar) to field sun.awt.X11GraphicsDevice.scale
WARNING: Please consider reporting this to the maintainers of com.install4j.runtime.installer.frontend.GUIHelper
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

ZAP did install completely.

**Comment by kingthorin** [comment]
This is just a WARNING, nothing to worry about. Thanks for letting us know.

Fixes for such issues are already being tracked:
- https://github.com/zaproxy/zaproxy/issues/2602
- https://github.com/zaproxy/zaproxy/issues/5359

**Comment by thc202** [comment]
This one is actually worrisome, we don't have access to newer versions of install4j anymore (thus a fix). Reopening as we are not tracking this in other issues (unless I missed it?).

**Comment by kingthorin** [comment]
Nope,  thats a good point.
