### ISSUE TITLE
Feature Request: start/stop/remove an AJAX spider scan from API

### ISSUE THREAD

**Issue by hazcod** [zaproxy/zaproxy#6061]
**Is your feature request related to a problem? Please describe.**
Comparable to `Spider`, start/stop/remove an AJAX spider scan from API

**Comment by thc202** [comment]
Closing as duplicate of #1954 (start/stop is already supported).

**Comment by hazcod** [comment]
@thc202 can you link to the docs mentioning that?

**Comment by thc202** [comment]
https://www.zaproxy.org/docs/api/#using-ajax-spider

**Comment by hazcod** [comment]
Seem they are missing from https://github.com/zaproxy/zap-api-go/tree/master/zap

**Comment by thc202** [comment]
Right, there are several API clients that are not that well maintained (lack of maintainer mainly), although I guess we could automate the update of the generated APIs (at least that would not lag behind).
