### ISSUE TITLE
On CSRF variable detection search for partial match instead of full

### ISSUE THREAD

**Issue by DiogoMRSilva** [zaproxy/zaproxy#6068]
**Is your feature request related to a problem? Please describe.**
Many times ZAP fails to find a lot of vulnerabilities because it don't refresh the CSRF tokens, the reason for that is that the names used for CSRF vars change a lot. 

**Describe the solution you'd like**
One possible improvement is to to see if variables names contain one of the names we know/have instead of a full match between variables names and the list. With this change If we add the name CSRF to the list we will detect almost all the cases.

**Would you like to help implementing this feature?**
yes

**Comment by psiinon** [comment]
Yes, been meaning to do this for a while ;)
As you probably know the relevant code is all in https://github.com/zaproxy/zaproxy/tree/develop/zap/src/main/java/org/zaproxy/zap/extension/anticsrf
Let us know if you have any questiosn about thes, other wise just go for it :)

**Comment by thc202** [comment]
Setting this to 2.10.0, not much left.
