### ISSUE TITLE
Allow to download & upload context through the API

### ISSUE THREAD

**Issue by hazcod** [zaproxy/zaproxy#6069]
**Is your feature request related to a problem? Please describe.**
The ability to download the context file and upload to create and/or replace over the API could allow for stateful automated scans with a stateless ZAP instance for batch scanning.

**Describe the solution you'd like**
Implement a `/JSON/context/action/downloadContext/` and `/JSON/context/action/uploadContext/`.

**Describe alternatives you've considered**
The current import and exportContext calls work with the local filesystem which is impractical when working in containers.

**Comment by kingthorin** [comment]
Its export/import but it should already be there.

**Comment by kingthorin** [comment]
Couldn't/shouldn't this be handled outside ZAP? I don't see how we could handle all the possible auth options/combinations.

**Comment by thc202** [comment]
What do you mean by handle?

**Comment by kingthorin** [comment]
Well if ZAP's supposed to download from some random site/source I'd expect some sort of auth to be required.
If ZAP's supposed to upload to some random site/storage I'd expect some sort of auth to be required.

To me dealing with all the possible destinations/sources/types of storage is a headache that should be handled outside of ZAP.
