### ISSUE TITLE
False positive: "Hash Disclosure - Mac OSX salted SHA-1"

### ISSUE THREAD

**Issue by a-h** [zaproxy/zaproxy#6071]
**Describe the bug**

The string "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFFFFEE37" is present in several widely used JavaScript NPM modules:

* https://www.npmjs.com/package/ecc-jsbn - 13M weekly downloads at time of writing
* https://www.npmjs.com/package/jsrsasign - 153K weekly downloads
* https://www.npmjs.com/package/oidc-client - 119K weekly downloads

This makes it likely to occur frequently as a false positive in many Web applications where the library has been bundled into the client-side javascript.

It's part of the OWASP baseline test, and produces a medium risk item.

**To Reproduce**

Run the ZAP baseline Docker image against the ecc-jsb code.

```
docker run owasp/zap2docker-weekly zap-baseline.py -t https://raw.githubusercontent.com/aduh95/ecc-jsb
n/master/lib/sec.js
```

See unexpected error listed:

```
...
WARN-NEW: Hash Disclosure - Mac OSX salted SHA-1 [10097] x 10
        https://raw.githubusercontent.com/aduh95/ecc-jsbn/master/lib/sec.js (200 OK)
        https://raw.githubusercontent.com/aduh95/ecc-jsbn/master/lib/sec.js (200 OK)
        https://raw.githubusercontent.com/aduh95/ecc-jsbn/master/lib/sec.js (200 OK)
        https://raw.githubusercontent.com/aduh95/ecc-jsbn/master/lib/sec.js (200 OK)
        https://raw.githubusercontent.com/aduh95/ecc-jsbn/master/lib/sec.js (200 OK)
...
FAIL-NEW: 0     FAIL-INPROG: 0  WARN-NEW: 3     WARN-INPROG: 0  INFO: 0 IGNORE: 0       PASS: 49
```

**Expected behavior**

Expected not to see these values listed as a Mac OSX salted SHA-1 hash.

**Software versions**
 - ZAP: Docker image owasp/zap2docker-weekly (0e0266a1c3aa)
 - OS: Linux (N/A)

**Would you like to help fix this issue?**

Sure, I'll help if I can.

**Comment by kingthorin** [comment]
It seems this collides with a crypto curve identifier, so this along with others are likely to be encountered.

We could:
1. Look for preceding `0x`. (Might not be sufficient for the majority of cases.)
1. Add a set of constants for the curve identifiers and raise matching alerts with lower confidence. (Or even exclude them at High Threshold.)
1. Other.

**Comment by kingthorin** [comment]
@psiinon @thc202 @ricekot any thoughts on this?

**Comment by psiinon** [comment]
We could always ignore JS files unless a Low threshold is used.
I would expect "interesting" hash disclosures to occur in HTML rather than JavaScript.
Thoughts?

**Comment by kingthorin** [comment]
Sure I’d be good with that.
