### ISSUE TITLE
Garbled UI after Fuzzer runs for a while

### ISSUE THREAD

**Issue by wadim-al** [zaproxy/zaproxy#6072]
**Describe the bug**
After Fuzzer is started and left for a while, interacting with all other UI in the app is broken. Submenus and every other control in the window starts to redraw incorrectly. Multiple copies of the previous drawn windows is drawn at incorrect positions

**To Reproduce**
Prerequisites:
Freshly installed Windows 10 2004 x64, latest official Java runtime x32 and x64.
1. Install ZAP 2.9.0 or 2020-06-08 weekly build
2. Start fuzzer
3. Leave it for 5 minutes
4. Start interacting everywhere in the app - open submenus, change tabs, open context menus

**Expected behavior**
UI is drawn correctly

**Screenshots**
https://youtu.be/C6JiYjKXhfI

**Software versions**
 - ZAP: 2.9.0, or 2020-06-08
 - OS: Windows 10 x64 2004
 - Java: oracle 1.8.0_251, x32 x64
 - NVIDIA RTX 2060 with latest available official driver.

**Errors from the zap.log file**
Nothing interesting was found in the log:
[zap - Copy.log](https://github.com/zaproxy/zaproxy/files/4895657/zap.-.Copy.log)

**Additional context**
Problem can be fixed by restarting the WIndows, but can arise again. The actual trigger wasn't found.
ZAP is started using the following commandline:
set jvmopts=-Xmx2048m
java %jvmopts% -jar "zap-2.9.0.jar" -installdir C:\\zaptest290weeklyh1 -dir C:\\zaptest290weeklyh1\\data -nostdout -host 192.168.0.2 -port 8080
The data dir with config and etc was created in some older version.

**Would you like to help fix this issue?**
Yes, I can provide any additional info, traces, dumps, etc. if asked.

**Comment by psiinon** [comment]
Not something I've seen before, but it looks like it _could_ be a driver bug :/

**Comment by wadim-al** [comment]
Is there a way to gather debug info on this?

**Comment by wadim-al** [comment]
I will try adding -Dsun.java2d.noddraw=true and post results if it will continue reproducing or not.

**Comment by thc202** [comment]
Could you provide thread dumps when that happens?

**Comment by wadim-al** [comment]
Yes, I will provide when this happens again at the next work session, not now.

**Comment by wadim-al** [comment]
[dumps.txt](https://github.com/zaproxy/zaproxy/files/4936799/dumps.txt)
Here are the dumps.

**Comment by thc202** [comment]
Thanks, I don't see anything odd and don't see any fuzzer threads, so it's most likely not related to the fuzzer (or ZAP itself).

The following doc has some information on how to diagnose these kind of problems:
https://docs.oracle.com/javase/7/docs/webnotes/tsg/TSG-Desktop/html/java2d.html#gcgtn

e.g. try change the D3D rasterizer or enable OpenGL (`-Dsun.java2d.opengl=True -Dsun.java2d.d3d=false`)

**Comment by thc202** [comment]
Good to hear that there's a workaround, given that it's probably an issue in the driver or JRE itself. You should try report it upstream.

Yes, I think this can be closed.
