### ISSUE TITLE
Allow to differentiate requests by body content in Sites tree

### ISSUE THREAD

**Issue by ricekot** [zaproxy/zaproxy#6079]
**Is your feature request related to a problem? Please describe.**
I was not able to view two separate POST requests made to a graphql endpoint (introspection + generated query) in the sites tree. They were distinguished in the History panel, but there was only one entry in the sites tree.

**Describe the solution you'd like**
Properly differentiate requests that show up in the sites tree.

**Would you like to help implementing this feature?**
Yes.

**Comment by psiinon** [comment]
Fixed via #6125
