### ISSUE TITLE
Randomizer required for fuzzer

### ISSUE THREAD

**Issue by huornlmj** [zaproxy/zaproxy#6081]
Currently, there is no clear way to generate random material for fuzzing.  It's mostly a list of pre-generated content.  Take the radamsa tool as an example.  If ZAP could generate random content the way radamsa does the it would be a fabulous feature.  Ore even a way to have radamsa create the random content for ZAp to use would be an alternative.   Basically the fuzzing in ZAP is not fuzzy enough.

**Comment by kingthorin** [comment]
Closing as a duplicate zaproxy/zaproxy#1436

**Comment by thc202** [comment]
You can use the Payload Generator script to call external/specific tools. The Regex and Json payload generators allow to create random payloads, to some extent.
