### ISSUE TITLE
BUG: Session ID Cookie available to JavaScript flagged even when the HttpOnly cookie flag is set.

### ISSUE THREAD

**Issue by globeone** [zaproxy/zaproxy#6082]
**Describe the bug**
When running a ZAP Scan the alert
"Session ID Cookie Available to JavaScript"
will flag even though the HttpOnly cookie flag is set. 
It might be something as simple as it's not noticing that the HttpOnly flag is in CamelCase instead of lowercase?

**To Reproduce**
1. Start a HUD session
2. Click on a page with a spring  sessionID cookie with the HttpOnly Flag
3. Scroll down to alerts (once the Passive Scanner has found the cookie)
4. See error and note that the description also describes a different sessionID
![2020-07-20_OWASP_ZAP_2 9 0_HttpOnlyBug](https://user-images.githubusercontent.com/10052587/87938829-6dd88400-ca97-11ea-8cdf-1b07454bf6fc.png)

Although now I look in the Screenshot it seems to come from the Active scanner
"Active (40013 - Session Fixation)"

**Expected behavior**
The HttpOnly flag should be detected no matter what case it has and no alert should be raised.
httponly, HttpOnly are both valid representations and camel case is in most documentation about the flag.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies
![image](https://user-images.githubusercontent.com/10052587/87939357-40d8a100-ca98-11ea-93c3-05870a19bcd7.png)

**Screenshots**
Screenshots are inline

**Software versions**
 - ZAP: 2.9.0
 - Add-on: 
[2020-07-20ZAPInstalledAddOns.xlsx](https://github.com/zaproxy/zaproxy/files/4947835/2020-07-20ZAPInstalledAddOns.xlsx)
 - OS: Windows 10 - 1909 (OS Build 18363.900)
 - Java: (ps maybe update the bug report boilerplate with a hint. Open a command line and type "java -version" for users who might not know how to get the version of java)
openjdk version "13.0.2" 2020-01-15
OpenJDK Runtime Environment (build 13.0.2+9)
OpenJDK 64-Bit Server VM (build 13.0.2+9, mixed mode, sharing)

 - Browser: 
Google Chrome Version 84.0.4147.89 (Official Build) (64-bit) (scanned with Chrome)
Firefox 78.0.2 (64-bits) (scanned with Firefox as well)

**Errors from the zap.log file**
See https://www.zaproxy.org/faq/what-is-the-default-directory-that-zap-uses/ for the location of the zap.log file for your OS.
![image](https://user-images.githubusercontent.com/10052587/87941887-17217900-ca9c-11ea-8947-84a572608316.png)
The only errors are from trying to import the OpenAPI doc from a valid OpenApi/Swagger Doc URL, which is fodder for a new bug report.

**Additional context**
ZAP was consistently locking out the user during the scan, we had to keep pausing the scan and re-enabling the user.

**Would you like to help fix this issue?**
I'd be happy to fix the FAQ and bug boilerplate if someone could point me to the edit pages.

**Comment by psiinon** [comment]
Thats strange - the code looks like its using camelCase: https://github.com/zaproxy/zap-extensions/blob/master/addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CookieHttpOnlyScanRule.java#L42

Re https://www.zaproxy.org/faq/what-is-the-default-directory-that-zap-uses/ - if you look at the bottom left of that page you'll see a link "Edit on GitHub" :D

**Comment by kingthorin** [comment]
Re: camelCase > `hasAttribute` uses `equalsIgnoreCase` so that shouldn't matter.

I'll do some testing.

**Comment by thc202** [comment]
The alert was raised by an active scan rule, Session Fixation.

**Comment by kingthorin** [comment]
https://github.com/zaproxy/zap-extensions/blob/bca32f0b745e3652cafd1bf475a28b9ee9b38688/addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/SessionFixationScanRule.java#L499 does seem to do a case sensitive check.

I'll start working towards some UnitTests and a fix.

@globeone seems likely to be a false positive. Thanks for letting us know.

**Comment by globeone** [comment]
Thanks for fixing this. It was indeed a false positive.

**Comment by thc202** [comment]
@globeone thanks, you'll need to open a pull request though.
