### ISSUE TITLE
Add generation date to the HTML and MD reports

### ISSUE THREAD

**Issue by globeone** [zaproxy/zaproxy#6084]
**Is your feature request related to a problem? Please describe.**
At the moment when sharing an HTML report the date the scan was performed is not on the report so it's difficult to compare reports when shared with vendors. Many companies have a scan policy of every x months. It would be really helpful to have the scan timestamp on the report. 

**Describe the solution you'd like**
Add a Timestamp of when the scan was completed to the HTML Report

**Describe alternatives you've considered**
There are no alternatives at the moment other than editing the HTML source by hand to add the timestamp.

**Additional context**
Here is a mock up of the request with exaggerated colors just so it stands out:
![2020-07-21-FeatureRequestTimestampOnScanReport](https://user-images.githubusercontent.com/10052587/88042846-dfbed500-cb4c-11ea-82c0-bc59599ed83e.png)

**Would you like to help to implement this feature?**
The source code of ZAP is daunting. I'll leave this one to the expert programmers.
I'm guessing there is a database field with the Scan Completion Timestamp
For current scan
Read `Scan Completion Timestamp` field in database
Write Timestamp to HTML Report
(if only programming was this easy) 😸

**Comment by kingthorin** [comment]
A report can include multiple scans, or no scan at all in the case of only passive results.

**Comment by globeone** [comment]
How about at least a timestamp of when the report is created, on the report?

**Comment by globeone** [comment]
![2020-07-21-FeatureRequestTimestampOnScanReport](https://user-images.githubusercontent.com/10052587/88048524-c66d5700-cb53-11ea-9ce5-6fc0fc0ad1ef.png)

This should be even easier:

On Create Report 
Write CurrentDate

it also helps in trying to find the SessionID to reopen the scan if necessary, which is also based on timestamp.

**Comment by kingthorin** [comment]
Yup that's probably workable.

**Comment by StefanTobler** [comment]
Design-wise, would it be more pleasing to have the time stamp in a box like it is shown above or just on its own line? 

![image](https://user-images.githubusercontent.com/22108632/89372577-84482780-d6b4-11ea-9cd3-e7d25c1d3b22.png)

Such as this.

I was just playing around with the box and felt that it was a bit distracting compared to the rest of the report.

**Comment by psiinon** [comment]
It could always go under the ZAP Scanning Report title on the top right?
Maybe just: "Generated on YYYY-MM-DD HH:mm:ss"?

**Comment by StefanTobler** [comment]
> It could always go under the ZAP Scanning Report title on the top right?
> Maybe just: "Generated on YYYY-MM-DD HH:mm:ss"?

Currently, I have the time generating like this `Generated on Thu, 6 Aug 2020 14:47:33` so that the date-time format stays consistent with the XML report. I can change both of them to `YYYY-MM-DD HH:mm:ss` if you prefer as they are both using the same date formatter. I am going to submit a PR for what I have now.
