### ISSUE TITLE
CRSF Scanner flagging when a <form> tag is embedded in JavaScript

### ISSUE THREAD

**Issue by globeone** [zaproxy/zaproxy#6089]
**Describe the bug**
Not sure it's a bug but it's baffled me and the developers so it's at least a bit confusing as to why, what is going on and what we can actually do about it. We've read the OWASP page on the subject and are still confused.
Our devs use a standard JavaScript library and in the library it contains a lonely `<form>` tag that gets generated into a form with all the attributes when the JavaScript runs. 

As the library is used in many websites we scan, we are consistently getting the anti Cross Site Request Forgery (CSRF) tokens scanner alert as shown here below.
![2020-07-22AntiCSRFOnFormInJavascript](https://user-images.githubusercontent.com/10052587/88178429-abb9e180-cc2a-11ea-82c0-d103a88859cb.png)

**To Reproduce**
1. Start a scan on a website containing main.js (I still have the question out if we wrote main.js or it's a standard library)
2. Start an Active Scan
3. The Active Scan will flag the anti CSRF token scanner on the single `<form>` tag from within the JavaScript
4. Confusion on why the context of HTML embedded in JavaScript is ignored. Is the alert just a regex looking for the <form> tag? 
5. More confusion on what the expected action to take next is.
6. Confusion if this is a false positive or not

Apologies for all the confusion this has stumped my team and most of the devs. 

**Expected behavior**
The Description is very complete, but doesn't say anything about the finding itself.
A better explanation of why anti CSRF relates to this lonely embedded `<form>` tag would be helpful.
Or
If it's a false positive, check for FileType (javascript) and Context before throwing the alert?

**Screenshots**
Inline screenshots

**Software versions**
 - ZAP: 2.9.0
 - Add-on: 
[2020-07-20ZAPInstalledAddOns.xlsx](https://github.com/zaproxy/zaproxy/files/4960100/2020-07-20ZAPInstalledAddOns.xlsx)

 - OS: Windows 10 1909 (18363.959)
 - Java: BellSoft Liberica OpenJDK 14 (I upgraded because JavaFX is included and Liberica claims to be the most compatible with Oracle JavaSE. Now the HTML preview works in ZAP which is awesome)
openjdk version "14.0.2" 2020-07-14
OpenJDK Runtime Environment (build 14.0.2+13)
OpenJDK 64-Bit Server VM (build 14.0.2+13, mixed mode, sharing)
 - Browser: 
Google Chrome 84.0.4147.89 (Official Build) (64-bit)
Firefox 78.0.2 (64-bits)

**Errors from the zap.log file**
I found this but not sure if it's related or not, it's the only errors I have in the logs about CSRF tokens. 
```
2020-07-15 14:05:28,013 [ZAP-ProxyThread-4] WARN  API - Bad request to API endpoint [/zap/rest/CSRFToken] from [127.0.0.1]:
Bad Format (bad_format)
	at org.zaproxy.zap.extension.api.API.handleApiRequest(API.java:425)
	at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(ProxyThread.java:499)
	at org.parosproxy.paros.core.proxy.ProxyThread.run(ProxyThread.java:335)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: java.lang.IllegalArgumentException: No enum constant org.zaproxy.zap.extension.api.API.Format.ZAP
	at java.base/java.lang.Enum.valueOf(Enum.java:266)
	at org.zaproxy.zap.extension.api.API$Format.valueOf(API.java:60)
	at org.zaproxy.zap.extension.api.API.handleApiRequest(API.java:404)
```

**Additional context**
If I'm missing something obvious please let me know. And thank you.

**Would you like to help fix this issue?**
I'd have to understand it to fix it, at the moment I'm at a loss.

**Comment by kingthorin** [comment]
Is the `content-type` of the response `text/javascript`?

I'd have to check the code but my 'guess' is that that rule is checking either all text type responses or all responses and should probably exclude/skip things that are specifically JS.

**Comment by psiinon** [comment]
I was just thinking the same thing. Yes, js can add forms which then done have the relevant CSRF tokens, but this wouldnt be a good way to detect them.
We could just checge these to only be reported at a low threshold for JS files...

**Comment by globeone** [comment]
Here is the response header from the example scan, and yes @kingthorin the content type is application/javascript

![2020-07-22antiCSRFjavascriptType](https://user-images.githubusercontent.com/10052587/88189132-035f4980-cc39-11ea-8a61-fc2dc6eefeac.png)
