### ISSUE TITLE
Docker container stable OR weekly do not create reports

### ISSUE THREAD

**Issue by ankh2054** [zaproxy/zaproxy#6093]
**Describe the bug**
Running the stable or weekly docker images no reports are generated using -x or -r options

**To Reproduce**
```
sudo docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-baseline.py     -t https://test.io -g gen.conf -r testreport.html

sudo docker run -v /home/test/:/zap/wrk/:rw -t owasp/zap2docker-stable zap-baseline.py     -t https://test.io -g gen.conf -r testreport.html

sudo docker run -v /home/test/:/zap/wrk/:rw -t owasp/zap2docker-weekly zap-baseline.py     -t https://test.io -g gen.conf -r testreport.html

sudo docker run -v /home/test/:/zap/wrk/:rw -t owasp/zap2docker-weekly zap-baseline.py     -t https://test.io -g gen.conf -x testreport.html
```

**Expected behavior**

**Screenshots**

**Software versions**
 - ZAP: Latest  owasp/zap2docker-weekly &  owasp/zap2docker-stable
 - OS: Ubuntu 18.04

**Errors from the zap.log file**
```
48991 [HSQLDB Timer @10d59286] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - Checkpoint start
48991 [HSQLDB Timer @10d59286] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - checkpointClose start
48992 [HSQLDB Timer @10d59286] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - checkpointClose synched
48996 [HSQLDB Timer @10d59286] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - checkpointClose script done
48996 [HSQLDB Timer @10d59286] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - dataFileCache commit start
49161 [HSQLDB Timer @10d59286] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - dataFileCache commit end
49167 [HSQLDB Timer @10d59286] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - checkpointClose end
49168 [HSQLDB Timer @10d59286] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - Checkpoint end - txts: 87362
57167 [ZAP-SpiderThreadPool-0-thread-2] INFO org.zaproxy.zap.spider.Spider  - Spidering process is complete. Shutting down...
57168 [ZAP-SpiderShutdownThread-0] INFO org.zaproxy.zap.extension.spider.SpiderThread  - Spider scanning complete: true
```

**Would you like to help fix this issue?**
yes definitely. I will also try and modify the Dockerfiles to keep it running after a scan and then perform a scan inside container.

**Comment by kingthorin** [comment]
You didn't provide the full path to your mounted directory to write the file.

**Comment by ankh2054** [comment]
Same issue, I have also logged into the container using and run the command directly from there and still not export is generated.

```
sudo docker run -v /home/test:/zap/wrk/ -t owasp/zap2docker-stable /bin/bash
zap@c5e796bca032:/zap$ ./zap-baseline.py -t https://test.io -x /zap/wrk/test.xml
```

Looking inside /zap/wrk there is no test.xml

**Comment by kingthorin** [comment]
Looks like you didn't set the permission `:rw`

**Comment by ankh2054** [comment]
trying again with :rw.

Also looking into the zap-baseline.py, the base_dir to where the reports are saved are set, so there should be no need to specify /zap/work
```
if running_in_docker():
        base_dir = '/zap/wrk/'
...
if report_html:
                # Save the report
                write_report(base_dir + report_html, zap.core.htmlreport())

            if report_json:
                # Save the report
                write_report(base_dir + report_json, zap.core.jsonreport())

            if report_md:
                # Save the report
                write_report(base_dir + report_md, zap.core.mdreport())

            if report_xml:
                # Save the report
                write_report(base_dir + report_xml, zap.core.xmlreport())

```

**Comment by ankh2054** [comment]
ill check the docker logs

**Comment by kingthorin** [comment]
Are you running on windows?

**Comment by ankh2054** [comment]
nope on ubuntu, but for some reason the container does not have rights to write to that directory.
ap@27e54591fc6d:/zap/wrk$ echo  1 > test.txt
bash: test.txt: Permission denied

**Comment by ankh2054** [comment]
inspecting the container it does have RW.

```
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/home/test",
                "Destination": "/zap/wrk",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
```

**Comment by ankh2054** [comment]
Problem seems is that /zap/wrk is owned by user 1001

```
zap@191745a32b87:/zap/wrk$ ls -la
total 9680588
drwxr-xr-x 7 1001 1001       4096 Jul 22 20:21 .
drwxr-xr-x 1 zap  zap        4096 Jul 22 20:24 ..
```

**Comment by ankh2054** [comment]
zap has UID of 1000

**Comment by ankh2054** [comment]
ah man this is weird, so wthat I ended having to so is do change the permission of my local volume /home/test to match the UID of ZAP (1001)

```
sudo chown 1001:1001 /home/test
```

**Comment by ankh2054** [comment]
so the issue seem to be that the volume is always created using the permission of the user running Docker, and /zap/wrk is therefore owned by root in the zap container and when  you enter the container you are user zap and therefore cannot write to that directory. 

Still seems like a docker issue to me.

**Comment by ankh2054** [comment]
found a better solution  

1. Find out who owns the directory you are mount /zap/wrk to
2. Identify the UID of that user
3. When running the container specify --user UID:UID of user whom owns directory

```
sudo docker run -v $(pwd):/zap/wrk/ --user 1001:1001 -t owasp/zap2docker-stable zap-baseline.py     -t https://test.io -g gen.conf -r testreport.htm
```

**Comment by psiinon** [comment]
Thanks for letting us know :)

**Comment by ankh2054** [comment]
Thanks for a great product 👍
