### ISSUE TITLE
OpenAPI add-on Import from File Dialog: 2 suggested improvements

### ISSUE THREAD

**Issue by davewichers** [zaproxy/zaproxy#6094]
This applies to this dialog, and likely the other 2 import mechanisms.

I have 2 improvement requests:
- [x] If you import something, it would be nice if it saved the File Path, URL, etc. so if you reopen the same dialog, the previous import is there by default.

This is useful, for example, if you import something and get error messages like 'request refused' because you forgot to start the target app. You could then start the app, reopen the same dialog, and then simply hit the 'Import' button as the target file would already be there.

- [x] Can some kind of import progress indicator be provided?

I have created an OpenAPI spec for OWASP Benchmark, and it contains 2740 entries.  It takes a LONG time to import, particularly if you forget to start Benchmark in the first place. As it waits for 2740 timeouts before the import finishes. Maybe when the import completes it can also say: N endpoints successfully imported (or something like that). M endpoints appear to be new. (Where M is new items added to the Site tree.)

I can send you the Benchmark OpenAPI spec file I've created so you can test any feature improvements along these lines against Benchmark.

**Comment by psiinon** [comment]
These sound useful enhancements, although I'm not sure how easy the progress indicator will be without looking at the code ;)
We would definitely be interested in the Benchmark OpenAPI spec - is that something you plan to include with Benchmark at some stage?

**Comment by davewichers** [comment]
It is now here: https://github.com/OWASP/Benchmark/blob/master/data/openapi.yaml. Per the commit comment, if you notice any problems with it, let me know as the paint isn't yet dry on this thing :-)

**Comment by kingthorin** [comment]
I'd be good with Option 1, it could be brought to front or given focus when things are added to it. But then it doesn't block UI or other work. We shouldn't encounter simultaneous imports very often, but that doesn't mean it never happens.

If it's meant to be used by multiple components/add-ons then I guess it should be added to [commonlib](https://github.com/zaproxy/zap-extensions/tree/master/addOns/commonlib) and commonlib set as a dependency of the add-ons that need it.

**Comment by thc202** [comment]
Closing with zaproxy/zap-extensions#2916 and zaproxy/zap-extensions#2942.
