### ISSUE TITLE
Bug: Compatibility: Future Proofing: Ruby Extension not compatible with Java 14

### ISSUE THREAD

**Issue by globeone** [zaproxy/zaproxy#6097]
**Describe the bug**
So, I was actually researching another bug I found before I report it... when in the Logs I saw a java stack trace that the Ruby extension had crashed out with a message that Java 14 is incompatible.
I know I'm pushing it a bit already running Java 14, but it's good to be Future Proof and Java claims to be backwards compatible. 😸 (riiight)

**To Reproduce**
1. Install Java 14 (I used the Liberica JDK 14)
2. Open ZAP
2a Install the Ruby Plugin if not already installed
3. Open the Log file
4. See error (it's attached in the log file section of this bug report)

**Expected behavior**
ZAP Ruby plugin code to be future proof

**Screenshots**
![image](https://user-images.githubusercontent.com/10052587/88296455-015fbe00-ccff-11ea-86eb-11d30572543a.png)

**Software versions**
 - ZAP: 2.9.0
 - Add-on: 
[2020-07-23ZAPInstalledAddOns.xlsx](https://github.com/zaproxy/zaproxy/files/4966502/2020-07-23ZAPInstalledAddOns.xlsx)

 - OS: Windows 10
[Environment]::OSVersion.VersionString
Microsoft Windows NT 10.0.18363.0

 - Java: Bellsoft Liberica Java 14 JDK Full (with JavaFX)
 java -version
openjdk version "14.0.2" 2020-07-14
OpenJDK Runtime Environment (build 14.0.2+13)
OpenJDK 64-Bit Server VM (build 14.0.2+13, mixed mode, sharing)

 - Browser: [e.g. chrome 66, firefox 59, safari 11.1]
Google Chrome Version 84.0.4147.89 (Official Build) (64-bit)
Firefox 78.0.2 (64-bits)

**Errors from the zap.log file**

[ZAPJava14RubyUnsupported.log.txt](https://github.com/zaproxy/zaproxy/files/4966429/ZAPJava14RubyUnsupported.log.txt)

**Additional context**
I'm not expecting too much from this bug it's more a marker to be prepared for future versions of Java. 

Maybe a bit of error handling so that the crash out of the plugin doesn't result in a Java stack trace. Instead, possibly a graceful disabling of the plugin and some kind of message to the user that Ruby will be unavailable for this session due to an unsupported Java version?

**Would you like to help fix this issue?**
Happy as always to test any fixes. It might be so easy as removing the Java Version check in the ruby plugin? This is speculation though as the source for ZAP is way over my head in complexity.

Thanks again and may everyone be happy and healthy.

**Comment by kingthorin** [comment]
This is already being tracked as part of:
- https://github.com/zaproxy/zaproxy/issues/3944
- https://github.com/zaproxy/zaproxy/issues/2602

**Comment by globeone** [comment]
Apologies I thought I searched thoroughly through earlier bugs. Apparently not.

**Comment by kingthorin** [comment]
No worries. Thanks for helping keep ZAP great 👍
