### ISSUE TITLE
Secure Connection Failed after importing certificates

### ISSUE THREAD

**Issue by paradoxite** [zaproxy/zaproxy#6101]
**Describe the bug**
I get error "Secure Connection Failed" with Error code: SEC_ERROR_BAD_SIGNATURE even after importing certificate in Firefox

**To Reproduce**
1. Generate certificate 
2. Import certificate in firefox
3. Open zap
4. Visit a website
5. See error

**Expected behavior**
Zap should capture the visited website and firefox would connect to the [website.]

**Software versions**
 - ZAP: 2.9.0
 - OS: [Linux Mate 20]
 - Java: [openjdk version "11.0.8"]
 - Browser: [78.0.2]

**Errors from the zap.log file**
2020-07-28 07:24:11,916 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Logs errors to the Output tab in development mode only

**Additional context**
I tried uninstalling, generating new certificate and importing it and changing network.proxy.allow_hijacking_localhost to true in about:config

**Would you like to help fix this issue?**
Yes, please.

**Comment by paradoxite** [comment]
Java version: openjdk version "11.0.8"

**Comment by kingthorin** [comment]
Did you import it as a CA certificate?

**Comment by paradoxite** [comment]
> Did you import it as a CA certificate?

Yes. I just visited an HTTP website and it worked. The problem is with HTTPS.

**Comment by kingthorin** [comment]
....If you visited a HTTP site that doesn't prove anything as the cert isn't implicated...

**Comment by kingthorin** [comment]
Please provide a screenshot of Firefox certificate preferences with the CA cert.

**Comment by paradoxite** [comment]
![proxy](https://user-images.githubusercontent.com/42909126/88575625-78b98880-d044-11ea-8f92-8480123082b5.png)

**Comment by kingthorin** [comment]
Thanks, and the cert details? (`Edit Trust`, and `View` you can do a full page screenshot from the `...` in the address bar)

**Comment by paradoxite** [comment]
![trust](https://user-images.githubusercontent.com/42909126/88577420-48271e00-d047-11ea-991d-9d6b2600b9e9.png)
How do I take a full page screenshot?

**Comment by paradoxite** [comment]
![1](https://user-images.githubusercontent.com/42909126/88577873-f763f500-d047-11ea-8445-7adb829751a3.png)
![2](https://user-images.githubusercontent.com/42909126/88577882-f9c64f00-d047-11ea-9a44-1f058e49c34b.png)
Sorry I didn't know what you meant with [...] to take a whole page screenshot.

**Comment by kingthorin** [comment]
No worries, you got the details I was after.

Is it all HTTPS sites that fail or a particular set/site or something local?

**Comment by paradoxite** [comment]
There is one https website that works upon visiting but doesn't get intercepted by zap. All other websites don't work and don't get intercepted either.

**Comment by kingthorin** [comment]
Are you using a proxy switcher like FoxyProxy or something? Have you restarted browser/zap/system (system shouldn't really be necessary but ..... IT 🤷 )

**Comment by paradoxite** [comment]
Not using any proxy switcher. I have restarted everything, even the system but still no luck,

**Comment by paradoxite** [comment]
Anything please?

**Comment by wadim-al** [comment]
When reinstalling the ZAP, did you delete the ZAP data folder containing the config?

**Comment by paradoxite** [comment]
That worked! Thanks <3

**Comment by wadim-al** [comment]
@paradoxite I'm glad you've managed to fix this!
