### ISSUE TITLE
Error starting Active Scan in "Everything in Scope" mode.

### ISSUE THREAD

**Issue by mauricew9** [zaproxy/zaproxy#6102]
**Describe the bug**
With 3 contexts in scope, starting Active Scan in "Everything in Scope" mode produces an error, and no scanning occurs. The following is written to the log:

425550872 [AWT-EventQueue-0] INFO org.parosproxy.paros.core.scanner.Scanner  - scanner started
425550873 [Thread-3781] ERROR org.parosproxy.paros.core.scanner.Scanner  - An error occurred while active scanning:
java.lang.NullPointerException
	at org.zaproxy.zap.model.StructuralSiteNode.isRoot(StructuralSiteNode.java:77)
	at org.parosproxy.paros.core.scanner.Scanner.scan(Scanner.java:231)
	at org.parosproxy.paros.core.scanner.Scanner.run(Scanner.java:208)
	at java.lang.Thread.run(Thread.java:748)

**To Reproduce**
1. Create 3 Contexts, configure each context to be in scope
2. Open the Active Scan wizard
3. For Staring Point field, click Select button and choose the "Everything in Scope" option
4. Finish the wizard and click the button to start the scan.
5. Error is written to log (see above) and no scanning takes place.

**Expected behavior**
Expect Active Scan to run, scanning all URLs currently in scope

**Screenshots**

**Software versions**
 - ZAP: 2.9.0
 - OS: Linux Mint 19.3
 - Java: openjdk version "1.8.0_252"
 - Browser: n/a

**Errors from the zap.log file**

425550872 [AWT-EventQueue-0] INFO org.parosproxy.paros.core.scanner.Scanner  - scanner started
425550873 [Thread-3781] ERROR org.parosproxy.paros.core.scanner.Scanner  - An error occurred while active scanning:
java.lang.NullPointerException
	at org.zaproxy.zap.model.StructuralSiteNode.isRoot(StructuralSiteNode.java:77)
	at org.parosproxy.paros.core.scanner.Scanner.scan(Scanner.java:231)
	at org.parosproxy.paros.core.scanner.Scanner.run(Scanner.java:208)
	at java.lang.Thread.run(Thread.java:748)

**Additional context**
n/a

**Would you like to help fix this issue?**
Yes.

**Comment by kingthorin** [comment]
What's the configuration of your two contexts?

**Comment by mauricew9** [comment]
Default (except for included URLs of course.) They each contain URLs from multiple sites.

**Comment by kingthorin** [comment]
Thanks, I’ve been able to re-create the issue.
