### ISSUE TITLE
Windows 10 Complete And Instant Crash

### ISSUE THREAD

**Issue by Undefined-Variables** [zaproxy/zaproxy#6107]
I have Windows 10 Pro 64 Bit running on two different machines, the first is a laptop with i5 Intel Chip, 4GB Ram and runs Zap without any issues. 

The second is a desktop that has an Quad Core AMD Chip has 16GB Ram and also running Windows 10 Pro 64 Bit but Zap starts off with a scan and after 3 or 4 minutes "Blip" crashes the machine without any warning, no blue screen and no apparent reason. On reboot Zap has not remembered my preferences and everything boots as normal.

I have attempted to get the crash dump file from Windows but because it dies instantly there is nothing dumped, so I watched task manager closely and there is no obvious spike in resources at or leading up to the crash...

So how do I diagnose the problem? This machine is many times more powerful than the laptop that has no issues. 

They both have the same 64 Bit version of the current release installed from the same downloaded file.  Any idea what the problem might be and any suggestions on how to solve it?

**Comment by psiinon** [comment]
A Java program like ZAP shouldnt be able to crash a machine :/
Not something I've had any experience with I'm afraid.
Which JVM are you using? Might be worth trying another one?

**Comment by wadim-al** [comment]
@Undefined-Variables Please check the Windows Event Viewer for logs. There might be indication of CPU, memory, driver, or drive errors. Try running ZAP and its data folders from another physical drive. Check for memory corruption. Check temperatures on everything. Try disabling all antivirus softwares. Do this one at a time. These are general tips when debugging such strange reboots. Sometimes it is worth to update the BIOS/UEFI, but it is dangerous. At the last resort try running with 1 memory stick at a time, or completely another stick. And try another quality power supply.

**Comment by Undefined-Variables** [comment]
@psiinon currently running the same on both machines... 

![java](https://user-images.githubusercontent.com/52648055/89265988-3c31f200-d62d-11ea-8331-220d86005db5.PNG)

The thought I give to this the more I am thinking its like @wadim-al is suggesting, a hardware issue or a software clash but normally with the latter you see BSOD and are also able to grab the dump and use windows debugger to see how, why, when the moment the system found its self in a unrecoverable state. 

@wadim-al  I think you may be correct in the fault being hardware, I have done the standard software drill and it made no  difference. but the sudden loss of power is almost like it shorts out. My Power supply is only a few moths old and upgraded to a real high quality  one. 

I will  do the step by stop elimination as soon as I have the time to rip it apart. I  just wanted to check there was not something known that could do this.

BTW the HUD is absolutely out of this world in terms of usability and the way the info is there without any extra effort is very nice and make my life testing as I write code a million times simpler so thank you for your hard work and for being open and free, you have made a difference to my work life 👍

**Comment by psiinon** [comment]
Thanks for letting us know, and the great feedback on the HUD!
We dont get a huge amount of feedback so its good to hear people find it really useful :)

**Comment by wadim-al** [comment]
@Undefined-Variables Power supply may be good, but it doesn't eliminate the probability of overloading or other faults. I've bought a power supply once, of a well known model, but after it failed, I've removed the sticker and found out it was fake (other sticker under it). I advise checking anyways to get facts, not assumptions. Also you may try some stress tests on different components to see how temperatures and voltages are behaving. The fact of restart without BSOD gives clues on some hardware protection or watchdog which resets the machine in case of problems, so you may also search on your motherboard or other hardware manufacturer forums for that restart issue.

**Comment by Undefined-Variables** [comment]
@wadim-al that is really good advice. I will do exactly as you suggest as soon as I have some time to think about this properly. 

I have always used Zap on my laptop until yesterday I was running a scan on my biggest site and started running out of memory so was seeing lag and hanging so thought using my more powerful machine was a good idea then when it just died I was lost for words so repeated it 5 or 6 times trying to work out the reason. 

Thanks for the advice it's appropriated :)

**Comment by Undefined-Variables** [comment]
@psiinon it's a game changer. It puts you in the application with all the information you need without having to flick back and forth! I can't believe people pay for other services that are not even close to this standard. 

You have blown the most popular paid service not just out of the water, they are floating around in space somewhere, wondering what happened.

**Comment by psiinon** [comment]
:D
