### ISSUE TITLE
Feature Request: Ability to easily share the entire session with another security researcher using ZAP

### ISSUE THREAD

**Issue by globeone** [zaproxy/zaproxy#6111]
**Is your feature request related to a problem? Please describe.**
When testing another companies web application for vulnerabilities it would be really nice to be able to share the entirety of the ZAP session with the security researcher from the other company, so they can walk through all the requests.

**Describe the solution you'd like**
There is a Snapshot Session menu option,
What would be nice is an Export (Share) Session

And then a corresponding Import Session that would import everything needed to view the entire session.

**Describe alternatives you've considered**
At the moment a Session file is several files it's unclear which of the files would need to be shared.

**Additional context**

![image](https://user-images.githubusercontent.com/10052587/89543645-76ec8380-d801-11ea-9598-d546d81f98ba.png)

**Would you like to help implementing this feature?**
Always happy to test.

**Comment by kingthorin** [comment]
Zip up the set of files and send it?

**Comment by thc202** [comment]
Closing as duplicate of #373.

**Comment by globeone** [comment]
> Zip up the set of files and send it?

Which files is unclear, there are like 6 different files per session and how does ZAP know which plugins to load in the marketplace in order recreate the session as it was?

**Comment by kingthorin** [comment]
> Which files is unclear, there are like 6 different files per session and how does ZAP know which plugins to load in the marketplace in order to recreate the session "as it was"?

All files created by ZAP and named as per your save name. A ZAP session is essentially a database. Alert details aren't retrieved from add-ons at read time, they're read from the DB. So even with different add-ons installed the session will be readable/browseable. If multiple parties want to "work" (test, spider, etc) on exactly the same session that's more challenging and would require collaboration between the individuals/parties and is outside of ZAP's scope (IMHO ... it's a desktop app not a server/multi-user app.)
