### ISSUE TITLE
ERROR HttpSender - URLDecoder: Illegal hex characters in escape (%) pattern - Error at index 0 in: "' "

### ISSUE THREAD

**Issue by globeone** [zaproxy/zaproxy#6112]
**Describe the bug**
Regression of:
1801
1848

It looks like a missing ' single quote is causing the HttpSender - URLDecoder to throw this error.
Should "' " Double Quote, Single Quote, Space, Close Double Quote  
not be "' '"  Double Quote, Single Quote, Space, Close Single Quote, Close Double Quote?
URLDecoder: Illegal hex characters in escape (%) pattern - Error at index 0 in: "' "

See the attached log file for the full error and locations in Java.

**To Reproduce**
1. Start a HUD scan
2. Click on Attack Mode
3. Click through the website

**Expected behavior**
Either the error should be handled or throw a warning so the end user knows what to do with the error.

**Screenshots**
Error only shows up in the log file, no user feedback is given that the error occurs

**Software versions**
 - ZAP: D-2020-803
 - Add-on: 
[2020-08-06_D-2020-803_InstalledAddons.xlsx](https://github.com/zaproxy/zaproxy/files/5036503/2020-08-06_D-2020-803_InstalledAddons.xlsx)

 - OS: Windows 10 19.09 18363.959
 - Java: Bellsoft Liberica JDK 14
 java -version
openjdk version "14.0.2" 2020-07-14
OpenJDK Runtime Environment (build 14.0.2+13)
OpenJDK 64-Bit Server VM (build 14.0.2+13, mixed mode, sharing)

 - Browser: 
Google Chrome: Version 84.0.4147.105 (Official Build) (64-bit)
Firefox: 79.0 (64-bits)

**Errors from the zap.log file**
[2020-08-06_URLDecoderIllegalHex_zap.log](https://github.com/zaproxy/zaproxy/files/5036467/2020-08-06_URLDecoderIllegalHex_zap.log)

**Additional context**

**Would you like to help fix this issue?**
Happy to test.

**Comment by thc202** [comment]
This is not an issue in ZAP itself.

@cak ping, `ReflectListener` needs to be updated to handle invalid values.

**Comment by cak** [comment]
Thanks and sorry - I'll look into and push an update out for Reflect.

**Comment by cak** [comment]
Update: Fixed issue with URLDecoding % ([fix](https://github.com/TypeError/reflect/commit/ea6de10fdaf266ba6e44e611df301219ab6e7604))
