### ISSUE TITLE
HTTPS Info tab should provide instructions on how to use it

### ISSUE THREAD

**Issue by globeone** [zaproxy/zaproxy#6113]
**Describe the bug**
The HTTPS Info tab has stopped working altogether

**To Reproduce**
1. Go to a website being tested
2. Click on HTTPS Info Tab
3. Wait 5 minutes
4. Wait 10 minutes
5. still blank after 20 minutes

**Expected behavior**
Some kind of feedback if the HTTPS Info is actually doing something. Progress bar, or something. Even an error message when it goes wrong would be helpful. Of course the results would be even better. 😸 

**Screenshots**
![image](https://user-images.githubusercontent.com/10052587/89561207-76abb280-d818-11ea-90c0-cd183df870cd.png)

**Software versions**
ZAP: D-2020-803

Add-on:
[2020-08-06_D-2020-803_InstalledAddons.xlsx](https://github.com/zaproxy/zaproxy/files/5036598/2020-08-06_D-2020-803_InstalledAddons.xlsx)

OS: Windows 10 19.09 18363.959

Java: Bellsoft Liberica JDK 14
java -version
openjdk version "14.0.2" 2020-07-14
OpenJDK Runtime Environment (build 14.0.2+13)
OpenJDK 64-Bit Server VM (build 14.0.2+13, mixed mode, sharing)

Browser:
Google Chrome: Version 84.0.4147.105 (Official Build) (64-bit)
Firefox: 79.0 (64-bits)

**Errors from the zap.log file**
[2020-08-06_URLDecoderIllegalHex_zap.log](https://github.com/zaproxy/zaproxy/files/5036619/2020-08-06_URLDecoderIllegalHex_zap.log)

**Additional context**
Am connected over VPN, but this has worked in the past with the HTTPS Info so might be unrelated.

**Would you like to help fix this issue?**
Sure, Testing is great

**Comment by globeone** [comment]
I thought it might be due to an out of memory error, so I increased the JVM memory size with
-Xmx4096m

Unfortunately this had no effect. The HTTPS Info still remains blank

Also, nothing gets logged to the log file when I open or close the tab.

Have tried clicking on the different domains in scope but no dice.

**Comment by kingthorin** [comment]
You're just showing the tab, that doesn't cause any action. Use the context menu in the Sites Tree or a History entry:
![image](https://user-images.githubusercontent.com/7570458/89564146-8f04d880-d7ea-11ea-89cb-e43d70ce65d7.png)

**Comment by thc202** [comment]
"TLS Debug" and "HTTPS Info" are two different functionalities. The "--- END of call --..." means that the check was done/finished. (I'm not sure the TLS Debug is working as expected with newer Java versions.)

**Comment by globeone** [comment]
> You're just showing the tab, that doesn't cause any action. Use the context menu in the Sites Tree or a History entry:

Sorry, my bad. I thought I had done that.

An exception did occur though while getting the results
An exception occurred while updating the General panel. Problem fetching certificate. err=java.lang.StringIndexOutOfBoundsException: begin 4, end -1, length 22Cipher Suites Supported:

![image](https://user-images.githubusercontent.com/10052587/89626485-d1392300-d899-11ea-9205-9360546d83dd.png)


But maybe a text hint in the GUI would help when opening the tab from the tab bar. 
"No site selected. Please right click a site in the site tree and choose HTTPS Info from the context menu."

![image](https://user-images.githubusercontent.com/10052587/89626195-4c4e0980-d899-11ea-8c1f-89a384a59ef8.png)

**Comment by thc202** [comment]
Tweaked the title to match what's being suggested.

**Comment by Infernalbronco** [comment]
Hi,  I am a contributor. I would like some advice on how to get started? Thank you!

**Comment by kingthorin** [comment]
Welcome aboard!

The code for the HttpsInfo add-on lives here > https://github.com/zaproxy/zap-extensions/tree/master/addOns/httpsInfo
I'd suggest just making a panel that's added at init that just displays a message like "To start an HTTPS assessment choose 'Scan HTTPS Configuration' from the context menu (right click) on a Sites Tree or History entry" (or something like that) which is then hidden or removed after the first actual tab is added.

**Comment by Infernalbronco** [comment]
Thank you for the opportunity!

**Comment by ablewitt** [comment]
@Infernalbronco are you still running with this? I have a solution if you wanted to team up?

**Comment by thc202** [comment]
This is being worked in zaproxy/zap-extensions#2580.

**Comment by ablewitt** [comment]
Thanks @thc202, looks like I missed out on this one.

**Comment by ablewitt** [comment]
I'm willing to finish this off if it has gone stale?
I did have a solution late last year however it looked like @Infernalbronco was onto it.

I have re-implemented my solution here,
ablewitt@187c225

**Comment by kingthorin** [comment]
@ablewitt thanks for reaching out. There is an existing PR, that's is close to done. If it turns out to be stalled or abandon we'll let you know.

**Comment by ablewitt** [comment]
thanks @RickM

I'm keen to get in contribute, I'll keep an eye out for other issues that
suit me.
