### ISSUE TITLE
Firefox launched from ZAP on Kali failing

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#6115]
First reported via https://groups.google.com/d/msg/zaproxy-users/gWXYGhBC3_s/D5Ojip4EAwAJ
Error reported by ZAP is: "Failed to start/connect to Firefix, is the browser available /supported"

It looks like the underlying cause is https://github.com/mozilla/geckodriver/issues/1756

Known workaround: 

1. Launch ZAP.
1. Goto Tools > Options.
1. Go down to the Selenium section.
1. In the Binaries > Firefox: field enter /usr/bin/firefox-esr
1. Click "Ok"  in the Options dialog to accept the changes.
1. Try launching Firefox from within ZAP.

**Comment by psiinon** [comment]
Have asked if its being worked on in https://chat.mozilla.org/#/room/#interop:mozilla.org

**Comment by kingthorin** [comment]
Ref: https://bugzilla.mozilla.org/show_bug.cgi?id=1649094

**Comment by psiinon** [comment]
Will hopefully be addressed by https://github.com/zaproxy/zap-extensions/pull/2604

**Comment by psiinon** [comment]
The new webdrivers have just been released. Can anyone confirm if this problem is now fixed on Kali?

**Comment by kingthorin** [comment]
I can confirm this works once again. Here's the situation/test:

1.  I launched ZAP and Firefox launched fine.
    - I checked the settings for the work around listed above. It was in place so I removed/cleared it.
2. I then tried to launch Firefox and it didn't launch.
3. I then applied the WebDriver update from the ZAP Marketplace, tried launching Firefox again and it worked :zap:
