### ISSUE TITLE
False Positive: Hidden File Found alerting on binaries like core dumps with HTTP 200 OK Html

### ISSUE THREAD

**Issue by globeone** [zaproxy/zaproxy#6116]
**Describe the bug**
A core file is an ELF binary file and never an HTML file.
When running a scan on 
https://url.domain.tld/somefolder/core
if the application is set to return HTTP 200 OK with an HTML Error page then the Hidden File Found flags with an alert.
For binary file types there needs to be a check to make sure it's not an HTML document to reduce false positives. 

**To Reproduce**
1. Go to a site one is scanning
2. Click on active scan
3. Wait for the scan to test for core files

**Expected behavior**
core files or other binaries should only flag if they are actually binaries and not HTML pages.

**Screenshots**
![image](https://user-images.githubusercontent.com/10052587/89644790-e70a1080-d8b8-11ea-8a21-4c421b96a3df.png)

**Software versions**
ZAP: D-2020-803

Add-on:
[2020-08-06_D-2020-803_InstalledAddons.xlsx](https://github.com/zaproxy/zaproxy/files/5041306/2020-08-06_D-2020-803_InstalledAddons.xlsx)

OS: Windows 10 19.09 18363.959

Java: Bellsoft Liberica JDK 14
java -version
openjdk version "14.0.2" 2020-07-14
OpenJDK Runtime Environment (build 14.0.2+13)
OpenJDK 64-Bit Server VM (build 14.0.2+13, mixed mode, sharing)

Browser:
Google Chrome: Version 84.0.4147.105 (Official Build) (64-bit)
Firefox: 79.0 (64-bits)

**Errors from the zap.log file**
[2020-08-06_URLDecoderIllegalHex_zap.log](https://github.com/zaproxy/zaproxy/files/5041310/2020-08-06_URLDecoderIllegalHex_zap.log)

**Additional context**
Here is the specification of a valid core file
https://www.gabriel.urdhr.fr/2015/05/29/core-file/

**Would you like to help fix this issue?**
Did some digging to find the "core" specification. happy to test any fixes.

**Comment by kingthorin** [comment]
Is the confidence High or Low for the alerts?

**Comment by globeone** [comment]
The Threshold was set to High

For the confidence I'm re-scanning as I had already marked them as False Positive. ♻️

**Comment by globeone** [comment]
![image](https://user-images.githubusercontent.com/10052587/89649530-3eac7a00-d8c1-11ea-9738-dc95c2c3e14d.png)

Confidence is Low.

Is there any way to turn of alerting for Confidence is Low? Threshold was already set to High
![image](https://user-images.githubusercontent.com/10052587/89649719-83381580-d8c1-11ea-8264-46126bf5c425.png)


The reason being is that we scan in a multi layered process as vendors will only fix the most pressing issues first in the "fear phase". The ones that can prove beyond a reasonable doubt.

So we whittle them down with

- SCAN with a tight profile with 0 false positives - fix most pressing
-- This build credibility and a willingness to fix issues
- RESCAN with a more relaxed profile - fix most pressing
-- here a repertoire is built up as a vendor is able to explain any false positives or mitigations
- RESCAN with a very relaxed profile - fix any outliers. 
-- here the relationship is good and a good healthy discussion on security can be formed

Vendors get really scared and angry with disbelief when vulnerabilities are found. Credibility in the reported findings is everything.

**Comment by kingthorin** [comment]
Confidence and Threshold are un-related. Those alerts are raised at LOW confidence because there was no content match, but there was a 200. They'd be HIGH confidence if the content match was also successful.

**Comment by globeone** [comment]
I was peaking in the OWASP_ZAP_D... `hidden_files.json` and it looks like it's already looking for the correct binary. Even with confidence LOW it shouldn't be flagging as the scanner knows exactly what to look for.

` {
      "path":"core",
      "binary":"\\x7fELF",
      "links":["https://en.wikipedia.org/wiki/Core_dump"],
      "type":"coredump",
      "source":"snallygaster"	
    },`

**Comment by kingthorin** [comment]
You need to read the help info on Threshold and Confidence, you still seem to be treated them as related and they completely aren't.

**Comment by globeone** [comment]
Point me to the help info on it and I'm happy to read it. 😄 
I realize they are two separate things, what I'm attempting to communicate is in real world scanning Threshold is less important than Confidence and that we need a way to set Confidence so that only High confidence findings are returned and the rest are left for when set to Medium or Low Confidence.

As a web security scanner scanning hundreds of websites removing low confidence false positives all day takes up too much time that I can rather be spending scanning other sites or using the more advanced features of ZAP to find more vulnerabilities.

**Comment by kingthorin** [comment]
The scan rule does know what to look for. Ex:
1. Check this path.
2. If 200 try to match content check.
- If the content check matches raise an alert with HIGH confidence (we're highly confident this is an actual problematic file).
- If the content check doesn't match raise an alert with LOW confidence (the server told us the file is there but it doesn't "look" like an actual problematic file, though we could be wrong.)

We "could" tie the second situation to [Threshold LOW](https://www.zaproxy.org/docs/desktop/ui/dialogs/options/pscanrules/), that's just not how it works today.

[Confidence ](https://www.zaproxy.org/docs/desktop/ui/dialogs/addalert/#confidence) = How sure we are about the result.
[Threshold ](https://www.zaproxy.org/docs/desktop/ui/dialogs/options/pscanrules/) = How willing or open the user is to False Positives/False Negatives.

Making such a change would be somewhat aligned with other recent changes:
https://github.com/zaproxy/zap-extensions/pull/2510
https://github.com/zaproxy/zap-extensions/pull/2493
https://github.com/zaproxy/zap-extensions/pull/2483

Though I say specifically "somewhat" because those all deal with non-200 response types. Really you should get the app fixed to handle 404s in an RFC compliant manner.

**Comment by globeone** [comment]
> Though I say specifically "somewhat" because those all deal with non-200 response types. Really you should get **the app** fixed to handle 404s in an RFC compliant manner.

LOL. Ok, in the real world very few developers follow RFC 404 anymore because it's in itself a become a security vulnerability. A hacker is then able to enumerate the pages on your website. When returning HTTP 200 to everything there is no way to count the files.
Most all modern applications return HTTP 200 these days with a custom error page in HTTP 200 OK. This also has to do with how some content delivery networks work.

**The app** is funny as we have more than 1000 internal apps and another 1000 external apps. All with different programming teams and programming methods. I love standards as much as the next guy (believe me, I've had my rants about standards) but very few developers are going to follow all the standards. 😄

**Comment by globeone** [comment]
https://www.zaproxy.org/docs/desktop/ui/dialogs/options/pscanrules/

This controls how likely ZAP is to report potential vulnerabilities.

If you select Off then the scanner won't run.
If you select Low then more potential issues will be raised which may increase the number of false positives.
**If you select High then fewer potential issues will be raised which may mean that some real issues are missed (false negatives).**

⏫ This is what I'm looking for. Threshold High, no false positives.

If the Confidence is High then ZAP is sure of the result and it's not a false positive right?

**Comment by kingthorin** [comment]
> ⏫ This is what I'm looking for. Threshold High, no false positives.

No DAST product is false positive free, despite claims. If there are situations we know of where false positives are more likely or possible then yes at HIGH threshold you should see fewer or none. However that may also mean you are getting false negatives.

> If the Confidence is High then ZAP is sure of the result and it's not a false positive right?

Not necessarily, it means ZAP is "more" sure that it's a true positive. That's part of why we have user set confidences of "Confirmed" and "False Positive". In very broad strokes we could say (and this is just me ... I haven't discussed this with anyone else in the core team); but, you could assume something like:
- Medium = 51%, or maybe more like 65% (more than half) sure.
- Low = Less than half sure.
- High = More than 80% sure.

You might want to learn about Alert Filters as well:
- https://www.zaproxy.org/docs/desktop/addons/alert-filters/
- https://groups.google.com/g/zaproxy-users/c/mK1oiWO0fLk/m/K-RG2hr7CQAJ

**Comment by globeone** [comment]
✅  The alert filters look great, I'll try them out, thanks for creating that feature.

😟  Am kind of concerned that if people create global alert filters in private that doesn't help the ZAP project or other security researchers running into the same issues with false positives when programming standards/habits change.

📆  Like for this specific issue, when around 3 years ago many in the enterprise web development community started serving HTTP 200 OK for everything and stopped using HTTP 404 NOT FOUND.

🎏 When a scan comes back completely clean with only Informational alerts, that's the red flag 🎏 when we start hunting for False Negatives. Then it's a matter of lowering the threshold and doing some manual hunting.

🌍  There are real world consequences for the results that ZAP produces. Security teams everywhere are small, overworked and don't have a lot of extra time. Vendors get overwhelmed if you show them all their vulnerabilities at once they end up fixing one thing or nothing with their already stretched development teams. 

🤖  So anything to automate the repetitive (like reducing and removing or even just grouping false positives on the report as they are in the tool) helps enormously.  

💯 Agreed that DAST (Dynamic Application Security Testing) is not going to be 100% free of false positives at our current level of technology. Competing tools like Netsparker (using proofs) and Immuniweb (using machine learning) get really, really close though and ZAP with the power of the community can reach that same level or better quality.

**Comment by kingthorin** [comment]
So here's the plan:

- Builtin checks with content checks will alert with HIGH confidence if both conditions are met (for any threshold).
- Builtin checks that only match path (200) will alert at LOW confidence (only at HIGH threshold).
- User added payloads/checks alert at LOW confidence (for any threshold).
