### ISSUE TITLE
Active Scan Policy stays grayed out to Default after creating a new scan policy

### ISSUE THREAD

**Issue by globeone** [zaproxy/zaproxy#6117]
**Describe the bug**
For a false positive I needed to run a rescan of just one Active Scan policy. In the Tabs I started a new 
Active scan tab. But the option to use the newly created policy remains greyed out.

**To Reproduce**
Clicked on the 
![image](https://user-images.githubusercontent.com/10052587/89647413-d5773780-d8bd-11ea-9e3d-974978ed95bc.png) icon and created a new scan policy with only one rule "hidden file detection"

![image](https://user-images.githubusercontent.com/10052587/89647707-3f8fdc80-d8be-11ea-931e-63322ead308e.png)

![image](https://user-images.githubusercontent.com/10052587/89647493-f0e24280-d8bd-11ea-9edc-1c6acb022849.png) 

I then clicked on the new scan Icon and selected a Starting Point which is not allowing me to select the new scan policy

![image](https://user-images.githubusercontent.com/10052587/89647730-4d456200-d8be-11ea-833e-adbc4fc83944.png)

**Expected behavior**
After creating a new scan policy it would be nice to be able to use said scan policy right away.

**Screenshots**
Inline 

**Software versions**
ZAP: D-2020-803

Add-on:
[2020-08-06_D-2020-803_InstalledAddons.xlsx](https://github.com/zaproxy/zaproxy/files/5041471/2020-08-06_D-2020-803_InstalledAddons.xlsx)

OS: Windows 10 19.09 18363.959

Java: Bellsoft Liberica JDK 14
java -version
openjdk version "14.0.2" 2020-07-14
OpenJDK Runtime Environment (build 14.0.2+13)
OpenJDK 64-Bit Server VM (build 14.0.2+13, mixed mode, sharing)

Browser:
Google Chrome: Version 84.0.4147.105 (Official Build) (64-bit)
Firefox: 79.0 (64-bits)

**Errors from the zap.log file**
[2020-08-07_ActiveScan_No_New_Policy_zap.log](https://github.com/zaproxy/zaproxy/files/5041506/2020-08-07_ActiveScan_No_New_Policy_zap.log)

**Additional context**
Related to : #6116
In the sense that I was trying to rescan to provide more data.

**Would you like to help fix this issue?**
Got lots to test with, so happy to test.

**Comment by thc202** [comment]
With Advanced Options selected you need to choose the policy from the Policy tab.

**Comment by globeone** [comment]
🤔 Ok, that's odd. What's the thinking behind not being able to select it from both the Scope and Policy tabs?

**Comment by kingthorin** [comment]
I suspect it's because sync between the two tabs is a challenge. Gotta know which one was changed most recently and update the other.

**Comment by globeone** [comment]
Could we click on the greyed out policy box and have it automatically switch to the Policy tab?

**Comment by rahulk22** [comment]
Is this issue fixed? Is there any other way of getting around this bug?

**Comment by kingthorin** [comment]
Nope.

Yes, use the advanced options.

**Comment by rahulk22** [comment]
I am facing this issue on Mac OS with zap 2.90

**Comment by rahulk22** [comment]
How to use advanced options? Where to go to see these advanced options?

**Comment by rahulk22** [comment]
My issue is after creating a new security policy using security policy manager, I am exporting it to my desktop folder on Mac. Now I am deleting this policy from policy and manager and trying to import from desktop. But the open file window for import is not showing policy file earlier exported there.

**Comment by kingthorin** [comment]
What Open file dialog?

**Comment by rahulk22** [comment]
![Uploading 7DE9750F-811C-4719-9AE6-9DD02B5C4F5E.jpeg…]()

**Comment by rahulk22** [comment]
<img width="938" alt="Screen Shot 2020-09-28 at 2 45 30 PM" src="https://user-images.githubusercontent.com/42449799/94489644-b4361780-0199-11eb-98dd-a2d2ab8362b8.png">

**Comment by kingthorin** [comment]
The only thing I can say is you seem to be in `Downloads` not `Desktop`.

![scan_policy](https://user-images.githubusercontent.com/7570458/94496446-5bc74000-01c2-11eb-9a5d-9f91282bb263.gif)

**Comment by rahulk22** [comment]
Accidentally I uploaded an image showing download folder. Desktop folder is also showing empty same as download folder.

**Comment by psiinon** [comment]
@rahulk22 you're using a Mac right? In which case its probably a Mac folder permissions thing.
ZAP womnt be able to see the contents of these folders unless your OS allows us to. Nothing we can do about it - you'll need to fix your folder perms. Although I'm using a Mac now I'm no expert, so I cant give much more help than that right now :/

**Comment by rahulk22** [comment]
Yup I am using Mac OS Catalina.

Regards,
Rahul Kojrekar

**Comment by psiinon** [comment]
OK, let us know if you work out how to fix the OS perms then...

**Comment by rahulk22** [comment]
I checked the Files and Folders section of my mac. See the screenshot. It doesn't list OWASP ZAP here and it's not letting me add any other app. + and - buttons are grayed out.
<img width="667" alt="Screen Shot 2020-09-29 at 10 12 35 AM" src="https://user-images.githubusercontent.com/42449799/94590982-4db60580-023c-11eb-9f09-b364e286b5e6.png">

**Comment by psiinon** [comment]
I do have OWASP ZAP included, but also can't see a way to add new programs from this screen.
However it looks like I can add programs via the "Full Disk Access" panel so try doing that...

**Comment by rahulk22** [comment]
I was able to export the policy file in a folder created under my user directory and export it from there. But still not able to export from desktop or downloads directories even after giving full disk access. I don’t see policy file stored under these folders.

**Comment by kingthorin** [comment]
Sadly, that’s an operating system issue not a ZAP issue.
