### ISSUE TITLE
Proxy listening error by default on Windows 10

### ISSUE THREAD

**Issue by irsdl** [zaproxy/zaproxy#6118]
**Describe the bug**
I get the following error despite the fact that the listening ports are free:
![image](https://user-images.githubusercontent.com/1798313/90016461-ecdd6880-dca1-11ea-947a-829e76179150.png)

**To Reproduce**
1. Install ZAP x64 installer on Windows 10 
2. Open ZAP
3. See the proxy listening error
4. Change the port and see the error again

**Expected behavior**
It should just start listening without being run under an elevated privilege.

**Software versions**
 - ZAP: 2.9.0
 - Add-on: all default
 - OS: Windows 10
 - Java: jre 1.8.0_261

**Comment by kingthorin** [comment]
Were you prompted to allow Java or ZAP to make firewall changes or something like that? (Did you say no?)

I'll see if I can find a screenshot that shows what I'm talking about.

I'm guessing that you're hitting a Windows Firewall (or AV Firewall) issue.

**Comment by kingthorin** [comment]
Something like this:
![img_5d41e693163ac 1](https://user-images.githubusercontent.com/7570458/90017371-6dd43a00-dc79-11ea-908c-30effb2d8f64.png)

**Comment by irsdl** [comment]
I had selected Allow but as I have just updated Windows this has happened. I have this problem with everything at the moment so I guess it is just me!

**Comment by kingthorin** [comment]
Thanks for letting us know.

**Comment by psiinon** [comment]
Thanks for letting us know. And hope you enjoy learning a bit more about ZAP :)
We've got lots of info on https://www.zaproxy.org/ and a load of videos on https://www.alldaydevops.com/zap-in-ten

**Comment by irsdl** [comment]
Apparently this is an issue that can happen in Windows: https://dandini.wordpress.com/tag/administered-port-exclusions/

So to see which ports are restricted:
```
netsh int ipv[46] show dynamicport tcp
```

To fix the issue (make sure you can understand the underlying security / functional issues):

```
reg add HKLM\SYSTEM\CurrentControlSet\Services\hns\State /v EnableExcludedPortRange /d 0 /f
```

Then reboot.

Not sure why this just happened to me after installing this patch Tuesday.
