### ISSUE TITLE
Outgoing proxy usage with credentials is broken in "Force Browse Site" causing 501 and 407 errors

### ISSUE THREAD

**Issue by wadim-al** [zaproxy/zaproxy#6120]
**Describe the bug**
If outgoing proxy is used with credentials and Forced Browse Site is called on a tested domain the following types of errors are shown from the proxy:

In the first scanned response:
HTTP/1.1 501 Not Implemented
Unsupported Request Method and Protocol

2nd and all further ones:
HTTP/1.1 407 Proxy Authentication Required
Cache Access Denied.

Impact: this forces me to write my own python script to dirbust with proxy support, or to load directories list as a payload to fuzzer configured to fuzz the URL path, which is slow and ineffective because of time taken to set up the fuzzer. "Force Browse Site" is an essential tool for testing and can't be used right now.

**To Reproduce**
1. Go to Settings and configure the outgoing proxy using its ip, port, login and password. It should be squid 3.5.12 hosted externally
2. In browser which proxies through 8080 port of OWASP ZAP open URL for the tested site.
3. In OWASP ZAP right-click the first browser's call to URL in the History tab and click Attack - Force Browse Site
4. See errors in scan results

**Expected behavior**
external squid proxy authentication is handled correctly when using "Force Browse Site"

**Screenshots**
![java-2020-08-14-10-14-30](https://user-images.githubusercontent.com/29713984/90223766-56cb4e80-de17-11ea-90b0-1204a38365c5.png)
![java-2020-08-14-10-14-35](https://user-images.githubusercontent.com/29713984/90223771-57fc7b80-de17-11ea-958b-903e66b36670.png)

**Software versions**
 - ZAP: D-2020-08-10
 - Scanner: Force Browse Site
 - OS: Windows 10 x64 2004
 - Java: Oracle JRE 1.8.0_251 both  x32 x64
 - Browser: FF 79 x64

**Errors from the zap.log file**
[log.txt](https://github.com/zaproxy/zaproxy/files/5073168/log.txt)

**Additional context**
This was encountered in D-2020-06-08 too

**Would you like to help fix this issue?**
Yes.

**Comment by thc202** [comment]
Closing with the changes done in #3060.

Feel free to reopen or leave a comment if you are still seeing this issue.
