### ISSUE TITLE
html encode in Generate anti-CSRF Test FORM

### ISSUE THREAD

**Issue by knassar702** [zaproxy/zaproxy#6121]
hi team

you can add html encode for `double quote` in Generate anti-CSRF Test FORM 

i've create a CSRF form and add a xss payload
![Screenshot at 2020-08-14 21-05-22](https://user-images.githubusercontent.com/45688522/90284212-28726100-de61-11ea-9a72-1e25d3df649d.png)

 but when add  qoute `"` in payload 
![Screenshot at 2020-08-14 20-56-42](https://user-images.githubusercontent.com/45688522/90284114-f06b1e00-de60-11ea-8bba-f4874491aa57.png)

burpsuite encode qoute

you shloud encode it

like that
`<input type='text' name='search' value="<img src=x onerror=&quot;alert('knassar702')&quot;>">`

**Comment by securityhook** [comment]
Same issue here.

**Comment by thc202** [comment]
Reopening as it was not addressed yet.
