### ISSUE TITLE
http sender did not intercept first request from active scan

### ISSUE THREAD

**Issue by ky0112** [zaproxy/zaproxy#6123]
When using anti-CSRF script from [community script](https://github.com/zaproxy/community-scripts/blob/master/httpsender/Capture%20and%20Replace%20Anti%20CSRF%20Token.js) with an active scan, the http sender will not intercept and not replace the anti-CSRF the first request from active scan. The anti-CSRF token will only replace correctly on the second request from active scan.

**Comment by psiinon** [comment]
Do you have a test case (or publicly available app) that we can use to reproduce this issue?
If not, can you confirm that the HTTP sender script is definitely not invoked for the first request? You may need to add extra diagnostics in the script in order to check this.

**Comment by ky0112** [comment]
Suspect that when running active scan with http sender, the active scan will replay once of the captured request in the context which had old anti-CSRF token. Even with http sender script, the http sender script will not invoke the first request from the active scan. 

Test case:
1. Load the http sender script
2. ZAP active scan > a request (have anti-CRSF token)
3. **Zap flow, Zap will replay this request to attack. Since request have old session and old anti-CRSF. Application will response invalid session/token. Zap will perform authentication(have anti-CSFR token; http sender capture/replace anti-CSRF token correctly) then zap will grab the valid session replay the request with valid session but with old anti-CRSF token which from the captured context request. Cause invalid anti-CSRF token and the session become invalid.
4. Then only the http sender kick it and replace the anti-CSRF token for upcoming request. Get invalid session due to previous request.

This will cause problem since some application will match valid session with valid anti-CSRF token. If the anti-CSFR token is invalid then session will be invalided too.

**Comment by kingthorin** [comment]
I don't see a way around this. Unless you (as an end user) prime the script with a valid value. Zap has to request content in order to get the token to then use.

**Comment by kingthorin** [comment]
This seems to be working as intended, per discussion amongst the team.
