### ISSUE TITLE
Persistent growing high CPU usage with proxy

### ISSUE THREAD

**Issue by wadim-al** [zaproxy/zaproxy#6138]
**Describe the bug**
High CPU usage 25% (1 full core) is observed after ZAP starts and proxies a WebSocket request from Firefox.
With passive scan configured to scan only in-scope objects, and none domains added to scope, after fuzzer scan finishes, 50% constant CPU usage is observed.
After a while, CPU utilization rises to 75% (3 full cores out of 4)

**To Reproduce**
1. Start ZAP 
2. Configure Passive scanner to scan only in-scope objects
3. Close ZAP
4. Restart ZAP
5. Open Firefox
6. Observe Firefox calls a WebSocket and gets response
7. Check ZAP CPU utilization
8. Fuzz some site with 2000 payloads
9. After fuzzing finishes, check CPU utilization
10. Wait 10 minutes.
11. Check CPU utilization

**Expected behavior**
ZAP when there is no active|passive jobs to do shouldn't utilize full cores of CPU.

**Screenshots**
![Taskmgr-2020-08-23-10-37-44](https://user-images.githubusercontent.com/29713984/90973654-c387cc80-e52c-11ea-85f2-e89a6fee32ff.png)

**Software versions**
 - ZAP 2.9.0 Release, ZAP_WEEKLY_D-2020-06-15, w2020-08-17
 - OS: Windows 10 x64 2004
 - Java: Oracle JRE 1.8.0_251 both x32 x64
 - Browser: Firefox 79 x64

**Errors from the zap.log file**
No errors in log, but uploading it for the purpose of identifying the running plugins
[log.txt](https://github.com/zaproxy/zaproxy/files/5113656/log.txt)

Here are 5 dump traces for 25% CPU Ut., 5 other for 50% and 5 for 75%.
[traces.txt](https://github.com/zaproxy/zaproxy/files/5113657/traces.txt)

**Additional context**
Occures on 3 different 2.9.0 builds including latest weekly.
Further testing showed that this doesn't occur with freshly installed ZAP with fresh configuration. I will add further info if I find the problematic plugin/configuration.

**Would you like to help fix this issue?**
Yes.

**Comment by wadim-al** [comment]
@thc202 could you please tell how to send the links to the uploaded dumps privately?

**Comment by wadim-al** [comment]
UPDATE: problem persists even after disabling passive scanner, and deleting most of the plugins.
The list of remaining ones:
![java-2020-08-24-11-15-25](https://user-images.githubusercontent.com/29713984/91020518-395a6980-e5fb-11ea-85e2-9a88ce9c2abd.png)

**Comment by thc202** [comment]
Email and public key to encrypt if needed:
https://keyserver.ubuntu.com/pks/lookup?search=0xC650B2EB170CE36613A164FAF29DBD3500548AA2&fingerprint=on&op=index

If the problem is in the proxy it doesn't matter the add-ons installed.

**Comment by wadim-al** [comment]
1) Please check your email for dumps. My proxy credentials and address are private information.
2) UPDATE:
I'm using an outgoing proxy, and after I've disabled the auto-update extension, I can't reproduce the problem. It seems that outgoing proxy blocks the auto-update and causes the high CPU usage. I never can update when connected to this proxy.

**Comment by wadim-al** [comment]
Update:
disabling all extensions (excluding dynssl) didn't help too.

**Comment by thc202** [comment]
Thanks for sharing the dumps.
