### ISSUE TITLE
Expose CWE Ids for cookie alerts

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#6140]
As per https://groups.google.com/g/zaproxy-users/c/9Lb1EvOWhMw/m/lzLXYKG2GAAJ

> the ZAP scan rules 10010 (Cookie No HttpOnly Flag) and 10011 (Cookie Without Secure Flag) seem to detect respectively CWE 1004 and 614. However the detail pages of the two alerts do not link the corresponding CWE values

The relevant code is:

- https://github.com/zaproxy/zap-extensions/blob/master/addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CookieHttpOnlyScanRule.java
- https://github.com/zaproxy/zap-extensions/blob/master/addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CookieSecureFlagScanRule.java

CWEs are easy to add, eg as per https://github.com/zaproxy/zap-extensions/blob/master/addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/DirectoryBrowsingScanRule.java#L157-L160

**Comment by martinspielmann** [comment]
Not 100% sure, but for me it seems CWE and WASC ID are managed already:
![image](https://user-images.githubusercontent.com/1359917/91911913-5a355580-ecb2-11ea-89a4-b2f692aa2849.png)


I think the "detail pages" in the issue descriptions refer to these ones: https://www.zaproxy.org/docs/alerts/ 
If so, the scope is bigger than thought as CWE links not only missing for cookie alerts, but for all alerts of type "Passive Scan Rule".

Would love to contribute, but not sure how these detail pages are generated. Can you provide a hint here?

**Comment by psiinon** [comment]
Ah yes.
The problem is that are set inline https://github.com/zaproxy/zap-extensions/blob/master/addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CookieHttpOnlyScanRule.java#L97-L98
This means that the script which generates the docs cant find them.
If they are put in functions called `getCweId()` and `getWascId()` then they will get included in the docs :)

**Comment by martinspielmann** [comment]
Ah, I see. Thank you! PR incoming :smiley:
