### ISSUE TITLE
[Zap Client API] installLocalAddon() method is not working

### ISSUE THREAD

**Issue by taehongmin** [zaproxy/zaproxy#6148]
**Describe the bug**
I received the cutom zap addon file from the security team. I'm trying to install this add on using 'Zap Client API'. when enter the path of the '.zap' file in the 'installLocalAddon()' method parameter, addon was not installed

**To Reproduce**
1. delete installed 'ascanrules' addon(it works well)
2. try to install custom addon file(name is 'ascanrules-release-33.0.9.zap') using installLocalAddon() method
![image](https://user-images.githubusercontent.com/55980540/91471039-76ab4980-e8d0-11ea-8a74-811f6d2e1b5d.png)

**Expected behavior**
adon is installed

**Screenshots**
![image](https://user-images.githubusercontent.com/55980540/91471787-7d868c00-e8d1-11ea-8b7b-6d6ec30bf115.png)

**Software versions**
 - ZAP: 2.9.0
 - Zap-ClientApi: 1.8.0
 - OS: Windows 10
 - Java: java 13 2019-09-17

**Comment by thc202** [comment]
That endpoint is only available when ZAP is started in dev mode (`-dev`) or running from source.

**Comment by taehongmin** [comment]
Thanks you! it's works well on dev mode
