### ISSUE TITLE
Option -I not recognized

### ISSUE THREAD

**Issue by phgeraldeli** [zaproxy/zaproxy#6149]
When using following command:

sudo docker run --rm -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-weekly zap-api-scan.py -t target -f openapi -c ./zap-rules/api-rules.conf -r security_report.html -I

I got this error:
      Invalid option I : option -I not recognized
      Usage: zap-api-scan.py -t <target> -f <format> [options] -t target         target API definition, OpenAPI or SOAP, local file or URL, eg https://www.example.com/openapi.json

I tried with stable and weekly, but they have the same problem. I'm using jenkins and docker to run zap on my API.

**Comment by kingthorin** [comment]
Is the a capital I or a lower L?

**Comment by phgeraldeli** [comment]
Capital i

**Comment by kingthorin** [comment]
Which weekly have you tried?
It wouldn't be in stable but should be in all weeklies after April 8th:
https://github.com/zaproxy/zaproxy/commits/develop/docker/zap-api-scan.py

**Comment by phgeraldeli** [comment]
> Which weekly have you tried?
> It wouldn't be in stable but should be in all weeklies after April 8th:
> https://github.com/zaproxy/zaproxy/commits/develop/docker/zap-api-scan.py

Yeah, that's why is soo odd. I don't use version label at all, just owasp/zap2docker-weekly.

**Comment by kingthorin** [comment]
So it works with latest werkly?

**Comment by thc202** [comment]
If not, it would be great if you could provide the image ID. I just tested with latest weekly and it worked (image ID `e28d16bb8a60`).

**Comment by phgeraldeli** [comment]
I tested with latest weekly, realize it only happens with full command:

sudo docker run --rm -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-weekly zap-api-scan.py -t target -f openapi -c ./zap-rules/api-rules.conf -r security_report.html -I

**Comment by thc202** [comment]
That works as well, are you sure that in Jenkins is also using the latest weekly? (Maybe it's using an older cached image?)

**Comment by phgeraldeli** [comment]
> That works as well, are you sure that in Jenkins is also using the latest weekly? (Maybe it's using an older cached image?)

Probably. I just cleaned up all my images and tried again. It Works! 

Thanks!!

**Comment by phgeraldeli** [comment]
I'm running zap on Openshift and pulling tag 2.9.0 and still isn't working.

How to reproduce:

zap.yaml

![image](https://user-images.githubusercontent.com/22543429/93782436-f2af5d80-fc00-11ea-8b88-fd3aaa9495e7.png)

Openshift Events

![image](https://user-images.githubusercontent.com/22543429/93782254-b5e36680-fc00-11ea-91e4-ef765f06d2a7.png)

Job Log

![image](https://user-images.githubusercontent.com/22543429/93782577-1c688480-fc01-11ea-8ee3-037a091c2e9b.png)

When i run with docker run locally using latest, it works. What could be happening?

**Comment by kingthorin** [comment]
The change/fix is available in latest 😉 

It won't be back ported.

**Comment by phgeraldeli** [comment]
Thanks!
