### ISSUE TITLE
Reporting: Missing evidence field on Customize HTML Report

### ISSUE THREAD

**Issue by globeone** [zaproxy/zaproxy#6151]
**Describe the bug**
The "Customize HTML Report Option" is missing the `evidence` field which is necessary for the receiver of the report to know where they need to solve the issue.

In this example, the HTML source code of the page is several thousand lines of code the report is Reverse Tabnabbing so the developer will need to know which anchor `<a>` tag to fix. Unfortunately, the evidence field isn't in the report so the report is not useful for solving the issue. Adding the Body field makes the report to long and unreadable, and without highlighting there is still no way to easily solve the issue.

**To Reproduce**
1. Browse through a site with the HUD to gather some alerts with Reverse Tabnabbing
2. Click on Create HTML Report
3. Scroll down to Remove all the alerts except Reverse Tabnabbing to make the report small and readable
4. Observer that there is no Evidence field showing the location of what needs to be fixed

**Expected behavior**
The evidence field should be included on the report to make the lives of developers trying to solve the security issues easier.

**Screenshots**

### Customize HTML Report
![image](https://user-images.githubusercontent.com/10052587/91550853-7db27600-e929-11ea-9930-adee7b1cd30c.png)

### Generate Report (with mockup of Evidence option)
![image](https://user-images.githubusercontent.com/10052587/91550879-886d0b00-e929-11ea-86b7-6328cbef514e.png)

### Location of data to put on the report
![image](https://user-images.githubusercontent.com/10052587/91551101-ef8abf80-e929-11ea-9851-3d2fa1f7da5b.png)

### Mockup with desired outcome
![image](https://user-images.githubusercontent.com/10052587/91551051-d4b84b00-e929-11ea-97c6-3d4d9ff7058d.png)

**Software versions**
 - ZAP: zap-D-2020-08-26
 - Add-on: 
[2020-08-28_D-2020-08-26_InstalledAddons.xlsx](https://github.com/zaproxy/zaproxy/files/5141563/2020-08-28_D-2020-08-26_InstalledAddons.xlsx)

 - OS: Windows 10 18363.1016
 - Java: 
openjdk version "14.0.2" 2020-07-14
OpenJDK Runtime Environment (build 14.0.2+13)
OpenJDK 64-Bit Server VM (build 14.0.2+13, mixed mode, sharing)
 - Browser: 
Google Chrome Version 84.0.4147.135 (Official Build) (64-bit)
Firefox 80.0 (64-bits)

**Errors from the zap.log file**
[2020-08-28zap.log](https://github.com/zaproxy/zaproxy/files/5141703/2020-08-28zap.log)

**Additional context**

**Would you like to help fix this issue?**
Happy to test.

**Comment by psiinon** [comment]
Ooops :)
FYI for anyone interested in looking at this, the code is in https://github.com/zaproxy/zap-extensions/tree/master/addOns/customreport/src/main/java/org/zaproxy/zap/extension/customreport

**Comment by psiinon** [comment]
Thanks for this - very well described :) I've just tweeted about it to see if we can get someone new to look at it: https://twitter.com/psiinon/status/1299305855943413760

**Comment by globeone** [comment]
I had a look at the extension, thinking it was just a quick field reference. But how do we know which field is the evidence field?

Is it as easy as:

`public boolean evidence() {
        return alertDetailstab.evidence();
    } ` 

and then fixing the JPanels to contain the switch?

**Comment by kingthorin** [comment]
Not quite that easy. In addition to your one line:

https://github.com/zaproxy/zap-extensions/blob/master/addOns/customreport/src/main/java/org/zaproxy/zap/extension/customreport/AlertDetailsPanel.java would need to be modified to include a checkbox for it.

https://github.com/zaproxy/zap-extensions/blob/master/addOns/customreport/src/main/java/org/zaproxy/zap/extension/customreport/ReportLastScan.java would need to be modified to check whether the option is enabled and include the field if the user does want it.

**Comment by thc202** [comment]
And change the XSLs to include that.

**Comment by PeteBoucher** [comment]
Opened a PR with my first pass at a solution. Any and all feedback much appreciated.
