### ISSUE TITLE
OpenAPI add-on Import Needs to Handle Missing/Empty Servers Block

### ISSUE THREAD

**Issue by davewichers** [zaproxy/zaproxy#6152]
**Describe the bug**
Per the Swagger spec (https://swagger.io/specification/) as stated: "servers - An array of Server Objects, which provide connectivity information to a target server. If the servers property is not provided, or is an empty array, the default value would be a Server Object with a url value of /."

The 'servers' block of a swagger doc is optional, but the OpenAPI add-on Import can't handle that, but it should.

**To Reproduce**
Import an OpenAPI spec with a missing or empty 'servers' block.

**Expected behavior**
My suggestion is that the plugin detect that it is missing or empty, and pop up a dialog saying something like, 'no servers are specified in this spec', please enter the URL of the target server you wish to test.

On a related note, I haven't tested a spec with multiple servers. ZAP should handle that too by saying something like, "multiple servers are defined in this spec. Which one do you want to test?" And provide a list of servers as defined to pick from. Or maybe even a checkbox list of URLs so the user can check off more than one?

**Comment by thc202** [comment]
Closing, this was done as part of #6754. The user is informed when there are no servers (when importing from local definition, from remote it's used the target server), for multiple servers they are all imported.
