### ISSUE TITLE
Export bug for XML files - observed while testing OWASP benchmark

### ISSUE THREAD

**Issue by DomKoe** [zaproxy/zaproxy#6155]
**Describe the bug**
Vulnerabilities detected by OWASP ZAP are not correctly exported into the XML file. 

**To Reproduce**
1. Go to 'Scan Policy Manager' and select for example XSS or SQLi options.
2. Start OWASP benchmark.
3. Use spider to crawl benchmark at https://localhost:8443/benchmark or use the OpenAPI function.
4. Attack folder like xss-00 until  xss-05/ sqli-00 until sqli-06.
5. Export the results in a xml file 
6. Create a Scorecard for it, with OWASP benchmark, using the createScorecard cmd/sh file. The xml has to be copied before into the folder results.
7. Compare the OWASP ZAP Session with the created Scorecard and click on the created .csv file, which indicates the expected results for each testcase.
8. Observe that in the XML file, found vulnerabilites with OWASP ZAP are not correctly exported.

**Expected behavior**
I expected to better results with OWASP ZAP which brought me to look for an error. 

**Screenshots**
Example showing  multiple XSS cases, which were correctly deteced but not exported by ZAP.
![bug_example](https://user-images.githubusercontent.com/15998138/91887799-8b4e5f80-ec8b-11ea-84b9-b11dd8f65bc5.PNG)

**Software versions**
 - ZAP: weekly release 26-08-2020
 - OS:  Windows 10
 - Java: openjdk version "1.8.0_261"
 - Browser: -

**Would you like to help fix this issue?**
I would like to fix / contribute to fixing this issue.

**Comment by thc202** [comment]
What settings were used to create the report? Did you increase the option Options > Alert > Max alert instances in report ?
https://www.zaproxy.org/docs/desktop/ui/dialogs/options/alert/#max-alert-instances-in-report

**Comment by DomKoe** [comment]
Damn, I did not export all my settings to the latest weekly release - my bad.

**Comment by AbhishekPuranam** [comment]
@DomKoe : did u generate the scorecard ?

**Comment by DomKoe** [comment]
@AbhishekPuranam Yes, all solved.
