### ISSUE TITLE
CustomReport: Report may include "seeming" duplicates

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#6158]
Since alert fields/details are optional the generated report may include what seem to be duplicates if details such as param, attack, evidence are excluded from the generated output.

https://github.com/zaproxy/zap-extensions/tree/master/addOns/customreport

**Comment by kingthorin** [comment]
Related to: zaproxy/zap-extensions#2528

**Comment by thc202** [comment]
Closing, the Custom Report add-on is being superseded by the Report Generation add-on:
https://www.zaproxy.org/docs/desktop/addons/report-generation/
