### ISSUE TITLE
Docker scripts should create and use a context when none specified

### ISSUE THREAD

**Issue by dicksnel** [zaproxy/zaproxy#6159]
**Is your feature request related to a problem? Please describe.**

The docker scripts do not use a default context when they are performing a spider or scan action:

If no contextfile is provided, context_name and context_id will be empty:

https://github.com/zaproxy/zaproxy/blob/ea06bfe1a01c505063c75f441e869721fb64a7ff/docker/zap_common.py#L381

https://github.com/zaproxy/zaproxy/blob/ea06bfe1a01c505063c75f441e869721fb64a7ff/docker/zap_common.py#L395

https://github.com/zaproxy/zaproxy/blob/ea06bfe1a01c505063c75f441e869721fb64a7ff/docker/zap_common.py#L407

With this setup, hooks are not able to use a context to for example include or exclude specific URL's.

**Describe the solution you'd like**

The docker scripts should use a default context if no contextfile is provided, example:

`context_name = 'docker-context'`

This allows hooks to use this context and manipulate it, for example from within a hook:

`zap.context.exclude_from_context('docker-context', 'http://xxx.*')`

**Would you like to help implementing this feature?**
Yes

**Comment by thc202** [comment]
It's possible for the hooks to create a context and use it.

**Comment by dicksnel** [comment]
@thc202 do you have an example of how this should be done?

I have the following code:

```
# create a new context
contextName = 'auth'
zap.context.new_context(contextName)

# include everything below the target
zap.context.include_in_context(contextName, "\\Q" + target + "\\E.*")
logging.info('Context - included ' + target + ".*")

# exclude url
zap.context.exclude_from_context(contextName, ''.*logout.*'')

# set the context in scope
zap.context.set_context_in_scope(contextName, True)
zap.context.set_context_in_scope('Default Context', False)
```

It is executed from a hook on zap_access_target. But this context will be ignored by the spider and scanner.

**Comment by thc202** [comment]
You can set the name/id after creating the context, e.g.:
```Python
import zap_common

# ...

context_name = 'auth'
context_id = zap.context.new_context(context_name)

zap_common.context_name = context_name
zap_common.context_id = context_id

# remaining context configs

```

**Comment by dicksnel** [comment]
I have the following simple hook on zap_access_target:

```
import zap_common

def zap_access_target(zap, target):
    context_name = 'auth'
    context_id = zap.context.new_context(context_name)

    zap_common.context_name = context_name
    zap_common.context_id = context_id
    
    # this does not work, sitemap.xml is in the spider results
    zap.context.exclude_from_context(context_name, '.*sitemap.*')

    # this works, no sitemap.xml in the spider results
    #zap.spider.exclude_from_scan('.*sitemap.*')
    #zap.ascan.exclude_from_scan('.*sitemap.*')

    return zap, target
```

If I am using the context, the excludes won't work (same for includes). Is there something missing from my example?

**Comment by thc202** [comment]
That hook would not work since nothing is being added to the context, if the spider scan is being started anyway (which seems to be the case) it means that you are not using the latest scripts, the scan/use of the context is only available in weekly and live Docker images (or if you use the scripts from develop).

**Comment by dicksnel** [comment]
I didn't notice support for the context was recently added, I was not using the latest zap2docker-weekly docker image. It is working perfectly now:

```
import zap_common

def zap_access_target(zap, target):
    context_name = 'auth'
    context_id = zap.context.new_context(context_name)

    zap_common.context_name = context_name
    zap_common.context_id = context_id
    
    # include the target
    zap.context.include_in_context(context_name, target + '.*')

    # exclude some stuff
    zap.context.exclude_from_context(context_name, '.*sitemap.*')

    return zap, target
```

Many thanks @thc202 !
