### ISSUE TITLE
How to remove/uninstall ZAP from Ubuntu?

### ISSUE THREAD

**Issue by PraneshASP** [zaproxy/zaproxy#6165]
I cant find any command or file to completely remove/uninstall zap and its dependencies from Ubuntu 18.04. How can I do this?

**Comment by kingthorin** [comment]
How did you install it to start with?

**Comment by PraneshASP** [comment]
I installed using the sh installer file. Now I found the uninstaller at /opt/zaproxy folder. 

Thanks for the instant response. 

Cheers!
