### ISSUE TITLE
Request for adding AutoMacroBuilderForZAP into the ZAP marketplace

### ISSUE THREAD

**Issue by gdgd009xcd** [zaproxy/zaproxy#6169]
**Add-on repo**
https://github.com/gdgd009xcd/AutoMacroBuilderForZAP

**Your contact details**
patsz.g1owq@gmail.com

**Are you one of the authors**
Yes

**Licence**
Apache-2.0 License

**Build instructions**
same as ZAP-extension addon.

**Link to more information**

**Twitter handle for tool or author(s)**
gdgd009xcd

**Promote to Beta or Release?**
Alpha

**Anything else we should know**

**Comment by gdgd009xcd** [comment]
I think this is not suitable for market place,so I may close this issue.

**Comment by kingthorin** [comment]
We just haven’t had a chance to review it, due to ramping toward a release.

However, it does seem to overlap a bit with Zest and the Sequence add-on.

**Comment by gdgd009xcd** [comment]
Yes,It may be a reinvention of the wheel. 
I'm very loose and lazy, so I don't want to write scripts like zest or scripts for web vulnerability testing. My dream is to automatically recognize the page flow of a web application and perform a fully automatic diagnosis.

**Comment by kingthorin** [comment]
We're happy for users to have options, if you're still interested in this being listed please feel free to re-open.
