### ISSUE TITLE
Add full url encode

### ISSUE THREAD

**Issue by knassar702** [zaproxy/zaproxy#6171]
hi team

zaproxy is not encoding all chars in urlencoder

For example `<img src=x onerror=alert(1)>`,
## burpsuite
![Screenshot at 2020-09-13 16-03-08](https://user-images.githubusercontent.com/45688522/93019973-0b4cc180-f5ca-11ea-8bfd-c519d73d6e80.png)

## ZAP
OUTPUT 
`%3Cimg+src%3Dx+onerror%3Dalert%281%29%3E`
***

burpsuite does a complete encoding all text

but zap only encoding some chars like `< | & ``

for fix that you need to change all chars from string to hex and add `%` before it

```python
#!/usr/bin/env python3
import binascii
def urlencoder(data):
    d = ''
    for word in data:
        d += '%' + binascii.b2a_hex(word.encode('utf-8')).decode('utf-8')
    return d

print(urlencoder('<img src=x onerror=alert(1)>'))
```
OUTPUT
```
%3c%69%6d%67%20%73%72%63%3d%78%20%6f%6e%65%72%72%6f%72%3d%61%6c%65%72%74%28%31%29%3e
```

best regards :heart:

**Comment by kingthorin** [comment]
Encode/Decode/Hash in the weekly and next release support scripted encodings, so you'll be able to do whatever you might want/need.

I'll look into addressing this particular requirement before release.
