### ISSUE TITLE
Unable to launch Browser in Manual Explore 

### ISSUE THREAD

**Issue by ashutoshsharma84** [zaproxy/zaproxy#6173]
I have installed ZAP 2.9.0 version and when selected "Manual Explore", unable to launch inbuilt browser.

The "Launch Browser" button/feature is not working, chrome and Firefox both are not working.

**Comment by psiinon** [comment]
As per https://www.zaproxy.org/faq/somethings-not-working-what-should-i-do/

Have you updated all of the add-ons?
Are there any errors in the zap.log file?
Ask on the user group _before_ raising an issue.

**Comment by ashutoshsharma84** [comment]
Thanks :)
