### ISSUE TITLE
Request for adding CustomActiveScanForZAP into the ZAP marketplace

### ISSUE THREAD

**Issue by gdgd009xcd** [zaproxy/zaproxy#6175]
**Add-on repo**
https://github.com/gdgd009xcd/CustomActiveScanForZAP

**Your contact details**
patsz.g1owq@gmail.com

**Are you one of the authors**
Yes

**Licence**
Apache 2.0

**Build instructions**
Same as zap-extension

**Link to more information**

**Twitter handle for tool or author(s)**
gdgd009xcd

**Promote to Beta or Release?**
No. alpha status.

**Anything else we should know**
I assigned ScanRule's getId to 120001.  Should I change getid to 40018?

**Comment by psiinon** [comment]
Thanks for submitting this add-on.
The master list of plugin IDs is https://github.com/zaproxy/zaproxy/blob/develop/docs/scanners.md
You should submit a PR against this file adding the id you want to use. It must be unique as that is how we identify add-ons.
Maybe 40037 as thats the main section for active scan rules?

**Comment by gdgd009xcd** [comment]
> Thanks for submitting this add-on.
> The master list of plugin IDs is https://github.com/zaproxy/zaproxy/blob/develop/docs/scanners.md
> You should submit a PR against this file adding the id you want to use. It must be unique as that is how we identify add-ons.
> Maybe 40037 as thats the main section for active scan rules?

Ok, I will use 40037 as getId value.
40037 CustomActiveScanForZAP
What kind of procedure do I need after this? Sorry, I 'm beginner for github issue.

**Comment by gdgd009xcd** [comment]
hello,

I issued a new release version.
https://github.com/gdgd009xcd/CustomActiveScanForZAP/releases/tag/v0.0.4
- added javahelp(href link to [wiki)](https://github.com/gdgd009xcd/CustomActiveScanForZAP/wiki/1.0.-Basic-Usage)

Please let me know if there is something wrong or missing.

**Comment by kingthorin** [comment]
@gdgd009xcd sorry we lost sight of this, shall we go with 0.5.6?

**Comment by gdgd009xcd** [comment]
Currently, i 'm busy with other work.
i will tackle this when other work is done.
so, i  close once.

**Comment by psiinon** [comment]
@gdgd009xcd fancy looking at submitting your add-on to the ZAP Marketplace again?
