### ISSUE TITLE
wappalyzer: Add support for CSS & DOM inspection

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#6180]
The [upstream project](https://github.com/AliasIO/wappalyzer) has [added support for CSS inspection](https://github.com/AliasIO/wappalyzer/commit/e619fce6e91f89be24dd8efc6470cd5014fe409a#diff-76d5ffeac090c76ed5f4c581f02f3c53). ZAP's Wappalyzer add-on should add support for the same. (As of 2020-10-28 there is only one of these in apps.json/technologies.json)

It's currently unclear to me if this is applicable to inline styles, just .css files, or both. However, the functionality can probably be handled similarly to scripts inspection.

Edit: The upstream project has also added support for more specific DOM inspection. Search for `"dom":` in apps.json/technologies.json for examples, there are only 7 as of 2020-10-28.

Refs:
- Add-on source: https://github.com/zaproxy/zap-extensions/tree/master/addOns/wappalyzer
- UnitTests: https://github.com/zaproxy/zap-extensions/tree/master/addOns/wappalyzer/src/test/java/org/zaproxy/zap/extension/wappalyzer

---

- [x] CSS inspection. (Done in: https://github.com/zaproxy/zap-extensions/pull/2648)
- [ ] DOM inspection.

**Comment by justdvnsh** [comment]
@kingthorin Hi. I am new contributor to this project. I'd like to contribute to ZAP. Can you please guide me through this issue ?

**Comment by kingthorin** [comment]
@justdvnsh pretty much everything is linked in the original issue above.

The input file larser: https://github.com/zaproxy/zap-extensions/blob/master/addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/WappalyzerJsonParser.java would need to be modified to collect the new details.
The passive scan component would need to be modified to actually process the new pieces: https://github.com/zaproxy/zap-extensions/blob/master/addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/WappalyzerPassiveScanner.java
There might be other minor changes needed too but they should become obvious as you proceed through the changes.

**Comment by justdvnsh** [comment]
@kingthorin Ok. Thanks. I'll proceed and let you know about the updates.

**Comment by justdvnsh** [comment]
@kingthorin Hi. I wanted to ask that when we check for default apps using ```apps.json```, so how do I add checks for css there. Like do I need to add css value for all the technologies mentioned there ? or something else .

**Comment by thc202** [comment]
The `apps.json` file already contains the CSS evidence if it applies (e.g. https://github.com/zaproxy/zap-extensions/blob/49c0b8db62de113fd764bb3a2a4be381afc6bd94/addOns/wappalyzer/src/main/resources/org/zaproxy/zap/extension/wappalyzer/resources/apps.json#L14590), the issue is for using those when scanning the messages.

**Comment by kingthorin** [comment]
Note, per: https://github.com/AliasIO/wappalyzer/pull/3440#issuecomment-717586317 HTML patterns are being deprecated in favor of DOM.

@justdvnsh have you been able to make any progress on this?

**Comment by justdvnsh** [comment]
@kingthorin No. I am not able to make any progress as of now .

**Comment by kingthorin** [comment]
Oksy no problem.

**Comment by bettercalln1ck** [comment]
Hey, I would like to work on this issue?

**Comment by kingthorin** [comment]
The DOM piece is left.

**Comment by bettercalln1ck** [comment]
Ok, I'll start working on it.
