### ISSUE TITLE
Generic Padding Oracle - FP matching CSS padding

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#6183]
I've seen a screenshot of a Generic Padding Oracle alert where the evidence appears to be the word `padding` and it appears to only be in CSS.
Presumably its matching this error pattern: https://github.com/zaproxy/zap-extensions/blob/master/addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/PaddingOracleScanRule.java#L41
I'm trying to get more evidence but it does look like we should be checking the original message for the error patterns and then either ignoring them or performing extra validation if they are present.

**Comment by psiinon** [comment]
Update, yes, its matching inline CSS.
Interestingly the target parameter is a known anticsrf token `csrfmiddlewaretoken` which explains why the attack changes the response.
Possible solutions:

- Check for pattern matches in original message, might not work in this case
- Dont attack known anti CSRF tokens as that will almost certainly change the response
- Other suggestions?

**Comment by kingthorin** [comment]
I vote for option 2.

**Comment by psiinon** [comment]
Another suggestion c/o @thc202 encode a safe value after https://github.com/zaproxy/zap-extensions/blob/master/addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/PaddingOracleScanRule.java#L133-L136 and see if that errors...

**Comment by kingthorin** [comment]
Sounds good.
