### ISSUE TITLE
Spidering site before Active Scan reduces the number of vulnerabilities found

### ISSUE THREAD

**Issue by cherdt** [zaproxy/zaproxy#6185]
**Describe the bug**
I'm using the HUD and exploring a vulnerable application (https://github.com/cherdt/foocoin).

If I log into the application, submit some sample text to a form POST, and run an Active Scan it finds a persistent XSS vulnerability.

If I log into the application, submit some sample text to a form POST, spider the site, and then run an Active Scan, it does _not_ find a persistent XSS vulnerability.

This seems unexpected.

**To Reproduce**
1. Run the sample app via Docker: `sudo docker run -it -p 8000:8000 --rm cherdt/foocoin`
2. Start ZAP and enable the HUD
3. Load http://localhost:8000/
4. Log in to the site as user `student`, password `123456`
5. Return to the main page
6. Click on the Student link
7. Submit "test" to the Status update form
8. Run an Active Scan

The scan should find 3 high severity alerts: Cross Site Scripting (Reflected), Cross Site Scripting (Persistent), and SQL Injection.

Run through the same steps (restarting the containerized app, restarting ZAP) and insert a Start Spider step between steps 7 and 8. The scan finds just 2 high severity alerts: Cross Site Scripting (Reflected) and SQL Injection.

**Expected behavior**
I expect the scan to find the at least the same errors, if not more errors, after spidering the site.

**Screenshots**

**Software versions**
 - ZAP: 2.9.0
 - Installed add-ons: [[id=alertFilters, version=10.0.0], [id=ascanrules, version=34.0.0], [id=bruteforce, version=9.0.0], [id=diff, version=10.0.0], [id=directorylistv1, version=4.0.0], [id=fuzz, version=12.0.0], [id=gettingStarted, version=11.0.0], [id=help, version=10.0.0], [id=hud, version=0.9.0], [id=importurls, version=7.0.0], [id=invoke, version=10.0.0], [id=onlineMenu, version=7.0.0], [id=openapi, version=15.0.0], [id=pscanrules, version=26.0.0], [id=quickstart, version=27.0.0], [id=replacer, version=8.0.0], [id=reveal, version=3.0.0], [id=saverawmessage, version=5.0.0], [id=savexmlmessage, version=0.1.0], [id=scripts, version=26.0.0], [id=selenium, version=15.1.0], [id=spiderAjax, version=23.1.0], [id=tips, version=7.0.0], [id=webdriverlinux, version=16.0.0], [id=websocket, version=21.0.0], [id=zest, version=31.0.0]]
 - OS: Kali Linux 2020.2
 - Java: openjdk 11.0.8
 - Browser: Firefox 68.11.0esr 

**Errors from the zap.log file**
Only one error, doesn't seem related:

    2020-09-18 20:53:26,084 [ZAP-PassiveScanner] ERROR InformationDisclosureInURL - No such file: /home/chris/.ZAP/xml/URL-information-disclosure-messages.txt

**Additional context**
I tried updating all installed add-ons, but after the update the HUD would not launch with either Firefox or Chromium. I uninstalled and reinstalled the zaproxy package and confirmed the behavior again with a clean install.

**Comment by psiinon** [comment]
Please ask about this on the ZAP User Group: https://groups.google.com/group/zaproxy-users
Issues as for specific bugs in ZAP, whereas this could be related to how you are using ZAP - at this stage we dont know.
If we identify a specific problem with ZAP then we can raise an issue for it.
