### ISSUE TITLE
Change whitelist and blacklist terms

### ISSUE THREAD

**Issue by olucheye** [zaproxy/zaproxy#6189]
Hello guys, 

Having worked on similar OSS projects recently, and also seeing current changes sweeping the ecosystem, I strongly believe that Zaproxy could make-do with a **terminology upgrade** from ones deemed hurtful, **to more functionally specific terms like "allowlist" and "blocklist"**

This could be done as a deprecation where for a period of time both terms could be used (some sort of mapping), until a specific version/date where only the new terms would work. I have done a sweep through the codebase and I would like to effect these changes if I have the team's go ahead.

**Comment by thc202** [comment]
Closing as duplicate of #6029.

**Comment by psiinon** [comment]
@olucheye but PRs for anything we havnt addressed yet much appreciated :)
