### ISSUE TITLE
Manual Explore does not work in Parrot OS

### ISSUE THREAD

**Issue by Anthonymcqueen21** [zaproxy/zaproxy#6199]
Started a new operating system known as parrot for white hat hacking and most of the application pentesting tools work. But for some reason again ZAP does not work manually when it comes to exploring manually. I had the same issue when i was Kali-Linux systems now its happening again. 

1. I went onto the options
2. I went on Selenium section
3. I went to binaries entered the same solution i got for kali-linux: /usr/bin/firefox-usr
4. I went back to manual explore.
5. I entered the address to the site i wanted to test
6. Nothing is happening ???

So i am wondering if there is another option that is needed for Parrot OS ???

**Comment by kingthorin** [comment]
Seems like a good question for the Parrot OS crew.

(Also the Kali fix is `firefox-esr`.)

- Did you update all your add-ons?
- What version of Firefox is available on Parrot (is it an ESR?)?
- What version of Java?

**Comment by Anthonymcqueen21** [comment]
1. Yes i did all the updates on ZAP
2. I am using Firefox 80.0.1 (64-bit) 

> Firefox for Parrot OS
> Parrot - 4.8

3. The version of Java i use is JRE 1.6

**Comment by kingthorin** [comment]
If you're using Java 1.6 I'm surprised ZAP ran at all. The current minimum requirement is 1.8.

**Comment by Anthonymcqueen21** [comment]
Sigh... so what should i do ?

**Comment by kingthorin** [comment]
No idea, I've never used Parrot OS.

**Comment by Anthonymcqueen21** [comment]
Okay thank you anyway.

**Comment by kingthorin** [comment]
Which variant are you using? https://www.parrotsec.org/download/

**Comment by Anthonymcqueen21** [comment]
Parrot Security MATE ISO (default)

**Comment by psiinon** [comment]
Are there any errors in the zap.log file?
If launching browsers is not working you can still manually configure browsers to proxy via ZAP. You will need to set the host:port and import / trust the ZAP root CA certificate.

**Comment by Anthonymcqueen21** [comment]
I already did that and i am still getting problems it makes no sense i installed the necessary certificates what could i be doing wrong ?

**Comment by psiinon** [comment]
No idea - we'll need some details in order to help you.
What are you daoing and what are you seeing?
Are there any errors in the zap.log?

**Comment by kingthorin** [comment]
You'll have to take it up with the Parrot OS crew.

I downloaded the ISO you for the variant you mentioned, created a VM, did all the pending updates. If you launch ZAP via the "owasp-zap" entry in the Applications menu, provide authentication when prompted update addons (if prompted) Manual Explore and Browser Launch fail.

If you launch zap via `/usr/share/zaproxy/zap.sh`, install all the addons (all the rules addons you want, WebDrivers Linux, Selenium, QuickStart, etc) they Manual Explore and Browser Launch work fine.

So it obviously has something to do with how they're launching it or securing/limiting it.

**Comment by Anthonymcqueen21** [comment]
Thank you everyone for helping me still does not work on my VM but works on my normal machine with no issues.
