### ISSUE TITLE
[Fatal Error] :1:3: The markup in the document preceding the root element must be well-formed.

### ISSUE THREAD

**Issue by kyrylo-tkachov** [zaproxy/zaproxy#6200]
**Describe the bug**
When I run job in Jenkins and use next steps I got this error:

**Error**
2020-09-28 11:50:57,537 Params: ['zap-x.sh', '-daemon', '-port', '35208', '-host', '0.0.0.0', '-config', 'api.disablekey=true', '-config', 'api.addrs.addr.name=.*', '-config', 'api.addrs.addr.regex=true', '-config', 'spider.maxDuration=0', '-addonupdate', '-addoninstall', 'pscanrulesBeta', '-addoninstall', 'ascanrulesBeta', '-addoninstall', 'pscanrulesAlpha', '-addoninstall', 'ascanrulesAlpha']
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
Sep 28, 2020 11:51:01 AM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
[Fatal Error] :1:3: The markup in the document preceding the root element must be well-formed.
[Fatal Error] :1:3: The markup in the document preceding the root element must be well-formed.

**Steps**
+ mkdir zap_report
+ chmod 777 zap_report
+ pwd
+sudo docker run -v /var/lib/jenkins/workspace/zaproxy-docker-container-full-scan/docker:/zap/wrk/:rw -t owasp/zap2docker-stable zap-full-scan.py -x zap_report/zap_full_report.xml -a -n latest.context -t *page*

The image pulled completely and user pref. directory created, then: [Fatal Error] :1:3: The markup in the document preceding the root element must be well-formed. In which document it must be well-formed?

**Comment by psiinon** [comment]
Are you actually experiencing any problems?
If so please describe them.
We cant tell whats going on just from that error message.

**Comment by kyrylo-tkachov** [comment]
> Are you actually experiencing any problems?
> If so please describe them.
> We cant tell whats going on just from that error message.

It is a problem with context file. Thanks a lot!
