### ISSUE TITLE
XXE scan rule should parse response to check vulnerability even when the HTTP response code is not 200 OK

### ISSUE THREAD

**Issue by ejayaraman** [zaproxy/zaproxy#6203]
**Background:**
This is logged on the back of the [discussion](https://groups.google.com/u/3/g/zaproxy-users/c/4QdC_m1Yo34) with the ZAP team about the current behaviour of [XML External Entity Attack scanner](https://www.zaproxy.org/docs/alerts/90023/). There were two concerns raised in this discussion. I am creating seperate tickets for them as they can be addressed independent of each other. For the other issue see: [6204](https://github.com/zaproxy/zaproxy/issues/6204)

**Current Behaviour:**
Currently, the XXE scanner parses the responses from `Local File Reflection Attack` and `Local File Inclusion Attack` only when the HTTP Status is 200 OK. 
[Local File Reflection Attack](https://github.com/zaproxy/zap-extensions/blob/master/addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/XxeScanRule.java#L260) parsing logic.
[Local File Inclusion Attack](https://github.com/zaproxy/zap-extensions/blob/master/addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/XxeScanRule.java#L325) parsing logic.

So if a response whose status code does not match OK then an alert will not be created even if the target file contents are included in the response. 

**Expected Behaviour:**
The response should be parsed regardless of the HTTP status code to check if the target file contents are included. 

**Version Information:**
**ZAP**: 2.9.0
**Scanner Version:** ascanrulesBeta-beta-28.zap
**Scan Rule Details:**
```json
{
    "allDependenciesAvailable":"true",
    "policyId":"4",
    "cweId":"611",
    "attackStrength":"DEFAULT",
    "alertThreshold":"DEFAULT",
    "name":"XML External Entity Attack",
    "wascId":"43",
    "id":"90023",
    "enabled":"true",
    "quality":"beta",
    "dependencies":[
   ]
}
```

**Comment by m0mosenpai** [comment]
Hi, i'll like to work on this issue. I'm supposed to remove the if condition in both files if I'm not wrong.

**Comment by kingthorin** [comment]
Yup. Additionally the UnitTest(s) should be updated and the CHANGELOG. But, let's not get into the weeds too much peripheral items can be discussed on PR review.

**Comment by kingthorin** [comment]
Assigned @ejayaraman Who has already started a fix/update.

Cc: @m0mosenpai

**Comment by m0mosenpai** [comment]
Ah I see np. I had been trying to implement the tests these past few days but was having a hard time understanding the code and implementing what I was trying to. My bad, I probably should have commented here once. First time working on open source actually haha... I'll look for another issue i can work on!

**Comment by kingthorin** [comment]
No worries, sorry for the overlap (not something we could predict). Thanks for your interest!

**Comment by chaudharydeepak** [comment]
@kingthorin - I would like take a jab at this issue. I have gone through expected behavior and its great there are unit tests in place ;) - please assign to me, if this is still available. Thank you.
