### ISSUE TITLE
Revisit XXE scan rule replacing the value of all the tags in the request, with attack entity, at once.

### ISSUE THREAD

**Issue by ejayaraman** [zaproxy/zaproxy#6204]
**Background:**
This is logged on the back of the [discussion](https://groups.google.com/u/3/g/zaproxy-users/c/4QdC_m1Yo34) with the ZAP team about the current behaviour of [XML External Entity Attack scanner](https://www.zaproxy.org/docs/alerts/90023/). There were two concerns raised in this discussion. I am creating seperate tickets for them as they can be addressed independent of each other. For the details of the other issue see [6203](https://github.com/zaproxy/zaproxy/issues/6203) 

**Current Behaviour:**
Currently, the `Local File Reflection Attack` in XXE scan rule replaces the value of all the tags in the original request with the attack entity at once. This happens in the `createLfrPayload` [here](https://github.com/zaproxy/zap-extensions/blob/a2e11b2859c466c01eb0115eba90f312b40af6fb/addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/XxeScanRule.java#L421).

_So, an example XML request:_
```xml
<?xml version="1.0" encoding="utf-8"?>

<someTag>
    <Tag1>value1</Tag1>
    <Tag2>value2</Tag2>
    <Tag3>value3</Tag3>
</someTag>
```

_will be transformed to:_
```xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE foo [
  <!ELEMENT foo ANY >
  <!ENTITY zapxxe SYSTEM "file:///etc/passwd">
]>

<someTag>
    <Tag1>&zapxxe;</Tag1>
    <Tag2>&zapxxe;</Tag2>
    <Tag3>&zapxxe;</Tag3>
</someTag>
```

The implication of this is, if  the service requires a valid value in one of the tags, then the application could fail even before XML is parsed. So even if there is a vulnerability in the XML parser, the parsing code will never be exercised resulting in the vulnerability not being found. 

**Expected Behaviour:**
Consider updating the rule to create attack payloads by replacing one tag value at a time. In the discussion thread, @kingthorin pointed out that this could result in a large number of requests. So the number of requests may have to be limited depending on the strength guidelines. See the discussion thread for more details. 

**Version Information:**
**ZAP**: 2.9.0
**Scanner Version:** ascanrulesBeta-beta-28.zap
**Scan Rule Details:**
```json
{
    "allDependenciesAvailable":"true",
    "policyId":"4",
    "cweId":"611",
    "attackStrength":"DEFAULT",
    "alertThreshold":"DEFAULT",
    "name":"XML External Entity Attack",
    "wascId":"43",
    "id":"90023",
    "enabled":"true",
    "quality":"beta",
    "dependencies":[
   ]
}
```

**Comment by darmis007** [comment]
Hey i would like to work on this issue? Could you please guide me

**Comment by kingthorin** [comment]
@darmis007 thanks. It'll involve the same classes as this PR: https://github.com/zaproxy/zap-extensions/pull/2568, and should probably wait until that PR is merged (hopefully soon). 

You could still go ahead and plan your changes though.

**Comment by ssyms** [comment]
@darmis007 Are you still working on this issue? I'd be interested in it if not

**Comment by kingthorin** [comment]
That might be partially my fault. I probably should have said something 20 days ago when the other was merged.

**Comment by ssyms** [comment]
No problem for me, just wondering if I could work on it since there's not many unassigned "good first issues" open right now.

**Comment by kingthorin** [comment]
Yes, go for it 👍

**Comment by pranavsaxena17** [comment]
@ssyms Are you still on this?I'll like to take this up if not.

**Comment by ssyms** [comment]
@pranavsaxena17 didn't even realize I had been assigned this issue, I've been working on #4112 . Feel free to take this one if you want
