### ISSUE TITLE
Scan Rule UnitTests

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#6212]
Prior to [promotion](https://github.com/zaproxy/zaproxy/issues/6211) Unit Tests should be added for the following Scan Rules:

- [x] CloudMetadataScanRule (Alpha)
- [x] AbstractAppFilePlugin (commonlib)
  - [x] EnvFileScanRule (Alpha)
  - [x] HtAccessScanRule (Beta)

**Comment by thc202** [comment]
The scan rule `ElmahScanRule` seems to have tests already. `EnvFileScanRule` and `HtAccessScanRule` would be tested mostly through the test of `AbstractAppFilePlugin`.

You are already working on this, right?

**Comment by kingthorin** [comment]
I haven’t started but planned to get working on it over the weekend.

**Comment by thc202** [comment]
OK.

**Comment by psiinon** [comment]
I'd be happier if CloudMetadataScanRule did some extra checking, ie some content - then we could raise an alert with a higher level of confidence. Not necessarily a blocker though.

**Comment by psiinon** [comment]
One caveat to the 'all rules must have unit tests' rule - I'd be happy to promote a rule if we had a good set of 3rd party tests that we could run (and score!) against, eg wavsep, firing range, OWASP benchmark, vuln app...
