### ISSUE TITLE
Support for checking if all executor threads paused in the PausableExecutorService

### ISSUE THREAD

**Issue by 15pratik** [zaproxy/zaproxy#6213]
On issuing a pause to the PauseableExecutorService, it holds the new threads from executing but does not pause the already running threads and they are supposed to run to completion.
It will be useful to have an API to expose the information on the number of running threads.

**Comment by thc202** [comment]
Could you provide details about the use case?

**Comment by 15pratik** [comment]
> Could you provide details about the use case?

The reason for issuing a pause on the executor service to have some system state changes which might affect the running threads. In this case, all threads are paused before making the state change. However, consider the threads were long running runnable and the already executing threads had not terminated when the pause was issued, it is only supposed to take care about not starting the execution of a new thread.
If the state is changed at this time, the running processes may fail due to the state changes. Thus the user might want to ensure he does not make the state changes until there is no running thread.

```
execService.pause();  //does not allow new threads to be executed - ongoing threads still active
while(execService.hasRunningThreads()) {
       wait();   //ensures all running threads run to completion
}
// no running threads
makeStateChanges();
execService.resume(); //allows new threads to be running with the new state
```

**Comment by thc202** [comment]
The interface was added to simply support pausing an executor (e.g. user pausing a scan), not for more elaborated use cases (not saying it can't be used for other things, just saying why it was added).

Could you be more explicit on what state is `makeStateChanges();` changing? Is that for the (possible) tasks queued or threads in a pool? Is this for an add-on or a core feature?

**Comment by 15pratik** [comment]
For my particular use case, I have multiple threads running at any point of time and they all write some data to a set of files. I need to ensure periodic backups which might take a while to upload the files and back them up. Meanwhile, I do not want any thread to write over the files which might lead to an inconsistent state of files. (say file1 was uploaded meanwhile file2 had an update entry, the backup will have file1 with an older state than file2)
Thus I need to ensure, the backup is initiated once all the running threads in the pool have run to completion (or no threads are executing) which may possibly write onto the files to be backed up.
Once the files are uploaded, the executor can be resumed.

**Comment by thc202** [comment]
Thanks for the details, IMHO that case does not warrant changing `PausableExecutorService` interface, which would introduce unnecessary overhead for all implementations for something that's not necessary in the majority of the cases. One can handle that case without needing to know the state of the executor threads, e.g. it could be used a `ReadWriteLock` to prevent writing new data while uploading.

**Comment by 15pratik** [comment]
I understand that there might be a different way to carry out the described operation. However with respect to the PausableExecutor if you see, `pause` is like an asynchronous operation. It isn't guaranteed that the executors have actually paused. Now, for any asynchronous operation, I feel there is a need to have a poll method to figure out if the operation is completed or not.

Coming back to the use cases, I think there is always be some combination of R/W locks that will work out. If someone wants to opt for a simpler code structure, one might go with PausableExecutor which helps to keep the code readable and easier to maintain. When applying the `pause` one needs a strict guarantee that nothing else is running, if this guarantee was not required then one could go without the pause also and having a pause would just be an optimisation to reduce the parallel load. When we talk about this guarantee for ensuring no background operations (in that executor service) there needs to be a mechanism to identify that the pause has gone through.

I respect your judgement to have this or not. It's just that I see a need for it and there is no robust way to implement it by extending the class. Below is the workaround to have the required functionality.

```
public class MyPausableExecutor extends PausableThreadPoolExecutor {
  public final AtomicInteger threadsStarted = new AtomicInteger(0);
  private final ReentrantReadWriteLock rwl = new ReentrantReadWriteLock();

  public MyPausableExecutor(
      int corePoolSize,
      int maximumPoolSize,
      long keepAliveTime,
      TimeUnit unit,
      BlockingQueue<Runnable> workQueue) {
    super(corePoolSize, maximumPoolSize, keepAliveTime, unit, workQueue);
  }

  @Override
  protected void beforeExecute(Thread t, Runnable r) {
    rwl.readLock().lock();
    try {
      super.beforeExecute(t, r);
      int numThreads = threadsStarted.incrementAndGet();
      log.debug("New thread started, Total Running Threads: {}", numThreads);
    } finally {
      rwl.readLock().unlock();
    }
  }

  @Override
  public void pause() {
    rwl.writeLock().lock();
    try {
      super.pause();
    } finally {
      rwl.writeLock().unlock();
    }
  }

  @Override
  public boolean hasRunningThreads() {
    rwl.readLock().lock();
    try {
      int numThreads = threadsStarted.get();
      log.debug("running {}, completed {}", numThreads, getCompletedTaskCount());
      return numThreads != getCompletedTaskCount();
    } finally {
      rwl.readLock().unlock();
    }
  }
}

```

**Comment by thc202** [comment]
Note that the workaround has concurrency issues. I was suggesting implementing this in your tasks not by overriding the executor. Just have a task do the sync (by acquiring the appropriate lock).

Closing as won't fix since this can be implemented in the add-on (or where the code lives), without introducing overhead in the executor.
