### ISSUE TITLE
Path traversal false positive on json response containing boolean 

### ISSUE THREAD

**Issue by Vrindanh** [zaproxy/zaproxy#6219]
Zap sets alert  for Path Traversal if it sees 200 OK   boolean value Json response 
Response :
{"somestring ":true}
The request is valid  request  with origin parameter modified . But the response above does not indicate any path on the server
The server concerned has directory browsing turned off and inputs validated

Alert Leve:High  Confidence:Medium
![image](https://user-images.githubusercontent.com/69756357/95089083-59746100-0741-11eb-9a94-858970bac389.png)

**Comment by kingthorin** [comment]
1. We're going to need much more info if you expect us to fix this. (What was the original response? What attack does ZAP list?
2. Directory Browsing is not the same as Path Traversal.

**Comment by Vrindanh** [comment]
URL | https://<servername>/p1/p2/api
-- | --
Method | POST
Parameter | origin
Attack | api

Original reponse and response after attack is same. The   Request contain all the required fields  and hence the response is 200.

**Comment by kingthorin** [comment]
I believe this is check 5 in the Path Traversal rule which boils down as:

1.  Request a URL with a filename that shouldn't exist.
2. Get the filename from the original URL (in your example: LOGIN.EXAMPLE.COM)
3. If there is a filename (some URLs end in slash....) and either the status code for the non-exist file isn't ok (200) or the word Exception or Error was in the response then continue.
4. With the original URL take the filename and insert it as a param value (hence: entityID=LOGIN.EXAMPLE.COM), send the request.
5. If the response is ok (200) and doesn't contain Error or Exception, then raise an alert. (As you've encountered.)

**Comment by psiinon** [comment]
If we do change this check then we should test this vs wavsep as it has a load of path traversal tests: http://zapbot.github.io/zap-mgmt-scripts/reports/wavsep-1.5-weekly-RBJ-M-M.html
