### ISSUE TITLE
Python API: core.rootcert() doesn't inherit the local proxies and API-key of the ZAPv2 class

### ISSUE THREAD

**Issue by cedricdv** [zaproxy/zaproxy#6230]
**Describe the bug**
zap.core.rootcert() doesn't follow the set proxies set in the zap object.

**To Reproduce**
```
zap = ZAPv2(apikey=apikey, proxies=proxies)
logging.info('ZAP Root CA: {}', format(zap.core.rootcert(apikey=apikey)))
```
`requests.exceptions.ProxyError: HTTPConnectionPool(host='<<<<apihostname>>>>>', port=8080): Max retries exceeded with url: http://zap/OTHER/core/other/rootcert/?apikey=<<<<apikey>>>> (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1056bb7f0>: Failed to establish a new connection: [Errno 61] Connection refused')))`

**Expected behavior**
I'd expect core.rootcert to just use the settings provided during class init but instead it uses "zap" as localproxy-hostname and I need to provide the apikey again in the rootcert method. I'd expect to just do:
```
zap = ZAPv2(apikey=apikey, proxies=proxies)
logging.info('ZAP Root CA: {}', format(zap.core.rootcert()))
```
**Software versions**
 - ZAP: ZAP 2.9.0 Docker image
 - Add-on: ZAPv2 Python API
 - OS: linux
 - Java: default
 - Browser: -

**Comment by cedricdv** [comment]
Renamed dockercontainer to zap for quick fix

**Comment by thc202** [comment]
Based on the errors `Cannot connect to proxy.` and `Connection refused` it seems that the API client is not able to connect to ZAP at all, most likely the proxy configuration is not correct (either the address or the port). The `zap` hostname is only used after establishing the connection.

**Comment by cedricdv** [comment]
> Based on the errors `Cannot connect to proxy.` and `Connection refused` it seems that the API client is not able to connect to ZAP at all, most likely the proxy configuration is not correct (either the address or the port). The `zap` hostname is only used after establishing the connection.

well yes, and that is exactly where things start to go wrong: after I get connected, suddenly that hostname zap starts showing up if the container is not called zap. If the container in which it is running is named zap there is no problem.

**Comment by thc202** [comment]
Which errors are you getting if the container is not called `zap`?
