### ISSUE TITLE
Commands ?

### ISSUE THREAD

**Issue by Anthonymcqueen21** [zaproxy/zaproxy#6238]
**- Hello everyone** 

My question is i am currently working on the Parrot OS security platform and i noticed a issue i was having when using the already per-installed Zaproxy. The automated scan works fine but for some reason the manual explore does not work effectively and does not show the browser i want for example Fire-Fox. So i took it upon myself to download another Zap-proxy to see if a fresh install can help me fix this issue i am having. Any help and or guidance would be greatly appreciated i just want to continue my training in pen testing.

After installation what are the commands needed to install and open the latest version of Zap-proxy successfully ?

**Comment by kingthorin** [comment]
Please don't ask questions as issues, especially when providing zero details - the [ZAP User Group]( https://groups.google.com/group/zaproxy-users) is a much better place for questions.

If you’re asking about a third party components such as the Jenkins plugin or VSTS plugin please look for their preferred support mechanism as these were not created by and are not supported by the core team.

---

This is a duplicate of: https://github.com/zaproxy/zaproxy/issues/6199

Please report your issue to the Parrot OS team.

**Comment by Anthonymcqueen21** [comment]
Hmm okay.
