### ISSUE TITLE
Script tab in ZAP D-2020-10-13 doesn't appear

### ISSUE THREAD

**Issue by sbzo** [zaproxy/zaproxy#6240]
**Describe the bug**
The tab of Scripts isn't available in this version.

**To Reproduce**
Open ZAP Proxy D-2020-10-13

**Screenshots**
In the picture is a comparison between the actual Dev release and the previous one. 
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/28350322/95932513-a71c4980-0d91-11eb-9c9e-5994e86cd96d.png">

**Software versions**
 - OS: macOS 10.15.7
 - Java: openjdk version "1.8.0_261"

**Errors from the zap.log file**
<img width="1624" alt="image" src="https://user-images.githubusercontent.com/28350322/95932881-9c15e900-0d92-11eb-95a0-07a4cc448185.png">

**Would you like to help fix this issue?**
I don't

**Comment by sbzo** [comment]
Thanks for your work.

**Comment by kingthorin** [comment]
@psiinon related to: https://github.com/zaproxy/zap-extensions/pull/2554 ?

**Comment by psiinon** [comment]
Oh, thats surprising.
As a test try starting the weekly with a new directory, eg using `-dir test`
Thats one of the tests I always do before releasing it. If just double checked and doing this with ZAP_D-2020-10-13 I _do_ get the Script Console tab.
Hoewever I will look into this asap...

**Comment by psiinon** [comment]
@thc202 has pointed out that this happens when you start the weekly in dark mode - I've just confirmed that.
This _might_ be related o the fact that #6202 hasnt been merged yet, but I've not confirmed that yet.
So a workaround is to not use dark mode for this weekly - we'll def get a fix in before the next one.

**Comment by sbzo** [comment]
Excellent, thanks
