### ISSUE TITLE
OWASP scanner error in Azure DevOps pipeline.

### ISSUE THREAD

**Issue by laminsamba** [zaproxy/zaproxy#6247]
Hi,

I am using OWASP in Azure DevOps pipeline. When I ran the test scanner, the test failed and output the following results below that required to be fixed.

- 	Content Security Policy (CSP) Header Not Set
- 	CSP Scanner: Wildcard Directive
- 	Information Disclosure - Suspicious Comments
- 	Modern Web Application
- 	CSP Scanner: X-Content-Security-Policy
- 	CSP Scanner: X-WebKit-CSP
- 	PII Disclosure
- 	Proxy Disclosure
- 	Strict-Transport-Security Header Not Set
- 	Timestamp Disclosure - Unix
- 	User Agent Fuzzer

**Architecture**
I’m deploying a .Net Core MVC application to Azure Web App, using Azure PaaS service. The Web App is deployed to an App Service Plan, which is hosting couple of other web apps.

**ISSUE**
I have implemented the recommendation according to the OWASP scanner test result and even though the fixes are still showing in the Request Header, after re-running the OWASP scanner again, the test failed to recognise these fixes. 

**Observation**
The fixes I implemented are carried out in the webapp which I have deployed to an App Service Plan in Azure. I think the OWASP scanner is running at the server level (i.e. APP Service Plan level), and therefore when the scanner runs, The app service override the configuration of the web app.

**Can anyone help me with these?**

Regards

**Comment by kingthorin** [comment]
Please don't ask questions as issues, especially when providing zero details - the [ZAP User Group]( https://groups.google.com/group/zaproxy-users) is a much better place for questions.

If you’re asking about a third party components such as the Jenkins plugin or VSTS plugin please look for their preferred support mechanism as these were not created by and are not supported by the core team.

**Comment by laminsamba** [comment]
Well I have an issue with this product which I’m looking for help. So if you cannot support me resolve this issue, the lease you can do it to redirect me to the right group in a respectful manner.

Dodou Lamin Samba
Software Consultant
London
United Kingdom
Tel: + 44 (0)750 1033 0160
LinkedIn: https://www.linkedin.com/in/lamin-samba
Twitter: https://twitter.com/samba_lamin

________________________________
