### ISSUE TITLE
Requester addon doesn't update the content-length

### ISSUE THREAD

**Issue by sbzo** [zaproxy/zaproxy#6254]
**Describe the bug**
The requester addon don't update the content length.

**To Reproduce**
Send a request to the requester addon. Do some change and send. 

**Expected behavior**
The addon should have an option to enable or disable the content length update like the manual requester change in the pull https://github.com/zaproxy/zaproxy/pull/6193

**Software versions**
 - ZAP: D-2020-10-20
 - Add-on: Requester 4.0

**Comment by sbzo** [comment]
If someone had the same issue, I find the following work around creating a replace rule like the following:

<img width="375" alt="Screen Shot 2020-11-30 at 8 05 19 PM" src="https://user-images.githubusercontent.com/28350322/100684321-16e99200-3348-11eb-9825-f1e03605aad5.png">

Removing the header content-length force the repeater addon recalculate it. If you are testing something like http smuggling and have to play with the content-lenght, remember disable the rule.

Best regards,

RLobo.

**Comment by psiinon** [comment]
For info we updated the core so that code could optionally not automatically get the content length updated.
I would have expected the Requester add-on to have been unaffected but it looks like it will need changes...

**Comment by rtpt-alexanderneumann** [comment]
I've ported the code from ZAP core to the requester and added a button to automatically fix the content length, PR is here: https://github.com/zaproxy/zap-extensions/pull/3008

**Comment by thc202** [comment]
That's mentioned in the README.
