### ISSUE TITLE
Script Console: Context Menu Issue

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#6256]
When a script is freshly added the "Enable Script(s)" context menu item doesn't render properly. Here's an animated GIF of the issue. Note it happens in both Light and Dark LaFs.
![script_console](https://user-images.githubusercontent.com/7570458/97081517-f011a080-15d0-11eb-9fae-29d8d0e8b68e.gif)

**Comment by thc202** [comment]
This a bug in the Script Console add-on, the menu item should not be visible when the selected scripts are not enableable.
