### ISSUE TITLE
Web Cache Deception (WCD) Scan Rule

### ISSUE THREAD

**Issue by CravateRouge** [zaproxy/zaproxy#6263]
**Is your feature request related to a problem? Please describe.**
I recently saw an [article](https://blog.apnic.net/2020/10/02/web-cache-attacks-in-the-tangled-web/) about the Web Cache Deception (WCD) vulnerability. This vulnerability happens when a front-end web cache and a back-end web server don't behave in symbiosis when they receive a request to a non-existing resource.

**Describe the solution you'd like**
I think that it would be interesting if this vulnerability could be spotted with the active scanner. The idea would be to:

1. Keep in memory the response to a _non-generic_<sup>1</sup> request e.g `https://www.example.com/my_profile` ;
2. Send the _non-generic_ request and append to it a non-existent resource e.g `https://www.example.com/my_profile/test.jpg` ;
3. Check if the response is the same for both requests ;
4. If the response is the same, resend 2. without cookies ;
5. If the response to 4. is the same as the response to 1. Bingo! we have a WCD.

[1]: By _non-generic_ I mean a request linked to a particular cookie value. It could be a session cookie for a page like `my_profile` but it could also be a common cookie like a language cookie (the page will be display in English if `lang=""` but in French if `lang=fr` )

**Describe alternatives you've considered**
Burp has an [extension](https://github.com/portswigger/web-cache-deception-scanner) to detect this vulnerability.

**Would you like to help implementing this feature?**
I would be glad to help but I'm a new Zap user and I have no idea on how Zap code works.

**Comment by bettercalln1ck** [comment]
Hey, I would like to work on this issue.

**Comment by psiinon** [comment]
@bettercalln1ck Got for it :) If you have any questions then just ask here...

**Comment by bettercalln1ck** [comment]
I don't have any questions at the moment. Thanks!

**Comment by kingthorin** [comment]
I guess this can be closed?

It seems the LevenshteinDistance calc might be causing performance issues: https://groups.google.com/g/zaproxy-users/c/_7XAyz1CEks but that's a separate item.

**Comment by kingthorin** [comment]
Done in: https://github.com/zaproxy/zap-extensions/pull/2696
