### ISSUE TITLE
Rule 10054 'Cookie Without SameSite Attribute' occurs even when cookie is ignored with -z rules.cookie.ignorelist

### ISSUE THREAD

**Issue by mig5** [zaproxy/zaproxy#6264]
**Describe the bug**

Applications behind an AWS Application Loadbalancer that use 'stickiness', cause the ALB to send two cookies in the response. One is AWSALB and the other is AWSALBCORS.

Only on the latter is the Samesite flag sent and it is set to 'None'. Neither have httponly and secure flags set.

A baseline scan will report the 10054 'Cookie Without SameSite Attribute' because it expects the value to be Lax or higher. It also reports the lack of httponly and secure flag on those cookies (rules 10010 and 10011). This is normal behaviour.

However, I am ignoring these cookies in my call to the Docker zap-baseline.py script by passing the `-z '-config "rules.cookieignorelist=AWSALB,AWSALBCORS"` flag, as can be seen here:

```
Command output: 2020-10-27 23:45:34,559 Params: ['zap-x.sh', '-daemon', '-port', '44356', '-host', '0.0.0.0', '-config', 'api.disablekey=true', '-config', 'api.addrs.addr.name=.*', '-config', 'api.addrs.addr.regex=true', '-config', 'spider.maxDuration=10', '-addonupdate', '-addoninstall', 'pscanrulesBeta', '-config', 'rules.cookie.ignorelist=AWSALB,AWSALBCORS']
```

With this arg it dutifully ignores the cookies for rules 10010 and 10011 (httponly and secure flags), but it keeps reporting the rule 10054 Samesite flag.

**To Reproduce**

Something like:

```
docker run -t owasp/zap2docker-stable zap-baseline.py -t https://www.example.com -z '-config "rules.cookie.ignorelist=AWSALB,AWSALBCORS"'
``` 

(requires a site that uses those cookies)

**Expected behavior**

If those cookies are being ignored with `rules.cookie.ignorelist`, then the rule 10054 should be ignored for those cookies, same as rules 10010 and 10011 seem to be ignored.

**Software versions**
 - ZAP: Docker image: `owasp/zap2docker-stable latest a05b3e5e1979`
 - OS: Ubuntu

**Comment by kingthorin** [comment]
[CookieSameSiteScanRule](https://github.com/zaproxy/zap-extensions/blob/master/addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CookieSameSiteScanRule.java) should implement functionality similar to: [CookieSecureFlagScanRule](https://github.com/zaproxy/zap-extensions/blob/f987f3e0e8daf2b6f3675639096c5461e80673a4/addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CookieSecureFlagScanRule.java#L77-L89)

Ref: https://www.zaproxy.org/docs/desktop/ui/dialogs/options/ruleconfig/

[CookieLooselyScopedScanRule](https://github.com/zaproxy/zap-extensions/blob/master/addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CookieLooselyScopedScanRule.java) should also implement the functionality, for consistency's sake.
