### ISSUE TITLE
Multiple site scan with one api endpoint

### ISSUE THREAD

**Issue by kenotsolutions** [zaproxy/zaproxy#6266]
Hi,
We created one API endpoint and started two different sites checks at the same time and we see the two reports contains each other URLs. Is there any way to use one endpoint and get the reports for belongings URL only for each sites? 

Thanks

**Comment by psiinon** [comment]
Please ask questions on the User Group: https://groups.google.com/group/zaproxy-users
We only use issues for identified problems or enhancement requests.
