### ISSUE TITLE
HTML / Markdown Report Generation Fails When Path Contains '#'

### ISSUE THREAD

**Issue by ricekot** [zaproxy/zaproxy#6267]
**Describe the bug**
HTML / Markdown Report Generation fails when the file name or path contains a '#'. XML and JSON reports are generated as expected.

**To Reproduce**
1. Go to 'Report'
2. Click on 'Generate HTML Report' or 'Generate Markdown Report'
3. Save the file with a '#' in it's name or path.

**Expected behavior**
The report is generated without a problem.

**Software versions**
 - ZAP: 2.9.0
 - OS: Windows 10, Linux
 - Java: openjdk version "11.0.8 2020-07-14"

**Additional context**
Discussed on IRC.

**Would you like to help fix this issue?**
Yes.

**Comment by thc202** [comment]
Some of the report add-ons might have the same problem, in case you want to take a look at those as well.
