### ISSUE TITLE
Send button is not displayed on default - "Open/Resend with Request Editor"

### ISSUE THREAD

**Issue by JeeKayPee** [zaproxy/zaproxy#6272]
1. Right-click on Post request (from History or Site Pane)
2. Click on Open/Resend with Request Editor" in the menu
3. The "Manual Request Editor" window would be displayed.

The Send button is missing. 
![2020-11-01_20-50-25](https://user-images.githubusercontent.com/45666264/97806936-1516ab00-1c84-11eb-86bd-cf62ac58bc3f.png)

This is the default view of the window. 
The send button is displayed if we maximize the window. 
![2020-11-01_20-52-46](https://user-images.githubusercontent.com/45666264/97806987-527b3880-1c84-11eb-89f2-f8ca619b4242.png)

I would request the placement of the send button to be brought down to the bottom right-hand side. 
Another possible solution is to make the default as a maximized window, however, placing the Send button to the bottom right would be more pleasing from a usability aspect.

**Comment by JeeKayPee** [comment]
Apologies.. I closed the issue by mistake.. Have reopened it

**Comment by kingthorin** [comment]
Is that with 2.9 or a weekly build?

**Comment by JeeKayPee** [comment]
> Is that with 2.9 or a weekly build?

This is 2.9.0

**Comment by thc202** [comment]
Closing as duplicate of #5831.
