### ISSUE TITLE
PII False-Positive

### ISSUE THREAD

**Issue by qasimmohammed** [zaproxy/zaproxy#6288]
**Describe the bug**
Potential indication of False-Positives:

Finding a lot of reports of PII. When doing a search of the page source, we're unable to locate the Evidence during a search except in 1 instance, where it is a CSS Margin reference

**To Reproduce**
Steps to reproduce the behaviour:
1. Running the Docker command:
`docker run -v /tmp/reports:/zap/wrk --log-driver json-file -t owasp/zap2docker-weekly zap-baseline.py -t <url> -r <url>.html`
where url indicates the URL of the affected site

**Expected behavior**

**Screenshots**

**Software versions**
 - ZAP: owasp/zap2docker-weekly docker image
 - Add-on: Name and version  zap-baseline.py (DIGEST:sha256:32976360a672d0bcaf5481d448f18017b1c56489e222215df0c3074f4bf3e39f)
 - OS: 
 - Java: 
 - Browser:

**Additional context**
Output on the ZAP Report (attached as "zap_issue_1_report_screenshot.png"):

```
High (Medium) | PII Disclosure
-- | --
Description | The response contains Personally Identifiable Information, such as CC number, SSN and similar sensitive data.
 

URL | https://studygroups.accaglobal.com/qa-theme/acca/bootstrap/css/bootstrap.min.css?v=3e64fe949c22031ab5dd
-- | --
Method | GET
Evidence | 36370249136206


Instances | 1
Solution |  
Other information | Credit Card Type detected: DinersClub
 
Reference |  
CWE Id | 359
WASC Id | 13
Source ID | 3

```

Proof that this is not an issue (zap_issue_1_report_proof_screenshot.png)

![zap_issue_1_report_proof_screenshot](https://user-images.githubusercontent.com/37535422/98686490-8cbd9780-2360-11eb-95ce-e97bff57f8d7.png)
![zap_issue_1_report_screenshot](https://user-images.githubusercontent.com/37535422/98688493-cf806f00-2362-11eb-859f-b164bc4f93c8.png)

**Comment by kingthorin** [comment]
It's not a false positive, the value does match the regex.

You can use various mechanisms such as Alert Filters, a progress file, etc to ignore or exclude them.

My question is why are you specifying percentages to 14 decimal places. That seems horribly in-efficient for whatever engine has to render things.

**Comment by psiinon** [comment]
Its an FP in that its not really PII. The fact that the alert gets raised is a problem with the rule not the site :)
Is CSS really that likely to include PII?
We could only check it on a low threshold - I can imagine other cases where we'd get FPs.

**Comment by kingthorin** [comment]
That's a good point, css could be ignored for the most part (cases of text/plain and ending css, or text/css). Within general HTML responses there isn't much we can do about it (maybe check if it's within a style attribute/element).
