### ISSUE TITLE
'Ignored' rules in a custom rule config file should also be excluded from the report

### ISSUE THREAD

**Issue by mig5** [zaproxy/zaproxy#6291]
**Is your feature request related to a problem? Please describe.**

I am using a custom config file to ignore certain rules so that they neither throw a FAIL nor a WARN (very useful for influencing the outcome of Jenkins builds as fail or succeed - thanks!)

This works fine, and those findings are also not thrown to STDOUT. However the 'ignored' rules still appear in the resulting report (e.g `-r report.html` is used), with whatever severity ZAP considers them to be (e.g Medium etc). This causes unnecessary management consternation about false positives.

**Describe the solution you'd like**

A rule marked as `IGNORE` in a custom config file, should be completely excluded from the resulting report. 

Only rules considered FAIL or WARN should appear in the report.

**Comment by psiinon** [comment]
This is the expected behaviour, but I agree its not the way it should really work.
The plan is to completely refactor how the packaged scans working - moving most of the functionality into an add-on which will therefore process the alerts inside ZAP rather than in the scripts.

**Comment by thc202** [comment]
This is a duplicate of #5212.

**Comment by mig5** [comment]
Quite right, sorry! I did search the issue queue but both of those have a bit more cryptic title (neither mention 'report') so I missed it.
