### ISSUE TITLE
`-I` flag doesn't work. 

### ISSUE THREAD

**Issue by prabhakarreddy1234** [zaproxy/zaproxy#6298]
As per the document here - https://www.zaproxy.org/docs/docker/full-scan/

  -I                do not return failure on warning

When i try below command

`docker run --rm -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-full-scan.py -j -t <URL> -g gen.conf -I -s -x OWASP-ZAP-Report.xml -r scan-report.html`

I get this error 

`Invalid option I : option -I not recognized`

**Comment by psiinon** [comment]
Thats only available on the weekly release. Which we should probably point out ;)

**Comment by prabhakarreddy1234** [comment]
Can you make it available in full scan as well? I'm using CICD to run zap full scan and doesn't want to fail the job just because of warnings. Is there any other way we can ignore warnings?

**Comment by psiinon** [comment]
That will happen when we release ZAP 2.10.0, which is getting close. No definite date yet though I'm afraid.
