### ISSUE TITLE
scan report html is missing META end tag

### ISSUE THREAD

**Issue by prabhakarreddy1234** [zaproxy/zaproxy#6302]
I ran below command and it worked well. It generated  .xml and .html reports.

`docker run --rm -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-full-scan.py -j -t <URL> -g gen.conf -x OWASP-ZAP-Report.xml -r scan-report.html`

But when i try to render this report in  Azure Devops i'm getting below warning and the report isn't being rendered.

`scan-report.html. Error : The 'META' start tag on line 3 position 2 does not match the end tag of 'head'. Line 65, position 3`

I do see that `META` tag doesn't have self closing or explicit end tag.

**Comment by psiinon** [comment]
None of the online examples of meta tags show a closing `/` and this reply implies that its not even allowed prior to HTML5 https://stackoverflow.com/questions/19506028/do-you-need-to-close-meta-and-link-tags-in-html

We dont directly put this meta tag in so it might not be easy to change in any case.
You could post process the file and add the slash in? :)

**Comment by thc202** [comment]
I'd suggest closing this, the meta tag does not need to be closed. Seems to be an issue with the renderer.
