### ISSUE TITLE
ZAP proxy and Big Sur OS X

### ISSUE THREAD

**Issue by sbzo** [zaproxy/zaproxy#6305]
**Describe the bug**
After update my OS to Big Sur, some panels are included as tabs in the same ZAP window, hiding the tools bar and blocking ZAP.

**To Reproduce**
1. Open ZAP_D-2020-11-10 in Big Sur.
2. Capture traffic and open the active scan panel.

**Expected behavior**
Each panel should be opened in a different window and not in the same window.

**Screenshots**
<img width="1250" alt="Screen Shot 2020-11-17 at 3 05 59 PM" src="https://user-images.githubusercontent.com/28350322/99442611-a40ffe00-28e7-11eb-9678-a765c277aabb.png">
<img width="1241" alt="Screen Shot 2020-11-17 at 3 06 34 PM" src="https://user-images.githubusercontent.com/28350322/99442618-a5d9c180-28e7-11eb-9541-62d8e320e124.png">

**Software versions**
 - ZAP: ZAP_D-2020-11-10
 - OS: OS X Big Sur
 - Java: java version "15" 2020-09-15 and openjdk version "1.8.0_232"

**Errors from the zap.log file**
[zap_bkp.log](https://github.com/zaproxy/zaproxy/files/5555982/zap_bkp.log)

**Comment by thc202** [comment]
Most likely an issue in the OS/JRE not ZAP.

**Comment by sbzo** [comment]
At this moment I'm considering install Linux in my Mac after install Big Sur :S

**Comment by psiinon** [comment]
Based on the general problems I've seen I have no intention of installing Big Sur on my Mac - I need to be able to actually use it for work.
Be very happy if anyone else would like to try to debug these issues but not something I can help with right now...

**Comment by Big-Juan** [comment]
Hi, Just to say I upgraded to Big Sur. Whenever I try and launch OWASP ZAP I get an error window saying "OWASP ZAP app cannot be opened because the developer cannot be verified" downloaded the latest OWASP ZAP verified checksums to ensure download integrity, same error.

**Comment by thc202** [comment]
That would be #6162, there's a workaround.

**Comment by falconws** [comment]
any update on this?

**Comment by psiinon** [comment]
It doesnt look like it does it? :)
I must admit that I've been puttting off upgrading my Mac to Big Sur because of the potential disruptions to my work.
I guess I should upgrade sooner rather than later so that at least one of the ZAP core team is using it :/

**Comment by ricekot** [comment]
Was this issue resolved?

**Comment by psiinon** [comment]
I've been using Big Sur for a while now and have had no problems with ZAP panels.
If no one else reports any problems soon then I think we can close this...

**Comment by thc202** [comment]
Closing, no reports.
