### ISSUE TITLE
Resume a session after start

### ISSUE THREAD

**Issue by hmolsen** [zaproxy/zaproxy#6306]
**Is your feature request related to a problem? Please describe.**
Sometimes I need to reboot or just restart the vm or even just ZAP during a pentest. I want to continue my session where I left off, after I restart ZAP. But I first have to click "no, i don't want to persist my session at this time" and then go to "file -> open session".

**Describe the solution you'd like**
I would love to have another rotary-button directly after start ("Do you want to persist the ZAP session?"), where I can choose to "Continue existing session." To make sure to continue with the correct session, the text could be "Resume session: [name of the session file]".

**Describe alternatives you've considered**
A dream would be to be able to actually choose the session, just in case you have multiple. But to be honest that's just because I assume that some might find that handy. As I do everything in separate VMs, I always have only the ONE session that I'd like to resume. 

**Additional context**

**Would you like to help implementing this feature?**

**Comment by psiinon** [comment]
TBH I'm nervous about adding more options to this dialog, I worry that people find it too confusing already.
FYI you can specify the existing session to use via the command line using the `-session` parameter: https://www.zaproxy.org/docs/desktop/cmdline/
You can also choose the "Dont show this dialog again" option which would then remove one step from your existing workflow.

It shouldnt be too hard to write a command line script which you could use to always start ZAP with the previous session - you could use this when you wanted to do that and use the std ZAP commands when you didnt. That would need to know where you save your current sessions, but as long as you have a consistant workflow then that shouldnt be a problem.

**Comment by hmolsen** [comment]
Thanks, Simon. Shortcut it with the `-session` param is a great idea and works perfectly for me!

**Comment by psiinon** [comment]
@hmolsen ok to close this issue?

**Comment by hmolsen** [comment]
Totally, thanks for your help!
