### ISSUE TITLE
Cannot Login to Site Using NTLM

### ISSUE THREAD

**Issue by TheBojingles** [zaproxy/zaproxy#6312]
Utilizing OWASP ZAP 2.9.0, I cannot login to a site using NTLM, it seems as though it is not passing the NTLM credentials through the ZAP proxy.  However, I can login fine just using a normal Firefox browsing window.  Checking the receiving server, the server never even see's a attempted login.

**Comment by thc202** [comment]
Could you provide more details on how you are trying to authenticate? Is that with the auth configuration in ZAP? Or, you are just trying to authenticate with the browser proxying through ZAP?
