### ISSUE TITLE
Replacer rule for query and path params

### ISSUE THREAD

**Issue by rakeshjain0512** [zaproxy/zaproxy#6314]
I want to perform OpenAPI 2.0 (swagger) based active scan on one of the API which is having query params and path params.
Using replacer rules, I'm looking to replace the default values used by ZAP (John Doe) with actual values of those parameters at runtime. However it seems that zap-clientapi supports replacer rules for matchtype either of REQ_HEADER, REQ_HEADER_STR, REQ_BODY_STR, RESP_HEADER, RESP_HEADER_STR, RESP_BODY_STR. and not for Query Params and Path Param.
As a result of this it makes the endpoints something like /customer/**customerId**/details , however I'd interested in using actual value of customerId while performing active scan and call should be made like /customer/**123456**/details.

**Comment by psiinon** [comment]
This is already supported - use REQ_HEADER_STR and that will match anything in the full header, including the url and any url parameters.

**Comment by psiinon** [comment]
Maybe we should tweak the help to make this clearer ;)
