### ISSUE TITLE
GraphQL add-on generates invalid message when query depth is reached

### ISSUE THREAD

**Issue by tpodom** [zaproxy/zaproxy#6316]
**Describe the bug**
Using the GraphQL add-on against our schema we ran into an issue with some of the messages being sent having invalid GraphQL syntax.  I was able to debug what the cause was and it was related to the max query depth limit.  What happens is that if the generator is at max query depth - 1 it will recurse into a field.  If that field type has no leaf types then the max query depth limit prevents the generator from adding any of the fields within the current field which leads to an empty selection set: "field { }" which is not valid.

**To Reproduce**
I don't have a pared down GraphQL schema that I can easily share but I think something like the following would reproduce the issue:

```
type User {
  id: ID!
  name: String!
  followers: Follow
}

type Follow {
  follower: User
  followee: User
}

type Query {
  user(id: ID!): User
}
```

**Expected behavior**
The GraphQL generator should not recurse into a field at query depth === max query depth limit - 1 if the field has no leaf fields.

**Screenshots**

**Software versions**
 - ZAP: 2.9.0
 - Add-on: GraphQL 0.2.0
 - OS: Docker Linux
 - Java: [e.g. openjdk version "1.8.0_171"]
 - Browser: N/A

**Errors from the zap.log file**
No errors were generated on the ZAP side.

**Additional context**

**Would you like to help fix this issue?**
I have a fix that I can submit as a PR if the change is acceptable: https://github.com/zaproxy/zap-extensions/compare/master...tpodom:fix_graphql_syntax_error?expand=1

**Comment by kingthorin** [comment]
@ricekot this one's for you 😀

**Comment by ricekot** [comment]
@tpodom Thanks for reporting this issue. Your solution is good, but it will still fail for the following schema:

```graphql
type Query {
  user(id: ID!): User
}

type User {
  follower: Follower
}

type Follower {
  favouriteIceCream: Flavour
}

type Flavour {
  flavour: String
}
```

With `maxQueryDepth = 2`, the query generated is `query { user (id: 1) { } } `

I can think of two possible solutions:
- The simple solution would be for the user to increase the maximum query depth.
- The other solution is to recurse until a field that has leaves is encountered. But this would mean ignoring `maxQueryDepth`.

**Comment by tpodom** [comment]
@ricekot that's a good point.  I wonder if a hybrid approach would work? Something like:
1. Try to continue past maxQueryDepth up to some threshold
2. If the query still cannot be generated properly, provide an error

I'm very new to ZAP so I don't have much experience to say how well #2 would work with providing some error during generation.  The main thing was that right now it required a bit of debugging to get to the root cause.

**Comment by ricekot** [comment]
@tpodom nice suggestions. They actually align with what we discussed on IRC. The plan is to introduce a new option, something like "ignore max query depth if query is invalid" that the user can enable. If the option is disabled, an error message will be displayed and the field (or the whole query) will be skipped. Also, providing/printing an error message should be straightforward as ZAP uses Apache Log4j for logging.
