### ISSUE TITLE
Unable to build zapproxy with gradle 

### ISSUE THREAD

**Issue by mrod23** [zaproxy/zaproxy#6320]
**Describe the bug**
Unable to build zaproxy 

**To Reproduce**
Pulled the latest and ran 
   ~/src/zap/zaproxy   develop  gradle :zap:run

**Expected behavior**
Expected build to work 

**Screenshots**
Command output
```
Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details

> Task :buildSrc:compileKotlin
The `kotlin-dsl` plugin applied to project ':buildSrc' enables experimental Kotlin compiler features. For more information see https://docs.gradle.org/6.7.1/userguide/kotlin_dsl.html#sec:kotlin-dsl_plugin

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/michael.rodriguez/src/zap/zaproxy/zap/zap.gradle.kts' line: 8

* What went wrong:
An exception occurred applying plugin request [id: 'org.zaproxy.zap.distributions']
> Failed to apply plugin class 'com.netflix.gradle.plugins.packaging.SystemPackagingBasePlugin'.
   > Could not create an instance of type com.netflix.gradle.plugins.packaging.ProjectPackagingExtension.
      > Could not find matching constructor for: org.gradle.api.internal.file.copy.DefaultCopySpec(org.gradle.api.internal.file.BaseDirFileResolver, org.gradle.api.internal.file.DefaultFileCollectionFactory, org.gradle.internal.instantiation.generator.DependencyInjectingInstantiator)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org


```
**Software versions**
 - ZAP: pulled the lates 
 - Add-on: none 
- Operation System: Mac
 - Java: openjdk version "1.8.0_275"
- Gradle version: 6.7.1

**Would you like to help fix this issue?**
Yes, I can help push a change. But not sure where to start.

**Comment by thc202** [comment]
Use the Gradle Wrapper, which uses the expected Gradle version.

**Comment by mrod23** [comment]
Sorry, not too familiar with Gradle. 
What would be the command I would run to use the gradle wrapper?

**Comment by mrod23** [comment]
Sorry, I'm not too familiar with Gradle. 
Can you send over the command I would run to use the wrapper?

**Comment by thc202** [comment]
Since you are using Mac, run `./gradlew`. More details about the wrapper in https://docs.gradle.org/current/userguide/gradle_wrapper.html#sec:using_wrapper

**Comment by mrod23** [comment]
thanks, that got it working for me
