### ISSUE TITLE
ZAP report html still shows ignore and pass information even when I use custom config file

### ISSUE THREAD

**Issue by yrlyd** [zaproxy/zaproxy#6321]
I want to try mark false positive by using zap-baseline.py from zap2docker-stable. 
I already create the custom config file like this : 
10010	FAIL	(Cookie No HttpOnly Flag)
10011	FAIL	(Cookie Without Secure Flag)
10012	FAIL	(Password Autocomplete in Browser)
10015	FAIL	(Incomplete or No Cache-control and Pragma HTTP Header Set)
10016	FAIL	(Web Browser XSS Protection Not Enabled)
10017	FAIL	(Cross-Domain JavaScript Source File Inclusion)
10019	FAIL	(Content-Type Header Missing)
10020	FAIL	(X-Frame-Options Header Scanner)
10021	FAIL	(X-Content-Type-Options Header Missing)
10023	IGNORE	(Information Disclosure - Debug Error Messages)
10024	IGNORE	(Information Disclosure - Sensitive Informations in URL)
10025	IGNORE	(Information Disclosure - Sensitive Information in HTTP Referrer Header)
10026	IGNORE	(HTTP Parameter Override)
10027	IGNORE	(Information Disclosure - Suspicious Comments)
10032	IGNORE	(Viewstate Scanner)
10040	IGNORE	(Secure Pages Include Mixed Content)
10105	IGNORE	(Weak Authentication Method)
10202	IGNORE	(Absence of Anti-CSRF Tokens)
2	IGNORE	(Private IP Disclosure)
3	IGNORE	(Session ID in URL Rewrite)
50001	IGNORE	(Script Passive Scan Rules)
90001	IGNORE	(Insecure JSF ViewState)
90011	IGNORE	(Charset Mismatch)
90022	IGNORE	(Application Error Disclosure)
90030	IGNORE	(WSDL File Passive Scanner)
90033	IGNORE	(Loosely Scoped Cookie)

but the html report still giving the same result still shows the same results when using a custom config file or using the default config file

I stored the gen.conf file to /zap/wrk/gen.conf

and using this command : 
`docker run -it owasp/zap2docker-stable /bin/bash -c "zap-baseline.py -t https://google-gruyere.appspot.com/534819239978349857162720010207950251616/ -a -c gen.conf -u /zap/wrk/ -r testreport.html"`

by log, its already correct, but somehow the html report still show the same output with default config file
is there any missing step here?

**Comment by thc202** [comment]
Closing as duplicate of #5212.
