### ISSUE TITLE
Getting Ban while fuzzing

### ISSUE THREAD

**Issue by SamirHamoud** [zaproxy/zaproxy#6323]
hello , i use POST Request method with Fuzzer on Login Page of a website but
when i enter the username/password  about 5-10 wrong times i get ban IP for 15 minutes!
is there any way to avoid getting ban  in login page or trying alot as i want without ban?
or can i change IP every request while fuzzing ?

plz help

**Comment by thc202** [comment]
This is a question for the [User Group](https://groups.google.com/group/zaproxy-users).

It's possible to use other IPs while fuzzing but it's not a built-in capability of ZAP.

**Comment by SamirHamoud** [comment]
It's possible to use other IPs while fuzzing but it's not a built-in capability of ZAP.

you mean i could change IP for every request ? 
i don't need One for all requests , that is the problem as i will get ban too
i wanna use random IPs every POST Request ! 
if i could , plz explain how to do it or give me any guide , thx

**Comment by kingthorin** [comment]
As @thc202 already said this isn't a functionality built into ZAP so you're better off asking for advice in the [User Group](https://groups.google.com/group/zaproxy-users).

**Comment by SamirHamoud** [comment]
Thx anyway

**Comment by SamirHamoud** [comment]
Hello ,
Is there anyway to bypass re-captcha while fuzzing ?
can't fuzz if website has re-captcha in response!

Plz help

**Comment by kingthorin** [comment]
Please don't ask questions as issues - the [ZAP User Group]( https://groups.google.com/group/zaproxy-users) is a much better place for questions.

If you’re asking about a third party components such as the Jenkins plugin or VSTS plugin please look for their preferred support mechanism as these were not created by and are not supported by the core team.

**Comment by SamirHamoud** [comment]
guys , i spent at least 1-2 years wasting time to find a way to bypass
captcha api v2-v3 images while fuzzing with Owasp Zap Proxy , but i
couldn't ! :(
please if anyone know the solution , help me!
i'm really so tired of that , where are the scientists ?!
