### ISSUE TITLE
AlertFilter changes are not reflected into HTML, JSON, XML report extraction

### ISSUE THREAD

**Issue by chvasu** [zaproxy/zaproxy#6324]
**Describe the bug**
Using the ZAP GUI, I marked an alert raised by ZAP as 'False Positive' by updating the 'Confidence' using the AlertFilter. This change is not reflected onto the ZAP reports extracted (either by REST API or from GUI) for HTML, JSON and XML formats.

**To Reproduce**
see above description

**Expected behavior**
Confidence value shown in HTML, JSON, XML reports as updated from AlertFilter addon.

**Screenshots**
none

**Software versions**
 - ZAP: 2.9.0 stable
 - Add-on: AlertFilter
 - OS: Windows 10
 - Java: Oracle Java version "1.8.0_231"
 - Browser: Chrome 87

**Errors from the zap.log file**
no errors in the log file.

**Additional context**
none

**Would you like to help fix this issue?**
no, hope that a fix is possible on this from the community

**Comment by thc202** [comment]
Related User Group thread: https://groups.google.com/g/zaproxy-users/c/kQr78Enao9A/m/N1CLETw-CAAJ

**Comment by psiinon** [comment]
@chvasu as per my reply on the User Group - did you apply the filter?
If not then this is working as expected.

**Comment by chvasu** [comment]
Yes, Simon. I confirm I created, tested, and applied the filter via the GUI and also the REST API.
However, I have used the cross-platform package, not the executable installer of ZAP.

**Comment by kingthorin** [comment]
The alerts do show as updated in the UI after applying the filter?

**Comment by chvasu** [comment]
Strangely, after restarting ZAP, it started to work fine. Apologies for the confusion. Closing the issue.
That said, I am a little disappointed that we cannot create a false positive on a ZAP alert using the REST API yet. It works only from the GUI and can be read using the REST API.

**Comment by psiinon** [comment]
@chvasu it should work fine via the API - maybe follow up on this on the ZAP User Group?

**Comment by kingthorin** [comment]
If you're using an up-to-date weekly you can bulk update alerts' Risk or Confidence: https://github.com/zaproxy/zaproxy/pull/5975
