### ISSUE TITLE
i meet a problem using WASZAP on linux command line

### ISSUE THREAD

**Issue by Oranger1** [zaproxy/zaproxy#6325]
i'm learning  to use sniper , and i need OWASP ZAP Integration;
![image](https://user-images.githubusercontent.com/65127626/100334186-68bfae80-300e-11eb-9ceb-9614bd263665.png)

But I don't know how to run OWASP and change port from 8080 to 8081 on linux command line.

![image](https://user-images.githubusercontent.com/65127626/100334433-bf2ced00-300e-11eb-9ac7-6715ae98e0be.png)

 i‘m so sorry for My English is poor so maybe some explaination is not accurate enough.

**Comment by thc202** [comment]
The command line argument is `-port`, so `-daemon -port 8081`.
https://www.zaproxy.org/docs/desktop/cmdline/

Usage questions should be asked in the [User Group](https://groups.google.com/group/zaproxy-users).

**Comment by Oranger1** [comment]
> 命令行参数是`-port`，如此`-daemon -port 8081`。
> https://www.zaproxy.org/docs/desktop/cmdline/
> 
> 使用问题应在[用户组中提出](https://groups.google.com/group/zaproxy-users)。



> The command line argument is `-port`, so `-daemon -port 8081`.
> https://www.zaproxy.org/docs/desktop/cmdline/
> 
> Usage questions should be asked in the [User Group](https://groups.google.com/group/zaproxy-users).

thanks!

but  i can't find another command's answer from  https://www.zaproxy.org/docs/desktop/cmdline/


![image](https://user-images.githubusercontent.com/65127626/100337524-7119e880-3012-11eb-9dcd-56665a59a628.png)

**Comment by thc202** [comment]
The following FAQ entry explains how to disable the API:
https://www.zaproxy.org/faq/why-is-an-api-key-required-by-default/

**Comment by Oranger1** [comment]
thank you very much！ Thanksgiving wishes for you and your family！

**Comment by Oranger1** [comment]
> The following FAQ entry explains how to disable the API key:
> https://www.zaproxy.org/faq/why-is-an-api-key-required-by-default/

thank you very much！ Thanksgiving wishes for you and your family！
