### ISSUE TITLE
Launch Browser not working in Manual Explore

### ISSUE THREAD

**Issue by najum98** [zaproxy/zaproxy#6326]
The "Launch Browser" button is not working in Manual explore section of ZAP, I have tried both with Chrome and Firefox, by enabling/disabling the HUD, but the button just presses and nothing happens, not even a message appears telling me about some error.

**To Reproduce**
1. Open ZAP
2. Go to "Manual Explore" under Quick Start
3. Click on "Launch Browser"

**Expected behavior**
I obviously was expecting for the proxy's browser to open up.

**Software versions**
 - ZAP: 2.9.0
 - OS: Parrot OS
Picked up _JAVA_OPTIONS: -Xmx512M
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b01-1-b01)
OpenJDK 64-Bit Server VM (build 25.212-b01, mixed mode)
 - Browser: Tried with both chrome and firefox

**Would you like to help fix this issue?**
Yes

**Comment by kingthorin** [comment]
Please refer to https://github.com/zaproxy/zaproxy/issues/6199

This seems to be an issue that the ParrotOS crew need to address.
