### ISSUE TITLE
Generate Alert Report freezes the zap application 

### ISSUE THREAD

**Issue by mohamedelgaml** [zaproxy/zaproxy#6336]
**Describe the bug**
when I try to generate a report all the report generated and working successfully but when trying to generate the Alert report the application freezs 
de any advice and guidance you need.

The current version is **2.9**

**Comment by kingthorin** [comment]
You mean with the add-on? 

If so, what customizations are you doing? How many alerts are you trying to report on?

**Comment by mohamedelgaml** [comment]
I need to report the high alerts only these threats are 50 but the overall alerts are more than 100K

**Comment by kingthorin** [comment]
Okay that gives us a better idea what's going on. Could you check if the "Export Report" add-on meets your requirement> https://www.zaproxy.org/docs/desktop/addons/export-report/

We are slowly phasing out the other reporting add-ons and merging any unique functionality into that one.

**Comment by thc202** [comment]
Did you check the zap.log file? https://www.zaproxy.org/faq/where-does-zap-put-its-logs/

**Comment by mohamedelgaml** [comment]
The report generated successfully but I must wait a long time to get my report

**Comment by mohamedelgaml** [comment]
Please be noted the same issue found also at the **Customize HTML Report**

**Comment by thc202** [comment]
Closing, the Alert Report add-on is being superseded by the Report Generation add-on:
https://www.zaproxy.org/docs/desktop/addons/report-generation/
