### ISSUE TITLE
Render HTML [bug or misconfiguration] 

### ISSUE THREAD

**Issue by Darkcast** [zaproxy/zaproxy#6339]
my apoligies if this has been covered here before I couldnt find the spesific issue for mac or the fix online 
I am sure i am doing something wrong and there something config I havent set up in my path or something 
if there is a wiki entry or an article that you could refer me to the fix I would greatly apreciated 
Thank you in advance
[zap.log](https://github.com/zaproxy/zaproxy/files/5635788/zap.log)
<img width="530" alt="Screen Shot 2020-12-03 at 5 58 15 AM" src="https://user-images.githubusercontent.com/1676655/101013632-989d1380-3532-11eb-920e-b5bf4f91cfb0.png">

**Describe the bug**
See image 

**To Reproduce**
open zap

**Expected behavior**
to run without problems 

**Screenshots**

**Software versions**
 - ZAP:290
 - Add-on: render HTML
 - OS: Catalina
 - Java: 
openjdk version "15.0.1" 2020-10-20
OpenJDK Runtime Environment (build 15.0.1+9)
OpenJDK 64-Bit Server VM (build 15.0.1+9, mixed mode, sharing)
- Browser: FF 83.0
**Errors from the zap.log file**
logged attached

**Additional context**
Yes, I LOVE ZAP ITS way better thought out than burp. Long live ZAP 👍 

**Would you like to help fix this issue?**
sure, its 2020 what could you wrong eh ?

**Comment by kingthorin** [comment]
It seems you've installed basically every available add-on. While that's fine it will definitely impact performance. If you have a requirement to use Browser View then yes you'll need to install JavaFX, the warning you received is perfectly normal.

**Comment by Darkcast** [comment]
> It seems you've installed basically every available add-on. While that's fine it will definitely impact resource usage (RAM/CPU). If you have a requirement to use Browser View then yes you'll need to install JavaFX, the warning you received is perfectly normal.

Yes you're totally correct, I am trying to learn how to use each and them decide if I need them or not.

**Comment by Darkcast** [comment]
Is there anything else you need from me?
Thank you for your time and help

**Comment by kingthorin** [comment]
Did installing JavaFX address the issue? Or, have you decided to proceed without Browser view?

**Comment by Darkcast** [comment]
I have installed javafx but still have the sams issue :( maybe installed it incorrectly.
what would be the best way to install java fx brew or ?
is there any particular command or logs you need me to provide to find out what the issue is ?
thank you for your help

**Comment by Darkcast** [comment]
ive tried everything and still havent been able to fix the rendering issue

**Comment by knassar702** [comment]
hi @Darkcast 
just download JavaFX and run this command

`$ java --module-path /usr/share/openjfx/lib/ --add-modules javafx.swing,javafx.web zap.jar`

https://github.com/knassar702/bruh2/blob/master/_posts/2020-09-09-htmlzaproxy.md

regards

**Comment by Darkcast** [comment]
> openjfx

will try it and report back. thank for the reply

**Comment by kingthorin** [comment]
@ Darkcast  success?

**Comment by kingthorin** [comment]
Same issue and solution covered here: https://stackoverflow.com/questions/66733466/javafx-noclassdeffounderror-zap-plugin-browser-view

Closing due to lack of reporting user follow-up.
