### ISSUE TITLE
Persist all data across sessions

### ISSUE THREAD

**Issue by bitshiftnetau** [zaproxy/zaproxy#6344]
**Is your feature request related to a problem? Please describe.**
I want to pause and persist forced browsing across sessions. Some targets take days to scan with the default wordlist and it would be really great to not lose that in case of a reboot. 

**Describe the solution you'd like**
I want more data to be included in the session persistence. Namely the percentage that has already been scanned during forced browsing, so I don't have to start from the beginning of the wordlist. I should be able to pause the browsing, save the session, close and re-open zaproxy, then hit play like nothing happened. It should be the same for any and all anything in zaproxy for persistence. Sure, I exported the results to csv at 15% but the scan is not complete.  

**Describe alternatives you've considered**
Using burp? I don't know if they have that feature either *shrugs*

**Would you like to help implementing this feature?**
I know it's a big ask and you probably haven't done this for a reason, or there is a better alternative. If it's simply the time needed to actually implement then yeh definitely I would be happy to instantiate this feature :) but I'm not available before April 2021 (OSCP, then moving country haha crazy times!)

**Comment by DiogoMRSilva** [comment]
This looks similar to https://github.com/zaproxy/zaproxy/issues/4270

**Comment by thc202** [comment]
Better make the other a tracker issue then.
