### ISSUE TITLE
Forced to enter data for fields I havent checked on ZAP plugin in Jenkins

### ISSUE THREAD

**Issue by laila2903** [zaproxy/zaproxy#6346]
Hey! I am being forced to enter data for fields I have not marked, for instance authentication fields are marked as required even though I wan¨t to execute simple ZAP scan. This is the ZAP Jenkins integration. 
<img width="1264" alt="Skjermbilde 2020-12-06 kl  21 31 13" src="https://user-images.githubusercontent.com/43816009/101291717-2c106600-380b-11eb-83f5-e277397b8804.png">

<img width="1264" alt="Skjermbilde 2020-12-06 kl  21 31 26" src="https://user-images.githubusercontent.com/43816009/101291728-3d597280-380b-11eb-8939-2b892071017f.png">

<img width="1280" alt="Skjermbilde 2020-12-06 kl  21 31 38" src="https://user-images.githubusercontent.com/43816009/101291731-41859000-380b-11eb-8137-b483da175cb3.png">

<img width="1255" alt="Skjermbilde 2020-12-06 kl  21 31 55" src="https://user-images.githubusercontent.com/43816009/101291734-45191700-380b-11eb-8fc1-d78cff8e8cd9.png">

**Comment by kingthorin** [comment]
Please don't ask questions as issues - the [ZAP User Group]( https://groups.google.com/group/zaproxy-users) is a much better place for questions.

If you’re asking about a third party components such as the Jenkins plugin or VSTS plugin please look for their preferred support mechanism as these were not created by and are not supported by the core team.
