### ISSUE TITLE
keepng alerts between scans

### ISSUE THREAD

**Issue by ghostinside** [zaproxy/zaproxy#6351]
when i do the first scan i have a bunch of alerts which are true to the current state of the application, if some of the alerts were fixed & new scan was running, the old alerts are still shown, if i clear the alerts tree & perform a scan once again, not all the alerts are shown after the scan. 

To get the app fully clearly tested once again i need to close the app & run the recording once again before the scan, creating new context does not help

owasp zap 2.9.0

**Comment by psiinon** [comment]
Sorry, I dont understand.
You've cleared the alerts, but you somehow want them kept?
In any case, theres no enough info here for us to do anything.

**Comment by ghostinside** [comment]
two scenarios:

- first, have alert, have it fixed & news scan running, despite fix alert still in the tree

- second, have alerts, fix them, a clear tree, run test once again, just few will found & presented in the tree. Close app, do new manual "recording", run scan, much more alerts will found 

please let me know if you need more details

**Comment by psiinon** [comment]
If you run a scan, clear the alerts and then run the same scan again then I would expect the same alerts to be found. But that does depend on the application responding in the same way to both scans.
If you perform a scan, create a new session and then perform the same steps I would also expect ZAP to find the same alerts, but again it depends on the app responding in the same way.
So I dont think you are doing anything that we wouldnt expect to work, if that makes sence.
I believe you when you say that ZAP is reporting more or less alerts, but just saying that doesnt help us much.
Ideally we'd need a test case that we can reproduce.
If we cant reproduce the problem then we cant investigate or fix it.

Failing that you'll need to do some investigating yourself.
Pick any of the alerts that either is or is not raised in one of the cases.
Check to see if the application responds in the same way to the attack that was reported.
ZAP scan rules are mostly fairly straightforward - if you app responds in the same way they will find the same things.
My initial guess is that your app is responding differently, but that is just a quess - we have no evidence to indicate whats actually going on.

**Comment by psiinon** [comment]
I believe you, I really do.
But I dont know what those alerts are or how your app is responding.
I cant reproduce this problem from a couple of screenshot showing different numbers.

Someone will need to work out what is going on by analysing what ZAP is sending to your app and how it is responding.
If this is a publicly available app then we can do that.
If its not then I'm afraid you (or someone else with access to the app) will have to do that. 
We can guide you but we cant guess what your app is doing.

**Comment by ghostinside** [comment]
the app is web API wich will respond exactly the same if you send  to it "same"(similar) parameters 

first screen alerts are: X-Frame-Options Header Not Set, Path Traversal, X-AspNet-Version Response Header, Incomplete or No Cache-control and Pragma HTTP Header Set, Server Leaks Information via "X-Powered-By" HTTP Response Header Field(s), X-Content-Type-Options Header Missing, Absence of Anti-CSRF Tokens, Cookie Without Secure Flag, Cross Site Scripting Weakness (Reflected in JSON Response), Cross Site Scripting Weakness (Persistent in JSON Response), Timestamp Disclosure - Unix, Information Disclosure - Suspicious Comments

the second screen alerts are: Cross Site Scripting Weakness (Reflected in JSON Response), Cross Site Scripting Weakness (Persistent in JSON Response)

the third same as first, but without Path Traversal

The wireless is that if you can see most of the alerts related to headers, which depends on the webserver configuration  &  still the same between scans / attacks

**Comment by ghostinside** [comment]
the web server is iis 10

**Comment by ghostinside** [comment]
running to the same issue again with another webapp, restored session from a snapshot, cleared events, started scan, just two alerts so far:

Cross Site Scripting Weakness (Reflected in JSON Response), Cross Site Scripting Weakness (Persistent in JSON Response) 

as soon as the scan ends will record again & run

**Comment by ghostinside** [comment]
newly recorded scan shows a completely diff picture 

![image](https://user-images.githubusercontent.com/10547793/101780049-1484f600-3b07-11eb-95ce-b8c97ec9f98a.png)

**Comment by ghostinside** [comment]
@psiinon i see that most alerts come when i record the application(manual explore), what is the diff between manual & scan approaches? 

P.S hud is disabled

**Comment by psiinon** [comment]
ZAP passively scans all of the requests that are proxied through it: https://www.zaproxy.org/docs/desktop/start/features/pscan/
When you perform and active scan ZAP will actively attack your app: https://www.zaproxy.org/docs/desktop/start/features/ascan/
TB I think we should close this issue and continue any discussions on the ZAP User Group: https://groups.google.com/group/zaproxy-users
So far it looks like ZAP is acting as designed. If we do find out that there are issues here then we can raise new (and more specific) issues...

**Comment by ghostinside** [comment]
lets close
