### ISSUE TITLE
Search/Find Highlight Issue

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#6359]
**Describe the bug**
While I was working towards adding some new functionality to the Wappalyzer extension I encountered a scenario whereby using the Search panel and leveraging the "Next" button to move through matches stopped highlighting the string that was actually being searched for. The first and second match were correct but subsequent highlights/matches highlighted seemingly random strings.

**To Reproduce**
1. Launch ZAP
2. Launch a browser from within ZAP (I used Firefox v83)
3. Browse to https://vuetifyjs.com/en/, (this next part may not technically be necessary, just covering what I'd done) scroll down to the project sponsors section, open the Crowdin and 'made with vue.js' links in new tabs.
4. In ZAP goto the Search tab and search for `.d-block `
5. Note a series of matches in `https://vuetifyjs.com/js/examples-source.bb0567b1.js`

**Expected behavior**
Correct highlights/matches.

**Screenshots**
![image](https://user-images.githubusercontent.com/7570458/101983298-31751280-3c48-11eb-8d2b-8d2be867c877.png)

**Software versions**
 - ZAP: Dev
 - Add-on: N/A
 - OS: Windows 10
 - Java: Adopt OpenJDK 11.0.9.1
 - Browser: Firefox v83

**Errors from the zap.log file**
None.

**Comment by kingthorin** [comment]
![image](https://user-images.githubusercontent.com/7570458/101983338-83b63380-3c48-11eb-9816-5c5ba7b3d768.png)

**Comment by kingthorin** [comment]
Note the issue manifests with or without the leading period, and also seems to impact the ctrl+F (Find) functionality.

**Comment by theamanrawat** [comment]
Hi @kingthorin , This search works on regular expressions so If You want to search `.d-block` then search it like this `(\.)d-block` and here is result.

![Screenshot 2020-12-15 182536](https://user-images.githubusercontent.com/35992750/102217756-13870680-3f03-11eb-931c-4fea1217af72.png)

**Comment by kingthorin** [comment]
Thanks, keep looking beyond the first two matches and you'll see manifestation of the issue.

Also note the leading period isn't [relevant](https://github.com/zaproxy/zaproxy/issues/6359#issuecomment-743747054). So there's no need to worry about escaping it.

**Comment by kingthorin** [comment]
I've just re-tested this in an up-to-date dev environment. It seems to behave as expected with 2.12.0 and the updated large response handling.
