### ISSUE TITLE
A post request is sent, but a get request is intercepted

### ISSUE THREAD

**Issue by cheng2020-G** [zaproxy/zaproxy#6362]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Software versions**
 - ZAP: [note that we typically only support the latest version of ZAP]
 - Add-on: Name and version [e.g. Passive Scan Rules Alpha v19. https://www.zaproxy.org/faq/how-do-i-see-what-version-of-an-add-on-extension-i-have-installed/]
 - OS: [e.g. Windows 10]
 - Java: [e.g. openjdk version "1.8.0_171"]
 - Browser: [e.g. chrome 66, firefox 59, safari 11.1]

**Errors from the zap.log file**
See https://www.zaproxy.org/faq/what-is-the-default-directory-that-zap-uses/ for the location of the zap.log file for your OS.

**Additional context**

**Would you like to help fix this issue?**
Just say if you'd like to try and help fix this issue. We'll provide any advice and guidance you need.

**Comment by kingthorin** [comment]
Closing, zero detail provided.

**Comment by thc202** [comment]
And for the record, ZAP by itself does not change the method of the requests intercepted.

**Comment by cheng2020-G** [comment]
1、Using JMeter to initiate post request



2、Block get request







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zaproxy/zaproxy"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月16日(星期三) 下午5:26
收件人:&nbsp;"zaproxy/zaproxy"<zaproxy@noreply.github.com&gt;;
抄送:&nbsp;"千^bei^不醉"<1007884377@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zaproxy/zaproxy] A post request is sent, but a get request is intercepted (#6362)





 
And for the record, ZAP by itself does not change the method of the requests intercepted.

**Comment by psiinon** [comment]
Still not enough evidence - we'll need some way to reproduce this. Are you sure JMeter isnt really generating a GET request?

**Comment by cheng2020-G** [comment]
JMeter actually generates two requests, a post and a get, but I only set the request once











------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zaproxy/zaproxy"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月16日(星期三) 下午5:47
收件人:&nbsp;"zaproxy/zaproxy"<zaproxy@noreply.github.com&gt;;
抄送:&nbsp;"千^bei^不醉"<1007884377@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zaproxy/zaproxy] A post request is sent, but a get request is intercepted (#6362)





 
Still not enough evidence - we'll need some way to reproduce this. Are you sure JMeter isnt really generating a GET request?
