### ISSUE TITLE
Fingerprinting tools - window text unreadable and unable to resize

### ISSUE THREAD

**Issue by securestep9** [zaproxy/zaproxy#6367]
**Describe the bug**

**To Reproduce**
1. Go to 'Tools->Fingerprinting tools
2. try to read text ending '...'
3. try to resize the window to be able to read the shortened text (not working)
4. Try to read the text endin '...'
5.  try to resize the window to be able to read the shortened text (not working)

**Expected behavior**
1. 'javascirpt -frameworks' and What to fingerp... text fits inside the windows so it is readable
2. The 'Fingerprinting tools' window is resizable 
3. when the windows i resized the shortened text showing '...' is expanded and the full label text is shown

**Screenshots**
screenshots attached
**Software versions**
 - ZAP: 2.10.0
 - Add-on: Name and version [e.g. Passive Scan Rules Alpha v19. https://www.zaproxy.org/faq/how-do-i-see-what-version-of-an-add-on-extension-i-have-installed/]
 - OS: macOS
 - Java: jdk 1.8.0_271
 - Browser: chrome 87
**Errors from the zap.log file**
no errors observed
![Screen Shot 2020-12-17 at 22 02 14](https://user-images.githubusercontent.com/20112179/102550332-9354d280-40b5-11eb-9534-9340bbd8abe6.png)
![Screen Shot 2020-12-17 at 22 02 31](https://user-images.githubusercontent.com/20112179/102550337-9485ff80-40b5-11eb-920a-030904313b1b.png)

**Additional [context**](url)
n/a
**Would you like to help fix this issue?**
n/a

**Comment by theamanrawat** [comment]
This extension has been removed.

zaproxy/zap-extensions#2657

**Comment by psiinon** [comment]
Removing from the marketplace via https://github.com/zaproxy/zap-admin/pull/452
Once thats merged then this issue can be closed.

**Comment by thc202** [comment]
No longer available in the marketplace.
