### ISSUE TITLE
can't resend request

### ISSUE THREAD

**Issue by kabezag** [zaproxy/zaproxy#6368]
**Describe the bug**
In today's update i cannot use the "resend request" feature. If the boton exist somewhere is not easy to see..

![image](https://user-images.githubusercontent.com/73066776/102660285-8f7a8c00-4159-11eb-8fd7-2a6ddd59c4e3.png)

version 2.10.0

**Comment by kingthorin** [comment]
Could you try moving the left/right divider further to the right?

**Comment by kabezag** [comment]
black magic! that fix my problem haha, thanks!

**Comment by kingthorin** [comment]
Great, thanks for letting us know.

I’m going to leave this open we should see if there’s something we can do for those situations.

**Comment by thc202** [comment]
Closing as duplicate of #5831.
