### ISSUE TITLE
Core API messages' related views return less messages than available

### ISSUE THREAD

**Issue by wadim-al** [zaproxy/zaproxy#6375]
**Describe the bug**
core.number_of_messages() function returns less messages, than I can see in the GUI.

**To Reproduce**
1. Run `pip3 install python-owasp-zap-v2.4`
2. Start ZAP
3. Turn off ZAP API key so the test script works with less modifications, enable localhost in additional local proxies
4. Proxy some requests from browser
5. Run the following script, adjust proxy IP or port as needed:
[test.txt](https://github.com/zaproxy/zaproxy/files/5751175/test.txt)
6. Proxy some more requests
7. Check if `core.number_of_messages()` function returns the right amount.

**Expected behavior**
If user sees 40 messages proxied in the GUI, than `core.number_of_messages()` should return 40.

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/29713984/103294239-82d02080-4a02-11eb-9d10-94dae8c66355.png)

**Software versions**
 - ZAP: D-2020-12-21 and many previous versions
 - OS: Windows 10 x64
 - Java: Java(TM) SE Runtime Environment (build 1.8.0_271-b09)
 - Python: 3.7.9
 - API python-owasp-zap-v2.4 0.0.18

**Errors from the zap.log file**
none

**Additional context**
none

**Would you like to help fix this issue?**
Yes.

**Comment by wadim-al** [comment]
I have no idea why but it stopped reproducing.

**Comment by thc202** [comment]
The messages' views don't return images, the difference might be because of that.

**Comment by wadim-al** [comment]
In the following example there are 8 nonimage requests and API returns 31, and the last nonimage request id is 32. If images weren't returned that would be 32 total - 24 images = 8 nonimage, but I have 31.
![Untitled](https://user-images.githubusercontent.com/29713984/103347550-5969d000-4aa8-11eb-8b87-e8a0ed6606ff.png)

**Comment by thc202** [comment]
The "missing" messages in the History tab would be the temporary messages, more details in: https://www.zaproxy.org/faq/why-are-there-missing-history-ids/
