### ISSUE TITLE
Zap scan got stuck at 56%

### ISSUE THREAD

**Issue by abhishek-mathur2** [zaproxy/zaproxy#6379]
We have execute Zap scan for each release and we have used Week Zap docker image. Earlier it was working fine for same set of sites. But it always stuck on 56%. Eventually sometimes its running fast and completed in 70 mins only.
OS: Linux

**Comment by psiinon** [comment]
Please ask about this on the ZAP User Group first: https://groups.google.com/group/zaproxy-users
We need to understand whats going on and then raise more specific issues if required.
