### ISSUE TITLE
Proxy script return value misinterpreted in 2.10.0

### ISSUE THREAD

**Issue by wing0ver** [zaproxy/zaproxy#6381]
**Describe the bug**
Hi,
Not sure if it's related to the version, but since the update to 2.10.0, I have this issue.

If I enable a proxy script, I have the error "Secure Connection Failed" in the browser when I try to connect to any url.
- it was working fine before the update (not 100% sure when it start to fail)
- I'm using dynamic SSL certificates, and SSL is working fine if I use proxy without any script enabled
- I tested with Jython and  Zest script, even with basic provided templates (so it's not related to the script himself)
- I tried to regenerate SSL certs, but doesn't help.
- no error in logs

From the browser side, it looks like the SSL is not validated when script is enabled.

Any advice to solve this issue ? 

Thanks

**To Reproduce**
1. Setup dynamic SSL certificates and browser proxy to connect through zap
2. Create new proxy script (jython or zest) and choose any default template
3. Enable the script
4. Connect to any url from browser

**Expected behavior**
Connection should be done and the script should be executed.

**Software versions**
 - ZAP: 2.10.0
 - Browser: Tried with Firefox & Chrome
 - OS : Kali linux

**Errors from the zap.log file**
No error in zap log.

**Would you like to help fix this issue?**
sure

**Comment by thc202** [comment]
What's the actual error?

**Comment by wing0ver** [comment]
In the browser I get this error  : "Secure Connection Failed" 
- The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
- Please contact the website owners to inform them of this problem.

Looks like SSL error, but it happens only if a proxy script is enabled.

**Comment by mayhem-am** [comment]
Does it help if you downgrade geckodriver version from 0.27.0 to 0.24.0?

**Comment by wing0ver** [comment]
No, same issue after downgrading geckodriver.

**Comment by johnz** [comment]
I have the same issue after upgrade to ZAP 2.10.0

When ZAP proxy script enabled
- request doesn't show under the history
- in Chrome dev tool network tab request show (failed)net::ERR_EMPTY_RESPONSE

When ZAP proxy script disabled
- request come through normal

When downgrade to ZAP 2.9.0 proxy script enabled, use the same Root CA Certificate
- request come through normal

**Comment by thc202** [comment]
The messages are being dropped instead of forward in 2.10 as the return value is being misinterpreted, as workaround you can change the script to return false.
