### ISSUE TITLE
Toolbar and Footer are tiny

### ISSUE THREAD

**Issue by avivmu** [zaproxy/zaproxy#6382]
The Toolbar & the Footer are very small and not proportional to the other UI elements.

![image](https://user-images.githubusercontent.com/19804341/104130126-c1a59500-5377-11eb-9525-529bf9a19fc3.png)

I'm on Fedora 32, java 15

[zap.log](https://github.com/zaproxy/zaproxy/files/5792997/zap.log)

It's the first time I'm opening zap.

**Comment by kingthorin** [comment]
Are you using a High DPI display or do you have scaling turned on in the Operating System?

**Comment by psiinon** [comment]
If so see https://www.zaproxy.org/faq/how-can-i-run-zap-with-a-high-dpi-display/

**Comment by avivmu** [comment]
> If so see https://www.zaproxy.org/faq/how-can-i-run-zap-with-a-high-dpi-display/

Thanks, I used the 

>  -Dsun.java2d.uiScale=2.5

And it works:
![image](https://user-images.githubusercontent.com/19804341/104188227-937c8f80-5421-11eb-8655-df7775273e5f.png)
