### ISSUE TITLE
Duplicate labels - idealFirstBug & good first issue

### ISSUE THREAD

**Issue by avivmu** [zaproxy/zaproxy#6391]
No need two labels for the same purpose

**Comment by psiinon** [comment]
We introduced idealFirst bug many years ago. Github then 'standardized' on 'good first issue'.
We decided to support both and while I'm happy to revisit that decision I'm not sure what advantage there is to dropping one of them?

**Comment by avivmu** [comment]
What advantage is to _have_ duplicate labels?
I agree that it's not a major problem but it's just less confusing new members, and less labeling for veteran members

**Comment by thc202** [comment]
For older links to keep working.

**Comment by thc202** [comment]
The labels have now descriptions, which should help clarify any confusions.

**Comment by avivmu** [comment]
What links will not work anymore if we remove a label? Also I cannot see the full description of idealFirstBug since it's truncated. Instead of dropping one we could deprecate it, and then after some time (hopefully) there will be no open issues with that label

**Comment by thc202** [comment]
That would lead to the problem mentioned above, older links would no longer show any issue.

**Comment by psiinon** [comment]
Pages like https://owasp.org/www-community/initiatives/gsoc/gsoc2020ideas link to the idealFirstBug's.
We probably wont have access to change all of the pages that link to them, and definitely wont have the ability to change peoples bookmarks.

**Comment by avivmu** [comment]
It's truncated in the filtering window: 
![image](https://user-images.githubusercontent.com/19804341/104327561-96e04b80-54f3-11eb-9394-f59c4d949df1.png)
, but I saw the [labels url](https://github.com/zaproxy/zaproxy/labels) and there it's ok.
I'll close the issue for now.
