### ISSUE TITLE
zap fuzzed urls not in left Sites tree

### ISSUE THREAD

**Issue by T35R6braPwgDJKq** [zaproxy/zaproxy#6398]
i would have asked in a google group, but dont have a google account, nor a mobile phone that im willing to give to google (please consider a mailing list like every other piece of software...) - frankly github account creation is a pita as well...

I have sites found via dirb that shall be accessible in zap.
therefore I exported the paths found by dirb and used the fuzzer.
Is there a way to get them into the Sites tab?

What is the best practice for that?
It seems to be a common problem (spider doesnt find everything, dirb widens the surface, now the surface shall be covered by active scan rules). doesnt it?

**Comment by kingthorin** [comment]
Unless something has changed recently you can join the Groups with any email address. 

- You can use a fuzz processor to add message to the Sites Tree, such as: https://github.com/zaproxy/community-scripts/blob/master/httpfuzzerprocessor/add_msgs_sites_tree.js
- If you just have a list of URLs you can import them: https://www.zaproxy.org/docs/desktop/addons/import-urls/
- You could use ZAP's internal dirbuster functionality (Forced Browse): https://www.zaproxy.org/docs/desktop/addons/forced-browse/

**Comment by T35R6braPwgDJKq** [comment]
thanks for your quick response. That probably solves all my problems.

**Comment by T35R6braPwgDJKq** [comment]
> Unless something has changed recently you can join the Groups with any email address.

at least I could not figure out how. Here it's stated that you need a gmail address (which needs a telephone)
https://support.google.com/groups/answer/1067205?rd=1

**Comment by thc202** [comment]
You can always reach us in IRC, does not require an email address at all.
https://www.zaproxy.org/community/
