### ISSUE TITLE
Dead links in the wiki/Examples of zap-extensions

### ISSUE THREAD

**Issue by CravateRouge** [zaproxy/zaproxy#6400]
**Describe the bug**
In the wiki/Examples page of zap-extensions, there are three dead links:

> Active scanners:
> 
>     Simple scanner -> The actual filename is now ExampleSimpleActiveScanRule.java instead of ExampleSimpleActiveScanner.java
> 
> Passive Scanners:
> 
>     Simple scanner -> The actual filename is now ExampleSimplePassiveScanRule.java
>     File based rules scanner -> The actual filename is now ExampleFilePassiveScanRule.java

**Comment by psiinon** [comment]
Thanks! I'll look at that right now...

**Comment by psiinon** [comment]
Done :)
