### ISSUE TITLE
zest authentication script for SAML

### ISSUE THREAD

**Issue by rami013** [zaproxy/zaproxy#6403]
I have been trying to automate ZAP to test an application, which uses SAML authentication. I have tracked the issue in zest where some captured values from the previous Response need to be sent in the subsequent Request body. This is done using zest {{var_name}} notation, but the value is sent without URL encoded. For example, if the value contains "+" (plus sign), it is sent as plus without URL encoding it. I am already setting in the header of the same request "Content-Type: application/x-www-form-urlencoded", however, it does not make any difference. I am looking at the sent data in "Zest Results" tab of ZAP. ZAP version is 2.10.0, and zest version is 33.0.0.

If you can help with URL encoding issue when sending a variable in zest, or redirect me to an existing script to handle SAML authentication in ZAP, that would be great.

**Comment by thc202** [comment]
The following thread in Zest group explains how to achieve that: https://groups.google.com/g/zaproxy-zest/c/Eqsbwj6xN4w

**Comment by rami013** [comment]
Thanks a lot. Now, I managed to get a valid session cookie. However, in the subsequent GET, zest/zap attaches the valid session cookie with an ending of "; {{}}=". That is, in the request, the following header is sent:

Cookie: <cookie_name>=<valid cookie value>; {{}}=

Application is now returning 401 Unauthorized with following details:

"type":"Validation Exception","message":"Not a valid cookie","errorId":"0x000201005"

It may be something to do with the validation process in the application, but I was wondering if there is anything I can do to remove the proceeding value, i.e. "; {{}}=", after the valid Cookie zap/zest is sending.

Thanks in advance.

**Comment by thc202** [comment]
Could you share the contents of the request as defined in the Zest script?

**Comment by rami013** [comment]
Finally I figured out that it was something to do with the application. This can be closed. Thanks.

**Comment by psiinon** [comment]
Thanks for letting us know.
