### ISSUE TITLE
Application Error Disclosure not detected

### ISSUE THREAD

**Issue by omerlh** [zaproxy/zaproxy#6412]
**Describe the bug**
We are using express with body parser. When the parser failed to parse the JSON, it returns error message that disclose too much information, and it is not detected by the relevant rule (90022).

**To Reproduce**
Here is a (redacted) error response:
```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>SyntaxError: Unexpected token <br> in JSON at position 98<br> &nbsp; 
...
</pre>
</body>
</html>
```

**Expected behavior**
An alert created for error disclosure

**Software versions**
 - ZAP: 2.9

 - OS: Mac

**Comment by kingthorin** [comment]
I'll be adding a payload for this, however, note the Application Errors passive scan rule has had custom payloads support for quite a while: https://www.zaproxy.org/docs/desktop/addons/passive-scan-rules/#application-errors

**Comment by kingthorin** [comment]
Note: You'll need to upgrade to ZAP 2.10.0 to get the latest add-on fixes (both this and the previous Suspicious Comments one).
