### ISSUE TITLE
Allow multiple request resends and fuzzing

### ISSUE THREAD

**Issue by Parveshdhull** [zaproxy/zaproxy#6416]
I am new to owasp zap. And having hard time to send multiple requests to resend. It only opens one request and if I send again, it replaces original.
It will be a nice feature if resend tabs can be pinned and persisted in session for further use. 

And same problem occurs with fuzzer. fuzzer even doesn't allow to use zap at all when fuzzer is opened. It will be awesome if instead of opening new window, it opens in new tab.

**Comment by kingthorin** [comment]
You shoukd grab the Requester addon from the Marketplace (three stacked blocks button in the main toolbar) and see if it fulfills your needs.

![](https://raw.githubusercontent.com/wiki/zaproxy/zap-extensions/images/zap-screenshot-browse-addons.png)

**Comment by Parveshdhull** [comment]
Yes, this is exactly what I was looking for. Although it resets after session closing, but for same session it works awesome. Thanks
