### ISSUE TITLE
False Positive: Path Traversal (RESTful API)

### ISSUE THREAD

**Issue by antengj** [zaproxy/zaproxy#6420]
Hi, 
When I use ZAP scan the restful api, there's a alert when param value same as part of url.
Is it a false positive?

![1.png](https://i.loli.net/2021/01/26/L6EPu1BiU2xAgwf.png)

**Comment by antengj** [comment]
`curl -i -s -k -X  'POST'  \
-H '' --data-binary $'{\"name\":\"applications\",\"type\":1,\"user_pool_id\":\"1349525004286562304\"}' \
'https://xxxx/api/v1/applications'`

**Comment by psiinon** [comment]
Please dont ask questions as issues.
The User Group is a much better place for them: https://groups.google.com/group/zaproxy-users
