### ISSUE TITLE
Connection leak with active ZAP sse add-on

### ISSUE THREAD

**Issue by bpapez** [zaproxy/zaproxy#6424]
**Describe the bug**
We use ZAP as passive scanner in our automated tests with Selenium. Our webapp makes use of server-sent events so we have also installed the ZAP sse add-on. However we found that in our bigger Selenium test suites there was a huge performance decrease. 
Each test opens a fresh browser instance from our Selenium grid (there are max. 6 parallel browser containers in Docker). The browser requests go via ZAP and an Apache2 reverse proxy to the backend server. We found that whenever we have the sse add-on installed the connection pool (max 300 connections) of our Apache2 reverse proxy is soon getting filled with many unclosed connections (see screenshot). We do not have that problem when the sse add-on is not installed.
The reverse proxy seem to correctly detect that a browser instance has disappeared, so the connection is closed and returned to the pool. But with the active sse add-on this does not happen.

**To Reproduce**
WIth our bigger test suites having more than hundred tests we can always reproduce the problem as each test is at least opening 3 sse connections.

**Expected behavior**
We expect that adding the sse add-on in our ZAP instance is not causing the SSE connections to not get closed when the client browser disappears.  

**Screenshots**
Here is a screenshot of the Apache2 status with 2 requests (there are hundreds similar ones in the rest of the file)
![image](https://user-images.githubusercontent.com/753358/106147932-bd9bb480-6178-11eb-9d47-4d47a2b86cf1.png)

**Software versions**
 - ZAP: 2.9.0 (official Docker image)
 - Add-on: Server-Sent Events 10.0.0
 - Browser: Chrome 87.0

**Would you like to help fix this issue?**
Yes

**Comment by psiinon** [comment]
Thanks for reporting this - tbh I didnt know if anyone was using this (although obviously I hoped they were) so good to hear that and this is something we should look at asap.
