### ISSUE TITLE
Allow to import burp configuration files

### ISSUE THREAD

**Issue by Mindslave** [zaproxy/zaproxy#6430]
**Is your feature request related to a problem? Please describe.**
I would like to be able to import burp-suite configuration files into zap. When testing applications listed on https://hackerone.com/directory/programs a burp configuration file is usually provied that takes care of adding everything to the scope (or context if we are talking zap) that we have permission to test.

**Describe the solution you'd like**
I would lke to have an option "import context from json" or something like that, which allows me to use these files to define the context in zap.

**Describe alternatives you've considered**
I could also imagine a small programm/script that converts these .json files into zap context files. 

Here I add an example configuration file, taking from a public program
```
{
    "target": {
        "scope": {
            "advanced_mode": true,
            "exclude": [],
            "include": [
                {
                    "enabled": true,
                    "file": "^/.*",
                    "host": "^larksuite\\.com$",
                    "port": "^80$",
                    "protocol": "http"
                },
                {
                    "enabled": true,
                    "file": "^/.*",
                    "host": "^larksuite\\.com$",
                    "port": "^443$",
                    "protocol": "https"
                },
                .........
            ]
        }
    }
}
```

**Would you like to help implementing this feature?**
Yes I would like to help if I can, I have never worked on zap before though and I am not familiar with java, thus some guidance would be required.

**Comment by psiinon** [comment]
Hiya @Mindslave  - sounds like a very useful feature and we'd be very happy to help you with any guidance you need :)
You actually have 2 options - you could implement this using a script which runs in ZAP or as a ZAP add-on.

In this case the format looks quite simple and so a script might be ideal - that could still add things like a menu item to the ZAP menus or any other graphical elements needed.
We have a load of example scripts here: https://github.com/zaproxy/community-scripts

If you'd rather create a ZAP add-on then thats fine too. The first step would be to set up a ZAP dev env: https://www.zaproxy.org/docs/developer/
Just let us know how you'd like to proceed and we can help you from there.

**Comment by Mindslave** [comment]
Thank you for the quick reply,

I think I favor the script way.
I will look into the examples you provided and see what I can get done. It's probably gonna take a few days before I can get to it. 
If you have any other good resources that might be helpful, please let me know.

**Comment by psiinon** [comment]
The community scripts repo has the best set of examples, but also have a look at the videos it links to.
And iy you have any other questions then just ask them here :)

**Comment by Mindslave** [comment]
Hey, 

I'm currently a bit lost on how to access the context inside a (python) script, I'm probably missing some import.

What I have so far is a Standalone-Script that opens a file-dialog to choose the json file, and then I extract all the regexes from that. That's all working well so far. But I don't know how to interact with the context and I couldn't find any good example for that. 

Basically I want to create a function `import_context(contextname, list_of_regexes)` that loops through the list and adds every pattern to the context.

This is what I have so far

```
from javax.swing import JFrame;
from javax.swing import JFileChooser;
import json

def get_file_name():
	frame = JFrame("Filename")
	frame.setLocation(100,100)
	frame.setSize(500,400)
	frame.setLayout(None)
	fc = JFileChooser()
	result = fc.showOpenDialog(frame)
	if not result == JFileChooser.APPROVE_OPTION:
		return None
	file_name = fc.getSelectedFile()
	return file_name

def get_url_regexes(file_name):
	with open(file_name, "r") as f:
		data = json.load(f)
	includes = data['target']['scope']['include']
	regexes = []
	for include in includes:
		regexes.append(include['host'])
	return regexes

def import_context():
	pass


file_name = get_file_name()
print("The filename is: ", file_name)
if file_name is None:
	pass
	#fail somehow?
url_regexes = get_url_regexes(str(file_name))
print(url_regexes)
#import_context(url_regexes)
```

**Comment by thc202** [comment]
Call `Session#getNewContext(String)` to create a new context then [add the URLs](https://javadoc.io/static/org.zaproxy/zap/2.10.0/org/zaproxy/zap/model/Context.html). The [Session](https://javadoc.io/static/org.zaproxy/zap/2.10.0/org/parosproxy/paros/model/Session.html) can be obtained through the [Model's singleton](https://javadoc.io/static/org.zaproxy/zap/2.10.0/org/parosproxy/paros/model/Model.html).

**Comment by Mindslave** [comment]
Hello everyone, since the script has been merged to be part of the community scripts, I think we can close this issue, do you agree?

**Comment by thc202** [comment]
Closing, included in Community Scripts add-on.
