### ISSUE TITLE
Firefox headless mode crashing

### ISSUE THREAD

**Issue by valentinmne** [zaproxy/zaproxy#6431]
I was trying to run ZAP with docker but I had an error on firefox and can't figure it out

DOCKER_VERSION = Docker version 20.10.2, build 2291f61
OS_VERSION = Centos 7
KERNEL_VERSION =  3.10.0-1127.10.1.el7.x86_64

Docker command used ``` docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-weekly zap-full-scan.py -t http://www.sgti4.fr -r testreport.html```

Error log :

 1612175771286   geckodriver     INFO    Listening on 127.0.0.1:10033
1612175771250   geckodriver     INFO    Listening on 127.0.0.1:14329
1612175771428   mozrunner::runner       INFO    Running command: "/usr/lib/firefox/firefox" "--marionette" "-headless" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofileRyAWdt"
1612175771440   mozrunner::runner       INFO    Running command: "/usr/lib/firefox/firefox" "--marionette" "-headless" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile8riCMS"
*** You are running in headless mode.
*** You are running in headless mode.

(firefox:311): GLib-GObject-WARNING **: 10:36:12.185: invalid (NULL) pointer instance

(firefox:311): GLib-GObject-CRITICAL **: 10:36:12.185: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(firefox:309): GLib-GObject-WARNING **: 10:36:12.185: invalid (NULL) pointer instance

(firefox:309): GLib-GObject-CRITICAL **: 10:36:12.185: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(/usr/lib/firefox/firefox:528): GLib-GObject-WARNING **: 10:36:13.284: invalid (NULL) pointer instance

(/usr/lib/firefox/firefox:528): GLib-GObject-CRITICAL **: 10:36:13.284: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(/usr/lib/firefox/firefox:909): GLib-GObject-WARNING **: 10:36:13.429: invalid (NULL) pointer instance

(/usr/lib/firefox/firefox:909): GLib-GObject-CRITICAL **: 10:36:13.429: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(/usr/lib/firefox/firefox:1008): GLib-GObject-WARNING **: 10:36:13.632: invalid (NULL) pointer instance

(/usr/lib/firefox/firefox:1008): GLib-GObject-CRITICAL **: 10:36:13.632: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(/usr/lib/firefox/firefox:1014): GLib-GObject-WARNING **: 10:36:13.647: invalid (NULL) pointer instance

(/usr/lib/firefox/firefox:1014): GLib-GObject-CRITICAL **: 10:36:13.647: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
console.warn: SearchSettings: "get: No settings file exists, new profile?" (new Error("", "(unknown module)"))
console.warn: SearchSettings: "get: No settings file exists, new profile?" (new Error("", "(unknown module)"))
console.error: Region.jsm: "Error fetching region" (new TypeError("NetworkError when attempting to fetch resource.", ""))
console.error: Region.jsm: "Failed to fetch region" (new Error("NO_RESULT", "resource://gre/modules/Region.jsm", 376))
console.error: Region.jsm: "Error fetching region" (new TypeError("NetworkError when attempting to fetch resource.", ""))
console.error: Region.jsm: "Failed to fetch region" (new Error("NO_RESULT", "resource://gre/modules/Region.jsm", 376))

(/usr/lib/firefox/firefox:1193): GLib-GObject-WARNING **: 10:36:15.491: invalid (NULL) pointer instance

(/usr/lib/firefox/firefox:1193): GLib-GObject-CRITICAL **: 10:36:15.491: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(/usr/lib/firefox/firefox:1291): GLib-GObject-WARNING **: 10:36:15.840: invalid (NULL) pointer instance

(/usr/lib/firefox/firefox:1291): GLib-GObject-CRITICAL **: 10:36:15.840: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
1612175775852   Marionette      INFO    Listening on port 40927

(/usr/lib/firefox/firefox:1300): GLib-GObject-WARNING **: 10:36:15.884: invalid (NULL) pointer instance

(/usr/lib/firefox/firefox:1300): GLib-GObject-CRITICAL **: 10:36:15.884: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
1612175776014   Marionette      WARN    TLS certificate errors will be ignored for this session
1612175776080   Marionette      INFO    Listening on port 35408
Feb 01, 2021 10:36:16 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
1612175776159   Marionette      WARN    TLS certificate errors will be ignored for this session
Feb 01, 2021 10:36:16 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C

**Comment by thc202** [comment]
That's "normal" output when running Firefox (e.g. https://github.com/mozilla/geckodriver/issues/347#issuecomment-261186848).
