### ISSUE TITLE
Any plans to push images to AWS public ECR ?

### ISSUE THREAD

**Issue by kiwimato** [zaproxy/zaproxy#6433]
**Is your feature request related to a problem? Please describe.**
I love Zaproxy and plan to use it in our CI/CD process, however with the recent Dockerhub rate limiting makes it harder.
Recently a lot of software like Terraform, etc started also pushing their docker images to https://gallery.ecr.aws/
This will fix the issue where pulling from Dockerhub in CI/CD process is rate limited after X number of pulls. AWS does not have any limits on pulls.

**Describe the solution you'd like**
Also push the official Docker images to gallery.ecr.aws

**Describe alternatives you've considered**
An alternative would be that I create my own ECR repo and push it there, but I would love to see this as an official image, since that way it will also help other people.

**Would you like to help implementing this feature?**
Sure, definitely! I'd love to help in my free time.

**Comment by psiinon** [comment]
Thanks for that suggestion - we'll definitely look into it!

**Comment by thc202** [comment]
Closing, the Docker images are being published to GHCR which does not have the pull rates. More details in the blog post: https://www.zaproxy.org/blog/2023-06-13-ghcr-docker-images/
