### ISSUE TITLE
Unable to reload plugin

### ISSUE THREAD

**Issue by h3xstream** [zaproxy/zaproxy#6435]
**Describe the bug**

It is not possible to reload a plugin.
ZAP also has issue with uninstalling plugin. The clean up is often incomplete. The .zip file will remain 

**To Reproduce**

Steps to reload a plugin:
1. Open "Plugin Manager"
2. Uninstall Plugin X
3. File > Load AddOn File
4. Select Plugin X

A popup will prompt saying the plugin could not be loaded.

**Expected behavior**

Plugin should be reloadable without the requirement to close the application.

**Screenshots**

The following capture show that the limitation:

![2021-02-02 13_38_08-OWASP ZAP](https://user-images.githubusercontent.com/593130/106647493-024e9380-655d-11eb-8245-a72827d2db22.png)

![2021-02-02 13_25_24-OWASP ZAP](https://user-images.githubusercontent.com/593130/106647856-78eb9100-655d-11eb-9b17-b3c394712f4b.png)

**Software versions**
OWASP ZAP
Version: 2.10.0

**Comment by thc202** [comment]
Closing, does not seem to be a ZAP issue.
