### ISSUE TITLE
Cannot use zap/JSON/ to load script using API

### ISSUE THREAD

**Issue by Homopatrol** [zaproxy/zaproxy#6439]
**Describe the bug**

When trying to load a script into to ZAP in order to run a JSON scan according to the tutorial - [https://www.zaproxy.org/docs/api/#json-based-authentication](url) the default url **http://zap/JSON/script/action/load** is used to call the API however this causes the script to fail but when I change the url to the UI the code is successfully loaded?

**To Reproduce**

My issue regards this section of code to load the script to ZAP :
```
    script_name = 'jwtScript.js'
    script_type = 'httpsender'
    script_engine = 'Oracle Nashorn'
    file_name = '/tmp/jwtScript.js'
    zap.script.load(script_name, script_type, script_engine, file_name)
```

When I run `zap.script.load()` in my pipeline I receive the error: 

```
File "/usr/local/lib/python3.9/site-packages/zapv2/script.py", line 122, in load
return six.next(six.itervalues(self.zap._request(self.zap.base + 'script/action/load/', params)))
```

```
File "/usr/local/lib/python3.9/site-packages/zapv2/__init__.py", line 175, in _request_api
raise Exception("Non-successful status code returned from ZAP, which indicates a bad request: "
Exception: Non-successful status code returned from ZAP, which indicates a bad request: 400response: {"code":"does_not_exist","message":"Does Not Exist"}
```
When debugging I can see the code is correctly calling **http://zap/JSON/script/action/load** however I cannot understand why this is failing in the pipeline?

I went to the UI **https://<our_domain>/UI/script/action/load/**

<img width="1625" alt="Screenshot 2021-02-04 at 16 11 18" src="https://user-images.githubusercontent.com/58219367/106921237-bb4ed280-6703-11eb-92b3-c87f13037849.png">

Filled out the form with the same parameters which also returned "does_not_exist" in regards to the file name despite me putting the absolute path in. 

Alternatively, I have used the script here  [https://www.zaproxy.org/docs/api/#scriptactionload](url) instead 
Which again suggests I use JSON - **'http://zap/JSON/script/action/load/'** also returns the same error…

However, when I change this to use the UI :
```
import requests
headers = {
  'Accept': 'application/json',
  'X-ZAP-API-Key': 'API_KEY'
}

r = requests.get('https://<our_domain> /UI/script/action/load/', params={
  'scriptName': 'string',  'scriptType': 'string',  'scriptEngine': 'string',  'fileName': 'string'
}, headers = headers)

print(r)
```
this returns 200 and appears to work?

I have traversed through the references between both the UI and JSON and have come up with this diagram..

<img width="1219" alt="Screenshot 2021-02-04 at 16 16 41" src="https://user-images.githubusercontent.com/58219367/106921989-77100200-6704-11eb-81d1-3b4e57cadd4d.png">

My question is what is the difference between the JSON and UI urls? And is there something I’m missing in loading my script that might be causing this to fail.

**Expected behavior**
I expected `zap.script.load()` to successfully run and return 200 using the default URL of **'http://zap/JSON/script/action/load/'**

**Software versions**
 - ZAP: v2.9.0 - Deployed on Openshift Container Platform 4.5
 - Add-on: using API version python-owasp-zap-v2.4 0.0.18
 - OS: [Mac OS X 10.15]
 - Java: N/A
 - Browser: [Firefox/84.0]

**Errors from the zap.log file**
```
168634187 [ZAP-ProxyThread-5549] WARN org.zaproxy.zap.extension.api.API  - Bad request to API endpoint [/JSON/script/action/load/] from [127.0.0.1]:
Does Not Exist (does_not_exist) : /Users/homopatrol/Downloads/zap/maintain-jwt.js
        at org.zaproxy.zap.extension.script.ScriptAPI.handleApiAction(ScriptAPI.java:319)
        at org.zaproxy.zap.extension.api.API.handleApiRequest(API.java:506)
        at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(ProxyThread.java:499)
        at org.parosproxy.paros.core.proxy.ProxyThread.run(ProxyThread.java:335)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by thc202** [comment]
Based on the error message in the log It seems the specified script path not correct.

**Comment by Homopatrol** [comment]
@thc202  I have checked the script exists in the current path and set it to be the full path, shoud this be refered to differently? - for example just to the directory the script is in?

**Comment by namloc2001** [comment]
I was working on this with @Homopatrol can can categorically confirm the file is at that location and is named as shown. When using the script:
```
r = requests.get('https://<our_domain>/UI/script/action/load/', params={
'scriptName': 'string', 'scriptType': 'string', 'scriptEngine': 'string', 'fileName': 'string'
}, headers = headers)
```

It would find this file, so something else is happening when using `JSON` in the URL path.

**Comment by kingthorin** [comment]
Permissions issue?

**Comment by Homopatrol** [comment]
@kingthorin this is a `ls -la` on the script i'm trying to upload:

`-rw-r--r--@ 1 homopatrol  staff  2500  4 Feb 11:02 maintain-jwt.js `

**Comment by psiinon** [comment]
If you are running ZAP in docker (e.g. using the packaged API scan) then you need to make sure that the script is visible from within docker.
Are you using the full path to the script outside of docker or inside?

**Comment by thc202** [comment]
Calling `/UI/script/action/load/` would return the API UI not actually call the load endpoint.

**Comment by Homopatrol** [comment]
@psiinon i have copied the script in my dockerfile - 
`COPY --chown=${UID}:0 aws-devsecops-workshop/pipeline/scripts/maintain-jwt.js /zap/maintain-jwt.js`

so my parameters in my script are :
`script_name = 'maintain-jwt.js' `
`script_type = 'httpsender'`
`script_engine = 'Oracle Nashorn'`
`file_name = '/zap/maintain-jwt.js'`

but this returns error 400 with **'http://zap/JSON/script/action/load/'** and appears to work with **https://<our_domain> /UI/script/action/load/** which suggests to me the path is correct.

**Comment by thc202** [comment]
Calling the UI endpoint is not evidence that the path is correct, that returns the API UI.

**Comment by Homopatrol** [comment]
@thc202  I understand that but I run into the same `{'code': 'does_not_exist', 'message': 'Does Not Exist'}` when using **http://<our_domain>/JSON/script/action/load/** 

I also used the following to check if the script can be seen and exists (which it does) :
`with os.scandir('/Users/homopatrol/Downloads/zap/') as entries:`
   ` for entry in entries:`
        `print(entry.name)`

**Comment by thc202** [comment]
Did you check that ZAP/Java has permissions to access your home files? (System Preferences > Security & Privacy > Privacy > Files and Folders)

Also, are you getting the same error in OC as in your local machine/mac?

**Comment by Homopatrol** [comment]
This is the location of the script I am trying to upload (this is all on my Mac) 
```
pandora@Pandoras-MacBook-Pro zap % pwd
/Users/pandora/Downloads/zap

pandora@Pandoras-MacBook-Pro zap % ls -la 
-rwxrwxrwx@  1 pandora  staff  2500  5 Feb 09:08 maintain-jwt.js
```
This is the script I am using to initate the upload
```
pandora@Pandoras-MacBook-Pro scripts % pwd
/Users/pandora/Downloads/zap/aws-devsecops-workshop/pipeline/scripts

pandora@Pandoras-MacBook-Pro scripts % ls -la
-rw-r--r--  1 pandora  staff  8197  8 Feb 10:04 pen-test-app.py
```
This is the USER I am running the upload script as 
```
pandora@Pandoras-MacBook-Pro scripts % id
uid=501(pandora), gid=20(staff)
```
I'm then running ZAP in a container on Openshift which is hosted on cloud and I am running port forward on my laptop to ZAP. This is the upload script
```
headers = {
    'Accept': 'application/json',
    'X-ZAP-API-Key': '<api-key>'
}
r = requests.get('http://localhost:8082/JSON/script/action/load/', params={
    'scriptName': 'maintain-jwt.js', 'scriptType': 'httpsender', 'scriptEngine':'Oracle Nashorn',
    'fileName': '/Users/pandora/Downloads/zap/maintain-jwt.js'
}, headers=headers)

print(r.json())
```
and when I run this I get the following response 
```
{'code': 'does_not_exist', 'message': 'Does Not Exist'}
```
And then when I change the code to be `http://localhost:8082/UI/script/action/load/` instead of `http://localhost:8082/JSON/script/action/load/` I then get the following repsonse `<Response [200]>`

**Comment by thc202** [comment]
That endpoint does not upload the script, that path indicates where the script is in the local file system where ZAP is running. You need to upload/copy it to the container before calling that endpoint (and use the local file system path).

**Comment by Homopatrol** [comment]
I have created a file in my persistent ZAP instance on Openshift
```
$ pwd
/zap/scripts/templates/httpsender      

$ ls -la 
total 28
drwxr-xr-x. 1 zap zap 4096 Feb  8 11:35  .
drwxr-xr-x. 1 zap zap 4096 Mar 19  2020  ..
-rw-r--r--. 1 zap zap 1183 Mar 19  2020  AddZapHeader.js
-rw-r--r--. 1 zap zap 1626 Mar 19  2020 'HttpSender default template.js'
-rw-r--r--. 1 zap zap 2473 Feb  8 11:35  maintain-jwt.js
```
Now when I run my `requests.get` script with `http://localhost:8082/JSON/script/action/load/` I recieve the response `{'code': 'already_exists', 'message': 'Already Exists'}`

**Comment by thc202** [comment]
Enable "Report error details via API" and execute again. Maybe the script was already added?
https://www.zaproxy.org/docs/desktop/ui/dialogs/options/api/

**Comment by Homopatrol** [comment]
I believe that link is for the dekstop UI which I am not using, do you know how I could enable this on the web UI or through a script?

**Comment by kingthorin** [comment]
That was just so you had a reference to the option. It'd be another config value like `config.api.incerrordetails`

**Comment by kingthorin** [comment]
Of course you can and should get this all working in desktop first.

**Comment by thc202** [comment]
For more details on how to know the config keys: https://www.zaproxy.org/faq/how-do-you-find-out-what-key-to-use-to-set-a-config-value-on-the-command-line/

**Comment by Homopatrol** [comment]
okay so I changed my scriptname to be from `maintain-jwt.js` to ->`maintain-jwt-2.js` so my code now reads
```
r = requests.get('http://localhost:8082/JSON/script/action/load/', params={
    'scriptName': 'maintain-jwt-2.js', 'scriptType': 'httpsender', 'scriptEngine': 'Oracle Nashorn',
    'fileName': '/zap/scripts/templates/httpsender/maintain-jwt.js'
}, headers=headers)
```
my the original maintain-jwt.js still exists in my ZAP instance
```
$ pwd
/zap/scripts/templates/httpsender      

$ ls -la 
total 28
drwxr-xr-x. 1 zap zap 4096 Feb  8 11:35  .
drwxr-xr-x. 1 zap zap 4096 Mar 19  2020  ..
-rw-r--r--. 1 zap zap 1183 Mar 19  2020  AddZapHeader.js
-rw-r--r--. 1 zap zap 1626 Mar 19  2020 'HttpSender default template.js'
-rw-r--r--. 1 zap zap 2473 Feb  8 11:35  maintain-jwt.js
```
Now when I run my request I get the response `{'Result': 'OK'}`
however when I jump inside my ZAP container and search to see if the script has been I cannot find it.
```
$ cd /
$ find . -name "maintain*" -type f
find: ‘./var/cache/ldconfig’: Permission denied
find: ‘./var/cache/apt/archives/partial’: Permission denied
find: ‘./proc/tty/driver’: Permission denied
find: ‘./proc/1/map_files’: Operation not permitted
find: ‘./proc/19797/map_files’: Operation not permitted
find: ‘./proc/19838/map_files’: Operation not permitted
./usr/share/aclocal-1.15/maintainer.m4
find: ‘./root’: Permission denied
find: ‘./etc/ssl/private’: Permission denied
./zap/scripts/templates/httpsender/maintain-jwt.js

$ ls -la .ZAP/scripts
total 24
drwxr-xr-x.  4 zap zap 4096 Feb  2 11:58 .
drwxr-xr-x.  1 zap zap 4096 Feb  2 11:58 ..
drwxr-xr-x. 15 zap zap 4096 Feb  2 11:58 scripts
drwxr-xr-x. 16 zap zap 4096 Feb  2 11:58 templates

$ ls -la .ZAP/scripts/scripts/httpsender/
total 8
drwxr-xr-x.  2 zap zap 4096 Feb  2 11:58 .
drwxr-xr-x. 15 zap zap 4096 Feb  2 11:58 ..

$ ls -la .ZAP/scripts/templates/
total 68
drwxr-xr-x. 16 zap zap 4096 Feb  2 11:58 .
drwxr-xr-x.  4 zap zap 4096 Feb  2 11:58 ..
drwxr-xr-x.  2 zap zap 4096 Feb  2 11:58 active
drwxr-xr-x.  2 zap zap 4096 Feb  2 11:58 authentication
drwxr-xr-x.  2 zap zap 4096 Feb  2 11:58 extender
drwxr-xr-x.  2 zap zap 4096 Feb  2 11:58 httpfuzzerprocessor
drwxr-xr-x.  2 zap zap 4096 Feb  2 11:58 httpsender
drwxr-xr-x.  2 zap zap 4096 Feb  2 11:58 passive
drwxr-xr-x.  2 zap zap 4096 Feb  2 11:58 payloadgenerator
drwxr-xr-x.  2 zap zap 4096 Feb  2 11:58 payloadprocessor
drwxr-xr-x.  2 zap zap 4096 Feb  2 11:58 proxy
drwxr-xr-x.  2 zap zap 4096 Feb  2 11:58 standalone
drwxr-xr-x.  2 zap zap 4096 Feb  2 11:58 targeted
drwxr-xr-x.  2 zap zap 4096 Feb  2 11:58 websocketfuzzerprocessor
drwxr-xr-x.  2 zap zap 4096 Feb  2 11:58 websocketpassive
drwxr-xr-x.  2 zap zap 4096 Feb  2 11:58 websocketsender

$ ls -la .ZAP/scripts/templates/httpsender/
total 12
drwxr-xr-x.  2 zap zap 4096 Feb  2 11:58  .
drwxr-xr-x. 16 zap zap 4096 Feb  2 11:58  ..
-rw-r--r--.  1 zap zap 1595 Feb  2 11:58 'HttpSender default template.zst'
```
can you explain what is happening? if the script been loaded where will it be stored?

**Comment by thc202** [comment]
ZAP does not copy/move the script, it will read it from the path specified.

**Comment by thc202** [comment]
Closing, everything seems to be working as expected.
