### ISSUE TITLE
WSDL file check raises an alert on all text/xml content

### ISSUE THREAD

**Issue by Stanislava27** [zaproxy/zaproxy#6440]
**Describe the bug**
I have been testing some test endpoints, where an xml file is returned. These tests get alert "A WSDL File has been detected.". I have been looking through the source code and found that Content-Type ".wsdl", "text/xml" or "application/wsdl+xml will trigger an alert (\zap\extension\soap\WSDLFilePassiveScanRule.java line 60-62). Some of the WSDL files will probably use text/xml, but not all. 

**To Reproduce**
1. Use a test endpoint, that returns xml and a header 'text/xml', like:
```xml
HTTP/1.1 200 OK
Content-Type: text/xml
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
Content-Security-Policy: default-src 'self'; frame-ancestors 'none'; form-action 'none'
Cache-Control: no-store

<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
</urlset> 
```
2. Run passive scan against it
3. Find a high severity alert named 'WSDL File Detection' in the HTML report

**Expected behavior**
XML content should not raise 'WSDL File Detection' alert

**Screenshots**
![image](https://user-images.githubusercontent.com/55736625/107028885-759b1400-67ae-11eb-87a1-5837028df47b.png)

**Software versions**
 - ZAP: [2.10.0]
 - Add-on: Name and version [Passive rules, SOAP Supporthttps://www.zaproxy.org/docs/desktop/addons/soap-support/]
 - OS: [Windows 10]
 - Java: [java version "1.8.0_281"]
 - Browser: [Edge used to read the reports]

**Errors from the zap.log file**
See https://www.zaproxy.org/faq/what-is-the-default-directory-that-zap-uses/ for the location of the zap.log file for your OS.

**Additional context**
The check can be found in script \addOns\soap\src\main\java\org\zaproxy\zap\extension\soap\WSDLFilePassiveScanRule.java line 60-62, where all the text/xml content will trigger an alert
![image](https://user-images.githubusercontent.com/55736625/107029209-f5c17980-67ae-11eb-9693-e5e2173f556b.png)

**Would you like to help fix this issue?**
Not this time, sorry

**Comment by psiinon** [comment]
Relevant file is https://github.com/zaproxy/zap-extensions/blob/master/addOns/soap/src/main/java/org/zaproxy/zap/extension/soap/WSDLFilePassiveScanRule.java

Anyone fance having a go at this?

**Comment by kingthorin** [comment]
Should be as simple as:
```diff
- return baseURL.endsWith(".wsdl")
-                    || contentType.equals("text/xml")
-                    || contentType.equals("application/wsdl+xml");
+ return (baseURL.endsWith(".wsdl")
+                    && contentType.equals("text/xml"))
+                    || contentType.equals("application/wsdl+xml");
```
