### ISSUE TITLE
[Feature request] allow the user to modify the request in fuzzer tab

### ISSUE THREAD

**Issue by knassar702** [zaproxy/zaproxy#6442]
hi team

You can allow the user to modify the request in fuzzer tab .?
![zapfuz](https://user-images.githubusercontent.com/45688522/107096374-4ff42600-6813-11eb-8111-b1ba0e49d26b.png)

Currently this can be done, but the user must send a request with the modification by using `requester` and then send it to fuzzer

sometimes we need that without send the request ,for testing race condition or something like that

regards
@knassar702

**Comment by thc202** [comment]
Closing as duplicate of #2315.
