### ISSUE TITLE
Cache Control passive scanner raises alerts even when "no-store" is present

### ISSUE THREAD

**Issue by acut3** [zaproxy/zaproxy#6446]
**Describe the bug**

An *"Incomplete or No Cache-control and Pragma HTTP Header Set"* alert is raised when a response has a `Cache-Control` header that contains `no-store`, but is missing either `no-cache` or `must-revalidate`.

This is incorrect, since `no-store` by itself is enough to ensure that the response won't be cached.

**To Reproduce**

1. Go to https://acut3.xyz/zap-hsq6cdm9wzyk/no-store.php
2. See how an alert is raised for "Incomplete or No Cache-control and Pragma HTTP Header Set"

**Expected behavior**

No error should be raised since a `Cache-Control: no-store` header is present in the response.

**Software versions**
 - ZAP: 2.10.0
 - Add-on: Passive scanner rules Release 33.0.0
 - OS: Linux
 - Java: openjdk 15.0.2
 - Browser: chromium 88.0.4324.150

**Would you like to help fix this issue?**

The logic in [CacheControlScanRule.java](https://github.com/zaproxy/zap-extensions/blob/3f73c8eead905d5d4e390f521505ad4865f9be7b/addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CacheControlScanRule.java#L77-L79) is incorrect:

```java
            if (cacheControlHeaders.isEmpty()
                    || // No Cache-Control header at all
                    cacheControlHeaders.indexOf("no-store") < 0
                    || cacheControlHeaders.indexOf("no-cache") < 0
                    || cacheControlHeaders.indexOf("must-revalidate") < 0) {
                this.raiseAlert(msg, id, HttpHeader.CACHE_CONTROL, cacheControlHeaders);
            }
```

This says that an alert should be raised if any of the `no-store`, `no-cache` or `must-revalidate` value is missing. I'm not sure what the intent was but I suspect it should be to raise an alert if none of them are present (i.e. those last two `||` should be `&&`).

**Comment by kingthorin** [comment]
I believe if you read the solution associated with the alert it suggests that all three directives should be used.

**Comment by kingthorin** [comment]
Confirmed the solution suggests all three, therefore if any are missing it will alert . The ‘or’ logic is correct, for the intended behaviour.

https://github.com/zaproxy/zap-extensions/blob/3f73c8eead905d5d4e390f521505ad4865f9be7b/addOns/pscanrules/src/main/resources/org/zaproxy/zap/extension/pscanrules/resources/Messages.properties#L158

**Comment by acut3** [comment]
But is the intended behavior correct? My understanding is that just setting `no-store` is enough. Many websites do just that, and the current rule results in many false positives.

**Comment by kingthorin** [comment]
I guess that might be up for debate. When the rule was created (years ago) the three directives were the defacto "industry standard".

According to current MDN docs, no other directives apply when `no-store` is present.

I believe we are willing to revise the scan rule if we can grow some consensus here.

We should probably (definitely IMHO) be dropping references to `pragma`, as outlined here: https://twitter.com/veggiespam/status/1359353014289649669 and elsewhere.

The other option we could pursue is to drop that scan rule all together as has been suggested in the past, and have people depend on:
- https://github.com/zaproxy/zap-extensions/blob/a0147f248dc359d2cc871ce09e0f98ab63f682f4/addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/RetrievedFromCacheScanRule.java
- https://github.com/zaproxy/zap-extensions/blob/d890679f6cea14cbdd1c60c2d9fb6543a671394c/addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/CacheableScanRule.java

The later of which I believe only raises informational findings and leaves it up to the analyst to determine impact, which isn't terribly practical for automated uses (there is no analyst). Also I don't know if either of those rules are up-to-date with RFCs and current cache/proxy behavior.

@psiinon @thc202 thoughts?

**Comment by acut3** [comment]
The RetrievedFromCacheScanRule passive rule mentioned above serves a different purpose and I don't think it can or should replace CacheControlScanRule, for two reasons:

1. RetrievedFromCacheScanRule works based on headers set by the cache. Those headers are informational only and there are no guaranties a cached response will contain any of them, or even that their value will be set correctly. CacheControlScanRule fills that gap by identifying the responses that *can* be cached (or stored).
2. RetrievedFromCacheScanRule will not help identify responses that can be cached client-side (by the browser). This is actually the main reason I use CacheControlScanRule, because in some cases responses that are cached by the browser can be used to read authenticated responses in a GET CSRF (see https://enumerated.wordpress.com/2019/12/24/sop-bypass-via-browser-cache/).

It looks like CacheableScanRule would do a good job at identifying what can be cached/stored, but as noted it's probably too verbose to be practical.

**Comment by kingthorin** [comment]
Okay that's a fair summary.

So that just leaves the question of whether or not we should adjust the guidance/solution that CacheControlScanRule is looking for?

**Comment by shehackspurple** [comment]
Hi, I'm hope I'm being helpful interjecting here. Is no-store enough even for older browsers? or just modern ones? Sometimes we want more than one defense/option, because we're worried about older browsers. I read all the links, but couldn't really see anything about backwards compatibility. (not reallllllly old browsers like I.E. 6, but not everyone is running latest chrome/firefox on the internet, can it protect those people?).

**Comment by psiinon** [comment]
@acut3 Whats your proposal now? Is it the same as your first comment?
Has anyone found any links which recommend for or against how the rule currently works or how its proposed to work?

**Comment by kingthorin** [comment]
@psiinon the English page on MDN says "no-store" is sufficient but the German (and likely other) page(s) still say the 3 the scan rule looks for "no-store, no-cache, must-revalidate".

**Comment by kingthorin** [comment]
I noticed last night while I was surfing that @april posted a blog about this last Sept. https://grayduck.mn/2021/09/13/cache-control-recommendations/ which is fairly up-to-date. 

> **Don't cache (default)**: `max-age=0, must-revalidate, no-cache, no-store, private`

>> When you're unsure, the above is the safest possible directive for Cache-Control. It instructs browsers, proxies, and other caching systems to not cache the contents of the request. Although it can have significant performance impacts if used on frequently-accessed public resources, it is a safe state that prevents the caching of any information.

>> It may seem that using `no-store` alone should stop all caching, but it only prevents the caching of data to permanent storage. Many browsers will still allow the caching of these resources to memory, even if it doesn't write them to disk. This can cause issues where shared systems may contain sensitive information, such as browsers maintaining cached documents for logged out users.

>> Although `no-store` may seem sufficient to instruct content delivery networks (CDNs) to not cache private data, [many CDNs ignore these directives to varying degrees](https://docs.fastly.com/en/guides/how-caching-and-cdns-work#cache-control). Adding `private` in combination with the above directives is sufficient to disable caching both for CDNs and other middleboxes.

Which seems to align with our current guidance. I guess I could try to email her and ask about the MDN language/locale discrepancy, but I'm not sure that's necessary.

Shall I add her blog as a reference?

**Comment by psiinon** [comment]
+1 for adding her blog and reducing confidence to `Low`
