### ISSUE TITLE
Manual Request Editor: Send Hotkey

### ISSUE THREAD

**Issue by ippsec-htb** [zaproxy/zaproxy#6448]
**Is your feature request related to a problem? Please describe.**
I am currently considering switching from BurpSuite to ZAP, the main thing that is preventing the switch is the lack of a Hotkey to send the request in "Manual Request Editor".  A large portion of my time is spent manually editing API Endpoints, SQL Injection, SSTI Payloads, etc, and being able to work purely on the keyboard is a huge quality of life improvement, especially when on a laptop.

**Would you like to help implementing this feature?**
You probably don't want me writing java code - but if there is some type of documentation on how the ZAP Hotkey system works, I'd be happy to take a swing at it.

**Comment by kingthorin** [comment]
Do you have a request for the default combo?

**Comment by ippsec-htb** [comment]
Alt+Enter or Alt+. would be great.

**Comment by psiinon** [comment]
Is this to launch the Manual Request Editor or to send the request from it?
You can already launch it via the <ctrl> M key but I dont think it will pick up a specific request.

**Comment by ippsec-htb** [comment]
This is to send a request from within the Manual Request Editor.

**Comment by psiinon** [comment]
Ah ha! In that case I definitely agree - we should have this as std on all relevant dialogs...

**Comment by kingthorin** [comment]
This will be available in next week's weekly build.

**Comment by zersiax** [comment]
Adding this for the " Add"  button in the fuzzer dialog would be similarly useful, however there are multiple flows for that dialog (e.g. there's also a remove button). I was going to go ahead and add it there, same as https://github.com/zaproxy/zaproxy/pull/6452 but for the fuzzer's add. Is  that alright or is someone else already doing this in a more global sense?

**Comment by kingthorin** [comment]
Go for it!

No one else has spoken up about working on it globally.

The fuzzer code us over here: https://github.com/zaproxy/zap-extensions/tree/master/addOns/fuzz

**Comment by zersiax** [comment]
thanks for the code pointer :) Will go have a look.

**Comment by thc202** [comment]
Please implement it as mentioned in https://github.com/zaproxy/zaproxy/pull/6452#issuecomment-779755807
