### ISSUE TITLE
Unable to import openAPI using file system

### ISSUE THREAD

**Issue by tulasik2992** [zaproxy/zaproxy#6450]
I am trying to import .yaml file using Import -- > Import using open API from local file system but getting error of 'failed to access specified definition'

**To Reproduce**
1. Go to Import.
2. Click on Import open API from local file system.
3. Import .json specified at https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v2.0/json/petstore-expanded.json(Got this from one of the issues from 2018)
4. failed to access specified definition' error is coming.

One of our APIs has .yaml file and I am successfully able to import it to postman and the same is failed to be imported in ZAP.I am using ZAP 2.10

**Expected behavior**
Successfully import the definition and help me do my work on attack.

![Screenshot 2021-02-11 at 3 26 19 PM](https://user-images.githubusercontent.com/78904580/107622364-bf3ba100-6c7d-11eb-982b-517a6416cbb3.png)

**Software versions**
 - ZAP: 2.10.0
 - OS: MAC catalina
 - Java: 1.8.0_181

**Comment by thc202** [comment]
Most likely ZAP has no permissions to access the file. Make sure that under System Preferences > Security & Privacy > Privacy > Files and Folders, ZAP/Java is allowed to access that location.

**Comment by tulasik2992** [comment]
As you said, i tried to change the settings but I don't see any such options available for ZAP. for that reason I went to remote windows desktop and tried importing. It worked. 
If its a permission issue, can you please help me with other use case where i am trying to import using the url.
I get below error when i tried :
![7822D658-B830-47B4-A0F5-41696B3F7B3E_1_105_c](https://user-images.githubusercontent.com/78904580/107730667-ff506180-6d19-11eb-8f6e-d61e72e3a45c.jpeg)

**Comment by kingthorin** [comment]
Did you check the output tab as tue dialog suggests?

**Comment by thc202** [comment]
Closing due inactivity, feel free to reopen after providing more details.
