### ISSUE TITLE
Any way to remove the target URL from reports for API scans?

### ISSUE THREAD

**Issue by mihai-cindea** [zaproxy/zaproxy#6451]
**Is your feature request related to a problem? Please describe.**
I have a .NET app which has Swagger. I provide the swagger.json URL to the API scanner, and that URL throws some vulnerabilities. However I cannot control swagger.json url from the .NET app.

**Describe the solution you'd like**
I'd like to be able to exclude the provided target from the reports with `globalexcludeurl` or some other solution.

**Describe alternatives you've considered**
Extra script which removes it after the report is created, but it can be cumbersome.

** Logs **
```
WARN-NEW: Incomplete or No Cache-control and Pragma HTTP Header Set [10015] x 1 
	https://redacted.com/swagger/v1/swagger.json (200 OK)
WARN-NEW: X-Content-Type-Options Header Missing [10021] x 1 
	https://redacted.com/swagger/v1/swagger.json (200 OK)
WARN-NEW: Strict-Transport-Security Header Not Set [10035] x 7 
```

**Would you like to help implementing this feature?**
Sure.

**Comment by psiinon** [comment]
Please dont ask questions as issues - the User Goup is a much better place for them: https://groups.google.com/group/zaproxy-users
