### ISSUE TITLE
Initial report shows PASS for some alerts, but the xml report states otherwise.

### ISSUE THREAD

**Issue by mihai-cindea** [zaproxy/zaproxy#6453]
**Describe the bug**
After running API scan from Docker, I get this output:
```
<snip>
PASS: Cookie Slack Detector [90027]
PASS: SOAP XML Injection [90029]
PASS: WSDL File Detection [90030]
PASS: Loosely Scoped Cookie [90033]
PASS: Cloud Metadata Potentially Exposed [90034]
WARN-NEW: Unexpected Content-Type was returned [100001] x 52 
	https://REDACTED.com/accounts/id/forms?api-version=api-version (405 Not Allowed)
	https://REDACTED.com/accounts/id/portfolio-product?api-version=api-version (405 Not Allowed)
	https://REDACTED.com/accounts/id/forms/outgoing?api-version=api-version (405 Not Allowed)
	https://REDACTED.com/accounts/id/validate-nominated-account?api-version=api-version (405 Not Allowed)
	https://REDACTED.com/accounts/id/fixed?api-version=api-version (405 Not Allowed)
WARN-NEW: Insecure HTTP Method - DELETE [90028] x 12 
	https://REDACTED.com/accounts/id/fixed?api-version=api-version (405 Method Not Allowed)
	https://REDACTED.com/accounts/id?api-version=api-version (405 Method Not Allowed)
	https://REDACTED.com/accounts/id/transfers/10?api-version=api-version/yxvqsb99tn (401 Unauthorized)
	https://REDACTED.com/accounts/validate-tax-wrapped-account?api-version=api-version (405 Method Not Allowed)
	https://REDACTED.com/accounts/id/validate-nominated-account?api-version=api-version/8twe13a99x (401 Unauthorized)
FAIL-NEW: 0	FAIL-INPROG: 0	WARN-NEW: 2	WARN-INPROG: 0	INFO: 0	IGNORE: 0	PASS: 114
```

However, the XML report includes issues like the following for a lot of urls:
```
A Client Error response code was returned by the server (100000)
Cookie Slack Detector (90027)
Insecure HTTP Method - PUT (90028)  # I noticed this one has the same plugin id as `Insecure HTTP Method - DELETE` so maybe this makes sense.
```

Note: I only saw this happen for the `live` image not the `stable` one, however I noticed a huge different in scope: the live image tests ~ 1200+ URLs while `stable` only about 180. That's why I'm not sure if this is a bug or intended behavior.

**To Reproduce**
Not sure this is reproduceable in other environments, but I run using Docker:
```
docker run --privileged -v ${PWD}:/zap/wrk/:rw owasp/zap2docker-live zap-api-scan.py -f openapi -t url -x repot.xml -I
```

**Expected behavior**
I expect to see the results in the xml report also in the log.

**Software versions**
 - ZAP: latest docker live image
 - Add-on: Name and version [e.g. Passive Scan Rules Alpha v19. https://www.zaproxy.org/faq/how-do-i-see-what-version-of-an-add-on-extension-i-have-installed/]
 - OS: [e.g. Windows 10]
 - Java: [e.g. openjdk version "1.8.0_171"]
 - Browser: [e.g. chrome 66, firefox 59, safari 11.1]

**Errors from the zap.log file**
N/A

**Additional context**
I need to run the `live` image since I need something that's not released in `stable` yet.

**Would you like to help fix this issue?**
Of course.

**Comment by kingthorin** [comment]
As there is no plan to change this, but there are plans to address it in the work-in-progress Automation Framework I'm closing this.
