### ISSUE TITLE
Configuration OUTOFSCOPE issues not shown in console output but in Reports.

### ISSUE THREAD

**Issue by AbhishekPuranam** [zaproxy/zaproxy#6455]
Hi , 

I am running a full scan using ZAP docker weekly. I have configured config_file  to ignore Private IP Disclosure. 

config_file
```
# zap-baseline rule configuration file
# Change WARN to IGNORE to ignore rule or FAIL to fail if rule matches
# Only the rule identifiers are used - the names are just for info
# You can add your own messages to each rule by appending them after a tab on each line.
2       OUTOFSCOPE      https://example.com/*
```
It executes and does not show in console output as expected. However, I am also exporting the results to an HTML file. I still see the alert in the HTML. How to avoid this issue not shown on HTML report.

**Comment by psiinon** [comment]
This is a known restriction. There are no plans to fix it in the packaged scans but it will be fixed in the new automation framework which is intended to replace the packaged scans.

**Comment by kingthorin** [comment]
Closing as duplicate zaproxy/zaproxy#6453
