### ISSUE TITLE
Update Reflect to 0.0.10

### ISSUE THREAD

**Issue by cak** [zaproxy/zaproxy#6456]
**Add-on repo**
https://github.com/TypeError/reflect

**Your contact details**
cak@derail.io

**Are you one of the authors**
Yes

**Licence**
Apache License 2.0

**Build instructions**
`grade build`

**Link to more information**

**Twitter handle for tool or author(s)**
OptionalValue

**Promote to Beta or Release?**
No

**Anything else we should know**
Updated to better handle URL decoding errors (addressing #6454 and #6112)

**Comment by thc202** [comment]
Done in zaproxy/zap-admin#474. Thanks @kingthorin!
