### ISSUE TITLE
Why ZAP required Root user to run 

### ISSUE THREAD

**Issue by balayogeeswar** [zaproxy/zaproxy#6457]
Hi , I am planning to host this docker stable release into RedHat Openshift, due to on-premises setup Root users access is disabled due to elevated rights .

https://hub.docker.com/layers/owasp/zap2docker-stable/latest/images/sha256-fa9c69ef7b4b5c6395df2fa50b40146651b87b6a0b019f97d930532bb4e79214?context=explore

How can zap run on normal user without root access.

Thanks,
Bala.

**Comment by psiinon** [comment]
Please dont ask questions as issues.
The User Group is a much better place for them: https://groups.google.com/group/zaproxy-users
