### ISSUE TITLE
Add 'static assets' as a valid caching case to 'Incomplete or No Cache-control' rule

### ISSUE THREAD

**Issue by Lonzak** [zaproxy/zaproxy#6462]
An "_Incomplete or No Cache-control and Pragma HTTP Header Set_" alert is raised when a response has a Cache-Control header that contains `Cache-Control: public, max-age=604800, immutable`.
So I would like to propose to extend this rule for the "static assets" case. It is perfectly valid to enable caching for css, js, images and the like.
[MDN states](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#caching_static_assets) that the following should be used `Cache-Control: public, max-age=604800, immutable`

```
//pseudo code)
if(url.endsWith(".css") || url.endsWith(".js"); || url.endsWith("png") //some other image format or even anything with ".XXX"){

if(cacheControlHeaders.indexOf("public") < 0
                    || cacheControlHeaders.indexOf("max-age") < 0
                    || cacheControlHeaders.indexOf("immutable") < 0) {
                this.raiseAlert(msg, id, HttpHeader.CACHE_CONTROL, cacheControlHeaders);
            }
}
//no cache case
else if (cacheControlHeaders.isEmpty()

```

**Comment by kingthorin** [comment]
How can you be sure js or images don’t contain sensitive details? There are plenty cases where js files contain sensitive “constants” and for images simply consider medical records etc.

Further there doesn’t seem to be a security issue in failing to cache css or js.

I guess this could be added as a brand new add-on that produces some sort of “performance” finding... 🤷‍♂️

**Comment by kingthorin** [comment]
I believe the best way for this to be handled is using Alert Filters:  https://www.zaproxy.org/docs/desktop/addons/alert-filters/

**Comment by Lonzak** [comment]
Yes there might be cases where certain images should not be cached. But then a rule (on informational level) could point that out. But on the other hand if people use caching incorrectly (e.g. do not specify max-age or some other not to be used options) they are only advised to use nostore/nocaching. Since that is not desired they ignore the hint or use altert-filters to rank it down.

**Comment by kingthorin** [comment]
I'm still not seeing the security issue in failing to cache these assets.

I do agree that Alert Filters aren't applicable.

You could leverage Alert Overrides to supplement/replace the details you're concerned about: 
- https://www.zaproxy.org/docs/desktop/start/features/alerts/
- https://www.zaproxy.org/blog/2020-05-11-alert-overrides-youdontknowzap/

The other simple option would be to add a scripted passive scan rule:
- https://github.com/zaproxy/community-scripts/tree/master/passive

**Comment by Lonzak** [comment]
Ok then at least the title and description should be adapted to indicate your intention. When reading the current, one gets the impression that caching is not an option at all. So some clarification would help here.

**Now:**
**Title**: Incomplete or No Cache-control and Pragma HTTP Header Set
**Description**: The cache-control and pragma HTTP header have not been set properly or are missing allowing the browser and proxies to cache content.
**Solution**: Whenever possible ensure the cache-control HTTP header is set with  no-cache, no-store, must-revalidate; and that the pragma HTTP header is  set with no-cache.

**Suggestion**:

**Title**: Re-examine Cache-control / Pragma HTTP Headers
**Description**: The cache-control and pragma HTTP headers have not been set properly or are missing, allowing the browser and proxies to cache content. For static assets like css, js or image file this might be the intended but make sure that no sensitive content will be cached.
**Solution:** Whenever possible ensure the cache-control HTTP header is set with "no-cache, no-store, must-revalidate;" and that the pragma HTTP header is  set to "no-cache". If an asset should be cached set it to "public, max-age=XXXX, immutable" and do not specify pragma.
**Reference**: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control

**Comment by kingthorin** [comment]
@Lonzak i see what you’re getting at. I’ll look at making some adjustments along these lines.
