### ISSUE TITLE
OWASP ZAP scan error using Azure DevOps

### ISSUE THREAD

**Issue by ZekeD3** [zaproxy/zaproxy#6463]
I have an Azure DevOps pipeline that has a "OWASP ZAP Scan" task in it.

Under ZAP API Configuration I have the-

ZAP API Url  - configured with the FQDN of the Server that has OWASP ZAP on it
API Key which was obtained from OWASP ZAP (under TOOLS, OPTIONS, API)
Target URL - That has site to be tested

When the pipeline is executed when it gets to the task it comes up with -
##[error]Task Failed. Error: {"Success":false,"Message":"Error: connect ECONNREFUSED 127.0.0.1:8090"}

When I start a browser session on the Server (that is specified in the ZAP API Url) and type 127.0.0.1:8090 if comes up with the Welcome screen indicating that the OWASP Zed Attack Proxy (ZAP) is running.

At a bit of a loss as we have Pipeline task configured as required.

**Comment by psiinon** [comment]
Please dont ask questions as issues.
The ZAP User Group is a much better place to ask them: https://groups.google.com/group/zaproxy-users
