### ISSUE TITLE
Parsing message body failed: Invalid JSON for form-based authentication

### ISSUE THREAD

**Issue by hnestorova** [zaproxy/zaproxy#6468]
**Describe the bug**
We run our recorded clean sessions using Jenkins. What I see in the Jenkins console is:
`09:13:23 [ZAP Jenkins Plugin] AUTHENTICATION ENABLED [ TRUE ]
09:13:23 [ZAP Jenkins Plugin] AUTHENTICATION MODE [ FORM_BASED ]
09:13:23 
09:13:23 [ZAP Jenkins Plugin] FORM BASED AUTH SET AS: loginUrl=http%3A%2F%2FPRIVATE%2FPRIVATE%2FservletsPublic%2Flogin&loginRequestData=userName%3D%7B%25username%25%7D%26password%3D%7B%25password%25%7D%26passwordName%3DPASSWORD
09:13:23 
09:13:23 Parsing message body failed: Invalid JSON: <json>:1:0 Expected json literal but found u
09:13:23 userName={%username%}&password={%password%}&passwordName=PASSWORD`

our setup before and currently are provided as screenshots - both produce the error

**Software versions**
 - ZAP: ZAP_WEEKLY_D-2021-02-15
 - Official OWASP ZAP Jenkins Plugin
 - OS: Windows Server 2016
 - Java: jdk-11.0.9+11
 - Browser: sessions lastly recorded on Chrome 88.0.4324.182

**Comment by hnestorova** [comment]
![current](https://user-images.githubusercontent.com/30794708/109282850-c1c5fb00-7826-11eb-9b75-41972ace263b.PNG)
![before](https://user-images.githubusercontent.com/30794708/109283061-fd60c500-7826-11eb-8800-c53135da2aed.PNG)

**Comment by psiinon** [comment]
I think it would be better to discuss this on the ZAP User Group: https://groups.google.com/group/zaproxy-users
At this stage we dont know if its a bug in ZAP or not, it could be a configuration issue.
Or it could be a bug in the Jenkins plugin, which is in fact no longer official and is not currently supported by the ZAP core team.
