### ISSUE TITLE
Cannot detect injection vulnerabilities on null value JSON objects

### ISSUE THREAD

**Issue by gitveio** [zaproxy/zaproxy#6469]
As the title describes, if the JSON of the request content is:
{"name":null}
The attribute of name will not be tested at all. In fact, the name has a SQL injection problem.

But if you modify the JSON to:
{"name":""}
In this case, the problem will be detected. I am not sure if this is a real problem or just a configuration problem.
Can anyone help me, thanks

**Comment by thc202** [comment]
Right, null values are not tested, I guess they aren't because ZAP does not know which type is supposed to be there (e.g. is it an object, an array, or a string?). It could default to string...

**Comment by psiinon** [comment]
+1 for defaulting to string :)

**Comment by gitveio** [comment]
Understand, thank you for your reply.

**Comment by gitveio** [comment]
Can I deal with this one, and if so, whether dealing with all null values will significantly reduce the test speed. If it is me, an option switch may be added to "input vectors", which is not checked by default. Is this acceptable, or some other ideas.

**Comment by thc202** [comment]
@gitveio are you still working on this issue?

**Comment by gitveio** [comment]
Sorry, I'm not working on it.

**Comment by thc202** [comment]
OK, no worries. Reopening, still worth addressing.
