### ISSUE TITLE
can't intercept request without response

### ISSUE THREAD

**Issue by knassar702** [zaproxy/zaproxy#6472]
hi team
I'm trying to intercept the request without response by click on `Toggle Break on All Requests` , but it doesn't work , it will intercept requests & responses

![zap1](https://user-images.githubusercontent.com/45688522/109583893-4e173d00-7b09-11eb-807c-ae9b69a1ef62.png)

**Comment by psiinon** [comment]
Are you sure?
Once a request has been intercepted then if you press "Step" then it will continue to the next response by design. To continue to the next request use the "Continue" button.

**Comment by knassar702** [comment]
hi @psiinon 
i know this options , but i need to keep zap intercept all requests , if i clicked on "Continue" button , zap will be stop requests intercept !

**Comment by khalil2535** [comment]
في زرين بيمرروا الطلب والرد يا خالد, استخدم الي باللون الأخضر بتمرر طلب واحد أما الي باللون الأحمر بتمرر كل الطلبات

![image](https://user-images.githubusercontent.com/26520106/110584008-3aa64a80-8177-11eb-9ae8-7f659259a130.png)

**Comment by knassar702** [comment]
@khalil2535 
عارف كانت الفكرة بس انك تقدر تعدي الريكويست والانترسيبت ميوقفش 
المهم حليتها بى انك تضيف اسكوب لي break
