### ISSUE TITLE
Add-on: Export Report not showing correct detail.

### ISSUE THREAD

**Issue by faisalusuf** [zaproxy/zaproxy#6474]
**Describe the bug**
Export Report addon is not showing the details filled when exporting.

**To Reproduce**
1. Go to 'Reports'
2. Click on 'Export Report'
3. Fill the information
4. Export report 

**Expected behavior**
The information filled in the form should be on the title page.

**Screenshots**
![image](https://user-images.githubusercontent.com/2043079/110153338-ba918500-7e04-11eb-9fa9-4bcdf2bd11e1.png)

**Software versions**
 - ZAP: 2.10.0
 - Add-on: Export Report (Latest)
 - OS: Kali 2021.1 & Windows 10
 - Java: 11
 - Browser: firefox

**Errors from the zap.log file**
Non

**Additional context**
![image](https://user-images.githubusercontent.com/2043079/110153612-1c51ef00-7e05-11eb-8d75-d872f118979b.png)

**Would you like to help fix this issue?**
Yes

**Comment by psiinon** [comment]
This add-on is being deprecated in favour of the new Report Generation add-on: https://www.zaproxy.org/docs/desktop/addons/report-generation/
It is not going to be updated any more and will be removed from the marketplace soon.
