### ISSUE TITLE
losing port using soapui go through zap to visit a website

### ISSUE THREAD

**Issue by zhongxinlei** [zaproxy/zaproxy#6475]
As of ZAP 2.8.0, if I use soapUI(with the same proxy as zap dose) to visit a website, the redirect would lose port info, which would ending up to 404. 
![{DE497927-CC43-4708-9861-833C6166086A}](https://user-images.githubusercontent.com/29734671/110194723-d3398380-7e74-11eb-819f-cc75cfdcfabd.png)

![{10C18477-B03F-4C75-B3B5-CB6093E03BC2}](https://user-images.githubusercontent.com/29734671/110194675-78a02780-7e74-11eb-9bf2-4defc6c9e942.png)
7ade.png)

back in ZAP 2.7.0, this problem did not exit.

**Comment by thc202** [comment]
Your request has two host headers.

**Comment by zhongxinlei** [comment]
@thc202 yes I got two host headers, but I think that's due to ZAP, if I disable HUD, then the lossing port thing disappears. So I think it could be an issue of ZAP.

**Comment by thc202** [comment]
Could you provide the original request being sent?

**Comment by thc202** [comment]
Closing, not enough information. Feel free to leave a comment with the original request that reproduces the issue.
