### ISSUE TITLE
[False Positive] The "None" value of the "SameSite" attribute of an HTTP cookie is incorrectly treated as invalid

### ISSUE THREAD

**Issue by vladimir-kazakov** [zaproxy/zaproxy#6482]
I have an HTTP cookie with the `SameSite` attribute, which value is `None`.

> Set-Cookie: name=value; path=/; secure; samesite=none

This cookie triggers the `Cookie Without SameSite Attribute` alert, which is wrong, because the cookie has this attribute.

Moreover, the description says:

> A cookie has been set with an invalid SameSite attribute value, which means that the cookie can be sent as a result of a 'cross-site' request.

This is also wrong, because `None` is [not an invalid value](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite#none), and there are good reasons to use it. In my case, it's an authentication through an external identity provider by using the OIDC protocol. So, it must be possible to send cookies to other sites, which request authentication.

I understand that in majority of cases `None` may not be a good choice, so it's okay to have an alert to draw attention. It's also impossible to say, without any context, whether this value is okay or not. This is not an issue. The issue is that the current behavior is confusing.

The expected behavior would be:
1. Don't say that the cookie doesn't have the `SameSite` attribute (because it's there).
2. Don't say that the value is invalid, unless it really is.
3. Don't say that `None` is an invalid value (because it's not, and there may be reasons to use it). A better option would be to ask to make sure, whether it's really okay to use this value in this specific case.

Currently, I'm using the latest version of OWASP ZAP (2.10.0), on the latest version of Windows 10 (20H2; 19042).

**Comment by psiinon** [comment]
I think the rule is correct, although it could be reworded for the "none" case.
As you say, ZAP cant tell if "none" is ok or not and so it should raise an issue by default.
We already have various ways of whitelisting alerts, including:

- The [rule option](https://www.zaproxy.org/docs/desktop/ui/dialogs/options/ruleconfig/) `rules.cookie.ignorelist`
- [Alert filters](https://www.zaproxy.org/docs/desktop/addons/alert-filters/) 

Those are the ways you can tell ZAP that its not a valid issue. I dont think we need additional options right now.

**Comment by vladimir-kazakov** [comment]
The main problem here is that this alert is reported in a very confusing way, saying that the `SameSite` attribute isn't there, and that its `None` value is invalid. Both claims are wrong. Currently, it looks like ZAP doesn't know about the `None` value, so it thinks that the `SameSite` attribute is missing.

Also, we shouldn't forget that `SameSite=None` and no `SameSite` at all are different cases with different behaviors.

**Comment by psiinon** [comment]
I agree the text should change.
And I'd be fine ignoring "None" on the high threshold.
