### ISSUE TITLE
Request to API URL https://myurl.internal:8080 from 10.x.x.x not permitted

### ISSUE THREAD

**Issue by legolasthehansy** [zaproxy/zaproxy#6486]
I'm trying to evaluate zaproxy and running it on a Red Hat 7 system. There is no GUI. 
ZAP Version - 2.10.0

Brought zap on the command line

`./zap.sh -daemon -host 0.0.0.0 -config api.addrs.addr.name=10.x.x.x -config api.disablekey=true`

However when we try to hit it from a browser on 10.x.x.x, we get a EMPTY RESPONSE. Below is what we see on the console, 

`241934 [ZAP-ProxyThread-73] WARN  org.zaproxy.zap.extension.api.API - Request to API URL https://myurl.internal:8080/ from 10.x.x.x not permitted
498447 [ZAP-ProxyThread-123] WARN  org.zaproxy.zap.extension.api.API - Request to API URL https://myurl.internal:8080/UI with host header 10.x.x.x not permitted`

Surely I'm missing something. Can you help me find out what it is?

**Comment by kingthorin** [comment]
Please don't ask questions as issues - the [ZAP User Group]( https://groups.google.com/group/zaproxy-users) is a much better place for questions.

If you’re asking about a third party components such as the Jenkins plugin or VSTS plugin please look for their preferred support mechanism as these were not created by and are not supported by the core team.

In this particular case I’d suggest referring to the API docs:  https://www.zaproxy.org/docs/api/
