### ISSUE TITLE
OpenAPI specification - handling 'enum' integer

### ISSUE THREAD

**Issue by jeremychoi** [zaproxy/zaproxy#6489]
**Is your feature request related to a problem? Please describe.**

Values in `enum` are not used when automated requests are sent from an openapi definition.

For example, where the following openapi definition exists,

```
"paths": {
        "/rule/": {
            "get": {
                "operationId": "rule_list",
                "summary": "List all rules",
                "description": "",
                "parameters": [{
                    "name": "category",
                    "in": "query",
                    "description": "Display rules of this category (number)",
                    "required": false,
                    "schema": {
                        "type": "array",
                        "items": {
                            "type": "integer",
                            "enum": [1, 2, 3, 4]
                        }
                    },
                    "style": "simple"
                }],
... omitted ...
```

the request must be sent with like `category=1` (1 is one of the values in enum). Currently, ZAP sends requests with `category=10` regardless of the values. All integer parameters seem to be set to '10'.

**Describe the solution you'd like**
one of the values defined in `enum` is used.

**Comment by sonawanesarvesh** [comment]
For me scenario is little different -  **only first value** from all below each enum is utilized by the active scanner and ignored all the rest values

    toDateQuery:
        name: to-date
        in: query
        description: 'This is used to retrieve the rates for a date in the past, i.e. historical rates (maximum of 36 months). It is not required for the current date''s rate. Date format should be MM/dd/yyyy. The Bloomberg time zone is GMT. E.g. 10/01/2019'
        required: true
        type: string
        enum: ['10/02/2019', '10/03/2019', '10/01/2019']

    fromDateQuery:
        name: from-date
        in: query
        description: 'This is used to retrieve the rates for a date in the past, i.e. historical rates (maximum of 36 months). It is not required for the current date''s rate. Date format should be MM/dd/yyyy. The Bloomberg time zone is GMT. E.g. 10/01/2019'
        required: true
        type: string
        enum: ['10/02/2019', '10/03/2019', '10/01/2019']

    priceTypeQuery:
        name: price-type
        in: query
        description: 'Type of daily exchange rate^(0[1-9]|1[012])[- /.](0[1-9]|[12][0-9]|3[01])[- /.](19|20)\d\d$ e.g. Daily sale, Daily buy, Daily average etc. Eg. ASK'
        required: false
        type: string
        enum:
            - ASK
            - BID
            - HIGH
            - LOW
            - LAST
            - '*'`

**Comment by thc202** [comment]
That's the expected behaviour, the endpoint is imported just once.

**Comment by sonawanesarvesh** [comment]
So instead of enum - can we use **default** in parameters or examples?

`toDateQuery:
    name: to-date
    in: query
    description: 'This is used to retrieve the rates for a date in the past, i.e. historical rates (maximum of 36 months). It is not required for the current date''s rate. Date format should be MM/dd/yyyy. The Bloomberg time zone is GMT. E.g. 10/01/2019'
    required: true
    type: string
    default: '10/02/2019',

**Comment by thc202** [comment]
Yes, OpenAPI add-on will use the default value or example if available.

**Comment by jeremychoi** [comment]
I just verified that the fist value of enum is used if the parameter is 'string' type as @sonawanesarvesh mentioned. However, this issue is still there when the parameter is the 'integer' type.

**Comment by jeremychoi** [comment]
@thc202 if I want to contribute to fixing it, how do I go about? any pointer would be appreciated!

**Comment by thc202** [comment]
fyi, I'm already addressing it. But for the record, the source for the OpenAPI add-on is in:
https://github.com/zaproxy/zap-extensions/tree/ccf495d2d399580a618adc9a76b98584bbdde73f/addOns/openapi

and the issue would be in the generators.
