### ISSUE TITLE
"Timestamp Disclosure - Unix" needs fine tuning

### ISSUE THREAD

**Issue by beatquantum** [zaproxy/zaproxy#6493]
Owasp Zap gives a very large number of alerts relating to Timestamp Disclosure by interpreting any large integer as a date.

**To Reproduce**
1. Use the following header on any nginx server
add_header Strict-Transport-Security "max-age=31536000; preload; includeSubDomains" always;
2. Run Owasp Zap (Windows)
3. Attack that server
4. Check Alerts / Timestamp Disclosure

**Expected behavior**
31356000 is a requirement for HSTS. Please visit hstspreload.org for details.
Any integer found in such headers should not be interpreted as a timestamp.

**Software versions**
 - ZAP: 2.10.0
 - OS: [e.g. Windows 10]
 - Java: [e.g. openjdk version "1.8.0_171"]
 - Browser: [e.g. chrome 66, firefox 59, safari 11.1]

**Would you like to help fix this issue?**
Yes, HSTS is only one example. I will be happy to provide a large list of headers for nginx and apache2, which contain such integers, so that the relevant lines can be excluded by the parser.

**Comment by psiinon** [comment]
@beatquantum a list of headers which typically have these large ints would be much appreciated - we could def whitelist those.

**Comment by kingthorin** [comment]
Could you please provide a redacted screenshot because HSTS is already on the ignore list.
https://github.com/zaproxy/zap-extensions/blob/450adfe5c5be38bd9bd37d0cba73f5262c6277cf/addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/TimestampDisclosureScanRule.java#L69-L75

**Comment by beatquantum** [comment]
> Was the HSTS value highlighted when you view the Alert? Does the same value appear elsewhere in the response (headers or body)?

31536000, which evaluates to: 1971-01-01 01:00:00
By the way, this is the minimum value that would qualify a domain to be included in the HSTS preload list.

**Comment by beatquantum** [comment]
> Could you please provide a redacted screenshot because HSTS is already on the ignore list.

Sure. Attached is the full screenshot. 
(No redaction is required as this is an experimental server.)
![owasp-1](https://user-images.githubusercontent.com/67234356/112423761-2774ac80-8d2b-11eb-860c-e00ecfc20344.JPG)

**Comment by beatquantum** [comment]
> @beatquantum a list of headers which typically have these large ints would be much appreciated - we could def whitelist those.

Happy to share. These are the redacted headers for Nginx, which may contain integer values if chosen by the developer. Large values may trigger the Timestamp Detection alert.

add_header Expect-CT 'max-age=3600, enforce, report-uri="https://something"';
add_header Expect-Staple "max-age=3600; report-uri=https://something; includeSubDomains; preload";
add_header Strict-Transport-Security "max-age=31536000; preload; includeSubDomains" always;
add_header Report-To "{\"group\":\"default\",\"max_age\":31536000,\"endpoints\":[{\"url\":\"https://something/a/d/g\"}],\"include_subdomains\":true}";
add_header NEL "{\"report_to\":\"default\",\"max_age\":31536000,\"include_subdomains\":true}";

Thanks.

**Comment by beatquantum** [comment]
@psiinon - I also have a few redacted examples for apache2 below.

Header set Expect-CT 'max-age=3600, report-uri="https://something", enforce'
Header set Expect-Staple "max-age=3600, includeSubDomains, preload, report-uri=\"https://something/r/d/staple/enforce\""
Header Set Cache-Control "max-age=0, no-store, no-cache, no-transform"
Header always set Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"

Thanks.

**Comment by kingthorin** [comment]
So it isn’t actually picking up the HSTS entry the issue is that ZAP highlights the first occurrence of the value which in this case happens to be the HSTS header though the value actually being caught by the scan rule is other headers `Report-to` and `Nel`

**Comment by beatquantum** [comment]
> 
> 
> So it isn’t actually picking up the HSTS entry. The issue is that ZAP highlights the first occurrence of the value which in this case happens to be the HSTS header, though the value actually being caught by the scan rule is other headers `Report-To` and `NEL`

You are right @kingthorin . I hope the other headers I indicated help adding exclusions.

**Comment by kingthorin** [comment]
We can add `Report-To` and `NEL` to the list of exclusions.
The values in the cache headers aren't large enough to be caught by the rule.

You could install the Alert Filters add-on and configure it for your Evidence value `31536000` (assuming of course that you've reviewed and are convinced that all of those are false positives).
