### ISSUE TITLE
Google Chrome bowser is not opening 

### ISSUE THREAD

**Issue by koustubh** [zaproxy/zaproxy#6494]
I am using ZAP tool to traverse all screens for web application. After updating ZAP to latest v2.10.0, ZAP tool is  not launching chrome browser although mozilla firefox browser is launching but without HUD.

Steps- 
1. Open ZAP tool 
2. Click on 'Manual Explore' with 'Standard Mode'
3. Enter URL to explore
4. Click on 'Launch Browser' button

1. After clicking on launch browser with Chrome option google chrome browser is opening for fraction of second and closing automatically. 
2. After clicking on launch browser with Firefox option browser is opening without HUD and no any URL is recording under sites tree

**Comment by thc202** [comment]
Please, provide the versions of the browsers.

**Comment by psiinon** [comment]
Have you updated all of the ZAP add-ons, especially the webdrivers?
What errors are shown in the zap.log file?
https://www.zaproxy.org/faq/somethings-not-working-what-should-i-do/#check-the-log-file

**Comment by koustubh** [comment]
> Please, provide the versions of the browsers.
Google Chrome
Version 89.0.4389.90 (Official Build) (64-bit)

Firefox
87.0

**Comment by koustubh** [comment]
> Have you updated all of the ZAP add-ons, especially the webdrivers?
> What errors are shown in the zap.log file?
> https://www.zaproxy.org/faq/somethings-not-working-what-should-i-do/#check-the-log-file

**Comment by psiinon** [comment]
So did updating the webdrivers do the trick?

**Comment by koustubh** [comment]
> Please, provide the versions of the browsers.



> Have you updated all of the ZAP add-ons, especially the webdrivers?
> What errors are shown in the zap.log file?
> https://www.zaproxy.org/faq/somethings-not-working-what-should-i-do/#check-the-log-file

please see error below from zap.log file-

ERROR ExtensionQuickStartLaunch - session not created: This version of ChromeDriver only supports Chrome version 85
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'SILICUS-LT-83', ip: '192.168.1.23', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_251'
Driver info: driver.version: ChromeDriver

**Comment by koustubh** [comment]
> So did updating the webdrivers do the trick?

I have updated 'Windows Webdrivers' to v 25.0.0 and tried still could see same error in zap.log file.

**Comment by koustubh** [comment]
mistakenly closed

**Comment by thc202** [comment]
Remove the directory `webdriver` in the ZAP home directory and start ZAP again.
https://www.zaproxy.org/faq/what-is-the-default-directory-that-zap-uses/

**Comment by thc202** [comment]
There's a newer version of the WebDriver add-on that should match the Chrome version you are using, still better do the above to ensure it uses the latest webdrivers.

**Comment by koustubh** [comment]
> Remove the directory `webdriver` in the ZAP home directory and start ZAP again.
> https://www.zaproxy.org/faq/what-is-the-default-directory-that-zap-uses/

I did the same and updated 'Windows Webdrivers' again and it worked..

Thank you very much!!!

**Comment by koustubh** [comment]
> There's a newer version of the WebDriver add-on that should match the Chrome version you are using, still better do the above to ensure it uses the latest webdrivers.

yes.. that worked.

**Comment by RKkomali** [comment]
Even i faced the same issue while launching chorme browser. 
@koustubh - Tell me how to updated the windows webdriver.

**Comment by kingthorin** [comment]
Click the Check for Updates button in the toolbar.

**Comment by koustubh** [comment]
> Even I faced the same issue while launching the chrome browser.
> @koustubh - Tell me how to update the windows web driver.

After updating web drives add-on please perform below steps too,

Remove the directory webdriver in the ZAP home directory and start ZAP again.
https://www.zaproxy.org/faq/what-is-the-default-directory-that-zap-uses/

**Comment by RKkomali** [comment]
> Click the Check for Updates button in the toolbar.
You mean to say under ZAP menu item.

**Comment by RKkomali** [comment]
> Click the Check for Updates button in the toolbar.

Sorry, I am new to this ZAP tool. Can you elaborate on the same?

**Comment by koustubh** [comment]
> > Click the Check for Updates button in the toolbar.
> 
> Sorry, I am new to this ZAP tool. Can you elaborate on the same?

You can see 'Manage Add-ons' option on tool bar. click on this then you could see add-ons window then you can update Webdrivers.

**Comment by RKkomali** [comment]
@koustubh- Refer attached document which i updated the web drivers.
[ZAP_Web_Driver_Update_Steps.docx](https://github.com/zaproxy/zaproxy/files/6318134/ZAP_Web_Driver_Update_Steps.docx)

**Comment by RKkomali** [comment]
> > Even I faced the same issue while launching the chrome browser.
> > @koustubh - Tell me how to update the windows web driver.
> 
> After updating web drives add-on please perform below steps too,
> 
> Remove the directory webdriver in the ZAP home directory and start ZAP again.
> https://www.zaproxy.org/faq/what-is-the-default-directory-that-zap-uses/

I was unable to delete the webdriver in the ZAP home directory. Please help me on this
![image](https://user-images.githubusercontent.com/82588955/114875243-bb153680-9e1a-11eb-887f-ef7cd48f4e71.png)

**Comment by thc202** [comment]
Exit ZAP and terminate all ChromeDriver processes (assuming just ZAP launched them).

**Comment by kingthorin** [comment]
Close ZAP, or the windows explorer, or command prompt that has that dir in use?

**Comment by RKkomali** [comment]
I am able to delete the web driver folder and restarted the ZAP but still, I was unable to re launch the chrome browser (After clicking on launch browser with Chrome option google chrome browser is opening for fraction of second and closing automatically.)

**Comment by thc202** [comment]
Which Chrome version? Also, what's in the log?

**Comment by RKkomali** [comment]
> Which Chrome version? Also, what's in the log?

Chrome version is "Version 90.0.4430.72 (Official Build) (64-bit)" . Where can I verify the logs?

**Comment by RKkomali** [comment]
> > Which Chrome version? Also, what's in the log?
> 
> Chrome version is "Version 90.0.4430.72 (Official Build) (64-bit)" . Where can I verify the logs?

[ZAP_Log.txt](https://github.com/zaproxy/zaproxy/files/6322464/ZAP_Log.txt)

**Comment by RKkomali** [comment]
> Exit ZAP and terminate all ChromeDriver processes (assuming just ZAP launched them).

I did the same but still unable to delete the webdriver folder under OWASAP ZAP folder

**Comment by koustubh** [comment]
> > > Which Chrome version? Also, what's in the log?
> > 
> > 
> > Chrome version is "Version 90.0.4430.72 (Official Build) (64-bit)" . Where can I verify the logs?
> 
> [ZAP_Log.txt](https://github.com/zaproxy/zaproxy/files/6322464/ZAP_Log.txt)

C:\Users\username\OWASP ZAP\zap.log

**Comment by thc202** [comment]
Restart the machine and delete the webdriver folder before using ZAP. The logs indicate that you are using an older/incompatible webdriver.

**Comment by thc202** [comment]
Also, there's a new version of the WebDriver add-on (which matches the browser version you are using).
