### ISSUE TITLE
Unable to run ZAP from source with Java 16

### ISSUE THREAD

**Issue by jangelesg** [zaproxy/zaproxy#6511]
**Describe the bug**
Error at building the project from source code.  Based on the documentation located in the following URL https://www.zaproxy.org/docs/developer/quick-start-build/ 

**To Reproduce**
1. Navigate to the cloned zaproxy folder and run the following command ./gradlew run 
2. See error  "**java.lang.NoClassDefFoundError: could not initialize class org.codehaus.groovy.runtime.invokerhelper "**'

**Expected behavior**
“Dev Build” loading window.

**Software versions**
 - ZAP: latest repo version v2.10.0
 - Add-on: 
 - OS: MacOS Big Sur 11.2.3 (20D91)
 - Java: openjdk version "16" 2021-03-16
OpenJDK Runtime Environment (build 16+36-2231)
OpenJDK 64-Bit Server VM (build 16+36-2231, mixed mode, sharing)
- gradle 6.8.3
**Errors from the zap.log file**

**Additional context**

**Would you like to help fix this issue?**
I'd like to try and help fix this issue.
I modified the following file "gradle-wrapper.properties" under zaproxy/gradle/wrapper and changed the value "distributionUrl" to https://services.gradle.org/distributions/gradle-6.6.1-bin.zip and the error disappear

**Comment by thc202** [comment]
Better use Java 8 or 11.

**Comment by jangelesg** [comment]
Gotcha,!! ill try with that version

**Comment by jangelesg** [comment]
done thks it worked with java 11

**Comment by thc202** [comment]
Reopening, still not addressed.
