### ISSUE TITLE
Buttons of Manage Tags dialog are too small

### ISSUE THREAD

**Issue by pranavsaxena17** [zaproxy/zaproxy#6512]
**Describe the bug**
The "Cancel" and "Delete" button of the Manage Tags dialog are too small for their text to be fully visible.

**To Reproduce**
1. Go to any entry in the History Tab.
2. Right click, go to "Manage Tags..."
3. The buttons' text is not fully visible.

**Screenshots**

![Screenshot from 2021-04-04 17-17-16](https://user-images.githubusercontent.com/58285865/113507760-0d786c80-956a-11eb-978f-e7da043f4b64.png)

**Expected behavior**
The buttons should be large enough for their text to display properly.

**Software versions**
 - ZAP: 2.10.0
 - OS: Ubuntu 20.04
 - Java: OpenJDK 11

**Comment by thc202** [comment]
Could provide a screenshot and indicate which look and feel you are using?

**Comment by pranavsaxena17** [comment]
Included the screenshot(it's the default Ubuntu Look and Feel)

**Comment by thc202** [comment]
Thank you.
