### ISSUE TITLE
False-positive: 40029 Trace.axd Information Leak

### ISSUE THREAD

**Issue by rugk** [zaproxy/zaproxy#6517]
**Describe the bug**
"Trace.axd Information Leak" is reported on a Docker file with an nginx server, just because some URL `http://localhost:8080/trace.axd`returns a 200 HTTP response.
This is a false-positive, because AFAIK we have a catch-all in our software to just return a 200 result with content to such unknown URLs. We certainly don't use ASP.Net.

Maybe better check for some content in there?

**To Reproduce**
Run the ZAP stable Docker image (full scan) against our project PrivateBin (docker image `privatebin/nginx-fpm-alpine`).
Here via GitHub:
https://github.com/PrivateBin/docker-nginx-fpm-alpine/actions/runs/716506686

See also attached HTML report there.

**Expected behavior**
40029 should not be reported.

**Screenshots**
<details>

Medium (Medium) | Trace.axd Information Leak
-- | --
Description | The  ASP.NET Trace Viewer (trace.axd) was found to be available. This  component can leak a significant amount of valuable information.
 
URL | http://localhost:8080/js/trace.axd
Method | GET
Evidence | HTTP/1.1 200 OK
URL | http://localhost:8080/css/bootstrap/trace.axd
Method | GET
Evidence | HTTP/1.1 200 OK
URL | http://localhost:8080/css/trace.axd
Method | GET
Evidence | HTTP/1.1 200 OK
URL | http://localhost:8080/img/trace.axd
Method | GET
Evidence | HTTP/1.1 200 OK
URL | http://localhost:8080/trace.axd
Method | GET
Evidence | HTTP/1.1 200 OK
URL | http://localhost:8080/css/prettify/trace.axd
Method | GET
Evidence | HTTP/1.1 200 OK
Instances | 6
Solution | Consider  whether or not Trace Viewer is actually required in production, if it  isn't then disable it. If it is then ensure access to it requires  authentication and authorization.
Reference | https://msdn.microsoft.com/en-us/library/bb386420.aspxhttps://msdn.microsoft.com/en-us/library/wwh16c6c.aspxhttps://www.dotnetperls.com/trace
CWE Id | 215
WASC Id | 13
Source ID | 1

</details>

**Software versions**
 - ZAP:  docker.io/owasp/zap2docker-stable:latest
 - Add-on: no idea
 - OS: Ubuntu
 - Java: no idea
 - Browser: no idea

via GitHub Action `zaproxy/action-full-scan@v0.2.0`

**Errors from the zap.log file**
See linked GitHub Actions run above

**Additional context**

**Would you like to help fix this issue?**
Maybe.

**Comment by thc202** [comment]
Why not 404? Custom pages could be of help: https://www.zaproxy.org/docs/desktop/start/features/custompages/

**Comment by rugk** [comment]
Well… it's just how simple the thing was designed. :smile: 

In any case, it's a false positive and checking some result content may be a good idea to avoid it.
