### ISSUE TITLE
Check more HTTP headers

### ISSUE THREAD

**Issue by rugk** [zaproxy/zaproxy#6518]
**Is your feature request related to a problem? Please describe.**
You seem to check for `X-Content-Type-Options`, but you miss a few more modern security headers, that are always recommend.

See:
https://securityheaders.com/
https://github.com/PrivateBin/PrivateBin/issues/765

**Describe the solution you'd like**
Basically we'd want this:
```
    Cross-Origin-Resource-Policy: same-origin
    Cross-Origin-Embedder-Policy: require-corp
    Cross-Origin-Opener-Policy: same-origin
    X-Content-Type-Options: nosniff
    X-Frame-Options: deny
```

**Describe alternatives you've considered**
Using the other given services/websites.

**Additional context**
As you report `X-Content-Type-Options` you should report these other's too, however.

**Would you like to help implementing this feature?**
Just say if you'd like to try and help implementing this feature. We'll provide any advice and guidance you need.

**Comment by thc202** [comment]
Those are included in https://www.zaproxy.org/docs/desktop/addons/passive-scan-rules-alpha/

**Comment by kingthorin** [comment]
XFO is also covered it in own rule.
