### ISSUE TITLE
Can not scroll past 'contexts' in 'sites' tab with FlatLaf L&F

### ISSUE THREAD

**Issue by FalcoGer** [zaproxy/zaproxy#6520]
**Describe the bug**
Can not use mouse wheel to scroll past 'Context' in 'Sites' tab.

**To Reproduce**
1. Go to 'Sites'
2. Browse around a bunch with the proxy on so the Sites populate
3. Scroll to the top of the list with both sites and contexts expanded
4. Use mouse wheel to scroll down

**Expected behavior**
The list scrolls normally to the bottom.

**Observed behavior**
The scrolling stops at the end of Contexts. Neither can you use arrow keys to go down from the bottom most entry in contexts.
However dragging the scrollbar manually with the mouse past that point allows normal scrolling. Just not when any context is in view.

**Screenshots**
N/A

**Software versions**
 - ZAP: 2.10
 - Add-on: N/A
 - OS: Ubuntu 20.04 (5.4.0-70-generic, amd64)
 - Java: openjdk 11.0.10 2021-01-19
 - Browser: N/A

**Errors from the zap.log file**
None

**Additional context**
None

**Would you like to help fix this issue?**
I don't do java.

**Comment by kingthorin** [comment]
Screenshot?

**Comment by FalcoGer** [comment]
> Screenshot?

How would I make a screenshot of me scrolling?

**Comment by FalcoGer** [comment]
Top of the list
![image](https://user-images.githubusercontent.com/16250196/113770962-18c2c800-9723-11eb-99f2-18e29e5003b2.png)

Can't scroll past here
![image](https://user-images.githubusercontent.com/16250196/113771013-2710e400-9723-11eb-8d93-95cb8f3894c6.png)

**Comment by thc202** [comment]
What are you scrolling on? Or how?

**Comment by FalcoGer** [comment]
I'm scrolling down the "Sites" tab on the left (as indicated by OP)
I use a touchpad's edge scroll on my laptop (works just fine everywhere else) with the mouse hovering over the list.

**Comment by thc202** [comment]
Thank you.
