### ISSUE TITLE
Filter Sites by Scope

### ISSUE THREAD

**Issue by FalcoGer** [zaproxy/zaproxy#6521]
**Is your feature request related to a problem? Please describe.**
When I set up my browser for proxying, the site map gets polluted by all manners of irrelevant requests. It's frustrating to keep an overview of the domain I'm trying to deal with.

**Describe the solution you'd like**
Filter the Sites by the scope or contexts that I'm working with.

**Describe alternatives you've considered**
Sort Sites by scope/context, so relevant entries are at the top
Hide sites easily with right click -> ignore domain

**Additional context**
Focus on what's important
![image](https://user-images.githubusercontent.com/16250196/113768765-7d305800-9720-11eb-92a8-290afb0b4350.png)

**Would you like to help implementing this feature?**
I don't do the java.

**Comment by kingthorin** [comment]
![image](https://user-images.githubusercontent.com/7570458/113770706-77bb1980-96f0-11eb-9b8b-5755c1dbefcf.png)
