### ISSUE TITLE
Filter for Fuzzer output

### ISSUE THREAD

**Issue by FalcoGer** [zaproxy/zaproxy#6522]
**Is your feature request related to a problem? Please describe.**
I was trying to use the fuzzer to do a directory search. However the fuzzer output is completely unfiltered and there are 99.99999% 404 Not found messages, for example. Or I get the same Error page (200 response code) over and over.

**Describe the solution you'd like**
A filter similar to wfuzz, allowing to filter for changes from a base, filter for return content length, filter for response status code, etc, filter for regex in response headers/body.

**Describe alternatives you've considered**
I couldn't think of anything that makes more sense than a filter.

**Additional context**
How would you find anything important in this mess?
![image](https://user-images.githubusercontent.com/16250196/113769390-3db63b80-9721-11eb-99c3-172e6570e59f.png)

**Would you like to help implementing this feature?**
I don't do the java

**Comment by kingthorin** [comment]
Goto the search tab, enter your criteria, in the location dropdown select "HTTP Fuzz Results". Ex:
![image](https://user-images.githubusercontent.com/7570458/113771199-15164d80-96f1-11eb-97ff-68d3f33efa91.png)

![image](https://user-images.githubusercontent.com/7570458/113771258-24959680-96f1-11eb-92e8-5821822e8a02.png)

**Comment by kingthorin** [comment]
Also you can:
- sort the table by clicking column headings
- export the table (using the export button)
- copy highlighted lines with standard OS copy/paste hotkeys
- add a script to set a custom state (tag) as you’re fuzzing and sort with that
