### ISSUE TITLE
API to save requests and responses as raw text

### ISSUE THREAD

**Issue by FalcoGer** [zaproxy/zaproxy#6523]
**Is your feature request related to a problem? Please describe.**
I wish to write an external program to pass a request file to `sqlmap` using the `-r` parameter. To that end I require the requests file in raw text. The API (http://localhost:8080/JSON/core/view/message/?apikey=[key]&id=[msgid]) however only outputs in JSON, HTML or XML which requires further parsing. On top of that it only outputs both requests and responses together, I am however only interested in the request.

**Describe the solution you'd like**
An API change or addition to get the requests and responses separately and in raw text form (application/octet-stream), headers and body separately and/or combined.

**Describe alternatives you've considered**
An additional parameter for Options/Applications to point to a temporary requests/response file

**Additional context**
No.

**Would you like to help implementing this feature?**
I don't do the java.

**Comment by kingthorin** [comment]
You could invoke sqlmap from within Zap and pass the details you want:
- https://www.zaproxy.org/docs/desktop/addons/invoke-applications/
- https://www.zaproxy.org/docs/desktop/addons/invoke-applications/options/

(I know it's not quite what you're after but it gives you immediate options, vs. waiting for someone to add the feature you're interested in.)

Out of curiosity is `application/octet-stream` a requirement, and if so why? (vs/ `text/plain`)

**Comment by kingthorin** [comment]
Oh and if you grab "Save Raw Message" from the ZAP Marketplace it provides the functionality you're after (I believe).

**Comment by psiinon** [comment]
I'm not keen on us adding "raw" API endpoints unless theres a good reason (like non text data such as the ZAP public cert).
I think they could easily become a mess and too dificult for us to document and maintain.
If you really dont want to parse data then APIs probably arent going to be for you - you can still use the GUI options or scripts.

**Comment by FalcoGer** [comment]
I found a solution in making a python script to fetch the relevant json from the API, build the request and send it off to sqlmap.
I then invoke the python script via 'applications' and provide it the %msgid%. I just wish it were more simple.

Also octet-stream because the request or response could contain raw binary, couldn't it?

**Comment by thc202** [comment]
A Targeted script would make it simpler (or at the very least reduce the "steps" needed).
