### ISSUE TITLE
Use more specific CWE ID for X-Frame-Options alert

### ISSUE THREAD

**Issue by ThunderSon** [zaproxy/zaproxy#6532]
**Describe the bug**

For the header of `X-Frame-Options`, the CWE provided is [CWE 16](https://cwe.mitre.org/data/definitions/16.html), whereas it can better be represented through [CWE 1021](https://cwe.mitre.org/data/definitions/1021.html).

This can take in as well CSP if `frame-ancestors` is set wrong or not set, but I believe there isn't a direct rule for that.

**Software versions**
 - ZAP: Latest, 2.10

**Issue as seen in ZAP**

`X-Frame-Options Header Not Set`:
- Description: "X-Frame-Options header is not included in the HTTP response to protect against 'ClickJacking' attacks."
- CWE ID: 16

**Would you like to help fix this issue?**
Sure

**Comment by kingthorin** [comment]
The current XFO rule does also check if CSP includes frame-ancestors, however it doesn’t analyze the way CSP-FA is configured.

**Comment by ThunderSon** [comment]
I'll leave CSP-FA implementation for another time (or another issue maybe), as it's a different "issue" so to say.
I'll take care of this ASAP.

**Comment by ThunderSon** [comment]
After reviewing netsparker and acunetix, they both mention CWE-693, which still seems generic. Before I implement this, I'd like to take the green light after this.
I see that 1021 is more clear and describes the issue better. If agreed, I'll consider reaching out to the companies about this as well.

**Comment by kingthorin** [comment]
1021 sounds good to me.
