### ISSUE TITLE
CWE 16 Category Shouldn't be Mapped to

### ISSUE THREAD

**Issue by ThunderSon** [zaproxy/zaproxy#6533]
**Describe the bug**
After going over a couple of vulnerabilities reported by ZAP, I noticed the usage of [CWE 16](https://cwe.mitre.org/data/definitions/16.html), which is a category and shouldn't be mapped to as per MITRE's recommendations in that article.

Most of those vulnerabilities should be mapped instead to [693](https://cwe.mitre.org/data/definitions/693) or any other better representative ID.

I believe this is more of an epic, than just a small issue. If someone can help out with planning this out, I can definitely lend a hand. Otherwise it might be too big for just me at the current time.

**Comment by kingthorin** [comment]
![image](https://user-images.githubusercontent.com/7570458/114286240-f8e51a00-9a2a-11eb-8a6d-51303aab7c46.png)
