### ISSUE TITLE
ZAP cannot launch browser on macOS

### ISSUE THREAD

**Issue by walsh72** [zaproxy/zaproxy#6543]
**Describe the bug**
Cannot launch browser from ZAP proxy

**To Reproduce**
in sites bar, right click, open url in browser

**Expected behavior**
browser to be opened

**Screenshots**
![Screenshot 2021-04-14 at 18 16 33](https://user-images.githubusercontent.com/39153598/114747448-24307780-9d51-11eb-8a2e-ec86bc6acfdf.png)
![Screenshot 2021-04-14 at 18 18 22](https://user-images.githubusercontent.com/39153598/114747479-2abeef00-9d51-11eb-919b-a1d0dc46b5b9.png)

**Software versions**
 - ZAP: latest - 2.10.0
 - Add-on: new install, default
 - OS: macOS, latest - 11.2.3 (20D91)
 - Java: 
    openjdk version "11.0.9.1" 2020-11-04 LTS
   OpenJDK Runtime Environment Corretto-11.0.9.12.1 (build 11.0.9.1+12-LTS)
   OpenJDK 64-Bit Server VM Corretto-11.0.9.12.1 (build 11.0.9.1+12-LTS, mixed mode)
 - Browser: Firefox, latest - 87.0(64bit)

**Errors from the zap.log file**
[zap.log](https://github.com/zaproxy/zaproxy/files/6312427/zap.log)

**Additional context**
You guys rock, excellent tool! Keep it this way : )

**Would you like to help fix this issue?**
Busy with other things, but thank you..

**Comment by thc202** [comment]
Could you delete the file `webdrivermacos-release-17.zap` and install the latest from the marketplace?

**Comment by walsh72** [comment]
I found file webdrivermacos-release-17.zap but also webdrivermacos-release-26.zap.
I deleted the first one, then unistalled and installed back webdrivermacos-release-26.zap

Issue still remains: 'open url in browser/firefox' or 'open url in browser/safari' do not work. Just figured out, that 'open url in system browser' works (it is safari).

**Comment by thc202** [comment]
Could you try Quick Start > Manual Explore > Launch Browser ?

**Comment by walsh72** [comment]
Browser launch worked some days ago, OSX security policy update? Accessing one app from another one?

Still the same, this is in my log:
2011 Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
2012 System info: host: 'bird.local', ip: '127.0.0.1', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '1.8.0_275'
2013 Driver info: driver.version: FirefoxDriver
2014 org.openqa.selenium.WebDriverException: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:21536
2015 Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
2016 System info: host: 'bird.local', ip: '127.0.0.1', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '1.8.0_275'
2017 Driver info: driver.version: FirefoxDriver
2018   at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:92) ~[selenium-release-15.3.0.zap:?]
2019   at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552) ~[selenium-release-15.3.0.zap:?]
2020   at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213) ~[selenium-release-15.3.0.zap:?]
2021   at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131) ~[selenium-release-15.3.0.zap:?]
2022   at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:147) ~[selenium-release-15.3.0.zap:?]
2023   at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriverImpl(ExtensionSelenium.java:865) ~[selenium-release-15.3.0.zap:?]
2024   at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriver(ExtensionSelenium.java:785) ~[selenium-release-15.3.0.zap:?]
2025   at org.zaproxy.zap.extension.selenium.internal.BuiltInSingleWebDriverProvider.getWebDriver(BuiltInSingleWebDriverProvider.java:62) ~[selenium-release-15.3.0.zap:?]
2026   at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriverImpl(ExtensionSelenium.java:680) ~[selenium-release-15.3.0.zap:?]
2027   at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriver(ExtensionSelenium.java:548) ~[selenium-release-15.3.0.zap:?]
2028   at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getProxiedBrowser(ExtensionSelenium.java:641) ~[selenium-release-15.3.0.zap:?]
2029   at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getProxiedBrowserByName(ExtensionSelenium.java:605) ~[selenium-release-15.3.0.zap:?]
2030   at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getProxiedBrowserByName(ExtensionSelenium.java:591) ~[selenium-release-15.3.0.zap:?]
2031   at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getProxiedBrowserByName(ExtensionSelenium.java:581) ~[selenium-release-15.3.0.zap:?]
2032   at org.zaproxy.zap.extension.quickstart.launch.ExtensionQuickStartLaunch$2.run(ExtensionQuickStartLaunch.java:224) [quickstart-release-29.zap:?]
2033   at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
2034 Caused by: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:21536

**Comment by thc202** [comment]
Might be that, I'll check if that happens in Catalina.

**Comment by thc202** [comment]
It does, it seems the `geckodriver` bundled does not have the correct arch, still checking why...

**Comment by thc202** [comment]
The latest version of MacOS WebDrivers add-on available in the marketplace addresses this issue.

**Comment by walsh72** [comment]
excellent, thank you!
