### ISSUE TITLE
Make API Scan target option accept also absolute file paths

### ISSUE THREAD

**Issue by jporzuceksfx** [zaproxy/zaproxy#6547]
**Is your feature request related to a problem? Please describe.**
When target `-t` option is used for local files, a relative path to current working directory has to be provided.

**Describe the solution you'd like**
Target options should accept both relative and absolute paths.

**Would you like to help implementing this feature?**
Yup, it's a simple single line change in `zap-api-scan.py`.

**Comment by thc202** [comment]
@jporzuceksfx do you still plan to work on this?
