### ISSUE TITLE
Failed Attack url read time out

### ISSUE THREAD

**Issue by nurulakbartanjung** [zaproxy/zaproxy#6548]
I use docker run for run service zap.sh but returnning error
![gambar](https://user-images.githubusercontent.com/33213081/114990984-4944f780-9ec3-11eb-88b5-3a170cb8b08f.png)
docker run --rm -v $(pwd):/zap/wrk/ owasp/zap2docker-stable zap.sh -cmd -quickurl http://website -quickprogress -quickout /zap/wrk/zap_report.xml

how to solve it?

**Comment by psiinon** [comment]
This is almost certainly a networking problem and not a bug in ZAP.
See if you can access that URL from the docker image using curl and if that doesnt help then ask on the User Group: https://groups.google.com/group/zaproxy-users
