### ISSUE TITLE
SameSite alert is not being raised when Max-Age<(Difference in LocalTimeZone and GMT)

### ISSUE THREAD

**Issue by ag-shr** [zaproxy/zaproxy#6550]
**Describe the bug**
Cookies sent without a SameSite attribute is not raising an alert because the cookie is being treated as expired.
This is happening because of different time zones. The Expiry attribute in the 'Set-Cookie' header is of a 'GMT' time zone and Zap is comparing it with the local time zone. 
So if the difference between the two time zones is greater than the expiry time of the cookie. 
No alert is being raised as the cookie is being treated as expired.

**To Reproduce**
1. Import the spring project (demo.zip) and run it.
2. Go to http://localhost:3000/noAlert while scanning the requests with Zap. Zap will not raise any alert even though the cookie is not expired. (Max age = 300 seconds)
3. Go to http://localhost:3000/alert while scanning the requests with Zap. Zap will raise a alert. (Max age = 24 hours)
4. Check alerts to confirm.

**Expected behavior**
Zap should give out an alert, since SameSite attribute is not present in the 'Set-Cookie' header.

**Software versions**
 - ZAP: 2.10.0
 - Add-on: Passive scanner rules 33.0.0
 - OS: Windows 10
 - Java: 11.0.9
 - Browser: Firefox 87.0
 
**Additional context**
The bug will be recreated using the exact configuration in the project, if the person recreating this has a local time zone in the GMT+ something zone. And conceptually it should be greater than 5 mins, i.e. if local time zone is GMT+00:30, then it is fine but if the local time zone is GMT+00:04 then it won't work without change the max age value accordingly.

**Project file**
[demo.zip](https://github.com/zaproxy/zaproxy/files/6326093/demo.zip)

**Would you like to help fix this issue?**
I would like to try and help fix this issue.
I think it is as simple as replacing 'LocalDateTime' to 'ZonedDateTime' in the isExpired method. (https://github.com/zaproxy/zap-extensions/blob/master/addOns/commonlib/src/main/java/org/zaproxy/addon/commonlib/CookieUtils.java#L222)
More analysis might be needed for this though.

**Comment by ag-shr** [comment]
Hi @thc202 @kingthorin, I had a doubt, in isExpired() method (https://github.com/zaproxy/zap-extensions/blob/master/addOns/commonlib/src/main/java/org/zaproxy/addon/commonlib/CookieUtils.java#L222 ) currently we are using two different formats to parse expiry date from cookie, the first one format("EEE, dd MMM yyyy HH:mm:ss zzz") seems good, I was doubtful about the second one("EEE, dd-MMM-yyyy HH:mm:ss zzz"). It seems that there are formats that should be supported for date/time, none of which matches the second one. 
Source - https://datatracker.ietf.org/doc/html/rfc7231#section-7.1.1.1

Should that be changed as well to include the older formats?

P.S. - I have the code ready to fix this issue, even wrote the test cases that was missing for this method. But am currently waiting for an go ahead from my organization, just to make sure that there isn't any conflict of interest.
So with that in regard, if it is in the best interest to assign this to someone else. Please do so, as I am not sure how long will it take to gain clarity on this. 
Thanks.

**Comment by thc202** [comment]
What's the doubt specifically? That's an older format.

Yes, ideally it should check for more formats.

**Comment by ag-shr** [comment]
Hi, sorry for the late reply. I missed the notification for your message.

Anyways, yeah so RFC 7231 does specify three different formats that one should support for Date. 
My point was that since that particular method has to change for the Zone issue. We can include the check for rest of the date formats as well.

**Comment by thc202** [comment]
I went ahead with a fix, please take a look: zaproxy/zap-extensions#2941.
