### ISSUE TITLE
ZAP Not working (Not Responding CPU Peek)

### ISSUE THREAD

**Issue by benzdmax** [zaproxy/zaproxy#6554]
I'm using ZAP_2.10.0 Not working

How to Resolve this issue

<img width="836" alt="image" src="https://user-images.githubusercontent.com/13346478/115346469-65ee7180-a1da-11eb-9d6b-1b5f17c170a2.png">

<img width="834" alt="image" src="https://user-images.githubusercontent.com/13346478/115346496-6e46ac80-a1da-11eb-9318-355988965a66.png">

**Comment by thc202** [comment]
You need to provide more details. What functionalities are you using? Which OS, Java? Can you provide a thread dump?

**Comment by benzdmax** [comment]
Hi
I use Macbook Big slur 11.2.3 and Kali Linux 2021.1 (Vm Fusion 12.1.1)

Function to use for the issue. I use automate scan. and I click to alert vulnerability after I can't click other menu krub.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/13346478/115349625-48230b80-a1de-11eb-8b54-e24651fa2602.png">

[Spindump.txt](https://github.com/zaproxy/zaproxy/files/6341207/Spindump.txt)

**Comment by thc202** [comment]
Thank you! This is the same as #5791.
