### ISSUE TITLE
During "Automated Scan", login account needs to recognize picture verification code

### ISSUE THREAD

**Issue by RiotGamesU** [zaproxy/zaproxy#6555]
I would like to ask about the picture verification code that needs to be recognized when logging in to the account on the login page during "Automated Scan". How do I log in at this time? Can the user manually enter the verification code when logging in?

**Comment by psiinon** [comment]
Please ask questions on the ZAP User Group: https://groups.google.com/group/zaproxy-users

**Comment by RiotGamesU** [comment]
> Please ask questions on the ZAP User Group: https://groups.google.com/group/zaproxy-users

ok,thanks
