### ISSUE TITLE
we have installed the latest version of bootstrap and JQuery , but we are still scanning for vulnerable JS library issue and suggest that we upgrade to the latest version 

### ISSUE THREAD

**Issue by lynn-liu1130** [zaproxy/zaproxy#6556]
**Describe the bug**
we have installed the latest version( 4.6.0.0) of Bootstrap and JQuery, but we are still scanning for vulnerable JS library issue and suggest that we upgrade to the latest version. 

**To Reproduce**
1. Full scan our project weblink
2. It will inform us of the Bootstrap version is 4.0.0 and the JQuery version is 3.3.1 and suggests that we upgrade to the latest version.  

**Expected behavior**
As we have installed the latest stable version( 4.6.0.). it should scan out the real version.

**Screenshots**
![image](https://user-images.githubusercontent.com/82919672/115486846-0c458000-a28a-11eb-8736-189995fef7fb.png)

**Software versions**
 - ZAP:2.10.0
 - Add-on: 
 - OS: [ Windows 10]
 - Java: 
 - Browser: [chrome  90.0.4430.72  ]

**Comment by kingthorin** [comment]
The evidence in the alerts was literally pulled from the content that passed through ZAP. So it seems you haven’t fully/properly upgraded the libraries.

**Comment by lynn-liu1130** [comment]
Attached the screenshot for your reference, could you give some adivse？
![image](https://user-images.githubusercontent.com/82919672/115534211-23a45d80-a2ca-11eb-86ab-6f1e52073fef.png)

**Comment by psiinon** [comment]
Have a look at the specific request / URL that ZAP is reporting an issue with. Can you find the evidence string in it?

**Comment by kingthorin** [comment]
Jquery-1.10.2 self declares as not 3.6 (per the URL in your screenshot).

Are you starting a new ZAP session? Or were you expecting ZAP to update/remove existing alerts?

**Comment by kingthorin** [comment]
This seems to be working as expected. If you still have an issue feel free to provide specific details, or start a discussion in the [User Group](https://groups.google.com/g/zaproxy-users).
