### ISSUE TITLE
Add/improve evidences on existing scan rules

### ISSUE THREAD

**Issue by DiogoMRSilva** [zaproxy/zaproxy#6563]
**Is your feature request related to a problem? Please describe.**
Some scan rules alerts don't have evidences or are not correctly set. Some of those are very easy.

**Describe the solution you'd like**
Add and fix scan rules evidences.

**Would you like to help implementing this feature?**
Yes, I will submit a PR.

**Comment by psiinon** [comment]
PRs to fix things always much appreciated :)
