### ISSUE TITLE
An error occurred while initialising JavaFX.The response view "Render HTML"will not be available.Make sure that JavaFX is available on your system or JRE/JDK The error was logged.

### ISSUE THREAD

**Issue by RiotGamesU** [zaproxy/zaproxy#6572]
After installing all the plug-ins, it prompts that JavaFX is missing. Install JavaFX according to the tutorial on the JavaFX official website, but the following error is prompted when zap is started:

An error occurred while initialising JavaFX.The response view "Render HTML"will not be available.Make sure that JavaFX is available on your system or JRE/JDK The error was logged.

In terms of Java version, openjdk15.0.1, openjdk15.0.2 and openjdk16.0.1 have been tested, and the same error mentioned above will appear.

**Comment by kingthorin** [comment]
See https://github.com/zaproxy/zaproxy/issues/6339

---

In order yo use the Browser view add-on you have to install JavaFX.

`sudo apt install openjfx` for Ubuntu.

You may also need to set the jfx path (https://openjfx.io/openjfx-docs/#install-javafx):
`export PATH_TO_FX=path/to/javafx/lib`

Per: https://github.com/zaproxy/zaproxy/issues/6339#issuecomment-758173453, you may also need to start ZAP as follows (or edit the shell script to do the same):
`$ java --module-path /usr/share/openjfx/lib/ --add-modules javafx.swing,javafx.web zap.jar`

**Comment by RiotGamesU** [comment]
> See #6339
> 
> In order yo use the Browser view add-on you have to install JavaFX.
> 
> `sudo apt install openjfx` for Ubuntu.
> 
> You may also need to set the jfx path (https://openjfx.io/openjfx-docs/#install-javafx):
> `export PATH_TO_FX=path/to/javafx/lib`
> 
> Per: [#6339 (comment)](https://github.com/zaproxy/zaproxy/issues/6339#issuecomment-758173453), you may also need to start ZAP as follows (or edit the shell script to do the same):
> `$ java --module-path /usr/share/openjfx/lib/ --add-modules javafx.swing,javafx.web zap.jar`

Thank u very very very much
