### ISSUE TITLE
Nested Cookies

### ISSUE THREAD

**Issue by jhowlett96** [zaproxy/zaproxy#6582]
I use nested cookies in my website (e.g. cookie name: cookie, cookie value: x=1&y=2&z=3).

I would like ZAP to be able to inject (XSS and SQLi) into nested cookies. 

Currently I am editing my website so that it doesn't use nested cookies however this isn't perfect as ZAP isn't testing the release version of my website.

Regards,
Jake

**Comment by kingthorin** [comment]
Is there an actual standard for that? (I'm not aware of one and couldn't find anything quickly.)

You could create a scripted variant to use in your scans. Examples & docs here: https://github.com/zaproxy/community-scripts/tree/master/variant

**Comment by psiinon** [comment]
Ah, didnt realise this is what you meant.
So you should be able to do this right now using input vector scripts: https://github.com/zaproxy/community-scripts/tree/master/variant - they define what ZAP attacks.

**Comment by kingthorin** [comment]
ZAP answers now in stereo! 😀  Hahahahaha

![](https://i.imgur.com/zfIck24.gif)

**Comment by jhowlett96** [comment]
I will look into that now, thanks kingthorin and psiinon

**Comment by thc202** [comment]
@jhowlett96 were you able to use the Input Vector script?

**Comment by jhowlett96** [comment]
@thc202 I haven't looked deeply into it as I have already altered my cookie usage for pentesting. I will be eventually implementing nested cookies via a input vector script. 

However from my initial search I couldn't find any good resources on input vector scripts and examples to help me target the cookies. Are there any good places to look for such examples and guidance on input vector scripts?

**Comment by thc202** [comment]
The are other scripts in Community Scripts that show how to handle cookies, e.g.: https://github.com/zaproxy/community-scripts/blob/38e09c8c01a86be615d3c3c8fe4bf60d1a091d41/httpsender/keep-cookies-going.js it really depends on how you want to do that, the same logic applies to the Input Vector script.

**Comment by jhowlett96** [comment]
I just needed a starting place, that should do me nicely @thc202 thank you for following up me request and giving me more guidance.

**Comment by thc202** [comment]
No problem, if you have any question let us know.

**Comment by jhowlett96** [comment]
/**
 * Input Vector script to help Zap attack compound cookies, i.e. cookies that contain multiple parameters
 * Format of a Compound cookie is Classic ASP compliant, i.e. of the form:
 *        <compoundcookie>=<p1name>=<p1value>&<p2name>=<v2value>&... - these cookies should be filtered out to stop ZAP attacking these cookies directly using : "ascan/action/addExcludedParam/?type=4&url=.*&name="
 * where parameter names and values must be URI component encoded.
 */
// gives parameters in the form <compoundcookie>:<p1name>=<p1value> , <compoundcookie>:<p2name>=<p2value> ...
var HtmlParameter = Java.type('org.parosproxy.paros.network.HtmlParameter');
var COOKIE_TYPE   = org.parosproxy.paros.network.HtmlParameter.Type.cookie;

/* List of compound cookies to target */
var compoundCookies = ['cookieName1', 'cookieName2', 'cookieName3', 'cookieName4'];

function parseParameters(helper, msg)
{
  var headers = msg.getRequestHeader();
  var cookies = headers.getCookieParams();
  
//  print('parseParameters: ' + msg.getRequestHeader().getURI().toString());
    
  for(var ci = cookies.iterator(); ci.hasNext(); )
  {
    var ix, cc = ci.next();
    if((ix = compoundCookies.indexOf(cc.getName())) >= 0)
    {
      var ei, pi, pl = cc.getValue().split("&");
//      print("  Splitting: " + compoundCookies[ix]);
      for(pi=0; pi < pl.length; pi++) {
        if((ei=pl[pi].indexOf('=')) > 0) {
          //print("    Var " + decodeURIComponent(pl[pi].substring(0,ei)) + "=" + decodeURIComponent(pl[pi].substring(ei+1)));
          helper.addParamQuery(compoundCookies[ix]+':'+decodeURIComponent(pl[pi].substring(0,ei)),decodeURIComponent(pl[pi].substring(ei+1)));
	   }
      }
    }
  }
}

/* Only one parameter is changed at a time so only one compound cookie to update */
function setParameter(helper, msg, param, value, escaped)
{
  var size = helper.getParamNumber();
  var pos = helper.getCurrentParam().getPosition();
  var ii,di,pn,cn,pf,vv;
  if((pos < size) && ((di = (pn = helper.getParamName(pos)).indexOf(':')) > 0) &&
     (compoundCookies.indexOf((cn = pn.substring(0,di))) >= 0))
  {
    var headers = msg.getRequestHeader();
    var cookies = headers.getCookieParams();
    pf = cn + ':';
    vv = '';
    for(ii=0; ii<size; ii++) {
      if(ii == pos) {
        vv = encodeURIComponent(helper.getParamName(ii).slice(di+1)) + "=" + encodeURIComponent(value) + "&" + vv;
      }
      else if((pn = helper.getParamName(ii)).startsWith(pf))
      {
        vv = encodeURIComponent(pn.slice(di+1)) + "=" + encodeURIComponent(helper.getParamValue(ii)) + "&" + vv;
      }
    }
    /* remove trailing '&' */
    vv = vv.slice(0,-1);
//    print('SetParameter: ' + cn + '=' + vv);
    vv = new HtmlParameter(COOKIE_TYPE,cn,vv);
    for(var ci = cookies.iterator(); ci.hasNext(); ) {
      var cc = ci.next();
      if (cc.getName().equals(cn)) {
        ci.remove();
        break;
      }
    }
    cookies.add(vv);
    msg.getRequestHeader().setCookieParams(cookies);
  }
  else {
    print('CompoundCookie SetParameter Error: Invalid input ' + size + ', ' + pos + ' -> ' + pn);
  }
}


/* Return null to Use default method */
function getLeafName(helper, nodeName, msg) {
	return null;
}

/* Return null to Use default method */
function getTreePath(helper, msg) {
	return null;
}

**Comment by jhowlett96** [comment]
This is the script that I have wrote to handle nested cookies, is this the sort of thing you had in mind?

Please feel free to add to the bank of community scripts if you think others could benefit from it.

Regards,
Jake

**Comment by kingthorin** [comment]
Yes, I haven't tested it at all but that's definitely the kind of thing I was picturing. Thanks for sharing!

**Comment by jhowlett96** [comment]
I have updated the script so that now you can either place into ccList an array of cookie names or you can use a global var named 'CompoundCookies'.

```
/**
 * Input Vector script to help Zap attack compound cookies, i.e. cookies that contain multiple parameters
 * Format of a Compound cookie is Classic ASP compliant, i.e. of the form:
 *        <compoundcookie>=<p1name>=<p1value>&<p2name>=<v2value>&...
 * where parameter names and values must be URI component encoded. Generates parameters in the form:
 *        <compoundcookie>:<p1name>=<p1value>
 *        <compoundcookie>:<p2name>=<p2value>
 *        ...
 * These compound cookies should be filtered out in Active Scan Exclude Param to stop ZAP attacking these cookies directly.
 */
var ScriptVars    = Java.type('org.zaproxy.zap.extension.script.ScriptVars');
var HtmlParameter = Java.type('org.parosproxy.paros.network.HtmlParameter');
var COOKIE_TYPE   = org.parosproxy.paros.network.HtmlParameter.Type.cookie;

/* List of compound cookies to target - either burn in list below (i.e. ccList = [ "<compoundcookie1>", "<compoundcookie2>", ... ]; )
 * or set via 'CompoundCookies' global var as a '&' separated list (i.e. "<compoundcookie1>&<compoundcookie2>&..." ) */
var ccList = [ ];

function parseParameters(helper, msg)
{
  var headers = msg.getRequestHeader();
  var cookies = headers.getCookieParams();
  var ix, ei, pi, pl;
  if(ccList.length == 0)
  {
    if((ei = ScriptVars.getGlobalVar('CompoundCookies')).equals('') || ((ccList = ei.split('&')).length == 0))
    {
      print('CompoundCookie Setup Error: GlobalVar CompoundCookies must be set to \'&\' separated list of compound cookies');
      return;
    }
    //print('CompoundCookie list: ' + ccList);
  }
  //print('parseParameters: ' + msg.getRequestHeader().getURI().toString());
  for(var ci = cookies.iterator(); ci.hasNext(); )
  {
    var cc = ci.next();
    if((ix = ccList.indexOf(cc.getName())) >= 0)
    {
      pl = cc.getValue().split('&');
      //print("  Splitting: " + ccList[ix]);
      for(pi=0; pi < pl.length; pi++) {
        if((ei=pl[pi].indexOf('=')) > 0) {
          //print("    Var " + decodeURIComponent(pl[pi].substring(0,ei)) + "=" + decodeURIComponent(pl[pi].substring(ei+1)));
          helper.addParamQuery(ccList[ix]+':'+decodeURIComponent(pl[pi].substring(0,ei)),decodeURIComponent(pl[pi].substring(ei+1)));
        }
      }
    }
  }
}

/* Only one parameter is changed at a time so only one compound cookie to update */
function setParameter(helper, msg, param, value, escaped)
{
  var size = helper.getParamNumber();
  var pos = helper.getCurrentParam().getPosition();
  var ii,di,pn,cn,pf,vv;
  if((pos < size) && ((di = (pn = helper.getParamName(pos)).indexOf(':')) > 0) &&
     (ccList.indexOf((cn = pn.substring(0,di))) >= 0))
  {
    var headers = msg.getRequestHeader();
    var cookies = headers.getCookieParams();
    pf = cn + ':';
    vv = '';
    for(ii=0; ii<size; ii++) {
      if(ii == pos) {
        vv = encodeURIComponent(helper.getParamName(ii).slice(di+1)) + "=" + encodeURIComponent(value) + "&" + vv;
      }
      else if((pn = helper.getParamName(ii)).startsWith(pf))
      {
        vv = encodeURIComponent(pn.slice(di+1)) + "=" + encodeURIComponent(helper.getParamValue(ii)) + "&" + vv;
      }
    }
    /* remove trailing '&' */
    vv = vv.slice(0,-1);
    //print('SetParameter: ' + cn + '=' + vv);
    vv = new HtmlParameter(COOKIE_TYPE,cn,vv);
    for(var ci = cookies.iterator(); ci.hasNext(); ) {
      var cc = ci.next();
      if (cc.getName().equals(cn)) {
        ci.remove();
        break;
      }
    }
    cookies.add(vv);
    msg.getRequestHeader().setCookieParams(cookies);
  }
  else {
    print('CompoundCookie SetParameter Error: Invalid input ' + size + ', ' + pos + ' -> ' + pn);
  }
}


/* Return null to Use default method */
function getLeafName(helper, nodeName, msg) {
	return null;
}

/* Return null to Use default method */
function getTreePath(helper, msg) {
	return null;
}

```

**Comment by kingthorin** [comment]
Nice work. Could you make a PR for https://github.com/zaproxy/community-scripts ?

Maybe declare variables individually and make the names more meaningful (so that others have an easier time modifying /adapting it).
