### ISSUE TITLE
ZAP view is very zoomed in on high display

### ISSUE THREAD

**Issue by ilambat** [zaproxy/zaproxy#6585]
When trying to launch ZAP 2.10, the view is zoomed in and it's unusable. 

My display settings were: 3840x2160 

I have also tried with 1920 x 1080 with no luck.

![image](https://user-images.githubusercontent.com/54954392/117135226-8e5f9980-ad9e-11eb-9768-31ede18672e6.png)
![image](https://user-images.githubusercontent.com/54954392/117135250-961f3e00-ad9e-11eb-9325-939a1fe2a491.png)

**Comment by psiinon** [comment]
Usually its too zoomed out on high def displays :P 
Have you changed any of the default settings, eg maybe when you were using an older java version?
See https://www.zaproxy.org/faq/how-can-i-run-zap-with-a-high-dpi-display/ but reverse the steps :)

**Comment by thc202** [comment]
Closing, no further feedback.
