### ISSUE TITLE
Info Disclosure false positive vs partial words

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#6589]
The Info Disclosure rule https://github.com/zaproxy/zap-extensions/blob/master/addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/InformationDisclosureSuspiciousCommentsScanRule.java alerts on Juice Shop matching both "query" and "select" when these are part of other words, eg "querySelector". In this case it gets a load of hits in javascript files, which is hardly surprising.
Proposal - we should not match against the words in https://github.com/zaproxy/zap-extensions/blob/master/addOns/pscanrules/src/main/zapHomeFiles/xml/suspicious-comments.txt if they are part of other words, ie have letters immediatelly before and/or after.
Alternative suggestions also appreciated :)

**Comment by kingthorin** [comment]
How about something like (assume this this is the `FIXME` payload and case insensitive regex, pseudo code):
if (contains("fixme") && not (regexMatch("\wfixme\s") or regexMatch("\sfixme\w") or regexMatch("\wfixme\w")

\s is whitespace, \w is word character (alphanum plus underscore)

That should match the first two,  but not last three of:
FIXME
fixme
dosomethingtofixme
fixmesometime
dofixmesometime

**Comment by psiinon** [comment]
But then that wont match a response containing `fixme dosomethingtofixme` will it?
I was thinking we could come up with a reg to match `non-char` `payload` `non-char` ...

**Comment by kingthorin** [comment]
Yes you'd still get a hit for that. I was concerned with ensuring we still allow/catch `=select`, `select:`, `query=`, things like that.

**Comment by kingthorin** [comment]
Agreed, the only thing it doesn't manage is your example: `fixme dosomethingtofixme`, but that's still 90% better.

**Comment by psiinon** [comment]
You sure? It does seem to match that, at least on https://www.regextester.com/

**Comment by kingthorin** [comment]
Sorry, failure to communicate I think. I thought you were originally suggesting it should skip that case (not match it).

I think we're good then with the word boundary idea as a solution.

**Comment by kingthorin** [comment]
I think this is more of an evidence issue, remember evidence is highlighted based on literal string and first match.

The scan rule already uses word boundaries.

**Comment by psiinon** [comment]
Yes, I've checked the Juice Shop results and while it does highlight based on the literal strings the actual evidence is present in all of the pages taking into account word boundries.
