### ISSUE TITLE
Content-Security-Policy: "require-trusted-types-for" is shown as Unrecognised directive-name

### ISSUE THREAD

**Issue by beatquantum** [zaproxy/zaproxy#6602]
The CSP directive "require-trusted-types-for" is official. See link. https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/trusted-types. However, Zaproxy gives a notice "Unrecognised directive-name".

**To Reproduce**
Use the following CSP on an Nginx server.
add_header Content-Security-Policy "default-src 'none'; require-trusted-types-for 'script';";

**Expected behavior**
No notice.

**Software versions**
 - ZAP: 2.10.0
 - OS: Windows 10

**Would you like to help fix this issue?**
Yes, i am happy to run the test again.
![require-trusted-types-for](https://user-images.githubusercontent.com/67234356/118347719-4595a680-b53d-11eb-9933-efad3fbfc363.JPG)

**Comment by thc202** [comment]
That's still a draft though.

**Comment by beatquantum** [comment]
Thanks @thc202 - Google CSP evaluator is already including it and Chrome, Edge, Opera and Android browsers are supporting it. We could change the ZAP notice to say it is a draft instead of unknown.

**Comment by kingthorin** [comment]
I thunk that's on the library that rule uses for evaluating CSP. There is a newer library available but it's a major revision with breaking changes. I don't know if it addresses this or not but am working toward getting it implemented.
