### ISSUE TITLE
Error while attacking web app: getting stuck at 88% and errors in terminal

### ISSUE THREAD

**Issue by ehtec** [zaproxy/zaproxy#6605]
I am testing a webapp with zaproxy (Kali linux, release 2.10 from apt-get). While testing, it gets stuck at some point at 88% and keeps showing a continuous inflow of the following error in terminal:

7349277 [ZAP-ProxyThread-22475] WARN  org.parosproxy.paros.core.proxy.ProxyThread - Failed to write/forward the HTTP response to the client: java.net.SocketException: Broken pipe (Write failed)
 
what am I doing wrong?
Thanks

**Comment by psiinon** [comment]
Please dont raise issues for questions - the ZAP User Group is a much better forum for these: https://groups.google.com/group/zaproxy-users
