### ISSUE TITLE
ZAP complains on duplicate CSP header where there is only one

### ISSUE THREAD

**Issue by omerlh** [zaproxy/zaproxy#6620]
**Describe the bug**
I noticed the following alert while scanning my website with Zap:

```
Passive (10055 - CSP)

The response contained multiple CSP headers, one or more of them contained a report-uri directive and therefore they could not be merged. The first identified header/policy was analyzed.
```

I checked manually and there is only one CSP header on the response so I am not sure why it is happen

**To Reproduce**
I am not sure how to reproduce, I will provide the full request / response via DM

**Expected behavior**
No alert shown 

**Screenshots**

**Software versions**
![image](https://user-images.githubusercontent.com/6730584/119255802-44601b80-bbc6-11eb-95d5-478852537ab0.png)

**Comment by kingthorin** [comment]
I’ll look into this.

Though it should be noted that the rule is moving to a new major version of the library used for CSP analysis and won’t be trying to merge policies anymore so this issue will go away anyway. (That PR is currently open.)

**Comment by kingthorin** [comment]
I've confirmed there is a logic error in the existing rule.

Should be:
```diff
diff --git a/addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ContentSecurityPolicyScanRule.java b/addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ContentSecurityPolicyScanRule.java
index 90b0322..424baea 100644
--- a/addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ContentSecurityPolicyScanRule.java
+++ b/addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ContentSecurityPolicyScanRule.java
@@ -395,7 +395,7 @@
             String policy) {
         String alertName = StringUtils.isEmpty(name) ? getName() : getName() + ": " + name;
         String otherInfo = "";
-        if (hasReportUri) {
+        if (multipleCsp && hasReportUri) {
             otherInfo = Constant.messages.getString(MESSAGE_PREFIX + "otherinfo.nomerge");
         } else if (multipleCsp) {
             otherInfo = Constant.messages.getString(MESSAGE_PREFIX + "otherinfo", policy);
```

I'd like to leave it unfixed and focus on getting https://github.com/zaproxy/zap-extensions/pull/2938 in place. After that PR there will be totally different multiple CSP handling.

**Comment by omerlh** [comment]
Thank you for taking the time to look into it!

**Comment by kingthorin** [comment]
Addressed in: https://github.com/zaproxy/zap-extensions/pull/2938
(Not yet released.)
