### ISSUE TITLE
PII False positive on decimal numbers

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#6639]
Decimal numbers like `52.5702100309281,` trigger the PII scan rule, and they shouldnt.
Example page: https://www.discoverireland.ie/limerick/glin-heritage-trails-knight-s-walk

They could be excluded using a similar check to https://github.com/zaproxy/zap-extensions/blob/master/addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/PiiScanRule.java#L118-L139

cc @hugobarona

**Comment by kingthorin** [comment]
The trouble with this is that we can't/don't know what format the data might take. Ex:
`jsmit52.5702100309281.2211` could be username, cc, expiry.

Note if it was raised it passed a LUHN check, and depending on alert details may have matched IBAN as well.

Note: I'm not saying we shouldn't revise the check, I'm just saying we need to be careful, or link whatever change to Threshold.

**Comment by psiinon** [comment]
@kingthorin completely agree

**Comment by hugobarona** [comment]
@kingthorin maybe you could consider including a confidence value to these rules, and then the user could set the confidence threshold to trigger the rule?

**Comment by subramanian0** [comment]
@psiinon  @kingthorin  : `5702100309281` is the only portion that passes LUHN right? What is the unit of a token here for an HTTPResponse? Can we skip if the token, in this case, `jsmit52.5702100309281.2211` has only numeric characters as it is then most probably just a floating-point number? Or is there a counter PII in other parts of the world? I guess LUHN is a better way than giving the control to the user, the unit of token is here in question. If someone uses each group of a card with a dot, like `5702.1003.09281`,  which would be a false negative here, but we can't try all possible combinations, or if some token `contains` LUHN validated to consider a PII.  I guess while this is in beta, we could ignore floats, add more capability to detect other forms of PII, and as an initial version reduce false positives then decide with giving more search results requiring manual verification.  Feel free to correct.

**Comment by kingthorin** [comment]
Yes it’s only matching that portion of the content, so the challenge is to decide what delimiters etc or char counts on either side to include and what analysis to perform to balance FP/FN/TP/TN outcomes.
