### ISSUE TITLE
Add tool name MetaData to .json results export file

### ISSUE THREAD

**Issue by davewichers** [zaproxy/zaproxy#6640]
The ZAP .xml results export includes:
```
<OWASPZAPReport version="zap version" generated="date/time">
<site name="https://localhost:8443" host="localhost" port="8443" ssl="true">
<alerts> ...
```
But the .json results file drops straight into:  "vulnerabilities": [

with no meta data before that. Can we add meta data at the top similar to the .xml results file, like:

- Tool Name
- Tool Version
- Date Results File Generated

Any other generic metadata you think might be useful to add at the top here. The site info is included in individual findings so not sure if needs to be repeated at the top, as results could span multiple sites, but might be nice as most scans are of individual sites.

**Comment by thc202** [comment]
What was used to generate the ".json" results? The JSON report includes the same info as XML.

**Comment by thc202** [comment]
In any case might be something to merge into #6483.

**Comment by kingthorin** [comment]
Note the current iteration of the reports include version and date. I’ve opened a PR to add a `programName=“OWASP ZAP”` element.

**Comment by thc202** [comment]
The current and previous iterations, that info was already included when the issue was raised. The issue title should be updated to match what is being done.
