### ISSUE TITLE
Hud not working when manually launching firefox

### ISSUE THREAD

**Issue by roflcow2** [zaproxy/zaproxy#6650]
firefox version: Firefox 89.0
Zap version: 2.10.0

When firefox is launched manually the hud displays, but does nothing. Some buttons work like Hiding the hud, but adding to scope, spidering, etc. does nothing. I first noticed this when trying to complete the hud tutorial

Works as should when firefox is launched via zap client

Reproduce:
-set zap local proxy to 127.0.0.1:8080
-set firefox manual proxy to 127.0.0.1:8080
-launch firefox manually
-hud appears
-attempt to add to site to scope via top left button
-nothing

I saw another thread saying to change browser.tabs.documentchannel to false, but I don't have this preference  the closest I have is browser.tabs.documentchannel.parent-controlled and it is set to false by default I tried swapping it to true and I also tried adding the the preference from the other thread manually and setting it to false, but no change.

I can provide more detail is needed

**Comment by psiinon** [comment]
Have you imported the ZAP root CA certificate as per https://www.zaproxy.org/docs/desktop/ui/dialogs/options/dynsslcert/ ?
Can you successfully proxy to an HTTPS site through ZAP without using the HUD?
As far as I'm aware you should not need to change any of the other Firefox prefs.
