### ISSUE TITLE
blank window with tiling window manager

### ISSUE THREAD

**Issue by knassar702** [zaproxy/zaproxy#6665]
hello everyone , im currently using [DWM](https://dwm.suckless.org/) this a tiling window manager when run zaproxy starts with blank screen

![screenshot-FZsLNH8sAbly3](https://user-images.githubusercontent.com/45688522/124339007-5660b100-dbab-11eb-8ecb-870281c8477d.png)

for fix that add this line to `zap.sh` file

```
export _JAVA_AWT_WM_NONREPARENTING=1
```
* https://github.com/swaywm/sway/issues/595

best regards
@knassar702

**Comment by kingthorin** [comment]
Thanks this is covered in the reference our FAQ refers to: https://www.zaproxy.org/faq/why-am-i-getting-blank-zap-windows-on-linux/

**Comment by knassar702** [comment]
hi @kingthorin , why don't we just add this to `zap.sh` file ?

**Comment by psiinon** [comment]
@knassar702 add what to the zap.sg file? That FAQ links to a page containing a set of suggestions. Which one(s) do you think we should be addins?

**Comment by psiinon** [comment]
Oh, the export you mentioned above ;) I dont have a problem with that, as long as it doesnt cause any other problems. Submit a PR?

**Comment by knassar702** [comment]
@psiinon 
Done :D
