### ISSUE TITLE
OpenAPI add-on misconverting OPTIONS endpoints

### ISSUE THREAD

**Issue by naggingant** [zaproxy/zaproxy#6666]
**Describe the bug**
Hello, community!
The issue is when I import an OpenAPI definition with some endpoints that support OPTIONS operation, the resulting endpoint in the ZAP session has **OPTION** method instead, without the last S

**To Reproduce**
1. Install OpenAPI Support add-on
2. Start a session
3. From the menu, import an OpenAPI definition, with content like the below
4. See under Sites tree that the endpoint has method `OPTION`

```json
{
  "openapi": "3.0.0",
  "info": {
    "title": "Example",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://example.com"
    }
  ],
  "paths": {
      "/resource": {
          "options": {
              "responses": {}
          }
      }
  }
}

```

**Expected behavior**
The converted endpoint should have as the method `OPTIONS`

**Screenshots**
![repro](https://user-images.githubusercontent.com/20988826/124445838-dc9f1200-ddba-11eb-87ad-2970f43a33a1.png)

**Software versions**
 - ZAP: 2.10.0
 - Add-on: OpenAPI Support 19.0.0
 - OS: Arch Linux
 - Java: OpenJDK 16.0.1
 - Browser: N/A

**Errors from the zap.log file**
None

**Additional context**
None

**Would you like to help fix this issue?**
A quick look at the source code instantly gave me a hint to fix this line and its references:
https://github.com/zaproxy/zap-extensions/blob/93ca159709c1c511d68dcbc249b462dcb0d13368/addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/network/RequestMethod.java#L26

I can definitely work on a PR, if this isn't any problem!

**Comment by thc202** [comment]
Assigned.
