### ISSUE TITLE
NoClassDefFoundError in CacheableScanRule

### ISSUE THREAD

**Issue by MichaelVetter** [zaproxy/zaproxy#6674]
We get a NoClassDefFoundError in CacheableScanRule when we run ZAP with the zap-maven-plugin. It seems to be a classpath issue because the required class HttpDateUtils is present in the latest version (1.4.0) of the installed commonlib addon.

**Errors from the zap.log file**
3257821 [ZAP-PassiveScanner] ERROR org.zaproxy.zap.extension.pscan.PassiveScanThread - Scanner Content Cacheability failed on record 1622 from History table: GET http://....
java.lang.NoClassDefFoundError: org/zaproxy/addon/commonlib/http/HttpDateUtils
	at org.zaproxy.zap.extension.pscanrulesAlpha.CacheableScanRule.parseDate(CacheableScanRule.java:705) ~[?:?]
	at org.zaproxy.zap.extension.pscanrulesAlpha.CacheableScanRule.scanHttpResponseReceive(CacheableScanRule.java:547) ~[?:?]
	at org.zaproxy.zap.extension.pscan.PassiveScanThread.run(PassiveScanThread.java:227) [zap-2.10.0.jar:2.10.0]

We do not get the error with all applications that we test. It seems to occur only under certain conditions.
HttpDateUtils was also added to another rule (SessionFixationScanRule) that does not throws this error. Maybe the relevant code lines are not used in our case.

**Software versions**
 - ZAP: OWASP ZAP 2.10.0
 - Add-on: "Finished installing new addon pscanrulesAlpha v32.0.0"
 - OS: Windows Server 2008 R2
 - Java: openjdk version 1.8.0_232
 - Browser:  firefox

**Comment by thc202** [comment]
The Active scanner rules (beta) add-on does not have this issue.
