### ISSUE TITLE
Baseline Scan with Automation Framework not support with OpenShift Security Context

### ISSUE THREAD

**Issue by Xaseron** [zaproxy/zaproxy#6677]
**Describe the bug**
We are using Jenkins to dynamically spawn Jenkins Agent on Kubernetes/OpenShit to run CI/CD and tests.
Openshit has a "Security" Feature that gives a random UserId on the start of the Container/Pod.
This random user has no write access to `/zap/`. The automation framework fails:
```
 2021-07-07 12:29:03,718 Could not find custom hooks file at /var/lib/jenkins/jobs/SDM/SockShop_Deploy/front-end/master/39/.zap_hooks.py 
 2021-07-07 12:29:03,718 Trigger hook: cli_opts, args: 1
 2021-07-07 12:29:03,719 Using port: 37244
 Using the Automation Framework
 Traceback (most recent call last):
   File "/zap/zap-baseline.py", line 629, in <module>
     main(sys.argv[1:])
   File "/zap/zap-baseline.py", line 340, in main
     with open(yaml_file, 'w') as yf:
 PermissionError: [Errno 13] Permission denied: '/zap/zap.yaml'
```
Zap already uses a custom dir `/zap/work` which we are mounting into the container.
Please consider writing everyting directly into this directory.

**To Reproduce**
1. Use OpenShit
2. Start pod with zap
3. Try to run a baseline scan without `--autooff`

**Expected behavior**
zap-baseline.py writes everythin directly to `/zap/wrk`

**Software versions**
 - ZAP: owasp/zap2docker-live:latest

**Additional context**
excerpt from the pod:
```yaml
apiVersion: "v1"
kind: "Pod"
spec:
  containers:
    - command:
        - "cat"
      image: "docker.artifactory.example.com/owasp/zap2docker-live"
      imagePullPolicy: "Always"
      name: "zaproxy"
      resources:
        limits:
          cpu: "250m"
          memory: "1000Mi"
        requests:
          cpu: "50m"
          memory: "100Mi"
      tty: true
      volumeMounts:
        - mountPath: "/zap/wrk"
          name: "zap-volume"
          readOnly: false
        - mountPath: "/var/lib/jenkins"
          name: "workspace-volume"
          readOnly: false
      workingDir: "/var/lib/jenkins"
```

**Would you like to help fix this issue?**
I can help testing a fix on OpenShit3.

**Comment by psiinon** [comment]
We cannot currently write everything to `/zap/wrk` as there is no guarantee that the user has mounted a directory to it - and by default they wont.
We need to write the zap-yaml file somewhere. How can we tell where to write it in all cases, not just this one?

**Comment by psiinon** [comment]
Admittedly we could use `/zap/wrk` if its available and if not then use `/zap` ...

**Comment by kingthorin** [comment]
>  We need to write the zap-yaml file somewhere. How can we tell where to write it in all cases, not just this one?

The system's default `temp` dir?

**Comment by Xaseron** [comment]
Alternativly you could give write access to others in `/zap`

**Comment by psiinon** [comment]
Allow any user to write to `/zap`? - that doesnt feel right :/

**Comment by psiinon** [comment]
Obvious solution ... use the users home dir, we must have write access to that as its where the ZAP files are written to :D

**Comment by Xaseron** [comment]
The user generated by OpenShift doesn't have a home dir. But i can set the `HOME` environment variable in my Jenkins pipeline. That would work for me.

**Comment by psiinon** [comment]
Thats good, esp as I've just implemented that fix :D
