### ISSUE TITLE
Could you please tell me where can I change the session save path? could I run the zap scan with one more application at the same time？

### ISSUE THREAD

**Issue by lynn-liu1130** [zaproxy/zaproxy#6680]
Hi,

I have some questions that I want to add here.

The sessions are saved in the C disk by default. how can I change the save path in D disk? 
Will sessions keep accumulating here? For example, if I run 2 scans for a application, will the 2 session records be stored here cumulatively?

![333](https://user-images.githubusercontent.com/82919672/125017535-eb7d1180-e0a5-11eb-98c4-2848e21a0eb0.PNG)

**Comment by kingthorin** [comment]
Please don't ask questions as issues - the [ZAP User Group]( https://groups.google.com/group/zaproxy-users) is a much better place for questions.
