### ISSUE TITLE
The importUrl api for open api on ZAP API UI always return {"importUrl":[]}

### ISSUE THREAD

**Issue by cjt0226** [zaproxy/zaproxy#6682]
**Describe the bug**
The importUrl api for open api on ZAP API UI always return {"importUrl":[]}

**To Reproduce**
1. execute "docker run --name zap_webswing -u zap -p 8080:8080 -p 8090:8090 -i owasp/zap2docker-stable:2.10.0 zap-webswing.sh"
2. access "http://localhost:8080/zap/"
3. Disable the api key: Tool -> options -> API -> Select "Disable the API key" -> OK
4. execute "docker exec -it zap_webswing /bin/bash"
5. execute "curl http://localhost:8090/JSON/openapi/action/importUrl/?url=https://petstore.swagger.io/v2/swagger.json"

**Expected behavior**
The importUrl should be a url list. But the actual return is {"importUrl":[]}

**Screenshots**
![WX20210710-192932](https://user-images.githubusercontent.com/24307110/125161511-63862d00-e1b5-11eb-80f6-675c1dae44aa.png)

**Software versions**
 - ZAP: 2.10.0

**Errors from the zap.log file**

**Additional context**
ZAP API UI also get {"importUrl":[]}
You can access and try via http://localhost:8090/UI/openapi/action/importUrl/

**Would you like to help fix this issue?**
I'd like to try and help fix this issue.

**Comment by kingthorin** [comment]
The parameter value needs to be URL rncoded to be sent/parsed properly.

**Comment by thc202** [comment]
That does not return a URL list but the warns/errors while importing.

**Comment by cjt0226** [comment]
> That does not return a URL list but the warns/errors while importing.

Does that mean the empty list is right without warns/error. So the urls has been imported, but which api to scan the urls?  Thanks for your response.

**Comment by kingthorin** [comment]
Yes, that’s correct.

See www.zaproxy.org/docs/api
