### ISSUE TITLE
alertFilter: Add apply API endpoint

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#6688]
Per discussion in: https://github.com/zaproxy/zaproxy/issues/6686

The alertFilter add-on API should have an `apply` endpoint in order to apply filters to existing alerts after they've been created.

**Comment by thc202** [comment]
Isn't this the same issue as 6686?

**Comment by kingthorin** [comment]
No, 6686 is a problem with setting them (in advance) then having them apply and report properly. This is just for the addition of the endpoint to apply them to existing alerts.
[At least that's the conclusion I reached... could be wrong.]

**Comment by thc202** [comment]
Maybe.

**Comment by thc202** [comment]
Seems there's already #5966.
