### ISSUE TITLE
Attack Surface Detector puts in extra forwardslash

### ISSUE THREAD

**Issue by rlgordey** [zaproxy/zaproxy#6696]
Url https://localhost:44356/api/Header/GetLogo gets added as https://localhost:44356//api/Header/GetLogo when I Import Endpoints From Source.

**Comment by kingthorin** [comment]
Please re-report via: https://github.com/secdec/attack-surface-detector-zap

ASD isn’t maintained by the core team.

**Comment by kingthorin** [comment]
Thanks @rlgordey.

https://github.com/secdec/attack-surface-detector-zap/issues/23
