### ISSUE TITLE
PII Disclosure false positive in SVG image

### ISSUE THREAD

**Issue by mig5** [zaproxy/zaproxy#6697]
**Describe the bug**

In https://github.com/zaproxy/zaproxy/issues/6288 and the corresponding PR https://github.com/zaproxy/zap-extensions/pull/2825 , you added rules to skip PII Disclosure false positives on CSS files.

I have just experienced the same issue, but in an SVG image.

**To Reproduce**

Run a scan against 	https://mydex.org/resources/papers/AchievingTransformationAtScale/mydex-ecosystem.svg (I am using owasp/zap2docker-live Docker image)

**Expected behavior**

The string '5798064304462212' and '4749835958005446' ought not to be detected as credit cards in the above SVG because the real values in the SVG are actually this:

```
747.5798064304462 212.30854248687663
```

```
871.4749835958005 446.74815452755905
```

Given that part of the matching string begins in a new set of digits beyond whitespace, along with decimal points, I don't think that this should be considered a match (although I understand that spaces are common in credit card number representation, but decimal points are not).

It seems to me that, like CSS, it seems unlikely that an SVG image would contain a credit card, but this might be disputable.

**Screenshots**

![Screenshot_2021-07-20_09-46-21](https://user-images.githubusercontent.com/99173/126241592-43ed5993-f527-4f1a-8cb2-0953cf15d5ea.png)

**Software versions**
 - ZAP: (Docker) owasp/zap2docker-live:latest Digest:sha256:ab4ca81362d9003efa9db59674b2bb4b401268bc6084730c028a63531b7fc046
 - OS: Ubuntu 18.04

**Would you like to help fix this issue?**

Sorry, I can't help fix this issue.

**Comment by kingthorin** [comment]
Related: https://github.com/zaproxy/zaproxy/issues/6639

**Comment by thc202** [comment]
Worth noting that this is fixed only with weekly/2.11.0.

**Comment by kingthorin** [comment]
It should be >80% or as-is since on responses the isImage check just looks for “image” in content-type. The only cases missed will be SVGs served with a non-standard content-type

**Comment by thc202** [comment]
True, was focusing just on the request part.
