### ISSUE TITLE
[help required] Generate HTML or PDF report from JSON

### ISSUE THREAD

**Issue by vishallanke** [zaproxy/zaproxy#6701]
Is there a way where I can generate HTML or any PDF report if I have ZAP JSON Files ?

**Comment by kingthorin** [comment]
I'm sure you can knock together some python to manipulate it however you like. However, that's not something that's facilitated by ZAP.

Please don't ask questions as issues - the [ZAP User Group]( https://groups.google.com/group/zaproxy-users) is a much better place for questions.
