### ISSUE TITLE
ZAP docker full scan - does it include ZAP API scan as well

### ISSUE THREAD

**Issue by bhuvi11** [zaproxy/zaproxy#6704]
Hello Team,

I see three different images for ZAP
1 ) ZAP baseline
2) ZAP full scan
3) ZAP API scan

Should we seperately use ZAP API image to scan APIs or is it covered in ZAP FULL Scan ?? 

Ideally FUll should cover API scan as well right ?

Please hlpe me on this.

Thanks in advance

**Comment by psiinon** [comment]
Please dont ask questions as issues - the ZAP User Group is a much better forum for them: https://groups.google.com/group/zaproxy-users

**Comment by bhuvi11** [comment]
I am not able to access the user group, that's why posted it as a question.
Can someone please help me?

**Comment by psiinon** [comment]
For info - this was followed up on IRC.
