### ISSUE TITLE
upstream proxy support in daemon mode / dockerized headless scans

### ISSUE THREAD

**Issue by dogasantos** [zaproxy/zaproxy#6707]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
just add --upstream-proxy 

Thanks

**Comment by kingthorin** [comment]
Upstream proxies can be set via the API.

**Comment by thc202** [comment]
And the command line (`-config` arguments).

**Comment by shanisma** [comment]
hi @dogasantos  try something like that `zap-cli -v start --start-options '-config api.disablekey=true -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true -config connection.proxyChain.enabled=true -config connection.proxyChain.hostName=<HOST> -config connection.proxyChain.port=<PORT>'`

**Comment by dogasantos** [comment]
thanks!!! It worked!
