### ISSUE TITLE
ZAP crash (on Kali, OpenJDK 11) consistent -> simple automated scan -> result window -> boom

### ISSUE THREAD

**Issue by norandom** [zaproxy/zaproxy#6710]
**Describe the bug**

ZAP crashes on Linux (Kali, Arch) when the results of an automated scan are being checked.

**To Reproduce**

https://www.youtube.com/watch?v=u3XJbCNWGrg 

1. Go to 'automated scan' -> enter URL
2. Click on 'attack'
3. Scroll down to 'results'
4. Experience a hanging application

**Expected behavior**

The application cannot be used. Breaking issue.

**Screenshots**

See video

**Software versions**
 - ZAP: [2.10.0]
 - Add-on: /
 - OS: [Kali Linux, Arch Linux]
 - Java: [Found Java version 11.0.11
Available memory: 1951 MB
Using JVM args: -Xmx487m
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
831 [main] INFO  org.zaproxy.zap.GuiBootstrap - OWASP ZAP 2.10.0 started 27/07/2021, 05:50:18 with home /home/kali/.ZAP/
]
 - Browser: /

**Errors from the zap.log file**

```
2021-07-27 05:50:54,325 [AWT-EventQueue-0] INFO  ENGINE - dataFileCache commit start
2021-07-27 05:50:54,326 [AWT-EventQueue-0] INFO  ENGINE - dataFileCache commit end
2021-07-27 05:50:54,328 [AWT-EventQueue-0] INFO  ENGINE - Database closed
2021-07-27 05:50:54,479 [AWT-EventQueue-0] INFO  ENGINE - dataFileCache open start
2021-07-27 05:50:54,480 [AWT-EventQueue-0] INFO  ENGINE - dataFileCache commit start
2021-07-27 05:50:54,481 [AWT-EventQueue-0] INFO  ENGINE - dataFileCache commit end
2021-07-27 05:50:54,481 [AWT-EventQueue-0] INFO  ENGINE - dataFileCache open end
```

**Additional context**

Also tested with the official installer. 

**Would you like to help fix this issue?**

Sure.

**Comment by thc202** [comment]
Is this a JRE crash?

**Comment by norandom** [comment]
No, it's a crash of ZAP. It crashes when the results are opened.

**Comment by kingthorin** [comment]
After watching the video it’s important to be clear a hang is not a crash. I believe you’re encountering: https://github.com/zaproxy/zaproxy/issues/5791

**Comment by norandom** [comment]
Yes, disabling the Syntax Highlight plugin resolves the hang situation as a workaround. Maybe it should be removed, because it's difficult to investigate the root cause here as a user.

**Comment by kingthorin** [comment]
Closing as duplicate.
