### ISSUE TITLE
Allow to regenerate expired certificate from warning dialogue

### ISSUE THREAD

**Issue by TNTBOMBOM** [zaproxy/zaproxy#6712]
Add "Regenerate Now" button, per: https://github.com/zaproxy/zaproxy/issues/6712#issuecomment-888866435
(and maybe an "Ignore" button?)

---

**Describe the bug**
Error message showing whenever i open zaproxy in kali (check the screenshot)

**To Reproduce**
1. Go to zaproxy icon
2. Open it

**Expected behavior**
No error

**Screenshots**

![rootcert](https://user-images.githubusercontent.com/11895339/127371962-b27de1a2-b1d8-4f01-a3c6-fa4708b04a41.png)

**Software versions**
 - ZAP: 2.10.0-0kali2
 - Add-on: N/A
 - OS: Kali 
 - Java: openjdk version 11
 - Browser: Firefox 78.12

**Comment by thc202** [comment]
As the dialogue says, you should regenerate it.

**Comment by TNTBOMBOM** [comment]
> As the dialogue says, you should regenerate it.

Shouldnt that be instructed from zap as well (link,video..) if not fixed through an update?

**Comment by kingthorin** [comment]
The dialog in your screenshot (from ZAP) instructs you to regenerate it. It isn't fixed via update because it's unique to every install.

Instructions are here: https://www.zaproxy.org/docs/desktop/ui/dialogs/options/dynsslcert/ and also in ZAP's help if you need them.

**Comment by TNTBOMBOM** [comment]
At least make it clear to the user how to generate the certificate at the first place (in that wiki it only show how to import/install it within firefox unless i missed that): 

Here are some screenshots might be useful to use: (you can change the text to whatever you like)

- Open zaproxy go to Tools -> Options..

![ca1](https://user-images.githubusercontent.com/11895339/127384813-1b8c5c7a-f148-442f-b574-170bf81eec39.png)

- On the left side scroll down to Dynamic SSL certificate

![ca2](https://user-images.githubusercontent.com/11895339/127385041-6c7824a7-d1c5-45a5-900c-ecf0010ba9b2.png)

- Generate new certificate and if you press on view it will show you the certificate details: 

![ca3](https://user-images.githubusercontent.com/11895339/127385235-ef4f242b-9869-42f0-b0ba-c0d449e2e195.png)

(you can add this image to https://www.zaproxy.org/docs/desktop/ui/dialogs/options/dynsslcert/#generate)

- Close certificate details and press on save

(the rest of the wiki explain how to import the certificate)

**Comment by psiinon** [comment]
I would not have a problem with a "Regenerate Now" button (or similar) on that dialog which opens up the relevant dialog - that way a user will be in the right place to export the cert.
Thoughts @thc202 @kingthorin ?

**Comment by thc202** [comment]
Sounds good to me.

**Comment by kingthorin** [comment]
Ya sure, that’s be fine.

**Comment by thc202** [comment]
Title updated accordingly (feel free to tweak).
