### ISSUE TITLE
how can add custom wordlist in zap actinve scan

### ISSUE THREAD

**Issue by RAVIPRAJ** [zaproxy/zaproxy#6721]
i want to scan 100 post and get request with custom wordlists 
i want to add custom wordlists in zap active scan it is possible to add them

**Comment by kingthorin** [comment]
Please don't ask questions as issues - the [ZAP User Group]( https://groups.google.com/group/zaproxy-users) is a much better place for questions.

---

This is something you'd do with the [Fuzzer](https://www.zaproxy.org/docs/desktop/addons/fuzzer/) or [Forced Browse](https://www.zaproxy.org/docs/desktop/addons/forced-browse/) functionality not Active Scan. (Unless you specifically mean lists of files/URLs to try in which case you could use Custom Payloads for the [Hidden File Finder](https://www.zaproxy.org/docs/desktop/addons/active-scan-rules-beta/#hidden-file-finder) scan rule.)
