### ISSUE TITLE
ZAP alertsSummary is not equal to report.html

### ISSUE THREAD

**Issue by wochicheng** [zaproxy/zaproxy#6729]
**Describe the bug**
After using the ascan API to scan the `http://testphp.vulnweb.com/`,then i want to check the results.but i find that the alert api's results is equal to report api'result

**Expected behavior**
i want to know which one of them is correct
**Screenshots**
![image](https://user-images.githubusercontent.com/62383904/128659134-199919ba-ed20-4fee-8bf0-68b5b45bbff0.png)
![image](https://user-images.githubusercontent.com/62383904/128659159-de10188a-3344-456d-bed5-16f573f6f493.png)
![image](https://user-images.githubusercontent.com/62383904/128659258-dc57b309-fc92-4b78-87a2-7b7f1e355a1b.png)

**Software versions**
 - ZAP: [2.10.0]
 - OS: [ Windows 10]
 - Java: [openjdk version "1.8.0_231"]
 - Browser: [edge  92.0.902.62)]

**Comment by psiinon** [comment]
They can both be correct :)
They are measuring different things, but someone will need to dig into the code to see exactly what they are doing...

**Comment by kingthorin** [comment]
Closing per previous comment.
