### ISSUE TITLE
Cross-Domain Misconfiguration Alert reference takes to a 404 not found page on hpenterprisesecurity

### ISSUE THREAD

**Issue by securestep9** [zaproxy/zaproxy#6731]
**Describe the bug**
Cross-Domain Misconfiguration Alert reference link is pointing at:

http://www.hpenterprisesecurity.com/vulncat/en/vulncat/vb/html5_overly_permissive_cors_policy.html

which is 404 (link outdated due to Fortify split from hpenterprisesecurity)
**To Reproduce**
1. Open any alert on Cross-Domain Misconfiguration in HUD or ZAP UI
2. Click on 
3. Scroll down to Reference, and click  on the link

**Expected behavior**
A webpage containing a reference of CORS misconfiguration

**Screenshots**
![Screen Shot 2021-08-10 at 11 51 23](https://user-images.githubusercontent.com/20112179/128855093-f40b5fc4-58ae-4b7f-a8cc-18494f9e0dcb.png) 
![Screen Shot 2021-08-10 at 11 57 21](https://user-images.githubusercontent.com/20112179/128855226-c046072a-d66f-4c0f-afb8-8590bb9d141c.png)

**Software versions**
 - ZAP: 2.10.0
 - OS: Cross-platofrm jar
 -  Java:  irrelevant
 - Browser: irrelevant

**Would you like to help fix this issue?**
yes - the link should go to: https://vulncat.fortify.com/en/detail?id=desc.config.dotnet.html5_overly_permissive_cors_policy

**Comment by securestep9** [comment]
looks like this is linked to #5364

**Comment by kingthorin** [comment]
https://github.com/zaproxy/zap-extensions/blob/23cc30d50c715c812b33a861ee5ad1cda30ce79b/addOns/pscanrules/src/main/resources/org/zaproxy/zap/extension/pscanrules/resources/Messages.properties#L42
