### ISSUE TITLE
SOCKS proxy Port field bug in GUI

### ISSUE THREAD

**Issue by d-lan2** [zaproxy/zaproxy#6732]
**Describe the bug**
The GUI does not allow the SOCKS Proxy: Port input to be written to.
Specifying the SOCKS Proxy port via Config.xml causes scanning error.

**To Reproduce**
I am trying to use the SOCKS proxy feature of OWASP ZAP and the first problem is:
within the GUI under Tools > Options > Connection > SOCKS Proxy
The application allows me to enable the SOCKS Proxy checkbox and specify the Host via input field but I unable to write to the Port input field, it seems to be disabled. It may be justified or it may be a bug with the GUI I am not too sure.

**Comment by kingthorin** [comment]
Are you using the arrows or trying to type?

What OS?
What version of Java?
What Look & Feel?
https://www.zaproxy.org/docs/desktop/ui/tlmenu/help/#support-info

**Comment by thc202** [comment]
Could you provide more details?

**Comment by thc202** [comment]
Closing, not enough details. Feel free to reopen or leave a comment.

**Comment by rayjolt** [comment]
I ran across this same bug today. Here's my support info:

```
OWASP ZAP
Version: 2.11.0
---
Installed Add-ons: [[id=alertFilters, version=13.0.0],
[id=ascanrules, version=41.0.0], [id=automation,
version=0.8.0], [id=bruteforce, version=11.0.0],
[id=commonlib, version=1.5.0], [id=custompayloads,
version=0.11.0], [id=diff, version=11.0.0],
[id=directorylistv1, version=5.0.0], [id=domxss,
version=11.0.0], [id=encoder, version=0.6.0],
[id=formhandler, version=4.0.0], [id=fuzz, version=13.5.0],
[id=gettingStarted, version=13.0.0], [id=graaljs,
version=0.2.0], [id=graphql, version=0.7.0], [id=help,
version=12.0.0], [id=hud, version=0.13.0], [id=importurls,
version=8.0.0], [id=invoke, version=11.0.0], [id=oast,
version=0.5.0], [id=onlineMenu, version=9.0.0], [id=openapi,
version=23.0.0], [id=pscanrules, version=36.0.0],
[id=quickstart, version=30.0.0], [id=replacer,
version=9.0.0], [id=reports, version=0.9.1], [id=retest,
version=0.2.0], [id=retire, version=0.9.0], [id=reveal,
version=4.0.0], [id=saverawmessage, version=6.0.0],
[id=savexmlmessage, version=0.2.0], [id=scripts,
version=29.0.0], [id=selenium, version=15.4.0], [id=soap,
version=11.0.0], [id=spiderAjax, version=23.7.0], [id=tips,
version=9.0.0], [id=webdriverlinux, version=33.0.0],
[id=websocket, version=24.0.0], [id=zest, version=35.0.0]]
---
Operating System: Linux
Java Version: Debian 13.0.5.1
System's Locale: en_GB
Display Locale: en_GB
Format Locale: en_GB
ZAP Home Directory: /home/me/.ZAP/
ZAP Installation Directory: /usr/share/zaproxy/./
Look and Feel: FlatLaf Light (com.formdev.flatlaf.FlatLightLaf)
```
Here's a screenshot: ![zap_options_connection_screen](https://user-images.githubusercontent.com/5244112/142725145-abdcc3a3-1b35-4a7d-8b5f-22d6f36b2c84.png)

The behaviour is the same as described by the OP. I can check the Enabled checkbox for the SOCKS Proxy section, and I can edit the Host text box. However, I cannot edit the Port text box. The Port text box looks like it is enabled, but if you try to type anything into it no characters are displayed.

**Comment by thc202** [comment]
Could you expand the dialogue to show the whole port field?

**Comment by rayjolt** [comment]
Aha, that's the issue. The important part wasn't being displayed!

![zap_options_connection_screen_wide](https://user-images.githubusercontent.com/5244112/142725556-bf04fb12-53d7-41b0-adbf-2d0f7c19ebbe.png)

I didn't notice the horizontal scrollbar, and didn't think to check for one. When I made the options window wider, the port number revealed itself, as you can see in the screenshot.

The first screenshot I posted is the default width of the options window - I hadn't changed that since installing ZAP. I'm not sure why the default width is one that causes horizontal scroll, but if that could be adjusted so that horizontal scroll is not necessary it would probably be less likely to trip up unwary users such as myself. Thanks for pointing out the issue. :)
