### ISSUE TITLE
We want your feedback overflows bounding box

### ISSUE THREAD

**Issue by jsoref** [zaproxy/zaproxy#6734]
**Describe the bug**

**To Reproduce**
1. Install 2.10.0
2. Launch it
3. Accept defaults for new project
4. Apply Add-on updates
5. Close add-on manager dialog
6. See red box running through `We`
7. See Red box clipped on right side as well
8. The labels for the three buttons above are also clipped, which is odd. -- Especially given that there's no way to scroll the rest of the content into view

**Expected behavior**
* Text shouldn't run outside of boxes and boxes shouldn't run out of viewport laterally w/o a scrollbar (and this doesn't want a scrollbar).
* Clipped content should be viewable by scrolling or dismissing clipping objects

**Screenshots**
![image](https://user-images.githubusercontent.com/2119212/128912502-f3ae6b0b-6701-49cd-ae22-9404f63dbb85.png)

**Software versions**
 - ZAP: 2.10.0
 - Add-on: ?
 - OS: macOS Big Sur 11.5.1
 - Java: (unknown)
 - Browser: 

**Errors from the zap.log file**

**Additional context**
After first launch

**Would you like to help fix this issue?**

**Comment by psiinon** [comment]
Resize the window so that its big enough :)
Or change the ZAP scaling so that everything is smaller - you can do that via Options / Display / General Font / Font size
Its hard creating GUIs that work well for a very wide range of display sizes. There will be a limit to what we can cope with.
