### ISSUE TITLE
File>Open Recent>

### ISSUE THREAD

**Issue by jsoref** [zaproxy/zaproxy#6735]
**Is your feature request related to a problem? Please describe.**
I've recently opened a session, and then I needed to restart, I'd like to be able to easily reopen the session

**Describe the solution you'd like**
File>Open Recent>...

**Describe alternatives you've considered**
One could have a start screen that shows recently opened files (VSCode and friends tend to have this, but they also have file>open recent)

**Additional context**
![image](https://user-images.githubusercontent.com/2119212/128938008-8619862b-6dac-487f-a08c-b086204f195c.png)

**Would you like to help implementing this feature?**

**Comment by psiinon** [comment]
Makes sense, and should not be too hard to implement :)

**Comment by jini0x** [comment]
Hi team, I would like to add this feature as my first issue.

**Comment by psiinon** [comment]
@jini0x assigned!
If you have any questions abou tthis issue then just ask them here :)
