### ISSUE TITLE
Support turning off show evidence highlight

### ISSUE THREAD

**Issue by jsoref** [zaproxy/zaproxy#6739]
**Is your feature request related to a problem? Please describe.**
At present, the evidence highlighter causes ZAP to hang for minutes at a time on large javascript files, making the app fairly unusable.

**Describe the solution you'd like**
A button in the alerts toolbar to turn on/off the evidence highlighter
![image](https://user-images.githubusercontent.com/2119212/128945717-b39198e4-c8cb-4e1f-ab04-2446884f8672.png)

**Describe alternatives you've considered**
The ability to force the lower pane to remember a preference for large response:
![image](https://user-images.githubusercontent.com/2119212/128945769-a7945121-03e0-47e6-b8b2-94001f4ca5ec.png)
and thus suppress evidence highlights:
![image](https://user-images.githubusercontent.com/2119212/128945801-dd6555d7-a8f5-404b-9af9-c5384f59dfd7.png)

An option in options to turn off the response view entirely

**Additional context**
(See other bugs?)

**Would you like to help implementing this feature?**

**Comment by kingthorin** [comment]
It isn’t the evidence highlight that’s the issue. It’s wordwrap and syntax.

You can prove this to yourself by proxying a large message and simply viewing it from the history tab (not in relation to an alert)

**Comment by jsoref** [comment]
I turned off wordwrap and syntax per @thc202, and he suggested filing this bug.

**Comment by kingthorin** [comment]
Hmmm okay

**Comment by thc202** [comment]
This is for workaround mainly (even with pain text view the UI lagged).

**Comment by kingthorin** [comment]
I agree.

**Comment by psiinon** [comment]
Me too :)
