### ISSUE TITLE
pscanrules Timestamp Disclosure should skip sequential/identical digits and have limited scope

### ISSUE THREAD

**Issue by jsoref** [zaproxy/zaproxy#6741]
**Describe the bug**

**To Reproduce**
1. Run a scan of content that includes 0 {repeated} or 1...9
2. See `Timestamp Disclosure - Unix` for both

**Expected behavior**
Sequential increasing numbers and a long sequence of the same numbers aren't timestamps, they're just poker hands (straight, n of a kind)

**Screenshots**
Timestamp Disclosure - Unix
![image](https://user-images.githubusercontent.com/2119212/128946034-90c4bf14-a751-49fa-baba-ee961b2b7ed7.png)

![image](https://user-images.githubusercontent.com/2119212/128946146-f935efe9-ebbb-4ee8-bc81-6df9fe6eaa7a.png)
```js
e.hexChars="0123456789abcdef"
```

**Software versions**
 - ZAP: 2.10.0
 - Add-on: pscanrules 35
 - OS: macOS Big Sur 11.5.1
 - Java: 
 - Browser: 

**Errors from the zap.log file**

**Additional context**
https://github.com/zaproxy/zap-extensions/blob/main/addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/TimestampDisclosureScanRule.java

**Would you like to help fix this issue?**
maybe

**Comment by kingthorin** [comment]
As you can see from Other Info those strings do evaluate to valid Unix time stamps. If you want to chance false negatives you can use High threshold to limit to +/- 1 year.

**Comment by jsoref** [comment]
I'm really only interested in poker runs here.

If someone does a non-run of `0123456879`, `0000020000`, or `3343333333`, I'd be vaguely interested in seeing it.

**Comment by kingthorin** [comment]
How would you suggest what time stamps we should exclude? Runs and sequences aren’t any more or less likely to be timestamps.

Nine ones are just as likely to be a time stamp as eight ones and some other digit.

**Comment by trevor-vaughan** [comment]
I'm running into something similar where random strings that could be timestamps are being flagged but are almost always garbage.

What I would like:

* A method to dictate valid timestamp ranges of concern (+/- 1 year from today)
  * This will remove 99% of the findings that I've seen
* A default to +/- 1 year from today (because of the above)
* Possibly split the alert flag  into different buckets
  * Critical: Timestamp +/- 1 day
  * High: Timestamp +/- 1 week
  * Moderate: Timestamp +/- 1 month
  * Low: Timestamp +/- 1 year
  * Informational: Timestamp outside of 1 year

**Comment by trevor-vaughan** [comment]
@kingthorin Well, I'll admit that it was in the help but I don't think I would have found that page through any of the ZAP contexts without assistance.

I walked through the menus and whatnot to see if I missed something but the link fromthe timestamp alerts to that particular help page eluded me.

Would it be possible to add some context sensitive help to the app regarding settings that can be tweaked for different alerts?

**Comment by kingthorin** [comment]
For some alerts, those adjustments are called out as part of the "Other Info" field. We probably need to be more consistent in that, or look into another option :grinning:
