### ISSUE TITLE
http://example.com and http://example.com/ are flagged separately

### ISSUE THREAD

**Issue by jsoref** [zaproxy/zaproxy#6742]
**Describe the bug**
I get identical alerts for a large number of checkers where the first two alerts are nearly identical:

```
GET: http://mysite.example.com
GET: http://mysite.example.com/
```

**To Reproduce**
1. Start a (spider) scan of http://mysite.example.com (a site that one runs locally or otherwise has authorization to scan)
2. Let it perform basic tests
3. View the alerts
4. Open the first couple of alert categories

**Expected behavior**
As it isn't possible to make a request for `NULL` using `http` (or `https`), the first item should be `http://mysite.example.com/`, not `http://mysite.example.com` and thus there shouldn't be duplication.

**Screenshots**
I'd have to set up an instance w/ `localhost`, and it's too late in my day for that.

**Software versions**
 - ZAP: 2.10.0
 - Add-on: pscanrules 35
 - OS: macOS Big Sur 11.5.1
 - Java: 
 - Browser: 

**Errors from the zap.log file**

**Additional context**

**Would you like to help fix this issue?**

**Comment by thc202** [comment]
One can use an absolute URI with empty path (not following the `NULL` part).

**Comment by jsoref** [comment]
Sure, entering a url in a browser one can, but the request made by the browser will include the `/`, and thus it's the same page.

**Comment by thc202** [comment]
Closing, this is the expected/wanted behaviour.
