### ISSUE TITLE
Env var is not working for authentication

### ISSUE THREAD

**Issue by amankumarchagti** [zaproxy/zaproxy#6751]
I defined the export ZAP_AUTH_HEADER_VALUE as env var in my Linux machine using the following command on my shell:
`export ZAP_AUTH_HEADER_VALUE=<-auth key->`
and then on the same shell, I started to zap on the same shell in GUI mode. the ZAP package i am using is Core Cross Platform Package. nd then I run the automation framework for the passive scan for the target URL in context. and when I checked the headers in spider -> message sub-tab, the header tab was empty. that means the env var auth header is not working.

Mark me correct if I'm doing some wrong step. or if I'm correct then how should this problem be resolved?
Thank you

**Comment by psiinon** [comment]
For info this was discussed on the OWASP #project-zap channel and as @amankumarchagti checked everything I could think of I asked him to raise this as an issue.

**Comment by psiinon** [comment]
I've just tried this on both 2.10.0 and the latest weekly release (on OS X) and the header was added for me.
<img width="1768" alt="Screenshot 2021-08-12 at 12 27 01" src="https://user-images.githubusercontent.com/1081115/129181817-3c7cb7b7-f4ee-4432-9c40-25bac1b670f4.png">

Note the `Authorization: this-is-a-test` header.

For this I used:
``` 
export ZAP_AUTH_HEADER_VALUE=this-is-a-test
```

@amankumarchagti can you supply a similar screenshot of a spider message, obfuscating any sensitive info.

**Comment by psiinon** [comment]
This was using an AF job - I tested it with the spider first, then created an AF plan from that, then restarted ZAP with that plan. In all cases the header was added.

**Comment by amankumarchagti** [comment]
Ok, let me try to do the same once again.

**Comment by amankumarchagti** [comment]
@psiinon env vars are working for me, I was checking the header sub-tab.my bad. Thank you
