### ISSUE TITLE
Enhance OpenAPI feature to support custom servers block for a specific path

### ISSUE THREAD

**Issue by davewichers** [zaproxy/zaproxy#6754]
**Is your feature request related to a problem? Please describe.**
I have an OpenAPI spec for an OWASP Benchmark style test app I'm building, that has services running on multiple ports. Per the OpenAPI spec, you can have 1 or more Servers blocks at the top of the file, but if you want to override those for a specific path, you can include a servers block inside that specific path.  ZAP doesn't support those, and so returns an error like this when parsing my OpenAPI spec:

Failed to access URL: https://localhost:8443/benchmark/sqli-00/BenchmarkTest00246?BenchmarkTest00246=BenchmarkTest00246 : org.apache.commons.httpclient.InvalidRedirectLocationException : Invalid redirect location: https://localhost:$%7BHTTPS_PORT_EXPRESS%7D/julietjs/Index.html

SIDE NOTE: This error message has a minor bug. It should show: 8443, instead of: $%7BHTTPS_PORT_EXPRESS%7D

Here's the openapi spec for this endpoint:

```
  /sqli-00/BenchmarkTest00246:
    get:
      servers:
      - url: https://localhost:9443/benchmark
      operationId: doget_246
      parameters:
      - in: query
        name: BenchmarkTest00246
        required: true
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            text/html: {}
```

**Describe the solution you'd like**
When a 'servers' block is specified for a specific path like this, ZAP should honor that path, rather than ignoring it and using the one specified at the top.

I would think this wouldn't be very difficult to implement. And without it, we can't easily test ZAP against test suites like this. We'd basically have to build an API spec per server, and run separate scans on each. This test app currently has 3 different servers and is likely to grow into more.

NOTE: Big chunks of my OpenAPI spec might have these. As such, if the size of the object is large for creating the Server attribute for a specific path, you might want to create a 'Set' of these and simply point each custom path to the same "Server' instance if the paths have the same URL. For example, in my current spec, I have 3 such Servers. The normal 1, and then 2 others, each for 1/3 of the end points.

**Comment by thc202** [comment]
Actually, just noticed that in the example provided the servers are in the operation not the path. Will add support for that too.
