### ISSUE TITLE
Alert report

### ISSUE THREAD

**Issue by shabisan** [zaproxy/zaproxy#6756]
Hi, 
I trying to find a way to make a report form all the alerts that I have.  Right now I can only see a PDF version of it. Is there another way to get a more user friendly format? 
I'm using ZAP desktop for windows

**Comment by thc202** [comment]
You can select different formats (Template field) with the Report Generation add-on: https://www.zaproxy.org/docs/desktop/addons/report-generation/

For usage questions it's better to use: https://groups.google.com/group/zaproxy-users
