### ISSUE TITLE
Duplicated comment for override methods

### ISSUE THREAD

**Issue by CoolKangaroo2022** [zaproxy/zaproxy#6762]
Hello! I find in your [Developer Guidelines](https://github.com/zaproxy/zaproxy/wiki/DevGuidelines) that 
> Do not add "(non-Javadoc)" comments to overriding methods (the default comment automatically added when overriding a method).

However, I still witness some "(non-Javadoc)" comments to overriding methods, e.g.,
* zap/src/main/java/org/zaproxy/zap/db/sql/SqlTableContext.java
* zap/src/main/java/org/zaproxy/zap/db/sql/SqlDatabase.java
* zap/src/main/java/org/parosproxy/paros/db/paros/ParosTableTag.java
......

Would you like to remove these comments?
If there is anything I can help with?

**Comment by thc202** [comment]
Feel free to open a pull request removing them.
