### ISSUE TITLE
ZAP does not exit in cmd mode

### ISSUE THREAD

**Issue by MilyMilo** [zaproxy/zaproxy#6765]
**Describe the bug**
ZAP process does not quit after running: `zap.sh -cmd -addoninstallall` instead it stays alive.
This is not limited to just `-addoninstallall`, running `zap.sh -cmd -help` behaves the same way.

It's problematic when trying to install addons in docker at build time.

**To Reproduce**
1. Run `zap.sh -cmd -addoninstallall` or `zap.sh -cmd -help`
2. Wait for output
3. See that the ZAP process is still alive

**Expected behavior**
I expected `-cmd` to behave as described in the help text: `Run inline (exits when command line options complete)` 

**Screenshots**
n/a

**Software versions**
- ZAP: 2.10.0
- Add-on: OpenAPI v20
- OS: OS X Big Sur + Alpine Linux (Docker)
- Java: openjdk 14.0.2 + openjdk version 1.8.0_282
- Browser: Chromium: 92.0.4515.131

**Errors from the zap.log file**
n/a

**Additional context**
n/a

**Would you like to help fix this issue?**
As before, can't really help with java

**Comment by thc202** [comment]
Could you provide a thread dump?

**Comment by thc202** [comment]
I did not reproduce the issue correctly, missed the part of installing all add-ons.

**Comment by psiinon** [comment]
We've discovered that the new oast add-on is not exiting correctly. A fix will be hopefully be available soon...
