### ISSUE TITLE
Ubuntu 20.04 installation error

### ISSUE THREAD

**Issue by HarlowIBM** [zaproxy/zaproxy#6770]
**Describe the bug**
Running Ubuntu installation instructions gives a signature error:
```
W: GPG error: http://download.opensuse.org/repositories/home:/cabelo/xUbuntu_20.04  InRelease: The following signatures were invalid: <Expired Signature> home:cabelo OBS Project <home:cabelo@build.opensuse.org>
E: The repository 'http://download.opensuse.org/repositories/home:/cabelo/xUbuntu_20.04  InRelease' is not signed.
```

**To Reproduce**
1. Go to https://software.opensuse.org/download.html?project=home%3Acabelo&package=owasp-zap
2. Follow Ubuntu installation instructions for 20.04
```
echo 'deb http://download.opensuse.org/repositories/home:/cabelo/xUbuntu_20.04/ /' | tee /etc/apt/sources.list.d/home:cabelo.list && \
  curl -fsSL https://download.opensuse.org/repositories/home:cabelo/xUbuntu_20.04/Release.key | gpg --dearmor | tee /etc/apt/trusted.gpg.d/home_cabelo.gpg > /dev/null && \
  apt update && \
  apt install owasp-zap
```

**Expected behavior**
Installations were working before August 20th. I'm guessing this is some kind of signature expiration.

**Software versions**
 - ZAP:  2.9.0 (whatever is installed by the above instructions)
 - Add-on: None
 - OS: Ubuntu 20.04
 - Java: 1.8.0_232
 - Browser: N/A for this

**Errors from the zap.log file**
N/A

**Additional context**
Running in a docker file.

**Would you like to help fix this issue?**
If I can, sure

Edit:
Also, sorry if this is the wrong place for this. Let me know if there is another repo or person I should reach out to directly. Thanks

**Comment by cabelo** [comment]
Solved

**Comment by kingthorin** [comment]
@HarlowIBM please give it a shot again.

**Comment by psiinon** [comment]
Many thanks @cabelo !

**Comment by HarlowIBM** [comment]
It works now, thanks for the quick turnaround on this!
