### ISSUE TITLE
Repo key failure

### ISSUE THREAD

**Issue by BloodyIron** [zaproxy/zaproxy#6773]
Using the Ubuntu 20.04 deb ppa/repo to install OWASP ZAP, and now I'm getting key issues:

Err:21 http://download.opensuse.org/repositories/home:/cabelo/xUbuntu_20.04  InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 18B6CC30405F642D

Can't find the current key info I need to pull, and the website last I tried did not give me current key info. This needs to get fixed as I cannot get updates now, so I'm going to disable the repo until I hear a solution here.

**Comment by kingthorin** [comment]
Did you encounter this today? We had a report of expired signatures and a subsequent fix overnight. See: https://github.com/zaproxy/zaproxy/issues/6770

**Comment by kingthorin** [comment]
Per: https://software.opensuse.org/download.html?project=home%3Acabelo&package=owasp-zap
```bash
echo 'deb http://download.opensuse.org/repositories/home:/cabelo/xUbuntu_20.04/ /' | sudo tee /etc/apt/sources.list.d/home:cabelo.list
curl -fsSL https://download.opensuse.org/repositories/home:cabelo/xUbuntu_20.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home_cabelo.gpg > /dev/null
sudo apt update
sudo apt install owasp-zap
```

Per the link you provided earlier you can see that the files were updated 24-Aug-2021.

**Comment by BloodyIron** [comment]
Okay looks like curling that Release.key works now, didn't work earlier. Never mind heh.

**Comment by kingthorin** [comment]
No problem, thanks for following up.
