### ISSUE TITLE
Formbased authentication issue

### ISSUE THREAD

**Issue by ksprakash357** [zaproxy/zaproxy#6779]
Hi,

Not able to add username and password

thanks

**Comment by kingthorin** [comment]
Please don't ask questions as issues - the [ZAP User Group]( https://groups.google.com/group/zaproxy-users) is a much better place for questions.

If you’re asking about a third party components such as the Jenkins plugin or VSTS plugin please look for their preferred support mechanism as these were not created by and are not supported by the core team.

---

When you post to the User Group I suggest providing much more detail. "Not able" is not something we can fix or offer advice on.
