### ISSUE TITLE
Question regarding creating an add-on.

### ISSUE THREAD

**Issue by HarshilPatel007** [zaproxy/zaproxy#6780]
Hello devs,
I'm new to ZAP and want to build an add-on that just add payloads strings to the current mouse pointer.
ex. : https://site.com/products?=10[PAYLOAD]&category=toys in the "Request panel" via right click menu and in some cases ask users for input like for ex. :
"How many tables you've find out?" -> user inputs "5".
So, the PAYLOAD would be like this. https://site.com/products?=10'+UNION+SELECT+1,2,3,4,5--

I want a custom entry in right click menu with 4-5 sub menus. 
ex. : 
- AddOn Name 
  - XSS PAYLOADS
    - PAYLOADS CATEGORY 1
       - 20-25 PAYLOADS....
    - PAYLOADS CATEGORY 2...
       - 20-25 PAYLOADS
     - PAYLOADS CATEGORY 3...
        - PAYLOAD SUB CATEGORY
            - 20-25 PAYLOADS
  - SQLi PAYLOADS
    - PAYLOADS CATEGORY 1
       - 20-25 PAYLOADS....
    - PAYLOADS CATEGORY 2...
       - 20-25 PAYLOADS
     - PAYLOADS CATEGORY 3...
        - PAYLOAD SUB CATEGORY
            - 20-25 PAYLOADS
 

I know the back-end side logic using JAVA and PYTHON but, the problem is I don't know where to start for front-end and what api should I use to do this thing?

the idea here is to I don't want to go back and forth between my payloads files and zap..!!!
I know I can add payloads into Fuzz and start fuzzing things. but, it's not good to fuzz things for 2-3 payloads (I think) and it took extra 2-3 steps.

**Comment by thc202** [comment]
This should be asked in the OWASP ZAP Developer Group: https://groups.google.com/g/zaproxy-develop
