### ISSUE TITLE
Ability to grep - match strings in fuzzer responses.

### ISSUE THREAD

**Issue by njmulsqb** [zaproxy/zaproxy#6788]
Fuzzer should have an option like Burp Intruder's Grep - Match where you can give a string/regex which gets matched against each response. Currently, I cant find any such option and the only option is to go through every response manually which is very time taking

Grep - Match is helpful when you're looking for special patterns in the responses.

**Comment by thc202** [comment]
Did you try use the Search tab? https://www.zaproxy.org/docs/desktop/ui/tabs/search/

**Comment by njmulsqb** [comment]
> Did you try use the Search tab? https://www.zaproxy.org/docs/desktop/ui/tabs/search/

Yes I tried, but it just returned the results from the responses in the sites tab and not from the fuzzer

**Comment by thc202** [comment]
You need to select "Fuzz Results" entry.

**Comment by njmulsqb** [comment]
> You need to select "Fuzz Results" entry.

Alright, Still grep - match feature is somewhat different, using this search feature I cant figure out what fuzzed response does not matches my given string/regex.

**Comment by thc202** [comment]
You can select "Inverse" for that.

**Comment by njmulsqb** [comment]
> You can select "Inverse" for that.

It worked, thanks.

Can you tell me if there's anyway to edit fuzzed request, change the payload or position of fuzzing? and how to delete previous fuzzer results so that the search dont fetches results from them?

**Comment by njmulsqb** [comment]
Also, does this search feature support regex matching?

**Comment by kingthorin** [comment]
> Can you tell me if there's anyway to edit fuzzed request

IIRC that’s already part of another issue. Though you can always manually send a request (which you can edit), then use that as your basis for fuzzing.

> change the payload or position of fuzzing?

You can setup
The fuzzer however you need. If you mean with persistent fuzzer settings that is already part of another issue.

> and how to delete previous fuzzer results so that the search dont fetches results from them?

Don’t recall off the top of my head, will check later.

**Comment by kingthorin** [comment]
>  and how to delete previous fuzzer results so that the search dont fetches results from them?

Currently it seems you can't remove individual runs, you can clear any that aren't actively running though. (So right now if you wanted to search different fuzz results individually you need to clear previous runs before searching.)

![image](https://user-images.githubusercontent.com/7570458/132334255-17b15d40-80ae-40bd-92a1-f2890a1d1b30.png)

**Comment by njmulsqb** [comment]
> > and how to delete previous fuzzer results so that the search dont fetches results from them?
> 
> Currently it seems you can't remove individual runs, you can clear any that aren't actively running though. (So right now if you wanted to search different fuzz results individually you need to clear previous runs before searching.)
> 
> ![image](https://user-images.githubusercontent.com/7570458/132334255-17b15d40-80ae-40bd-92a1-f2890a1d1b30.png)

Thanks. I think removing individual runs can be a good addition to Zaproxy.

**Comment by kingthorin** [comment]
You can also use the "Tag Creator" Fuzz Processor to regex match/extract parts of responses (it'll show in the "State" column).

**Comment by kingthorin** [comment]
@njmulsqb did we give you enough options to get something working grep wise?

**Comment by kingthorin** [comment]
Leno response in a week.
