### ISSUE TITLE
fuzzer: Update Help

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#6791]
https://www.zaproxy.org/docs/desktop/addons/fuzzer/options/ does not seem to be in-sync with the current Fuzzer options dialog:

![image](https://user-images.githubusercontent.com/7570458/132358994-9c706fdd-4b12-4f01-8c34-3369f92c3650.png)

https://github.com/zaproxy/zap-extensions/blob/main/addOns/fuzz/src/main/javahelp/org/zaproxy/zap/extension/fuzz/resources/help/contents/options.html seems incomplete/out-dated and should be updated.

**Comment by njmulsqb** [comment]
Hi @kingthorin,

As I am going through ZAP fuzzer these days I myself noticed that the documentation for Fuzzer available at the official website is really outdated and incomplete. I thought of writing the blog post but I think making it better on the official website would be a better idea.

I am thinking to update the fuzzer related pages on the official website that includes:
https://www.zaproxy.org/docs/desktop/addons/fuzzer/
https://www.zaproxy.org/docs/desktop/addons/fuzzer/options/

and other fuzzer related pages.

For this purpose, I would require to discuss the features of fuzzer with someone about their working to document them properly. For example, I have no idea what "payload replacement strategy" is about forget about documenting it. I hope you got my point

**Comment by kingthorin** [comment]
@njmulsqb the official site content is generated based on the help content packaged with the fuzzer add-on, so all your updates would be via: https://github.com/zaproxy/zap-extensions/blob/main/addOns/fuzz/src/main/javahelp/org/zaproxy/zap/extension/fuzz/resources/help/contents/

Feel free to ask questions here.

As for replacement strategy it's supposed to control the order that multiple payload lists are iterated, however in the quick test I just did they both behaved the same way 😢 (@thc202 @psiinon @ricekot any thoughts on that?).

**Comment by thc202** [comment]
If that's the case it's broken.

**Comment by kingthorin** [comment]
In case it matters, I was using the Numberzz generator.

(I noticed a tertiary issue with it, the non-first time the Numberzz panel is displayed Increment value resets to zero and you can't accept the dialog without setting it to a non-zero value....I had to planned to look at that when I looked at the delay item.)

**Comment by njmulsqb** [comment]
> In case it matters, I was using the Numberzz generator on three positions. (Fuzzer 13.2.0)
> I'll also re-try it on another system in a bit.
> 
> (~I noticed a tertiary issue with it, the non-first time the Numberzz panel is displayed the Increment value resets to zero and you can't accept the dialog without setting it to a non-zero value....I had to planned to look at that when I looked at the delay item.~ [zaproxy/zap-extensions#3133](https://github.com/zaproxy/zap-extensions/pull/3133))

You mentioned Numberzz so let me ask here, can we bruteforce starting from values 0000 in numberzzz? I tried but cant enter more than one 0

**Comment by thc202** [comment]
You can use the Expand payload processor for that: https://www.zaproxy.org/docs/desktop/addons/fuzzer/processors/

**Comment by njmulsqb** [comment]
Hi,

I have added the missing definitions to the documentation, so the PR is ready to merge, but I believe some definitions like Payload Replacement Strategy needs more in depth explanation

**Comment by njmulsqb** [comment]
The page still hasnt updated at https://www.zaproxy.org/docs/desktop/addons/fuzzer/options/. It has merged, isn't it?

**Comment by thc202** [comment]
The site is updated when the add-ons are released.
