### ISSUE TITLE
OWASP ZAP Basic authentification

### ISSUE THREAD

**Issue by daskibo** [zaproxy/zaproxy#6793]
I am try repeat https://play.sonatype.com/watch/ttqKANDzJCAdBUkPrsz6Td,
but without success.
Please advice me any deatails or reason, what I did mistakly

https://user-images.githubusercontent.com/80215349/132682228-1db6f6d5-aa2c-4d67-bbbb-74384a5bf8de.mp4

**Comment by kingthorin** [comment]
1. You don't have a logged in or logged out indicator set.
2. The context does not seem to include the URL you're trying to access. (There's a chance I"m wrong, the video is kinda hard to make out.)

---

Please don't ask questions as issues - the [ZAP User Group]( https://groups.google.com/group/zaproxy-users) is a much better place for questions.
