### ISSUE TITLE
False Positive: Source Code Disclosure - PHP :: Roboto-Medium.ttf

### ISSUE THREAD

**Issue by globeone** [zaproxy/zaproxy#6795]
Found a False Positive in the Source Code Disclosure - PHP. 

The scans regex reports the Google font Roboto-Medium.ttf as being PHP.

![image](https://user-images.githubusercontent.com/10052587/132691188-39145235-903c-425c-8b86-9294cdb89a7f.png)

But as one can see, it's not PHP as there are control characters used in the webFont. 

![image](https://user-images.githubusercontent.com/10052587/132690265-94f58b48-2dd5-482e-afa5-ba9f4e5a156a.png)

and one can see that the content type is font/ttf
![image](https://user-images.githubusercontent.com/10052587/132690619-4283c4e8-6fb5-4486-b58b-5b9cab90ef40.png)

OWASP ZAP version: Weekly D-2021-09-07
System: Windows 10
JavaVersion: openjdk 11.0.12 2021-07-20 LTS
OpenJDK Runtime Environment (build 11.0.12+7-LTS)
OpenJDK 64-Bit Server VM (build 11.0.12+7-LTS, mixed mode)

**Comment by kingthorin** [comment]
Yup, this should be updated to use similar functionality to the Timestamp Disclosure rule:
https://github.com/zaproxy/zap-extensions/search?l=Java&q=ttf
