### ISSUE TITLE
False Positive issues

### ISSUE THREAD

**Issue by sunnyshi1** [zaproxy/zaproxy#6796]
**Describe the bug**
1. Advanced SQL Injection - Microsoft SQL Server/Sybase time-based blind, as Certs platform is implemented with the Microsoft login authentication to access any of the URL’s So any type of SQL injection cannot be possible without valid resource pro login credentials.
2. LDAP Injection, as Certs platform is implemented with the Microsoft login authentication to access any of the URL’s So any type of LDAP injection cannot be possible without valid resource pro login credentials.
3. Content Security Policy (CSP) Header Not Set, as Certs platform is implemented with the Microsoft login authentication to access any of the URL’s So any type of css, html, etc. File cannot be altered without valid resource pro login credential
4.  Web Cache Deception,as Certs platform is implemented with the Microsoft login authentication to access any of the URL’s valid resource pro login credentials is required hence the caching of any of the method response data is difficult.

**To Reproduce**

1. Open ZAP
2. Click 'Manul Explore'
3. Copy 'https://certscenterapp-certscenterstaging.azurewebsites.net' to 'URL to explore'
4. Click 'Launch Browser'
5. Right-click this URL under the sites
6. Click 'spider scan'
7. Click start scan
8. After spider scan, right-click the URL under the sties
9. Choose medium as  the threshold  and choose insane as the strength on the policy page
10. Click start scan

**Expected behavior**
These false-positive issues should not be scanned.

**Screenshots**
![image](https://user-images.githubusercontent.com/90362548/132818056-67209e6a-f04c-422d-a51e-3b80abe6988e.png)
![image](https://user-images.githubusercontent.com/90362548/132818097-ceb15ec4-54fb-451f-9203-cc282568a01e.png)
![image](https://user-images.githubusercontent.com/90362548/132818158-87957e43-7ea6-486c-ad1e-da5cd4497edd.png)
![image](https://user-images.githubusercontent.com/90362548/132818227-1d2fb65f-3bc7-48b2-9b10-d4b402afd7ef.png)

**Software versions**
 - ZAP: [OWASP ZAP 2.10.0]
 - Add-on:
•Active Scan Rules Beta
•Active Scan Rules Alpha
•Advanced SQL Injection Scanner
•Passive Scan Rules Beta
•Access Control Testing
•Passive Scan Rules Alpha
 - OS: [Windows 10]

**Comment by kingthorin** [comment]
1. This is a time based injection test, if subsequent tests were slower than the original then success is a reasonable conclusion for the scan rule to make.
2. Seems to have been legitimately identified by diffing results, however it is probably unlikely that an LDAPi would occur through manipulation of the content-type header.
3. There's no debate here, either the CSP header was there or it wasn't. If this is unimportant to your or outside of your control that's your call. You can manually set the findings as FP or create an Alert Filter.
4. Difficulty ! = false positive.

**Comment by psiinon** [comment]
For info issues that cover multiple potential problems are not really that useful - we would much rather see one issue per false possitive, or at least per rule.
We also need details of how to reproduce them.
I'll update this FAQ to make that clear: https://www.zaproxy.org/faq/how-do-i-handle-a-false-positive/

**Comment by sunnyshi1** [comment]
Thanks for your help, I'm sorry I couldn't send more details because some information are confendetial, I will create a alter filter to handle these issues.
