### ISSUE TITLE
False Positive issues2

### ISSUE THREAD

**Issue by sunnyshi1** [zaproxy/zaproxy#6797]
**Describe the bug**
1. Insecure HTTP Method - PATCH, there is no any patch methods in the scanned website
2. Insecure HTTP Method - PUT,  there is no any patch methods in the scanned website
3. Interger Overflow Error issue, the url zap scan try to attack is an Error Page.
4. Web Cache Deception, it is a false positive alert since the 403 error page handles all attacks.

To Reproduce

1. Open ZAP
2. Click 'Manul Explore'
3. Copy 'https://datacaptureplatform-1-test.azurewebsites.net' to 'URL to explore'
4. Click 'Launch Browser'
5. Right-click this URL under the sites
6. Click 'spider scan'
7. Click start scan
8. After spider scan, right-click the URL under the sties
9. Choose medium as the threshold and choose insane as the strength on the policy page
10. Click start scan

**Expected behavior**
These false-positive issues should not be scanned

**Screenshots**
![image](https://user-images.githubusercontent.com/90362548/132820555-0e08128b-6cc6-489f-81d9-079286952851.png)
![image](https://user-images.githubusercontent.com/90362548/132820581-2277323e-5ff3-4258-86c4-ea30ed0786af.png)
![image](https://user-images.githubusercontent.com/90362548/132820752-67bdc5b5-2ebd-4dbf-9fe3-e78804613fbe.png)
![image](https://user-images.githubusercontent.com/90362548/132820913-eceba623-46ce-4cba-8c5e-cf1aec48a740.png)

**Software versions**
 - ZAP: [OWASP ZAP 2.10.0]
 
 - Add-on: 
•  Active Scan Rules Beta
• Active Scan Rules Alpha
• Advanced SQL Injection Scanner
• Passive Scan Rules Beta
• Access Control Testing
• Passive Scan Rules Alpha

 - OS: [e.g. Windows 10]

**Comment by kingthorin** [comment]
1. The PATCH request was successful (or well not denied). You can manually mark these FP or create an Alert Filter.
2. The PUT request was successful (or well not denied). You can manually mark these FP or create an Alert Filter.
3. We'd need the actually requests/responses. If the initial page was a 500 the scan rule would not have run. You can either mark these FP, define a Custom Error Page, or setup an Alert Filter.
4. The requested resources were all within the similarity threshold of the original request. Given some of these are css etc it seems unlikely that this would be an FP. However, given that the scan rule assumes the original request is authorized/authenticated then perhaps there's something that can be done to keep this from running if no auth is setup.

**Comment by sunnyshi1** [comment]
Thanks for your help, I will create Alter Filter to handle these issues.
