### ISSUE TITLE
False Positive issue3

### ISSUE THREAD

**Issue by sunnyshi1** [zaproxy/zaproxy#6798]
**Describe the bug**
1. Vulnerable JS Library, till now the latest version for Jquery is 3.6.0 and ZAP suggests updating the Jquery version to the latest one. Elio Yan tried so but some pages of Supervisor Portal don't work after that. So we only update the version to 2.2.4 to keep all pages work, and we will update the version gradually in future work.
2. Viewstate without MAC Signature (Unsure), add EnableViewStateMac="true" in CaseManagement.aspx
Just enable the ViewStateMac without encrypting the view state with the suggestion of Microsoft
Note: Do not encrypt ViewState unless it contains sensitive data. To avoid the performance overhead of encryption, consider storing sensitive data on the server and not in ViewState.
https://docs.microsoft.com/en-us/previous-versions/msp-n-p/ff649308(v=pandp.10)?redirectedfrom=MSDN
We have extracted the view state and decode to check the Mac signature.
It mentioned 20 byte(s) left over, perhaps an HMACSHA1 signature.
http://viewstatedecoder.azurewebsites.net/
We highly considered it is a false positive.

**To Reproduce**

1. Open ZAP
2. Click 'Manul Explore'
3. Copy 'http://test-iis-new:7880' to 'URL to explore'
4. Click 'Launch Browser'
5. Right-click this URL under the sites
6. Click 'spider scan'
7. Click start scan
8. After spider scan, right-click the URL under the sties
9. Choose medium as the threshold and choose insane as the strength on the policy page
10. Click start scan

**Expected behavior**
These positive issues should not be scanned.

**Screenshots**
![image](https://user-images.githubusercontent.com/90362548/132824911-20b578b4-fbe3-4aaa-9931-fa27741579a4.png)
![image](https://user-images.githubusercontent.com/90362548/132824981-3de73e74-2751-42b6-8130-974dfe89b145.png)

**Software versions**
 - ZAP: [OWASP ZAP 2.10.0]
 - Add-on: 
• Active Scan Rules Beta
• Active Scan Rules Alpha
• Advanced SQL Injection Scanner
• Passive Scan Rules Beta
• Access Control Testing
• Passive Scan Rules Alpha

 - OS: [e.g. Windows 10]

**Comment by kingthorin** [comment]
1. If you choose not to upgrade a dated component that doesn’t mean it’s a false positive.
2. Is already noted experimental, unsure, and low confidence. If you believe it’s a false positive then mark it as such(either manually or with an Alert Filter).

I believe this particular ticket should be closed.
