### ISSUE TITLE
The reports includes the OUTOFSCOPE urls.

### ISSUE THREAD

**Issue by mailtokun** [zaproxy/zaproxy#6799]
**Describe the bug**
Ignored some urls by `OUTOFSCOPE`  in below config file. But it still showing in JSON/MD reports. Is there any workaround to ignore them in reports? 

## config file
```
90022	OUTOFSCOPE	https://oss.test.cloud.xx.com/status/api/v1/status/incidents*
90022	OUTOFSCOPE	https://oss.test.cloud.xx.com/status/api/v1/status/notifications*
90022	OUTOFSCOPE	https://oss.test.cloud.xx.com/status/api/v1/status/maintenances*
```

**Comment by psiinon** [comment]
Please dont ask questions as issues - the ZAP User Group is a much better place to ask them: https://groups.google.com/group/zaproxy-users
