### ISSUE TITLE
"SQL Injection - Microsoft SQL Server" link in Report Add-on takes user to "SQL Injection" section

### ISSUE THREAD

**Issue by jhowlett96** [zaproxy/zaproxy#6800]
I am using the Reports Add-on and generating a report using API reports/action/generate endpoint. My template=traditional-html-plus and theme=light (I haven't tested this bug with other templates). 

When I click on the "SQL Injection - Microsoft SQL Server" link in the Alerts table I am taken to the "SQL Injection" alerts instead.

This is due to both sections having id of "#plugin-40018" and both links therefore using href="#plugin-40018". "SQL Injection" is the first section on the report with this id so both links take you there.

**Comment by kingthorin** [comment]
A scan rule can raise multiple alerts. The particular error string or whatever in this case was likely just a Microsoft SQL Server error (or triggered by MS specific query syntax), via the generic SQLi scan rule (40018).

https://github.com/zaproxy/zap-extensions/search?q=40018

https://github.com/zaproxy/zap-extensions/blob/eee960de14f9dadcf3a32c33547dde2b524ddc31/addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/SqlInjectionScanRule.java#L148-L175
