### ISSUE TITLE
Root CA expired but regenerated root CA not used by OWASP ZAP

### ISSUE THREAD

**Issue by SimonRWaters** [zaproxy/zaproxy#6805]
I started 2.10.0, it correctly reported the Root CA had expired.
I generated a Root CA in the Dynamic SSL settings. I saved this to a file and imported to browser.
OWASP ZAP was using old Root CA, so restarted OWASP ZAP and it is still using the expired CA Cert.

This is on Debian, I appear to have installed OWASP ZAP by tar ball to "~/ZAP" originally, and then installed via packaging tool to /usr/share/zaproxy. But otherwise fairly vanilla install.

I resolved it by renaming "~/.ZAP" to "~/.ZAP.OLD", when everything started working as expected, but obviously a lot of other configuration is potentially "lost" (Probably for the better in this instance but others may be more frustrated by such an issue). The installation was August 12 2020. I still have the ".ZAP.OLD" (for now).

**Comment by psiinon** [comment]
You can just regenerate the ZAP certificate via the Options / Dynamic SSL Certificate screen, you dont need to loose all of your other configs.
https://www.zaproxy.org/docs/desktop/ui/dialogs/options/dynsslcert/

**Comment by psiinon** [comment]
Related: #6712

**Comment by SimonRWaters** [comment]
That is what I describe doing in the report, something was preventing it being saved correctly, I have tried to reproduce, but it isn't anything to do with the certificates, as putting the old one back behaves as expected. So I suspect it is a more generic issue.

**Comment by psiinon** [comment]
Ah sorry, I missed that.
When you try to save it are there any errors in the zap.log file?
https://www.zaproxy.org/faq/somethings-not-working-what-should-i-do/#check-the-log-file
