### ISSUE TITLE
enhance: commonlib with standard resource identification methods

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#6810]
In follow-up to https://github.com/zaproxy/zap-extensions/pull/3137 and earlier PRs. Centralize/generalize `isCss`/`isJavaScript`/`isFontRequest`. Handle both request and response in single methods (to reduce verbosity). Consider implementing a joint method like `isResource(Httpmessage)`.

**Comment by kingthorin** [comment]
Font checking currently impacts pscanrules and pscanrulesAlpha. Centralized/generalized version should use the getEscapedPath() variant.

**Comment by kingthorin** [comment]
Discussion of using Control Characters as a mechanism to identify binary responses: https://github.com/zaproxy/zaproxy/issues/6820

**Comment by kingthorin** [comment]
Some reference PRs that might help someone along the way:
- https://github.com/zaproxy/zap-extensions/pull/2825
- https://github.com/zaproxy/zap-extensions/pull/3137
- https://github.com/zaproxy/zap-extensions/pull/2827

**Comment by ArkaprabhaChakraborty** [comment]
@kingthorin I want to work on this issue
