### ISSUE TITLE
False Positive: Source Code Disclosure - PHP :: PNG (Portable Network Graphic) files

### ISSUE THREAD

**Issue by globeone** [zaproxy/zaproxy#6820]
**Describe the bug**
The Souce Code Disclosure — PHP alert is flagging on binary PNG files

**To Reproduce**
1. Run a scan on a website containing PNG files
2. Open the alert on Source Code Disclosure — PHP
3. Observe that the check is only seems to be looking for <?= which is not enough to determine if a file is PHP or not.

**Expected behavior**
The Source Code Disclosure - PHP test could look at the Content-Type header (e.g. Content-Type: image/png) and the file-signature at the beginning of the file to determine if it's really PHP or not. An additional way is to check for control characters. Seeing as control characters (e.g. BELL char(7), NULL char(0), SOH char(^A), in PHP would throw invalid syntax.  

List of File Signatures
https://en.wikipedia.org/wiki/List_of_file_signatures
List of Control Characters
https://en.wikipedia.org/wiki/Control_character

The CHARACTER class
https://cr.openjdk.java.net/~iris/se/15/latestSpec/api/java.base/java/lang/Character.html

With the CONTROL method that should make it easy to detect control characters
CONTROL
public static final byte CONTROL
General category "Cc" in the Unicode specification.
Since:
1.1

(please forgive me if I got the words class and method mixed up. Java uses different names than other programming languages to express these concepts.)

How to check for character properties in Java
https://docs.oracle.com/javase/tutorial/i18n/text/charintro.html

```
char var = '^A'; 
string str_no = "This is not a PHP file";
string str_yes = "This could be a PHP file";

if (Character.getType('var') == Character.CONTROL) {
    System.out.print(str_no+"\n");
} else {
    System.out.print(str_yes+"\n");
}
```

**Screenshots**
Response body, showing it's really PNG
![image](https://user-images.githubusercontent.com/10052587/134171960-69f740e4-11ef-416d-949c-efaaf6c580e6.png)

Flagged on <?= yet Content-Type: image/png
![image](https://user-images.githubusercontent.com/10052587/134167059-ca0bd51f-b8c7-4910-8f8f-9bea2d940ee8.png)

**Software versions**
 - ZAP: D-2021-09-20
 - Add-on: Passive 1099 Source Code Disclosure
 - OS: Windows 10
 - Java: openjdk version "11.0.12" 2021-07-20 LTS
OpenJDK Runtime Environment (build 11.0.12+7-LTS)
OpenJDK 64-Bit Server VM (build 11.0.12+7-LTS, mixed mode)
 - Browser: Version 93.0.4577.82 (Official Build) (64-bit)

**Errors from the zap.log file**
[2021-09-21_sanitized_zap.log](https://github.com/zaproxy/zaproxy/files/7203035/2021-09-21_sanitized_zap.log)

**Additional context**
Related to:
False Positive: Source Code Disclosure — PHP :: Roboto-Medium.ttf #6795

**Would you like to help fix this issue?**
Offered some suggested fixes, and I'm happy to test.

**Comment by globeone** [comment]
As it was marked as a False Negative, here is the actual PNG file that was flagged by ZAP.
![github6820](https://user-images.githubusercontent.com/10052587/134182122-f3b5a0ae-10cb-4ee4-9aed-3acbf67c38cd.png)

**Comment by kingthorin** [comment]
Oops I just hit the wrong label 😢
