### ISSUE TITLE
Javascript automatically executed when copying "XSS" code.

### ISSUE THREAD

**Issue by ostracize** [zaproxy/zaproxy#6823]
**Describe the bug**
Copying the code
`<IFRAME SRC="javascript:alert('XSS');"></IFRAME>`
from anywhere in the interface causes the javascript code to be executed 

**To Reproduce**
1. Put the above code anywhere into the OWASP ZAP interface.
2. As above, copy the code and OWASP ZAP will show the javascript alert

**Expected behavior**
Javascript does not execute

**Screenshots**
![image](https://user-images.githubusercontent.com/2067246/134386803-25a68737-40c4-4e7b-864e-c2a131e1c0ec.png)

**Software versions**
 - ZAP: Observed on build 2021-08-17
 - Browser: Firefox 92.0

**Other notes**
In terms of security, this is probably a low concern. Perhaps at best, a user could be tricked into copying this code off a target site and the target could then "attack" the user back.

**Comment by kingthorin** [comment]
What OS?
What java package/version?

**Comment by kingthorin** [comment]
For the record I'm unable to make anything of this sort happen on `Microsoft Windows [Version 10.0.19042.1237]` w/ `openjdk version "11.0.6" 2020-01-14`.

**Comment by thc202** [comment]
Seems to be Webswing based on the popup.

**Comment by ostracize** [comment]
Ubuntu 20.04
OpenJDK Java 11.0.11
And yes, the Webswing GUI

**Comment by kingthorin** [comment]
In that case it's outside of ZAP's control (from my perspective).

**Comment by ostracize** [comment]
Good point. Perhaps an issue with Webswing itself? 
At any rate, it is likely triggered when ZAP prompts the user to confirm the copy to the host machine:
![image](https://user-images.githubusercontent.com/2067246/134399472-31d9d65b-88ca-43cc-9eab-92b45b35a5ef.png)
The dialogue is not sanitizing the input. Just seems to be an annoyance.

**Comment by thc202** [comment]
Yes, this should be reported to Webswing.

**Comment by ostracize** [comment]
Much appreciated.

**Comment by thc202** [comment]
Could you circle back?

**Comment by kingthorin** [comment]
Probably not related but interesting timing/ similarity.

https://mobile.twitter.com/GHSecurityLab/status/1441072962912784389
