### ISSUE TITLE
Support HTTPS pass-through

### ISSUE THREAD

**Issue by SkypLabs** [zaproxy/zaproxy#6832]
**Is your feature request related to a problem? Please describe.**
Yes, I am conducting a penetration test for which I need to analyse the traffic of mobile applications (Android and iOS). The mobile applications use SSL/TLS pinning at different locations in the code (different libraries/frameworks with their own SSL/TLS pinning mechanisms). I could successfully disable SSL/TLS pinning for some libraries but one still resists me at the moment. I don't really need to analyse the requests sent by the library for which SSL/TLS pinning is still enabled but I definitely need to analyse the other ones.

My problem is that ZAP replaces the TLS certificates of all requests sent by the mobile applications without the possibility to ignore some of them. In my case, it makes it impossible to continue to test the mobile applications due to how they behave.

**Describe the solution you'd like**
Add an option to ignore some SSL/TLS certificates. It means not replacing them with ones generated by ZAP on the fly, or said differently, forwarding the requests without touching them.

**Describe alternatives you've considered**
I don't see any.

**Additional context**
N/A

**Would you like to help implementing this feature?**
If I can find the time for it, yes!

**Comment by psiinon** [comment]
For web applications I'd recommend handling this in the browser, eg using an add-on like Foxy Proxy to selectively proxy specific URLs through ZAP (or not).
But for mobile that could be tricky :/

**Comment by kingthorin** [comment]
FAQ for selective proxying: https://www.zaproxy.org/faq/what-options-exist-for-selective-proxying/

**Comment by SkypLabs** [comment]
> For web applications I'd recommend handling this in the browser, eg using an add-on like Foxy Proxy to selectively proxy specific URLs through ZAP (or not). But for mobile that could be tricky :/

Indeed, it's rather tricky on mobile devices, hence this feature request. I think HTTPS pass-through would be the easiest way to circumvent the problem and would make ZAP even more adaptable to all sorts of situations.

Thanks @thc202 for having changed the title, it's better this way!

**Comment by thc202** [comment]
This will be provided by the Network add-on.

**Comment by thc202** [comment]
Closing, with the merge of #7080 this feature should now be available.

**Comment by SkypLabs** [comment]
Great news! Many thanks.
