### ISSUE TITLE
Improve Content Security Policy Description

### ISSUE THREAD

**Issue by sgerlach** [zaproxy/zaproxy#6839]
**Describe the bug**
The Content Security Policy Plugin description could use some tweaking to help users understand what it's doing and or alerting on. The evidence provided is showing the existing CSP, but when it alerts, it's unclear that it's trying to tell you that a MISSING or overly lax setting is set in one of the headers.  Today, the scanner (I think) is looking for these values existence and weakness of setting

`script-src, style-src, img-src, frame-ancestors, connects-src, frame-src, font-src, media-src, object-src, manifest-src, worker-src, prefetch-src, form-action
`

https://github.com/zaproxy/zap-extensions/blob/main/addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ContentSecurityPolicyScanRule.java

Feedback from users is that when A value or multiple values exist and are correct, the alert description and evidence make it seem like the value in the evidence is what is being alerted upon, even though it is likely correct.

**To Reproduce**
1. Run scan with the CSP checker turned on with a website with a single CSP value
2. View the alert description and evidence
3. Become confused... :)

**Expected behavior**
The description of the alert possibly should mention what headers and values it's looking for and indicate the evidence is pointing out MISSING settings and or weak values.

**Software versions**
 - ZAP: 2.11
 - Add-on: Content Security Policy Passive Scan Rule (https://github.com/zaproxy/zap-extensions/blob/main/addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ContentSecurityPolicyScanRule.java)
 - OS: NA
 - Java: NA
 - Browser: NA

**Would you like to help fix this issue?**
Maybe, if this is simply adding text to the description. :)

**Comment by kingthorin** [comment]
As far as I know the wildcard description is actually really specific: https://github.com/zaproxy/zap-extensions/blob/8834d7ca048471b66ca096a741dec0aa578ee7d0/addOns/pscanrules/src/main/resources/org/zaproxy/zap/extension/pscanrules/resources/Messages.properties#L197

If it lists a directive then it's one impacted by the issue. If the list is as above then the answer is they're all impacted.

However, if you have ideas on clarifying then I'm all for it.

**Comment by sgerlach** [comment]
With a content security policy like this
`Content-Security-Policy: frame-ancestors 'none';`
Today you get this alert, which I think is at best misleading. I think it means to list the rest of the headers that are missing., but I could be wrong.

> CSP Scanner: Wildcard Directive MEDIUM
> Category:Information Leakage
> The following directives either allow wildcard sources (or ancestors), are not defined, or are overly broadly defined: frame-ancestor

**Comment by sgerlach** [comment]
Ahhhh I see the problem. It's a dynamic description issue. Not a bug, alert happened the right way. CLosing

**Comment by kingthorin** [comment]
Thanks for confirmation my Scott, saved me a bunch of testing and wracking my brain.
