### ISSUE TITLE
SQL Injection vulnerabilities not detected by zap-api-scan

### ISSUE THREAD

**Issue by marwagad** [zaproxy/zaproxy#6847]
Hello all,
I have tried to run the below commands for this API but it didn't show me any SQL injection vulnerabilities found although this site is vulnerable can anyone explain why, please. 

docker pull owasp/zap2docker-weekly  
docker run -t owasp/zap2docker-weekly zap-api-scan.py -t https://demo.testfire.net/login.jsp -f openapi

**Comment by psiinon** [comment]
Please dont ask questions as issues - the ZAP User Group is a much better forum for them: https://groups.google.com/group/zaproxy-users
