### ISSUE TITLE
New Error when running latest zap2docker-weekly docker image w/ Traceback

### ISSUE THREAD

**Issue by dfuentes77** [zaproxy/zaproxy#6850]
**Describe the bug**
Since last update of zap2docker image 2hrs ago, I'm getting error this error:

```
2021-10-04 18:10:50,633 Could not find custom hooks file at /home/zap/.zap_hooks.py 
Using the Automation Framework
Traceback (most recent call last):
  File "/zap/zap-baseline.py", line 648, in <module>
    main(sys.argv[1:])
  File "/zap/zap-baseline.py", line 403, in main
    copyfile(yaml_file, '/zap/wrk/zap.yaml')
  File "/usr/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/zap/wrk/zap.yaml'
```

when running this in our CI system:

```
      printf "Running zap2docker baseline scan against ${ENV}\n\n"
      docker run -v $(pwd):/zap/wrk/:rw --rm -it owasp/zap2docker-weekly \
          zap-baseline.py -c repo/ci/files/alerts.conf -I \
                          -r archive/"${ENV}-baseline-report-${SCAN_DATE}".html \
                          -t "${TEST_URL}"
```

I see a mention to using Automation Framework in [Changelog](https://github.com/zaproxy/zaproxy/blob/main/docker/CHANGELOG.md) but no mention as to what I need to add/change or any breaking changes that I need to account for.

**Expected behavior**
Prior to the update 2 hours ago, it ran with the normal PASS/WARN output as expected

**Software versions**
 - latest zap2docker image update on Oct 4th

**Comment by dfuentes77** [comment]
I'm setting `--autooff` for now until this is fixed, per:
https://www.zaproxy.org/blog/2021-06-15-baseline-scan-changes/

I've tried running it manually in a variety of ways in our CI system and checked if I can set a flag for where it'll read/write _**zap.yaml**_, but I can't seem to find that.

**Comment by psiinon** [comment]
Thanks for reporting this.
Does ZAP/Docker have write access to the cwd?
I'm assuming not, thats where it will try to write the zap.yaml file.
However it should still work without write access, so thats a bug - it should really just warn you and carry on.
