### ISSUE TITLE
OWASP ZAP File upload addon release in ZAP marketplace

### ISSUE THREAD

**Issue by preetkaran20** [zaproxy/zaproxy#6862]
**Add-on repo**
https://github.com/SasanLabs/owasp-zap-fileupload-addon

**Your contact details**
preetkaran20@gmail.com, @sasan_karan

**Are you one of the authors**
Yes

**Licence**
If not clearly stated in the repo.

**Build instructions**
https://github.com/SasanLabs/owasp-zap-fileupload-addon/releases/tag/1.1.0

**Link to more information**

**Twitter handle for tool or author(s)**
@sasan_karan

**Promote to Beta or Release?**
Note that all new add-ons start at Alpha status.

**Anything else we should know**

**Comment by thc202** [comment]
That's the same version already released to dev, right?

fyi, 2.11 is already available in Maven Central if you want to stop using the snapshot.
