### ISSUE TITLE
Introduce a new ZAP report variant/type which supports SARIF

### ISSUE THREAD

**Issue by de-jcup** [zaproxy/zaproxy#6875]
**Is your feature request related to a problem? Please describe.**

We want to integrate ZAP in our security orchestration  tool [SecHub](https://github.com/Daimler/sechub) but the existing reports do not contain enough data. We would prefer a [Sarif](https://docs.oasis-open.org/sarif/sarif/v2.1.0/sarif-v2.1.0.html) based report with data about request + response (body and header) and some more necessary information.

Inside this issue we want to clarify if the community would find this useful inside the existing Zap extension "reports" and a PR would be embraced or if there is a need for an own custom extension to handle this.

Also the information about the SARIF format structure shall be initial documented here  (not all wanted parts are directly available in SARIF , e.g. there is no dedicated field for recommendations -  see https://github.com/oasis-tcs/sarif-spec/issues/472 - and must be provided there by so called "property bags"). 

**Describe the solution you'd like**
A SARIF report containing all necessary information for a developer to understand and reprocude a vulernability. So a fix of the security bug becomes very easy.

**Describe alternatives you've considered**
- We thought about accessing/storing  the session. But this seems to be a data base dump and is no option
- We thought about using report "traditional-json" and transfer at our side to SARIF, but the request/response data is completely missing
- We thought about creating a new report variant "tracing-json" and adopt the thymeleaf parts so HTTP data from `Alert` will be available inside report. But there we would still need a transformation at SecHub side and also it's not clear if the ZAP community would like this. Providing a new report in SARIF format (which seems to become  the standard for SAST but contains also fields for web request and response and can be used for DAST as well) could be more helpful/needed.

**Additional context**
At https://github.com/Daimler/sechub we are just implementing an `OWASP Zap` `PDS` integration (see https://daimler.github.io/sechub/latest/sechub-product-delegation-server.html )
Our approach is to orchestrate the scan process make it easy to integrate in CI/CD without much effort and to help developers to identify, understand and to reproduce the security vulnerability easily.

The available report variants (see https://github.com/zaproxy/zap-extensions/tree/main/addOns/reports/src/main/zapHomeFiles/reports ) have not the fields of the full HTTP data to reproduce at developer site (Request header + body and related Response header and body).

IMHO it is very important for an developer to understand and to reproduce the problem, so it is easier to fix. OWASP Zap has all these information inside it's session - but not inside the machine readable reports.

**Would you like to help implementing this feature?**
Yes indeed, I will already start with an implementation in our fork and would provide a PR.
I think I understood the architectural concept and will add content below
 https://github.com/zaproxy/zap-extensions/tree/main/addOns/reports/src/main/zapHomeFiles/reports

**Comment by de-jcup** [comment]
Here our (SecHub team) thoughts about wanted output (it is not 100% correct JSON because of comments and using new lines, but this is only for documentation/understanding):

~~~json
{
	"runs": [
		{
			"results": [
				{
					"level": "error",
					"locations": [
						{
							"physicalLocation": {
								"artifactLocation": {
									"uri": "https://localhost:8081/greeting?name=%3C%2Fp%3E%3Cscript%3Ealert%281%29%3B%3C%2Fscript%3E%3Cp%3E"
								},
                                // either we use the region or just the property bag
                                "region": {
                                    "startLine": 10, // the line references to the webRequest.body line
                                    "snippet": {
                                        "text": "<p>XSS attackable parameter output: </p><script>alert(1);</script><p>!</p>"
                                    }
                                }
							},
                            "properties": {
                                // the attack and evidence do not have to be the same
                                "attack": "</p><script>alert(1);</script><p>",
                                "evidence": "</p><script>alert(1);</script><p>"
                            }
						}
					],
                    // the message from OWASP ZAP is very generic
                    // it is maybe the best to create a formatted message
                    // with placeholders
					"message": {
						"text": "Cross Site Scripting (Reflected) found in URI: {0}. Send attack vector {1} and the evidence {2} in the web response shows the attack was successful.",
                        "arguments": [ 
                            "https://localhost:8081/greeting",
                            "</p><script>alert(1);</script><p>",
                            "</p><script>alert(1);</script><p>"
                        ]
					},
                    // the pluginId of an alert should be used as ruleId
                    // see: https://www.zaproxy.org/docs/alerts/
                    // example: https://www.zaproxy.org/docs/alerts/40012/
					"ruleId": "40012",
                    "webRequest": {
                        "protocol": "HTTP",
                        "version": "1.1",
                        // in absolute form see: 5.3 in https://www.rfc-editor.org/rfc/rfc7230.txt
                        "target": "https://localhost:8081/greeting?name=%3C%2Fp%3E%3Cscript%3Ealert%281%29%3B%3C%2Fscript%3E%3Cp%3E",
                        // this is optional
                        "parameters": {
                            "name": "%3C%2Fp%3E%3Cscript%3Ealert%281%29%3B%3C%2Fscript%3E%3Cp%3E",
                            // or without the encoding
                            "name": "</p><script>alert(1);</script><p>"
                        },
                        "method": "GET",
                        "headers": {
                            "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:93.0) Gecko/20100101 Firefox/93.0",
                            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
                            "Accept-Language": "en-US,en;q=0.5",
                            "Authorization": "Basic dGVzdHVzZXI6cGFzc3dvcmQtMTIzNDU=", // should probably be obfuscated
                            "Connection": "keep-alive",
                            "Referer": "https://localhost:8081/hello",
                            "Cookie": "locale=de; JSESSIONID=2327E9EBE8342769A6DB1322562DD850",
                            "Upgrade-Insecure-Requests": "1",
                            "Sec-Fetch-Dest": "document",
                            "Sec-Fetch-Mode": "navigate",
                            "Sec-Fetch-Site": "same-origin",
                            "Sec-Fetch-User": "?1",
                            "Content-Length": "0"
                        },
                        "body": {
                            // both or only one of them
                            "text": "",
                            "binary": ""
                        }
                    },
                    "webResponse": {
                        "protocol": "HTTP",
                        "version": "1.1",
                        "statusCode": 200,
                        "reasonPhrase": "OK",
                        "headers": {
                            "Set-Cookie": "locale=de; HttpOnly; SameSite=strict",
                            "X-Content-Type-Options": "nosniff",
                            "X-XSS-Protection": "1; mode=block",
                            "Cache-Control": "no-cache, no-store, max-age=0, must-revalidate",
                            "Pragma": "no-cache",
                            "Expires": "0",
                            "Strict-Transport-Security": "max-age=31536000 ; includeSubDomains",
                            "X-Frame-Options": "DENY",
                            "Content-Security-Policy": "script-src 'self'",
                            "Referrer-Policy": "no-referrer",
                            "Content-Type": "text/html;charset=UTF-8",
                            "Content-Language": "en-US",
                            "Date": "Mon, 18 Oct 2021 07:25:32 GMT"
                        },
                        "body": {
                            // both or only one of them
                            "text": "<!DOCTYPE HTML>
                            <html>
                            <head>
                                <title>Getting Started: Serving Web Content</title>
                                <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
                            </head>
                            <body>
                                <!-- unsecure text used (th:utext instead th:text)- to create vulnerability (XSS) -->
                                <!-- simple usage: http://localhost:8080/greeting?name=Test2</p><script>;alert("hallo")</script> -->
                                <p >XSS attackable parameter output: </p><script>alert(1);</script><p>!</p>
                            </body>
                            </html>",
                            "binary": ""
                        },
                        "noResponseReceived": false
                    }
				}
			],
            "webRequests": [
                // as far as I understood: 
                // - only needed in case we have the same request multiple times and want to link to it via index
            ],
            "webResponses": [
                // as far as I understood: 
                // - only needed in case we have the same response multiple times and want to link to it via index
            ],
			"taxonomies": [
				{
					"downloadUri": "https://cwe.mitre.org/data/xml/cwec_v4.4.xml.zip",
					"guid": "f2856fc0-85b7-373f-83e7-6f8582243547",
					"informationUri": "https://cwe.mitre.org/data/published/cwe_v4.4.pdf/",
					"isComprehensive": true,
					"language": "en",
					"minimumRequiredLocalizedDataSemanticVersion": "4.4",
					"name": "CWE",
					"organization": "MITRE",
					"releaseDateUtc": "2021-03-15",
					"shortDescription": {
						"text": "The MITRE Common Weakness Enumeration"
					},
					"taxa": [
						{
							"fullDescription": {
								"text": "The software does not neutralize or incorrectly neutralizes user-controllable input before it is placed in output that is used as a web page that is served to other users."
							},
							"guid": "1a37bf66-7c5a-3aa0-94bb-ffae58a9e01c",
							"helpUri": "https://cwe.mitre.org/data/definitions/79.html",
							"id": "79",
							"shortDescription": {
								"text": "Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')"
							}
						}
					],
					"version": "4.4"
				}
			],
			"tool": {
				"driver": {
					"guid": "4d841334-0141-4e13-bdd0-53087266ebcd",
					"informationUri": "https://www.zaproxy.org/",
					"name": "OWASP ZAP",
					"rules": [
						{
                            // pluginId/alertRef
							"id": "40012",
							"defaultConfiguration": {
								"level": "error"
							},
                            // summary of plugin: https://www.zaproxy.org/docs/alerts/40012/
							"fullDescription": {
								"text": "Cross-site Scripting (XSS) is an attack technique that involves echoing attacker-supplied code into a user's browser instance. A browser instance can be a standard web browser client, or a browser object embedded in a software product such as the browser within WinAmp, an RSS reader, or an email client. The code itself is usually written in HTML/JavaScript, but may also extend to VBScript, ActiveX, Java, Flash, or any other browser-supported technology.
                                When an attacker gets a user's browser to execute his/her code, the code will run within the security context (or zone) of the hosting web site. With this level of privilege, the code has the ability to read, modify and transmit any sensitive data accessible by the browser. A Cross-site Scripted user could have his/her account hijacked (cookie theft), their browser redirected to another location, or possibly shown fraudulent content delivered by the web site they are visiting. Cross-site Scripting attacks essentially compromise the trust relationship between a user and the web site. Applications utilizing browser object instances which load content from the file system may execute code under the local machine zone allowing for system compromise.
                                
                                There are three types of Cross-site Scripting attacks: non-persistent, persistent and DOM-based.
                                Non-persistent attacks and DOM-based attacks require a user to either visit a specially crafted link laced with malicious code, or visit a malicious web page containing a web form, which when posted to the vulnerable site, will mount the attack. Using a malicious form will oftentimes take place when the vulnerable resource only accepts HTTP POST requests. In such a case, the form can be submitted automatically, without the victim's knowledge (e.g. by using JavaScript). Upon clicking on the malicious link or submitting the malicious form, the XSS payload will get echoed back and will get interpreted by the user's browser and execute. Another technique to send almost arbitrary requests (GET and POST) is by using an embedded client, such as Adobe Flash.
                                Persistent attacks occur when the malicious code is submitted to a web site where it's stored for a period of time. Examples of an attacker's favorite targets often include message board posts, web mail messages, and web chat software. The unsuspecting user is not required to interact with any additional site/link (e.g. an attacker site or a malicious link sent via email), just simply view the web page containing the code."
							},
                            // name
							"name": "Cross Site Scripting (Reflected)",
                            // in the json format those are called reference and a list of links as <p> elements
							"properties": {
                                "references": [
                                    "http://projects.webappsec.org/Cross-Site-Scripting",
                                    "https://owasp.org/www-community/attacks/xss/",
                                    "https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html",
                                    "https://owasp.org/www-project-top-ten/2017/A7_2017-Cross-Site_Scripting_(XSS)"
                                ],
                                // solution
                                "solution": {
                                    "text": "<p>Phase: Architecture and Design</p><p>Use a vetted library or framework that does not allow this weakness to occur or provides constructs that make this weakness easier to avoid.</p><p>Examples of libraries and frameworks that make it easier to generate properly encoded output include Microsoft's Anti-XSS library, the OWASP ESAPI Encoding module, and Apache Wicket.</p><p></p><p>Phases: Implementation; Architecture and Design</p><p>Understand the context in which your data will be used and the encoding that will be expected. This is especially important when transmitting data between different components, or when generating outputs that can contain multiple encodings at the same time, such as web pages or multi-part mail messages. Study all expected communication protocols and data representations to determine the required encoding strategies.</p><p>For any data that will be output to another web page, especially any data that was received from external inputs, use the appropriate encoding on all non-alphanumeric characters.</p><p>Consult the XSS Prevention Cheat Sheet for more details on the types of encoding and escaping that are needed.</p><p></p><p>Phase: Architecture and Design</p><p>For any security checks that are performed on the client side, ensure that these checks are duplicated on the server side, in order to avoid CWE-602. Attackers can bypass the client-side checks by modifying values after the checks have been performed, or by changing the client to remove the client-side checks entirely. Then, these modified values would be submitted to the server.</p><p></p><p>If available, use structured mechanisms that automatically enforce the separation between data and code. These mechanisms may be able to provide the relevant quoting, encoding, and validation automatically, instead of relying on the developer to provide this capability at every point where output is generated.</p><p></p><p>Phase: Implementation</p><p>For every web page that is generated, use and specify a character encoding such as ISO-8859-1 or UTF-8. When an encoding is not specified, the web browser may choose a different encoding by guessing which encoding is actually being used by the web page. This can cause the web browser to treat certain sequences as special, opening up the client to subtle XSS attacks. See CWE-116 for more mitigations related to encoding/escaping.</p><p></p><p>To help mitigate XSS attacks against the user's session cookie, set the session cookie to be HttpOnly. In browsers that support the HttpOnly feature (such as more recent versions of Internet Explorer and Firefox), this attribute can prevent the user's session cookie from being accessible to malicious client-side scripts that use document.cookie. This is not a complete solution, since HttpOnly is not supported by all browsers. More importantly, XMLHTTPRequest and other powerful browser technologies provide read access to HTTP headers, including the Set-Cookie header in which the HttpOnly flag is set.</p><p></p><p>Assume all input is malicious. Use an \"accept known good\" input validation strategy, i.e., use an allow list of acceptable inputs that strictly conform to specifications. Reject any input that does not strictly conform to specifications, or transform it into something that does. Do not rely exclusively on looking for malicious or malformed inputs (i.e., do not rely on a deny list). However, deny lists can be useful for detecting potential attacks or determining which inputs are so malformed that they should be rejected outright.</p><p></p><p>When performing input validation, consider all potentially relevant properties, including length, type of input, the full range of acceptable values, missing or extra inputs, syntax, consistency across related fields, and conformance to business rules. As an example of business rule logic, \"boat\" may be syntactically valid because it only contains alphanumeric characters, but it is not valid if you are expecting colors such as \"red\" or \"blue.\"</p><p></p><p>Ensure that you perform input validation at well-defined interfaces within the application. This will help protect the application even if a component is reused or moved elsewhere.</p>"
                                },
								"confidence": "medium" // possible values (false-positive, low, medium, heigh, confirmed)
							},
							"relationships": [
								{
									"kinds": [
										"superset"
									],
									"target": {
										"guid": "6bd55435-166c-3594-bc06-5e0dea916067",
										"id": "89",
										"toolComponent": {
											"guid": "f2856fc0-85b7-373f-83e7-6f8582243547",
											"name": "CWE"
										}
									}
								}
							],
                            // same as name
							"shortDescription": {
								"text": "Cross Site Scripting (Reflected)"
							}
						}
					],
					"semanticVersion": "2.11.0",
					"supportedTaxonomies": [
						{
							"guid": "f2856fc0-85b7-373f-83e7-6f8582243547",
							"name": "CWE"
						}
					],
					"version": "2.11.0"
				}
			}
		}
	],
	"$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
	"version": "2.1.0"
}
~~~

**Comment by de-jcup** [comment]
Inside the Issue only CWE should be implemented as taxonomy - easy to reference as `helpUri` and wellknwon.

**Comment by Jeeppler** [comment]
@psiinon, @thc202 and @kingthorin the pull request is out: https://github.com/zaproxy/zap-extensions/pull/3253.

**Comment by de-jcup** [comment]
@psiinon 

Actually, we wanted to make the SARIF support/reporting in Owasp Zap available to everyone who uses the ZAP.

Our SARIF reporting integration does work well and the PR was created, but unfortunately, the ZAP team  had strong concerns about the inclusion of the Sarif reporting in the original reporting. 

So I decided following: As before, we will integrate Sarif reporting into the reporting extension in our fork and keep it compatible and maintain it. So we can use it inside SecHub, enhance SARIF feature set and act very fast while we are integrating ZAP as a SecHUb PDS solution.

Should the ZAP team decide at some time that our SARIF solution might fit in well with the standard reporting, we are of course happy to create a PR again - we prefer "upstream first".

For details please look at https://github.com/zaproxy/zap-extensions/pull/3253#issuecomment-1010730391

Note: Please keep in mind that 2022-01-25 our fork repository will move from https://github.com/Daimler/zap-extensions/ to https://github.com/mercedes-benz/zap-extensions/ . Also sechub will move from https://github.com/Daimler/sechub to https://github.com/mercedes-benz/sechub

**Comment by psiinon** [comment]
Hi @de-jcup we do actually agree that this enhancement could be very useful for other ZAP users and we would like to include it in the ZAP code base.
We would just like it to be moved into a new add-on which can still live in the zap-extensions repo.
It can still be included in the ZAP Marketplace and could potentially be included as standard with ZAP.
We can help with the code restructuring if you like - it will not remove any features and as far as ZAP users will be concerned the UI will stay the same, it will just be in its own add-on.
There is a lot of code here and even if this was contributed by one of the ZAP Core Team I think we'd want it in its own add-on.

**Comment by de-jcup** [comment]
Hi @psiinon thank you for the response.

## Current situation
At the moment we (SecHub developer team) are running out of time (not only because of ZAP integration but also other stuff) and we still need some additions/changes/improvements etc. for SecHub report integration from the implemented ZAP sarif reporting. So I think having the changes currently all done inside the fork is the best and fastest solution. We want to integrate ZAP into SecHub as soon as possible.

When we have done the SecHub integration and all fits well, we will have more time and I will try another PR /discuss again how to integrate into official ZAP world. Maybe a video meetup would be a good option to get to know each other and to clarify some parts more easy.

## Future
### Another addon inside zap-extensions
#### Concerns
Here my concerns about moving it to another addon

- at least at the moment this is still just a specialized  reporting - so 2 reportings inside ZAP?
- an `APIimplementor` for another addon should (IMHO) normally have an unique identifier for the api. So I think the API
  would no longer be something with "..report.." inside and we would be forced to use something like "...sarif..." instead?
- an addOn should be IMO always autark and has no dependencies to other addOns (except it works like in OSGI where you have a dedicated extension mechanism). So I would have to copy (more or less) all reporting Java classes including UI  (e.g. reporting dialog, add a new toolbar icon) and reporting logic (thymeleaf,, helpers etc.) into the new addon as well? Or maybe I am wrong, it's just an assumption
- UX : users would have two ways to create a report?
- Documentation: additional descriptions of the new REST API parts (I am not sure, maybe this is generated automatically?) - would mean in this case that also most parts would be duplicated (because same like reporting addon)

#### Unclear
- Naming .. would be only "sarif" ?
- Would the core team be in charge for decisions on this addon and the future improvements there?
- ... more ... 

### An external addon hosted by SecHub team
#### Concerns
- same concerns like in "additional addon in zap-extensions" (copy code, etc.)
- hosting
- twitter account
- legal /group processes
- ... more...

**Comment by Jeeppler** [comment]
@psiinon my colleague @de-jcup explained the technical reason, why we have difficulties understanding the separate add-on request. However, I previously pointed out some organizational issues with a separate add-on approach: https://github.com/zaproxy/zap-extensions/pull/3253#issuecomment-1008705574.

We are more than happy to get in touch with the ZAP Core Team, to discuss this issue in more detail in the future. To get in contact with us have a look at the `MAINTAINERS.md` file in SecHub: https://github.com/Daimler/sechub.

However, for the next couple of weeks we will use the fork approach as it is the most efficient and comfortable approach for us.

**Comment by Jeeppler** [comment]
We have an update on this topic:

Daimler is now Mercedes-Benz. With the name change the GitHub repository changed it's name as well: https://github.com/mercedes-benz/sechub.

Furthermore, it is now possible to use SecHub and Owasp Zap together. We made this available to everybody: https://github.com/mercedes-benz/sechub/tree/develop/sechub-pds-solutions/owasp-zap

In addition, we have renewed interest in integrating the SARIF support into the Owasp Zap reporting add-on. We love to discuss this topic with @psiinon. To continue the communication, we would like to ask @psiinon to email J. Eppler and A. Tregnaghi. You can find the email address of both in the `MAINTAINERS.md` file.  The `MAINTAINERS.md` file can be found in the SecHub repository: https://github.com/mercedes-benz/sechub.

**Comment by psiinon** [comment]
@Jeeppler email sent :D

**Comment by de-jcup** [comment]
There exists a new PR for this feature - https://github.com/zaproxy/zap-extensions/pull/4078.

As discussed, this is inside the reporting extension, but without any changes to existing (other) code or resources and all parts are inside own folders/packages.

**Comment by Jeeppler** [comment]
@psiinon thanks for your help on this issue.

**Comment by psiinon** [comment]
A pleasure!
We're releasing the reports add-on right now, will post to the user group / twitter /mastodon once its available 😁

**Comment by Jeeppler** [comment]
@psiinon awesome, thank you 👍
