### ISSUE TITLE
Global alert Filter and Global Exclude URL is ignored for initial alerts when importing OpenAPI definition

### ISSUE THREAD

**Issue by kiwimato** [zaproxy/zaproxy#6877]
**Describe the bug**
There are 2 alerts which show up even if I enable Global alert Filter or Global Exclude URL for it:
  * X-Content-Type-Options
  * Incomplete or No Cache-control Header Set
  
The regex I'm using: `https?://.*/swagger/.*`
URL: `https://redacted.com/swagger/v1/swagger.json`

This happens for both the Docker API scan and for Desktop OWASP ZAP 2.11.0.
I also noticed that I don't have to actually scan for them to apear in the Desktop version, it's enough that i import the OpenAPI swagger.json file and they pop up.

**To Reproduce**
1. Open OWASP ZAP 2.11.0 latest version
2. Click Tools -> Options -> Set a Global alert filter and Global Exclude URL for `https?://.*/swagger/.*`. For alert filter check URL is Regex? and set Alert Type to `Incomplete or No Cache-control Header Set`
3. Import a swagger.json url which doesn't have the Cache-control header set.
4. See alert pop up in Alerts tab

**Expected behavior**
I would expect it to be ignored completely.

**Software versions**
 - ZAP: 2.11.0
 - OS: Linux latest Manjaro & docker image build by you guys.
 - Java: openjdk 11.0.12 2021-07-20

**Would you like to help fix this issue?**
Sure.

**Comment by thc202** [comment]
Requests sent directly from ZAP (like the import) are not affected by the global exclusions. The alert filter should work though.

**Comment by kingthorin** [comment]
[Tested,](https://www.regexplanet.com/share/index.html?share=yyyypdehjnr), thought it might be an issue with slashes and escaping, but seems not.

**Comment by kingthorin** [comment]
Thanks for the details, I’ll see if I can re-create.

**Comment by kingthorin** [comment]
No problem, thanks for following up!
