### ISSUE TITLE
JavaFX error for "Render HTML" at startup.

### ISSUE THREAD

**Issue by HarshilPatel007** [zaproxy/zaproxy#6878]
**Describe the bug**
I got this error at the startup of OWASP ZAP 2.11.0 .
please see screenshots for the error info.

**To Reproduce**
1. start zap 2.11.0
2. See error

**Screenshots**
![Screenshot from 2021-10-18 17-13-08](https://user-images.githubusercontent.com/16424866/137724454-bd271f84-eca8-4e63-a2ea-8c36e43fb7ef.png)
![Screenshot from 2021-10-18 17-16-35](https://user-images.githubusercontent.com/16424866/137724460-91b8cd2e-51b7-4958-8517-ffe3f0b9e24e.png)

**Software versions**
 - ZAP: 2.11.0
 - Add-on: Browser View 5.0.0
 - OS: Linux
 - Java: java-17-openjdk , java-openjfx 17
 - Browser: [e.g. chrome 94]

**Comment by HarshilPatel007** [comment]
> As the message says, that happens when JavaFX is not available.

But, I've java-openjfx installed.

**Comment by HarshilPatel007** [comment]
> Installed is not the same as available though, with newer Java versions you need to allow access to JavaFX (#6728 shows the additional changes required).

so, how can I allow access to JavaFX ..????

**Comment by thc202** [comment]
The [changes in #6728](https://github.com/zaproxy/zaproxy/pull/6728/files) show how, you need to edit the startup script and add the parameters.

**Comment by HarshilPatel007** [comment]
> The [changes in #6728](https://github.com/zaproxy/zaproxy/pull/6728/files) show how, you need to edit the startup script and add the parameters.

did the changes as mentioned in the pull request.
got this error.
```
Found Java version 17
Available memory: 3797 MB
Using JVM args: -Xmx949m
Error occurred during initialization of boot layer
java.lang.LayerInstantiationException: Package jdk.internal.jimage.decompressor in both module java.base and module jrt.fs
```

**Comment by kingthorin** [comment]
No further input in 13mo. Closing.
