### ISSUE TITLE
ZAP Session timeout - Websocket Token base Authentication 

### ISSUE THREAD

**Issue by ChapsRo** [zaproxy/zaproxy#6879]
Hi, I am stuck on a web-app assessment which is hosted in a Embedded system. Apart from the login sequence, all communication related to session is happening through websockets. Once the login credentials are provided, the connections is upgraded and the credentials are passed through websocket. The application responds with a token which will be checked every 3 second through websocket keepalive request. 

While I intercept the request through ZAP proxy, this session is getting timeout within few seconds and I can't capture any requests post authentication. I have set the options like "Exclude Websocket" , "Forward all websocket communication" etc, but nothing worked. Please let me help in this case
<img width="676" alt="Capture" src="https://user-images.githubusercontent.com/65649241/137728253-8666bca5-8adc-4596-8b40-053a8b926462.PNG">
.

**Comment by psiinon** [comment]
Please dont ask questions like this as issues.
The ZAP User group is a much better place for them: https://groups.google.com/group/zaproxy-users
