### ISSUE TITLE
bugtracker: Address Deprecations

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#6893]
The last few dependency updates have introduced deprecations in the [bugtracker](https://github.com/zaproxy/zap-extensions/tree/main/addOns/bugtracker) add-on. As mentioned here: https://github.com/zaproxy/zap-extensions/pull/3273

They should be addressed.

**Comment by thc202** [comment]
@iamdebojyoti are you still working on this issue?

**Comment by iamdebojyoti** [comment]
@thc202, sorry I am busy with another issue. Please assign it to @kaash-bot

**Comment by thc202** [comment]
No problem, done.

**Comment by thc202** [comment]
First you should set up your dev env, docs in: https://www.zaproxy.org/docs/developer/

Once you have zap-extensions repo you need to look at the deprecations warnings in the bug tracker add-on, and address them.

**Comment by kingthorin** [comment]
I'd have to look at the library but there should still be a way to auth with username/PAT, no oauth necessary.

**Comment by kingthorin** [comment]
Looks like there are some examples on: https://github-api.kohsuke.org/

**Comment by kingthorin** [comment]
Setup a junk repo (https://GitHub.new), create a PAT, build the add-on, use ZAP with the built add-on.

**Comment by kingthorin** [comment]
I don’t know. That’s kind of the point of the issue. If all the details were obvious and known then the work would already be done.

**Comment by kingthorin** [comment]
@kaash-bot are you tackling this or not?

**Comment by kingthorin** [comment]
Okay, thanks for giving it a shot.

**Comment by nikhildougall** [comment]
Hi, is this issue open?

**Comment by kingthorin** [comment]
Yes, and yes 👍

**Comment by thc202** [comment]
@nikhildougall are you still working on this? Any questions?

**Comment by nikhildougall** [comment]
Hi @thc202 , sorry got busy with another task. I am trying to find the alternative for github account login which is deprecated in the code. I got one solution that we should use PAT in that, but in that we need that token . So I am stuck in that like how to get it. Trying to find the way out.

**Comment by thc202** [comment]
That will be provided by the user (instead of the username/password).

**Comment by nikhildougall** [comment]
What if instead of taking password we just oauth token and just  change this deprecated function- GitHub.connectUsingPassword(username, password) to this - GitHub.connectUsingOAuth(password)  and in this password will be oue oauth token?

**Comment by kingthorin** [comment]
As you prefer. That will mean also making changes to the UI.
Going from username/password to username/PAT seemed easiest to me but I’m not stuck on that idea.

**Comment by kingthorin** [comment]
https://docs.github.com/en/rest/overview/other-authentication-methods#via-oauth-and-personal-access-tokens seems to suggest that’s PATs are oauth tokens 🤷‍♂️

**Comment by nikhildougall** [comment]
Yeah correct.

**Comment by thc202** [comment]
@nikhildougall let us know if we can help with anything.

**Comment by kingthorin** [comment]
I can confirm that the existing functionality works by simply providing a PAT where password is requested. Therefore this change should be essentially trivial. If there's no update by 2022-03-21 I'll probably go ahead with it.
