### ISSUE TITLE
Unable to use replace.full_list(0).replacement= in .prob file if the string contains a space

### ISSUE THREAD

**Issue by so87** [zaproxy/zaproxy#6899]
zap-api-scan.py -z -configfile <location>

can't have a space in the config file. Can't do \x20 or "\"

**Comment by kingthorin** [comment]
Do it in desktop, check the config file to see how it’s saved?

**Comment by thc202** [comment]
Might worth looking at https://docs.oracle.com/javase/8/docs/api/java/util/Properties.html#load-java.io.Reader- to know how the file is read (and the escapes).

**Comment by so87** [comment]
@kingthorin I'm not sure how to look at a default .zap file. I am not sure how to configure a .prop file settings in the zap interface and then have it save to a file. I have only been working with the API scripts and have been trying to make .prop file myself but the documentation for "replacer" didn't seem to cover how to make spaces in your variable names.

@thc202 so here is my string:
"Basic base64string="
So based on that doc i should do that:
"Basic\ base64string\="
Right?

Or should i do the space as: "\u0020"

**Comment by so87** [comment]
I would proxy the zap-api script through zap or burp but i am not sure how to do that. on the commandline, there is no option to specify a proxy. So through all of this, i just see a bunch of errors in my report, without being able to see what i am actually sending.

**Comment by thc202** [comment]
Could you provide the whole line that you are having problems with? The space in that location should not need to be escaped.

**Comment by kingthorin** [comment]
> @kingthorin I'm not sure how to look at a default .zap file. I am not sure how to configure a .prop file settings in the zap interface and then have it save to a file. I have only been working with the API scripts and have been trying to make .prop file myself but the documentation for "replacer" didn't seem to cover how to make spaces in your variable names.

I wasn't suggesting reversing a *.zap (not sure where that idea came from, those are zap add-ons). Not talking about the .prop file either. I was suggesting that you fire up ZAP in desktop mode, create the rule in the GUI, exit zap, and look at the xml config file.

https://www.zaproxy.org/faq/how-do-you-find-out-what-key-to-use-to-set-a-config-value-on-the-command-line/

**Comment by so87** [comment]
@thc202 
formhandler.fields.field(0).fieldId=accountId
formhandler.fields.field(0).value=asdfasdfasdfasdfasdf
formhandler.fields.field(0).enabled=true
replacer.full_list(1).description=Authorization
replacer.full_list(1).enabled=true
replacer.full_list(1).matchtype=REQ_HEADER
replacer.full_list(1).matchstr=Authorization
replacer.full_list(1).regex=false
replacer.full_list(1).replacement=Basic asdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfI\=

**Comment by so87** [comment]
@kingthorin sorry i didn't mean .zip, i mean't .prop. 
I made the following config on MAC
![image](https://user-images.githubusercontent.com/13263774/139695223-3130fc06-e052-4b96-ba51-5807115cb5c0.png)

where do i look for the config file?

**Comment by thc202** [comment]
Where you have `(1)` you should use `(0)`, since there's no other replacer rule being defined.

**Comment by so87** [comment]
@thc202 ha that did the trick. Sorry for the silly error and thanks for the help!

**Comment by so87** [comment]
@thc202 is there a way i can proxy all of my zap command line scans so that way in the future i can see what i am sending?

**Comment by psiinon** [comment]
The plan is for you to be able to export (nearly) everything you do in the desktop as an Automation Framework plan.
https://www.zaproxy.org/docs/automate/automation-framework/

**Comment by so87** [comment]
@thc202 nevermind i found the answer here: https://github.com/zaproxy/zaproxy/issues/6707
