### ISSUE TITLE
owasp/zap2docker-bare image does not contain zap-baseline.py script

### ISSUE THREAD

**Issue by FrederikCampagne** [zaproxy/zaproxy#6914]
In the documentation it states that the docker images all have the zap-baseline.py script. However when I inspect the contents of the owasp/zap2docker-bare image it's not there.

**Comment by psiinon** [comment]
OK, thats a documentation issue then, the bare image is deliberately minimilistic.
Can you let us know where you saw that?

**Comment by FrederikCampagne** [comment]
https://www.zaproxy.org/docs/docker/about/

It states that all docker images can run the following set of packaged scan
scripts:
- Baseline scan
-Full scan
- Api scan

Also, I get that it's deliberately minimalist. However, what can it run? It
doesn't say clearly.

**Comment by thc202** [comment]
It can run ZAP.

**Comment by FrederikCampagne** [comment]
Hahaha, fair enough. They all do, very true.

**Comment by psiinon** [comment]
`For the bare release (a very small Docker image, contains only the necessary required dependencies to run ZAP, ideal for CI environments):` seems to say it all ;)
PR submitted to fix the issue :)
