### ISSUE TITLE
Retire HTTPSInfo / TLS Debug

### ISSUE THREAD

**Issue by globeone** [zaproxy/zaproxy#6918]
**Describe the bug**
When checking the TLS ciphers using HTTPSInfo the first line reports a StringIndexOutOfBoundsException error and then only shows a few of the actual ciphers on the web server, and none of the TLS1.3 ciphers. 

An exception occurred while updating the General panel. Problem fetching certificate. `err=java.lang.StringIndexOutOfBoundsException: begin 4, end -1, length 22`Cipher Suites Supported:
TLS_DHE_RSA_WITH_AES_256_GCM_SHA384(0x9f)(MEDIUM,TLSv1.2)
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256(0xc02f)(STRONG,TLSv1.2)
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384(0xc030)(STRONG,TLSv1.2)
TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256(0xcca8)(STRONG,TLSv1.2)

**To Reproduce**
1. Go to 'a URL in the sites panel'
2. Right Click on 'one of the URL and choose HTTPSInfo'
3. Move to the HTTPSInfo tab
4. See error ::
5. An exception occurred while updating the General panel. Problem fetching certificate. `err=java.lang.StringIndexOutOfBoundsException: begin 4, end -1, length 22`Cipher Suites Supported:

**Expected behavior**
For HTTPSInfo to show all the available Cipher suites for the URL

**Screenshots**
![image](https://user-images.githubusercontent.com/10052587/141121720-9794ebbf-04c1-4321-b951-beb66f13ab54.png)

**Software versions**
 - ZAP: ZAPD_2021-11-08
 - Add-on: HTTPSInfo Alpha 13.0.0 
 -  OS: Windows 10
 - Java: 
 java -version
openjdk version "11.0.12" 2021-07-20 LTS
OpenJDK Runtime Environment (build 11.0.12+7-LTS)
OpenJDK 64-Bit Server VM (build 11.0.12+7-LTS, mixed mode)
 - Browser: Chrome Version 95.0.4638.69 (Official Build) (64-bit)

**Errors from the zap.log file**
[log_httpsinfo.log](https://github.com/zaproxy/zaproxy/files/7513081/log_httpsinfo.log)

**Additional context**
From the log it looks like DeepViolet is the source of the issue. I also see that DeepViolet no longer has a maintainer. A shame, as Weak TLS is a compliance issue that should really be a part of the alerts. Using nmap --script ssl-enum-ciphers or an external parties tool outside the network can cause problems and is frowned upon when scanning internally.

https://github.com/spoofzu/DeepViolet

**Would you like to help fix this issue?**
Happy to provide detailed bug reports and test fixes.

**Comment by thc202** [comment]
This is a known issue spoofzu/DeepViolet#279.

**Comment by globeone** [comment]
Since DeepViolet is no longer maintained, is it worthwhile removing the HTTPSInfo plugin, as it's giving incorrect information?

**Comment by kingthorin** [comment]
You tell us. Would you rather be able to use it for 1.0, 1.1, and 1.2 assessments or would you rather it was dropped because of a 1.3 issue?

**Comment by globeone** [comment]
HTTPInfo is giving incorrect information even for TLS1.2 ciphers.  HTTPSInfo returned only 2x of the TLS1.2 ciphers when there are 5x TLS1.2 and 3x TLS1.3 ciphers set, so it's not reliable at all. In my humble opinion, it can be more dangerous to offer a broken tool giving incorrect information, especially when relying on the tool to make compliance and auditing decisions based on the results. 

Unless there are plans to maintain DeepViolet or find another solution to get the full set of TLS ciphers, then my recommendation would be to disable or remove the HTTPSInfo plugin. 

Possibly with a recommendation to add documentation on adding nmap --script-ssl-enum-ciphers as an external application in ZAP. As, nmap is very reliable in getting TLS ciphers.

**Comment by kingthorin** [comment]
I'm okay with us retiring it. @psiinon @thc202 @ricekot thoughts?

**Comment by psiinon** [comment]
Maybe post to the user group saying that we are going to retire it unless someone wants to step up and maintain it?
That gives people warning of what we're going to do and might just encourage someone to take it on?

**Comment by kingthorin** [comment]
Sure, I'll post something.

**Comment by globeone** [comment]
### workaround

For anyone finding this ticket and needed TLS cipher scanning the workaround is as follows:

You'll need to have "nmap"  installed on your machine for this to work.
You can get Nmap from https://nmap.org/download.html

Go to
 

- > Tools..
- >  Options..
- >  Applications

and fill in the Nmap option as such:

- > Display Name: NMAP TLS Enum Ciphers
- > Full command: the full path to the Nmap binary on your machine 
- > Working Directory: same as the binary
- > Parameters: --script ssl-enum-ciphers %host%
- > and check all the boxes

![image](https://user-images.githubusercontent.com/10052587/141143451-6a50f3cc-6395-4ef2-99bd-2dade9667834.png)

Then when you right-click on a URL in the Sites panel and choose run application

![image](https://user-images.githubusercontent.com/10052587/141143985-95d3bced-7a34-4fdf-80ea-79edd135896a.png)

ZAP will return the Ciphers from NMAP in the Output Tab

![image](https://user-images.githubusercontent.com/10052587/141144345-ab654fe6-4c27-48d4-9593-2efc741c7fa4.png)

**Comment by kingthorin** [comment]
Thanks! Tweeted: https://twitter.com/owasp_wstg/status/1458462516707741702

**Comment by thc202** [comment]
That's the same number of ciphers as reported by HTTPSInfo add-on (for TLSv1.2).

**Comment by globeone** [comment]
> That's the same number of ciphers as reported by HTTPSInfo add-on (for TLSv1.2).

For this URL, for another URL that I scanned yesterday, the output was incomplete as described earlier with missing ciphers.

![image](https://user-images.githubusercontent.com/10052587/141150070-9a79c75d-12b9-41db-9ff6-643b1792b41f.png)

**Comment by thc202** [comment]
Thank you for the clarification, did nmap also report the 5 ciphers?

**Comment by globeone** [comment]
This is what NMAP sees for the URL so yes, NMAP shows all the Ciphers. 

![image](https://user-images.githubusercontent.com/10052587/141156303-396ff6cc-8c31-4255-849c-5d78ae1915d7.png)

**Comment by thc202** [comment]
@kingthorin could you also include TLS Debug in your post? That one is no longer working properly with Java 11+ and if there are not that many users relying on it it could be retired too (IMO).

**Comment by kingthorin** [comment]
Okay

**Comment by thc202** [comment]
Thanks.

**Comment by kingthorin** [comment]
- https://groups.google.com/g/zaproxy-users/c/bHUBByCmYHE
- https://twitter.com/zaproxy/status/1458609176599478274

**Comment by kingthorin** [comment]
Assigning myself for now. The thread currently only has 14 views, the tweet has been retweeted 4 times and gathered 12 likes. However, so far no objections.

Will provide an update in ~1week with a decision.

**Comment by kingthorin** [comment]
Note there has not been anyone speak against the idea of retiring these. In 3320 I've suggested that the user could take HttpsInfo 3rd party if they like (as yet, no response to that idea either).

**Comment by kingthorin** [comment]
No objections after a week.

I'll start putting together the removal PRs.

**Comment by psiinon** [comment]
There _may_ be someone interested in looking at these .. I've just pinged them ...

**Comment by thc202** [comment]
It could still be maintained as a 3rd party add-on(s).

**Comment by kingthorin** [comment]
Closing. The add-ons have been retired and removed from Crowdin.

If someone wishes to take either third party and work on them they can be retrieved in their latest state from the following commit: https://github.com/zaproxy/zap-extensions/tree/c87edcecfcd8f790de30bb99db5e2c462f6028d9/
