### ISSUE TITLE
Load scripts via "zap-baseline.py" script  for CI/CD

### ISSUE THREAD

**Issue by Zilborg** [zaproxy/zaproxy#6930]
**Is your feature request related to a problem? Please describe.**
For authentication and ANTI-CSRF and etc. scripts loading and check in CI/CD. 

**Describe the solution you'd like**
Add option in `zap-baseline.py` script for loading.

**Would you like to help implementing this feature?**
I've implemented this in pull request and it working for my case.

**Comment by psiinon** [comment]
This is already possible, albeit not as easy as it could be.
I dont think we should be extending the packaged scans for these sort of things - the Automation Framework is how we should support them going forwards: https://www.zaproxy.org/docs/automate/automation-framework/

**Comment by Zilborg** [comment]
In this point (https://www.zaproxy.org/docs/automate/automation-framework/) I don't see authentication and Anti-CSRF options.
Via my wrap I can export scripts from ZAP Desktop to container via baseline and include check from different roles in CI/CD and it does not mean deploy ZAP API like stand alone server.

**Comment by psiinon** [comment]
The AF is being actively developed - initial auth support is here: https://www.zaproxy.org/docs/desktop/addons/automation-framework/environment/
In time it will support all of the auth and ant-csrf features that ZAP supports :)

**Comment by kingthorin** [comment]
Per above and the discussion on the associated PR this seem addressed.
