### ISSUE TITLE
ZAP not reporting the Content-Security-Policy (CSP) Header Missing vulnerability

### ISSUE THREAD

**Issue by Tarvinder91** [zaproxy/zaproxy#6935]
**Describe the bug**
The website doesnt have CSP headers but the tool is not reporting the vulnerability.

**To Reproduce**
Scan the website using both Spider and Ajax spider. The website (cant share due to security) doesnt implement the CSP headers but the tool doesnt report any. The other tools like veracode and SecurityScorecard both report this 

**Expected behavior**
The following vulnerability should also be reported.

CWE-829: Inclusion of Functionality from Untrusted Control Sphere
https://cwe.mitre.org/data/definitions/829.html
https://content-security-policy.com/

**Screenshots**
These are the only list of vulnerabilities found. CSP missing isnt included in any
![onlythesevulnerabilities](https://user-images.githubusercontent.com/32476445/142038864-99163483-8b55-499d-803d-0cb8247e639f.JPG)

**Software versions**
 - ZAP: 2.11.0
 - Add-on: Name and version [e.g. Passive Scan Rules Alpha v19. https://www.zaproxy.org/faq/how-do-i-see-what-version-of-an-add-on-extension-i-have-installed/]
 - OS: Windows 10
 - Java: java version "1.8.0_311"
   Java(TM) SE Runtime Environment (build 1.8.0_311-b11)
   Java HotSpot(TM) 64-Bit Server VM (build 25.311-b11, mixed mode)
 - Browser: Firefox94

**Would you like to help fix this issue?**
Cant help much

**Comment by thc202** [comment]
Was Passive scanner rules (beta) installed? https://www.zaproxy.org/docs/alerts/10038/

**Comment by Tarvinder91** [comment]
No. Its running on default rules. I will install them and get back

**Comment by Tarvinder91** [comment]
Passive Scanner Rules v 36.0.0 was installed by default. Do we need the beta version?

**Comment by psiinon** [comment]
Yes - https://www.zaproxy.org/docs/alerts/10038/ Status: Beta

**Comment by Tarvinder91** [comment]
Yes after installing the beta version, I can see the vulnerability. Thank you so much.
