### ISSUE TITLE
Suggest Renaming X-Frame-Options Header Not Set rule

### ISSUE THREAD

**Issue by davewichers** [zaproxy/zaproxy#6937]
Per: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options - X-Frame-Options is obsolete, replaced by CSP frame-ancestors. I think CSP frame-ancestors has been out long enough and is well supported enough that this ZAP rule should be titled with the current recommendation, rather than the old one. The rule should still look for both of course, and only flag when both are not there, but should 'by title' recommend the recommended header, not the obsolete one.

**Comment by kingthorin** [comment]
Seems reasonable, we could name it more generically. Something about clickjack prevention or framing control.

**Comment by davewichers** [comment]
I think that's a good idea. I think 'Missing Anti-Clickjacking Header' or something like that would be better, and would stand the test of time if the header name/type evolves again.
