### ISSUE TITLE
Snapshot Session As... -- Returns unhelpful message: 'Error saving session snapshot'

### ISSUE THREAD

**Issue by davewichers** [zaproxy/zaproxy#6938]
I'm using ZAP 2.11.0, and when I invoke Snapshot Session As..., an error dialog comes up and says only: 'Error saving session snapshot'.

This isn't very helpful. Seems like the error dialog should explain why, somehow. Or an error message should appear in the Output tab, but I can't find anything useful.

Any clue what the problem might be? And also why it doesn't provide more info? (Can we improve that?)

I don't have the session Persisted. Do you have to do that first before you can use this feature? If so, then the error dialog should explain that. I have no clue if that is the cause of the problem.

UPDATE: I successfully invoked Persist Session... first, and then tried Snapshot Session As..., and now it works. So if you have to do A before you can use B, then can the error dialog be updated to explain that?  I have no idea if there are ANY other features like this in ZAP, but if there are, all of them should be updated to be more explanatory like this. (Thx)

**Comment by kingthorin** [comment]
Thanks for following up

**Comment by davewichers** [comment]
You're welcome. I know we can improve the error message, but as an alternative, is there a way to make it work without requiring Persist Session be enabled first?  Might be slower, but it should be possible shouldn't it?

**Comment by kingthorin** [comment]
I’ll have to look at the code, I was thinking more that snapshot should be disabled if the session hasn’t already been persisted.

**Comment by thc202** [comment]
It will not be slower, it's just how it was designed, creating snapshots for temporary sessions might not be the best or expected behaviour.

Agreed, disable and inform with tooltip why.
