### ISSUE TITLE
ARM/M1 support for docker image

### ISSUE THREAD

**Issue by idontusenumbers** [zaproxy/zaproxy#6944]
Using the existing image doesn't work, even emulated, on M1 Mac; the webswing page hangs mid load.

I might recommend the following changes to the dockerfile to get native ARM/M1 support:

1. Update the base image for the builder to use am ARM JDK, like `bellsoft/liberica-openjdk-alpine:11`
2. Remove JAVA_HOME bits because
  a) They are platform-specific which causes rebuilding on ARM to pull the ARM ubuntu image then reference the x86 JRE
  b) They don't seem to be required; I removed them and the app works fine

Finagling the image a bit more to pull files from git into the builder then copy from builder into the image, I was able to get zap running pretty well on my M1 mac mini. For an official build, pulling from git wouldn't be relevant.

**Comment by psiinon** [comment]
Right now I'm not aware of anyone in the core team having access to an M1.
You can submit a PR and we can validate that it doesnt impact other platforms but theres not much point in any of us working on it if we cant test it...

**Comment by idontusenumbers** [comment]
How about a raspberry pi?

**Comment by psiinon** [comment]
Did that years ago :D https://github.com/zaproxy/zaproxy/wiki/zappi

**Comment by idontusenumbers** [comment]
I'm suggesting building and testing the aarch64 docker image on a Raspberry Pi then M1 macs can use that image

**Comment by nigamelastic** [comment]
I just got an M1 mac, If there is a guide/documentation on compiling it, may be i can send a PR with a build? unfortunately i couldnt find any

**Comment by idontusenumbers** [comment]
@nigamelastic you can just change the base image for the build phase to one that has an arm variant, and remove the explicit x86 path for the JRE in the latter phase. The main base image, ubuntu, already publishes an arm variant.

**Comment by anarang** [comment]
I recently got a Mac M1 and have been facing trouble running the zaproxy container on mac m1, I reported the issues I am facing here: https://github.com/RedHatProductSecurity/rapidast/issues/12 
@nigamelastic can you please suggest the base image to use and which Dockerfile https://github.com/zaproxy/zaproxy/tree/main/docker to make changes to. Looking for some help here. thanks.

**Comment by nigamelastic** [comment]
Sorry for the late response, I somehow missed these comments.
@anarang  simply compile the sources or install it from homebrew that worked for me
@idontusenumbers sorry I did not get that, if its still not available please tell me how can I help

**Comment by idontusenumbers** [comment]
@nigamelastic I see the latest Dockerfile is still referencing the explicit platform in the JAVA_HOME (you can just remove that line) https://github.com/zaproxy/zaproxy/blob/main/docker/Dockerfile-stable#L74

After that, the multi arch builds would need to be enabled; see https://docs.docker.com/desktop/multi-arch/

**Comment by darunesh-RH** [comment]
Building image and running by replacing https://github.com/zaproxy/zaproxy/blob/main/docker/Dockerfile-stable#L2 with **FROM bellsoft/liberica-openjdk-alpine:11 AS builder**  and removing java path at https://github.com/zaproxy/zaproxy/blob/main/docker/Dockerfile-stable#L74 in Dockerfile-stable, I am able to run zaproxy on Mac M1 arch.

**Comment by anarang** [comment]
I updated the comment on the original thread in rapiDAST repo here: https://github.com/RedHatProductSecurity/rapidast/issues/12#issuecomment-1117307233

In addition, I tried to run a basic scan using zap-baseline.py in the image provided by @darunesh-RH and here is the output:
Reference: https://www.zaproxy.org/docs/docker/baseline-scan/ 

```
$ docker pull usr7771/zap-mac-m1:zap-mac-m1
$ docker run -it usr7771/zap-mac-m1:zap-mac-m1                                                                                                                                                                                    2
zap@db7655738e32:/zap$ zap-baseline.py -t https://anishanarang.com -r report-an.html
2022-05-04 13:34:45,899 Could not find custom hooks file at /home/zap/.zap_hooks.py 
2022-05-04 13:34:45,899 A file based option has been specified but the directory '/zap/wrk' is not mounted 
Usage: zap-baseline.py -t <target> [options]
    -t target         target URL including the protocol, e.g. https://www.example.com
Options:
    -h                print this help message
......
```
What do you think can possibly be the issue here? 
thanks for the help here @darunesh-RH , I suggest you can raise a PR with the fix you updated in text above and we should be able to test out the changes thoroughly.

**Comment by thc202** [comment]
The issue is `A file based option has been specified but the directory '/zap/wrk' is not mounted`.

**Comment by kingthorin** [comment]
`A file based option has been specified but the directory '/zap/wrk' is not mounted` seems to cover it.

You need to write the report somewhere it can actually write.

**Comment by psiinon** [comment]
Read the docs? :)
If you run the command with `-h` you get lots more info along with a link to https://www.zaproxy.org/docs/docker/baseline-scan/ which has even more...

**Comment by anarang** [comment]
@psiinon thanks, it worked! sorry I missed it in the docs.
