### ISSUE TITLE
Provide argument based alert messages instead of generic

### ISSUE THREAD

**Issue by de-jcup** [zaproxy/zaproxy#6945]
**Is your feature request related to a problem? Please describe.**
Some commercial security tools do provide parametrized messages which are really nice to read for end users when it comes to automated scans.

While implementing SARIF reporting (see https://github.com/zaproxy/zaproxy/issues/6875) I recognized, that the
messages available in `ReportData`/`Alert` instances are very generic.

The sarif format provides arguments for texts and initially I would tried to provide sarif result messages like:
```json
"message": {
	"text": "Cross Site Scripting (Reflected) found in URI: {0}. Send attack vector {1} and the evidence {2} in the web response shows the attack was successful.",
         "arguments": [ 
             "https://localhost:8081/greeting",
             "</p><script>alert(1);</script><p>",
              "</p><script>alert(1);</script><p>"
      ]
},
```
But this is not possible, because there is no API.  So inside SARIF reporting, the normal description etc. is used instead.

**Describe the solution you'd like**
I would like to have the possibility to access a parameterized user message like

```java
// some pseudo java code for usage explanation
...
Alert alert = fetchTheAlert();
MessageData  messageData = alert.getDescriptionMessage();

String text = null;
if (messageData != null){
   MessageFormat messageFormat =  messageData.getFormat();
   Object[] messageArguments = messageData.geArguments()

   text = messageFormat.format(messageArguments);
}else{
   // no dedicated message found, so fallback to standard text
   text  = fetchStandardText();
}
...

```

So every report could contain a very details message for the user. The messages could be implemented step by step, so no "BigBang" necessary.
Of course this could also be used inside the ZAP UI to provider a better UIX (e.g. for a tooltip when hoovering over an alert)

**Describe alternatives you've considered**
- Improve Sarif/Reporting: The reports shall be "dumb" at my opion and implementing any additional logic here would make no sense there. The logic of those things must handled inside zaproxy (IMHO)
-  just provide the generic text (as done in SARIF reporting now)

**Would you like to help implementing this feature?**
Maybe

**Comment by thc202** [comment]
The descriptions are expected to be generic since that applies to all alerts of the same type.

**Comment by kingthorin** [comment]
When ZAP raises alerts the person that implemented the scan rule already had a chance to add finding specific details in the description etc. there are a number of rules that do this.

**Comment by de-jcup** [comment]
@kingthorin : The SARIF format does provide here a possibility to separate the message from parameters. But when the message of the alert rule does already add finding specific details this should be good enough. 

Maybe this feature request would not bring much benefit here - to have the parameters available inside the Alert objects would be nice, but brings much effort (IMHO) and what exactly could tools do with it? The SARIF specification does provide arguments, but ... what exactly should we an application do with it?

 @jeeppler: When the alert rules are in charge of providing the description and some alert rules do already add finding specific data inside the description.... What do you think?

**Comment by kingthorin** [comment]
I don't see how you'd add specifics after the fact, kinda seems like "enhancing a picture".

**Comment by Jeeppler** [comment]
@thc202 pointed that all alerts of the same type are grouped together. As a result, they have all the same message text. 

The problem with this approach is, that it does not give the user any hint about what is really wrong with the specific alert/URL he/she/their is looking at. The solution text has the same limitation. It is basically, I generic snippet from the Common Weakness Enumeration page.

The alert message and solution, help little to nothing in understanding the problem. As a user, I have to look at the URL, attack and evidence to understand the problem.

From a users perspective, especially those which do not use OWASP ZAP everyday, it would be nice to have a specific message and solution for the issue at hand. Users like operations engineers and developers trying to fix the issues are left alone.

SARIF makes this limitation obvious, as SARIF considers each instance of an alert as another finding. For example, OWASP ZAP finds 3 instances of an XSS vulnerability in the application, there will be three findings with the exact same generic message.

**Comment by thc202** [comment]
That's the purpose of the "other info" (more details about the actual issue), along with attack and evidence.

**Comment by kingthorin** [comment]
> SARIF makes this limitation obvious, as SARIF considers each instance of an alert as another finding. For example, OWASP ZAP finds 3 instances of an XSS vulnerability in the application, there will be three findings with the exact same generic message.

Yup just like 3 occurrences of 'you could use a lambda here' or 'this is unsafe hashing' or 'this could NPE'...

We can debate this in circles until we're all blue in the face. There are 1000s and 1000s of things ZAP could maybe even should do differently (for for every DAST/SAST on the market), the fact remains this is what we have to work with and I don't see SARIF (which others have already produced) being a driver for major change. Unless you have some Java devs available to work overhauling all the scan rules.

I don't mean this to seem like I'm dumping on anyone or any ideas but we don't seem to be landing anywhere useful, just talking in circles.

>The alert message and solution, help little to nothing in understanding the problem. As a user, I have to look at the URL, attack and evidence to understand the problem.

Yes all parts of the alert are relevant to get the full context of the issue. Just like the SAST examples above without a line # or class name the description is useless.

> Edit: With that not saying that all rules do that, but should.

_Could :wink:_

**Comment by de-jcup** [comment]
I think the idea itself would be useful, but I see also the effort and ... in relation to the benefits.. currently is too much. To avoid people getting blue while debating this in circles I will close the issue ;-)

Thanx for the thoughts and comments.

**Comment by de-jcup** [comment]
Remark - I will now use inside sarif report results the `otherInfo` when not `null`- when `otherInfo` is `null` the "normal" generic `description` from alert will be used as fallback. So alert rules having a dedicated/specific other info set will have different messages as mentioned above.

**Comment by kingthorin** [comment]
I'd suggest using them to supplement not supplant (concatenate not replace), for my 2 cents.

**Comment by Jeeppler** [comment]
@thc202 @kingthorin thanks for your inside. Indeed it would mean a lot of work to overhaul all the rules.

Furthermore, the question of how to improve the description/solution to the point where most people are able to understand and find it easy to fix the vulnerability is far beyond the scope of this issue. However, it is still worth a thought.
