### ISSUE TITLE
Unable to launch the zap tool through zap.exe in java code

### ISSUE THREAD

**Issue by Charlie-nap** [zaproxy/zaproxy#6948]
I am trying to launch the ZAP tool through java code, but when I try to execute the program, ZAP tool does not open fully

Below is the java code
Process p = Runtime.getRuntime().exec("zap.exe");  
p.waitFor();  

I want the process to wait till the ZAP tool is completely Launched, If I use zap.bat my process does not wait till the Zap Tool is launched

Kindly requesting help to solve this issue, Thanking you in advance
![zap](https://user-images.githubusercontent.com/94967361/143231669-aacc08ce-afe9-4545-8ad9-bc0e8cfe61a1.PNG)

**Comment by thc202** [comment]
The most reliable way is to try connect to ZAP API, once successful it means ZAP is fully started. You should not `waitFor()` since that will block until ZAP is terminated.

Usage questions are better asked in the OWASP ZAP User Group: https://groups.google.com/g/zaproxy-users
