### ISSUE TITLE
New Passive scan rule for metadata request headers

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#6955]
Add a new passive scan rule which looks for metadata headers https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers#fetch_metadata_request_headers

For info these are supported in FX 90 (havnt checked Chrome yet) https://blog.mozilla.org/security/2021/07/12/firefox-90-supports-fetch-metadata-request-headers/

TBH I'm not quite sure what the rule could or should do, but thought I'd raise the issue to start that discussion :D
I dont think most sites will need to use them, so reporting them as missing might be a step too far.
Reporting their presence at info level is an option, as is reporting any invalid values.
Any other suggestions?

**Comment by kingthorin** [comment]
Setting "good second issue" based on initial implementation with simple:

>  Reporting their presence at info level is an option, as is reporting any invalid values.

**Comment by aayushhyadav** [comment]
I would like to work on this

**Comment by aayushhyadav** [comment]
Basically we need to scan the request headers and verify if these headers are present or not (have invalid values etc) then raise an alert in the Alerts tab with risk type as informational and maybe provide some suggestions in the solution section. Any other ideas?

**Comment by aayushhyadav** [comment]
Also, changes would be required in zap-extensions under pscanrules right?

**Comment by thc202** [comment]
Generally new scan rules should start in alpha state (e.g. `pscanrulesAlpha`, `ascanrulesAlpha`).

https://github.com/zaproxy/zaproxy/issues/6955#issuecomment-1483996286

Yes.

**Comment by aayushhyadav** [comment]
I have started making changes in pscanrulesAlpha. Could anyone guide me how to test the changes locally? I have tried executing the spider but the control doesn't seem to enter the new pscan rule.

**Comment by kingthorin** [comment]
You need to build and use the add-on. Info here: https://www.zaproxy.org/docs/developer/quick-start-build/

**Comment by aayushhyadav** [comment]
Wanted to clarify a few things
1. As there are 5 different headers (as per [https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers#fetch_metadata_request_headers](url)), should we have a different alert for each header? or a common alert for all headers (like if one or more are missing we raise a missing error stating "one or more are missing")?
2. Same query for reporting alerts for invalid values (common or different alerts?) (IMO different headers would provide more info)
3. What would be the values for plugin ID, WASC ID, CWE ID, Confidence, reference and alert tags?
