### ISSUE TITLE
Import Postman API definitions

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#6960]
Some links:

- https://blog.postman.com/travelogue-of-postman-collection-format-v2/
- https://schema.postman.com/json/collection/v2.1.0/collection.json

**Comment by codebyshubham** [comment]
Hi @psiinon 
I'm from Postman, I would like to work on this but I'm not comfortable in JAVA. If I'm not wrong, I need to work on both 
**zaproxy** and the **zap-extension** repository as correct?

**Comment by psiinon** [comment]
Hiya @codebyshubham - good to hear from you!
Yes, this will need to be written in java. But only the zap-extension repo will need to be changed.
FYI we have specified this as one of the potential projects for GSoC 2022 https://owasp.org/www-community/initiatives/gsoc/gsoc2022ideas

**Comment by codebyshubham** [comment]
Okay, not an issue I'll pick up JAVA while going through the **Import openAPI** extension code and try to replicate it for the Postman API definition. You can assign this to me and I'll let you know If I get stuck.

**Comment by thc202** [comment]
That's not a good example to base of.

**Comment by codebyshubham** [comment]
Can you suggest the right example or the right path? I've set up the code locally.

**Comment by thc202** [comment]
I understood but replicate is not the best at least using OpenAPI add-on, if that's just for the base of the add-on that's ok otherwise the import itself better write from scratch.

**Comment by codebyshubham** [comment]
Thanks
let me go through the codebase to get a better idea.

**Comment by kingthorin** [comment]
@codebyshubham not to rush or pressure you, but we'd like to get a feeling for how committed to this you are? This particular idea is one of the suggestions we've made for GSoC 2022 so if you are leaning towards tackling it we should take it off the list.

**Comment by codebyshubham** [comment]
Hi @kingthorin 
Yes, You can assign this feature to me. I'll complete this feature with all the new changes in Postman collections.

**Comment by thc202** [comment]
@codebyshubham how are things going?

**Comment by codebyshubham** [comment]
Even though I'm struggling in JAVA, things are going better than I expected. I might need some help for sending multipart data in request. I'll ping one of your team once I'll handle other types of request bodies and different methods.

**Comment by codebyshubham** [comment]
Even though I'm struggling in JAVA, things are going better than I expected. I might need some help for sending multipart data in request. I'll ping one of you once I'll handle other types of request bodies and different methods.

**Comment by thc202** [comment]
Great!

**Comment by thc202** [comment]
@codebyshubham let us know if there's anything we can do to help.

**Comment by kingthorin** [comment]
@codebyshubham any further movement on this?

**Comment by kingthorin** [comment]
https://groups.google.com/g/zaproxy-users/c/NKh6fHomTgw

**Comment by Avinash-Acharya** [comment]
Since I have good knowledge of Java , I would love to work on this issue.
Can someone explain in brief what is needed to be done here.

**Comment by kingthorin** [comment]
The exim or openapi add-on should be enhanced to be able to import a Postman collection.

You could also look at/build on the commits here: https://github.com/codebyshubham/zap-extensions

**Comment by Avinash-Acharya** [comment]
Thanks I will take a look into it.

**Comment by Avinash-Acharya** [comment]
> You could also look at/build on the commits here: https://github.com/codebyshubham/zap-extensions

By going through the code in the mentioned repo, I just recognized that the new addon "importPostmanCollectionv2" is basically just a clone of another addon by the name "GraphQl".

I got few questions:
- Can I take reference from any other addon to build this one?(probably openAPI addon holds the similarity)
- Is there any other resource that I can go through which could assist me throughout the build?(I am currently understanding the working of REST-API , Postman and how to import its collection)

**Comment by thc202** [comment]
GraphQL is better example than OpenAPI, but you are welcome to check any (just don't model it exactly like OpenAPI, the current structure makes it harder to maintain).

The referenced links in the issue summary, check Postman docs and the schema.

**Comment by Avinash-Acharya** [comment]
I will keep all three add-ons in mind for an reference, Thanks.

**Comment by Avinash-Acharya** [comment]
Few Questions:
- What action will ZAP perform after importing Postman collections?
- What are the basic similarity between exim, GraphQL, and OpenAPI addons? (where can I find the exim addon, I wanted to use it in the GUI for an reference but I can't locate it.)
- What are the issues you guys faced in the current structure which made it harder to maintain?

**Comment by thc202** [comment]
1. That's up to the user to decide, the add-on should just import into ZAP.
2. All allow to import data into ZAP. See https://www.zaproxy.org/docs/desktop/addons/import-export/
3. If you are referring to the OpenAPI add-on, the flow is not easy to follow, changes required in several places depending on the type/data (e.g. query vs body) being generated even when the data should be the same…

**Comment by Avinash-Acharya** [comment]
> 3. If you are referring to the OpenAPI add-on, the flow is not easy to follow, changes required in several places depending on the type/data (e.g. query vs body) being generated even when the data should be the same…

Hence I shouldn't follow the code but just the basic structure as an idea to build this new addon from stratch. Am I right?

**Comment by thc202** [comment]
Correct, you can definitely get good ideas from that add-on but don't design the new add-on solely based on that one.

**Comment by Avinash-Acharya** [comment]
In short , We need to build a addon which imports postman collections. 
All the information you need can be found in the comments and the reference link above.

**Comment by MrDHat** [comment]
Hey people 👋🏼 

It's not quite clear from the comments, so I wanted to understand if this is being actively looked into. I am part of the team at Postman which is considering supporting this as a part of the bigger API Security push & would be interested in helping the community if I can!

**Comment by kingthorin** [comment]
Someone from the Postman team had previously started tackling it but then we stopped hearing from them.

It’s now a potential issue to be tackled via GSoC.

**Comment by MrDHat** [comment]
Yeah, I did see that from the comments. I assume that something would have changed priorities on their end which could have resulted in the abandonment of the project. Don't want to comment on that though 🙂

Happy to help in any way I can with the project if a student decides/doesn't decide to take this project up. I am assuming we'll know that by May (if I am getting the GSoC dates right)

**Comment by kingthorin** [comment]
Thanks @MrDHat

**Comment by Avinash-Acharya** [comment]
![image](https://user-images.githubusercontent.com/120123021/227729025-2a18186b-bca3-466e-8e94-a37dbe251063.png)

Is following this schema fine? Most of the addons follow this flow.

**Comment by kingthorin** [comment]
Yup, there are probably simpler examples but you’re right they mostly follow that structure.

In this case I’m not sure if it needs to be a completely new add-on or just functionality added to exim.

**Comment by Avinash-Acharya** [comment]
Before I start with new addon , I will go with exim. If it works completely fine with few enhancement it will be great.

**Comment by ricekot** [comment]
It would be good to see a proposal / plan of action before you actually start the implementation. I find writing down what I'm planning to do before I actually start coding helps me think more clearly and ends up saving me time down the line.

**Comment by Avinash-Acharya** [comment]
Can I DM you in IRC?

**Comment by ricekot** [comment]
Sure.

**Comment by Avinash-Acharya** [comment]
![image](https://user-images.githubusercontent.com/120123021/227996168-5f2bad62-5c34-420d-9cab-dcab668255e7.png)

(Reference to OpenAPI Add-on) To import an definition we use an external library(the path doesn't belongs to the package) 
*_I am not sure so can someone confirm this_

**Comment by VitikaSoni** [comment]
Could I please get assigned to this? :)

**Comment by psiinon** [comment]
Done 😁

**Comment by thc202** [comment]
Should we close this issue now? https://www.zaproxy.org/blog/2023-09-25-postman-add-on/
