### ISSUE TITLE
Why does zaproxy load an existing session take a very long time?

### ISSUE THREAD

**Issue by dm116** [zaproxy/zaproxy#6964]
**Describe the bug**
Why does zaproxy load an existing session take a very long time?

**To Reproduce**
1. Runing zaproxy on the terminal
2. Open a exist session.

**Expected behavior**

**Screenshots**

**Software versions**
 - ZAP:  zap-2.11.0
 - OS: FreeBSD 13.0
 - Java: openjdk version "1.8.0_302"

**Comment by thc202** [comment]
Closing, duplicate of #1364.
