### ISSUE TITLE
Can't Launch Chrome from manual expore 

### ISSUE THREAD

**Issue by ex4722** [zaproxy/zaproxy#6978]
**Describe the bug**
Launching Chrome from the manual explore causes chrome to launch up and then crashes seemingly due to web driver issues. 

**To Reproduce**
 1.   Manual explore
 2.  Select "Chrome" as the browser
 3.  Press "Launch browser"
 4.  (HUD enabled or disabled doesn't make a difference)

**Expected behavior**
Chrome to launch 

**Screenshots**

**Software versions**
 - ZAP: 2.11.1
 - Add-on: NONE
 - OS: MacOs Big Sur ( M1 ) 
 - Java: Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)
 - Browser: Chrome Version 96.0.4664.93 (Official Build) (arm64)

**Errors from the zap.log file**
ORG.OPENQA.SELENIUM.SESSIONNOTCREATEDEXCEPTION: SESSION NOT CREATED: THIS VERSION OF CHROMEDRIVER ONLY SUPPORTS CHROME VERSION 93
CURRENT BROWSER VERSION IS 96.0.4664.110 WITH BINARY PATH /APPLICATIONS/GOOGLE CHROME.APP/CONTENTS/MACOS/GOOGLE CHROME
BUILD INFO: VERSION: 'UNKNOWN', REVISION: 'UNKNOWN', TIME: 'UNKNOWN'
SYSTEM INFO: HOST: 'SOMETHING', IP: 'SOMETHING', OS.NAME: 'MAC OS X', OS.ARCH: 'X86_64', OS.VERSION: '11.5', JAVA.VERSION: '11.0.12'
DRIVER INFO: DRIVER.VERSION: CHROMEDRIVER
REMOTE STACKTRACE: 0   CHROMEDRIVER                        0X0000000104F643C9 __GXX_PERSONALITY_V0 + 553177
1   CHROMEDRIVER                        0X0000000104EF61D3 __GXX_PERSONALITY_V0 + 102115
2   CHROMEDRIVER                        0X0000000104AC3008 CHROMEDRIVER + 172040
3   CHROMEDRIVER                        0X0000000104AE92EA CHROMEDRIVER + 328426
4   CHROMEDRIVER                        0X0000000104AE4E26 CHROMEDRIVER + 310822
5   CHROMEDRIVER                        0X0000000104AE193E CHROMEDRIVER + 297278
6   CHROMEDRIVER                        0X0000000104B1ACEB CHROMEDRIVER + 531691
7   CHROMEDRIVER                        0X0000000104B14CE3 CHROMEDRIVER + 507107
8   CHROMEDRIVER                        0X0000000104AEB600 CHROMEDRIVER + 337408
9   CHROMEDRIVER                        0X0000000104AEC795 CHROMEDRIVER + 341909
10  CHROMEDRIVER                        0X0000000104F25571 __GXX_PERSONALITY_V0 + 295553
11  CHROMEDRIVER                        0X0000000104F39CCF __GXX_PERSONALITY_V0 + 379359
12  CHROMEDRIVER                        0X0000000104F3AF5F __GXX_PERSONALITY_V0 + 384111
13  CHROMEDRIVER                        0X0000000104F3F65B __GXX_PERSONALITY_V0 + 402283
14  CHROMEDRIVER                        0X0000000104F3B42F __GXX_PERSONALITY_V0 + 385343
15  CHROMEDRIVER                        0X0000000104F1A46C __GXX_PERSONALITY_V0 + 250236
16  CHROMEDRIVER                        0X0000000104F55AD8 __GXX_PERSONALITY_V0 + 493544
17  CHROMEDRIVER                        0X0000000104F55C61 __GXX_PERSONALITY_V0 + 493937
18  CHROMEDRIVER                        0X0000000104F6B9D8 __GXX_PERSONALITY_V0 + 583400
19  LIBSYSTEM_PTHREAD.DYLIB             0X00007FFF204068FC _PTHREAD_START + 224
20  LIBSYSTEM_PTHREAD.DYLIB             0X00007FFF20402443 THREAD_START + 15

	AT JDK.INTERNAL.REFLECT.NATIVECONSTRUCTORACCESSORIMPL.NEWINSTANCE0(NATIVE METHOD) ~[?:?]
	AT JDK.INTERNAL.REFLECT.NATIVECONSTRUCTORACCESSORIMPL.NEWINSTANCE(UNKNOWN SOURCE) ~[?:?]
	AT JDK.INTERNAL.REFLECT.DELEGATINGCONSTRUCTORACCESSORIMPL.NEWINSTANCE(UNKNOWN SOURCE) ~[?:?]
	AT JAVA.LANG.REFLECT.CONSTRUCTOR.NEWINSTANCE(UNKNOWN SOURCE) ~[?:?]
	AT ORG.OPENQA.SELENIUM.REMOTE.W3CHANDSHAKERESPONSE.LAMBDA$ERRORHANDLER$0(W3CHANDSHAKERESPONSE.JAVA:62) ~[?:?]
	AT ORG.OPENQA.SELENIUM.REMOTE.HANDSHAKERESPONSE.LAMBDA$GETRESPONSEFUNCTION$0(HANDSHAKERESPONSE.JAVA:30) ~[?:?]
	AT ORG.OPENQA.SELENIUM.REMOTE.PROTOCOLHANDSHAKE.LAMBDA$CREATESESSION$0(PROTOCOLHANDSHAKE.JAVA:126) ~[?:?]
	AT JAVA.UTIL.STREAM.REFERENCEPIPELINE$3$1.ACCEPT(UNKNOWN SOURCE) ~[?:?]
	AT JAVA.UTIL.SPLITERATORS$ARRAYSPLITERATOR.TRYADVANCE(UNKNOWN SOURCE) ~[?:?]
	AT JAVA.UTIL.STREAM.REFERENCEPIPELINE.FOREACHWITHCANCEL(UNKNOWN SOURCE) ~[?:?]
	AT JAVA.UTIL.STREAM.ABSTRACTPIPELINE.COPYINTOWITHCANCEL(UNKNOWN SOURCE) ~[?:?]
	AT JAVA.UTIL.STREAM.ABSTRACTPIPELINE.COPYINTO(UNKNOWN SOURCE) ~[?:?]
	AT JAVA.UTIL.STREAM.ABSTRACTPIPELINE.WRAPANDCOPYINTO(UNKNOWN SOURCE) ~[?:?]
	AT JAVA.UTIL.STREAM.FINDOPS$FINDOP.EVALUATESEQUENTIAL(UNKNOWN SOURCE) ~[?:?]
	AT JAVA.UTIL.STREAM.ABSTRACTPIPELINE.EVALUATE(UNKNOWN SOURCE) ~[?:?]
	AT JAVA.UTIL.STREAM.REFERENCEPIPELINE.FINDFIRST(UNKNOWN SOURCE) ~[?:?]
	AT ORG.OPENQA.SELENIUM.REMOTE.PROTOCOLHANDSHAKE.CREATESESSION(PROTOCOLHANDSHAKE.JAVA:128) ~[?:?]
	AT ORG.OPENQA.SELENIUM.REMOTE.PROTOCOLHANDSHAKE.CREATESESSION(PROTOCOLHANDSHAKE.JAVA:74) ~[?:?]
	AT ORG.OPENQA.SELENIUM.REMOTE.HTTPCOMMANDEXECUTOR.EXECUTE(HTTPCOMMANDEXECUTOR.JAVA:136) ~[?:?]
	AT ORG.OPENQA.SELENIUM.REMOTE.SERVICE.DRIVERCOMMANDEXECUTOR.EXECUTE(DRIVERCOMMANDEXECUTOR.JAVA:83) ~[?:?]
	AT ORG.OPENQA.SELENIUM.REMOTE.REMOTEWEBDRIVER.EXECUTE(REMOTEWEBDRIVER.JAVA:552) ~[?:?]
	AT ORG.OPENQA.SELENIUM.REMOTE.REMOTEWEBDRIVER.STARTSESSION(REMOTEWEBDRIVER.JAVA:213) ~[?:?]
	AT ORG.OPENQA.SELENIUM.REMOTE.REMOTEWEBDRIVER.<INIT>(REMOTEWEBDRIVER.JAVA:131) ~[?:?]
	AT ORG.OPENQA.SELENIUM.CHROME.CHROMEDRIVER.<INIT>(CHROMEDRIVER.JAVA:181) ~[?:?]
	AT ORG.OPENQA.SELENIUM.CHROME.CHROMEDRIVER.<INIT>(CHROMEDRIVER.JAVA:168) ~[?:?]
	AT ORG.OPENQA.SELENIUM.CHROME.CHROMEDRIVER.<INIT>(CHROMEDRIVER.JAVA:157) ~[?:?]
	AT ORG.ZAPROXY.ZAP.EXTENSION.SELENIUM.EXTENSIONSELENIUM.GETWEBDRIVERIMPL(EXTENSIONSELENIUM.JAVA:952) ~[?:?]
	AT ORG.ZAPROXY.ZAP.EXTENSION.SELENIUM.EXTENSIONSELENIUM.GETWEBDRIVER(EXTENSIONSELENIUM.JAVA:868) ~[?:?]
	AT ORG.ZAPROXY.ZAP.EXTENSION.SELENIUM.INTERNAL.BUILTINSINGLEWEBDRIVERPROVIDER.GETWEBDRIVER(BUILTINSINGLEWEBDRIVERPROVIDER.JAVA:63) ~[?:?]
	AT ORG.ZAPROXY.ZAP.EXTENSION.SELENIUM.EXTENSIONSELENIUM.GETWEBDRIVERIMPL(EXTENSIONSELENIUM.JAVA:754) ~[?:?]
	AT ORG.ZAPROXY.ZAP.EXTENSION.SELENIUM.EXTENSIONSELENIUM.GETWEBDRIVER(EXTENSIONSELENIUM.JAVA:561) ~[?:?]
	AT ORG.ZAPROXY.ZAP.EXTENSION.SELENIUM.EXTENSIONSELENIUM.GETPROXIEDBROWSER(EXTENSIONSELENIUM.JAVA:710) ~[?:?]
	AT ORG.ZAPROXY.ZAP.EXTENSION.SELENIUM.EXTENSIONSELENIUM.GETPROXIEDBROWSERBYNAME(EXTENSIONSELENIUM.JAVA:651) ~[?:?]
	AT ORG.ZAPROXY.ZAP.EXTENSION.SELENIUM.EXTENSIONSELENIUM.GETPROXIEDBROWSERBYNAME(EXTENSIONSELENIUM.JAVA:627) ~[?:?]
	AT ORG.ZAPROXY.ZAP.EXTENSION.SELENIUM.EXTENSIONSELENIUM.GETPROXIEDBROWSERBYNAME(EXTENSIONSELENIUM.JAVA:611) ~[?:?]
	AT ORG.ZAPROXY.ZAP.EXTENSION.SELENIUM.EXTENSIONSELENIUM.GETPROXIEDBROWSERBYNAME(EXTENSIONSELENIUM.JAVA:601) ~[?:?]
	AT ORG.ZAPROXY.ZAP.EXTENSION.QUICKSTART.LAUNCH.EXTENSIONQUICKSTARTLAUNCH.LAMBDA$LAUNCHBROWSER$1(EXTENSIONQUICKSTARTLAUNCH.JAVA:209) ~[?:?]
	AT JAVA.LANG.THREAD.RUN(UNKNOWN SOURCE) [?:?]

**Would you like to help fix this issue?**
Please help :)

**Comment by kingthorin** [comment]
Looks like we need to upgrade form: 95.0.4638.17 to 96.0.4664.45
