### ISSUE TITLE
"The provided browser was not found" while it is effectively installed

### ISSUE THREAD

**Issue by meetinthemiddle-be** [zaproxy/zaproxy#7008]
**Describe the bug**
On my M1 mac running Monterey, when I fire a browser through ZAP using "Manual Explore" I get an error saying "The provided browser was not found", even though the selected browser is installed 

This happens for Chrome and Safari, but not for Firefox

**To Reproduce**
1. Click "Manual Explore" in the "Quick Launch" pane
2. On the line labeled "Explore your application" select "Chrome"
3. Click the "Launch Browser" button
4. See an error pop up saying "The provided browser was not found"

**Expected behavior**
The selected browser - controlled by selenium - should start.

**Software versions**
 - ZAP: 2.11.1
 - OS: MacOS Monterey 12.1 on M1 CPU
 - Java Version : Unsure; `java -version` fails

**Errors from the zap.log file**
```
2022-01-04 10:36:08,628 [ZAP-BrowserLauncher] ERROR ExtensionQuickStartLaunch - unknown error: Chrome failed to start: was killed.

  (unknown error: DevToolsActivePort file doesn't exist)

  (The process started from chrome location /Applications/Google Chrome.app/Contents/MacOS/Google Chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

Build info: version: 'unknown', revision: 'unknown', time: 'unknown'

System info: host: '***REDACTED***', ip: 'f***REDACTED***', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '11.1', java.version: '11.0.12'

Driver info: driver.version: ChromeDriver
```

**Would you like to help fix this issue?**
Yes

**Comment by kingthorin** [comment]
Are you able to launch Chrome from the CLI? (Chrome itself, not involving ZAP)

**Comment by thc202** [comment]
Yes, there's more info in Slack.

**Comment by kingthorin** [comment]
Relevant bits from slack:

```
...
MeetInTheMiddle  4 hours ago
cd'd into that dir and then launched using ./Google Chrome
MeetInTheMiddle  4 hours ago
stdout says "Opening in existing browser session."
MeetInTheMiddle  4 hours ago
And Chrome opens (edited) 
MeetInTheMiddle  4 hours ago
What is interesting in the error message though is this : os.name: 'Mac OS X', os.arch: 'x86_64',
MeetInTheMiddle  4 hours ago
I have an M1 mac, not an Intel Mac
thc202  4 hours ago
Chrome version?
MeetInTheMiddle  4 hours ago
But I'm assuming that running ZAP in Rosetta could make it think it's on Intel
MeetInTheMiddle  4 hours ago
@thc202: Version 96.0.4664.110 (Official Build) (arm64)
MeetInTheMiddle  4 hours ago
(additionally: When using the ZAP Cross-platform installer in a Win11 VM, both Chrome and Firefox work OOTB after installing them.)
...
```

**Comment by hahwul** [comment]
Hi @thc202 @kingthorin :D
Um, I've been experiencing similar issues lately too. 
In my case, `Firefox` has an `The provided browser was not found.` error. the mac I have is all the same 😭

- [X] M1 Mac macOS Monterey 12.2 
- [X] Intel Mac macOS Monterey 12.2
- [X] Intel Mac macOS Monterey 12.2.1

All three are installed to ZAP 2.11.1 and Firefox, and they were already well used. Is there any good solution?

**Log**
```
584929 [ZAP-BrowserLauncher] ERROR org.zaproxy.zap.extension.quickstart.launch.ExtensionQuickStartLaunch - Extension should contain either install.rdf or manifest.json metadata file
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: '***REDACTED***, ip: '***REDACTED***', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '11.2', java.version: '11.0.12'
Driver info: driver.version: FirefoxDriver
org.openqa.selenium.WebDriverException: Extension should contain either install.rdf or manifest.json metadata file
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: '***REDACTED***', ip: '***REDACTED***', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '11.2', java.version: '11.0.12'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.firefox.internal.FileExtension.getExtensionId(FileExtension.java:129) ~[?:?]
	at org.openqa.selenium.firefox.internal.FileExtension.installExtensionFromFileTo(FileExtension.java:93) ~[?:?]
	at org.openqa.selenium.firefox.internal.FileExtension.writeTo(FileExtension.java:74) ~[?:?]
	at org.openqa.selenium.firefox.FirefoxProfile.installExtensions(FirefoxProfile.java:425) ~[?:?]
	at org.openqa.selenium.firefox.FirefoxProfile.layoutOnDisk(FirefoxProfile.java:403) ~[?:?]
	at org.openqa.selenium.firefox.FirefoxProfile.toJson(FirefoxProfile.java:360) ~[?:?]
	at org.openqa.selenium.firefox.FirefoxOptions.asMap(FirefoxOptions.java:364) ~[?:?]
	at org.openqa.selenium.MutableCapabilities.<init>(MutableCapabilities.java:48) ~[?:?]
	at org.openqa.selenium.firefox.FirefoxDriver.dropCapabilities(FirefoxDriver.java:257) ~[?:?]
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:147) ~[?:?]
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriverImpl(ExtensionSelenium.java:1009) ~[?:?]
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriver(ExtensionSelenium.java:868) ~[?:?]
	at org.zaproxy.zap.extension.selenium.internal.BuiltInSingleWebDriverProvider.getWebDriver(BuiltInSingleWebDriverProvider.java:63) ~[?:?]
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriverImpl(ExtensionSelenium.java:754) ~[?:?]
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriver(ExtensionSelenium.java:561) ~[?:?]
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getProxiedBrowser(ExtensionSelenium.java:710) ~[?:?]
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getProxiedBrowserByName(ExtensionSelenium.java:651) ~[?:?]
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getProxiedBrowserByName(ExtensionSelenium.java:627) ~[?:?]
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getProxiedBrowserByName(ExtensionSelenium.java:611) ~[?:?]
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getProxiedBrowserByName(ExtensionSelenium.java:601) ~[?:?]
	at org.zaproxy.zap.extension.quickstart.launch.ExtensionQuickStartLaunch.lambda$launchBrowser$1(ExtensionQuickStartLaunch.java:209) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

**Comment by thc202** [comment]
Seems to be Eval Villain add-on causing the issue.

**Comment by kingthorin** [comment]
Seems like an issue with the update workflow. It needs to be set to follow redirects. Will send an update soon.

**Comment by psiinon** [comment]
I think this should be fixed now.
@hahwul can you confirm its working for you after you update the Eval Villian add-on?

**Comment by hahwul** [comment]
@psiinon 
Yes, I just updated Addon, and Firefox is working well! Thank you so much :D

**Comment by kingthorin** [comment]
Thanks for letting us know.

**Comment by kingthorin** [comment]
To the original issue: It looks like Chromedriver for M1 is a separate binary: https://chromedriver.storage.googleapis.com/index.html?path=97.0.4692.71/

**Comment by globeone** [comment]
This is not only a M1 issue. The same issue started cropping up in the weekly 2022-02-28 release of ZAP and is also present in the 2022-03-08 release for Windows 10.

**Comment by thc202** [comment]
Is that with Chrome too? Which version?

**Comment by globeone** [comment]
![image](https://user-images.githubusercontent.com/10052587/157246678-68bffeb6-0707-4a1e-8642-852f4538d3fb.png)

Version 99.0.4844.51 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/10052587/157246767-9efd85e0-ff19-4021-917c-b43190aaa089.png)

**Comment by globeone** [comment]
Does ZAP expect chrome.exe to be in the PATH environment variable? It seems like there has been an update that removes chrome.exe from the PATH.

**Comment by globeone** [comment]
Found the issue. It's the Selenium Driver. adding the correct Selenium web driver for the browser version from
https://chromedriver.chromium.org/downloads

fixes the issue.

**Comment by globeone** [comment]
drop the correct version of the chrome driver for your browser version:

![image](https://user-images.githubusercontent.com/10052587/157249850-63815fb3-6ae7-4ed9-b5f1-aeaf2e29bf50.png)

everything works normally again
![image](https://user-images.githubusercontent.com/10052587/157249589-53b5dbfe-1308-46b2-b6f8-b345db55962d.png)

**Comment by globeone** [comment]
Is it possible to reopen this issue? There are still problems opening Chrome on the Mac even with the latest chrome driver. The Chrome location field is missing and on the Mac Chrome won't open.

Even when we exclude chromedriver (mac64) from gatekeeper, chrome is not opening through ZAP.

If not then I'll make a new ticket.

![image](https://user-images.githubusercontent.com/10052587/162929596-96cab43c-a6ff-4d89-b57b-eb083634fb7a.png)

**Comment by thc202** [comment]
Make sure that the add-ons are up-to-date, if you are not seeing the Chome binary option it means you are not using the latest version.

Could you provide the log?

**Comment by globeone** [comment]
I'm sanitizing the log at the moment. The only version of ZAP that is installable and runnable on the Mac is via Homebrew
`brew install --cask owasp-zap --no-quarantine`
and the chromedriver we got here:
`https://chromedriver.chromium.org/downloads`

**Comment by globeone** [comment]
So, here is the sanitized log from a Mac
At the start of the log the bundled Chromedriver doesn't match the version of Chrome. 
There is no user interaction here with a warning pop-up ("chromedriver is outdated please update the chromedriver") 

Near the end of the logging, after we replaced the Chromedriver with the version closest matching to the browser, we observe that there is a timeout warning. Again, no user interaction or popup to inform the user that chromedriver has timed out.

version of Chrome Driver used
[ChromeDriver 100.0.4896.60](https://chromedriver.storage.googleapis.com/index.html?path=100.0.4896.60/)

Google's current version of Chrome in use
The actual browser version is 100.0.4896.88

[sanitized_mac_zap.log](https://github.com/zaproxy/zaproxy/files/8472323/sanitized_mac_zap.log)

**Comment by globeone** [comment]
The Selenium version is 15.5.1 and there are no newer versions available

![image](https://user-images.githubusercontent.com/10052587/162951059-90d67609-ff1f-4de3-b94c-a71c87dabd97.png)

**Comment by psiinon** [comment]
It looks like you just posted a screenshot and these deleted it?
Which indicated that most of your add-ons are not on the latest version...

**Comment by globeone** [comment]
@thc202 
Thanks for your help it's indeed solved through a Add On update. 

Maybe we can have a user interaction when Chrome doesn't open that brings people directly to the marketplace?

![image](https://user-images.githubusercontent.com/10052587/162951789-1027e42b-e897-4e79-801d-0f0d1ce9c935.png)

![image](https://user-images.githubusercontent.com/10052587/162951902-17304277-ccdb-4614-af76-e896322fbabf.png)

**Comment by thc202** [comment]
There's an option to automatically update the add-ons: https://www.zaproxy.org/docs/desktop/ui/dialogs/options/checkforupdates/
