### ISSUE TITLE
GitHub Releases with actual Release Notes

### ISSUE THREAD

**Issue by BloodyIron** [zaproxy/zaproxy#7009]
Hey so it looks like GitHub is pretty heavily used for this project, but when I look at numbered releases (not weekly) I see no release notes. Like, what was added, fixed, existing bugs, etc. Can we please get release notes for each release on GitHub? It's really useful for any open source project, and is especially helpful for IT Professionals to decide whether they want to accelerate upgrading to a new version, or hold off, etc.

**Comment by psiinon** [comment]
The release notes are here: https://www.zaproxy.org/docs/desktop/releases/
I guess we could link to them from the GitHub release pages.
They are however always linked to from the main ZAP Downloads page: https://www.zaproxy.org/download/

**Comment by psiinon** [comment]
Links manually added to

- https://github.com/zaproxy/zaproxy/releases/tag/v2.11.1
- https://github.com/zaproxy/zaproxy/releases/tag/v2.11.0

**Comment by kingthorin** [comment]
While I don't disagree that more documentation or cross linking is good/handy. We are a small team and can only support the latest version, so the answer to whether you should upgrade or not should always be "yes" :grinning: :wink:

**Comment by BloodyIron** [comment]
> While I don't disagree that more documentation or cross linking is good/handy.
> 
> We are a small team and can only support the latest version, so the answer to whether you should upgrade or not should always be "yes" grinning wink

Uhhh it's pretty naive to think that code will never regress or break. I honestly cannot trust that any software will be bug free when releases come out, which is part of why I say this.

**Comment by kingthorin** [comment]
Oh no things will break and be fixed, that's why you should stay up-to-date.
