### ISSUE TITLE
Authentication control support & Multi-user support (webswing/docker)

### ISSUE THREAD

**Issue by BloodyIron** [zaproxy/zaproxy#7010]
I'm liking what I see in OWASP ZAP, as I've used it on my work laptop to address a few iTSec situations already. And I saw that with the webswing stuff, and the docker container stuff, we can implement a more permanent version that can be accessed via a webGUI. Nice!

However, when I try to dig further into the documentation, there's a few aspects that I find lacking, especially considering this is an ITSec focused too.

1. I can't seem to find a way to limit access by user authentication
2. I can't tell if the webswing session is single-user or if there's some way to have multi-user usage for the same docker container instance

When it comes to authentication, I know there's probably some things I can do at the docker-configuration layer to apply some form of auth in yaml init code, but frankly I'd rather the authentication mechanism be done inside OWASP ZAP so that the authentication mechanism can be obfuscated from anyone that has access to the code. We have DevOps staff who aren't tasked specifically with ITSec stuff, so there's legitimate need to have them see/read the code, but not necessarily be able to log into some systems (such as this). Additionally, if there are already authentication mechanisms I can use, I can't find them in the documentation (again, webswing). I would ask that LDAP(S) at a minimum be included, but if SAML or other SSO could be added that'd be stellar. If we could interface conveniently (and securely) with our central-authentication ecosystem (ActiveDirectory, Google Workspaces, self-hosted LDAP, SAML/SSO, whatever) then that would be ideal IMO, as then we can grant access to this system through group membership (as one way).

To put it another way, I don't really want any malicious actor in our environment (internal or not) pivoting to our OWASP ZAP system and deleting my scan history, halting scans, or anything like that. This really should be behind login credentials one way or another.

When it comes to single/multi-user, right now it's probably going to be only me using this system, however I think it's reasonable to consider that there's likely going to be times we will want to run multiple scans at the same time, initiated by different users, and not womp (erase/cancel) the work other staff have already done in their OWASP ZAP session (or whatever appropriate term is here). With how long OWASP ZAP scans can take, one user wiping the work of another (even if it's by mistake) is very problematic. So again, I can't tell if this is single-user or multi-user (webswing). If it is actually, properly, multi-user capable, it would be nice if the documentation had all the ins and outs of that fleshed out so I and others know what configurations there are we can use, what behaviour to expect, and things like that. If there is no multi-user capabilities, I would like to as that such a feature be added to the roadmap for completion "whenever".

I know that both of these are likely tall asks, and months to years to roll out, but I think they both are legitimately warranted for this tool, and I think it would help take it to the next level, so to say. So any chance we can get the balls rolling on these? Start that momentum so it might eventually come to reality? :) Please?

Thanks for such an awesome tool! \o/

**Comment by psiinon** [comment]
I'm afraid ZAP is currently a single user system, whether accessed via WebSwing, the Desktop or the API.
We did look at changing that but concluded that it would be too much work and not the best approach given where we are now.
I think its best to launch ZAP for each use and restrict each instance to one user.
We did have plans to create "ZAP as a Service" but unfortunately we decided that we couldnt resource it given the reletively small size of the core team.
For people who want something like that I suggest looking at the many 3rd parties who are building solutions on top of ZAP, we've listed all of the ones we aware of on https://www.zaproxy.org/third-party-services/

**Comment by BloodyIron** [comment]
Ahh that's understandable and unfortunate. Do you think it might happen "some day"? (asking out of curiosity)

As for one instance per user, that's likely achievable. Do you have any recommended methods for securing each instance behind auth? I'm not sure where my head should be at for auth in this kind of a topology (and what layer it operates at).

Also, the WebSwing documentation doesn't seem to talk about what happens if the web page is refreshed, or the docker instance restarted. What happens to the in-progress or scanning data/results in those scenarios? I think it would be useful for those gotchas/outcomes to be explained on said doc pages. Also hoping to take the response into consideration for day to day usage and planning (I don't wanna lose my results!).

**Comment by psiinon** [comment]
"Some day"? Who knows :)
Right now we just dont have enough contributors to think about starting it. If a load of the right people turned up tomorrow then sure, they could definitely work on it. But thats outside of our control.

TBH I think of the WebSwing option as a good way to run the ZAP desktop for people who dont want to install Java.
I dont see it as a good option for making ZAP as a Service.

If the docker instance is restarted then you lose everything. 
In theory you could map a local drive and use that for the ZAP db, in which case you souldnt lose the data. But thats not something I've tried.
Re refreshing the page - I'm not sure - try it and see, thats what I would do ;)

All of our docs are open source, so if you'd like to improve them then please go ahead.
All of those pages have an "Edit on GitHub" link at the bottom on them :D

**Comment by kingthorin** [comment]
ZaaS is already an idea and not being actively pursued. Since this issues hasn't had any feedback in a year I'm closing it. ZaaS as an idea will live on elsewhere.
