### ISSUE TITLE
ZAP  to support passing proxy configuration in order to test websites accessible behind a proxy in CI

### ISSUE THREAD

**Issue by mudit94** [zaproxy/zaproxy#7013]
**Is your feature request related to a problem? Please describe.**

ZAP should support passing proxy configuration in order to test websites accessible behind a proxy in CI
**Describe the solution you'd like**
ZAP should support passing proxy configuration in order to test websites accessible behind a proxy in CI. Proxy information should be set by using arguments
**Describe alternatives you've considered**

**Additional context**

**Would you like to help implementing this feature?**
Just say if you'd like to try and help implementing this feature. We'll provide any advice and guidance you need.

**Comment by psiinon** [comment]
All of the ZAP config settings can already be set via the command line: https://www.zaproxy.org/faq/how-do-you-find-out-what-key-to-use-to-set-a-config-value-on-the-command-line/

**Comment by thc202** [comment]
And the corresponding option: https://www.zaproxy.org/docs/desktop/ui/dialogs/options/connection/#use-proxy-chain

**Comment by mudit94** [comment]
Hi, @psiinon, It seems it seems the config for proxy chains is not working. I am just getting 1 url found.

**Comment by psiinon** [comment]
It seems "your config for proxy chains" is not working :)
In theory it could be a bug in ZAP but its more likely to be a mistake on your side.
Start a thread on the ZAP User Group https://groups.google.com/group/zaproxy-users giving as many details as you can.
