### ISSUE TITLE
wappalyzer: potential performance tweak

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#7014]
Implement something similar to https://github.com/AliasIO/wappalyzer/issues/5379#issuecomment-989454679, pre-processing rules to prevent regex scanning of huge strings.

**Comment by kingthorin** [comment]
Upstream code ref: https://github.com/AliasIO/wappalyzer/commit/91bcf03f8893c740ca553e1c2fdd7a5baaf7d038#diff-ad7c0e5878800a307cc8ca5b8b986a9565346764379d65c12a986ff0260b486dR518

**Comment by thc202** [comment]
Worth doing some tests to verify that the same applies in Java.

**Comment by kingthorin** [comment]
That makes sense, however, I think I’ll probably need advice on coming up with a practical way to do that.

**Comment by kingthorin** [comment]
https://www.oracle.com/technical-resources/articles/java/architect-benchmarking.html
