### ISSUE TITLE
Zap baseline not producing html report in gitlab

### ISSUE THREAD

**Issue by mudit94** [zaproxy/zaproxy#7015]
**Describe the bug**
Zap baseline.py is not producing report in gitlab
**To Reproduce**
Use the -r zap_report.html in zap-baseline.py

**Expected behavior**
HTML report should get generated

**Screenshots**

**Software versions**
 - ZAP: docker image owasp/zap2docker-stable
 - Add-on: Name and version [e.g. Passive Scan Rules Alpha v19. https://www.zaproxy.org/faq/how-do-i-see-what-version-of-an-add-on-extension-i-have-installed/]
 - OS: [e.g. Windows 10]
 - Java: [e.g. openjdk version "1.8.0_171"]
 - Browser: [e.g. chrome 66, firefox 59, safari 11.1]

**Errors from the zap.log file**
See https://www.zaproxy.org/faq/what-is-the-default-directory-that-zap-uses/ for the location of the zap.log file for your OS.

**Additional context**

**Would you like to help fix this issue?**
Just say if you'd like to try and help fix this issue. We'll provide any advice and guidance you need.

**Comment by psiinon** [comment]
What is the full command you are using (obfuscating sensitive info like the target)?
Do you get any errors, either on the command line or in the zap.log file?

**Comment by mudit94** [comment]
the issue is resolved. i added extra space character

**Comment by maartenkuijpers** [comment]
hi @mudit94 , I'm experiencing exactly the same thing but cannot get it solved. I cannot think of a place where I could add an extra space character... Could you please let me know what you did where?  Thanks!!
