### ISSUE TITLE
Bad request to API endpoint 

### ISSUE THREAD

**Issue by Koploseus** [zaproxy/zaproxy#7016]
**Describe the bug**
I'm launching a scan via the API, and i have an error with Spider : 

![image](https://user-images.githubusercontent.com/25018500/148918531-81c8b87d-68b0-4f59-b9e5-0ac0a79b2c43.png)
i get this : org.zaproxy.zap.extension.api.ApiException: no_implementor

**To Reproduce**
1. Use docker zap2docker-stable
2. docker run -u zap -p 8080:owasp/zap2docker-stable zap.sh -daemon -host 0.0.0.0 -port 6666 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true -config api.key=XXXXXX
3. Launch the scan
4. Wait for spider

**Screenshots**

**Software versions**
 - ZAP: [note that we typically only support the latest version of ZAP]
 - Add-on: Name and version [e.g. Passive Scan Rules Alpha v19. https://www.zaproxy.org/faq/how-do-i-see-what-version-of-an-add-on-extension-i-have-installed/]
 - OS: [e.g. Windows 10]
 - Java: [e.g. openjdk version "1.8.0_171"]
 - Browser: [e.g. chrome 66, firefox 59, safari 11.1]

**Comment by psiinon** [comment]
The wappalyzer add-on is not included by default in the stable image.
You will need to install it, eg using the command line option:
`-addoninstall wappalyzer`

**Comment by psiinon** [comment]
Thats assuming you are calling that API endpoint directly - is that the case?

**Comment by Koploseus** [comment]
Yes! 

I'm gonna try with the cli option

**Comment by Koploseus** [comment]
Ok so now i have this : 

![image](https://user-images.githubusercontent.com/25018500/148921453-7a7e6f4f-2603-4efb-b070-fe11f69d6c71.png)


And : 

![image](https://user-images.githubusercontent.com/25018500/148921482-a5068c6b-7002-40c0-a2aa-b623b732316e.png)

**Comment by psiinon** [comment]
The first doesnt bother me, those errors can probably be ignored.
I think the second one jusy means the site you requested was not found. Try usiong the `view/listSites/` to see what sites are available.

**Comment by Koploseus** [comment]
![image](https://user-images.githubusercontent.com/25018500/148922633-0b160e3c-7619-4e94-8f2d-aa5e20c48145.png)

Well it's inside

**Comment by kingthorin** [comment]
When you called `listSite` what did you pass as params?

We need you to be specific and tell us exactly what you’ve done along with the screenshots. Expecting us to guess the exact conditions isn’t going to work.

**Comment by Koploseus** [comment]
Well i pushed the API Key (that i use also for the ZAP api scanner launch ) 

![image](https://user-images.githubusercontent.com/25018500/148932754-5023d474-4bf0-4823-9949-fdfd4fb5d557.png)
I can find the url that i want to reach and test

**Comment by kingthorin** [comment]
I was referring to the singular call back here https://github.com/zaproxy/zaproxy/issues/7016#issuecomment-1009781126

**Comment by Koploseus** [comment]
Well i just launched the docker (with the same command line on my initial post + -addoninstall wappalyzer . 

I launched the scan via the API, it's started, and i only printed the logs of the docker and put the screenshot here.

**Comment by kingthorin** [comment]
The command in you original ticket entry is invalid, you’ve cropped something at the docker port mapping.

If what your saying is that you passed nothing to `listSite` (singular) then of course you got a does not exist exception, ZAP isn’t clairvoyant, it can’t read your mind to know which site you want the wappalyzer details for.

**Comment by Koploseus** [comment]
> The command in you original ticket entry is invalid, you’ve cropped something at the docker port mapping.
> 
> If what your saying is that you passed nothing to `listSite` (singular) then of course you got a does not exist exception, ZAP isn’t clairvoyant, it can’t read your mind to know which site you want the wappalyzer details for.

Yep i did saw it after.

I change it by : 

docker run -d  -u  zap -p 8090:8000 -i owasp/zap2docker-stable zap.sh -daemon -host 0.0.0.0 -port 8000 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true -config api.key=bdac94643a64d66afc1a5a6a285e40e4  -addoninstall wappalyzer (like on this doc)

How can i push it correctly ? I'm using Patrowl with it

**Comment by kingthorin** [comment]
If you want the wappalyzer details for a single site you pass the `site` param with the site you want details for. (Ex: when you listed sites you had two, so pass one of those values)

If you want wappalyzer details for all sites then use the `listAll` end point.

**Comment by psiinon** [comment]
This is not looking like a bug in ZAP - lets move the discussions to the ZAP User Group: https://groups.google.com/group/zaproxy-users
