### ISSUE TITLE
Use the sql file fuzzer in the baseline scan

### ISSUE THREAD

**Issue by priyanka-raghavan-maersk** [zaproxy/zaproxy#7019]
**Is your feature request related to a problem? Please describe.**
I use the SQL fuzzer in owasp zapdesktop a lot after i finish writing some code. 
It would be so nice if i could add this as a part of an automation suite of tests

**Describe the solution you'd like**
I would like to have the same way of doing a dockerized package baseline/apiscan and specify fuzzing of certain parameters and have output spit out.

**Describe alternatives you've considered**
I am trying to write a script now to do this.

**Additional context**

**Would you like to help implementing this feature?**
Absolutely. I am a c# developer but helping make some 1 line changes in Java on another project but can do.

**Comment by psiinon** [comment]
I'm not sure that this is a good option for the baseline scan tbh.
Just spitting out the fuzzer output will not help most users.
You can already call and ZAP API endpoint using the Scan Hooks: https://www.zaproxy.org/docs/docker/scan-hooks/
Admittedly the fuzzer doesnt support the API yet, but thats a different issue: https://github.com/zaproxy/zaproxy/issues/1689
