### ISSUE TITLE
Standardize risk for CSRF related scan rules (10202 & 20012)

### ISSUE THREAD

**Issue by MrAkansh** [zaproxy/zaproxy#7021]
**Describe the bug**
We have observed that Beta alert ID 20012 seems duplicate of Release alert ID 10202. Please review, if this is correct.
https://www.zaproxy.org/docs/alerts/20012/ (Name: Anti-CSRF Tokens Check )
https://www.zaproxy.org/docs/alerts/10202/ (Name: Absence of Anti-CSRF Tokens )

Also 

**Software versions**
 - ZAP: 2.11.1
 - Add-on: Name and version [e.g. Passive Scan Rules Alpha v19. https://www.zaproxy.org/faq/how-do-i-see-what-version-of-an-add-on-extension-i-have-installed/]
 - OS: [e.g. Windows 10]
 - Java: [e.g. openjdk version "1.8.0_171"]
 - Browser: [e.g. chrome 66, firefox 59, safari 11.1]

**Comment by kingthorin** [comment]
One is a passive scan rule, one is an active scan rule.

**Comment by MrAkansh** [comment]
Hi Kingthorin,

Thanks for quick response. Do you mean to  say 10202 is passive and 20012 is active but both rules are for checking Absence of Anti-CSRF Tokens.

**Comment by kingthorin** [comment]
> Do you mean to say 10202 is passive and 20012 is active

Yes.

> both rules are for checking Absence of Anti-CSRF Tokens.

The passive one simply checks whether they seem to be present. The active one attempts to abuse forms/submissions in a way to may proove they aren't in use.

**Comment by MrAkansh** [comment]
Great Thanks for the confirmation. It's appreciated. 
Since end result is same by both the rules (20012 & 10202 ) i.e. Absence of Anti-CSRF Tokens..  Should not they have the same severity? Currently, 20012 is at High, 10202  is at Low. 10202 is a release.

**Comment by kingthorin** [comment]
Arguably. I can discuss it with the team. With Firefox 96 just being released I believe all major browsers now apply samesite=lax to cookies so CSRF should be less of a concern, so perhaps there's worthy debate on that side as well.

It seems the two rules were developed at different times and likely worked on by different people. It seems reasonable that if you've confirmed (actively) that an issue is present the risk is High. While if you're simply missing a potential security control (of which there could be more than one) Low might be reasonable as well.

Anyway I'll try to bring it up with the team and see what people think.

**Comment by kingthorin** [comment]
https://groups.google.com/g/zaproxy-users/c/V6hfXbOvk5Q

**Comment by MrAkansh** [comment]
Hi Kingthorin,

how are you, hoping well.

Please review if any conclusion is reached on this. I agree with your inputs that both the rules should be brought to the same risk alert level. Is valid or not valid is a 

https://groups.google.com/g/zaproxy-users/c/V6hfXbOvk5Q

**Comment by thc202** [comment]
Could you update the issue title accordingly?

**Comment by MrAkansh** [comment]
Thanks @kingthorin @thc202 

Appreciate, your efforts on this issue.  Please confirm the conclusion on this, once ready to share.
