### ISSUE TITLE
No Ajax Spider checkbox in Quick start page in Latest version of Zap(2.11.1)

### ISSUE THREAD

**Issue by vigneshgan** [zaproxy/zaproxy#7023]
In earlier version of Zap, we could see Ajax spider checkbox which is useful to detect more URL's while running the full scan in Quick start screen. After updating to newer version i.e., 2.11.1, this option is missing, please fix this issue.

I am using Linux Fedora OS, screenshot is attached as below:

![Screen Shot 2022-01-13 at 3 46 46 PM](https://user-images.githubusercontent.com/14109606/149311541-a9a28507-e2e6-4cb4-9d5c-59238411f6bd.png)

**Comment by psiinon** [comment]
Do you have the Ajax Spider installed?
Its there on my install of 2.11.1 ...

**Comment by vigneshgan** [comment]
Yes Ajax Spider is added, check the screenshot below:

**Comment by psiinon** [comment]
Thats weird, it should be there then :/
Any errors in the zap.log file? https://www.zaproxy.org/faq/somethings-not-working-what-should-i-do/
Anyone else have this problem?

**Comment by kingthorin** [comment]
Are you able to launch firefox from the toolbar?

**Comment by vigneshgan** [comment]
Yes I can Launch firefox from zap:
![Screen Shot 2022-01-13 at 7 15 58 PM](https://user-images.githubusercontent.com/14109606/149341684-ac8653c4-7b4f-4d5f-b944-9242a0dcaf69.png)

**Comment by psiinon** [comment]
As per above comment- any errors in the zap.log file?

**Comment by vigneshgan** [comment]
The information provided is not enough for me to understand in that link and also I tried to find in Google, didn't get any solution, since I am new to Linux, please provide more info to get the zap.log file

**Comment by kingthorin** [comment]
Goto: https://www.zaproxy.org/faq/somethings-not-working-what-should-i-do/#check-the-log-file. In the "Check the log file" section read and click the "default directory" link, read:
> ### Linux
>
> ~/.ZAP

On your system goto `~/.ZAP`, ex: open a terminal and enter:
```console
cd ~/.ZAP
ls *.log
```

Review/provide whatever files are listed.

If `~/.ZAP` isn't found on your system then reach out to whoever supports your OS and ask them how they've packaged/changed things.

**Comment by vigneshgan** [comment]
Thank you @kingthorin , I got the log file. I have attached the file, please check why Ajax checkbox is not shown in GUI:
[Zaplog.txt](https://github.com/zaproxy/zaproxy/files/7880977/Zaplog.txt)

**Comment by thc202** [comment]
The cause should be "WARN  AddOn - Invalid add-on: …" try delete the files `~/.ZAP/plugin/selenium-release-15.6.0.zap` and `~/.ZAP/plugin/webdriverlinux-release-34.zap` and install the Selenium and WebDrivers add-on again.

**Comment by vigneshgan** [comment]
I have uninstalled Selenium and Linux Webdriver, Linux Webdriver could able to install it from Market place but I couldn't reinstall Selenium, searched in Market place, it's not available. Can you please suggest.

**Comment by thc202** [comment]
Maybe it's already installed? Could you provide the log again? (Just the part of a recent startup.)

**Comment by vigneshgan** [comment]
It was installed, I uninstalled it since you told me to do so, I have to install it, it's not available in Market place, it's not there in Install list as well. Due to this, I cannot run Ajax scan and I cannot launch browser from zap any more. I tried to reinstall Zap once again, still Selenium is not shown in installed add on. 
Can you tell me, how to uninstall Zap completely, so that I will install from scratch, in this way, I may get the Selenium add on. I have attached latest Zap log file. Please help..
[Zaplog (1).txt](https://github.com/zaproxy/zaproxy/files/7881906/Zaplog.1.txt)

**Comment by psiinon** [comment]
Try resetting the ZAP configs - theres an option on the bottom left of the Options dialog (from memory).

**Comment by psiinon** [comment]
Just reinstalling ZAP wont necessarily help - there are configs held in the std directory that wont get cleared that way: https://www.zaproxy.org/faq/what-is-the-default-directory-that-zap-uses/

**Comment by vigneshgan** [comment]
I did the restore defaults, still couldn't find Selenium add on in the installed add ons list. Is there any other way to install Add on apart from Market place?

**Comment by thc202** [comment]
It was not installed at least not properly as the log indicated that the add-on had errors, that's why I suggested deleting them. The latest log you provided still shows them, did you remove them?

**Comment by thc202** [comment]
And to be clear I'm referring to the add-ons not ZAP itself.

**Comment by vigneshgan** [comment]
Yes I removed it by using uninstall select from the installed list.
![Screen Shot 2022-01-17 at 6 38 35 PM](https://user-images.githubusercontent.com/14109606/149774862-ab1f96a6-e501-4083-81a8-7ac3a25d0a00.png)

**Comment by vigneshgan** [comment]
@thc202: Please let me know, if we uninstall an add-on, how to reinstall it again. I believed it should be available in Market place but it's not there. In that situation how to reinstall it again?

**Comment by kingthorin** [comment]
Goto ZAP's home directory and manually delete it from the `plugins` directory.

**Comment by thc202** [comment]
Delete both files mentioned previously. Once that's done you should be able to see the add-ons in the marketplace.

**Comment by vigneshgan** [comment]
@kingthorin and @thc202  : You people are awesome:), Thank you very much, I could see the Selenium in Market place now.

**Comment by kingthorin** [comment]
Great, let us know if the checkbox is visible again once you install it and restart ZAP.

**Comment by vigneshgan** [comment]
The Ajax issue is also resolved. I could see the check box now. Thank you all for your valuable time to assist me.
![Screen Shot 2022-01-18 at 10 25 37 AM](https://user-images.githubusercontent.com/14109606/149873879-7932a8de-2b39-4418-986f-e855199d1558.png)

**Comment by vigneshgan** [comment]
The issue is resolved, will close the issue.
