### ISSUE TITLE
Upgrading OWASP ZAP JWT addon

### ISSUE THREAD

**Issue by preetkaran20** [zaproxy/zaproxy#7028]
**Add-on repo**
https://github.com/SasanLabs/owasp-zap-jwt-addon/releases/tag/v1.0.2

**Your contact details**
preetkaran20@gmail.com

**Are you one of the authors**
Yes

**Licence**
Apache License 2.0

**Build instructions**
If not in the repo.

**Link to more information**

**Twitter handle for tool or author(s)**
@sasan_karan

**Promote to Beta or Release?**
Note that all new add-ons start at Alpha status.

**Anything else we should know**

**Comment by preetkaran20** [comment]
Hi team,

I have updated the binaries with newer changes as discussed: https://github.com/SasanLabs/owasp-zap-jwt-addon/releases/tag/v1.0.2

thanks,
Karan

**Comment by preetkaran20** [comment]
Hi @psiinon , 

When can we expect the addon release? Can you please help with releasing it early? 

Thanks, 
Karan

**Comment by kingthorin** [comment]
Sorry we lost sight of this, will try to get this going early next week.

**Comment by preetkaran20** [comment]
@kingthorin thankyou !!!

**Comment by thc202** [comment]
Closing, the newer version is now available in the marketplace.

**Comment by preetkaran20** [comment]
Thankyou @thc202 @kingthorin
