### ISSUE TITLE
PathTraversalScanRule rule Check 5 false positive, 100% repro

### ISSUE THREAD

**Issue by ghostinside** [zaproxy/zaproxy#7031]
if the database field is < 30 chars length the first request to field with value "thishouldnotexistandhopefullyitwillnot" (this is const from rule NON_EXISTANT_FILENAME) will return <> 200, as we got <> 200 the second request will be made (in our case the end of the API URL is /update, owasp makes the second request with field: "update") with value "update" in a field what leads to response 200 (just because the value fit the field length) & false-positive reported, to fix, please use in the second request the same length value

<> 200 request

{"Personal":null,"InstitutionAddressPhoneReport":"SASH\n10 High 94\nSalmon Arm , British Columbia VoE 1XO, Canada\n(250) 832-7447","ID":"65","PID":26,"EFROM":"1977-09-01T00:00:00.000Z","ETO":"1990-06-30T00:00:00.000Z","ENAME":"SASH","EADDRESS":"10 High 94","ECITY":"Salmon Arm ","ESTATE":"BC",**"EZIP":"thishouldnotexistandhopefullyitwillnot"**,"ECOUNTRY":"CA","EPROGRAM":"High School","EDEGREE":"sdfdsfs","EMAJOR":"dsfsdf","ISGRADUATE":true,"ETYPE":"0","BPHONE":"2508327447","ISGIBILL":false,"ETYPE_VALUE":"High School","ESTATE_VALUE":"British Columbia","ECOUNTRY_VALUE":"Canada"}

200 (second request)

{"Personal":null,"InstitutionAddressPhoneReport":"SASH\n10 High 94\nSalmon Arm , British Columbia VoE 1XO, Canada\n(250) 832-7447","ID":"65","PID":26,"EFROM":"1977-09-01T00:00:00.000Z","ETO":"1990-06-30T00:00:00.000Z","ENAME":"SASH","EADDRESS":"10 High 94","ECITY":"Salmon Arm ","ESTATE":"BC",**"EZIP":"update"**,"ECOUNTRY":"CA","EPROGRAM":"High School","EDEGREE":"sdfdsfs","EMAJOR":"dsfsdf","ISGRADUATE":true,"ETYPE":"0","BPHONE":"2508327447","ISGIBILL":false,"ETYPE_VALUE":"High School","ESTATE_VALUE":"British Columbia","ECOUNTRY_VALUE":"Canada"}

testing url

POST https://localhost/personal/api/Education/update

**Comment by psiinon** [comment]
Oh interesting - thanks for reporting this. I wonder if it impacts other scan rules in a similar way..

**Comment by ghostinside** [comment]
if you can also add a request ID to the alert report, it can save a lot of time during the investigation

**Comment by thc202** [comment]
Which report specifically?

**Comment by ghostinside** [comment]
here 

![image](https://user-images.githubusercontent.com/10547793/149996616-60a39b83-33ac-4e53-969e-e6b6f5841814.png)

i can see the request which leads to the alert, but it is hard to find which one was before or after to investigate sequence (if the rule use several requests), having ID i can easily find the sequence in active scan report & investigate

**Comment by kingthorin** [comment]
Check 5 purposefully re-uses the last portion of the URL path in parameter values in order to attempt a "local" traversal (perhaps inclusion would be a better word).

**Comment by sgerlach** [comment]
I DO think the regex might need to be case insensitive. Saw a payload with "error" in the body and returned 200 and FP'd
https://github.com/zaproxy/zap-extensions/blob/1feff0ca7f87d7d0fd5719b66514dee6dd800696/addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/PathTraversalScanRule.java#L476

Not sure that's related to the original example or not...

**Comment by kingthorin** [comment]
Per https://github.com/zaproxy/zaproxy/issues/7031#issuecomment-1015809942 check 5 is behaving as expected.

Per release [39](https://github.com/zaproxy/zap-extensions/releases/ascanrules-v39) and [45](https://github.com/zaproxy/zap-extensions/releases/ascanrules-v45) other on-topic improvements have been made. Check 5 is skipped at High threshold and the pattern was made case insensitive.
