### ISSUE TITLE
Cloud Metadata Potentially Exposed false positive 

### ISSUE THREAD

**Issue by EndPositive** [zaproxy/zaproxy#7033]
**Describe the bug**
The Cloud Metadata Potentially Exposed active rule generates false-positives for all 200 pages that instead do errorhandling/redirect using JavaScript.

**To Reproduce**
Example (reduced) response body that triggers an alert:

```
HTTP /1.1 200 OK
connection : close
content-length: 375
content-type: text/html

<html>
<body>
<script>
window.location = "https://www."+window.location.hostname.split('.')[window.location.hostname.split('.').length -2]+'.'+window.location.hostname.split('.')[window.location.hostname.split('.').length -1];
</script>
</body>
</html>
```

**Expected behavior**
The active rule detects the redirect and does not trigger an alert.

**Software versions**
 - ZAP: v2.11.1 In Docker
 - Add-on: CloudMetadataScanRule in ascanrulesBeta v39.0.0
 - OS: In Docker
 - Java: In Docker
 - Browser: In Docker

**Would you like to help fix this issue?**
Of course, but Java is not my best.

**Comment by kingthorin** [comment]
Leverage custom error pages? They exist to facilitate this exact issue, when apps/servers don't follow industry standards.

**Comment by EndPositive** [comment]
Custom error pages would indeed be a  quick fix for this issue. It would be really cool if we can detect such scenarios automatically. There's some work for this in `paros.core.scanner.Analyser.isFileExist`, which checks if some other page redirects to the same page. In this issue, we could do the same, but then allowing javascript to run (so that we redirect).

**Comment by kingthorin** [comment]
This scan rule could do a prelim dummy request (`/somefilethatshouldnotexistandlisteklydoesnot`) and see if that response is the same as the test response. If it does then don't alert, if it doesn't then alert. In your example above both should be the 200 page doing the JS redirect. The active scanner can't execute the JS but the scenario should still pan out.

**Comment by EndPositive** [comment]
Cool, I think that would solve the issue in most cases, except when the response body contains (part of) the url, thus not being identical on a random request.

**Comment by thc202** [comment]
@kingthorin did you check if with the custom pages the issue is addressed already? The Analyser does what's being suggested here and iirc the custom pages uses the Analyser.

**Comment by kingthorin** [comment]
I haven't checked yet. I do recall that we leveraged the analyser in some of the checks/methods I just don't recall which off the top of my head.

**Comment by kingthorin** [comment]
If the check of the header status code was replaced with [`isPage200(HttpMessage)`](https://github.com/zaproxy/zaproxy/blob/1f69b4fafbadb341dc95dc56ba1f5f3407ac589d/zap/src/main/java/org/parosproxy/paros/core/scanner/AbstractPlugin.java#L611-L630) then this would be covered by Custom Pages and Analyser.

**Comment by EndPositive** [comment]
Awesome, thanks a lot!

**Comment by sgerlach** [comment]
I know this is closed, but this test seems to be looking for some VERY specific content. I know customer error pages work is complete, but could/should add some response content checking here given that it's targeting some well known patterns?

**Comment by kingthorin** [comment]
Sure if there are known/stable patterns to look for.
