### ISSUE TITLE
Support for handling oauth 2.0 type authentication in zap baseline scan

### ISSUE THREAD

**Issue by mudit94** [zaproxy/zaproxy#7034]
I am using zap baseline scan via gitlab ci for testing a web application. The site uses oauth 2.0 type authentication sign-in mechanism. My application is like first it asks for username, then after username is verified, it asks for password. The authentication page is not on the same domain as that of the application

**Describe the solution you'd like**
Support for the authentication stated above

**Comment by adest** [comment]
👍

**Comment by psiinon** [comment]
Closing as done. If anyone has problems with the above solution then its best to first post to the user group: https://groups.google.com/group/zaproxy-users
