### ISSUE TITLE
Hidden File Finder false positive

### ISSUE THREAD

**Issue by EndPositive** [zaproxy/zaproxy#7036]
**Describe the bug**
In this specific case, a hidden file was found on a page that returned a 302 status code. I can imagine there are cases in which the redirect actually points to an existing file, but in this case the redirect is to an error page.

**To Reproduce**
Example (reduced) response body that triggers an alert:
```
HTTP /1.1 302 Found
location: /Error/ItemNotFound?aspxerrorpath=/.svn/entries
<html>
<head><title>Object moved</title></head>
<body>
<h2>Object moved to <a href="/Error/ItemNotFound?aspxerrorpath=/.svn/entries">here</a>.</h2>
</body>
</html>
```

**Expected behavior**
The alert it not triggered.

**Software versions**
- ZAP: v2.11.1 In Docker
- Add-on: Hidden File Finder in ascanrulesBeta v39.0.0
- OS: In Docker
- Java: In Docker
- Browser: In Docker

**Additional context**
This add-on already integrates with custom error pages and analyzer. I'm looking if we can find a way to improve the analyzer to detect this scenario.

**Would you like to help fix this issue?**
Of course, but Java is not my best.

**Comment by kingthorin** [comment]
The does the call at 626 callback to statuscode though?

**Comment by kingthorin** [comment]
@EndPositive there are dev docs here: https://www.zaproxy.org/docs/developer/

Most of the core team uses Eclipse, it's easy to run ZAP in debug mode.

You can run Unit Tests from within Eclipse as well, or you can use `./gradlew :aO:ascanrulesBeta:check` (that'll run all the unit tests for the whole add-on, so really eclipse is kinda handy for specific test methods or classes).

**Comment by kingthorin** [comment]
@EndPositive do you plan to try making these changes?

**Comment by kingthorin** [comment]
@EndPostitive can you confirm this is the handling you were concerned about?

![image](https://user-images.githubusercontent.com/7570458/157467828-acd3d3cb-5a24-4687-811b-709947291cce.png)

If so the current version of the HFF seems to handle it as expected.

**Comment by kingthorin** [comment]
Hmmm I might still be wrong. It seems the few sites I found were still 404'ing properly on paths that were asp or aspx.

**Comment by kingthorin** [comment]
I’ll see if I can get something going with Apache and PHP.

**Comment by kingthorin** [comment]
Okay here's what I built:
```
<VirtualHost *:80>
    DocumentRoot /Users/myuser/Downloads/xampp-portable-win32-5.6.23-0-VC11/xampp/htdocs/test.local
    ServerName test.local

    # Other directives here
    ErrorDocument 404 /err/404.php
</VirtualHost>
```

`404.php`
```php
<?php
	if (!empty($_SERVER['HTTPS']) && ('on' == $_SERVER['HTTPS'])) {
		$uri = 'https://';
	} else {
		$uri = 'http://';
	}
	$uri .= $_SERVER['HTTP_HOST'];
    $url =  "//{$_SERVER['HTTP_HOST']}{$_SERVER['REQUEST_URI']}";

    $escaped_url = htmlspecialchars( $url, ENT_QUOTES, 'UTF-8' );
	header('Location: '.$uri.'/err/error.php?page='.$escaped_url);
	exit;
?>
```

`error.php`
```php
<?php
	echo '<H1>'.$_GET["page"].' Not Found</H1>';
?>
```

So all 404 requests are 302d to error.php which echoes the path that wasn't found.

I discovered that Anlyser trusts the message's final response when checking things, so if it follows redirects by default then the above condition isn't caught. I'll be opening a PR to make hidden file requests not follow redirects.
