### ISSUE TITLE
WAF evasion by placing rate-limiting per-second feature.

### ISSUE THREAD

**Issue by elogada** [zaproxy/zaproxy#7037]
**Is your feature request related to a problem? Please describe.**
Cloudflare (among other WAFs) have a rate-limit feature wherein they will hand you an error code 429 if you send too much. This is problematic for some features such as Forced Browse, especially in the case of remote cloud environments (ie staged in Azure) wherein the requests are _far too fast_ for the simple "concurrent threads" setting.

**Describe the solution you'd like**
DirBuster had a solution for this: "Maximum Requests per Second". In my experience, 9 requests per second is enough to evade the Cloudflare rate-limit.

**Describe alternatives you've considered**
An alternative is a seconds/milliseconds-based delay system. This is similar to SQLMap or Dirb wherein you may place a millisecond-based delay.

**Additional context**
At present only "Concurrent Threads" is what I see (especially under Forced Browsing mode). It would be great if this were a Global feature. This is problematic in cloud solutions like AWS and Azure because even just 1 thread is enough to create extreme request rates.

**Would you like to help implementing this feature?**
I can only provide testing scenarios and beta testing of the feature. I am not adept at coding in Java sadly.

**Comment by thc202** [comment]
For Forced Browse it might just be a matter of exposing the option. I think there's already an issue for this.

**Comment by thc202** [comment]
There's a PR to add this globally: zaproxy/zap-extensions#4011.

**Comment by thc202** [comment]
Closing as done with the global rate limiting: https://www.zaproxy.org/docs/desktop/addons/network/options/ratelimit/
