### ISSUE TITLE
Updating ZAP to latest version on Parrot OS

### ISSUE THREAD

**Issue by Anthonymcqueen21** [zaproxy/zaproxy#7045]
Hello everyone, I have been trying to find online way to update the latest version of ZAP on Linux. I am currently using the Parrot OS system and I have updated the tools, but the overall project needs to be updated. Any help or suggestions would be greatly appreciated, thank you for the command line.

**Comment by kingthorin** [comment]
You’ll need to reach out to Parrot OS support and get them to update their package likely.

https://community.parrotsec.org/c/support/6

**Comment by kingthorin** [comment]
Seems like they do have 2.11.1 packaged, update however you normally would on Parrot.

https://deb.parrot.sh/parrot/pool/main/z/zaproxy/

**Comment by Anthonymcqueen21** [comment]
Alright thanks ill check it out.
