### ISSUE TITLE
Automation Framework: full auth script support

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#7048]
The current yaml for authentication is defined on https://www.zaproxy.org/docs/desktop/addons/automation-framework/environment/

Proposed yaml for script based authentication:
```
authentication:
  method: script
  parameters:
    script:          # String, path to script (at least full path, plan to add relative)
    scriptEngine:    # String, the name of the script engine to use
  scriptParameters:
    key1: value1
    key2: value2
  scriptCredentials:
    key3: value3
    key4: value4
```
Authentication scripts define the required and optional parameters they need as well as the credentials.
The yaml doesnt have to differentiate between required and optional parameters - the script will report if any required parameters are missing.
The credentials are passed to the script separately which is why they need to be in a separate element.

Note that the current session management script code does not handle script parameterts.
The plan is to add these as above, ie:
```
sessionManagement:
  method: script
  script:           # String, path to script (at least full path, plan to add relative)
  scriptEngine:     # String, the name of the script engine to use
  scriptParameters:
    key1: value1
    key2: value2
```
I might be able to make the `scriptEngine` element optional if the script has the right extension...

**Comment by psiinon** [comment]
It turns out session management already supports script params - I'll update the help to reflect this:
```
sessionManagement:
  method: script
  script:           # String, path to script (at least full path, plan to add relative)
  scriptEngine:     # String, the name of the script engine to use
  parameters:       # Key/value pairs required for scripts
    key1: value1
    key2: value2
```
The credentials are associated with the use rather than the auth script, so I'm thinking of changing the users section from
```
  users:                           # List of one or more users to use for authentication
  - name:                          # String, the name to be used by the jobs
    username:                      # String, the username to use when authenticating, vars supported
    password:                      # String, the password to use when authenticating, vars supported
```
to
```
  users:                           # List of one or more users to use for authentication
  - name:                          # String, the name to be used by the jobs
    credentials:                   # A list of key/value pairs - can include any needed for scripts
      username:                    # String, the username to use when authenticating, vars supported
      password:                    # String, the password to use when authenticating, vars supported
      exampleKey:                  # String, and example which would be passed onto an auth script as a credential
```
Hopefully I can change this in a backwards compatible way - so the old form will be read in but it will always be output in the new form.

The authentication section could also be simplified to move the `script` and `scriptEngine` elements into the existing `parameters` (in a backwards compatible way again) and also pass any additional ones onto the relevant script:
```
authentication:
  method: script
  parameters:                  # A list of key/value pairs - can include any needed for scripts
    script:                    # String, path to script (at least full path, plan to add relative)
    scriptEngine:              # String, the name of the script engine to use
    exampleKey:                # String, and example which would be passed onto an auth script
```

Thoughts?

**Comment by thc202** [comment]
Sounds good to me.

**Comment by thc202** [comment]
Done with zaproxy/zap-extensions#3491 ?

**Comment by psiinon** [comment]
Yes :D
