### ISSUE TITLE
How to stop freezing or crashing.

### ISSUE THREAD

**Issue by Anthonymcqueen21** [zaproxy/zaproxy#7050]
Hello Zap world my question is whenever i am on Attack mode and testing my target how do i minimize the risk of the application freezing and or crashing. Which leads to shut down and restart my work all over again and its just an annoyance what do i need to do to limit the active scanner and test each page manually with limitations. I am sure you guys get this question a lot but some insight and help to minimize this issue would help, thank you.

**Comment by psiinon** [comment]
Please ask questions on the ZAP User Goup: https://groups.google.com/group/zaproxy-users

**Comment by Anthonymcqueen21** [comment]
Thanks
