### ISSUE TITLE
Unable to execute zap authenticated scan by importing contexts (form based authentication)

### ISSUE THREAD

**Issue by mudit94** [zaproxy/zaproxy#7052]
**Describe the bug**
Unable to execute zap authenticated scan by importing contexts (form based authentication)

**To Reproduce**
IN a gitlab stage
I have below config 2022-01-27 09:10:28,780 http://localhost:48009 "GET http://zap/JSON/spider/action/scanAsUser/?contextId=1&userId=323&apikey= HTTP/1.1" 400 58
Traceback (most recent call last):
  File "/zap/zap-baseline.py", line 521, in main
    zap_spider(zap, target)
  File "/zap/zap_common.py", line 104, in _wrap
    return_data = func(*args_list, **kwargs)
  File "/zap/zap_common.py", line 420, in zap_spider
    raise_scan_not_started()
  File "/zap/zap_common.py", line 407, in raise_scan_not_started
    raise ScanNotStartedException('Failed to start the scan, check the log/output for more details.')
zap_common.ScanNotStartedException: Failed to start the scan, check the log/output for more details.
2022-01-27 09:10:28,782 Failed to find zap_log /zap/zap.out
2022-01-27 09:10:28,782 Trigger hook: pre_exit, args: 3
  script:
    - mkdir /zap/wrk
    - cp accessauth.context /zap/wrk
    - /zap/zap-baseline.py  -I -d  -U test -n accessauth.context -t "<url>" -r zap_report.html -z "-config connection.proxyChain.enabled=true -config connection.proxyChain.hostName=hostname -config connection.proxyChain.port=port" -m 10 -a -j
    - cp /zap/wrk/zap_report.html .

I am getting below error:
2022-01-27 09:10:28,780 http://localhost:48009 "GET http://zap/JSON/spider/action/scanAsUser/?contextId=1&userId=323&apikey= HTTP/1.1" 400 58
Traceback (most recent call last):
  File "/zap/zap-baseline.py", line 521, in main
    zap_spider(zap, target)
  File "/zap/zap_common.py", line 104, in _wrap
    return_data = func(*args_list, **kwargs)
  File "/zap/zap_common.py", line 420, in zap_spider
    raise_scan_not_started()
  File "/zap/zap_common.py", line 407, in raise_scan_not_started
    raise ScanNotStartedException('Failed to start the scan, check the log/output for more details.')
zap_common.ScanNotStartedException: Failed to start the scan, check the log/output for more details.
2022-01-27 09:10:28,782 Failed to find zap_log /zap/zap.out
2022-01-27 09:10:28,782 Trigger hook: pre_exit, args: 3

**Expected behavior**

**Screenshots**

**Software versions**
 - ZAP: [note that we typically only support the latest version of ZAP]
 - Add-on: Name and version [e.g. Passive Scan Rules Alpha v19. https://www.zaproxy.org/faq/how-do-i-see-what-version-of-an-add-on-extension-i-have-installed/]
 - OS: [e.g. Windows 10]
 - Java: [e.g. openjdk version "1.8.0_171"]
 - Browser: [e.g. chrome 66, firefox 59, safari 11.1]

**Errors from the zap.log file**
See https://www.zaproxy.org/faq/what-is-the-default-directory-that-zap-uses/ for the location of the zap.log file for your OS.

**Additional context**

**Would you like to help fix this issue?**
Just say if you'd like to try and help fix this issue. We'll provide any advice and guidance you need.

**Comment by thc202** [comment]
You should check ZAP's log to know the actual reason, the scan would not start if not able to access the target.

**Comment by psiinon** [comment]
This is likely to be a misconfiguration issue rather than a bug in ZAP.
In which case the User Group is a much better place to ask for assistance: https://groups.google.com/group/zaproxy-users
If it does turn out to be a bug in ZAP then we can raise a specific issue for that problem.
