### ISSUE TITLE
Font / text corruption on the GUI

### ISSUE THREAD

**Issue by mgelly-scr** [zaproxy/zaproxy#7053]
Hi, this is probably an issue with my installation but I cannot find what can be the issue.
After installing the windows version of ZAP 2.11.1, I have some corruption / misrendering of the font in the GUI

Here is a screen as an example:
![image](https://user-images.githubusercontent.com/45166103/151385677-8076e2fd-b2d1-49b6-b35b-8030e343fca6.png)

I tried reinstalling completely the software, rebooting, deleting the folder `C:\Users\{USER}\OWASP ZAP`, nothing.
Knowing that JRE is up to date and ZAP is the only software showing this issue.

Can you help me? Thank you.

**Comment by kingthorin** [comment]
Looks like you've set your language to something other than English.

You can either find this options screen and set it to English (which might mean trial and error of that menu is translated as well). Or you can just hit the restore defaults button in the bottom left:

![image](https://user-images.githubusercontent.com/7570458/151387955-989968a1-a5c8-4857-ad4a-7f2bd7ddd015.png)

**Comment by mgelly-scr** [comment]
Thank you for your response, but it seems this is not the problem.
I am a french user, so by default the language was set on french, I found the option and set it on the first value (normally english as I saw on another pc), and nothing has changed:

![image](https://user-images.githubusercontent.com/45166103/151393377-6af007f0-25ce-453a-a643-e39ff73fd236.png)

**Comment by psiinon** [comment]
Based on the file path you have given I'm guessing you are using Windows - which version?
And which JRE?

**Comment by mgelly-scr** [comment]
Indeed, as said before, I am on Windows:
- Windows 10 Pro 21H2 build 19044.1415
- JRE build 1.8.0_321-b07

@kingthorin : I did closed ZAP / start again, but nope no change and the language change was applied as some text were in english (like my screenshot above, but in english)

**Comment by kingthorin** [comment]
Could you share a screenshot of your ZAP Display settings? (You might have to resize the dialog to show all the content)
![image](https://user-images.githubusercontent.com/7570458/151398041-03a3ecf1-ba59-4c40-9c30-6fb3341d1b5a.png)

**Comment by mgelly-scr** [comment]
I "hope" this is the right screen, since I cannot read anything...
(in two parts, because of the broken display, the settings modal is huge)

![image](https://user-images.githubusercontent.com/45166103/151503689-45bd9c7d-8a22-44db-943a-870c5410c913.png)
![image](https://user-images.githubusercontent.com/45166103/151503817-6918dbc0-aabf-473b-981f-2d9a68585879.png)

**Comment by thc202** [comment]
Could you try setting a font?

**Comment by mgelly-scr** [comment]
Ok, changing the values for the font name seems to have fixed the issue.
What is the default font used by ZAP?

**Comment by thc202** [comment]
ZAP does not set a default, great to hear that's now working. Odd that it didn't happen in previous versions.

**Comment by thc202** [comment]
Should we close this? Not sure there's much we can do here.

**Comment by mgelly-scr** [comment]
Oh, sorry yes. Case close for my side. The issue seems to come from the default font used after installation. I do not know what could be the problem, but I could bypass this by using another font.
Thank you.

**Comment by thc202** [comment]
No problem.
