### ISSUE TITLE
False Positives for Timestamp Disclosure

### ISSUE THREAD

**Issue by sofiyanguyen** [zaproxy/zaproxy#7057]
**Describe the bug**
Getting false positives for Rule 10096 Timestamp Disclosure with values that could never be timestamps - eg, those beginning/ending in the following:
 - ending in `%`, eg  `.33333333%`
 - ending in `em` , eg `.33333333em`
 - ending in `rem`, eg `.33333333rem`
 - beginning with a `.`, eg `1.1592500000000001`
 - beginning with other numbers, eg `000000000000000000000000000000001`

**To Reproduce**
1. Run an active scan on a website containing the semantic offline stylesheet (sorry don't have an example site)
2. See false positives

**Expected behavior**
Scan excludes false positives that are identifiable by regex rules and prefixes/suffixes

**Screenshots**
![image](https://user-images.githubusercontent.com/62967560/151723141-ca4b6a16-1f5f-4f15-b4f2-b705480f0070.png)
![image](https://user-images.githubusercontent.com/62967560/151723160-5140e2b3-27c7-44d9-95f0-396ef6c957a0.png)

**Software versions**
 - ZAP: 2.11.1
 - OS: Windows 10
 - Java Version: Oracle Corporation 1.8.0_311
 - Browser: N/A

**Would you like to help fix this issue?**
No experience with Java, but could probably help.

**Comment by kingthorin** [comment]
> - ending in `%`, eg  `.33333333%`
> - ending in `em` , eg `.33333333em`
> - ending in `rem`, eg `.33333333rem`

Those three can likely be addressed.

> - beginning with a `.`, eg `1.1592500000000001`
Could be period delimited, there's nothing we can do about this.

> - beginning with other numbers, eg `000000000000000000000000000000001`

I thought this one was already addressed, will have to check.

**Comment by sofiyanguyen** [comment]
Good point about period delimiting. That first screenshot shows the last point - `1.1592500000000001` has more than 8 digits after the dot, yet only last 8 are highlighted.

**Comment by kingthorin** [comment]
I put together a UnitTest for the specific cases you mentioned, the only one that currently makes it through is the first one. Alerts are not raised for the rest.

```java
    @ParameterizedTest
    @ValueSource(strings = {"0.33333333%", "0.33333333em", "0.33333333rem", "1.1592500000000001", "000000000000000000000000000000001"})
    void shouldNotRaiseAlertOnIrrelevantValues(String value) throws Exception {
        // Given
        HttpMessage msg = createMessage(value);
        // When
        scanHttpResponseReceive(msg);
        // Then
        assertEquals(0, alertsRaised.size());
    }
```

Handling the first case is as simple as changing the regex from `\\b[0-9]{8,10}\\b` to `\\b[0-9]{8,10}\\b(?!%)`.

Would you be able to provide full responses that you got alerts on? The evidence highlighting in ZAP's alerts is based on first match.

**Comment by sofiyanguyen** [comment]
Sorry - I don't think I can provide the response, since it's the bundled js code for my application. I've tested that regex against my response body and it's not coming back with any hits. The weird thing is, I test it with the old regex and get the same result - no matches. But there are at least a hundred alerts in the ZAP GUI (with Threshold Medium/Default for that Passive scan rule). I'm not sure why this is happening. At the very least, you got one fix out of it so I'm happy to leave it at that.

**Comment by kingthorin** [comment]
After the updated rule is released please let us know if you see further occurrences. Also remember to check the response(s) for multiple occurrences of the evidence string.
