### ISSUE TITLE
Docker image - Disabling scan rules at command line not working

### ISSUE THREAD

**Issue by tspearconquest** [zaproxy/zaproxy#7060]
**Describe the bug**
Hi, we run zap in a docker image as: `zap-full-scan.py -t "target" -d -j -I -a -g full-scan.conf -r full-scan-report.html -z "-config 90003=IGNORE"` but the Subresource Integrity Attribute missing section still appears in our scan report.

**To Reproduce**
1. `docker pull owasp/zap2docker-weekly`
2. `docker run --rm -it owasp/zap2docker-weekly`
3. Scan some target which has no subresource integrity attributes: `zap-full-scan.py -t "target" -d -j -I -a -g full-scan.conf -r full-scan-report.html -z "-config 90003=IGNORE"`
4. Observe SRI attribute missing warnings appear in the output from the scan
5. Check report and find SRI attribute missing section still appears

**Expected behavior**
ID 90003 would not be checked at all, making the scan faster, and reducing findings in the report for things we don't care about in our development environment.

**Screenshots**

**Software versions**
 - ZAP: weekly docker image
 - Add-on: the ones installed by default in the weekly docker image
 - OS: Ubuntu 18.04 (Azure managed Kubernetes nodes)
 - Java: n/a
 - Browser: n/a

**Errors from the zap.log file**

**Additional context**
Its not very clear what the key/value pairs should contain with the `-z "-config aaa=bbb"` argument because the config file generated with -g doesn't have anything that matches that `aaa=bbb` syntax, so I am hoping that I'm just misunderstanding something.

We have stopped other findings in our reports before by adding the ID to the `ignore_scan_rules` array in the python script in the image, but that was done that way because we run zap as a cron job in kubernetes and adding the ID into the file in the image was the simple way to disable that rule for all of our environments, whereas here we want to avoid modifying the image in order to keep the SRI attribute checks on prod but not dev.

**Comment by thc202** [comment]
That's not a valid config. The state of the packaged scans' scan rules are configured with the configuration file.

**Comment by tspearconquest** [comment]
Ok thanks, now I have an idea for how to get this done via the config file. Could you help me understand where to find the key=value pairs that are valid for the -config flag, so that I understand its use better?

**Comment by kingthorin** [comment]
https://www.zaproxy.org/faq/how-do-you-find-out-what-key-to-use-to-set-a-config-value-on-the-command-line/

Since we've identified that there isn't actually an issue here the [ZAP User Group]( https://groups.google.com/group/zaproxy-users) is a much better place for questions/discussion.
