### ISSUE TITLE
90003\tIGNORE does not work in zap-full-scan.py

### ISSUE THREAD

**Issue by tspearconquest** [zaproxy/zaproxy#7061]
**Describe the bug**
In follow up to #7060 I ran the same command as I posted previously, without the -z flag, and generated a clean config file. Then I modified that config file to make 90003 show as IGNORE instead of WARN.

```
zap@dev-scan-manual-4vb87:/zap$ grep 90003 full-scan.conf
90003	IGNORE	(Sub Resource Integrity Attribute Missing - Passive/alpha)
```

Then I ran zap again as: `zap-full-scan.py -t "target" -d -j -I -a -c ../full-scan.conf -r full-scan-report.html`

The report still came out with the SRI attribute missing warning finding.

**To Reproduce**
1. `docker pull owasp/zap2docker-weekly`
2. `docker run --rm -it owasp/zap2docker-weekly`
3. Scan some target which has no subresource integrity attributes: `zap-full-scan.py -t "target" -d -j -I -a -g full-scan.conf -r full-scan-report.html`
4. Modify the generated full-scan.conf file to ignore 90003
5. Scan the target again with this command line: `zap-full-scan.py -t "target" -d -j -I -a -c full-scan.conf -r full-scan-report.html`
6. Observe SRI attribute missing warnings appear in the output from the scan
7. Check report and find SRI attribute missing section still appears

**Expected behavior**
SRI attributes would not be checked at all, making the scan faster, and reducing findings in the report for things we don't care about in our development environment.

**Screenshots**

**Software versions**
 - ZAP: weekly docker image
 - Add-on: the ones installed by default in the weekly docker image
 - OS: Ubuntu 18.04 (Azure managed Kubernetes nodes)
 - Java: n/a
 - Browser: n/a

**Errors from the zap.log file**

**Additional context**
Its not very clear what the key/value pairs should contain with the `-z "-config aaa=bbb"` argument because the config file generated with -g doesn't have anything that matches that `aaa=bbb` syntax, so I am hoping that I'm just misunderstanding something.

We have stopped other findings in our reports before by adding the ID to the `ignore_scan_rules` array in the python script in the image, but that was done that way because we run zap as a cron job in kubernetes and adding the ID into the file in the image was the simple way to disable that rule for all of our environments, whereas here we want to avoid modifying the image in order to keep the SRI attribute checks on prod but not dev.

**Comment by kingthorin** [comment]
The config file you created controls the results of the scan, not the content of the report. These are fundamentally different things.

Related:
- https://github.com/zaproxy/zaproxy/issues/6291
- https://github.com/zaproxy/zaproxy/issues/5212
- https://github.com/zaproxy/zaproxy/issues/5019
