### ISSUE TITLE
Add a way to disable passive scan rules from plugins that doesn't require access to the API

### ISSUE THREAD

**Issue by tspearconquest** [zaproxy/zaproxy#7071]
**Is your feature request related to a problem? Please describe.**
Hello, I've been trying to find a way to remove findings regarding missing Subresource Integrity attributes from our organization's ZAP scan reports.

It seems we need to disable scan rule 90003. The documentation and issues I've reviewed so far seem to indicate that the only way to disable this rule is via the API, but we have configured ZAP in such a way that prevents any access to the API for security and automation reasons.

I tried posting on the user group to find a way to disable this scan rule without access to the API, but didn't get a response: https://groups.google.com/g/zaproxy-users/c/dyQ9U9MPF20

So I can only conclude that this is not possible at this time and thus I have opened a feature request.
If the feature exists, I have not been able to find any documentation thus far relating to how to use it, so in that case, this feature request is for more/better documentation.

**Describe the solution you'd like**
Please create a way to disable scan rules from plugins that doesn't require access to the API.

**Describe alternatives you've considered**
See my post in the user group which is linked above. Details about this are provided there.

**Comment by psiinon** [comment]
Yes it is possible.
The user group is the right place for questions, you just need some patience :)
