### ISSUE TITLE
ZAP API Scan fails to parse swagger definition

### ISSUE THREAD

**Issue by Ed87** [zaproxy/zaproxy#7073]
I have .NET 5 API that I am running a ZAP API scan against . 

When I run this command from Windows 10 it works perfect and the report is generated - for this first  use-case I have the API hosted in IIS on Windows Server 2016 :

`docker run -v "$(pwd):/zap/wrk/:rw" -t owasp/zap2docker-weekly zap-api-scan.py -t http://10.XXX.XXX.XXX:8002/account?field4=4488082040118"&"field7=GENERIC01"&"field10=ABC076 -f openapi  -r C:\Users\tshumaed\Documents\DEPLOYS\ZAP_Report.htm
`
My error occurs when I switch to Linux . I have hosted the API on a k0s cluster on Debian 10 Buster and run the command as:
`docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-weekly zap-api-scan.py -t http://10.XXX.XXX.XXX:32518/account?field4=4488082040118"&"field7=GENERIC01"&"field10=DCF43 -f openapi -r ~/home/golide/Projects/ZAP_REPORT.htm`

The command gives an error:
```
12575 [ZAP-daemon] INFO  org.parosproxy.paros.extension.ExtensionLoader - Initializing Passive Scan Rules
12575 [ZAP-daemon] INFO  org.parosproxy.paros.extension.ExtensionLoader - Initializing Ajax Spider Automation Framework Integration
12579 [ZAP-daemon] INFO  org.parosproxy.paros.extension.ExtensionLoader - Initializing Handles all of the calls to ZAP services
12801 [ZAP-daemon] INFO  org.zaproxy.addon.oast.services.callback.CallbackService - Started callback service on 0.0.0.0:42279
12811 [ZAP-daemon] INFO  org.zaproxy.addon.network.ExtensionNetwork - Creating new root CA certificate.
14810 [ZAP-daemon] INFO  org.zaproxy.addon.network.ExtensionNetwork - New root CA certificate created.
17862 [ZAP-daemon] INFO  org.parosproxy.paros.CommandLine - Add-on update check complete
17866 [ZAP-daemon] INFO  org.parosproxy.paros.CommandLine - Add-on already installed: /zap/./plugin/pscanrulesBeta-beta-29.zap
17868 [ZAP-daemon] INFO  org.zaproxy.zap.DaemonBootstrap - ZAP is now listening on 0.0.0.0:47455
22574 [ZAP-Import-OpenAPI-1] WARN  org.zaproxy.zap.extension.openapi.ExtensionOpenApi - Failed to parse OpenAPI definition.

org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerException: Failed to parse swagger defn null
22575 [ZAP-Import-OpenAPI-1] WARN  org.zaproxy.zap.extension.openapi.ExtensionOpenApi - Failed to parse swagger defn null
org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerException: Failed to parse swagger defn null
        at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.readOpenAPISpec(SwaggerConverter.java:200) ~[openapi-beta-26.zap:?]
        at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.getRequestModels(SwaggerConverter.java:184) ~[openapi-beta-26.zap:?]
        at org.zaproxy.zap.extension.openapi.ExtensionOpenApi$1.run(ExtensionOpenApi.java:365) [openapi-beta-26.zap:?]
22655 [ZAP-ProxyThread-10] INFO  org.parosproxy.paros.core.scanner.Scanner - scanner started
23400 [Thread-6] INFO  org.parosproxy.paros.core.scanner.HostProcess - Scanning 2 node(s) from http://10.170.8.204:32518
23403 [Thread-6] INFO  org.parosproxy.paros.core.scanner.HostProcess - start host http://10.170.8.204:32518 | RemoteFileIncludeScanRule strength MEDIUM threshold MEDIUM
..............
............
```

The report is missing also in the export directory.

What am  I missing ? @psiinon

**Comment by kingthorin** [comment]
ZAP doesn’t seem to be able to retrieve the spec to parse. Likely a networking or timing issue between things starting up.

**Comment by Ed87** [comment]
Very strange  @kingthorin  given that I am running the command on the actual server where the API is hosted.

Actually I switched to this Linux instance because the command was timing out when the API was on a remote Windows server.
What can I do , if anything , to get around this issue ?****

**Comment by kingthorin** [comment]
Does that URL actually host an OpenAPI definition because it looks as if it’s an actual direct API endpoint.

**Comment by Ed87** [comment]
.Net 5 by default creates an API Project that is configured with the OpenAPI spec, if thats what you mean . Yes , its an API endpoint and I have been able to run ZAP scan against the same - only that this time the API was hosted on a Windows server and I was running the command from **_my Local Windows PC_**.  
How can I check if the URL hosts/contains an OpenAPI definition -- not sure though what that means exactly , my understanding is that since the scan worked when I was in Windows context it means ZAP is already able to detect an OpenAPI definition

**Comment by Ed87** [comment]
Can I exec into the ZAP container and try to curl the URL ? Im guessing thats a first to see the actual issue

**Comment by kingthorin** [comment]
When you access the /account end point as you have in your example does it return whatever the response is to that action or a full openapi spec? Because zap is expecting you to point to the spec not an individual endpoint with params.

I have no idea why it may have seemed to work before and not now, I don’t have access to your history or environment. You’ll have to debug it.

**Comment by kingthorin** [comment]
The [ZAP User Group]( https://groups.google.com/group/zaproxy-users) is a much better place for questions like this.
