### ISSUE TITLE
Automation Framework - import job

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#7078]
Add a new job to the [Automation Framework](https://www.zaproxy.org/docs/desktop/addons/automation-framework/) - sugested interface:
```
 - type: import                        # Import a file of requests
    parameters:
      type:                            # String: One of ['har', 'modsec2', 'url', 'zaplog']
      fileName:                        # String: Name of the file containing the requests
```
The job should be part of the [exim](https://www.zaproxy.org/docs/desktop/addons/import-export/) add-on.
The implementation will be very similar to the [soap job](https://www.zaproxy.org/docs/desktop/addons/soap-support/automation/).
Initial soap job PR: [2765](https://github.com/zaproxy/zap-extensions/pull/2765/files)
Latest soap job code: [org/zaproxy/zap/extension/soap/automation](https://github.com/zaproxy/zap-extensions/tree/main/addOns/soap/src/main/java/org/zaproxy/zap/extension/soap/automation)

**Comment by LakiG** [comment]
Hi
I would like to work on this issue. Can you please assign this to me?

**Comment by thc202** [comment]
Assigned.

**Comment by psiinon** [comment]
Great! Let us know if you need any more advice and guidance with it.
