### ISSUE TITLE
Get False Positive count using alertCountsByRisk  api

### ISSUE THREAD

**Issue by d-apurva** [zaproxy/zaproxy#7079]
**Is your feature request related to a problem? Please describe.**
I have automated the process of scanning api and ui using zap api's and Jenkins. The automation is working fine end to end and I am creating a Github issue also attaching the reports generated by ZAP.
In Github issue description I am providing count of Low, High, Medium and Informational alerts using alertCountsByRisk api.
In some scenarios I am marking some of the alerts to False Positive. So now I can see the count of all alerts except for False Positive.
And I have automated script such a way that if all alerts count are zero, Github issue will be closed with a comment that there is no vulnerability, so closing the issue
Now I want to provide the information about False Positive count also.

**Describe the solution you'd like**
Now if I run alertCountsByRisk  api, I get output as
`{"High":0,"Low":0,"Medium":0,"Informational":2}`
But I want output as
`{"High":0,"Low":0,"Medium":0,"Informational”:0, "FalsePositive":2}`

**Comment by psiinon** [comment]
This is where the API endpoint is defined: https://github.com/zaproxy/zaproxy/blob/1f69b4fafbadb341dc95dc56ba1f5f3407ac589d/zap/src/main/java/org/zaproxy/zap/extension/alert/AlertAPI.java#L75

**Comment by abhinav-koppula** [comment]
Hi,
I am interested in working on this issue. Can you please assign this to me?

**Comment by d-apurva** [comment]
@abhinav-koppula Do we have any update on this?

**Comment by LakiG** [comment]
Hi,
In case the issue is not being worked on, I would be interested in it.

**Comment by d-apurva** [comment]
@LakiG as there is no update from @abhinav-koppula .
So can you please help with this.

**Comment by LakiG** [comment]
Sure
@zap team, is it okay if I can work on this?

**Comment by thc202** [comment]
It would be preferable to finish the other issue first.

**Comment by thc202** [comment]
Reassigned.
