### ISSUE TITLE
Automate all the scans in the site map

### ISSUE THREAD

**Issue by MR-pentestGuy** [zaproxy/zaproxy#7094]
### Is your feature request related to a problem? Please describe.

Hi Zap Team, I would like to know if it is possible to scan and spider multiple sites at the same time like the burp suite 

### Describe the solution you'd like

It would be better if we can scan all the sites at once 

### Describe alternatives you've considered

.

### Would you like to help fix this issue?

- [X] Yes

**Comment by kingthorin** [comment]
Add them all to a Context and scan the context as the target.

**Comment by kingthorin** [comment]
The [ZAP User Group]( https://groups.google.com/group/zaproxy-users) is a much better place for questions.

**Comment by psiinon** [comment]
Also, you can start as many spiders and active scans as you want (and your machine can handle) at the same time.
Right click a node, Attack. Spider of Active scan etc
The relevant tabs have pull downs so you can select the scan you want.
