### ISSUE TITLE
Active scanning is scanning all websites, not only the ones in the list

### ISSUE THREAD

**Issue by oabuoun** [zaproxy/zaproxy#7104]
### Describe the bug

ZAP HUD is active scanning all websites referred to by the original site you want to scan, even if they are not in allow list.

Description:
I'm running ZAP 2.11.1 on Ubuntu 20.04 inside a VM (VirtualBox). I was testing ZAP on JuiceShop for one of my course. I started ZAP, then I started the preconfigured Firefox Browser. I visited 127.0.0.1:3000 (juiceshop) and then chose to run the Spider, Ajax Spider, Active scanning on the 127.0.0.1:3000. 
Suddenly after sometime, I found out that it's actually scanning other websites which mostly used by firefox and mozilla for different activities, such a: stop-tracking, etc

I thought that I misconfigured the test. I repeated the test again but this time I disabled the the network on the whole physical machine, I found out that it tried to active-scan firefox URLs but it got error 502 since there is no network this time.

I checked the log of the previous session and it's the same thing. HUD is trying to scan all sites.

### Steps to reproduce the behavior

1. Run JuiceShop
2. Start ZAP
3. Start thenpreconfigured Firefox Browser in ZAP
4. Visit 127.0.0.1:3000
5. Run Spider, AJAX Spider and active scanning, Attack mode for 127.0.0.1:3000
6. Check the log in ZAP and you will find that other sites are being included in the log

### Expected behavior

Only the main website you added in the list should be included in the active-scanning

### Software versions

ZAP 2.11.1 on Ubunut 20.04 (inside VM: VirtualBox)

### Would you like to help fix this issue?

- [X] Yes

**Comment by psiinon** [comment]
No, ZAP is not actively scanning these sites, it is only passively scanning them.
Thats what ZAP does.
If you want to ask more questions about this then the User Group is the best place to ask: https://groups.google.com/group/zaproxy-users
