### ISSUE TITLE
Scripts as First Class Scan Rules

### ISSUE THREAD

**Issue by ricekot** [zaproxy/zaproxy#7105]
### Is your feature request related to a problem? Please describe.

Elevate scripts to the same level as scan rules.

Scan Rules | Scripts
-- | --
Each scan rule has a unique ID. They are all documented [here](https://github.com/zaproxy/zaproxy/blob/main/docs/scanners.md). | Most scripts do not have a unique ID.
Active Scan Rules are categorized and can be added to [Scan Policies](https://www.zaproxy.org/docs/desktop/start/features/scanpolicy/). | Scripts can’t be added individually to scan policies.
Scan Rules cannot be edited while ZAP is running. | Scripts can be edited while ZAP is running via the Script console.
Active Scan Rules can scan the Host | Active Scripts cannot scan the host (see https://github.com/zaproxy/zaproxy/issues/5595)
  | Script scan rules can check the attack strength and alert threshold, though that's currently tied to the "main" script active scan rule
Scan rules are shown on https://www.zaproxy.org/docs/alerts/ | A/Pscan scripts are currently not shown on https://www.zaproxy.org/docs/alerts/ (WebSocket pscan rules are)
Scan rules are not disabled when an exception occurs | a/pscan rules are currently disabled when an exception is encountered

## Active Scan Scripts
- Register and add a unique ID to all active scripts
- Show scripts in the scan policy selection menu and allow adding them to scan policies
- Allow active scan scripts to scan the host once
- Add attributes of scan rules to scripts as well (e.g. alert threshold, strength, etc.)

## Passive Scan Scripts
- Add a unique ID to all passive scripts (including websocket)

## Scan Rule Scripts Without IDs
New scripts added by the user may not contain IDs. Or they could be using an ID already reserved by another scan rule / script.

This could be solved in the following ways:
- Scan Rule Scripts will be invalid until the user adds a unique ID for them, or,
- A unique ID is automatically generated for each new script. 

## Script Naming Scheme
Add a uniform naming scheme for scripts - but that may break some people's workflows who use the script name to enable / disable it via the API. To prevent that, link the old names to the old ones or use synonyms or aliases or something similar. Maybe this could be done (or also done) via Alerts' source.

### Describe alternatives you've considered

Convert all scripts to Java scan rules?

### Would you like to help fix this issue?

- [ ] Yes

**Comment by psiinon** [comment]
Re naming schemes: https://twitter.com/psiinon/status/1504475442484432897 :D
