### ISSUE TITLE
Remove code deprecated in 2.6.0

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#7106]
This is a handle turning exercise - no coding skill is needed, you just need to be thorough :)

1. Find out what needs to be removed: `grep -R deprec zap/src/main/java | grep "2.6.0"` - there should be 41 matches
2. Remove the classes / methods / fields found above
3. Add a `ZAP` header to any `paros` code changed (see examples below)
4. Add the affected classes / methods / fields to `zap/zap.gradle.kts` (see below)
5. Run `spotlessApply`
6. Run `./gradlew japicmp` - it should pass, if not check the report it generates
7. Update the corresponding help file (see below)

Example PRs:

2.2.0 + 2.3.0: code: https://github.com/zaproxy/zaproxy/pull/7067 help: https://github.com/zaproxy/zap-core-help/pull/414
2.4.x: code: https://github.com/zaproxy/zaproxy/pull/7068 help: https://github.com/zaproxy/zap-core-help/pull/415
2.5.0: code: https://github.com/zaproxy/zaproxy/pull/7102 help: https://github.com/zaproxy/zap-core-help/pull/420

**Comment by jini0x** [comment]
Hi Simon, I can assist here.

**Comment by jini0x** [comment]
![image](https://user-images.githubusercontent.com/53784718/156021709-4df3d2a7-a40c-4aef-b3b4-7eaa5056b69a.png)

There is @SuppressWarnings("deprecation") comment in PopupMenuRemove without the version(2.6.0)

**Comment by thc202** [comment]
That's the suppression of the warning which had to be added because of the deprecation of the method, the call can be  removed.

**Comment by jini0x** [comment]
Any idea about this error: 
![image](https://user-images.githubusercontent.com/53784718/156030254-51d75565-098a-4215-a912-4f824ef22d7a.png)

**Comment by thc202** [comment]
That's steps 4 and 6 of the issue description.

**Comment by jini0x** [comment]
I think I need to add the path for the class and remove the parameter name...
For example: "org.zaproxy.zap.control.AddOn#AddOn(String text)" --> "org.zaproxy.zap.control.AddOn#AddOn( java.lang.String)"

**Comment by thc202** [comment]
That's correct (take a look at the referenced pull requests).

**Comment by jini0x** [comment]
Yes I'm learning from that pull req, but this time it's more complex(thank you for your time), I have 3 problems :

1- [enumeration](https://github.com/zaproxy/zaproxy/blob/main/zap/src/main/java/org/zaproxy/zap/extension/brk/ExtensionBreak.java):
  fieldExcludes->"org.zaproxy.zap.extension.brk.ExtensionBreak#DialogType" **(not sure how to add an enum type)**
 methodExcludes->"org.zaproxy.zap.extension.brk.ExtensionBreak#dialogShown(org.zaproxy.zap.extension.brk.ExtensionBreak.DialogType)"

2 -"[org.zaproxy.zap.spider.Spider#Spider](https://github.com/zaproxy/zaproxy/blob/main/zap/src/main/java/org/zaproxy/zap/spider/Spider.java)(org.zaproxy.zap.extension.spider.ExtensionSpider,org.zaproxy.zap.spider.SpiderParam,ConnectionParam,org.parosproxy.paros.model.Model,org.zaproxy.zap.model.Context)",

3- [SC class](https://github.com/zaproxy/zaproxy/blob/main/zap/src/main/java/org/zaproxy/zap/view/ScanPanel2.java) :
org.zaproxy.zap.extension.spider.ExtensionSpider,org.zaproxy.zap.spider.SpiderParam,ConnectionParam,org.parosproxy.paros.model.Model,org.zaproxy.zap.model.Context)",
        "org.zaproxy.zap.view.ScanPanel2#ScanPanel2(java.lang.String, javax.swing.ImageIcon, org.zaproxy.zap.view.SC, org.parosproxy.paros.common.AbstractParam)" **(SC is extending ScanController class)**

**Comment by thc202** [comment]
1. The `DialogType` should be added to `classExcludes`, e.g.: `"org.zaproxy.zap.extension.brk.ExtensionBreak\$DialogType"`.
2. It's missing the package for `ConnectionParam`.
3. Use the class `org.zaproxy.zap.model.ScanController`.

**Comment by jini0x** [comment]
Finally, thank you very much 
![image](https://user-images.githubusercontent.com/53784718/156066390-b7c9909b-f39d-4567-a4ff-a9a718f1ba85.png)

**Comment by jini0x** [comment]
Help changes can be found here: [#425](https://github.com/zaproxy/zap-core-help/pull/425)
