### ISSUE TITLE
False Positive: Server Side Code Injection - ASP Code Injection

### ISSUE THREAD

**Issue by jhowlett96** [zaproxy/zaproxy#7107]
Hi,

I have recently ran two scans using ZAP and found two independent false positives using the 'Server Side Code Injection - ASP Code Injection' rule. 

They were both found in URL '.*.png' on two seperate png files. Both outputs also have a content type of 'image/png'. 

**Alert information for one of the alerts:**

**Response Body:** 
```
PNG

IHDR(-S9PLTEÿÿÿµÿÿÿ½1ÀÀÀyÿÿºÿËcÿß{ÿÓkÿóÿ÷¥}ÿû÷ÿçÿë F8tRNS@æØfbIDATx^UÊWÃ0CA¤SËý%Òþá xÀÂÍìåëîÁ8<3Ü gø¼ÙNáJkZ+üÆ>E¸üÂG´?¶p¤"¹= ZHË©IHúÃ553`ÓIEND®B`
```

**Attack:**
 "+response.write([{0}*{1})+"

**Evidence:**
 0

Both alerts had an evidence: 0

I have looked at the source code and it states that it uses 2 7-digit random numbers. Therefore all that should be needed to fix this is to add a minimum limit of '1' so that '0' cannot be used (which is what creates evidence of '0').

**Comment by psiinon** [comment]
The rule is https://www.zaproxy.org/docs/alerts/90019/ - that includes a link to the code.
One possible fix could be to not scan images or similar binary files, at least at medium strength. I think we've done that for other rules.
If so this could be an easy one to fix..

**Comment by jhowlett96** [comment]
That is one solution but doesn't fix the root of the problem which is a multiply by 0 that causes the evidence to be '0' and so this could also happen in a .asp page with content type of text/html.

[Line](https://github.com/zaproxy/zap-extensions/blob/3717d3f02fda505eccf1a60a9b5abca00776b1ef/addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/CodeInjectionScanRule.java#L240-L241)

Extert from _https://www.geeksforgeeks.org/java-util-random-nextint-java/_
java.util.Random.nextInt(int n) : The nextInt(int n) is used to get a random number between 0(inclusive) and the number passed in this argument(n), exclusive.
