### ISSUE TITLE
Commit message format in contribution guidelines not clear

### ISSUE THREAD

**Issue by rugk** [zaproxy/zaproxy#7109]
https://github.com/zaproxy/zaproxy/blob/main/CONTRIBUTING.md#what-we-zap-team-expect-from-you

It says there:
> For example: https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#format-commit-messages

However, the linked site has changed apparently and the linked headline cannot be found anymore, only a line length limit can be found.

---

Personally I can BTW recommend https://www.conventionalcommits.org/ as a standard way that also has a lot of tools around e.g. for automatic Changelog generation out of these commits etc.
In case you want to change that.

**Comment by kingthorin** [comment]
Good catch, thanks.
