### ISSUE TITLE
Authentication launch parameters PLEASE

### ISSUE THREAD

**Issue by BloodyIron** [zaproxy/zaproxy#7113]
### Is your feature request related to a problem? Please describe.

I am trying to get the ZAP docker container(s) to work in our k8s environment with an initial implementation. In that, do a full-scan to a target URL, output html report, there we go.

The part that I am finding particularly obnoxious and painful to work with (and I'm being very unsuccessful with, btw) is the aspect of authentication.

Some of our websites (that are pre-prod) use HTTP authentication, where the HTTPD prompts for username/password. For the time being, that's how some of our websites work. The username and password are not sensitive content whatsoever.

So I need a way to pass the username and password when first accessing the website and then scan the whole website. Pretty basic stuff. But for the life of me I cannot wrap my head around how exactly this is achieved properly.

In one regard, I'm trying to figure out how to use a context file, but that is painful to generate, and seems to FORCE me to declare every single FQDN (and wildcards) that could possible be relevant here. But I want to do that when I pass the TARGET URL parameter to the scan command. I only care about the context file because it seems I _NEED_ it to be able to use an HTTP username/password.

Okay, so let's try the Automation Framework example. Well, there's a section that talks about... environment variables, but also mentions yaml structure? Which is it... environment variables, or YAML structure? I can't actually tell from this documentation, because there are NO examples of how to use this in either YAML or environment variables. The closest I can find is some sort of mention of proxy auth headers for environment variables, but that even further muddies down the water as to what can and cannot be done!

### Describe the solution you'd like

Here's what I NEED. I NEED the ability to pass "--authentication_mode" (HTTP/whatever), "--username $username", "--password $password" to the launch parameters of the scan. Whether it's the zap-full-scan.py, or Automation framework, or whatever. Or something of equivalent SIMPLE functionality.

I have been burning so much time just trying to wrap my head around how the most basic of authentication works in this program, and I STILL cannot tell how tf to use it.

YES I know this is an insecure method, because passwords could be insecurely injected. In this case I'm willing to accept it because those credentials are NOT sensitive. Let ME have the choice.

Launch parameters are also preferable because it makes automating the use of the docker containers in yaml k8s files wayyyyy better than having to inject a context file into a docker image. Like really, the docker container usage here is less than ideal. It doesn't even have awscli by default so I can upload the report to an s3 bucket (which I have had to cobble together a work-around to do)

### Describe alternatives you've considered

I've read all the documentation I can find, looked for as many examples as I can, and I still can't figure out how to get HTTP authentication working in docker in any convenient or usable way.

### Would you like to help fix this issue?

- [ ] Yes

**Comment by BloodyIron** [comment]
I have seriously gone to hell and back trying to figure this out. This really is problematic.

**Comment by kingthorin** [comment]
Please don't ask questions as issues - the [ZAP User Group]( https://groups.google.com/group/zaproxy-users) is a much better place for questions.

You can also find all kinds of info about automating ZAP here: https://www.zaproxy.org/docs/automate/ or by using your favorite search engine.

**Comment by BloodyIron** [comment]
I clicked on the "Feature Request" button when creating the ticket. How exactly is this not a feature request? PLEASE RE OPEN @kingthorin

**Comment by kingthorin** [comment]
It’s not a feature request because ZAP already handles BASIC authentication you just have to set it up and use it.

**Comment by BloodyIron** [comment]
You did not actually read my request. The request is to have the authentication as launch parameters, and the justification is also included. This is a feature request. Do you not see the problem I have? Or do you just not care?

**Comment by kingthorin** [comment]
It’s all already doable.

**Comment by psiinon** [comment]
Yes, we care.
But this is already achievable so it is not a feature request, its a question about how to use existing functionality.
If you're having problems setting up ZAP then ask questions on the right forums, dont just raise issues.

**Comment by BloodyIron** [comment]
> It’s all already doable.

It is already doable to declare HTTP authentication, username and password with launch parameters, instead of the context file? Because so far as I can tell from the documentation, and the output of --help/equivalent, it is not already doable.

**Comment by BloodyIron** [comment]
> Yes, we care. But this is already achievable so it is not a feature request, its a question about how to use existing functionality. If you're having problems setting up ZAP then ask questions on the right forums, dont just raise issues.

This is asking for a feature that doesn't exist, in that, the declarations are done so as a launch parameter (to the scripts/automation framework), not declared in a context file, that needs to be injected into an ephemeral docker container. The inclusion of where my frustration derives in the original post is to give functional context.

**Comment by psiinon** [comment]
Please take this discussion onto the User Group: https://groups.google.com/group/zaproxy-users
If as a result we agree that improvements are needed then we will be very happy to open new feature request issues.
