### ISSUE TITLE
CSP 'unsafe-inline' in default-src without script-src/style-src present doesn't raise alert

### ISSUE THREAD

**Issue by jhowlett96** [zaproxy/zaproxy#7120]
### Describe the bug

If script-src or style-src isn't present in CSP then it takes the value of the default-src. Zap only tests if the script-src is present then tests for 'unsafe-inline' however there should be an else case that tests for the presence of 'unsafe-inline' in the default-src if script-src/style-src is not present.

### Steps to reproduce the behavior

create CSP without script-src and style-src. 
add 'unsafe-inline' to defaut-src

### Expected behavior

An alert created for script-src if 'unsafe-inline' present in default-src and script-src is not present in CSP.
An alert created for style-src if 'unsafe-inline' present in default-src and style-src is not present in CSP.

### Software versions

pscanrules, version=39.0.0

### Would you like to help fix this issue?

- [ ] Yes

**Comment by kingthorin** [comment]
@jhowlett96 thanks for raising this. Fix is inbound :grinning:

**Comment by thc202** [comment]
I did nothing though.
