### ISSUE TITLE
Unable to send manual POST requests

### ISSUE THREAD

**Issue by volkan-ozdemir** [zaproxy/zaproxy#7136]
### Describe the bug

Hi,

It looks like OWASP ZAP can't craft a manual POST request from scratch and it always sends it as a GET request.

### Steps to reproduce the behavior

1. Open a website with .php form (http://example.com/example.php).
2. Create a manual request .php page. Select POST as method and fill the body with request parameters.
3. OWASP Zap will send the request as a GET.
4. Open another unrelated website with a post form. Fill the form and send it as usual so that OWASP Zap will catch a POST request.
5. Manually edit this POST request and just change the request adress.
6. OWASP Zap will now correctly send POST requests.

In essence, it looks like OWASP Zap cannot convert an original GET request to POST request.

### Expected behavior

OWASP Zap should be able to correctly change the method of request via manual request editor.

### Software versions

OS: Kali 2022.1

OWASP ZAP
Version: 2.11.1
Installed Add-ons: [[id=alertFilters, version=13.0.0],
[id=ascanrules, version=44.0.0], [id=automation,
version=0.13.0], [id=bruteforce, version=11.0.0],
[id=callhome, version=0.3.0], [id=commonlib, version=1.8.0],
[id=custompayloads, version=0.11.0], [id=diff,
version=11.0.0], [id=directorylistv1, version=5.0.0],
[id=directorylistv2_3, version=4.0.0],
[id=directorylistv2_3_lc, version=4.0.0], [id=domxss,
version=12.0.0], [id=encoder, version=0.6.0], [id=exim,
version=0.1.0], [id=formhandler, version=4.0.0], [id=fuzz,
version=13.6.0], [id=fuzzdb, version=8.0.0],
[id=fuzzdboffensive, version=4.0.0], [id=gettingStarted,
version=13.0.0], [id=graaljs, version=0.2.0], [id=graphql,
version=0.8.0], [id=help, version=14.0.0], [id=hud,
version=0.13.0], [id=importurls, version=9.0.0], [id=invoke,
version=11.0.0], [id=jython, version=12.0.0], [id=network,
version=0.1.0], [id=oast, version=0.10.0], [id=onlineMenu,
version=9.0.0], [id=openapi, version=26.0.0],
[id=pscanrules, version=39.0.0], [id=quickstart,
version=33.0.0], [id=replacer, version=9.0.0], [id=reports,
version=0.12.0], [id=requester, version=5.0.0], [id=retest,
version=0.2.0], [id=retire, version=0.10.0], [id=reveal,
version=4.0.0], [id=saverawmessage, version=7.0.0],
[id=savexmlmessage, version=0.3.0], [id=scripts,
version=30.0.0], [id=selenium, version=15.7.0], [id=soap,
version=13.0.0], [id=spiderAjax, version=23.7.0],
[id=sqliplugin, version=15.0.0], [id=tips, version=9.0.0],
[id=tokengen, version=15.0.0], [id=wappalyzer,
version=21.9.0], [id=webdriverlinux, version=36.0.0],
[id=websocket, version=24.0.0], [id=zest, version=35.0.0]]
Operating System: Linux
Java Version: Debian 11.0.14
System's Locale: en_CA
Display Locale: en_GB
Format Locale: en_CA
ZAP Home Directory: /home/volkan/.ZAP/
ZAP Installation Directory: /usr/share/zaproxy/./
Look and Feel: FlatLaf Light (com.formdev.flatlaf.FlatLightLaf)

### Additional context

Issue looks similar to: https://github.com/zaproxy/zaproxy/issues/5592

### Would you like to help fix this issue?

- [ ] Yes

**Comment by kingthorin** [comment]
Please add the request you crafted and can’t send.

**Comment by mir-cybernetics** [comment]
Original Request:
GET http://10.10.102.107/challenges//chall3.php?file=test HTTP/1.1
Host: 10.10.102.107
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Connection: keep-alive
Referer: http://10.10.102.107/challenges/chall3.php
Upgrade-Insecure-Requests: 1

Edited Request:
POST http://10.10.102.107/challenges//chall3.php HTTP/1.1
Host: 10.10.102.107
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Connection: keep-alive
Referer: http://10.10.102.107/challenges/chall3.php
Upgrade-Insecure-Requests: 1
Content-Length: 9

file=test

I found this bug while trying to tackle Challenge 3 of File Inclusion vulnerabilities on tryhackme (https://tryhackme.com/room/fileinc)

So converting a GET request to POST doesn't work and OWASP Zap keeps sending it as a GET request.

**Comment by volkan-ozdemir** [comment]
Original Request:
GET http://10.10.102.107/challenges//chall3.php?file=test HTTP/1.1
Host: 10.10.102.107
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,/;q=0.8
Accept-Language: en-US,en;q=0.5
Connection: keep-alive
Referer: http://10.10.102.107/challenges/chall3.php
Upgrade-Insecure-Requests: 1

Edited Request:
POST http://10.10.102.107/challenges//chall3.php HTTP/1.1
Host: 10.10.102.107
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,/;q=0.8
Accept-Language: en-US,en;q=0.5
Connection: keep-alive
Referer: http://10.10.102.107/challenges/chall3.php
Upgrade-Insecure-Requests: 1
Content-Length: 9

file=test

I found this bug while trying to tackle Challenge 3 of File Inclusion vulnerabilities on tryhackme (https://tryhackme.com/room/fileinc)

So converting a GET request to POST doesn't work and OWASP Zap keeps sending it as a GET request.

**Comment by thc202** [comment]
The log should contain the details of what's wrong.

**Comment by volkan-ozdemir** [comment]
I'm closing the issue, it looks like problem is actually related to how http server handles the Content-Type header.

ZAP doesn't automatically update the Content-Type header on original GET requests that are converted to POST requests.

Adding `Content-Type: application/x-www-form-urlencoded` to POST request fixes the issue.
