### ISSUE TITLE
Browser Recorder

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#7139]
ZAP should already be able to cope with any form of authentication, but it can be painful to set up by the user.
An option to launch a browser to record the authentication sequence in a way that can be replayed as an auth script could be really helpful for some apps.
However recording what a browser does is non trivial.

One option it to fork and extend an existing project:

[Selenium Recorder](https://github.com/seleniumhq/selenium-ide) allows you to record and playback test automation for the web. Note that this is being rewritten as an electron app.

[Headless recorder](https://github.com/checkly/headless-recorder) is a Chrome extension that records your browser interactions and generates a Playwright or Puppeteer script. 

Any other similar open source project is also a candidate for using.

Another option is to implement our our browser add-on 'inspired' by existing projects.

Ideally we would support both Firefox and Chrome, but just supporting one of those browsers would be better than nothing.
The script generated does not really matter as long as it runs reliably in ZAP and handles all common browser interactions required for authentication. Note that client side Zest is an option here.

User experience is very important - we want this to be as easy to use as possible. Browser extensions are a good option here as we can now launch browsers with any extensions installed.

Support and maintenance is also important - the less ongoing maintenance the better.

This is a non trivial project but could be ideally suited for GSoC.

**Comment by psiinon** [comment]
Its unlikely that we will have an embedded browser again.
We did bundle JxBrowser but they changed the licence agreement.
Right now ZAP can use any modern browser thats installed. 
We can start them with Firefox or Chrome plugins - we do that for Eval Villian: https://www.zaproxy.org/docs/desktop/addons/eval-villain/

**Comment by levihackerman-102** [comment]
Ahh, so basically in this project the add-on will attach whichever extension we use to the browser when launched form ZAP? 
If we go the extension route that is

**Comment by levihackerman-102** [comment]
Also, headless-recorder doesn't support automatic cookie handling as of now, would this feature be required for our use case?

**Comment by psiinon** [comment]
So headless recorder doesnt handle cookies? I'd expect that to be a significant problem for authentication flows, which are a key usecase for this development. We could inject them in ZAP but it would be a pain...

**Comment by levihackerman-102** [comment]
Selenium does provide options to set cookies so I guess we could make that work that way...

**Comment by Avinash-Acharya** [comment]
Is Java being used in this? (except the TypeScript which was mentioned in the idea list)

**Comment by thc202** [comment]
Java will be needed, for ZAP side.

**Comment by psiinon** [comment]
I'm expecting the main functionality will be Type Script.

**Comment by Avinash-Acharya** [comment]
Since I have no knowledge of Type Script, It will be hefty to learn both, the language and to learn how to contribute to this .
Would you recommend me going forward and learning, or should I just look for a different project to work on.

**Comment by Avinash-Acharya** [comment]
- Does following the basic structure of selenium and the headless recorder to build ZAP extension enough?(except pentesting)
- If I am sure , This extension will do the same job of an ZAP app but the extension only pentest the particular webpage the user is on, because attacking and generating the report for multiple pages (whole website) takes lot of time.

**Comment by aryangupta701** [comment]
To confirm the direction of my thinking about this project, I am considering the development of a browser extension that is inspired by Selenium IDE. The extension will record user actions such as clicking, typing, usernames, and passwords (with measures in place to ensure the security of sensitive information). It may also record cookies, although the purpose of these cookies in replaying is still under consideration. The extension will communicate with a Java application to send all recorded actions. These actions can then be used to generate a script in Java for automating replaying. This script can be used as an authentication script for an application that requires it.

However, I have some questions regarding the project. Firstly, as users may have different authentication techniques, how can the extension cope with these variations? Secondly, I would like further clarification on the replaying aspect of the project. Does replaying only involve integrating the script with other applications to use it as an authentication script, or is there more to it?

**Comment by psiinon** [comment]
Sorry for the delayed responses - things have been a bit busy for me recently :/
I'm actually a fan of learning languages by using then to develop non trivial stuff - if you know Java Script then learning Type Script should not be too big an ask. Thats what I'm doing right now 😁 
Yes, we would want a browser extenson which runs on both Firefox and Chrome which can record all user interactions.
These would be relayed to ZAP via the ZAP API (its easy to add new endpoints).
ZAP already supports scripting, so we can use either selenium scripts or Zest scripts (which use selenium) to replay them.
The fact that we are recording user interactions should mean we can cope with all of the authentication techniques (with the possible exception of 2FA). 
We just need to be able to run the authentication scripts from ZAP, via the ZAP desktop, in daemon, and cmd modes.

**Comment by aryangupta701** [comment]
Okay, Thank you I got it.

**Comment by Aarav238** [comment]
@psiinon  it should be in any specific tech stack ? or we can decide the tech stack for it . As i can understand you want a extension that records the user activities while logging in and logging out . I have done lot of backend work in authentication, I like working on backend too. I would like to work on it as  this is the something of my interest. This should be a extension or anything else?

**Comment by aryangupta701** [comment]
I looked into the `scripts` addon and I was thinking of integrating the replay functionality with the 'scripts` . Is it possible for the zest scripts to follow along with the `script` generated during recording which involved user interactions also? Or will integration of the replay functionality with a headless browser and testing once the authentication has been done will be more correct?

**Comment by Avinash-Acharya** [comment]
@aryangupta701 You may find [This](https://youtube.com/playlist?list=PLhW3qG5bs-L8qJoRNpkQX_NVrHwYjVxe9) helpful.

**Comment by psiinon** [comment]
I would aim to keep the tech stack as light as possible.
On the ZAP side we should already include everything needed, but if any new libraries are required then they can be added. The functionality would be added as a ZAP add-on.
On the client side I have a confession to make - we already have a browser extension in development. This would provide most of the stack required for the client side as well.
The extension uses Type Script, and I'd be keen for the Browser Recorder to use that as well. 
Again libraries can be added, but based on experience the more client side libraries added the harder it gets to maintain, so minimising those would be ideal.
Ideally the Recorder would generate Zest scripts - if we find we need something that Zest cannot currently do then we would aim to extend Zest 😁 
We can already launch and control browsers using Zest.

**Comment by aryangupta701** [comment]
Oh, so a browser extension is already under development. So, do we need to work on an extension for the browser recorder under this project or not?

**Comment by psiinon** [comment]
@aryangupta701 @Aarav238 (and anyone else interested in this issue) can you send an email to me: psiinon@gmail.com
I'll share some more backgroun info...

**Comment by KushalGhosh9899** [comment]
Hey, I was going through this issue and done some researched to solve this issue. 
Just wanted to confirm is anyone working on it or may i take it?

**Comment by aryangupta701** [comment]
hey, @KushalGhosh9899 I am working on this issue :). But since this is a GSoC project more than one people can apply their proposal to the mentor and they will select it. It is up to you if you want to apply or not.

**Comment by psiinon** [comment]
@KushalGhosh9899 as @aryangupta701 explained this is a Google Summer of Code project.
As such it will only be assigned if/when a GSoC proposal to implement this project has been accepted through GSoC.

**Comment by KushalGhosh9899** [comment]
Got it @aryangupta701,best of luck buddy.

**Comment by Darkcoder011** [comment]
hello i am Abhijit dengale 
i want to be the part of your community Through this GSOC 2023
 i want more info About the Project to write the proposal

Thanks!!

**Comment by kingthorin** [comment]
See above, and jump in tackling some issues prior to GSoC.

**Comment by Darkcoder011** [comment]
ok thanks @kingthorin

**Comment by Selwan7131** [comment]
Hello I want to contribute to this project! 
I will be here  mentioning the advantages and disadvantages of both solutions you proposed:
fork and extend an existing project: 
	advantages:
		Including leveraging an existing codebase. 
                Speeding up development time.
		Taking advantage of a pre-existing user base. 
	disadvantages:
		Ensuring compatibility with ZAP, conflicts may occur because of dependencies.
		Code maintenance in case the forked code was modified.
implement our our browser add-on 'inspired' by existing projects:
	advantages:
		Control over the project.
		Cutomization based on your needs
		Avoiding compatibility issues
	disadvantages:
		Long development time
		Effort will be needed for users to adapt it because it will be a new extension they are not used to.

**Comment by thc202** [comment]
Can/should we close this now? https://www.zaproxy.org/blog/2023-09-11-browser-recorder/

**Comment by psiinon** [comment]
Implemented! Good work @aryangupta701 😁
