### ISSUE TITLE
Param digger add-on (GSoC)

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#7140]
[Param Miner](https://portswigger.net/bappstore/17d2949a985c4b7ca092728dba871943) is a Burp extension which identifies hidden, unlinked parameters. It's particularly useful for finding web cache poisoning vulnerabilities.
It is based on this research by James Kettle: https://portswigger.net/research/practical-web-cache-poisoning

This feature was requested via twitter: https://twitter.com/hahwul/status/1502642090232414208

This will be a non trivial development but could be an idea GSoC (or similar) project

---

See: https://github.com/zaproxy/zaproxy/issues/7140#issuecomment-1144734876 for follow-on tasks.

**Comment by kingthorin** [comment]
Might be able to draw some ideas from this project as well: https://github.com/s0md3v/Arjun

**Comment by ArkaprabhaChakraborty** [comment]
Can I be assigned this issue? :)

**Comment by kingthorin** [comment]
Super short list?
https://github.com/lutfumertceylan/top25-parameter

Could also leverage the HUNT lists.
https://github.com/bugcrowd/HUNT/blob/master/Remix/ZAPRemix/src/main/kotlin/HuntData.kt

**Comment by ArkaprabhaChakraborty** [comment]
Thank you @. I'll try to use them too. This will speed up the bruteforce process and will also help to identify what type of attack can be carried out with these parameters.

**Comment by kingthorin** [comment]
Just ideas, don't let any of it interfere with actually finishing/progressing :wink:

**Comment by ArkaprabhaChakraborty** [comment]
More projects to be considered during research!!
https://twitter.com/hahwul/status/1538539422437609472

**Comment by ArkaprabhaChakraborty** [comment]
Thanks @hahwul!

**Comment by ArkaprabhaChakraborty** [comment]
Another sort of list https://wordlists.assetnote.io/
:)

**Comment by ArkaprabhaChakraborty** [comment]
7 PRs merged! More incoming! Woohoo! :)

**Comment by kingthorin** [comment]
This may also provide some ideas:
https://github.com/maK-/parameth

**Comment by ArkaprabhaChakraborty** [comment]
> This may also provide some ideas: https://github.com/maK-/parameth

Wow, this tool is OLD :). It uses python 2 :).

**Comment by ArkaprabhaChakraborty** [comment]
> This may also provide some ideas: https://github.com/maK-/parameth

So this one has deprecated hard :)  and I can't set this project up :). Taking ideas from this would be a tough one since I can't tinker with it :). But I'll try :).

**Comment by kingthorin** [comment]
I think their README includes details on using virtual env, also there's a PR you could review/pull that adds a docker'ized version.

Anyway don't get stuck on it, it just came up in my suggestions this morning so I passed it along.

**Comment by ArkaprabhaChakraborty** [comment]
I had a glance through the code :) it was a short one so didn't take much time [ Compared to mine.. ahem ahem :) ]. I can implement this as a final check If none of the dedicated guesses finds anything. Sort of like a final tactic hit.

**Comment by ArkaprabhaChakraborty** [comment]
Can this issue be reanmed to Param Digger? :) Since its the primary issue Im using for tracking :).

**Comment by ArkaprabhaChakraborty** [comment]
I think this can be closed now. We can create a new tracker issue for Param Digger
