### ISSUE TITLE
SQLi Report Flag is incorrect

### ISSUE THREAD

**Issue by ahmadfikrimasyhur** [zaproxy/zaproxy#7163]
### Describe the bug

![image](https://user-images.githubusercontent.com/30574371/159650490-0f644c44-2d88-4c63-a2a6-40ff1a029f98.png)

The result of the scan has Red Alert Flag on the SQLi menu, that is I think is incorrect, 
because when I test in Postman with the same request parameters the response has expected behavior.

### Steps to reproduce the behavior

1. go to quick start
2. fill url check use traditional spider and ajax spider
3. then click attack

### Expected behavior

not added on the SQLi menu

### Software versions

2.11.1

### Would you like to help fix this issue?

- [ ] Yes

**Comment by psiinon** [comment]
"SQL injection may be possible" - strictly speaking this is true :)
You havnt provided us with enough information to either determine if it is true or not or to do anything about it if it is not true.
We dont have access to your app.
