### ISSUE TITLE
Loss of new line chars for GZIP HTTP responses returned by the API

### ISSUE THREAD

**Issue by DiogoMRSilva** [zaproxy/zaproxy#7171]
### Describe the bug

When the content encoding of a message response is gzip the method `httpMessageToSet` of `ApiResponseConversionUtils.java` reads the unzipped content line by line and forgets to add the new line chars to the string is going to add to the ApiResponseConversionUtils. The code where this happen is:
```java
if (HttpHeader.GZIP.equals(
                msg.getResponseHeader().getHeader(HttpHeader.CONTENT_ENCODING))) {
            // Uncompress gziped content
            try (ByteArrayInputStream bais =
                            new ByteArrayInputStream(msg.getResponseBody().getBytes());
                    GZIPInputStream gis = new GZIPInputStream(bais);
                    InputStreamReader isr = new InputStreamReader(gis);
                    BufferedReader br = new BufferedReader(isr); ) {
                StringBuilder sb = new StringBuilder();
                String line = null;
                while ((line = br.readLine()) != null) {
                    sb.append(line);
                }
                map.put("responseBody", sb.toString());
            } catch (IOException e) {
                LOGGER.error("Unable to uncompress gzip content: " + e.getMessage(), e);
                map.put("responseBody", msg.getResponseBody().toString());
            }
        } else {
            map.put("responseBody", msg.getResponseBody().toString());
        }
```

### Steps to reproduce the behavior

1. Make a request to a server that responds with gzip encoding using the ZAP API ( `/JSON/core/action/accessUrl/`)
2. On the API request result check if the response has new line chars.

### Expected behavior

The response should have new line characters.

### Software versions

The main branch

### Would you like to help fix this issue?

- [X] Yes

**Comment by thc202** [comment]
Assigned.
