### ISSUE TITLE
automation: Add save-as

### ISSUE THREAD

**Issue by tkisason** [zaproxy/zaproxy#7178]
Edit: **See https://github.com/zaproxy/zaproxy/issues/7178#issuecomment-1118991263**

---

### Describe the bug

This is an issue in the ZAP GUI. When the user wants to create a new automation job, he adds the automation tab, adds the parameters, fills in the variables, etc. After the first save if an user alters the job and wants to save the new plan the interface is bugged and he cannot save the job, the file picker window doesn't show up. 

### Steps to reproduce the behavior

1. Create a new automation job in the ZAP GUI
2. Edit the automation job, add parameters, etc.
3. Save the plan (a file picker opens up and the user selects where to save the new yaml file)
4. Run the plan to test it out
5. Alter the job
6. Try to save the altered plan, the save option doesn't work work and the file picker doesn't open. 

### Expected behavior

on 6. the file picker should appear when the user clicks "Save Plan"

### Software versions

OWASP ZAP
Version: 2.11.1
---
Installed Add-ons: [[id=alertFilters, version=13.0.0],
[id=ascanrules, version=43.0.0], [id=automation,
version=0.9.0], [id=bruteforce, version=11.0.0],
[id=callhome, version=0.0.3], [id=commonlib, version=1.6.0],
[id=diff, version=11.0.0], [id=directorylistv1,
version=5.0.0], [id=domxss, version=12.0.0], [id=encoder,
version=0.6.0], [id=formhandler, version=4.0.0], [id=fuzz,
version=13.5.0], [id=gettingStarted, version=13.0.0],
[id=graaljs, version=0.2.0], [id=graphql, version=0.7.0],
[id=help, version=14.0.0], [id=hud, version=0.13.0],
[id=importurls, version=8.0.0], [id=invoke, version=11.0.0],
[id=network, version=0.0.1], [id=oast, version=0.6.0],
[id=onlineMenu, version=9.0.0], [id=openapi,
version=24.0.0], [id=pscanrules, version=37.0.0],
[id=quickstart, version=32.0.0], [id=replacer,
version=9.0.0], [id=reports, version=0.10.0], [id=retest,
version=0.2.0], [id=retire, version=0.9.0], [id=reveal,
version=4.0.0], [id=saverawmessage, version=6.0.0],
[id=savexmlmessage, version=0.2.0], [id=scripts,
version=29.0.0], [id=selenium, version=15.5.1], [id=soap,
version=12.0.0], [id=spiderAjax, version=23.7.0], [id=tips,
version=9.0.0], [id=webdrivermacos, version=33.0.0],
[id=websocket, version=24.0.0], [id=zest, version=35.0.0]]

### Would you like to help fix this issue?

- [X] Yes

**Comment by tkisason** [comment]
After some further testing and digging in the code, i found out that it will just dump data to the old file name which you selected the first time. This is also ok, but it's unclear from the interface that it will use the first selected file name for next saves.

**Comment by kingthorin** [comment]
Doesn’t subsequent use of save in most modern applications (like in the last 30 years) re-use the existing file?

**Comment by tkisason** [comment]
Yeah, i got confused when i removed the file and still couldn't create a new job with a new filename. Not a bug, but if you are creating multiple automations, you need to either remove all elements or exit zap, since you can't change the filename. So, not a bug, but maybe a Save and Save As option could be better.  🤷 I can close this as resolved, or we can leave it as an idea to add a Save As option, maybe as someone's first commit.

**Comment by psiinon** [comment]
I think a "Save As..." option would be very useful - if anyone fancies having a look at this we can give any guidance needed.

**Comment by Siddharth3330** [comment]
I would like to work over it, can I get some pointers to start.

**Comment by psiinon** [comment]
Hiya @Siddharth3330 thanks for offering to help - I've assigned this to you :)

It should just be a UI change, so hopefully relatively straight forward.

I'd suggest adding a new button next to the "Save" one, same icon but with a plus or pen overlay (we can help with that).
The Save button is added here: https://github.com/zaproxy/zap-extensions/blob/main/addOns/automation/src/main/java/org/zaproxy/addon/automation/gui/AutomationPanel.java#L176

Have a look at that class and then ask any questions you have here 😁

**Comment by Siddharth3330** [comment]
Hi @psiinon, in getSavePlanButton() method initially the button is not enabled I was unable to understand where exactly that button was getting enabled later on in that method. I made a similar method for making a save-as button, in that method if I put saveAsPlanButton.setEnabled(true); then button is working fine and saving the plan but if I put saveAsPlanButton.setEnabled(false); and make changes in plan still this new button is not getting enabled. Please guide :)

**Comment by thc202** [comment]
The save button enabled state is changed in `setCurrentPlan` and `updateSaveButton`, you'll have to change the save as in there as well.

**Comment by Siddharth3330** [comment]
Thanks @thc202, I understand and its working now :)

**Comment by tkisason** [comment]
Thank you!
