### ISSUE TITLE
Unable to generate testreport

### ISSUE THREAD

**Issue by janibashamd** [zaproxy/zaproxy#7179]
### Describe the bug

Hi Team,

I am trying to use docker image with baseline scan which is scanning fine.

But when i tried to create report using below command i don't see any testreport or conf file

_docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-baseline.py -t https://jb1.f5-hyd-demo.com/ -g gen.conf -r testreport.html_

Last few line outputs:
28187 [ZAP-PassiveScanner] INFO  org.zaproxy.zap.extension.pscan.PassiveScanThread - Disabling passive scanner Anti-clickjacking Header as it has raised more than 10 alerts.
28201 [ZAP-PassiveScanner] INFO  org.zaproxy.zap.extension.pscan.PassiveScanThread - Disabling passive scanner Content Security Policy (CSP) Header Not Set as it has raised mo  re than 10 alerts.
30067 [ZAP-SpiderThreadPool-0-thread-2] INFO  org.zaproxy.zap.spider.Spider - Spidering process is complete. Shutting down...
30069 [ZAP-SpiderShutdownThread-0] INFO  org.zaproxy.zap.extension.spider.SpiderThread - Spider scanning complete: true on https://jb1.f5-hyd-demo.com/ at 2022-03-30T07:20:48.  403+0000

### Steps to reproduce the behavior

Try to execute below command:
docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-baseline.py -t https://jb1.f5-hyd-demo.com/ -g gen.conf -r testreport.html

### Expected behavior

Ideally report and conf file should be created

### Software versions

OS:
[root@gitlab-runner zap]# cat /etc/os-release
NAME="CentOS Stream"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Stream 8"

Docker version:
[root@gitlab-runner zap]# docker version
Client: Docker Engine - Community
 Version:           20.10.12
 API version:       1.41

### Would you like to help fix this issue?

- [ ] Yes

**Comment by kingthorin** [comment]
You need to specify the full path for the report otherwise you’re writing it inside the container and not preserving it. Ex: `/zap/wrk/testteport.html`

Please don't ask questions as issues - the [ZAP User Group]( https://groups.google.com/group/zaproxy-users) is a much better place for questions.

**Comment by janibashamd** [comment]
i thought its a issue so raised it here..

**Comment by janibashamd** [comment]
Tried below command as well but no luck:
docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-baseline.py -t https://jb1.f5-hyd-demo.com/ -g /zap/wrk/gen.conf -r /zap/wrk/testreport.html


Even documentation didn't say anything about this issue, so please give valid and full command..

**Comment by psiinon** [comment]
The docs do actually give an example: https://www.zaproxy.org/docs/docker/baseline-scan/

```
docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-baseline.py \
    -t https://www.example.com -g gen.conf -r testreport.html
```

I've just tried that and it does write `testreport.html` to the cwd...

**Comment by janibashamd** [comment]
for some reason i tried same command but it didn't work out and i don't see any config or reports in cwd:

[root@gitlab-runner zap]# ls
[root@gitlab-runner zap]#

**Comment by psiinon** [comment]
This is likely to be an environment issue, ie related to gitlab.
Its not going to be a ZAP issue, so for more help please ask on the [ZAP User Group](https://groups.google.com/group/zaproxy-users)

**Comment by psiinon** [comment]
FYI I've submitted a PR to add to the Docker diagnostics page: https://github.com/zaproxy/zaproxy-website/pull/895/files
