### ISSUE TITLE
ZAP Hud not displaying

### ISSUE THREAD

**Issue by techbud** [zaproxy/zaproxy#7184]
I'm new to the tool so might be a mistake on my end. But was learning how to use it and the HUD looks pretty cool but for some reason the HUD isn't working. I'm on Firefox 91.7.0esr. Zap 2.11.1. Tried refreshing a million times, I know one of the guys in discord is on and older version and it works?

**Comment by kingthorin** [comment]
Are you launching Firefox from within ZAP?
Have you visited a site? (It won't show on about:blank or ZAPs news page.)

**Comment by techbud** [comment]
I'm launching from ZAP, but I'm visiting the site within hack the box academy, tried different sites and it doesn't load up.

**Comment by kingthorin** [comment]
On Kali?

**Comment by techbud** [comment]
Yes kali on current version. I'm trying to delete all and reinstall at the moment then reupdate the app.

**Comment by kingthorin** [comment]
I've got a VM around, I'll update and give it a shot.

**Comment by techbud** [comment]
No go after a new installation

**Comment by techbud** [comment]
Alright I got it working by the grace of god and a little luck. I was having trouble setting up re placers in the menus also, hit hit reset button in the options menu, generated a new ssl cert and the hud is up.

**Comment by kingthorin** [comment]
Oh great. Thanks for letting us know.
