### ISSUE TITLE
unable to get DOM results

### ISSUE THREAD

**Issue by alexhyd22** [zaproxy/zaproxy#7185]
while i scanned my website dom based  scan is skipping everytime i scan. but all the other type of scans are working fine. DOM based scan is being cancelled everytime with out my notice.

**Comment by thc202** [comment]
You can check why it's being skipped by hovering its icon in the [Scan Progress dialogue](https://www.zaproxy.org/docs/desktop/ui/dialogs/scanprogress/), that's also [logged](https://www.zaproxy.org/faq/where-does-zap-put-its-logs/).
The scan rule is skipped if not able to start the browser, verify that you are using the latest WebDriver add-ons and that the browser is installed.

These type of usage questions are better for the [OWASP ZAP User Group](https://groups.google.com/group/zaproxy-users).
