### ISSUE TITLE
ModuleNotFoundError: No module named 'zap_common'

### ISSUE THREAD

**Issue by 589290** [zaproxy/zaproxy#7188]
### Describe the bug

zap_common.py does not seem to be included as part of the Linux binary package, but it should be... right?
https://github.com/zaproxy/zaproxy/releases/download/v2.11.1/ZAP_2.11.1_Linux.tar.gz

### Steps to reproduce the behavior

1. download https://github.com/zaproxy/zaproxy/releases/download/v2.11.1/ZAP_2.11.1_Linux.tar.gz
2. try to run a scan
3. zap_common.py is missing... 
4. error!

### Expected behavior

zap_common.py is included causing no error

### Software versions

2.11.1

### Would you like to help fix this issue?

- [X] Yes

**Comment by thc202** [comment]
Those are included in the Docker images: https://www.zaproxy.org/docs/docker/

**Comment by 589290** [comment]
@thc202 right, but if you're building you own custom docker image and pulling down the Linux tar release, you will have to pull down the zap_common.py separately/independently. It would be nice if this python library was included in the Linux release so that it would be tracked/released in tandem with the Linux package.

**Comment by psiinon** [comment]
The future direction is actually to use the Automation Framework: https://www.zaproxy.org/docs/automate/automation-framework/
We have started to move the packaged scans over to use the AF under the covers - this does not depend on docker but can run in docker or any other container if required.
As such I do not anticipate us wanting to spend more time on zap_common than we need to...

**Comment by psiinon** [comment]
We are a relatively small team and so have to prioritise what we support.
Right now zap_common is "internal" and not one of the external interfaces we "officially" document or support.
If you can explain your usecase then maybe we can get a better understanding of your requirements.

**Comment by 589290** [comment]
@psiinon our usecase is to offer a hardened container: https://repo1.dso.mil/dsop/opensource/owasp-zap/owasp-zap/-/tree/development

**Comment by psiinon** [comment]
OK, that sounds like a reasonable option.
Do you know how it will differ from ours?
We'd be happy to accept PRs which harden our images as long as they do not impact existing users.
At this stage I cant see any of us working on packaging those scripts I'm afraid :/

**Comment by 589290** [comment]
The hardening process for us, so far with zaproxy, has been to been to build the image entirely offline and air gapped. This is a core requirement for all container images that reside on IronBank. Hence the need for a new Dockerfile and accompanying hardening manifest in the repo1 repository. 

Unfortunately, I don't believe there is anything from our image build customizations that would be of any benefit to bring into zaproxy mainline. Otherwise, I would gladly contribute a PR. 

Circling back to the original reason this request was opened, zap_common.py being unpackaged at this point, made our build process slightly more complicated -- but not impossible. However, I think that issue has already been addressed here.

I've also documented the future build automation, mentioned in this ticket, that zaproxy has planned. That way, we can continue to refine how our secure image is built when those changes go public in future releases of zaproxy.

You may consider this issue resolved, thank you.
