### ISSUE TITLE
ZAP getting stuck during active scan in daemon mode 

### ISSUE THREAD

**Issue by RajatGupta16197** [zaproxy/zaproxy#7225]
### Describe the bug

ZAP  when running in daemon mode is getting stuck while running active scan for 15+hrs, but when running in non-daemon mode then ZAP is getting completed within an hour. 
The target and scan policy being same while initiating the scan in daemon and non-daemon mode.

### Steps to reproduce the behavior

1. Start ZAP with daemon mode
2. Spider scan 
3. Ajax Spider 
4. Active scan 

### Expected behavior

ZAP should complete the scan regardless of the daemon setting.

### Software versions

2.11.1

### Errors from the zap.log file

This was getting printed many times.
2022-04-20 07:26:54,495 [HSQLDB Timer @295eaa7c] INFO  ENGINE - Checkpoint start
2022-04-20 07:26:54,495 [HSQLDB Timer @295eaa7c] INFO  ENGINE - checkpointClose start
2022-04-20 07:26:54,504 [HSQLDB Timer @295eaa7c] INFO  ENGINE - checkpointClose synched
2022-04-20 07:26:54,510 [HSQLDB Timer @295eaa7c] INFO  ENGINE - checkpointClose script done
2022-04-20 07:26:54,510 [HSQLDB Timer @295eaa7c] INFO  ENGINE - dataFileCache commit start
2022-04-20 07:26:54,568 [HSQLDB Timer @295eaa7c] INFO  ENGINE - dataFileCache commit end
2022-04-20 07:26:54,592 [HSQLDB Timer @295eaa7c] INFO  ENGINE - checkpointClose end
2022-04-20 07:26:54,593 [HSQLDB Timer @295eaa7c] INFO  ENGINE - Checkpoint end - txts: 252483

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment]
Could you attach the whole log?

**Comment by RajatGupta16197** [comment]
[zap.log](https://github.com/zaproxy/zaproxy/files/8528776/zap.log)

**Comment by RajatGupta16197** [comment]
It was stuck, so we have terminated the ZAP session from the API.

**Comment by thc202** [comment]
The provided log does not show ZAP running for the mentioned hours.

**Comment by psiinon** [comment]
@RajatGupta16197 why do you think the active scan was still running?
In daemon mode ZAP will keep running until you stop it.

**Comment by RajatGupta16197** [comment]
Active scan because when I checked the status from ZAP from API, the overall status can be seen and the scan progress can be seen in ascan. 

As soon as the active scan is getting completed we are stopping the daemon, but in this case active scan is getting stuck.

**Comment by thc202** [comment]
So far there's no evidence that the scan is stuck.

**Comment by thc202** [comment]
Could you provide the log when running with GUI?

**Comment by RajatGupta16197** [comment]
[zap.log](https://github.com/zaproxy/zaproxy/files/8530109/zap.log)
Since the scan was running for almost 24hrs+, so we had to kill the scan. I have attached the logs for the scan.

**Comment by psiinon** [comment]
If you are already using the API then call the endpoint to check the scan progress and let us know what it returns: https://www.zaproxy.org/docs/api/#ascanviewscanprogress

**Comment by RajatGupta16197** [comment]
[zap.log](https://github.com/zaproxy/zaproxy/files/8537189/zap.log)
[zap_response.txt](https://github.com/zaproxy/zaproxy/files/8537195/zap_response.txt)
I had initiated a scan yesterday and its still running, I have attached logs and the response from the  scan progress end point

**Comment by kingthorin** [comment]
It seems to still be running. The log shows some scan rules are sending 10s of 1000s of requests so the site is obviously huge or not well explored/modeled.

Ex: ` PathTraversalScanRule in 30864.073s with 43602 message(s) sent and 1 alert(s) raised.` is almost 8hrs on it's own.

**Comment by k3v3n** [comment]
I'm experiencing similar issue with ZAP on long scan (+4hours). We curl the the localhost:8080/ui for our healthcheck and it does not respond over a long period of time. Using zap2docker-weekly image. Also tried the `docker run -u zap -p 8080:8080 -p 8090:8090 -i owasp/zap2docker-weekly zap-webswing.sh` on https://public-firing-range.appspot.com/ and I have the same behaviour. The API is not responding and there are plenty of `usr/bin/python3 /usr/local/bin/zap-cli status ` of processes running. Could it be related to some WebSocket pscan rules with Firefox and the new network addon ?

**Comment by thc202** [comment]
That's a different issue, could you provide a thread dump when that happens?

**Comment by kingthorin** [comment]
8080 != 8090

**Comment by thc202** [comment]
The `zap-cli` processes are because of https://www.zaproxy.org/docs/docker/about/#healthcheck which are probably hitting the wrong port (8080 instead of 8090).

**Comment by k3v3n** [comment]
> That's a different issue, could you provide a thread dump when that happens?

[zap-2022-04-22-thread-dump.txt](https://github.com/zaproxy/zaproxy/files/8543213/zap-2022-04-22-thread-dump.txt)

**Comment by thc202** [comment]
Thank you, could you provide another one (if still running)? What is being done prior to that state?

**Comment by k3v3n** [comment]
> Thank you, could you provide another one (if still running)? What is being done prior to that state?

Thanks for the reply. Still testing on firing range but it's not always the case. Also, we automate the process so the killed and restart at the end of the scan.

**Comment by thc202** [comment]
How are you telling when the scan is done? I don't see anything wrong in that thread dump, maybe with `ZAP-IO-EventExecutor-3-1` but without knowing what's being done and if it's actually hanging there (it should timeout the connect). I assume that you are using the default connection settings?

Do you have the zap.log?

**Comment by RajatGupta16197** [comment]
> It seems to still be running. The log shows some scan rules are sending 10s of 1000s of requests so the site is obviously huge or not well explored/modeled.
> 
> Ex: ` PathTraversalScanRule in 30864.073s with 43602 message(s) sent and 1 alert(s) raised.` is almost 8hrs on it's own.

But when I am running it on the same target in non daemon mode then it is getting completed within an hour

**Comment by thc202** [comment]
Most likely you are not using the same settings. You can use a lower attack strength to reduce the number of requests sent but better try make the target more responsive under load. There are also other options to reduce the time the scan or the scan rules are allowed to run: https://www.zaproxy.org/docs/desktop/ui/dialogs/options/ascan/

**Comment by RajatGupta16197** [comment]
I tried with low strength as well but the result was same. Does anything change internally while running zap in daemon and non daemon mode. I am sharing the logs for the non daemon mode, where the scan got completed successfully with the same policy but it is failing continuously in the daemon mode.
[zap.log](https://github.com/zaproxy/zaproxy/files/8590271/zap.log)
 
![image](https://user-images.githubusercontent.com/52082380/165933024-adbdd5c6-fedd-4985-9989-b7ce86240250.png)

**Comment by kingthorin** [comment]
> Does anything change internally while running zap in daemon and non daemon mode.

No.

**Comment by RajatGupta16197** [comment]
Any updates ?

**Comment by kingthorin** [comment]
Only what’s above👆

**Comment by thc202** [comment]
@RajatGupta16197 did you ensure that the same settings are in use in both cases?

**Comment by RajatGupta16197** [comment]
Yes, we used the same settings in both the cases

**Comment by RajatGupta16197** [comment]
Can we limit the number of request send per scan rule through ZAP on the target ?

**Comment by thc202** [comment]
As mentioned in https://github.com/zaproxy/zaproxy/issues/7225#issuecomment-1113156927 you can use a lower attack strength to reduce the number of requests sent.

**Comment by kingthorin** [comment]
But really you should figure out what the delta is in daemon mode. Either your target is taking a performance hit or you don't have something setup the same.

**Comment by RajatGupta16197** [comment]
> As mentioned in [#7225 (comment)](https://github.com/zaproxy/zaproxy/issues/7225#issuecomment-1113156927) you can use a lower attack strength to reduce the number of requests sent.

This we have already tried but the result was same

**Comment by RajatGupta16197** [comment]
> But really you should figure out what the delta is in daemon mode. Either your target is taking a performance hit or you don't have something setup the same.

Everything remains the same, only thing we changed was daemon to non-daemon mode rest all was same but we found the duration and scan request different for both of them

**Comment by thc202** [comment]
Are you using the API in both cases?

**Comment by RajatGupta16197** [comment]
> Are you using the API in both cases?

Yes

**Comment by kingthorin** [comment]
No further input/details in 5mo.
