### ISSUE TITLE
Scan Rule with empty name in the Scan Progress window and Scan Policy window

### ISSUE THREAD

**Issue by globeone** [zaproxy/zaproxy#7228]
### Describe the bug

When viewing the Scan Progress window there is a mystery attack (blank title) between CORS Header and Spring Actuator Information Leak.
Also under Miscellaneous in the Scan Policy window 

### Steps to reproduce the behavior

- Start an Active Scan
- Click on the Progress icon 
-- ![image](https://user-images.githubusercontent.com/10052587/164455219-88058065-f8a2-4b80-a347-1931defc7f7e.png)
- scroll to the bottom of the window listing the attacks
- observe an attack missing a title between CORS Header and Spring Actuator Information Leak

OR 

- Open Analyse menu option
- Scan policy manager...
- Default Policy
- Miscellaneous
- Observe that the first attack is missing a title.

### Expected behavior

Expect for all attacks to have a title so one knows what attack vector is used. Also for debugging if something goes wrong with this specific attack.

### Software versions
```
OWASP ZAP
Version: D-2022-04-19

Installed Add-ons: [[id=accessControl, version=8.0.0],
[id=alertFilters, version=14.0.0], [id=amf, version=3.0.0],
[id=ascanrules, version=47.0.0], [id=ascanrulesAlpha,
version=38.0.0], [id=ascanrulesBeta, version=41.0.0],
[id=attacksurfacedetector, version=1.1.4], [id=authstats,
version=2.0.0], [id=automation, version=0.15.0],
[id=browserView, version=5.0.0], [id=bruteforce,
version=12.0.0], [id=callgraph, version=5.0.0],
[id=callhome, version=0.4.0], [id=commonlib,
version=1.10.0], [id=coreLang, version=16.0.0],
[id=custompayloads, version=0.11.0], [id=diff,
version=12.0.0], [id=directorylistv1, version=6.0.0],
[id=directorylistv2_3, version=4.0.0],
[id=directorylistv2_3_lc, version=4.0.0], [id=domxss,
version=13.0.0], [id=encoder, version=0.7.0], [id=exim,
version=0.2.0], [id=fileupload, version=1.1.0],
[id=formhandler, version=5.0.0], [id=fuzz, version=13.7.0],
[id=fuzzdb, version=8.0.0], [id=gettingStarted,
version=14.0.0], [id=graaljs, version=0.3.0], [id=graphql,
version=0.10.0], [id=help, version=15.0.0], [id=hud,
version=0.14.0], [id=imagelocationscanner, version=3.0.0],
[id=importurls, version=9.0.0], [id=invoke, version=12.0.0],
[id=jsonview, version=2.0.0], [id=jwt, version=1.0.2],
[id=network, version=0.3.0], [id=oast, version=0.11.0],
[id=onlineMenu, version=10.0.0], [id=openapi,
version=28.0.0], [id=plugnhack, version=13.0.0],
[id=portscan, version=10.0.0], [id=pscanrules,
version=41.0.0], [id=pscanrulesAlpha, version=35.0.0],
[id=pscanrulesBeta, version=30.0.0], [id=quickstart,
version=34.0.0], [id=reflect, version=0.0.11],
[id=regextester, version=2.0.0], [id=replacer,
version=10.0.0], [id=reports, version=0.14.0],
[id=requester, version=5.0.0], [id=retest, version=0.3.0],
[id=retire, version=0.11.0], [id=reveal, version=5.0.0],
[id=revisit, version=4.0.0], [id=saml, version=9.0.0],
[id=scripts, version=31.0.0], [id=selenium, version=15.9.0],
[id=sequence, version=7.0.0], [id=soap, version=14.0.0],
[id=spiderAjax, version=23.8.0], [id=sqliplugin,
version=15.0.0], [id=tips, version=10.0.0], [id=tokengen,
version=15.0.0], [id=treetools, version=8.0.0],
[id=viewstate, version=3.0.0], [id=wappalyzer,
version=21.9.0], [id=webdriverlinux, version=38.0.0],
[id=webdrivermacos, version=39.0.0], [id=webdriverwindows,
version=38.0.0], [id=websocket, version=26.0.0], [id=zest,
version=36.0.0]]

Operating System: Windows 10
Java Version: Eclipse Adoptium 17.0.2
System's Locale: en_US
Display Locale: en_GB
Format Locale: en_US
ZAP Home Directory: C:\Users\$USER\OWASP ZAP_D\
ZAP Installation Directory: C:\Users\$USER\LocalPrograms\ZAPWeekly\ZAP_D-2022-04-19\.\
Look and Feel: FlatLaf Light (com.formdev.flatlaf.FlatLightLaf)
```

### Screenshots

![image](https://user-images.githubusercontent.com/10052587/164451919-ff1cacdc-7005-44ce-9b94-a4e436363267.png)

and

![image](https://user-images.githubusercontent.com/10052587/164456157-84e79186-826e-407b-9061-7b6858378d17.png)

### Errors from the zap.log file

none as it's a GUI visual error (missing title)

### Additional context

Checked the Marketplace and all items have titles. 

### Would you like to help fix this issue?

- [X] Yes

**Comment by kingthorin** [comment]
Could you run this standalone script and share the output?
https://github.com/zaproxy/community-scripts/blob/main/standalone/Active%20scan%20rule%20list.js

**Comment by globeone** [comment]
sure, can I run it directly in ZAP by adding it to the Scripts tab?

**Comment by thc202** [comment]
Based on that it's the FileUpload scan rule that's missing all the info.

**Comment by kingthorin** [comment]
Thanks @globeone @thc202 I'll open an issue in the appropriate repo.

**Comment by globeone** [comment]
Could it have to do maybe with this description with these special characters? It stands out to me.

![image](https://user-images.githubusercontent.com/10052587/164472628-ffb62a50-1a48-415b-82a3-73940dcfaf2f.png)

**Comment by globeone** [comment]
Found it! This one is blank Plugin ID 40041

![image](https://user-images.githubusercontent.com/10052587/164473741-18c36417-2d76-4494-aa70-e90296f749ac.png)

**Comment by thc202** [comment]
Reopening, we should change core to at least log a warning (and ideally fallback to the classname instead of leaving the name empty).

**Comment by kingthorin** [comment]
```js
// This script gives details about all of the active scan rules installed

extAscan = org.parosproxy.paros.control.Control.getSingleton().
    getExtensionLoader().getExtension(
        org.zaproxy.zap.extension.ascan.ExtensionActiveScan.NAME);

plugins = extAscan.getPolicyManager().getDefaultScanPolicy().getPluginFactory().getAllPlugin().toArray();

print('\n');

for (var i=0; i < plugins.length; i++) {
  if (plugins[i].getId() == 40041) {
    try {
      print ('Plugin ID: ' + plugins[i].getId());
      print ('Name: ' + plugins[i].getName());
      print ('Desc: ' + plugins[i].getDescription());
      print ('Risk: ' + plugins[i].getRisk());
      print ('Soln: ' + plugins[i].getSolution());
      print ('Ref:  ' + plugins[i].getReference());
      print ('CWE:  ' + plugins[i].getCweId());
      print ('WASC:  ' + plugins[i].getWascId());
      print ('');
    } catch (e) {
      print (e);
    }
  }
}
```

**Comment by globeone** [comment]
@kingthorin 
Here is the sanitized log file
[zap copy.log](https://github.com/zaproxy/zaproxy/files/9241888/zap.copy.log)

**Comment by globeone** [comment]
and here is the results from the Active Scan Rules script
[active_scan_rules.txt](https://github.com/zaproxy/zaproxy/files/9241951/active_scan_rules.txt)

Still showing the same plugin without a label
```
Plugin ID: 40041
Name: 
Desc: 
Risk: 2
Soln: 
Ref:  
CWE:  0
WASC:  0
```

**Comment by thc202** [comment]
As mentioned in the other issue the corresponding add-on was not yet released with the fix.

**Comment by globeone** [comment]
@thc202  oh, I thought I read that the fix was already implemented that would show the class of the plugin when no label was available. Was that not successful, or feasible ?

**Comment by thc202** [comment]
There are two issues, one in ZAP itself which should show something always (this was not yet done) and the other in the add-on to properly load the scan rule name (fixed but not yet released).

**Comment by globeone** [comment]
@thc202 Okay sounds good. Patience is a virtue and it's only cosmetic. :-) thanks for taking a few moments to revisit this issue today, I appreciate it.
