### ISSUE TITLE
False positive *** EXPERIMENTAL *** This website uses ASP.NET’s Viewstate but maybe without any MAC.

### ISSUE THREAD

**Issue by vahidaftahi** [zaproxy/zaproxy#7230]
MAC is set for all pages on this website that were alerted and despite the high alert is produced.
The .NET version in use is the 4.2.
Please check back as As investigating that ZAP may produces a false Positive for this flagged “Experimental (Unsure)” alert.

**Comment by kingthorin** [comment]
Please provide all the details of the alert.

**Comment by vahidaftahi** [comment]
correction: The .NET version in use is the 4.5.2.

**Comment by kingthorin** [comment]
Still need the full details.

**Comment by kingthorin** [comment]
It would still be really nice to have to details.

However, we could add a condition to: https://github.com/zaproxy/zap-extensions/blob/f3b38c7bec369b15fb4e99b229046881b7430797/addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ViewstateScanRule.java#L68 so that it's only raised if [threshold](https://www.zaproxy.org/docs/desktop/ui/dialogs/scanpolicy/#threshold) is low.

**Comment by vahidaftahi** [comment]
Hi Rick,

Thanks for your feedback – sorry for delay.
Per ZAP alert that is set to HIGH – “*** EXPERIMENTAL *** This website uses ASP.NET’s Viewstate but maybe without any MAC. (Issue #7230)”
The alert is coming up despite of MAC to be used.
Particularly puzzled with ““*** EXPERIMENTAL ***” as it may be a test and our products are struggling to fix this issue and have not been successful.

Unsure what “v.hasMACtest1” and “v.hasMACtest2”  do in :
if (!v.hasMACtest1() || !v.hasMACtest2()) if (!v.hasMACtest1() && !v.hasMACtest2()) alertNoMACforSure(msg, id); else alertNoMACUnsure(msg, id);

and if you can help us modify the code to lower the alert to Medium or Low.
Nessus produces a “Medium” on this issue per on-line investigation.

Looking forward to your feedback Thanks for your help

With Regards,
Vahid Aftahi
Mitel Product Security

**Comment by kingthorin** [comment]
"*** EXPERIMENTAL ***" is just part of the alert name, meant to indicate that part of the scan rule code (which raised this alert) is well experimental :grinning:

If you're team is positive that MAC is enabled for the viewstate in question then I would say don't worry about it too much.

I will be updating the scan rule to add Threshold handling for that particular alert/condition.
