### ISSUE TITLE
Add Authorization header in Active Scan

### ISSUE THREAD

**Issue by Syntax3r** [zaproxy/zaproxy#7232]
Hey All,
I'm trying to add the Authorization header while zap is doing the active Scan. In my case Authentication is done by JSON , I have done the following step to authenticate into the application.

*Note : I have selected the zest script because in my scenario some headers are required in the request. i.e (Origin, Content-Type, Authorizaton : Bearer undefined).*
1. Record a Zest Script while login and save it for authentication purpose. i.e AuthenticationScript.zst
2. In the Authentication tab I have selected the Authentication method as follow : 
- script Based Authentication
- load Zest Script(AuthenticatinScript) previously saved.
3. Finally I have successfully login in to application using this method.

**But for the active scan purpose, I need the Authorization token in my every request**
(Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsImlhdCI6MTY1MDYyNzAwMSwiZXhwIjoxNjUwNjMwNjAxfQ.w7A3oNeldNdoKOOOFaghdELOfsDMnCXsJ5NqtmtZE08  ).

how do I achieve this?

**Comment by kingthorin** [comment]
Please don't ask questions as issues - the [ZAP User Group]( https://groups.google.com/group/zaproxy-users) is a much better place for questions.

https://www.zaproxy.org/docs/desktop/addons/replacer/
