### ISSUE TITLE
Docker based API scan not to report HTTP 400 to HTTP 404?

### ISSUE THREAD

**Issue by karsten-wagner** [zaproxy/zaproxy#7234]
### Is your feature request related to a problem? Please describe.

The docker container based API scan contains additional scripts that aim to alert on certain problematic conditions specific to APIs.
One of the scripts will add an "informational" log entry to the report for any HTTP response code between 400 and 599 (all client and all sever error codes). This typically leads to many of those informational notes, which renders the report very long on the one hand side and the report is not so suited to hand it over to a third party saying "all good".

See here:
https://github.com/zaproxy/zaproxy/blob/d206743afce14ff2b0d702d82e7f6ff38e4b4525/docker/scripts/scripts/httpsender/Alert_on_HTTP_Response_Code_Errors.js#L24

### Describe the solution you'd like

I'd like to question the community here if this is really a desirable approach in the current way implemented. A zap scan by intention hands over a lot of somewhat "random" input to the API and tries to access areas on the server that actually should be protected.

My proposal is to change the script referenced above in a way it will ignore HTTP 400 to HTTP 404 and only report errors >HTTP 404. Eventually it would make sense to split the script into 2 parts and somehow allowing the user to select if all error codes are reported or only those >HTTP404.

400)
A desirable response for any input not in line with the API specification. Zap creates a lot of long text inputs, partially aiming to access server side places that should be protected. Using HTTP 400 (or HTTP 403) seems also like a common reaction of an API that is protected by a Web Application Firewall (WAF). So this is some sort of "graceful" feedback of the API to tell the user something went wrong and not a security vulnerability in the first place.

401 / 403)
This means "no authentication provided" or "access to requested resource not granted with given authorization". To my understanding zap will handle this by either repeating the request with a maintained authorization, or the actual response is acceptable as zap did not manage to access a server area it should not access.
At some point of scanning it might be useful to report this to the user who runs the scan to indicate missing authentication/authorization, but for recurring scans the access credentials should be present and so this type of response is acceptable.

404)
Finally if a requested resource is simply not present, this is an acceptable result. Since zap scans many different inputs, it has to be expected that many of them will not be present on the server and a simple HTTP 404 is then actually a "good" response in terms of vulnerabilities.

Note on other codes)
HTTP 405 as "method not allowed" is something I did not experience when using zap, so it keeps scanning only what is documented. It would be something a manual penetration test might check. Since the documented cases should work, a HTTP 405 response would indeed show an unexpected behavior.
HTTP 429 is used to indicate "too many requests" in a given time period. This is an indication the test results are not complete, since the call was blocked on some sort of API gateway. For the scanning user this is a needed indication to increase allowed limits or reduce the frequency between the single calls.
HTTP 500 is actually a good idea to report. Input should be sanitized and gracefully rejected on server side and not lead to exceptions. Other HTTP error codes like 502/503 should also be indicated to the scanning user highlighting again the scan might be incomplete...

### Describe alternatives you've considered

Users can overwrite the script and mount a custom version into the docker container.

Loading a custom rule set did not seem to have any effect, since the API specific scan rules are loaded unconditionally *after* the custom rule sets have been evaluated:
https://github.com/zaproxy/zaproxy/blob/d206743afce14ff2b0d702d82e7f6ff38e4b4525/docker/zap-api-scan.py#L399-L403

### Additional context

I am aware this might be a discussion around personal preference. Please share your thoughts...

### Would you like to help fix this issue?

- [ ] Yes

**Comment by kingthorin** [comment]
You can use alert filters, different execution methods, etc to make this work as you see fit.

Since this is the only request in years for the script and package scans existing I don’t see us changing it.
