### ISSUE TITLE
Spider to use multipart forms

### ISSUE THREAD

**Issue by jhowlett96** [zaproxy/zaproxy#7251]
### Is your feature request related to a problem? Please describe.

Currently the spider uses standard forms for multipart forms. The reasoning is that no files are uploaded and so no need, found here: [SpiderHtmlFormParser.java#L181-L182](https://github.com/zaproxy/zaproxy/blob/03f922c739708bb8c2f1278e85f074180c4f17de/zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlFormParser.java#L181-L182)

However think of the case below. 

A page with a multipart form submission with 2 inputs one file and other plain text input. 

The page POSTed to first tests if not multipart if not then throw error (this is where the current request from the spider would get to in the page). Next splits the multipart form into its different inputs. 

The page then uses the second input and writes to the database without suitable protection from SQL injection, for example the user key of the user that has attempted to upload an image and an increment on total number of attempts by user.

Then finally the page tests the first form input which was the image (which ZAP still wouldn't include but that is fine for this example because the main thing is to detect the SQL injection).

ZAP would then state that the page is not SQL injectable however it is. 

### Describe the solution you'd like

The spider to correctly construct multipart forms 

### Describe alternatives you've considered

I cannot think of any other solutions than properly constructing the multipart form.

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment]
Closing as duplicate of #7197.
