### ISSUE TITLE
Current release for Python API is out of date

### ISSUE THREAD

**Issue by sarahgibs** [zaproxy/zaproxy#7254]
### Describe the bug

The Python API wrapper has been updated over the past two years, but the last release was made on Dec 18, 2020. The version on pip does not contain all of the current functionality including the reports endpoints. 

### Steps to reproduce the behavior

Follow the instructions to install the wrapper with pip, try and use the reports section of the API, encounter an error such as "AttributeError: 'ZAPv2' object has no attribute 'reports'". 

### Expected behavior

I would expect the wrapper installed from pip to have the functionality presented in the source code. 

### Software versions

It's listed as v2.4 in the pip install.

### Additional context

This would be very useful to have, if it's possible to do another release. 
Thank you!

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment]
Latest release is 0.0.20 https://pypi.python.org/pypi/python-owasp-zap-v2.4
Python 2.7 is no longer supported.

**Comment by sarahgibs** [comment]
thank you, and sorry. I was sure I had run --upgrade while trying to get this to work. I had not.
