### ISSUE TITLE
Alert Id 10055 - script-src unsafe-inline but in fact style-src is unsafe-inline

### ISSUE THREAD

**Issue by derhecht** [zaproxy/zaproxy#7263]
I'm using ZAP Docker proxy to check an API and check results within Sonar.

Got results like:
CSP Scanner: script-src unsafe-inline
Vulnerability Minor
Tags cweid-16, owasp-a6, wascid-15, zaproxy
Available SinceJan 08, 2021
Solution :
Ensure that your web server, application server, load balancer, etc. is properly configured to set the Content-Security-Policy header.
References:
    https://www.w3.org/TR/CSP2/
    https://caniuse.com/#search=content+security+policy
    https://content-security-policy.com/
    https://github.com/shapesecurity/salvation
    https://cwe.mitre.org/data/definitions/16.html
    https://www.zaproxy.org/docs/alerts/10055/

In fact my CSP header is: content-security-policy: default-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline';

Looks like the check which results in this finding does not check if style or script-src is defined in CSP header.

**Comment by kingthorin** [comment]
Thanks for reporting this, I'll do some testing and look into it.

**Comment by kingthorin** [comment]
I'm unable to recreate. Please provide the full headers from the associated HTTP message.

**Comment by kingthorin** [comment]
Tested with:
```java
    @Test
    void shouldRaiseAlertWhenCspIncludesScriptUnsafeInline2() {
        // Given
        HttpMessage msg = createHttpMessage("default-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline';");
        // When
        scanHttpResponseReceive(msg);
        // Then
        assertThat(alertsRaised.size(), equalTo(2));
        // Verify the specific alerts
        assertThat(alertsRaised.get(1).getName(), equalTo("CSP: style-src unsafe-inline"));
        assertThat(alertsRaised.get(1).getRisk(), equalTo(Alert.RISK_MEDIUM));
        assertThat(alertsRaised.get(1).getConfidence(), equalTo(Alert.CONFIDENCE_MEDIUM));
        assertThat(alertsRaised.get(1).getAlertRef(), equalTo("10055-6"));

        assertThat(alertsRaised.get(0).getName(), equalTo("CSP: Wildcard Directive"));
    }
```

**Comment by derhecht** [comment]
I will close this as it looks like this is an issue with the Sonar plugin. Just tested with another service. Same problems here. Sonar not equals log from ZAP execution. Sry.

**Comment by kingthorin** [comment]
No problem, thanks for confirming.
