### ISSUE TITLE
Spider: href="#" generating URLs in site tree

### ISSUE THREAD

**Issue by jhowlett96** [zaproxy/zaproxy#7265]
### Describe the bug

The spider is finding href="#" links and registering them as URLs, a GET request with the same URL as the page it was present on without any URL parameters. 

This isn't correct as a href="#" doesn't reload the page, it only sets the anchor point and therefore the GET request the spider is making should not be done.

This isn't just for empty element ids (href="#") but also for links including element ids (href="#{ELEMENT_ID}")

### Steps to reproduce the behavior

1 web page containing a <a> with href="#" 

Use this web page as a seed for a spider but add a URL argument (a=1 for example)

Complete spider

You will see two nodes in the site tree

One with the original request (page with a URL argument) and the other is same URL but without any URL arguments

### Expected behavior

Do not add requests generated by href="#" to the site tree.

### Software versions

2.11.1

### Would you like to help fix this issue?

- [ ] Yes

**Comment by kingthorin** [comment]
Please provide some screenshots of the Sites Tree and actual HTML for the full tags.

Also is this the traditional Spider or the Ajax Spider?

**Comment by jhowlett96** [comment]
I am using the traditional spider. While generating a small test case I found out that this only occurs when the form method is POST. 

Example:
I have used ASP. This probably works on other files but is untested.

Page 1, where the spider should start from:
```
<%
Response.Write "<!DOCTYPE html><html xmlns=""http://www.w3.org/1999/xhtml"" lang=""en"" xml:lang=""en"">"
Response.Write "<HEAD><title>1</title></HEAD>"
Response.Write "<BODY><form action=""2.asp"" method=""post"">"
Response.Write "<input type=""submit"" name=""submit"" value=""submit""/>"
Response.Write "</form></BODY></HTML>"
%>
```

Page 2, the action of the form
```
<%
Response.Write "<!DOCTYPE html><html xmlns=""http://www.w3.org/1999/xhtml"" lang=""en"" xml:lang=""en"">"
Response.Write "<HEAD><title>2</title></HEAD>"
Response.Write "<BODY><a href=""#"">HERE</a></BODY>"
Response.Write "</HTML>"
%>
```

See below the output from ZAP showing the GET and POST URLs of 2.asp in the site tree.

![ZAP output](https://user-images.githubusercontent.com/64079227/166685138-f0ac5d41-f531-4583-b9a5-aa160015c190.gif)

**Comment by jhowlett96** [comment]
Similar outcomes, URLs with no arguments added to site tree but a different cause. You can distinguish between the two because #7161 doesn't add a referrer header but URLs generated with this method do have referrer headers.

**Comment by kingthorin** [comment]
I started putting together changes for this. Then we discussed it more as a team. The consensus is that:

> The Spider is meant to find content/functionality not necessarily to behave exactly like a Browser. To that end the existing behavior maximizes discovery.
