### ISSUE TITLE
Selenium not defaulting to bundled ChromeDriver

### ISSUE THREAD

**Issue by globeone** [zaproxy/zaproxy#7272]
### Describe the bug

For the last 3 versions of ZAP weekly when opening the Tools, Option.. Selenium panel the web driver for Chrome gets erased every time the panel is opened. Additionally on a fresh install ZAP is unable to find Chrome nor the webdriver even though both are in their default locations. 

### Steps to reproduce the behavior

- Install a fresh copy of Zap Weekly 22-05-03
- tools
- options
- selenium
- Observe that the fields are blank
- observe that chrome.exe is in it's default location on the filesystem
- observe that the chromedriver.exe is located in the location automatically generated by ZAP on the first launch
- Fill in the path to the chromedriver and chrome in the panel
- close ZAP
-  open ZAP
- go to Tools
- Options
- Selenium
- Observe that the web driver path has been erased. 
- Every use of ZAP one has to point ZAP to the web driver
- Possibly related to the tickets. Chrome can't be found, or browser not installed messages tickets. 

### Expected behavior

Would be nice if ZAP worked again like it used to automatically finding chrome.exe and the bundled chromedriver.exe in their default locations. Would also be nice if ZAP didn't erase settings, previously set by a user. 

### Software versions

OWASP ZAP
Version: D-2022-05-03

Installed Add-ons: [[id=accessControl, version=8.0.0],
[id=alertFilters, version=14.0.0], [id=ascanrules,
version=47.0.0], [id=ascanrulesAlpha, version=38.0.0],
[id=ascanrulesBeta, version=41.0.0],
[id=attacksurfacedetector, version=1.1.4], [id=authstats,
version=2.0.0], [id=automation, version=0.16.0],
[id=bruteforce, version=12.0.0], [id=callhome,
version=0.4.0], [id=commonlib, version=1.10.0],
[id=coreLang, version=16.0.0], [id=custompayloads,
version=0.11.0], [id=diff, version=12.0.0],
[id=directorylistv1, version=6.0.0], [id=directorylistv2_3,
version=4.0.0], [id=directorylistv2_3_lc, version=4.0.0],
[id=domxss, version=13.0.0], [id=encoder, version=0.7.0],
[id=exim, version=0.2.0], [id=formhandler, version=5.0.0],
[id=fuzz, version=13.7.0], [id=gettingStarted,
version=14.0.0], [id=graaljs, version=0.3.0], [id=graphql,
version=0.10.0], [id=help, version=15.0.0], [id=hud,
version=0.14.0], [id=imagelocationscanner, version=3.0.0],
[id=invoke, version=12.0.0], [id=jsonview, version=2.0.0],
[id=network, version=0.3.0], [id=oast, version=0.11.0],
[id=onlineMenu, version=10.0.0], [id=openapi,
version=28.0.0], [id=plugnhack, version=13.0.0],
[id=portscan, version=10.0.0], [id=pscanrules,
version=41.0.0], [id=pscanrulesAlpha, version=35.0.0],
[id=pscanrulesBeta, version=30.0.0], [id=quickstart,
version=34.0.0], [id=reflect, version=0.0.11],
[id=regextester, version=2.0.0], [id=replacer,
version=10.0.0], [id=reports, version=0.14.0],
[id=requester, version=5.0.0], [id=retest, version=0.3.0],
[id=retire, version=0.11.0], [id=reveal, version=5.0.0],
[id=revisit, version=4.0.0], [id=scripts, version=31.0.0],
[id=selenium, version=15.9.0], [id=sequence, version=7.0.0],
[id=soap, version=14.0.0], [id=spiderAjax, version=23.8.0],
[id=sqliplugin, version=15.0.0], [id=tips, version=10.0.0],
[id=tokengen, version=15.0.0], [id=treetools,
version=8.0.0], [id=wappalyzer, version=21.10.0],
[id=webdriverlinux, version=39.0.0], [id=webdrivermacos,
version=40.0.0], [id=webdriverwindows, version=39.0.0],
[id=websocket, version=26.0.0], [id=zest, version=36.0.0]]

Operating System: Windows 10
Java Version: Eclipse Adoptium 17.0.2
System's Locale: en_US
Display Locale: en_GB
Format Locale: en_US
Default Charset: windows-1252
ZAP Home Directory: C:\Users\$USER\OWASP ZAP_D\
ZAP Installation Directory: C:\Users\$USER\LocalPrograms\ZAPWeekly\ZAP_D-2022-05-03\.\
Look and Feel: FlatLaf Light (com.formdev.flatlaf.FlatLightLaf)

### Screenshots

![2022-05-06_zapcantfindchrome](https://user-images.githubusercontent.com/10052587/167122219-bb31006b-f188-434d-88ae-7a83085f7bee.png)

and after a stop start of ZAP

![image](https://user-images.githubusercontent.com/10052587/167123292-fe94c2d0-7eeb-43fe-bd36-f9f52edeb0ed.png)

### Errors from the zap.log file

[zap.log](https://github.com/zaproxy/zaproxy/files/8639652/zap.log)

### Additional context

Suspect this is related to
#7095 The provided Browser was not found

### Would you like to help fix this issue?

- [X] Yes

**Comment by globeone** [comment]
![image](https://user-images.githubusercontent.com/10052587/167127653-57f1feb0-3ade-4f43-8943-40ff7ccfb4b1.png)

**Comment by thc202** [comment]
Yes, it's caused by a bug in the latest release.

**Comment by thc202** [comment]
The latest version of Selenium add-on (15.9.0) should address this.
