### ISSUE TITLE
Got error when build new add-on and start ZAP with Dev mode

### ISSUE THREAD

**Issue by RealAlphaMan** [zaproxy/zaproxy#7283]
I want to create new add-on and run it in ZAP Dev mode.

I'm using Mac M1, when I use jdk 17 to build add-on, it's ok but cannot run ZAP in Dev mode (from source code), I got error:
```
Task :buildSrc:compileKotlin FAILED
e: java.lang.NoClassDefFoundError: Could not initialize class org.jetbrains.kotlin.com.intellij.pom.java.LanguageLevel
```

If I use jdk8 (install adoptopenjdk8), I can run ZAP in Dev mode but cannot build add-on, I got error
`error listing module locations for SYSTEM_MODULES: java.io.IOException: can't find system classes Fatal Error: Unable to find package java.lang in classpath or bootclasspath`

I'm a newbie in java, so, many thanks if you can support me this case!

**Comment by kingthorin** [comment]
Please don't ask questions as issues - in this case the [ZAP Dev Group](https://groups.google.com/g/zaproxy-develop) is a much better place for such questions.
