### ISSUE TITLE
How to send mail when high alert appear in scan

### ISSUE THREAD

**Issue by jlbaum** [zaproxy/zaproxy#7290]
### Is your feature request related to a problem? Please describe.

Hello I would like to send emails to an smtp to syslog when a critical alert is received

### Describe the solution you'd like

Could I use this to develop this feature to send mail when receive an alert?
https://www.zaproxy.org/docs/developer/creating-new-addon-in-zap-extensions/

### Describe alternatives you've considered

No

### Additional context

No

### Would you like to help fix this issue?

- [ ] Yes

**Comment by psiinon** [comment]
Please dont ask questions as issues. The ZAP groups are a much better place for those: https://www.zaproxy.org/community/

**Comment by kingthorin** [comment]
Go for it. Though you should develop it as a third party add-on not add it to zap-extensions.

Some examples of other third party add-ons:
- https://github.com/kingthorin/neonmarker
- https://github.com/SasanLabs/owasp-zap-jwt-addon
