### ISSUE TITLE
Ability to provide values for OpenAPI schema types 

### ISSUE THREAD

**Issue by vx-sec** [zaproxy/zaproxy#7293]
### Is your feature request related to a problem? Please describe.

The OpenAPI import add-on uses a predefined hashmap for default values to use if no values are specified as example.  
That presents an issue for endpoints like `/accounts/{account_id}/remove` where an example value might change between each testing, and the default `10` for integers is most likely wrong.  

### Describe the solution you'd like

An options menu like the existing Form Handler, that will also let users programmatically set OpenAPI values for each type before running ZAP.  

### Describe alternatives you've considered

Setting example values for each endpoint's types for ZAP to use, but editing the openapi spec file before each run is a slowdown if ZAP is used as a DAST in an SDLC.

### Would you like to help fix this issue?

- [X] Yes

**Comment by psiinon** [comment]
This is already supported as per https://www.zaproxy.org/docs/desktop/addons/openapi-support/#user-specified-values
Have you tried that?

**Comment by vx-sec** [comment]
Oh I somehow missed that point. 

I am guessing this is how you specify values for types through Form Handler?


![image](https://user-images.githubusercontent.com/103114290/169512839-459302f9-7cbc-4df2-ae18-4b7e876cd088.png)

**Comment by psiinon** [comment]
Yeah, thats how you do it :)
Let us know how you get on with that...

**Comment by vx-sec** [comment]
Works like a charm, should have RTFM. :)
For example in case of `/accounts/{account_id}/remove`, you just specify `account_id` as a field name and give it a value in form handler. 
Closing.
