### ISSUE TITLE
ZAP API requests can be excluded from proxy

### ISSUE THREAD

**Issue by mihaiursulego** [zaproxy/zaproxy#7301]
### Describe the bug

Hello,

On current https://github.com/zaproxy/zaproxy/blob/main/zap/src/main/java/org/zaproxy/zap/authentication/HttpAuthenticationMethodType.java#L401 was introduced a bug which blocks things for http requests which aren't using a realm as the if was removed.

### Steps to reproduce the behavior

1. Take the variant before the PR 7085 and do a generic SCAN with proxy. Doesn't throw error on
http://zap/JSON/script/action/setGlobalVar/?zapapiformat=JSON&formMethod=GET&varValue=https%3A%2F%2Fgoogle.com&varKey=ZapScan.target
3. Take the variant after the PR 7085 and do the same generic scan and it will throw error on  http://zap/JSON/script/action/setGlobalVar/?zapapiformat=JSON&formMethod=GET&varValue=https%3A%2F%2Fgoogle.com&varKey=ZapScan.target
The tests where done using powershell script with invoke-web cmdlet.

### Expected behavior

To be able to use http api authentication without realm

### Software versions

From ZAP_WEEKLY_D-2022-02-14.zip all release are affected.

### Additional context

```console
ZAP Error [java.net.UnknownHostException]: zap
     | Stack Trace: java.net.UnknownHostException: zap  at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)  at
     | java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)  at java.net.Socket.connect(Socket.java:607)  at org.zaproxy.zap.ZAP$ProtocolSocketFactoryImpl.createSocket(ZAP.java:434)
     | at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:728)  at
     | org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)  at
     | org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:457)  at
     | org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:207)  at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)  at
     | org.parosproxy.paros.network.HttpSender.executeMethod(HttpSender.java:432)  at org.parosproxy.paros.network.HttpSender.runMethod(HttpSender.java:674)  at
     | org.parosproxy.paros.network.HttpSender.send(HttpSender.java:629)  at org.parosproxy.paros.network.HttpSender.sendAuthenticated(HttpSender.java:604)  at
     | org.parosproxy.paros.network.HttpSender.sendAndReceiveImpl(HttpSender.java:1036)  at org.parosproxy.paros.network.HttpSender.sendAndReceive(HttpSender.java:996)  at
     | org.zaproxy.addon.network.internal.server.http.handlers.HttpSenderHandler.handleMessage(HttpSenderHandler.java:80)  at
     | org.zaproxy.addon.network.internal.server.http.MainServerHandler.notifyMessageHandlers(MainServerHandler.java:118)  at
     | org.zaproxy.addon.network.internal.server.http.MainServerHandler.processMessage(MainServerHandler.java:100)  at
     | org.zaproxy.addon.network.internal.server.http.LocalServerHandler.processMessage(LocalServerHandler.java:63)  at
     | org.zaproxy.addon.network.internal.server.http.MainServerHandler.process(MainServerHandler.java:83)  at
     | org.zaproxy.addon.network.internal.server.http.MainServerHandler.channelRead0(MainServerHandler.java:72)  at
     | org.zaproxy.addon.network.internal.server.http.MainServerHandler.channelRead0(MainServerHandler.java:37)  at
     | io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)  at
     | io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)  at
     | io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:61)  at
     | io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:370)  at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)  at
     | io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)  at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)  at
     | io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)  at java.lang.Thread.run(Thread.java:748)
```

### Would you like to help fix this issue?

- [X] Yes

**Comment by kingthorin** [comment]
What's the error you're encountering?

**Comment by mihaiursulego** [comment]
@kingthorin  ZAP Error [java.net.UnknownHostException]: zap
     | Stack Trace: java.net.UnknownHostException: zap  at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)  at
     | java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)  at java.net.Socket.connect(Socket.java:607)  at org.zaproxy.zap.ZAP$ProtocolSocketFactoryImpl.createSocket(ZAP.java:434)
     | at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:728)  at
     | org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)  at
     | org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:457)  at
     | org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:207)  at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)  at
     | org.parosproxy.paros.network.HttpSender.executeMethod(HttpSender.java:432)  at org.parosproxy.paros.network.HttpSender.runMethod(HttpSender.java:674)  at
     | org.parosproxy.paros.network.HttpSender.send(HttpSender.java:629)  at org.parosproxy.paros.network.HttpSender.sendAuthenticated(HttpSender.java:604)  at
     | org.parosproxy.paros.network.HttpSender.sendAndReceiveImpl(HttpSender.java:1036)  at org.parosproxy.paros.network.HttpSender.sendAndReceive(HttpSender.java:996)  at
     | org.zaproxy.addon.network.internal.server.http.handlers.HttpSenderHandler.handleMessage(HttpSenderHandler.java:80)  at
     | org.zaproxy.addon.network.internal.server.http.MainServerHandler.notifyMessageHandlers(MainServerHandler.java:118)  at
     | org.zaproxy.addon.network.internal.server.http.MainServerHandler.processMessage(MainServerHandler.java:100)  at
     | org.zaproxy.addon.network.internal.server.http.LocalServerHandler.processMessage(LocalServerHandler.java:63)  at
     | org.zaproxy.addon.network.internal.server.http.MainServerHandler.process(MainServerHandler.java:83)  at
     | org.zaproxy.addon.network.internal.server.http.MainServerHandler.channelRead0(MainServerHandler.java:72)  at
     | org.zaproxy.addon.network.internal.server.http.MainServerHandler.channelRead0(MainServerHandler.java:37)  at
     | io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)  at
     | io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)  at
     | io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:61)  at
     | io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:370)  at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)  at
     | io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)  at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)  at
     | io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)  at java.lang.Thread.run(Thread.java:748) '

**Comment by mihaiursulego** [comment]
@thc202 normal inside company security scanning. I've supplied  an external link because doesn't matter which link is added for scanning it will give the same error ... Which doesn't happen with versions before w2022-02-14. Could please you help me?

**Comment by thc202** [comment]
The referenced pull request is unrelated to the steps and the exception provided. Are you accessing the ZAP API before calling that endpoint?
The realm is not taking into account unless the site requests HTTP authentication, which does not seem to be the case.

**Comment by dracmic** [comment]
@thc202  it isn't the single the call I am doing and they are successful only this failing. How I mentioned I've tested the one before the mentioned release and it works. I am running the zap scanner inside docker and I have some custom build this scripts which I also tested today all day, but the cause after testing weekly releases it is the PR mentioned in my case.

**Comment by mihaiursulego** [comment]
@thc202  it isn't the single the call I am doing and they are successful only this failing. How I mentioned I've tested the one before the mentioned release and it works. I am running the zap scanner inside docker and I have some custom build this scripts which I also tested today all day, but the cause after testing weekly releases it is the PR mentioned in my case.

**Comment by thc202** [comment]
ZAP is composed of different codebases, given the date when the issue started and the exception provided most likely problem is in an add-on (i.e. Network) not the referenced pull request. I still need the details that lead to the issue.

**Comment by mihaiursulego** [comment]
@thc202 simply I've taken over the task to update the internal company zap scanner and the source code in the release was your latest stable release. As I prefer to be up to date and automate the things, I was trying to get the latest weekly and throw it inside the docker(entire directory of Zap unmodified). But I got bumped over this, and after investigating the internal scripts and checked all the possibilities, I've taken the weekly releases after the latest release and found out where the issue was introduced for me. They are only wrappers on top of ZAP which are adding exclusions through zapproxy and adding variables and they crash as shown above.

**Comment by kingthorin** [comment]
Details of exactly what API calls etc are being used, in what order, are necessary to re-create and troubleshoot the issue.

If you’re unable to provide the details we will be unable to assist further.

**Comment by mihaiursulego** [comment]
@kingthorin  as I am on EU region I will do a list of the calls and I will come to you tomorrow, which are all to your zap proxy.

**Comment by mihaiursulego** [comment]
@kingthorin  @thc202  can you please advise how to share the execution logs as they are kinda big to be shared as raw here. I've used a personal domain which I own instead of the company one.

**Comment by thc202** [comment]
Are the logs with debug? Did you try attach them? Otherwise you can try send them directly I guess (same username at gmail).

**Comment by mihaiursulego** [comment]
With debug info from wrappers not from ZAP itself. I can't attach them here :)  only to raw paste :)

**Comment by mihaiursulego** [comment]
I've send them to your gmail @thc202.

**Comment by thc202** [comment]
Thank you!

Have you tried with the latest weekly release? Could you if not?
There were more changes since then that could have address this (thinking of zaproxy/zap-extensions#3615).

**Comment by mihaiursulego** [comment]
@thc202  I'm sorry to announce you that from that I started to investigate and debug it so the latest release doesn't solve it. As I wanted to have a Dockerfile which will pull and copy the latest weekly and bake it in docker.

**Comment by thc202** [comment]
That's ok, could you still provide the logs with the latest weekly? I'm interested in an up-to-date stacktrace.

**Comment by mihaiursulego** [comment]
@thc202  you have them in email :)

**Comment by thc202** [comment]
Thank you for the details provided.
