### ISSUE TITLE
Translation project transfer

### ISSUE THREAD

**Issue by cn-fairy** [zaproxy/zaproxy#7314]
### Is your feature request related to a problem? Please describe.

Transfer translation to GitHub

### Describe the solution you'd like

Crowdin is not conducive to translation. Can you put translation on GitHub?

### Describe alternatives you've considered

Transfer translation to GitHub

### Screenshots

![image](https://user-images.githubusercontent.com/74580422/171574516-410b70e5-d500-4e18-95e1-4ce67843061a.png)

### Additional context

Because there are many people involved in the translation of crowdin, it is impossible to determine exactly which word is the most accurate. Compared with crowdin, the translation progress is very slow. I hope to transfer the translation project to GitHub.

Consultation: If I download the language files on crowdin.com and translate them independently, how can I generate and use my custom language pack files?

### Would you like to help fix this issue?

- [x] Yes

**Comment by psiinon** [comment]
Crowdin is a platform focussed on traslation - I'm not sure how transfering to github will help.
Can you explain in detail why you think it would be better?
We have over 600 people translating zaproxy on Crowdin, we would need to be sure that the majority of active translators would prefer github over Crowdin, which tbh I think is unlikely.

**Comment by cn-fairy** [comment]
Crowdin's access is restricted in some countries (China). When there are multiple translations of a word, it can't be well communicated and confirmed to adopt that one.
Or both Crowdin and GitHub are adopted to avoid some inaccessible translation project being suspended.

**Comment by dies** [comment]
Hi @cn-fairy 

Crowdin is not banned in China. Crowdin uses AWS infrastructure to make it as fast as possible in China

**Comment by cn-fairy** [comment]
Yes, the inaccessible description error (only the company network test was used)

**Comment by kingthorin** [comment]
So you couldn’t access it from work and assumed that meant it was blocked across China?
