### ISSUE TITLE
Allow icons to be scaled independently of the text

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#7326]
As per #541 buttons are scaled when the default font is scaled.
Having an option to scale them independently would help some people.
I think keeping the current behaviour as the default would be best.

**Comment by psiinon** [comment]
If anyone else fancies having a go at this then the key class is https://github.com/zaproxy/zaproxy/blob/main/zap/src/main/java/org/zaproxy/zap/utils/DisplayUtils.java - esp the getScaledIcon(..) methods.
The options will also need changing as well as the relevant dialog...

**Comment by Siddharth3330** [comment]
Hi, I would like to work on it.

**Comment by Siddharth3330** [comment]
Hi, I believe I didn't understand the problem statement correctly.
When I tried scaling font size the icon size remains the same. So do we require a similar block like "General Font" to scale the icon size within this display option? 
![Screenshot (152)](https://user-images.githubusercontent.com/67500395/177720163-20d145fc-b3ec-43c5-aaab-905c74d8ce9d.png)
