### ISSUE TITLE
Path Traversal test false positive

### ISSUE THREAD

**Issue by notgreg** [zaproxy/zaproxy#7348]
We are running zap on our website , and it is reporting that we are vulnerable to Path Traversal

but i cannot see how this is any thing to do with folder traversal , the page does not allow path names or deal with filenames and the attack is not even submitting any of the parameters that would cause a problem

URL | http://lor-c2dev-001/selenium/admin/strings/10?searchLanguage=10
Method | GET
Parameter | searchLanguage
Attack | 10
Evidence |  
URL | http://lor-c2dev-001/selenium/admin/strings/11?searchLanguage=11
Method | GET
Parameter | searchLanguage
Attack | 11
Evidence

it repeats this attack 80 times on various pages.

is this a mistake in the test or am i missing something

Thanks 
Craig

**Comment by kingthorin** [comment]
Seems like a duplicate. The behaviour of the rule/check is described here: https://github.com/zaproxy/zaproxy/issues/7031#issuecomment-1015809942

**Comment by kingthorin** [comment]
It's probably also a FP in your case, as with the issue you've duplicated. The problem would be if a malicious user could reference the local file and thus get the source code or some other unwanted behaviour.

**Comment by notgreg** [comment]
Thanks for the replies. do you know a way to stop this FP from happening, My boss does not want any false positives in the report if possible as they just show as alerts on customers systems when they run it and we then have to explain that to them

**Comment by kingthorin** [comment]
You can set an Alert Filter to classify it FP and exclude FPS from reports. Or you could disable the rule.

https://www.zaproxy.org/docs/desktop/addons/alert-filters/

**Comment by kingthorin** [comment]
Duplicate of zaproxy/zaproxy#7031
