### ISSUE TITLE
Add application/x-ndjson to avoid Unexpected Content-Type was returned

### ISSUE THREAD

**Issue by RubenPozoMolina** [zaproxy/zaproxy#7349]
### Is your feature request related to a problem? Please describe.

We are getting  Unexpected Content-Type was returned for application/x-ndjson type.

### Describe the solution you'd like

Add the type to expected types

### Describe alternatives you've considered

Modify code locally

### Would you like to help fix this issue?

- [X] Yes

**Comment by RubenPozoMolina** [comment]
I created https://github.com/RubenPozoMolina/zaproxy/pull/1 pr to add this document type

**Comment by thc202** [comment]
It was created in your repo, could you do the PR against this one? Could you also update the changelog?
