### ISSUE TITLE
Header `If-None-Match: *` removed for PUT requests

### ISSUE THREAD

**Issue by DeppLearning** [zaproxy/zaproxy#7353]
### Describe the bug

This has been raised before: https://github.com/zaproxy/zaproxy/issues/1284

I am experiencing the same issue, however for a PUT request. Mozilla describes two use cases for the header, where the second reads:

> For other methods, and in particular for [PUT](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PUT), If-None-Match used with the * value can be used to save a file not known to exist, guaranteeing that another upload didn't happen before, losing the data of the previous put;

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-None-Match

From what I understood, ZAP strips the header since it's related to caching and one want's fresh data. However, PUT requests shouldn't be cacheable anyways.

### Steps to reproduce the behavior

Proxy a request containing the header through ZAP

### Expected behavior

Header is not stripped

### Software versions

owasp/zap2docker-bare:2.11.1

### Would you like to help fix this issue?

- [X] Yes

**Comment by FlorinPetreanBentley** [comment]
Any updates regarding this issue? Or any workarounds?

**Comment by thc202** [comment]
As workaround you can add the header back with e.g. HTTP Sender script.

**Comment by thc202** [comment]
Yes, that's why you need to add it back there.

I assumed you knew what message you wanted to change and the value to set. The Proxy script should allow you to get that info (along with global variables).
