### ISSUE TITLE
Chrome issue when clicking Launch Browser

### ISSUE THREAD

**Issue by bepooley** [zaproxy/zaproxy#7355]
### Describe the bug

Hello 

We have installed OWASP ZAP 2.11.1 on our development network. We have selected the standard method of installation which includes the automatic updates. When selecting “Manual Explore”, adding in a URL and then when selecting Launch Browser it works when Firefox is selected, but it does not work when Chrome is selected. When Chrome is selected a window appears as if it will open, but then it closes automatically. 

 

Our version of Chrome is 102.0.5005.63

 

Please assist. 

 

Thank you 

### Steps to reproduce the behavior

We have installed OWASP ZAP 2.11.1 on our development network. We have selected the standard method of installation which includes the automatic updates. When selecting “Manual Explore”, adding in a URL and then when selecting Launch Browser it works when Firefox is selected, but it does not work when Chrome is selected. When Chrome is selected a window appears as if it will open, but then it closes automatically. 

### Expected behavior

Chrome should open 

### Software versions

OWASP ZAP 2.11.1
Our version of Chrome is 102.0.5005.63

### Would you like to help fix this issue?

- [ ] Yes

**Comment by bepooley** [comment]
![image](https://user-images.githubusercontent.com/108015165/175097450-8eb1e09b-a652-419e-b47a-1eeb6c9a97bd.png)

**Comment by kingthorin** [comment]
Please update it, you have 33 installed but 39 is available which includes ChromeDrive 102.x.x.x.

**Comment by bepooley** [comment]
I have performed the update but it is still not working it says "the provided browser was not found" Is there a way that I need to pre-configure it to proxy through ZAP?

**Comment by kingthorin** [comment]
Are you able to start Chrome from a command prompt?
Was Chrome installed from the Windows store or a Google provided installer?

**Comment by kingthorin** [comment]
Probably just `chrome.exe`

**Comment by psiinon** [comment]
They have now been released.
@bepooley can you update and try again?

**Comment by bepooley** [comment]
I am having an issue with receiving updates - when I go into Manage Add-ons I get an error as screenshotted below

**Comment by bepooley** [comment]
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/108015165/176448241-f5e5c653-2fc9-4260-9ad5-818c4c9e44e4.png)

**Comment by thc202** [comment]
@bepooley any details?

**Comment by bepooley** [comment]
We downloaded and imported the certificate for OWASP into the browser. Then modified the proxy chain in OWASP to use an outgoing proxy servers and added our domain name and port. Once this was done, the updates came through :)

Thanks for your help all
