### ISSUE TITLE
alertRef 10054 seems to miss to fill evidence when SAMESITE set to None

### ISSUE THREAD

**Issue by agroszer** [zaproxy/zaproxy#7358]
### Describe the bug

Response sets cookies like this:

![Screenshot_2022-06-23_13-56-59](https://user-images.githubusercontent.com/350912/175293206-8121c32d-1327-4d81-85f1-586c8028b89e.png)

I get results in JSON:
```				{
					"pluginid": "10054",
					"alertRef": "10054",
					"alert": "Cookie with SameSite Attribute None",
					"name": "Cookie with SameSite Attribute None",
					"riskcode": "1",
					"confidence": "2",
					"riskdesc": "Low (Medium)",
					"desc": "<p>A cookie has been set with its SameSite attribute set to \"none\", which means that the cookie can be sent as a result of a 'cross-site' request. The SameSite attribute is an effective counter measure to cross-site request forgery, cross-site script inclusion, and timing attacks.</p>",
					"instances":[ 
						{
							"uri": "https://app.shoobx.com/",
							"method": "GET",
							"param": "",
							"attack": "",
							"evidence": ""
						},
						{
							"uri": "https://app.shoobx.com/robots.txt",
							"method": "GET",
							"param": "",
							"attack": "",
							"evidence": ""
						}
					],
					"count": "2",
					"solution": "<p>Ensure that the SameSite attribute is set to either 'lax' or ideally 'strict' for all cookies.</p>",
					"otherinfo": "",
					"reference": "<p>https://tools.ietf.org/html/draft-ietf-httpbis-cookie-same-site</p>",
					"cweid": "1275",
					"wascid": "13",
					"sourceid": "1"
				},
				{
					"pluginid": "10054",
					"alertRef": "10054",
					"alert": "Cookie without SameSite Attribute",
					"name": "Cookie without SameSite Attribute",
					"riskcode": "1",
					"confidence": "2",
					"riskdesc": "Low (Medium)",
					"desc": "<p>A cookie has been set without the SameSite attribute, which means that the cookie can be sent as a result of a 'cross-site' request. The SameSite attribute is an effective counter measure to cross-site request forgery, cross-site script inclusion, and timing attacks.</p>",
					"instances":[ 
						{
							"uri": "https://app.shoobx.com/",
							"method": "GET",
							"param": "AWSELB",
							"attack": "",
							"evidence": "Set-Cookie: AWSELB"
						},
						{
							"uri": "https://app.shoobx.com/robots.txt",
							"method": "GET",
							"param": "AWSELB",
							"attack": "",
							"evidence": "Set-Cookie: AWSELB"
						}
					],
					"count": "2",
					"solution": "<p>Ensure that the SameSite attribute is set to either 'lax' or ideally 'strict' for all cookies.</p>",
					"otherinfo": "",
					"reference": "<p>https://tools.ietf.org/html/draft-ietf-httpbis-cookie-same-site</p>",
					"cweid": "1275",
					"wascid": "13",
					"sourceid": "1"
				},
```

`evidence` gets filled when `SAMESITE` is unset, but not when `SAMESITE` in `None`

### Steps to reproduce the behavior

see above

### Expected behavior

I think `evidence` should contain "Set-Cookie: AWSELBCORS"

### Software versions

"@version": "2.11.1"

### Would you like to help fix this issue?

- [X] Yes

**Comment by kingthorin** [comment]
The code in question is here:
- Scan rule > https://github.com/zaproxy/zap-extensions/blob/main/addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CookieSameSiteScanRule.java
- Unit tests > https://github.com/zaproxy/zap-extensions/blob/main/addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/CookieSameSiteScanRuleUnitTest.java
- - CHANGELOG > https://github.com/zaproxy/zap-extensions/blob/main/addOns/pscanrules/CHANGELOG.md

Information on setting up a dev environment is available here: https://www.zaproxy.org/docs/developer/

**Comment by kingthorin** [comment]
It should be as simple as looking at how the 'missing' code adds the evidence and make sure the 'none' code does the same thing. Update the 'none' unit tests to assert that evidence is properly set. Add a note to the 'Unreleased' section of the CHANGELOG, probably under the `### Changed` sub-heading.

**Comment by agroszer** [comment]
Apparently I filed the bug at the wrong repo... PR is up for review, what to do?
