### ISSUE TITLE
Webhook alerts

### ISSUE THREAD

**Issue by roisec** [zaproxy/zaproxy#7361]
### Is your feature request related to a problem? Please describe.

When the active scan is finished, 
I want the ability to send a summary of findings through the webhook URL.

### Describe the solution you'd like

Ability to configure it through the zap settings.

### Describe alternatives you've considered

Using an external extension

### Would you like to help fix this issue?

- [x] Yes

**Comment by thc202** [comment]
Did you try using the ZAP API?

**Comment by thc202** [comment]
@RoiSec do you have more information?

**Comment by RoiSec** [comment]
Hi @thc202 ,
I know the ZAP API, 
I am using ZAP within CI/CD and I want to inform when scan is finished, I prefer to use it besides checking the API periodically.
In Addition, a feature that sends webhook with a summary of the result can be nice and makes life easy.

**Comment by kingthorin** [comment]
So you want ZAP to initiate a specific request on specific events?

**Comment by RoiSec** [comment]
@kingthorin ,Yes

**Comment by psiinon** [comment]
This can be achieved by scripts.
How are you running ZAP?
Using the packages scans, the Automation Framework, daemon + API or ??

**Comment by kingthorin** [comment]
Relevant docs/resources:
- https://www.zaproxy.org/docs/internal-events/
- https://github.com/zaproxy/community-scripts/blob/main/extender/ZAP%20onEvent%20Handler.js

**Comment by RoiSec** [comment]
@kingthorin 
Do you mean to modify the script and use trigger actions for events?
How can I configure that automatically at the CI/CD pipeline? 
Why do I need to write a script? I think it's a legitimate feature that needs to be out of the box.

**Comment by psiinon** [comment]
You can write a script to do it now.
Or you can wait for us (or someone else) to implement it at some unspecified point in the future.
I personally dont think this needs to be supported out of the box, especially as I'd expect people to have different requirements.
Scripts can be added via the command line [scri](https://www.zaproxy.org/faq/how-do-you-add-a-script-to-zap-from-the-command-line/)
or via the Automation Framework `script` job: https://www.zaproxy.org/docs/desktop/addons/script-console/automation/

**Comment by kingthorin** [comment]
@RoiSec psiinon’s answer kind of covers it

**Comment by RoiSec** [comment]
@psiinon 
My planning is to corporate ZAP during the CI, enrich the ZAP with HTTP requests and context and then start the active scan of several attacks.
I am pretty not fully understand how ZAP is built for CI/CD pipelines and there is no option to trigger a webhook or make an HTTP request when it is finished.
currently, I have 2 options, write a script wrapper that updates when something occurs or use a ZAP script.

**Comment by psiinon** [comment]
@RoiSec so you want a web hook to be invoked when the ZAP active scan completes?
What data would you like it to send?
Can you give an example interface?
If its not too complicated then we might be able to create an example for the Community Scripts repo - I'm sure other people would find this useful too...

**Comment by RoiSec** [comment]
Hi, 
I would like to trigger actions when:
active scan started, finished, paused and etc.
Data:
I would like to send a summary of the findings when the scan is finished.
a number of alerts per severity, on every alert supply a link for more details, and support JSON output, ability to whitelist alerts by severity, status block/pass(want to use it for CICD checks), link to scanning report.
example usage: slack message with the above information

**Comment by kingthorin** [comment]
That’s all stuff you can do via the API like everyone else that uses ZAP in CI/CD.

**Comment by psiinon** [comment]
Yeah, thats way more than just a webhook :P 
The Automation Framework is also an option: https://www.zaproxy.org/docs/automate/automation-framework/

We actually have an example script which handles events: https://github.com/zaproxy/community-scripts/blob/main/extender/ZAP%20onEvent%20Handler.js
We also give details of all the events that ZAP can raise here: https://www.zaproxy.org/docs/internal-events/

I'm all for things like slack integration but this issue if far too generic for my liking and is already handled by scripts.
So I vote for closing it.
Thoughts from anyone else?

**Comment by RoiSec** [comment]
It can all be done by API scripts, but it’s much more effort to handle. I think meant to be built-in feature beside develop such scripts.
I think product for CI/CD should have the capability of to send webhook triggers

**Comment by kingthorin** [comment]
I agree @psiinon .

This is the only time it’s ever come up. We know there are tons and tons of CI/CD invocations daily based on the existing functionality and our stats. There are options which have been presented.

**Comment by ricekot** [comment]
@roisec You may take a look at https://www.zaproxy.org/blog/2022-09-13-zap-extender-scripts/#subscribe-to-zap-events for an example script that sends alerts raised by ZAP to a Discord webhook. You could modify the script to listen for events published by `org.zaproxy.zap.extension.ascan.ActiveScanEventPublisher` (see https://www.zaproxy.org/docs/internal-events/) and send custom messages to your own webhook.
