### ISSUE TITLE
Import ZAP Alert Rules to a file 

### ISSUE THREAD

**Issue by Srujankumar99** [zaproxy/zaproxy#7366]
Hi,

I'm working on Automating the Dynamic Scan Analysis and I would like to pass the a set of scan rules to the API's while doing the scan. 

Instead of scanning the API's with all the ZAP rules - I would like to scan all the API with only few rules. Multiple API's will be scanned in parallel by passing set of rules in the scan. 

How do we import the ZAP Alert rules ( https://www.zaproxy.org/docs/alerts/ ) to a json/xml or any file?

Appreciate the help.

Thank you

**Comment by thc202** [comment]
Depends on how you are automating ZAP, see: https://www.zaproxy.org/docs/automate/

Usage questions are better in the OWASP ZAP User group: https://groups.google.com/g/zaproxy-users
