### ISSUE TITLE
ability to regex or diff and remove unnecessary things from response body

### ISSUE THREAD

**Issue by aerosayan** [zaproxy/zaproxy#7368]
### Is your feature request related to a problem? Please describe.

Response bodies are obviously sometimes very large. It becomes difficult to find interesting and different things.

Common things which don't help pentesters include embedded google analytics code, embedded css, 6-10 MB sized embedded js script libraries like jquery, embedded svg and other things.

Sometimes websites use a common base of code to do everything, and for pentesting purposes, they're unnecessary.

I would like to remove things that clutter the response body, so I could find interesting things.

### Describe the solution you'd like

Not sure completely. This would be very useful but more experienced cybersecurity people maybe able to say exactly which features would be helpful for this. If this is something your team would be interested in, we could fine-tune the details later.

For now, only the basic feature request is clear to me ...

1. allow the user to use a "diff" or "regex" method to remove unnecessary text from the response body, so we can find interesting things in the code easily

### Describe alternatives you've considered

Save the responses in text files, then run a bash/python script to find common blobs of text, and remove them. Then go through each response to find interesting things.

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment]
Encode/Decode dialogue with custom scripts should allow to do this.

**Comment by psiinon** [comment]
I think scripts are the way to go.
Have a look at https://github.com/zaproxy/community-scripts/blob/main/targeted/Find%20HTML%20comments.js - I think it could be the basis of something much more sophisticated. If you write anything that significantly enhances it then please contribute it back :)

**Comment by psiinon** [comment]
Thats the advantage of scripting - you can make it as simple or complicated as you like 😁

**Comment by kingthorin** [comment]
Since you e agreed scripting is the solution there doesn’t seem to be a reason to keep this open.
