### ISSUE TITLE
Add ability to add custom hosts with fixed addresses (à la /etc/hosts)

### ISSUE THREAD

**Issue by TheDcoder** [zaproxy/zaproxy#7371]
### Is your feature request related to a problem? Please describe.

I'm always frustrated when I need to modify my `/etc/hosts` file to add a custom host with a fixed address to fool my web-browser to use a different host name for the same remote host.

### Describe the solution you'd like

Since ZAP operates as a proxy, it can easily intercept requests to certain hosts and then redirect them to fixed addresses to replicate the same behavior.

### Describe alternatives you've considered

Editing the hosts file directly but it's a B-grade way to do this in my opinion.

### Would you like to help fix this issue?

- [ ] Yes

**Comment by TheDcoder** [comment]
@thc202 My bad, I did a customary search but none of the keywords matched, oops.

By the way, you closed this as "not planned" but you've added the duplicate issue to a new milestone? The message is kind of confusing :)

**Comment by thc202** [comment]
That's a GitHub UI thing, that "category" includes duplicates.

**Comment by thc202** [comment]
We can't choose the actual reason of the "not planned".

**Comment by TheDcoder** [comment]
Ah, I see. Thanks for checking.
