### ISSUE TITLE
Support Apple Silicon

### ISSUE THREAD

**Issue by silverskyvicto** [zaproxy/zaproxy#7376]
### Is your feature request related to a problem? Please describe.

There is no ZAP desktop application that is compatible with Apple Silicon.

### Describe the solution you'd like

I would like to see official support for Apple Silicon.

If it can be run on an Apple Silicon-compatible application, better performance can be expected.

### Describe alternatives you've considered

When running ZAP on Apple Silicon, Rosetta2 must be used.

### Would you like to help fix this issue?

- [X] Yes

**Comment by psiinon** [comment]
As far as I'm aware none of the Core Team has access to an Apple Silicon box, which could prove problematic.
Oracle have released a version of Java for Arm 64 : https://www.oracle.com/java/technologies/downloads/#jdk17-mac
Try that and let us know if it works :)

**Comment by DiogoMRSilva** [comment]
Hi, I use a mac with M1 and have no issues. If you want it to run without Rosetta2 you can install an ARM JDK and run ZAP through the [ZAP_2.11.1_Crossplatform.zip](https://github.com/zaproxy/zaproxy/releases/download/v2.11.1/ZAP_2.11.1_Crossplatform.zip)

**Comment by silverskyvicto** [comment]
@psiinon 
I ran the `copyMandatoryAddOns` task and ran it with just Mandatory Addon and it worked fine.

Also, when I ran the `copyZapAddOns` task and started it, the following warning message was displayed.
```
An error occurred while initialising JavaFX. The response view "Render hTML" will not be available. 
Make sure that JavaFX is available on your system or JRE/JDK. The error was logged.
```

I excluded the BrowserView addon and it worked fine.

**Comment by kingthorin** [comment]
That’s normal.

**Comment by rhoekman** [comment]
I was also able to compile it for M1 but the Firefox browser when launched from the toolbar or in headless spider crawl, it is still Intel. Any ideas on how to make those compile for the M1 aswell?
<img width="1184" alt="zap-macos-m1-screenshot" src="https://user-images.githubusercontent.com/9697537/180583778-57f5ad67-5c9f-430c-896b-6f77f5b2687f.png">

**Comment by kingthorin** [comment]
It’s using whatever you have installed.

We don’t bundle browsers.

**Comment by rhoekman** [comment]
Firefox that I have installed is a Univeral Binary. Pretty weird that it picks/uses an Intel version.

**Comment by kingthorin** [comment]
That’s probably a gecko driver thing. I don’t know for sure but it’s likely just a numbers assumption on Mozilla’s part, Intel’ish CPUs are likely easily 90 of their install base. If it isn’t a CPU decision it might be an install path one which also plays a numbers game :wink:

(Of course that’s all speculation on my part.)

**Comment by rhoekman** [comment]
Yeah you are right, gecko driver is still Intel. So that makes sense in this case. Firefox launched from the dock runs as Apple Silicon. I think the driver (or arch check) that ZAP uses in ~/Library/Application Support/ZAP/webdriver/macos/64/geckodriver needs te be updated?

**Comment by thc202** [comment]
It should be already picking the appropriate arch. Under Options > Selenium click Bundled, and tell which one it selects.

**Comment by rhoekman** [comment]
<img width="881" alt="zap-selenium-webdrivers-screenshot" src="https://user-images.githubusercontent.com/9697537/180599778-f6a2977e-1722-4e3e-ba0c-aa4aa899c20a.png">

Also the drivers in the arm64 directory are not executable. It appears these are binaries for Linux with Arm processors. Apple Silicon seems to be **aarch64**

In _webdrivers.gradle.kts_ it seems to not picking up the correct arch type and falls back to 64:

fun getArchPath(task: DownloadWebDriver): String {
    return when (task.arch.get()) {
        DownloadWebDriver.Arch.X32 -> "32"
        DownloadWebDriver.Arch.ARM64 -> "arm64"
        else -> "64"
    }
}

**Comment by thc202** [comment]
Provide the value of the Java system property `os.arch`.

**Comment by rhoekman** [comment]
Not sure what you mean or what you want me to do? 😬

**Comment by thc202** [comment]
Run the following as a Stand Alone JavaScript script:
```js
print(java.lang.System.getProperty("os.arch"))
```
https://www.zaproxy.org/docs/desktop/addons/script-console/

**Comment by rhoekman** [comment]
Ah gotcha 🙂 It's indeed **aarch64**

<img width="390" alt="screenshot-arch-check" src="https://user-images.githubusercontent.com/9697537/180635161-23b16397-84b1-4154-853c-2d50263828d0.png">

**Comment by thc202** [comment]
That's the expected architecture and the one used to determine the location of the binary.

Could you use the `file` command on the binary in the `arm64` directory?
Could you also check the logs to see if there's any warning related to the WebDriver?

**Comment by rhoekman** [comment]
Output of file command:
geckodriver: Mach-O 64-bit executable arm64

I'm not seeing any errors in the logs

**Comment by rhoekman** [comment]
When I go to Tools > Options > Selenium > Webdrivers and click on Bundled the path changes to:

`/Users/rickhoekman/Library/Application Support/ZAP_D/webdriver/macos/arm64/geckodriver`

And this works! 🙂

**Comment by kingthorin** [comment]
Perfect, that’s what @thc202 [suggested](https://github.com/zaproxy/zaproxy/issues/7376#issuecomment-1193070941) so we’re glad it worked.

**Comment by rhoekman** [comment]
Yeah, a bit of an oversight on my part.😬 What does Bundle do.. grabs/detects the right path?

btw. Running this now is blazing fast! 😃

**Comment by rhoekman** [comment]
Still after every build, I have to Bundle it otherwise it still uses the Intel version.

**Comment by thc202** [comment]
What do you mean with "after every build"? Are you running ZAP from source?

**Comment by rhoekman** [comment]
Yes I do

**Comment by thc202** [comment]
I'd suggest you use `-dir` then, to avoid using the configs from the main home.

**Comment by rhoekman** [comment]
> As far as I'm aware none of the Core Team has access to an Apple Silicon box, which could prove problematic.

I have a MacBook Air M1 that I could setup and give access to the Core Team if needed?
