### ISSUE TITLE
OWASP ZAP plugin for TeamCity

### ISSUE THREAD

**Issue by priyajaroli** [zaproxy/zaproxy#7378]
### Is your feature request related to a problem? Please describe.

We want to integrate ZAP in our CI/ CD pipeline, we have teamcity implemented for the same. Need OWASP ZAP plugin for TeamCity?

### Would you like to help fix this issue?

- [X] Yes

**Comment by kingthorin** [comment]
Why is a plug-in needed?

**Comment by priyajaroli** [comment]
> Why is a plug-in needed?
> 

We want to integrate ZAP in our CI/CD pipeline and we are using TeamCity for CI/CD. I will look into the ways to automate ZAP . Thanks

**Comment by thc202** [comment]
Closing, we don't have any plans to provide nor maintain a TeamCity plugin.

If you want to do that and coordinate efforts with others the dev group is a good place: https://groups.google.com/group/zaproxy-develop
