### ISSUE TITLE
CSP Alert missing when there is invalid character in header

### ISSUE THREAD

**Issue by balakrishnangithub** [zaproxy/zaproxy#7379]
## Version
ZAP 2.11.1

## Brief on issue
When the Content-Security-Policy header has an invalid character ZAP completely ignores the CSP alert.

#### Valid Header
```
Header set Content-Security-Policy "default-src 'self' 'unsafe-eval' 'unsafe-inline' cdn.jsdelivr.net;"
```

#### Invalid Header
```
Header set Content-Security-Policy "default-src ‘self’ 'unsafe-eval' 'unsafe-inline' cdn.jsdelivr.net;"
```
It's the invalid Unicode single quote.

#### ZAP Report with invalid header
![Screenshot 2022-07-10 002117](https://user-images.githubusercontent.com/4893873/178120048-05d19016-4f94-4e32-964e-047c1ff683b1.png)
#### ZAP Report with valid header
![Screenshot 2022-07-10 000622](https://user-images.githubusercontent.com/4893873/178120125-ee18f31a-716a-40da-963f-ead549d259c5.png)

**Comment by kingthorin** [comment]
Please use the proper issue template in the future.
