### ISSUE TITLE
Incorrect canonical url formation prevents scanning when there is '#' in the url

### ISSUE THREAD

**Issue by sourabhsdeshpande** [zaproxy/zaproxy#7384]
### Describe the bug

When a URL has **#** in it then, in the spidering process, canonical url formed is wrong. This prevents further scan..
Let's say, there is below url for one of the anchor tags. Note **#** in the url.
https://myserver/planningmodule/#?PId=110c162d-8956-40b2-bec7-fbdba8898a4a&id=1
In above case, when scan happens, canonical url formed is- https://myserver/planningmodule/
Note that, it has ignored the url and parameters after **#**. Hence, page is not scanned.

It is common to have **#** in the urls for SPA applications.

### Steps to reproduce the behavior

1. Via Zap automation API(or may be Zap tool itself), trigger a Zap scan on the target **whose anchor tag contains the URL having **#**** For example, https://myserver/planningmodule/#?PId=110c162d-8956-40b2-bec7-fbdba8898a4a&id=1
2. Let the scan complete.
3. Note that, scanning has not happed for the URL whose anchor tag had **#** in it.
4. It tries to scan the url **https://myserver/planningmodule/** and without query string parameters. Hence, there is no meaning to the url.
5. Log in the log file- 
spider.parser.SpiderHtmlParser - Canonical URL constructed using  https://myserver/planningmodule/#?PId=110c162d-8956-40b2-bec7-fbdba8898a4a&id=1 : **https://myserver/planningmodule/**

### Expected behavior

Canonical url should be formed considering all the query string parameters.
In this case, for example,- https://myserver/planningmodule/#?PId=110c162d-8956-40b2-bec7-fbdba8898a4a&id=1 
So that, there the scanner will scan this urls and more urls under above url.

### Software versions

Zap version: 2.11.1

### Errors from the zap.log file

[ZAP-SpiderThreadPool-0-thread-2] DEBUG org.zaproxy.zap.spider.URLCanonicalizer - Resolved URL: https://myserver/planningmodule/#?PId=110c162d-8956-40b2-bec7-fbdba8898a4a&id=1 

[ZAP-SpiderThreadPool-0-thread-2] DEBUG org.zaproxy.zap.spider.parser.SpiderHtmlParser  - https://myserver/planningmodule/#?PId=110c162d-8956-40b2-bec7-fbdba8898a4a&id=1 : https://myserver/planningmodule/

[ZAP-SpiderThreadPool-0-thread-2] DEBUG org.zaproxy.zap.spider.SpiderController - https://myserver/planningmodule/

[ZAP-SpiderThreadPool-0-thread-2] DEBUG org.zaproxy.zap.spider.filters.DefaultFetchFilter - Checking: https://myserver/planningmodule/

[ZAP-SpiderThreadPool-0-thread-2] DEBUG org.zaproxy.zap.spider.filters.MaxChildrenFetchFilter - Checking: https://myserver/planningmodule/

### Additional context

I did some investigation in code in Github and found that below might be the cause for it.

Issue most likely is in function `getCanonicalURL(String, String) Line numbers- 174, 175` in file https://github.com/zaproxy/zaproxy/blob/ad7eb1e2fa072893e8498387ee78e66f87b87a57/zap/src/main/java/org/zaproxy/zap/spider/URLCanonicalizer.java

### Would you like to help fix this issue?

- [ ] Yes

**Comment by kingthorin** [comment]
The URLs are malformed to begin with, everything after the # is considered part of the fragment and only relevant client side. If you wish to pass query parameters they should be before the fragment specifier.

**Comment by kingthorin** [comment]
https://www.rfc-editor.org/rfc/rfc3986#section-4.1

`relative-ref = relative-part [ "?" query ] [ "#" fragment ]`

**Comment by psiinon** [comment]
The traditional spider will not be able to handle URLs with a "#" in them for the reasons @kingthorin has given.
The Ajax Spider should be able to handle them much better - have you tried that?
If you still have problems then let us know - I am looking at how we can make ZAP handle modern web apps much more effectively.
