### ISSUE TITLE
owasp Zap y genymotion

### ISSUE THREAD

**Issue by KT518** [zaproxy/zaproxy#7385]
### Is your feature request related to a problem? Please describe.

Hola, soy nueva por aca....no se si sea la opción indicada.
Estoy emulando el celular con Genymotion y con owasp zap lo tengo como proxy para ver la emulación y los problemas de unas app. 
Me funciona la sincronización de zap y genymotion, descargo la app de la tienda del celular virtualizado y cuando la abro me pide autenticación normal de la app, yo tengo el usuario real y funcional, pero cuando le doy el usuario y la contraseña se queda en ese paso.
Estuve indagando y me digeron que hacen autenticación con google oa2. Cómo puedo saltarme éste control de la app? 
Saludos!!

### Describe the solution you'd like

poder navegar por la app descargada del play store en genymotion, y que las tramas queden en OWASP ZAP 

### Describe alternatives you've considered

- Actualizaciones al día tanto de Owasp Zap como Genymotion
- El certificado de Owasp ZAP lo volví a generar y realizar toda la configuración 
- He instalado un APK que se llama cydia-substrate-0-9-4011-15-g1dd8971-android.apk
pero no funciono...sigo sin poder ingresar a la app que quiero ver en genymotion y zap

### Screenshots

![OWASP ZAP-Genymotion](https://user-images.githubusercontent.com/109567127/179657882-fa2ad27d-0b81-4c56-8af6-4229c11c6676.jpg)

### Additional context

No se si es por acá el reporte, pido excusas de antemano.

### Would you like to help fix this issue?

- [X] Yes

**Comment by KT518** [comment]
es OAuth 2

**Comment by thc202** [comment]
These type of questions are better for the OWASP ZAP User Group: https://groups.google.com/group/zaproxy-users
