### ISSUE TITLE
Zap WebSwing does not start in owasp/zap2docker-stable:2.11.1

### ISSUE THREAD

**Issue by JWebDev** [zaproxy/zaproxy#7391]
### Describe the bug

```
zap@21508e4fa06a:/zap$ ./zap-webswing.sh
xvfb-run: error: Xvfb failed to start
```

### Steps to reproduce the behavior

just start script in container
```
zap@21508e4fa06a:/zap$ ./zap-webswing.sh
xvfb-run: error: Xvfb failed to start
```

### Expected behavior

Zap WebSwing will start in owasp/zap2docker-stable:2.11.1

### Software versions

owasp/zap2docker-stable:2.11.1

### Errors from the zap.log file

`xvfb-run: error: Xvfb failed to start`

### Would you like to help fix this issue?

- [ ] Yes

**Comment by psiinon** [comment]
How are you starting your docker container?
I followed the instructions on https://www.zaproxy.org/docs/docker/webswing/ and it worked fine for me, ie

- `docker run -u zap -p 8080:8080 -p 8090:8090 -i owasp/zap2docker-stable zap-webswing.sh`

**Comment by psiinon** [comment]
I've also just started a bash shell in docker using:

- docker run -u zap -p 8080:8080 -p 8090:8090 -i -t owasp/zap2docker-stable bash

And then starting webswing using:

- ./zap-webswing.sh

That also worked fine for me.
This is on a MacBook. What OS are you using?

**Comment by JWebDev** [comment]
Hi @psiinon ,
Thanks for the answer.

I'm starting container with docker-compose but container itself with entrypoint. 
I am using Windows.
But with the previous version everything worked(Webswing) for me.

Dockerfile
```
FROM owasp/zap2docker-stable:2.11.1

#EXPOSE 9988 #ZapAPI
#EXPOSE 9977 #zapwebswing

ENV HOSTNAME="owasp-agent"
ENV ZAP_PORT=9988
ENV ZAP_WEBSWING_OPTS="-host 0.0.0.0 -port $ZAP_PORT"
ENV ZAP_API_KEY=WIe1SRD2345YLl

USER zap

RUN zap.sh -cmd -addoninstallall;\
    zap.sh -cmd -addonUpdate

USER root
RUN apt-get update && apt-get install -q -y software-properties-common traceroute iputils-tracepath procps iputils-ping net-tools nano tzdata vim less jq dos2unix

RUN chown zap:zap /owasp-agent;\
    chmod +x /owasp-agent/entrypoint.sh;\
    dos2unix /owasp-agent/entrypoint.sh

USER zap

ENTRYPOINT ["/owasp-agent/entrypoint.sh"]
```
entrypoint.sh
```
zap-webswing.sh &
zap.sh -daemon -host 0.0.0.0 -port $ZAP_PORT -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true -config api.key=$ZAP_API_KEY
tail -f /dev/null
```

**Comment by psiinon** [comment]
Sorry, we can only support our docker images, not ones created by yourself or other people.
WebSwing appears to be working fine in our docker images so I dont think this is a ZAP problem.
However we will be happy to give help and advice on the ZAP User Group - so please start a thread there: https://groups.google.com/group/zaproxy-users
