### ISSUE TITLE
Unable to build zap image from source - ZIP Bomb Error

### ISSUE THREAD

**Issue by ParthibanSG** [zaproxy/zaproxy#7393]
Hello,

I am customizing ZAP image for our internal use in our organization and I had to include ENV step in Dockerfile-weekly for setting proxy to download the webswing zip file. However, when I build the image, webswing extract is failing with zip bomb error. Could you please help to resolve it?

```
 => CACHED [builder 3/4] WORKDIR /zap                                                                              0.0s
 => ERROR [builder 4/4] RUN if [ -z "" ] ;  then curl -s -L  "https://dev.webswing.org/files/public/webswing-exa  39.2s
 => CANCELED [stage-1  2/19] RUN apt-get update && apt-get install -q -y --fix-missing  make  automake  autoconf  39.2s
------
 > [builder 4/4] RUN if [ -z "" ] ;     then curl -s -L  "https://dev.webswing.org/files/public/webswing-examples-eval-22.1.2-distribution.zip" > webswing.zip;         else curl -s -L  "-22.1.2-distribution.zip" > webswing.zip; fi &&      unzip webswing.zip &&    rm webswing.zip &&      mv webswing-* webswing &&       rm -Rf webswing/apps/:
#17 39.03 Archive:  webswing.zip
#17 39.03    creating: webswing-examples-eval-22.1.2/
#17 39.03    creating: webswing-examples-eval-22.1.2/admin/
#17 39.03   inflating: webswing-examples-eval-22.1.2/admin/admin.bat
#17 39.03 error: invalid zip file with overlapped components (possible zip bomb)
```

I tried with all three weekly releases from today... Issue is same in Windows 10 and Linux OS (RHEL7 and RHEL8)

Thanks

**Comment by psiinon** [comment]
Do you need WebSwing?
If not I'd remove it :)
If you do then try unzipping that file on the command line with different tools / options and see what works.

**Comment by ParthibanSG** [comment]
> Do you need WebSwing? If not I'd remove it :) If you do then try unzipping that file on the command line with different tools / options and see what works.

I tried with 7z, zip, JAR and it fails in all cases... Any other extract tool suggestions please? :)

**Comment by psiinon** [comment]
No - you could try asking WebSwing - its their zip.
Or you could pay them for a full license...

**Comment by thc202** [comment]
The Webswing was updated to the latest version available, you should contact them if the error persists.
