### ISSUE TITLE
Set environement variable for automation using command line.

### ISSUE THREAD

**Issue by malylemire1** [zaproxy/zaproxy#7396]
### Is your feature request related to a problem? Please describe.

I cannot use docker.

### Describe the solution you'd like

zap.bat -cmd -autorun scan.yaml -e variablename=value

### Describe alternatives you've considered

Using docker.

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment]
That's being passed to ZAP, try setting it before `zap.bat`.

**Comment by kingthorin** [comment]
Please don't ask questions as issues - the [ZAP User Group]( https://groups.google.com/group/zaproxy-users) is a much better place for questions.

**Comment by malylemire1** [comment]
Sorry I talk about Automation environment variables inside the yaml file.
---
env:
  vars:

**Comment by psiinon** [comment]
Same answer - ask on the [User Group](https://groups.google.com/group/zaproxy-users) :)
