### ISSUE TITLE
Rest API to accept input to manual Request Editor

### ISSUE THREAD

**Issue by dflickema-r7** [zaproxy/zaproxy#7399]
Is there an input API method for interacting with the manual request editor?  There's a feature in the Burp API where I can send a request to the "sender" or replay functionality from outside Burp itself.

**Comment by thc202** [comment]
There's `sendRequest` (https://www.zaproxy.org/docs/api/) which allows to send manually crafted requests (which can then be opened from within ZAP), but there's no API method to show the Manual Request Editor.

**Comment by thc202** [comment]
The OWASP ZAP User Group is a better place to ask usage questions though: https://groups.google.com/group/zaproxy-users
