### ISSUE TITLE
ascan disableAllScanners API endpoint no longer disabled all scanners

### ISSUE THREAD

**Issue by craigmarksmith** [zaproxy/zaproxy#7400]
### Describe the bug

As of ZAP `w2022-03-07`, using the API endpoint `ascan/action/disableAllScanners/` with a policy file no longer disabled scanners that are identified in that policy file as enabled.

### Steps to reproduce the behavior

The issue is best demonstrated using the following scripts.

Create a file named `test.py`
```py
import time
from subprocess import Popen

from zapv2 import ZAPv2 as ZAP

def print_totals(json):
  totals = {
    'enabled': 0,
    'disabled': 0,
  }

  for scanner in json['scanners']:
    if scanner['enabled'] == 'true':
      totals['enabled'] = totals['enabled'] + 1
    else:
      totals['disabled'] = totals['disabled'] + 1
  
  print(totals)

port = '42248'

settings = [
  '/zap/zap.sh', '-daemon',
  '-config', 'network.localServers.mainProxy.address=0.0.0.0',
  '-config', f'network.localServers.mainProxy.port={port}',
  '-dir', '/home/zap',
  '-config', 'api.disablekey=true',
  '-config', 'api.addrs.addr.name=.*',
  '-config', 'api.addrs.addr.regex=true',
  '-silent'
]

connection_details = {'http': f'http://127.0.0.1:{port}', 'https': f'http://127.0.0.1:{port}'}

p = Popen(settings)
print('sleeping...')
time.sleep(10)
print('done')
print('ZAP should be running')

zap = ZAP(proxies=connection_details)

policy_name = 'API-Minimal'

url = zap.base + 'ascan/view/scanners'
before_response = zap._request(url, {'scanPolicyName': policy_name, 'apikey': ''})
print_totals(before_response)
zap.ascan.disable_all_scanners(policy_name)
after_response = zap._request(url, {'scanPolicyName': policy_name, 'apikey': ''})
print_totals(after_response)
```

create a bash script `run.sh` with the contents

```sh
#!/bin/bash

docker run -d -it --name zap-test owasp/zap2docker-weekly:w2022-07-25
docker cp test.py zap-test:/zap
docker exec -it zap-test mkdir /home/zap/policies
docker exec -it zap-test cp /home/zap/.ZAP_D/policies/API-Minimal.policy /home/zap/policies
docker exec -it zap-test python /zap/test.py
docker kill zap-test
```

Make the script executable, `chmod 755 run.sh`

Run the script.

The script will 

- start the ZAP docker container
- copy the test python script to it
- move the API policy to the expected policy location
- run the python script (which will...)
  - start ZAP
  - query the API to get all the scanners for the API policy, then count the number of enabled and disabled scanner
  - call ascan `disabledAllScanners` with the API policy
  - query the API to get all the scanners for the API policy, then count the number of enabled and disabled scanner
- kill the container

The output I've experienced is:
```
{'enabled': 25, 'disabled': 36}
{'enabled': 16, 'disabled': 45}
```

### Expected behavior

All the scanners for the policy should be disabled. On versions of ZAP before `w2022-03-07`, the output of the above script is:

```
{'enabled': 25, 'disabled': 36}
{'enabled': 0, 'disabled': 61}
```

### Software versions

since w2022-03-07

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment]
Unrelated to the issue, you can use `-host` and `-port` instead of the `mainProxy` configs.

**Comment by craigmarksmith** [comment]
Thank you @thc202 for picking this up and dealing with it so quickly! And thank you for the [tip](https://github.com/zaproxy/zaproxy/issues/7400#issuecomment-1203945540), I tried it and it worked perfectly. 🙇
