### ISSUE TITLE
Automatic scanning

### ISSUE THREAD

**Issue by gzhankh** [zaproxy/zaproxy#7415]
### Is your feature request related to a problem? Please describe.

In the process of using it, I found that automatic scanning could not scan out all the resources or requests of the website. I wonder if there is a function that can configure some fixed requests so that the crawler can climb the resources of the website through these requests

### Describe the solution you'd like

Maybe I mean, I can configure some requests, and then ZAP can follow my configuration to crawl the site or attack the site

### Describe alternatives you've considered

I used forced browsing, but I don't think the effect is ideal.

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment]
There's a job to send custom requests: https://www.zaproxy.org/docs/desktop/addons/automation-framework/job-requestor/

Note that usage questions are better for the OWASP ZAP User Group: https://groups.google.com/group/zaproxy-users
