### ISSUE TITLE
Import default context behavior is painful

### ISSUE THREAD

**Issue by jsoref** [zaproxy/zaproxy#7421]
### Describe the bug

I had a session, and I liked its context, so I saved it. I created a new session and tried to import the default context. I got an error.

### Steps to reproduce the behavior

1. Have an existing session (from a long time ago)
2. File>Open Session...
3. File>Export context
4. Save
5. File>New session
6. File>Import Context...
7. Select the context
8. Click OK

### Expected behavior

If there's a conflict with an existing context name, it could:
* offer to replace the context
* offer to rename the context
* suggest how to delete the existing conflicting context

### Software versions

2.11.1

### Screenshots

![image](https://user-images.githubusercontent.com/2119212/184708501-389a44ca-c54f-4b0a-9783-4fcff7f725c5.png)

Note that it doesn't even tell me the name of the existing context (if a dialog is going to show something like this, it should at least provide that information...)

### Would you like to help fix this issue?

- [ ] Yes

**Comment by psiinon** [comment]
All good suggestions 😄
