### ISSUE TITLE
`File`>`Persist Session...` should be disabled with open session

### ISSUE THREAD

**Issue by jsoref** [zaproxy/zaproxy#7423]
### Describe the bug

If one creates a session and selects the option to persist (I can't recall what it's called) then the persist option does nothing remotely useful.

### Steps to reproduce the behavior

1. Create a default session (that will save its stuff)
2. Use `File`>`Persist Session...`

### Expected behavior

* It should not be possible to get a dialog saying "you can't do this"
* The menu item should not be enabled if it won't function

### Software versions

2.11.1

### Path
<img width="291" alt="image" src="https://user-images.githubusercontent.com/2119212/184914447-3a1c0bb2-50a6-447b-b5ad-39399b4475d8.png">

<img width="434" alt="image" src="https://user-images.githubusercontent.com/2119212/184914344-4bcf9be8-d346-4fcd-ab3f-54f6572368d3.png">

### Disabled menus
<img width="252" alt="image" src="https://user-images.githubusercontent.com/2119212/184914479-a17d64a1-17ea-4994-a455-ed383b674059.png">

<img width="292" alt="image" src="https://user-images.githubusercontent.com/2119212/184914404-725479f0-60b4-447a-9c9d-4df2bb6394f9.png">

### Would you like to help fix this issue?

- [ ] Yes

**Comment by kingthorin** [comment]
Related: https://github.com/zaproxy/zaproxy/pull/6984

**Comment by thc202** [comment]
This is a regression, it was working that way in previous versions.

**Comment by thc202** [comment]
Caused by #5873.

**Comment by kingthorin** [comment]
@thc202 If you’ve already figured out what’s needed here feel free to PR it. I haven’t even looked. I just saw this while perusing issues the other day and figured it should be tackled for 2.12.

**Comment by thc202** [comment]
OK.
