### ISSUE TITLE
Not detecting response code as possible SQL Injection

### ISSUE THREAD

**Issue by MayurVirkar** [zaproxy/zaproxy#7425]
### Describe the bug

If an endpoint is crashing with 500 with a particular payload, such as ' or ? It should be flagged as a possible SQL injection endpoint

### Steps to reproduce the behavior

Run a scanner on an endpoint that has blind SQL injection vulnerability

### Expected behavior

To detect 500 as a possible SQL injection endpoint

### Software versions

2.1.1

### Would you like to help fix this issue?

- [ ] Yes

**Comment by kingthorin** [comment]
Please be much more specific.

**Comment by kingthorin** [comment]
Closing, Insufficient Evidence to action.
