### ISSUE TITLE
Enable the Alert_on_HTTP_Response_Code_Errors on zap-full-scan.py

### ISSUE THREAD

**Issue by hideintheclouds** [zaproxy/zaproxy#7426]
### Is your feature request related to a problem? Please describe.

The zap-api-scan.py script from the docker image loads and enables a httpsender .js script to report alerts for 4XX and 5XX HTTP Status codes.
https://github.com/zaproxy/zaproxy/blob/82bbffd6c6c4a95bb882eafef950e31617fbce6f/docker/zap-api-scan.py#L400

https://github.com/zaproxy/zaproxy/blob/82bbffd6c6c4a95bb882eafef950e31617fbce6f/docker/zap-api-scan.py#L369

I believe that showing 5XX server errors in the report could also be useful when scanning a web application, so the owners could make the application more robust by handling some of the reported 5XX.

### Describe the solution you'd like

Load & Enable the Alert_on_HTTP_Response_Code_Errors.js in the zap-full-scan.py script provided with the ZAP docker image

### Describe alternatives you've considered

Create a hook to enable&load the httpsender js script

### Would you like to help fix this issue?

- [ ] Yes

**Comment by psiinon** [comment]
I can see why this would be useful ... but I'm afraid I dont think we should implement it in the full scan.
I dont think everyone would want this which would mean yet another command line option, and we've already got lots of those.
My recommendation is to use the [Automation Framework](https://www.zaproxy.org/docs/automate/automation-framework/) - we are migrating the packaged scans to use this under the covers anyway.
Will that work for you now or are you using some of the fullscan options that the AF doesnt currently support?
