### ISSUE TITLE
param miner: "Chunk SIze" seems misleading

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#7427]
### Describe the bug

In the Param Miner add-on the "Chunk Size" doesn't really control the size of the chunks, but more the number of chunks.

### Steps to reproduce the behavior

1. Run ZAP w/ Param Miner installed.
2. Proxy a resource you want to param mine.
3. Start Param Miner, look at the "URL Guess" tab.
4. Note the default "Chunk Size" is two.
5. Run Param Miner.
6. Note that it divides the list in two versus sending requests with two "params".

### Expected behavior

The behavior is fine but perhaps the UI element could/should be renamed?

"Chunk Size" -> "Number of Chunks" ?

### Software versions

OWASP ZAP
Version: Dev Build

Installed Add-ons: [... [id=paramminer, version=0.0.1] ...]

Operating System: Windows 10
Architecture: amd64
Java Version: Eclipse Adoptium 11.0.16
System's Locale: en_US
Display Locale: en_GB
Format Locale: en_US
Default Charset: UTF-8
ZAP Home Directory: C:\Users\thorin\OWASP ZAP_D\
ZAP Installation Directory: C:\Users\thorin\Desktop\zap-ws\zaproxy\zap\src\main\dist\.\
Look and Feel: FlatLaf Dark (com.formdev.flatlaf.FlatDarkLaf)

### Screenshots

As you can see here 'Chunk Size' 2, means divide the list in 2, not use 2 items in each chunk.
![image](https://user-images.githubusercontent.com/7570458/185399073-467102a5-7491-431a-819c-191ddddd5c8f.png)

### Errors from the zap.log file

None

### Additional context

Related to zaproxy/zaproxy#7140

### Would you like to help fix this issue?

- [ ] Yes

**Comment by ArkaprabhaChakraborty** [comment]
Damn! I really need to learn this skill of creating good issues :)
