### ISSUE TITLE
Incorrect classification Informational for Information Disclosure - Sensitive Information in URL

### ISSUE THREAD

**Issue by globeone** [zaproxy/zaproxy#7428]
### Describe the bug

The Information Disclosure - Sensitive Information in URL is currently classified as Informational. Please change this classification to default Medium or High as this check actually shows that user enumeration is possible. We had two cases where it was possible to change the userID in the URL to someone else to see their data, that we ignored as the alert was only Informational. This is clearly a real world vulnerability and not Informational, so needs a higher classification to make it stand out more. Especially in high workload environments where the high and mediums are taken care of first.

### Steps to reproduce the behavior

- Scan an application where the userID is used in the URL to create the page in a GET request
- The Passive rule Information Disclosure - Sensitive Information in the URL will flag as Informational
- go to Alerts
- Observer that the alert is indeed Informational
- click tediously each alert one by one to change to Medium or High
- (yes I know, I need to open a new feature request to be able to move a group of vulnerable items to a different severity in one click)

### Expected behavior

The classification should fit the strength of the vulnerability. As this check is very effective it should be Medium or High. 

### Software versions

OWASP ZAP
Version: D-2022-08-15

Installed Add-ons: [[id=accessControl, version=8.0.0],
[id=alertFilters, version=14.0.0], [id=ascanrules,
version=47.0.0], [id=ascanrulesAlpha, version=38.0.0],
[id=ascanrulesBeta, version=42.0.0],
[id=attacksurfacedetector, version=1.1.4], [id=authstats,
version=2.0.0], [id=automation, version=0.17.0],
[id=bruteforce, version=12.0.0], [id=callhome,
version=0.5.0], [id=commonlib, version=1.10.0],
[id=coreLang, version=16.0.0], [id=custompayloads,
version=0.11.0], [id=diff, version=12.0.0],
[id=directorylistv1, version=6.0.0], [id=directorylistv2_3,
version=4.0.0], [id=directorylistv2_3_lc, version=4.0.0],
[id=domxss, version=14.0.0], [id=encoder, version=0.7.0],
[id=exim, version=0.3.0], [id=fileupload, version=1.1.0],
[id=formhandler, version=6.0.0], [id=fuzz, version=13.7.0],
[id=gettingStarted, version=14.0.0], [id=graaljs,
version=0.3.0], [id=graphql, version=0.10.0], [id=help,
version=15.0.0], [id=hud, version=0.14.0],
[id=imagelocationscanner, version=3.0.0], [id=invoke,
version=12.0.0], [id=jsonview, version=2.0.0], [id=network,
version=0.3.0], [id=oast, version=0.11.0], [id=onlineMenu,
version=10.0.0], [id=openapi, version=28.0.0],
[id=plugnhack, version=13.0.0], [id=portscan,
version=10.0.0], [id=pscanrules, version=43.0.0],
[id=pscanrulesAlpha, version=35.0.0], [id=pscanrulesBeta,
version=30.0.0], [id=quickstart, version=34.0.0],
[id=reflect, version=0.0.11], [id=regextester,
version=2.0.0], [id=replacer, version=10.0.0], [id=reports,
version=0.16.0], [id=requester, version=7.0.0], [id=retest,
version=0.3.0], [id=retire, version=0.15.0], [id=reveal,
version=5.0.0], [id=revisit, version=4.0.0], [id=scripts,
version=31.0.0], [id=selenium, version=15.10.0],
[id=sequence, version=7.0.0], [id=soap, version=14.0.0],
[id=spiderAjax, version=23.9.0], [id=sqliplugin,
version=15.0.0], [id=tips, version=10.0.0], [id=tokengen,
version=15.0.0], [id=treetools, version=8.0.0],
[id=wappalyzer, version=21.12.0], [id=webdriverlinux,
version=43.0.0], [id=webdrivermacos, version=44.0.0],
[id=webdriverwindows, version=43.0.0], [id=websocket,
version=27.0.0], [id=zest, version=36.0.0]]

Operating System: Windows 10
Architecture: amd64
Java Version: Eclipse Adoptium 17.0.4
System's Locale: en_US
Display Locale: en_GB
Format Locale: en_US
Default Charset: windows-1252
ZAP Home Directory: C:\Users\$USER\OWASP ZAP_D\
ZAP Installation Directory: C:\Users\$USER\LocalPrograms\ZAPWeekly\ZAP_D-2022-08-15\.\
Look and Feel: FlatLaf Light (com.formdev.flatlaf.FlatLightLaf)

### Screenshots

![image](https://user-images.githubusercontent.com/10052587/185588706-61e4a0f9-14b6-491e-9ff4-8f905c8c8529.png)

### Errors from the zap.log file

Zap Log is irrelevant for this case as it's just classification of a vulnerability.

### Additional context

If it's as easy as just changing a label in the sourcecode, please just point me to the right place and I'll put in a pull request.

### Would you like to help fix this issue?

- [X] Yes

**Comment by thc202** [comment]
Please, check zaproxy/zap-extensions#3743.

**Comment by thc202** [comment]
The scan rule can't tell if there's any issue or not.

**Comment by thc202** [comment]
As for the other comment, there's already #1603.

**Comment by kingthorin** [comment]
If you can suggest some logic to differentiate an IDOR from a random/un-interesting param value please let us know.

**Comment by globeone** [comment]
Observing the current check over several scans, it's already pretty darn accurate at only showing interesting parameters and values. This is why I want to increase it's importance as it would be better to filter false positives than miss the true positives.

The most important findings are the ones with the **userid=** parameter put together with a **GET request** and an **integer value**. These are the easiest for a opportunistic hacker to try. 

**userid=ABCD1234**

For email address logins as well it would be nice to have a heads up from ZAP "This field is potentially fuzzable". Then one could choose to, time permitting to supply ZAP with a Fuzzing list of e-mail addresses to test with. Or ZAP could spot test with common names e.g. john.smith@email.domain

**username=lastname.firstname@email.domain**

things like a login token (which are also flagged by the current check) would be harder to crack but are still relevant for someone performing web security scans to heads up to the developers.

loginToken={SHA256 HASH}

In the end though, as someone performing web security scans every day, the most helpful would be just to increase the severity as the check already works very well as designed.

**Comment by kingthorin** [comment]
Any field is fuzzable (no "potential" about it).

`loginToken={SHA256 HASH}` already exists if you've configured authentication for the app. https://www.zaproxy.org/docs/alerts/10057/ I guess that could be extended to look for plain text occurrences, however they'd probably still be alerted low or info because it is unsurprising to find a user's username used within an app.

You seem to have some specific user cases for your apps, where assumptions workout, I'd suggest scripting some scan rules for your org. You could also contribute them back to the [community](https://github.com/zaproxy/community-scripts/).

**Comment by globeone** [comment]
"the most helpful would be just to increase the severity as the check already works very well as designed."

Why would I make a completely new scan rule when the current one works perfectly fine, but just is flagged too low severity? 

I'm really confused. Are you saying that you don't have any faith in the functioning of the current Information Disclosure - Sensitive Information in URL rule, and that we just 'got lucky'?

**Comment by globeone** [comment]
Now I'm really curious as to the counter argument to leaving the Information Disclosure - Sensitive Information in URL at Informational.

**Comment by kingthorin** [comment]
I should have thought of this earlier.

You can just use an Alert Filter to increase the Severity/Risk for your usage (you can even apply Alert Filters after the fact).

https://www.zaproxy.org/docs/desktop/addons/alert-filters/

**Comment by kingthorin** [comment]
> I'm really confused. Are you saying that you don't have any faith in the functioning of the current Information Disclosure - Sensitive Information in URL rule, and that we just 'got lucky'?

No, I'm sure it works as intended. However, I don't think your experience/idea is universally applicable. Plus we haven't discussed the actual alert details, I'm sure it alerted on email addresses but as far as I know it shouldn't simply alert on alphanumeric strings (userid IDOR as suggested in your earlier response `userid=ABCD1234`.)

**Comment by globeone** [comment]
Global Alert Filters is great! Documentation on  Global Alert Filters is lacking, hence not being able to find them or use them effectively, will see if there is time to do a pull request on the documentation this weekend.

I can't prove the case without disclosing the actual vulnerability so am closing the ticket as - Using Global Alert Filters is the recommended solution.

**Comment by kingthorin** [comment]
Thanks @globeone
