### ISSUE TITLE
Invalid session path causes ZAP to fail to start

### ISSUE THREAD

**Issue by AS22222** [zaproxy/zaproxy#7436]
### Describe the bug

Failed to start ZAP
 

Message:
    java.lang.reflect.InvocationTargetException
Level:
    SEVERE
Stack Trace:
null
    java.awt.EventQueue.invokeAndWait(Unknown Source)
    java.awt.EventQueue.invokeAndWait(Unknown Source)
    org.zaproxy.zap.GuiBootstrap.initControlAndPostViewInit(GuiBootstrap.java:226)
    org.zaproxy.zap.GuiBootstrap.access$100(GuiBootstrap.java:64)
    org.zaproxy.zap.GuiBootstrap$2.run(GuiBootstrap.java:175)
    java.lang.Thread.run(Unknown Source)
Illegal char :> at index 2: /C:/Users/Arpit.Singh/OWASP.session
    sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
    sun.nio.fs.WindowsPathParser.parse(Unknown Source)
    sun.nio.fs.WindowsPathParser.parse(Unknown Source)
    sun.nio.fs.WindowsPath.parse(Unknown Source)
    sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
    java.nio.file.Paths.get(Unknown Source)
    org.zaproxy.zap.model.SessionUtils.getSessionPath(SessionUtils.java:39)
    org.zaproxy.zap.GuiBootstrap$3.run(GuiBootstrap.java:246)
    java.awt.event.InvocationEvent.dispatch(Unknown Source)
    java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    java.awt.EventQueue.access$500(Unknown Source)
    java.awt.EventQueue$3.run(Unknown Source)
    java.awt.EventQueue$3.run(Unknown Source)
    java.security.AccessController.doPrivileged(Native Method)
    java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    java.awt.EventQueue.dispatchEvent(Unknown Source)
    java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    java.awt.EventDispatchThread.run(Unknown Source)

### Steps to reproduce the behavior

1. Go to cmd
2. Run the following in windows cmd prompt: zap.bat -session /path/to/sessions  -script /complete/path/script.js
3. Run

### Expected behavior

It should run without error

### Software versions

2.11.1

### Screenshots

![image](https://user-images.githubusercontent.com/112489582/187444924-61db7a61-0732-452e-a1d6-763ac6f197a6.png)

### Would you like to help fix this issue?

- [X] Yes

**Comment by psiinon** [comment]
@AS22222 the user group is a better forum for these sorts of questions, and I've replied to your thread: https://groups.google.com/g/zaproxy-users/c/QNP3IhDQXgo/m/XJHlNUxjAQAJ
