### ISSUE TITLE
StrictTransportSecurityScanRule code appears to be doing case-sensitive header search

### ISSUE THREAD

**Issue by thetumper** [zaproxy/zaproxy#7437]
### Describe the bug

My ZAP scan contained the STS issue for not having the associated header on the response, as needed:

https://www.zaproxy.org/docs/alerts/10035/

We are on a node.js platform, with the helmet library used to add the essential security headers.  The node handling for headers is to lowercase them, in order to make all case variations uniform:

https://nodejs.org/es/docs/guides/anatomy-of-an-http-transaction/#method-url-and-headers

That puts the onus on other tooling to be doing case insensitive searches/looks for header names.

I confirmed that I can see the header on the response (please see attached screenshot of logged response headers).  But based on the code link in the OWASP issue, it looks like the header name is being searched for in a case-sensitive way:

https://github.com/zaproxy/zap-extensions/blob/main/addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/StrictTransportSecurityScanRule.java

Please see lines 51 and 107+.

### Steps to reproduce the behavior

1. Run the ZAP scan on a node.js based API, with the STS header being set.
2. Seemingly, node will return the header name in all lower-case.
3. ZAP STS check will not match it, and raises the issue 10035.

### Expected behavior

Expected the STS check to successfully find the header, even with the name represented as "strict-transport-security" (vs. "Strict-Transport-Security".

### Software versions

Running on node.js 14.20.0, helmet 6.0.0.

### Screenshots

<img width="1101" alt="response_headers" src="https://user-images.githubusercontent.com/37218954/187708256-a03af3aa-23b1-49f5-8975-61a80a601678.png">

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment]
Could you provide the HTTP response header associated with the alert?

**Comment by kingthorin** [comment]
You can see here the call that is used on 107 uses a normalized name: https://github.com/zaproxy/zaproxy/blob/33328d36c11b95a1c2574d79a43849571e4d27ff/zap/src/main/java/org/parosproxy/paros/network/HttpHeader.java

**Comment by kingthorin** [comment]
As @thc202 said, we need to see the HTTP Response actually associated with the alert because that's what ZAP analyzed and alerted on. (ZAP doesn't see or care about your config.)

**Comment by thetumper** [comment]
My apologies.  I found the response logs from the scan, and see this:

WARN-NEW: Strict-Transport-Security Header Not Set [10035] x 4 
	https://mysubdomain.host.com/v2/ops (403 Forbidden)
	https://mysubdomain.host.com/v2/ping (403 Forbidden)
	https://mysubdomain.host.com/v2/ping (403 Forbidden)
	https://mysubdomain.host.com/v2/ops (403 Forbidden)
FAIL-NEW: 0	FAIL-INPROG: 0	WARN-NEW: 1	WARN-INPROG: 0	INFO: 0	IGNORE: 0	PASS: 113

It looks like the URLs are missing a base path.  Those should look like:

https://mysubdomain.host.com/api/v2/ops

I will see about configuring the scan parameters to correctly use the base path; I expected it to be picked up from the swagger file, but we have it represented in that as relative server url, not as a base path or part of each route's path.
