### ISSUE TITLE
Allow to filter alerts based on alert ref

### ISSUE THREAD

**Issue by JoeAdamski** [zaproxy/zaproxy#7438]
For CSP we have the following vulnerabilities specified.

|Reported Rule ID | CSP-ID | Rule description
-|-|-
10055|[10055](https://www.zaproxy.org/docs/alerts/10055)| CSP
10055|[10055-1](https://www.zaproxy.org/docs/alerts/10055-1)| CSP: X-Content-Security-Policy
10055|[10055-2](https://www.zaproxy.org/docs/alerts/10055-2)| CSP: X-WebKit-CSP
10055|[10055-3](https://www.zaproxy.org/docs/alerts/10055-3)| CSP: Notices
10055|[10055-4](https://www.zaproxy.org/docs/alerts/10055-4)| CSP: Wildcard Directive
10055|[10055-5](https://www.zaproxy.org/docs/alerts/10055-5)| CSP: script-src unsafe-inline
10055|[10055-6](https://www.zaproxy.org/docs/alerts/10055-6)| CSP: style-src unsafe-inline
10055|[10055-7](https://www.zaproxy.org/docs/alerts/10055-7)| CSP: script-src unsafe-hashes
10055|[10055-8](https://www.zaproxy.org/docs/alerts/10055-8)| CSP: style-src unsafe-hashes
10055|[10055-9](https://www.zaproxy.org/docs/alerts/10055-9)| CSP: Malformed Policy (Non-ASCII)

When I attempt to configure an alert filter I'm provided with the following options (where CSP is rule id 10055):

![image](https://user-images.githubusercontent.com/28110685/187752656-9bbc3e99-4b05-40d5-8d4d-f1363cdccb1b.png)

Currently, I cannot find a way to add a filter to one of the sub-rules because they all share Rule ID 10055 and provide no way for me to differentiate in the alert rules.

[ContentSecurityPolicyScanRule.java](https://github.com/zaproxy/zap-extensions/blob/main/addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ContentSecurityPolicyScanRule.java#L448)

Should these all have unique Rule ID's? Or maybe we could set the attack type here as `alertRef`? This might provide a way for users to define alert filters specific to each rule type.

**Comment by ricekot** [comment]
Alternatively, each alertRef could be a new entry in the Alert Type drop-down.

**Comment by kingthorin** [comment]
It seems that the filters display name but depend on the pluginId. I guess we could change that handling from int to string and use the example alerts for names/alertrefs (if getExampleAlerts doesn't return an empty list, otherwise just use the plugin name/ID.)

Thoughts? Feedback?

**Comment by JoeAdamski** [comment]
I see there are some other alerts that are grouped similar to CSP.
https://www.zaproxy.org/docs/alerts/


|Rule ID | Group
-|-
10020|Clickjack
10032|Viewstate
10055|CSP
20019 |External Redirect
40040|CORS
40043|Log4Shell
90004|Spectre Vuln

It would be nice if the solution could provide an avenue to resolve the issues these might have as well.

I'm curious why we grouped these like this while Cookies vulnerabilities all have their own unique Rule ID?

@kingthorin If we could migrate to use rule-id's with hyphens and include all the rules in the Alert Type pull down that would be great.

It seems like an "easy" approach might be too simply `setAttack(alertRef)`. Then users could filter based on the alertRef string. Or possibly setAttack with the appropriate rule id. Like `setAttack("10055-1")`. Then this would make it a CSP only solution.

**Comment by kingthorin** [comment]
> I'm curious why these are grouped these like this while Cookies vulnerabilities all have their own unique Rule ID?

Just depends how things were built.

> @kingthorin If we could migrate to use rule-id's with hyphens and include all the rules in the Alert Type pull down that would be great. I didn't check the type, but suspect its an integer.

Ya that's what I was suggesting :grinning:

**Comment by thc202** [comment]
I unassigned myself from this issue. I was thinking on adding a separate text field for the alert ref (though the current refs follow the `-integer` scheme it's a free text string).

I'm not sure about adding refs to the alert type and use examples, that prevents the configuration of rules and refs not currently present in ZAP (unless you make the combo box editable).

**Comment by kingthorin** [comment]
Well if we did it as a text field and checkbox like others then it would allow different batching/grouping with regex which might be easier? Or a separate multi-select combo?

I dunno there are lots of options. I'm just not sure what's best.

**Comment by 3XC1T3D** [comment]
We also would like to filter on Alert Refs. A separate multi-select combo would be nice or somthing. In our case we are using the owasp automation tooling and it would be nice, if we could subfilter in the automation yaml on alert refs.

For example you choose CSP and after that nothing or a specific Alert ref like CSP: script-src unsafe-inline or the id 10055-5.

Is there an ETA when it will be possible? 😅

**Comment by 3XC1T3D** [comment]
Hi,

would it be possible in the first step that we have the ability to configure it throught the automation framework and afterwards through the owasp Desktop Tool? :sweat_smile: 

best regards and thank you for your effort

**Comment by david-modica-thomas** [comment]
What needs doing for this one? 

Being able to filter on the hyphenated value ( Rule ID, Alert ID, Alert Ref?) somehow would be useful. 

At the moment, for example if you want to mark a CSP rule, such as `10055-4 | CSP: Wildcard Directive` as `False Positive`, it will then apply to and filter out _all_ CSP issues detected.

Subscribing.

**Comment by kingthorin** [comment]
Seems like this is held up with UI debate. If you could read the comments and add your thoughts that might help get it moved along.

**Comment by david-thomas-2023** [comment]
For my part, I'm using the automation framework, so would just like some way to be more specific in an `alertFilter` job such as

```
- type: alertFilter                  
  alertFilters:
    - ruleId: 10055
      alertRef: 10055-4
      newRisk: "False Positive"
```

I guess that would mean 

1. adding a new field for the string type alert reference with the option to filter on that, e.g `alertRef` or `alertId`

Alternatively, 

2. if the ruleId itself could support the string value such as `10055-4` and show that level of detail in the UI dropdown with the label there, that would be good. However, I imagine it may be difficult to refactor that `ruleId` field/type and the new field could be simplest. 

Ultimately, just looking for a reasonable way to be more specific with the `alertFilter` sub-type.

**Comment by thc202** [comment]
It's not being held, it's just that the changes are not finished yet, will move this up.
