### ISSUE TITLE
Manual Request Editor - Add Content-Type when switching to POST

### ISSUE THREAD

**Issue by Leyart** [zaproxy/zaproxy#7440]
### Is your feature request related to a problem? Please describe.

Opening a GET request with the request editor and switching the method with the dropdown from GET to POST moves the query parameters to the request body but it is not adding the correct content-type header, making the call silently fail.

### Describe the solution you'd like

As in BURP, when switching HTTP methods via Dropdown from GET to POST, the Content-Type: application/x-www-form-url-encoded should be added

### Describe alternatives you've considered

That seems to be the simplest solution to me. We could even specify how to convert the content to be sent in the body, but would make the flow clumsy

### Would you like to help fix this issue?

- [X] Yes

**Comment by psiinon** [comment]
Sounds good to me 😁 @Leyart would you like this to be assigned to you?

**Comment by Leyart** [comment]
Yes please, made me waste quite some time during an assessment because I was naturally expecting this to happen, I am now pissed at myself enough to fix it for good as soon as I have time
