### ISSUE TITLE
Zap can not detect the vulnerability when the login is in plain text

### ISSUE THREAD

**Issue by guglielmo84** [zaproxy/zaproxy#7444]
If a site uses HTTP and basic authentication, this is a security problem. 
Passwords are managed in plain text. 
This is vulnerable to a man in-middle attack. 
Zap can not detect this vulnerability.

**Comment by guglielmo84** [comment]
URL TEST: 
http://deprecated-nexus.regione.toscana.it/nexus/

OSWAP ZAP 2.11.1

**Comment by kingthorin** [comment]
Have you actually logged in while proxying through ZAP?

**Comment by guglielmo84** [comment]
The scan is without authentication

TEST URL:
http://deprecated-nexus.regione.toscana.it/nexus/ (IP: 159.213.235.254)

**Comment by kingthorin** [comment]
Then the issue won’t be identified because ZAP never encounters the condition.
