### ISSUE TITLE
Zap Unresponsive or Crashes entirely with High CPU and Memory Utilization When Selecting Alerts, Can't Export Session

### ISSUE THREAD

**Issue by adamzg** [zaproxy/zaproxy#7447]
Installation - Kali on Windows Hyper-V, 
![kali-hyper-v](https://user-images.githubusercontent.com/1001471/188737215-a9f90f9f-68dd-4e05-9064-3af5c6bdec75.png)

Zap (uninstalled using apt and then reinstalled) after experiencing same issue being reported here.

> ┌──(root㉿kali)-[/home/adam]
> └─# apt-get remove --purge zaproxy
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> The following packages will be REMOVED:
>   zaproxy*
> 0 upgraded, 0 newly installed, 1 to remove and 1572 not upgraded.
> After this operation, 232 MB disk space will be freed.
> Do you want to continue? [Y/n] Y
> (Reading database ... 398810 files and directories currently installed.)
> Removing zaproxy (2.11.1-0kali1) ...
> Processing triggers for kali-menu (2022.2.0) ...
>                                                                                                                                                 
> ┌──(root㉿kali)-[/home/adam]
> └─# apt-get install zaproxy       
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> The following NEW packages will be installed:
>   zaproxy
> 0 upgraded, 1 newly installed, 0 to remove and 1572 not upgraded.
> Need to get 185 MB of archives.
> After this operation, 232 MB of additional disk space will be used.
> Get:1 http://kali.download/kali kali-rolling/main amd64 zaproxy all 2.11.1-0kali1 [185 MB]
> Fetched 185 MB in 1min 34s (1,966 kB/s)                                                                                                        
> Selecting previously unselected package zaproxy.
> (Reading database ... 398578 files and directories currently installed.)
> Preparing to unpack .../zaproxy_2.11.1-0kali1_all.deb ...
> Unpacking zaproxy (2.11.1-0kali1) ...
> Setting up zaproxy (2.11.1-0kali1) ...
> Processing triggers for kali-menu (2022.2.0) ...
>                                                                                                                                                 
> ┌──(root㉿kali)-[/home/adam]
> └─# apt update zaproxy   

Import a context that includes the user to be forced and the user credentials...
![zap-issue-context](https://user-images.githubusercontent.com/1001471/188738337-74025b4b-0355-40ae-a87d-ac3c1e0e1c08.png)
Use a forced user and login.  In this test case SSO through KeyCloak is involved, but probably not related.

Attack a website using the "Attack..." or use the quick start menu and pick a random starting point in the app., doesn't seem to matter.

Allow the scan to complete
Attempt to review the Alerts on the Alerts tab.
Click the first alert
Click the second alert
**Actual result** - application becomes unresponsive and CPU and memory usage spike to ~100% even if memory is increased (tried with both 1/4 allocated memory and 1/2 allocated memory with 4GB allocated to Hyper-V.  The more alerts the more unstable the program becomes.  This has resulted in many crashes.
**Expected Result** - Tree node should expand promptly to show contents of node.
![zap-problem-annotated](https://user-images.githubusercontent.com/1001471/188737161-7d26dfb6-3ebd-452a-bf65-bcec2f25bd82.png)
![zap-problem](https://user-images.githubusercontent.com/1001471/188737198-968985ae-5d1f-42c2-a8f0-7b36106aedca.png)
![zap-issue-part-2](https://user-images.githubusercontent.com/1001471/188737219-4d30d6e4-506e-4535-86d3-6bef9d4d4d3a.png)

Attempt to Snapshot the session
Actual result - displays error dialog "Error saving session snapshot"
Expected result - export session dialog box should appear

**Comment by kingthorin** [comment]
This is a known issue which we believe is fixed in the current weeklies please try one of those downloads/releases and let us know.

**Comment by thc202** [comment]
Ref #5791.

**Comment by thc202** [comment]
Closing as duplicate, feel free to reopen or leave a comment if you are able to reproduce the issue in a weekly release.

**Comment by adamzg** [comment]
@kingthorin thanks for the quick response.  I'm not able to validate the fix because I'm not authorized to run a non-prod release in my current engagement.  Would reducing the max. response size under the database settings be a possible workaround until the fix is released to production?

![zap-problem-database-size](https://user-images.githubusercontent.com/1001471/188907823-32489e83-8ec4-4e3f-8211-d2d7a4cd648d.png)

**Comment by kingthorin** [comment]
Not really, that'll just lead to things being truncated in the DB. There are other workarounds mentioned in the issue link thc202 provided. (Disable line wrap and syntax highlighting.)
