### ISSUE TITLE
Feature-Policy ➡️ Permissions-Policy

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#7458]
https://www.zaproxy.org/docs/alerts/10063/ Should be updated for the more recent variant. This should probably be handled similar to the older CSP header variants.

Reference:
- https://scotthelme.co.uk/goodbye-feature-policy-and-hello-permissions-policy/

**Comment by kingthorin** [comment]
Actually it looks like this may already be the case code wise. I’ll double check messages, help, alert refs, and example alerts.

https://github.com/zaproxy/zap-extensions/blob/main/addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/PermissionsPolicyScanRule.java

**Comment by thc202** [comment]
Ref zaproxy/zap-extensions#2940.
