### ISSUE TITLE
Zap-cli "Scan status command"

### ISSUE THREAD

**Issue by Michealpool** [zaproxy/zaproxy#7462]
### Is your feature request related to a problem? Please describe.

Hello team,

 i am using zap-cli , for the current running scan, i want to check the status in percentage but there is no zap-cli command available. Can you please add this feature in new version of docker image.  

### Describe the solution you'd like

i search alot but no solution available 

### Describe alternatives you've considered

don not know

### Would you like to help fix this issue?

- [x] Yes

**Comment by thc202** [comment]
That's a third party tool: https://github.com/Grunny/zap-cli

It's not clear which scan you are referring to, but the ZAP API provides scan progresses: https://www.zaproxy.org/docs/api/ (AJAX Spider does not though).

For further usage questions ask in the OWASP ZAP User group: https://groups.google.com/group/zaproxy-users

**Comment by Michealpool** [comment]
Thank you for your response. i am asking about active scan progress via zap-cli.

**Comment by psiinon** [comment]
Which is not supported by us 😁
