### ISSUE TITLE
Cannot Install Zap Version 2.11 

### ISSUE THREAD

**Issue by bhaveshraj336** [zaproxy/zaproxy#7467]
### Describe the bug

I am unable to install zap v11 in Windows 10 
also i can update zap from v9 

### Steps to reproduce the behavior

1.Double Click on Installer 
2. Nothing Works

### Expected behavior

Zap proxy is unable to install

### Software versions

v11

### Errors from the zap.log file

[zap.log](https://github.com/zaproxy/zaproxy/files/9598301/zap.log)

### Would you like to help fix this issue?

- [ ] Yes

**Comment by kingthorin** [comment]
Please be more specific than "can't", what happens when you try?

**Comment by kingthorin** [comment]
>  also i can update zap from v9

Perfect. So what's the issue?

**Comment by bhaveshraj336** [comment]
@kingthorin So when I tried to install  Zapv11 and Zapv10 directly using windows installer it couldn't install it 
But when I tried to install the v9 it installed successfully and also I can not update the version 9 it gives some error

**Comment by bhaveshraj336** [comment]
> an u

I can't update v9 (misspelled)

**Comment by kingthorin** [comment]
"couldn't" doesn't tell us anything, that we can provide advice on.

**Comment by bhaveshraj336** [comment]
> "couldn't" doesn't tell us anything that we can provide advice on.

![Screenshot (367)](https://user-images.githubusercontent.com/53301324/191008663-3eda5200-c2b8-4dcb-9b38-8638efbfb7fc.png)

it closes after this screen

**Comment by kingthorin** [comment]
> " The crash happened outside the Java Virtual Machine in native code."

Seems like a Chocolatey issue.

**Comment by bhaveshraj336** [comment]
> > "couldn't" doesn't tell us anything that we can provide advice on.
> 
> ![Screenshot (367)](https://user-images.githubusercontent.com/53301324/191008663-3eda5200-c2b8-4dcb-9b38-8638efbfb7fc.png)
> 
> it closes after this screen

and these one @kingthorin

**Comment by bhaveshraj336** [comment]
> > "couldn't" doesn't tell us anything that we can provide advice on.
> 
> ![Screenshot (367)](https://user-images.githubusercontent.com/53301324/191008663-3eda5200-c2b8-4dcb-9b38-8638efbfb7fc.png)
> 
> it closes after this screen

and these one @kingthorin

**Comment by kingthorin** [comment]
Did you mean to add a second screenshot?

**Comment by bhaveshraj336** [comment]
> Did you mean to add a second screenshot?

The installer don't continue after this screen
The screen closes itself after the progress bar gets to half

**Comment by thc202** [comment]
That's a JVM crash, try update Java to a newer version. There's nothing we can do from ZAP side.

**Comment by bhaveshraj336** [comment]
![image](https://user-images.githubusercontent.com/53301324/191011283-2ddec2a8-d6bd-48e4-98dd-d3fd9e141b64.png)

Java version is lastest

**Comment by bhaveshraj336** [comment]
![image](https://user-images.githubusercontent.com/53301324/191011344-a0de850f-fa9a-41d0-bf39-b89de0b1096b.png)

**Comment by kingthorin** [comment]
Apparently you have multiple JREs installed.
> Java VM: Java HotSpot(TM) 64-Bit Server VM (10.0.2+13, mixed mode, 

Goto a command prompt and type `java -version` then provide the output.

**Comment by bhaveshraj336** [comment]
@kingthorin @thc202 It got installed by downgrading the java to 1.8.202
![image](https://user-images.githubusercontent.com/53301324/191012186-ba6b1881-1337-448c-8bef-a4d79d449e2f.png)

**Comment by kingthorin** [comment]
Thanks for letting us know.
