### ISSUE TITLE
Automated Scan URL to attack column can't not type.

### ISSUE THREAD

**Issue by schedule6666** [zaproxy/zaproxy#7469]
To Whom It May Concern,

I am writing in reference to the URL to attack column has been blocked. 
![1663741319122](https://user-images.githubusercontent.com/7088527/191430975-5efe7524-979b-4ac1-a80b-0ac1ad394057.jpg)
I had been updated all plugin but it doesn't work. Would there is any possibility to fix this issue?

**Comment by psiinon** [comment]
It is because you have selected "Protected Mode" (top left).
Change that to "Standard Mode".
FYI these sort of questions are more suitable for the ZAP User Group rather than raising as issues: https://groups.google.com/group/zaproxy-users

**Comment by schedule6666** [comment]
Thanks for your help. It works for me.
