### ISSUE TITLE
ZAP Webswing not working in swarm

### ISSUE THREAD

**Issue by GiganteX** [zaproxy/zaproxy#7479]
### Describe the bug

If I run the sample ZAP Webswing command (docker run) it works fine, but I'm trying to start it up in my swarm. This is the command:

docker service create --replicas 1 --name zap \
--network mynetwork \
-p 8080:8080 -p 8090:8090 \
owasp/zap2docker-stable:latest zap-webswing.sh

but I get the "unhealthy container" message, and I don't know why.
What could be the issue?

### Steps to reproduce the behavior

see above

### Expected behavior

see above

### Software versions

the latest

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment]
You need to specify the port ZAP is listening, more info in: https://www.zaproxy.org/docs/docker/about/#healthcheck
