### ISSUE TITLE
Docker: AttributeError: 'pscan' object has no attribute 'disable_all_tags'

### ISSUE THREAD

**Issue by barbeque-squared** [zaproxy/zaproxy#7483]
### Describe the bug

When running `zap-full-scan.py` from a Docker image, it crashes with the following error:
```
2022-09-27 01:17:22,509 Unexpected error: <class 'AttributeError'>
Traceback (most recent call last):
  File "/zap/zap-full-scan.py", line 331, in main
    zap_tune(zap)
  File "/zap/zap_common.py", line 405, in zap_tune
    zap.pscan.disable_all_tags()
ERROR <class 'AttributeError'>
AttributeError: 'pscan' object has no attribute 'disable_all_tags'
```
This is new (could be older in code but a newer docker image) but this failure didn't occur ~30 hours ago.

### Steps to reproduce the behavior

1. Use image `owasp/zap2docker-weekly`
2. `zap-full-scan.py -j -a -t https://my-domain.org -c config.tsv -r report.html`

### Expected behavior

The test runs normally

### Software versions

Docker image version at the time of writing is `sha256:b4d214c419fd7d1f60d2f5ed7eb23ad1e007b5d84e2f67ba5a52469eea124d40`
It is very possible that other commands are also affected (since it appears it's going through zap_common)

### Errors from the zap.log file

There are no errors in the logfile (zap.out) but I attached it anyway. I da to manually add `.log` to the filename otherwise github doesn't accept it.
[zap.out.log](https://github.com/zaproxy/zaproxy/files/9652384/zap.out.log)

### Would you like to help fix this issue?

- [ ] Yes

(EDIT: formatting)

**Comment by psiinon** [comment]
Thanks for reporting this.
It turns out that moving to a different base image had the side effect of installing an older version of the ZAP python API library. No idea why :/
We'll regenerate the weekly and live images as soon as the fix is merged...

**Comment by psiinon** [comment]
The weekly and live docker images are being rebuilt now...

**Comment by psiinon** [comment]
The weekly and live docker images have now been released. The stable image should not have been affected.
