### ISSUE TITLE
Using the Active Scan for GET targets sends a 'Content-Length' header

### ISSUE THREAD

**Issue by mikkoparviainen** [zaproxy/zaproxy#7484]
When using the Active Scan for a GET target Zap sends the header 'Content-Length: 0' in the requests.

This should not happen and can prevent scanning some servers which do reject the 'Content-Length: 0' header in GET requests.

Reproduction:
Install Python
Start Python http server: `python -m http.server 7777`
Start Zap GUI, proxy at 8080, turn off HUD
Make a request using curl: `curl --proxy http://localhost:8080 http://localhost:7777`
See the request in Zap history
Right click the request in Zap history, select "Open/Resend in request editor"
See that no "content-length" header is present
Right click the request again, select "Attack->Active Scan"
Check the requests in the Active Scan tab
See that all the request have the header `Content-Length: 0`

The requests in the attack should not have the "Content-Length" header as some systems reject GET requests with it.

Zap version used: 2.11.1

**Comment by psiinon** [comment]
Have you got the "Update Content Length: button selected?
https://www.zaproxy.org/docs/desktop/ui/dialogs/man_req/#docsdesktopimagesfugueapplication-resizepng-update-content-length

**Comment by psiinon** [comment]
Sorry, just re-read the description - ignore the above question 😄
