### ISSUE TITLE
Encode/Decode/Hash tool should allow to create hashes in lower case

### ISSUE THREAD

**Issue by josemlwdf** [zaproxy/zaproxy#7503]
### Describe the bug

When we use the hash option, the result from every hash type is displayed in UPPERCASE

### Steps to reproduce the behavior

1. Open the Encode/Decode/Hash tool
2. Go to the Hash tab
3. Type anything
4. The resulting hashes are Uppercase wich is incorrect and prevent from reusing this results.

### Expected behavior

# text "test":
MD5 Hash | 098f6bcd4621d373cade4e832627b4f6
SHA1 Hash | a94a8fe5ccb19ba61c4c0873d391e987982fbbd3
SHA 256 Hash | 9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08

### Software versions

Version: 2.11.1

### Screenshots

![img](https://user-images.githubusercontent.com/60181010/194038655-dc335bda-1291-45ff-8bab-619b1d1b7d03.png)

### Would you like to help fix this issue?

- [ ] Yes

**Comment by psiinon** [comment]
Can you point to a link which states uppercase is invalid for hashing output?
My understanding is that the hashes are actually binary - we are displaying the hex representations which are case insensitive.
Can you also explain what prevents you from using the uppercase versions?

**Comment by kingthorin** [comment]
Note the [encode add-on](https://github.com/zaproxy/zap-extensions/tree/main/addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/predefined) doesn't force it one way or another, that's simply what Java's internals return.

https://docs.oracle.com/javase/7/docs/api/java/security/MessageDigest.html

Since it's now scriptable it should easy for a user to do the same thing the predefined processors do and simply add a `toLowerCase()` when the string is returned.

**Comment by josemlwdf** [comment]
![img](https://user-images.githubusercontent.com/60181010/194149553-5ddf02c3-c0de-47ec-8bbc-f03c1a6b0880.png)
This is why i posted it as a bug. Once someone will try to reuse the values from ZAP, their tokens, cookies or whatever will mess up. Just because ZAP outputs the hashes in Upercase. As you can see in my little python experiment, my Base 64 cookie is different in both cases because of uppercases.

**Comment by kingthorin** [comment]
That’s a base64 issue not a zap issue. Uppercase and lowercase in hashes mean exactly the same thing.

**Comment by psiinon** [comment]
I'd have no problem with an option to use lowercase, but forcing it to always generate lowercase would then mean we probably break it for people who need it that way 😉

**Comment by josemlwdf** [comment]
I do not want to find a failure in ZAP. I just wanted to make an statement that since ZAP outputs the hashes in a less common way and since it does not provide a solution to change between lowercase/uppercase, it makes more difficult the use of the tool. And if i posted it is because i love ZAP and i want to contribute to improve it and make it a more efficient tool.

**Comment by kingthorin** [comment]
There's a scriptable workaround in-flight.
https://github.com/zaproxy/zap-extensions/pull/4193#issuecomment-1295881150

**Comment by kingthorin** [comment]
We will be doing something about this. I'm not exactly sure what yet, but I thought I'd poll the twitterverse to at least establish a default.
https://twitter.com/kingthorin_rm/status/1586747412495978497

I did notice this weekend that Cyber Chef seems to default to lowercase.

**Comment by kingthorin** [comment]
Not exactly a huge sample size, but it seems lower is preferred:
![image](https://user-images.githubusercontent.com/7570458/199821279-7bd7e920-f2f3-4087-ac24-8d00fd235ee3.png)

**Comment by kingthorin** [comment]
Note: Encoder 1.0.0 with the fix for this issue is being released this morning: https://github.com/zaproxy/zap-extensions/releases/tag/encoder-v1.0.0
