### ISSUE TITLE
Unexpected results when manually calling getInteractshService.deregister()

### ISSUE THREAD

**Issue by someusername123** [zaproxy/zaproxy#7504]
### Describe the bug

When manually calling the function `Java.type("org.parosproxy.paros.control.Control").getSingleton().getExtensionLoader().getExtension("ExtensionOast").getInteractshService().deregister()` I would expect the OAST canaries defined to be reset to allow for a new one to be used, it would appear the code ends early on [InteractshService.java#278](https://github.com/zaproxy/zap-extensions/blob/931a07fa696dc156cc1f0c1a85bf4db71b4e4889/addOns/oast/src/main/java/org/zaproxy/addon/oast/services/interactsh/InteractshService.java#L273-L278) if the code returned is not 200.

### Steps to reproduce the behavior

1. Start a interactsh OOB server
2. Let the client sit for a few days until the interactsh server loses the correlation-id
3. Call Java.type("org.parosproxy.paros.control.Control").getSingleton().getExtensionLoader().getExtension("ExtensionOast").getInteractshService().deregister()

### Expected behavior

I would expect the de register option to clear the current server payload listed regardless of the returned code from the OAST service.

### Software versions

2.11.1

### Errors from the zap.log file

 [ZAP-ScriptExecutor-Deregiser OAST.js] WARN  InteractshService - Error during interactsh deregister, due to bad HTTP code 400. Content: {"error":"could not remove id: could not get correlation-id from cache"}

### Would you like to help fix this issue?

- [ ] Yes

**Comment by njmulsqb** [comment]
Please assign this to me! :)

**Comment by thc202** [comment]
Done :)

**Comment by njmulsqb** [comment]
When trying to generate a new payload with interactsh it gives me this error, is it a glitch or am I doing something wrong?
![image](https://user-images.githubusercontent.com/47940898/194939750-ddd15bc5-cba6-4ce6-80b3-4342b2378264.png)

**Comment by ricekot** [comment]
Could you try using one of the new default interactsh servers - one of `oast.pro,oast.live,oast.site,oast.online,oast.fun,oast.me` (as documented on https://github.com/projectdiscovery/interactsh).

**Comment by kingthorin** [comment]
Did you include the scheme?

**Comment by njmulsqb** [comment]
![image](https://user-images.githubusercontent.com/47940898/195058443-2851abd3-201b-454f-847e-c38e9621103e.png)

**Comment by kingthorin** [comment]
Hmmmm things to try: Move to another field. Click okay for the dialog and go back in.

**Comment by thc202** [comment]
That's mentioned in the help https://www.zaproxy.org/docs/desktop/addons/oast-support/services/interactsh/options/#active-payloads

**Comment by njmulsqb** [comment]
> Click okay for the dialog and go back in.

This worked, don't you think this should work without re-opening the dialog?

**Comment by someusername123** [comment]
@njmulsqb Thank you for the quick bug fix!
