### ISSUE TITLE
ZAP seems to report Content-Security-Policy: frame-ancestor 'none'; as an alert 

### ISSUE THREAD

**Issue by ovanekem** [zaproxy/zaproxy#7506]
### Describe the bug

I'm testing my application using ZAP proxy.
It reported a `CSP: Wildcard Directive` alert with as evidence the `Content-Security-Policy` having value of `frame-ancestor 'none';`
See below:
<img width="1026" alt="image" src="https://user-images.githubusercontent.com/3407155/194287070-4f7a0070-8e6d-4058-952f-b4dcedc87e2d.png">
However looking at the guidelines I see that having a value of 'none' is indeed what would be requested, see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors#:~:text=The%20HTTP%20Content%2DSecurity%2DPolicy,also%20supported%20in%20older%20browsers).

Also when I test my website with https://cspvalidator.org/ I get a green result:
<img width="1389" alt="image" src="https://user-images.githubusercontent.com/3407155/194287594-dd8e9d37-53a8-469d-b582-27ce0e96ca39.png">

I thought that the CSP headers check was delegated to https://github.com/shapesecurity/salvation but looking at the source code I think it is evaluated by the `pscanrules` add-on and more specifically by https://github.com/zaproxy/zap-extensions/blob/main/addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ContentSecurityPolicyScanRule.java (I have however not evaluated the code, maybe someone will tell me my configuration is not correct in the first place ;-)).

### Steps to reproduce the behavior

1. Perform an attack on a website which has the header `Content-Security-Policy: frame-ancestor 'none';`
2. The alert with risk medium is returned

### Expected behavior

To me a website with `Content-Security-Policy: frame-ancestor 'none';` should not report an alert at CSP level.

### Software versions

```
OWASP ZAP
Version: 2.11.1
---
Installed Add-ons: [[id=alertFilters, version=13.0.0],
[id=ascanrules, version=48.0.0], [id=ascanrulesBeta,
version=42.0.0], [id=attacksurfacedetector, version=1.1.4],
[id=automation, version=0.17.0], [id=bruteforce,
version=11.0.0], [id=callhome, version=0.4.0],
[id=commonlib, version=1.10.0], [id=custompayloads,
version=0.12.0], [id=diff, version=11.0.0],
[id=directorylistv1, version=5.0.0], [id=domxss,
version=13.0.0], [id=encoder, version=0.6.0], [id=exim,
version=0.2.0], [id=formhandler, version=6.0.0], [id=fuzz,
version=13.7.0], [id=fuzzdb, version=9.0.0],
[id=fuzzdbwebbackdoors, version=2.0.0], [id=gettingStarted,
version=13.0.0], [id=graaljs, version=0.2.0], [id=graphql,
version=0.10.0], [id=help, version=14.0.0], [id=httpsInfo,
version=12.0.0], [id=hud, version=0.14.0], [id=importurls,
version=9.0.0], [id=invoke, version=11.0.0], [id=network,
version=0.2.0], [id=oast, version=0.11.0], [id=onlineMenu,
version=9.0.0], [id=openapi, version=28.0.0], [id=portscan,
version=9.0.0], [id=pscanrules, version=43.0.0],
[id=pscanrulesBeta, version=30.0.0], [id=quickstart,
version=34.0.0], [id=replacer, version=10.0.0], [id=reports,
version=0.15.0], [id=retest, version=0.3.0], [id=retire,
version=0.15.0], [id=reveal, version=4.0.0],
[id=saverawmessage, version=7.0.0], [id=savexmlmessage,
version=0.3.0], [id=scripts, version=31.0.0], [id=selenium,
version=15.10.0], [id=soap, version=14.0.0], [id=spiderAjax,
version=23.9.0], [id=sqliplugin, version=15.0.0], [id=tips,
version=9.0.0], [id=tokengen, version=15.0.0],
[id=wappalyzer, version=21.13.0], [id=webdrivermacos,
version=45.0.0], [id=websocket, version=26.0.0], [id=zest,
version=36.0.0]]
---
Operating System: Mac OS X
Java Version: Eclipse Foundation 11.0.12
System's Locale: en_BE
Display Locale: en_GB
Format Locale: en_BE
ZAP Home Directory: /Users/ovanekem/Library/Application Support/ZAP/
ZAP Installation Directory: /Applications/OWASP ZAP.app/Contents/Java/./
Look and Feel: FlatLaf Light (com.formdev.flatlaf.FlatLightLaf)
```

### Would you like to help fix this issue?

- [ ] Yes

**Comment by kingthorin** [comment]
Please read the full alert details, it isn't complaining about what is specified but rather what isn't specified.

**Comment by ovanekem** [comment]
Ok sorry, this was not clear to me. So updating the existing header to something like:

`Content-Security-Policy: frame-ancestors 'none'; default-src: 'self';`

should then remediate the risk I guess.

**Comment by kingthorin** [comment]
That's a good start, but you'll need to specify values for all the directives that don't fallback to default-src.

https://github.com/zaproxy/zap-extensions/blob/ffe2fd9563838cbdd857c5bca46b99d7da9ce754/addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ContentSecurityPolicyScanRule.java#L75-L84

**Comment by ovanekem** [comment]
ok got it thanks a lot @kingthorin
