### ISSUE TITLE
Baseline error on Stable

### ISSUE THREAD

**Issue by funderpanda** [zaproxy/zaproxy#7509]
Using ZapDocker stable 2.11.1

When using the following command line
`python3 /zap/zap-baseline.py -z ' -config start.checkForUpdates=false -config start.checkAddonUpdates=false -config values.auto_update_addons=True -config connection.proxyChain.exclusions.exclusion.name=link -config connection.proxyChain.enabled=true -config connection.proxyChain.hostName=proxy -config connection.proxyChain.port=port' -n context.yml -t https://link.com`

12:43:50  Traceback (most recent call last):
12:43:50    File "/zap/zap-baseline.py", line 504, in main
12:43:50      zap_tune(zap)
12:43:50    File "/zap/zap_common.py", line 401, in zap_tune
12:43:50      zap.pscan.disable_all_tags()
12:43:50  AttributeError: 'pscan' object has no attribute 'disable_all_tags'
12:43:50  ERROR <class 'AttributeError'>

**Comment by psiinon** [comment]
@funderpanda Are you using the latest zap2docker-stable image
Have you made any changes to the image?
What command are you using to start the image?
What is the output of `pip3 show  python-owasp-zap-v2.4` in this image?

I've tried an equivalent of this command and it worked ok for me.
FYI `-n context.yml` looks wrong to me - the context file for the packaged scans should be an XML file.

**Comment by funderpanda** [comment]
---
env:
  contexts:
  - name: "petStoreContext"
    urls:
    - "https://petstore.swagger.io"
    includePaths:
    - "https://petstore.swagger.io/login"
    excludePaths:
    - "https://petstore.swagger.io"

**Comment by kingthorin** [comment]
You don’t seem to be using an up-to-date image, or you have customized and forgot.

https://pypi.org/project/python-owasp-zap-v2.4/

**Comment by funderpanda** [comment]
Thank you, updating the python zap seemed to fix it :)
