### ISSUE TITLE
i what start this appliction,but it went error

### ISSUE THREAD

**Issue by dpengchen** [zaproxy/zaproxy#7545]
![图片](https://user-images.githubusercontent.com/116140374/198203993-35170337-c8a6-4ddd-8c19-2690c37222b8.png)

![图片](https://user-images.githubusercontent.com/116140374/198204109-1b3ff659-573b-4c69-883c-ebc05b49db13.png)
 
please help me, thanks !

**Comment by ricekot** [comment]
Please go through https://www.zaproxy.org/docs/developer/quick-start-build/#installing-zap-add-ons. You need to install mandatory add-ons when building ZAP from source. Also, please post any future development related questions to https://groups.google.com/group/zaproxy-develop.

**Comment by dpengchen** [comment]
> Please go through https://www.zaproxy.org/docs/developer/quick-start-build/#installing-zap-add-ons. You need to install mandatory add-ons when building ZAP from source. Also, please post any future development related questions to https://groups.google.com/group/zaproxy-develop.

thank you! question solving.
