### ISSUE TITLE
ZapDocker Not Redirecting

### ISSUE THREAD

**Issue by funderpanda** [zaproxy/zaproxy#7549]
Hi so I'm running the following on zapdocker stable (lastest). 

I want to log onto my site and I can do this by curling https://site.com/login?username=username&password=password with the header 'referer: https://site.com/' 
I tried replicating it on zap

`python3 zap-baseline.py -z '-config ZAP_AUTH_HEADER_VALUE=value -config ZAP_AUTH_HEADER=value' -t https://site.com/login?username=username&password=password
`

Issue is zap times out [Errno 5] Failed to connect to ZAP after 600 seconds
I was wondering if redirection is blocked as my curl command works just fine. 

Thank you!

**Comment by psiinon** [comment]
Please ask these sort of questions on the ZAP User Group: https://groups.google.com/group/zaproxy-users
If it turns out theres a bug that needs fixing then we can raise an issue here.
