### ISSUE TITLE
Alert selection automatically focusing the Request/Response tabs in Full layout

### ISSUE THREAD

**Issue by ilan-pav** [zaproxy/zaproxy#7559]
### Describe the bug

When in the "Alerts" tab, having a list of alerts on the left, pressing one of the alerts will open one of the requests that have the issue. 
If I just want to read information about this kind of issue, being redirected automatically (and randomly) to one of the requests just makes me go again to the "Alerts" tab and press again. Feels to me like a bug. Going to a request should be triggered only by pressing the specific request.

### Steps to reproduce the behavior

1. Go to "Alerts". (Having several kinds of alerts, with multiple requests in each of them).
2. While collapsed, press on one of the alerts.
3. Notice how you are redirected to a request instead of the alert description.

### Expected behavior

On the "Alerts" tab, I would like to be able to press the different alerts and read their descriptions. 
Currently I'm redirected to the "Request&Response" tab after each click, having to go back to the "Alerts" tab. 

### Software versions

Zap 2.12.0

### Screenshots

![image](https://user-images.githubusercontent.com/93528246/198878580-74a4b294-4098-4cf8-9b8a-0d2c7a278c1d.png)

Pressing where I drew the red dots redirects me to the "Request&Response" tab.

### Would you like to help fix this issue?

- [ ] Yes

**Comment by kingthorin** [comment]
It's not a bug, that's the intended behavior. The request/response selected are the one associated with the first alert (of that particular type).

**Comment by thc202** [comment]
I think the problem is the focus not opening the request.

**Comment by kingthorin** [comment]
I think it the view the user is in it might be changing panels.

**Comment by ilan-pav** [comment]
I now noticed that the issue happens when I'm in "Full layout". When in "Expend information tabs" it works nicely.
