### ISSUE TITLE
Docker healthcheck fails when UI is disabled

### ISSUE THREAD

**Issue by acardnell-intruder** [zaproxy/zaproxy#7563]
### Describe the bug

When disabling the UI via a `conf` file using `api.uienabled=false`, the ZAP API will work as expected but the Docker healthcheck will no longer succeed, and the container will eventually be labelled as `unhealthy`.

Not sure if this behaviour is intentional - the documentation seems to imply the UI and API would be treated separately.

### Steps to reproduce the behavior

1. Create `conf` file with api.uienabled=false
2. Start container `zap.sh -daemon -port <some-port> -host 0.0.0.0 -config api.key=<some-key> -configfile path/to/conf`
3. Container will start and show it is listening on `<some-port>` but healthcheck will never succeed.

### Expected behavior

If the API has started successfully and is listening on whatever port it has been assigned then the healthcheck should succeed.

### Software versions

Happening on the latest (2.12.0) but also the more recent versions of 2.11 as well.

**Comment by psiinon** [comment]
If you're actually setting the API key on the command line then the health check will fail on any ZAP API endpoint unless you also set that key via an env var (this will required changes to the docker file as well).
Are you ok doing that?

**Comment by kingthorin** [comment]
> the documentation seems to imply the UI and API would be treated separately

It’s not clear what docs you’re referring to but it seems likely that it is referring to the Java GUI and web API. (Not the web UI.)

**Comment by acardnell-intruder** [comment]
> 

Thanks for the quick reply! The API key is set via the command line because it is being set dynamically by a script. The healthcheck passes as soon as I remove the `api.uienabled=false` from the `conf` file.

Here is the response with the option enabled:

<img width="727" alt="image" src="https://user-images.githubusercontent.com/103442492/198995385-62667c81-6afa-4e0d-a34e-0a03457f706b.png">

![image](https://user-images.githubusercontent.com/103442492/198995188-84803734-6d40-45c5-aad3-fa41be1e59db.png)

Here is the response with the option disabled:

<img width="913" alt="image" src="https://user-images.githubusercontent.com/103442492/198996655-ed006442-1bd4-4446-b0e5-4f9564412694.png">

![image](https://user-images.githubusercontent.com/103442492/198996819-969372d6-ba02-4058-bc9c-8143ff7e4262.png)

It is worth noting that if I fudge the healthcheck and just get it to return a successful exit code then everything else works and I can initiate and run scans happily via the API.

**Comment by rashied-r** [comment]
I have the same issue inside the docker container doesn't exist zap-cli file, so we can not get healthy in the new version that releases on [2022-10-27](https://hub.docker.com/layers/owasp/zap2docker-stable/s2022-10-27/images/sha256-7a669aec036cb47107463c10a722fb581da3e7200b816de3feb92f05ccbcdb03?context=explore)

**Comment by kingthorin** [comment]
zap-cli was third party and unmaintained, it’s been removed, as was announced on Twitter and via the User Group
https://groups.google.com/g/zaproxy-users/c/e_hv9dGHgF8/m/-SuSSL6jBAAJ

**Comment by rashied-r** [comment]
Thanks @kingthorin 

How can we get a healthy message from zap instead of using zap-cli status
Do you have any suggestions?

**Comment by kingthorin** [comment]
You can use curl: https://github.com/zaproxy/zaproxy/pull/7487
