### ISSUE TITLE
zap-cli is not available on the latest docker image

### ISSUE THREAD

**Issue by thiagosanches** [zaproxy/zaproxy#7564]
### Describe the bug

If you try to execute the `zap-cli` command inside the running container you will get an error:

```
OCI runtime exec failed: exec failed: unable to start container process: exec: "zap-cli": executable file not found in $PATH: unknown
```

### Steps to reproduce the behavior

1. Run the following command to create a running container: 
```bash
docker run --detach -v /tmp/zap-report:/zap/wrk/:rw -p 0:8090 -i owasp/zap2docker-stable zap.sh -daemon -port 8090 -host 0.0.0.0 -config 'api.addrs.addr.name=.*' -config api.addrs.addr.regex=true -config api.key=key
```
2. Try to run the `zap-cli` on the running container:
```bash
docker exec <containerId> zap-cli
```

Result:
```
OCI runtime exec failed: exec failed: unable to start container process: exec: "zap-cli": executable file not found in $PATH: unknown
```

### Expected behavior

If we try with the `2.11.1` tag it works properly:
```bash
docker run --detach -v /tmp/zap-report:/zap/wrk/:rw -p 0:8090 -i owasp/zap2docker-stable:2.11.1 zap.sh -daemon -port 8090 -host 0.0.0.0 -config 'api.addrs.addr.name=.*' -config api.addrs.addr.regex=true -config api.key=key
```

```bash
docker exec <containerId> zap-cli
```

![image](https://user-images.githubusercontent.com/5191469/199023215-7508541e-3078-40ac-a412-465a59bc460a.png)

### Software versions

It happens on the latest docker image.

### Would you like to help fix this issue?

- [ ] Yes

**Comment by psiinon** [comment]
This was planned and announced on the ZAP User Group: https://groups.google.com/g/zaproxy-users/c/e_hv9dGHgF8/m/roGXlbV3LwAJ

**Comment by thiagosanches** [comment]
Oh, I was not aware about it @psiinon, thank you for letting me know!
So, we can close this ticket.
