### ISSUE TITLE
ZAP 2.12.0 Can't Find Java JRE in Windows

### ISSUE THREAD

**Issue by aaronaru** [zaproxy/zaproxy#7565]
I attempted to install ZAP 2.12.0 on my Windows 10 64-bit system, and got an error that it couldn't find the JRE necessary for the installation. JRE was already installed (and ZAP 2.11.1 had installed on top of it with no problems), but I went ahead and installed the latest JRE Version 8 Update 351. Same error as before when attempting to install ZAP 2.12.0. I reinstalled ZAP 2.11.1 with no problems.

**Comment by kingthorin** [comment]
2.12 requires Java 11.
