### ISSUE TITLE
SQL Injection False Positive Confirmation?

### ISSUE THREAD

**Issue by nchilds** [zaproxy/zaproxy#7567]
We have OWASP ZAP scanning the swagger.json Open API Definition for various API's in our application, and the following SQL Injection rule has been failing intermittently: 

SQL injection may be possible.
Do not trust client side input, even if there is client side validation in place. In general, type check all data on the server side. If the application uses JDBC, use PreparedStatement or CallableStatement, with parameters passed by '?' If the application uses ASP, use ADO Command Objects with strong type checking and parameterized queries. If database Stored Procedures can be used, use them. Do *not* concatenate strings into queries in the stored procedure, or use 'exec', 'exec immediate', or equivalent functionality! Do not create dynamic SQL queries using simple string concatenation. Escape all data received from the client. Apply an 'allow list' of allowed characters, or a 'deny list' of disallowed characters in user input. Apply the principle of least privilege by using the least privileged database user possible. In particular, avoid using the 'sa' or 'db-owner' database users. This does not eliminate SQL injection, but minimizes its impact. Grant the minimum database access that is necessary for the application.

Stack trace:
https://app.azurewebsites.net/swagger/v3/swagger.json?query=query+AND+1%3D1+--+, GET, query,

We had the developers take a look at the API, but they reported that there is no injection vulnerability in the API itself, indicating a false positive. Would appreciate some guidance on how we can go about confirming that this is a false positive, or otherwise.

**Comment by kingthorin** [comment]
You can refer to the [OWASP WSTG](https://owasp.org/wstg) is a good place to start learning about SQLi and app sec testing.

You could also trust your devs, or contract an assessment out.

The code is Open Source so you could have a look and specifically re-create the traffic.

The [ZAP User Group]( https://groups.google.com/group/zaproxy-users) is a much better place for questions of this nature. If you do post over there please provide more details (which scan rule triggered the alert, what input vectors were in use, the ‘other info’ associated with the alert, etc).
