### ISSUE TITLE
I want change program name, an error occurred org.zaproxy.zap.ZAP not find

### ISSUE THREAD

**Issue by dpengchen** [zaproxy/zaproxy#7568]
![image](https://user-images.githubusercontent.com/116140374/199227860-29500bcd-e596-4f5d-9ee1-6171a4bbff37.png)
I want change program name, an error occurred org.zaproxy.zap.ZAP not find.
what to do change Tab Control name

![image](https://user-images.githubusercontent.com/116140374/199228382-d426dd0b-d2db-4d67-9bc7-bc89746b0f3e.png)

**Comment by dpengchen** [comment]
> Why do you want to do this? It just looks like you are trying to rebrand ZAP, which is not exactly ethical.

I have a lot of respect for the software and the developer, but my BOOS demanded it.I am very sorry that.

**Comment by kingthorin** [comment]
Sometimes you have to stand up for what’s right. 

Feel free to let your boss know we have some thoughts for them.

**Comment by dpengchen** [comment]
> Sometimes you have to stand up for what’s right.
> 
> Feel free to let your boss know we have some thoughts for them.

I don't know they didn't get permission,I'm sorry.

I will refuse this project.
