### ISSUE TITLE
Provided Browser was not found

### ISSUE THREAD

**Issue by ghoshsoumen** [zaproxy/zaproxy#7570]
Am using ZAP 2.12.0. On Manual Explore, I enter a URL, select Chrome and click on Launch Browser, a window appears temporarily and closes. Then a popup is appearing with message "The provided browser was not found".
With Firefox, even the windows doesn't appear and straightaway the error popup appears.
Anyone facing this issue and any resolution known to anyone would be of help.

**Comment by kingthorin** [comment]
Next time you report an issue please properly complete the template.

**Comment by kingthorin** [comment]
That sometimes happens when your browser has an update pending.

**Comment by kingthorin** [comment]
Also ensure you’ve upgraded all your add-one.

The [ZAP User Group]( https://groups.google.com/group/zaproxy-users) is a much better place for further discussion.
