### ISSUE TITLE
I made an error while compiling

### ISSUE THREAD

**Issue by TemptEyes** [zaproxy/zaproxy#7573]
![image](https://user-images.githubusercontent.com/117426937/199899636-8ab78282-8c9e-4b7b-999e-fd69ede1eaf8.png)

**Comment by TemptEyes** [comment]
The project can be run, but not packaged

**Comment by psiinon** [comment]
Please do not ask questions as issues.
For development questions you can use the ZAP Developer Group: https://groups.google.com/group/zaproxy-develop
