### ISSUE TITLE
The `zap-x.sh` script should exit with the exit code of `zap.sh`

### ISSUE THREAD

**Issue by trevor-vaughan** [zaproxy/zaproxy#7576]
### Describe the bug

When using `zap-x.sh` in pipelines, it is important to know if there was an error with ZAP itself.

The current script will output the exit code from the `rm -f` command regardless of the status of ZAP.

### Steps to reproduce the behavior

1. Do something that messes up the core ZAP run
2. Check `$?` and see that it is `0`

### Expected behavior

The exit code is that returned by `zap.sh`

### Software versions

All

### Would you like to help fix this issue?

- [X] Yes

**Comment by psiinon** [comment]
Yeah, it should do this ;)
FYI the zap-x.sh script isnt really needed any more as we use headless browsers by default, but we'll have to keep it around for everyone who currently uses it..
