### ISSUE TITLE
ZAP API: Session overwrite parameter doesn't work in core/action/saveSession/ handle

### ISSUE THREAD

**Issue by shad0wrunner** [zaproxy/zaproxy#7587]
In ZAP 2.11.1 I wasn't able to overwrite session via API handle core/action/saveSession/

I am sending a request like the following: JSON/core/action/saveSession/?name=session&overwrite=true but nevertheless get a response:

{"code":"already_exists","message":"Already Exists"}

and the session is not overwritten

**Comment by psiinon** [comment]
Is this still the case for ZAP 2.12.0 ?

**Comment by shad0wrunner** [comment]
Hi,

Yes, it can reproduced in 2.12.0 unfortunately.

This is what I've done:
1. Started ZAP in daemon mode
2. Opened API GUI - http://172.16.31.19:8080/UI/core/action/saveSession/
3. Saved a session as "session" using the API
4. Tried to save the same session as "session" specifying "overwrite" parameter as "true".

Result: {"code":"already_exists","message":"Already Exists"}

**Comment by kingthorin** [comment]
You can only overwrite if the session is empty.

**Comment by thc202** [comment]
And the session just needs to be saved once (to the same location).

**Comment by psiinon** [comment]
As per the above comments, the session is actually a database. It only needs to be saved once. After that all updates are automatically saved.
