### ISSUE TITLE
Levo.ai add-on for ZAP

### ISSUE THREAD

**Issue by ricekot** [zaproxy/zaproxy#7588]
### Add-on repo

https://github.com/levoai/levoai-zap-addon

### Your contact details

akshath.kothari@levo.ai

### Are you one of the authors?

- [X] Yes

### License

Apache-2.0 license

### Build instructions

The add-on uses the `org.zaproxy.add-on` gradle plugin so the build instructions are the same as for other ZAP add-ons.

### Link for more information

Documentation for Levo is available at https://docs.levo.ai/.
I will be adding documentation specific to using this add-on soon.

### Twitter handle for tool or author(s)

https://twitter.com/LevoIncHQ

**Comment by kingthorin** [comment]
It doesn't seem like there's a release available.

**Comment by thc202** [comment]
Done in zaproxy/zap-admin#861.
