### ISSUE TITLE
ZAP Stable Docker Image Is Changing Post Release

### ISSUE THREAD

**Issue by SOOS-JJennings** [zaproxy/zaproxy#7591]
### Describe the bug

We believe your stable docker image versions are not actually static. For example, yesterday we fully regression tested our application which relies on a tag owasp/zap2docker-stable:2.12.0 (0f5578a52ae8), but then this morning we found that zap2docker was failing with errors that were not present yesterday (possibly related to add-ons loading dynamically?)

Has your build process changed? What is the proper way to get a version of zap where the dependencies are all pinned and unchanging?

Thanks

### Steps to reproduce the behavior

n/a

### Expected behavior

stable versions of zap2docker should be static once released

### Software versions

2.12.0 (and likely other stable versions as well)

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment]
I don't think we have that documented but it was mentioned in a blog post a while ago https://www.zaproxy.org/blog/2021-10-07-zap-2-11-0/#docker

You need to use a dated tag. Although those errors should no longer be happening with the latest image (released some hours ago).

Even if the image was no longer being updated the add-ons are still updated when ZAP runs, if you really want to use always the same versions of the add-ons you would have to disable the add-ons updates.

**Comment by SOOS-JJennings** [comment]
Thanks @thc202 this is helpful.
