### ISSUE TITLE
OpenAPI path parameter incorrectly imported

### ISSUE THREAD

**Issue by pdlopez** [zaproxy/zaproxy#7597]
### Describe the bug

Hello!

I'm importing an OpenAPI definition, and one endpoint has a path parameter, which ZAP takes as a path/directory, not as a parameter to inyect.
OpenAPI documentation: https://swagger.io/docs/specification/describing-parameters/

Is there something that I am missing when importing the API definition? Some extra configuration for this kind of parameter?

Thank you!

### Steps to reproduce the behavior

1. Go to **_Import_** menu, **_Import an OpenAPI definition_**... and load a swagger.json file containing an endpoint using a path parameter
2. Check the generated site tree, attack the endpoint with SQL inyection or try to edit the request.

### Expected behavior

The expected behavior is that ZAP takes the path parameter as something inyectable while testing, not as a directory/path, otherwise ZAP is not testing correctly API endpoints.

### Software versions

I'm using OWASP ZAP 2.11.1

### Screenshots

swagger.json
![image](https://user-images.githubusercontent.com/107931905/201108861-95e7270f-880d-4098-b99c-cf668d9b24c7.png)

Site tree
![image](https://user-images.githubusercontent.com/107931905/201108720-08a543b1-84bd-4410-b247-d8d06a147286.png)

Request
![image](https://user-images.githubusercontent.com/107931905/201109077-ae7f40d3-f0c4-4046-9e7a-b29f7566a8e8.png)

When executing an attack
![image](https://user-images.githubusercontent.com/107931905/201109596-10c250b9-fc7f-4b62-9901-f2b992978146.png)

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment]
Is `URL Query String & Data Driven Nodes` enabled? What scan rules are you using? Not all scan rules attack parameters.

**Comment by kingthorin** [comment]
Looks right to me. With no example or default.

**Comment by thc202** [comment]
@pdlopez do you have more details?
