### ISSUE TITLE
Not working with Cloudbuild Ci

### ISSUE THREAD

**Issue by yanis-incepto** [zaproxy/zaproxy#7603]
### Describe the bug

Hello,
every time I try to launch it with Cloudbuild CI, i get an error. It says me that zap fails to start
Output of the CI : 
Status: Downloaded newer image for owasp/zap2docker-stable:latest
docker.io/owasp/zap2docker-stable:latest
2022-11-16 16:00:26,640 Trigger hook: cli_opts, args: 1
2022-11-16 16:00:26,641 Using port: 53775
2022-11-16 16:00:26,641 Trigger hook: start_zap, args: 2
2022-11-16 16:00:26,641 Starting ZAP
2022-11-16 16:00:26,641 Failed to start ZAP :(
ERROR
ERROR: build step 0 "owasp/zap2docker-stable" failed: step exited with non-zero status: 3

### Steps to reproduce the behavior

Step of the Ci I used (replaced the url with those of google to don't display my company website url : 
`- name: 'owasp/zap2docker-stable'`
    `id: ci-zaproxy`
    `args: ['zap-full-scan.py', '-t', 'https://www.google.com', '-d']`

### Expected behavior

It should work the same manner as it works when i launch it with docker on my computer but actually, it doesn't and so, we can't launch zaproxy on our CIs

### Software versions

I use the latest version of zap of owasp/zap2docker-stable

### Would you like to help fix this issue?

- [X] Yes

**Comment by kingthorin** [comment]
It doesn't say "failed to start" it says "failed step".

**Comment by yanis-incepto** [comment]
Thanks for your answer but what do you mean by try to run zap directly ? On command line ? I can't because cloudbuild is a cloud solution and i have no access to it on command line.
But don't you know if there's a possibility to get logs for the execution please ?

**Comment by kingthorin** [comment]
>  But don't you know if there's a possibility to get logs for the execution please ?

It's your CI, you tell us :grinning: ZAP logs to a file called “zap.log” in the ZAP [‘home’ directory](https://www.zaproxy.org/faq/what-is-the-default-directory-that-zap-uses/).

**Comment by yanis-incepto** [comment]
It's Cloudbuild CI so no, i can't launch it directly from command line. Okay thanks, i'll mount and verify this file.

**Comment by thc202** [comment]
You don't need the command line, just replace the `args` to run ZAP e.g.: `['/zap/zap.sh', '-cmd']`

**Comment by yanis-incepto** [comment]
Hello,
Sorry for the late answer.
It worked using your parameters. It shows this : 
Found Java version 11.0.17
Available memory: 3930 MB
Using JVM args: -Xmx982m
1280 [main] INFO  org.parosproxy.paros.Constant - Copying default configuration to /home/zap/.ZAP/config.xml
1592 [main] INFO  org.parosproxy.paros.Constant - Creating directory /home/zap/.ZAP/session
1593 [main] INFO  org.parosproxy.paros.Constant - Creating directory /home/zap/.ZAP/dirbuster
1594 [main] INFO  org.parosproxy.paros.Constant - Creating directory /home/zap/.ZAP/fuzzers
1595 [main] INFO  org.parosproxy.paros.Constant - Creating directory /home/zap/.ZAP/plugin
Nov 22, 2022 8:46:59 AM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
PUSH

But with zap.sh, can i launch a scan ? Is it possible it'll work ? Thanks you

**Comment by thc202** [comment]
If ZAP is able to start the problem is not #7556. What do you get using this script `/zap/zap-x.sh`?

You could use the [Automation Framework](https://www.zaproxy.org/docs/automate/automation-framework/), but not directly the packaged scans.

**Comment by yanis-incepto** [comment]
Hello, Thanks for your answer. It works but ends with a timeout. With these scripts, can we launch zaproxy scan ?
End of the output : 
20827 [ZAP-BootstrapGUI] WARN  org.flywaydb.core.internal.database.base.Database - Flyway upgrade recommended: HSQLDB 2.7 is newer than this version of Flyway and support has not been tested. The latest supported version of HSQLDB is 2.6.
20858 [ZAP-BootstrapGUI] INFO  org.flywaydb.core.internal.command.DbValidate - Successfully validated 1 migration (execution time 00:00.018s)
20875 [ZAP-BootstrapGUI] INFO  org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory - Creating Schema History table "PUBLIC"."flyway_schema_history" ...
20933 [ZAP-BootstrapGUI] INFO  org.flywaydb.core.internal.command.DbMigrate - Current version of schema "PUBLIC": << Empty Schema >>
20947 [ZAP-BootstrapGUI] INFO  org.flywaydb.core.internal.command.DbMigrate - Migrating schema "PUBLIC" to version "1 - Create table boast"
20980 [ZAP-BootstrapGUI] INFO  org.flywaydb.core.internal.command.DbMigrate - Successfully applied 1 migration to schema "PUBLIC", now at version v1 (execution time 00:00.055s)
20994 [ZAP-BootstrapGUI] INFO  org.zaproxy.addon.oast.services.callback.CallbackService - Started callback service on 0.0.0.0:37171
21135 [ZAP-BootstrapGUI] INFO  org.zaproxy.addon.network.ExtensionNetwork - Creating new root CA certificate.
22624 [ZAP-BootstrapGUI] INFO  org.zaproxy.addon.network.ExtensionNetwork - New root CA certificate created.
TIMEOUT
ERROR: context deadline exceeded

**Comment by thc202** [comment]
You still need to provide the `-cmd` or `-daemon`. Could you try again with the `zap-full-scan.py`?

> With these scripts, can we launch zaproxy scan ?

Those scripts just start ZAP, you would have to use the Automation Framework or other custom scripts to control ZAP.
