### ISSUE TITLE
Allow to download/upload files through the ZAP API

### ISSUE THREAD

**Issue by trevor-vaughan** [zaproxy/zaproxy#7607]
### Is your feature request related to a problem? Please describe.

I wish to use ZAP as a daemon in a container as part of a CI pipeline.

However, to do so, I either need to roll a new ZAP image for every type of target I wish to examine or I need to use ZAP as the base image itself.

With [GitLab services](https://docs.gitlab.com/ee/ci/services/), you cannot modify the running image on load, so you end up having to run ZAP as the "runner" which is not ideal.

### Describe the solution you'd like

I would like any API endpoint that allows for loading from a file on the local filesystem to either:

1. Have an associated `upload` endpoint that will put the file into the correct location
2. Allow me to upload the entire file contents as part of a `POST`
   * I'm not 100% sure this will work for everything but it will certainly work for anything plain-text

### Describe alternatives you've considered

I haven't found any good way around this issue

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment]
Can't you mount (e.g. `-v`) the directory with the files you need?

**Comment by trevor-vaughan** [comment]
@thc202 Not when running as a GitLab service. They're fire and forget as far as I can tell.

**Comment by trevor-vaughan** [comment]
It gets quite difficult to handle this in a k8s and/or cloud environment without jumping through a lot of hoops. Being able to just shove what I want at the daemon would be extremely powerful.

**Comment by kingthorin** [comment]
That seems more like a GitLab issue than a zap one. You can already import contexts etc through the API. If you can’t present some storage to zap, that’s out of zap’s control.

**Comment by trevor-vaughan** [comment]
@kingthorin Yep, that's why this is a feature request. As a daemon, ZAP has no need for dynamic or saved storage. I can literally download everything via the API.

I just can't upload via the API so I want to be able to shove in plain text files via the API to be able to do all the things.

**Comment by kingthorin** [comment]
What plain text file would zap need to consume?

**Comment by kingthorin** [comment]
So you want the Automation Framework to have an api to accept its yaml plans? 

If you can provide it to the api why can’t you provide it to the cli?

**Comment by trevor-vaughan** [comment]
The minimum list for me so far is:
* scripts
* policies
* contexts

Ideally, it would be a direct file upload with a target name and type.

Going from the `zaproxy` Node implementation, something like:

```javascript
  zaproxy.script.upload(scriptName, scriptType, scriptEngine, fileName, <other optional stuff>)

  zaproxy.ascan.upload(fileName)

  zaproxy.context.upload(fileName)
```

**Comment by trevor-vaughan** [comment]
> So you want the Automation Framework to have an api to accept its yaml plans?

Yes

> If you can provide it to the api why can’t you provide it to the cli?

If I'm running the daemon as a service, I don't have access to the CLI, nor can I get files into the image dynamically.

Basically, this is the missing piece to making the daemon a completely standalone service that does not require users to do anything on the filesystem.

**Comment by kingthorin** [comment]
To me all of those things are in place, they’re just not called “upload”. If you’re truly running zap with no storage then there’s likely to be other issues 🤷‍♂️

I suspect I’m missing something subtle, and will admit to essentially zero k8s experience. So I’ll leave this to others.

**Comment by trevor-vaughan** [comment]
@kingthorin It's certainly possible that I'm missing something.

Scenario:

Given a script that I want to get into ZAP
And I do not have access to the command line
And I do not have the ability to add files to the remote system where ZAP is running
How do I do this?

**Comment by trevor-vaughan** [comment]
Note, I didn't say that ZAP doesn't have storage. I said that I don't have *access* to the storage.

**Comment by psiinon** [comment]
OK, that makes sense.
We've avoided remote script (etc) upload to ZAP to reduce the attack surface area.
However I guess we could permit file upload, either via an additional add-on or APIs which could be disabled by default but enabled if required?
Definitely one for us to think carefully about, but I can it would have real benefits..

**Comment by kingthorin** [comment]
> Note, I didn't say that ZAP doesn't have storage. I said that I don't have _access_ to the storage.

Told you it must be subtle. (Yes you kinda covered this earlier but this made it clear.)

**Comment by trevor-vaughan** [comment]
> OK, that makes sense. We've avoided remote script (etc) upload to ZAP to reduce the attack surface area. However I guess we could permit file upload, either via an additional add-on or APIs which could be disabled by default but enabled if required? Definitely one for us to think carefully about, but I can see it would have real benefits..

Ran into this again recently. Would a second API key work for uploads? I get the increased attack surface, but you really shouldn't be exposing your scanners broadly anyway.

**Comment by kingthorin** [comment]
> but you really shouldn't be exposing your scanners broadly anyway

Users and their foot guns 😁

**Comment by thc202** [comment]
Given #7943 I guess this is more llikely to happen.

**Comment by trevor-vaughan** [comment]
> > but you really shouldn't be exposing your scanners broadly anyway
> 
> Users and their foot guns 😁

I mean sure but 🤷. I just want the ability to shoot myself in the foot when I want to 😁

**Comment by trevor-vaughan** [comment]
The end result I'm looking for is:
* Start ZAP (toggling uploads via CLI or config file works)
* Upload whatever files I need in order to fully configure the scanner
* Reload ZAP if necessary
* Scan all the things

It sounds like a CLI option would work fine as long as everything else could be configured to look in wherever things got uploaded without issue.

In the future, having namespaced endpoints that allow you to configure different scanner features would probably be safest, but it's also a lot of work.

**Comment by trevor-vaughan** [comment]
I think that should work. Do you see any issues with loading files into ZAP from a single location? I can't remember if any of the standard plugins were picky about paths and directory structure.

**Comment by psiinon** [comment]
I'm hoping there won't be any problems.. but I've identified all of the API endpoints which support file paths and will manually test them all 😀
