### ISSUE TITLE
ssl peer shut down incorrectly

### ISSUE THREAD

**Issue by LiouLiu9** [zaproxy/zaproxy#7612]
### Describe the bug

When I run zap 2.12 on a Macbook, I experienced ssl peer shut down incorrectly issue. I also tried all the suggestions in the instruction https://www.zaproxy.org/faq/how-to-connect-to-an-https-site-that-reports-a-handshake-failure/, and the issue is not fixed yet.

### Steps to reproduce the behavior

1, set up ZAP proxy connection 127.0.0.1:8080
2, Firefox network proxy setting is set as 127.0.0.1:8080
3, import OWASP.ert into Firefox trusted certs
4, active scan a website facing to the internet
5, I use company owned laptop but there is proxy setting on it
6, got error fail in handshake
7, I downloaded JDK 19 and still has the issue
8, modified the zap.sh file as stated in https://www.zaproxy.org/faq/how-to-connect-to-an-https-site-that-reports-a-handshake-failure/

### Expected behavior

scan should run

### Software versions

zap 2.12.0 for MAC OS

### Would you like to help fix this issue?

- [X] Yes

**Comment by thc202** [comment]
Did you configure an outgoing proxy in ZAP?

**Comment by LiouLiu9** [comment]
Where can I find this setting? Tried to look for it but could not find it.

**Comment by thc202** [comment]
In Options > Network > Connection > HTTP Proxy
https://www.zaproxy.org/docs/desktop/addons/network/options/connection/#http-proxy

**Comment by LiouLiu9** [comment]
Yes it has been done. 
<img width="733" alt="Screen Shot 2022-11-23 at 1 59 02 pm" src="https://user-images.githubusercontent.com/98074760/203461517-e051cafd-5477-4522-840f-44fb95ebadf4.png">

**Comment by kingthorin** [comment]
> 5, I use company owned laptop but there is proxy setting on it

The company proxy settings should go in that screen.

**Comment by kingthorin** [comment]
At least I believe that’s what he was getting at. I don’t have zap in front of me right now to check.

**Comment by LiouLiu9** [comment]
> 

sorry my bad. There is no proxy in our company.

**Comment by LiouLiu9** [comment]
Disabled proxy in http and SOC and it works again. Thanks so much for helping me out. I do not recall I need to turn these settings off when using older versions. Anyway, very happy that it works now. Thanks for the good work OWASP has done.

**Comment by kingthorin** [comment]
Thanks for confirming
