### ISSUE TITLE
Authentication PUT/POST no longer handling Content-Length header automagically

### ISSUE THREAD

**Issue by someusername123** [zaproxy/zaproxy#7614]
### Describe the bug

I have custom ZAP authentication scripts that have recently stopped adding the Content-Length headers for POST / PUT data requests which has broken their automation. 
If this is intended I can work around it, but I figured I would post a bug report as this appeared after taking the major upgrade to 2.12

### Steps to reproduce the behavior

Create a basic Authentication script that sends a PUT or POST request and observe that the content-length header is not automagically handled as it once was.

### Expected behavior

The expected, or previous behavior I should say, is that the Content-Length header is automatically set depending on the size of the body data.

### Software versions

2.12

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment]
That's by design, while that was convenient ZAP should not be changing the messages from what was crafted by the user or the tools. The scripts (and almost everything) are expected to craft the message as they need. (e.g. We have changed the example Authentication scripts long ago to do that zaproxy/community-scripts#85)

**Comment by knilink** [comment]
@thc202 
would be great and will save a lot of time if there is a warning log for missing content-length.
Also I guess it worth being mentioned in the readme/template 
https://github.com/zaproxy/community-scripts/blob/4e7e4651576eef732f2d4f8920688faad66ac71b/authentication/README.md
