### ISSUE TITLE
False positive for "Modern Web Application"

### ISSUE THREAD

**Issue by peter17** [zaproxy/zaproxy#7617]
### Describe the bug

I scan my website using Zaproxy.

I get the informational alert: "The application appears to be a modern web application. If you need to explore it automatically then the Ajax Spider may well be more effective than the standard one." with:

Evidence: `<a>`

Problem: this was raised by a URL which corresponds to a JPEG image!

Indeed, if I look at the bytes in the image, I find the string "`<a>`".

### Steps to reproduce the behavior

Host an image containing bytes <a> on a website.

Scan the website.

Observe the report.

### Expected behavior

This should not raise the informational alert: "The application appears to be a modern web application".

It makes no sense to deduce that from binary data.

I suggest that the alert should consider either the response body itself (it should be HTML) or the Content-Type header of the response.

### Software versions

I use version 2.12.0

### Would you like to help fix this issue?

- [X] Yes

**Comment by psiinon** [comment]
Thats really strange.
These lines should ensure it just checks HTML responses: https://github.com/zaproxy/zap-extensions/blob/main/addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ModernAppDetectionScanRule.java#L44-L46

What is the content-type in the response?

**Comment by thc202** [comment]
oops, it's missing the return.

**Comment by psiinon** [comment]
Ha! I missed that 🤣

**Comment by kingthorin** [comment]
@peter17 do you want to tackle fixing it?

**Comment by peter17** [comment]
@kingthorin Done, thanks!
