### ISSUE TITLE
untitled1.data file size too large

### ISSUE THREAD

**Issue by gabrielmocanu** [zaproxy/zaproxy#7622]
### Describe the bug

After running zap for more than one week I observed that `/home/zap/.ZAP/session/untitled1.data` file has around 20 GB.
There is a way in zap to resize this file automatically(delete / truncate it) without restarting the container?

### Steps to reproduce the behavior

1. Start a container with [ZAP]
2. Start scanning
3. Check the size of `untitled1.data` from `/home/zap/.ZAP/session/untitled1.data` in the container.

[ZAP]: https://hub.docker.com/r/owasp/zap2docker-stable/the 

### Expected behavior

I need a way to resize that file without restarting the container or any action from outside the container.

### Software versions

owasp/zap2docker-stable:2.11.1

### Would you like to help fix this issue?

- [ ] Yes

**Comment by psiinon** [comment]
ZAP is not designed to be run as a long running service.
For automation we recommend that you start a new ZAP instance for each scan you wish to perform.
FYI the User Group is probably a better place for discussions around these sort of issues: https://groups.google.com/group/zaproxy-users

**Comment by gabrielmocanu** [comment]
Thanks @psiinon !!
