### ISSUE TITLE
Authentication script got error since 2.12.0 due to lack of cookie headers

### ISSUE THREAD

**Issue by tiwgit** [zaproxy/zaproxy#7631]
### Describe the bug

After upgrading ZAP from 2.11.1 to 2.12.0, our custom authentication script got error due to these behavior changes as below.

1. `Content-Length` header is not set automatically.
2. Domain level cookie is not sent.

Here is a sample authentication script.
```
var HttpRequestHeader = Java.type("org.parosproxy.paros.network.HttpRequestHeader");
var HttpHeader = Java.type("org.parosproxy.paros.network.HttpHeader");
var URI = Java.type("org.apache.commons.httpclient.URI");
var AuthenticationHelper = Java.type("org.zaproxy.zap.authentication.AuthenticationHelper");

function authenticate(helper, paramsValues, credentials) {
  var msg = helper.prepareMessage();

  print("Sending GET");
  msg.setRequestHeader(
    new HttpRequestHeader(
      HttpRequestHeader.GET,
      new URI("https://test.lvh.me:8443/"),
      HttpHeader.HTTP11
    )
  );
  helper.sendAndReceive(msg);
  AuthenticationHelper.addAuthMessageToHistory(msg);

  print("Sending POST");
  msg.setRequestHeader(
    new HttpRequestHeader(
      HttpRequestHeader.POST,
      new URI("https://test.lvh.me:8443/"),
      HttpHeader.HTTP11
    )
  );
  msg.setRequestBody("user=test");
  helper.sendAndReceive(msg);

  return msg;
}
```

The first GET request returns a cookie with domain level as below.
```
HTTP/1.1 200 OK
Server: nginx/1.22.0
Date: Fri, 02 Dec 2022 06:48:07 GMT
Content-Type: text/html
Content-Length: 104
Last-Modified: Mon, 20 Jun 2022 08:21:32 GMT
Connection: keep-alive
ETag: "62b02e0c-68"
Cache-Control: no-store
Set-Cookie: __Secure-test=AAA; domain=.lvh.me; secure; httponly; samesite=lax
Accept-Ranges: bytes
```

With ZAP 2.11.1, the second POST request has both `Content-Length` and `Cookie` header as below.
```
POST https://test.lvh.me:8443/ HTTP/1.1
Host: test.lvh.me:8443
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:92.0) Gecko/20100101 Firefox/92.0
Pragma: no-cache
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded
Cookie: __Secure-test=AAA
Content-Length: 9

user=test
```

However, with ZAP 2.12.0, neither of these headers is sent as below.
```
POST https://test.lvh.me:8443/ HTTP/1.1
Host: test.lvh.me:8443
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; x64; rv:105.0esr) Gecko/20010101 Firefox/105.0esr
Pragma: no-cache
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded

user=test
```

### Steps to reproduce the behavior

1. Add the example authentication script above.
2. Configure "Script-based Authentication" and load the authentication script in the context.
3. Add an user to the context.
4. Run spider at the site to run authentication script.

### Expected behavior

The same behavior as 2.11.1 is expected.
1. `Content-Length` header is set automatically.
2. Domain level cookie is sent.

### Software versions

Found Java version 19.0.1
Read custom JVM args from /Users/user/Library/Application Support/ZAP/.ZAP_JVM.properties
Using JVM args: -Xmx10240m -Xms4096m
402 [main] INFO  org.parosproxy.paros.Constant - Backing up config file to /Users/user/Library/Application Support/ZAP/config.xml.bak
411 [main] INFO  org.parosproxy.paros.Constant - Upgraded from 20011001
OWASP ZAP
Version: 2.12.0
Installed Add-ons: [[id=alertFilters, version=14.0.0], [id=ascanrulesAlpha, version=40.0.0], [id=ascanrulesBeta, version=42.0.0], [id=automation, version=0.19.0], [id=bruteforce, version=12.0.0], [id=callhome, version=0.5.0], [id=commonlib, version=1.11.0], [id=custompayloads, version=0.12.0], [id=database, version=0.1.0], [id=diff, version=12.0.0], [id=directorylistv1, version=5.0.0], [id=directorylistv2_3, version=4.0.0], [id=directorylistv2_3_lc, version=4.0.0], [id=domxss, version=14.0.0], [id=encoder, version=0.7.0], [id=exim, version=0.3.0], [id=fileupload, version=1.1.0], [id=formhandler, version=6.1.0], [id=fuzz, version=13.8.0], [id=fuzzdb, version=9.0.0], [id=fuzzdboffensive, version=4.0.0], [id=gettingStarted, version=14.0.0], [id=graaljs, version=0.3.0], [id=graphql, version=0.10.0], [id=help, version=15.0.0], [id=httpsInfo, version=13.0.0], [id=hud, version=0.15.0], [id=importurls, version=9.0.0], [id=invoke, version=12.0.0], [id=jsonview, version=2.0.0], [id=jwt, version=1.0.2], [id=network, version=0.2.0], [id=oast, version=0.13.0], [id=onlineMenu, version=10.0.0], [id=openapi, version=28.0.0], [id=pscanrules, version=44.0.0], [id=pscanrulesAlpha, version=36.0.0], [id=pscanrulesBeta, version=30.0.0], [id=replacer, version=11.0.0], [id=reports, version=0.15.0], [id=requester, version=7.0.0], [id=retest, version=0.4.0], [id=retire, version=0.15.0], [id=reveal, version=5.0.0], [id=saml, version=9.0.0], [id=saverawmessage, version=7.0.0], [id=savexmlmessage, version=0.3.0], [id=scripts, version=33.0.0], [id=selenium, version=15.11.0], [id=soap, version=14.0.0], [id=spiderAjax, version=23.10.0], [id=sqliplugin, version=15.0.0], [id=tips, version=10.0.0], [id=webdrivermacos, version=46.0.0], [id=websocket, version=27.0.0], [id=zest, version=37.0.0]]
Operating System: Mac OS X
Architecture: aarch64
Java Version: Homebrew 19.0.1
System's Locale: ja_JP
Display Locale: ja_JP
Format Locale: ja_JP
Default Charset: UTF-8
ZAP Home Directory: /Users/user/Library/Application Support/ZAP/
ZAP Installation Directory: /Users/user/OwaspZap/ZAP_2.12.0/./
Look and feel: Mac OS X (com.apple.laf.AquaLookAndFeel)

### Screenshots

First GET request
<img width="1175" alt="GET" src="https://user-images.githubusercontent.com/18191015/205246552-30e781c4-f5e9-4c1a-aeba-5bf142726043.png">

Second POST request
with ZAP 2.11.1
<img width="1175" alt="2_11_1_POST" src="https://user-images.githubusercontent.com/18191015/205246678-785d2e68-8673-41ae-ae1f-738ed04e3ef5.png">

with ZAP 2.12.0
<img width="1175" alt="2_12_0_POST" src="https://user-images.githubusercontent.com/18191015/205246760-a93e96fa-0885-467a-961f-8025c2479400.png">

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment]
For the Content-Length see https://github.com/zaproxy/zaproxy/issues/7614#issuecomment-1324173421
