### ISSUE TITLE
False positive in HtAccessScanRule?

### ISSUE THREAD

**Issue by peter17** [zaproxy/zaproxy#7632]
### Describe the bug

When performing a scan with a high threshold on my website, the HtAccessScanRule  is triggered.

I have a `.htaccess` file in the public directory and my Apache server (2.4.52) returns a 403 response with the default content (same as HtAccesScanRuleUnitTest::DEFAULT_BODY).

I notice that Apache will return the same 403 response for any path starting with `.ht` (ex: `.htthisfiledoesnotexist`) so I think the alert is not relevant.

### Steps to reproduce the behavior

Run a scan on a Apache web server with `.htaccess Information Leak` enabled.

The alert will be triggered even if there is no `.htaccess` present.

### Expected behavior

The alert should be triggered only if there is a `.htaccess` available, i.e. a response that is not a 40x and a content that is not HTML.

Also, if a `.htaccess` is really available, IMHO, it should be raised at standard level, not only high level, because `.htaccess` files may contain sensitive data like environment variables.

### Software versions

I use Zap Proxy 2.12.0

### Would you like to help fix this issue?

- [X] Yes

**Comment by psiinon** [comment]
That sounds like a false positive, but its a bit unexpected. 
For info the relevant class is [HtAccessScanRule](https://github.com/zaproxy/zap-extensions/blob/main/addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/HtAccessScanRule.java).
This class extends [AbstractAppFilePlugin](https://github.com/zaproxy/zap-extensions/blob/main/addOns/commonlib/src/main/java/org/zaproxy/addon/commonlib/AbstractAppFilePlugin.java) and that looks like it should ignore 40x responses.

@peter17 can you post the exact HTTP response, obfuscating any sensitive information, like URLs.

**Comment by peter17** [comment]
Hi @psiinon 

Thanks for your answer, I have another scan currently running so I performed the requests using curl:
```
└─$ curl -D - https://REDACTED/.htaccess 
HTTP/2 403 
date: Fri, 02 Dec 2022 10:19:24 GMT
content-type: text/html; charset=iso-8859-1
cf-cache-status: BYPASS
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=ByREDACTEDpa"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
strict-transport-security: max-age=2592000; preload
x-content-type-options: nosniff
server: cloudflare
cf-ray: 77REDACTED29c-CDG
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access this resource.</p>
<hr>
<address>Apache/2.4.54 (Ubuntu) Server at REDACTED Port 443</address>
</body></html>
```
Above, the `.htaccess` file actually exists on my website. Below, the `.htwhatever` file does not exist.
```
└─$ curl -D - https://REDACTED/.htwhatever
HTTP/2 403 
date: Fri, 02 Dec 2022 10:19:45 GMT
content-type: text/html; charset=iso-8859-1
cf-cache-status: BYPASS
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=N0REDACTEDUm"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
strict-transport-security: max-age=2592000; preload
x-content-type-options: nosniff
server: cloudflare
cf-ray: 77REDACTED82-CDG
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access this resource.</p>
<hr>
<address>Apache/2.4.54 (Ubuntu) Server at REDACTED Port 443</address>
</body></html>
```
The responses are identical, so they do not prove the existence of the `.htaccess` file.

Regards

**Comment by kingthorin** [comment]
Yes if you incorrectly return 403 instead of properly returning a 404 it may misbehave.

Since it’s triggering the 403 case there’s obviously no content etc to check.

I guess you could configure a Custom Page (404 type) to treat 403 as an 404, and that would probably address the issue.

**Comment by peter17** [comment]
@kingthorin sure, but it looks like returning a 403 is the default Apache behavior for paths starting with `.ht`...

I can fix this by changing Zap Proxy's configuration but shouldn't this be fixed in the the class itself?

Best regards

**Comment by peter17** [comment]
Also, is it correct that the alert should raise even though the `.htaccess` file is not available?

**Comment by kingthorin** [comment]
401/403 is a special case and yes it’s intentionally alerted on.

Does the server actually return 404 in other cases?

**Comment by peter17** [comment]
Yes, it does:

```
└─$ curl -D - https://REDACTED/.notaccess  
HTTP/2 404 
date: Fri, 02 Dec 2022 12:15:37 GMT
content-type: text/html; charset=iso-8859-1
cache-control: max-age=2678400
cf-cache-status: MISS
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=RaREDACTEDQq"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
strict-transport-security: max-age=2592000; preload
x-content-type-options: nosniff
server: cloudflare
cf-ray: 7REDACTED0-CDG
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
<hr>
<address>Apache/2.4.54 (Ubuntu) Server at REDACTED Port 443</address>
</body></html>
```

**Comment by kingthorin** [comment]
Thanks

**Comment by peter17** [comment]
@kingthorin any suggestion on how to fix this? Would you agree if I make it so the alert is not raised if the Content-Type of the  response is HTML? Best regards

**Comment by kingthorin** [comment]
No because it could be plain text if it’s the actual file or it could be wrapped in json or xml depending on the app.

I’d suggest modifying the isFalsePositive method to make another `.ht*` request if it 404s then alert, otherwise don’t.

**Comment by kingthorin** [comment]
Oh it looks like this rule is already doing some content type handling so ignore those comments. I’d still suggest the status code handling.

**Comment by evgeniy44** [comment]
Hi guys, can I work on this?

**Comment by kingthorin** [comment]
@peter17 I guess you’re not putting a fix together?

**Comment by peter17** [comment]
@evgeniy44 @kingthorin Sure, sorry about this. I started working on this but I was not sure about how to proceed and it finally got out of my mind... Regards

**Comment by kingthorin** [comment]
No problem, thanks for letting us know.

**Comment by evgeniy44** [comment]
I've reproduced this issue in my local environment and can say the following things:
- This alert is thrown with risk level = 'INFO'
- The alert message: "Based on response status code htaccess file may be protected by an authentication or authorization mechanism.". So the message is seems to be correct.
- It never comes to HtAccessScanRule.isFalsePositive() method. AbstractAppFilePlugin throws the alert without this check.
Based on that, I'm unsure if this is a real bug. Or I missed something?
What do you think?
