### ISSUE TITLE
After install program fails to load

### ISSUE THREAD

**Issue by Apextek1** [zaproxy/zaproxy#7639]
### Describe the bug

I  installed OWASP ZAP 2.12.0 on Windows 10 and the install went fine. When i click the icon I get a dialog box that appears and it reads _ "This application requires a Java Runtime Environment 11.0.0. When you click OK it takes you to the Java website where it asks to install Java 8?

I also tried installing OpenJDK17U-jdk_x64_windows_hotspot_17.0.5_8 form Adoptium without success

I understand that Oracle dropped the JRE and it was not included in JDK11. How do we work around that?

Any help would be appreciated

### Steps to reproduce the behavior

See above

### Expected behavior

Expected the config screen to appear

### Software versions

2.12.0

### Would you like to help fix this issue?

- [X] Yes

**Comment by thc202** [comment]
This is a question for the User Group: https://groups.google.com/group/zaproxy-users

Make sure that the `java` command is not version 8 (you seem to have several versions installed now).
