### ISSUE TITLE
Add ESLint to Node JS API

### ISSUE THREAD

**Issue by njmulsqb** [zaproxy/zaproxy#7646]
### Is your feature request related to a problem? Please describe.

No, not really a problem

### Describe the solution you'd like

There should be a linter like added to Node JS API that follows the modern coding patterns and practices and makes the API code compliant to them.

I ran ESlint on my local copy of Node JS API and it gave thousands of errors, so definitely a thing that should be considered

### Describe alternatives you've considered

None.

### Screenshots

![image](https://user-images.githubusercontent.com/47940898/206451813-b236bd2f-e92b-4645-922e-72785b392d4f.png)

### Would you like to help fix this issue?

- [X] Yes

**Comment by njmulsqb** [comment]
Following tasks needs to be done roughly (taken from `users.js`, will be more or less same for all the files since same generator is being used for that.

- [ ] Extra semicolon  
- [ ] More than 1 blank line not allowed 
- [ ] Missing space before function parentheses
- [ ] ["contextId"] is better written in dot notation 
- [ ] A space is required after '{'
- [ ] Unnecessarily quoted property 'contextId' found
- [ ] A space is required before '}'  


Mentioning here so that each one can be solved with a PR of its own and can be tracked.

**Comment by thc202** [comment]
We shouldn't rely on the generator, instead it should be auto formatted and validated in the repo.

**Comment by njmulsqb** [comment]
> We shouldn't rely on the generator, instead it should be auto formatted and validated in the repo. I guess some things might be better changing in the generator but we shouldn't rely solely on the generator to format the code properly.

In this way, each time newly generated code will contain lint issues, wont it be better to stop them from being generated e.g remove addition of semi-colons?

**Comment by thc202** [comment]
As the last part of the sentence says there are things that worth changing but we shouldn't rely just on the generator, the repo should allow to validate and fix the code.

**Comment by njmulsqb** [comment]
> As the last part of the sentence says there are things that worth changing but we shouldn't rely just on the generator, the repo should allow to validate and fix the code.

Can you specify the things that we should rely on generator for from the above list for my understanding?

**Comment by thc202** [comment]
What changes are not fixed by the linter?

**Comment by njmulsqb** [comment]
For reference of recent chat with thc202 in IRC, Eslint needs to be added to CI like this: https://github.com/zaproxy/zap-api-python/blob/master/.github/workflows/ci.yml

**Comment by njmulsqb** [comment]
@thc202 How about using pre-commit hooks with libraries like https://www.npmjs.com/package/husky and use them to ensure that each commit is linted properly? CI implementation wont be required then.

**Comment by thc202** [comment]
We should still validate in CI, local hooks can be bypassed.
