### ISSUE TITLE
Possible false positive in CSP Header test

### ISSUE THREAD

**Issue by davidahall** [zaproxy/zaproxy#7653]
I think there's a false positive in checking for CSP Headers.

From the [ContentSecurityPolicyMissingScanRule ](https://github.com/zaproxy/zap-extensions/blob/main/addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ContentSecurityPolicyMissingScanRule.java) implementation:

```
        if (!cspHeaderFound && !hasMetaCsp(source)
                || (AlertThreshold.LOW.equals(this.getAlertThreshold())
                        && (!xCspHeaderFound || !xWebKitHeaderFound))) {
            // Always report if the latest header isnt found,
            // but only report if the older ones arent present at Low threshold
            newAlert()
                    .setRisk(Alert.RISK_MEDIUM)
                    .setConfidence(Alert.CONFIDENCE_HIGH)
                    .setDescription(getAlertAttribute("desc"))
                    .setSolution(getAlertAttribute("soln"))
                    .setReference(getAlertAttribute("refs"))
                    .setCweId(693) // CWE-693: Protection Mechanism Failure
                    .setWascId(15) // WASC-15: Application Misconfiguration
                    .raise();
        }
```

If the AlertThreshhold is LOW and neither archaic header is found, won't this fire whether the current CSP Header is found or not?

Also -- the current guidance that I've been able to find is that the X- and WebKit- headers are obsolete and should not be used.  Should this logic be 

```
        if (!cspHeaderFound && !hasMetaCsp(source) {
            if (xCspHeaderFound || xWebKitHeaderFound) {
                // Raise an alert about use of archaic CSP header usage
            } else {
                // Raise an alert about no CSP header used at all
            }
        }
```

**Comment by kingthorin** [comment]
It's possible the logic is wrong. The test cases are here: https://github.com/zaproxy/zap-extensions/blob/main/addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/ContentSecurityPolicyMissingScanRuleUnitTest.java

**Comment by davidahall** [comment]
The unit test 'givenCspHeaderAtLowAlertThresholdThenAlertRaised' feels wrong based on the current CSP guidance.  Current guidance is that the 'Content-Security-Policy' header should be used in all cases and that the two older headers are obsolete and should no longer be used.  Based on this, then if a CSP Header is included, then no alert should be raised.  The test should be renamed 'givenCspHeaderAtLowAlertThresholdThenNoAlertRaised' and line 133 should be 'assertThat(alertsRaised.size(), is(0));'

**Comment by kingthorin** [comment]
Your argument seems sounds to me. Are you interested in tackling the changes?

**Comment by davidahall** [comment]
For reference: 

HTTP Headers[¶](https://cheatsheetseries.owasp.org/cheatsheets/Content_Security_Policy_Cheat_Sheet.html#http-headers)

The following are headers for CSP.

    Content-Security-Policy : W3C Spec standard header. Supported by Firefox 23+, Chrome 25+ and Opera 19+

    Content-Security-Policy-Report-Only : W3C Spec standard header. Supported by Firefox 23+, Chrome 25+ and Opera 19+, whereby the policy is non-blocking ("fail open") and a report is sent to the URL designated by the report-uri (or newer report-to) directive. This is often used as a precursor to utilizing CSP in blocking mode ("fail closed")

    DO NOT use X-Content-Security-Policy or X-WebKit-CSP. Their implementations are obsolete (since Firefox 23, Chrome 25), limited, inconsistent, and incredibly buggy.

**Comment by davidahall** [comment]
I've not contributed before; I can give it a shot.

**Comment by kingthorin** [comment]
Are you okay using Git/GitHub? Know how to open a Pull Request etc?

The Dev Guide is here > https://www.zaproxy.org/docs/developer/

You'll need to update the scan rule, unit tests, and the [CHANGELOG.md](https://github.com/zaproxy/zap-extensions/blob/main/addOns/pscanrules/CHANGELOG.md) in the add-on (your update will go in the Unreleased section toward the top, likely under the 'Fixed' subheading ... have a glance around the file for inspiration :wink: ).

**Comment by thc202** [comment]
The help should also be updated, which mentions this exact behaviour.

**Comment by davidahall** [comment]
I've submitted [pull request #4338](https://github.com/zaproxy/zap-extensions/pull/4338) to address this issue
