### ISSUE TITLE
JWT decode support in "Encode/Decode/Hash" tool

### ISSUE THREAD

**Issue by oxdef** [zaproxy/zaproxy#7654]
### Is your feature request related to a problem? Please describe.

JWT is a pretty popular format for tokens in web applications. Therefore it is often needed to decode it while testing web applications. Currently "Encode/Decode/Hash" tool in ZAP doesn't support decoding of JWT and external tools like jwt.io are used in such case.

### Describe the solution you'd like

"Encode/Decode/Hash" tool already has `Base 64` decoding feature so it should be simple to add another panel for JWT into "Decode" tab.

Algorithm for decoding could be:

1. Try to split string by `.` into 3 parts
2. If success then `base64` try to decode first 2 parts and replace the third one with `SIGNATURE` place holder.

In the future "JWT Encode" feature could be implemented but it looks like more complex from UI.

### Describe alternatives you've considered

User can utilize external tools, like jwt.io, for such purpose.

### Screenshots

![owasp-zap-jwt-decode](https://user-images.githubusercontent.com/3337518/207726604-30bd3cdf-d601-4289-bd58-5dcfcb1763dc.png)

### Would you like to help fix this issue?

- [X] Yes

**Comment by kingthorin** [comment]
This might be better suited for: https://github.com/SasanLabs/owasp-zap-jwt-addon/ ?

**Comment by thc202** [comment]
Or Community Scripts add-on.

**Comment by kingthorin** [comment]
Yup https://github.com/zaproxy/community-scripts/tree/main/encode-decode would be a good option too.

**Comment by kingthorin** [comment]
Good point, I'll tackle that.
