### ISSUE TITLE
docker/stable error after 2.12.0 update "Unable to create home directory: /zap/?/.ZAP/"

### ISSUE THREAD

**Issue by trigger1919** [zaproxy/zaproxy#7655]
### Describe the bug

We started to catch an error in our Jenkins pipeline which runs docker/stable. No code changes had been made since last successful launch.

"Unable to create home directory: /zap/?/.ZAP/"

We build our zap image from dockerfile:
```
FROM owasp/zap2docker-stable
RUN ./zap.sh -cmd -addonupdate
```
Building command:
docker build -t "our_docker_image_tag" --no-cache=true --pull=true "path_to_our_dockerfile"

Then run with:
docker run --pull=always --rm --interactive --user 1000 --volume="wrk_dir_on_jenkins":/zap/wrk:rw --volume="path_to_zaplog_on_jenkins":/home/zap/.ZAP/zap.log:rw --env-file "env_file" --env "env_variable" -- "tag_of_our_zap_docker_stable_image" zap.sh -cmd -autorun "path_to_af_config_file"

After the image is downloaded we catch the error:
```

5e0c6c00e2dd: Pull complete
56b1ccf83050: Pull complete
6fcee3c5b75a: Pull complete
Digest: sha256:9c2e18c9634cec911f566d2a23c09ebff0c42506ee25c490f8e0ac4ddd6647de
Status: Downloaded newer image for "our_repo_and_tag_for_zap":latest
Unable to create home directory: /zap/?/.ZAP/
Is the path correct and there's write permission?
```

### Steps to reproduce the behavior

Build and launch docker image according to the description above.

### Expected behavior

The error does not happen.

### Software versions

2.0.12

### Would you like to help fix this issue?

- [ ] Yes

**Comment by ricekot** [comment]
Assuming that you intend to run the script as the `zap` user, could you try using `--user=zap` or `--user=1337`? The image was recently updated to explicitly set the uid for the `zap` user to 1337.

**Comment by trigger1919** [comment]
When trying
docker run --rm --interactive --user 1337 --volume="%cd%":/zap/wrk:rw --volume="%cd%"\zap.log:/home/zap/.ZAP/
zap.log:rw  -- {path_to_docker_image}:latest zap.sh -cmd -version
Found Java version 11.0.16
Available memory: 19008 MB
Using JVM args: -Xmx4752m
2022-12-15 12:23:36,228 main ERROR RollingFileManager (/home/zap/.ZAP//zap.log) java.io.FileNotFoundException: /home/zap/.ZAP/zap.log (Permission denied) j
ava.io.FileNotFoundException: /home/zap/.ZAP/zap.log (Permission denied)
...
2.12.0

**Comment by twolfart** [comment]
Same here, the change of uid broke current toolchain:
```
docker run -v $(pwd):/zap/wrk/ -ti owasp/zap2docker-stable ls -al
...
drwxr-xr-x 1 zap  zap     4096 Dec  6 09:25 webswing
drwxrwx--- 1 1000 1000   12288 Dec 15 09:41 wrk
drwxr-xr-x 2 zap  zap     4096 Jan  2  1970 xml
```

**Comment by trigger1919** [comment]
Ideally, zap user id should be set back to 1000. Changing to 1337 breaks the chain on launches on CI systems, where id 1000 can be a default user for launching a set of nested docker images.

I believe there is a good rationale for changing to 1337 :)

**Comment by ricekot** [comment]
Changing the UID for the `zap` user doesn't _really_ solve the problem of mismatching UIDs of files in mounted volumes. However, I understand the rationale of changing it to 1000 since that is the default UID of a newly created user in most linux systems. There is also the option of making root the default user in the container but I'm not sure if that's a best practice.
