### ISSUE TITLE
Provide context menu to paste out-of-band payloads

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#7665]
Provide context menu in message panels to (optionally generate and) paste out-of-band payloads for all services available (BOAST, Callbacks, Interactsh).

Currently you have to go the options to generate/copy the payloads, e.g:
https://www.zaproxy.org/docs/desktop/addons/oast-support/services/interactsh/options/#active-payloads
https://www.zaproxy.org/docs/desktop/addons/oast-support/services/boast/options/#active-servers

**Comment by psiinon** [comment]
c/o https://twitter.com/sajidbutt09/status/1606159424527036416 😁

**Comment by aryangupta701** [comment]
hello, pease assign this issue to me

**Comment by aryangupta701** [comment]
thankyou, can you please guide me how to work on this issue ?

**Comment by thc202** [comment]
Usually it's preferable to finish ongoing contributions.

**Comment by aryangupta701** [comment]
I had one issue assigned, I have submitted it and now waiting for it to get reviewed. So, in the meanwhile time I thought of seeing new issues. Hope it is fine.

**Comment by thc202** [comment]
Yes, I did say usually. That's to avoid having too many PRs open that might end up stale.

**Comment by aryangupta701** [comment]
Okk I will take care of this, thankyou.

**Comment by aryangupta701** [comment]
Hello I want to work on this issue now. Please guide me.

**Comment by thc202** [comment]
Have you checked the OAST add-on?

**Comment by aryangupta701** [comment]
yes I have checked it, I am not able to understand the payloads part and where the context menu should be present

**Comment by thc202** [comment]
What don't you understand? How they are generated?

The context menu should be present in the places we allow to edit/send an HTTP/WebSocket message (e.g. Manual Request Editor, Break, Fuzzer when editing). This should be added in a generic way, check `ExtensionPopupMenuItem` and its subclasses for ideas, check also which menus are shown in the mentioned places.

**Comment by aryangupta701** [comment]
I got it. Thankyou

**Comment by aryangupta701** [comment]
1. Open ZAP on your computer.

2. Go to the message panel in ZAP where you want to insert the payload.

3. Right-click on the panel and select "Insert Payload" from the context menu.

4. A sub-menu will appear showing the available services, including BOAST and Interactsh.

5. Select the service you want to use (e.g. BOAST or Interactsh).

6. The payload will be automatically generated and inserted into the panel.

**Comment by thc202** [comment]
Yes, for point 6 it should also allow to paste with generating new ones.

**Comment by aryangupta701** [comment]
okay

**Comment by aryangupta701** [comment]
I have a doubt, when the user clicks on `generate and paste payload` the old payloads will also be pasted or only the newly generated payload will be pasted ?

**Comment by kingthorin** [comment]
If the operation is `Generate and Paste OAST Payload` then it’d be a new one. If the operation is just Paste OAST Payload then it should paste the current (old) one.

Only in the locations previously mentioned, ex: where a message can be edited.

**Comment by aryangupta701** [comment]
okay thankyou

**Comment by aryangupta701** [comment]
I am thinking of keeping the following structure: 

Insert New Payload -> BOAST
                                     Call Back
                                     Interactsh

Insert Old Payloads -> BOAST
                                     Call Back
                                     Interactsh

Is this fine ?

**Comment by aryangupta701** [comment]
Is this structure fine?

![Screenshot from 2023-02-06 11-01-28](https://user-images.githubusercontent.com/87857234/216891318-447117b7-dbb2-48e8-ad32-90601c08bd72.png)

**Comment by thc202** [comment]
Looks fine to me, but rather than Old I'd call it Existing or Latest.

**Comment by thc202** [comment]
https://github.com/zaproxy/zaproxy/issues/7665#issuecomment-1418203836

2. It's not just that class it should also be supported in WebSocket messages.

**Comment by aryangupta701** [comment]
okk sure

**Comment by aryangupta701** [comment]
mls*****************qbouzm.odiss.eu. 
Boast generates this kind link should I add any http/https header in it while pasting from context menu, will it be beneficial? 

For eg : https://mls*****************qbouzm.odiss.eu

**Comment by aryangupta701** [comment]
okk. Also one more doubt, if there are many existing Boast payloads then should they all be pasted when I click on `paste existing boast payload` ? 

For eg this : 
![Screenshot from 2023-02-06 22-51-00](https://user-images.githubusercontent.com/87857234/217041333-39072496-3b2c-467c-91ce-f5b08e32cdb4.png)

**Comment by kingthorin** [comment]
I’d say paste the latest.

**Comment by thc202** [comment]
You can also show them as submenu items and allow the user to pick, but latest sounds good.

**Comment by aryangupta701** [comment]
ok, Thankyou. I am going with `latest` option.
