### ISSUE TITLE
Export OpenAPI specifications from ZAP

### ISSUE THREAD

**Issue by roisec** [zaproxy/zaproxy#7667]
### Is your feature request related to a problem? Please describe.

Hi, 
Is there any option to export Openapi specifications from ZAP?
The goal is connecting ZAP to CI tests, by that, I want to export the open API to see the diff between versions, and know the API specifications.
It may help security engineers and developers to know their apps better.

### Describe the solution you'd like

built-in feature in ZAP converts automatically to OpenAPI file.

### Describe alternatives you've considered

I saw an option to export har file and then convert it able to convert to OpenAPI.

### Would you like to help fix this issue?

- [x] Yes

**Comment by thc202** [comment]
Do you mean the OpenAPI specifications that were imported into ZAP? Otherwise there's https://www.zaproxy.org/addons/#addon-levoai

**Comment by roisec** [comment]
No,
I meant export openapi file from traffic that routed through the ZAP proxy.

**Comment by roisec** [comment]
I meant the ability to generate OpenAPI file from traffic that routed through ZAP proxy.

**Comment by buchi-busireddy** [comment]
> I meant the ability to generate OpenAPI file from traffic that routed through ZAP proxy.

@roisec That's exactly what the Levo.ai addon is for. Please let me know if you need any help using it.
Full disclosure: I'm one of the founders of Levo.ai.

**Comment by thc202** [comment]
I think this can be closed since there's already an add-on in the marketplace that provides this feature.
