### ISSUE TITLE
Add ability to set a list of 'additional elements to click' in Automation Framework AjaxSpider job

### ISSUE THREAD

**Issue by trigger1919** [zaproxy/zaproxy#7672]
### Is your feature request related to a problem? Please describe.

Add ability to set a list of additional elements to crawl in Automation Framework AjaxSpider job.

Similarly to what we can do in UI (see screenshot).

### Describe the solution you'd like

A block in AjaxSpider AF config where I can set a list of additional elements to click.

### Describe alternatives you've considered

A block in AjaxSpider AF config where I can set a list of additional elements to click.

### Screenshots

![image](https://user-images.githubusercontent.com/27839647/210063348-c701cffc-44a4-4741-b6eb-03fabd87ffc2.png)

### Would you like to help fix this issue?

- [ ] Yes

**Comment by Vitika9** [comment]
Why I can't see this block in Options AJAX Spider screen, what I am missing?
<img width="524" alt="image" src="https://user-images.githubusercontent.com/79760854/213914416-8f8f3e64-b4f0-4a7a-a1b8-441d134df767.png">

**Comment by Vitika9** [comment]
May I please get assigned to this?

**Comment by thc202** [comment]
Assigned.
