### ISSUE TITLE
Cannot Generate report. No template options presented

### ISSUE THREAD

**Issue by rexprintz79** [zaproxy/zaproxy#7674]
### Describe the bug

After running  a scan successfully I try to generate a report to present to my co workers. However I cannot do this because no template options are presented (HMTL, PDF, ETC.) 

So because of this I cannot create reports and it is rather frustrating. 

Things I tried. 

1. Making sure all add ons were updating
2. Making sure Zap was updated. 
3. Tried different URLS
4. Tried uninstalling and re installing report generation
5. Tried uninstalling and restalling application as a whole. 

Nothing worked. 
![Screen Shot 2023-01-03 at 2 06 57 PM](https://user-images.githubusercontent.com/94565591/210433115-aacab798-7ffb-491e-8005-eb7c3551f989.png)
![Screen Shot 2023-01-03 at 2 07 22 PM](https://user-images.githubusercontent.com/94565591/210433179-4a4d4a75-be22-45c9-ba95-0119b553fb06.png)

### Steps to reproduce the behavior

1. Run a scan
2. Click on generate report 
3. Fill out report details
4. Try to generate report.

### Expected behavior

1. Run a scan
2. Click on generate report
3. Fill out report details
4. Generate report from selecting a report template

### Software versions

Version 2.12.0 

Using a Mac (Monterey)

### Screenshots

![Screen Shot 2023-01-03 at 2 12 48 PM](https://user-images.githubusercontent.com/94565591/210433940-1901fe98-a97a-4bfb-a50e-8445ee19b273.png)

### Errors from the zap.log file

N/A

### Would you like to help fix this issue?

- [X] Yes

**Comment by rexprintz79** [comment]
![Screen Shot 2023-01-03 at 2 40 39 PM](https://user-images.githubusercontent.com/94565591/210437972-c68cff5f-4e9e-453d-a7e5-619f7031d44c.png)

Nothing @thc202

**Comment by thc202** [comment]
By default that should be `/Users/<YourUser>/Library/Application Support/ZAP/reports`, try setting that one. (You can also click the Reset button to restore the defaults).

**Comment by rexprintz79** [comment]
@thc202 Ok 

Good news I was able to find that directory easily... bad news is I cannot seem to save the directory  ON the template directory options. 

Reset does not save my change. and keeps the same (wrong) directory. Maybe I set default to Desktop somehow somewhere else? but am not sure how?  
![Screen Shot 2023-01-03 at 3 05 48 PM](https://user-images.githubusercontent.com/94565591/210441369-dffed09c-7c12-4efb-a02b-0a5a3c5f9420.png)

**Comment by kingthorin** [comment]
This looks like a MacOS permissions issue. We have an existing issue for that, it’s got some suggestions. I don’t have a link handy but perhaps you can search or someone else can add it.

**Comment by thc202** [comment]
As workaround you can copy that directory to the desktop and select that one.

Might be a permission issue but I would have expected that ZAP would still be able to access the home directory (and its contents).

**Comment by psiinon** [comment]
@rexprintz79 have you given ZAP "Full Disk Access" ?
If not then thats the first thing to try.

**Comment by rexprintz79** [comment]
@psiinon @thc202 @kingthorin 

You guys were correct. Permissions issue. I gave ZAP full disk access to the template directory and I was able to make the change... After this I was able to create a report. 

Thank you all for your help, you guys have saved me a lot of headache. I am very grateful.
