### ISSUE TITLE
Challenging issues with ZAP 

### ISSUE THREAD

**Issue by roisec** [zaproxy/zaproxy#7681]
### Is your feature request related to a problem? Please describe.

Hi, 
I have 3 Challenging issues with ZAP and I would like to hear from the experienced people that know ZAP well.
I am working for integrating ZAP within the CI/CD  separate pipe line(nightly run), our effort is to corporate the Zap with (E2E)End to end tests to enrich ZAP with Api requests and then starting active scan for specific attaks.
Currently it's works partially for us but there are three important things we want to improve:
1. Authentication session - our app uses Authorization custom header (not cookie) and when we start the active scan  the scanner uses old session header and the active scan not work properly because uses old deleted session, how do we can configure that ZAP uses the updated session header? 
2. Let's say E2E tests create, edit and delete custom obejets. objects ID's are dynamically generated by the server and the client uses the  the object ID for edit the object. When I started Active scan, the scanner actively create the object but don't know how to use the Object ID for editing  and delete the object (he uses not relevant object Id).Do you have any solution for this? Do you have cache all the responsed parameters and used the for the next requests?
3. The E2E tests uses to edit specific object which created dynamically during the scans, the app uses dynamic URLs like: /api/v1/edit/< uuid >
When we starting the active scan ZAP don't know the dynamic url parameters and can find the relevant object id. How to deal with this problem? 
 
I think ZAP can bring big advantage, However, we are encountering serious problems and would be happy to hear about the possible solutions, if there are any solution.

### Describe the solution you'd like

* There is solution about the HTTP session extension but may not help us with the custom header auth. (https://www.zaproxy.org/docs/desktop/start/features/httpsessions/)
* We know there is the ddc data driven content but it's not relevant for API JSON requests. (https://www.zaproxy.org/docs/desktop/start/features/ddc/)

### Describe alternatives you've considered

None

### Would you like to help fix this issue?

- [X] Yes

**Comment by kingthorin** [comment]
Please don't ask questions as issues - the [ZAP User Group]( https://groups.google.com/group/zaproxy-users) is a much better place for questions.
