### ISSUE TITLE
Automation: Support replacer

### ISSUE THREAD

**Issue by PyterBd** [zaproxy/zaproxy#7686]
### Is your feature request related to a problem? Please describe.

I'm trying to test a pre-production environment that requires HTTP basic auth to access the site (configured this way to prevent crawlers), then within the site use regular form-based authentication.

### Describe the solution you'd like

Replacer within the gui allows Zap to pass basic auth values into all requests within the defined context, adding this to the Authentication Framework would enable the same functionality.

### Describe alternatives you've considered

I have considered defining the `ZAP_AUTH_HEADER_VALUE` before the scan but haven't tested this yet.

### Would you like to help fix this issue?

- [ ] Yes

**Comment by psiinon** [comment]
For info, related to https://github.com/zaproxy/zaproxy/issues/6461 😁

**Comment by thc202** [comment]
As workaround you can configure the replacer through the command line https://www.zaproxy.org/faq/how-do-you-find-out-what-key-to-use-to-set-a-config-value-on-the-command-line/
