### ISSUE TITLE
owasp/zap2docker-bare - 2.12.0 - release process

### ISSUE THREAD

**Issue by rsi21** [zaproxy/zaproxy#7688]
### Describe the bug

Hi all,

I started using the following docker image: owasp/zap2docker-bare in version 2.12.0 last December 2022.
And i was having a CI working properly.

Now I started again CI using the same image and i have proxy issues, and using previous version 2.11.1 it is working again.

So looking at docker hub I saw that image 2.12.0 has been pushed 9 days ago, so it means 2.12.0 image is not the same than 1 month ago.

![image](https://user-images.githubusercontent.com/14235105/212040859-86fab074-013c-4852-97f3-b1edcea8897f.png)

So my concerne is more around the release process, is it normal that a tagged  image has been updated ?

Hope my question is clear,

Thanks

### Steps to reproduce the behavior

Docker pull image owasp/zap2docker-bare in version 2.12.0

### Expected behavior

Retrieve always the same image for a specific version tag.

### Software versions

2.12.0

### Would you like to help fix this issue?

- [ ] Yes

**Comment by psiinon** [comment]
The ZAP User Group is a better place for questions: https://groups.google.com/group/zaproxy-users
But yes, we update the stable and bare docker images once a month as per https://www.zaproxy.org/docs/docker/about/#stable

**Comment by rsi21** [comment]
Thanks @psiinon (get it for questions i will check there, sorry!)
