### ISSUE TITLE
GraphQL addon throws NullPointerException when POST body is empty and content type header is not set

### ISSUE THREAD

**Issue by pf-msi** [zaproxy/zaproxy#7689]
### Describe the bug

GraphQL addon contains class VariantGraphQl which might throw following NPE:

```
79904 [ZAP-ActiveScanner-1] ERROR org.zaproxy.zap.extension.ascanrules.PathTraversalScanRule - Error occurred while scanning with variant org.zaproxy.addon.graphql.VariantGraphQl
java.lang.NullPointerException: null
        at org.zaproxy.addon.graphql.VariantGraphQl.getQuery(VariantGraphQl.java:81) ~[?:?]
        at org.zaproxy.addon.graphql.VariantGraphQl.setMessage(VariantGraphQl.java:46) ~[?:?]
        at org.parosproxy.paros.core.scanner.AbstractAppParamPlugin.scan(AbstractAppParamPlugin.java:93) ~[zap-2.12.0.jar:2.12.0]
        at org.parosproxy.paros.core.scanner.AbstractPlugin.run(AbstractPlugin.java:361) ~[zap-2.12.0.jar:2.12.0]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
```

### Steps to reproduce the behavior

Run active scan on the service producing POST requests with missing (empty) payload and missing content type header. GraphQL addon will fail with NPE as above.

### Expected behavior

Do not throw a NPE. 

### Software versions

ZAP 2.12.0
graphql addon 0.12.0

### Additional context

There seem to be a logical condition bug in https://github.com/zaproxy/zap-extensions/blob/main/addOns/graphql/src/main/java/org/zaproxy/addon/graphql/VariantGraphQl.java#L80-L81 
```
if (!body.isEmpty() && contentTypeHeader == null
                    || contentTypeHeader.contains(HttpHeader.JSON_CONTENT_TYPE)) {
[...]
```
If `body` is empty and `contentTypeHeader` is null, it'll execute the last condition. Probably it's enough to add parenthesis, like
```
if (!body.isEmpty() && (contentTypeHeader == null
                    || contentTypeHeader.contains(HttpHeader.JSON_CONTENT_TYPE))) {
[...]
```
unless such case should be treated in a different way.

### Would you like to help fix this issue?

- [ ] Yes

**Comment by psiinon** [comment]
Good spot!

**Comment by psiinon** [comment]
This is an ideal bug for a new contributor.
Note that in addition to the one line fix we would want a unit test.
If you are interested in working on this then please comment on the issue and we can help you from there 😁

**Comment by Shershon25** [comment]
Hey @psiinon, can I work on this? I'm a newbie and I feel like this will be a good starting point for me.

**Comment by Shershon25** [comment]
Hey! I want to make sure if I am going in the right direction.
I have changed the condition statement. 
Now I have to add a separate unit test for this `graphql` addon that would verify whether 'null' is returned by the specific `getQuery` function at appropriate conditions, right?

**Comment by Shershon25** [comment]
Hey! I have added two unit tests to assert that no parameters were extracted. Can I make a pull request in `zap-extensions` repo so that it can be verified whether all requirements have been met?

**Comment by psiinon** [comment]
@Shershon25 please do!
