### ISSUE TITLE
False positives in Forbidden Redirect

### ISSUE THREAD

**Issue by Perfect-Chaos** [zaproxy/zaproxy#7697]
### Behaviour
The check "External Redirect" (ExternalRedirectScanRule) criticizes a redirect-param because the param is used (in the URI-subdirectory-part) of the following redirect.

### Expected
The check only needs to alert if the domain-part of the redirect can be manipulated.

### Explanation
Hello,

I have a SSO-application which redirects the user back to the requested page after login. One url-parameter (redirect-param) contains the requested subdirectory which cannot be validated because I have absolutely no control over the websites which use the SSO-apllication.
So when a request comes from https://www.testdomain.com/test/subdirectory the redirect-param only contains "/test/subdirectory" while the redirect domain is determined by other, secured mechanisms.

The check "External Redirect" (extension/ascanrules/ExternalRedirectScanRule.java) returns with a high security alert while just saying:
Attack: 6567167381554875494.owasp.org
Evidence: 6567167381554875494.owasp.org

The suggested resolution is:
_Use an "accept known good" input validation strategy, i.e., use an allow list of acceptable inputs that strictly conform to specifications. Reject any input that does not strictly conform to specifications, or transform it into something that does._

As far as I understand, the code of the plugin just checks if a redirect has occured and if the content of the redirect-param is somewhere present in the redirect-payload. It is not checked where the redirect-param is present in the redirect uri (in this case just the subdirectory part, not as domain) or if the domain can be manipulated.

Is this behaviour correct and useful? How should anyone be able to validate unknown subdirectory-parts of a redirect? Can the behaviour be altered in any way?

Thanks for your time and help!

**Comment by kingthorin** [comment]
I believe this is already being fixed in: https://github.com/zaproxy/zap-extensions/pull/4116

**Comment by kingthorin** [comment]
In the future please use the existing/proper issue templates.

**Comment by thc202** [comment]
There's not enough evidence to know if that PR addresses it though.

**Comment by Perfect-Chaos** [comment]
Sorry for not using the correct template as I was unaware of it!!

Yeah correct the redirected uri is `www.testdomain.com/6567167381554875494.owasp.org` which results in an error page but the report states a high risk level.

**Comment by kingthorin** [comment]
Thanks for confirming.

**Comment by thc202** [comment]
Is that the value of the `Location` header?

**Comment by Perfect-Chaos** [comment]
My site uses 302 to redirect and the value "https://www.testdomain.com/6567167381554875494.owasp.org" is transfered via `Location` header.

The alert details are the following:
Reference:
http://projects.webappsec.org/URL-Redirector-Abuse
http://cwe.mitre.org/data/definitions/601.html

CWE Id: 601
WASC Id: 38
Plugin Id: 20019

**Comment by thc202** [comment]
Thank you.
