### ISSUE TITLE
Tools > Options > Target is missing

### ISSUE THREAD

**Issue by recepbalibey** [zaproxy/zaproxy#7706]
Hello.
I am curious if I am able to scan an IP address using OWASP ZAP? It is the web server IP.
As I searched:

> To use OWASP ZAP with an IP address, you will need to set up a target. To do this, open OWASP ZAP and select 'Tools' from the top menu bar. From the drop-down menu, select 'Options'. This will open the ZAP Options window. Select 'Targets' from the left-hand menu, then click 'Add'. Enter the IP address into the 'Address' field and the port number into the 'Port' field. Select 'OK' to save the target.

But I do not see it. I updated from Help sections as well.
![image](https://user-images.githubusercontent.com/47719328/215208922-5a124b6c-c69e-4391-9962-90f6cd8ed374.png)

**Comment by kingthorin** [comment]
Where is that text copied from?

**Comment by recepbalibey** [comment]
I did not find any solutions on google about "how to use an IP address as a target for OWASP ZAP" so I asked the popular tool, new friend ChatGPT.  Sorry, was not available at all always?

**Comment by kingthorin** [comment]
ChatGPT is simply wrong.

Please refer to the Getting Started Guide: https://www.zaproxy.org/getting-started/

Anywhere you specify a target you can use http://<ip> or https://<ip>

**Comment by recepbalibey** [comment]
http://IP
https://IP
Actually, I already tried these options in the first place,but I was getting "connection refused", so I was curious if I was doing something wrong. Thanks for the answer though, I will take a look at the guide again and it is probably about my server.

**Comment by kingthorin** [comment]
Okay, the [ZAP User Group]( https://groups.google.com/group/zaproxy-users) is a much better place for questions. If you don't sort it out.
