### ISSUE TITLE
The Cloud Metadata scan rule should allow for specifying "failure" codes

### ISSUE THREAD

**Issue by trevor-vaughan** [zaproxy/zaproxy#7710]
### Is your feature request related to a problem? Please describe.

Looking at [the code](https://github.com/zaproxy/zap-extensions/blob/main/addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/CloudMetadataScanRule.java#L112) the only check is that the cloud metadata endpoint does not return an error and has something in the body of the message.

For applications that 30x redirect instead of failing on an invalid endpoint, this appears to trigger a false-positive alert.

### Describe the solution you'd like

I would like to either:
* be able to provide a list of "failure" error codes
* be able to provide a list of "success" error codes
* or provide an expected body regex to be checked

### Describe alternatives you've considered

Presently, the check is simple enough that it looks like you either need to disable the check or fork the code to modify the logic.

### Would you like to help fix this issue?

- [ ] Yes

**Comment by trevor-vaughan** [comment]
Hmm....I'm not seeing how those would match up.

I don't want to trust the endpoint, I do want it to be scanned and it's not a CSRF issue or cookie issue.

Or are you saying that users should implement a custom rule config?

**Comment by thc202** [comment]
A 30x is not success.

**Comment by trevor-vaughan** [comment]
🤔 Hmm....I may need to double check with the scanning team. I wonder if it was an internal application redirect instead.

**Comment by kingthorin** [comment]
The `isSuccess` call does account for [Custom Pages](https://www.zaproxy.org/docs/desktop/start/features/custompages/) so you can already customize the handling.

**Comment by trevor-vaughan** [comment]
Ah, got it. @kingthorin I'll give that a go and see what happens.

Thanks all. Will re-open if it turns out to be something that can't be handled with inbuilt capabilities.

**Comment by kingthorin** [comment]
Okay. I'll re-open and assign until I get a chance to take a look at that.

Analyser should be catching redirect behavior for 404s as used to be regularly experienced with ASP.NET apps.

**Comment by kingthorin** [comment]
isSuccess already checks `parent.getAnalyser().isFileExist(msg)` so without very specific details there's nothing further I can do here?

https://github.com/zaproxy/zaproxy/blob/d102f07cb8b3a7a9fe76efcdb3cb21bea7dd59bc/zap/src/main/java/org/parosproxy/paros/core/scanner/AbstractPlugin.java#L740-L749

@thc202 were you suggesting something like:
```diff
    public boolean isSuccess(HttpMessage msg) {
        if (isCustomPage(msg, CustomPage.Type.NOTFOUND_404)
                || isCustomPage(msg, CustomPage.Type.ERROR_500)) {
            return false;
        }
        if (isCustomPage(msg, CustomPage.Type.OK_200) || parent.getAnalyser().isFileExist(msg)) {
            return true;
        }
+        if (!parent.getAnalyser().isFileExist(msg)) {
+            return false;
+        }
        return HttpStatusCode.isSuccess(msg.getResponseHeader().getStatusCode());
    }
```

**Comment by kingthorin** [comment]
Ping @thc202 🙂

**Comment by kingthorin** [comment]
Pssst 😇

**Comment by kingthorin** [comment]
Discussed via email. The addition was agreed to, but in conjunction with the removal of the previous OR.
