### ISSUE TITLE
ScanHeadersAllRequests does not work in the docker image by triggering with API

### ISSUE THREAD

**Issue by maojui** [zaproxy/zaproxy#7712]
### Describe the bug

I set ScanHeadersAllRequests to "true" and started the active scan, but messages show that it did not scan the headers of requests.

It works on ZAP Desktop by selecting the checkbox but fails from trigger by API. In my website target, scanning by OWASP ZAP GUI can always find an alert with high-risk: integer overflow error, however, if I scan through the docker image will not find it. The result of it is when I scan with GUI, request headers can be replaced with some random value, but if I scan with API will not, even if I set ScanHeadersAllRequests to "true".

### Steps to reproduce the behavior

I use `python-owasp-zap-v2.4` for request API, and load the request by sending har request.
Enable only "Integer overflow" scanner and set `option_inject_plugin_id_in_header` and `option_scan_headers_all_requests` to True.
Finally, print out those message headers send by active scan.

Here is my code:

```python
import json
import time
from zapv2 import ZAPv2

CONTAINER_PORT = 6789
apiKey = '123456789'

SCAN_POLICY = "MyScanPolicy"

zap = ZAPv2(apikey=apiKey, proxies={'http': f'http://localhost:{CONTAINER_PORT}', 'https': f'http://localhost:{CONTAINER_PORT}'})
zap.core.new_session()

entry = {"request": { ... } }

zap.core.send_har_request(json.dumps(entry))

zap.ascan.add_scan_policy(SCAN_POLICY)
zap.ascan.disable_all_scanners(SCAN_POLICY)
zap.ascan.enable_scanners(30003, SCAN_POLICY)

assert zap.ascan.set_option_inject_plugin_id_in_header(True) == 'OK'
assert zap.ascan.set_option_scan_headers_all_requests(True) == 'OK'

scanId = zap.ascan.scan(url='http://127.0.0.1/cgi', scanpolicyname=SCAN_POLICY, recurse=True, method=None, postdata=True, inscopeonly=None)

while (int(zap.ascan.status(scanId)) < 100):
    time.sleep(1)

message_ids = zap.ascan.messages_ids(scanId)

for mid in message_ids:
    print('================================')
    har = json.loads(zap.core.messages_har_by_id(mid))
    headers = har['log']['entries'][0]['request']['headers']
    for header in headers:
        print(f'{header["name"]}: {header["value"]}')
```

### Expected behavior

I expected the header in some messages will be replace with a big number, but it did not happen.
All the requests have the same headers.

Toggle `option_inject_plugin_id_in_header` can turn on and off X-ZAP-Scan-ID, so API seems working well. 
I can't figure out what happens on `option_scan_headers_all_requests` :((

```
...
Host: 127.0.0.1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: zh-TW,zh;q=0.8,en-US;q=0.5,en;q=0.3
Token: sjm6iktXud3OrvpD5FDPEBgUqd1gFeiYJJzfBnF9YJTOBcg+UsWckWDpT6e2jXvV6k30aTT9bSA0cYfm56Vn7cpQgMC97mOJ0Qa+Ifj/4xL17JuH/yc9jtEu/OpZ0sd1R5Z8QY1EerJ6wAzC9LzfBMZHPa1uGYv/jm/Ar/+dCOg=
X-Requested-With: XMLHttpRequest
Connection: keep-alive
Referer: http://127.0.0.1/
Cookie: cookie_language=defLang; HTTP_TRACKID=b23ca8f53b224447566d7a1de19671af
X-ZAP-Scan-ID: 30003
================================
Host: 127.0.0.1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: zh-TW,zh;q=0.8,en-US;q=0.5,en;q=0.3
Token: sjm6iktXud3OrvpD5FDPEBgUqd1gFeiYJJzfBnF9YJTOBcg+UsWckWDpT6e2jXvV6k30aTT9bSA0cYfm56Vn7cpQgMC97mOJ0Qa+Ifj/4xL17JuH/yc9jtEu/OpZ0sd1R5Z8QY1EerJ6wAzC9LzfBMZHPa1uGYv/jm/Ar/+dCOg=
X-Requested-With: XMLHttpRequest
Connection: keep-alive
Referer: http://127.0.0.1/
Cookie: cookie_language=defLang; HTTP_TRACKID=b23ca8f53b224447566d7a1de19671af
X-ZAP-Scan-ID: 30003
...
```

### Software versions

OWASP ZAP 2.11.1 
OWASP ZAP 2.12.0 - image ID: 43637dfa04b3

### Would you like to help fix this issue?

- [ ] Yes

**Comment by maojui** [comment]
To scan HTTP requests, make sure you have enabled the 4th bit in option_target_params_injectable. 

```python
assert zap.ascan.set_option_target_params_injectable(8) == 'OK'
```

**Comment by psiinon** [comment]
Thanks for letting us know!
