### ISSUE TITLE
False Positive: ZAP Cross Site Scripting (Persistent) for non-html response

### ISSUE THREAD

**Issue by swetapatel9591** [zaproxy/zaproxy#7713]
We have one endpoint which returns data in plain text for CSV file generation. If some column of this CSV file data has a value as "<script>alert(1);</script>" then it's reporting an XSS Persistent attack with non-existent parameter names.

Sample URL: <base_url>/transactionErrors?format=csv&fileName=SLA

Sample Response: 
ACTIVITY ID,CUSTOMER CODE,CUSTOMER NAME
12Test,,<script>alert(1);</script>

<img width="605" alt="image" src="https://user-images.githubusercontent.com/114212208/215733556-f0f8ba48-a7c7-4dda-96aa-cedc1acd4c96.png">

**Comment by kingthorin** [comment]
Note the Other Info note ;)

**Comment by swetapatel9591** [comment]
Is it a valid false positive? Can you confirm?

**Comment by kingthorin** [comment]
I guess that depends how the csv is processed/used

**Comment by swetapatel9591** [comment]
I also want to know how the scanner is reporting the Parameter value because the reported parameter "comments" is nowhere in the returned string.

**Comment by psiinon** [comment]
Have a look at the full response.
We dont have access to that 😁

**Comment by thc202** [comment]
That's the parameter from where the payload was sent, the persistence might happen in a completely unrelated endpoint.

**Comment by swetapatel9591** [comment]
It's nowhere in the full response. :)

**Comment by swetapatel9591** [comment]
"That's the parameter from where the payload was sent, the persistence might happen in a completely unrelated endpoint." - can you elaborate more on this point? Wants to understand this security issue.

**Comment by thc202** [comment]
https://owasp.org/www-community/attacks/xss/#reflected-and-stored-xss-attacks

Somewhere in your application the user is able to persist/store XSS payloads and at some other point they end up in a a CSV file, that's what's happening. Whether it's an actual security issue depends on how (and where) the CSV content is being used.
