### ISSUE TITLE
Ascan Category summaries not updated

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#7716]
### Describe the bug

The Active scan dialog Category Threshold and Stength columns are not updated when the "Go" buttons are used.
The underlying rules are however set correctly.
https://groups.google.com/g/zaproxy-users/c/AfVXJpiPPYw/m/m4Jg2KmvAQAJ

### Steps to reproduce the behavior

As per https://groups.google.com/g/zaproxy-users/c/AfVXJpiPPYw/m/m4Jg2KmvAQAJ

### Expected behavior

The Threshold and Strength columns should be updated to reflect the new states.

### Software versions

2.12.0

### Screenshots

See https://groups.google.com/g/zaproxy-users/c/AfVXJpiPPYw/m/m4Jg2KmvAQAJ

### Would you like to help fix this issue?

- [ ] Yes

**Comment by kingthorin** [comment]
From discussion on IRC:

> Probably related to #3538 in the end. It's seems related to the state of the panel: if you reset the dialogue it the categories are updated properly.
> It might be easy to fix but whoever tackles it will have to read the code closely, seems to be missing a policy update somewhere in the flow.

**Comment by aayushhyadav** [comment]
I would like to work on this issue.

**Comment by kingthorin** [comment]
I haven’t looked at the code yet, but that explanation seems reasonable to me.

I’d suggest re-reading the IRC comment above and double checking what reset does. It may not change your analysis but hopefully it’ll support your plan.

**Comment by thc202** [comment]
Review what `applyThreshold` does and from where the table model reads the values. The `setValueAt` is called when doing the changes directly in the table.

**Comment by aayushhyadav** [comment]
![image](https://user-images.githubusercontent.com/65152709/219709468-28d7bd93-d4fe-4e94-9c55-8222b263c4dc.png)
This `for` loop in `CustomScanDialog.java` class creates the category panels.
![image](https://user-images.githubusercontent.com/65152709/219714055-c1566dde-ee56-48a8-9d16-7fbc36d57fa8.png)
Here, `setTable` of `PolicyCategoryPanel.java` class is invoked for each panel.
![image](https://user-images.githubusercontent.com/65152709/219714579-262c152c-ff3f-41f7-9416-24d0fab161ac.png)
However, in `setTable` the `if` statement is true only for category 3 (Miscellaneous) and hence, only values for Miscellaneous are populated. Also I believe, the table fetches values from here.
![image](https://user-images.githubusercontent.com/65152709/219715023-b5ad0ca1-8bc2-46da-a399-9de022081c78.png)

**Comment by aayushhyadav** [comment]
![image](https://user-images.githubusercontent.com/65152709/219716007-25d7443f-2121-4d2e-85ca-e793d74d2708.png)
On clicking the go button, this method is called. Again, `for` loop runs only once for category 3 but the values are not reflected in UI in-spite of calling `setAlertThreshold`

**Comment by thc202** [comment]
The number and which categories are shown/iterated is not relevant to this issue. If you want to see more check that you have the `ascanrules*` add-ons installed, from the behaviour you are describing it seems you only have the Script Active Scan Rules which is added by core.

> On clicking the go button, this method is called. Again, `for` loop runs only once for category 3 but the values are not reflected in UI in-spite of calling `setAlertThreshold`

That's the effect of the issue, you should now check the policy (e.g.`PluginFactory`) being updated and the one that the panels have (and at which point is it made different).

**Comment by aayushhyadav** [comment]
![image](https://user-images.githubusercontent.com/65152709/220167860-47658c8b-7d67-4ef8-a079-848b848f3e6e.png)
![image](https://user-images.githubusercontent.com/65152709/220168255-5e4743ab-8151-4176-91dc-29a6090f7806.png)
While creating the UI components, policy object ID is 11109
![image](https://user-images.githubusercontent.com/65152709/220168817-8beee02f-5bf5-4322-b5e1-b7d449118b07.png)
However, when go button is clicked policy object ID is 11603
I believe this is happening due to `scanPolicy = null` in `CustomScanPolicy` in `ScanPolicyPanel` class
I commented `scanPolicy = null` and tried, panels were updating as expected

**Comment by psiinon** [comment]
Cool - PR? 😁

**Comment by thc202** [comment]
Make sure that does not affect existing behaviour, e.g. #7221.
