### ISSUE TITLE
ApplicationErrorScanRule JS / CSS false positives

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#7724]
### Describe the bug

ApplicationErrorScanRule raises alerts if specific error strings are found in any web page.
Some JavaScript frameworks will include these strings as part of their error handling, as could CSS files.
Errors like this are much less likely in static pages like JS / CSS so we should probably only raise them at a LOW threashold.

Code is https://github.com/zaproxy/zap-extensions/blob/main/addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ApplicationErrorScanRule.java

### Steps to reproduce the behavior

Create a JS file using any of the strings https://github.com/zaproxy/zap-extensions/blob/main/addOns/pscanrules/src/main/zapHomeFiles/xml/application_errors.xml
When passively scanned by ZAP an alert will be raised.

### Expected behavior

Error alerts on JS / CSS files will only be raised at a LOW threshold.

### Software versions

2.12.0

### Would you like to help fix this issue?

- [ ] Yes

**Comment by parthn2** [comment]
Hi, Can I work on this?

**Comment by psiinon** [comment]
@parthn2 you can - its now assigned to you!

**Comment by lucifer1702** [comment]
I am interested in  working on this issue

**Comment by kingthorin** [comment]
Thanks @lucifer1702 but as you can see it was just assigned 3 days ago.

**Comment by kingthorin** [comment]
@parthn2 dev docs are here:
https://www.zaproxy.org/docs/developer/

The rule in question is here: https://github.com/zaproxy/zap-extensions/blob/main/addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ApplicationErrorScanRule.java
Unit tests here: 
- https://github.com/zaproxy/zap-extensions/blob/main/addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/ApplicationErrorScanRuleUnitTest.java

You can get some pointers in this PR: https://github.com/zaproxy/zap-extensions/pull/2925

Don't forget to update the help and changelog.

Ref: [threshold](https://www.zaproxy.org/docs/desktop/ui/dialogs/scanpolicy/#threshold)

**Comment by lucifer1702** [comment]
@kingthorin ahh , my bad will look for another one , on a side note is it plausible for me to learn a new language like ruby in the remaining time so that i can contribute to owasp much more .(frankly speaking i always wanted to learn ruby but couldnt cause of the time constraints of my college
)

**Comment by kingthorin** [comment]
Not really the right place for this discussion. I'm not sure if OWASP has any ruby based projects. ZAP is mainly Java. But for my 2 cents most modern languages are largely the same; sure there are minor syntax/convention differences but a loop is a loop is a loop. Feel free to discuss more via [Slack](https://owasp.org/slack) ([self registration](https://owasp.org/slack/invite)).

**Comment by parthn2** [comment]
> @parthn2 dev docs are here: https://www.zaproxy.org/docs/developer/
> 
> The rule in question is here: https://github.com/zaproxy/zap-extensions/blob/main/addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ApplicationErrorScanRule.java Unit tests here: https://github.com/zaproxy/zap-extensions/blob/main/addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/ApplicationErrorScanRuleUnitTest.java
> 
> You can get some pointers in this PR: [zaproxy/zap-extensions#2925](https://github.com/zaproxy/zap-extensions/pull/2925)
> 
> Don't forget to update the help and changelog.
> 
> Ref: [threshold](https://www.zaproxy.org/docs/desktop/ui/dialogs/scanpolicy/#threshold)

Thanks for the resources. They are very helpful to understand the issue.
And sorry for the delay, I had an exam today, so wasn't able to work before! Will create a PR this weekend.

**Comment by code-sparsh** [comment]
@parthn2 Hey! Are you currently working on this issue? I saw that it's been some time since you last talked about it so I thought I should give it a try myself. 
I have done the required changes on my local to fix the issue. So if you aren't working on it, I can take up the issue. 

Will be waiting for your reply before I start a pull request :)

**Comment by code-sparsh** [comment]
@psiinon @kingthorin Should I open up the PR?

**Comment by kingthorin** [comment]
Sure. Don’t forget unit tests, and CHANGELOG.
