### ISSUE TITLE
Stability Issue with Websocket Connections in version 2.12.0

### ISSUE THREAD

**Issue by knilink** [zaproxy/zaproxy#7730]
### Describe the bug

After upgrading to version 2.12.0, the issue of maintaining stable websocket connections has been observed when there are multiple active connections.

To try to resolve the issue, the following steps have been taken but didn't work:
  - Uninstalling all websocket-related add-ons.
  - Enabling "Forwarding all Websocket communication."
  - Adding `ws://.*` and `wss://.*` exclusions to the context file.

### Steps to reproduce the behavior

  1. Start the Zaproxy container and open it in webswing:
    `docker run --rm -it -p 8080:8080 -p 8090:8090 owasp/zap2docker-stable:s2023-02-06 zap-webswing.sh`
  2. Start a websocket server (in this case, `jmalloc/echo-server`):
    `docker run --rm -it -p 3000:8080 jmalloc/echo-server`
  3. Start chrome with proxying:
    `google-chrome --incognito --proxy-server="localhost:8090" --ssl-proxy="localhost:8090" --ignore-certificate-errors --user-data-dir=/tmp/zaptest`
  4. Go to `http://192.168.1.2:3000/.ws` (assuming the host's IP is `192.168.1.2`), and open more pages to establish more active websocket connections.

Upon following these steps, some of the existing connections will be disconnected.

### Expected behavior

Websocket connections should remain connected, at least as stable as in version 2.11 or with a configuration option to maintain stability.

### Software versions

The latest version that worked correctly was `owasp/zap2docker-stable:s2022-10-03` with version `2.11.1`. The current latest version `owasp/zap2docker-weekly:w2023-02-06` has not resolved the issue.

### Screenshots

![image](https://user-images.githubusercontent.com/17878530/217735344-00e0f5c8-60fb-4a99-adb3-a10a152e0d48.png)

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment]
Thanks for reporting!
