### ISSUE TITLE
commonlib handles only JSON Objects causing issues with Web Cache Deception scan rule

### ISSUE THREAD

**Issue by nate-thegrate** [zaproxy/zaproxy#7736]
### Describe the bug

```
[ZAP-ActiveScanner-0] ERROR org.zaproxy.zap.extension.ascanrulesAlpha.WebCacheDeceptionScanRule
 - net.sf.json.JSONException: A JSONObject text must begin with '{' at character 1 of []
```

I'm getting this error multiple times during the active scan. Sometimes it shows an empty list, and other times it's a list of JSON objects (e.g. `at character 1 of [{"key1":"val1"},{"key2":"val2"}]`)

### Steps to reproduce

1. Enable [Web Cache Deception](https://www.zaproxy.org/docs/alerts/40039/)
2. Scan a website that sometimes uses JSON arrays `[]` instead of JSON objects `{}`

### Expected behavior

The scan should be able to handle JSON arrays.

I could be wrong though—if this scan rule is making calls that aren't supposed to return arrays, then I guess it's a problem with the website I'm scanning, and we can close this issue right away.

### Software versions

OWASP ZAP
Version: 2.12.0

All marketplace addons are installed & up-to-date.
<details>
<summary>Installed Add-ons:</summary>
<br>
[[id=accessControl, version=8.0.0],
[id=alertFilters, version=15.0.0], [id=allinonenotes,
version=2.0.0], [id=amf, version=3.0.0], [id=ascanrules,
version=52.0.0], [id=ascanrulesAlpha, version=42.0.0],
[id=ascanrulesBeta, version=44.0.0],
[id=attacksurfacedetector, version=1.1.4], [id=authhelper,
version=0.2.0], [id=authstats, version=2.0.0],
[id=automation, version=0.24.0], [id=beanshell,
version=7.0.0], [id=browserView, version=5.0.0],
[id=bruteforce, version=12.0.0], [id=bugtracker,
version=4.0.0], [id=callgraph, version=5.0.0], [id=callhome,
version=0.6.0], [id=codedx, version=9.0.0], [id=commonlib,
version=1.13.0], [id=communityScripts, version=15.0.0],
[id=coreLang, version=15.0.0], [id=custompayloads,
version=0.12.0], [id=database, version=0.1.0], [id=diff,
version=12.0.0], [id=directorylistv1, version=5.0.0],
[id=directorylistv2_3, version=4.0.0],
[id=directorylistv2_3_lc, version=4.0.0], [id=domxss,
version=14.0.0], [id=encoder, version=1.0.0],
[id=evalvillain, version=0.1.1], [id=exim, version=0.4.0],
[id=fileupload, version=1.1.0], [id=formhandler,
version=6.1.0], [id=fuzz, version=13.9.0], [id=fuzzdb,
version=9.0.0], [id=fuzzdboffensive, version=4.0.0],
[id=gettingStarted, version=14.0.0], [id=graaljs,
version=0.3.0], [id=graphql, version=0.13.0], [id=groovy,
version=3.1.0], [id=help, version=15.0.0], [id=help_ar_SA,
version=1.0.0], [id=help_bs_BA, version=9.0.0],
[id=help_es_ES, version=10.0.0], [id=help_fil_PH,
version=3.0.0], [id=help_fr_FR, version=10.0.0],
[id=help_id_ID, version=3.0.0], [id=help_ja_JP,
version=10.0.0], [id=help_ms_MY, version=1.0.0],
[id=help_pt_BR, version=11.0.0], [id=help_ru_RU,
version=2.0.0], [id=help_tr_TR, version=2.0.0],
[id=help_zh_CN, version=3.0.0], [id=highlighter,
version=8.0.0], [id=hud, version=0.16.0],
[id=imagelocationscanner, version=4.0.0],
[id=importLogFiles, version=6.0.0], [id=importurls,
version=9.0.0], [id=invoke, version=12.0.0], [id=jruby,
version=8.0.0], [id=jsonview, version=2.0.0], [id=jwt,
version=1.0.3], [id=jython, version=12.0.0], [id=kotlin,
version=1.1.0], [id=levoai, version=0.2.0], [id=neonmarker,
version=1.5.0], [id=network, version=0.6.0], [id=oast,
version=0.14.0], [id=onlineMenu, version=10.0.0],
[id=openapi, version=32.0.0], [id=packpentester,
version=0.1.0], [id=packscanrules, version=0.0.1],
[id=paramdigger, version=0.1.0], [id=plugnhack,
version=13.0.0], [id=portscan, version=10.0.0],
[id=pscanrules, version=45.0.0], [id=pscanrulesAlpha,
version=37.0.0], [id=pscanrulesBeta, version=31.0.0],
[id=quickstart, version=36.0.0], [id=reflect,
version=0.0.11], [id=regextester, version=2.0.0],
[id=replacer, version=12.0.0], [id=reports, version=0.19.0],
[id=requester, version=7.1.0], [id=retest, version=0.5.0],
[id=retire, version=0.19.0], [id=reveal, version=5.0.0],
[id=revisit, version=4.0.0], [id=saml, version=10.0.0],
[id=saverawmessage, version=7.0.0], [id=savexmlmessage,
version=0.3.0], [id=scripts, version=35.0.0], [id=selenium,
version=15.11.0], [id=sequence, version=6.0.0], [id=soap,
version=17.0.0], [id=spider, version=0.2.0], [id=spiderAjax,
version=23.11.0], [id=sqliplugin, version=15.0.0], [id=sse,
version=12.0.0], [id=svndigger, version=4.0.0], [id=tips,
version=10.0.0], [id=tokengen, version=15.0.0],
[id=treetools, version=8.0.0], [id=viewstate,
version=3.0.0], [id=wappalyzer, version=21.18.0],
[id=webdriverlinux, version=51.0.0], [id=webdrivermacos,
version=51.0.0], [id=webdriverwindows, version=50.0.0],
[id=websocket, version=28.0.0], [id=zest, version=38.0.0]]
</details>

Operating System: Windows 10
Architecture: amd64
Java Version: Oracle Corporation 18.0.2.1
System's Locale: en_US
Display Locale: en_GB
Format Locale: en_US
Default Charset: UTF-8
ZAP Home Directory: C:\Users\17202\OWASP ZAP\
ZAP Installation Directory: C:\Program Files\OWASP\Zed Attack Proxy\.\
Look and Feel: FlatLaf Light (com.formdev.flatlaf.FlatLightLaf)

### Errors from the zap.log file

```
[ZAP-ActiveScanner-0] ERROR org.zaproxy.zap.extension.ascanrulesAlpha.WebCacheDeceptionScanRule - A JSONObject text must begin with '{' at character 1 of []
net.sf.json.JSONException: A JSONObject text must begin with '{' at character 1 of []
	at net.sf.json.util.JSONTokener.syntaxError(JSONTokener.java:499) ~[json-lib-2.4-jdk15.jar:?]
	at net.sf.json.JSONObject._fromJSONTokener(JSONObject.java:972) ~[json-lib-2.4-jdk15.jar:?]
	at net.sf.json.JSONObject._fromString(JSONObject.java:1201) ~[json-lib-2.4-jdk15.jar:?]
	at net.sf.json.JSONObject.fromObject(JSONObject.java:165) ~[json-lib-2.4-jdk15.jar:?]
	at net.sf.json.JSONObject.fromObject(JSONObject.java:134) ~[json-lib-2.4-jdk15.jar:?]
	at org.zaproxy.addon.commonlib.http.ComparableResponse.getAllPaths(ComparableResponse.java:471) ~[?:?]
	at org.zaproxy.addon.commonlib.http.ComparableResponse.bodyTreesStructureHeuristic(ComparableResponse.java:416) ~[?:?]
	at org.zaproxy.addon.commonlib.http.ComparableResponse.compareWith(ComparableResponse.java:162) ~[?:?]
	at org.zaproxy.zap.extension.ascanrulesAlpha.WebCacheDeceptionScanRule.initialTest(WebCacheDeceptionScanRule.java:157) ~[?:?]
	at org.zaproxy.zap.extension.ascanrulesAlpha.WebCacheDeceptionScanRule.scan(WebCacheDeceptionScanRule.java:78) ~[?:?]
	at org.parosproxy.paros.core.scanner.AbstractPlugin.run(AbstractPlugin.java:361) ~[zap-2.12.0.jar:2.12.0]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
```

**Comment by kingthorin** [comment]
Looks like ComparableResponse needs to handle arrays and not assume objects when calculating tree paths for JSON responses.

**Comment by kingthorin** [comment]
I’ve started to look into fixing this.

**Comment by nate-thegrate** [comment]
Yay! Thanks y'all, this is awesome!

**Comment by kingthorin** [comment]
I’ll get the rule add-on tweaked next week and release both.

**Comment by thc202** [comment]
Tweaked?

**Comment by kingthorin** [comment]
To require the right version of commonlib.

**Comment by thc202** [comment]
That's not necessary, there are no binary changes.

**Comment by kingthorin** [comment]
Okay I’ve kicked off the commonlib release
