### ISSUE TITLE
Support for authentication details in OpenAPI add-on

### ISSUE THREAD

**Issue by cedricbu** [zaproxy/zaproxy#7739]
### Is your feature request related to a problem? Please describe.

When using ZAP over API, I was using the "forced user" to make all my requests authenticated, including retrieval of the OAS definition using the OpenAPI extension.

I am currently migrating to Automation, and thus I am planning to use the OpenAPI job to retrieve and load OASes. However, the openapi job currently does not have a "user" element, unlike activeScan and spider, and thus openapis' apiUrl may fail in case the OAS URL requires authentication.

### Describe the solution you'd like

Having a `user` element in openapi job, which is currently not present (https://github.com/zaproxy/zap-extensions/blob/main/addOns/openapi/src/main/resources/org/zaproxy/zap/extension/openapi/resources/openapi-max.yaml), which would be used when `apiUrl` is defined.

### Describe alternatives you've considered

There would be alternatives, such as scripting, or downloading the file in a separate way and then use apiFile.
However, it somehow feels like the cleanest solution would be to use an existing user session.

### Would you like to help fix this issue?

- [X] Yes

**Comment by psiinon** [comment]
Its worth nothing that the OpenAPI add-on does not support importing an API definition using an authenticated user at all, not just via the AF plan 😁
