### ISSUE TITLE
Requestor GUI misbehaviour

### ISSUE THREAD

**Issue by ArkaprabhaChakraborty** [zaproxy/zaproxy#7740]
I noticed this weird glitching of the requestor options bar. See the send opinion gets glitched between the buttons. The glitching goes away after I extend it fully but ideally it shouldn't be there.
![Screenshot from 2023-02-16 21-09-56](https://user-images.githubusercontent.com/58482073/219415101-29f2f0f2-b4be-4cc4-966b-276fa0574546.png)

Suggestion: probably go for double bars instead of a single long one and change the send button into an icon like ones used for mails or just basically an arrow with a hovertext

**Comment by ArkaprabhaChakraborty** [comment]
> I noticed this weird glitching of the requestor options bar. See the send opinion gets glitched between the buttons. The glitching goes away after I extend it fully but ideally it shouldn't be there. ![Screenshot from 2023-02-16 21-09-56](https://user-images.githubusercontent.com/58482073/219415101-29f2f0f2-b4be-4cc4-966b-276fa0574546.png)
> 
> Suggestion: probably go for double bars instead of a single long one and change the send button into an icon like ones used for mails or just basically an arrow with a hovertext

Also moving up the "open with requester" into the top instead of having the manual request editor at the top seems more plausible :). I like the requestor more :P.

**Comment by thc202** [comment]
This is the same as #3961.
