### ISSUE TITLE
GET forms complaining about potential CSRF attacks

### ISSUE THREAD

**Issue by Chemaclass** [zaproxy/zaproxy#7741]
### Describe the bug

It doesn’t make sense to protect GET requests from CSRF attacks. However, if the form doesn't have a "hidden csrf token" the program complains with a "Warning - Medium level", which is mixed up with other potential real warnings, eg POST requests.

More details: https://security.stackexchange.com/questions/115794/should-i-use-csrf-protection-for-get-requests

### Steps to reproduce the behavior

Load any website with a form with method GET request, and without a "hidden CSRF token",
then you will see a "Warning - Medium level" saying that you need a CSRF token.

### Expected behavior

Hidden CSRF token should be expected for non-GET form requests.

### Software versions

Latest 2.12
<img width="421" alt="Screenshot 2023-02-16 at 17 08 21" src="https://user-images.githubusercontent.com/5256287/219422373-c37428f7-7628-4ac7-8d12-5494f50833aa.png">

### Screenshots

It's a `form method="get"` request, but still showing the Medium Risk warning:
<img width="843" alt="Screenshot 2023-02-16 at 17 10 30" src="https://user-images.githubusercontent.com/5256287/219422869-63aed6a6-54d0-4efa-8abe-83c9e3ae0e60.png">

>**Note**: The work around I found in the meanwhile is to add the hidden csrf token... but it seems a bit overwhelming for a GET request.

### Would you like to help fix this issue?

- [ ] Yes

**Comment by kingthorin** [comment]
I agree that those could be skipped/ignored since tall the data is being leaked via the URL anyway. In the mean time:
- You can ignore certain forms: https://www.zaproxy.org/docs/desktop/ui/dialogs/options/ruleconfig/
- You could setup alert filters: https://www.zaproxy.org/docs/desktop/addons/alert-filters/
