### ISSUE TITLE
ZAP 2.12.0-stable works on and off.

### ISSUE THREAD

**Issue by coltonfreeman26** [zaproxy/zaproxy#7743]
### Describe the bug

Good day all,
We are consuming your owasp/zap2docker-stable:2.12.0 image. We do make some changes to it as we have to rebase it but we try to mirror it as closely as possible. I have been testing it against your upstream image and have been getting the same results. 
Yesterday both images were able to run the full and baseline scans just a generic `./zap-baseline-scan.py -t https://www.google` today however both are throwing the error `Failed to access summary file /home/zap/zap_out.json`. The 2.11.1 image works fine for us thus far. 
Also there is one other issue we are running into with mounting files. We are trying to mount `/tmp/zap:/zap/wrk:rw` then run 
`docker run -d -it -v /tmp/zap:/zap/wrk:rw <image> /bin/bash`. After we exec in and try to run any scan we get a `Bad message` error on the mounted volume.
Long story short I was wondering if there is an issue with the frequency of how often the scan works. Yesterday was hit or miss but they did work and today we are getting nothing but failures. Do you have any advice for how to fix that `Bad message` error or is that only fixable with running as user root?

### Steps to reproduce the behavior

`docker run -d -it -v /tmp/zap:/zap/wrk:rw <image> /bin/bash`
`docker exec -it \[container id\] /bin/bash`
`zap-full-scan.py -t https://www.zaproxy.org -r pen-test-report.html -w pen-test-report.md -J pen-test-report.json -x pen-test-report.xml | grep PASS | tee /zap/wrk/passed.txt`
Output varies. Sometimes it is the `errno74 Bad message` or `Failed to access summary file /home/zap/zap_out.json` we do get once in a while `ZAP failed to start`
When running the zap-cli command we get an unknown command so I am guessing that has been removed.

### Expected behavior

Running basic scans does not result in any errors such as `failed to create file` `cannot access directory` `Bad message` on files and directories mounted `ZAP failed to start` 

### Software versions

We are rebasing our image off of python-3.9.16 which in turn is based off Red Hats UBI8 image. We have made the adjustments needed and it has worked for for us recently.
```
zap@74374ae12814:/zap$ pip3 show  python-owasp-zap-v2.4 
Name: python-owasp-zap-v2.4
Version: 0.0.21
Summary: OWASP ZAP 2.12 API client
Home-page: https://www.zaproxy.org/
Author: ZAP development team
Author-email: 
License: ASL2.0
Location: /usr/local/lib/python3.9/site-packages
Requires: requests, six
Required-by: 
```

### Errors from the zap.log file

No zap.log file created.

### Additional context

Please let me know if I can provide any more information. I am not too familiar with Zap but would love to try and help out.

### Would you like to help fix this issue?

- [ ] Yes

**Comment by coltonfreeman26** [comment]
Everything works as expected when running as root.

**Comment by thc202** [comment]
Sounds more like a problem with the host/env rather than of the images. In any case you have to provide more details (e.g. ZAP log file, script output) about the problems you are seeing.

**Comment by psiinon** [comment]
The fact that it worked yesterday but failed today implies to me that its a problem on your side - the stable image did not change.
I think it is related to the way you are mounting the drive, or something to do with the drive you are mounting.
Whats the environment you are running in?
Is this environment stable?

**Comment by psiinon** [comment]
No problem, and thanks for letting us know!
