### ISSUE TITLE
DOM XSS scan rule should bypass internal browser requests

### ISSUE THREAD

**Issue by salviolorenzo** [zaproxy/zaproxy#7746]
### Describe the bug

When running a Dynamic API scan, the reported results seem to be flagging a call to `https://content-signature-2.cdn.mozilla.net/chains/remote-settings.content-signature.mozilla.org-**.chain`
![Screenshot 2023-02-21 at 8 49 52 AM](https://user-images.githubusercontent.com/40444290/220412762-fdb8e361-eef8-4cf3-97b6-5871992c911c.png)

This is occurring regardless of the contents of the API being scanned. 
To demonstrate this issue, I created a based express api found here: https://github.com/salviolorenzo/zap-openapi-example
Running the api/index.js and then running a scan against that will always have a content-type warning for the above mentioned mozilla.net endpoint

### Steps to reproduce the behavior

1. Run an OpenAPI defined local API -- example defined here: https://github.com/salviolorenzo/zap-openapi-example
2. Follow instructions here to set up a scan pointed at the local API: https://appdefensealliance.dev/casa/tier-2/ast-guide/dynamic-scan
3. Open results-full file to see Unexpected Content-Type error

### Expected behavior

The scan should not return warnings that are outside the scope of the scanned API. The call to `https://content-signature-2.cdn.mozilla.net/` appears to occur as a result of standing up an instance of Firefox, and as such should be ignored from the report. 

### Software versions

owasp/zap2docker-stable:2.12.0
Image ID: 3666744972aa

### Would you like to help fix this issue?

- [ ] Yes

**Comment by psiinon** [comment]
I'm guessing the browser was started as a result of running the DOM XSS rule.
The latest reports allow you to specify which domains to report issues on - I would recommend using those.

**Comment by salviolorenzo** [comment]
@psiinon Appreciate the quick response! I cannot seem to find documentation on specifying domains to report on. Would you mind pointing me in the right direction? Thanks!

**Comment by psiinon** [comment]
https://www.zaproxy.org/docs/desktop/addons/report-generation/
How are you currently generating the reports?
The Report Generation add-on will work from the desktop, the Automation Framework and the API 😁

**Comment by kingthorin** [comment]
Are you talking about this alert? https://github.com/zaproxy/zaproxy/blob/af431ed622ca4c97c8d591233aec197a1733b561/docker/scripts/scripts/httpsender/Alert_on_Unexpected_Content_Types.js#L53

**Comment by salviolorenzo** [comment]
@kingthorin Yep that's the one!

**Comment by salviolorenzo** [comment]
@psiinon currently generating reports via command line with the docker image. Essentially a variation of this command: 
`docker run -p 8080:8080 -v $(pwd):/zap/wrk/:rw 
-t owasp/zap2docker-stable zap-api-scan.py 
-t https://example.com -f openapi-P 8080 
-c zap-casa-api-config.conf 
-x results-full.xml`

**Comment by kingthorin** [comment]
@psiinon / @thc202 / @ricekot shall we add `application/octet-stream` and `binary/octet-stream` to the list of "known" content types in the script?

**Comment by psiinon** [comment]
> @psiinon currently generating reports via command line with the docker image. Essentially a variation of this command: `docker run -p 8080:8080 -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-api-scan.py -t https://example.com -f openapi-P 8080 -c zap-casa-api-config.conf -x results-full.xml`

Possibly .. although I dont think this is really the correct solution - another rule could easily be triggered.

**Comment by thc202** [comment]
https://github.com/zaproxy/zaproxy/issues/7746#issuecomment-1438970082
IMO that's a workaround, we should ensure that DOM XSS bypasses those requests (e.g. by respecting the Global Excludes).
