### ISSUE TITLE
despite exclusion of a URL it is still displayed under results

### ISSUE THREAD

**Issue by 8linkz** [zaproxy/zaproxy#7753]
### Describe the bug

Hallöchen,

since this is my first report please do not bash :-).

It seems to be a combination of several errors for me.

I have examined my own website with ZAP standard settings via manual explore (via Firefox).
and there are always firefox typical URLs to exclude. 
I noticed that I have to exclude a URL 2x for the proxy, so that it disappears in the "Sites" display.
disappears in the "Sites" display.

This leads to the fact that one and the same entry is now in there twice (exclusion proxy). 
But in the alerts the URL is not removed and you cannot delete it collectively.
If you select the alert -> right click delete, then only one entry is deleted instead of the complete list. 
the complete list.

Maybe I'm just doing something wrong - thanks for your work.

### Steps to reproduce the behavior

VMWare Kali 04/2022 Iso Image completely updated
installed ZAP 2.12.0 via apt
started ZAP and updated only the installed addons
restarted ZAP
no persistent session selected
selected manual explore and entered http://blinkz.info 
Launch browser without HUD
briefly waited and then excluded all Firefox typical URLs 
Start Spider on http://blinkz.info
then start Ajax-Spider on http://blinkz.info
If both are finished you have to wait about 5 minutes and then the URL will appear
https://firefox-settings-attachments.cdn.mozilla.net under "Sites
If you exclude this for the proxy, you have to do this 2x and it will be listed 2x. The entries of the above URL will not be removed from the alerts.
Right click on the alert -> Delete -> does not delete the e.g. 1000 entries but only one of them.

![grafik](https://user-images.githubusercontent.com/90318259/220888855-b62fde5a-679c-4760-b15a-d69b089df521.png)
![grafik](https://user-images.githubusercontent.com/90318259/220888974-3e50d97b-2d21-4c6a-b150-f90f0e52b504.png)
![grafik](https://user-images.githubusercontent.com/90318259/220889186-4a1d2dca-f121-44c1-8aec-79a25e2e6a32.png)

After deleting the number is only reduced by 1 and as you can see in the screenshot above there should be more 1299 deleted entries.
![grafik](https://user-images.githubusercontent.com/90318259/220889264-79989829-1a81-4a17-849e-5ab96a48f8ce.png)

You may use my website for testing.

### Expected behavior

1. no duplications in the exclusion window

2. if you delete the whole alert, then all entries under it should be deleted as well, not just one.

### Software versions

OWASP ZAP
Version: 2.12.0

Installed Add-ons: [[id=alertFilters, version=15.0.0],
[id=ascanrules, version=52.0.0], [id=automation,
version=0.24.0], [id=bruteforce, version=12.0.0],
[id=callhome, version=0.6.0], [id=commonlib,
version=1.13.0], [id=database, version=0.1.0], [id=diff,
version=12.0.0], [id=directorylistv1, version=5.0.0],
[id=domxss, version=14.0.0], [id=encoder, version=1.0.0],
[id=exim, version=0.4.0], [id=formhandler, version=6.1.0],
[id=fuzz, version=13.9.0], [id=gettingStarted,
version=14.0.0], [id=graaljs, version=0.3.0], [id=graphql,
version=0.13.0], [id=help, version=15.0.0], [id=hud,
version=0.16.0], [id=invoke, version=12.0.0], [id=network,
version=0.6.0], [id=oast, version=0.14.0], [id=onlineMenu,
version=10.0.0], [id=openapi, version=32.0.0],
[id=pscanrules, version=45.0.0], [id=quickstart,
version=36.0.0], [id=replacer, version=12.0.0], [id=reports,
version=0.19.0], [id=requester, version=7.1.0], [id=retest,
version=0.5.0], [id=retire, version=0.19.0], [id=reveal,
version=5.0.0], [id=scripts, version=35.0.0], [id=selenium,
version=15.11.0], [id=soap, version=17.0.0], [id=spider,
version=0.2.0], [id=spiderAjax, version=23.11.0], [id=tips,
version=10.0.0], [id=webdriverlinux, version=51.0.0],
[id=websocket, version=28.0.0], [id=zest, version=38.0.0]]

Operating System: Linux
Architecture: amd64
Java Version: Debian 17.0.6
System's Locale: en_US
Display Locale: en_GB
Format Locale: en_US
Default Charset: UTF-8
ZAP Home Directory: /home/mp/.ZAP/
ZAP Installation Directory: /usr/share/zaproxy/./
Look and Feel: FlatLaf Light (com.formdev.flatlaf.FlatLightLaf)

### Would you like to help fix this issue?

- [ ] Yes

**Comment by kingthorin** [comment]
You'd probably be better off setting or editing Global Excludes, vs. excluding from the proxy. "Exclude from Proxy" is specific it only excludes things from the Proxy functionality of ZAP not the Spiders or Active Scan (so if you re-introduce one of those URLs/hosts via active scan or either spider then you'd still see it).

Deleting Alerts based on the alert heading should work fine to remove them all, I've never encountered an issue with that.

Note: The DOM XSS rule launches browsers which are Firefox by default, and the AJAX Spider uses Firefox by default.

**Comment by thc202** [comment]
https://www.zaproxy.org/docs/desktop/ui/dialogs/options/globalexcludeurl/

**Comment by thc202** [comment]
The alerts not being deleted is most likely #2593.

**Comment by 8linkz** [comment]
thank you for your quick response.

As far as I noticed, the alerts are properly deleted when the URL is in scope. If this was removed afterwards (from sites), then it does not seem to work.

**Comment by 8linkz** [comment]
@kingthorin I don't exclude the URL via the menu but via Sites -> Right click URL -> Exclude Proxy -> this results in the entry appearing in Proxy but remaining under "Sites" as well. If you do this a second time, the URL disappears from Sites and appears twice in Proxy. And this is only with this URL - I mean I have seen until now no other where I noticed this.

**Comment by kingthorin** [comment]
I’ll have to test, there should be no correlation between Proxy Exclusion and changes to the site tree. Are you 100% sure you didn’t hit Delete in the context menu?

**Comment by thc202** [comment]
https://github.com/zaproxy/zaproxy/issues/7753#issuecomment-1441612107

It's not about being in scope or not but how they are deleted.

https://github.com/zaproxy/zaproxy/issues/7753#issuecomment-1441627370

That's most likely because of the number of requests being made, that some were deleted does not prevent new ones from being added (especially if they are being sent in rapid succession while/after being deleted).

**Comment by kingthorin** [comment]
Hmmm okay I wouldn’t have guessed that. However, it still leaves questions about the behavior. Passive scan queue re-adding it?

**Comment by 8linkz** [comment]
i test it again - I had to wait a bit and opened the alerts. Took about 5 minutes?

the numbers are then exploded in addition as you can see in the screenshot, the display is rendered distorted. I wanted to report this anyway, had this among other things with javascript files, different websites and also with a bare metal installation.



In the single view it looks ok, but if you select the alert type, then the font chops up

![grafik](https://user-images.githubusercontent.com/90318259/220907801-19185914-852b-4a27-bf94-bb1dbb4170fe.png)
![grafik](https://user-images.githubusercontent.com/90318259/220907568-e894cba1-a377-41bd-b517-d9519650deef.png)

**Comment by thc202** [comment]
Can you show the AJAX Spider tab?

**Comment by 8linkz** [comment]
![grafik](https://user-images.githubusercontent.com/90318259/220909362-7c7eebe7-869d-4395-b386-9a341f425aa2.png)

**Comment by thc202** [comment]
OK, so the browser you mentioned left open is the one manually launched from ZAP, right?

**Comment by 8linkz** [comment]
I start the browser from ZAP via manual explore + http://blinkz.info then wait a short time -> exclude them from the proxy (the spider is then also not interested in them) and start first the normal spider and is this ready the Ajax. The browser of manual explore is the complete time open.

![grafik](https://user-images.githubusercontent.com/90318259/220911265-32ba114f-c784-4d43-bc42-ed4a1f2a29a9.png)

**Comment by 8linkz** [comment]
https://youtu.be/UZyNVqI0xDo

**Comment by kingthorin** [comment]
The video is worth watching. My guess is that it's a browser that the AJAX Spider failed to kill. I'll try to reproduce.

**Comment by thc202** [comment]
The video shows #2593. It's the launched browser not AJAX Spider's one. (The requests would show with the AJAX Spider icon moreover the AJAX Spider has a restrictive access policy, the PEM requests are not allowed.)

**Comment by kingthorin** [comment]
If it’s the launched browser then shouldn’t Exclude from Proxy actually be in play though?

**Comment by thc202** [comment]
The PEMs are excluded after being proxied and after all the alerts were raised (queue is at zero and the CPU usage already dropped).

**Comment by kingthorin** [comment]
Okay, around 633 it is a different exclusion than the original set.
