### ISSUE TITLE
Automation UI sets active scan max threads to 0, makes active scan to hang

### ISSUE THREAD

**Issue by sseelmann** [zaproxy/zaproxy#7754]
### Describe the bug

When playing with the automation UI I managed to set the active scan `threadPerHost` property to `0` which made the active scan do nothing and hang forever.

### Steps to reproduce the behavior

1. In the ZAP UI create a new automation
2. Select a profile that contains the `activeScan`, e.g. OpenAPI or Full Scan
3. Configure the "Active Scan" job
4. Check the "Show Advanced Options" checkbox
5. Open the "Advanced" tag and observe that `Threads per Host` is set to `0`
6. Save the "Active Scan" job
7. Save the automation plan and observe that property `threadPerHost` is set to `0`

### Expected behavior

1. Automation UI should set threads per host to the default value (2)
2. Active scan should fail or at least log a warning if threads per host is set to 0

### Software versions

2.12.0

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment]
The hang was fixed in #7579. But we should change Automation Framework to stop doing that.

**Comment by kingthorin** [comment]
Is this fixed following @psiinon's PR?
