### ISSUE TITLE
Run after build to dmg and click Check Update to get an error.

### ISSUE THREAD

**Issue by decuple-dream** [zaproxy/zaproxy#7756]
### Describe the bug

Hello Team! I'm going to build and use 'zaproxy', 'zap-extension' and 'zap-hud' on my MacBook in an arrch64 environment.
In the latest github, the build seems to have been successful even though the following message appears:
```
> Task :zap:distMacArm64
created: /Users/Eo/zap/zaproxy/zap/build/distributions/ZAP_2.13.0-SNAPSHOT_aarch642.dmg

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.6/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 1m 41s
```

<img width="1039" alt="스크린샷 2023-02-25 오전 4 01 15" src="https://user-images.githubusercontent.com/67303734/221268482-1bd66461-c32b-4939-9194-0394d9c5c34f.png">

### Steps to reproduce the behavior

1. Build zaproxy, zap-hud, and zap-extension all.
2. Build to dmg, move to Application, and run.
3. Click the Update Check button to confirm the update.
4. On the other hand, the latest release dmg works well.

### Expected behavior

The marketplace or update should be successful even when building it yourself.

### Software versions

version 2.13.0 - SNAPSHOT

### Errors from the zap.log file

```
2023-02-25 03:56:51,048 [ZAP-cfu] ERROR ExtensionCallHome - Expected '200 OK' but got '404 Not Found'
java.io.IOException: Expected '200 OK' but got '404 Not Found'
	at org.zaproxy.addon.callhome.ExtensionCallHome.sendServiceRequest(ExtensionCallHome.java:203) ~[?:?]
	at org.zaproxy.addon.callhome.ExtensionCallHome.getServiceData(ExtensionCallHome.java:216) ~[?:?]
	at org.zaproxy.addon.callhome.ExtensionCallHome.getCheckForUpdatesData(ExtensionCallHome.java:225) ~[?:?]
	at org.zaproxy.addon.callhome.ExtensionCallHome.get(ExtensionCallHome.java:235) ~[?:?]
	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate.getRemoteConfiguration(ExtensionAutoUpdate.java:1000) ~[zap-2.13.0-SNAPSHOT.jar:2.13.0-SNAPSHOT]
	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate$4.run(ExtensionAutoUpdate.java:1128) ~[zap-2.13.0-SNAPSHOT.jar:2.13.0-SNAPSHOT]
```

### Would you like to help fix this issue?

- [X] Yes

**Comment by kingthorin** [comment]
That’s normal. 2.13 update manifests don’t exist yet.

**Comment by kingthorin** [comment]
The [ZAP Developer Group]( https://groups.google.com/group/zaproxy-develop) is a much better place for such discussions.

**Comment by decuple-dream** [comment]
Hi, @kingthorin, thanks to reply! 
So, is "Error encountered. Please check manually for new updates" an error that appears because there are no new updates?
The market place also shows an error like that, so does that mean that all of them are installed in my Zap?
Thanks for letting us know about the forum.

**Comment by kingthorin** [comment]
No the error appears because you built a release version that doesn’t exist.

**Comment by decuple-dream** [comment]
I don't know what you mean. Can't I use the market place when I build my own?

**Comment by kingthorin** [comment]
Version 2.13 doesn't exist.

**Comment by thc202** [comment]
Technically it's a dev release (i.e. `SNAPSHOT`) not 2.13.0. I think before we used `dev` in such case.

**Comment by decuple-dream** [comment]
<img width="471" alt="스크린샷 2023-02-25 오전 9 47 36" src="https://user-images.githubusercontent.com/67303734/221326350-8e00e1da-e0b7-4e86-bf92-6dd70b67ced8.png">

Could you explain why Marketplace is not available more easily?

**Comment by kingthorin** [comment]
1) You can just run from source without actually building/installing.
2) @thc202 has submitted a fix so that CFU will treat snapshots as dev versions for updates.
3) The 2.13 update manifests won’t exist until just a few days before we actually release 2.13.

**Comment by decuple-dream** [comment]
Thank you for taking your precious time. @kingthorin, @thc202

**Comment by thc202** [comment]
For the record, this is now addressed.
