### ISSUE TITLE
zaproxy doesn't work with localhost URL on podman, even when the local network is accessible

### ISSUE THREAD

**Issue by t1u1** [zaproxy/zaproxy#7757]
### Describe the bug

Running the baseline scan on `https://example.com` works fine. Which means there is no problem with the podman installation.

However, running the baseline scan on `http://localhost:5173` doesn't produce any output, even after waiting for 30 minutes. The container just hangs and I have to kill it with `podman kill`

### Steps to reproduce the behavior

An http server is running on port 5173. It logs requests so that I can tell if a request is being made by zaproxy to it.

Command to begin the scan:

`podman run --network=host  -t owasp/zap2docker-stable zap-baseline.py -t http://localhost:5173 -d`

I see the following output:
```
2023-02-25 04:17:46,735 Trigger hook: cli_opts, args: 1
2023-02-25 04:17:46,735 Using port: 56455
Using the Automation Framework
2023-02-25 04:17:46,737 Starting ZAP
2023-02-25 04:17:46,737 Params: ['/zap/zap-x.sh', '-cmd', '-port', '56455', '-host', '0.0.0.0', '-config', 'database.recoverylog=false', '-config', 'api.disablekey=true', '-config', 'api.addrs.addr.name=.*', '-config', 'api.addrs.addr.regex=true', '-addonupdate', '-addoninstall', 'pscanrulesBeta']
```

And then it hangs.

### Expected behavior

It should scan the given URL, or atleast output what the error is.

I know that the URL is accessible within the container, because if I run `/bin/bash` in the container, and `curl http://localhost:5173`, it works.

### Software versions

I am using the `stable` docker image.

I tried to get the version info via `-z -suppinfo` but no version is printed.

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment]
Provide the contents of the zap.log.

**Comment by t1u1** [comment]
Where do I find `zap.log`? I mounted a directory for `/zap/wrk/` . In that a `zap.yml` gets created. But there is no `zap.log` created. This is true even for the run with `https://example.com` (which is successful).

**Comment by thc202** [comment]
https://www.zaproxy.org/faq/where-does-zap-put-its-logs/ `~/.ZAP`

**Comment by t1u1** [comment]
Thanks, I found out the logs, and also an update: it worked after running the same command multiple times.

* I first tried `./zap-baseline.py -t http://localhost:5173/ -d` which failed.
* In the same container instance, I then tried `./zap-baseline.py -t https://example.com/ -d` which failed too.
* Then I ran the command for example.com again, and it worked!
* Then I ran the command for localhost again and it worked!

The logs are attached here: https://gist.github.com/t1u1/3889a1bca96d38a73376c417a6d11b6f

There are three log files for three scenarios:
* failure for localhost
* success for example.com
* success for localhost

**Comment by t1u1** [comment]
> Seems like a networking or timing issue.

I can't see why though, especially while accessing localhost. `curl` inside the container and browser both work fine for the localhost server.

**Comment by thc202** [comment]
I'd suggest trying with the weekly image the issue #3798 is preventing ZAP from being properly initialised.

**Comment by t1u1** [comment]
the weekly image is working fine! thanks :+1: 

I am closing this issue.

I hope there's a new stable release soon
