### ISSUE TITLE
Check for unsafe TLS versions (TLS 1.0 and 1.1)

### ISSUE THREAD

**Issue by FiveOFive** [zaproxy/zaproxy#7760]
### Is your feature request related to a problem? Please describe.

Many vulnerability scanners and pentests will report unsafe TLS version support. I have not seen a scan rule or addon for this in ZAP. Is there a way already to test TLS versions? And if not, would there be interest in adding one? I'd be interested in helping to add it, though my schedule is a little tight in the immediate future. So if anyone is especially excited about it, feel free to jump ahead of me.

Thanks! 

### Describe the solution you'd like

Alerts for unsafe TLS versions. Would a passive scan rule be the correct place for this?

### Describe alternatives you've considered

Currently using other scanning tools in addition to ZAP to get this information.

### Would you like to help fix this issue?

- [X] Yes

**Comment by thc202** [comment]
See #6918.

**Comment by kingthorin** [comment]
I think you'd be better off using [Qualys](https://www.ssllabs.com/ssltest/), [O_Saft](https://owasp.org/www-project-o-saft/), or nmap scripts.

The JRE even disables cruddy SSL/TLS depending on which JRE you're using, so leveraging a Java based tool for testing such isn't the most wonderful plan.

**Comment by kingthorin** [comment]
Also, as a tester; SSL/TLS findings are kinda filler, or symptoms or greater issues.

**Comment by FiveOFive** [comment]
Thanks for the quick responses. That makes sense that the JRE is challenging for SSL/TLS testing and that it is better or at least easier to use other tools. We can close this.
