### ISSUE TITLE
Make a Pro Version

### ISSUE THREAD

**Issue by hakdogpinas** [zaproxy/zaproxy#7762]
### Is your feature request related to a problem? Please describe.

I think it's time to sell this and looks like it's more better than burpsuite pro. I wanted to buy this so the developer will have more money to have budget and to fasten the development on this one.

### Describe the solution you'd like

I think it's time to sell this and looks like it's more better than burpsuite pro. I wanted to buy this so the developer will have more money to have budget and to fasten the development on this one.

### Describe alternatives you've considered

I think it's time to sell this and looks like it's more better than burpsuite pro. I wanted to buy this so the developer will have more money to have budget and to fasten the development on this one.

### Would you like to help fix this issue?

- [X] Yes

**Comment by psiinon** [comment]
Thank you for your words of encouragement 😁 
We are actually looking for ways to fund ZAP development better, but we do still want to keep ZAP as open source. There are plenty of closed source commercial web security tools out there, but very few OSS ones that are actively maintained.
BTW you can already fund ZAP development: https://www.zaproxy.org/supporters/

**Comment by thc202** [comment]
Closing since this is not an issue in ZAP itself. Further discussion can happen in the [OWASP ZAP Developer Group
](https://groups.google.com/g/zaproxy-develop).
