### ISSUE TITLE
Do not report insecure methods on APIs

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#7772]
### Describe the bug

Prompted by https://twitter.com/shuckle/status/1632778237452378112
Methods like PUT and PATCH are validly used by API calls so we probably shouldnt flag these on API endpoints, is those that return structured data like JSON and XML.
The relevant code is https://github.com/zaproxy/zap-extensions/blob/main/addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/InsecureHttpMethodScanRule.java

### Steps to reproduce the behavior

1. Explore an app that uses methods like PUT / PATCH for its API
2. Perform an active scan with the Insecure HTTP Method rule enabled
3. See the Insecure HTTP Method alert raised

### Expected behavior

No sure alerts should be raised for APIs

### Software versions

Latest rules

### Would you like to help fix this issue?

- [ ] Yes

**Comment by code-sparsh** [comment]
Can I be assigned to this? I have gone through the java file mentioned above.

**Comment by psiinon** [comment]
@code-sparsh assigned 😁

**Comment by code-sparsh** [comment]
Hi, just want to clear out some confusion. As per the issue, we don't need to flag PUT/PATCH methods as Insecure if the server is sending JSON or XML back as a response. And for any other response types (like JS), it should call it insecure. Am I right in understanding this?

**Comment by psiinon** [comment]
Thats my suggestion, yes. But if other people have any views on this I'd love top hear them...

**Comment by code-sparsh** [comment]
Hi, can you please confirm these changes. 
https://github.com/code-sparsh/zap-extensions/commit/0271869d3997ed335ee7e9554e49f4744d17cfac

Also, is there any need to do changes in Unit Tests for this commit? 

Actually, this would be my first PR so that's why I might be acting like a noobie. Sorry for that.

**Comment by kingthorin** [comment]
Looks reasonable. Yes the unit tests should be updated to test the revised behaviour. The help content should be updated to explain or note the behaviour.

**Comment by code-sparsh** [comment]
Actually I don't think there's any need to change the unit tests for this (based on what I understood after reading the code).

I updated the help content, as suggested.
Should I go ahead with the pull request?

**Comment by thc202** [comment]
The tests should cover the new behaviour. Feel free to open the PR anytime, it can be worked on as needed.

**Comment by thc202** [comment]
Note that the changelog entry should be added under the Unreleased section.

**Comment by code-sparsh** [comment]
@kingthorin I will keep that in mind from next time. Thanks
