### ISSUE TITLE
The certificate for odiss.eu expired on 3/7/2023

### ISSUE THREAD

**Issue by alqomar** [zaproxy/zaproxy#7773]
### Describe the bug

Hi, thanks for this wonderful software. 
When testing xss/redirect found out that the certificate for BOAST server URL (odiss.eu) was expired on 3/7/2023.
Payload (xxxxxxxxxxxxx.odiss.eu) still work, able to poll connections. However the expired certificate worrying.

### Steps to reproduce the behavior

1. Visit payload url in browser e.g https://xxxxxxxxxxxxxxx.odiss.eu
2. Firefox will block connection due to expired certificate
or
1. Check expiration date at https://crt.sh/?q=odiss.eu

### Expected behavior

BOAST server should have valid certificate

### Software versions

2.12.0

### Additional context

Sorry if this is not the right template/place to report this issue.

### Would you like to help fix this issue?

- [ ] Yes

**Comment by kingthorin** [comment]
Thanks, we'll reach out to the maintainer and find out what's up.

**Comment by thc202** [comment]
This is not an issue in ZAP.
