### ISSUE TITLE
Enable 'rules.domains.trusted' config for 10017 (Cross-Domain JavaScript Source File Inclusion)

### ISSUE THREAD

**Issue by MarkAuderli** [zaproxy/zaproxy#7775]
There is rule configuration we can use to prevent the following rule from triggering an alert

**90003** (Sub Resource Integrity Attribute Missing - Passive/beta)

To stop this raising an alert for trusted domains we can set '**rules.domains.trusted**' in the config

Can we use this setting in the following rule also?

**10017** (Cross-Domain JavaScript Source File Inclusion - Passive/release)

This seems related to me, we can secure both using an integrity hash, but for our site we cant do that as the third party script changes as updates are released. We trust the src, but we cant specify that in the 10017 rule right now.

**Comment by psiinon** [comment]
Yes, I think the 10017 rule should support trusted domains.
This should be a relatively easy change - just duplicate the "trustedDomains code from https://github.com/zaproxy/zap-extensions/blob/main/addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/SubResourceIntegrityAttributeScanRule.java to https://github.com/zaproxy/zap-extensions/blob/main/addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CrossDomainScriptInclusionScanRule.java and add some unit tests.
Flagged as a `good first issue` 😁

**Comment by CVamsi27** [comment]
Hello, I would like to work on this.
