### ISSUE TITLE
Please enable 'Issues' for the repo zaproxy/zap-api-dotnet

### ISSUE THREAD

**Issue by gmaran23** [zaproxy/zaproxy#7779]
### Is your feature request related to a problem? Please describe.

I'd be nice to collaborate with others on enhancements, right here in Github. 

### Describe the solution you'd like

Could you enable 'Issues' for the Dot Net API repo?

https://github.com/zaproxy/zap-api-dotnet

### Describe alternatives you've considered

None

### Would you like to help fix this issue?

- [X] Yes

**Comment by thc202** [comment]
Issues have been enabled in the repo.
