### ISSUE TITLE
maxAlertsPerRule for activeScan job

### ISSUE THREAD

**Issue by 3XC1T3D** [zaproxy/zaproxy#7784]
### Is your feature request related to a problem? Please describe.

Because you can not set maxAlertsPerRule in activeScan, the reports are very bloated.

### Describe the solution you'd like

I would like to have a possibilty to configure maxAlertsPerRule also for the activeScan like it is possible for passiveScan

### Describe alternatives you've considered

unfortunately there is no alternative

### Would you like to help fix this issue?

- [ ] Yes

**Comment by 3XC1T3D** [comment]
Hi @thc202 ,

due to the merge from https://github.com/zaproxy/zaproxy/pull/7869 this request is complete or not?

Best Regards

**Comment by thc202** [comment]
No, this requires further changes in the Automation ad-on.

**Comment by 3XC1T3D** [comment]
Oh thank you for the hint 😅

So i'll wait till the changes are done.

Thank you for your effort 👍

**Comment by 3XC1T3D** [comment]
Hi @thc202 ,

we are running the owasp/zap2docker-bare:latest Docker Image but we are still getting the Warning: Unrecognised parameter for job activeScan : maxAlertsPerRule

Could you give me a hint, how i recognize when this option is in the zap2docker-bare Docker Image?

best regards

**Comment by thc202** [comment]
The add-on was not yet released, in the meantime you would have to use `-live` or `-weekly`.
