### ISSUE TITLE
Scan freezes on newer macbooks (2021)

### ISSUE THREAD

**Issue by zhannaavanesova** [zaproxy/zaproxy#7802]
Hello,

I am seeing an issue with running a scan on a newer macbook pro (2021, Apple M1 Max), it is extremely slow and it usually freezes around 44-46%. The scan takes several hours to complete, this has been tested on 2 different 2021 macbooks and it is the same behavior. The same scan seems to run fine on a 2018 macbook pro (2.6 GHz 6-Core Intel Core i7) and it completes in about 10ish minutes. Is this a known issue and is there a workaround? I am running the quick start automated scan using only traditional spider.

Thanks in advance!

**Comment by zhannaavanesova** [comment]
ZAP version 2.12.0
openjdk version “11.0.11” 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

**Comment by thc202** [comment]
Did you install the dmg? That uses amd64 JRE. If the one you have installed is an arm64 try launching ZAP with that one instead.

**Comment by thc202** [comment]
@zhannaavanesova ping

**Comment by SecT0uch** [comment]
I also experience the same issue on Manjaro Linux x64:
zaproxy-weekly 2023_04_04-1
openjdk version "11.0.18" 2023-01-17
OpenJDK Runtime Environment (build 11.0.18+10)
OpenJDK 64-Bit Server VM (build 11.0.18+10, mixed mode)

ZAP's Firefox opened but always happens on the ZAP interface.

I don't know if this is related

**Comment by thc202** [comment]
If you call the `zap.sh` script (bundled in the [installation dir](https://www.zaproxy.org/faq/where-is-zap-installed/#mac-os))  directly you can use the `JAVA_HOME` env var (if not the default Java).

**Comment by thc202** [comment]
Alternatively you can use the [Cross Platform Package](https://www.zaproxy.org/download/) which will use the default JRE.

**Comment by thc202** [comment]
Closing, there's no info to address the possible issue. (It would be great to know if using the arm64 JRE helped or not.)
