### ISSUE TITLE
Config properties for `ajaxSpider.allowedResources` are ignored for new homes

### ISSUE THREAD

**Issue by sseelmann** [zaproxy/zaproxy#7809]
### Describe the bug

For an automated scan I want to modify (actually disable) the AJAX spider allowed resources. The properties are defined in a config file. I use a new/empty directory so the default config is copied (printed to output). But when running ZAP the default allowed resources config is used.

### Steps to reproduce the behavior

1. Create properties file to overwrite `ajaxSpider.allowedResources` (note that `ajaxSpider.numberOfBrowsers` is only included for demonstration purpose)

```
$ cat bug-allowed-resources.properties
ajaxSpider.allowedResources.allowedResource(0).enabled=false
ajaxSpider.allowedResources.allowedResource(1).enabled=false
ajaxSpider.numberOfBrowsers=2
```
2. Create a minimal automation file
```
$ cat bug-allowed-resources.yaml
env:
  contexts:
    - name: Default Context
      urls:
        - https://example.com
jobs: []
```
3. Run ZAP (in docker, create a new dir)
```
$ docker run -it --rm \
  -v $(pwd):/zap/wrk \
  -w /zap/wrk \
  owasp/zap2docker-stable \
  zap.sh -dir /zap/wrk/bug-allowed-resources -cmd -configfile  /zap/wrk/bug-allowed-resources.properties -autorun /zap/wrk/bug-allowed-resources.yaml
...
385 [main] INFO  org.parosproxy.paros.Constant - Copying default configuration to /zap/wrk/bug-allowed-resources/config.xml
...
```
4. Check the created `bug-allowed-resources/config.xml` file. Observe that the requested changes for `ajaxSpider.allowedResources` from the config file are not applied. (but note that the change for `ajaxSpider.numberOfBrowsers` is applied!)
```
$ grep -A12 "<ajaxSpider" bug-allowed-resources/config.xml
    <ajaxSpider version="6">
        <numberOfBrowsers>2</numberOfBrowsers>
        <allowedResources>
            <allowedResource>
                <regex>^http.*\.js(?:\?.*)?$</regex>
                <enabled>true</enabled>
            </allowedResource>
            <allowedResource>
                <regex>^http.*\.css(?:\?.*)?$</regex>
                <enabled>true</enabled>
            </allowedResource>
        </allowedResources>
    </ajaxSpider>

```

### Expected behavior

The created `config.xml` includes the requested changes from the config file.

### Software versions

2.12.0

### Additional context

Workaround: run the `zap.sh` a 2nd time after the `config.xml` was initially created

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment]
Could you tell why you are disabling them?

**Comment by sseelmann** [comment]
Maybe related, if not then let me know and I'll create a separate issue.

I encountered another strange behavior for the form handler config. If I configure more than 3 form handler fields only the first 3 are applied to the `config.xml`, the remaining are some other (default?) form handler fields.

My properties file:
```
ajaxSpider.allowedResources.allowedResource(0).enabled=false
ajaxSpider.allowedResources.allowedResource(1).enabled=false
ajaxSpider.numberOfBrowsers=2
formhandler.fields.field(0).fieldId=foo
formhandler.fields.field(0).value=1234
formhandler.fields.field(0).enabled=true
formhandler.fields.field(1).fieldId=bar
formhandler.fields.field(1).value=5678
formhandler.fields.field(1).enabled=true
formhandler.fields.field(2).fieldId=baz
formhandler.fields.field(2).value=a-b-c
formhandler.fields.field(2).enabled=true
formhandler.fields.field(3).fieldId=qux
formhandler.fields.field(3).value=x-y-z
formhandler.fields.field(3).enabled=true
```

The resulting `formhandler` section in the config.xml (only the first 5 fields included, there are more). Note that the config for the 4th field `qux` (index 3) is not there:
```
    <formhandler version="1">
        <fields>
            <field>
                <fieldId>foo</fieldId>
                <value>1234</value>
                <enabled>true</enabled>
            </field>
            <field>
                <fieldId>bar</fieldId>
                <value>5678</value>
                <enabled>true</enabled>
            </field>
            <field>
                <fieldId>baz</fieldId>
                <value>a-b-c</value>
                <enabled>true</enabled>
            </field>
            <field>
                <fieldId>(?i)_?back[-_]?(?:link|uri|url)?</fieldId>
                <value>https://zap.example.com</value>
                <enabled>true</enabled>
                <regex>true</regex>
            </field>
            <field>
                <fieldId>(?i)_?bg[-_]?colou?r</fieldId>
                <value>#FFFFFF</value>
                <enabled>true</enabled>
                <regex>true</regex>
            </field>

```

**Comment by sseelmann** [comment]
> Could you tell why you are disabling them?

Our application includes various 3rd party servies (Google Tag Manager, TrackJS for error reporting, Intercom chat, Osano cookie consent). Especially Intercom and Osano then show up in the UI and the AJAX spider attempts to interact with them. Ofc I could ask to deploy a variant of the application without those resources, but disabling/removing the allowed resources also does the trick.

**Comment by thc202** [comment]
Thank for the answer and the report of the `formhandler` issue.
