### ISSUE TITLE
Issue from https://github.com/zaproxy/zaproxy/issues/7301

### ISSUE THREAD

**Issue by mihaiursulego** [zaproxy/zaproxy#7811]
### Describe the bug

Hello guys,

I have again the same issue specified in the https://github.com/zaproxy/zaproxy/issues/7301 which was introduced in w2022-09-26. Could you please check?

Best regards,
Mihai Ursu

### Steps to reproduce the behavior

Same error as on  https://github.com/zaproxy/zaproxy/issues/7301

### Expected behavior

To be able to run

### Software versions

w2022-09-26

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment]
Please provide the details/steps to reproduce the issue you are having, I'm excluding `.*` from the proxy and still able to access the API.
You should also use the latest version, if not already.

**Comment by thc202** [comment]
Please provide the stacktrace.

**Comment by thc202** [comment]
I can see there's a bug when adding everything to pass-through and accessing the API with HTTPS but those are not the settings from the last time.

**Comment by thc202** [comment]
No worries, thank you for letting us know!

**Comment by thc202** [comment]
https://github.com/zaproxy/zaproxy/issues/7811#issuecomment-1497133094

Being fixed in zaproxy/zap-extensions#4542.
