### ISSUE TITLE
can't connect to www.zaproxy.org but others can

### ISSUE THREAD

**Issue by andrealbergaria** [zaproxy/zaproxy#7815]
Um using zaproxy v2.12.0 .
Can only connect to google, facebook ,youtube and others, if i use tls version1.2.
or else i get ssl handshake faiiure.
For www.zaproxy.org im having handshake failure, Ive checked the ssl versions, and i notice that google accept RSA (instead of ECDHE)  while www.zaproxy.org uses ECDHE . Could this be true?!
Is this a bug? And why i can only connect to google if using tls1.2 ?!
Thanks in advance

**Comment by thc202** [comment]
What Java build/version? Are you using custom security JRE options? Do you mean v1.2 as opposed to v1.3?

**Comment by andrealbergaria** [comment]
openjdk version "17" 2021-09-14
i mean 1.2 opposed to 1.3...1.3 doesnt work on google. i dont know what custom security JRE options is
