### ISSUE TITLE
OpenApi scan problem

### ISSUE THREAD

**Issue by C1ph3R-s** [zaproxy/zaproxy#7827]
### Describe the bug

Dear all,

I have a problem with api scan with jar (but it also a problem with zap.sh) so I have already installed required add-ons but it seams to me, it does not work at all.

```sh
java --version
openjdk 11.0.18
```

```sh
java -jar zap-D-2023-04-10.jar -h | grep "openapi"
        -openapifile <path>      Imports an OpenAPI definition from the specified file name
        -openapiurl <url>        Imports an OpenAPI definition from the specified URL
        -openapitargeturl <url>  The Target URL, to override the server URL present in the OpenAPI definition. Refer to the help for supported format.
```
```sh
java -jar zap-D-2023-04-10.jar -cmd -addonlist | grep "OpenAPI"
Levo.ai levoai  v0.2.0  alpha   Build OpenAPI Specs with ZAP traffic using Levo.ai.
OpenAPI Support openapi v34.0.0 beta    Imports and spiders OpenAPI definitions.
```

```sh
java -jar zap-D-2023-04-10.jar \
-cmd \
-addonupdate \
-config api.disablekey=true \
-openapitargeturl https://foo.com/swagger/v1/swagger.json 
-quickout test.html
```

and it gives back nothing just a blank line, i have also started in damon mode, but I got the same result:
```sh
20615 [ZAP-daemon] INFO  org.parosproxy.paros.CommandLine - Add-on update check complete
20639 [ZAP-daemon] INFO  org.zaproxy.addon.network.ExtensionNetwork - ZAP is now listening on localhost:8080
(end of the log)
```

### Steps to reproduce the behavior

Install steps:
```sh
curl -L -o ZAP_2_12_0_unix.sh https://github.com/zaproxy/zaproxy/releases/download/v2.12.0/ZAP_2_12_0_unix.sh && \
apt install python3.10-venv openjdk-11-jdk -y && \ 
chmod +x ZAP_2_12_0_unix.sh && \
./ZAP_2_12_0_unix.sh -q
```

### Expected behavior

Api scan with -openapitargeturl

### Software versions

2.12.0

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment]
The `-quickout` only works when using `-quickurl`.
https://www.zaproxy.org/docs/desktop/addons/quick-start/cmdline/

**Comment by thc202** [comment]
I'd suggest taking a look at the Automation Framework: https://www.zaproxy.org/docs/desktop/addons/automation-framework/

Closing, since this is not an issue. The OWASP ZAP User Group is a better place for usage questions: https://groups.google.com/group/zaproxy-users

**Comment by C1ph3R-s** [comment]
@thc202 thanks for your reply, but I also tried without -quickout but I got the same results. Btw quickurl work well.
The problem is the api scan, it does not work at all, so if you have a working configuration pls share with me.

**Comment by psiinon** [comment]
Best to move this conversation to the User Group or try the Automastion Framework...

**Comment by kingthorin** [comment]
This isn't the place for questions. Please take the discussion to the user group.
