### ISSUE TITLE
Concurrent HTTP/2 requests are not returning data consistently

### ISSUE THREAD

**Issue by Jegeva** [zaproxy/zaproxy#7838]
### Describe the bug

When ALPN HTTP/1.1 is disabled and HTTP2 requests work (cd. #7837)
the data returned by the http/2 request is inconsitant.

some requests return OK with a 0 byte content

### Steps to reproduce the behavior

in the main proxy properties, HTTP/1.1 is disabled in the ALPN extention
go to http://www.http2demo.io/
click "run http/2 test"
check that the requests are actually over HTTP/2
check that some of the images are actually delivered through zap
check that  some of the images are 0 byte responses

### Expected behavior

the images should all be returned consistantly

### Software versions

zap D-2023-04-17 - 20230421 - 143242

### Screenshots

![image](https://user-images.githubusercontent.com/4939609/233644073-40b52b07-7a52-4d3c-bdb2-6350c9705b36.png)

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment]
Those requests failed, you might want to check the response.

**Comment by Jegeva** [comment]
> Those requests failed, you might want to check the response.

They are working fine without ZAP and i have the same behaviour on other sites : ok on the pure browser and failing with ZAP

**Comment by kingthorin** [comment]
They could also be cached, if status is 304 size will be zero.

**Comment by Jegeva** [comment]
> They could also be cached, if status is 304 size will be zero.

I am running the browser with disable cache and 
![image](https://user-images.githubusercontent.com/4939609/233647700-36afd0c4-936a-498b-9089-d8bb5b555abd.png)
