### ISSUE TITLE
Testing script-based Authentication on DVWA failing

### ISSUE THREAD

**Issue by preewo** [zaproxy/zaproxy#7841]
### Describe the bug

We have been following the Script-Based Authentication procedure from the ZAP API documentation.
SendAndRecieve Post msg is redirecting to login , failing to create proper SessionID.
example of Post code :

```js
function authenticate(helper, paramsValues, credentials) {

  var loginUrl = paramsValues.get("Login_URL");
  var csrfTokenName = paramsValues.get("CSRF_Field");
  var csrfTokenValue = extractInputFieldValue(getPageContent(helper, loginUrl), csrfTokenName);
  var postData = paramsValues.get("POST_Data");
  postData = postData.replace('{%username%}', encodeURIComponent(credentials.getParam("Username")));
  postData = postData.replace('{%password%}', encodeURIComponent(credentials.getParam("Password")));
  postData = postData.replace('{%' + csrfTokenName + '%}', encodeURIComponent(csrfTokenValue));
  var msg = sendAndReceive(helper, loginUrl, postData);
  return msg;
}

function getRequiredParamsNames() {
  return [ "Login_URL", "CSRF_Field", "POST_Data" ];
}

function getOptionalParamsNames() {
  return [];
}

function getCredentialsParamsNames() {
  return [ "Username", "Password" ];
}

function getPageContent(helper, url) {
  var msg = sendAndReceive(helper, url);
  return msg.getResponseBody().toString();
}

function sendAndReceive(helper, url, postData) {
  var msg = helper.prepareMessage();
  var method = "GET";
  if (postData) {
    method = "POST";
    msg.setRequestBody(postData);
  }

  var requestUri = new org.apache.commons.httpclient.URI(url, true);
  var requestHeader = new org.parosproxy.paros.network.HttpRequestHeader(method, requestUri, "HTTP/1.1");
  msg.setRequestHeader(requestHeader);
  helper.sendAndReceive(msg);
  return msg;
}

function extractInputFieldValue(page, fieldName) {
  var Source = Java.type("net.htmlparser.jericho.Source");
  var src = new Source(page);
  var it = src.getAllElements('input').iterator();
  while (it.hasNext()) {
    var element = it.next();
    if (element.getAttributeValue('name') == fieldName) {
      element.getAttributeValue('value');
      return element.getAttributeValue('value');
    }
  }
  return '';
}
```

Alternatively I've also tried the following:

```js
function authenticate(helper, paramsValues, credentials) {
    var loginUrl = paramsValues.get("Login_URL");
    
    // access the login page and retrieve the user_token CSRF token
    var getRequest = helper.prepareMessage();
    var getRequestHeader = new org.parosproxy.paros.network.HttpRequestHeader("GET", new org.apache.commons.httpclient.URI(loginUrl, true), "HTTP/1.0"); // also tried with HTTP/1.1
    getRequest.setRequestHeader(getRequestHeader);
    helper.sendAndReceive(getRequest, true);
    var responseBody = getRequest.getResponseBody().toString();
    
    var csrfTokenName = paramsValues.get("CSRF_Field");
    var csrfTokenValue = extractInputFieldValue(responseBody, csrfTokenName);
    
    // do a POST with the username, password and CSRF token extracted from above
    var postRequest = helper.prepareMessage()
    var postRequestHeader = new org.parosproxy.paros.network.HttpRequestHeader("POST", new org.apache.commons.httpclient.URI(loginUrl, true), "HTTP/1.0"); // also tried with HTTP/1.1
    postRequestHeader.setHeader("Content-Type", "application/x-www-form-urlencoded");
    // postRequestHeader.setHeader("Content-Length", "88"); // also tried hard-coding the correct Content-Length
    postRequest.setRequestBody("username=" + encodeURIComponent(credentials.getParam("Username")) + "&password=" + encodeURIComponent(credentials.getParam("Password")) + "&Login=Login" + "&user_token=" + csrfTokenValue);
    postRequest.setRequestHeader(postRequestHeader);
    helper.sendAndReceive(postRequest, true);
    
    return postRequest;
}
```

### Steps to reproduce the behavior

1. Set up DVWA on port 3000
```sh
docker run --rm -it -p 3000:80 --platform linux/amd64 vulnerables/web-dvwa
```

2. import `auth-dwva-test.js` to the authentication scripts

3. Setup context following the Zapproxy documentation 
[ZAP Script Based Authentication](https://www.zaproxy.org/docs/api/#script-based-authentication)

5. Run a spider on http://localhost:3000

### Expected behavior

Post redirect after 302 code should go to index.php and not login.php with no error message.

### Software versions

ZAP 2.12.0

### Screenshots

![Screenshot 2023-04-25 at 18 03 48](https://user-images.githubusercontent.com/74400966/234319952-dca34d45-cf68-4410-9d42-cd79e3b99023.png)
![Screenshot 2023-04-25 at 17 31 12](https://user-images.githubusercontent.com/74400966/234310484-9faaf6d7-4e6e-4539-8c40-4f4d450b0e2c.png)
![Screenshot 2023-04-25 at 17 32 42](https://user-images.githubusercontent.com/74400966/234310472-b4a0493c-0131-41ea-b335-05e64149ce0f.png)
![Screenshot 2023-04-25 at 17 32 37](https://user-images.githubusercontent.com/74400966/234310476-93f79aa2-7cd9-4229-b541-26be5fc2f065.png)
![Screenshot 2023-04-25 at 17 32 26](https://user-images.githubusercontent.com/74400966/234310480-05682b39-69e6-4956-817b-288f7c5c0edd.png)
![Screenshot 2023-04-25 at 17 31 24](https://user-images.githubusercontent.com/74400966/234310482-e7dbae91-2879-4f1d-9352-da89480afaf7.png)
![Screenshot 2023-04-25 at 17 33 00](https://user-images.githubusercontent.com/74400966/234310461-fbe3a95a-0f81-4754-9660-cb09ccca3162.png)

### Errors from the zap.log file

No error showed up :
```1144527 [ZAP-SpiderInitThread-10] INFO  org.zaproxy.addon.spider.Spider - Starting spider...
1144539 [ZAP-SpiderInitThread-10] INFO  org.zaproxy.addon.spider.Spider - Scan will be performed from the point of view of User: Administrator
1144565 [ZAP-SpiderThreadPool-10-thread-1] INFO  org.zaproxy.zap.users.User - Authenticating user: Administrator
1144884 [ZAP-SpiderThreadPool-10-thread-1] INFO  org.zaproxy.addon.spider.Spider - Spidering process is complete. Shutting down...
1144902 [ZAP-SpiderShutdownThread-10] INFO  org.zaproxy.addon.spider.SpiderThread - Spider scanning complete: true on Context: DVWA at 2023-04-25T17:29:56.581+0300
```

### Would you like to help fix this issue?

- [X] Yes

**Comment by psiinon** [comment]
Also, have you seen https://www.zaproxy.org/faq/details/setting-up-zap-to-test-dvwa/ ?

**Comment by preewo** [comment]
> You seem to be statically assigning the content-length before building the body, are you 100% sure 88 is the correct value?

@kingthorin I've updated the ticket, the hard-coded `Content-Length` was only one the attempts to make sure that wasn't the problem.

**Comment by preewo** [comment]
> Also, have you seen https://www.zaproxy.org/faq/details/setting-up-zap-to-test-dvwa/ ?

@psiinon Yes, thank you, i've tried it as well but still didn't work

**Comment by kingthorin** [comment]
What version of DVWA are you using?

**Comment by preewo** [comment]
> What version of DVWA are you using?

@kingthorin Damn Vulnerable Web Application (DVWA) v1.10 *Development* , since docker pulls the latest version
