### ISSUE TITLE
2.12.0 occasionally frozen on startup waiting for Session pop-up.

### ISSUE THREAD

**Issue by c-goosen** [zaproxy/zaproxy#7867]
### Describe the bug

Opening OWASP ZAP on ARM64 Linux can get frozen on startup when waiting for Session popup screen.

Very sure this is the session issue as if you specify a session in the CLi start of zaproxy, this issue dissapears as in the below:
`zaproxy -session /home/kali/Desktop/zap-session.session 
`

It is an intermittent issue

### Steps to reproduce the behavior

1. Start ZAP on up to date kali linux (this happens on install from source as well)
2. Create a new session.
3. Do some scanning.
4. Close ZAP
5. Open ZAP again.

### Expected behavior

Should show pop-up window to create new session.

### Software versions

2.12.0

### Screenshots

![image](https://github.com/zaproxy/zaproxy/assets/7881734/7c658290-622f-486e-8d7a-cd90d883f08a)

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment]
Please, obtain and attach a thread dump, `kill -3` the ZAP process.

**Comment by thc202** [comment]
For the record there's a thread dump in: https://groups.google.com/g/zaproxy-users/c/yTG-Sa99uC0/m/51aroSOJBAAJ

That indicates that the session dialogue should be being shown already, I guess might not be visible for other reasons other than ZAP. Would be great if you could cycle through ZAP windows to ensure if it's there or not.

**Comment by c-goosen** [comment]
```
┌──(goose㉿kali)-[~/Desktop/orders_api]
└─$ ps aux |grep zap  
goose      35551  0.7  2.0 14413924 663004 ?     Sl   09:43   0:29 java -Xmx8000m -jar /usr/share/zaproxy/zap-2.12.0.jar
goose      47986  0.0  0.0   6408  2012 pts/4    S+   10:45   0:00 grep --color=auto zap
                                                                                                                                                                                                                                              
┌──(goose㉿kali)-[~/Desktop/orders_api]
└─$ kill -3 35551     
                                                                                                                                                                                                                                              
┌──(goose㉿kali)-[~/Desktop/orders_api]
└─$ sudo kill -3 35551
                                                    
```                       
Still running, no affect on process.

**Comment by c-goosen** [comment]
Also recreated this on x86 Kali this morning on AMD machine.

**Comment by thc202** [comment]
The `kill -3` is just to obtain a thread dump, it would be in the output/console.

This does seem to be a problem related to Kali (or JRE/GTK/WM). Are you also using the default JRE? Java 17?
