### ISSUE TITLE
HTTP Header Path Traversal Error Timeout

### ISSUE THREAD

**Issue by ibndias** [zaproxy/zaproxy#7868]
### Describe the bug

There is an HTB machine named 'Inject' which has path traversal vulnerabilities in HTTP header

When I tried using ZAP manual request editor, ZAP just hangs and showing error timeout. But when i use Burp Suite, it just works.

### Steps to reproduce the behavior

1. Run HTB Inject Machine https://app.hackthebox.com/machines/533
2. Upload an image in <machineip:8080>/upload page
3. After image uploaded, URL will be shown to show image. This is where path traversal vulnerability exist, but ZAP cannot get response.
4. Make a HTTP Request
```
GET /show_image?img=../ HTTP/1.1
Host: 10.10.11.204:8080
Cache-Control: max-age=0
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.5672.93 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Referer: http://10.10.11.204:8080/upload
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
Connection: close
```

### Expected behavior

A response would be
```
HTTP/1.1 200 
Accept-Ranges: bytes
Content-Type: image/jpeg
Content-Length: 4096
Date: Tue, 16 May 2023 20:15:55 GMT
Connection: close

java
resources
uploads

```
I tried this using Burpsuite but in ZAP it just hangs and returns timout.

### Software versions

I tried using ZAP 2.12.0 and ZAP weekly, 2023-05-15. Both experience the same issue

### Screenshots

Burp Result
![image](https://github.com/zaproxy/zaproxy/assets/3958152/4027bd5e-caa4-4a00-aa6f-43711aca4781)

ZAP Result
Ignore the response, it's the previous request response.
![image](https://github.com/zaproxy/zaproxy/assets/3958152/2c26bc01-5ad5-496f-81c9-cad466616cd1)

### Errors from the zap.log file

[zap.log](https://github.com/zaproxy/zaproxy/files/11491792/zap.log)

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment]
Did you try sending with the `Connection: close` header?

**Comment by thc202** [comment]
In any case can you confirm the connection is closed by the server?

**Comment by ibndias** [comment]
> Did you try sending with the `Connection: close` header?

![image](https://github.com/zaproxy/zaproxy/assets/3958152/3bbca96c-206f-4027-ad91-f8ce9763bb5e)

Changing to the `Connection: close` header returns a close connection from server

**Comment by thc202** [comment]
What's the content of the response body?

**Comment by ibndias** [comment]
ah yes, sorry my bad. Didn't check it because it's just greyed out. Need to manually change Body view to Text.
![image](https://github.com/zaproxy/zaproxy/assets/3958152/6b5019ca-11d7-4b4d-a682-91311ca740ff)
It is solved then, but why does the intercept request from ZAP gives `Connection: keep-alive`?

**Comment by kingthorin** [comment]
That must be what the browser was sending.

**Comment by ibndias** [comment]
Okay thanks !
