### ISSUE TITLE
Full scan not stopping with -m parameter

### ISSUE THREAD

**Issue by lindy63** [zaproxy/zaproxy#7870]
### Describe the bug

`docker run -t owasp/zap2docker-stable zap-full-scan.py -t  <url> -m 1 -d`

Does not seem to stop after specified time, it either runs to completion or manual cancellation

### Steps to reproduce the behavior

1. `docker run -t owasp/zap2docker-stable zap-full-scan.py -t  <url> -m 1 -d`
2. The scan does not stop

### Expected behavior

The scan should stop after the time in minutes specified by `-m`

### Software versions

docker zap2docker-stable 

### Screenshots

![image](https://github.com/zaproxy/zaproxy/assets/61848016/2ebe89c2-8e20-4752-a8ad-0ebf6098cfd6)

![image](https://github.com/zaproxy/zaproxy/assets/61848016/95f891fd-0fae-4340-a14f-a97dea570933)

### Errors from the zap.log file

None, scan seems to be working fine, apart from not stopping

### Additional context

Apologies if I am doing something stupid!

### Would you like to help fix this issue?

- [x] Yes

**Comment by kingthorin** [comment]
Per the documentation `-m` controls how long the spider runs. Not, how long the entire script takes.

https://www.zaproxy.org/docs/docker/full-scan/

**Comment by psiinon** [comment]
If you want a quick scan then use the baseline.
The full scans not going to get anywhere in 1 min.

**Comment by lindy63** [comment]
Gotcha, thanks guys and very sorry for my misunderstanding, it's clear now I've re-read the docs!
