### ISSUE TITLE
ZAP cookie management does not have the same behavior as browsers

### ISSUE THREAD

**Issue by pgoncalvesgit** [zaproxy/zaproxy#7874]
### Describe the bug

Currently, when a cookie has a value that contains one of the following characters (` `, `;`, `,`, `\`, `"`) it will be quoted when added to the request. This is being done when [formating the cookies](https://github.com/zaproxy/zap-extensions/blob/1dba24971f0f0c7385286dcf573e2f30925b385a/addOns/network/src/main/java/org/apache/hc/client5/http/impl/classic/ZapRequestAddCookies.java#L178), which, by what I was able to find/debug, will always be [this implementation](https://github.com/apache/httpcomponents-client/blob/5b61e132c3871ddfa967ab21b3af5d6d738bc6e8/httpclient5/src/main/java/org/apache/hc/client5/http/impl/cookie/RFC6265CookieSpec.java#L209). Although from my understanding this was done to try and deal with this special characters, Edge, Firefox, Safari and Chrome do not have this behaviour, neither does Burp.

Even if at first glance this might not be a problem, since having quotes is optional according to the [RFC6265](https://datatracker.ietf.org/doc/html/rfc6265#section-4.1.1), servers might not expect quotes to appear, which therefore can harm the scanner's ability to detect vulnerabilities. This behaviour can be seen on: [hack-yourself-first](http://hack-yourself-first.com/)

### Steps to reproduce the behavior

Example 1: (EDIT: Make sure Accept Cookies option is set)
1. Open the Requester
2. Send the following request:
> GET http://hack-yourself-first.com/ HTTP/1.1
Host: hack-yourself-first.com
content-length: 0

3. Send the same request again.
  3.1. A Cookie header will appear with 2 cookies. The cookie VisitStart value will be surrounded by quotes even though set-cookie did not have them.
  3.2 Server will return 500

Example 2:
1. Do a Manual Explore of the home page of [hack-yourself-first](http://hack-yourself-first.com/)
2. Start the spider
3. Check the responses on the new pages that appear, they are all returning 500

This is caused by the cookie VisitStart=XX/XX/XXXX XX:XX:XX XX getting quoted which then causes the server to not be able to parse it as a timestamp.

We can however go around the bug within example 1 by sending a request without the VisitStart cookie:
1. Open the Requester
2. Send the following request:
> GET http://hack-yourself-first.com/ HTTP/1.1
Host: hack-yourself-first.com
content-length: 0
Cookie: ASP.NET_SessionId=et3o4na4f5cpnud245gx3vac;

### Expected behavior

It is expected that the cookie is not changed and quotes are not added.

### Software versions

OWASP ZAP
Version: Dev Build

Installed Add-ons: [[id=ascanrules, version=55.0.0],
[id=automation, version=0.29.0], [id=callhome,
version=0.7.0], [id=commonlib, version=1.15.0],
[id=database, version=0.2.0], [id=encoder, version=1.2.0],
[id=graaljs, version=0.4.0], [id=network, version=0.9.0],
[id=oast, version=0.16.0], [id=pscanrules, version=49.0.0],
[id=quickstart, version=38.0.0], [id=reports,
version=0.21.0], [id=requester, version=7.3.0], [id=retire,
version=0.23.0], [id=scripts, version=39.0.0], [id=selenium,
version=15.12.0], [id=spider, version=0.5.0],
[id=webdriverwindows, version=55.0.0]]

### Screenshots

![imagem](https://github.com/zaproxy/zaproxy/assets/46837775/8710adaf-37f2-40fa-8632-60c1c7c3b083)
![imagem](https://github.com/zaproxy/zaproxy/assets/46837775/75398f36-f47b-4e87-b91d-c36910e1da84)
![imagem](https://github.com/zaproxy/zaproxy/assets/46837775/c9ca73d5-636e-435c-bb44-974d929dc471)

### Would you like to help fix this issue?

- [X] Yes

**Comment by thc202** [comment]
#1232

**Comment by pgoncalvesgit** [comment]
Hey @thc202 Sorry to annoy, is it possible to get a status on this? Can I help with anything?

**Comment by pgoncalvesgit** [comment]
Any updates?

**Comment by psiinon** [comment]
Any updates will be added to this issue.
We are a relatively small team and have lots to do I'm afraid.
We will hopefully have news of more sponsorship options soon - the more sponsorship we get the more people we can get to work on ZAP and the quicker we can fix issues like this 😁

**Comment by thc202** [comment]
This is being worked on though.

**Comment by thc202** [comment]
https://github.com/zaproxy/zaproxy/issues/7874#issuecomment-1559285576

That's a workaround to match this specific case, not the fix.

**Comment by pgoncalvesgit** [comment]
Totally understand you. Didn't want this to be left in the dark and wanted a confirmation. Thank you for the quick response :)

If there is anything I can try and help with, I am all yours.
