### ISSUE TITLE
Marketplace Addon extension does not auto load on browser launch

### ISSUE THREAD

**Issue by frost19k** [zaproxy/zaproxy#7878]
### Describe the bug

I installed the Eval Villian Addon from the Marketplace & enabled the addon in the Selenium configuration, but the extension does not load when I launch Firefox.

I can "Install Addon from file" within Firefox, and select the file `selenium/extensions/eval_villain-latest-fx.xpi` which will load correctly & then I can use it. 

But it will not auto load on launch. 

Have I missed something?

### Steps to reproduce the behavior

1. Install Eval Villain from Marketplace
2. Go to Tools > Options > Selenium & ensure the extension is enabled under "Browser Extensions"
3. Launch Firefox from ZAP & notice that the extension is missing.

### Expected behavior

Eval Villian addon should be installed when Firefox is launched from ZAP

### Software versions
```
OWASP ZAP
Version: 2.12.0

Installed Add-ons: [[id=alertFilters, version=15.0.0],
[id=ascanrules, version=54.0.0], [id=automation,
version=0.28.0], [id=bruteforce, version=12.0.0],
[id=callhome, version=0.6.0], [id=commonlib,
version=1.14.0], [id=communityScripts, version=16.0.0],
[id=custompayloads, version=0.12.0], [id=database,
version=0.1.0], [id=diff, version=12.0.0],
[id=directorylistv1, version=5.0.0], [id=domxss,
version=15.0.0], [id=encoder, version=1.1.0],
[id=evalvillain, version=0.2.0], [id=exim, version=0.5.0],
[id=formhandler, version=6.2.1], [id=fuzz, version=13.9.0],
[id=fuzzdb, version=9.0.0], [id=fuzzdboffensive,
version=4.0.0], [id=gettingStarted, version=14.0.0],
[id=graaljs, version=0.3.0], [id=graphql, version=0.15.0],
[id=help, version=15.0.0], [id=hud, version=0.16.0],
[id=importurls, version=9.0.0], [id=invoke, version=12.0.0],
[id=jsonview, version=2.0.0], [id=jython, version=12.0.0],
[id=network, version=0.8.0], [id=oast, version=0.15.0],
[id=onlineMenu, version=10.0.0], [id=openapi,
version=33.0.0], [id=pscanrules, version=48.0.0],
[id=pscanrulesBeta, version=33.0.0], [id=quickstart,
version=37.0.0], [id=replacer, version=12.0.0], [id=reports,
version=0.20.0], [id=requester, version=7.2.0], [id=retest,
version=0.5.0], [id=retire, version=0.22.0], [id=reveal,
version=5.0.0], [id=saverawmessage, version=7.0.0],
[id=savexmlmessage, version=0.3.0], [id=scripts,
version=38.0.0], [id=selenium, version=15.12.0], [id=soap,
version=17.0.0], [id=spider, version=0.4.0], [id=spiderAjax,
version=23.13.1], [id=tips, version=10.0.0], [id=viewstate,
version=3.0.0], [id=webdriverlinux, version=55.0.0],
[id=websocket, version=28.0.0], [id=zest, version=38.0.0]]

Operating System: Linux
Architecture: amd64
Java Version: N/A 17.0.7
System's Locale: en_GB
Display Locale: en_GB
Format Locale: en_GB
Default Charset: UTF-8
ZAP Home Directory: /home/maazb/.ZAP/
ZAP Installation Directory: /usr/local/share/zaproxy/./
Look and Feel: FlatLaf Darcula (com.formdev.flatlaf.FlatDarculaLaf)
```

### Would you like to help fix this issue?

- [ ] Yes

**Comment by psiinon** [comment]
Arg. Firefox have probably changed something ☹️ 
I'll look into it...

**Comment by psiinon** [comment]
It looks like this is a combination of a Firefox change, a Selenium bug and the way the Manaifest is written: https://github.com/swoops/eval_villain/issues/5
So while we cant fix this right now we are trying to work with Selenium and the Eval Villain author to get this fixed one way or another.

**Comment by psiinon** [comment]
@frost19k this should now be fixed, with help from folks from Selenium and Mozilla!
Update your Selenium add-on and try it again - it should be fine now...

**Comment by frost19k** [comment]
@psiinon I'm so sorry about the late reply. 

Thank you soo much for fixing this so quickly. I updated the add-on & now it does indeed load on launch.
