### ISSUE TITLE
ZAP 2.12 ActivClient Issue

### ISSUE THREAD

**Issue by Foteini7** [zaproxy/zaproxy#7893]
With ZAP 2.10 we were able to add CAC/PIV certificates in the keystore by adding the PCKS#11 driver for ActivClient.

ZAP 2.12 displays an error that the driver or password is wrong, the previous functionality is lost.

**Comment by kingthorin** [comment]
Please open your issue properly and provide all the requested details:
https://github.com/zaproxy/zaproxy/issues/new/choose

**Comment by thc202** [comment]
Did it work in 2.11?

**Comment by kingthorin** [comment]
See #7895

**Comment by Foteini7** [comment]
I have not tried the 2.11 version, this can be an option if it works, since the 2.10 has the log4j issue
