### ISSUE TITLE
Docker error during update of add-on ExtensionGraphQlSpider

### ISSUE THREAD

**Issue by SDreamer88** [zaproxy/zaproxy#7894]
### Describe the bug

 Hi
I'm trying to run a scan in the docker and it is throwing the following error:
An error occurred while uninstalling the extension "org.zaproxy.addon.graphql.spider.ExtensionGraphQlSpider" bundled in the add-on "graphql"

I've already used the latest stable docker version and the version from  s2023-04-10

Is there a way to install/uninstall manually that add-on? or Is there a the General fix?

### Steps to reproduce the behavior

1.- Run this in the the server:

docker run -v $(pwd)/owaspzap:/zap/wrk/:rw owasp/zap2docker-stable:latest zap-full-scan.py \
-t https://demoowaspnsu.azurewebsites.net/ \
-J report.json \
-r report.html \
-w Report.md \
-m 1 \
-d -I

### Expected behavior

The creation of the scan reports

### Software versions

Docket image latest

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment]
What's the ID of the image? The stable image was released today, ensure first, you are using that one.

**Comment by SDreamer88** [comment]
> What's the ID of the image? The stable image was released today, ensure first you are using that one.

Hi, I used the latest tag ` zap2docker-stable:**latest** ` 

I didn't used the 2.12.0 because was the version prior.

**Comment by kingthorin** [comment]
That doesn't answer the question. We specifically want to know the ID so we can tell which fixes might or might not be in place. Due to timing.

**Comment by thc202** [comment]
A bigger excerpt of the log would also help (e.g. the part that says which add-ons are installed and being updated).

**Comment by SDreamer88** [comment]
> That doesn't answer the question. We specifically want to know the ID so we can tell which fixes might or might not be in place. Due to timing.
Here you have
![image](https://github.com/zaproxy/zaproxy/assets/90362210/bf1bd093-24a3-491a-a567-a552ca33d3d6)
[2023-06-06 docker latest run.txt](https://github.com/zaproxy/zaproxy/files/11667726/2023-06-06.docker.latest.run.txt)

**Comment by SDreamer88** [comment]
> That's not the latest, it should be:
> 
> ```
> REPOSITORY                TAG       IMAGE ID       CREATED        SIZE
> owasp/zap2docker-stable   latest    cd51a669ebec   4 hours ago    2.11GB
> ```
> 
> The log also shows the add-ons are outdated, which points to an older image.

Hi All,

That was the problem, the image was the latest but not the most recent.
By removing the old one, adding space to the server and installing the most recent solved the issue.

Thanks for your guidance.
