### ISSUE TITLE
By zap-webswing show message 'You appear to be running ZAP in a container, so launching browsers has been disabled as this is unlikely to work.'

### ISSUE THREAD

**Issue by acn-handong-liu** [zaproxy/zaproxy#7911]

**Comment by acn-handong-liu** [comment]
hello
1. on window, i execute as 'docker run -v C:\Users\xxx\owasp-new:/zap/wrk/:rw -u zap -p 8080:8080 -p 9090:9090 -i owasp/zap2docker-stable zap-webswing.sh'
2. on firebox i access http://localhost:8080/zap/
3. page manual explore appear following:
![image](https://github.com/zaproxy/zaproxy/assets/35675231/06b9d176-8e4b-488f-ac03-f83e412f82b4)
![image](https://github.com/zaproxy/zaproxy/assets/35675231/de26c600-84bd-4746-807f-4e34b6dd6c0f)

You will need to use a browser that you don't launch from ZAP, configure it to proxy through ZAP and to import the ZAP root CA certificate.
If you think ZAP will be able to launch browsers in your environment then you can enable this feature via the Option: Display / Enable app integration in containers.

please help me resolve it.

**Comment by thc202** [comment]
There's nothing to resolve, ZAP is running inside the container and the browser would be launched inside the container as well (which would fail or not be accessible).

Please use the [ZAP User Group](https://groups.google.com/g/zaproxy-users) for usage questions, it's not clear what you are trying to achieve.
