### ISSUE TITLE
Custom docker image does not work properly

### ISSUE THREAD

**Issue by ibby24** [zaproxy/zaproxy#7923]
### Describe the bug

Hello,

I have created a docker file with the following..

```
FROM owasp/zap2docker-stable
USER root
RUN echo "forcing update" && \
 	apt update && \
        apt upgrade -y && \
        apt install -y jq libxml-xpath-perl curl && \
	    pip3 install awscli yq jinja2-cli
RUN pip3 install chardet urllib3 zapcli 
USER zap

COPY --chown=zap . /zap/wrk/

WORKDIR /zap/wrk/
ENV JMEM="-Xmx7g -Xmx7g"
# required as we are running in the test vpc which doesn't have internet access
RUN bash /zap/wrk/get-zap-plugins.sh

RUN mkdir -p /home/zap/.ZAP/plugin && \
    mv /zap/wrk/plugin /home/zap/.ZAP/plugin

RUN env BUILD_MODE=true /zap/wrk/run-in-pipeline.sh || true
ENTRYPOINT /bin/bash

```

### Steps to reproduce the behavior

The build completes and the image is pushed up. 

when I start the codepipeline and use 
`zap-api-scan.py -d -t ${TARGET_URL}v1/graphql -s -f graphql  -c gen.conf`
which is in the run-in-pipeline.sh 
It runs and eventually throws an error message. 

`<span><span>
Unexpected error: <class 'AttributeError'>
File "/zap/zap-api-scan.py", line 399, in main
zap_tune(zap)
File "/zap/zap_common.py", line 405, in zap_tune
zap.pscan.disable_all_tags()
AttributeError: 'pscan' object has no attribute 'disable_all_tags'
Failed to find zap_log /zap/zap.out

--

</span></span><span><span>ERROR &lt;class 'AttributeError'&gt;</span></span>`

### Expected behavior

for it to show the output of the URLs with issues or problems.

### Software versions

owasp/zap2docker-stable

### Errors from the zap.log file

This is ran in a codebuild pipeline, the container starts and then stops and I do not have access to the zap.log file.

### Would you like to help fix this issue?

- [ ] Yes

**Comment by kingthorin** [comment]
By installing zapcli which hasn't been updated in 5 years, you've probably got an old version of the client api which doesn't know about pscan.disable_all_tags.

If you choose to build your own image you're kind of on your own.

**Comment by thc202** [comment]
As curiosity, why are you installing `zapcli`?

**Comment by ibby24** [comment]
because it is called in a script.
What is the replacment of zap-cli?

**Comment by psiinon** [comment]
The supported automation options are listed on https://www.zaproxy.org/docs/automate/
I'd recommend looking at the Automation Framework.
