### ISSUE TITLE
ZapSocketTimeoutException triggers Strict Transport Security alert

### ISSUE THREAD

**Issue by rbliss** [zaproxy/zaproxy#7934]
### Describe the bug

It appears that a `ZapSocketTimeoutException` occurring mid spider scan triggers a false positive  `Strict-Transport-Security Header Not Set` alert.

This can happen when scanning a website that may have a firewall or other security defense measure that blocks an IP once a scan is detected.

It seems like the spider returns an ZAP IO Error response, and it's this response that gets judged as failing.
```
HTTP/1.1 400 ZAP IO Error
Content-Type: text/plain; charset=UTF-8
Content-Length: 1382
```
From the screenshot below, you'll see a bunch of different requests, all listed under this alert. All the response headers and bodies are the ZAP IO Error.

### Steps to reproduce the behavior

The simplest way to recreate is to throw a `throw new ZapSocketTimeoutException("Example exception", 10);` after [`parent.getHttpSender().sendAndReceive(msg);`](https://github.com/zaproxy/zap-extensions/blob/1c671a21f7cf072e829e1bb56542ce7dd710e860/addOns/spider/src/main/java/org/zaproxy/addon/spider/SpiderTask.java#L420) in SpiderTask.java which simulates the behavior I'm seeing.

### Expected behavior

`Strict-Transport-Security Header Not Set` alert would not be triggered in the event of a ZapSocketTimeoutException. 
Perhaps a different alert is triggered to signal an incomplete scan.

### Software versions
```
OWASP ZAP
Version: 2.12.0

Installed Add-ons: [[id=alertFilters, version=16.0.0],
[id=ascanrules, version=55.0.0], [id=authhelper,
version=0.8.0], [id=automation, version=0.29.0],
[id=bruteforce, version=13.0.0], [id=callhome,
version=0.6.0], [id=commonlib, version=1.14.0],
[id=custompayloads, version=0.12.0], [id=database,
version=0.1.0], [id=diff, version=12.0.0],
[id=directorylistv1, version=5.0.0], [id=domxss,
version=15.0.0], [id=encoder, version=1.1.0], [id=exim,
version=0.5.0], [id=formhandler, version=6.3.0], [id=fuzz,
version=13.9.0], [id=gettingStarted, version=14.0.0],
[id=graaljs, version=0.3.0], [id=graphql, version=0.17.0],
[id=help, version=15.0.0], [id=hud, version=0.16.0],
[id=invoke, version=12.0.0], [id=network, version=0.9.0],
[id=oast, version=0.15.0], [id=onlineMenu, version=10.0.0],
[id=openapi, version=34.0.0], [id=pscanrules,
version=49.0.0], [id=quickstart, version=37.0.0],
[id=replacer, version=12.0.0], [id=reports, version=0.22.0],
[id=requester, version=7.2.0], [id=retest, version=0.5.0],
[id=retire, version=0.23.0], [id=reveal, version=5.0.0],
[id=scripts, version=38.0.0], [id=selenium,
version=15.12.1], [id=soap, version=17.0.0], [id=spider,
version=0.4.0], [id=spiderAjax, version=23.14.1], [id=tips,
version=10.0.0], [id=webdrivermacos, version=56.0.0],
[id=websocket, version=28.0.0], [id=zest, version=38.0.0]]

Operating System: Mac OS X
Architecture: x86_64
Java Version: Eclipse Adoptium 11.0.16.1
System's Locale: en_US
Display Locale: en_GB
Format Locale: en_US
Default Charset: UTF-8
ZAP Home Directory: /Users/*****/Library/Application Support/ZAP/
ZAP Installation Directory: /Applications/OWASP ZAP.app/Contents/Java/./
Look and Feel: FlatLaf Light (com.formdev.flatlaf.FlatLightLaf)
```

### Screenshots

<img width="2552" alt="Screenshot 2023-07-05 at 1 58 46 PM" src="https://github.com/zaproxy/zaproxy/assets/108509/f9338ade-9fd5-40af-8024-36fdf5f2c965">

### Would you like to help fix this issue?

- [x] Yes

**Comment by thc202** [comment]
> The simplest way to recreate is to throw a throw new ZapSocketTimeoutException("Example exception", 10); after [parent.getHttpSender().sendAndReceive(msg);](https://github.com/zaproxy/zap-extensions/blob/1c671a21f7cf072e829e1bb56542ce7dd710e860/addOns/spider/src/main/java/org/zaproxy/addon/spider/SpiderTask.java#L420) in SpiderTask.java which simulates the behavior I'm seeing.

That does not recreate the issue, that's changing the response of the target, which can still be passively scanned. (That's not different from having a HTTP Sender script doing changes to the response.)

Do you have an outgoing proxy configured in ZAP? Would be great to know more details about the actual conditions before the timeout.

**Comment by rbliss** [comment]
No special configuration or setup of a proxy. I started from the default Zap configuration and ran the passive scan on a particular website. 

I tried creating a webserver locally that would do the same sort of blocking but was unable. Hence manually throwing the error to trigger the HSTS alert similar to how it might be done in a mocked unit test. It seems reasonable to assume `parent.getHttpSender().sendAndReceive(msg);` would throw the `ZapSocketTimeoutException` from the stack trace in the screenshot.

Let me get permission to share the URL of the website scanned, you can scan to recreate the exact issue.

<img width="747" alt="Screenshot 2023-07-06 at 9 31 09 AM" src="https://github.com/zaproxy/zaproxy/assets/108509/841d5cc5-622a-44ac-9ddd-fb735789debb">
<img width="755" alt="Screenshot 2023-07-06 at 9 31 15 AM" src="https://github.com/zaproxy/zaproxy/assets/108509/b3be2fed-93e1-4e6e-b40c-280120a9235c">

**Comment by thc202** [comment]
It's reasonable to assume that and that's what's happening, but throwing the exception after it's not. The state of the message is different, in the latter case it would be flagged already has having a response from the server thus eligible to be passive scanned, while if there was an exception while sending/receiving the message it would not have that flag set.

Thank you!

**Comment by rbliss** [comment]
Good note about the flag, I was unaware of that as I'm still learning about the codebase. Thanks! I'll follow up with more detail when I have it.

**Comment by thc202** [comment]
@rbliss were you able to obtain more details about the issue?

**Comment by thc202** [comment]
I'd still prefer knowing how this happened.

**Comment by kingthorin** [comment]
I agree, but after a month we still don't have details 🤷‍♂️
