### ISSUE TITLE
Allow API definitions to be uploaded via the ZAP API

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#7943]
### Is your feature request related to a problem? Please describe.

Right now we only support API definitions loaded from a file or from a URL.
Allowing API definitions to be uploaded via the ZAP API would help where the definition is not available via a URL and is not present on the machine running ZAP.

Should be supported for:

- [ ] OpenAPI
- [ ] GraphQL
- [ ] SOAP
- [ ] Postman

### Describe the solution you'd like

As above :)

### Describe alternatives you've considered

Uploading the API definitions via files or URLs.

### Would you like to help fix this issue?

- [ ] Yes

**Comment by kingthorin** [comment]
Postman?

**Comment by psiinon** [comment]
+1 cc @VitikaSoni 😁

**Comment by psiinon** [comment]
FYI we're discussing supporting file upload/download via the API. 
So you would be able to upload and download files to/from one specific directory (with protections against path traversal;). 
This would then effectively give us support for all files ZAP allows you to access locally. 
We would probably protect this via a cmdline option - the default would be off. 
Feedback on this proposal appreciated..
