### ISSUE TITLE
Fuzzer might not show the encoded URL after edits

### ISSUE THREAD

**Issue by timruff** [zaproxy/zaproxy#7947]
### Describe the bug

In the fuzzer when I put a fuzzer between < and >, the encoding of the signs works badly.
For example for the string <a> I must have a %3Ca%3E encoding, instead I have %aCa%3E.
For the string <a2> I have the encoding %a2Ca%3E which is also not good, it should be %3Ca2%3E.

### Steps to reproduce the behavior

In History, go to Attack->Fuzz..
In Url variable edit to <test> and Save.
Select edit and click on add
Add the string and Start Fuzzer.

### Expected behavior

Example <a> im expect to %3Ca%3E and not %aCa%3E.

### Software versions

OWASP ZAP
Version: 2.13.0

Installed Add-ons: [[id=accessControl, version=8.0.0],
[id=alertFilters, version=17.0.0], [id=ascanrules,
version=56.0.0], [id=attacksurfacedetector, version=1.1.4],
[id=authhelper, version=0.9.0], [id=automation,
version=0.30.0], [id=browserView, version=6.0.0],
[id=bruteforce, version=14.0.0], [id=callhome,
version=0.7.0], [id=commonlib, version=1.15.0],
[id=communityScripts, version=17.0.0], [id=custompayloads,
version=0.12.0], [id=database, version=0.2.0], [id=diff,
version=13.0.0], [id=directorylistv1, version=6.0.0],
[id=domxss, version=16.0.0], [id=encoder, version=1.2.0],
[id=evalvillain, version=0.2.0], [id=exim, version=0.6.0],
[id=fileupload, version=1.1.0], [id=formhandler,
version=6.4.0], [id=fuzz, version=13.10.0], [id=fuzzdb,
version=9.0.0], [id=fuzzdboffensive, version=4.0.0],
[id=gettingStarted, version=15.0.0], [id=graaljs,
version=0.4.0], [id=graphql, version=0.18.0], [id=help,
version=16.0.0], [id=help_fr_FR, version=10.0.0], [id=hud,
version=0.17.0], [id=invoke, version=13.0.0], [id=jruby,
version=8.0.0], [id=jsonview, version=2.0.0], [id=jwt,
version=1.0.3], [id=jython, version=12.0.0], [id=kotlin,
version=1.1.0], [id=neonmarker, version=1.5.0], [id=network,
version=0.10.0], [id=oast, version=0.16.0], [id=onlineMenu,
version=11.0.0], [id=openapi, version=35.0.0],
[id=packpentester, version=0.1.0], [id=portscan,
version=10.0.0], [id=pscanrules, version=50.0.0],
[id=quickstart, version=38.0.0], [id=replacer,
version=13.0.0], [id=reports, version=0.23.0],
[id=requester, version=7.3.0], [id=retest, version=0.6.0],
[id=retire, version=0.24.0], [id=reveal, version=6.0.0],
[id=scripts, version=39.0.0], [id=selenium,
version=15.13.0], [id=soap, version=18.0.0], [id=spider,
version=0.5.0], [id=spiderAjax, version=23.15.0],
[id=sqliplugin, version=15.0.0], [id=tips, version=11.0.0],
[id=tokengen, version=15.0.0], [id=viewstate,
version=3.0.0], [id=wappalyzer, version=21.22.0],
[id=webdriverlinux, version=57.0.0], [id=websocket,
version=29.0.0], [id=zest, version=39.0.0]]

Operating System: Linux
Architecture: amd64
Java Version: Oracle Corporation 17.0.7
System's Locale: fr_FR
Display Locale: en_GB
Format Locale: fr_FR
Default Charset: UTF-8
ZAP Home Directory: /home/parrot/.ZAP/
ZAP Installation Directory: /opt/zaproxy/./
Look and Feel: FlatLaf Light (com.formdev.flatlaf.FlatLightLaf)

### Screenshots

![Capture d’écran_2023-07-14_00-11-37](https://github.com/zaproxy/zaproxy/assets/28568410/15c4419f-d779-4798-a996-cbf5761689e3)

### Would you like to help fix this issue?

- [X] Yes

**Comment by kingthorin** [comment]
Could you provide screenshots of the payload location being set and the payload config?

**Comment by timruff** [comment]
Here is a screenshot of the payload as well as its operation, I tried on Zap owasp 2.12.0 it works but not on 2.13.0.

![Capture d’écran du 2023-07-14 00-57-11](https://github.com/zaproxy/zaproxy/assets/28568410/035d7de1-5096-4005-ba58-78e8db76ad6c)

**Comment by timruff** [comment]
The problem is not only the display, it also concerns the fuzzing itself, the result is impacted.

**Comment by thc202** [comment]
Check what you selected and what's being fuzzed.

**Comment by thc202** [comment]
Same comment as above, if you are trying to say that ZAP should not automatically encode the URL, that's another known issue (already raised).

**Comment by timruff** [comment]
Ok thanks for the feedback, it would be possible if one day the bug will be fixed. This should be put in duplicate issue.
