### ISSUE TITLE
Update endpoint for version check of ChromeDriver

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#7955]
Update the endpoint (and logic) to check for new ChromeDriver versions. More info in https://github.com/GoogleChromeLabs/chrome-for-testing#json-api-endpoints

Note that the latest ChromeDriver (as of writing) has an issue finding (plain) Chrome binary on macOS (GoogleChromeLabs/chrome-for-testing#30). Probably better to wait for a fix otherwise the macOS users will have to manually specify the Chrome binary (ChromeDriver v114 finds Chrome v115).

**Comment by kingthorin** [comment]
https://github.com/zaproxy/zap-extensions/blob/main/.github/workflows/create_webdriver_update.yml
