### ISSUE TITLE
Firefox is sending requests to unknown websites (probably bookmarks)

### ISSUE THREAD

**Issue by 0xcrypto** [zaproxy/zaproxy#7974]
### Describe the bug

Running ZAP on a target in any mode results in sending extra requests. I am not sure where it is coming from. As I am running Fedora, I have bookmarks to Fedora websites. So I think it might be loading the bookmark icons. I tried deleting the bookmarks too but they keep coming back.

### Steps to reproduce the behavior

1. Open any target in either automatic or manual explore.
2. Notice the Site tree. If your Firefox has bookmarks, there should be these extra requests depending on the default bookmarks your Firefox has.

### Expected behavior

Should not send requests to the bookmarks. If it is not possible to remove, requests should not be added to the site tree.

### Software versions

OWASP ZAP v2.13.0

### Screenshots

As evident in the screenshot, it has sent a request to fedoraproject.org, okd.io, creativecommons.org etc.

![Screenshot_2023-08-03_08-28-33](https://github.com/zaproxy/zaproxy/assets/6683856/39868e3b-4d50-47c2-92c5-9d167fb4bce9)

### Would you like to help fix this issue?

- [x] Yes

**Comment by thc202** [comment]
You mean the browser sent those requests?

**Comment by 0xcrypto** [comment]
> You mean the browser sent those requests?

Yes, the embedded Firefox.

**Comment by psiinon** [comment]
Yeah, I remember seeing that when I used Fedora.
Thats not something ZAP is doing, and I'm pretty sure Firefox is not controlling this either, so its some changes Fedora makes.
So its not something we are in control of.
However if you could send us details then we could add suitable regex patterns to the Global Exclusions: https://www.zaproxy.org/docs/desktop/addons/network/options/globalexclusions/

**Comment by 0xcrypto** [comment]
@psiinon 

```
https://abs.twimg.com
https://abs.twimg.com/favicons
https://abs.twimg.com/favicons/favicon.ico
https://alt.fedoraproject.org
https://alt.fedoraproject.org/static
https://alt.fedoraproject.org/static/images
https://alt.fedoraproject.org/static/images/favicon.ico
https://creativecommons.org
https://creativecommons.org/wp-content
https://creativecommons.org/wp-content/uploads
https://creativecommons.org/wp-content/uploads/2016
https://creativecommons.org/wp-content/uploads/2016/05
https://creativecommons.org/wp-content/uploads/2016/05/cc-site-icon-300x300.png
https://developer.jboss.org
https://developer.jboss.org/resources
https://developer.jboss.org/resources/images
https://developer.jboss.org/resources/images/palette-1001
https://developer.jboss.org/resources/images/palette-1001/faviconImage-1406099167844-favicon.ico
https://diasp.org
https://diasp.org/assets
https://diasp.org/assets/favicon-6c483382d6196fb46215c44e6bdaffcdd019cc0a8e12fd1a1b62356721de1476.png
https://fedoraproject.org
https://fedoraproject.org/favicon.ico
https://fedoraproject.org/spins
https://fedoraproject.org/spins/
https://fonts.googleapis.com
https://fonts.googleapis.com/css?family=Poiret+One%7CSource+Sans+Pro
https://fonts.gstatic.com
https://fonts.gstatic.com/s
https://fonts.gstatic.com/s/poiretone
https://fonts.gstatic.com/s/poiretone/v14
https://fonts.gstatic.com/s/poiretone/v14/UqyVK80NJXN4zfRgbdfbo55cVw.woff2
https://fonts.gstatic.com/s/sourcesanspro
https://fonts.gstatic.com/s/sourcesanspro/v22
https://fonts.gstatic.com/s/sourcesanspro/v22/6xK3dSBYKcSV-LCoeQqfX1RYOo3qOK7l.woff2
https://labs.fedoraproject.org
https://labs.fedoraproject.org/static
https://labs.fedoraproject.org/static/images
https://labs.fedoraproject.org/static/images/favicon.ico
https://librivox.org
https://librivox.org/wp-content
https://librivox.org/wp-content/themes
https://librivox.org/wp-content/themes/librivox
https://librivox.org/wp-content/themes/librivox/favicon.ico
https://riot.im
https://riot.im/app
https://riot.im/app/vector-icons
https://riot.im/app/vector-icons/favicon.ico
https://www.okd.io
https://www.okd.io/img
https://www.okd.io/img/icons
https://www.okd.io/img/icons/favicon.png
https://www.redditstatic.com
https://www.redditstatic.com/favicon.ico
https://www.wikipedia.org
https://www.wikipedia.org/static
https://www.wikipedia.org/static/favicon
https://www.wikipedia.org/static/favicon/wikipedia.ico
```

**Comment by psiinon** [comment]
Wow!
Hum .. are the icons being displayed for the sites?
If so then maybe it is Firefox - its got to get them somehow...

**Comment by 0xcrypto** [comment]
Yes the icons are visible for bookmarks. I could not replicate this in an Ubuntu box, despite having bookmarks. In Fedora, the bookmarks toolbar is always visible while in Ubuntu it is not. In both cases, icons are visible. Unfortunately I cannot share the screenshot of ubuntu due to NDA with the company who provides this vm workstation.

**Comment by psiinon** [comment]
I think that will be it then.
I'm not sure what we can do about that - I dont particularly want to block all of those sites :/

**Comment by 0xcrypto** [comment]
> I think that will be it then. I'm not sure what we can do about that - I dont particularly want to block all of those sites :/

yes that's understandable. Maybe a custom profile to remove bookmarks can be used if selenium is being used behind the scenes. Ref. https://stackoverflow.com/a/14662366

**Comment by psiinon** [comment]
FYI I've updated https://www.zaproxy.org/faq/why-does-zap-access-out-of-scope-domains/ - ok to close this?

**Comment by 0xcrypto** [comment]
Yes it looks good. For this issue ticket, I think it can be converted to a feature request. I was wondering if a custom profile for the embedded firefox could be implemented in the core. It can allow more features like per-setting some configurations etc.

If it does not align with the purpose of ZAP, maybe someone (or I) can try building a plugin to fix this.

**Comment by psiinon** [comment]
I'll open a new ticket if thats alright.
We do have other reasons why having custom browser profiles available would be useful ;)
We would need to work out how we maintain these - browsers have the habit of changing things often :/
The functionality would probably be implemented in the Selenium add-on, but thats just an implementation detail.

**Comment by 0xcrypto** [comment]
Awesome, I will try to contribute as much possible.

**Comment by psiinon** [comment]
We actually had a related issue - I've updated it: https://github.com/zaproxy/zaproxy/issues/4339
Feel free to comment on that as well :)
