### ISSUE TITLE
Allow zap api to return found alerts to an automation framework execution plan

### ISSUE THREAD

**Issue by Sperez96** [zaproxy/zaproxy#7994]
### Is your feature request related to a problem? Please describe.

Hi,

Currently, to get the alerts found in zap via the api, the call https://www.zaproxy.org/docs/api/#alertviewalerts is used.

However, in the event that a zap automation process has been launched to detect alerts (for example for a scan of an openapi document), we cannot know if the generated alerts are part of this scan, or a previous one.

If you use JSON/automation/view/planProgress/?planId=id, you do not get the result of the execution, but the moment in which it has finished.

The only way to analyze the vulnerabilities found is with the previous endpoint, but that can bring us, either previous executions, or executions of other analyzes for different apis.

The only way would be to use the automation job report, but if we execute via api, the client may not be in the same place as the server, and may not be able to access that file to process the output

### Describe the solution you'd like

Enable a new endpoint that allows consulting, through a parameter (planId) the list of alarms found, if any

### Describe alternatives you've considered

When we consult the execution plan process, obtain a new section with the list of alerts found

### Would you like to help fix this issue?

- [ ] Yes

**Comment by psiinon** [comment]
Can you explain how you are using ZAP?
While AF plans can be invoked via the API the assumption was that most people would be running them inline.

**Comment by Sperez96** [comment]
The problem is that I can execute several AF plans in a row, and each one generate a different result. If I can't tell the output of each execution via api, I have to restart zap each time, so it doesn't mix up the alerts found between executions

Executing from the command line, through the report job I can obtain it, but the api does not allow it. It works only if the client generates the report on his own computer.

In case an alert has been fixed, and you want to check it, if I relaunch the AF, as the alert was detected at a previous point, it appears that my api presents that alert, when it would not be true

**Comment by kingthorin** [comment]
You can start a new ZAP session (via the API) without killing and restarting ZAP, 

Reports can also be generated via the API, and I'm currently working on: [Provide API endpoint to get/download the report](https://github.com/zaproxy/zaproxy/issues/7821),

> In case an alert has been fixed, and you want to check it, if I relaunch the AF, as the alert was detected at a previous point, it appears that my api presents that alert, when it would not be true

Why would you do this with an existing session or alerts?

**Comment by Sperez96** [comment]
With the two points you mention, in principle it would be enough to solve both problems. The endpoint to create a new session would be: https://www.zaproxy.org/docs/api/#httpsessionsactioncreateemptysession prior to the execution of the plan. With what you say about releasing the report resource via api, everything would be correct.

Thank you so much

**Comment by thc202** [comment]
It's not that endpoint but https://www.zaproxy.org/docs/api/#coreactionnewsession

Closing, since existing open issues already cover the wnted use case.
