### ISSUE TITLE
Delayed Proxying of Requests Following Long Polling Request

### ISSUE THREAD

**Issue by icongit4c** [zaproxy/zaproxy#7998]
### Describe the bug

Hi.

First, congrats on joining the SSP!

A few months ago we upgraded from 2.11.1 to 2.12.0. After the upgrade, we started seeing issues with ZAP’s proxying functionality that were triggered by our site’s use of long polling. 

After a user logs into our site, 1 long polling HTTP connection is established between the browser and our server that remains open for 60 seconds and then recycles. As the user navigates through our site, performs queries and submits forms, other HTTP requests are generated outside of that long polling connection.

In 2.12.0, we started seeing some of those other HTTP requests get queued behind the long polling request and sometimes dropped. The requests that are queued are proxied up to 60 seconds after the request was originally generated. This leads to an upstream timeout in a tool that we’re using to generate the traffic through the proxy. In the end, the automated traffic generation is not able to complete successfully.

We experience this issue with long polling, but I don’t think this is issue is limited to this use-case. I think this will happen anytime one of the event executor threads handles an HTTP request that takes a long time to complete. Subsequent requests will continue to be assigned to the thread and just queued until the request completes or times-out. The queued requests are never picked-up by any of the other event executor threads even if they are idle.

Besides observing the delayed proxying behavior in the ZAP longs, we were able to see where in the ZAP/Netty code this happens.
During startup, ExtensionNetwork.initEventGroups() creates a DefaultEventExecutorGroup which uses DefaultEventExecutor which subclasses SingleThreadEventExecutor. SingleThreadEventExecutor overrides Executor.execute() by adding the Runnable that handles HTTP request processing to its task queue. During runtime, MainEventHandler.channelRead0() calls DefaultEventExecutor.execute() to offload the processing of the socket channel handler.

To work around the delayed proxying issue, we have changed the number of processors on the host running ZAP so that a different event executor distribution algorithm is used and the thread pool is larger. In addition, we have greatly increased sleep times and wait time-outs in our traffic generating tool to help compensate for the delay in proxying some requests. These changes ultimately increased the runtime of our ZAP scan from ~15 mins to ~4 hours. This will of course increase as we add more coverage for our application and we add traffic for our other applications. This won’t be sustainable. Also, this work-around isn’t stable. It definitely decreased the amount of delays and dropped requests that result in timeouts for our traffic tool, but the success of this work-around really depends on timing and traffic distribution; sometimes we still have issues.

Is there any configuration or solution for this that I am missing? If not, can this issue be addressed?

Thanks
Chris

### Steps to reproduce the behavior

We are reproducing this issue using our website that establishes a long polling connection. Outside of using a site like this, this could probably be reproduced by starting ZAP with -Dio.netty.availableProcessors=1 and -config connection.timeoutInSecs= to a high number of seconds and connecting to a web service that either does long polling or just holds a HTTP request open for a long period of time. While the first connection is established, send a 2nd request. When the first request completes, in the ZAP longs you will see that the 2nd request is proxied with a large delay approximately equal to the time the first request completed minus the time the 2nd request was sent by the browser.

### Expected behavior

Long polling requests should not cause a delay in proxy traffic. We did not have this problem in previous ZAP releases.

### Software versions

OWASP ZAP
Version: 2.12.0
Installed Add-ons: [[id=alertFilters, version=14.0.0], [id=ascanrules, version=49.0.0], [id=automation, version=0.19.0], [id=bruteforce, version=12.0.0], [id=callhome, version=0.5.0], [id=commonlib, version=1.11.0], [id=database, version=0.1.0], [id=diff, version=12.0.0], [id=directorylistv1, version=5.0.0], [id=domxss, version=14.0.0], [id=encoder, version=0.7.0], [id=exim, version=0.3.0], [id=formhandler, version=6.1.0], [id=fuzz, version=13.8.0], [id=gettingStarted, version=14.0.0], [id=graaljs, version=0.3.0], [id=graphql, version=0.11.0], [id=help, version=15.0.0], [id=hud, version=0.15.0], [id=invoke, version=12.0.0], [id=network, version=0.3.0], [id=oast, version=0.13.0], [id=onlineMenu, version=10.0.0], [id=openapi, version=29.0.0], [id=pscanrules, version=44.0.0], [id=quickstart, version=35.0.0], [id=replacer, version=11.0.0], [id=reports, version=0.16.0], [id=requester, version=7.0.0], [id=retest, version=0.4.0], [id=retire, version=0.16.0], [id=reveal, version=5.0.0], [id=scripts, version=33.0.0], [id=selenium, version=15.11.0], [id=soap, version=15.0.0], [id=spider, version=0.1.0], [id=spiderAjax, version=23.10.0], [id=tips, version=10.0.0], [id=webdriverlinux, version=46.0.0], [id=websocket, version=27.0.0], [id=zest, version=37.0.0]]
Operating System: Linux
Architecture: amd64
Java Version: Eclipse Adoptium 11.0.13
System's Locale: en_US
Display Locale: en_GB
Format Locale: en_GB
Default Charset: UTF-8
Look and Feel: Metal (javax.swing.plaf.metal.MetalLookAndFeel)

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment]
The version 2.12 is no longer supported, you should try with 2.13.

**Comment by icongit4c** [comment]
Getting the new version approved and installed and retesting will take time. I pulled the latest code and I see that the same code that I pointed out in the original comment as causing the problem is also in 2.13.0. I pulled network-v0.10.0. Please let me know if I’m not looking at the correct version of the zap-extensions code. Is there something that was changed in ZAP 2.13.0 that I’m missing in-terms of how the event executors handle requests?

**Comment by thc202** [comment]
Point is fixes will not be released to version 2.12 only to the latest release.

**Comment by icongit4c** [comment]
Thanks. Yes we always pull the latest ZAP release before testing during our release cycle. Our cycles are long so we pulled 2.12.0 a few months ago as it was the latest when we were ready to do testing. It took weeks for us to troubleshoot this which is why we're reporting the issue now.

**Comment by thc202** [comment]
I'd suggest report issues sooner rather than later, even if it's just to makes us aware of potential/existing problems.

As for your code query, since version 0.6.0 the proxy/server requests are offloaded to a custom executor. If you are able to try newer versions of the add-ons (rather than the whole ZAP version) in your environment I'd suggest using that version or  newer (up to 0.9.0 inclusive).

**Comment by thc202** [comment]
@icongit4c were you able to try a newer version?

**Comment by icongit4c** [comment]
Hi. Yes, we did a full upgrade to 2.13.0 and we don't see the problem anymore. Thank you!

**Comment by thc202** [comment]
Thank you for letting us know!
