### ISSUE TITLE
OpenAPI Import dialog hangs

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#8011]
### Describe the bug

OpenAPI Import dialog hangs when importing https://catfact.ninja/docs/api-docs.json

### Steps to reproduce the behavior

1. Import an Open API Definition
2. Specify the URL: https://catfact.ninja/docs/api-docs.json
3. "Import"
4. A dialog is shown: "Successfully parsed OpenAPI definition"
5. Click on the "OK" button
6. The "Import OpenAPI Definition" dialog keeps "whirring"

### Expected behavior

The definition will be successfully imported and the dialog will not keep whirring.

### Software versions

Latest code in dev.

### Errors from the zap.log file

None.

### Would you like to help fix this issue?

- [ ] Yes

**Comment by kingthorin** [comment]
Note you seem to be using the new (unreleased) Open API add-on. https://github.com/zaproxy/zap-extensions/commit/5ccf7adaf89d0f1e6321e62057ef4dea243a3280

In 35.0.0 (currently released) this seems to behave properly.

**Comment by thc202** [comment]
The issue does say `Latest code in dev.`

**Comment by kingthorin** [comment]
Oops missed it 🤦‍♂️
