### ISSUE TITLE
Move `ValueGenerator` to an add-on

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#8016]
The core code no longer uses/needs it (spider was moved to an add-on) and the add-ons that rely on it can start relying on other add-on (maybe Common Library?).
This will make it easier to add new functionality and not depend on core releases.

Related to zaproxy/zap-extensions#4795.

**Comment by thc202** [comment]
Also, a good opportunity to tidy up the interface.

**Comment by thc202** [comment]
The core code that needs to be moved is just the interface and the default implementation, both really small compared to `formhandler`.

The zap-extensions add-ons that are using the interface/implementation are `graphql`, `openapi`, `soap`, and `spider`, all of them already depend on `commonlib`.

**Comment by kingthorin** [comment]
Okay, fair enough.

**Comment by karthikuj** [comment]
Yes, I think this will also make it easier to add more default values for different mime types in file input.
