### ISSUE TITLE
Some characters not displayed in the Language combo box

### ISSUE THREAD

**Issue by hkly-1245** [zaproxy/zaproxy#8018]
### Describe the bug

When the en_US locale is used, in the "Options" window then "Language" menu, some Select Box items for the "Languages:" option are not displayed correctly. This probably because of an encoding error. 

### Steps to reproduce the behavior

Go to "Tools" menu -> click "Options" 

In the Option window, Select "Language" item from the "Options" Select drop down.  

In the "Language" form: click on the "Language" SelectBox, scroll to the bottom.

### Expected behavior

For each locale, each item in the Language Select Box should be correctly encoded.  

### Software versions

ZAP
Version: Dev Build

Installed Add-ons: [[id=callhome, version=0.8.0], [id=help,
version=17.0.0], [id=help_ar_SA, version=2.0.0],
[id=help_az_AZ, version=1.0.0], [id=help_bs_BA,
version=10.0.0], [id=help_da_DK, version=1.0.0],
[id=help_de_DE, version=1.0.0], [id=help_el_GR,
version=1.0.0], [id=help_es_ES, version=11.0.0],
[id=help_fa_IR, version=1.0.0], [id=help_fil_PH,
version=4.0.0], [id=help_fr_FR, version=11.0.0],
[id=help_hi_IN, version=1.0.0], [id=help_hr_HR,
version=1.0.0], [id=help_hu_HU, version=1.0.0],
[id=help_id_ID, version=4.0.0], [id=help_it_IT,
version=1.0.0], [id=help_ja_JP, version=11.0.0],
[id=help_ko_KR, version=1.0.0], [id=help_ms_MY,
version=2.0.0], [id=help_pl_PL, version=1.0.0],
[id=help_pt_BR, version=12.0.0], [id=help_ro_RO,
version=1.0.0], [id=help_ru_RU, version=3.0.0],
[id=help_si_LK, version=1.0.0], [id=help_sk_SK,
version=1.0.0], [id=help_sl_SI, version=1.0.0],
[id=help_sq_AL, version=1.0.0], [id=help_sr_CS,
version=1.0.0], [id=help_sr_SP, version=1.0.0],
[id=help_tr_TR, version=3.0.0], [id=help_ur_PK,
version=1.0.0], [id=help_zh_CN, version=4.0.0], [id=network,
version=0.11.0]]

Operating System: Windows 10
Architecture: amd64
Java Version: Oracle Corporation 17.0.2
System's Locale: en_US
Display Locale: en_GB
Format Locale: en_US
Default Charset: windows-1252
ZAP Home Directory: C:\Users\hkly\ZAP_D\
ZAP Installation Directory: C:\Users\hkly\OneDrive\Documents\GitHub\git_collabs\zaproxy\zap\src\main\dist\.\
Look and Feel: FlatLaf Light (com.formdev.flatlaf.FlatLightLaf)

### Screenshots

![image](https://github.com/zaproxy/zaproxy/assets/133721553/2176d8cf-c78d-4f77-9ae8-1a367bacac10)

### Would you like to help fix this issue?

- [X] Yes

**Comment by thc202** [comment]
That's a problem with the font which is not able to render those characters. You might want to selected other font in the Display options panel (assuming the system has one that is able to render those characters, it works fine in macOS and Linux distros).

**Comment by kingthorin** [comment]
Might need to ensure use of composite fonts.

https://github.com/zaproxy/zaproxy/issues/5542#issuecomment-611515462

**Comment by thc202** [comment]
Does it explain why it's rendered correctly in other systems/fonts? If you select Arial in Windows the Kanji is no longer rendered while with the default font it is.

**Comment by kingthorin** [comment]
Hmm good question, I'm not sure.
