### ISSUE TITLE
Update Download Icon

### ISSUE THREAD

**Issue by hkly-1245** [zaproxy/zaproxy#8043]
### Is your feature request related to a problem? Please describe.

User interface icons must be as meaningful to the user as they can get. In the main window lower bar, the download icon design is curently a blue arrow with a colored windows (vista?) icon.

![image](https://github.com/zaproxy/zaproxy/assets/133721553/6b26bef3-c84d-47fd-9501-9f1c59f66590)

![image](https://github.com/zaproxy/zaproxy/assets/133721553/f1d4e1a4-4e47-40b7-be55-7fb53955e8c4)

This could confuse the user since ZAP is a multi-OS tool that runs in a variety of environements, not only windows.

### Describe the solution you'd like

Remove the old windows logo for a clean blue arrow. 

![image](https://github.com/zaproxy/zaproxy/assets/133721553/9620f03b-718e-4e0a-9db6-f4a1d794a9a3)

Eventualy, if the windows logo was here to put an emphasis on the file system, add to it a more generic file symbol.

### Describe alternatives you've considered

Change the arrow color for a green arrow. This seems confusing since green arrows icons are used in the requester and in panels to select items in lists.

### Would you like to help fix this issue?

- [X] Yes

**Comment by kingthorin** [comment]
It should probably use one of the standard ZAP blues, unfortunately I do t know the names/codes off the top of my head.

**Comment by psiinon** [comment]
Choosing icons for ZAP is hard - like most security tools ZAP does a lot of 'weird' things, and none of the core team are graphics artists 😉 
Its for this reason we always recommend icons from (or made up from) the Diagona or Fugue icon sets: https://p.yusukekamiyamane.com/
This keeps the overall look and feel of ZAP more consistant.
We do make exceptions for add-ons specific to a particular technology like python of course.

The current [download.png](https://p.yusukekamiyamane.com/icon/search/fugue/icon/download.png) icon is from that set.
It is actually an arrow with coloured blocks in it, which ties in well with the [block.png](https://p.yusukekamiyamane.com/icon/search/fugue/icon/block.png) we use for add-ons. It is not, as far as I am aware, related to Vista.

This is actually one of the icons I think does a good job of representing downloading so I'm not in favour of changing it unless the replacement is clearly better while staying in the same style as the existing icons.

**Comment by psiinon** [comment]
OK, ok, its a Friday, and its nearly beer o'clock, so I created this based on 2 existing fugue icons.
Thoughts?

![add0n-download](https://github.com/zaproxy/zaproxy/assets/1081115/2e863b22-0696-472a-b618-00e5c328412f)

**Comment by kingthorin** [comment]
I’m good with that if it fits the normal/default dimensions.

**Comment by psiinon** [comment]
2nd option:

![download-addon](https://github.com/zaproxy/zaproxy/assets/1081115/23bfa598-38a5-4477-b607-d98e77c14d9e)

**Comment by psiinon** [comment]
With slightly lighter background (discussing in irc;)

![download-addon-2](https://github.com/zaproxy/zaproxy/assets/1081115/58e65917-5648-4b3c-b935-ca53fab15eb5)
