### ISSUE TITLE
OSX version Ventura (13.5.1) not correctly supported by zap.sh script

### ISSUE THREAD

**Issue by Lyr** [zaproxy/zaproxy#8046]
### Describe the bug

The double click on the "OWASP ZAP.app" icon on Application directory on OSX Ventura (default installation) doesn't run anything and any error appears.

### Steps to reproduce the behavior

1. Download version 2.13.0 of Zap
2. Unzip the downloaded file
3. Paste the "OWASP ZAP.app"  on Application directory
4. Launch ""OWASP ZAP.app" as other application

### Expected behavior

The ZAP application must be launched or at least an error must appear for the final user.

### Software versions

2.13.0

### Errors from the zap.log file

no zap.log have been written at this step.

### Additional context

When the run in a terminal, this error appears :
_ZAP requires a minimum of Java 11 to run, found_

### Would you like to help fix this issue?

- [X] Yes

**Comment by thc202** [comment]
This is unrelated to the macOS version, running Ventura and not seeing that issue.

**Comment by Lyr** [comment]
Yes, you right, it's more the "$OS" = "Darwin", also, it's the java management on OSX that is the root cause, anyway, as first user on Ventura this part doesn't work, so I precise the OSX version cause I haven't other way to test on other version/OS

**Comment by thc202** [comment]
It's not just `"$OS" = "Darwin"` since I'm using different versions of macOS and they work fine (though I'm still not using 13.5.1 which I guess it might have changed something).
In any case the proposed fix is not correct, should not blanket all 13.x versions.

**Comment by Lyr** [comment]
I guess this part of code first have been good reason to be here (for some specific context on osx) so I'm not able to validate this part on other osx version, just the patch works on osx ventura.

**Comment by thc202** [comment]
Would be better to know why it's not finding the bundled Java version which is the root cause of the issue.

**Comment by Lyr** [comment]
> Would be better to know why it's not finding the bundled Java version which is the root cause of the issue.

I remove all the part 'if [ "$OS" = "Darwin" ]' and it looks ok (also for Ventura only). That could mean this old script code is useless now? But since whic osx version?

**Comment by thc202** [comment]
See https://github.com/zaproxy/zaproxy/blob/438f49c3db13eaff90c6c68a6e5c663a4dc4dc7c/zap/src/main/dist/zap.sh#L22

We want to use the bundled version first.

Try check the result of the commands in: https://github.com/zaproxy/zaproxy/blob/438f49c3db13eaff90c6c68a6e5c663a4dc4dc7c/zap/src/main/dist/zap.sh#L46

That should help know what the problem is.

**Comment by Lyr** [comment]
> 

Yes this one https://github.com/zaproxy/zaproxy/blob/438f49c3db13eaff90c6c68a6e5c663a4dc4dc7c/zap/src/main/dist/zap.sh#L46

works now on osx, but this line never been executed if "if [ "$OS" = "Darwin" ]; then",  cause the code fail on this part

**Comment by Lyr** [comment]
The main root cause is that, on the bundle jvm : 
/Applications/OWASP\ ZAP.app/Contents/PlugIns/jre-jdk-11.0.19+7-jre/Contents/Home/bin/java 
zsh: bad CPU type in executable: /Applications/OWASP ZAP.app/Contents/PlugIns/jre-jdk-11.0.19+7-jre/Contents/Home/bin/java
So after, the line to catch java version doesn't work well

**Comment by thc202** [comment]
Which DMG did you download? And what CPU arch do you have?

**Comment by Lyr** [comment]
CPU : 
```
sysctl -a | grep brand
machdep.cpu.brand_string: Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
```
DMG from : 
https://github.com/zaproxy/zaproxy/releases/download/v2.13.0/ZAP_2.13.0.dmg

md5sum :
b7355ec3c46928c004b32b56c12adcbc  ZAP_2.13.0.dmg

**Comment by thc202** [comment]
That works fine here:
```
/Applications/OWASP\ ZAP.app/Contents/PlugIns/jre-jdk-11.0.19+7-jre/Contents/Home/bin/java --version
openjdk 11.0.19 2023-04-18
OpenJDK Runtime Environment Temurin-11.0.19+7 (build 11.0.19+7)
OpenJDK 64-Bit Server VM Temurin-11.0.19+7 (build 11.0.19+7, mixed mode)
```
And:
```
sysctl -a | grep brand
machdep.cpu.brand_string: Intel(R) Core(TM) …
```

The md5 sum is the same here.

What does the following give you?
```
file /Applications/OWASP\ ZAP.app/Contents/PlugIns/jre-jdk-11.0.19+7-jre/Contents/Home/bin/java
```

**Comment by Lyr** [comment]
file /Applications/OWASP\ ZAP.app/Contents/PlugIns/jre-jdk-11.0.19+7-jre/Contents/Home/bin/java :
/Applications/OWASP ZAP.app/Contents/PlugIns/jre-jdk-11.0.19+7-jre/Contents/Home/bin/java: Mach-O 64-bit executable arm64

**Comment by thc202** [comment]
Hmm, based on that it seems you downloaded/installed [ZAP_2.13.0_aarch64.dmg](https://github.com/zaproxy/zaproxy/releases/download/v2.13.0/ZAP_2.13.0_aarch64.dmg) instead.

**Comment by Lyr** [comment]
> Hmm, based on that it seems you downloaded/installed [ZAP_2.13.0_aarch64.dmg](https://github.com/zaproxy/zaproxy/releases/download/v2.13.0/ZAP_2.13.0_aarch64.dmg) instead.

Ok, I redo install from scratch with fresh downloaded archive
