### ISSUE TITLE
Spider and Active scan does not work if url in context contains '#'.

### ISSUE THREAD

**Issue by ramanandk9** [zaproxy/zaproxy#8048]
### Describe the bug

When I tried to run active scan and spider on this url -> https://example.com/app1/#/.* zap does nothing. spider immedietly shows progress 100% without any result and active scan always remains at 0%. while with URLs without '#' zap works fine.

![image](https://github.com/zaproxy/zaproxy/assets/52555449/5e5f6d69-02bb-4bc9-b609-01b3005fd158)

### Steps to reproduce the behavior

1. add a urls with '#' in it in scan context.
2. run active scan on it. (verify nothing happens)
3. run spider on it (verify nothing happens)

### Expected behavior

zap should work normally with urls having '#' in them.

### Software versions

Version: 2.13.0

### Screenshots

![image](https://github.com/zaproxy/zaproxy/assets/52555449/9f7275c4-b188-4397-bca2-6a0b80a84bae)

no url found using spider (when url contains '#') progress 100%

![image](https://github.com/zaproxy/zaproxy/assets/52555449/fd8efb48-72aa-4da9-9895-0693d3c29c29)

active scan does not starts.

### Errors from the zap.log file

***** here in logs url does not included '#', while seems before scan '#' is removed from url. *****

2023-09-01 16:41:40,967 [ZAP-SpiderInitThread-8] INFO  SpiderThread - Starting spidering scan on https://example.com/app1/ at 2023-09-01T16:41:40.967+0530
2023-09-01 16:41:40,967 [ZAP-SpiderInitThread-8] INFO  Spider - Spider initializing...
2023-09-01 16:41:40,967 [ZAP-SpiderInitThread-8] INFO  Spider - Starting spider...
2023-09-01 16:41:40,967 [ZAP-SpiderInitThread-8] WARN  Spider - No seeds available for the Spider. Cancelling scan...
2023-09-01 16:41:40,967 [ZAP-SpiderInitThread-8] INFO  SpiderThread - Spider scanning complete: false on https://example.com/app1/ at 2023-09-01T16:41:40.967+0530
2023-09-01 16:41:48,028 [AWT-EventQueue-0] INFO  Scanner - scanner started
2023-09-01 16:41:48,028 [Thread-1653] INFO  Scanner - scanner completed in 0s

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment]
The fragments/anchors are not sent to the server side, the regular expression should not include them.

**Comment by psiinon** [comment]
Remove the `#` and everything after it.
ZAP will not (currently) see those fragments.

**Comment by ramanandk9** [comment]
removing '#' results in wrong url, 
like correct url is: app.com/#/app/1
but zap scans it like app.com/app/1 which results in an error page.

**Comment by psiinon** [comment]
Remove the `#` **and everything after it**

The traditional spider is not likely to work well with this app.
You should be able to provide the full URL with the complete fragment to the AJAX Spider - if that doesnt work then its a bug.

**Comment by ramanandk9** [comment]
tried with Ajax spider, that too eliminating '#'.

**Comment by psiinon** [comment]
OK, that could be a bug then.
Theres no point in the traditional spider or active scanner supporting fragments, it makes no sence for them.
The AJAX spider is another matter - it opens the URL in browsers so can handle fragments.

Why doesnt the active scanner need to handle them?
Because it attacks the requests made to the server - those do not contain fragments.
The only exception is the DOM XSS scanner, but we have plans for that - stay tuned for more news..

**Comment by ramanandk9** [comment]
steps: 1. attack with ajax spider on url like: https://example.com/scope1/#/app/1/dashboard.
2. for all such urls in ajax spider console it will show urls like: example.com/scope1/app/1/dashboard.
as this is not correct url so spider will end up very quickly with few wrong urls.

In case of more info needed please specify what is needed.
thankyou

**Comment by ramanandk9** [comment]
checked with non-headless browser (firefox), none of the discovered url contained '#'. (expected all urls to contain '#')

**Comment by psiinon** [comment]
Which URLs?
If they are the ones received by ZAP then they will not contain fragments - those are not sent to the server and so are not (currently) seen by ZAP.

**Comment by ramanandk9** [comment]
you are right, in browser I can see it is showing correct url, the isue there is it is opening a lot of browsers, and looping on the same url.

**Comment by psiinon** [comment]
Yes, crawljax does loop on the same URL quite a bit. Its actually doing quite a lot - trying to interact with GUI components, so while it might appear to be doing nothing different it may well be doing some very different things.

**Comment by ramanandk9** [comment]
on a lighter note: when it is expected that server side will support fragments/anchors? As it makes no sense to run only ajax spider. there is not much informative results.

**Comment by psiinon** [comment]
Technically server side can never support fragments - they do not get sent from the browser.
However we are working on getting this info directly from the browser and exposing it in ZAP.
Expect an announcement fairly soon...

**Comment by ramanandk9** [comment]
great, thankyou for answers.
