### ISSUE TITLE
Allow to choose the font for Script Console's code text area

### ISSUE THREAD

**Issue by rtqate** [zaproxy/zaproxy#8065]
### Describe the bug

1. The font in the Script Console tab is too small.
2. The font type in the tab is different from what is set in Options>Display>Work Panel Font.
3. Additionally, the color contrast in this tab may need improvement.

### Steps to reproduce the behavior

1. Make sure a dark theme is active (Flat Dark or Flat Darcula), and the Work Panels Font under Options>Display is set to a comfortable value (e.g., 20). Choose a font type. Restart ZAP Proxy, if needed.
2. Go to the Requester tab, and note that the font settings are respected.
3. Go to the Script Console tab, and check the font size and type.

### Expected behavior

The font size and name, in the Script Console tab, should be same as set by the user.

### Software versions

zaproxy 2.12.0 
(I haven't upgraded  ZAP yet, waiting for 2.13 in the Arch repo.)

----------------------------------------------
OWASP ZAP
Version: 2.12.0

Installed Add-ons: [[id=alertFilters, version=16.0.0],
[id=ascanrules, version=55.0.0], [id=automation,
version=0.29.0], [id=bruteforce, version=13.0.0],
[id=callhome, version=0.6.0], [id=commonlib,
version=1.14.0], [id=custompayloads, version=0.12.0],
[id=database, version=0.1.0], [id=diff, version=12.0.0],
[id=directorylistv1, version=5.0.0], [id=domxss,
version=15.0.0], [id=encoder, version=1.1.0], [id=exim,
version=0.5.0], [id=formhandler, version=6.3.0], [id=fuzz,
version=13.9.0], [id=gettingStarted, version=14.0.0],
[id=graaljs, version=0.3.0], [id=graphql, version=0.17.0],
[id=help, version=15.0.0], [id=hud, version=0.16.0],
[id=invoke, version=12.0.0], [id=network, version=0.9.0],
[id=oast, version=0.15.0], [id=onlineMenu, version=10.0.0],
[id=openapi, version=34.0.0], [id=pscanrules,
version=49.0.0], [id=pscanrulesAlpha, version=39.0.0],
[id=pscanrulesBeta, version=33.0.0], [id=quickstart,
version=37.0.0], [id=replacer, version=12.0.0], [id=reports,
version=0.22.0], [id=requester, version=7.2.0], [id=retest,
version=0.5.0], [id=retire, version=0.23.0], [id=reveal,
version=5.0.0], [id=scripts, version=38.0.0], [id=selenium,
version=15.12.1], [id=soap, version=17.0.0], [id=spider,
version=0.4.0], [id=spiderAjax, version=23.14.1], [id=tips,
version=10.0.0], [id=webdriverlinux, version=56.0.0],
[id=websocket, version=28.0.0], [id=zest, version=38.0.0]]

Operating System: Linux
Architecture: amd64
Java Version: N/A 17.0.8.1
System's Locale: en_US
Display Locale: en_GB
Format Locale: en_US
Default Charset: UTF-8
ZAP Home Directory: /home/art/.ZAP/
ZAP Installation Directory: /usr/share/zaproxy/./
Look and Feel: FlatLaf Dark (com.formdev.flatlaf.FlatDarkLaf)

### Screenshots

![settings_font_](https://github.com/zaproxy/zaproxy/assets/90438548/d3883f46-7b59-48fb-9f09-f4c2c4226c9f)

![font_script_tiny_](https://github.com/zaproxy/zaproxy/assets/90438548/35660833-6715-4b4d-b610-2101d8f410e6)

### Would you like to help fix this issue?

- [ ] Yes

**Comment by kingthorin** [comment]
2.12 is no longer supported. Please upgrade and let us know if you still encounter this issue.

**Comment by kingthorin** [comment]
I see your arch note 🤦‍♂️

**Comment by kingthorin** [comment]
Please provide full version details as the template requested.

**Comment by rtqate** [comment]
Added the version details  :)

**Comment by kingthorin** [comment]
Thanks!

**Comment by kingthorin** [comment]
I've confirmed this issue and am working on a fix.

**Comment by thc202** [comment]
I'd argue that using a custom font just for Script Console would be better, in fact we could use one by default that's more appropriate for code.

**Comment by kingthorin** [comment]
I believe this was meant to apply to the script output panel not the syntax/code panel.

**Comment by kingthorin** [comment]
Yes, I see that the screenshot actually shows the syntax/code panel. So my conclusion having simply read the text was wrong. I think I'll push a change for the output which can be refined further as we sort out how we'd actually like this handled overall for the scripts add-on (ex: Do we want separate code/output font settings, or simply a separate code font.... are we adding that setting tot he existing scripts options panel or do we need it in core?)

**Comment by kingthorin** [comment]
So the call at SyntaxHighlightTextArea.java#L1269 is supposed to get the font scaled to the default (general) font size. But that doesn't seem to be working.

**Comment by kingthorin** [comment]
I propose:
- We add an "Output" font in Display options to be used both in the script console output and the main/core Output panel (and others?).
- In the scripts add-on an Option is added for "Code" font or something like that, which is used to override RSyntaxTextArea's font when it's set to a user selected option.

**Comment by thc202** [comment]
Sounds good to me. (I think we should also set good defaults but can be other issue.)

**Comment by rtqate** [comment]
Do we know when this will be resolved (or is anything needed, like a user story, etc.)?

**Comment by kingthorin** [comment]
I am currently assigned but haven't started yet. The assignment was left from earlier when I thought there was a possible quick fix. I do intend to get to the outlined fix(es) from a few comments ago but have no timeline.

We can assign or add someone else if they're interested in tackling one or both in the meantime.

**Comment by thc202** [comment]
Tweaked the title to match the earlier proposal and created other issue to handle the output (#8125). This should make this issue simpler (the Script Console now has options, so should be just a matter of adding a new option and apply the font).

**Comment by thc202** [comment]
@kingthorin re https://github.com/zaproxy/zaproxy/issues/8065#issuecomment-1714123427 the PR #6557 (and follow up) needs to be applied to `SyntaxHighlightTextArea`. It could also be tweaked to use the work panels font… that should be even faster to do than adding the new option (which would address the original issue being reported here).
