### ISSUE TITLE
How show pass scan in xml report

### ISSUE THREAD

**Issue by hiran-filho** [zaproxy/zaproxy#8074]
### Describe the bug

Hello,
I'm new to using ZAP, I use it as Docker in a pipeline.

For some time I have been searching on the internet so that the generated xml report contains all scans and not just the one that was presented as a failure. For analytical monitoring.

### Steps to reproduce the behavior

docker run -u 0 -v $(Build.SourcesDirectory)/owaspzap:/zap/wrk/:rw -t owasp/zap2docker-stable zap-api-scan.py -t https://func-gdc-api-dev-01.azurewebsites.net -f openapi -r report.html -x report.xml -l "PASS"

### Expected behavior

I expected that the scans that appear as pass in the prompt would also appear in the report as passed

### Software versions

owasp/zap2docker-stable:latest

### Screenshots

![image](https://github.com/zaproxy/zaproxy/assets/109706220/47898b4c-10f7-4bb5-9b1f-ba8b2e454efe)
![image](https://github.com/zaproxy/zaproxy/assets/109706220/2080a113-a5f6-4c0e-aede-ac76cfa68dee)

### Would you like to help fix this issue?

- [ ] Yes

**Comment by kingthorin** [comment]
Please don't ask questions as issues - the [ZAP User Group]( https://groups.google.com/group/zaproxy-users) is a much better place for questions.

---

The "Pass" output by the packaged scans is simply a summary provided by the packaged scan, it isn't really something tracked by ZAP.

You could look at creating your own custom report template though.
https://www.zaproxy.org/docs/desktop/addons/report-generation/create/

**Comment by hiran-filho** [comment]
@kingthorin ,

Sorry for the location where I opened no sections for questions but I will ask in the group, but how do I generate a report and use an official docker image to solve my problem, sorry for my lack of knowledge
