### ISSUE TITLE
CSP: prefetch-src is deprected and not supported by most Browsers

### ISSUE THREAD

**Issue by ShelwinWu** [zaproxy/zaproxy#8077]
### Describe the bug

ZAP still reports issue when there is no "prefetch-src" directive set for CSP,
![image](https://github.com/zaproxy/zaproxy/assets/139086169/1f9e5371-a3d9-4916-820e-8d62811170a6)

while according to this https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/prefetch-src
the directive is deprecated.

### Steps to reproduce the behavior

Scan against any site that having the following CSP header defined, the tool will report Alert: CSP: Wildcard Directive:

Content-Security-Policy: default-src 'self' https:; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; frame-src 'self'; font-src 'self'; media-src 'self'; object-src 'self'; manifest-src 'self'; worker-src 'self'; form-action 'self'; frame-ancestors 'self';

the alert has this information:
The following directives either allow wildcard sources (or ancestors), are not defined, or are overly broadly defined: 
prefetch-src

### Expected behavior

the "Prefectch-src" directive for CSP is deprecated, missing of it in CSP should be not considered as a vulnerability.

### Software versions

ZAP 2.13.0

### Would you like to help fix this issue?

- [ ] Yes

**Comment by psiinon** [comment]
The screenshot shows you are using ZAP 2.9.0.
That version is very old and is not maintained.
Can you reproduce this in the latest version of ZAP, currently 2.13.0?

**Comment by ShelwinWu** [comment]
the scan was conducted by version 2.13.0, I am using 2.9 to open the session and review the findings.
![image](https://github.com/zaproxy/zaproxy/assets/139086169/66b26bb7-168c-4e99-84f3-a294ded2d245)

**Comment by psiinon** [comment]
Thanks for the update. 
Note that using an older version of ZAP to the one a session was created with could cause any number of problems. We really do not recommend doing that 😀
