### ISSUE TITLE
Add sections to the Traditional HTML report to match the Traditional HTML w/ requests + responses

### ISSUE THREAD

**Issue by FiveOFive** [zaproxy/zaproxy#8088]
### Is your feature request related to a problem? Please describe.

I'd like to use some of the sections from the "Traditional HTML with requests and responses" report that are not available in the "Traditional HTML report", such as the passingrules and statistics. I'm not using the "Traditional HTML with requests and responses" directly because including all of the requests and responses generates much larger report files.

### Describe the solution you'd like

To have the same sections available for the "Traditional HTML" as the "Traditional HTML Report with requests and responses"

### Describe alternatives you've considered

- Creating a custom report template. This works fine for me. I'm opening the issue to see if there is broader interest in updating the Traditional HTML report for all ZAP users
- For ZAP to have just one Traditional HTML report template with the option to include/exclude the requests and responses. That will be easier to maintain vs two different, but very similar templates.

### Would you like to help fix this issue?

- [X] Yes

**Comment by kingthorin** [comment]
The "Traditional" reports are purposefully kept as close to the original core reports as possible.

Anyone is free to submit new templates/options.

**Comment by FiveOFive** [comment]
> The "Traditional" reports are purposefully kept as close to the original core reports as possible.
> 
> Anyone is free to submit new templates/options.
> 
> Other team members may have other thoughts or takes 🤷‍♂️

That makes sense to keep them close to the originals. I probably won't submit these small changes to the Traditional templates as a new template, so I'll close this issue. If we come up with some bigger changes or a new template, we'll definitely send it in.
