### ISSUE TITLE
Raw HTML displayed in options panels for search matches

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#8111]
### Describe the bug

After a user has searched within ZAP's options, the title border(s) within some of the Network options panels display raw HTML instead of properly highlighting.

### Steps to reproduce the behavior

1. Open ZAP.
2. Go into the Option panel.
3. Type "prox" in the search area and hit the magnifying glass button.
4. Goto: Network > Local Servers/Proxies note both the border titles now include raw HTML.

### Expected behavior

The border titles should properly render the text and highlight without raw HTML.

### Software versions

Tested in both current dev and 2.13.0.

Network add-on 0.11.2.

### Screenshots

![image](https://github.com/zaproxy/zaproxy/assets/7570458/555cd8be-cad6-467e-8fc0-4d35cc89a9a1)

### Errors from the zap.log file

None

### Additional context

N/A

### Would you like to help fix this issue?

- [ ] Yes

**Comment by kingthorin** [comment]
Note: I've just tested further this isn't limited to the network add-on. If the user searches for "base" it also occurs on the "Encode/Decode" panels. I believe that it is therefore likely to impact all title borders.

**Comment by thc202** [comment]
This is a side effect of #7488. I don't see a way of tweaking the background for highlight without access to the [`JLabel`](https://github.com/openjdk/jdk/blob/8f8c45b54a0ca2d676b76521fef87fb3a3ccad97/src/java.desktop/share/classes/javax/swing/border/TitledBorder.java#L103) of the `TitleBorder`s…

Fixes/workarounds thought:
- Use reflection to enable the HTML rendering of the affected instances (on highlight) but leads to ugly warn in the output.
- "Fork" the class to use a custom `JLabel` with HTML rendering enabled, requires copying a lot of code and replace all usages of the "old" class.
- Stop using titled borders, which means not have the issue at all but requires changing all the codebase.
- ?

**Comment by psiinon** [comment]
* Accept this issue? 😁

**Comment by thc202** [comment]
I tried that and with the default colour it didn't look ok (lack of contrast), it will require some more work to use the correct colours.
