### ISSUE TITLE
Report issue (html, json, xml) for ZAP version 2.11 to 2.14

### ISSUE THREAD

**Issue by Ch4ng3TheW0rld** [zaproxy/zaproxy#8122]
### Describe the bug

Used solution: Owasp ZAP Headless
1.After scan, we can get alertsSummary and show bellow information.
![image](https://github.com/zaproxy/zaproxy/assets/70000024/f4274a1f-20b6-4de4-bd26-2c9c0e4e4c51)

But when try to get "scanning report" not showing any result, for any used format htmlreport, jsonreport, xmlreport.
![image](https://github.com/zaproxy/zaproxy/assets/70000024/aaab11be-4c98-40f8-84ba-d920098aea5b)

**Impacted version:**
ZAP_2.11.0_Linux.tar.gz
ZAP_2.12.0_Linux.tar.gz
ZAP_2.13.0_Linux.tar.gz
ZAP_2.14.0_Linux.tar.gz

**Version which is working perfectly:**
ZAP_2.10.0_Linux.tar.gz

### Steps to reproduce the behavior

1.Run zap deamon
zap.sh -daemon -host 0.0.0.0 -port 80 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true -config api.key=String

2.delete alerts & set the url
curl -s "http://xxx.amazonaws.com/JSON/alert/action/deleteAllAlerts/?apikey=String"
curl -s "http://xxx.amazonaws.com/JSON/core/action/accessUrl/?apikey=String&url=https://www.xxxxxx&followRedirects=false"

3.Start scan
curl -s "http://xxx.amazonaws.com/JSON/ascan/action/scan/?apikey=String&zapapiformat=JSON&formMethod=GET&url=https://www.xxxxxx&recurse=&inScopeOnly=false&scanPolicyName=&method=&postData=&contextId="

4.check status
curl "http://xxx.amazonaws.com/JSON/ascan/view/status/?apikey=String&scanId=0"
curl "http://xxx.amazonaws.com/JSON/alert/view/alertsSummary/?apikey=String&baseurl=https://www.xxxxxx"

5.Report
http://xxx.amazonaws.com/OTHER/core/other/htmlreport/?apikey=String
http://xxx.amazonaws.com/OTHER/core/other/jsonreport/?apikey=String
http://xxx.amazonaws.com/OTHER/core/other/xmlreport/?apikey=String

### Expected behavior

Below alertsSummary, must include in HTML-Report, JSON-Report, XML-Report
![image](https://github.com/zaproxy/zaproxy/assets/70000024/f4274a1f-20b6-4de4-bd26-2c9c0e4e4c51)

### Software versions

**Impacted version:**
ZAP_2.11.0_Linux.tar.gz
ZAP_2.12.0_Linux.tar.gz
ZAP_2.13.0_Linux.tar.gz
ZAP_2.14.0_Linux.tar.gz

**Version which is working perfectly:**
ZAP_2.10.0_Linux.tar.gz

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment]
The steps don't really help reproduce the issue.

**Comment by Ch4ng3TheW0rld** [comment]
Replace "xxx.amazonaws.com" to $ZAP_URL
And Target URL = https://www.xxxxxx (any url.)

then you can see the mismatch information between
alertsSummary
htmlreport

**Comment by kingthorin** [comment]
Makes sense.

- https://www.zaproxy.org/docs/desktop/releases/2.11.0/#report-generation
- https://www.zaproxy.org/docs/desktop/releases/2.11.0/#zap-api-deprecated-endpoints
- https://www.zaproxy.org/docs/api/#zap-api-reports

**Comment by thc202** [comment]
Looks odd still, the old deprecated core report endpoints call the new reports endpoint so they should work the same.
