### ISSUE TITLE
Release process, no debian package generated.

### ISSUE THREAD

**Issue by asziranyi** [zaproxy/zaproxy#8127]
### Describe the bug

This may be a bug in the release process. There is no debian package generated for the releases. Is this a planned change?

### Steps to reproduce the behavior

Go to: https://github.com/zaproxy/zaproxy/releases/tag/v2.14.0
There is no debian package generated.
Go to: https://github.com/zaproxy/zaproxy/releases/tag/v2.13.0
There is '[zaproxy_2.13.0-1_all.deb](https://github.com/zaproxy/zaproxy/releases/download/v2.13.0/zaproxy_2.13.0-1_all.deb)' generated.

### Expected behavior

Generated debian package.

### Software versions

2.14.0

### Would you like to help fix this issue?

- [X] Yes

**Comment by thc202** [comment]
Yes, that was on purpose, you can download deb packages from the downloads page (Linux Repos) https://www.zaproxy.org/download/
