### ISSUE TITLE
Release 1.2.1 version of FileUpload addon

### ISSUE THREAD

**Issue by preetkaran20** [zaproxy/zaproxy#8134]
### Add-on repo

https://github.com/SasanLabs/owasp-zap-fileupload-addon/releases/tag/1.2.1

### Your contact details

preetkaran20@gmail.com

### Are you one of the authors?

- [X] Yes

### Twitter handle for tool or author(s)

sasan_karan

**Comment by thc202** [comment]
There are some exceptions (SasanLabs/owasp-zap-fileupload-addon#21) that (IMO) should be fixed before releasing to the marketplace as it prevents the Options dialogue from being used (improved in #8135).

**Comment by preetkaran20** [comment]
@thc202 Thanks a lot for the PR. I have created a newer release version 1.2.1. 

thanks,
Karan
