### ISSUE TITLE
can't generate a report on 2.14.0

### ISSUE THREAD

**Issue by atlantsecurity** [zaproxy/zaproxy#8138]
### Describe the bug

Failed to generate report: Can't load the XML resource (using TrAX transformer). org.xml.sax.SAXParseException; lineNumber: 5207; columnNumber: 53; An invalid XML character (Unicode: 0x2) was found in the element content of the document.

### Steps to reproduce the behavior

1. Generate PDF report. 
2. Error message. 

### Expected behavior

Report should be generated regardless of input or invalid characters. It's a PDF document. 

### Software versions

2.14.0

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment]
Could you provide the Help > Support Info? Would be good to provide the whole exception as well.

**Comment by thc202** [comment]
The file zap.log in the ZAP home dir: https://www.zaproxy.org/faq/what-is-the-default-directory-that-zap-uses/

**Comment by thc202** [comment]
Closing with the changes done in zaproxy/zap-extensions#5279.

Latest version of Report Generation add-on should no longer fail to generate the report when it contains "invalid" unicode characters.
