### ISSUE TITLE
Add sarif report generation when using zap full san script

### ISSUE THREAD

**Issue by megalucio** [zaproxy/zaproxy#8148]
### Is your feature request related to a problem? Please describe.

I was able to generate a sarif report directly in the tool in the reports section. However this option is not available when we run as a fulls can as per [here](https://www.zaproxy.org/docs/docker/full-scan/) and also can be seen in the [code](https://github.com/zaproxy/zaproxy/blob/main/docker/zap-full-scan.py#L471). Only json report is possible.

### Describe the solution you'd like

When using this functionality it will be nice if sarif report can also be generated.

### Describe alternatives you've considered

Generate the report manually in the tool or using the API but then it gets much more complicated.
This seems to work as well https://github.com/SvanBoxel/zaproxy-to-ghas

### Screenshots
<img width="823" alt="image" src="https://github.com/zaproxy/zaproxy/assets/10451680/84a1a647-d065-4190-913c-2ca58662c7a1">
<img width="819" alt="image" src="https://github.com/zaproxy/zaproxy/assets/10451680/69dccdc3-d109-4008-ba69-6daaf02838d9">

_No response_

### Would you like to help fix this issue?

- [X] Yes

**Comment by thc202** [comment]
See https://github.com/zaproxy/zaproxy/pull/8005#issuecomment-1676468723

**Comment by psiinon** [comment]
Closing because we do not want to kee adding more and more options to the packaged scans.
The automation framework is the way to go, it already supports all of the reports, not just the sarif one.
It can also be run from the command line as well as in docker.
