### ISSUE TITLE
Timestamp Disclosure scan rule should use the HTTP header as alert's parameter

### ISSUE THREAD

**Issue by jkibmus** [zaproxy/zaproxy#8160]
### Is your feature request related to a problem? Please describe.

I have some alerts that were generated due to matches found in response headers that I would like to filter as false positives, but I can't seem to find a way to do so.

Example:

Rule:  Timestamp Disclosure - Unix
Response Header: x-myuuid: 1111.1698202345.1111

The timestamp is found as it should be, but as this case is perfectly safe, I'd like to ignore it if the value comes from this header.

The evidence however is just "1698202345" so there is no context for me to make a filter that would ignore it in the x-myuuid header but continue to report it if it were found  elsewhere.

### Describe the solution you'd like

The following was suggested:
```
It looks like we are not including the parameter in the alert.
Could you raise an issue for us to do that for headers?
You would then be able to filter on that header.
```

### Describe alternatives you've considered

We considered excluding all timestamps from alerts, but that idea is rejected because we only want to mark one specific header as safe to contain timestamps.

### Would you like to help fix this issue?

- [ ] Yes

**Comment by kingthorin** [comment]
For my two cents this is a good case for post processing with a script or external to ZAP.

**Comment by thc202** [comment]
I believe this issue was meant for the specific scan rule to include the corresponding header in the `param` of the alert, @psiinon right?

**Comment by psiinon** [comment]
> I believe this issue was meant for the specific scan rule to include the corresponding header in the `param` of the alert, @psiinon right?

Exactly what I was going to suggest 😁

**Comment by thc202** [comment]
Updated the title.

**Comment by jkibmus** [comment]
Thank you!

**Comment by kingthorin** [comment]
Released this morning as part of: https://github.com/zaproxy/zap-extensions/releases/tag/pscanrules-v53
