### ISSUE TITLE
Include/Exclude import/export URL dialogs maintain previously chosen directory

### ISSUE THREAD

**Issue by double16** [zaproxy/zaproxy#8167]
### Is your feature request related to a problem? Please describe.

When I have several files to import or export, I need to navigate to the directory each time. It's inconvenient.

### Describe the solution you'd like

Keep the last directory used in import/export dialogs as a persistent preference.

### Describe alternatives you've considered

There are none.

### Would you like to help fix this issue?

- [ ] Yes

**Comment by psiinon** [comment]
We should do this for all file selection dialogs, independently of each other.

**Comment by thc202** [comment]
Duplicate of #5945.
