### ISSUE TITLE
client: Allow cells in Client Map and Client History to be individually copied

### ISSUE THREAD

**Issue by double16** [zaproxy/zaproxy#8173]
### Is your feature request related to a problem? Please describe.

I want to copy the storage key out of the table. I can only copy the entire row. The value is binary and large and makes it cumbersome. This occurs for both the Client Map and Client History tables.

### Describe the solution you'd like

Allow each cell to be copied individually. A context menu with "Copy" and using the keyboard would be consistent.

### Describe alternatives you've considered

Editing the pasted content or re-type the value.

### Would you like to help fix this issue?

- [ ] Yes

**Comment by psiinon** [comment]
Good suggestion!

**Comment by psiinon** [comment]
@double16  Unfortunately Java only lets us select individual cells if we enable cell selection, but we dont do that anywhere else and I'm conserned it will look "wrong" (and present us with other usability challenges).
How able separate menu options for "Copy Source URL", "Copy Test" - will that work for you?
Which fields would you want to be able to copy other than the URLs and text?

**Comment by psiinon** [comment]
@double16 thanks. Would be interested in hearing how you are using this info (or planning to) and where you would like the client add-on to go - either here or elsewhere (like the User Group)

**Comment by double16** [comment]
With the client integration with the AJAX spider, I think the view into the local and session storage is great. Otherwise it requires manual inspection. Even with manual inspection it's nice to have the info in ZAP to refer to rather than using dev tools and that will become more useful when the data is persisted. If the data could easily be integrated with decode/view tools like base64 or JSON that makes it better.

**Comment by psiinon** [comment]
Oh - didnt think of encode/decode integration .. but that really makes sense..

**Comment by psiinon** [comment]
Encode/decode suggestion added to https://github.com/zaproxy/zaproxy/issues/5996 - enable for all text fields inc tables 😁

**Comment by psiinon** [comment]
A new version of the client add-on has been released.
Let us know if the new context menu options work for you!

**Comment by double16** [comment]
Works great, thanks!
