### ISSUE TITLE
Visibility is not optimal in Client Details, Client Map tab when using the dark theme

### ISSUE THREAD

**Issue by hahwul** [zaproxy/zaproxy#8175]
### Is your feature request related to a problem? Please describe.

When using the dark themes, some parts in the Client Details and Client Map appear as white areas. This causes visual discomfort. 

![](https://github.com/zaproxy/zaproxy/assets/13212227/591c30c2-b792-46e8-96cd-6f6e9d204693)

I think, It's the themes that need improvement.

- Client Details
  - Flat Dark
  - Flat Dracula
  - CDE/Motif
- Client Map
  - CDE/Motif
  - MacOS X

### Metal
![](https://github.com/zaproxy/zaproxy/assets/13212227/72f3ea19-8ee6-4694-a0b1-adb9e3d56a8e)
*Client Details*

### Nimbus
![](https://github.com/zaproxy/zaproxy/assets/13212227/b4ecff04-4cef-482e-ba8e-810d03e4d388)
*Client Details*

### CDE/Motif
![](https://github.com/zaproxy/zaproxy/assets/13212227/57ba1643-05de-499f-87b0-d28334b7bec5)
*Client Details*

![](https://github.com/zaproxy/zaproxy/assets/13212227/512e02df-746e-4c24-8e7a-bb3bb6f8746c)
*Client Map*

### MacOS X
![](https://github.com/zaproxy/zaproxy/assets/13212227/a5498f3a-3ee3-496d-94f7-4d0793b2aa6f)
*Client Details*

![](https://github.com/zaproxy/zaproxy/assets/13212227/00e8fb77-0ee5-4604-bad5-52377a547801)
*Client Map*

### Flat Light
![](https://github.com/zaproxy/zaproxy/assets/13212227/8a0f3094-0063-4f1b-84a4-2e1385e9b2cc)
*Client Details*

### Flat Dark
![](https://github.com/zaproxy/zaproxy/assets/13212227/1f6ddab5-5544-4a35-9d0c-78c3b369e45c)
*Client Details*

### Flat IntelliJ
![](https://github.com/zaproxy/zaproxy/assets/13212227/d9a1d78a-3696-4728-b153-9d5116058827)
*Client Details*

### Flat Dracula
![](https://github.com/zaproxy/zaproxy/assets/13212227/20213a20-6a37-40af-961d-c1a831ee680e)
*Client Details*

### Describe the solution you'd like

It seems like we need some additional handling for the dark themes in the Client Map and Details tab.

### Describe alternatives you've considered

.

### Would you like to help fix this issue?

- [X] Yes

**Comment by thc202** [comment]
Did you restart after switching themes?

**Comment by hahwul** [comment]
@thc202 
Yes, that's right! The issue still happens after a restart 😭

https://github.com/zaproxy/zaproxy/assets/13212227/c9d6ce57-928f-4926-a92c-e7d1477a80b5

**Comment by hahwul** [comment]
Now client details is look lovely! Thank you so much :D

![](https://github.com/zaproxy/zaproxy/assets/13212227/8d3a7e14-9209-469c-aab8-4a75a31a8923)
