### ISSUE TITLE
Provide a button to "auto-lowercase" HTTP/2 header names in request editors

### ISSUE THREAD

**Issue by ricekot** [zaproxy/zaproxy#8176]
### Is your feature request related to a problem? Please describe.

Sending HTTP/2 requests with header names with uppercase characters in them causes a Stream reset exception.

This can be annoying when you copy HTTP/1.1 requests from e.g. browsers and you want send them as HTTP/2.

### Describe the solution you'd like

Provide a button (like the "Update Host Header" button) in the Manual Request Editor and the Requester to automatically lowercase all header names for convenience.

### Describe alternatives you've considered

Manually inspect and lowercase each header name in the HTTP request.

### Would you like to help fix this issue?

- [ ] Yes

**Comment by amitpanwar789** [comment]
i will like to work on this

**Comment by thc202** [comment]
Assigned, let us know if you have any question.

**Comment by amitpanwar789** [comment]
can you please tell me how can I send request using http/2 protocol as I am using below request where all headers name are in lowercase but I am getting error as `IO error in sending request:class org.apache.hc.core5.http.ConnectionClosedException: Connection is closed`

```
GET http://fonts.gstatic.com/s/i/productlogos/googleg/v6/24px.svg HTTP/1.1
host: fonts.gstatic.com
sec-ch-ua: "chromium";v="113", "not-a.brand";v="24"
sec-ch-ua-mobile: ?0
user-agent: mozilla/5.0 (windows nt 10.0; win64; x64) applewebkit/537.36 (khtml, like gecko) chrome/113.0.5672.127 safari/537.36
sec-ch-ua-platform: "linux"
accept: image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8
x-client-data: cjnnyge=
sec-fetch-site: cross-site
sec-fetch-mode: no-cors
sec-fetch-dest: image
referer: https://www.google.com/
accept-encoding: gzip, deflate
accept-language: en-GB,en-US;q=0.9,en;q=0.8
content-length: 0
```

**Comment by thc202** [comment]
```diff
-GET http://fonts.gstatic.com/s/i/productlogos/googleg/v6/24px.svg HTTP/1.1
-host: fonts.gstatic.com
+GET https://fonts.gstatic.com/s/i/productlogos/googleg/v6/24px.svg HTTP/2
```

**Comment by amitpanwar789** [comment]
I'd like to propose an idea: What if, instead of having a dedicated button in the requester tab, we automatically convert all request headers name to lowercase before sending them? This approach could be beneficial for both HTTP/1.1 and HTTP/2 protocols.

**Comment by thc202** [comment]
We should send what the user wants (whenever possible), they know better what they are testing/verifying.

**Comment by amitpanwar789** [comment]
I've made some modifications to the Requester add-on to gain a better understanding of its inner workings. However, when I run the zap dev  , these changes don't seem to be reflected there. Is there anything specific I need to do, such as updating ZAP Proxy, to apply the Requester changes ?

**Comment by thc202** [comment]
Did you install the add-on? https://www.zaproxy.org/docs/developer/quick-start-build/#installing-zap-add-ons

**Comment by amitpanwar789** [comment]
I am trying to put a extra JToggle button in requestPanel in  [HttpPanelSender.java](https://github.com/zaproxy/zap-extensions/blob/main/addOns/requester/src/main/java/org/zaproxy/addon/requester/internal/HttpPanelSender.java) to convert the http header name to lowercase, but how can i get the all request header name , i guessed i will get it from  [HttpMessage](https://github.com/zaproxy/zaproxy/blob/main/zap/src/main/java/org/parosproxy/paros/network/HttpMessage.java) Class ?  am i thinking right or there is another way to get and modify that information ?

**Comment by thc202** [comment]
That's right, there's an HTTP Sender script that does that: https://github.com/zaproxy/community-scripts/blob/cfa189657909c2594f4c2dd4722cdf95dca91d31/httpsender/UpgradeHttp1To2.js

**Comment by amitpanwar789** [comment]
One question, how can we get HttpMessage class instance in HttpPanelSender Class to modify the http header name from there ?

**Comment by thc202** [comment]
It can be obtained through `requestPanel.getMessage()` (though you should save it first, by calling `saveData()`).

**Comment by amitpanwar789** [comment]
sorry to bother you again, but requestPanel.getMessage() is giving me Message interface, but i need HttpMessage in this getRequestHeader() method which give me all information but i can't do like requestPanel.getMessage().getRequestHeader() ?

**Comment by thc202** [comment]
Not bothering, feel free to ask any time. It's safe to cast it to `HttpMessage`.

Because so far there was no need to, the base panels are generic, they can show any `Message` not just `HttpMessage` and that panel was not needing it.

**Comment by amitpanwar789** [comment]
but then, how can i get HttpMessage , i can't just do requestPanel.getMessage().getRequestHeader() as this is giving me compile time error ?

**Comment by psiinon** [comment]
Something like: `((HttpMessage)requestPanel.getMessage()).getRequestHeader()`

**Comment by psiinon** [comment]
Why cant you use it? Details please!
Also, I'm not sure thats the right method to add.
You can just loop through them and call setHeaderValues(..)

**Comment by thc202** [comment]
Changes done to core will not be visible to add-ons until we release a new version, but I don't think changing core is needed to address this issue (as mentioned in: https://github.com/zaproxy/zaproxy/issues/8176#issuecomment-1832487417).

**Comment by amitpanwar789** [comment]
Okay, I understand. I've added a button to lowercase the header names, and it's working well. Should I submit a pull request now .
```
    private JButton getButtonLowerCaseHeaderName(){
        if(lowerCaseHeaderName == null){
            lowerCaseHeaderName = new JButton(ExtensionRequester.createIcon("lowercase-header-button.png"));
            lowerCaseHeaderName.setToolTipText("Lowercase Headers");
            lowerCaseHeaderName.addActionListener(e->lowerCaseHeaderNameButtonTriggered());
        }
        return lowerCaseHeaderName;
    }

    private void lowerCaseHeaderNameButtonTriggered(){
        customHttpPanelRequest.saveData();
        HttpRequestHeader httpRequestHeader = ((HttpMessage)customHttpPanelRequest.getMessage()).getRequestHeader();
        List<HttpHeaderField> headers = httpRequestHeader.getHeaders();

        for (int i = 0 ; i < headers.size(); i++) {
            httpRequestHeader.setHeader(headers.get(i).getName(),null);
        }
        for(int i = 0; i < headers.size(); i++){
            httpRequestHeader.addHeader(headers.get(i).getName().toLowerCase(Locale.ROOT),headers.get(i).getValue());
        }
        customHttpPanelRequest.updateContent();
    }
```
