### ISSUE TITLE
MP4 video file reported as PHP Source Code Disclosure

### ISSUE THREAD

**Issue by Piedone** [zaproxy/zaproxy#8191]
### Describe the bug

When running the Baseline scan on a single-page website (not SPA, just has one page) that includes an MP4 file as a background animation, ZAP will recognize the video file as PHP source code disclosure.

### Steps to reproduce the behavior

1. Create an Automation Framework plan from the Baseline profile. See mine attached below.
2. Start an [Orchard Core](https://orchardcore.net/) app set up with the [Coming Soon recipe](https://docs.orchardcore.net/en/latest/OrchardCore.Themes/TheComingSoonTheme/Assets/) on localhost. [Here's](https://zapmp4issuedemo.dotnest.net/) an online version of it for your convenience.
3. Run the scan via Docker with `docker run --add-host localhost:host-gateway -v path/to/local/folder:/zap/wrk/:rw -t softwaresecurityproject/zap-weekly:20231113 zap.sh -cmd -autorun /zap/wrk/Baseline.yml`.
4. Observe that the scan takes too long for a single page (on my machine this was about half an hour) and then see in the generated report that the MP4 file was indicated by ZAP as PHP source code disclosure. Attaching the report below.

[Baseline.txt](https://github.com/zaproxy/zaproxy/files/13359433/Baseline.txt)

[Report.zip](https://github.com/zaproxy/zaproxy/files/13359451/Report.zip)

### Expected behavior

The MP4 file isn't considered PHP source code disclosure, and the scan finishes within seconds.

### Software versions

2.14.0 used to create the plan, weekly 20231113 to execute it in Docker. Running under Windows 11. Including details of 2.14.0 below.

ZAP
Version: 2.14.0

Installed Add-ons: [[id=alertFilters, version=18.0.0],
[id=ascanrules, version=58.0.0], [id=authhelper,
version=0.10.0], [id=automation, version=0.33.0],
[id=bruteforce, version=15.0.0], [id=callhome,
version=0.10.0], [id=commonlib, version=1.19.0],
[id=database, version=0.3.0], [id=diff, version=14.0.0],
[id=directorylistv1, version=7.0.0], [id=domxss,
version=18.0.0], [id=encoder, version=1.4.0], [id=exim,
version=0.8.0], [id=formhandler, version=6.5.0], [id=fuzz,
version=13.12.0], [id=gettingStarted, version=16.0.0],
[id=graaljs, version=0.5.0], [id=graphql, version=0.21.0],
[id=help, version=17.0.0], [id=hud, version=0.18.0],
[id=invoke, version=14.0.0], [id=network, version=0.12.0],
[id=oast, version=0.17.0], [id=onlineMenu, version=12.0.0],
[id=openapi, version=38.0.0], [id=postman, version=0.2.0],
[id=pscanrules, version=52.0.0], [id=quickstart,
version=43.0.0], [id=replacer, version=15.0.0], [id=reports,
version=0.26.0], [id=requester, version=7.4.0], [id=retest,
version=0.8.0], [id=retire, version=0.27.0], [id=reveal,
version=7.0.0], [id=scripts, version=43.0.0], [id=selenium,
version=15.16.0], [id=soap, version=20.0.0], [id=spider,
version=0.7.0], [id=spiderAjax, version=23.18.0], [id=tips,
version=12.0.0], [id=webdriverwindows, version=65.0.0],
[id=websocket, version=30.0.0], [id=zest, version=42.0.0]]

Operating System: Windows 11
Architecture: amd64
Java Version: Oracle Corporation 21.0.1
System's Locale: en_US
Display Locale: en_GB
Format Locale: en_US
Default Charset: UTF-8
ZAP Home Directory: C:\Users\lehoc\ZAP\
ZAP Installation Directory: C:\Program Files\ZAP\Zed Attack Proxy\.\
Look and Feel: FlatLaf Light (com.formdev.flatlaf.FlatLightLaf)

### Screenshots

From the report:

![image](https://github.com/zaproxy/zaproxy/assets/1976647/be20002b-4510-45f5-ae3c-f6884b49f9bc)

### Errors from the zap.log file

This is a bit tricky due to Docker, but let me know if this would help and I'll try to present it.

### Would you like to help fix this issue?

- [ ] Yes

**Comment by ricekot** [comment]
https://github.com/StartBootstrap/startbootstrap-coming-soon/blob/master/src/assets/mp4/bg.mp4

**Comment by psiinon** [comment]
We could change all of the source code detection rules to either

- Only work on known text responses
- Ignore known binary responses

Right now they just ignore specific response types like CSS, JS, images and fonts..

**Comment by kingthorin** [comment]
Thanks @ricekot.

My intention was to have the rule ignore binary'ish responses, we have a utility method for that now.

**Comment by Piedone** [comment]
While I can't add anything useful, thank you everyone for being so quick to chime in!

I can keep the demo website up however long it's necessary, it's no issue. But yeah, probably it running on Orchard Core doesn't affect the results. And the code is basically the same as [Start Bootstrap - Coming Soon](https://github.com/StartBootstrap/startbootstrap-coming-soon).

**Comment by kingthorin** [comment]
I'm not actually able to get the file to pop with the Source Code Disclosure rule, but it seems logical to skip binary'ish files anyway.

**Comment by kingthorin** [comment]
Confirmed adding `ResourceIdentificationUtils.responseContainsControlChars(msg)` to the skip conditions addresses the issue. Will PR later today.

**Comment by Piedone** [comment]
Thank you for fixing this so quickly! You don't need [the test site](https://zapmp4issuedemo.dotnest.net/) anymore, right?

**Comment by kingthorin** [comment]
No problem. Yes you can take that offline. Thanks for your support, it's really great when users can provide such specific examples!

**Comment by Piedone** [comment]
Great, thanks!
