### ISSUE TITLE
A new session was started in another window. This session has been closed.

### ISSUE THREAD

**Issue by ding-ning1991** [zaproxy/zaproxy#8195]
### Describe the bug

when i visit "http://localhost:8080/zap" in my browser first it is fine, but when i visit the url second in another windows, my first window show:
<img width="356" alt="image" src="https://github.com/zaproxy/zaproxy/assets/60917904/d2ec3492-7f47-44a4-a1cd-4d80df868d1e">

but i want the zap can be visit in different browser windows even different computer's browser simultaneously, and the webswing log shows the error log:"The home directory is already in use. Ensure no other ZAP instances are running with the same home directory: /home/zap/.ZAP/"

what can i do to slove this problem? thanks.

### Steps to reproduce the behavior

1. I pull the zap docker image:  zaproxy:stable , 
2. I start  the stable image and change the container file:/zap/webswing/webswing.config, main change the field:"maxClients" : from value 1 to 5, "sessionMode" value from "CONTINUE_FOR_BROWSER" to  "CONTINUE_FOR_BROSE", Here is my webswing.config:
 {
  "/" : {
    "path" : "/",
    "security" : {
      "module" : "EMBEDED",
      "config" : {
        "users" : [ {
          "username" : "admin",
          "password" : "pwd",
          "roles" : [ "admin" ]
        }, {
          "username" : "support",
          "password" : "pwd",
          "roles" : [ "support" ]
        }, {
          "username" : "user",
          "password" : "pwd"
        } ]
      },
      "classPath" : [ ]
    },
    "langFolder" : "${webswing.configDir}/lang",
    "homeDir" : "${user.dir}",
    "allowedCorsOrigins" : [ "*" ],
    "adminConsoleUrl" : "http://localhost:8090"
  },
  "/zap" : {
    "path" : "/zap",
    "webFolder" : "",
    "icon" : "icon.png",
    "security" : {
      "module" : "INHERITED",
      "classPath" : [ ],
      "authorizationConfig" : {
        "users" : [ ],
        "roles" : [ ]
      }
    },
    "swingConfig" : {
      "allowUpload" : true,
      "allowDownload" : true,
      "isolatedFs" : false,
      "theme" : "Murrine",
      "directdraw" : false,
      "javaFx" : true,
      "debug" : false,
      "userDir" : "",
      "jreExecutable" : "${java.home}/bin/java",
      "javaVersion" : "${java.version}",
      "launcherType" : "Desktop",
      "launcherConfig" : {
        "args" : "-host 0.0.0.0 -port 8090",
        "mainClass" : "org.zaproxy.zap.ZAP"
      },
      "dockMode" : "ALL",
      "swingSessionTimeout" : 300,
      "allowDelete" : true,
      "allowAutoDownload" : true,
      "allowJsLink" : true,
      "fontConfig" : { },
      "classPathEntries" : [ "zap-*.jar" ],
      "transferDir" : "${user}/upload",
      "transparentFileSave" : true,
      "clearTransferDir" : true,
      "transparentFileOpen" : true,
      "timeoutIfInactive" : false,
      "allowLocalClipboard" : true,
      "allowServerPrinting" : false,
      "homeDir" : "/zap"
    },
    "enabled" : true,
    "langFolder" : "",
    "maxClients" : 5,
    "monitorEdtEnabled" : true,
    "allowStealSession" : true,
    "goodbyeUrl" : "",
    "name" : "ZAP",
    "autoLogout" : true,
    "sessionMode" : "CONTINUE_FOR_USER",
    "uploadMaxSize" : 5,
    "webHomeDir" : "/zap"
  }
}

3. I commit this container and use the follow command to start zap in my linux server:
docker run -u zap -p 8080:8080 -p 8090:8090 -i zaproxy:test zap-webswing.sh
4. i visit "http://localhost:8080/zap" in my browser first it is fine, but when i visit the url second in another windows, my first window show:A new session was started in another window. This session has been closed.

### Expected behavior

i want the zap can be visit in different browser windows even different computer's browser simultaneously

### Software versions

zap--->ZAP2.14.0
webswing--->22.2.4

### Would you like to help fix this issue?

- [ ] Yes

**Comment by psiinon** [comment]
Sorry, this just is not possible.
The ZAP desktop is designed to be single user - you cannot have to versions of the desktop used by different users which still work on the same db.
On top of this, WebSwing does not support multiple users accessing an app in this way.
You can still access ZAP via WebSwing in one window and proxy through ZAP to your target app in another as described on https://www.zaproxy.org/docs/docker/webswing/#proxying-through-zap

**Comment by ding-ning1991** [comment]
> Sorry, this just is not possible. The ZAP desktop is designed to be single user - you cannot have to versions of the desktop used by different users which still work on the same db. On top of this, WebSwing does not support multiple users accessing an app in this way. You can still access ZAP via WebSwing in one window and proxy through ZAP to your target app in another as described on https://www.zaproxy.org/docs/docker/webswing/#proxying-through-zap

Oh I know! Thanks
