### ISSUE TITLE
Empty fields in Value Generator appear as "paramValue" in SOAP requests instead of empty string

### ISSUE THREAD

**Issue by apgrucza** [zaproxy/zaproxy#8202]
### Describe the bug

Fields added in the Value Generator can have an empty value. The [documented](https://www.zaproxy.org/docs/desktop/addons/value-generator/) behavior is for this to result in an empty string being used in requests. But for SOAP requests, the field gets a value of `paramValue` instead.

### Steps to reproduce the behavior

1. Go to 'ZAP Desktop UI'.
2. Click 'Tools', 'Options', 'Value Generator' and add a field. Use a name that matches that of a string field in your API, and leave the value empty.
3. Click 'Import', 'Import a WSDL File' and import your API.
4. In the 'Sites' tab, right-click one of the imported API methods and click 'Open in Requester Tab'.
5. In the 'Requester' tab, locate the field in the SOAP request. The value will be `paramValue`, e.g. `<ns1:RequestID>paramValue</ns1:RequestID>`.

### Expected behavior

The value of the field should be empty, e.g. `<ns1:RequestID/>`.

### Software versions

ZAP
Version: 2.14.0

Installed Add-ons: [[id=alertFilters, version=18.0.0],
[id=ascanrules, version=58.0.0], [id=authhelper,
version=0.10.0], [id=automation, version=0.33.0],
[id=bruteforce, version=15.0.0], [id=callhome,
version=0.10.0], [id=commonlib, version=1.18.0],
[id=database, version=0.3.0], [id=diff, version=14.0.0],
[id=directorylistv1, version=7.0.0], [id=domxss,
version=18.0.0], [id=encoder, version=1.4.0], [id=exim,
version=0.7.0], [id=formhandler, version=6.5.0], [id=fuzz,
version=13.12.0], [id=gettingStarted, version=16.0.0],
[id=graaljs, version=0.5.0], [id=graphql, version=0.20.0],
[id=help, version=17.0.0], [id=hud, version=0.18.0],
[id=invoke, version=14.0.0], [id=network, version=0.12.0],
[id=oast, version=0.17.0], [id=onlineMenu, version=12.0.0],
[id=openapi, version=38.0.0], [id=postman, version=0.2.0],
[id=pscanrules, version=52.0.0], [id=quickstart,
version=43.0.0], [id=replacer, version=15.0.0], [id=reports,
version=0.26.0], [id=requester, version=7.4.0], [id=retest,
version=0.8.0], [id=retire, version=0.27.0], [id=reveal,
version=7.0.0], [id=scripts, version=42.0.0], [id=selenium,
version=15.15.0], [id=soap, version=20.0.0], [id=spider,
version=0.7.0], [id=spiderAjax, version=23.17.0], [id=tips,
version=12.0.0], [id=webdriverlinux, version=65.0.0],
[id=websocket, version=30.0.0], [id=zest, version=42.0.0]]

Operating System: Linux
Architecture: amd64
Java Version: Debian 11.0.21
System's Locale: en
Display Locale: en_GB
Format Locale: en
Default Charset: UTF-8
ZAP Home Directory: /home/zap/.ZAP/
ZAP Installation Directory: /zap/./
Look and Feel: FlatLaf Light (com.formdev.flatlaf.FlatLightLaf)

### Would you like to help fix this issue?

- [ ] Yes

**Comment by kingthorin** [comment]
Could you provide a minimal wsdl to reproduce the issue?

**Comment by thc202** [comment]
The add-on tests have one.
