### ISSUE TITLE
Bump the base Docker image from bullseye-slim to bookworm-slim

### ISSUE THREAD

**Issue by sastorsl** [zaproxy/zaproxy#8211]
### Is your feature request related to a problem? Please describe.

zaproxy currently use Debian 11, code name **bullseye**.
The new LTS - Long Term Support - release from Debian is **bookworm**, and has been in LTS since June 2023.

### Describe the solution you'd like

Update the base image for zaproxy to the latest LTS release of Debian - code name **bookworm**.

NB! The default java version in bookworm is openjdk 17.

### Describe alternatives you've considered

There are many small base images around, and evaluating all of them would require feature comparisons, licencing evaluation, etc. I've not undertaken this at this moment.

### Screenshots

N/A

### Additional context

There are quite a few [CVE's](https://en.wikipedia.org/wiki/Common_Vulnerabilities_and_Exposures) in Debian Bullseye at the moment. Quite a few less in Bookworm. Now this may change, but staying current is a way to navigate this territory.

### Would you like to help fix this issue?

- [X] Yes

**Comment by sastorsl** [comment]
See weekly in #8612

**Comment by thc202** [comment]
And stable in #8792.
