### ISSUE TITLE
ZAP quit unexpectedly.

### ISSUE THREAD

**Issue by jauharvp** [zaproxy/zaproxy#8214]
### Describe the bug

Click Reopen to open the application again. Click Report to see more detailed information and send a report to Apple.

### Steps to reproduce the behavior

1. Run ZAP with IntelliJ

### Expected behavior

Run ZAP Dev with IntelliJ

### Software versions

Mac OS 14.0

### Screenshots

![image](https://github.com/zaproxy/zaproxy/assets/13345445/2f815aed-62ba-4ed7-b593-672ac84c5503)

### Errors from the zap.log file

ROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':zap:run'.
 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Process 'command '/opt/homebrew/Cellar/openjdk@17/17.0.9/libexec/openjdk.jdk/Contents/Home/bin/java'' finished with non-zero exit value 133

### Would you like to help fix this issue?

- [X] Yes

**Comment by thc202** [comment]
I'd guess https://bugs.openjdk.org/browse/JDK-8266242 given it has the same exit code and it also happens with macOS. You might want to try with Java 22, in any case crashes are usually a problem with the JRE.
