### ISSUE TITLE
The "Cross Site Scripting (DOM Based)" active scan rule seems to take too much time

### ISSUE THREAD

**Issue by Piedone** [zaproxy/zaproxy#8222]
### Describe the bug

This is not definitely a bug, but perhaps it's a performance issue. I noticed that the "Cross Site Scripting (DOM Based)" active scan rule takes a lot more time, usually two orders of magnitude more, than any other scan rules. Now, it might do this much more work too, but is this indeed expected?

Related user group thead [here](https://groups.google.com/g/zaproxy-users/c/TxHqhnarpuU).

### Steps to reproduce the behavior

1. Use the Automation Framework plan attached here: [FullScanWithScript.txt](https://github.com/zaproxy/zaproxy/files/13517143/FullScanWithScript.txt). This is almost just the Full Scan, but contains a script to print the runtime of each rule, written by @psiinon.
2. Run the scan for a site with at least a couple dozen pages. I don't know how much of a difference the site's content and size make, but I've run it for a local version of https://lombiq.com/. Also, I've run it with the `docker run --add-host localhost:host-gateway -v E:\ShortPath\zap:/zap/wrk/:rw -t softwaresecurityproject/zap-stable:2.14.0 zap.sh -cmd -autorun /zap/wrk/FullScanWithScript.yml` command from under Windows 11, however, neither using the desktop app, nor running with Docker under Ubuntu seems to make a difference.
3. Observe an output similar to what's below. Notice that "Cross Site Scripting (DOM Based)" dominates the scan time with around 140s, with everything else taking at most 8s and usually less than 1s.

### Expected behavior

Cross Site Scripting (DOM Based) also takes only <10s and the scan finishes much faster.

### Software versions

`softwaresecurityproject/zap-stable:2.14.0` Docker image under Windows 11 (and very similar behavior with ZAP desktop v2.14.0 and Docker under Ubuntu).

### Would you like to help fix this issue?

- [ ] Yes

**Comment by kingthorin** [comment]
Doesn't seem surprising to me. It's actually launching browsers (headless by default), having them make specific requests and analyzing the response/state.

**Comment by Piedone** [comment]
Thanks for your quick reply! Is it the only (non-beta) rule that launches browsers?

**Comment by kingthorin** [comment]
It's the only only rule that launches browsers 😉

**Comment by Piedone** [comment]
So it is expected for it to take so much more time than any other rule then, right?

**Comment by Piedone** [comment]
Should I keep this open, then?

**Comment by kingthorin** [comment]
Wait for someone else from the core team to add their thoughts. I suspect so, but a second opinion is a good move.

**Comment by psiinon** [comment]
Its absolutely expected 😁 
As @kingthorin said, the other rules all make requests directly from ZAP. They can do this very quickly.
The DOM XSS rule launches browsers, this is always going to take considerably more time.
And thats one reason why its in its own add-on, so its easy for people to disable if they want.

**Comment by Piedone** [comment]
I see, thank you.
