### ISSUE TITLE
Is there any way to integrate ZAP proxy with selenium or playwright GUI tests , so that when our automated GUI tests are running ZAP can scan and identify vulnerabilities and create report for the same?

### ISSUE THREAD

**Issue by kunalthergaonkar** [zaproxy/zaproxy#8229]
### Is your feature request related to a problem? Please describe.

With docker image we are able to scan only the specified URL and other additional pages which appear only when giving proper input are getting missed with automated securecode box advanced zap scan.

### Describe the solution you'd like

when our automated GUI tests are running ZAP should scan and identify vulnerabilities and create report for the same

### Describe alternatives you've considered

Manual ZAP scan from UI

### Would you like to help fix this issue?

- [X] Yes

**Comment by psiinon** [comment]
The ZAP User Group would be a better place to discuss this: https://groups.google.com/group/zaproxy-users
