### ISSUE TITLE
False-positive for hidden file CWE 538

### ISSUE THREAD

**Issue by epomatti** [zaproxy/zaproxy#8234]
### Describe the bug

The spider is reporting `BitKeeper` as a hidden file. It does not exist in the code base and the response is a redirect 301 Moved Permantently.

Confidence is set to low (default).

![image](https://github.com/zaproxy/zaproxy/assets/6530769/57a59acd-3ebd-43f3-ac32-f61efad4182a)

### Steps to reproduce the behavior

1. Run a traditional or AJAX crawler in a web site using default confidence. Return 301.

### Expected behavior

We would expect no alert when there is a redirect as a response.

### Software versions

```
ZAP
Version: 2.14.0

Installed Add-ons: [[id=alertFilters, version=19.0.0],
[id=ascanrules, version=59.0.0], [id=authhelper,
version=0.10.0], [id=automation, version=0.34.0],
[id=bruteforce, version=15.0.0], [id=callhome,
version=0.10.0], [id=commonlib, version=1.20.0],
[id=database, version=0.3.0], [id=diff, version=14.0.0],
[id=directorylistv1, version=7.0.0], [id=domxss,
version=18.0.0], [id=encoder, version=1.4.0], [id=exim,
version=0.8.0], [id=formhandler, version=6.5.0], [id=fuzz,
version=13.12.0], [id=gettingStarted, version=16.0.0],
[id=graaljs, version=0.5.0], [id=graphql, version=0.21.0],
[id=help, version=17.0.0], [id=hud, version=0.18.0],
[id=importurls, version=9.0.0], [id=invoke, version=14.0.0],
[id=network, version=0.13.0], [id=oast, version=0.17.0],
[id=onlineMenu, version=12.0.0], [id=openapi,
version=38.0.0], [id=postman, version=0.2.0],
[id=pscanrules, version=53.0.0], [id=quickstart,
version=43.0.0], [id=replacer, version=16.0.0], [id=reports,
version=0.26.0], [id=requester, version=7.4.0], [id=retest,
version=0.8.0], [id=retire, version=0.28.0], [id=reveal,
version=7.0.0], [id=saverawmessage, version=7.0.0],
[id=savexmlmessage, version=0.3.0], [id=scripts,
version=43.0.0], [id=selenium, version=15.16.0], [id=soap,
version=20.0.0], [id=spider, version=0.7.0], [id=spiderAjax,
version=23.18.0], [id=tips, version=12.0.0],
[id=webdriverlinux, version=66.0.0], [id=webdrivermacos,
version=66.0.0], [id=webdriverwindows, version=66.0.0],
[id=websocket, version=30.0.0], [id=zest, version=42.0.0]]

Operating System: Windows 11
Architecture: amd64
Java Version: Eclipse Adoptium 17.0.6
System's Locale: en_US
Display Locale: en_GB
Format Locale: en_US
Default Charset: windows-1252
ZAP Home Directory: C:\Users\evand\ZAP\
ZAP Installation Directory: C:\Users\evand\Downloads\ZAP_2.14.0\.\
Look and Feel: FlatLaf Light (com.formdev.flatlaf.FlatLightLaf)
```

### Would you like to help fix this issue?

- [ ] Yes

**Comment by kingthorin** [comment]
If it doesn't exist then return a 404.

Alternatively set up Custom Pages defining your non-compliant 301 for a 404 behaviour. Or use an Alert Filter.

**Comment by psiinon** [comment]
I don't think we should alert on redirects in this case, whatever the "right" way is to handle such a file requests😀

**Comment by thc202** [comment]
From a quick look at the rule it shouldn't be raising an alert for redirects by default: https://github.com/zaproxy/zap-extensions/blob/58fc06e71c9477adcac67a5ae7bd8c65628a3782/addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/HiddenFilesScanRule.java#L125-L140

**Comment by kingthorin** [comment]
1. As you can see from the alert this is for the active scanner so the repo steps are invalid.
2. You mentioned confidence a lot, were you meaning to say Threshold a bunch of those times?

As far as I see from the rule you would have had to set Threshold High for ZAP to return such an alert.
https://github.com/zaproxy/zap-extensions/blob/main/addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/HiddenFilesScanRule.java

But it seems like this rule is treating Threshold backward 🤷‍♂️ https://www.zaproxy.org/docs/desktop/ui/dialogs/scanpolicy/#threshold

I’ll rework that.

**Comment by kingthorin** [comment]
I’m wrong, it wouldn’t have had to be High because BitKeeper is a custom payload.

**Comment by kingthorin** [comment]
Based on the logic of the rule it’s hitting the is200 branch then isCustom so either there’s an incorrect Custom Page definition or Analyser misidentified some behaviour/handling.

Without further specifics we won’t be able to address the original issue.

**Comment by thc202** [comment]
We should be including that info in the alerts.

**Comment by kingthorin** [comment]
Wouldn't that require core changes? Or do you just mean the conditions within the rule itself? (In this case it has to be those branches due to Medium Risk/Low Confidence, I guess we could include that as "Other Info" though).

**Comment by epomatti** [comment]
@kingthorin 

> If it doesn't exist then return a 404.

We don't get alerts for other files, except for this one.
I'll talk with the team and check if 404 makes more sense.

> incorrect Custom Page definition

I haven't set any of that, ZAP is new from the repository and only running the crawler.

> Without further specifics we won’t be able to address the original issue.

Let me know if there's any information or test I can do.

**Comment by kingthorin** [comment]
> We don't get alerts for other files, except for this one.

Let us know what you find out, we do t have access to your environment, I can’t tell you why that one would behave any differently.

> I haven't set any of that, ZAP is new from the repository and only running the crawler.

You would have had to run an active scan to get that alert. You can see that in the screenshot you provided.

**Comment by epomatti** [comment]
@kingthorin the frontend code is hosted on AWS Amplify. It looks like Amplify expects the `/` at the end, but it could be the application route (I don't think so, the build should be static so it doesn't make sense to me).

I'll investigate further.

![image](https://github.com/zaproxy/zaproxy/assets/6530769/271d63ee-443d-4b25-85e6-12db20cfaf3a)

![image](https://github.com/zaproxy/zaproxy/assets/6530769/1ba34458-7610-4a53-b964-2733d4cf2c31)

**Comment by epomatti** [comment]
@kingthorin is it possible to set the crawlers to add a `/` at the end of the URL?

This `http://example.com/BitKeeper/` instead of this `http://example.com/BitKeeper`.

Our frontend build is a static export, and Amplify adds a trailing slash by default if there isn't one, as explored [here][1] and [here][2].

I would like to keep Amplify default behavior.

[1]: https://github.com/aws-amplify/amplify-hosting/issues/2719
[2]: https://stackoverflow.com/questions/58032225/prevent-aws-amplify-from-adding-trailing-slash-and-forcing-redirect

**Comment by kingthorin** [comment]
It's looking for a file not a directory.

**Comment by thc202** [comment]
@epomatti were you able to find out why it passed the 200 check with a 301?

**Comment by epomatti** [comment]
@thc202 it didn't pass, still reports as a low severity alert. I'll handle it as false-positive.

**Comment by thc202** [comment]
With passing the 200 check I mean this if statement, https://github.com/zaproxy/zap-extensions/blob/58fc06e71c9477adcac67a5ae7bd8c65628a3782/addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/HiddenFilesScanRule.java#L125 which would be a bug somewhere.

**Comment by kingthorin** [comment]
So do you have further details? A packet capture or something?

**Comment by epomatti** [comment]
```go
package main

import (
	"fmt"
	"net/http"
)

func main() {
	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprintf(w, "ok")
	})

	http.HandleFunc("/BitKeeper", func(w http.ResponseWriter, r *http.Request) {
		http.Redirect(w, r, "/", http.StatusMovedPermanently)
	})

	err := http.ListenAndServe(":8888", nil)
	if err != nil {
		fmt.Println(err)
	}
}
```

![image](https://github.com/zaproxy/zaproxy/assets/6530769/d1c505af-95da-4f5f-8696-45d0791272f0)

**Comment by kingthorin** [comment]
Was the start location for you scan http://localhost:8888 ? (I just want to make sure I'm definitely testing all the same conditions/proceas.)

**Comment by epomatti** [comment]
That's correct.

**Comment by kingthorin** [comment]
Thanks for putting that together, I can confirm that I was able to recreate the issue.

I'll have to debug further but I suspect it has to do with difference in file vs directory 404 handling.

**Comment by kingthorin** [comment]
There seems to be nothing further we can do here since the server responds 200 to the majority of requests and only redirects on specific strings.

![image](https://github.com/zaproxy/zaproxy/assets/7570458/6281faf8-2230-4981-b7d8-bc93c247471a)

**Comment by thc202** [comment]
Still sounds like a bug, where is the 301 being considered a 200, Analyser?

**Comment by thc202** [comment]
That would be great, thank you!
