### ISSUE TITLE
zap-api-scan.py fails with a config file with empty lines

### ISSUE THREAD

**Issue by kovacsbela** [zaproxy/zaproxy#8237]
### Describe the bug

I have pulled `docker pull owasp/zap2docker-weekly:latest@sha256:888516653c34567971d5d8e4b58863c53ea5d6c6baae0e345d56860e35f753a4` and I am running 
```zap-api-scan.py -j -d -t openapi-2414775296.json -f openapi -c zap.conf -r report.html -w report.md -J report.json ...``` on latest weekly `owasp/zap2docker-weekly                             latest                 1c6bca9169a1   16 hours ago    1.86GB`
where `zap.conf` contains empty lines between some other configs, then it exits after printing:
```
2023-12-12 08:53:19,341 Failed to load config file /zap/wrk/zap.conf Unexpected number of tokens on line - there should be at least 3, tab separated:

```
(empty line in 2nd row)

These empty lines are probably not ignored because of (this)[https://github.com/zaproxy/zaproxy/commit/0e5a9b6cf478bb8ba5372e01b64f96adac53abc2#diff-98e727b210699131d2194fd611f0b3144be743fd9bad19109380af5b97a17305L155-R155] change in the logic(1 length of a `\n` is now not ignored) in zaproxy/zaproxy#8230 ? 
Can you please check if this is an intended modification?

### Steps to reproduce the behavior

Run `zap-api-scan.py ` with a `-c` config file that contains an empty line. Once I removed empty lines, my scan start up fine.

### Expected behavior

Ignore empty lines in config file. Empty line is in this case probably a singe new line char?

### Software versions

I pulled via `docker pull owasp/zap2docker-weekly:latest@sha256:888516653c34567971d5d8e4b58863c53ea5d6c6baae0e345d56860e35f753a4`

### Would you like to help fix this issue?

- [X] Yes

**Comment by psiinon** [comment]
ZAP should ignore either completely empty lines or lines starting with a # comment.
The fix is for you to remove those lines or comment them out.

**Comment by psiinon** [comment]
@kovacsbela Just checked and the baseline scan is fine with completely blank lines, so I'm guessing yours had one whitespace character?

**Comment by kovacsbela** [comment]
My config file looks something like:
```
# comment
40045	IGNORE	(Spring4Shell)

# other comment
90004	IGNORE	(Insufficient Site Isolation Against Spectre Vulnerability)
```
resulting in an error complaining about number of the tokens in the empty line:
```
2023-12-12 10:07:28,339 Failed to load config file /zap/wrk/zap.conf Unexpected number of tokens on line - there should be at least 3, tab separated:

```

When I remove the empty line, it just proceeds with the scan:
```
# comment
40045	IGNORE	(Spring4Shell)
# other comment
90004	IGNORE	(Insufficient Site Isolation Against Spectre Vulnerability)
```

Excuse my python here, but when I am trying recreate the python code around load_config, my below snippet results in the output here:
```
config = open('zap.conf', 'r')
for line in config:
  print("line:'{0}' len:{1}".format(line, len(line)))
config.close()
```

output with len=1 for the empty row:
```
line:'# comment
' len:10
line:'40045	IGNORE	(Spring4Shell)
' len:28
line:'
' len:1
line:'# other comment
' len:16
line:'90004	IGNORE	(Insufficient Site Isolation Against Spectre Vulnerability)
' len:73
```


Also I missed one very important detail: my config file was working before current weekly latest tag.

**Comment by kovacsbela** [comment]
Not sure what I am missing, but this says 0:
```
❯ awk '{ print length }' zap.conf
9
27
0
15
72
```

**Comment by psiinon** [comment]
Theres probably an extra whitespace character. It looks like the previous code ignored lines with one character in, while the current code wont do that.
The short term fix for you is to remove those lines or start them with a #
We may change the script to ignore all lines just containing whitespace.

**Comment by kovacsbela** [comment]
We use weekly:latest to scan many services in our CI. This change is breaking many of them, as (probably for readability?) we have - until now considered to be - empty lines in them. Is it possible to revert the threshold to 1, keeping the code compatible with "older" version of the config - just until we get to the bottom of this? When I read through again on my python code, and awk above, I still beleive my line only contains a single new line char, that leads to a len=1.

**Comment by kovacsbela** [comment]
Ah, my colleague experienced with python coming up with a proposal to do len check like: `if line.startswith('#') or len(line.strip()) == 0:`

**Comment by bvidosits** [comment]
We understand the short-term fix, just leaving this issue here that
```
for line in file:
```
with or without `.readlines()` still includes end of line characters, therefore their length will never be 0

**Comment by psiinon** [comment]
Thats how I was thinking of fixing it 😀   
Either of you could submit a PR 😁 If so dont forget to update the changelog with a one line explanation..
