### ISSUE TITLE
generate csv on python after scan

### ISSUE THREAD

**Issue by BlAd373** [zaproxy/zaproxy#8245]
Hi everyone 
I working on personal script on python3
 this is function i using 
scan proceed perfect spider passive and active  scan but receive error 
Can you suggest how i can fix it?

Active Scan completed
Error in ZAP scanning: 'module' object is not callable
Traceback (most recent call last):
  File "2osint.py", line 333, in <module>
    zap_results = zap_get_alerts(f"http://{domain_to_search}", ZAP_API_KEY)
                  ^^^^^^^^^^^^^^
NameError: name 'zap_get_alerts' is not defined

def zap_spider_scan(target, api_key):
    try:
        zap = ZAPv2(apikey=api_key)
        zap.urlopen(target)
        time.sleep(2)
        scanid = zap.spider.scan(target)
        time.sleep(2)
        while int(zap.spider.status(scanid)) < 100:
            print('Spider progress %: {}'.format(zap.spider.status(scanid)))
            time.sleep(2)
        print('Spider completed')

        while int(zap.pscan.records_to_scan) > 0:
            print('Records to passive scan : {}'.format(zap.pscan.records_to_scan))
            time.sleep(2)
        print('Passive Scan completed')

        print('Active Scanning target {}'.format(target))
        scanid = zap.ascan.scan(target)
        while int(zap.ascan.status(scanid)) < 100:
            print('Scan progress %: {}'.format(zap.ascan.status(scanid)))
            time.sleep(5)
        print('Active Scan completed')

        # Fetching alerts
        alerts = zap.core.alerts(baseurl=target)
        pprint(alerts)  # Displaying the alerts

    except Exception as e:
        print(f"Error in ZAP scanning: {e}")

**Comment by kingthorin** [comment]
Seems pretty self explanatory 

> NameError: name 'zap_get_alerts' is not defined

**Comment by kingthorin** [comment]
Please don't ask questions as issues - the [ZAP User Group]( https://groups.google.com/group/zaproxy-users) is a much better place for questions.
