### ISSUE TITLE
Scan report does not have enough details on the alerts

### ISSUE THREAD

**Issue by YanFangJi** [zaproxy/zaproxy#8254]
### Is your feature request related to a problem? Please describe.

The `Parameter` in the instance details are always empty, sometimes `Evidence` is missing, and sometimes `Attack` is missing in the report. Please see below screenshot. 
<img width="1682" alt="image" src="https://github.com/zaproxy/zaproxy/assets/8417452/4ca232d6-4db6-4ac5-a254-21b860019e41">

FYI. I ran the scan using below command:
```
docker run --network=zap-network --name zap \
	-v ${WORKSPACE}:/zap/wrk/:rw -t owasp/zap2docker-weekly \
	zap-api-scan.py -f openapi -z "-addoninstall pscanrulesBeta -config formhandler.fields.field(0).fieldId=status -config formhandler.fields.field(0).value=sold -config formhandler.fields.field(0).enabled=true" -r api-scan-report-zap.html -J api-scan-report-zap.json -t 'https://petstore3.swagger.io/api/v3/openapi.json'
```

### Describe the solution you'd like

We want all the details displayed in the report, what request being made and what parameters/body being used.

Actually I can't even find the request details (request header, parameter, body) in the ZAP log, is this by design and why?

### Describe alternatives you've considered

No.

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment]
The default report does not include the HTTP messages, you would have to use another one, e.g. https://www.zaproxy.org/docs/desktop/addons/report-generation/report-traditional-html-plus/

Not all alerts have a parameter, evidence, or attack, when they don't apply (e.g. a server misconfiguration does not apply to a parameter, a passive alert does not have an attack).

**Comment by YanFangJi** [comment]
@thc202 thanks! I will take a look at the addon. 

Do you know where to find the request details (request header, parameter, body) in the ZAP log?

**Comment by YanFangJi** [comment]
> The default report does not include the HTTP messages, you would have to use another one, e.g. https://www.zaproxy.org/docs/desktop/addons/report-generation/report-traditional-html-plus/
> 
> Not all alerts have a parameter, evidence, or attack, when they don't apply (e.g. a server misconfiguration does not apply to a parameter, a passive alert does not have an attack).

Hi @thc202 , the HTML format you mentioned is available in Desktop version, but not available in Docker version. In docker version, I can't specify other **HTML/JSON** type for `zap-api-scan.py`.
```
    -r report_html    file to write the full ZAP HTML report
    -w report_md      file to write the full ZAP Wiki(Markdown) report
    -x report_xml     file to write the full ZAP XML report
    -J report_json    file to write the full ZAP JSON document
```

**Comment by kingthorin** [comment]
Yup that’s true, it’s one of the limitations of the packaged scans.

**Comment by thc202** [comment]
It might not be provided as a switch but you can still generate any report needed using scan hooks: https://www.zaproxy.org/docs/docker/scan-hooks/

**Comment by psiinon** [comment]
Or you can use the Automation Framework: https://www.zaproxy.org/docs/automate/automation-framework/
The packaged scans are being migrated to use this under the covers so its our recommended option for non trivial authentication.

**Comment by YanFangJi** [comment]
> It might not be provided as a switch but you can still generate any report needed using scan hooks: https://www.zaproxy.org/docs/docker/scan-hooks/

There is no instruction on how to do that. By saying "but you can still generate any report needed", you mean generate report by myself instead of using the addon? So I need to query the session DB to get the request/response details? @thc202

**Comment by YanFangJi** [comment]
> Or you can use the Automation Framework: https://www.zaproxy.org/docs/automate/automation-framework/ The packaged scans are being migrated to use this under the covers so its our recommended option for non trivial authentication.

Thanks! @psiinon is there a planned end date for packaged scan supporting? I will take a look at the automation framework.

**Comment by thc202** [comment]
https://github.com/zaproxy/zaproxy/issues/8254#issuecomment-1865364147

The scan hooks give you access to the ZAP API (`zap` parameter), which can be used to call the API of the add-ons, e.g.: https://www.zaproxy.org/docs/desktop/addons/report-generation/api/

**Comment by YanFangJi** [comment]
@thc202 thanks! I will try to add scan hooks.

**Comment by YanFangJi** [comment]
Hi @thc202 , which scan hook should I use? I see below list of hooks from here https://github.com/zaproxy/community-scripts/blob/main/other/scan-hooks/template.py, but it seems no suitable hook for report generation:
```
def cli_opts(opts):
	print("cli_opts({})".format(opts))

def zap_started(zap, target):
	print("zap_started({}, {})".format(zap, target))

def importing_openapi(target_url, target_file):
	print("importing_openapi({}, {})".format(target_url, target_file))

def importing_soap(target_url, target_file):
	print("importing_soap({}, {})".format(target_url, target_file))

def load_config(config, config_dict, config_msg, out_of_scope_dict):
	print("load_config({}, {}, {}, {})".format(config, config_dict, config_msg, out_of_scope_dict))

def print_rules_wrap(count, inprog_count):
	print("print_rules_wrap({}, {})".format(count, inprog_count))

def start_zap(port, extra_zap_params):
	print("start_zap({}, {})".format(port, extra_zap_params))

def start_docker_zap(docker_image, port, extra_zap_params, mount_dir):
	print("start_docker_zap({}, {}, {}, {})".format(docker_image, port, extra_zap_params, mount_dir))

def start_docker_zap_wrap(cid):
	print("start_docker_zap_wrap({})".format(cid))

def zap_access_target(zap, target):
	print("zap_access_target({}, {})".format(zap, target))

def zap_spider(zap, target):
	print("zap_spider({}, {})".format(zap, target))

def zap_spider_wrap(unused):
	print("zap_spider_wrap(unused)")

def zap_ajax_spider(zap, target, max_time):
	print("zap_ajax_spider({}, {}, {})".format(zap, target, max_time))

def zap_ajax_spider_wrap(unused):
	print("zap_ajax_spider_wrap(unused)")

def zap_active_scan(zap, target, policy):
	print("zap_active_scan({}, {}, {})".format(zap, target, policy))

def zap_active_scan_wrap(unused):
	print("zap_active_scan_wrap(unused)")

def zap_get_alerts(zap, baseurl, denylist, out_of_scope_dict):
	print("zap_get_alerts({}, {}, {}, {})".format(zap, baseurl, denylist, out_of_scope_dict))

def zap_get_alerts_wrap(alert_dict):
	print("zap_get_alerts_wrap({})".format(alert_dict))

def zap_import_context(zap, context_file):
	print("zap_import_context({}, {})".format(zap, context_file))

def zap_import_context_wrap(context_id):
	print("zap_import_context_wrap({})".format(context_id))

def zap_pre_shutdown(zap):
	print("zap_pre_shutdown({})".format(zap))

def pre_exit(fail_count, warn_count, pass_count):
	print("pre_exit({}, {}, {})".format(fail_count, warn_count, pass_count))
```

**Comment by psiinon** [comment]
`zap_pre_shutdown` should be fine.

**Comment by YanFangJi** [comment]
Hi @thc202 @psiinon , I know I shouldn't ask unrelated question in this thread, but I have a question posted here never got answered https://groups.google.com/g/zaproxy-users/c/uQqU8m0CUWM/m/iBh6SoAZAwAJ. Is it the correct place to ask that kind of questions or should I open github issues? Thanks and sorry I really don't know how to get help on that question.

**Comment by psiinon** [comment]
@YanFangJi ooops - that was nearly a year ago :O
The User Group is the right place, but we are a small team and sometimes questions slip through the cracks. The best thing to do is to post to that thread saying that you still want to know 😁
