### ISSUE TITLE
Unexpected error about fuzzdb-release-9 and others appears diring ZAP 2.14 autoscan

### ISSUE THREAD

**Issue by JuraLys** [zaproxy/zaproxy#8256]
### Add-on repo

https://github.com/zaproxy/zap-extensions/

### Your contact details

zem.ljn@gmail.com

### Are you one of the authors?

- [ ] Yes

### Link for more information

https://prnt.sc/4s0IZmIhcv9N
https://prnt.sc/qGS61MGdn0du
https://prnt.sc/XwqqnDQ8yrPE
https://prnt.sc/7wbQHKV6cP_s
https://prnt.sc/D3Mm1fd87_TI

### Anything else we should know

Just installed ZAP 2.14 on Windows 10 x64 and started first auto scan

**Comment by thc202** [comment]
That's unrelated to the scans, that happens when validating the downloaded add-ons and it seems the hash didn't match (corrupt download is the most likely).
