### ISSUE TITLE
Sections' options might not be fully shown in Generate Report dialog

### ISSUE THREAD

**Issue by amitpanwar789** [zaproxy/zaproxy#8259]
### Describe the bug

I'm encountering a visual issue with the "Contents" checkbox located within the Template in the Generate Report panel. The padding around Contents checkbox appears to be broken, resulting in an inconsistent and potentially confusing appearance.

### Steps to reproduce the behavior

1. Go to Report menu and click on Generate report option.
2. Click on Template option
3. Now user can see the inconsistency of padding around contents checkbox

### Expected behavior

Padding around content checkbox must be consistent.

### Software versions

Zap version 2.14.0

### Screenshots

![Screenshot from 2023-12-20 16-52-16](https://github.com/zaproxy/zaproxy/assets/64302444/4911c63d-6436-4853-82c8-6dd511b75a6c)

### Would you like to help fix this issue?

- [X] Yes

**Comment by psiinon** [comment]
I had noticed that asd well 😉 
If you resize the dialog that fixes it .. but it would be really good to implement a proper fix.
@amitpanwar789 would you like us to assign this to you?

**Comment by amitpanwar789** [comment]
Sure, i will fix it.

**Comment by amitpanwar789** [comment]
I think we need to give minimum size to sectionsPane so that it will show Sufficient number of options.
```

    private JScrollPane getSectionsScrollPane() {
        if (sectionsPane == null) {
            sectionsPane = new JScrollPane();
            sectionsPane.setMinimumSize((DisplayUtils.getScaledDimension(400, 300))); //modified
        }
        return sectionsPane;
    }
```

**Comment by psiinon** [comment]
Try it and see? 😁 
For getting set up with ZAP development see https://www.zaproxy.org/docs/developer/

**Comment by amitpanwar789** [comment]
I tried it already, and it's working fine.

**Comment by psiinon** [comment]
Great!
Submit a PR?

**Comment by psiinon** [comment]
Dont forget to add a comment to the changelog: https://github.com/zaproxy/zap-extensions/blob/main/addOns/reports/CHANGELOG.md

**Comment by thc202** [comment]
Setting a minium size is a workaround.
