### ISSUE TITLE
Plan.yml not updating context on save

### ISSUE THREAD

**Issue by danbuntu** [zaproxy/zaproxy#8261]
### Describe the bug

After editing a context and selecting save/ save as in the automation pane the created plan.yml file doesn't always contain the updated context information. This seems to be a bit sporadic though and possibly a misundetaning on my part.

 

### Steps to reproduce the behavior

Open zap and select new session
Open the automation pane
Open an existing plan.yml
Run the job in order to get the context held in the yml file to display (this in it's self is very confusing)
Stop the job
Open the context
Add an exclusion
'Save as' the automation job - overwriting the existing yml file
Open the yml file in notepad and the added exclusion doesn't show in the excludePaths section

### Expected behavior

I would expect any changes made to the context to be saved in the automation plan yml when it's saved. This is assuming that the automation.yml should contain all the information needed to run the plan from the zap.sh cli

### Software versions

Support info:

ZAP
Version: 2.14.0

Installed Add-ons: [[id=alertFilters, version=19.0.0],
[id=ascanrules, version=59.0.0], [id=authhelper,
version=0.10.0], [id=automation, version=0.34.0],
[id=bruteforce, version=15.0.0], [id=callhome,
version=0.10.0], [id=commonlib, version=1.20.0],
[id=database, version=0.3.0], [id=diff, version=14.0.0],
[id=directorylistv1, version=7.0.0], [id=domxss,
version=18.0.0], [id=encoder, version=1.4.0], [id=exim,
version=0.8.0], [id=formhandler, version=6.5.0], [id=fuzz,
version=13.12.0], [id=gettingStarted, version=16.0.0],
[id=graaljs, version=0.5.0], [id=graphql, version=0.22.0],
[id=help, version=17.0.0], [id=hud, version=0.18.0],
[id=invoke, version=14.0.0], [id=network, version=0.13.0],
[id=oast, version=0.17.0], [id=onlineMenu, version=12.0.0],
[id=openapi, version=38.0.0], [id=postman, version=0.2.0],
[id=pscanrules, version=53.0.0], [id=quickstart,
version=43.0.0], [id=replacer, version=16.0.0], [id=reports,
version=0.27.0], [id=requester, version=7.4.0], [id=retest,
version=0.8.0], [id=retire, version=0.28.0], [id=reveal,
version=7.0.0], [id=scripts, version=44.0.0], [id=selenium,
version=15.16.0], [id=soap, version=21.0.0], [id=spider,
version=0.8.0], [id=spiderAjax, version=23.18.0], [id=tips,
version=12.0.0], [id=webdriverwindows, version=67.0.0],
[id=websocket, version=30.0.0], [id=zest, version=43.0.0]]

Operating System: Windows 11
Architecture: amd64
Java Version: Eclipse Adoptium 11.0.21
System's Locale: en_GB
Display Locale: en_GB
Format Locale: en_GB
Default Charset: windows-1252
ZAP Home Directory: C:\Users\daniel.attwood\ZAP\
ZAP Installation Directory: C:\Program Files\ZAP\Zed Attack Proxy\.\
Look and Feel: FlatLaf Light (com.formdev.flatlaf.FlatLightLaf)

### Would you like to help fix this issue?

- [ ] Yes

**Comment by psiinon** [comment]
"Open the context" - are you doing this in the ZAP Sites Tree or in the AF Environment?

**Comment by danbuntu** [comment]
Ok thats begining to make some sense. I'm actually working my way though through your videos and I've just come accross this bit the editing of the paths directly in the plan.

I think some the of the confusion on my part is that it does take the include and exclude paths from the context pane the first time you create the plan. It also takes the authentication information and puts it in the yml. Loading the automation plan will cause the context editor to appear in the tree ui when run. So the two do appear to be intrinsicly linked.

**Comment by psiinon** [comment]
Thats right.
You can create a plan using an existing context, and running a plan created a context.
But updating the context in the Sites Tree does _not_ change the plan.
You can however update the context in the plan.

I can see why this is confusing 😉

**Comment by psiinon** [comment]
So I think this is a misundersatanding rather than a bug - ok for us to close this @danbuntu ?

**Comment by danbuntu** [comment]
Yes very happy to close it. Thank you very much for your help.
