### ISSUE TITLE
ZAP unable to autoscan some specific sites which other similar tools can scan 

### ISSUE THREAD

**Issue by JuraLys** [zaproxy/zaproxy#8267]
### Is your feature request related to a problem? Please describe.

Try to autoscan specific site like dls.gov.ua, see screenshot
![image](https://github.com/zaproxy/zaproxy/assets/146434286/edc01ce4-92fe-4ac6-9199-8aedcc44ca67)

### Describe the solution you'd like

Implement ability to scan such sites

### Describe alternatives you've considered

I see no alternatives 

### Screenshots

![image](https://github.com/zaproxy/zaproxy/assets/146434286/d07dcc29-a153-47d6-b985-195c24400350)

### Would you like to help fix this issue?

- [X] Yes

**Comment by JuraLys** [comment]
see also similar issue with cip.gov.ua
![image](https://github.com/zaproxy/zaproxy/assets/146434286/59958df4-93c6-40fc-80c1-ab8f1c2ebb5c)

**Comment by JuraLys** [comment]
the same for http://navy.mil.gov.ua
![image](https://github.com/zaproxy/zaproxy/assets/146434286/f35d451d-256a-4c28-b352-66a10fdef516)

**Comment by thc202** [comment]
This does not seem to be a ZAP issue, seems you are being blocked (connected refused and the 403s). Maybe changing the user-agent might help but you should not be hammering live sites anyway.

**Comment by JuraLys** [comment]
Take example from Acunetix 
![acunetix-scan403](https://github.com/zaproxy/zaproxy/assets/146434286/eca6c6c8-c49b-4567-9f44-4feb506b4313)

**Comment by kingthorin** [comment]
I'm confused, its progress is also 0% and it noted the 403...

**Comment by JuraLys** [comment]
> I'm confused, its progress is also 0% and it noted the 403...

Acunetix found the way to complete scan. see attached report.
[acunetix-mfa.gov.ua-scan.pdf](https://github.com/zaproxy/zaproxy/files/13816365/acunetix-mfa.gov.ua-scan.pdf)

**Comment by thc202** [comment]
You can still scan the target, you just need to do it through the Spider/Active Scan tabs instead of relying on Quick Start, but you should understand that having connection problems and 403s is something you should address first, otherwise is pointless doing so.
