### ISSUE TITLE
Button Text is not fully shown in Add Note Dialog

### ISSUE THREAD

**Issue by amitpanwar789** [zaproxy/zaproxy#8275]
### Describe the bug

I'm encountering a visual issue with the Add Note Dialog window. The button text is not fully shown resulting in an inconsistent and potentially confusing appearance.

### Steps to reproduce the behavior

1. Right click on any request
2. Select Note options
3. Now user can see the inconsistency in button text.

### Expected behavior

Button text must be fully shown.

### Software versions

Zap version 2.14.0

### Screenshots

![Screenshot from 2023-12-28 15-06-51](https://github.com/zaproxy/zaproxy/assets/64302444/58dece6c-9378-49a4-ab5d-570dab9bf6c3)

### Would you like to help fix this issue?

- [X] Yes

**Comment by kingthorin** [comment]
That's just a work around again. In other languages it may not be enough..... I probably really needs a repaint or validate again like the other issue/PR.

**Comment by thc202** [comment]
In this specific case the fix is to remove all hardcoded sizes (no min, max, or preferred needed) and let the layout manager do its job. I will open a PR shortly revamping the layout of the dialog.
