### ISSUE TITLE
Use CSRF Token partial matching in scan rules

### ISSUE THREAD

**Issue by e-belair** [zaproxy/zaproxy#8280]
### Describe the bug

I have partial matching enabled and I still get warnings about Anti-CSRF token missing.
As you can see in the picture, the setting is enabled. Then in my form, I have the token "_csrf_token" in the element name.
Maybe I didn't understand the goal of this parameter, but I expected my token name to be detected as anti-CSRF token because in my app, all the token names are generated to be unique on the web page.

![image](https://github.com/zaproxy/zaproxy/assets/596562/53d88267-2314-4ca2-acaf-02e694d28184)
![image](https://github.com/zaproxy/zaproxy/assets/596562/a6fc0f48-4877-4671-bbaf-3a726f6b3fd0)

Note : I've created this issue following the recommendation on google group: https://groups.google.com/g/zaproxy-users/c/TuDKUcg9rR0/m/8ca3H6F7BAAJGoogle Group

### Steps to reproduce the behavior

1. Create a form containing a CSRF token input with a name containing _csrf_token such as foobar_csrf_token
2. Ensure partial matching in checked and you have a rule for _csrf_token
3. Scan the page containing the form
4. Enjoy the error

### Expected behavior

I expect the error to not occur. I mean, if my input name is foobar_csrf_token, zap should find it as it contains the partial name _csrf_token.

### Software versions

2.14.0

### Would you like to help fix this issue?

- [ ] Yes

**Comment by kingthorin** [comment]
It seems when partial matching was added to the core it wasn't accounted for in the scan rule(s).

- CsrfCountermeasuresScanRule.java (passive) seems to be using equalsIgnoreCase.
- CsrfTokenScanRule.java (active) doesn't use those settings/names at all.

**Comment by thc202** [comment]
It was not meant for the scan rules but the anti-csrf regeneration.

**Comment by kingthorin** [comment]
Hmmm the group thread really read like the scan rule. I'm happy to leave it open for both though 🤷‍♂️

**Comment by thc202** [comment]
I was referring to the (original) option.

**Comment by kingthorin** [comment]
Oh, I see what you're getting at.

**Comment by e-belair** [comment]
Ha ok, so if I correctly understood, the option is only used to make zap resend the token on the next requests?

**Comment by thc202** [comment]
It was used only in that functionality but I don't see a reason why it can be used more generally (I was just justifying why the scan rules were not using it).

**Comment by e-belair** [comment]
Ok I see. In my case, it would be great to have this feature. I have a lot of forms with generated csrf token names. I could mark the test as false positive, but it would not be a great idea IMO.
