### ISSUE TITLE
ZAP API Python - Users component: get_user_by_id only returns the user's credentials

### ISSUE THREAD

**Issue by grepmam** [zaproxy/zaproxy#8282]
### Describe the bug

As the name of the bug reads, when using the **get_user_by_id** method, it does not return the complete **user information**, only the **user's credentials information** (sessionName and type). This is because the **next method** of **module six** is taking the **first element** of the response iterator.

### Steps to reproduce the behavior

1. Create ZAP instance.
2. Create context.
3. Create user for the context.
4. Use zap.users.get_user_by_id(context_id, user_id).

### Expected behavior

It is expected to return the following:
```json
{
  "credentials": "{ \"sessionName\": \"<sessionName>\", \"type\": \"<type>\"}",
  "name": "<user>",
  "contextId": "<context_id>",
  "id": "<user_id>",
  "enabled": "<state>"
}
```

### Software versions

ZAP
Versión: 2.14.0

### Would you like to help fix this issue?

- [ ] Yes

**Comment by psiinon** [comment]
This looks like a python client issue (which is still our code;).
ZAP should be returning the full set of data: https://github.com/zaproxy/zaproxy/blob/v2.14.0/zap/src/main/java/org/zaproxy/zap/extension/users/UsersAPI.java#L434

**Comment by psiinon** [comment]
I guess this is the relevant line?
https://github.com/zaproxy/zap-api-python/blob/0.2.0/src/zapv2/users.py#L43
Note that it is generated code, which could make the fix a bit more tricky..

**Comment by thc202** [comment]
The problem is that the API client implementation expects the response to be wrapped in an object, that happens for most of the responses but not this one… I guess we'll have to add something to the generator to handle this case differently (or change the response but that will break user's scripts).

**Comment by thc202** [comment]
Which scripts specifically?

**Comment by grepmam** [comment]
I don't know, I say the latter because of what he said in his last comment. I assume you are referring to the user scripts that use this component or am I wrong? Sorry if I caused confusion.

**Comment by grepmam** [comment]
Hello! Any news on this problem? Is it being treated?

Thanks in advance.

**Comment by kingthorin** [comment]
Not actively.

**Comment by grepmam** [comment]
Thank you all very much for fixing it!
