### ISSUE TITLE
ZAP unable to resolve specific URL by unknown reason

### ISSUE THREAD

**Issue by JuraLys** [zaproxy/zaproxy#8288]
### Describe the bug

Run ZAP and try to autoscan tax.gov.ua URL
See attached screenshots

### Steps to reproduce the behavior

Run ZAP and try to autoscan tax.gov.ua URL
See attached screenshots

### Expected behavior

ZAP should perform autoscanning for tax.gov.ua URL

### Software versions

ZAP Version: 2.14.0

Installed Add-ons: [[id=alertFilters, version=19.0.0],
[id=ascanrulesBeta, version=48.0.0], [id=authhelper,
version=0.10.0], [id=automation, version=0.34.0],
[id=bruteforce, version=15.0.0], [id=callhome,
version=0.10.0], [id=commonlib, version=1.18.0],
[id=coreLang, version=15.0.0], [id=custompayloads,
version=0.13.0], [id=database, version=0.3.0], [id=diff,
version=14.0.0], [id=directorylistv1, version=7.0.0],
[id=directorylistv2_3, version=4.0.0],
[id=directorylistv2_3_lc, version=4.0.0], [id=domxss,
version=18.0.0], [id=encoder, version=1.4.0],
[id=formhandler, version=6.5.0], [id=fuzz, version=13.12.0],
[id=fuzzdboffensive, version=4.0.0], [id=gettingStarted,
version=16.0.0], [id=graaljs, version=0.5.0], [id=graphql,
version=0.21.0], [id=help, version=17.0.0], [id=hud,
version=0.18.0], [id=invoke, version=14.0.0], [id=network,
version=0.12.0], [id=oast, version=0.17.0], [id=onlineMenu,
version=12.0.0], [id=openapi, version=38.0.0], [id=portscan,
version=10.0.0], [id=postman, version=0.2.0],
[id=pscanrules, version=53.0.0], [id=pscanrulesBeta,
version=35.0.0], [id=quickstart, version=43.0.0],
[id=replacer, version=16.0.0], [id=reports, version=0.26.0],
[id=requester, version=7.4.0], [id=retest, version=0.8.0],
[id=retire, version=0.26.0], [id=reveal, version=7.0.0],
[id=scripts, version=44.0.0], [id=selenium,
version=15.15.0], [id=soap, version=20.0.0], [id=spider,
version=0.7.0], [id=spiderAjax, version=23.18.0],
[id=sqliplugin, version=15.0.0], [id=svndigger,
version=4.0.0], [id=tips, version=12.0.0], [id=tokengen,
version=15.0.0], [id=wappalyzer, version=21.28.0],
[id=webdriverwindows, version=67.0.0], [id=websocket,
version=30.0.0], [id=zest, version=42.0.0]]

Operating System: Windows 10
Architecture: amd64
Java Version: Eclipse Adoptium 21.0.1
System's Locale: uk_UA
Display Locale: en_GB
Format Locale: uk_UA
Default Charset: UTF-8
ZAP Home Directory: C:\Users\Admin\ZAP\
ZAP Installation Directory: C:\Program Files\ZAP\Zed Attack Proxy\.\
Look and Feel: FlatLaf Light (com.formdev.flatlaf.FlatLightLaf)

### Screenshots

![tax gov ua-url(](https://github.com/zaproxy/zaproxy/assets/146434286/8e6cfbd6-67f2-46f7-aff5-a9dfdd09b83f)
![tax gov ua-site](https://github.com/zaproxy/zaproxy/assets/146434286/6c324bd7-0520-4415-bbc5-b0e989e74080)

### Would you like to help fix this issue?

- [X] Yes

**Comment by kingthorin** [comment]
Check your URL. It seems you have to use HTTPS.

**Comment by JuraLys** [comment]
> Check your URL. It seems you have to use HTTPS.

ZAP must resolve such hosts in any case

**Comment by kingthorin** [comment]
The message is just misleading. Https works fine, http fails.

I agree it should be tweaked but I was trying to get you working/progressing 😉

**Comment by thc202** [comment]
What's the expectation here, DNS queries fail sometimes.

**Comment by JuraLys** [comment]
> What's the expectation here, DNS queries fail sometimes.

Why It is normal for you?

**Comment by psiinon** [comment]
The User Group is the right place for these sort of questions: https://groups.google.com/group/zaproxy-users
If it turns out theres a bug in ZAP then an issue will be appropriate.

**Comment by JuraLys** [comment]
> The User Group is the right place for these sort of questions: https://groups.google.com/group/zaproxy-users If it turns out theres a bug in ZAP then an issue will be appropriate.

Why my report is not enough?(

**Comment by thc202** [comment]
What do you expect ZAP to do in this case?

**Comment by JuraLys** [comment]
> What do you expect ZAP to do in this case? (Yes, I read the expectation added in the issue but if ZAP is not able to resolve the address it will not able to scan it.)

it's very easy to fix in code: if http is not resolved then try https
