### ISSUE TITLE
JRE 11

### ISSUE THREAD

**Issue by slossy88** [zaproxy/zaproxy#8289]
### Is your feature request related to a problem? Please describe.

I am unable to download JRE 11 from Java's website... they only support download of version 8. Java has stated that if an app uses other versions that they should be bundled with the app. Can we get a bundle, or am I able to use JDK 11 instead of JRE 11?

### Describe the solution you'd like

bundle

### Describe alternatives you've considered

installing JDK, ot switching to version 8

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment]
You can use a JDK, but you can also download a JRE from other providers, e.g. https://adoptium.net/temurin/releases/

Questions are better asked in the User Group: https://groups.google.com/group/zaproxy-users
