### ISSUE TITLE
ZAP crashed by unknown reason when autoscaning specific site

### ISSUE THREAD

**Issue by JuraLys** [zaproxy/zaproxy#8292]
### Describe the bug

ZAP crashed by unknown reason when autoscaning specific site tax.gov.ua. see attached logs

### Steps to reproduce the behavior

Run ZAP and start autoscan tax.gov.ua URL
ZAP crashed after several hours.

### Expected behavior

ZAP should not crash

### Software versions

ZAP Version: 2.14.0

Installed Add-ons: [[id=alertFilters, version=19.0.0],
[id=ascanrulesBeta, version=48.0.0], [id=authhelper,
version=0.10.0], [id=automation, version=0.34.0],
[id=bruteforce, version=15.0.0], [id=callhome,
version=0.10.0], [id=commonlib, version=1.18.0],
[id=coreLang, version=15.0.0], [id=custompayloads,
version=0.13.0], [id=database, version=0.3.0], [id=diff,
version=14.0.0], [id=directorylistv1, version=7.0.0],
[id=directorylistv2_3, version=4.0.0],
[id=directorylistv2_3_lc, version=4.0.0], [id=domxss,
version=18.0.0], [id=encoder, version=1.4.0],
[id=formhandler, version=6.5.0], [id=fuzz, version=13.12.0],
[id=fuzzdboffensive, version=4.0.0], [id=gettingStarted,
version=16.0.0], [id=graaljs, version=0.5.0], [id=graphql,
version=0.21.0], [id=help, version=17.0.0], [id=hud,
version=0.18.0], [id=invoke, version=14.0.0], [id=network,
version=0.12.0], [id=oast, version=0.17.0], [id=onlineMenu,
version=12.0.0], [id=openapi, version=38.0.0], [id=portscan,
version=10.0.0], [id=postman, version=0.2.0],
[id=pscanrules, version=53.0.0], [id=pscanrulesBeta,
version=35.0.0], [id=quickstart, version=43.0.0],
[id=replacer, version=16.0.0], [id=reports, version=0.26.0],
[id=requester, version=7.4.0], [id=retest, version=0.8.0],
[id=retire, version=0.26.0], [id=reveal, version=7.0.0],
[id=scripts, version=44.0.0], [id=selenium,
version=15.15.0], [id=soap, version=20.0.0], [id=spider,
version=0.7.0], [id=spiderAjax, version=23.18.0],
[id=sqliplugin, version=15.0.0], [id=svndigger,
version=4.0.0], [id=tips, version=12.0.0], [id=tokengen,
version=15.0.0], [id=wappalyzer, version=21.28.0],
[id=webdriverwindows, version=67.0.0], [id=websocket,
version=30.0.0], [id=zest, version=42.0.0]]

Operating System: Windows 10
Architecture: amd64
Java Version: Eclipse Adoptium 21.0.1
System's Locale: uk_UA
Display Locale: en_GB
Format Locale: uk_UA
Default Charset: UTF-8
ZAP Home Directory: C:\Users\Admin\ZAP\
ZAP Installation Directory: C:\Program Files\ZAP\Zed Attack Proxy\.\
Look and Feel: FlatLaf Light (com.formdev.flatlaf.FlatLightLaf)

### Errors from the zap.log file

[zap-crash.log](https://github.com/zaproxy/zaproxy/files/13884465/zap-crash.log)
[untitled8-crash.log](https://github.com/zaproxy/zaproxy/files/13884467/untitled8-crash.log)

### Would you like to help fix this issue?

- [X] Yes

**Comment by psiinon** [comment]
Are there no other zap.log files?

**Comment by psiinon** [comment]
And can you provide any more details about the crash - what actually happened? Were there any errors shown?
I cant see anything relevant in those logs :/

**Comment by psiinon** [comment]
Thats going to be hard to diagnose ☹️ 
Could something else have killed it?
Any evidence of a Java core dump?

**Comment by JuraLys** [comment]
second time gui crash when scanned other site, see
[zap-gui-crash2.txt](https://github.com/zaproxy/zaproxy/files/13889427/zap-gui-crash2.txt)

**Comment by kingthorin** [comment]
`java.lang.OutOfMemoryError`

**Comment by thc202** [comment]
Merging into #8255, once in OOME realm anything bad can happen.

**Comment by JuraLys** [comment]
one more crash, see trace
[zap-gui-crash3.txt](https://github.com/zaproxy/zaproxy/files/13931196/zap-gui-crash3.txt)

**Comment by psiinon** [comment]
`Exception: java.lang.OutOfMemoryError` once more...

**Comment by JuraLys** [comment]
ZAP hanged when autoscaning, see 
[ZAP-gui-hang-during-scan.txt](https://github.com/zaproxy/zaproxy/files/14024298/ZAP-gui-hang-during-scan.txt)
