### ISSUE TITLE
Update fuzzdb-offensive add-on to make it clear it may trigger anti-virus tools

### ISSUE THREAD

**Issue by JuraLys** [zaproxy/zaproxy#8297]
### Is your feature request related to a problem? Please describe.

see attached screenshot

### Describe the solution you'd like

Just run ZAP

### Describe alternatives you've considered

-

### Screenshots

![zap-virus(](https://github.com/zaproxy/zaproxy/assets/146434286/1b7fc8ad-652e-4c63-b2bb-0e89cf6c5fd5)

### Would you like to help fix this issue?

- [X] Yes

**Comment by psiinon** [comment]
That is a question not a feature request.
Please ask questions on the ZAP User Group: https://groups.google.com/group/zaproxy-users

**Comment by psiinon** [comment]
Just noticed that its the web-backdoors add-on.
This add-on was explicitly created to contain the fuzz-db files which anti-virus tools often flag up.
So renaming and re-openning, as we should make this more explicit.
It would still have been better as a question on the User Group 😛

**Comment by psiinon** [comment]
We note it on https://www.zaproxy.org/docs/desktop/addons/fuzzdb-files/ but not on 
https://www.zaproxy.org/docs/desktop/addons/fuzzdb-offensive/

**Comment by psiinon** [comment]
Hopefully this is clearer: https://www.zaproxy.org/docs/desktop/addons/fuzzdb-offensive/
