### ISSUE TITLE
Missing Implementation: deleteLeaf and deleteSubtree Methods

### ISSUE THREAD

**Issue by gitgoap** [zaproxy/zaproxy#8301]
### Describe the bug

The current implementation of the `SqlTableStructure` class in the Zed Attack Proxy (ZAP) codebase is missing the implementations for the `deleteLeaf` and `deleteSubtree` methods. These methods are marked as "TODO" in the code, indicating that their logic has not been implemented yet.

## Proposed Solution
Provide the necessary logic to implement the `deleteLeaf` and `deleteSubtree` methods, ensuring they perform the required deletion operations based on the provided session and structure IDs.

### Steps to reproduce the behavior

N/A

### Expected behavior

The `deleteLeaf` and `deleteSubtree` methods should be implemented to allow proper deletion of records from the database, in accordance with the intended functionality.

### Software versions

<kbd>ZAP 2.14.0</kbd>

### Screenshots

![Screenshot 2024-01-11 220331](https://github.com/zaproxy/zaproxy/assets/117789470/13c52bdc-4fa5-41f3-bc2c-b7a0604f94b3)

## Impact
The absence of these methods may affect the intended functionality of the application, as the ability to delete a leaf or subtree from the database is crucial for managing the data structure.

### Would you like to help fix this issue?

- [X] Yes

**Comment by thc202** [comment]
This is not a bug. Given the methods are not used implementing them would not make any difference.

**Comment by gitgoap** [comment]
@thc202 That's correct, it isn't a bug. I didn't had any option to improve the label when I listed this issue and by default 'bug' label was marked.

**Comment by kingthorin** [comment]
Given the age of the TODO notes the methods don't seem necessary.
