### ISSUE TITLE
PII Disclosure false positive in GUIDs and similar hexadecimal strings.

### ISSUE THREAD

**Issue by sarahelsaig** [zaproxy/zaproxy#8303]
### Describe the bug

We use GUIDs in our ASP.NET Core site as random unique IDs. This inconsistently trips the PII Disclosure alert. See the screenshot below. This happens whenever there is a long enough purely numeric sequence inside the hexadecimal string.

### Steps to reproduce the behavior

1. Have a cshtml page where a variable like `var carouselId = $"carousel-{Guid.NewGuid():N}";` is displayed. (The `N` format refers to GUIDs without separating dashes, so it's just a long hex string. We already use this format extensively, so changing it is not really viable.)
2. Run the scan a few times. The site in question had several such strings, it triggered on most scans, but it's not a given.

### Expected behavior

If the suspected PII is a substring of a larger hexadecimal string (could be matched with a regex like `\b[0-9a-fA-F]*[a-fA-F][0-9a-fA-F]*\b`) then it shouldn't be identified as a number.

### Software versions

We use the docker image `softwaresecurityproject/zap-stable:2.14.0`.

### Screenshots

![image](https://github.com/zaproxy/zaproxy/assets/4007293/1deb9142-bfa9-4f5c-bc36-07f7cb360ea4)

### Would you like to help fix this issue?

- [ ] Yes

**Comment by kingthorin** [comment]
Unfortunately as your example perfectly illustrates fully numeric hex numbers are exactly the same as credit card numbers, or any appropriate length numeric string. How to you propose we differentiate?

**Comment by kingthorin** [comment]
Also all the PII matches use word boundaries so that numeric string likely appears more than once in the related response. ZAP's matching (in the UI) is based on first match.

https://github.com/zaproxy/zap-extensions/blob/main/addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/PiiScanRule.java

**Comment by psiinon** [comment]
I was going to say we should ignore numbers in much larger number, but it appears we already do :/
@sarahelsaig can you confirm that those string appear in other places in the response with word boundries (ie not part of larger numbers)?
For ways to handle false positives where we cant fix the code see https://www.zaproxy.org/faq/how-do-i-handle-a-false-positive/
