### ISSUE TITLE
zap-api-scan.py allow to use a URL when overriding hostname (`-O`)

### ISSUE THREAD

**Issue by cerrussell** [zaproxy/zaproxy#8312]
### Describe the bug

[Current logic in zap-api-scan.py](https://github.com/zaproxy/zaproxy/blob/b2aed8b5005495af6177a1ad92645d30d126f811/docker/zap-api-scan.py#L421) uses [urllib.parse.urljoin](https://docs.python.org/3/library/urllib.parse.html) to produce a server url when the -O (host override) option is used. This creates an issue when the target is also a URL and its scheme differs from that of the override host.

### Steps to reproduce the behavior

The issue can easily be demonstrated:

```python
from urllib.parse import urljoin
target_url = 'https://website.com/openapi.json'
host_override = 'http://127.0.0.1:3000'
target = urljoin(target_url, '//' + host_override)
print(target)
``` 

expected result: http://127.0.0.1:3000
actual result: https://http://127.0.0.1:3000

If the host override is given as just '127.0.0.1:3000', that results in a syntactically correct URL of `https://127.0.0.1:3000' that is still not actually correct.

### Expected behavior

I expect valid URL input to stay valid and for the scheme of the override host to be respected. Something like the following would work.

```python
if host_override and urlparse(host_override).scheme:
    target = host_override
elif host_override:
    target = urljoin(target_url, '//' + host_override)
```   

instead of the current:
```python
if host_override:
    target = urljoin(target_url, '//' + host_override)
``` 

### Software versions

I am using the zap nightly docker image which I pulled today.

<details><summary>Image details</summary>
<p>

  "Id" : "sha256:916f71db4468fb060f44918ec194dd8eb58b539b1e3aec4f354118a3e4c50502",
  "RepoTags" : [ "ghcr.io/zaproxy/zaproxy:nightly" ],
  "RepoDigests" : [ "ghcr.io/zaproxy/zaproxy@sha256:c1175078d375070d992f0c248e9075f00c0e6601a545d8a70e0862f8f881301e" 

</p>
</details> 

### Screenshots

![image](https://github.com/zaproxy/zaproxy/assets/80227828/a2b07125-a9eb-4835-9211-c6f6cbe9c691)

### Would you like to help fix this issue?

- [X] Yes

**Comment by kingthorin** [comment]
Hmm it is supposed to be just host override (specifically) however it is reasonable to expect it to function as you did (IMHO).

**Comment by thc202** [comment]
The help does say that it's expected a hostname not a URL (`the hostname to override in the (remote) OpenAPI spec`).

**Comment by thc202** [comment]
Feel free to open a PR changing the behaviour.
