### ISSUE TITLE
Webpages distinguished by URL fragment (site.com/#/abc) are neither visible nor recorded by ZAP

### ISSUE THREAD

**Issue by techboy-coder** [zaproxy/zaproxy#8316]
### Describe the bug

I've been trying out ZAP on [OWASP Juice Web App](https://owasp.org/www-project-juice-shop/). Both the normal and ajax crawler don't seem to be able to pickup on urls like: `http://localhost:3000/#/complain`, `http://localhost:3000/#/chatbot`, `http://localhost:3000/#/score-board`, etc...

In the settings for the _spiders_ I've set **query parameter handling** to `consider both parameter name and value`. Fragments here seem to get ignored(?).

I came across [this](https://groups.google.com/g/zaproxy-users/c/Oewloo_0F8Y) discussion suggesting to: 1) Remove `localhost` and `127.0.0.1` from the "No proxy for" box and 2) set `network.proxy.allow_hijacking_localhost` to `true` in `about:config` which I both did. Whenever visiting any of the urls like: `http://localhost:3000/#/name` I get url=`http://localhost:3000/` code=`304/Not modified` in the _history_ tab of ZAP.

Am I missing out on something here or is this the intended way how ZAP is supposed to work?

### Steps to reproduce the behavior

1. Run OWASP Juice Web App
2. Try to use Ajax (and normal) spidering
3. Check Sitetree and/or search for pages like  `http://localhost:3000/#/complain`, `http://localhost:3000/#/chatbot`, `http://localhost:3000/#/score-board`... which are clearly visible (Inspect elements on browser)

### Expected behavior

I expected that these urls would be picked up on (either through allowing them through a config/settings option) or checking the ajax rendered webpage hash (or similar identifier) and then to see them in the Sitetree.

### Software versions

ZAP
Version: 2.14.0

Installed Add-ons: [[id=alertFilters, version=18.0.0],
[id=ascanrules, version=58.0.0], [id=authhelper,
version=0.10.0], [id=automation, version=0.33.0],
[id=bruteforce, version=15.0.0], [id=callhome,
version=0.8.0], [id=commonlib, version=1.18.0],
[id=database, version=0.3.0], [id=diff, version=14.0.0],
[id=directorylistv1, version=7.0.0], [id=domxss,
version=18.0.0], [id=encoder, version=1.4.0], [id=exim,
version=0.7.0], [id=formhandler, version=6.5.0], [id=fuzz,
version=13.12.0], [id=gettingStarted, version=16.0.0],
[id=graaljs, version=0.5.0], [id=graphql, version=0.20.0],
[id=help, version=17.0.0], [id=hud, version=0.18.0],
[id=invoke, version=14.0.0], [id=network, version=0.12.0],
[id=oast, version=0.17.0], [id=onlineMenu, version=12.0.0],
[id=openapi, version=37.0.0], [id=postman, version=0.2.0],
[id=pscanrules, version=52.0.0], [id=quickstart,
version=43.0.0], [id=replacer, version=15.0.0], [id=reports,
version=0.26.0], [id=requester, version=7.4.0], [id=retest,
version=0.8.0], [id=retire, version=0.26.0], [id=reveal,
version=7.0.0], [id=scripts, version=42.0.0], [id=selenium,
version=15.15.0], [id=soap, version=20.0.0], [id=spider,
version=0.7.0], [id=spiderAjax, version=23.17.0], [id=tips,
version=12.0.0], [id=webdriverlinux, version=64.0.0],
[id=websocket, version=30.0.0], [id=zest, version=42.0.0]]

Operating System: Linux
Architecture: amd64
Java Version: N/A 21
System's Locale: en_US
Display Locale: en_GB
Format Locale: en_US
Default Charset: UTF-8
ZAP Home Directory: /home/tbc/.ZAP/
ZAP Installation Directory: /usr/share/zaproxy/./
Look and Feel: FlatLaf Light (com.formdev.flatlaf.FlatLightLaf)

### Screenshots

![image](https://github.com/zaproxy/zaproxy/assets/71926891/3ee7ce46-f830-4f9c-a3c5-78779287e4e9)

### Would you like to help fix this issue?

- [x] Yes

**Comment by psiinon** [comment]
Fragments are not sent from the browser to the server, so thats why ZAP hasnt seen them in that past.
However the add-on does add support for them: https://www.zaproxy.org/docs/desktop/addons/client-side-integration/
If you'd like more info on it please ask on the User Group: https://groups.google.com/group/zaproxy-users
