### ISSUE TITLE
Can ZAP docker scan multiple IPs and Ports?

### ISSUE THREAD

**Issue by IGNFIfortrue** [zaproxy/zaproxy#8322]
### Is your feature request related to a problem? Please describe.

 sudo docker run -v /app/zap/wrk:/zap/wrk -t softwaresecurityproject/zap-stable zap-full-scan.py -I -t http://127.0.0.1:80 -J report.json -r report.html

Recently I plan to integrate ZAP into my CICD pipeline, but I found if I have multiple targets, we have some services using different IP and ports, then I have no choice to scan multiple targets in one round,

may I ask if you have such funtions? if yes could you help me with this?
thanks a lot

### Describe the solution you'd like

run a command mentioned above to scan multiple targets in one round,

### Describe alternatives you've considered

other ways to use ZAP to scan multiple targets

### Would you like to help fix this issue?

- [ ] Yes

**Comment by kingthorin** [comment]
Please don't ask questions as issues - the [ZAP User Group]( https://groups.google.com/group/zaproxy-users) is a much better place for questions.
