### ISSUE TITLE
owasp/zap2docker-stable:2.14.0 - No manifest file causing build error on Jenkins

### ISSUE THREAD

**Issue by deepamalik18** [zaproxy/zaproxy#8329]
Docker image used(owasp/zap2docker-stable:latest) 
 latest: Pulling from owasp/zap2docker-stable
Getting Error "  mediaType in manifest should be 'application/vnd.docker.distribution.manifest.v2+json' not 'application/vnd.oci.image.manifest.v1+json'" while building build on Jenkins

**Comment by thc202** [comment]
Pulls just fine here, which version of Docker are you using?

**Comment by deepamalik18** [comment]
Previously we were using 2.11.1 and Jenkins builds were smooth. Something changed from past 2-3 days we are getting error " manifest unknown". So we updated to latest, 2.14.0 but no luck. 
docker manifest inspect --verbose owasp/zap2docker-stable:latest
**no such manifest: docker.io/owasp/zap2docker-stable:latest**

docker manifest inspect --verbose owasp/zap2docker-stable:latest
no such manifest: docker.io/owasp/zap2docker-stable:latest

**Comment by deepamalik18** [comment]
Local docker version is Docker version 20.10.21, build baeda1f

**Comment by thc202** [comment]
Using `Docker version 25.0.2, build 29cf629` here. Given the age of 20.10.21 I'd say it does not support the media type being used by the newer images.

**Comment by deepamalik18** [comment]
I did upgraded my docker version to 25.0.1 and was trying to inspect manifest file.

docker manifest inspect  owasp/zap2docker-stable:2.14.0 
It has following "mediaType": "application/vnd.oci.image.index.v1+json",

Are there any images with manifest.v2+json ?

**Comment by thc202** [comment]
Probably not, but isn't it working with the newer Docker version?

**Comment by thc202** [comment]
Bump.
