### ISSUE TITLE
Allow for modern and plus type of reports

### ISSUE THREAD

**Issue by ocenteno** [zaproxy/zaproxy#8338]
### Is your feature request related to a problem? Please describe.

Having hardcoded types of reports is quite inflexible.
On top of it, I could figure out how it works for the baseline scan, but api and full are a bit more cryptic in the way they use report templates.

### Describe the solution you'd like

It would be great to be able to parameterise the template we want to use instead of defaulting everything to the traditional.

### Describe alternatives you've considered

-template modern
-template plus
-template traditional

### Would you like to help fix this issue?

- [X] Yes

**Comment by psiinon** [comment]
Are you talking about the packaged scans or something else?
If its something else then I'm not sure I follow you...

**Comment by kingthorin** [comment]
For my two cents: If you want more flexibility use an automation mechanism that's built for more flexibility like the API or automation framework.

**Comment by psiinon** [comment]
> For my two cents: If you want more flexibility use an automation mechanism that's built for more flexibility like the API or automation framework.

That is the workaround, and tbh the recommended approach.

**Comment by ocenteno** [comment]
I'm talking about the reports, they are only generated with the traditional templates

**Comment by ocenteno** [comment]
I'm using the Docker image for automation, it is very convenient.
What I lack is details about the passed tests in the reports.
I found that such information is only displayed in the traditional-html-plus and modern report templates, but the templates are hardcoded when we ask for -r my_report.html.
Thus, I'd like a way to decide what template to use.

All these templates are already stored in the reports.zap library within the Docker image.

**Comment by psiinon** [comment]
Understood.
But note that the Automation Framework does already support all of the report types and can be used in the Docker images.

**Comment by psiinon** [comment]
Just discussed this in irc.

This can be achieved in docker using either:

- [Automation Framework](https://www.zaproxy.org/docs/automate/automation-framework/) (the recommended option)
- [Scan Hooks](https://www.zaproxy.org/docs/docker/scan-hooks/)

The packaged scans already have lots of command line options and we do not want to add to them.

**Comment by ocenteno** [comment]
Thanks @psiinon ,

If I understand correctly it means creating my custom yaml instead of using the auto generated by each of the pre-packaged scans, right?

is there any templating or tool I can use to generate it?

**Comment by psiinon** [comment]
See https://www.zaproxy.org/docs/automate/automation-framework/ - lots of v specific videos linked off there too 😁 
You can create and test an AF plan in ZAP before exporting it to use on the command line, and that is indead the recommended approach.
