### ISSUE TITLE
Provided Browser Not Found

### ISSUE THREAD

**Issue by Praneshsha-2024** [zaproxy/zaproxy#8340]
### Describe the bug

i have installed 2.14 Version, my chrome Browser Version is 121.0.167 , but the ZAP home Webdriver is installing with webdriver 118 version , 
so when i do quick launch , Manual Explore am getting Provided Browser not found error. 

is there a limitation for ZAP that i cant use more than 118 driver version- please advice. 

### Steps to reproduce the behavior

i have installed 2.14 Version, my chrome Browser Version is 121.0.167 , but the ZAP home Webdriver is installing with webdriver 118 version , 
so when i do quick launch , Manual Explore am getting Provided Browser not found error. 

is there a limitation for ZAP that i cant use more than 118 driver version- please advice. 

### Expected behavior

Browser should open with the provided URL and start scanning

### Software versions

2.14 Version of ZAP . 
Chrome browser is 121.0.XXXX

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment]
Ensure you update the WebDriver add-on to latest version (which does support Chrome 121, e.g. https://github.com/zaproxy/zap-extensions/releases/tag/webdriverwindows-v70).

**Comment by Praneshsha-2024** [comment]
I have matched with latest chromedriver on Zap/Webdriver Folder , now first thing is browser is opening , but when i do manual explore there is no scan/ request / response records. 

ZAP is not doing passive scanning, pls suggest

**Comment by Praneshsha-2024** [comment]
@thc202 , can you please suggest pls

**Comment by kingthorin** [comment]
Please don't ask questions as issues - the [ZAP User Group]( https://groups.google.com/group/zaproxy-users) is a much better place for questions.
