### ISSUE TITLE
Manual Explore - Passive Scanning - NOt capturing any actions/ Request / Response

### ISSUE THREAD

**Issue by Praneshsha-2024** [zaproxy/zaproxy#8341]
### Describe the bug

Manual Explore - i could open the URL and doing login actions, but there was no request/ Response stored in machine. 

### Steps to reproduce the behavior

Launch ZAP -- Manual Explore - provide this URL https://mozart-forms.iso.com
now select Chrome browser and launch browser . 
Browser opens , am able to pass ID and Passowrd and navigate inside the application, 
but there is no request / Response stored , ZAP is clean as like it started . 

### Expected behavior

I need to do passive scanning . 

### Software versions

ZAP 2.14.0

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment]
Please, use the user group for usage questions.
