### ISSUE TITLE
Graal Engine Issue with Multi Threaded Access on Active Scanner

### ISSUE THREAD

**Issue by 5ubterranean** [zaproxy/zaproxy#8348]
### Describe the bug

When using a custom written active rule script, after a short while it gets disabled giving the error about multi threaded access not allowed for js.

### Steps to reproduce the behavior

1. Add the attached script to the active rules scripts (set ECMAScript: Graal.js as engine)
[off by slash.txt](https://github.com/zaproxy/zaproxy/files/14348920/off.by.slash.txt)
2. Launch an Active Scan on a site already visited with ZAP (the tests were made having all the installed active rules disabled and scripts but the one attached)
3. After a short while the script will get disabled and the next output will show on the script console
```
org.graalvm.polyglot.PolyglotException: Multi threaded access requested by thread Thread[ZAP-ActiveScanner-0,3,main] but is not allowed for language(s) js.org.graalvm.polyglot.PolyglotException: Multi threaded access requested by thread Thread[ZAP-ActiveScanner-0,3,main] but is not allowed for language(s) js.
```

### Expected behavior

It's known that Graal.js can't run multi threaded like it was already asked on https://github.com/zaproxy/zaproxy/issues/6992 and later fixed on https://github.com/zaproxy/zap-extensions/pull/4009
So this error shouldn't happen anymore, unless there is a configuration that has to be made in order to avoid trying to execute Graal.js multi threaded.

### Software versions

ZAP
Version: 2.14.0

Installed Add-ons: [[id=accessControl, version=9.0.0],
[id=alertFilters, version=19.0.0], [id=allinonenotes,
version=2.0.0], [id=ascanrules, version=63.0.0],
[id=attacksurfacedetector, version=1.1.4], [id=authhelper,
version=0.12.0], [id=automation, version=0.35.0],
[id=bruteforce, version=15.0.0], [id=callgraph,
version=5.0.0], [id=callhome, version=0.10.0],
[id=commonlib, version=1.22.0], [id=communityScripts,
version=18.0.0], [id=custompayloads, version=0.13.0],
[id=database, version=0.3.0], [id=diff, version=14.0.0],
[id=directorylistv1, version=7.0.0], [id=domxss,
version=18.0.0], [id=encoder, version=1.4.0], [id=exim,
version=0.8.0], [id=fileupload, version=1.2.1],
[id=formhandler, version=6.5.0], [id=fuzz, version=13.12.0],
[id=gettingStarted, version=16.0.0], [id=graaljs,
version=0.5.0], [id=graphql, version=0.22.0], [id=help,
version=17.0.0], [id=highlighter, version=8.0.0], [id=hud,
version=0.18.0], [id=imagelocationscanner, version=4.0.0],
[id=invoke, version=14.0.0], [id=jruby, version=8.0.0],
[id=jsonview, version=3.0.0], [id=jwt, version=1.0.3],
[id=jython, version=14.0.0], [id=maplocal, version=0.0.1],
[id=neonmarker, version=1.6.0], [id=network,
version=0.13.0], [id=oast, version=0.17.0], [id=onlineMenu,
version=12.0.0], [id=openapi, version=39.0.0],
[id=paramdigger, version=0.2.0], [id=postman,
version=0.2.0], [id=pscanrules, version=56.0.0],
[id=pscanrulesAlpha, version=42.0.0], [id=pscanrulesBeta,
version=37.0.0], [id=quickstart, version=43.0.0],
[id=reflect, version=0.0.11], [id=replacer, version=16.0.0],
[id=reports, version=0.29.0], [id=requester, version=7.4.0],
[id=retest, version=0.8.0], [id=retire, version=0.31.0],
[id=reveal, version=7.0.0], [id=revisit, version=5.0.0],
[id=scripts, version=45.0.0], [id=selenium,
version=15.18.0], [id=soap, version=21.0.0], [id=spider,
version=0.10.0], [id=spiderAjax, version=23.18.0],
[id=sqliplugin, version=15.0.0], [id=tips, version=12.0.0],
[id=tokengen, version=15.0.0], [id=treetools,
version=8.0.0], [id=wappalyzer, version=21.31.0],
[id=webdriverlinux, version=70.0.0], [id=websocket,
version=30.0.0], [id=zest, version=43.0.0]]

Operating System: Linux
Architecture: amd64
Java Version: Debian 17.0.7
System's Locale: en_US
Display Locale: en_GB
Format Locale: en_US
Default Charset: UTF-8
Look and Feel: FlatLaf Dark (com.formdev.flatlaf.FlatDarkLaf)

### Additional context

<details>
<summary>Active scan script used</summary>

```js
// Note that new active scripts will initially be disabled
// Right click the script in the Scripts tree and select "enable"  

/**
 * Scans a "node", i.e. an individual entry in the Sites Tree.
 * The scanNode function will typically be called once for every page. 
 * 
 * @param as - the ActiveScan parent object that will do all the core interface tasks 
 *     (i.e.: sending and receiving messages, providing access to Strength and Threshold settings,
 *     raising alerts, etc.). This is an ScriptsActiveScanner object.
 * @param msg - the HTTP Message being scanned. This is an HttpMessage object.
 */
ScriptVars = Java.type("org.zaproxy.zap.extension.script.ScriptVars");

function scanNode(as, msg) {
    // Debugging can be done using println like this
    print('scan called for url=' + msg.getRequestHeader().getURI().toString());

    // Copy requests before reusing them
    //msg = msg.cloneRequest();
    orheader = msg.getRequestHeader();
    if (orheader.getMethod() == 'GET') {
        //Looks for every / in path
        indices = [];
        if (orheader.getURI().getPath()){
            for( i=0; i<orheader.getURI().getPath().toString().length;i++) {
                if (orheader.getURI().getPath().toString()[i] === "/") indices.push(i);
            }
            originalPath = orheader.getURI().getPath().toString();
        }
        else{
            originalPath = ""
        }
        
        //Tests for every path found except the first one
        for(i = 1; i < indices.length; i++){
            msg = msg.cloneRequest();
            header = msg.getRequestHeader();
            header.getURI().setQuery("");
            newPath = originalPath.substr(0,indices[i]) + "../";
            print(newPath);
            //Stores the scanned paths on a global variable so they don't get scanned again
            alreadyScanned = ScriptVars.getGlobalCustomVar(this['zap.script.name']);
            print(alreadyScanned);
            if (alreadyScanned == null) {
                alreadyScanned = [];
            }
            if (alreadyScanned.indexOf(newPath) != -1) {
                //return;
            }
            alreadyScanned.push(newPath);
            ScriptVars.setGlobalCustomVar(this['zap.script.name'],alreadyScanned);
            msg.getRequestHeader().getURI().setPath(newPath);

            // sendAndReceive(msg, followRedirect, handleAntiCSRFtoken)
            as.sendAndReceive(msg, false, false);

            if (msg.getResponseHeader().getStatusCode() == 403){
                addAlert(as, msg, newPath, header.getURI().toString());
            }
        }
    }
    
}

function addAlert(as, msg, evidence, uri) {
    var alertRisk = 3
    var alertConfidence = 2
    var alertTitle = 'Nginx Off by slash'
    var alertDesc = 'The application might be vulnerable to path traversal due a misconfiguration on Nginx.'
    var alertSolution = 'Add a trailing / to the reported path on the sites file.'
    var alertInfo = 'https://i.blackhat.com/us-18/Wed-August-8/us-18-Orange-Tsai-Breaking-Parser-Logic-Take-Your-Path-Normalization-Off-And-Pop-0days-Out-2.pdf'
    var cweId = 22 //Improper Limitation of a Pathname to a Restricted Directory ('Path Traversal')
    var wascId = 14 //Server Misconfiguration
    var tagName = "OWASP_2021_A05"
    var tagValue = "https://owasp.org/Top10/A05_2021-Security_Misconfiguration/"
    var reference = "https://i.blackhat.com/us-18/Wed-August-8/us-18-Orange-Tsai-Breaking-Parser-Logic-Take-Your-Path-Normalization-Off-And-Pop-0days-Out-2.pdf"
    var parameter = ""
    var attack = ""
    var inputVector = ""

    newAlert = as.newAlert();
    newAlert.setRisk(alertRisk);
    newAlert.setConfidence(alertConfidence);
    newAlert.setName(alertTitle);
    newAlert.setDescription(alertDesc);
    newAlert.setSolution(alertSolution);
    newAlert.setOtherInfo(alertInfo);
    newAlert.setCweId(cweId);
    newAlert.setWascId(wascId);
    newAlert.setMessage(msg);
    newAlert.setEvidence(evidence);
    newAlert.setUri(uri);
    newAlert.addTag(tagName, tagValue);
    newAlert.setReference(reference);
    newAlert.setParam(parameter);
    newAlert.setAttack(attack);
    newAlert.setInputVector(inputVector);
    newAlert.raise();

    //as.raiseAlert(alertRisk, alertConfidence, alertTitle, alertDesc, url, '', '', alertInfo, alertSolution, path, cweId, wascId, msg);
}

/**
 * Scans a specific parameter in an HTTP message.
 * The scan function will typically be called for every parameter in every URL and Form for every page.
 * 
 * @param as - the ActiveScan parent object that will do all the core interface tasks 
 *     (i.e.: sending and receiving messages, providing access to Strength and Threshold settings,
 *     raising alerts, etc.). This is an ScriptsActiveScanner object.
 * @param msg - the HTTP Message being scanned. This is an HttpMessage object.
 * @param {string} param - the name of the parameter being manipulated for this test/scan.
 * @param {string} value - the original parameter value.
 */
function scan(as, msg, param, value) {
    
}

```

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment]
Using default active scanner configurations?

**Comment by 5ubterranean** [comment]
I created a scan policy and set everything off, and only left "script Active rules" on default, everything else as default.

**Comment by thc202** [comment]
This is an issue in the script implementation, you are storing/accessing the JS array concurrently, the array itself does not support concurrency neither the engine allows that, you could/should use one of the Java collections that supports concurrency or sync its access.
