### ISSUE TITLE
ZAP 2.14.0 installer on Windows have misleading text when asking for Java Runtime Environment

### ISSUE THREAD

**Issue by eiriklid** [zaproxy/zaproxy#8355]
### Describe the bug

When trying to install on Windows I got asked if I could point to the location of Java.

As I didn't have Java installed I went to https://www.java.com/en/download/ and downloaded the latest version ( jre-8u401-windows-x64).
I found it a bit weird that ZAP asked for minimum version of 11, when the latest is version 8.

Then selecting the java.exe did not work.

Only after I came across this post https://stackoverflow.com/a/75093390/5918611 and installed the latest OpenJDK, would the installer succeed.

I'm sure that this issue is trivial for anyone who have done any development in Java, but I found it confusing. I see that similar issues have been raised before as well: https://github.com/zaproxy/zaproxy/issues/6122  

### Steps to reproduce the behavior

Install ZAP without Java on Windows

### Expected behavior

I would expect an error message that the describes what is needed to fix the problem.

### Software versions

ZAP 2.14.0

### Would you like to help fix this issue?

- [X] Yes

**Comment by psiinon** [comment]
And where did you download ZAP From?
https://www.zaproxy.org/download/ states that: "The Windows and Linux versions require Java 11 or higher to run."

**Comment by eiriklid** [comment]
![image](https://github.com/zaproxy/zaproxy/assets/14213127/2e52cc6f-5d40-4a01-be98-310a231ad6f3)
From my googling I wonder if it is actually referring to jdk, and not jre. Could that be the case?

**Comment by eiriklid** [comment]
Downloaded from https://www.zaproxy.org/download/

**Comment by eiriklid** [comment]
From https://www.java.com/en/download/help/whatis_java.html

> **What will I get when I download Java software from java.com?**
> The Java Runtime Environment (JRE) version 8 is what you get when you download Java software from java.com.

**Comment by thc202** [comment]
No, the JRE is more than enough to run ZAP as long as it is 11+. We do not recommend downloading from `java.com, the installer should be linking to https://adoptium.net/

**Comment by eiriklid** [comment]
aha, thank you! Sorry for the confusion. 
I used https://adoptium.net/ for the jdk originally, but I can confirm that it also works when using the jre from https://adoptium.net/.

**Comment by thc202** [comment]
Closing as this is now clarified.
