### ISSUE TITLE
Allow to resend a request with keyboard shortcut (Ctrl+M)

### ISSUE THREAD

**Issue by njmulsqb** [zaproxy/zaproxy#8365]
### Describe the bug

When I have a request opened, I want to quickly send it to request editor using default keyboard shortcut i.e. Ctrl + M (like we do with Ctrl + W to send it to requester tab) but it doesnt work, it opens the request editor but with some placeholder request data

### Steps to reproduce the behavior

1. Ctrl + M on a request

### Expected behavior

It should send the opened to request to the request editor window using Ctrl + M

### Software versions

ZAP
Version: 2.14.0

Installed Add-ons: [[id=accessControl, version=9.0.0],
[id=alertFilters, version=19.0.0], [id=ascanrules,
version=63.0.0], [id=authhelper, version=0.12.0],
[id=automation, version=0.35.0], [id=browserView,
version=6.0.0], [id=bruteforce, version=15.0.0],
[id=callhome, version=0.10.0], [id=commonlib,
version=1.22.0], [id=custompayloads, version=0.13.0],
[id=database, version=0.3.0], [id=diff, version=14.0.0],
[id=directorylistv1, version=7.0.0], [id=domxss,
version=18.0.0], [id=encoder, version=1.4.0],
[id=evalvillain, version=0.3.0], [id=exim, version=0.8.0],
[id=fileupload, version=1.2.1], [id=formhandler,
version=6.5.0], [id=fuzz, version=13.12.0],
[id=gettingStarted, version=16.0.0], [id=graphql,
version=0.23.0], [id=help, version=17.0.0], [id=highlighter,
version=8.0.0], [id=hud, version=0.18.0], [id=invoke,
version=14.0.0], [id=jsonview, version=3.0.0], [id=jwt,
version=1.0.3], [id=network, version=0.14.0], [id=oast,
version=0.17.0], [id=onlineMenu, version=12.0.0],
[id=openapi, version=39.0.0], [id=postman, version=0.2.0],
[id=pscanrules, version=56.0.0], [id=quickstart,
version=43.0.0], [id=replacer, version=16.0.0], [id=reports,
version=0.29.0], [id=requester, version=7.4.0], [id=retest,
version=0.8.0], [id=retire, version=0.31.0], [id=reveal,
version=7.0.0], [id=scripts, version=45.0.0], [id=selenium,
version=15.19.0], [id=soap, version=21.0.0], [id=spider,
version=0.10.0], [id=spiderAjax, version=23.18.0],
[id=sqliplugin, version=15.0.0], [id=tips, version=12.0.0],
[id=webdriverwindows, version=72.0.0], [id=websocket,
version=30.0.0], [id=zest, version=43.0.0]]

Operating System: Windows 11
Architecture: amd64
Java Version: Oracle Corporation 19.0.2
System's Locale: en_US
Display Locale: en_GB
Format Locale: en_US
Default Charset: UTF-8
ZAP Home Directory: C:\Users\najam\ZAP\
ZAP Installation Directory: C:\Program Files\ZAP\Zed Attack Proxy\.\
Look and Feel: FlatLaf Light (com.formdev.flatlaf.FlatLightLaf)

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment]
It's not supposed to work that way since that shortcut is to open the Manual Request Editor dialogue not to resend (which is other dialogue).

**Comment by njmulsqb** [comment]
Opening the dialog in most cases is for sending the request, simply opening it will demand copy/pasting the request manually.

**Comment by psiinon** [comment]
I'd def be in favour for Ctrl + M to open any currently selected request in the manual req dialog.
I would really like it to be possible to just use ZAP via the keyboard .. but there are quite a few tricky parts to that...

**Comment by njmulsqb** [comment]
> I would really like it to be possible to just use ZAP via the keyboard .. but there are quite a few tricky parts to that...

I totally second this, it makes life so much easier when you can use keyboard shortcuts to perform stuff instead of hovering over UI. e.g. in Burp you press Ctrl + I for sending current request to Intruder, Ctrl + R for repeater, etc. That's how it should be in case of ZAP as well. Global shortcuts that every user knows.

Also shortcuts should be mentioned with Fuzz, request editor, encode/decode buttons like they're mentioned with Select All, Open in Requester Tab, etc. in context menu.

**Comment by psiinon** [comment]
These sort of things could be good first/second issues, as long as we can point people to good example code ...
