### ISSUE TITLE
Ability to copy URL from request editor

### ISSUE THREAD

**Issue by njmulsqb** [zaproxy/zaproxy#8368]
### Is your feature request related to a problem? Please describe.

N/A

### Describe the solution you'd like

I would want to be able to edit the request URL from the request editor or requester window. 

### Describe alternatives you've considered

I can do it from site tree but it will be more feasible to do it from request editor.

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment]
Edit or copy?

**Comment by kingthorin** [comment]
I think we are failing to understand how using a menu is better than just highlighting and copying with standard menus or hotkeys.

**Comment by njmulsqb** [comment]
> I think we are failing to understand how using a menu is better than just highlighting and copying with standard menus or hotkeys.

I just noticed the URL is in full form in the request editor unlike Burp; yeah copying manually makes sense. Thanks
