### ISSUE TITLE
Shouldn't this be Dracula instead of Darcula?

### ISSUE THREAD

**Issue by njmulsqb** [zaproxy/zaproxy#8372]
### Describe the bug

While selecting the theme of ZAP, I see this option _Flat Darcula_, it seems a typo to me.

### Steps to reproduce the behavior

1. Go to ZAP GUI
2. Click the "Dynamically switch the look and feel" button

### Expected behavior

It should be "Dracula"

### Software versions

ZAP
Version: 2.14.0

Installed Add-ons: [[id=accessControl, version=9.0.0],
[id=alertFilters, version=19.0.0], [id=ascanrules,
version=63.0.0], [id=authhelper, version=0.12.0],
[id=automation, version=0.35.0], [id=bruteforce,
version=15.0.0], [id=callhome, version=0.10.0],
[id=commonlib, version=1.22.0], [id=custompayloads,
version=0.13.0], [id=database, version=0.3.0], [id=diff,
version=14.0.0], [id=directorylistv1, version=7.0.0],
[id=domxss, version=18.0.0], [id=encoder, version=1.4.0],
[id=exim, version=0.8.0], [id=formhandler, version=6.5.0],
[id=fuzz, version=13.12.0], [id=gettingStarted,
version=16.0.0], [id=graaljs, version=0.5.0], [id=graphql,
version=0.23.0], [id=help, version=17.0.0], [id=hud,
version=0.18.0], [id=invoke, version=14.0.0], [id=network,
version=0.14.0], [id=oast, version=0.17.0], [id=onlineMenu,
version=12.0.0], [id=openapi, version=39.0.0], [id=postman,
version=0.2.0], [id=pscanrules, version=56.0.0],
[id=quickstart, version=43.0.0], [id=replacer,
version=16.0.0], [id=reports, version=0.29.0],
[id=requester, version=7.4.0], [id=retest, version=0.8.0],
[id=retire, version=0.31.0], [id=reveal, version=7.0.0],
[id=scripts, version=45.0.0], [id=selenium,
version=15.19.0], [id=soap, version=21.0.0], [id=spider,
version=0.10.0], [id=spiderAjax, version=23.18.0], [id=tips,
version=12.0.0], [id=webdrivermacos, version=73.0.0],
[id=websocket, version=30.0.0], [id=zest, version=43.0.0]]

Operating System: Mac OS X
Architecture: aarch64
Java Version: Eclipse Adoptium 11.0.20.1
System's Locale: en_PK
Display Locale: en_GB
Format Locale: en_PK
Default Charset: UTF-8
ZAP Home Directory: /Users/administrator/Library/Application Support/ZAP/
ZAP Installation Directory: /Applications/ZAP.app/Contents/Java/./
Look and Feel: Mac OS X (com.apple.laf.AquaLookAndFeel)

### Screenshots

<img width="126" alt="image" src="https://github.com/zaproxy/zaproxy/assets/47940898/c7873d84-755e-44db-b12d-95c275405a99">

### Would you like to help fix this issue?

- [X] Yes

**Comment by thc202** [comment]
No, as seen in https://github.com/JFormDesigner/FlatLaf?tab=readme-ov-file#flatlaf---flat-look-and-feel

Please, use the user group for questions: https://groups.google.com/g/zaproxy-users/
