### ISSUE TITLE
 open browser  fail

### ISSUE THREAD

**Issue by hqf007** [zaproxy/zaproxy#8373]
### Describe the bug

in version 2.11 ,i can open chrome ,it works ok.................but the new version 2.14 can't .it report [the provided browser not found ]
is the selenium version not support or chrome version not support?

### Expected behavior

in the quick start ,click open browser 

### Software versions

2.14

### Would you like to help fix this issue?

- [ ] Yes

**Comment by psiinon** [comment]
See https://www.zaproxy.org/faq/how-can-i-fix-browser-was-not-found/
