### ISSUE TITLE
False Positive -- SQL Injection - SQLite

### ISSUE THREAD

**Issue by njmulsqb** [zaproxy/zaproxy#8381]
ZAP scanner has found this issue in multiple URLs (interestingly in CSS files too, related https://github.com/zaproxy/zaproxy/issues/6911#issuecomment-962447121)

<img width="995" alt="image" src="https://github.com/zaproxy/zaproxy/assets/47940898/c02bd339-ba45-4dd5-a206-2521baae7516">

I have tried changing this random blob value to massive figures but the response time is not very different, also the application is responding normally, some of the URLs are images/css/js as already mentioned while others are GET requests with params but I dont think so there's any SQLi

**Comment by thc202** [comment]
Closing as duplicate of #8112, specifically https://github.com/zaproxy/zaproxy/issues/8112#issuecomment-1819848796

**Comment by njmulsqb** [comment]
@thc202 but in the above case not all findings are in static files, some are in GET requests to web endpoints as well.

**Comment by thc202** [comment]
Whether or not they are static is not the problem, the problem is that the current time based tests are not reliable (and what the linked comment aims to address).
