### ISSUE TITLE
Add websockets to search functionality

### ISSUE THREAD

**Issue by someusername123** [zaproxy/zaproxy#8397]
### Is your feature request related to a problem? Please describe.

No, not related to a problem. In some of my use cases with ZAP I would like to be able to go and search the websockets for a pattern but this functionality is currently not there.

### Describe the solution you'd like

To be able to search the websockets history within the search functionality

### Describe alternatives you've considered

Currently what I use is breakpoints, but this many times will break the application as it is expecting a reply within a certain time frame.

### Would you like to help fix this issue?

- [ ] Yes

**Comment by someusername123** [comment]
I searched the open tickets for items related to this, if this is a duplicate please feel free to let me know and close the ticket!

**Comment by thc202** [comment]
Not exactly search but you can filter for a pattern (which should yield the same results).

**Comment by someusername123** [comment]
I actually just figured that out and felt kind of silly for opening this request. There is also search (find) functionality in the websockets tab that will do what I'm looking for by hitting ctrl+f. Going to close this ticket, thanks for the feedback!
