### ISSUE TITLE
Scan Reporting Empty GUID as Vulnerable JS Library Version

### ISSUE THREAD

**Issue by terminal-root** [zaproxy/zaproxy#8398]
### Describe the bug

We have had daily docker scans going for a while and recently a new item showed up in the report that was not there before.

```
The identified library lodash, version 00000000-0000-0000-0000-000000000000 is vulnerable
```

Stack trace:
```
https://example.com/service/main.asdf.js, GET, ,
```
(parts of url changed for privacy)

To me, this seems like something odd is happening with the version identification rather than an actual vulnerability. Am I thinking correctly? Or, should I take this more seriously?

### Steps to reproduce the behavior

Use Automation Framework YAML plan to run authenticated spider and generate report on the stable docker release of ZAP.

### Expected behavior

Any versions shown in vulnerability listings are valid.

### Software versions

2.14.0 (owasp/zap2docker-stable)

### Screenshots

![image](https://github.com/zaproxy/zaproxy/assets/24536673/cf4c6b57-da0c-4f0a-98fb-516e6ba84696)

### Would you like to help fix this issue?

- [X] Yes

**Comment by thc202** [comment]
Same root problem as #8384.
