### ISSUE TITLE
Manually set key binds not Applying.

### ISSUE THREAD

**Issue by yada97** [zaproxy/zaproxy#8408]
### Describe the bug

The process of applying your own key binds does not work. You can actually apply but the key bind does not work. In fact, going back to the keyboard settings does not show any sign of any key binds set.  

### Steps to reproduce the behavior

1. Go to Tools then Options
2.  Go to Keyboard and Apply any key bind you feel like
3. Test the Key bind you just applied
4. Check in The Tools/Options/Keyboard section if the key bind had actually been set.

### Expected behavior

When Applying the key bind, you would expect that the keyboard shortcut would work after being applied.

### Software versions

2.14.0-1

### Would you like to help fix this issue?

- [ ] Yes

**Comment by psiinon** [comment]
Confirmed on macOS

**Comment by psiinon** [comment]
Update - some settings work while others dont. This could be due to macOS being "complicated" with key bindings.
e.g. see https://bugs.openjdk.org/browse/JDK-8013459

**Comment by yada97** [comment]
I' am on Linux, The key binds still do not work.

**Comment by yada97** [comment]
On restarting ZAP, the key binds did apply.
