### ISSUE TITLE
Incorrect request with sender

### ISSUE THREAD

**Issue by zakrush** [zaproxy/zaproxy#8409]
### Describe the bug

I found some bug with skripting and send request to Keycloak. 
I think this bug in core. I will try to debug it later. 

I describe it in community https://groups.google.com/g/zaproxy-users/c/4CCpxGmS6X0
I have script below in attach.
[ds_session_header.txt](https://github.com/zaproxy/zaproxy/files/14663219/ds_session_header.txt)

When I print the data from HttpMessage() object of login func I got correct data. If I copy and paste header and body from print output to requester I got access_token in response. Howere in HTTP Sender script I got "Missing form parameter: grant_type"

I touch tcp_dump on server and found that Request are comming without body, but I make in script all correctly. 

### Steps to reproduce the behavior

1. Install and configure some server for test
2. Setup jython plugin and copy script from attach to HTTP sender scripts
3. Setup KAFKA url and username and password in login function. formBody variable
4. Enable script
5. Start ative scan any target

### Expected behavior

The request that is sending by zap throught sender work correctly and send headers and body. 

### Software versions

ZAP
Version: D-2024-03-18

Installed Add-ons: [[id=accessControl, version=10.0.0],
[id=alertFilters, version=20.0.0], [id=ascanrules,
version=64.0.0], [id=ascanrulesAlpha, version=46.0.0],
[id=ascanrulesBeta, version=52.0.0], [id=authhelper,
version=0.13.0], [id=automation, version=0.36.0],
[id=bruteforce, version=16.0.0], [id=callhome,
version=0.12.0], [id=commonlib, version=1.23.0],
[id=communityScripts, version=18.0.0], [id=coreLang,
version=16.0.0], [id=custompayloads, version=0.13.0],
[id=database, version=0.4.0], [id=diff, version=15.0.0],
[id=directorylistv1, version=8.0.0], [id=domxss,
version=19.0.0], [id=encoder, version=1.5.0], [id=exim,
version=0.9.0], [id=fileupload, version=1.2.1],
[id=formhandler, version=6.6.0], [id=fuzz, version=13.13.0],
[id=graaljs, version=0.6.0], [id=graphql, version=0.24.0],
[id=help, version=17.0.0], [id=invoke, version=15.0.0],
[id=jwt, version=1.0.3], [id=jython, version=14.0.0],
[id=network, version=0.15.0], [id=oast, version=0.18.0],
[id=openapi, version=40.0.0], [id=plugnhack,
version=14.0.0], [id=portscan, version=11.0.0], [id=postman,
version=0.3.0], [id=pscanrules, version=57.0.0],
[id=pscanrulesAlpha, version=42.0.0], [id=pscanrulesBeta,
version=38.0.0], [id=replacer, version=17.0.0], [id=reports,
version=0.31.0], [id=requester, version=7.5.0], [id=retest,
version=0.9.0], [id=retire, version=0.33.0], [id=reveal,
version=8.0.0], [id=saml, version=10.0.0], [id=scripts,
version=45.1.0], [id=selenium, version=15.20.0],
[id=sequence, version=8.0.0], [id=soap, version=22.0.0],
[id=spider, version=0.11.0], [id=spiderAjax,
version=23.19.0], [id=sqliplugin, version=15.0.0],
[id=webdriverlinux, version=76.0.0], [id=webdrivermacos,
version=76.0.0], [id=webdriverwindows, version=76.0.0],
[id=websocket, version=31.0.0], [id=zest, version=44.0.0]]

Operating System: Linux
Architecture: amd64
CPU Cores: 16
Max Memory: 7 GB
Java Version: Debian 11.0.22
System's Locale: en
Display Locale: en_GB
Format Locale: en
Default Charset: UTF-8
ZAP Home Directory: /home/zap/.ZAP_D/
ZAP Installation Directory: /zap/./
Look and Feel: FlatLaf Light (com.formdev.flatlaf.FlatLightLaf)

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment]
Make sure to update the content-length header to match that of the body sent.

**Comment by kingthorin** [comment]
Your script is limited to:
```
// 		2	ACTIVE_SCANNER_INITIATOR
// 		3	SPIDER_INITIATOR
```

https://github.com/zaproxy/community-scripts/tree/main/httpsender

**Comment by zakrush** [comment]
> Your script is limited to:
> 
> ```
> // 		2	ACTIVE_SCANNER_INITIATOR
> // 		3	SPIDER_INITIATOR
> ```
> 
> https://github.com/zaproxy/community-scripts/tree/main/httpsender

Yes. I wanted it. 
@thc202 Thanks very much. I spent a lot of time for this.

**Comment by kingthorin** [comment]
> Yes. I wanted it.

My point was you shouldn't expect it to impact other things like Requester etc if you've limited it :wink: 🤷‍♂️
