### ISSUE TITLE
UI problem on ZAP

### ISSUE THREAD

**Issue by rasehum** [zaproxy/zaproxy#8424]
![image](https://github.com/zaproxy/zaproxy/assets/60820917/2fe3bbdf-bf57-4768-9f16-c35492b2715c)

As you can see from this issue, whenever my mouse moves, ZAP decides to go haywire and I am not able to see anything on the screen.

**Comment by rasehum** [comment]
![image](https://github.com/zaproxy/zaproxy/assets/60820917/cbd81ec9-acc8-48c1-b7f4-ac5d20c0836a)
Here are some other Pictures of the issue. My Java is up to date, and I am currently using Java 22
![image](https://github.com/zaproxy/zaproxy/assets/60820917/f96cd15c-bcef-4f29-a1e8-c26ed4df43ee)

**Comment by kingthorin** [comment]
Likely a JRE or gfx issue. I'd suggest a reboot and retry.

Also Java 22 was just released and I doubt anyone in the team has tested with it yet.

**Comment by kingthorin** [comment]
Next time you open an issue please use a proper template so that we get all the proper details.

https://github.com/zaproxy/zaproxy/issues/new/choose
