### ISSUE TITLE
"Cloud Metadata Potentially Exposed" Correct Response Inquiry

### ISSUE THREAD

**Issue by dennisarriola** [zaproxy/zaproxy#8428]
Hello,

I am new to ZAP and was assigned to check the security of our web application using ZAP.

One of the findings was "Cloud Metadata Potentially Exposed".
However, I read some "false positive" result regarding this "Cloud Metadata Potentially Exposed" item.
I would like to know more about this item specifically the "expected result/respond" if the web application is really vulnerable.

I upload the request and respond in my testing.
Request:
![ZapRequest_1](https://github.com/zaproxy/zaproxy/assets/54200801/af25252e-8db0-4f94-a21c-f39e266c335b)
Respond:
![ZapRespond_1](https://github.com/zaproxy/zaproxy/assets/54200801/b91fcf04-c58c-4541-8a50-642a94ab77fc)
 
Can someone explains to me what the meaning of the respond?
Is our web application is really vulnerable with "Cloud Metadata Potentially Exposed"?

I couldn't find the same response with ours. 

Thank you very much in advance.

**Comment by bj-taduran** [comment]
Hi, @dennisarriola 

The response is not conclusive yet. Further investigation on your web server has to be conducted.

CONTEXT:

The "Cloud Metadata Potentially Exposed" alert only means that your web server is not blocking the use of "169.254.169.254" in the "host" header of the http request. As a best practice, requests like this has to be blocked. Your web server might have a proxy setting that uses the "host" header for routing messages, but your web server should never route to "169.254.169.254" as information (cloud instance/infrastructure information) from this IP address can compromise your whole cloud environment.

Some web servers use the "host" header from the http request to route the message to the IP address or domain indicated. This happen when your web server acts as a proxy and has a similar configuration like below
```
location / {
    proxy_pass http://$host; # To repeat: don't do this!
}
```
this configuration is an example from NGINX.

NEEDED ACTION:

If your web server is acting as a proxy, you must block requests with "host" value of "169.254.169.254". Normally, there's no reason for you to route requests to this IP address.

If your server is not a proxy, better to remove any similar configuration.

FURTHER INFO AND DISCUSSION:
https://www.nginx.com/blog/trust-no-one-perils-of-trusting-user-input/

Tell me, if this explanation has been helpful.

**Comment by dennisarriola** [comment]
Hello @bj-taduran,

Thank you for your detailed explanation!
Definitely, your answer helps us a lot understanding this "Cloud Metadata Potentially Exposed" vulnerability item.

I have additional questions tho.
You've mentioned that "Further investigation on your web server has to be conducted" and suggested some NEEDED ACTION, upon checking, our web server has a feature that can connect to a proxy server, in relation to your suggested NEEDED ACTTION,  if we block requests with "host" value of "169.254.169.254", will this fix this finding ("Cloud Metadata Potentially Exposed")? And this wont be included in the rescan?

Thank you very much, kabayan. 
Pinoy din ako. :D

**Comment by thc202** [comment]
Where do you see it's acting as a proxy?

**Comment by dennisarriola** [comment]
Hello @thc202, @bj-taduran,

Thanks for clarifying.

Our web server can be configured to connect to a proxy server (different PC) to allow connection from our web server to internet needed for our application to work. This case is only application if the network environment needs proxy to connect outside of the company network.

Hope this will help. 
Thank you again~
