### ISSUE TITLE
ZAP does not pause autoscan when internet connection become lost

### ISSUE THREAD

**Issue by JuraLys** [zaproxy/zaproxy#8430]
### Describe the bug

ZAP does not stop autoscan when internet connection become lost

### Steps to reproduce the behavior

Run ZAP and start autoscan of some site
Disconnect internet and observe ZAP progress

### Expected behavior

ZAP should show error about disconnection and stop scan

### Software versions

ZAP Version: 2.14.0

Installed Add-ons: [[id=alertFilters, version=19.0.0],
[id=ascanrules, version=65.0.0], [id=ascanrulesBeta,
version=53.0.0], [id=authhelper, version=0.12.0],
[id=automation, version=0.37.0], [id=bruteforce,
version=15.0.0], [id=callhome, version=0.11.0],
[id=commonlib, version=1.23.0], [id=coreLang,
version=15.0.0], [id=custompayloads, version=0.13.0],
[id=database, version=0.3.0], [id=diff, version=14.0.0],
[id=directorylistv1, version=7.0.0], [id=directorylistv2_3,
version=4.0.0], [id=directorylistv2_3_lc, version=4.0.0],
[id=domxss, version=18.0.0], [id=encoder, version=1.4.0],
[id=exim, version=0.8.0], [id=formhandler, version=6.5.0],
[id=fuzz, version=13.12.0], [id=gettingStarted,
version=16.0.0], [id=graaljs, version=0.5.0], [id=graphql,
version=0.23.0], [id=help, version=17.0.0], [id=hud,
version=0.18.0], [id=invoke, version=14.0.0], [id=network,
version=0.15.0], [id=oast, version=0.17.0], [id=onlineMenu,
version=12.0.0], [id=openapi, version=39.0.0], [id=portscan,
version=10.0.0], [id=postman, version=0.2.0],
[id=pscanrules, version=57.0.0], [id=pscanrulesBeta,
version=37.0.0], [id=quickstart, version=45.0.0],
[id=replacer, version=16.0.0], [id=reports, version=0.31.0],
[id=requester, version=7.5.0], [id=retest, version=0.8.0],
[id=retire, version=0.33.0], [id=reveal, version=7.0.0],
[id=scripts, version=45.1.0], [id=selenium,
version=15.20.0], [id=soap, version=22.0.0], [id=spider,
version=0.10.0], [id=spiderAjax, version=23.18.0],
[id=sqliplugin, version=15.0.0], [id=svndigger,
version=4.0.0], [id=tips, version=12.0.0], [id=tokengen,
version=15.0.0], [id=wappalyzer, version=21.33.0],
[id=webdriverwindows, version=77.0.0], [id=websocket,
version=30.0.0], [id=zest, version=43.0.0]]

Operating System: Windows 10
Architecture: amd64
Java Version: Eclipse Adoptium 21.0.1
System's Locale: uk_UA
Display Locale: en_GB
Format Locale: uk_UA
Default Charset: UTF-8
ZAP Home Directory: C:\Users\Admin\ZAP\
ZAP Installation Directory: C:\Program Files\ZAP\Zed Attack Proxy\.\
Look and Feel: Metal (javax.swing.plaf.metal.MetalLookAndFeel)

### Errors from the zap.log file

[ZAP-does-not-stop-autoscan.txt](https://github.com/zaproxy/zaproxy/files/14878022/ZAP-does-not-stop-autoscan.txt)

### Would you like to help fix this issue?

- [X] Yes

**Comment by psiinon** [comment]
There should also be options to stop the ZAP scan if the server starts returning too many (for example) 5xx codes, or too many auth failures.

**Comment by ganesh-dagadi** [comment]
I went over the error log files and had a look at the code,
[This](https://github.com/zaproxy/zap-extensions/blob/495bc2f31359c07eda59d8c737c9837c1e1241e0/addOns/network/src/main/java/org/zaproxy/addon/network/internal/client/apachev5/HttpSenderApache.java#L490-L492) is where the connection loss is detected and thrown as `IOException` 

I believe that this exception is somehow thrown up to the `HostProcess` which is then handled by stopping the `HostProcess`. The `HostProcess` should call the `stop()` method of the parentScanner.

Is my approach correct? If it is, how is the (specific method that uses the connection in Host process) `IOException` thrown from the connection loss?

**Comment by thc202** [comment]
That's not where the connection loss is detected, there the connection is just being closed prematurely (which can happen for several reasons unrelated to the overall health of the connection to the target).

For this issue we should look at the rate of connection failures to the target.
