### ISSUE TITLE
Disable cache - deleting cache headers

### ISSUE THREAD

**Issue by roisec** [zaproxy/zaproxy#8437]
### Is your feature request related to a problem? Please describe.

Hi 
I am trying easily to disable the cache for all the requests.
Some requests are cached, and I want to see the complete original response.
In burp proxy, there is an easy solution to do that:
The cache headers are:
If-Modified-Since
If-None-Match
![image](https://github.com/zaproxy/zaproxy/assets/68992144/745ac07e-8455-454d-bffb-1fb29d27f8ba)

### Describe the solution you'd like

Out-of-the-box support to disable cache in ZAP proxy

### Describe alternatives you've considered

Using ZAP scripts?

### Would you like to help fix this issue?

- [ ] Yes

**Comment by roisec** [comment]
Is there any option to set the config using a file?
If I would like to use it on CI/CD and load static config for this?

**Comment by psiinon** [comment]
You can use the Automation Framework 😁 
https://www.zaproxy.org/docs/automate/automation-framework/
https://www.zaproxy.org/docs/desktop/addons/replacer/automation/

**Comment by kingthorin** [comment]
These could be added as default Replacer rules, however they'd still ship initially disabled. I currently have a PR in-flight that's adding some handling to disable Report-To / Report-Uri after that's dealt with I'd be happy to tackle this. In CI/CD you'd still need to handle them somehow.

**Comment by roisec** [comment]
thanks

**Comment by kingthorin** [comment]
Did you close this on purpose? Should we not add rules for this?

**Comment by roisec** [comment]
Yes, if I able to enable rules automatically on CICD then it would work fine.

**Comment by kingthorin** [comment]
Well automatically via the API or Automation Framework.

**Comment by thc202** [comment]
If you are going to do work through the API/AF, you can already add/enable them, not need to wait for default rules.

**Comment by kingthorin** [comment]
💯 %
