### ISSUE TITLE
2.14版本的报告问题

### ISSUE THREAD

**Issue by wanghonghe** [zaproxy/zaproxy#8446]
### Is your feature request related to a problem? Please describe.

当完成扫描之后，点击“报告”——“生成报告“，导出并打开后并没有实质性内容。
不像2.11版本那样可以导出多种格式的报告，而且报告内容很丰富，可以体现实质性漏洞细节等内容。

### Describe the solution you'd like

希望能够像2.11版本的报告一样

### Describe alternatives you've considered

没有

### Screenshots

奇怪，截图上传不了。。。。

### Would you like to help fix this issue?

- [ ] Yes

**Comment by kingthorin** [comment]
What version of the report add-on are you using?

**Comment by wanghonghe** [comment]
zap版本为最新的2.14.0
报告没有安装第三方版本，直接”报告“——”生成报告“

**Comment by kingthorin** [comment]
I didn’t ask about third party plugins.

Please add version information from ZAPs menu Help > Support Info, or from the CLI using the -suppinfo switch.

**Comment by wanghonghe** [comment]
> I didn’t ask about third party plugins.
> 
> Please add version information from ZAPs menu Help > Support Info, or from the CLI using the -suppinfo switch.

Support Info:
ZAP
版本： 2.14.0

已安装的附加组件： [[id=alertFilters, version=20.0.0],
[id=ascanrules, version=65.0.0], [id=authhelper,
version=0.12.0], [id=automation, version=0.38.0],
[id=bruteforce, version=15.0.0], [id=callhome,
version=0.11.0], [id=commonlib, version=1.24.0],
[id=database, version=0.3.0], [id=diff, version=14.0.0],
[id=directorylistv1, version=7.0.0], [id=domxss,
version=18.0.0], [id=encoder, version=1.4.0], [id=exim,
version=0.8.0], [id=formhandler, version=6.5.0], [id=fuzz,
version=13.12.0], [id=gettingStarted, version=16.0.0],
[id=graaljs, version=0.6.0], [id=graphql, version=0.23.0],
[id=help, version=17.0.0], [id=hud, version=0.18.0],
[id=invoke, version=14.0.0], [id=network, version=0.15.0],
[id=oast, version=0.17.0], [id=onlineMenu, version=12.0.0],
[id=openapi, version=39.0.0], [id=postman, version=0.3.0],
[id=pscanrules, version=57.0.0], [id=quickstart,
version=45.0.0], [id=replacer, version=16.0.0], [id=reports,
version=0.31.0], [id=requester, version=7.5.0], [id=retest,
version=0.8.0], [id=retire, version=0.34.0], [id=reveal,
version=7.0.0], [id=scripts, version=45.2.0], [id=selenium,
version=15.21.0], [id=soap, version=22.0.0], [id=spider,
version=0.10.0], [id=spiderAjax, version=23.18.0], [id=tips,
version=12.0.0], [id=webdriverwindows, version=79.0.0],
[id=websocket, version=30.0.0], [id=zest, version=44.0.0]]

操作系统： Windows 10
架构： amd64
Java版本： Oracle Corporation 11.0.21
系统语言环境： zh_CN
显示语言环境： zh_CN
格式语言环境： zh_CN
默认字符集： GBK
ZAP Home 目录： C:\Users\admin\ZAP\
ZAP 安装目录： D:\Program Files\ZAP\Zed Attack Proxy\.\
外观： Windows (com.sun.java.swing.plaf.windows.WindowsLookAndFeel)

**Comment by wanghonghe** [comment]
https://blog.csdn.net/A_991128a/article/details/133785991
我的报告菜单中只有”与其他会话比较“和”生成报告“这两个功能，没有像这个文章中的那么多报告选项。而且导出的报告也没有实质的内容。

**Comment by psiinon** [comment]
This appears to be a support question rather than a bug in ZAP or feature request.
As such it should be asked on the ZAP USer Group: https://groups.google.com/group/zaproxy-users
