### ISSUE TITLE
As of 4 days ago there are only arm64 versions of the docker image available for zap2docker-stable

### ISSUE THREAD

**Issue by jcwimer** [zaproxy/zaproxy#8450]
### Describe the bug

https://hub.docker.com/r/owasp/zap2docker-stable/tags

There are only arm64 versions of the docker image availabe there are not longer amd64 versions pushed.

### Steps to reproduce the behavior

Go to https://hub.docker.com/r/owasp/zap2docker-stable/tags
 and see
![image](https://github.com/zaproxy/zaproxy/assets/4930626/ead13c8b-a5f9-4577-ba72-44570d6d88cc)

### Expected behavior

I should see amd64 versions available

### Software versions

Docker
Linux amd64

### Screenshots

![image](https://github.com/zaproxy/zaproxy/assets/4930626/bb682331-84e7-4220-aac0-51860a6bdfa9)

### Would you like to help fix this issue?

- [X] Yes

**Comment by jcwimer** [comment]
Looks like the documentation updated to use ghcr.io/zaproxy/zaproxy:stable

I have switched and it's now working.

**Comment by kingthorin** [comment]
Duplicate of #8440
