### ISSUE TITLE
publishing only linux/arm64 images to dockerhub?

### ISSUE THREAD

**Issue by rchincha** [zaproxy/zaproxy#8451]
### Describe the bug

https://hub.docker.com/r/owasp/zap2docker-stable/tags

Something broke recently, and only linux/arm64 images are being pushed to dockerhub.

### Steps to reproduce the behavior

https://hub.docker.com/r/owasp/zap2docker-stable/tags

### Expected behavior

Expect linux/amd64 and other platforms as well.

### Screenshots

https://hub.docker.com/r/owasp/zap2docker-stable/tags

### Would you like to help fix this issue?

- [ ] Yes

**Comment by psiinon** [comment]
Dup https://github.com/zaproxy/zaproxy/issues/8440

**Comment by kingthorin** [comment]
Duplicate of https://github.com/zaproxy/zaproxy/issues/8440

---

OWASP ZAP Docker images are no more, this should not be news:
https://www.zaproxy.org/blog/2023-08-01-zap-is-joining-the-software-security-project/#docker-hub
https://www.zaproxy.org/blog/2023-10-12-zap-2-14-0/#rebranding-and-docker-hub-move

(And many more posts in the user group and other places.)

For images that should be used: https://www.zaproxy.org/docs/docker/about/#install-instructions

---

Please refer to: https://www.zaproxy.org/download/#docker

As ZAP is no longer an OWASP project the images are moving away from the OWASP Docker org and will soon no longer be available there.

The images published today/this week are still a work in progress.
