### ISSUE TITLE
Why did I not have a quick start when installing zap2.14 for Win10

### ISSUE THREAD

**Issue by guoqi1234512** [zaproxy/zaproxy#8461]
### Describe the bug

Originally, there was a quick start in the morning, but it suddenly disappeared in the afternoon

### Steps to reproduce the behavior

I updated the software plugin

### Expected behavior

I need a quick start

### Software versions

2.14

### Screenshots

![QQ图片20240430165131](https://github.com/zaproxy/zaproxy/assets/164964610/e9507b28-f94b-43e9-a0ae-817925b5e047)

### Would you like to help fix this issue?

- [X] Yes

**Comment by thc202** [comment]
Use the ZAP User Group for questions: https://groups.google.com/g/zaproxy-users
