### ISSUE TITLE
no quick start 

### ISSUE THREAD

**Issue by guoqi1234512** [zaproxy/zaproxy#8463]
### Describe the bug

After the installation of 2.14zap, there was no quick start. There was still some in the morning, but not in the afternoon. Win10 system

### Steps to reproduce the behavior

no quick start

### Expected behavior

i need quick start

### Software versions

zap 2.14

### Screenshots

![QQ图片20240430165131](https://github.com/zaproxy/zaproxy/assets/164964610/80e53a2c-c03e-46c1-b107-5f06cf3d666c)

### Would you like to help fix this issue?

- [X] Yes

**Comment by guoqi1234512** [comment]
who help me

**Comment by psiinon** [comment]
Please ask questions like this on the User Group: https://groups.google.com/group/zaproxy-users
