### ISSUE TITLE
ZAP hanging when starting with Tech Detection add-on loading data

### ISSUE THREAD

**Issue by JuraLys** [zaproxy/zaproxy#8464]
### Describe the bug

Run ZAP and start autoscan specific site fakty.ua
Wait until ZAP gui crashes and close javaa console window
Run zap.bat again and observe hang when starting, see 
![ZAP-hang-when-starting](https://github.com/zaproxy/zaproxy/assets/146434286/1f24b951-b18a-4bfe-9b67-a24e77551a53)

### Steps to reproduce the behavior

Run ZAP and start autoscan specific site fakty.ua
Wait until ZAP gui crashes and close javaa console window
Run zap.bat again and observe hang when starting

### Expected behavior

ZAP should start

### Software versions

Updated ZAP 2.14
updated Windows 10 x64

### Screenshots

![ZAP-hang-when-starting](https://github.com/zaproxy/zaproxy/assets/146434286/4b63f0a9-acda-4201-bc03-517f5958ed8f)

### Errors from the zap.log file

[zap-log.zip](https://github.com/zaproxy/zaproxy/files/15161382/zap-log.zip)
[ZAP-gui-hang-when-starting2.txt](https://github.com/zaproxy/zaproxy/files/15161383/ZAP-gui-hang-when-starting2.txt)
[ZAP-gui-hang-when-starting.txt](https://github.com/zaproxy/zaproxy/files/15161384/ZAP-gui-hang-when-starting.txt)
[ZAP-gui-crash-when-scaning.txt](https://github.com/zaproxy/zaproxy/files/15161385/ZAP-gui-crash-when-scaning.txt)

### Would you like to help fix this issue?

- [X] Yes

**Comment by psiinon** [comment]
Please ask about these sort of problems on the user group: https://groups.google.com/group/zaproxy-users
We can raise an issue if a specific problem is identified in ZAP.
Rigjht now this is too generic.

**Comment by psiinon** [comment]
Sorry, I was too hasty! The logs do show a problem that we'll look into...

**Comment by kingthorin** [comment]
Version 21.36.0 of the Tech Detection add-on (wappalyzer) was just released which we hope addresses this issue. Please let us know if you continue to have problems after upgrading.
