### ISSUE TITLE
alertFilters filter not working fine with contexts.

### ISSUE THREAD

**Issue by magmax** [zaproxy/zaproxy#8471]
### Describe the bug

When using `context` on the configuration for `alertFilters` using automation framework, the filter doesn't work.

### Steps to reproduce the behavior

I've tested this using the spring4shell active scan, but probably others can be used. In addition, I'm using the spider to discover the real vulnerable path, and perhaps that could be improved as well.

1. dump this gist: https://gist.github.com/magmax/78f6195c7952c6bd68c8acba6f798ee3
2. change [the report dir](https://gist.github.com/magmax/78f6195c7952c6bd68c8acba6f798ee3#file-automate-scan-spring2shell-yaml-L66) on line 66 for `file-automate-scan-spring2shell.yaml` file
3. run the server: `python spring4shell-vulnerable.py`. This will expose the "vulnerable" server on port 8001.
4. run zaproxy: `zaproxy -cmd -port 8000 -autorun ${PWD}/zap/automate-scan-spring2shell.yaml -dir ${PWD}/zapdata`
5. the resultant report will mark the Spring2shell vulnerability as an error. Sometimes it is required to run step 4 several times until it appears, due to the spider randomness.
6. Now remove [the context](https://gist.github.com/magmax/78f6195c7952c6bd68c8acba6f798ee3#file-automate-scan-spring2shell-yaml-L57) from the alertFilter (line 57).
7. run zaproxy again: `zaproxy -cmd -port 8000 -autorun ${PWD}/zap/automate-scan-spring2shell.yaml -dir ${PWD}/zapdata`
8. Sometimes the previous command doesn't work at first time, so run it twice. It seems not to update correctly the output. Again, if the report doesn't show the spring4shell in any sense, it might be due to spider randomness.
9. now the vulnerability should be correctly marked as false positive.

### Expected behavior

mark vulnerabilities as false positives correctly, even using contexts, or remove contexts from documentation.

### Software versions

ZAP
Version: 2.14.0
Installed Add-ons: [[id=alertFilters, version=18.0.0], [id=ascanrules, version=58.0.0], [id=authhelper, version=0.10.0], [id=automation, version=0.33.0], [id=bruteforce, version=15.0.0], [id=callhome, version=0.8.0], [id=commonlib, version=1.18.0], [id=database, version=0.3.0], [id=diff, version=14.0.0], [id=directorylistv1, version=7.0.0], [id=domxss, version=18.0.0], [id=encoder, version=1.4.0], [id=exim, version=0.7.0], [id=formhandler, version=6.5.0], [id=fuzz, version=13.12.0], [id=gettingStarted, version=16.0.0], [id=graaljs, version=0.5.0], [id=graphql, version=0.20.0], [id=help, version=17.0.0], [id=hud, version=0.18.0], [id=invoke, version=14.0.0], [id=network, version=0.12.0], [id=oast, version=0.17.0], [id=onlineMenu, version=12.0.0], [id=openapi, version=37.0.0], [id=postman, version=0.2.0], [id=pscanrules, version=52.0.0], [id=quickstart, version=43.0.0], [id=replacer, version=15.0.0], [id=reports, version=0.26.0], [id=requester, version=7.4.0], [id=retest, version=0.8.0], [id=retire, version=0.26.0], [id=reveal, version=7.0.0], [id=scripts, version=42.0.0], [id=selenium, version=15.15.0], [id=soap, version=20.0.0], [id=spider, version=0.7.0], [id=spiderAjax, version=23.17.0], [id=tips, version=12.0.0], [id=webdriverlinux, version=64.0.0], [id=websocket, version=30.0.0], [id=zest, version=42.0.0]]
Operating System: Linux
Architecture: amd64
Java Version: Ubuntu 11.0.22
System's Locale: en_US
Display Locale: en_GB
Format Locale: en_GB
Default Charset: UTF-8

### Would you like to help fix this issue?

- [X] Yes

**Comment by kingthorin** [comment]
Move the alert filter job ahead of the job that is raising the alert.
