### ISSUE TITLE
ZAP should display popup message when autoscan complete

### ISSUE THREAD

**Issue by JuraLys** [zaproxy/zaproxy#8485]
### Is your feature request related to a problem? Please describe.

ZAP should display popup message when autoscan complete

### Describe the solution you'd like

ZAP should display popup message when autoscan complete

### Describe alternatives you've considered

no

### Would you like to help fix this issue?

- [X] Yes

**Comment by kingthorin** [comment]
Why?

**Comment by psiinon** [comment]
I think this is an idea case for an extender script - that should be possible right now.
I'd start with https://github.com/zaproxy/community-scripts/blob/main/extender/ZAP%20onEvent%20Handler.js

**Comment by kingthorin** [comment]
https://www.zaproxy.org/docs/internal-events/

**Comment by JuraLys** [comment]
> Why?

user should be notified

**Comment by psiinon** [comment]
But what about when the spider finishes, or any of the large number of events ZAP supports happens?
I think it would be wrong to add options in the GUI for each of these possibilities, especially when they can be easily acheived via a script.
If you would like help writing one then ask for help on the [Scripts Group](https://groups.google.com/g/zaproxy-scripts).
And if you do get one working then please submit it to the [Community Scripts](https://github.com/zaproxy/community-scripts)
