### ISSUE TITLE
issue when installing the new version 

### ISSUE THREAD

**Issue by DorghamX** [zaproxy/zaproxy#8486]
when i tried to update to the latest version of zap the uninstallation process was done successfully but when it tried to install the new version it popup this error 
![Screenshot 2024-05-12 160753](https://github.com/zaproxy/zaproxy/assets/74857675/a57358bf-12bc-44e3-97a0-f3450b9e0050)
and it doesn't matter how many times i click yes it still pops up again 

any advice ?

**Comment by kingthorin** [comment]
1) Use the issue templates next time.
2) Is the drive full or do you need admin etc permissions to install in your environment?

**Comment by DorghamX** [comment]
No its not full and i already run it as administrator

**Comment by kingthorin** [comment]
Exit ZAP, goto the location, delete the file. Launch ZAP goto the market place and install Active Scan Rules.

**Comment by DorghamX** [comment]
there is no location because as i mentioned this error occurs during the installation process so it's not installed yet 

![Screenshot 2024-05-12 172446](https://github.com/zaproxy/zaproxy/assets/74857675/18e48fc0-2e6b-4dd8-928b-086dab332323)

if i clicked "Cancel" the whole installation process will be canceled and if i clicked "yes" the error pops up again

**Comment by kingthorin** [comment]
Maybe your download is futzed. Delete the installer and re-DL.

**Comment by DorghamX** [comment]
no this also not working i deleted it and redownloaded it twice the "Windows (64) Installer 2.15.0" is the one that have the problem on the other hand the cross platform package works fine and same with the older version of it "Windows (64) Installer 2.14.0" i downloaded it again and installed it successfully

**Comment by kingthorin** [comment]
What Java do you have installed?
What OS?
Any AV?

**Comment by thc202** [comment]
Make sure you don't have any anti-virus or other program blocking the file copy. (The installer is working fine, it was tested before the release.)

**Comment by DorghamX** [comment]
yeah disabling the anti-virus made it work 
thanks
