### ISSUE TITLE
Getting High Alert ("SQL injection may be possible"), whie we are not using sql in the application.

### ISSUE THREAD

**Issue by jitendra-90** [zaproxy/zaproxy#8487]
### Describe the bug

Getting too many High Alert related to SQL injection, while we not using sql dababase in the application, we are using api with encrypted parameters, still getting this type of alert from zap tool active scan report.

### Steps to reproduce the behavior

1. Go to tree view section
2. right click on the site and go on the Attacks and click on Active Scan
3. select all the check boxes from the popup
4. start the Scan 

### Expected behavior

there should not be Sql-Injection and MongoDb related alert in the report, both are not used in the application

### Software versions

2.14.0

### Screenshots

![image](https://github.com/zaproxy/zaproxy/assets/163534165/8aa154aa-4522-46e1-8197-c09e38359d1b)

### Would you like to help fix this issue?

- [X] Yes

**Comment by thc202** [comment]
You should use 2.15 and provide the versions of the add-ons.

**Comment by psiinon** [comment]
Pro tip - use the technolgy option to turn off the SQL rules: https://www.zaproxy.org/blog/2023-11-20-technology-support/

In any case, theres no enough info in this issue for us to do anything.
As per https://www.zaproxy.org/faq/how-do-i-handle-a-false-positive/ : "Please report any false positives that you identify supplying as much information as you can, while obfuscating any sensitive information. New issues should just cover one scan rule and should include enough information for us to reproduce the problem."

**Comment by jitendra-90** [comment]
When I am trying to install 2.15 version then detecting malware while creating plugin files on the system

**Comment by psiinon** [comment]
Thats likely to be a problem with your malware detection software, not ZAP.
If you think it might be a problem with ZAP them please let us know all of the details it gives you.

**Comment by jitendra-90** [comment]
I am attaching the detail of detected malware 
![image](https://github.com/zaproxy/zaproxy/assets/163534165/2fd66d75-eaa8-463b-90a9-e8b7fdc791c4)

**Comment by psiinon** [comment]
It could be related to https://github.com/zaproxy/zaproxy/issues/8488
In any case, this is likely to be a problem with your virus scanner, not a ZAP issue.
