### ISSUE TITLE
The default view of opening fuzzer window, can not add locations

### ISSUE THREAD

**Issue by wallenZhao2046** [zaproxy/zaproxy#8492]
### Describe the bug

When open fuzzer window, the default view can not add locations, the add button in fuzzer location dialog is disabled. You have to click the combination to display Header and body button, then the add button in fuzzer location dialog will be enabled. For first-time users of Fuzzer, it can be confusing as to why the inability to set a location causes the Fuzzer to be unusable.

The default view, the add button is disabled
![image](https://github.com/zaproxy/zaproxy/assets/15209792/12509e3a-e63a-442f-8bae-ee53e969db1b)

Clicked to display header and body button, the add button is enabled
![image](https://github.com/zaproxy/zaproxy/assets/15209792/1061e684-c197-4234-b475-4258e32d04ad)

### Steps to reproduce the behavior

1. From the site list, select the HTTP request you want to fuzz test. Right-click and select Attack ⇒ "Send to Fuzzer".
2. In the fuzzer window, you will see this bug

### Expected behavior

expect the  add button in fuzzer location dialog is enabled. Or the default view is the combination to display Header and body.

### Software versions

Zap version 2.15.0

### Would you like to help fix this issue?

- [ ] Yes

**Comment by kingthorin** [comment]
I believe that's by design.

How would ZAP know where you want the payload added?

**Comment by kingthorin** [comment]
Please let us know if you feel something is outstanding here.
