### ISSUE TITLE
false positive of sql Injection

### ISSUE THREAD

**Issue by ziadtoa** [zaproxy/zaproxy#8503]
### Describe the bug

The app in giving:
https://nacc.gov.lb/en/commission-news-page/?csrf_token=edd354c1bd75595c3c7a7c333d815e7596bcc26dd6cac7d397ddf4e9dcdc0954&title=ZAP&year-select=2024
 
" | case randomblob(1000000) when not null then "" else "" end | "
![image](https://github.com/zaproxy/zaproxy/assets/157237679/5c25f6c3-5249-4c75-842a-2190e3f57c75)

as sql injection. I have tried to insert this link but my wordpress threw the call. I am using wordfence as a plugin.
your keeps showing me that there is an injection. How can I prove it is a false positive since when I try the injections detected by your app the wordpress sites throw them all.

### Steps to reproduce the behavior

![image](https://github.com/zaproxy/zaproxy/assets/157237679/723fd2c1-9456-42ae-8722-6aa2713c94b5)

### Expected behavior

Expected not to se this as sql injection since we tested this directly on the website and it doesn't accept the url

### Software versions

Woordpress with wordfence plugin

### Would you like to help fix this issue?

- [ ] Yes

**Comment by strayobject** [comment]
This is unlikely a false positive and it is not a zap bug. It points to the fact that login form is a possible gateway to timing attacks as the response time differs based on the query passed into it.

**Comment by psiinon** [comment]
The issue clearly states "SQL injection may be possible".
It does not say that SQL injection _IS_ possible.

I think we can close this in favour of https://github.com/zaproxy/zaproxy/issues/7341 - views?

**Comment by kingthorin** [comment]
Agreed

**Comment by thc202** [comment]
I'd close it based on the work being done in https://github.com/zaproxy/zaproxy/issues/8112#issuecomment-1819848796 just extracting it into other scan rule will not address the FP reported here.

In any case both issues are now referenced for those that want to follow up.
