### ISSUE TITLE
Provided browser was not found error in ZAP.

### ISSUE THREAD

**Issue by MassimoPyhton** [zaproxy/zaproxy#8505]
Hi guys! Downloaded ZAP OWASP but the Mozilla or other browser can't be opened for proxy interception. The error "Provided browser was not found" pop up. In the list of the Default User Agent there is no the last version of Mozilla or Chrome or whatever browser in it. So obviously ZAP does not see the browser at all. Any ideas?

**Comment by psiinon** [comment]
See https://www.zaproxy.org/faq/how-can-i-fix-browser-was-not-found/
And please do not ask questions like this as issues - the ZAP User Group is a much better forum for these: https://groups.google.com/group/zaproxy-users
