### ISSUE TITLE
UI search not highlighting correctly

### ISSUE THREAD

**Issue by deoktr** [zaproxy/zaproxy#8509]
### Describe the bug

When searching for `proxy` in the Network > Local Servers/Proxies tab, the text of the section containing the address and the port, the title is not rendered correctly and shows raw HTML.

### Steps to reproduce the behavior

1. Go to tools > options
2. Search for `proxy`
3. Go to Network > Local Servers/Proxies tab

### Expected behavior

A red styled text.

### Software versions

OWASP ZAP
Version: 2.12.0

Installed Add-ons: [[id=alertFilters, version=14.0.0],
[id=ascanrules, version=49.0.0], [id=automation,
version=0.19.0], [id=bruteforce, version=12.0.0],
[id=callhome, version=0.5.0], [id=commonlib,
version=1.11.0], [id=database, version=0.1.0], [id=diff,
version=12.0.0], [id=directorylistv1, version=5.0.0],
[id=domxss, version=14.0.0], [id=encoder, version=0.7.0],
[id=exim, version=0.3.0], [id=formhandler, version=6.1.0],
[id=fuzz, version=13.8.0], [id=gettingStarted,
version=14.0.0], [id=graaljs, version=0.3.0], [id=graphql,
version=0.11.0], [id=help, version=15.0.0], [id=hud,
version=0.15.0], [id=invoke, version=12.0.0], [id=network,
version=0.3.0], [id=oast, version=0.13.0], [id=onlineMenu,
version=10.0.0], [id=openapi, version=29.0.0],
[id=pscanrules, version=44.0.0], [id=quickstart,
version=35.0.0], [id=replacer, version=11.0.0], [id=reports,
version=0.16.0], [id=requester, version=7.0.0], [id=retest,
version=0.4.0], [id=retire, version=0.16.0], [id=reveal,
version=5.0.0], [id=scripts, version=33.0.0], [id=selenium,
version=15.11.0], [id=soap, version=15.0.0], [id=spider,
version=0.1.0], [id=spiderAjax, version=23.10.0], [id=tips,
version=10.0.0], [id=webdriverlinux, version=46.0.0],
[id=websocket, version=27.0.0], [id=zest, version=37.0.0]]

Operating System: Linux
Architecture: amd64
Java Version: Debian 11.0.20
System's Locale: en_GB
Display Locale: en_GB
Format Locale: en_GB
Default Charset: UTF-8
ZAP Home Directory: /home/htb-ac-1301733/.ZAP/
ZAP Installation Directory: /usr/share/zaproxy/./
Look and Feel: FlatLaf Dark (com.formdev.flatlaf.FlatDarkLaf)

### Screenshots

![image](https://github.com/zaproxy/zaproxy/assets/35725720/e1d15db8-eb20-4ea4-bd0e-67428ee04e40)

### Would you like to help fix this issue?

- [ ] Yes

**Comment by psiinon** [comment]
ZAP 2.12.0 is very old, and is no longer supported.
We only support the latest version of ZAP, which is currently 2.15.0.

**Comment by thc202** [comment]
This is a duplicate of #8111, addressed in 2.14.
