### ISSUE TITLE
Search in notes

### ISSUE THREAD

**Issue by SkypLabs** [zaproxy/zaproxy#8518]
### Is your feature request related to a problem? Please describe.

It is currently not possible to search in notes.

### Describe the solution you'd like

I would like to be able to search into the notes I have taken.

`Notes` should be added to the drop-down menu for the search scope, along with `URL`, `Tag`, `HTTP Fuzzer Results`, etc.

![Screenshot_20240614_120208](https://github.com/zaproxy/zaproxy/assets/9932586/b865d7d3-b2f6-4c0a-a8b8-9b3355ba6dd8)

### Describe alternatives you've considered

N/A

### Would you like to help fix this issue?

- [X] Yes

**Comment by kingthorin** [comment]
Here's the PR where I added the tag search support: https://github.com/zaproxy/zaproxy/issues/8422

**Comment by thc202** [comment]
Be good if it was explained what's the expected behaviour, e.g. do you want to see the notes or the messages that have a note with a given regex.

**Comment by SkypLabs** [comment]
> Here's the PR where I added the tag search support: #8422

Thanks! I should have time to work on it in a few days.

> Be good if it was explained what's the expected behaviour, e.g. do you want to see the notes or the messages that have a note with a given regex.

Good point. I actually didn't feel the need to give more details as the current behaviour seems good to me. When searching for a term (e.g. URL, tag), both the request and the match string are displayed.

**Comment by thc202** [comment]
Is the whole note going to be displayed or just the exact match (and the user will have to go see the note through the context menu)? The tags and matches are usually shorter than notes.

**Comment by SkypLabs** [comment]
> Is the whole note going to be displayed or just the exact match (and the user will have to go see the note through the context menu)? The tags and matches are usually shorter than notes.

I imagine displaying a fraction of the note, like a few words before and after the exact match. I'm not sure it's the best approach but I think I will experiment a bit and see how it goes.
