### ISSUE TITLE
add content-type support for application/taxii+json

### ISSUE THREAD

**Issue by br01805** [zaproxy/zaproxy#8522]
### Is your feature request related to a problem? Please describe.

Currently when running scans against TAXII servers we are receiving content-type unexpected error. I'm largely assuming this is due to ZAP not supporting content type application/taxii+json

### Describe the solution you'd like

If possible could you all add "application/taxii+json" to the content-type expected list

### Describe alternatives you've considered

There are no alternatives

### Would you like to help fix this issue?

- [ ] Yes

**Comment by kingthorin** [comment]
For my two cents this is as expected. The number of ZAP users scanning a TAXII or STIX service is VERY low (IMO).

The proper way to handle this not being applicable for you is:
- Using [Alert filters](https://www.zaproxy.org/docs/desktop/addons/alert-filters/).
- Using a [scan hook](https://www.zaproxy.org/docs/docker/scan-hooks/) (if you're using packaged scans).

**Comment by thc202** [comment]
We have talked in the past about making the check more lenient for JSON content-types.

**Comment by kingthorin** [comment]
Okay; I could look at doing that.
