### ISSUE TITLE
CSP: Wildcard Directive

### ISSUE THREAD

**Issue by njmulsqb** [zaproxy/zaproxy#8529]
### Describe the bug

I am getting this alert on CSP policy that doesn't include any wildcards.

### Steps to reproduce the behavior

Here's the CSP that is being detected to contain wildcards

```
default-src 'self'; script-src 'self' cdn.website.com; connect-src 'self' wss: staging.api.website.io test-website.auth0.com website-files-staging.s3.us-west-2.amazonaws.com website-files-staging.s3.amazonaws.com website-files-staging.s3-us-west-2.amazonaws.com; img-src 'self' website-merchant-logos.website.com website-counterparty-logos.website.com website-files-staging.s3.us-west-2.amazonaws.com website-files-staging.s3.amazonaws.com website-files-staging.s3-us-west-2.amazonaws.com data:; frame-src 'self' test-website.auth0.com cdn.website.com; style-src 'self' 'unsafe-inline' fonts.googleapis.com fonts.gstatic.com; font-src 'self' data: fonts.googleapis.com fonts.gstatic.com;

```

### Expected behavior

This policy should not be alerted to contain wildcard directives.

### Software versions

ZAP
Version: 2.15.0

Installed Add-ons: [[id=accessControl, version=10.0.0],
[id=alertFilters, version=21.0.0], [id=ascanrules,
version=66.0.0], [id=authhelper, version=0.13.0],
[id=automation, version=0.40.1], [id=bruteforce,
version=16.0.0], [id=callhome, version=0.12.0],
[id=commonlib, version=1.26.0], [id=custompayloads,
version=0.13.0], [id=database, version=0.4.0], [id=diff,
version=15.0.0], [id=directorylistv1, version=8.0.0],
[id=domxss, version=19.0.0], [id=encoder, version=1.5.0],
[id=exim, version=0.9.0], [id=formhandler, version=6.6.0],
[id=fuzz, version=13.13.0], [id=gettingStarted,
version=17.0.0], [id=graaljs, version=0.7.0], [id=graphql,
version=0.24.0], [id=help, version=18.0.0], [id=hud,
version=0.19.0], [id=invoke, version=15.0.0], [id=network,
version=0.16.0], [id=oast, version=0.18.0], [id=onlineMenu,
version=13.0.0], [id=openapi, version=41.0.0], [id=postman,
version=0.4.0], [id=pscanrules, version=58.0.0],
[id=quickstart, version=47.0.0], [id=replacer,
version=18.0.0], [id=reports, version=0.32.0],
[id=requester, version=7.6.0], [id=retest, version=0.9.0],
[id=retire, version=0.36.0], [id=reveal, version=8.0.0],
[id=scripts, version=45.4.0], [id=selenium,
version=15.25.0], [id=soap, version=23.0.0], [id=spider,
version=0.11.0], [id=spiderAjax, version=23.19.0], [id=tips,
version=13.0.0], [id=wappalyzer, version=21.38.0],
[id=webdrivermacos, version=91.0.0], [id=websocket,
version=31.0.0], [id=zest, version=45.0.0]]

Operating System: Mac OS X
Architecture: aarch64
CPU Cores: 8
Max Memory: 6 GB
Java Version: Eclipse Adoptium 11.0.23
System's Locale: en_PK
Display Locale: en_GB
Format Locale: en_PK
Default Charset: UTF-8
ZAP Home Directory: /Users/administrator/Library/Application Support/ZAP/
ZAP Installation Directory: /Applications/ZAP.app/Contents/Java/./
Look and Feel: Mac OS X (com.apple.laf.AquaLookAndFeel)

### Would you like to help fix this issue?

- [ ] Yes

**Comment by kingthorin** [comment]
What are the description and other info for the alert?

**Comment by njmulsqb** [comment]
Description: Content Security Policy (CSP) is an added layer of security that helps to detect and mitigate certain types of attacks. Including (but not limited to) Cross Site Scripting (XSS), and data injection attacks. These attacks are used for everything from data theft to site defacement or distribution of malware. CSP provides a set of standard HTTP headers that allow website owners to declare approved sources of content that browsers should be allowed to load on that page — covered types are JavaScript, CSS, HTML frames, fonts, images and embeddable objects such as Java applets, ActiveX, audio and video files.

The following directives either allow wildcard sources (or ancestors), are not defined, or are overly broadly defined: 
connect-src, frame-ancestors, form-action

The directive(s): frame-ancestors, form-action are among the directives that do not fallback to default-src, missing/excluding them is the same as allowing anything.

**Comment by njmulsqb** [comment]
For connect-src, it is saying that its over broadly defined. What's the definition for over-broadly?

**Comment by psiinon** [comment]
I'm guessing that because its missing `;` before the `wss:`

**Comment by kingthorin** [comment]
I can confirm it's the colon it doesn't like, that might be a bug in the library we depend on. I'll have to investigate further.

**Comment by psiinon** [comment]
but .. that "mistake" could be handled very differently by different browsers, so it may actually be a valid finding...

**Comment by kingthorin** [comment]
Sorry let me correct/clarify myself. The issue is `wss:` allows wss from any domain.

**Comment by psiinon** [comment]
So ZAP correctly identified a subtle bug which has significant implications 😁

**Comment by kingthorin** [comment]
That's my take.
