### ISSUE TITLE
Broken report while sharing to others through email 

### ISSUE THREAD

**Issue by rajeshrajt** [zaproxy/zaproxy#8530]
### Describe the bug

Once generated report shared to others through email 
But in there system it is not showing with the same style logo broken styles also broke

### Steps to reproduce the behavior

Generate the report 
Share that to other user 
Open the report in that system 

### Expected behavior

It should show the same style in all systems

### Software versions

Using windows 11 Os with chrome as a browser 

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment]
What report specifically? The HTML ones might have other files (CSS, JS) in a separate directory, you need to share everything.

**Comment by rajeshrajt** [comment]
How I share those normally if I want to share zap report to others how can
I proceed kindly do the needful

**Comment by thc202** [comment]
Just ensure you send all files created, it should work fine if all are there.

**Comment by rajeshrajt** [comment]
i have generated that in zap tool Report --> generate report section it is downloaded as html file so i am sharing that file only you mentioned need to share all files created ..please help me to resolve this issue i want to share the html report without css and js collapsed kindly let me know the steps to do

**Comment by thc202** [comment]
Choose one of the Traditional HTML reports which is a single file.
https://www.zaproxy.org/docs/desktop/addons/report-generation/templates/
