### ISSUE TITLE
After installing ZAP 2.15.0 on Debian 12, it is not possible to start by running “zap” or “zapproxy” or “owasp-zap”.

### ISSUE THREAD

**Issue by cqhtyi** [zaproxy/zaproxy#8537]
### Describe the bug

The following is the method to install ZAP 2.14.0 on Debian12:

```
echo 'deb http://download.opensuse.org/repositories/home:/cabelo/Debian_12/ /' | sudo tee /etc/apt/sources.list.d/home:cabelo.list
curl -fsSL https://download.opensuse.org/repositories/home:cabelo/Debian_12/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home_cabelo.gpg > /dev/null
apt update
apt install owasp-zap
```

After installation, run `owasp-zap` You can start ZAP.
But ZAP 2.15.0 becomes:

```
echo 'deb http://download.opensuse.org/repositories/home:/cabelo/Debian_12/ /' | sudo tee /etc/apt/sources.list.d/home:cabelo.list
curl -fsSL https://download.opensuse.org/repositories/home:cabelo/Debian_12/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home_cabelo.gpg > /dev/null
sudo apt update
sudo apt install zap
```
After installation, you must run /usr/share/zap/zap.sh to start ZAP.

Where is "symbolic link" go?
Why did you change the package name?

### Steps to reproduce the behavior

-bash: zap: command not found
-bash: zapproxy: command not found
-bash: owasp-zap: command not found

### Expected behavior

Create the correct link under /usr/bin/

### Software versions

:~# apt show zap
```
Package: zap
Version: 2.15.0-1
Priority: optional
Section: unknown
Maintainer: Alessandro de Oliviera Faria (A.K.A. CABELO) <cabelo@opensuse.org>
Installed-Size: 266 MB
Recommends: openjdk-8-jre
Download-Size: 213 MB
APT-Manual-Installed: yes
APT-Sources: http://download.opensuse.org/repositories/home:/cabelo/Debian_12  Packages
Description: Zed Attack Proxy
 The Zed Attack Proxy (ZAP) is an easy to use integrated penetration testing tool for finding vulnerabilities in web applications. It is designed to be used by people with a wide range of security experience and as such is ideal for developers and functional testers who are new to penetration testing. ZAP provides automated scanners as well as a set of tools that allow you to find security vulnerabilities manually.

```

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment]
ZAP is no longer part of OWASP that's the reason why it no longer uses "owasp". Did you try with `zaproxy`?

**Comment by cqhtyi** [comment]
Yes, I tried zaproxy, but the system said command not found

**Comment by cqhtyi** [comment]
Line 61 of "/usr/share/zap/debian/rules"
`#ln -s $(CURDIR)/debian/zap/usr/share/zap/zap.sh $(CURDIR)/debian/zap/usr/bin/zaproxy`
this line is commented.

**Comment by thc202** [comment]
I noticed.

**Comment by psiinon** [comment]
@cabelo any thoughts / suggestions?

**Comment by cabelo** [comment]
> @cabelo any thoughts / suggestions?

I will work on it this weekend.

**Comment by cabelo** [comment]
@cqhtyi 
Is it possible for you to help test whether the **zaproxy** command is working now?

**Comment by cqhtyi** [comment]
root@debian:~# apt install zap -y
```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Recommended packages:
  openjdk-8-jre
The following NEW packages will be installed:
  zap
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 213 MB of archives.
After this operation, 266 MB of additional disk space will be used.
Get:1 http://ftp.lysator.liu.se/pub/opensuse/repositories/home%3A/cabelo/Debian_12  zap 2.15.0-1 [213 MB]
Err:1 http://ftp.lysator.liu.se/pub/opensuse/repositories/home%3A/cabelo/Debian_12  zap 2.15.0-1
  File has unexpected size (212812172 != 212810392). Mirror sync in progress? [IP: 130.236.254.251 80]
  Hashes of expected file:
   - SHA256:eddbb8acaff984f33cbfa5340237423f8e767e27704f0e35fc49a70be639f181
   - SHA1:5e8394c53dc5c31261c40995435fe579f2e36ce3 [weak]
   - MD5Sum:d7b57c5745988a7993ea5f3dbad42f1e [weak]
   - Filesize:212810392 [weak]
E: Failed to fetch http://ftp.lysator.liu.se/pub/opensuse/repositories/home%3A/cabelo/Debian_12/amd64/zap_2.15.0-1_amd64.deb  File has unexpected size (212812172 != 212810392). Mirror sync in progress? [IP: 130.236.254.251 80]
   Hashes of expected file:
    - SHA256:eddbb8acaff984f33cbfa5340237423f8e767e27704f0e35fc49a70be639f181
    - SHA1:5e8394c53dc5c31261c40995435fe579f2e36ce3 [weak]
    - MD5Sum:d7b57c5745988a7993ea5f3dbad42f1e [weak]
    - Filesize:212810392 [weak]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

```

**Comment by cqhtyi** [comment]
I think I'll wait for the mirrors to sync.

**Comment by cabelo** [comment]
> I think I'll wait for the mirrors to sync.

try this command

echo 'deb http://download.opensuse.org/repositories/home:/cabelo/Debian_12/ /' | sudo tee /etc/apt/sources.list.d/home:cabelo.list
curl -fsSL https://download.opensuse.org/repositories/home:cabelo/Debian_12/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home_cabelo.gpg > /dev/null
sudo apt update
sudo apt install zap

**Comment by cqhtyi** [comment]
I have tried your command but the system automatically redirects to the mirror site and I don't know how to download from opensuse.
```
So I always get this error:
Get:1 http://ftp.lysator.liu.se/pub/opensuse/repositories/home%3A/cabelo/Debian_12  zap 2.15.0-1 [213 MB]
Err:1 http://ftp.lysator.liu.se/pub/opensuse/repositories/home%3A/cabelo/Debian_12  zap 2.15.0-1
  File has unexpected size (212812172 != 212810956). Mirror sync in progress? [IP: 130.236.254.251 80]
  Hashes of expected file:
   - SHA256:3c3e1f5b34f38ad0f1cd7bc25910bd2a150d0f3ff3ad175c373f1fcfec456cca
   - SHA1:e7ab07f14f9348c0b97bd3557dec739b91562948 [weak]
   - MD5Sum:e2968faea3a7a0f34b06a0c5c5f8df1f [weak]
   - Filesize:212810956 [weak]
E: Failed to fetch http://ftp.lysator.liu.se/pub/opensuse/repositories/home%3A/cabelo/Debian_12/amd64/zap_2.15.0-1_amd64.deb  File has unexpected size (212812172 != 212810956). Mirror sync in progress? [IP: 130.236.254.251 80]
   Hashes of expected file:
    - SHA256:3c3e1f5b34f38ad0f1cd7bc25910bd2a150d0f3ff3ad175c373f1fcfec456cca
    - SHA1:e7ab07f14f9348c0b97bd3557dec739b91562948 [weak]
    - MD5Sum:e2968faea3a7a0f34b06a0c5c5f8df1f [weak]
    - Filesize:212810956 [weak]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by cabelo** [comment]
> I have tried your command but the system automatically redirects to the mirror site and I don't know how to download from opensuse. So I always get this error:
> 
> ```
> Get:1 http://ftp.lysator.liu.se/pub/opensuse/repositories/home%3A/cabelo/Debian_12  zap 2.15.0-1 [213 MB]
> Err:1 http://ftp.lysator.liu.se/pub/opensuse/repositories/home%3A/cabelo/Debian_12  zap 2.15.0-1
>   File has unexpected size (212812172 != 212810956). Mirror sync in progress? [IP: 130.236.254.251 80]
>   Hashes of expected file:
>    - SHA256:3c3e1f5b34f38ad0f1cd7bc25910bd2a150d0f3ff3ad175c373f1fcfec456cca
>    - SHA1:e7ab07f14f9348c0b97bd3557dec739b91562948 [weak]
>    - MD5Sum:e2968faea3a7a0f34b06a0c5c5f8df1f [weak]
>    - Filesize:212810956 [weak]
> E: Failed to fetch http://ftp.lysator.liu.se/pub/opensuse/repositories/home%3A/cabelo/Debian_12/amd64/zap_2.15.0-1_amd64.deb  File has unexpected size (212812172 != 212810956). Mirror sync in progress? [IP: 130.236.254.251 80]
>    Hashes of expected file:
>     - SHA256:3c3e1f5b34f38ad0f1cd7bc25910bd2a150d0f3ff3ad175c373f1fcfec456cca
>     - SHA1:e7ab07f14f9348c0b97bd3557dec739b91562948 [weak]
>     - MD5Sum:e2968faea3a7a0f34b06a0c5c5f8df1f [weak]
>     - Filesize:212810956 [weak]
> E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
> ```
> 
> I think if you change the file name from 2.15.0-1 to 2.15.0-2 that would solve the problem?
> 
> update: I just tried using the mirror from ftp.gwdg.de and now the **zaproxy** command works fine

Thanks for the feedback, sorry @psiinon  and everyone for the mistake I made.

**Comment by thc202** [comment]
Thank you for the quick fix!

**Comment by psiinon** [comment]
@cabelo no problem - and thanks for the fix!
