### ISSUE TITLE
Use argparse in zap-api-scan.py instead of handmade checks

### ISSUE THREAD

**Issue by Nounoursdestavernes** [zaproxy/zaproxy#8550]
### Is your feature request related to a problem? Please describe.

Currently, zap-api-scan.py use handmade verifications to handle arguments. This is a low efficient solution and could be improved by the use of argparse module (https://docs.python.org/3/library/argparse.html)

### Describe the solution you'd like

Refactor the corresponding code using the appropriate library.

### Describe alternatives you've considered

None.

### Would you like to help fix this issue?

- [X] Yes

**Comment by thc202** [comment]
There was already a PR adding this #7213, but not sure worth the effort, the packaged scans will be superseded at some point.

**Comment by thc202** [comment]
Closing, since this is a task under #3566.
