### ISSUE TITLE
JS strings interpreted as Dangerous JS Function

### ISSUE THREAD

**Issue by fzx404** [zaproxy/zaproxy#8553]
### False Positive :
An HTTP response containing the cache-control directive `must-revalidate` will correctly trigger the `eval` regex and therefore be noticed by the 10110 Passive Scanner (Dangerous JS Function).

Requires Passive Scanner Beta so that "Dangerous JS Function" alerts are reported.

### Steps to reproduce the behavior

1. Perform an HTTP request to a webpage whose reply contains : `Cache-Control:  must-revalidate`.
2. Watch ZAP tagging this request as _Dangerous JS Function_ (Passive - 10110).
3. Open Request & Responses tab and see the highlighted part `eval` in `must-revalidate`, without having any other `eval` highlighted in the page content.
4. Look at the alerts tab, and find the evidence `eval` accordingly.

### Expected behavior

As this directive has nothing to do with eval, such an alert should not be raised.

### Software versions

ZAP 2.15.0 Desktop

### Additional context

Passive Scanner rules (beta) version 39.0.0

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment]
Did you check in the response body? The response header is not checked at all, unfortunately the highlight happens on the first match.

**Comment by psiinon** [comment]
Yeah, thats not right. Maybe we should check for a non alphabetic character on each side, and/or a bracket to the right ignoring whitespace?
The code is here: https://github.com/zaproxy/zap-extensions/blob/main/addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/JsFunctionScanRule.java

**Comment by fzx404** [comment]
> Did you check in the response body? The response header is not checked at all, unfortunately the highlight happens on the first match.

Ah well my bad then, I thought it would highlight every instances.
The js file in question does indeed have a "eval" in it, but it is part of a link to an external website, so no code execution anyway.

Thank you both for the responses though!

**Comment by psiinon** [comment]
@fzx404 can you supply the surrounding snippet, we might still be able to improve the regexes to avoid more FPs...

**Comment by fzx404** [comment]
Sure, here it is.
It is part of a var declaration containing in particular a quite long css code.
Since it does contain dozens and dozens of link unrelated to me, I will scrap it to a smaller version. 

<details>
  <summary>Snippet 1</summary>
  var V=hungarian:['A[href*="ad.eval.hu"]','A[href*="ad.netmedia.hu"]','A[href*="daserver.ultraweb.hu"]',"#cemp_doboz",".optimonk-iframe-container"],iDontCareAboutCookies:['.alert-info[data-block-track*="CookieNotice"]',".ModuleTemplateCookieIndicator",".o--cookies--container",".cookie-msg-info-container","#cookies-policy-sticky"]
</details>

And this one (I don't know if the regex is case sensitive)

<details>
  <summary>Snippet 2</summary>
function T(){var n=window,e=navigator;return y(["ApplePayError"in n,"CSSPrimitiveValue"in n,"Counter"in n,0===e.vendor.indexOf("Apple"),"getStorageUpdates"in e,"WebKitMediaKeys"in n])>=4}
</details>

**Comment by kingthorin** [comment]
I haven't tested yet. The first one makes sense we do test with word boundaries which the periods would qualify as. The second one I don't think is an issue because it's a substring so shouldn't match. Will try to test over the weekend.
