### ISSUE TITLE
Manage Add-ons table columns should all have names

### ISSUE THREAD

**Issue by jsoref** [zaproxy/zaproxy#8554]
0. If necessary, set up and start your Screen Reader (which will be very disappointed by blank column headers/menu items)

1. Install ZAP 2.15.0 (arm64, on macOS 14.5)
2. Open ZAP
3. (ignore the NPE that's fixed by https://github.com/zaproxy/zap-extensions/pull/5485 -- this may require a restart)
4. you'll probably get the update dialog, but if not, go to `Help`>`Check for Updates...`
5. click the widget above the scrollbar
6. See:
    <img width="801" alt="image" src="https://github.com/user-attachments/assets/30d36ed8-1689-4cc0-b538-3bceb4481efe">

    This is probably from https://github.com/zaproxy/zaproxy/blob/7c67c305ec58af971aa13132cc97093b18b5db3f/zap/src/main/java/org/zaproxy/zap/extension/autoupdate/InstalledAddOnsTableModel.java#L40-L46

7. click the marketplace tab
8. click the widget above the scrollbar
9. See:
    <img width="802" alt="image" src="https://github.com/user-attachments/assets/c4042f2f-ac79-4f32-8b66-e84202fff750">

    This is probably from https://github.com/zaproxy/zaproxy/blob/7c67c305ec58af971aa13132cc97093b18b5db3f/zap/src/main/java/org/zaproxy/zap/extension/autoupdate/UninstalledAddOnsTableModel.java#L36-L44

**Comment by jessemchung** [comment]
So, yeah I see this as well, just a quick confirmation, the goal is to remove the blank spaces right?

I am not going to work on this yet, I just want to confirm

**Comment by jsoref** [comment]
The blank entries should be filled with words.

**Comment by jessemchung** [comment]
@jsoref Right, makes sense.  What sort of text should be there though?  

Should the first be, "Alerts"?  Since it can be issues that prevent the add from working but also just show optional addons that could be used with it

And should the last column be "Select"?  It is the checkbox column to select specific add ons to uninstall or apply updates to.

**Comment by jsoref** [comment]
I'm on the fence between `Select` and `Selected` for the last column.

Can you give me examples of rows with content for that first column? I can't reason with what I have here.

**Comment by jessemchung** [comment]
Gotcha, might be a bit, there's one other issue I want to finish up first.

**Comment by jessemchung** [comment]
@jsoref Oh sorry, I just realized you had a much easier request than I thought.  Yeah I can do that more or less

This is what the columns look like.  I realized my other pull request was in zap extensions so I could actually fiddle around with this a bit.  Adding titles resulted in me having to adjust the width of the columns.

<img width="1792" alt="Screenshot 2024-09-15 at 10 55 47 PM" src="https://github.com/user-attachments/assets/35298ac2-cc9a-49cc-b0e8-00c2d7d09f4d">

**Comment by jsoref** [comment]
Offhand, I think `Note` is probably better. It doesn't sound  like they're always "Warnings" and I don't think "Info" fits either.

I'm leaning towards `Selected` over `Select` for the last column. That the button at the bottom of the second picture says `Install Selected` makes me more happy w/ my preference.

> [!NOTE]  
> While a column title might need more space to be fully rendered, I'm ok with it being truncated, even truncated to purely `...` -- on average a user won't care in the list view, and if they want to, they're free to resize it to learn the full title name. The only place where we really want the full title to be always visible is in the menu where the user can choose the columns.

**Comment by jessemchung** [comment]
Okay, makes sense.  I guess yeah, the column titles don't really do anything since they cannot be sorted by so having them be truncated makes sense.  In that case they can probably stay unmodified.

**Comment by jessemchung** [comment]
@jsoref hey, so this is what they look like now with the changes so far.  It looks good to me.

<img width="1792" alt="Screenshot 2024-09-17 at 7 02 59 PM" src="https://github.com/user-attachments/assets/e862eb99-5fb6-4197-b430-8a709eb3ca15">

<img width="1792" alt="Screenshot 2024-09-17 at 7 04 10 PM" src="https://github.com/user-attachments/assets/7759b2a5-20de-46f7-9b30-a9d4c8e441cc">

**Comment by jsoref** [comment]
Can you try changing the first column to `Note`?

**Comment by jessemchung** [comment]
@jsoref Sorry, that was my bad, I didn't apply the change correctly.  Here it is correctly



<img width="1792" alt="Screenshot 2024-09-17 at 7 18 03 PM" src="https://github.com/user-attachments/assets/1978345a-9b19-4744-8837-fd0dfe6af9e1">
<img width="1792" alt="Screenshot 2024-09-17 at 7 18 16 PM" src="https://github.com/user-attachments/assets/f499435f-d1ca-484f-91af-b43d6748b1ba">

**Comment by jsoref** [comment]
No worries. I think this looks good enough to me.
