### ISSUE TITLE
zaproxy wont' render. arch linux official unix install dwm

### ISSUE THREAD

**Issue by RomanDono89** [zaproxy/zaproxy#8577]
### Describe the bug

zaproxy won't render.
I first installed zaproxy via the blackarch repo, then i removed it, as it didn't work, and used the oficial installer for unix, wich had the same problem, system info: cpu= AMD ryzen 5 5600G, 16GB of ram, kernel = 6.9.3-hardened1-1-hardened, Window manager = dwm. If any more information about the system is needed i'll happily provide it.
information about zaproxy: $ zap.sh --help
Found Java version 22.0.2
Available memory: 15338 MB
Using JVM args: -Xmx3834m
The home directory is already in use. Ensure no other ZAP instances are running with
the same home directory: /home/reiman/.ZAP/
__

### Steps to reproduce the behavior

install arch linux with kernel 6.9.3-hardened1-1-hardened and dwm, add the blackarch repo,  install zaproxy, remove zaproxy, install zaproxy from the official unix installer.

### Expected behavior

being able to see the program

### Software versions

Found Java version 22.0.2
Available memory: 15338 MB
Using JVM args: -Xmx3834m
ZAP
Version: 2.15.0
Installed Add-ons: [[id=alertFilters, version=21.0.0], [id=ascanrules, version=67.0.0], [id=authhelper, version=0.13.0], [id=automation, version=0.40.1], [id=bruteforce, version=16.0.0], [id=callhome, version=0.12.0], [id=commonlib, version=1.26.0], [id=database, version=0.4.0], [id=diff, version=15.0.0], [id=directorylistv1, version=8.0.0], [id=domxss, version=19.0.0], [id=encoder, version=1.5.0], [id=exim, version=0.10.0], [id=formhandler, version=6.6.0], [id=fuzz, version=13.13.0], [id=gettingStarted, version=17.0.0], [id=graaljs, version=0.7.0], [id=graphql, version=0.24.0], [id=help, version=18.0.0], [id=hud, version=0.19.0], [id=invoke, version=15.0.0], [id=network, version=0.16.0], [id=oast, version=0.19.0], [id=onlineMenu, version=13.0.0], [id=openapi, version=42.0.0], [id=postman, version=0.4.0], [id=pscanrules, version=59.0.0], [id=quickstart, version=48.0.0], [id=replacer, version=18.0.0], [id=reports, version=0.32.0], [id=requester, version=7.7.0], [id=retest, version=0.9.0], [id=retire, version=0.37.0], [id=reveal, version=8.0.0], [id=scripts, version=45.5.0], [id=selenium, version=15.27.0], [id=soap, version=23.0.0], [id=spider, version=0.11.0], [id=spiderAjax, version=23.20.0], [id=tips, version=13.0.0], [id=webdriverlinux, version=96.0.0], [id=websocket, version=31.0.0], [id=zest, version=46.0.0]]
Operating System: Linux
Architecture: amd64
CPU Cores: 12
Max Memory: 3 GB
Java Version: Arch Linux 22.0.2
System's Locale: en_US
Display Locale: en_GB
Format Locale: en_GB
Default Charset: UTF-8
ZAP Home Directory: /home/reiman/.ZAP/
ZAP Installation Directory: /opt/zaproxy/./
Look and Feel: Metal (javax.swing.plaf.metal.MetalLookAndFeel)

### Screenshots

![zaproxy-BShlErsc](https://github.com/user-attachments/assets/87526a45-7612-4d08-92ab-38ce06b2b4da)

### Errors from the zap.log file

[zap.log](https://github.com/user-attachments/files/16378309/zap.log)

### Additional context

I first installed zaproxy via the blackarch repo, then i removed it, as it didn't work, and used the oficial installer for unix, wich had the same problem, system info: cpu= AMD ryzen 5 5600G, 16GB of ram, kernel = 6.9.3-hardened1-1-hardened, Window manager = dwm. If any more information about the system is needed i'll happily provide it.
information about zaproxy: $ zap.sh --help
Found Java version 22.0.2
Available memory: 15338 MB
Using JVM args: -Xmx3834m
The home directory is already in use. Ensure no other ZAP instances are running with
the same home directory: /home/reiman/.ZAP/

### Would you like to help fix this issue?

- [X] Yes

**Comment by thc202** [comment]
This one might help https://www.zaproxy.org/faq/why-am-i-getting-blank-zap-windows-on-linux/ try setting `_JAVA_AWT_WM_NONREPARENTING=1`

**Comment by RomanDono89** [comment]
i tried setting _JAVA_AWT_WM_NONREPARENTING=1 and running again the application, it didn't work, then i tried rebooting and setting the variable again, it did work. i am closing the issue, thank you for your help thc202
