### ISSUE TITLE
Why not use in AjaxSpider configurationBuilder.SetBasicAuth ()

### ISSUE THREAD

**Issue by 10zh** [zaproxy/zaproxy#8594]
### Is your feature request related to a problem? Please describe.

old:
![image](https://github.com/user-attachments/assets/9f708d42-de5d-4f5d-a358-aa6d7f1cef6d)

new:
![a4bd5695ff1332a3450cba2ae81727c](https://github.com/user-attachments/assets/fb110a73-12a0-4845-b2e2-b563c8c1a765)

### Describe the solution you'd like

AjaxSpider uses Basic/Digest authentication directly

### Describe alternatives you've considered

a

### Screenshots

a

### Additional context

a

### Would you like to help fix this issue?

- [ ] Yes

**Comment by psiinon** [comment]
@10zh can you explain what difference this would make?

**Comment by 10zh** [comment]
@psiinon When executing AjaxSpider automatically. After the URL is opened, the browser automatically passes Basic authentication. Then Crawljax can handle the current URL.

**Comment by psiinon** [comment]
@10zh does it not work currently with ZAP configured to handle Basic auth?

**Comment by 10zh** [comment]
Yes

**Comment by 10zh** [comment]
@psiinon yes

**Comment by kingthorin** [comment]
Okay so this can be closed?

**Comment by thc202** [comment]
Because ZAP needs to handle the authentication either way, why add another way of handling auth should be the question.
