### ISSUE TITLE
macOS amd64 installer for `v2.15.0` installs `v2.11.1`

### ISSUE THREAD

**Issue by flyinghermit** [zaproxy/zaproxy#8604]
macOS amd64 installer asset for `v2.15.0` downloaded from the [download page](https://www.zaproxy.org/download/) and the Github [release page](https://github.com/zaproxy/zaproxy/releases/tag/v2.15.0) installs `v2.11.1`

**Comment by psiinon** [comment]
@flyinghermit The download page links to the files on the 2.15.0 release page.
Which specific link do you think installs 2.11.1?

**Comment by kingthorin** [comment]
Please be much much more specific about what you've done and what you're experiencing.

The downloads and release both point to 2.15 resources.

**Comment by flyinghermit** [comment]
**Reproduction steps:**
1. Download the macOS amd64 installer for `v2.15.0`

The download link is https://github.com/zaproxy/zaproxy/releases/download/v2.15.0/ZAP_2.15.0.dmg


<img width="1482" alt="Screenshot 2024-08-24 at 2 25 48 PM" src="https://github.com/user-attachments/assets/cab474bc-be82-41bc-914d-345dee3a88d3">

3. Open the downloaded `ZAP_2.15.0.dmg` file and complete installation.
4. Open ZAP
The initialization dialog tells its `v2.11.1`.
<img width="408" alt="Screenshot 2024-08-24 at 2 32 55 PM" src="https://github.com/user-attachments/assets/04892787-4f41-49c5-8e80-e5bbc6cf4fa3">


ZAP detects it's `v2.11.1` and suggests to launch `v2.15.0`. But this just again installs `v2.11.1`
<img width="518" alt="Screenshot 2024-08-24 at 2 24 29 PM" src="https://github.com/user-attachments/assets/81387573-469c-4b1a-8a58-55807c2f311e">

**Comment by kingthorin** [comment]
The screenshot you provided is zap starting not installing. It seems you've got an old possibly broken install already.

Others on the team do have Mac's and can double check on Monday. But given how long 2.15 is out I highly doubt no-one would have mentioned this earlier if it'd been an actual issue.

**Comment by flyinghermit** [comment]
> 3. Open the downloaded ZAP_2.15.0.dmg file and complete installation.
> 4. Open ZAP
> The initialization dialog tells its v2.11.1.
>> The screenshot you provided is zap starting not installing. It seems you've got an old possibly broken install already.

Yup, my reply mentions that the screenshot is on the initialization step.

> But given how long 2.15 is out I highly doubt no-one would have mentioned this earlier if it'd been an actual issue.

Sure, I did try this couple times, removing ZAP and re-installing it again. So whatever it is, looks like an issue with the installer or the version that is bundled with the `.dmg` asset itself. Stable installers usually detect older installation and update/replace it with newer one. Here, it does detect older version on each start (should actually detect during installation), informs user about the newer version, provides a mechanism to update it, but still fails at it.

**Comment by thc202** [comment]
Open ZAP instead of OWASP ZAP (and uninstall the latter).

**Comment by kingthorin** [comment]
@flyinghermit sorted?
