### ISSUE TITLE
Make Timed-based Delays in ascanrules configurable for More Flexible Scanning

### ISSUE THREAD

**Issue by tenaz3** [zaproxy/zaproxy#8606]
### Is your feature request related to a problem? Please describe.

In the ZAP `ascanrules` module on  [repo](https://github.com/zaproxy/zap-extensions), timed-based scan rules use hardcoded(5s) delays, like in the CommandInjectionScanRule class. These fixed delays can't be changed easily, which can be a pain in different situations—especially on false positives.

### Describe the solution you'd like

It would be great if these delays were configurable. We could set up a system where the delay is controlled by an environment variable or a config file. That way, users can adjust the timing without having to dive into the code. A utility class could manage this delay setting so that all scan rules use the same timing logic.

### Describe alternatives you've considered

**Editing the Code Directly**: People can manually change the delay in the code, but that’s not practical, especially when updating to newer versions.
**Command-Line Options**: Another idea is using command-line arguments for setting the delay, but that might be more complicated and less consistent.

### Additional context

Making the delay configurable would give users more control and make ZAP scans more flexible and efficient, adapting better to different environments and needs: 
https://github.com/zaproxy/zap-extensions/blob/main/addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/CommandInjectionScanRule.java#L610

### Would you like to help fix this issue?

- [ ] Yes

**Comment by kingthorin** [comment]
It's already configurable via Rule Config options:
https://www.zaproxy.org/docs/desktop/ui/dialogs/options/ruleconfig/

Which is setable via the CLI:
https://www.zaproxy.org/docs/desktop/cmdline/
