### ISSUE TITLE
Form Based Authentication Error

### ISSUE THREAD

**Issue by Add2502** [zaproxy/zaproxy#8607]
The dropdown menus for the username and password parameters are empty, and I’m unable to type anything manually into the fields. May I know what is the exact issue on this and how to resolve this? Thank you. Your assistance is much appreciated. 
![Screenshot 2024-08-27 110018](https://github.com/user-attachments/assets/2089e229-7020-41b9-98a9-aaa7181344df)

**Comment by thc202** [comment]
You didn't set the Login Request POST Data, which is from where the parameters are read.
