### ISSUE TITLE
zap-api-scan.py Gitlab CI/CD support: A file based option has been specified but the directory '/zap/wrk' is not mounted

### ISSUE THREAD

**Issue by xl32** [zaproxy/zaproxy#8616]
### Is your feature request related to a problem? Please describe.

Consider the following Gitlab CI/CD job configuration:
```zap-check:
  stage: pre-sonarqube-check
  image:
    name: ghcr.io/zaproxy/zaproxy:stable
    entrypoint: ["zap-api-scan.py", "-t", "https://example.com/api/docs", "-f", "openapi", "-r", "zaproxy-htmlReport.html", "-r", "zaproxy-report.xml"]
  artifacts:
    paths:
      - zap/wrk/zaproxy-report.xml
      - zap/wrk/zaproxy-htmlReport.html
  ```
Currently, it fails with the error message "A file based option has been specified but the directory '/zap/wrk' is not mounted".

At the same time, Gitlab allows resulting files retrieval from the container itself, and does not support mounts at this syntax, unfortunately.

### Describe the solution you'd like

Add a new key for zap-api-scan.py:

--no-mount: Do not check if /zap/wrk dir is mounted and silently create it instead

### Describe alternatives you've considered

-

### Would you like to help fix this issue?

- [x] Yes

**Comment by psiinon** [comment]
There is a workaround for this - use the Automation Framework instead.
That is the recommended way forwards - we do not want to keep adding more command line options to the packaged scans.

**Comment by xl32** [comment]
@psiinon, looks like too complex (creating additional yaml, learning about AF, ...) for such a simple task: probably if I could suggest a pull request it can be reviewed? I checked the code of zap-api-scan.py and this looks as essential feature for me.

**Comment by psiinon** [comment]
Its not "just adding another parameter" for us, its maintaining these scripts over a long period of time.
The packaged scans have proved popular but difficult to use and maintain.
Everyone wants little things added to them.

We have decided to focus on the Automation Framework, we are (still) in the process of migrating them all to use the AF under the covers.
We will _not_ be adding any new parameters to any of them except in exceptional circumstances, and I dont think this is one of them.

I keep meaning to add an API scan equivalent to the community scripts.
Heres the one I was planning to add, but its not been revied yet:
```
---
# An API plan that will not do anything unless you add one or more suitable API definitions.
# You need to define at least one graphql, openapi, or soap endpoint, then you can delete the API jobs that don't have one.
env:
  contexts:
  - name: "Example"
    urls:
    - "${ZAP_TARGET}"
    includePaths: []
    excludePaths: []
  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true
  vars: {}
jobs:
- parameters:
    scanOnlyInScope: true
    enableTags: false
  rules: []
  name: "passiveScan-config"
  type: "passiveScan-config"

- type: "graphql"
  parameters:
    endpoint:           # String: the endpoint URL, default: null, no schema is imported
    schemaUrl:          # String: URL pointing to a GraphQL Schema, default: null, import using introspection on endpoint
    schemaFile:         # String: Local file path of a GraphQL Schema, default: null, import using schemaUrl

- type: "openapi"
  parameters:
    apiFile:            # String: Local file containing the OpenAPI definition, default: null, no definition will be imported
    apiUrl:             # String: URL containing the OpenAPI definition, default: null, no definition will be imported
    targetUrl:          # String: URL which overrides the target defined in the definition, default: null, the target will not be overridden

- type: soap
  parameters:
    wsdlFile:           # String: Local file path of the WSDL, default: null, no definition will be imported
    wsdlUrl:            # String: URL pointing to the WSDL, default: null, no definition will be imported

- parameters:
  policyDefinition:
    defaultStrength: "medium"
    defaultThreshold: "medium"
    rules: []
  name: "activeScan"
  type: "activeScan"
- parameters: {}
  name: "passiveScan-wait-pre-report"
  type: "passiveScan-wait"
- parameters:
    template: "modern"
    reportTitle: "ZAP Scanning Report"
    reportDescription: ""
  name: "report"
  type: "report"
```

**Comment by psiinon** [comment]
FYI this version has the scripts and latest API rules defined: https://github.com/zaproxy/community-scripts/pull/466
