### ISSUE TITLE
Having 401 error when running automated scan 

### ISSUE THREAD

**Issue by Add2502** [zaproxy/zaproxy#8618]
Having 401 error when running automated scan and when i did some reading it is an authentication error. Then i tried to accessing the web application via the Zaproxy's browser and login with my credential. However, it's failed even I already put in the correct credential. Why is this happened? Please help me. For your info, the web app is using SSO for login. is it because of SSO? or other issue?

![zaperror](https://github.com/user-attachments/assets/426c64f2-5f67-445d-8d90-8cfa4cd18e99)

**Comment by thc202** [comment]
Closing since this is for issues not usage questions, there's already a question in the user group too (which I assume is yours).
https://groups.google.com/g/zaproxy-users/c/MRwJFy-ItI0/m/NoRx0pOCAQAJ
