### ISSUE TITLE
Frequent False Positives: Hash Disclosure - Mac OSX salted SHA-1

### ISSUE THREAD

**Issue by rbliss** [zaproxy/zaproxy#8624]
### Describe the bug

Passing along a friendly report of a rule with frequent false positive.

We have seen quite a few instances of high threat level alerts being raised for `Hash Disclosure - Mac OSX salted SHA-1`. I've reviewed the findings, and have concluded that all are false positives. 

### Steps to reproduce the behavior

A selection of examples:

- `0048E3008E40001CE400F4780031EC001AA200192000F80E` found in the markup:

```
<embed id="example" name="widget" src="http://example.com/common/swf/widget.swf?wid=0048E3008E40001CE400F4780031EC001AA200192000F80E" width="200" height="280" type="application/x-shockwave-flash">
```

- `B222222222222222222222222222222222222222222222222` found in the content of an image/jpeg.

- `496F6965726E6174636F6E61674164636F756E74696E6721` found in the content of a PDF.

- `2833C52A1F55BA254A23A9237908EE49FB3655B5CC1414FE` found in a nonce param of an anchor link on a page:

```
<a href="https://www.example.com/?nonce=2833C52A1F55BA254A23A9237908EE49FB3655B5CC1414FE
```

Let me know if you would like more examples.

### Expected behavior

Up to the Zap team's judgement.  In an earlier report on this rule, Javascript file scanning was ignored: https://github.com/zaproxy/zaproxy/issues/6071

Overall, my impression is that Mac OS X has been updated to not store hashed passwords anywhere that's easily access-able or dump-able. 

Some possible options I've thought of:

- Remove the Mac OS X Hash pattern detection all together, as no longer relevant
- Reclassify the finding to low confidence
- Make stricter and not scan PDFs or Images
- Probabilistically screen out hashes that have zero or too few letters in them

### Software versions

Zap 2.15

### Would you like to help fix this issue?

- [X] Yes

**Comment by kingthorin** [comment]
> Up to the Zap team's judgement. In an earlier report on this rule, Javascript file scanning was ignored: https://github.com/zaproxy/zaproxy/issues/6071

It wasn't ignored it resulted in a fix/adjustment.

**Comment by rbliss** [comment]
My apologies on my wording. I meant it was fixed by not scanning the JS file for hashes. :)

**Comment by kingthorin** [comment]
>Please add version information from ZAPs menu Help > Support Info, or from the CLI using the -suppinfo switch.

It's important for us to have full version details.

Also if you could provide the response headers for these two examples that would really help:

> B222222222222222222222222222222222222222222222222 found in the content of an image/jpeg.
> 496F6965726E6174636F6E61674164636F756E74696E6721 found in the content of a PDF.

The first and fourth examples you provided seem perfectly fine to me. Sure you've identified that they're FPs, which is why users can set Alerts as False Positives. But they're also totally plausible as some sort of disclosure.

**Comment by kingthorin** [comment]
Given that the code already notes that SHA hashes are frequently used and not necessarily indicative of an issue I'd agree that we can reduce Risk and Confidence of the Mac OSX to match.

https://github.com/zaproxy/zap-extensions/blob/cafc98f6fcd405e92fd7c3465c0726261f630945/addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/HashDisclosureScanRule.java#L118C1-L140C79

**Comment by rbliss** [comment]
@kingthorin Thank you for the consideration. Here are the headers for those two findings:

The response headers for `B222222222222222222222222222222222222222222222222` (image):
```
HTTP/1.1 200 OK
Age: 0
Cache-Control: public, max-age=1800, must-revalidate
Content-Disposition: inline; filename="example.jpg"
Content-Length: 266279
Content-Security-Policy: script-src 'none'; frame-src 'none'; sandbox;
Content-Type: image/jpeg
Date: Sun, 01 Sep 2024 10:49:05 GMT
Last-Modified: Mon, 11 Dec 2023 19:39:09 GMT
Server: Vercel
Strict-Transport-Security: max-age=63072000
Vary: Accept
X-Vercel-Cache: MISS
X-Vercel-Id: cle1::bwkkf-1725187744664-96e09c071b22
X-Vercel-Imgsrc: 0ae80e931a7afb15c7c3cf42f0531140
```

The response headers for `496F6965726E6174636F6E61674164636F756E74696E6721` (PDF):
```
HTTP/1.1 200 OK
Date: Sun, 01 Sep 2024 16:21:49 GMT
Server: Apache
Last-Modified: Fri, 18 Sep 2020 09:36:17 GMT
Accept-Ranges: bytes
Content-Length: 10587866
Content-Type: application/pdf
```

And the completed ZAP version info:

```
ZAP
Version: 2.15.0
Installed Add-ons: [[id=alertFilters, version=21.0.0], [id=ascanrules, version=67.0.0], [id=authhelper, version=0.15.1], [id=automation, version=0.42.0], [id=bruteforce, version=16.0.0], [id=callhome, version=0.13.0], [id=commonlib, version=1.27.0], [id=database, version=0.5.0], [id=diff, version=15.0.0], [id=directorylistv1, version=8.0.0], [id=domxss, version=19.0.0], [id=encoder, version=1.5.0], [id=exim, version=0.10.0], [id=formhandler, version=6.6.0], [id=fuzz, version=13.13.0], [id=gettingStarted, version=17.0.0], [id=graaljs, version=0.7.0], [id=graphql, version=0.24.0], [id=help, version=18.0.0], [id=hud, version=0.19.0], [id=invoke, version=15.0.0], [id=network, version=0.17.0], [id=oast, version=0.19.0], [id=onlineMenu, version=13.0.0], [id=openapi, version=42.0.0], [id=postman, version=0.4.0], [id=pscan, version=0.0.1], [id=pscanrules, version=60.0.0], [id=quickstart, version=49.0.0], [id=replacer, version=18.0.0], [id=reports, version=0.33.0], [id=requester, version=7.7.0], [id=retest, version=0.10.0], [id=retire, version=0.39.0], [id=reveal, version=8.0.0], [id=scripts, version=45.6.0], [id=selenium, version=15.29.0], [id=soap, version=23.0.0], [id=spider, version=0.11.0], [id=spiderAjax, version=23.21.0], [id=tips, version=13.0.0], [id=webdriverlinux, version=101.0.0], [id=websocket, version=31.0.0], [id=zest, version=46.0.0]]
Operating System: Linux
Architecture: amd64
CPU Cores: 4
Max Memory: 1 GB
Java Version: Debian 11.0.24
System's Locale: en
Display Locale: en_GB
Format Locale: en_GB
Default Charset: UTF-8
ZAP Home Directory: /home/zap/.ZAP/
ZAP Installation Directory: /zap/./
Look and Feel: Metal (javax.swing.plaf.metal.MetalLookAndFeel)
```

I'll make sure to include complete ZAP info in any future reports.

**Comment by rbliss** [comment]
Another interesting false positive under `Hash Disclosure - Mac OSX salted SHA-1`.

Evidence: `115114971181011081199710810997114116112108117112`
It was in some JSON output into script block on the HTML page: `1390:"brand-115114971181011081199710810997114116112108117112",`

**Comment by kingthorin** [comment]
That makes sense, both JSON and HTML are included, and that does match the pattern.

For the earlier two examples I asked about, are you sure that `[id=pscanrules, version=60.0.0]` was in use at the time? Because it was only released two days ago and was updated to only target text type responses (so the image and application types should be excluded/skipped).

**Comment by rbliss** [comment]
You are right. I checked the version from the machine that ran the scan, however the machine was updated yesterday. The scan was performed for both the PDF detection and Image detection on 9/1, so it sounds like you beat me to the punch.

**Comment by rbliss** [comment]
Would it make sense to rename to "Salted SHA-1" with the lower threat and confidence? To your point, these are findings that match the pattern, but seem more generic than a hashed Mac OS X password sha floating around.

**Comment by kingthorin** [comment]
Yup, I'll keep this open and make that adjustment.
