### ISSUE TITLE
ZAP  alerts not showing

### ISSUE THREAD

**Issue by PalomaGomes2001** [zaproxy/zaproxy#8629]
Hello
I am trying to run a scan on a website made specifically to test and after the scan it is showing zero alerts. I am not able to figure out how to show any alerts because I know that the website should have many.
Please provide any assistance

**Comment by kingthorin** [comment]
Please don't ask questions as issues - the [ZAP User Group]( https://groups.google.com/group/zaproxy-users) is a much better place for questions.
