### ISSUE TITLE
en_GB locale support

### ISSUE THREAD

**Issue by omerf-hmcts** [zaproxy/zaproxy#8637]
### Is your feature request related to a problem? Please describe.

Our OS locale needs to be set to en_GB

```bash
LANG=en_GB.UTF-8
LANGUAGE=en_GB.UTF-8
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=en_GB.UTF-8

```

But when we run ZAP

```bash

 /opt/zap/zap.sh 
Available memory: 7937 MB
Setting jvm heap size: -Xmx512m
Can't find bundle for base name Messages, locale en_GB

```

### Describe the solution you'd like

en_GB locale to be added

### Describe alternatives you've considered

ZAP to include en_GB locale support

### Would you like to help fix this issue?

- [X] Yes

**Comment by psiinon** [comment]
UK English is supported out of the box., and is in fact the default.
This is almost certainly a local configuration and not a bug in ZAP - please ask on the ZAP User Group: 
https://groups.google.com/group/zaproxy-users

**Comment by omerfsen** [comment]
Hi,

I checked on ZAP_2.15.0
```bash
ls -lR ZAP_2.15.0/lang|grep GB
``` 

that there is no locale file for en_GB.. I don't think we supporrt it.. I already asked onn zaproxy-users group too

**Comment by psiinon** [comment]
Wi llreply on the user group
