### ISSUE TITLE
XSS Reflected - False Positives

### ISSUE THREAD

**Issue by FiveOFive** [zaproxy/zaproxy#8640]
### Describe the bug

I’ve seen two cases of Cross Site Scripting (Reflected) that seem to be false positives. Both occur when a web application uses the attack parameter in multiple places. For example in both a script tag and in the value of an input element.

### Case 1: text and input value

**Conditions:**

- The attack parameter is used in both plain text e.g. `<div>text</div>` and as the value of an input element
- The parameter is being sanitized differently for the text and input value

**Steps:**

1. ZAP submits the safe eye catcher payload: `0W45pz4p`. In the response, the payload is present in the input value and plain text.

```
<html>

<body>
  <h1>XSS test case with text and input value</h1>
  <form method="POST" action="/text-and-input-value">
    <input name="input" type="text" id="input" value="0W45pz4p">
    <button type="submit">POST</button>
  </form>
  <div>You submitted: 0W45pz4p</div>
</body>

</html>
```

2. Because the eye catcher payload was returned in the input value, ZAP will perform the tag attacks. ZAP submits a tag attack payload: `" onMouseOver="alert(1);`. In the response, the attack is escaped in the input value, but matches exactly in the plain text.

```
<html>

<body>
  <h1>XSS test case with text and input value</h1>
  <form method="POST" action="/text-and-input-value">
    <input name="input" type="text" id="input" value="&quot; onMouseOver=&quot;alert(1);">
    <button type="submit">POST</button>
  </form>
  <div>You submitted: " onMouseOver="alert(1);</div>
</body>

</html>
```

3. The rule alerts as true for XSS with the tag attack payload. However, I think it should be false, because while the attack payload is present in the page, it’s not in the correct location.

### Case 2: script tag and input value

**Conditions:**

- The attack parameter is being used in both a script tag and as the value of an input element.
- The parameter is being sanitized differently for the script tag and for the input value.
- The html and javascript are also using different quotes. e.g. html is double and javascript is single

**Steps:**

1. ZAP submits the safe eye catcher payload: `0W45pz4p`. In the response, the payload is present in a script tag and input value

```
<html>
<script>var='0W45pz4p'</script>

<body>
  <h1>XSS test case with script tag and input value</h1>
  <form method="POST" action="/script-and-input-value">
    <input name="input" type="text" id="input" value="0W45pz4p">
    <button type="submit">POST</button>
  </form>
  <div>You submitted: 0W45pz4p</div>
</body>

</html>
```

2. Because the eye catcher payload was returned in a script tag, ZAP will perform the script attacks. ZAP submits a script attack payload: `';alert(1);'`. In the response, the attack is escaped in the script tag, but matches exactly in the value of the input element

```
<html>
<script>var='%27%3Balert(1)%3B%27'</script>

<body>
  <h1>XSS test case with script tag and input value</h1>
  <form method="POST" action="/script-and-input-value">
    <input name="input" type="text" id="input" value="';alert(1);'">
    <button type="submit">POST</button>
  </form>
</body>

</html>
```

3. The rule alerts as true for XSS with the script attack payload. However, I think it should be false, because while the attack payload is present in the page, it’s not inside a script tag.

### Expected behavior

When a web application is using parameters in multiple places of the response, the cross site scripting scan rule should verify that the matched attack parameters are in a location that is vulnerable for to the attack.

### Software versions

ZAP
Version: 2.15.0

Installed Add-ons: [[id=alertFilters, version=21.0.0],
[id=ascanrules, version=66.0.0], [id=authhelper,
version=0.13.0], [id=automation, version=0.40.0],
[id=bruteforce, version=16.0.0], [id=callhome,
version=0.12.0], [id=commonlib, version=1.25.0],
[id=custompayloads, version=0.13.0], [id=database,
version=0.4.0], [id=diff, version=15.0.0],
[id=directorylistv1, version=8.0.0], [id=domxss,
version=19.0.0], [id=encoder, version=1.5.0], [id=exim,
version=0.9.0], [id=formhandler, version=6.6.0], [id=fuzz,
version=13.13.0], [id=gettingStarted, version=17.0.0],
[id=graaljs, version=0.7.0], [id=graphql, version=0.24.0],
[id=help, version=18.0.0], [id=hud, version=0.19.0],
[id=importurls, version=9.0.0], [id=invoke, version=15.0.0],
[id=network, version=0.16.0], [id=oast, version=0.18.0],
[id=onlineMenu, version=13.0.0], [id=openapi,
version=40.0.0], [id=postman, version=0.4.0],
[id=pscanrules, version=58.0.0], [id=quickstart,
version=47.0.0], [id=replacer, version=17.0.0], [id=reports,
version=0.32.0], [id=requester, version=7.6.0], [id=retest,
version=0.9.0], [id=retire, version=0.35.0], [id=reveal,
version=8.0.0], [id=saverawmessage, version=7.0.0],
[id=savexmlmessage, version=0.3.0], [id=scripts,
version=45.3.0], [id=selenium, version=15.23.0], [id=soap,
version=23.0.0], [id=spider, version=0.11.0],
[id=spiderAjax, version=23.19.0], [id=tips, version=13.0.0],
[id=webdrivermacos, version=82.0.0], [id=websocket,
version=31.0.0], [id=zest, version=45.0.0]]

Operating System: Mac OS X
Architecture: aarch64
CPU Cores: 8
Max Memory: 4 GB
Java Version: Eclipse Adoptium 11.0.23
System's Locale: en_US
Display Locale: en_GB
Format Locale: en_US
Default Charset: UTF-8
ZAP Installation Directory: /Applications/ZAP.app/Contents/Java/./
Look and Feel: FlatLaf Light (com.formdev.flatlaf.FlatLightLaf)

### Additional context

Report files:

[xss-report.json](https://github.com/user-attachments/files/17033768/xss-report.json)
[xss-report.pdf](https://github.com/user-attachments/files/17033770/xss-report.pdf)

Frequency:

I've seen this cases on 3 different client websites in the past month. However, the xss rule has found many more real findings, so overall it's been a great rule!

### Would you like to help fix this issue?

- [ ] Yes

**Comment by psiinon** [comment]
@FiveOFive thank you for such good information - this makes the task of fixing this rule so much easier!

**Comment by psiinon** [comment]
It looks like the XSS rules doesnt handle payloads being reflected in different contexts very well.
The fixes should be straightforward, but might be needed in quite a few paths ..

**Comment by psiinon** [comment]
After checking the code again it looks like setting the threshold to High should fix this!
I'm going to look at changing that to the default as I thin kthat makes much more sense.

**Comment by FiveOFive** [comment]
Thanks @psiinon! The change looks good to me. I pulled it and tested on a few sites.
