### ISSUE TITLE
The Provided browser was not found

### ISSUE THREAD

**Issue by jitendra-90** [zaproxy/zaproxy#8644]
### Describe the bug

I am not able to perform manual scanning due to getting this error as I attached screenshot, while I have already installed both browser which are showing in the dropdown
![image](https://github.com/user-attachments/assets/2166470b-1063-4330-aa8f-044de1327a0b)

### Steps to reproduce the behavior

I am not able to perform manual scanning due to getting this error as The Provided browser was not found

### Expected behavior

I am trying to perform manual scan then Browser should open with HUD option

### Software versions

ZAP 2.15.0

### Would you like to help fix this issue?

- [ ] Yes

**Comment by psiinon** [comment]
You clearly didnt look at the URL https://www.zaproxy.org/faq/no-browser/
