### ISSUE TITLE
Ajax Spider Repeatedly Visits the Same URLs Multiple Times

### ISSUE THREAD

**Issue by redkit75** [zaproxy/zaproxy#8645]
### Describe the bug

I'm experiencing an issue with the Ajax Spider component in ZAP where it repeatedly visits the same URLs multiple times during a scan. For example, the URL http://testphp.vulnweb.com/AJAX/artists.php is visited over 100 times in a single scan session.

### Steps to reproduce the behavior

Steps to Reproduce:

1. Set up ZAP and start the Ajax Spider on the URL http://testphp.vulnweb.com/.
2. Observe the repeated visits to the same URL, particularly for paths like AJAX/artists.php and others.
3. Even with configurations like setOptionClickElemsOnce(true) and limiting MaxCrawlDepth, the spider revisits these URLs excessively.

### Expected behavior

The Ajax Spider should only visit each unique URL once, unless the URL has dynamic parameters or specific conditions that would require multiple visits.

Actual Behavior:

The same URL is visited numerous times, leading to a longer scanning time and unnecessary load on the target application. This issue persists even when the following configurations are applied:

setOptionClickElemsOnce(true)
setOptionMaxCrawlDepth(5)
setOptionMaxCrawlStates(10)
setOptionRandomInputs(false)

### Software versions

2.15.0

### Would you like to help fix this issue?

- [ ] Yes

**Comment by psiinon** [comment]
This is not actually surprising.
The AJAX spider fills in forms and clicks on elements. If there are lots of links to one page (like AJAX/artists.php) then the AJAX spider will keep revisiting it.
Note that the crawling code is not actually in ZAP but in a 3rd party project: https://github.com/crawljax/crawljax
Finally, we plan to develop a new client based spider to replace the AJAX Spider: https://github.com/zaproxy/zaproxy/issues/8646
