### ISSUE TITLE
retire: Performance improvement

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#8659]
### Is your feature request related to a problem? Please describe.

The data `Repo` used by the retire add-on: https://github.com/zaproxy/zap-extensions/tree/main/addOns/retire is now parsed/initialized multiple times when the rule is instantiated or used by the passive scanner.

### Describe the solution you'd like:

It should override the `copy()` method of `PluginPassiveScanner` to use the same Repo across various copies.

### Describe alternatives you've considered:

We had initially considered simply making it static but the consensus seemed to be that overriding copy was a better choice.

### Screenshots:

n/a

### Additional context:

n/a

### Would you like to help fix this issue?

- [ ] Yes

**Comment by kingthorin** [comment]
Sure, done.

**Comment by dipeshsingh253** [comment]
Hi @kingthorin,

I followed the documentation, which was very clear and easy to follow. I was able to set up the development environment without any issues.

Could you clarify exactly where I need to override the `copy` method? Should this be done in an existing file, or would we need to create a new scanner specifically for the `Repo`?

Thanks!

**Comment by kingthorin** [comment]
That'd be here: https://github.com/zaproxy/zap-extensions/blob/main/addOns/retire/src/main/java/org/zaproxy/addon/retire/RetireScanRule.java

**Comment by Aman-SB** [comment]
Hi @kingthorin ,
I would like to work on this issue and help implement the solution. Could you please assign this to me?
Thanks!

**Comment by kingthorin** [comment]
It was just assigned yesterday ⬆️

**Comment by Aman-SB** [comment]
Thank you for letting me know! I see that it's already been assigned. If there's anything else I can help with or any other open issues, I'd be happy to contribute!

**Comment by kingthorin** [comment]
There should be a set tagged `goodfirstissue`. Really you can tackle anything in the issue tracker.

Of the goodfirstissuesnI might suggest looking at the one about implementing getExampleAlerts. There are tons of items to tackle there and also lots of linked PRs to refer to. It's also an issue that can have multiple assignees. If you do choose to work on it just pick one or two items and we'll mark them for you. (There's no need to try to do them all, small or single items are easier to review)

**Comment by Aman-SB** [comment]
Thank you for the suggestions! I'll take a closer look at the good_first_issue and review the linked PRs to get a better understanding. I'll start by picking one or two items to work on and will comment on the issue when I'm ready to proceed. I appreciate the guidance!

**Comment by dipeshsingh253** [comment]
Hi @kingthorin , so I went through the [file](https://github.com/zaproxy/zap-extensions/blob/main/addOns/retire/src/main/java/org/zaproxy/addon/retire/RetireScanRule.java) and started with implementation but I am not able to figure out what exactly we have to override in the copy method here. In original implementation it's just creating new instance of same type with same config every time. 

```java 
public PluginPassiveScanner copy()
            throws InstantiationException,
                    IllegalAccessException,
                    IllegalArgumentException,
                    InvocationTargetException,
                    NoSuchMethodException,
                    SecurityException {
        PluginPassiveScanner pps = this.getClass().getConstructor().newInstance();
        Configuration conf = this.getConfig();
        if (conf == null) {
            throw new IllegalArgumentException(
                    "Cannot copy "
                            + this.getClass().getCanonicalName()
                            + " : "
                            + this.getName()
                            + " as the configuration is null");
        }
        pps.setConfig(conf);
        return pps;
    }
```

**Comment by thc202** [comment]
The override should do the same (without reflection) and ensure the `repo` is reused by all copies.

**Comment by dipeshsingh253** [comment]
Hi @thc202 , @kingthorin , I have created a [PR](https://github.com/zaproxy/zap-extensions/pull/5788) for this issue. 

Please review it and give further feedback.

**Comment by dipeshsingh253** [comment]
Hi @thc202 , @kingthorin , I have created a [PR](https://github.com/zaproxy/zap-extensions/pull/5788) for this issue. 

Please review it and give further feedback.
