### ISSUE TITLE
Ability to grep patterns from responses coming in Fuzzer

### ISSUE THREAD

**Issue by njmulsqb** [zaproxy/zaproxy#8669]
### Is your feature request related to a problem? Please describe.

When fuzzing a web endpoint, there often comes a scenario where you're looking for a specific response pattern, for example if a web application is returning "No account found with that username." you'd be interested to fuzz and see a response where this message is not present to find a potentially correct username.

### Describe the solution you'd like:

Though it can be found by response body size but in cases where username is reflected in the body, different usernames causes different response body size hence detecting by size becomes difficult specially on large payload sets.

It will be good to have something related to burp's grep and match in ZAP, more: https://portswigger.net/burp/documentation/desktop/tools/intruder/uses/harvesting

### Describe alternatives you've considered:

N/A

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment]
This is a duplicate of #7482. The HTTP Fuzzer Processor scripts allow you to grep and more.

**Comment by kingthorin** [comment]
The readme in https://github.com/zaproxy/community-scripts/tree/main/httpfuzzerprocessor provides examples of how to do this `addCustomState` as the grepped value, etc.
