### ISSUE TITLE
TLS1.0 Support in ZAp

### ISSUE THREAD

**Issue by xyplex** [zaproxy/zaproxy#8672]
### Describe the bug:

I am using HackTheBox machien Beep and I need ZAp to be able to use TLS 1.0

 How do I switch on TLS 1.0 support in ZAP

![image](https://github.com/user-attachments/assets/0d9d4b3f-683c-4e05-9e7a-907947df760c)

### Steps to reproduce the behavior:

Start attack https url

### Expected behavior:

i expect ZAP to attack the machine

### Software versions:

ZAP
Version: 2.15.0

Installed Add-ons: [[id=alertFilters, version=22.0.0],
[id=ascanrules, version=68.0.0], [id=authhelper,
version=0.15.1], [id=automation, version=0.43.0],
[id=bruteforce, version=16.0.0], [id=callhome,
version=0.13.0], [id=commonlib, version=1.28.0],
[id=custompayloads, version=0.13.0], [id=database,
version=0.6.0], [id=diff, version=16.0.0],
[id=directorylistv1, version=8.0.0], [id=domxss,
version=19.0.0], [id=encoder, version=1.5.0], [id=exim,
version=0.12.0], [id=formhandler, version=6.6.0], [id=fuzz,
version=13.14.0], [id=gettingStarted, version=18.0.0],
[id=graaljs, version=0.8.0], [id=graphql, version=0.25.0],
[id=help, version=18.0.0], [id=hud, version=0.19.0],
[id=invoke, version=15.0.0], [id=jsonview, version=3.0.0],
[id=network, version=0.18.0], [id=oast, version=0.20.0],
[id=onlineMenu, version=13.0.0], [id=openapi,
version=43.0.0], [id=postman, version=0.4.0], [id=pscan,
version=0.0.1], [id=pscanrules, version=61.0.0],
[id=quickstart, version=50.0.0], [id=replacer,
version=19.0.0], [id=reports, version=0.34.0],
[id=requester, version=7.7.0], [id=retest, version=0.10.0],
[id=retire, version=0.41.0], [id=reveal, version=8.0.0],
[id=scripts, version=45.7.0], [id=selenium,
version=15.30.0], [id=soap, version=23.0.0], [id=spider,
version=0.12.0], [id=spiderAjax, version=23.21.0], [id=tips,
version=13.0.0], [id=webdriverlinux, version=108.0.0],
[id=websocket, version=31.0.0], [id=zest, version=47.0.0]]

Operating System: Linux
Architecture: amd64
CPU Cores: 24
Max Memory: 3 GB
Java Version: Debian 23
System's Locale: en
Display Locale: en_GB
Format Locale: en
Default Charset: UTF-8
ZAP Home Directory: /home/kali/.ZAP/
ZAP Installation Directory: /usr/share/zaproxy/./
Look and Feel: FlatLaf Light (com.formdev.flatlaf.FlatLightLaf)

### Would you like to help fix this issue?

- [X] Yes

**Comment by thc202** [comment]
Do the inverse of https://www.java.com/en/configure_crypto.html#DisableTLS it's a JRE config not ZAP one.
