### ISSUE TITLE
Update docs to mention that AF jobs' order matter

### ISSUE THREAD

**Issue by vasylmalanka** [zaproxy/zaproxy#8675]
### Describe the bug:

An alert filter with a new risk level is shown in the command output but seems to be ignored in the report

### Steps to reproduce the behavior:

1. Save configuration:
```
env:                                  
  contexts:
    - name: "Site Production"
      urls:
        - "https://site.com/"
    - name: "Site Staging"
      urls:
        - "https://staging.site.com/"
  parameters:
    failOnError: true
    failOnWarning: true
    progressToStdout: true
jobs:
  - type: spiderAjax
    parameters:
      maxDuration: 1
      context: "Site Production"
  - type: spiderAjax
    parameters:
      maxDuration: 1
      context: "Site Staging"
  - type: report
    risks:  
      - high
      - medium
      - low
      - info
  - type: alertFilter
    alertFilters:
      - ruleId: 10038
        newRisk: "Info"
```
2. Run the command using the configuration:
` docker run --rm -v $(pwd):/zap/wrk/:rw -t ghcr.io/zaproxy/zaproxy:stable zap.sh -cmd -autorun /zap/wrk/config.yaml`
3. Check the report

### Expected behavior:

The "Content Security Policy (CSP) Header Not Set" alert type has Risk: "Info"

### Software versions:

2.15.0

### Screenshots:

![Screenshot 2024-10-16 134846](https://github.com/user-attachments/assets/d7aefcb1-2aef-4d02-a6c7-84b40564433b)

### Additional context:

Console output:
```
docker run --rm -v $(pwd):/zap/wrk/:rw -t ghcr.io/zaproxy/zaproxy:stable zap.sh -cmd -autorun /zap/wrk/config.yaml
Found Java version 11.0.24
Available memory: 15856 MB
Using JVM args: -Xmx3964m
444 [main] INFO  org.parosproxy.paros.Constant - Copying default configuration to /home/zap/.ZAP/config.xml
524 [main] INFO  org.parosproxy.paros.Constant - Creating directory /home/zap/.ZAP/session
525 [main] INFO  org.parosproxy.paros.Constant - Creating directory /home/zap/.ZAP/dirbuster
525 [main] INFO  org.parosproxy.paros.Constant - Creating directory /home/zap/.ZAP/fuzzers
525 [main] INFO  org.parosproxy.paros.Constant - Creating directory /home/zap/.ZAP/plugin
Oct 16, 2024 11:29:47 AM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
Job spiderAjax set maxDuration = 1
Job spiderAjax set context = Site Production
Job spiderAjax set maxDuration = 1
Job spiderAjax set context = Site Staging
Job alertFilter set ruleId = 10038
Job alertFilter set newRisk = Info
Job spiderAjax started
Job spiderAjax terminated
Job spiderAjax found 3,581 URLs
Job spiderAjax finished, time taken: 00:01:05
Job spiderAjax started
Job spiderAjax terminated
Job spiderAjax found 2,589 URLs
Job spiderAjax finished, time taken: 00:01:05
Job report started
Job report generated report /zap/wrk/2024-10-16-ZAP-Report-site.com.html
Job report finished, time taken: 00:00:06
Job alertFilter started
Job: alertFilter Added global filter for alertId: 10038 new risk: Info
Job alertFilter finished, time taken: 00:00:00
Automation plan succeeded!
```

### Would you like to help fix this issue?

- [ ] Yes

**Comment by kingthorin** [comment]
You're creating the alert filter after all other work, you should in fact define the filter before spidering.

**Comment by vasylmalanka** [comment]
> You're creating the alert filter after all other work, you should in fact define the filter before spidering.

Oh, I expected the configuration to be processed regardless of the order of the jobs. Is it mentioned in the documentation?

**Comment by psiinon** [comment]
The order of the jobs is absolutely key. I dont think we mention that in the docs because I thought that would be "obvious" 😁 My bad...

**Comment by vasylmalanka** [comment]
> The order of the jobs is absolutely key. I dont think we mention that in the docs because I thought that would be "obvious" 😁 My bad...

We could have different experience based on with what tools we worked in past. I got used to the idea that the rules are processed regarding their type not order. But processing them by order does also make sense. It just should be mentioned in the documentation.

**Comment by thc202** [comment]
It's also probably better to add the [`passiveScan-wait`](https://www.zaproxy.org/docs/desktop/addons/passive-scanner/job-pscanwait/) job before generating the report, you might end up missing alerts.

**Comment by psiinon** [comment]
> > The order of the jobs is absolutely key. I dont think we mention that in the docs because I thought that would be "obvious" 😁 My bad...
> 
> We could have different experience based on with what tools we worked in past. I got used to the idea that the rules are processed regarding their type not order. But processing them by order does also make sense. It just should be mentioned in the documentation.

I completely agreee 😁
