### ISSUE TITLE
HTTP/2 Request Support in ZAP Proxy

### ISSUE THREAD

**Issue by redkit75** [zaproxy/zaproxy#8697]
### Describe the bug:

Hello,

I'm experiencing an issue where OWASP ZAP can't send HTTP/2 requests. When I attempt to send requests using HTTP/2, they fail(502). However, when the requests are sent as HTTP/1.0 or HTTP/1.1, they work as expected.

**Requester**
```
GET https://www.google.com HTTP/2
Host: www.google.com
Pragma: no-cache
Cache-Control: no-cache
```

Error: IO error in sending request: class org.apache.hc.core5.http2.H2StreamResetException: Stream reset (1).

ZAP Version: 2.15.0
OS: Linux
Other Tools: I have verified that this issue doesn't occur in Burp Suite, which can send HTTP/2 requests successfully.

### Steps to reproduce the behavior:

1. Requester
2. Attempt to send a simple HTTP/2 request through ZAP.
3. Notice that the request fails, whereas the same request sent as HTTP/1.1 works without issue.

### Expected behavior:

ZAP should support HTTP/2 requests in addition to HTTP/1.0 and HTTP/1.1 to allow broader testing coverage for modern applications, many of which now rely on HTTP/2 and HTTP/3.

### Software versions:

2.15.0

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment]
Lower case the header names (there's a button that does that).

**Comment by redkit75** [comment]
It gives the same error again.
