### ISSUE TITLE
Vulnerable JS Library (Powered by Retire.js) - CWE-829

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#8732]
10003	Vulnerable JS Library (Powered by Retire.js) (RetireScanRule)	Passive	release

**Comment by kingthorin** [comment]
https://cwe.mitre.org/data/definitions/1395.html
CWE-1395: Dependency on Vulnerable Third-Party Component

**Comment by thc202** [comment]
This rule was not using CWE-200.

**Comment by kingthorin** [comment]
Yup, your right. 

But "CWE-829: Inclusion of Functionality from Untrusted Control Sphere" was not an accurate choice. There's no assessment or establishment of "Trust".

Whether the control sphere is trusted or not it's more likely: "CWE-1395: Dependency on Vulnerable Third-Party Component "
