### ISSUE TITLE
OpenAPI Scan - Bad request to API endpoint [/JSON/openapi/view/results/] - ApiException: BAD_VIEW (results)

### ISSUE THREAD

**Issue by revotasks** [zaproxy/zaproxy#8736]
### Describe the bug:

My scan was running, and I was receving the first requests until the first issue raised, I got this error in my DOCKER console:

"2024-11-21 22:46:15 223693 [ZAP-IO-Server-1-1] WARN org.zaproxy.zap.extension.api.API - Bad request to API endpoint [/JSON/openapi/view/results/] from [172.17.0.1]: 2024-11-21 22:46:15 org.zaproxy.zap.extension.api.ApiException: BAD_VIEW (results) [...]"

If I'm not mistaken, as soon as the first problem is raised, zap tries to add it to “/JSON/openapi/view/results” (its own endpoint) but can't find it, so the code stops by itself.

### Steps to reproduce the behavior:

Launch the zap api container:

ZAP_DOCKER_IMAGE="zaproxy/zap-stable"
ZAP_HOST="0.0.0.0"

docker run -u zap -d --name zap-container \
  -p 8080:8080 -p 8090:8090 \
  $ZAP_DOCKER_IMAGE zap.sh -daemon \
  -host $ZAP_HOST -port 8080 \
  -config api.addrs.addr.name=.* \
  -config api.addrs.addr.regex=true \
  -config api.key=$ZAP_API_KEY

Launch the script:

BASE_ZAP_URL="http://localhost:8080/JSON"
OPENAPI_URL="${BASE_ZAP_URL}/openapi/action/importFile/" 
OPENAPI_FILE_PATH="openapi.json"

OPENAPI_SCAN_RESPONSE=$(curl "${OPENAPI_URL}?apikey=${ZAP_API_KEY}&target=${TARGET_URL}&file=${OPENAPI_FILE_PATH}")

You can also simply try this :
curl http://localhost:8080/JSON/openapi/view/results?apikey=${ZAP_API_KEY} Res: {"code":"bad_view","message":"Bad View"}
curl -I http://localhost:8080/JSON/openapi/view/results?apikey=${ZAP_API_KEY}

ZAP send a request to its API but it didn't exist.

### Expected behavior:

ZAP endpoint /JSON/openapi/view/results/ should exist on "zaproxy/zap-stable" to save each result

### Software versions:

current latest version of zaproxy/zap-stable (2.15.0)

### Would you like to help fix this issue?

- [ ] Yes

**Comment by psiinon** [comment]
You are getting an error because there is no such endpoint.
The endpoints this add-on supports are listed on https://www.zaproxy.org/docs/desktop/addons/openapi-support/#api
