### ISSUE TITLE
OWASP ZAP in docker: "ERROR HTTPConnectionPool(host='localhost', port=43067): Max retries exceeded with url" error during zap-full-scan.py

### ISSUE THREAD

**Issue by YuriiHapon** [zaproxy/zaproxy#8738]
Firstly, i setted up virtual machine on my PC. 
It was Ubuntu 24.04, 4 RAM, 2 CPU. During OWASP ZAP test i started scan in next command 
`docker run -m 3.7g -v ${PWD}:/zap/wrk/:rw zaproxy/zap-stable zap-full-scan.py -t https://app.myapp.com -r app-full-scan.html -d` 
Scan was successfully finished

After that, i bought VPS and setted up it as my VM. Ubuntu 24.04, 4 RAM, 2 CPU. But, after running same command as on VM, during 25% of scanning i have next error.

[Link for log file](https://drive.google.com/file/d/1BXt7C0bkvPYvt1fDpe5iNhFzfxgz0St1/view?usp=drive_link)

I had same issue on VM several times, but for some reason this error disappeared on VM. But on VPS i still have this issue and have no idea how to fix it?

The first thing that came to mind was a lack of RAM. But why i can provide successfully scan on VM with same RAM?

**Comment by psiinon** [comment]
Please ask questions like this on the ZAP User Group: https://groups.google.com/group/zaproxy-users
Oh, and ZAP has not been an OWASP project for over a year 😁
