### ISSUE TITLE
Missing active scan rule ID 0 in Automation Framework plan

### ISSUE THREAD

**Issue by Dipen-Saka** [zaproxy/zaproxy#8746]
### Describe the bug:

When I customised my Automation Framework Plan , I added few Active Scan rules which were available in zap . One of which is "Directory Browsing" with Alert Id / Id = 0. 
So when we save that Plan as a .yaml file , maybe it considers it as NULL instead of "0" and ommits to "id: 0" in the .yaml file.
Resulting in error: "error : YAML file failed to load: Cannot invoke "java.lang.Integer.intValue()" because "id" is null" 
Whenever we try to import this .yaml file again for the Automation Framework

### Steps to reproduce the behavior:

1. Create an Automation Framework Plan
2. add active scan rule : "Directory Browsing"
3. Save the plan. It gets saved as .yaml file
4. Try to export it in another Session
5. we get the error : "error : YAML file failed to load: Cannot invoke "java.lang.Integer.intValue()" because "id" is null"

### Expected behavior:

ZAP should import the .yaml file without any issues as we have exported it from ZAP itself.
But the issue with id = 0 throws error

### Software versions:

ZAP 2.15.0

### Screenshots:

Created an Automation Plan: 
and added the active scan rule "Directory Browsing" with Id = "0" :
![Image](https://github.com/user-attachments/assets/4e6db8b2-dcf8-42ea-8237-a2f347bc7828)

Saved the Plan with name "zap-bug.yaml" :
![Image](https://github.com/user-attachments/assets/de43c8fe-3c94-4e6b-9fd3-996fffaca532)

Opened the zap-bug.yaml file.
We can see the rule added has "id" missing .:
![Image](https://github.com/user-attachments/assets/9936bfcd-5884-421a-afd2-fe4fe310021e)

Importing the same yaml file gives us error:
![Image](https://github.com/user-attachments/assets/19bed8c0-da5c-47ad-89bc-b1c4adf0dab6)

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment]
This is because of the default values being omitted.

**Comment by Dipen-Saka** [comment]
Yes if we manually add id=0 in the .yaml file then it works perfectly fine . 
I initially thought maybe while saving it into .yaml format its omitting the value 0 as null .

**Comment by thc202** [comment]
Doesn't `ALWAYS` address it?

**Comment by kingthorin** [comment]
If we don't care about negative values. Which I guess are handled elsewhere. So yes that'd be fine. Will fire in a PR

**Comment by psiinon** [comment]
We dont use negative values now, and I dont think we should in the future either.

**Comment by kingthorin** [comment]
That was kinda my point 😉
