### ISSUE TITLE
Why are all the current reports passed when the problems in the previous baseline scan report have not been fixed?

### ISSUE THREAD

**Issue by tangzhiqiangh** [zaproxy/zaproxy#8776]
site has always had these issues, but we haven't fixed them yet. Why are they suddenly showing as passing? I scanned multiple different sites and found no issues. All passed.

`docker run -v /home/ubuntu/zap-report:/zap/wrk/:rw -t ghcr.io/zaproxy/zaproxy:stable zap-baseline.py     -t  https://www.example.com     -g /zap/wrk/gen_$(date +'%Y%m%d_%H%M%S').conf     -r /zap/wrk/ZAP-baseline-Report_Test_$(date +'%Y%m%d_%H%M').html > /home/ubuntu/zap-report/zap_output_BASELINE_Test_$(date +'%Y%m%d_%H%M%S').log`

![Image](https://github.com/user-attachments/assets/369cf700-7290-49c9-86e8-0678263cdf4d)

![Image](https://github.com/user-attachments/assets/58d4d65c-6c94-4547-bec8-2cf59fb79a78)

**Comment by kingthorin** [comment]
Is it also running super quick?

Looks like you're just generating the configuration file `-g`.

**Comment by psiinon** [comment]
Please do not ask questions as issues - ask them on the ZAP User Group: https://groups.google.com/group/zaproxy-users
